### ISSUE TITLE
Tutorial about Pagespeed  testing for AMP pages/site

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1001]
Need an tutorial to explain users about the AMP speed testing they do often on Pagespeed tool.

**Comment by udiudiudiudi** [comment]
hello, is there an active thread about google page insights, currently ampforwp stands in between 80-90, and it would be best to go above 90

**Comment by ahmedkaludi** [comment]
This is an old thread

**Comment by udiudiudiudi** [comment]
whats the updated one regarding google page insights?
