### ISSUE TITLE
Static Caching with Auto Minification System for AMP 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1002]
We can cache the AMP pages as static html pages in the wp-content/amp-cache/ folder which then will be served as minified and gzip'ed to the user.

The cache will be flushed when a user publishes or updates a new post or a user actually flushes the cache from an option in our backend.

This can be a huge performance upgrade for all the AMP users.

I would be interested in hearing the thoughts of the community.

Regards,
Ahmed

**Comment by MARQAS** [comment]
Also, it would be better if we can add the option to clear/update the Google cache as well. 

Some users want this feature as it is a little bit difficult or not an easy thing to understand. 

So we can make this an option to make it easy for our users

**Comment by ahmedkaludi** [comment]
We already have this. No need to have a ticket for this.
