### ISSUE TITLE
Check the sanitization of images

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1008]
Some users are reporting that images are getting distorted. 
The reason might be they are not giving height and width. 

ref: https://wordpress.org/support/topic/images-are-distorted-2/

**Comment by MARQAS** [comment]
http://wetraveltheworld.de/reisetipps-barcelona-sehenswuerdigkeiten/amp/

**Comment by ahmedkaludi** [comment]
You need to test this with the user's site. We don't know how is he adding those images. I doubt it's with some page builder? I'm closing this for now.
