### ISSUE TITLE
Twitter Embed is not working

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1010]
When we add the twitter URL in the editor, it works on non-amp and amp version but when we add the twitter embed code it's not working on amp pages/posts.

We need to test and resolve it.

Ref: https://secure.helpscout.net/conversation/400576043/14370/?folderId=1060551

**Comment by MARQAS** [comment]
Replaced the embed with URL which then gets sanitized into amp-twitter

**Comment by ahmedkaludi** [comment]
checked and closed.
