### ISSUE TITLE
JS error with tinymce-widget-pointer.min.js

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1012]
ref: https://wordpress.org/support/topic/js-error-with-tinymce-widget-pointer-min-js/

**Comment by MohammedKaludi** [comment]
Working on my system, waiting for the users reply on wp forum

Please check this screenshot: http://take.ms/cngWQ

**Comment by pra85** [comment]
I am facing a similar issue with plugin version - 0.9.58.1 on WP 4.8.1 . Can't create or edit widgets due to it. Only after installing the Black Studio TinyMCE plugin ( https://wordpress.org/plugins/black-studio-tinymce-widget/ ) does it work

**Comment by ahmedkaludi** [comment]
@pra85 It should work with the Black Studio TinyMCE plugin as well as long as you have the latest versions of both.
