### ISSUE TITLE
Radio button not working for Show View more Button"

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1018]

**Comment by ahmedkaludi** [comment]
@MohammedKaludi  Can you give some more data on this please?

**Comment by MohammedKaludi** [comment]
@ahmedkaludi Explained to mayank about the issue and he fixed it.

**Comment by MohammedKaludi** [comment]
Working smoothly now. Closing the ticket.
