### ISSUE TITLE
Version 0.9.56 Breaks my page

### ISSUE THREAD

**Issue by MrViSiOn** [ahmedkaludi/accelerated-mobile-pages#1020]
Hi.

In last update, there is a php error, in class wp-content/plugins/accelerated-mobile-pages/templates/customizer/customizer.php

Line 44 should be

`public static function register_customizer_ui( $wp_customize ) {`

In order to make working the add_action

`add_action( 'amp_customizer_register_ui', array( __CLASS__, 'register_customizer_ui' )  );`

Regards!

**Comment by MohammedKaludi** [comment]
Hey @MrViSiOn 

Thank you very much for reporting the issue, it is not our plugin that broke the site, it is the update of AMP plugin by Automattic that broke the code, in the change log you can see "- Fix: PHP Warnings from `register_customizer_ui` (props jahvi)" 

But we have acted on it quickly and pushing the update to our plugin as well.

It will be available to you in 30 mins or so.

Thank you very much for reporting the issue.

Thank you,
Mohammed Kaludi

**Comment by MohammedKaludi** [comment]
Tested on multiple systems and its working now, with old and new versions
