### ISSUE TITLE
The new version broke my website.

### ISSUE THREAD

**Issue by aashishpahwa** [ahmedkaludi/accelerated-mobile-pages#1021]
Hi
The latest version broke my website. Had to delete it from cpanel.

Error 
Fatal error: Cannot make static method AMP_Customizer_Design_Settings::register_customizer_ui() non static in class AMPFORWP_Customizer_Design_Contols in /home/xxxxx/public_html/wp-content/plugins/accelerated-mobile-pages/templates/customizer/customizer.php on line 217

Tell me how to cope up with this and getting previous settings back

**Comment by MohammedKaludi** [comment]
Reported at #1020 as well and will continue the conversion on #1020

**Comment by aashishpahwa** [comment]
How will I get my previous settings back? I have your bugged plugin in my trash

**Comment by MohammedKaludi** [comment]
we have pushed the update,  just deactivate the AMP by automattic plugin and install the update and then reactivate it and all things will comeback to normal.

And you will also get your settings back as well.
