### ISSUE TITLE
The tag ‘script’ is disallowed except in specific forms

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1024]
The new updates(AMP and AMPforWP) are throwing this error, we have to check the sanitization properly and resolve it ASAP

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/latest-update-crashes-site-3/
https://wordpress.org/support/topic/i-have-updated-the-amp-plugin-and-the-plugin-is-corrupted/

**Comment by ahmedkaludi** [comment]
@MARQAS @MohammedKaludi If this is fixed then close the ticket please.
