### ISSUE TITLE
Post AMP 0.5 Update Bugs

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1025]
- [x] Ads are not working after the update (This is confirmed.)  #1030 https://wordpress.org/support/topic/comments-do-not-appear-ads-do-not-appear/

- [x] Static Homepage is not working: https://wordpress.org/support/topic/static-home-page-is-not-working-after-update/

- [x] No Category: https://wordpress.org/support/topic/another-problem-with-category/#post-9386390

- [x] Warnings: https://wordpress.org/support/topic/warning-invalid-argument-supplied-for-foreach-in-15/

- [x] Some pages are working, some are not: see the below comment for more info on this

- [x] Below the Post content ads are only displaying when our plugin is downgraded to 0.9.56 and AMP by Automattic 0.4.2 #1030

**Comment by MARQAS** [comment]
Some pages are not working, users also reporting this: 
https://wordpress.org/support/topic/some-pages-working-some-not/
https://wordpress.org/support/topic/guys-get-your-s-together/

**Comment by MARQAS** [comment]
Note: Only some categories are not working not all

**Comment by ahmedkaludi** [comment]
All the things mentioned are working as expected.
