### ISSUE TITLE
Cookie notifications for website in the EU.

### ISSUE THREAD

**Issue by nicholasgriffintn** [ahmedkaludi/Accelerated-Mobile-Pages#103]
Hey,

I had to edit the plugin in order to enable it to show notifications for cookies, as is required by the EU directive and I figured it would be better to share my edited code with the main plugin so everyone can have this feature and I have less to change with every update :).

I have created a pull request of the finished code, please take a look at let me know what you think.

**Comment by nicholasgriffintn** [comment]
Here's the pull request: #104

**Comment by MohammedKaludi** [comment]
Thank you very much @nicholasgriffintn  I have seen the code, looks okay to me. But will test once locally and  will merge it.

Thank you once again for your support and contribution.

**Comment by nicholasgriffintn** [comment]
@MohammedKaludi Awesome, let me know if there's anything I need to change for any of my pull requests and I will add it in.

**Comment by nicholasgriffintn** [comment]
This has been added so I am closing the issue.
