### ISSUE TITLE
AMP 0.5 vendor update

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1033]
## AMP 0.5 vendor update

- [x] Whitelist Sanitizer: Replace Blacklist Sanitizer with a whitelist-based approach using the AMP spec (props delputnam)
- [x] Image Dimensions: Replace fastimage with fasterimage for PHP 5.4+. Enables faster downloads and wider support (props gititon)
- [x] Embed Handlers: Added support for Vimeo, SoundCloud, Pinterest (props amedina) and PlayBuzz (props lysk88)
- [x] Analytics: UI for easier addition of analytics tags (props amedina)
- [x] Fix: parse query strings properly (props amyevans)
- [x] Fix: Old slug redirect for AMP URLs (props rahulsprajapati)
- [x] Fix: Handle issues with data uri images in CSS (props trepmal)
- [x] Fix: Add amp-video js for amp-video tags (props ptbello)
- [x] Fix: Output CSS for feature image (props mjangda)
- [x] Fix: Fix attribute when adding AMP Mustache lib (props luigitec)
- [x] Fix: Various documentation updates (props piersb, bhhaskin)
- [ ] Fix: PHP Warnings from register_customizer_ui (props jahvi)

- [x] Fix: Coding Standards (props paulschreiber)

- [x] Dailymotion embed as well

**Comment by MARQAS** [comment]
amp-video resolved here: #991

**Comment by MARQAS** [comment]
Analytics added here: #1084

**Comment by MARQAS** [comment]
Fix: parse query strings properly is related to wpcom

**Comment by MARQAS** [comment]
Regarding this one: 
Fix: Old slug redirect for AMP URLs
How about archives? @MohammedKaludi

**Comment by MARQAS** [comment]
@MohammedKaludi will look into PHP Warnings from register_customizer_ui

**Comment by MARQAS** [comment]
We will tackle Whitelist Sanitizer here: #1357

**Comment by MohammedKaludi** [comment]
All the things are working as expected, tested thoroughly and didn't find any issue.
