### ISSUE TITLE
Favicon for AMP

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1039]
Guys, please check Favicon is showing or not in AMP

Ref: https://secure.helpscout.net/conversation/397847948/14244/?folderId=1060551

**Comment by DZuz14** [comment]
Adding this in the SEO-> Additional tags section of the plugin worked fine. It passed the validator test for me.

`<link rel="icon" type="image/ png" href="yourlinktoyourimagehere.png">`

**Comment by MohammedKaludi** [comment]
Working and favicon directly connect with the option in Theme Customizer, so amp will automatically get the favicon set in normal site.
Ticket Closed.
