### ISSUE TITLE
OverRide the black list sanitizer

### ISSUE THREAD

**Issue by ambantatua** [ahmedkaludi/accelerated-mobile-pages#1042]
Hi there,
Is it possible to address the issue of form elements being blacklisted now that you have bundled AMP by Automattic?
File location vendor/amp/includes/sanitizers/class-amp-blacklist-sanitizer.php - I'm currently commenting the form elements out.

Thanks.

**Comment by ahmedkaludi** [comment]
A tutorial in developer documentation on how to over ride the black list sanitizer would make sense.

**Comment by MARQAS** [comment]
https://ampforwp.com/tutorials/article/override-blacklist-sanitizer/

**Comment by MohammedKaludi** [comment]
:+1:
