### ISSUE TITLE
Image URL In Structured Data On  Home Page is catching the latest posts featured Image.

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1044]
![view-source_https___www gigrev com_amp_ - google chrome 2017-08-10 21 14 37](https://user-images.githubusercontent.com/28556545/29179105-17f20b72-7e11-11e7-9971-79f219ab13bc.png)

$data should be made to null on home page so the Default Image in Structured Data taken instead of any random posts  featured image

**Comment by Frenchomatic** [comment]
I think it should take any properly defined featured image defined on the page and if not the default image. See issue here #1013
