### ISSUE TITLE
Rename AMP loop widget areas or add proper descriptions

### ISSUE THREAD

**Issue by joycegrace** [ahmedkaludi/accelerated-mobile-pages#1045]
Reference this thread: https://wordpress.org/support/topic/amp-above-loop-and-amp-below-loop-widget-areas/

AMP below loop and AMP above loop widget areas are currently only working on the home page, so the labelling is a bit misleading. 

If this is the case, the labelling should say "AMP home page below loop" and "AMP home page above loop" so the user knows they won't appear in the regular template loop on all pages.

Or add a descriptor below the title saying so. This could save a lot of time and confusion. 

Better solution: Add a loop area that applies site-wide on all AMP pages. Users can control with widget logic, to get it to appear on specific AMP pages? Or new widget area for site-wide loops.

**Comment by MohammedKaludi** [comment]
769b82fd0c522923143fca5f49f88ea8bf6b0284

**Comment by MohammedKaludi** [comment]
Gap needs to be fixed https://monosnap.com/file/cXQozOC19wcO4txwz90ElEWS2x9ZpM

**Comment by potatoqualitee** [comment]
ive been at this all day. the loops are useless for me and the title didnt let on that it'd only work on the homepage. any way i can get what i want to show above my recipes?

https://www.realcajunrecipes.com/recipe/beignets-a-french-doughnut/amp

**Comment by potatoqualitee** [comment]
(i only commented, i did not unassign, github is whack)

**Comment by ahmedkaludi** [comment]
@potatoqualitee just send me an email on team@ampforwp.com and my team will take care of it
