### ISSUE TITLE
Create site-wide loop widget areas

### ISSUE THREAD

**Issue by joycegrace** [ahmedkaludi/accelerated-mobile-pages#1046]
Hi there, it would be awesome to have site-wide AMP loop widget areas, just like the current widget areas that only work on the home page.

Reference: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1045

And https://wordpress.org/support/topic/amp-above-loop-and-amp-below-loop-widget-areas/

This would be great for getting sidebar content on AMP pages.

Also awesome if this could work with widget logic plugin: https://wordpress.org/plugins/widget-logic/

**Comment by pegazee** [comment]
This ticket is done in #1045

**Comment by MohammedKaludi** [comment]
More info on #1045
