### ISSUE TITLE
structured data improvements suggestions from users

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1048]
Google recommends that within the structured schema.org for an AMP article, a description should be supplied as well as a headline. It isn’t mandatory but it is something they would prefer to see given.

Would it be worth considering setting a structured description to at least take the meta description until a better solution can be found?

------------------------
As an enhancement down the line - I think there is a real need to allow json to be embedded into the head of an AMP article via the editor. To currently do it requires a lot of mucking about in functions.php. For example, it is currently quite difficult to put a local business structured data type onto an AMP article.

**Comment by MARQAS** [comment]
@frenchomatic can you talk about structured data in this ticket?

It's getting mixed up there.

**Comment by Frenchomatic** [comment]
oK I put it here to keep on topic. This looks to me like there is a logic issue. 

So includes\vendor\amp\includes\class-amp-post-template.php function is doing something strange.

It appears that the private function build_post_data() runs twice on a static home page but only once on a normal page.

Reference comments about setting the author + issue of wrong featured image in structured data on a static home page.

On a static home page it goes through the function below twice. There are two scenarios. If the site has no blog at all, the first time the author is NULL and on the second pass it gets the correct author display name. However, the structured data element is being set on the first time round and doesn't get reset with the correct data on the second (not sure why). It doesn't get the correct featured image either in the structured data.

private function build_post_data() {
		$post_title = get_the_title( $this->ID );
		$post_publish_timestamp = get_the_date( 'U', $this->ID );
		$post_modified_timestamp = get_post_modified_time( 'U', false, $this->post );
		$post_author = get_userdata( $this->post->post_author );
**echo "--- why is this null first time round --- " . $post_author->display_name;**
If there is a blog on the site too, then it still goes round twice but on both occasions it gets the correct author display name. It still doesn't get the correct featured image though.

And this is what is gets echoed to the screen with my insertion:

why is this null first time round --- --- why is this null first time round --- mydisplayname

Conversely when there is a blog on the site, the static home page gives this

--- why is this null first time round --- mydisplayname--- why is this null first time round --- mydisplayname

It seems to me that this function runs for the loop first (whether a blog exists or not) and then runs again for the home page.

I did send you an email with examplae web sites.

**Comment by Frenchomatic** [comment]
To get a description for structured data = to the meta description (seems like a good first step) in private function build_post_data()  -  includes/vendor/amp/includes/class-amp-post-template

I think we can do this in terms of getting a description into the structured data? 

$desc = ampforwp_generate_meta_desc();
.
.
.

'description' => $desc,

This seems to work nicely although it is inefficient calling that function once for structured data and another time for the meta description. You will know a better way for sure.  We still have the issue for static home pages (author display names and featured images so there is no confusion).

**Comment by Frenchomatic** [comment]
Can you confirm what I am seeing that private function build_post_data() is running twice on a static front-page.

**Comment by MARQAS** [comment]
Personally I think you need a hook so json can be added in the head of any page via the custom editor. It can be used for adding structured data. For example a use case - article about a local business. The local business schema can be easily added. At the moment it requires playing around with functions.php to test for a page and add it in conditionally.

By @Frenchomatic

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/some-small-issues-version-0-9-59/

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/featured-image-static-home-page-incorrect-structured-data/
