### ISSUE TITLE
Need to escape alt tag

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1049]
alt tag needs escaping @MARQAS use esc_attr($var_name);

User is facing the validation issue because of this. Ref: https://wordpress.org/support/topic/trying-to-get-rid-of-one-final-small-error-to-get-our-amp-homepage-working/

**Comment by Frenchomatic** [comment]
I think you should do what you have done on other pages in frontpage_elements and that is use the proper alt tag and not the post title. (i.e. your function ampforwp_thumbnail_alt()).  No real reason to make the front page different.

**Comment by ahmedkaludi** [comment]
Reviewed
