### ISSUE TITLE
Alt tag on frontpage elements

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1050]
Related to #1049 but not quite the same issue (may as well fix all at the same time):

I think you should do what you have done on other pages in frontpage_elements and that is use the proper alt tag and not the post title. (i.e. your function ampforwp_thumbnail_alt()).  No real reason to make the front page different. This works for me but you can obviously do it differently or condition it on the post title if alt is empty. 

```
<figure class="amp-wp-article-featured-image wp-caption"> <?php  
				$thumb_id = get_post_thumbnail_id($post_id);
				$image = wp_get_attachment_image_src( $thumb_id, 'medium' ); 
				$caption = get_the_post_thumbnail_caption( $post_id ); 
				$alt = esc_attr(get_post_meta( $thumb_id, '_wp_attachment_image_alt', true));
				?>
				<amp-img src="<?php echo $image[0]; ?>" width="<?php echo $image[1]; ?>" height="<?php echo $image[2]; ?>" layout=responsive alt="<?php echo $alt; ?>" >  </amp-img>
```

I already do something similar on the logo in header-bar.php because the logo has an alt tag defined.

**Comment by Frenchomatic** [comment]
Thanks Marqas - lots of progress.

**Comment by Frenchomatic** [comment]
Also, as you can see on the forum people have an issue with blurred images. Why not use the same featured image with screen set on the front page as on all other pages / posts. I know it takes a bit more resource but it is minuscule and it avoids people posting on the forum about it.

**Comment by MARQAS** [comment]
Hi @Frenchomatic , 
I have created a separate ticket about the featured, we will test it and will definitely solve this problem
#1063

**Comment by ahmedkaludi** [comment]
Reviewed
