### ISSUE TITLE
A smooth way to migrate from other AMP plugins to AMPforWP

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1051]
There are many users who want to migrate from other AMP plugins to this and they want to redirect those URLs to the correct amphtml i.e., /amp/ in the end. 

reference: https://wordpress.org/support/topic/go-from-site-comamppost-to-site-compostamp/

This is just one example, much more are there. If we can give them a better solution, they will not hesitate much about their URLs.

**Comment by Frenchomatic** [comment]
Redirectmatch will probably be the most efficient way to do this.
