### ISSUE TITLE
Redirection issues

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1052]
I am creating a new ticket for all the redirection issues so that it can be easy for us to manage all redirection concerning issues.

Here is the list: 

- [ ] Post pagination: /?amp to /amp/  
ref: https://wordpress.org/support/topic/pagination-url-pretty-permalink-unaccessible/
This will be covered here: #1007 

- [x] Blog should redirect to blog when homepage support is off in AMP
ref: #871 
- [x] Disbale mobile redirection on Custom post types(non amp)
ref: #1028 

- [x] Redirect categories when AMP is disabled on them
ref: #999 

- [x] extra redirection with mobile redirection enabled
ref: #879 #933 

- [x] Mobile redirection is not working on home if pages support is off
ref: https://wordpress.org/support/topic/mobile-redirect-on-home/

- [x] View non-amp version link on blog posts pages goes to static home page and not the normal blog posts page.
ref: https://wordpress.org/support/topic/some-small-issues-version-0-9-59/

Feel free to add more items in the list if you find any. (please make sure to add the reference as well)

**Comment by MARQAS** [comment]
If mobile redirection doesn't work on Custom frontpage, then enable the AMP on that page. 
It will surely work

**Comment by ahmedkaludi** [comment]
The first task was added as a separate ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1007
