### ISSUE TITLE
Youtube Shortcode is not working

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1054]
We have to run this ShortCode: 
[youtube]https://www.youtube.com/watch?v=0EW22LzSaJA[/youtube] in AMP.

Ref: https://secure.helpscout.net/conversation/412810554/15153/?folderId=1060551

**Comment by ahmedkaludi** [comment]
we already have a default youtube shortcode. No need to add this support. If you want to add youtube... Add direct link, default youtube shortcode or embed code.
