### ISSUE TITLE
removal of category and tags from single

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1055]
I have one future enhancement to recommend that I know users will want because they often ask theme developers how to remove it. On blog posts, it puts in a link to the category in the top right hand corner. Many people have single category blogs and they want to hide the category. It is not serving any puposes. A toggle is needed in the admin panel under "single" so the test to echo it fails - something like

if ( $ampforwp_categories && !redux ..... ) : ?>
 	<div class="amp-wp-meta amp-wp-tax-category ampforwp-tax-category">

**Comment by ahmedkaludi** [comment]
are you talking about the one that displays in the single posts?
A screenshot would be helpful.

**Comment by Frenchomatic** [comment]
The one that appears on posts. Imagine you set up a blog with a single category  -  you have a simple blog posts page which then links to all of the posts. Those posts do not need a category link in the top right hand corner.

**Comment by Frenchomatic** [comment]
In reality this is a bug still in 9.65.1 - the issue is if you turn it off in the admin panel - 

1. you just get the words still rather than it being removed entirely. 
2. It also removes your tags completely and you may want these to be showing. 

alot of people use tags and don't use categories - visa versa too.

**Comment by mayanksharma9033** [comment]
In our Post builder launch option, the categories link are not working properly to show and hide the categories links on the single post, some user want this or some user don't want it depends, we need to decide it.

**Comment by Frenchomatic** [comment]
The option to turn categories off only removes the link. It doesn't remove the words which it should - think of a single blog with only one category - you don't show it because you have a blog posts page. Turning off categories also removes tags. Many people use tags and not categories.
