### ISSUE TITLE
AMP vendor update to 0.5.1

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1056]
Ref: https://wordpress.org/plugins/amp/#developers

**Comment by ahmedkaludi** [comment]
# Bugs reported

- [ ] https://wordpress.org/support/topic/notice-with-new-version/#post-9467635 ( https://github.com/Automattic/amp-wp/issues/149 )

**Comment by MARQAS** [comment]
More details: #1033 
Closing this ticket
