### ISSUE TITLE
Author Name, Category and Tags must be Clickable

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1057]
the meta info in a post such as an author name, category and tags must be clickable to its respected page in all desings.

![how to embed a youtube video _ homedew - google chrome 2017-08-17 19 19 45](https://user-images.githubusercontent.com/28556545/29415625-409d80cc-8381-11e7-9360-917389b4a46f.png)

**Comment by Frenchomatic** [comment]
I can see several issues here. In many cases people run single blogs and they don't want to show the category at all whether linked or not.  #1055 .  Linking author probably needs to be optional because again many people link not to the author profile but to their about us page.

**Comment by ahmedkaludi** [comment]
@Sejiro-Hiko they are already clickable. If the archive support is enabled then they also becomes clickable.

**Comment by Frenchomatic** [comment]
I can't really add more to what I have said -  things like author, categories and that type of stuff need to be optionally turned on/off
