### ISSUE TITLE
Posts with no images on Archive pages are limited to 65%

### ISSUE THREAD

**Issue by agk4444** [ahmedkaludi/accelerated-mobile-pages#1058]
While the posts with no images look fine on the home page, any post on the archive pages are left aligned and squeezed to 65%.

Changing 
`<div class="amp-wp-content amp-loop-list ">`
to 
`<div class="amp-wp-content amp-loop-list <?php if ( has_post_thumbnail() ) { } else{?>amp-loop-list-noimg<?php } ?>">`

can resolve the issue.

**Comment by MohammedKaludi** [comment]
Tested, its working and looks nice.
