### ISSUE TITLE
Create a hook after body tags

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1059]
Create a hook after starting body tag and one more just before closing body tag.

**Comment by MARQAS** [comment]
We already have hooks just before the closing of the body tag. "amp_post_template_footer"

**Comment by Frenchomatic** [comment]
Personally I think you need a hook so json can be added in the head of any page via the custom editor. It can be used for adding structured data. For example a use case - article about a local business. The local business schema can be easily added. At the moment it requires playing around with functions.php to test for a page and add it in conditionally.

**Comment by MARQAS** [comment]
Hi @Frenchomatic, 
Thanks for the suggestion, noted down in the structured data list.

**Comment by ahmedkaludi** [comment]
tested and added
