### ISSUE TITLE
Unlink titles on blog posts page + archives

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1060]
Many people do not link titles on their archive pages or blog posts page. Many unlink the image too. They use a read more link instead after the excerpt. 

Would it be possible to create a document that references how to make a customization in their functions.php file.  Such a document of popular customizations would mean the same questions in the forum become quicker to answer.

**Comment by ahmedkaludi** [comment]
Yes, I agree that popular customizations document should be there but I don't see why would people don't want to link titles as links. Also we're quickly going to move all-in into AMP theme Framework, so I guess this is safe to close.

**Comment by Frenchomatic** [comment]
One reason is that it is not WCAG 2.0 accessible. It means those with screen readers get two adjacent links to the same information. Yes you can close it.
