### ISSUE TITLE
Blog posts page when set as the posts page

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1062]
In index.php I think there is a problem with this code or more correctly there needs to be a test for a blog posts page when it is set as the posts page. That is pretty much the normal situation. 

````
<?php if ( is_archive() ) {
 			the_archive_title( '<h1 class="amp-wp-title">', '</h1>' );
 			the_archive_description( '<div class="taxonomy-description">', '</div>' );
 		} ?>
````

As this stands the title of the blog posts page doesn't show. In addition, clicking the link for the non-amp version goes to the home page and not to the blog posts page. Solution to the first part is this 

````
<?php if ( is_archive() ) {
 	the_archive_title( '<h1 class="amp-wp-title">', '</h1>' );
 	the_archive_description( '<div class="taxonomy-description">', '</div>' );
 }elseif(is_home()){
	echo '<h1 class="amp-wp-title">' . get_the_title(get_option('page_for_posts', true)) . '</h1>';
 }
````
To solve the second requires modification of function function ampforwp_view_nonamp() in features.php to separate out the cases of front_page and is_home

**Comment by Frenchomatic** [comment]
Do you have a fix for  ampforwp_view_nonamp()

**Comment by MARQAS** [comment]
I think I have covered this here #1052

**Comment by ahmedkaludi** [comment]
@Frenchomatic Can you test it with 0.9.63 and confirm if it's fixed?

**Comment by Frenchomatic** [comment]
I will try to look at this in the monring on my test site and also see what things are left on the list that I wrote.

**Comment by Frenchomatic** [comment]
works now in 9.65.1
