### ISSUE TITLE
Test Frontpage Featured Image

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1063]
Some users are reporting that the Featured Image of static Frontpage is blurred.

We need to understand their use case, test and resolve it if it's necessary.

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/frontpage-image-too-small/

**Comment by Frenchomatic** [comment]
There are a few posts that explain the issue. It is because medium for many people is 300px wide and the image gets blurred. Why is the full featured image not being used with scrset as on posts/pages generally.

**Comment by MARQAS** [comment]
This is resolved in #1050

**Comment by pegazee** [comment]
I've tested this scenario with all designs and it seems that issue has been resolved in the #1050. Now, Featured image working perfectly on the Custom FrontPage

**Comment by Frenchomatic** [comment]
Good - is it using screen sets and is it the image presented in the structured data? I haven't had a chance to test. The accompanying (related) issue is that the custom home page on design 2 is not using the same html or css as any other page.

**Comment by MohammedKaludi** [comment]
Tested and a solution is working for both big and small images.
