### ISSUE TITLE
Textarea for body tag?

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1064]
Should we add a text area for body tag as well? like the way, we are adding it for header and footer. 

Reason: According to amp-auto-ads, the ad code should be immediately after the body. So if user wants to add the auto ads they have to use the hook from #1059 

Is text area a better solution or there's another workaround?

**Comment by Frenchomatic** [comment]
If you do that I guarantee people will put non-compliant stuff into it like javascript or json.

**Comment by MARQAS** [comment]
I think a note that says to add AMP validated content only will work, what you say @Frenchomatic ?
