### ISSUE TITLE
a bunch of critical errors have just popped up. I have changed nothing.

### ISSUE THREAD

**Issue by gatehealing** [ahmedkaludi/accelerated-mobile-pages#1067]
Most critical issues are on gatehealing.com/about-jonathan/amp . . . the other one is on /amp

One of the non-critical is a page blocked by robots.txt so I'm not worried about that. The other non-critical is on about-jonathan/contact/amp 

I'm not sure what information is helpful, so please let me know if there is a better way to get you the information.

Here is a copy/paste of google webmaster tools Test page for /about-jonathan/amp - I have expanded the Instances to show the line numbers, so this is long (just the /about-jonathan/amp list):
Not a valid AMP page
Invalid AMP pages will not have AMP-specific features in Google search results
Fix the following 5 issues

Prohibited HTML Tag with AMP equivalent
The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?
6 instances
Line 491:1256
<img src="https://gatehealing.com/wp-content/uploads/2016/08/Gate-logo.jpg" alt="Counseling Austin" /></a><nav role="navigation" itemscope="itemscope"
Line 491:6456
<img class="size-full wp-image-3212" src="https://gatehealing.com/wp-content/uploads/2016/08/Jon-chest-up-2small-e1488657483634.jpg" alt="Jonathan F.
Line 491:12882
<img src="https://gatehealing.com/wp-content/uploads/2016/09/stress-management-65x65.jpg" alt="Fear is not Predictive" class="tt-blog-sc-img" /><h4>Fe
Line 491:13317
<img src="https://gatehealing.com/wp-content/uploads/2017/08/toxic-people-1-65x65.jpg" alt="Dealing with Toxic People" class="tt-blog-sc-img" /><h4>De
Line 491:13758
<img src="https://gatehealing.com/wp-content/uploads/2017/08/toxic-people-65x65.jpg" alt="Understanding Toxic People" class="tt-blog-sc-img" /><h4>Und
Line 491:14260
<img src="https://gatehealing.com/wp-content/uploads/2017/07/qtq80-gla7B4-65x65.jpeg" alt="Understanding the Problem Doesn&#8217;t Guarantee its Resol

Learn more about this issue

Prohibited or invalid use of HTML Tag
The attribute 'as' may not appear in tag 'link rel='.
1 instance
Line 1:18592
<link rel="preload" as="style" media="all" href="https://gatehealing.com/wp-content/cache/autoptimize/css/autoptimize_ff134455ea72666b527a0531eeffde3f

Learn more about this issue
The attribute 'media' may not appear in tag 'style amp-custom'.
1 instance
Line 1:714
<style type="text/css" id="aoatfcss" media="all">html,body,div,span,h1,h2,p,a,img,strong,i,ul,li,fieldset,form,label{border:0;font-size:100%;vertical-

Learn more about this issue
The attribute 'onblur' may not appear in tag 'input'.
1 instance
Line 491:837
<input type="text" name="s" class="s" id="s" value="Search" onfocus="this.value=(this.value=='Search') ? '' : this.value;" onblur="this.value=(this.va

Learn more about this issue
The attribute 'onfocus' may not appear in tag 'input'.
1 instance
Line 491:837
<input type="text" name="s" class="s" id="s" value="Search" onfocus="this.value=(this.value=='Search') ? '' : this.value;" onblur="this.value=(this.va

Learn more about this issue
The attribute 'onload' may not appear in tag 'link rel='.
1 instance
Line 1:18592
<link rel="preload" as="style" media="all" href="https://gatehealing.com/wp-content/cache/autoptimize/css/autoptimize_ff134455ea72666b527a0531eeffde3f

Learn more about this issue
The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.
1 instance
Line 26:760
<style type='text/css'>/*removes the comments bubble icon*/

Learn more about this issue
The mandatory attribute 'target' is missing in tag 'FORM [method=GET]'.
1 instance
Line 491:676
<form role="search" method="get" action="https://gatehealing.com/" class="search-form"><fieldset> <label for="s">Search this website</label> <span cla

Learn more about this issue
The parent tag of tag 'link rel=stylesheet for fonts' is 'noscript', but it can only be 'head'.
1 instance
Line 1:18807
<link type="text/css" media="all" href="https://gatehealing.com/wp-content/cache/autoptimize/css/autoptimize_ff134455ea72666b527a0531eeffde3f.css" rel

Learn more about this issue

Invalid CSS stylesheet
The inline 'style' attribute is not allowed in AMP documents. Use 'style amp-custom' tag instead.
11 instances
Line 491:6380
<div id="attachment_3212" style="width: 160px" class="wp-caption alignleft"><img class="size-full wp-image-3212" src="https://gatehealing.com/wp-conte
Line 491:8162
<p style="text-align: left;"><h4 class="heading-horizontal" style="margin:20px 0 20px 0;"><span>Solution-oriented training</span></h4><p style="text-a
Line 491:8191
<h4 class="heading-horizontal" style="margin:20px 0 20px 0;"><span>Solution-oriented training</span></h4><p style="text-align: left;">While working at
Line 491:8296
<p style="text-align: left;">While working at an international Employee Assistance Program (EAP), I had the good fortune of receiving in-person traini
Line 491:8607
<ul style="text-align: left;"><li>Insoo Kim-Berg</li><li>Scott Miller, PhD</li><li>Barry Duncan, PhD</li></ul><p style="text-align: left;">These teach
Line 491:8717
<p style="text-align: left;">These teachers were extremely important in shaping my approach to effective psychotherapy. I learned to assume that you a
Line 491:9123
<h3 class="heading-horizontal" style="margin:20px 0 20px 0;"><span>LPC Supervisor</span></h3><p>An <a href="https://gatehealing.com/counseling-austin/
Line 491:9748
<h3 class="heading-horizontal" style="margin:20px 0 20px 0;"><span>Management Consultant &#8211; Trauma Specialist</span></h3><p>For 7 years, Jonathan
Line 491:10393
<h3 class="heading-horizontal" style="margin:20px 0 20px 0;"><span><a name="item1"></a>Teacher, Facilitator, Writer</span></h3> Teaching small groups
Line 491:10947
<span style="text-decoration: underline;"><strong>Writing for Baba Ram Dass</strong></span> &#8211; After having met with him on several occasions, Jo
Line 491:11710
<span style="text-decoration: underline;">Be Here Now</span>, and shared their experiences and thoughts on the Ram Dass Now blog. He used the opportun

Learn more about this issue
The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value 'https://gatehealing.com/wp-content/cache/autoptimize/css/autoptimize_ff134455ea72666b527a0531eeffde3f.css'.
1 instance
Line 1:18807
<link type="text/css" media="all" href="https://gatehealing.com/wp-content/cache/autoptimize/css/autoptimize_ff134455ea72666b527a0531eeffde3f.css" rel

Learn more about this issue

AMP markup missing or incorrect
The mandatory attribute '⚡' is missing in tag 'html ⚡ for top-level html'.
1 instance
Line 1:214
<html lang="en-US"> <head><meta name="viewport" content="width=device-width, initial-scale=1" /><link rel="profile" href="http://gmpg.

Learn more about this issue
The property 'minimum-scale' is missing from attribute 'content' in tag 'meta name=viewport'.
1 instance
Line 1:256
<meta name="viewport" content="width=device-width, initial-scale=1" /><link rel="profile" href="http://gmpg.org/xfn/11"><link rel="pingback" href="htt

Learn more about this issue
The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.
1 instance
Line 521:624

Learn more about this issue
The mandatory tag 'head > style[amp-boilerplate]' is missing or incorrect.
1 instance
Line 521:624

Learn more about this issue
The mandatory tag 'html ⚡ for top-level html' is missing or incorrect.
1 instance
Line 521:624

Learn more about this issue
The mandatory tag 'meta charset=utf-8' is missing or incorrect.
1 instance
Line 521:624

Learn more about this issue
The mandatory tag 'meta name=viewport' is missing or incorrect.
1 instance
Line 521:624

Learn more about this issue
The mandatory tag 'noscript > style[amp-boilerplate]' is missing or incorrect.
1 instance
Line 521:624

Learn more about this issue

User-authored JavaScript found on page
The tag 'script' is disallowed except in specific forms.
5 instances
Line 1:19557
<script type="text/javascript" data-cfasync="false">var disableStr = 'ga-disable-UA-10352992-3';
Line 490:941
<script type="text/javascript" async defer
Line 494:2089
<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
Line 518:86
<script type="text/javascript" defer src="https://gatehealing.com/wp-content/cache/autoptimize/js/autoptimize_c8e48e903851a5a485156fc99a99ec9a.js"></s
Line 518:242
<script data-cfasync='false'>/*! loadCSS. [c]2017 Filament Gr

Here's the copy/paste of the critical error on /amp (also expanded, but very short):
Not a valid AMP page
Invalid AMP pages will not have AMP-specific features in Google search results
Fix the following issue

Invalid usage of AMP tags
The attribute 'border' may not appear in tag 'amp-img'.
1 instance
Line 317:200
<amp-img class="alignnone" title="Psychology Today Verification" src="https://therapists.psychologytoday.com/rms/external_verification.php?profid=4255

**Comment by gatehealing** [comment]
I'm not sure if the entire text from what I put in my post is in what I see above . . . looks like it actually pulled text and images from my website rather than just showing the code. Pls let me know if I need to do something different.

**Comment by Frenchomatic** [comment]
There is no amp page here https://gatehealing.com/about-jonathan/ so impossible to help. Also you will find more response on the wordpress forum as github is mainly for bugs and development.

**Comment by gatehealing** [comment]
I'll have to look into why there's no amp page for that . . . looks like it is redirecting to the non amp version for some reason. I'll goto WordPress forum now. Thanks for heads up. Not sure how I wound up here though. . . I think I followed some kind of support link from the plugin itself . . . that may need to be checked, but I'm not entirely sure.

**Comment by nicholasgriffintn** [comment]
Yeah, looking at it your error it's because AMP isn't working on your site. adding "/amp" to any of your URLs simply goes to a 404, so that's definitely your issue. Be sure that the plugin is installed and activated if it is then trying to re-save your permalinks might work.

This should probably be closed now.

**Comment by gatehealing** [comment]
Yeah, I just decided to delete the plugin altogether. Thanks though, before deleting it I did try the permalinks solution to no avail.

**Comment by MARQAS** [comment]
Hi @gatehealing , sorry for the delayed response. 

If something like that happens try to use Custom AMP editor, there are still many attributes which AMP don't support and will through validation errors. 
So for those pages, you can use custom AMP editor. Just copy the content into Custom AMP Editor and remove those attributes from Custom AMP Editor.

**Comment by ahmedkaludi** [comment]
We have fixed most of errors in 0.9.63. 

If you find any errors then please report them to https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1219

Closing this one.
