### ISSUE TITLE
Static front-page

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1068]
The more I look at the front-page the more I don't understand why it is built in this way - the structure is quite different to any other type of post/page. Why is the same code as in single.php not being used. The position of the h1 and featured image is different and a different div is being used as well. It means for example that you get padding around the featured image on the home page which you don't get on a normal page.   

**Normal page/ post** 

```
<main>
		<article class="amp-wp-article">
... meta stuff
          <header class="amp-wp-article-header ampforwp-title">
	             <h1 class="amp-wp-title"> My page title </h1>
	</header>
```

**Front-page** 

```
<header class="amp-wp-article-header ampforwp-title">
			<h1 class="amp-wp-title"> My home page title </h1>
</header>
<main>
		<div class="amp-wp-content the_content">
                    <figure class="amp-wp-article-featured-image wp-caption">
```
It means if you use the custom editor for a static home page then you don't get quite the same as any other page in terms of structure or the way it looks.

**Comment by MARQAS** [comment]
@Frenchomatic 
I made several changes based on your suggestions
Can you check now?

**Comment by Frenchomatic** [comment]
Just tested on saleking.com and your proposed changes correct the problem of the home page looking different - image now fills the area without padding all around it. Well done.  

I have rolled the code back on the test domain for the time being but your commits do appear to solve the issue.
