### ISSUE TITLE
Insertion of strange spaces around H1 titles

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1069]
I notice additional spaces are being put in around h1 titles on all types of pages, archives, tags, etc - very strange as they do not appear on the regular pages when using code like `the_archive_title('','') ` is being used. I can't see why it is doing this only when used in amp pages.

**Comment by Frenchomatic** [comment]
Seems to to still be doing this on version 0.9.5.9 - see test system which is running latest version.

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic ,

Are you talking about this by any chance?

![inkedview_source_newsdesk_dev_category_account_li](https://user-images.githubusercontent.com/28556545/30971422-7608a348-a485-11e7-8307-708b6eaa3770.jpg)

**Comment by Frenchomatic** [comment]
It is occurring between H1 tags on most pages -  see test system running latest version -` www.saleking.com`

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic  Can you please test this commit and let me know.

**Comment by Frenchomatic** [comment]
Yes it works except you forgot to do the opening h1 on the home page in frontpage elements e.g. take the space out

<h1 class="amp-wp-title"><?php if( is_plugin_active( 'sitepress-multilingual-cms/sitepress.php' )

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic  please test the latest commit for this.
