### ISSUE TITLE
Featured Image is missing

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1071]
Put the same image in the content and there is no featured image.

Desc: There will be no Featured Image when the same image as featured image is added in the content

ref: https://wordpress.org/support/topic/amp-with-featured-image-same-as-image-in-content/

**Comment by MohammedKaludi** [comment]
The issue is back @ahmedkaludi #670

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by stefanoborghi** [comment]
I still have this issue in version 0.9.97.21 @ahmedkaludi
