### ISSUE TITLE
Invisible tags are visible on AMP pages

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1072]
ref: https://wordpress.org/support/topic/invisible-tags-are-visible-on-amp-pages/

**Comment by nicholasgriffintn** [comment]
As i said to the guy on the support page:

> There’s a reason it omits style=”display:none;” and that’s because it’s not valid AMP HTML, with that code your AMP pages will not validate with Google as you can only set one set of styles with AMP.

This isn't really fixable.

**Comment by Frenchomatic** [comment]
Absolutely correct Marqas.

**Comment by ahmedkaludi** [comment]
agreed @nicholasgriffintn and @Frenchomatic
