### ISSUE TITLE
Extending Structured Data JSON 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1073]
"Personally I think you need a hook so json can be added in the head of any page via the custom editor. It can be used for adding structured data. For example a use case - article about a local business. The local business schema can be easily added. At the moment it requires playing around with functions.php to test for a page and add it in conditionally.
"
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1059#issuecomment-323607409

**Comment by Frenchomatic** [comment]
Thanks for putting this issue in. It would be a nice to have. It is not  essential but will give us a small competitive advantage as google loves structured data.

**Comment by ahmedkaludi** [comment]
We already have this ticket: #323

So, we will merge the ticket with it.
