### ISSUE TITLE
Warning: Illegal string offset 'id' in

### ISSUE THREAD

**Issue by mandazi** [ahmedkaludi/accelerated-mobile-pages#1077]
I just installed this WordPress plugin and I am getting this error on the AMP pages:

```
Warning: Illegal string offset 'id' in /wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 2635

Warning: Illegal string offset 'id' in /wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 2639
```

What could be the issue?

Thanks!

**Comment by MARQAS** [comment]
Hi @mandazi ,

Can you tell me which version of the plugin you are using?

**Comment by mandazi** [comment]
@MARQAS Version 0.9.59

**Comment by muhammadyaseenNTV** [comment]
Warning: Illegal string offset 'amp-on-off-for-all-posts' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 64
this error genrated

**Comment by muhammadyaseenNTV** [comment]
Warning: Illegal string offset 'amp-on-off-for-all-posts' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 64

Warning: Illegal string offset 'amp-on-off-for-all-pages' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 69

Warning: Illegal string offset 'ampforwp-homepage-on-off-support' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 74

Warning: Illegal string offset 'ampforwp-archive-support' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 80

Warning: Illegal string offset 'ga-feild' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 92

Warning: Illegal string offset 'amp-design-selector' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 100

Warning: Illegal string offset 'ampforwp-custom-logo-dimensions' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 1163

Warning: Illegal string offset 'amp-analytics-select-option' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 2078

Warning: Illegal string offset 'amp-design-selector' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 4498

Warning: Illegal string offset 'amp-opt-color-rgba-colorscheme' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 4716

Warning: Illegal string offset 'color' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 4716

Warning: Illegal string offset 'amp-design-selector' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 7297

Warning: Illegal string offset 'ampforwp-homepage-on-off-support' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6335

Warning: Illegal string offset 'amp-frontpage-select-option' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6338

Warning: Illegal string offset 'ampforwp-homepage-on-off-support' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6335

Warning: Illegal string offset 'amp-frontpage-select-option' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6338

Warning: Illegal string offset 'REDUX_last_saved' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php on line 740

Warning: Illegal string offset 'REDUX_LAST_SAVE' in /home/nowthisviral/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php on line 742

**Comment by muhammadyaseenNTV** [comment]
i will install the AMP and activated then ALL error genrated

**Comment by muhammadyaseenNTV** [comment]
No open website in desktop view

**Comment by pegazee** [comment]
Hi @muhammadyaseenNTV, This ticket was closed in 2017.  So, We'll move your query to this ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2958. You can tackle this ticket
