### ISSUE TITLE
Category and Tag Base Remover as core features

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1079]
Category and Tag Base Remover as core features and it should not conflict with the category base remover extension.

**Comment by ajeetku** [comment]
If this feature is implemented. Ensure that previous plugin is activated or not, if yes than deactivate it silently old plugin.

**Comment by MohammedKaludi** [comment]
Yes, Working with and without the plugin, smooth!!! :)
