### ISSUE TITLE
/?amp not loading the accelerated page

### ISSUE THREAD

**Issue by 1radiohead** [ahmedkaludi/Accelerated-Mobile-Pages#108]
It showed the first time I used the plugin. Then I uninstalled it & tried another amp plugin & went back to yours. Now the amp page wont load. Thanks.

**Comment by 1radiohead** [comment]
More important is google isn't seeing any AMPs. I did resubmit pages & post in fetch as google. Thanks

**Comment by ahmedkaludi** [comment]
@1radiohead Can you update on this?

**Comment by 1radiohead** [comment]
Sorry what exactly is it you want me to do?

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 16, 2016 at 2:45 PM, Ahmed Kaludi<notifications@github.com> wrote:   
@1radiohead Can you update on this?

**Comment by 1radiohead** [comment]
Right now I'm using your paid priority support.
