### ISSUE TITLE
Author avatars not being removed

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1087]
I notice that avatars are being only hidden using css as opposed to being removed completely – this occurs even when post meta is set to off and avatars are set to not show in main wp admin.
ref: https://wordpress.org/support/topic/author-avatars-not-being-removed/

**Comment by MARQAS** [comment]
We need to test this and make sure that the avatars should be visible only when users want it.

**Comment by Frenchomatic** [comment]
Wordpress 4.8.1 has a switch in the admin panel to not show avatars.

**Comment by Frenchomatic** [comment]
This is not solved in version 9.60 - design 2
