### ISSUE TITLE
Option to add custom things in Instant Articles

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1089]
Header, footer, and article. 

May be we should provide text areas?

**Comment by ahmedkaludi** [comment]
@MARQAS has anyone requested this?

**Comment by MARQAS** [comment]
Yes, users were asking about this on the forum

**Comment by mayanksharma9033** [comment]
Hi @MARQAS,

But my opinion is it is not a bug right, so we don't want now this feature. We will add this in future.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
