### ISSUE TITLE
amphtml: url makes 301 redirection

### ISSUE THREAD

**Issue by MrViSiOn** [ahmedkaludi/accelerated-mobile-pages#1092]
Hi!

I think this is a bad function of the plugin:

I realized that url in meta amphtml always appends a trailing slash at the end of url. This is due to _trailingslashit_ function.

/templates/features.php

Line 258 should (or could) be: 

`printf( '<link rel="amphtml" href="%s" />', esc_url( $amp_url ));`

Or at least, check wordpress permlinks and detect if site urls ends with slash to use _trailingslahit_ function.

This is for avoiding 301 redirections when site does not ends with slahses in its urls

What do you think?

**Comment by Frenchomatic** [comment]
yes - it would be better to test. However,  most people have a trailing slash at the end of urls due to the wordpress permalinks.

**Comment by MrViSiOn** [comment]
It is your decision... I test my webpage in a SEO tool and It said to me that my web has a lot of 301 redirections... and this "issue" is one of the reason.

I think that this url has to be the sema structure that wordpress: if it does not finish with slash, this amphtml shouldn't finish with slash

Am I right?

**Comment by Frenchomatic** [comment]
Not my decision - I am not the developer or support. Yes - it would be better to test and assign $ampurl given the permalink structure. That may be simpler to say than done given it is not just the line you are talking about that will need changing.   The trailingslash issue comes up all over the plugin too for structured data attributes, links, menu links, etc.

**Comment by MrViSiOn** [comment]
You right, this is a huge change then...

**Comment by Frenchomatic** [comment]
Read what I put on the forum. The root of your issue is probably something to do with the fact that  non / urls are not being redirected to ones with a / on the end. It is better that you set things up so links without the / get redirected to the canonical which has a / on the end. Have you checked your htaccess too? W3TC - just deactivate it until things work properly.

**Comment by MrViSiOn** [comment]
The case I'm talking about is the one wich no / has at the end

Like: http://domain/post-name

And amphtml value would be http://domain/post-name/amp/

That amphtml will redirect to http://domain/post-name/amp

That's what I mean

**Comment by MrViSiOn** [comment]
URL:
https://modulos-prestashop.com/analisis-contra-reembolso-con-recargo

amphtml value is: https://modulos-prestashop.com/analisis-contra-reembolso-con-recargo/amp/

But amphtml redirects to https://modulos-prestashop.com/analisis-contra-reembolso-con-recargo/amp

**Comment by Frenchomatic** [comment]
Thought you were the chap on the forum.  My response is almost identical though. Why do you have 

https://modulos-prestashop.com/analisis-contra-reembolso-con-recargo
https://modulos-prestashop.com/analisis-contra-reembolso-con-recargo/

These both have the correct canonical which has a trailing /.

**Comment by MrViSiOn** [comment]
Where is the forum link?

I can't find it

Sorry for this silly question .(

**Comment by MARQAS** [comment]
@MrViSiOn Many users have asked us to add the trailingslash, that's the reason we have added it.
But few users like you are not using /  in the end.

So I believe it would be better to match both needs. 

@Frenchomatic , I have the same thing in my mind :)

**Comment by Frenchomatic** [comment]
Forum link https://wordpress.org/support/topic/amp-page-redirecting-to-normal-http-page/ There are similarities to your issue.

**Comment by ahmedkaludi** [comment]
@MrViSiOn please test this in the 0.9.60 update. It should be working fine.
