### ISSUE TITLE
Light box for Gallery as part of Page Builder

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1094]
How can we show amp-lightbox in the gallery of images?

REF: https://secure.helpscout.net/conversation/420989551/15731/?folderId=1060551

- [ ] Light box as option in the Gallery Module

- [ ] Light box as an option in Image Module.

**Comment by MohammedKaludi** [comment]
One of our user has created a ticket at: https://wordpress.org/support/topic/image-lightbox-in-amp-pages/#post-9788466

He asked us about 8 months back and we are yet to solve this, so we need to learn from this mistake and start implementing things faster.

**Comment by beingsmart3** [comment]
Again We have the same question with WP Touch.

Ref:  https://secure.helpscout.net/conversation/515201367/21043?folderId=1060551
