### ISSUE TITLE
Trailing slash issue

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1095]
The use of the trailingslashit function creates issues for those where their permalinks do not have trailing slashes. The true permalink needs to be tested and used. This problem surfaces in several places including setting of canonicals, structured attributes and on menu links. 

For most people they use trailingslashes on their permalinks and the current code works well - however a few don't.  Having solved the problem originally for the normal case where permalinks do have trailing slashes a few people are having issues - #1092 and on the forum.

**Comment by MARQAS** [comment]
@ahmedkaludi don't close this ticket, as there are other places as well where double trailingslah function is used, we will test it properly in next update.

**Comment by MohammedKaludi** [comment]
Looks great :+1:
