### ISSUE TITLE
google maps iframe – link to larger map

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1099]
This is a strange one – if you embed a google map iframe on your site then the link to larger map will pop a new window. However, in AMP although the iframe renders correctly, the little blue link does nothing.

It appears that in /includes/vendor/amp/includes/sanitizers/class-amp-iframe-sanitizer.php there is a small issue with this line missing the ability to pop links

`const SANDBOX_DEFAULTS = 'allow-scripts allow-same-origin';`

To have the little blue links to a larger map pop in AMP requires this line to be as follows

`const SANDBOX_DEFAULTS = 'allow-scripts allow-same-origin allow-popups';`

Any thoughts on this? It passes validation too so there appears to be no issue.

**Comment by MohammedKaludi** [comment]
Working and closing the ticket.
