### ISSUE TITLE
loading time

### ISSUE THREAD

**Issue by m0sagal** [ahmedkaludi/accelerated-mobile-pages#1101]
Can you suggest tips to improve the loading time
URL : [Repatriation to Pero](https://beassistance.com/destinations/south-america/repatriation-of-deceased-to-peru-lima/amp/)
Thanks

**Comment by Frenchomatic** [comment]
Remove unnecessary fonts, reduce size of images to those for mobiles (means you may need to make special versions of your AMP pages), don't use too much custom css, avoid custom javascript, don't load google ads or other affiliate type stuff, remove google analytics - keep payload as small and simple as possible. 

Your ability to improve loading time is fairly limited.

**Comment by ahmedkaludi** [comment]
@m0sagal Yes, as @Frenchomatic said. That's the general stuff.

This repo is for maintaining the issues, so we can focus on the issues.
