### ISSUE TITLE
Cant disable AMP on Frontpage

### ISSUE THREAD

**Issue by cgpro** [ahmedkaludi/accelerated-mobile-pages#1102]
My Settings:
Homepage Support: Off
Enable Page Builder for AMP: Off

I only want it to enable on my posts.

I use the visual composer for content editing and the Content is empty... therefore is here no benefit for AMP on the Frontpage (Homepage)

I use WP Rocket for caching, I tried also to empty the cache, no success. I saved the permalinks again also...

And there is an other bug: The <title> is not in sync with the Yoast settings.

**Comment by MARQAS** [comment]
Hi @cgpro 
That's strange. Can you share the URL?

**Comment by ahmedkaludi** [comment]
@cgpro You can just disable the Homepage support from the General settings.

**Comment by ahmedkaludi** [comment]
@cgpro We haven't seen this issue yet, Can you please update? or we will have to close this ticke.t

**Comment by MohammedKaludi** [comment]
Closing the ticket, for now, please update the plugin to the latest version and if the issue persists, then please feel free to reopen the ticket.

Mohammed Kaludi
