### ISSUE TITLE
Just tried Version 0.9.60.

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1103]
Just tried Version 0.9.60 **(now 0.9.61)**  Here is a list of outstanding issues.  All of my other tickets can be closed if necessary to save having confusion. 

It works as before but it doesn’t address many of the issues I have listed over the past weeks on both the forum and in github.

1. Static home page is using different css and has a different html structure to other pages (no reason I can see as to why if you are using the custom editor). It means the home page whatever you do is always going to look slightly different. Should it not be using the same code as single.php if it is a static home page? (**I put up some workaround code on the wordpress forum**). 

2. The featured image for a static home page is not the one given in the structured data. - see #1118 

3. The featured image on a static home page is not rendered in the same way using screen sets as featured images are rendered on other posts/pages.

4. H1 should be using the same css on whatever page you are on. If using a different class for .archive_ title then by default it should be the same as .page_title. A minor detail.

5. The logo is not using the alt tag if it has one and still just uses the site title.

6. The archive description is not being rendered onto a blog posts page.

7. The blog posts page title is not being rendered onto the page. It needs to be using this get_the_title(get_option(‘page_for_posts’, true));

8. A new one – breadcrumbs being added and not wanted. Also incorrectly points to /amp and not /amp/

9. No way in admin to remove the categories link from AMP posts.

10. Google advises that a structured description attribute is given on an AMP page. This could by default be set to the meta desription in class-amp-post-template.php - see #1118 It could be resolved here.

11. Gravatar code still being added to the page even though it is set to not display in WP admin. Insted css is being used to set display:none;

12. /blog/amp/page/2/ etc structured data @id is incorrect as it misses page number .

13. Additonal spaces are being applied to <title> bla bla </title> on static home page and blog posts page – may be an interaction with Genesis.

14. H3 being used for tag archive headings but then followed by H2s.

**Comment by MARQAS** [comment]
Hi @Frenchomatic 
Thank you so much for your feedback on these issues. 
I will surely look into them. :)

**Comment by Frenchomatic** [comment]
I will close this as they are still present in the latest version - see #1155
