### ISSUE TITLE
Design 3 Menu RTL?

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1106]
![screenshot_15](https://user-images.githubusercontent.com/16532359/30104319-eb4805ec-9312-11e7-857f-bf750be5a88d.png)

REF: https://secure.helpscout.net/conversation/424004611/15887/?folderId=1060551

**Comment by pegazee** [comment]
And also There is another small problem with RTL
Instead of "Category: Beauty" is "Beauty Category:" showing
ScreenShot> http://take.ms/bOCV4

Ref: https://secure.helpscout.net/conversation/424004611/15887/?folderId=1060551
