### ISSUE TITLE
Enable / Disable Post pagination option

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#111]
Enable / Disable Post pagination option

SUGGESTED AT https://wordpress.org/support/topic/couple-of-questions-previousnext-functionality-language-changefeatured-image/

**Comment by nicholasgriffintn** [comment]
Hey,

I already had some code for this on my own site, so I figured that I would make a quick pull request for this feature, you can find it at #113.

**Comment by ahmedkaludi** [comment]
This was added as featured. Thanks.
