### ISSUE TITLE
If canonical home URL is https://example.com, https://example.com/amp/ wrongly sets https://example.com/

### ISSUE THREAD

**Issue by KenYN** [ahmedkaludi/accelerated-mobile-pages#1112]
With version 0.9.60 at this line of code:

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/cb89130648d53d29553d5ca26e6e8333dfee2a72/templates/features.php#L3332

My web site (default WordPress, basically) has the home page as https://example.com, but on the AMP index page, I see `<link rel="canonical" href="https://example.com/">`. Google Search Console complains about a "Major content mismatch (Critical issue)" and won't give me an AMP listing for my home page.

For now, I have hard-coded this hack:

    <link rel="canonical" href="<?php 
        if ($amp_url == "https://example.com/")
        {
	    $amp_url = "https://example.com";
	}
	echo $amp_url ?>">

It would be nice to have a proper fix.

**Comment by MARQAS** [comment]
Hi @KenYN 
As far as I know, this is the proper fix only. 
user_trailingslashit function will check if your normal link contains '/' or not if it's present it will add '/' else it won't do anything

Can you share your website URL?

**Comment by KenYN** [comment]
FYI, my web site is https://whatjapanthinks.com - I believe I have the default `.htaccess`, so I think any standard WP install would exhibit this issue.

BTW, I should probably do this instead rather than hardcode the URL:

    <link rel="canonical" href="<?php 
        if ($amp_url == get_home_url() . "/")
        {
            $amp_url = get_home_url();
        }
        else
        {
            $amp_url = user_trailingslashit($amp_url)
        }
        echo $amp_url ?>">

**Comment by Frenchomatic** [comment]
Google puts a / on the end. Why would you want to remove it. 
<img width="634" alt="screen shot 2017-09-12 at 17 08 59" src="https://user-images.githubusercontent.com/8357531/30333453-442608f2-97dd-11e7-81be-5567cff3e7a1.png">
See screenshot

**Comment by KenYN** [comment]
Hmm, perhaps there is another error? This is what I get:

![Validator error](https://i.imgur.com/vR3xQda.png)

However, validators do not report an error.

Let me go back to the default URL... I'm sure I used to get a 403 from Google on https://whatjapanthinks.com/, but I'm no longer sure... I'll have a look at that Product issue too.

**Comment by Frenchomatic** [comment]
Look what google is telling you - your canonical url has a / on it.  it is also telling you that you have a content mismatch (look at your normal and amp pages - would you say they are similar - I wouldn't. Try extending the excerpt length on AMP pages - you will need to modify archive.php and index.php). You should also declare this on the home page (it is missing) and wherever you have a link to the home page put a / on it. So basically on your logo. All in this respect is normal and correct. 

http headers also checkout 200 OK with a / on the url.

**Comment by KenYN** [comment]
@Frenchomatic Ahh, I see what you are saying; I should at least get some images into my AMP front page. Unfortunately I don't use WP's Featured Image stuff, so I'll see what I can do with #1098.

I'll also close this as it's basically a PEBCAK...
