### ISSUE TITLE
WPTouch Mobile theme Goes Blank with the AMP after 0.9.49 Versions.

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1113]
the mobile theme goes blank after sometime when the latest versions are in use.

It works fine with till 0.9.49 version.

Ref: Gistreel.com
<img width="307" alt="screen shot 2017-09-09 at 08 52 08" src="https://user-images.githubusercontent.com/28556545/30238450-9416bb10-9565-11e7-9ba9-359d9438c218.png">

**Comment by Frenchomatic** [comment]
When I goto your site in mobile I see i clearly.
<img width="369" alt="screen shot 2017-09-12 at 17 04 09" src="https://user-images.githubusercontent.com/8357531/30333259-ce8cc478-97dc-11e7-9674-fdc315148994.png">

**Comment by StraitTwistedMe** [comment]
You can preview the mobile theme here... I enabled another theme so my visitors can access the site.

https://www.gistreel.com/?wptouch_preview_theme=enabled

**Comment by ahmedkaludi** [comment]
@StraitTwistedMe Please provide us the login info so we can check and help you solve it. We have to ask because we can't reoccur the issue on our end. Please allow us to help you.

We will keep this ticket active for one more week.

**Comment by MohammedKaludi** [comment]
Closing the ticket for now, feel free to reopen with appropriate details, so we can resolve the issue.
