### ISSUE TITLE
Ad5 code injected twice

### ISSUE THREAD

**Issue by liuyigh** [ahmedkaludi/accelerated-mobile-pages#1116]
0.9.60 on two sites using this plugin. Code as below:

```
<div class="amp-ad-wrapper"><amp-ad class="amp-ad-5"
							type="adsense"
							width=336 height=280
							data-ad-client="ca-pub-xxx"
							data-ad-slot="72xxx08"></amp-ad> </div></header>
<div class="amp-ad-wrapper"><amp-ad class="amp-ad-5"
							type="adsense"
							width=336 height=280
							data-ad-client="ca-pub-xxx"
							data-ad-slot="72xxx08"></amp-ad> </div>
```
Switching to ad3 is a workaround. Please fix.

**Comment by MARQAS** [comment]
@liuyigh Can you tell me which design you are using?

**Comment by liuyigh** [comment]
I didn't know there is a design thing until you asked me. I checked settings, the theme selector says "design two", if that's what you mean.

**Comment by Sejiro-Hiko** [comment]
@liuyigh  I've tested the issue on my end but and everything is working as expected, Can you please look into it again on your end and let us know.

We'll be releasing a new update before 17/Oct/17, If you can update us on this issue we'll be able to release the solution in this update

**Comment by liuyigh** [comment]
Thanks for the update. Problem still presents in 0.9.62:

Code: 

```<header class="amp-wp-article-header ampforwp-title">
	<h1 class="amp-wp-title"> AcelRx: Smarter Pain Relief in the Shadow of Opioid Epidemic	</h1>
	<div class="amp-ad-wrapper"><amp-ad class="amp-ad-5"
							type="adsense"
							width=336 height=280
							data-ad-client="ca-pub-9183261696279727"
							data-ad-slot="2064067402"></amp-ad> </div></header>
<div class="amp-ad-wrapper"><amp-ad class="amp-ad-5"
							type="adsense"
							width=336 height=280
							data-ad-client="ca-pub-9183261696279727"
							data-ad-slot="2064067402"></amp-ad> </div><div class="amp-wp-article-content">
	<!--Post Content here-->
	<div class="amp-wp-content the_content">
```

Screenshot

![screen shot 2017-10-10 at 11 19 32](https://user-images.githubusercontent.com/5641850/31403159-2c0b1664-adad-11e7-871e-bf35c594613b.png)

**Comment by Sejiro-Hiko** [comment]
@liuyigh Thanks for the swift update, We've got the issue and will be resolved in the upcoming update and If you want to implement the solution just remove the following code from: 
accelerated-mobile-pages\templates\design-manager\design-2\elements\title.php at **line no:** 7
<?php do_action('ampforwp_below_the_title'); ?>

REF: 
![c__xampp_htdocs_wordpress_wp-content_plugins_accelerated-mobile-pages_templates_design-manager_design-2_elements_title php accelerated-mobile-pages amp-wp-0 5 schema - sublime text unregistered 2017-10-11 12 44 20](https://user-images.githubusercontent.com/28556545/31426707-09e6d188-ae82-11e7-99dd-ec87b88503b5.png)

**Comment by liuyigh** [comment]
as simple as that. I should have guessed that! Thanks!

**Comment by MohammedKaludi** [comment]
:+1:
