### ISSUE TITLE
Alt tag Improvement (Priority)

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1117]
ampforwp_thumbnail_alt() is causing validation errors.

thumbnails are not generating (missing height and width) in the loop.

Ref: elpasobackclinic.com 
currently I've commented the ampforwp_thumbnail_alt() in index.php and archive.php

**Comment by Frenchomatic** [comment]
Works for me. Please give a correct link to your problem page.

**Comment by MARQAS** [comment]
@Sejiro-Hiko 
Working fine on my end as well and there seems to be no problem in the code. 
Asif please do check properly and check if there's something related to the theme or any other plugin.

**Comment by Sejiro-Hiko** [comment]
@MARQAS  I've checked and there's no plugin or theme compatibility issue.
and the issues still exist.

ref: https://www.elpasobackclinic.com/es/category/athletes/amp/page/47/

again, I've commented the ampforwp_thumbnail_alt() in index.php and archive.php and things are working fine!

**Comment by MohammedKaludi** [comment]
Seems working.
