### ISSUE TITLE
Excerpt Length feature in Design two and Three

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1122]
Excerpt Length feature in Design two and Three

**Comment by Frenchomatic** [comment]
Not sure how to get in contact - I have written to team@magazine3.com .

**Comment by ahmedkaludi** [comment]
@Frenchomatic Yes, that's the best way to get in touch.

**Comment by Frenchomatic** [comment]
Thanks - I sent an email. Some feedback would be appreciated. I don't believe these are customizations but essential fixes as they are at the foundation of the plugin. 


On 15 Sep 2017, at 10:51, Ahmed Kaludi <notifications@github.com> wrote:

@Frenchomatic <https://github.com/frenchomatic> Yes, that's the best way to get in touch.
