### ISSUE TITLE
Body Class for target specific pages

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1123]
Body class for everything. 
Home, page, single, post type, etc etc.

**Comment by Sejiro-Hiko** [comment]
Design 1:
1. "amp_home_body" is added for home_page
2. "archives_body" is added for category & taxonomy

Design 2:
1. "archives_body" is added for category & taxonomy

On Rest, We're already making unique classes.

**Comment by MohammedKaludi** [comment]
Classes are loading as expected, now all the body tags of pages have context specific classes
