### ISSUE TITLE
Allow people to use more than one analytics option, Convert the select into Multiselect.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1124]
Allow people to use more than one analytics option, Convert the select into Multiselect.

**Comment by ahmedkaludi** [comment]
+2

**Comment by Sejiro-Hiko** [comment]
+1

**Comment by MohammedKaludi** [comment]
:+1:  tested and working as expected also it's getting the previously saved data
