### ISSUE TITLE
This application is temporarily over its serving quota. Please try again later.

### ISSUE THREAD

**Issue by mhannigan** [ahmedkaludi/accelerated-mobile-pages#1125]
Where AMP page should load Disqus comments, it displays this message instead. "OVER QUOTA: This application is temporarily over its serving quota. Please try again later."
It isn't like this all the time, but it seems to happen at night. Any page on my site will show you when it is happening.
Https://www.brainchamber.com/amp/

**Comment by MARQAS** [comment]
hi @mhannigan 
Can you share a screenshot or screencast?

**Comment by mhannigan** [comment]
Yes. I have a screenshot, but I'm not sure if it will let me attach it here.

**Comment by mhannigan** [comment]
Oh. From the desktop version I can.  Here is the screenshot
![screenshot_20171004-015419](https://user-images.githubusercontent.com/3442860/31161743-3aec95f0-a8a7-11e7-874f-2098d1e9f23b.png)

**Comment by mhannigan** [comment]
This only happens in the AMP version of the page.

**Comment by ahmedkaludi** [comment]
@mhannigan We recently got the understanding of this issue and we will be fixing this very soon in the upcoming updates. This issue was also referenced on  #1183 

We will fix it in the upcoming releases for sure.

**Comment by ahmedkaludi** [comment]
I'll be fixed in the disqus ticket we have
