### ISSUE TITLE
Analytics and GTM should be able to run simultaneously 

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1126]
When GTM is enabled then Google Analytics is Not Working.

Ref: https://merveozkaynak.com

**Comment by Sejiro-Hiko** [comment]
Tested thoroughly Analytics and GTM are running Simultaneously.

We'll be closing this ticket unless we've got more flags (reports & concerns) related to this issue.

**Comment by MohammedKaludi** [comment]
Closing the ticket for now.
