### ISSUE TITLE
AAWP plugin Compatibility

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1128]
AAWP(Amazon Affiliate for WordPress) plugin is adding the extra CSS which is beyond the limit and giving the validation issues.

Here we'll find this plugin: https://secure.helpscout.net/conversation/429637562/16097/?folderId=1060551

**Comment by Sejiro-Hiko** [comment]
Submit a ticket to the aawp 
Ref: https://aawp.de/kontakt/#wpforms-17207

Let's wait and here from them.

**Comment by Sejiro-Hiko** [comment]
Spoke with the plugin developers, we were supposed to remove the functionality of AAWP from the AMP but found out that they'll be optimizing their code for better compatibility.

**Comment by flowdee** [comment]
FYI: As @Sejiro-Hiko said there will be an update including AMP improvements very soon! I'll keep you updated.

**Comment by MohammedKaludi** [comment]
Closing the ticket, for now, if AAWP guys are not fixing the issue in some time then, feel free to reopen the ticket and we will fix it.

Mohammed Kaludi

**Comment by flowdee** [comment]
FYI: We just released a new version of AAWP (v3.6.6) which includes optimizations for our AMP styles. I suggest upgrading your sites to the latest version asap.

In case some of you still have issues, please get in touch with us directly via: https://getaawp.com/contact/

**Comment by Sejiro-Hiko** [comment]
@flowdee Thank you so much for this.
