### ISSUE TITLE
Multiple debug notices

### ISSUE THREAD

**Issue by ob-ivan** [ahmedkaludi/accelerated-mobile-pages#1130]
Just installed version 0.9.61 of the plugin. Using with version 0.5.1 of AMP plugin.

On my production site I see many notices:

Notice: Undefined index: ampforwp-seo-custom-additional-meta in path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1556

Notice: Only variables should be passed by reference in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-2/elements/bread-crumbs.php on line 71

Notice: Trying to get property of non-object in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-2/elements/bread-crumbs.php on line 82

Will provide any additional info if required.

**Comment by MARQAS** [comment]
Hi @ob-ivan 
Thank you for letting us know this. 
I am looking into it.

**Comment by ob-ivan** [comment]
When on category page https://mysite/category/press-center/news/amp/ --- I get the following notices:

Notice: Undefined variable: selected_cats in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 3533

Notice: Trying to get property of non-object in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 222

Notice: Trying to get property of non-object in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 148

Notice: Trying to get property of non-object in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 172

Notice: Trying to get property of non-object in /path/to/public_html/wp-content/plugins/glue-for-yoast-seo-amp/classes/class-frontend.php on line 316

Notice: Trying to get property of non-object in /path/to/public_html/wp-content/plugins/glue-for-yoast-seo-amp/classes/class-frontend.php on line 338

Notice: Trying to get property of non-object in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 198

**Comment by MARQAS** [comment]
Archive debug notices: #918

**Comment by ob-ivan** [comment]
On a page with post_type=page I also get the following notice:

 Notice: Функция AMP_Post_Template::verify_and_include вызвана неправильно. Path validation for template (/home/web/smithouse.ru/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp//templates/bread-crumbs.php) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. Дополнительную информацию можно найти на странице «Отладка в WordPress». (Это сообщение было добавлено в версии 0.1.) in /home/web/smithouse.ru/public_html/wp-includes/functions.php on line 4138

I don't why this one got translated and how to switch error messages back to English, but this roughly reads as:

Notice: function AMP_Post_Template::verify_and_include was called incorrectly. Path validation for template (/home/web/smithouse.ru/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp//templates/bread-crumbs.php) failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. Please find additional info on "Debugging in WordPress" page. (This message was added in version 0.1) in /home/web/smithouse.ru/public_html/wp-includes/functions.php on line 4138

I didn't modify any of plugins or wordpress core code. I don't know why the double slash (//) in the path. Please ask for any additional info as required to debug this.

**Comment by ob-ivan** [comment]
Well, concerning double slash there is a clear inconsistency in the code:

accelerated-moblie-pages.php:414 defines `AMP__DIR__` constant as `plugin_dir_path(__FILE__) . 'includes/vendor/amp/'` with a trailing slash, while class AMP_Post_Template constructor sets up `$this->template_dir` variable as `AMP__DIR__ . '/templates'` (possibly filtered, possibly not) with additional slash, thus the double slash.

I don't know though, whether this really causes any trouble or simply distracts our attention from the main problem.

**Comment by ob-ivan** [comment]
Also when I turn off "Author Bio in Single" switch at `/wp-admin/admin.php?page=amp_options&tab=2` page and press "Save Changes" button, it is not saved. Instead an alert pops up saying "There was a problem with your action. Please try again or reload the page." Trying again or reloading doesn't help. At the same time the following notice appears in the server's error log:

PHP Notice:  Undefined index: type in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php on line 2962, referer: http://mysite/wp-admin/admin.php?page=amp_options&tab=2

I run an isolated development environment, so I'm 100% positive this notice happens on save.

**Comment by ob-ivan** [comment]
Just updated to 0.9.62. All above mentioned issues persist.

In addition now all pages (both admin and front-end) show:

Notice: Undefined variable: output in /home/web/smithouse.ru/public_html/wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/blurb.php on line 2

This is pretty annoying and I would like it removed as soon as possible.

**Comment by MARQAS** [comment]
Hi @ob-ivan ,
We have not added it in our previous update, it will be added it in this update.

**Comment by ob-ivan** [comment]
It's okay, we're not pressed on time on these.

**Comment by ob-ivan** [comment]
More notices found today on an archive page:

PHP Notice:  Undefined offset: 0 in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 3525
PHP Notice:  Trying to get property of non-object in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 3525
PHP Notice:  Undefined variable: selected_cats in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 3533

**Comment by MohammedKaludi** [comment]
Tested with WP Debug and found no warnings so far. Closing the ticket.

**Comment by AzharKhanplay** [comment]
Notice: Use of undefined constant __DIR__ - assumed '__DIR__' in  /public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 21

**Comment by manniamc** [comment]
Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/accelerated-mobile-pages/includes/welcome.php on line 343
