### ISSUE TITLE
Responsify WP Lazy loading causes blank image (Compatibility)

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1131]
Responsify WP Lazy loading causes blank image (Compatibility)

https://secure.helpscout.net/conversation/430633191/16142/

**Comment by MohammedKaludi** [comment]
this will now add the compatibility for Responsify WP

**Comment by jejakmedia** [comment]
please to theme from mythemeshop.com too :-(, because i'm used it :-(

**Comment by MohammedKaludi** [comment]
@jejakmedia  Can you please tell what theme you are using and what do you suggest for mythemeshop?

**Comment by jejakmedia** [comment]
I use Best Theme & Ribbon theme (Mythemeshop,com), please fix this theme :-(

**Comment by Sejiro-Hiko** [comment]
@jejakmedia Can you please create a new Issue for as this is a closed Issue.

We'll surely add the compatibility for this.
Can you please mail us at team@magazine3.com and If possible send the theme files for **testing purpose**

**Comment by jejakmedia** [comment]
@Sejiro-Hiko  & @MohammedKaludi : I've sent an email & Create Issue.
http://prntscr.com/gxdrl3
