### ISSUE TITLE
Hide AMP by specific Categories performs horribly

### ISSUE THREAD

**Issue by jeichorn** [ahmedkaludi/accelerated-mobile-pages#1133]
This feature
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/872

Needs to be implemented in a different way.  What is happening right is you are grabbing the entire contents of every post you want to filter.  Think about the case where you are blocking 1000 or 10,000, or 100,000 posts.

The case I was seeing was 8k posts being blocked using 50mb/s of network bandwidth.

A work around would be to cache the ids in the transient cache, though you will still blow up if enough posts where blocked.

**Comment by MARQAS** [comment]
Hi @jeichorn 
Can you explain this: "What is happening right is you are grabbing the entire contents of every post you want to filter" ?

Actually, We are not grabbing the content of every post. We are just using their id's to skip them from becoming AMP. 

If you can explain this issue with more details that would really help us to understand and resolve it soon.

**Comment by ahmedkaludi** [comment]
Hey Joshua @jeichorn  

Just wanted to follow up on the last message. I'm personally a fan of Pagely and we would really appreciate your help in this.

**Comment by jeichorn** [comment]
Sorry I missed your last update.

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/d0ac3c0a2dd1e7dfccb3b2ce05e661b30ba14538/templates/features.php#L3254

So while you are only using the post_id, get_posts is loading all of the content to build the post object, so you are still transferring it from the database to php.

It looks like you need to have access to the WP_Query object to in order to limit the returned fields.

https://stackoverflow.com/questions/26420726/limiting-returned-wordpress-fields-from-wp-query-or-get-functions

**Comment by MohammedKaludi** [comment]
Tested and now getting only category ids instead of whole post object.
