### ISSUE TITLE
RSS/Feed URL Error on Smartphone

### ISSUE THREAD

**Issue by array064** [ahmedkaludi/accelerated-mobile-pages#1134]
Hi, 

Looks like there is a bug. If I enable the “Mobile Redirection” feature, then I try to open the RSS/feed URL (http://www.yourdomain.com/feed/) from a smartphone, then the page that appears is not an RSS/feed page, but redirected to a post (which is not an RSS/feed page). This doesn't happen if it opens via a desktop browser.

I have tried to solve this problem by re-saving (refresh) the permalink option on wordpress, and then clearing the cache, but still not working.

CMIIW.

**Comment by MohammedKaludi** [comment]
@array064 thank you for reporting the issue, we have assigned the ticket in this milestone, we will look into the issue and will get back to if any info required.

Thanks,
Mohammed Kaludi

**Comment by array064** [comment]
Wow, thanks.

**Comment by MohammedKaludi** [comment]
@array064 this has been fixed and will be pushed in tomorrow's update.

Issue Fixed and Closing the ticket.
