### ISSUE TITLE
Super Socializer plugin compatibilty (causes Validation issues)

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1139]
Super Socializer plugin compatibility
Conversation here: https://secure.helpscout.net/conversation/443460390/16716/?folderId=1060551

REF: https://wordpress.org/support/topic/critical-errors-in-google-webmasters/#post-9528176

**Comment by pegazee** [comment]
On my end working perfectly, not showing any errors. And already contacted to the user who reports this issue. Waiting for user reply.
