### ISSUE TITLE
Plugin hogging database connections

### ISSUE THREAD

**Issue by Munger** [ahmedkaludi/accelerated-mobile-pages#1140]
I'm running WordPress on Amazon AWS using auto-scaling, load-balanced Amazon Linux Instances with the database on RDS and web root on EFS. When I activate AMP, everything works fine for a short period then I notice that the number of open database connections rises rapidly until mac_connecions is reached, at which point the database stops responding to connections and the site fails. Accelerated Mobile Pages version 0.9.62, Advanced AMP Ads version 1,7 and WordPress version 4.8.2–en_GB.

**Comment by ahmedkaludi** [comment]
That's really strange.  Can you go through the logs and share them with us? It would be really helpful for us to see what might be causing that and how can we fix it

**Comment by Munger** [comment]
I'll try, but I'm not exactly sure what I'm looking for. It's a slow process because I'm still making absolutely sure it isn't another plugin causing the issue. I've temporarily disabled AMP until I've run the site for 24 hours without a hitch. To add further complication I have other plugins that depend upon AMP that I've also had to disable. One is the MonsterInsights AMP module and the other is the Newspaper AMP theme. Once I've fully eliminate everything else I'll reenable AMP and test it for 12 hours before switching on the dependencies. 

Currently it does look like its AMP that is holding connections open, but I'll make absolutely sure.

Tim Hosking

**Comment by Munger** [comment]
How Ahmed. 

I can confirm that the problem only occurs when AMP is enabled. I have to be careful about reenabling it as it takes out our live site for up to twenty minutes, which is roughly how long it takes me to clear out the plugins, reboot the web servers and database instance to clear the connections. 

Are you by any chance using mysql_pconnect() to create persistent connections? I get a feeling that the code is throwing an exception before the connection is closed and simply retries whatever it is it is doing and opening another connection. 

I'm trying to think of things that would cause our site to behave differently. One thing that springs to mind is that the web root lives on EFS mounted via NFSv4. This is significantly slower than block storage, but is required as we always have at least two Apache servers sharing it, a number that increases in response to sever load. We overcome that by using opcache and CloudFront to minimise disk I/O. However, if your code is timing out waiting for a local page to be served that could potentially cause issues. 

Tim Hosking

**Comment by ahmedkaludi** [comment]
Hi Tim @Munger

That's strange. Have you tried checking server logs, Apache logs or PHP logs? There has to be something there..

If you can find the reason then we can immediately work on it and fix them.

**Comment by ahmedkaludi** [comment]
I'm sorry, I close it by accident. Please see my previous message.

**Comment by Munger** [comment]
I'll have to wait until the site is quiet because it *will* crash our live site. If I knew what I was looking for in the logs it might help. 

Tim Hosking

**Comment by Munger** [comment]
Hello again. 

I reeabled the plugin last night and this morning the database was hung due to excessive connections. There were no new messages in the php error log. 

Tim Hosking

**Comment by Munger** [comment]
Is there any way you could send me a version with extra debug messages, particularly wherever the code opens or closes a database connection? Once I see how and where you have gone that I can add more to get some idea of what is going on. I really can't leave the plugin enabled and unattended on a live site, but if I'm monitoring the log it will give me a chance to disable it whenever it looks like it's going awry. 

Tim Hosking

**Comment by Munger** [comment]
This is still an issue. What's worse is it's also impacting another site that runs different plugins. Indeed, that site is running nginx and php-fpm. 

Tim Hosking

**Comment by ahmedkaludi** [comment]
@Munger I really don't know what might be causing this. Can you test the new 0.9.63 version? as we have fixed a performance issue in it.

**Comment by ahmedkaludi** [comment]
@Munger Any Update on this? Please check and let me know so that we can understand and help you fix it.

**Comment by Munger** [comment]
I’ve had it disabled for some time now as it brings the server to its knees. I need a debug version that outputs more log messages to make any reasonable attempt at getting to the bottom of it. My guess is that it’s taking a long time processing whatever it is it’s doing. I can’t replicate this on on a test server because I can’t add any realistic load. 

Currently I’m looking at reintroducing a varnish cache in front of each server to alleviate the problem. I can confirm that the problem only rears it’s head when the following three plugins are enabled:

AMP for WordPress
Advanced AMP Ads
AMP Newspaper Theme.

I’ve discarded about 5 other plugins to clean the server a little. I’m using memcached to cache DB queries and opcache to take some load from php-fpm.  

Tim Hosking

**Comment by mayanksharma9033** [comment]
Hi @Munger,

We have Memcached, PHP-fpm and varnish cache in our plugin, but we didn't get this type of issue.

**Comment by ahmedkaludi** [comment]
@Munger You can use NewRelic and their monitoring is the top class. You can use that to understand who's making the most load and what's the reason behind it. They give the data for each and every single thing. Please use that and give that to us. We will be happy to improve upon it. 

Till then, I have no option but to close this ticket.

You are welcome at anytime. You can also contact on team@magazine3.com - I will be happy to work with you or anyone who can help us solve this.
