### ISSUE TITLE
Page builder for number of pictures and Gallery

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1142]
Ref: https://secure.helpscout.net/conversation/437625501/16425/?folderId=1060551

## Steps
- [x] Multiple Image selection option from WP Media Lib

- [x] Make the Gallery Module

- [ ] Front End of it.

**Comment by MohammedKaludi** [comment]
http://take.ms/d6hOq  Gallery Tiled option is working, but Slider Gallery is not working, no gallery is visible, also when not in used lightbox.js is also loading.

**Comment by ahmedkaludi** [comment]
**Major Bug:** The Images does not save properly, see:  http://take.ms/XASe3
