### ISSUE TITLE
Cannot redeclare mysql2date

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1144]
Log Error: [Mon Sep 25 18:42:28 2017] [error] [client 85.140.3.174] PHP Fatal error: Cannot redeclare mysql2date() (previously declared in /var/www/www-root/data/www/site.com/wp-includes/functions.php:26) in /var/www/www-root/data/www/site.com/functions.php on line 42

Let's change it with our prefix so it doesn't conflict.
REF: https://wordpress.org/support/topic/problems-after-installing-0-9-62/

**Comment by Internapse** [comment]
Thank you for addressing promptly. Unfortunately this issue caused my contact forms to not work after upgrading to the latest version of this plugin. For now, the only solution I see is to downgrade the plugin.

**Comment by Sejiro-Hiko** [comment]
Hi @Internapse  ,

I've tried to recreate the issue on my end but unfortunately unable to do so, can you please try to change the following code in **accelerated-mobile-pages\pagebuilder\amp-page-builder.php**
at **line number 161**:
**from** : `require_once "functions.php";`
**to** : `require_once AMP_PAGE_BUILDER.'functions.php';`

**Comment by MohammedKaludi** [comment]
:+1
