### ISSUE TITLE
validation for session in php

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1146]
Notice: A session had already been started - ignoring session_start() in /wp-content/plugins/accelerated-mobile-pages/includes/redirect.php on line 62

replace this:
session_start();

for:

// make the use of sessions possible.
if (!session_id()) {
    session_start();
}
or:

if(empty($_SESSION))
    session_start();

REF: https://wordpress.org/support/topic/validation-for-session-in-php/

**Comment by ajeetku** [comment]
This issue resolved #1158
For more details see:  7f41707102f233db36d0fae270e635fc09a922d7
