### ISSUE TITLE
Notification causes validation error.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1147]
When enabled Notifications on design 2 (maybe other designs too), it cause validation issues. 
"The tag 'amp-user-notification' requires including the 'amp-user-notification' extension JavaScript."

User has reported and I have checked in my localhost too, it's a valid one.

Ref: https://wordpress.org/support/topic/amp-validation-fail/

**Comment by pegazee** [comment]
On my end working perfectly, not showing any errors. And I had contacted to the user who reports this issue. Waiting for user reply.

**Comment by keyuramins** [comment]
I have the same error that emerged today in the search console and upon checking it in for AMP validation, it actually provides me this error:
The tag 'amp-user-notification' requires including the 'amp-user-notification' extension JavaScript.

It happens on this page - https://jenascarpetcleaning.com.au/amp/

Please help us to resolve this error.
Cheers
