### ISSUE TITLE
Just tried version 0.9.62

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1155]
Just tried Version 0.9.60 **(now 0.9.62)**  Here is a list of outstanding issues.  All of my other tickets can be closed if necessary to save having confusion. 

Here is the test site: `saleking.com` (you have the login details for it already). It is using design 2.

It works as before but it doesn’t address many of the issues I have listed over the past weeks on both the forum and in github.

1. Static home page is using different css and has a different html structure to other pages (no reason I can see as to why if you are using the custom editor). It means the home page whatever you do is always going to look slightly different. Should it not be using the same code as single.php if it is a static home page? (**I put up some workaround code on the wordpress forum**). 

2. The featured image for a static home page is not the one given in the structured data. - see #1118 

3. The featured image on a static home page is not rendered in the same way using screen sets as featured images are rendered on other posts/pages.

4. H1 should be using the same css on whatever page you are on. If using a different class for .archive_ title then by default it should be the same as .page_title. A minor detail. For example, this is using an H3 for the title but it should be an H1.  H2 should not be following H3. 

`saleking.com/tag/coppell-dentist/amp/`

5. The logo is not using the alt tag if it has one and still just uses the site title.

6. The archive description is not being rendered onto a blog posts page.

`saleking.com/orthodontics-braces/amp/`

7. The blog posts page title is not being rendered onto the page. It needs to be using this get_the_title(get_option(‘page_for_posts’, true));

`saleking.com/orthodontics-braces/amp/`

8. A new one – breadcrumbs being added and not wanted. Also incorrectly points to /amp and not /amp/ - looks like you change that in the AMP admin section but it doesn't correct the url anyway.

9. No way in admin to remove the categories link from AMP posts (feature request).

10. Google advises that a structured description attribute is given on an AMP page. This could by default be set to the meta desription in class-amp-post-template.php - see #1118 It could be resolved here.

11. Gravatar code still being added to the page even though it is set to not display in WP admin. Instead css is being used to set display:none;

12. /blog/amp/page/2/ etc structured data @id is incorrect as it misses page number .

13. Additonal spaces are being applied to <title> bla bla </title> on static home page and blog posts page – may be an interaction with Genesis.

14. Additional spaces are being added into H1 tags on pages and posts  ` <h1> my title </h1>`

15. There is an issue with features.php - if no blog is defined then the structured attribute for person on a static home page is NULL. This is because the test is for archive only and it is not testing for a static home page. Bizarrely the code around that test is also running twice for a static home page. Easy to see if you put a couple of echoes in and print them to the screen.

**Comment by ahmedkaludi** [comment]
@Frenchomatic I am extremely thankful for this feedback and I want to act on this. Having said that, Give us some time. In the next two months, we will be only focusing in fixing the GitHub issues.

**Comment by Frenchomatic** [comment]
I put this up so you can see that the issues are still present.  I have added urls on the test site so you can see 1-13 them individually.  I will close the older post.

**Comment by Frenchomatic** [comment]
#1063 The image issue point 1 is solved with the latest commit. A solution has been offered also for those that want to have a static home page using the same css and html structure as other pages.

**Comment by ahmedkaludi** [comment]
NOTE TO DEVELOPERS: The more info about this on Helpscout: https://secure.helpscout.net/conversation/440017405/16524/?folderId=1060551

**Comment by MARQAS** [comment]
@Frenchomatic 
Some issues(listed below) have been resolved in the previous update. Can you confirm it?

2. The featured image for a static home page is not the one given in the structured data. - see #1118

3. The featured image on a static home page is not rendered in the same way using screen sets as featured images are rendered on other posts/pages.

8. A new one – breadcrumbs being added and not wanted. Also incorrectly points to /amp and not /amp/ - looks like you change that in the AMP admin section but it doesn't correct the url anyway.

10. Google advises that a structured description attribute is given on an AMP page. This could by default be set to the meta desription in class-amp-post-template.php - see #1118 It could be resolved here.

11. Gravatar code still being added to the page even though it is set to not display in WP admin. Instead css is being used to set display:none;

12. /blog/amp/page/2/ etc structured data @id is incorrect as it misses page number .

13. Additonal spaces are being applied to <title> bla bla </title> on static home page and blog posts page – may be an interaction with Genesis.

14. Additional spaces are being added into H1 tags on pages and posts <h1> my title </h1>

**Comment by Frenchomatic** [comment]
I was just about to respond - here we go. I have marked out those which are solved. 

Just tried Version 0.9.63. Here is a list of outstanding issues. All of my other tickets can be closed if necessary to save having confusion.

Here is the test site: saleking.com (you have the login details for it already). It is using design 2.

1. Static home page is using different css and has a different html structure to other pages (no reason I can see as to why if you are using the custom editor). It means the home page whatever you do is always going to look slightly different. Should it not be using the same code as single.php if it is a static home page? (I put up some workaround code on and another github ticket). - RECOGNIZE THIS IS AN OPINION.

2. The featured image for a static home page is not the one given in the structured data. - see #1118
**SOLVED**

3. The featured image on a static home page is not rendered in the same way using screen sets as featured images are rendered on other posts/pages. **SOLVED**

4. H1 should be using the same css on whatever page you are on. If using a different class for .archive_ title then by default it should be the same as .page_title. A minor detail. For example, this is using an H3 for the title but it should be an H1. H2 should not be following H3.

 saleking.com/tag/coppell-dentist/amp/

5. The logo is not using the alt tag if it has one and still just uses the site title.

6. The archive description is not being rendered onto a blog posts page.

http://www.saleking.com/articles-dentistry/amp/

7. The blog posts page title is not being rendered onto the page. It needs to be using this get_the_title(get_option(‘page_for_posts’, true));

http://www.saleking.com/articles-dentistry/amp/

8 . Breadcrumb for home incorrectly points to /amp and not /amp/ The switch in AMP to turn it off works so for me it is **SOLVED**


10. No way in admin to remove the categories link from AMP posts (feature request).

11. Google advises that a structured description attribute is given on an AMP page. This could by default be set to the meta desription in class-amp-post-template.php - see #1118 It could be resolved here - **SOLVED**

12. Gravatar code still being added to the page even though it is set to not display in WP admin. Instead css is being used to set display:none; **SOLVED**

13. /blog/amp/page/2/ etc structured data @id is incorrect as it misses page number . **SOLVED**

14. Additonal spaces are being applied to <title> bla bla </title> on static home page and blog posts page – may be an interaction with Genesis. **SOLVED**

15. Additional spaces are being added into H1 tags on pages and posts <h1> my title </h1> **SOLVED**

16. There is an issue with features.php - if no blog is defined then the structured attribute for person on a static home page is NULL. This is because the test is for archive only and it is not testing for a static home page. Bizarrely the code around that test is also running twice for a static home page. Easy to see if you put a couple of echoes in and print them to the screen. - I HAVE NOT BEEN ABLE TO TEST THIS YET

**Comment by Frenchomatic** [comment]
So collecting together what I have left for version 0.9.63.

1. Static home page is using different css and has a different html structure to other pages (no reason I can see as to why if you are using the custom editor). It means the home page whatever you do is always going to look slightly different. Should it not be using the same code as single.php if it is a static home page? (I put up some workaround code on the wordpress forum). - MY OPINION & I OFFERED A SOLUTION.


2. H1 should be using the same css on whatever page you are on. If using a different class for .archive_ title then by default it should be the same as .page_title. A minor detail. For example, this is using an H3 for the title but it should be an H1. An H2 should not be following H3.

http://www.saleking.com/tag/coppell-dentist/amp/

3. The logo is not using the alt tag if it has one and still just uses the site title.

4. The archive description is not being rendered onto a blog posts page.

http://www.saleking.com/articles-dentistry/amp/

5. The blog posts page title is not being rendered onto the page. It needs to be using this get_the_title(get_option(‘page_for_posts’, true));

http://www.saleking.com/articles-dentistry/amp/

6. Breadcrumb for home link incorrectly points to /amp and not /amp/ 

http://www.saleking.com/the-difference-between-canker-sores-and-cold-sores/amp/

7. No way in admin to remove the categories link from AMP posts (feature request).

8. A new one - This post was last modified on June 29, 2017, 2:18 pm . How can this be turned off. 


9. There is an issue with features.php - if no blog is defined then the structured attribute for person on a static home page is NULL. This is because the test is for archive only and it is not testing for a static home page. Bizarrely the code around that test is also running twice for a static home page. Easy to see if you put a couple of echoes in and print them to the screen. - I HAVE NOT BEEN ABLE TO TEST THIS YET

**Comment by MARQAS** [comment]
8. It can be turned off from AMP Options Panel i.e., Design->Single->Show Post Modified Date

**Comment by MARQAS** [comment]
7. You can turn it off with Archive support option.

**Comment by Frenchomatic** [comment]
7. On the test site I have it is turned on but doesn't show and I have archive support turned on. 

`http://www.saleking.com/articles-dentistry/amp/
`
 8. yes I see that now. sorry.

**Comment by MARQAS** [comment]
7. So you want to keep the archive support enabled but don't require categories link in posts?

**Comment by MARQAS** [comment]
2, 3, 5, 6:  Done

**Comment by MARQAS** [comment]
9. Can you test it properly and show me the screenshot if possible?
I just checked on your dev site and it is working fine there as well.

**Comment by MARQAS** [comment]
4. Can you explain this a bit more? Archive description on the Blog page?

**Comment by Frenchomatic** [comment]
http://www.saleking.com/articles-dentistry   -> title is Articles – Dentistry

http://www.saleking.com/articles-dentistry/amp/  -> no title

There is no h1 title title on the page. 

Forget about the archive description. I worked out that is a genesis thing. I have to copy my archive description into the description box as well.

**Comment by MARQAS** [comment]
7. Sorry, I didn't understand this at that time. You are talking about the Posts links on the title of the post on the blog, right? this: http://take.ms/0rflpY 

I just discussed this with my Team and we don't think that this will be useful for AMP especially in our Designs. 
Even if we made changes in it,  there is a huge probability that our users will not be able to catch this thing up very soon and can be panicked about it. (You know this thing better than me)
We are trying our best to make it simplest as possible. So the users who don't even have little bit programming knowledge can understand it. 

If you can explain me the use cases of it and also some examples, I will discuss this again with my team to sort it out.

**Comment by MARQAS** [comment]
1. I will look into it in #1175

**Comment by Frenchomatic** [comment]
7. No I mean the categories link on a blog page itself in the top right hand corner. 

http://www.saleking.com/the-risks-of-oral-piercing/amp/

It says categories: dentistry . What I am asking is how is that turned off?  I know how to code it out but is it an option in the admin panel. The reason is simple - you have a blog with only one category.  Your blog posts page is effectively the category.

**Comment by MARQAS** [comment]
It is connected with archive support option. Disable the archive page support option from the General settings of AMP, the links will go away

**Comment by Frenchomatic** [comment]
Yes but if I do that, I think you can't have tags. 

On 12 Oct 2017, at 15:44, Mohammed Razzaq <notifications@github.com> wrote:

It is connected with archive support option. Disable the archive page support option from the General settings of AMP, the links will go away

**Comment by MARQAS** [comment]
Hmm, you're right. 
I will make a separate option for it then.

**Comment by Frenchomatic** [comment]
Well done Marqas - given some of the forum feedback is tunring negative the next version needs to be really watertight at the core level and the basic wordpress setup scenarios. It is more important than additional features and things like that.

**Comment by ahmedkaludi** [comment]
@Frenchomatic I totally agree, we will try our best to keep up to your level of expectations.

 We will be releasing 0.9.64 today, I am closing this ticket. Please let us know what are the improvements you see in the next thread. Because extremely hard to tackle 10 different issues in one thread from a development point of view. 

I would like to request you one thing, Please make a separate ticket for each issue, we will have better clarity internally and can achieve far more as well


Thank you again, you have been very helpful in improving this plugin.

**Comment by Frenchomatic** [comment]
It has been a pleasure to help.
