### ISSUE TITLE
Error after 0.9.62 in Breadcrumbs

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1159]
Strict Standards: Only variables should be passed by reference in /homepages/19/d379746342/htdocs/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-2/elements/bread-crumbs.php on line 71

https://secure.helpscout.net/mailbox/cfb9786cbb6b9b7c/1060551/

**Comment by JuanJueves** [comment]
I´ve just discovered that the problem also plays back with the previous version. I've replaced it to debug the error for the moment, but nothing, it still appears when you enter an amp link of any post.
![amp problem](https://user-images.githubusercontent.com/32333559/30918262-56996656-a39e-11e7-88b1-6e9b095b9d83.jpg)

**Comment by MARQAS** [comment]
Resolved in #1130
