### ISSUE TITLE
embedly oembed  support in wordpress

### ISSUE THREAD

**Issue by mayanksharma9033** [ahmedkaludi/accelerated-mobile-pages#1160]

**Comment by zabi332** [comment]
One more user is asking for this feature.

Ref: https://secure.helpscout.net/conversation/464357752/18106?folderId=1060551

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
