### ISSUE TITLE
Notice on activation

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1161]
activating your plugin (debug=TRUE)

( ! ) Notice: Undefined variable: output in /wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/blurb.php on line 2

REF: https://wordpress.org/support/topic/notice-on-activation-2/

**Comment by davideprevosto** [comment]
Fast fix (don't know the logic behind scripts)

> blurb.php:2

```
if (empty($output)) {
    $output = '';
}
```

**Comment by ajeetku** [comment]
This issue has resolve in 52da3a1 commit
