### ISSUE TITLE
Page Builder causes Incompatibility with the Divi theme

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1162]
Since I have installed AMP for WP, I cannot edit any page anymore.
In the post edit screen, I get a popup saying:

Divi Builder Timeout
Oops, it looks like the Divi Builder failed to load. Performing the following actions may help solve the problem.

1. You are using third party plugins. Try disabling each plugin to see if one is causing a conflict.

The problem disappears if I disable the AMP for WP plugin.

REF: https://wordpress.org/support/topic/incompatibility-with-the-divi-theme/

**Comment by ahmedkaludi** [comment]
This only happens with Divi version 3.0.76, the user has also sent us the copy on team@magazine3.com

Also, @ajeetku when you are moving to waiting, you must write some reference.

**Comment by ahmedkaludi** [comment]
**UPDATE**
We have the staging info from this user. The issue is there, we will sit together and troubleshoot it.

https://secure.helpscout.net/conversation/442504987/16638/?folderId=1060556

**Comment by ahmedkaludi** [comment]
UPDATE:
Pushing this for the next version.

**Comment by MohammedKaludi** [comment]
UPDATE: 
Need to update the TINYMCE code and will take some time to test, so moving this for the next version.

I'm sure by end of next week we will have time to fix it and test properly.

**Comment by MohammedKaludi** [comment]
Working smoothly. Closing the ticket.
