### ISSUE TITLE
AMP Page Builder and HTTPS

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1164]
**1**
You are loading image like:
http:\/\/via.placeholder.com\/150x150
so our websites are not fully loaded via HTTPS anymore, so please remove this strict HTTP or use https://via.placeholder.com/350×150

**2** I do not want to use the AMP Page Builder and it is set to off in /wp-admin/admin.php?page=amp_options&tab=2 so why this builder still loaded when I edit a page?

REF: https://wordpress.org/support/topic/amp-page-builder-and-https/

**Comment by MohammedKaludi** [comment]
:+1:
