### ISSUE TITLE
v 0.9.61 Introduces New Conflict with another Plugin (WP/LR Sync)

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1165]
After updating to the latest AMP for WP (0.9.61) I’ve run into a new conflict with another plugin (WP/LR Sync). The two had been playing nicely before now.

Rolling back to AMP for WP 0.9.60 resolves the issue, so it appears to be something new with 0.9.61. Nothing in the new changelog leaps out at me for causing the conflict which prevents WP/LR Sync from connecting to WP.

AMP for WP 0.9.61
WP/LR Sync 3.2.6
WP 4.8.1

REF: https://wordpress.org/support/topic/v-0-9-61-conflict-after-latest-amp-for-wp-update/#post-9510923

**Comment by MohammedKaludi** [comment]
Issue Explanation from the user:

> There’s nothing showing up in PHP error logs, but while AMP for WP is activated then WP/LR Sync can no longer authenticate and log in. Disabling AMP for WP resolves the issue immediately. This is a new issue–they’ve previously worked without issue together.

**Comment by Sejiro-Hiko** [comment]
asked the user to test it with the latest version and the behaviour of the issue.
https://wordpress.org/support/topic/v-0-9-61-conflict-after-latest-amp-for-wp-update/#post-9626778

**Comment by ahmedkaludi** [comment]
No feedback, so closed.
