### ISSUE TITLE
Content gets clipped when multiple ‘blockquotes’ are used in article

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1166]
I’m using the latest version of the plugin (0.9.61) and I just discovered that the AMP content gets clipped if there are more than one blockquotes. It appears that the AMP content removes all content between first and last blockquote. For example, compare the content at these two links

Web/desktop version: http://www.opindia.com/2017/09/repeat-a-lie-a-thousand-times-and-it-becomes-the-truth-this-wsj-columnist-tells-us-how/

AMP version: http://www.opindia.com/2017/09/repeat-a-lie-a-thousand-times-and-it-becomes-the-truth-this-wsj-columnist-tells-us-how/amp/

Could you please resolve it at the earliest?

The page I need help with: http://www.opindia.com/2017/09/repeat-a-lie-a-thousand-times-and-it-becomes-the-truth-this-wsj-columnist-tells-us-how/

REF: https://wordpress.org/support/topic/content-gets-clipped-when-multiple-blockquotes-are-used-in-article/#post-9512896

**Comment by MARQAS** [comment]
It's working fine on my end. 
Asked the user to contact us

**Comment by ahmedkaludi** [comment]
UPDATE:
We contacted user ( https://secure.helpscout.net/conversation/446604833/16935/?folderId=1060556 ) about the issue and have got no positive response.

We will keep this for another week, if no positive response or same issue, then we have to close it.

**Comment by MARQAS** [comment]
Contacted the user again, if there is no response till the end of this week then we can close this ticket.

**Comment by ahmedkaludi** [comment]
Twitter video embed support added.

We are still not sure why the content was clipped into two but it's possible that it might be the reason.
