### ISSUE TITLE
Blog Posts shows hidden in this use case

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1167]
Custom front page – ON, built homepage entirely with the Custom AMP Editor and is set in the dropdown selector of AMP Custom front page.

The Blog page is not set to hidden and still displays an empty page while trying to load it’s AMP version there.

REF: https://wordpress.org/support/topic/amp-blog-posts-page-isnt-showing/#post-9506252

**Comment by MohammedKaludi** [comment]
Closing the ticket, for now, if the issue persists, please open the ticket.

**Comment by Sejiro-Hiko** [comment]
Issue has been resolved stated by the customer who reported this.
Ref: https://wordpress.org/support/topic/amp-blog-posts-page-isnt-showing/#topic-9497089-replies
