### ISSUE TITLE
meta description is not being used for structured data

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1168]
The meta description is not being used for structured data. Needs something like this either in

class-amp-post-template.php

$desc = esc_attr(ampforwp_generate_meta_desc());
'description' => $desc,

or in features.php 

$desc = esc_attr(ampforwp_generate_meta_desc());
$metadata['description'] = $desc;

REF: https://wordpress.org/support/topic/meta-description-is-not-being-used-for-structured-data/

**Comment by MARQAS** [comment]
Done in #1048
