### ISSUE TITLE
Not working perfectly for me.

### ISSUE THREAD

**Issue by umerkakar** [ahmedkaludi/Accelerated-Mobile-Pages#117]
Hi,
The plugin not work for me alone. I have to use another AMP plugin with it to get it worked. (https://github.com/automattic/amp-wp) And when we are on an amp page. All link on the page are still non amp that should be amp.

With use of that plugin URL become /amp/ and without it your plugin settings and etc not loads.

jobsingcc.com this is my project.

**Comment by ahmedkaludi** [comment]
@umerkakar are you still having these issues? Can you please be specific with the issues so we can understand and improve?

**Comment by khaledMohammed000** [comment]
I have seen that your project is looking fine on AMP pages 👍 

@umerkakar Yes sir we need https://github.com/automattic/amp-wp for our plugin to work and also AMP pages need /amp in the URL  

Please Update to the latest version to benefit better :)
