### ISSUE TITLE
Image unavailable

### ISSUE THREAD

**Issue by BalajiInfoSoft** [ahmedkaludi/accelerated-mobile-pages#1170]
Theme Used: Schema by MTS
Image not displayed when lazy load is active in theme options.
1 more
There is no amp support for categories and tag pages
All pages and posts are in amp but when i click on any of the categories like this one [https://iamsher.com/sad-sher-o-shayari/](url)  or tags https://iamsher.com/sher/sher-o-shayari/ the site structure changes and seems that i got redirected to some other site.

**Comment by Sejiro-Hiko** [comment]
@BalajiInfoSoft  Have you enabled the Archive Support?

I hope this will resolve your categories and tags issue.
Please let us know as soon as you tested it.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by BalajiInfoSoft** [comment]
AMP not working with BE theme.

website : https://shertheprotector.com


Loved your recent updates it's working for Archive,  categories and tags
page.
