### ISSUE TITLE
Compatibility with oEmbed of Youtube

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1171]
Compatibility with oEmbed of Youtube, two reports so far, we need to test.
https://secure.helpscout.net/conversation/434910935/16332/?folderId=1060551

**Comment by ahmedkaludi** [comment]
We need to test this.

**Comment by pegazee** [comment]
Tested on my end, Working perfectly without any errors.

**Comment by MohammedKaludi** [comment]
:+1:
