### ISSUE TITLE
Caption Support in image Gallery [PULL REQUEST]

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1172]
Caption Support in image Gallery. The solution is already in the Pull request, we need to test it and merge it: https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/1136

**Comment by Sejiro-Hiko** [comment]
Incomplete Solution.

**Comment by MohammedKaludi** [comment]
Closing this ticket, more info at #1136
