### ISSUE TITLE
Mobile redirection must not have an end point but  it should work as excpected

### ISSUE THREAD

**Issue by mayanksharma9033** [ahmedkaludi/accelerated-mobile-pages#1173]
User from mobile device (mobiles and tables screens lower than 1024px) acess the website diretly to urls without /amp/ then site ALSO uses your theme template but URL still original... not /amp/ in slug:

Not only redirection is needed, also few changes like canonical url, urls on social buttons, every place where url shows, etc

We need this redirection because our responsive template is more than 3x slower than AMP theme and google loves speed so we can test this redirection :)

Reference ticket  https://secure.helpscout.net/conversation/424875394/15917/?folderId=1060551

**Comment by ahmedkaludi** [comment]
Take over was the feature in which we had this
