### ISSUE TITLE
Sorting out design #2 – static front page [TESTING]

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1175]
We just need to test. @pegazee and I talked about this. 

Code, instructions and the reasons are already at https://wordpress.org/support/topic/sorting-out-design-2-static-front-page/

**Comment by Frenchomatic** [comment]
This specific issue forms part of this #1155 point 1.

**Comment by pegazee** [comment]
Regarding the Featured Image issue on the Frontpage, solved in #1063. And for the rest of the code, We've decided to keep as it is.

**Comment by Frenchomatic** [comment]
I see you have solved the scrsets etc but why would you want to use different html and css for a static home page using the custom editor to any other page?  It doesn't make sense. The featured image ends up looking different to any other page with padding around it.

**Comment by MARQAS** [comment]
If we are testing it and planning to made some changes, then consider other Designs as well
