### ISSUE TITLE
amp-auto-ads for sites with RTL support ON

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1176]
Links and screenshot available at: https://wordpress.org/support/topic/how-to-add-code-after-the-tag/page/2/#post-9537038

my site link

my current set up to amp-auto-ads is

1- amp-auto-ads ad code after the <body> tag.only in single.php
wp-content / plugins / accelerated-mobile-pages / templates / design-manager / design-1/single.php
screen shot of after body amp-auto-ads

2- amp-auto-ads script in the <head>
setting / advanced setting / enter HTML in header

3 – amp RTL Support ON .

here are the result:

screenshot of amp-auto-ads with RTL Support ON

………….

but when i turn RTL suppourt off
the AD alignment is perfect but my content is mixed.
screenshot of amp-auto-ads while RTL Support OFF

so please fix amp-auto-ads for sites with RTL support ON, so we could have perfect content and amp-auto-ads together.

**Comment by malwareoverflow** [comment]
@MohammedKaludi  can you please suggest me how can I edit html inside body of amp pages? I have been searching for long time but no luck.
