### ISSUE TITLE
Activation: Lots of PHP notices by Slava Abakumov (@slaffik)

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1177]
Are we still having these? 

- [x]  https://wordpress.org/support/topic/lots-of-php-notices-5/

- [x]  https://wordpress.org/support/topic/front-end-php-notice-on-a-page/

- [x] https://wordpress.org/support/topic/front-end-php-notice-on-a-post/

- [x] https://wordpress.org/support/topic/template-and-breadcrumb-error-after-update/#post-9496947

**Comment by MARQAS** [comment]
Resolved in #966 #1130 #1159 
Moving it to the Review Board

**Comment by MohammedKaludi** [comment]
Reviewed the tickets, no warnings so far and looks good.
