### ISSUE TITLE
Disqus implementation causes over quota sometimes.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1183]
Can we do a better implementation...... 
![celeb-wink-12](https://user-images.githubusercontent.com/16532359/31045473-7afde146-a602-11e7-88f2-c4d0fb3b26e3.jpg)

**Comment by ahmedkaludi** [comment]
This one is tricky for sure. We'll tackle this in the next week.

**Comment by pegazee** [comment]
- [ ] There is also an issue for height, it's too small and not scrollable on iPhone devices. 

User reported: https://secure.helpscout.net/conversation/449303253/17096/?folderId=1060556

**Comment by zabi332** [comment]
one of our users reported this "Over Quota"  issue.

ref: https://secure.helpscout.net/conversation/452492336/17249/

**Comment by ahmedkaludi** [comment]
The over quota sometime caused by our API since we deliver hundreds of thousands of requests every day.

Height issue has been resolved

**Comment by gauravanni** [comment]
someone fixed this issue

**Comment by LinhMai90** [comment]
tôi đã gặp phải lỗi này, làm ơn hãy khác phục nó
This application is temporarily over its serving quota. Please try again later.

https://automexico.com/conduccion/evitar-ser-victima-de-los-montachoques-aid10724/amp

**Comment by LinhMai90** [comment]
I've encountered this error, please fix it
This application is temporarily over its serving quota. Please try again later.
https://automexico.com/conduccion/evitar-ser-victima-de-los-montachoques-aid10724/amp

**Comment by LinhMai90** [comment]
![image](https://user-images.githubusercontent.com/31911781/103985270-3384af80-51bb-11eb-80d2-5cca40f87155.png)
