### ISSUE TITLE
load_plugin_textdomain returns false

### ISSUE THREAD

**Issue by davideprevosto** [ahmedkaludi/accelerated-mobile-pages#1184]
Hi there,
I am trying to use POT file, without success.
I'd create an italian translation of POT file, and save it:

`/app/public/wp-content/plugins/accelerated-mobile-pages/languages/accelerated-mobile-pages-it_IT.mo`

but translation doesn't works. I also tryed to save .mo file in `/app/public/wp-content/languages/plugins/accelerated-mobile-pages-it_IT.mo` without success.

thank you

**Comment by ahmedkaludi** [comment]
@davideprevosto To be very honest, I haven't done translation ever. And the translation docs are very less and confusing. 

What can we do to solve this. If anyone knows localization better, then please help us. @nicholasgriffintn @leoosa @frechomatic

**Comment by davideprevosto** [comment]
@ahmedkaludi I am available to debug with you, I think it should be an interesting feature.

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi I would have to take a look, but it's probably just a simple error such as the .mo file not being readable.

@davideprevosto, if you could check that the .mo file is readable, that would be a quick debug to make sure, if that's not it then we would have to debug further.

**Comment by davideprevosto** [comment]
@nicholasgriffintn .mo file is readable

**Comment by nicholasgriffintn** [comment]
@davideprevosto Sorry, just checking as it is a common issue that the file isn't readable by Wordpress.

I'll see if I can have a look.

**Comment by nicholasgriffintn** [comment]
@davideprevosto If it is possible, could you link to your translation file? It would help me and others to debug this.

**Comment by MohammedKaludi** [comment]
@davideprevosto ping

**Comment by davideprevosto** [comment]
Hi @MohammedKaludi,
I apologize for delay. 

- I updated your plugin to the last version: 0.9.65.1
- I'd create a new spanish file with PoEdit, based on your .pot file
- I saved the new file in this way: `./wp-content/languages/plugin/accelerated-mobile-pages-es_ES.mo`
- did the same for an italian file and save it: .`/wp-content/languages/plugin/accelerated-mobile-pages-it_IT.mo`

NOW, it works like a charm.

**Comment by mayanksharma9033** [comment]
Hi @davideprevosto,
That's really great.

@MohammedKaludi ,
Moving this ticket to review & Q/A  Section
