### ISSUE TITLE
Grab the first image instead of post thumbnail for featured image

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1189]
Grab the first image instead of post thumbnail for featured image

2 users have already requested and I think there is a percentage of users who have this use case.

https://wordpress.org/support/topic/show-first-image-instead-of-post-thumbnail/

**Comment by MARQAS** [comment]
If we take the first image as the featured image, Then what about those who don't want the featured image?

I guess we should make an option for it, that's the only safe side in my opinion.

**Comment by MohammedKaludi** [comment]
Fixed and now can be closed
