### ISSUE TITLE
Give default Height and width values for ads

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1190]
Default height and width values are not set for ads, instead of this added a placeholder because of this users get confused and they think that the values are set already but it's not, And giving the validation issue.

ScreenShot> http://take.ms/GQLl0

My suggestion is, make a drop-down menu section instead of this http://take.ms/YpZZQ and give the default ads values so that user can choose the values and set.

**Comment by ahmedkaludi** [comment]
If we do this, it can mess up alot of pre-existing settings, let's not do that since people are used to it.
