### ISSUE TITLE
Replace fastimage with fasterimage for PHP 5.4+

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1191]
- [x] In recent update 0.5 of AMP By Automattic, they relace the fastimage with fasterimage for PHP 5.4+
Screenshot> http://take.ms/YiWqe

- [x] After you do that, make sure you check this task in #1033

Ref: https://secure.helpscout.net/conversation/440966610/16577/?folderId=1514170

**Comment by Sejiro-Hiko** [comment]
Need to test it thoroughly.
