### ISSUE TITLE
AMP not working on password-protected pages

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1192]
If mobile redirection is ON, then it's giving too many redirect error.

Ref: https://secure.helpscout.net/conversation/441028863/16581/?folderId=1622967

**Comment by ahmedkaludi** [comment]
Let's test this @pegazee

**Comment by Sejiro-Hiko** [comment]
Tested it and the Issue is valid so, I've removed the AMP from it.

**Comment by MohammedKaludi** [comment]
Use skip post instead.

**Comment by MohammedKaludi** [comment]
:+1:
