### ISSUE TITLE
width="" height="" causing critical errors for alot of people. Possible solution

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1197]
Let's detect width="" height=""  and then make it 150 x 150 with responsive tag?

See: http://take.ms/cfTaC

REF: https://wordpress.org/support/topic/amp-image-error/#post-9557876

**Comment by pegazee** [comment]
One more user reported : https://secure.helpscout.net/conversation/443970227/16783?folderId=1060551

**Comment by Sejiro-Hiko** [comment]
asked the user for the Fusion Core File.

Ref: https://secure.helpscout.net/conversation/443970227/16783?folderId=1060556

**Comment by Sejiro-Hiko** [comment]
This Issue was resolved in the previous update.

**Comment by MohammedKaludi** [comment]
and it is working tested on https://www.fin****alku.com/sobat-finansialku-want-hear/amp
