### ISSUE TITLE
Add support to Vk.com video

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/accelerated-mobile-pages#1202]
ref:  https://wordpress.org/support/topic/can-you-add-support-to-vk-com-video/

**Comment by MARQAS** [comment]
It is working fine. 
The embed is in the iframe format which will directly be converted to amp-iframe. 
I tried adding the code which user gave and it is working fine.

**Comment by MARQAS** [comment]
There's an AMP component for VK: https://www.ampproject.org/docs/reference/components/amp-vk
But it is for Posts and Widgets not for videos. And the embed of VK post in this format:

```
<div id="vk_post_1_2442097"></div><script type="text/javascript">
  (function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "https://vk.com/js/api/openapi.js?156"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'vk_openapi_js'));
  (function() {
    if (!window.VK || !VK.Widgets || !VK.Widgets.Post || !VK.Widgets.Post("vk_post_1_2442097", 1, 2442097, 'RzJ1I03ZdnrTdlMYDF-71r_EA5bh')) setTimeout(arguments.callee, 50);
  }());
</script>
```

And for amp-vk component, we require Owner id, Post id, and Security hash. 
Any idea how we can extract these things for AMP from the above code?

**Comment by MohammedKaludi** [comment]
:+1:
