### ISSUE TITLE
Turn on the WP Debug and make sure there are no errors.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1203]
- [x] http://take.ms/24CJT

- [x] Notice: Undefined variable: page in /app/public/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 2516 Notice: Undefined variable: page in /app/public/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 2516

- [x] Notice: Undefined offset: 0 in /app/public/wp-content/plugins/accelerated-mobile-pages/base_remover/base_remover.php on line 151

**Comment by MARQAS** [comment]
2nd one resolved in #1048

**Comment by MohammedKaludi** [comment]
@MARQAS also check Design-2 and Design-3

**Comment by MohammedKaludi** [comment]
Looks good, tested with Debug: True and found no warning till now.
