### ISSUE TITLE
amp-mustache and amp-form scripts not loading on custom frontpage

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1204]
I've checked with the CF7 and amp opt-in plugins, It seems on custom frontpage amp-mustache and amp-form scripts are not loading and giving the validation issues. We need test one more time.

Note: I've checked in the design 2

**Comment by ahmedkaludi** [comment]
If this is true, then let's act on it @pegazee

**Comment by MARQAS** [comment]
@pegazee I have added the scripts in amp-cf7 dev branch.

**Comment by pegazee** [comment]
The issue is resolved and the code is added in the "Contact Form 7 for AMP" plugin.
