### ISSUE TITLE
Couple of things to check before release 0.9.63

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1206]
- [x] What happens to the old category base remover plugin

- [x] Configuration wizard Frontend Css

- [x] Config wizard Images change

- [x] Search > AMP Activate > onClick message

- [x] Options > Design Preview

**Comment by ErikThiart** [comment]
Anything I can help with?

**Comment by ahmedkaludi** [comment]
@ErikThiart I really appreciate that, the review is almost done. I'm just finishing up things and getting it ready for the release, 

If you can test the master branch code and see if you find any error while installation or usability.
