### ISSUE TITLE
Trailing Slash issue

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/accelerated-mobile-pages#1207]
Reference: https://wordpress.org/support/topic/a-very-polite-reminder-about-trailing-slash-issue/

Screenshot:
![missing_slash](https://user-images.githubusercontent.com/24407596/31283588-a6f6367e-aad3-11e7-9306-c31dd6e1724a.png)

**Comment by MARQAS** [comment]
Resolved in #1095

**Comment by MohammedKaludi** [comment]
Working as expected :+1:
