### ISSUE TITLE
itemtype attribute is striping in the ul tag

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1210]
Ref: https://secure.helpscout.net/conversation/444309450/16806/?folderId=1060551

ScreenShot> https://content.screencast.com/users/JacobSEO/folders/Jing/media/bca65d9a-78dc-4b2d-b2d0-c40bece20b54/2017-10-05_1101.png

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko Nice, working as expected.  :+1:  Closing the ticket.
