### ISSUE TITLE
Debug Error due to vendor AMP

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1213]
Debug Error due to vendor AMP

Issue in get( 'post_amp_styles' )

add_action( 'amp_post_template_css', 'amp_post_template_add_styles', 99 );
function amp_post_template_add_styles( $amp_template ) {
	$styles = $amp_template->get( 'post_amp_styles' );
	if ( ! empty( $styles ) ) {
		echo '/* Inline styles */' . PHP_EOL;
		foreach ( $styles as $selector => $declarations ) {
			$declarations = implode( ";", $declarations ) . ";";
			printf( '%1$s{%2$s}', $selector, $declarations );
		}
	}
}

if  post_amp_styles is empty then its showing warning, need to either create empty array by default or check it in a better way.

**Comment by MARQAS** [comment]
This one should also be done in .67

**Comment by MohammedKaludi** [comment]
Tested and it is working smoothly.
