### ISSUE TITLE
Hreflang and internationalization. 

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1216]
https://ampbyexample.com/introduction/internationalization/

We need an easy way to support this. The nice side effect if you do have a header script box for each page, it means other structured data can be entered like local business etc.

**Comment by ahmedkaludi** [comment]
@Frenchomatic Is this something similar to WPML?

**Comment by Frenchomatic** [comment]
I don't use WPML. I use https://wordpress.org/plugins/hreflang-tags-by-dcgws/ to include hreflang declarations in the header. These show a page has different language variants .  These obviously get stripped for AMP. So  I am having to do this in my functions.php file to get  the same effect

```
function amp_hefrelangs_special() {
if (is_page('avis') && is_amp_endpoint())
{ 
?><link rel="alternate" href="https://www.mydomain.com/example/amp/" hreflang="en" />
?><link rel="alternate" href="https://www.mydomain.fr/exemple/amp/" hreflang="fr" />
<?php
}
elseif(is_page('a-propos-de-nous') && is_amp_endpoint())
{ 
?>
?><link rel="alternate" href="https://www.mydomain.com/example2/amp/" hreflang="en" />
?><link rel="alternate" href="https://www.mydomain.fr/exemple2/amp/" hreflang="fr" />
<?php
 }
etc

add_action( 'amp_post_template_head', 'amp_hefrelangs_special');

```

**Comment by Frenchomatic** [comment]
#1433 I will close it here
