### ISSUE TITLE
Debug Errors Post 0.9.63

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1219]
I have updated plugin to 0.9.63, clear all caches and made some tests.

Below errors generated:

- [x] PHP Notice: Undefined index: ampforwp-category-base-removel-link in /data/www/XXXXXX/XXXXXX/www/wp-content/plugins/accelerated-mobile-pages/base_remover/base_remover.php on line 46

- [x] PHP Notice: Undefined index: ampforwp-tag-base-removal-link in /data/www/XXXXXX/XXXXXX/www/wp-content/plugins/accelerated-mobile-pages/base_remover/base_remover.php on line 47

- [x] PHP Notice: Undefined index: amp-on-off-for-all-posts in /data/www/XXXXXX/XXXXXX/www/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 3739

- [ ] PHP Notice: Undefined index: amp-on-off-for-all-posts in /data/www/XXXXXX/XXXXXX/www/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 49

- [x] PHP Notice: Use of undefined constant AMPFORWP_DM_SOCIAL_CHECK - assumed AMPFORWP_DM_SOCIAL_CHECK in /data/www/XXXXXX/XXXXXX/www/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 384

- [x] PHP Notice: Undefined index: type in /data/www/XXXXXX/XXXXXX/www/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php on line 2962

- [ ] and this Redux one (I am not developing online so don’t know what can be the issue) https://imgur.com/a/XGz3b Also the same as #549

REF: https://wordpress.org/support/topic/several-errors-regarding-php-mostly/#post-9567127

---------

- [x]  Notice: Undefined index: ampforwp-custom-type in ...\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 1050 - FROM: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/970

**Comment by MohammedKaludi** [comment]
:+1:
