### ISSUE TITLE
Fatal error after 0.9.63 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1220]
Fatal error</b>: Uncaught Error: Cannot use object of type WpSoL_Configuration as array in /public_html/wp-content/plugins/accelerated-mobile-pages/install/index.php:509
Stack trace:

REF: 

1. https://wordpress.org/support/topic/500-errors-no-settings-breaks-admin-php/#post-9567311

2. https://secure.helpscout.net/conversation/445654667/16881/?folderId=1060551

**We still don't know what's causing this. we need to be on a lookout.....like...right now!**

**Comment by ahmedkaludi** [comment]
any idea on this @nicholasgriffintn @Frenchomatic

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi looks to be a problem with the Wordpress Speed of Light plugin (https://en-gb.wordpress.org/plugins/wp-speed-of-light/) from the error that he noted.

Seems to be a conflict with the install process.

**Comment by MohammedKaludi** [comment]
:+1:
