### ISSUE TITLE
Lazy Loading Issue with Wowmall theme 

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1222]
Images going blank when enabled the option.

Ref: https://www.youtubebulkviews.com/youtube/buy-youtube-views/

![image](https://user-images.githubusercontent.com/28556545/31329379-74c8a21a-acf7-11e7-93d5-383d2a95b5a2.png)

**Comment by Sejiro-Hiko** [comment]
Working Properly, Issue Was fixed along with the Faster Image #1191 Need to test on different systems

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko whats the status of this ticket?

**Comment by MohammedKaludi** [comment]
Wowmall theme has not made the lazy loading the WordPress way.
Removing the ticket from the milestone.
