### ISSUE TITLE
Prophoto6 Theme  is not allowing to setup the AMP menus ,it will override the AMP Menus and not showing same as Theme Menu Reported by a user

### ISSUE THREAD

**Issue by mayanksharma9033** [ahmedkaludi/accelerated-mobile-pages#1224]
Reference ticket:-

https://secure.helpscout.net/conversation/435148839/16342/?folderId=1060551

EDIT BY AHMED: DO THIS TICKET AT THE END. Low Priority.

**Comment by MohammedKaludi** [comment]
This ticket does not be reported as a bug, actually, this is incompatible coding done by the theme developer. Still keeping this ticket open and see if we can help the user.

Removing from this milestone.

MK

**Comment by ahmedkaludi** [comment]
This is the error of the Theme Developer. The theme developer does not allow users to use default WP features. There is no point in wasting time with this theme. We're already wasted alot of time in the name of help and god. :)
