### ISSUE TITLE
Home button in mobile admin doesn't work

### ISSUE THREAD

**Issue by georgeiMac5k** [ahmedkaludi/accelerated-mobile-pages#1226]
I've found a small bug in the mobile version of WP-admin area. When I click on the Home button, than before the last update (and before the adding of Visit AMP link) Home button takes me to my homepage, but now this button do nothing, so I can only go to "Visit AMP" link. Tested on mobile Chrome (on Galaxy S8) and also in Chrome desktop (in developer console and mobile view).

![2017-10-09 23 19 53](https://user-images.githubusercontent.com/15585200/31359031-6688e830-ad48-11e7-8eb3-dbfd633a6e2e.jpg)

**Comment by MARQAS** [comment]
Hi @georgeiMac5k 
It's working fine on my end, can you send us your WP login info at team@magazine3.com?

**Comment by MohammedKaludi** [comment]
Closing the ticket, if the issue persists then @georgeiMac5k feel free to reopen the ticket and email us to team@magazine3.com and we will go deep into the issue.
