### ISSUE TITLE
Override Homepage Thumbnail Size in Design 3

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1227]
Option to override Homepage Thumbnail Size in Design 3

I said previously that we won't do it but the requests are coming in so we will have to do this for sure.

REF: https://wordpress.org/support/topic/override-homepage-thumbnail-size/

**Comment by MARQAS** [comment]
Instead of Option we made some changes in the code to make the look and feel of images better in D3.

**Comment by MARQAS** [comment]
Checked and reviewed by @ahmedkaludi
