### ISSUE TITLE
https://schema.org/SiteNavigationElement missing from menus

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1229]
On design 2: 

Header and footer menus are removing a nav structured element

itemtype="https://schema.org/SiteNavigationElement"

Menu items are keeping  itemprop="url" but removing the spans with itemprop="name" around the item name.

**Comment by Frenchomatic** [comment]
In header-bar.php I am now using this which checks out on google's structured tester

```
<nav id ="primary-amp--menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
      <?php
          $menu = wp_nav_menu( array(
                                    'theme_location' => 'amp-menu' ,
                                    'link_before'     => '<span itemprop="name">',
                                    'echo' => false) );
          echo strip_tags( $menu , '<ul><li><a><span><div>'); ?>
</nav>
```
It will need to be applied to the footer menu too.

**Comment by Sejiro-Hiko** [comment]
Hi @Frenchomatic Does it removing the attributes from <ul> tag? and can you please check this with the latest update?

**Comment by Frenchomatic** [comment]
This is not corrected in the latest version 0.9.65.1 - saleking.com is an example using that version.

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic can you test this latest ticket where we've improved the sanitization 
#1270 and let us know.

**Comment by Frenchomatic** [comment]
Please see my reply. It is not a sanitisation issue but the code needs to be in header.php

On 25 Oct 2017, at 20:06, Sejiro-Hiko <notifications@github.com> wrote:

@Frenchomatic <https://github.com/frenchomatic> can you test this latest ticket where we've improved the sanitization
#1270 <https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1270> and let us know.

**Comment by Frenchomatic** [comment]
I don't use WPML. I use a plugin but the issue is that their is no place to insert json or additional information in the header on an individual page basis.


On 25 Oct 2017, at 20:06, Sejiro-Hiko <notifications@github.com> wrote:

@Frenchomatic <https://github.com/frenchomatic> can you test this latest ticket where we've improved the sanitization
#1270 <https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1270> and let us know.

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic test this commit

**Comment by Frenchomatic** [comment]
No - it is nearly there but not complete - look at my code above. You are not putting in <span itemprop="name"> around the menu item names.

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic test the latest commit

**Comment by Frenchomatic** [comment]
yes that is now fine and it checks out on structured data too - good stuff. These are good things to do but I really would like to push #1260 . This ticket is a deal breaker for production web sites and it has been going on for 4 versions now without being fixed.  For my production sites I have to fudge it in a very messy way.

**Comment by Sejiro-Hiko** [comment]
#1260  is in Progress and would be fixed in this update

**Comment by MohammedKaludi** [comment]
@Frenchomatic I have created a milestone only to tackle issue regarding Structured Data https://github.com/ahmedkaludi/accelerated-mobile-pages/milestone/54

I'm sure we will be able to fix all the structured data related in this milestone.

Mohammed Kaludi

**Comment by ahmedkaludi** [comment]
Update: The Markup is not correct,

Make sure it's according to: https://gist.github.com/jessotron/143bf76b448578329896#file-nav-schema-markup

**Comment by Frenchomatic** [comment]
That markup in the gist above is wrong -  itemprop name goes around the actual menu word. 

`<a href="https://www.example.com/menu-item1/" itemprop="url"><span itemprop="name">my thing</span></a>`

This is correct - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0edb6776623ab8304cb33884bfe1cd0ffe876fc5

**Comment by Sejiro-Hiko** [comment]
Can you provide any reference or proof to that?

**Comment by Frenchomatic** [comment]
Yes - if you look at a professionally made theme - for example those offered under the genesis framework.  They are the most influential Wordpress development group out there and their themes contain structured microdata as standard. Here is one of my genesis sites saleking.com  - 

https://search.google.com/structured-data/testing-tool#url=saleking.com

You can look at Studiopress own website too who make genesis. Their menus are marked up with a span of itemprop=name around the actual menu name. 

That menu is standard code (I have done nothing to it).  The code I give above allows me to replicate that in AMP - saleking.com/amp/ .  If you do it the other way round I am not sure what the structured tester  will do.
