### ISSUE TITLE
Better UX in Ads options suggestion by user in Live Q&A

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1232]
I don't know if you already did this, but a﻿ good idea would be to enter the Adsense Publisher only once.. (just UX) but you know I love your plugin.... you are the best

**Comment by Sejiro-Hiko** [comment]
We cannot do this for the two following reasons.
1. Already thousands of users implement this and If we made the changes then there'll be an issue with the existing implementation of ads.

2. There's a use case where users implement ads with multiple Adsense accounts and If we implement this then they won't be able to use multiple accounts.
so therefore we will not be making any changes to it.
