### ISSUE TITLE
Debug notices in 0.9.63

### ISSUE THREAD

**Issue by ob-ivan** [ahmedkaludi/accelerated-mobile-pages#1235]
Continued from #1130. I'm updated to 0.9.63 and still some notices occur:

1) Notice: Only variables should be passed by reference in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-1/elements/bread-crumbs.php on line 73

2) PHP Notice:  AMP_Post_Template::get вызвана <strong>неправильно</strong>. Called for non-existant key ("post_amp_styles"). 0.1.) in /path/to/public_html/wp-includes/functions.php on line 4138

**Comment by ahmedkaludi** [comment]
Hi @ob-ivan 
Can you please update to 0.9.64 and let us know if you still find those errors?

**Comment by ob-ivan** [comment]
Just updated to 0.9.64. Can still see no. 1: " Notice: Only variables should be passed by reference in /home/web/smithouse.ru/public_html/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-1/elements/bread-crumbs.php on line 73" on a single post http://mysite/press-center/blog/22378/amp/

My php version is 7.1.4

**Comment by MohammedKaludi** [comment]
This has been fixed in #1267
