### ISSUE TITLE
View AMP on Admin Bar for the respected page/post If enable.

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1236]
![a homepage section - homedew - google chrome 2017-10-11 17 11 58](https://user-images.githubusercontent.com/28556545/31438823-627f18ee-aea7-11e7-82e3-7e4aa3e7eff0.png)

- [x] Feature

- [x] Frontend

- [x] Proper Conditioning.

**Comment by MohammedKaludi** [comment]
@ahmedkaludi - Check the labeling
