### ISSUE TITLE
Leave a Comment issue with Mobile Redirection 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1239]
Leave a Comment issue with Mobile Redirection 
http://take.ms/NHJ5u

REF: https://wordpress.org/support/topic/leave-a-comment-and-view-non-amp-version-not-work/

**Comment by MARQAS** [comment]
It's working fine on my end

**Comment by MohammedKaludi** [comment]
@MARQAS user has replied, moving the ticket to tasks

**Comment by ahmedkaludi** [comment]
The user is willing to work with us to solve this one at: https://secure.helpscout.net/conversation/448665645/17058/?folderId=1060551

We need to fix this one for sure in the next version 0.9.65

**Comment by MARQAS** [comment]
@nicholasgriffintn and @Frenchomatic 
Can you guys please check if it's working on your end or not?

**Comment by MohammedKaludi** [comment]
removing the ticket from the milestone, I'm checking it now.

**Comment by MohammedKaludi** [comment]
Fixed the issue was on users server.

>Hi Ahmed and Marqas,
I found the problem. It is due to the php session in my server was not working. I have fixed it.
Thanks a lot for your support.


https://wordpress.org/support/topic/leave-a-comment-and-view-non-amp-version-not-work/#post-9626964

Closing the ticket.
