### ISSUE TITLE
PHP warning on line 147 after 0.9.63

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1241]
After the last big update you made I got this error log message for all my websites Im using AMP 4 WP.

10-Oct-2017 13:08:10 UTC] PHP Warning: date() expects parameter 2 to be integer, string given in ../public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 174

REF: https://wordpress.org/support/topic/php-warning-on-line-147/

**Comment by MARQAS** [comment]
I guess we should do this ticket in https://github.com/ahmedkaludi/accelerated-mobile-pages/milestone/52 
What say? @ahmedkaludi and @MohammedKaludi ?

**Comment by MohammedKaludi** [comment]
Fixed and now closing the ticket.
