### ISSUE TITLE
Structured data issue with a use case.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1242]
Use Case: If you have a site with no blog (i.e. no posts page set up), then the structured data for a custom home page (static) is messed up – many attributes in the json are set to NULL

On design 2 it looks like a test is missing for a static home page when the structured data is set.

`<script type=”application/ld+json”>{“@context”:”http:\/\/schema.org”,”@type”:”Article”,”mainEntityOfPage”:”https:\/\/www.example.com\/”,”publisher”:{“@type”:”Organization”,”name”:”mycompany”,”logo”:{“@type”:”ImageObject”,”url”:”https:\/\/www.example.com\/wp-content\/uploads\/2017\/09\/mylogo.png”,”height”:”60″,”width”:”256″}},”headline”:” | thesitetitle”,”description”:”bla bla bla”,”datePublished”:null,”dateModified”:null,”author”:{“@type”:”Person”,”name”:null},”image”:{“@type”:”ImageObject”,”url”:”https:\/\/www.example.com\/wp-content\/uploads\/2017\/04\/blabla.jpg”,”height”:441,”width”:700}}</script>

`

REF: https://wordpress.org/support/topic/home-page-problem-9-6-3/

**Comment by MohammedKaludi** [comment]
:+1:
