### ISSUE TITLE
defer tag adding automatically, when Speed Booster Pack plugin activate.

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1245]
Speed Booster Pack plugin activates with our plugin, it's adding defer tag in amp scripts automatically. We need to test and make it as compatibility.

ref: https://secure.helpscout.net/conversation/446165913/16920?folderId=1514170
ScreenShot> http://take.ms/tUlHU

**Comment by ajeetku** [comment]
Issue not re-generated

**Comment by MohammedKaludi** [comment]
Tested multiple times and the issue is not reoccurring.
