### ISSUE TITLE
AMP Page Builder not saving images

### ISSUE THREAD

**Issue by laura-ionescu** [ahmedkaludi/accelerated-mobile-pages#1246]
Hello guys!
My name is Laura, I'm working for SuperWPHeroes company in Romania.
I installed AMP for WP plugin because we are planning to create an AMP website version for a client of ours. 
I'm currently experiencing some difficulties with the AMP Page builder when trying to add an images with Image module. The issue is that I can't set the image width and height when adding a photo in AMP page builder: https://prnt.sc/gwvt1t  
I know that in order to be a AMP Valid format, weight and height must be provided for all images but in frontend the image uploaded is squeezed on 150x150 dimension: https://prnt.sc/gwvwye

Please notice that I deactivated all the plugins except AMP for WP.

Looking forward for your advise,
Thank you very much guys!

Laura

**Comment by MohammedKaludi** [comment]
Hey @laura-ionescu 
Thank you for creating the ticket and reporting the issue, after your feedback we have created 2 fields for height and width, so users can add height and width according to their requirements.

We will release this feature in next update which we are planning to release on Sunday.

Please do let me know your feedback.

Thank you,
Mohammed Kaludi

**Comment by MohammedKaludi** [comment]
@ajeetku need some work in the image module checkout  #1290 

Closing this ticket for now. more on image module in ticket #1290
