### ISSUE TITLE
 Best & Ribbon Theme (Mythemeshop,com) image not shown in AMP

### ISSUE THREAD

**Issue by jejakmedia** [ahmedkaludi/accelerated-mobile-pages#1252]
**Best & Ribbon Theme** (_Mythemeshop,com_) Lazy load post content images  activated so image not shown in AMP. 

http://prntscr.com/gxdplg

**Comment by Sejiro-Hiko** [comment]
@jejakmedia 

Can you please send us those two theme files so that we can re-create the issue on our end and resolve it.
send those file at the following email address: team@magazine3.com
Thank you for your cooperation.

**Comment by Sejiro-Hiko** [comment]
@jejakmedia ,

I've followed you up on this through our official support channel, Please provide us the themes (Best & Ribbon) so that we can resolve this issue and release it with this update otherwise we have to close this ticket.
​
