### ISSUE TITLE
Post support is turned off then Meta box should also be removed

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1253]
Post support is turned off then Meta box should also be removed

![image](https://user-images.githubusercontent.com/16532359/31579340-dbcbb4f8-b151-11e7-9974-b165f0150279.png)

**Comment by MARQAS** [comment]
I guess we should make it just like Pages so that users can get an option to show AMP only on few articles but not on all
