### ISSUE TITLE
How to Remove Featured Image in Below Post Tittle in AMP

### ISSUE THREAD

**Issue by jejakmedia** [ahmedkaludi/accelerated-mobile-pages#1255]
How to Remove Featured Image in Below Post Tittle because blocking ads if placed below post title in AMP

**Comment by MARQAS** [comment]
@jejakmedia You can change the position from AMP customizer. 
Appearance->AMP, from here you can change the positions or even turn them off

**Comment by line2share** [comment]
Amp for wp Version 0.9.97.57 error can't disable featured image in single post.

I've already uncheck featured image on Appearance > amp > design > featured image. But featured image still showing.
