### ISSUE TITLE
Version 9.6.4 Scenario static home page + blog posts page

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1256]
I have just tested 9.6.4 on my test domain (saleking.com) - the scenario as you know is a static home page and a blog posts page. **THINGS ARE LOOKING GOOD**.   and all appears to be in order. 

Tomorrow, I will test on another site which doesn't contain a blog posts page to cover the other major Wordpress scenario where there are no posts. However, I think it is going to be fine.  If I disable the blog posts page on my test domain the static home page still displays the correct structured data which was a major issue for me on my production sites. 

I will report back if I see any outstanding issues.

**Comment by MARQAS** [comment]
Hi @Frenchomatic 
Sure, please let us know if you face any issues

**Comment by Frenchomatic** [comment]
We have some in the other scenario - #1260
