### ISSUE TITLE
Excerpt length feature request

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1257]
Admin panel set of excerpt length for blog posts (archive type) pages. Just a nice to have.

**Comment by ahmedkaludi** [comment]
I guess it's same request as #1122

if it is, then please close the ticket

**Comment by Frenchomatic** [comment]
Yes - forgot that was some time ago - the old ticket can be closed. 

On 16 Oct 2017, at 14:48, Ahmed Kaludi <notifications@github.com> wrote:

I guess it's same request as #1122 <https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1122>
if it is, then please close the ticket

**Comment by ahmedkaludi** [comment]
yep, it is
