### ISSUE TITLE
Separate Categories + tags feature request

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1258]
Option to turn the display of categories in top right  hand corner of post to off but still show tags after post (i.e separate them as mentioned previously - I can't find the ticket).  Many people use tags but don't have categories. It is all or nothing at the moment.

**Comment by MARQAS** [comment]
I guess it has been resolved here: #1055 , right?

**Comment by Frenchomatic** [comment]
Yes - I think so
