### ISSUE TITLE
Version 9.6.4 Bugs - Static home page and no blog posts page

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1260]
On a production site I just tried version 9.6.4. as things appear to work on my test site. However, my production site has no blog posts page and no blog posts. The following problems result

1.  Related posts show even when turned off on pages. 
2. Some of the structured data on the static home page is NULL. (i.e.  headline:  NULL | title of my blog , "datePublished":null,"dateModified":null,"author":{"@type":"Person","name":""}

**These two problems were the same in version 9.5.9- 9.6.3**

If a blog posts page with posts is defined then neither of these problems surface because the static home page takes some of its details from the blog posts page.

**Comment by Frenchomatic** [comment]
Looks like function ampforwp_search_or_homepage_or_staticpage_metadata is not setting all required data for featured image and there is an issue for the headline.

**Comment by Frenchomatic** [comment]
This is not just aminor bug but a core problem. A static home page is not being treated independently. If you look at the function where structure data is set it only says 'if archive'. There is no test if static homepage set this bla bla. 

That means as another user has said, a blog posts pages and a static home page are getting either the same data or if a blog posts page doesn't exist at all the static homepage gets NULL data. He has not deployed the plugin on a production money site because if this. 

Is the problem clear now? Please look at the function and it is obvious that a static home page never gets the correct structure data.

**Comment by Frenchomatic** [comment]
Problem still exists in version 9.6.5.1

In  function ampforwp_update_metadata_featured_image( $metadata, $post ) . 

This code never gets run for a static home page 

` $metadata['author'] = array(
						'@type' 	=> 'Person',
						'name' 		=> $structured_data_author ,
					);
$metadata['headline'] = $structured_data_archive_title;`

**Comment by MARQAS** [comment]
@Frenchomatic 
I made few changes, Can you check now and let us know?

**Comment by Frenchomatic** [comment]
Yup - looks like you are getting the author now for a static home page correctly - it looks like you need to do thasame thing for headline so it takes the page title as you do on any other page.

**Comment by MARQAS** [comment]
It's already there. Just made few changes that will differentiate the Frontpage with Blog so that the Frontpage can take the title of its own.

**Comment by ahmedkaludi** [comment]
@Frenchomatic Do you think this ticket needs more refinement?

**Comment by Frenchomatic** [comment]
If it differentiates between a blog posts page and a static home page then you have got it.  The only bit that was not working in the file I tested above was the headline - The 3 scenarios - static home page only, static home page + blog posts page, home page is a blog posts page.
