### ISSUE TITLE
Social Locker Plugin Can't Active in AMP

### ISSUE THREAD

**Issue by jejakmedia** [ahmedkaludi/accelerated-mobile-pages#1262]
Social Locker Plugin Can't Active in AMP Please fix it.

**Comment by ahmedkaludi** [comment]
@jejakmedia what exactly happens when you are using Social Locker?

What's the problem are you facing?

Its upto Social Locker to make their plugin compatible with AMP, but if there is something we can do then please let us know so we will get in touch with them.

**Comment by mayanksharma9033** [comment]
Hi, I tested it out in my localhost and didn't get any type of error, AMP compatibility missed in Social Locker Icon.
