### ISSUE TITLE
Option to hide date from D1 & D3 Homepage Loop

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1264]
Option to hide date from D1 & D3 Homepage Loop

REF: https://wordpress.org/support/topic/hiding-more-and-date-on-homepage/#post-9587367

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko there was a bug Multiple buttons were showing http://take.ms/XJuyY

**Comment by MohammedKaludi** [comment]
:+1:
