### ISSUE TITLE
New set of Sharing Buttons

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1265]
- [x] Reddit
- [x] Tumblr
- [x] Telegram
- [x] Digg
- [x] StumbleUpon

REF: https://wordpress.org/support/topic/reddit-tumblr-digg-stumble-social-icons/#post-9586789

**Comment by beingsmart3** [comment]
- [ ] Wechat
- [ ] Viber

Ref:  https://secure.helpscout.net/conversation/505225418/20340?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:
