### ISSUE TITLE
How can I add tables to Instant Articles?

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1266]
How can I add tables to Instant Articles? At the moment Facebook is not accepting me because on Instant Articles posts are missing content (like tables).

One of our users reported we need to test.
Ref: https://secure.helpscout.net/conversation/447171772/16984?folderId=1060551

**Comment by MohammedKaludi** [comment]
Great and its working <figure class="op-interactive">
