### ISSUE TITLE
How many posts can instant articles generate?

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1271]
Can it generate all the posts? ( Question from a user in Telegram community)

I guess we should test this and might even give an option to the users to select the number of posts?

**Comment by nicholasgriffintn** [comment]
Mine generates 6, not sure if that is the max, but that's what I am getting. I presume that it is currently going from the number of posts that one shows on their homepage, which for me is 6.

I would +1 an option to select the number of posts.

**Comment by MohammedKaludi** [comment]
Working and closing the ticket.
