### ISSUE TITLE
the page builder don´t work...

### ISSUE THREAD

**Issue by rafacarreto** [ahmedkaludi/accelerated-mobile-pages#1278]
the page builder don´t work. i mean, i can edit the blocks, insert the information and save it, but then in the front side of the page the content is not showing... the option "use Content as AMP Content" is disabled. 
the custom editor works well when is activated.

**Comment by ajeetku** [comment]
I have checked not found that issue.
Please provide more details, because we can't regenerate the issue

**Comment by MohammedKaludi** [comment]
Closing the ticket, @rafacarreto if the issue persists please reopen the ticket.
