### ISSUE TITLE
When AMP support is off for a specific CPT then all the AMP related metaboxes should be removed

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1289]
Rightnow Pagebuilder and AMP content is not removed. 

Need to rewrite the code and fix it once in for all.

**Comment by MARQAS** [comment]
Currently, Pagebuilder is for only post and page. 
Regarding the other meta boxes, we are using a function which will check if AMP is enabled on that post type or not, if yes then only we are adding those meta boxes.

**Comment by MohammedKaludi** [comment]
The issue is valid.

How to recreate, turn off the post or page support and check if all the AMP related meta boxes are gone or not.

http://take.ms/yguax
