### ISSUE TITLE
Navigate word customization

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/Accelerated-Mobile-Pages#129]
Navigate’ can be customized
https://wordpress.org/support/topic/custom-image-field-and-few-useful-suggestions

**Comment by MohammedKaludi** [comment]
Few sugestions from that ticket.

1. Turn On/Off Tags
2. RTL/LTR Or Auto Text Direction
3. ‘Navigate’ can be customized
4. Custom Field Thumbnail

**Comment by ahmedkaludi** [comment]
RTL, Tags on/off and Navigate text change has been added.
