### ISSUE TITLE
0.9.65 Bugs

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1291]
- [ ] Search options, works but then once clear the words from the search bar, the Option panel does work properly. 

- [x] All the Pages have Validation errors when enabled the disqus comments system

**Comment by ahmedkaludi** [comment]
the first task will be https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1238 

So closing this ticket

**Comment by MohammedKaludi** [comment]
Search bar is done.
