### ISSUE TITLE
Don't load unused css selectors

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1292]
A small enhancement - in style.php  - it is not necessary to load quite a bit of css if it is not being used. For example, comments and related posts. A simple test could be used to exclude unused css selectors allowing the overall size of the page to be reduced.

**Comment by ahmedkaludi** [comment]
I totally agree. Homepage should not load Single's Css and same rule should apply to other pages.

That's what you meant, right?

**Comment by Frenchomatic** [comment]
Not sure I follow you  about home page  - if you are not using comments or related posts anywhere then why load the css for those things. Tablepress css is loaded conditionally but not much else.

**Comment by ahmedkaludi** [comment]
Tested. Hopefully, everything is working :)
