### ISSUE TITLE
Internal Error 500 is thrown on profile page when AMP is activated 

### ISSUE THREAD

**Issue by JohNan** [ahmedkaludi/accelerated-mobile-pages#1296]
Hi,

When visiting a user profile (`wp-admin/user-edit.php?user_id=XXX`) I get the following 500 error thrown. This only happens when I have this plugin enabled, every time. As soon as I disable the plugin there is no issues visiting the page. By inspecting the suggested lines of the error, it happens when WP tries to flush the output buffer `ob_end_flush()`. Does AMP put a lot of information in there even when I only use the Admin pages?

I have tried the latest version `0.9.65`

functions.php line 3721
```
function wp_ob_end_flush_all() {
	$levels = ob_get_level();
	for ($i=0; $i<$levels; $i++)
		ob_end_flush();
}
```

Php Error
```
2017/10/23 08:15:03 [error] 2181#2181: *67844673 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /XXXXX/public_html/wp/wp-includes/wp-db.php on line 1851
PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 102400 bytes) in /XXXX/public_html/wp/wp-includes/functions.php on line 3721" while reading response header from upstream, client: XXXXX, server: XXXXX, request: "GET /wp-admin/user-edit.php?user_id=XXXXX&wp_http_referer=%2Fwp-admin%2Fusers.php%3Fs%XXXXX%26action%3D-1%26new_role%26paged%3D1%26action2%3D-1%26new_role2 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:",
```

**Comment by ahmedkaludi** [comment]
Hi @JohNan 
Are you using any plugins for User profile or role editing as well?

**Comment by JohNan** [comment]
The main problem was caused by another plugin, but in combination with AMP the server threw the 500 error and was the drop that got the water over the edge. So fixing the other plugin got things working again.
