### ISSUE TITLE
FB IA- show/hide Instant Article on specific posts 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1297]
We can make the changes to show/hide AMP on new or previous posts by using the "Show AMP on current page" option but we don't have the feature like this for FB instant article on the particular posts.

Ref:
https://secure.helpscout.net/conversation/453466459/17312?folderId=1060551

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
