### ISSUE TITLE
Facebook comments position not working 

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1298]
Facebook comments position was not working, when we use the Design customizer http://take.ms/9iFkF, we need to connect that option with facebook comments and also for Disqus comments.

ref: https://secure.helpscout.net/conversation/440551712/16548?folderId=1060551

**Comment by ahmedkaludi** [comment]
There's no plan to connect FB and Disqus comments with Post Layout builder since we haven't focused on that feature and it's the least used feature.
