### ISSUE TITLE
typeWatch is not a function

### ISSUE THREAD

**Issue by valtido** [ahmedkaludi/accelerated-mobile-pages#1299]
The whole plugin is not working at all.

I get this... 

    admin-script.js?ver=1.0.0:17 Uncaught TypeError: jQuery(...).typeWatch is not a function

When I add typeWatch manually it still gives me errors something about redux or something like that.

**Comment by ahmedkaludi** [comment]
Also, another issue that might be related is https://wordpress.org/support/topic/bugs-last-update-0-9-65/#post-9618256

**Comment by ahmedkaludi** [comment]
https://prnt.sc/h0tcfw

https://wordpress.org/support/topic/backupbuddy-backup-error-due-to-ampforwp-js/#post-9611769

**Comment by pegazee** [comment]
User reported: https://secure.helpscout.net/conversation/453845972/17350?folderId=1060551

screencast> http://take.ms/E4S2u

**Comment by MohammedKaludi** [comment]
Issue has been fixed in 0.9.65.2 and got the confirmation https://wordpress.org/support/topic/no-more-jetpack-statistic-with-0-9-64/page/2/
