### ISSUE TITLE
Blank Image on index if no featured image

### ISSUE THREAD

**Issue by Asif2BD** [ahmedkaludi/Accelerated-Mobile-Pages#13]
In my test the home page appears like this [screen-1](https://www.dropbox.com/s/2g1lq8rmgzd74o3/Screenshot%202016-07-05%2003.53.55.png?dl=1). 
Looking at themes/default/index.php it seems the function
```
                        <?php
			$thumb_id = get_post_thumbnail_id();
			$thumb_url_array = wp_get_attachment_image_src($thumb_id, 'thumbnail', true);
			$thumb_url = $thumb_url_array[0];            
			?> 
``` 
The function get_post_thumbnail_id(); works only when the post has an featured image. Many themes and website does not use that function. Now in most of my theme or plugin we use a backfill to find first appeared image, and when null return for featured, use that.

Check this documentation [here](https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/#comment-330) or I use this function below sometime, you could use that too.

```
      function asif_get_first_image($text){
      $first_img = '';
      ob_start();
      ob_end_clean();
      $output = preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i', $text, $matches);
      $first_img = isset($matches [1] [0]) ? $matches [1] [0] : '';	
      return $first_img;
    					}
```

Was looking forward to using this instead of official AMP because of home page support but this error causing issue. Quick turnaround will be very helpful.

**Comment by ahmedkaludi** [comment]
Hey @Asif2BD  Thank you so much for such an amazing help! 

I will test the code and include it in the next update. I have added this ticket to the Next Release Milestone.


Thank you so much again 👍 

Regards,
Ahmed

**Comment by MohammedKaludi** [comment]
Checking the Featured image with has_post_thumbnail and showing image
only if featured image is available.
