### ISSUE TITLE
Conflict siteorigin jquery

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1301]
The amp is conflicting with the siteorigin widget builder. It does not open a lightbox. It always comes back to widget. Whenever you click on the siteorigin constructor. When you disable the plugin it works. Whenever active error appears in wp-admin / widgets.php line 125

REF: https://wordpress.org/support/topic/conflict-siteorigin-jquery/

**Comment by MohammedKaludi** [comment]
Issue is fixed, 
https://wordpress.org/support/topic/no-more-jetpack-statistic-with-0-9-64/page/2/
