### ISSUE TITLE
Wrong link to categories and tags in Newspaper AMP Theme

### ISSUE THREAD

**Issue by adrianleira** [ahmedkaludi/accelerated-mobile-pages#1302]
I have Archives [Category & Tags] disabled, but in the link to categories and tags adds the parameter /amp

**Comment by kuaza61** [comment]
install and active this plugins: https://ampforwp.com/amp-category-base-remove-support/#utm_source=options-panel&utm_medium=extension-tab_amp-category-base-remove-support&utm_campaign=AMP%20Plugin

After: https://ampforwp.com/tutorials/article/flush-rewrite-urls/

voila ;)
