### ISSUE TITLE
Error with backupbuddy

### ISSUE THREAD

**Issue by Dahnark** [ahmedkaludi/accelerated-mobile-pages#1303]
I am getting this error when I try to do a backup with Backupbuddy:

![3khx575](https://user-images.githubusercontent.com/7463564/31903681-172d8106-b829-11e7-93c1-75f2ce1e0b6c.png)

**Comment by MohammedKaludi** [comment]
Hey @Dahnark,

Issue has been fixed in 0.9.65.2 and got the confirmation https://wordpress.org/support/topic/no-more-jetpack-statistic-with-0-9-64/page/2/

Thank you,
Mohammed Kaludi
