### ISSUE TITLE
Breadcrumb with tag (Feature request)

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1305]
It would be useful to have the breadcrumbs link something like this: homepage > tag > article title.

ref: https://secure.helpscout.net/conversation/445668442/16882?folderId=1060551

**Comment by ahmedkaludi** [comment]
The styling is correct, In my opinion.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
