### ISSUE TITLE
placeholder-icon.png is 404 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1310]
Reported by a user at https://wordpress.org/support/topic/placeholder-icon-png/#post-9612279

https://wordpress.org/plugins/redirection/

Check out for design one. Eror appears when design one in use.

See this: http://take.ms/jSsIs

**Comment by MohammedKaludi** [comment]
Url path updated and 404 fixed, closing the ticket. :+1:
