### ISSUE TITLE
Next / Previous links

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1312]
Next / previous links show on pages as well as blog posts in 9.65.1 . It doesn't make much sense for them to be showing on pages. I thought I posted this on github but I can't find it - perhaps I just mentioned it in the forum.  Needs a simple test in content.php with  !is_page().

```
<!--Post Next-Previous Links-->
	<?php global $redux_builder_amp;
		if($redux_builder_amp['enable-single-next-prev'] && !is_page()) { ?>
```

**Comment by MARQAS** [comment]
Resolved here: #1268
