### ISSUE TITLE
amp-app-banner Support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1314]
hello, i would showing a call-to-action to install an app in my site with amp plugin.
it is possibile?

the specific of AMP is:
https://ampbyexample.com/components/amp-app-banner/

**Comment by ahmedkaludi** [comment]
The official demo is not working as well.

**Comment by Zabi09** [comment]
We will build once it's implemented correctly so closing this ticket for now
