### ISSUE TITLE
Plain Permalinks Issues.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1318]
Although the plain permalinks work fine on the posts. They don't on certain pages: Make sure you check the "AMP HTML" link and "Canonical Link".
- [x]  Homepage doesn't work
- [x] Frontpage from Reading settings, and the homepage doesn't work.
- [x] Internal Linking does not work properly.
- [x] Pages doesn't work. 
- [x] Archive doesn't work. 
- [x] Breadcrumb link doesn't work. 

- [x] View amp link in the wp-admin bar

**Comment by MohammedKaludi** [comment]
All url code updated for D1 now should with any permalink types https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8bd51bf3c4b53752a3bf4f214ee23477796fd5e1

**Comment by MohammedKaludi** [comment]
All the links have been tested multiple times and I hope all the posts, pages, interlinks in all designs should work properly.
