### ISSUE TITLE
The Future of The AMP Post Builder

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1319]
So, we have this really amazing feature called Post Builder in AMP options > Design > Misc > Launch button.

It's got the Live preview, with the sorting ability, but not many people are using it and it's kind of not that stable.

I am not sure what's the future of it, or if it's good one or not.

We need to discuss this and reach to a decision.

**Comment by MARQAS** [comment]
we have removed the old customizer so I guess this one is sorted.
