### ISSUE TITLE
data-loading-strategy = prefer-viewability-over-views

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1320]
data-loading-strategy = prefer-viewability-over-views

https://www.ampproject.org/docs/guides/ads/ads_tips

**Comment by MohammedKaludi** [comment]
Changed the default value of the control : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7d30d52019ba39067df3ef44461561a6226416f3
