### ISSUE TITLE
minify output weird characters with other minification

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1322]
special characters appear on amp pages

Ref: https://secure.helpscout.net/conversation/457073677/17610?folderId=1060556
Ref: https://secure.helpscout.net/conversation/456838226/17604?folderId=1060551

**Comment by ahmedkaludi** [comment]
This was due to the AMP cache not g-zipping properly on frontend, It's fixed already.

We will roll out an update for AMP cache on Monday with further testing.
