### ISSUE TITLE
Content selector for AMP pages in Dropdown

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1326]
Content selector for AMP pages in Dropdown

**Comment by MohammedKaludi** [comment]
Create a Central place for AMP panel inside post area, so we will have all the controls in one area.

**Comment by pegazee** [comment]
**  review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
The Solution added in this ticket is not relevant as per the new code base, and we will need to create a proper UI for the section and will add it accordingly.

Closing this ticket for now and the development will continue on this ticket #3753
