### ISSUE TITLE
"Custom AMP frontpage" feature works, but doesn't show correct "Title"

### ISSUE THREAD

**Issue by kIwOk168** [ahmedkaludi/Accelerated-Mobile-Pages#133]
Kudos for adding the "Custom AMP frontpage" feature on the latest update.  I tried it out and it works but I notice that the "title" doesn't render correctly.  It still says "Page Not Found."

I tried flushing rewrite rules and clearing cache already.  Here's an image.

![issue01](https://cloud.githubusercontent.com/assets/22364679/18899726/aae2c798-856d-11e6-9742-4bb289362a1b.jpg)

**Comment by ahmedkaludi** [comment]
Please update to the latest version, it should fix the issue.
