### ISSUE TITLE
Since update to 0.9.66, I cannot edit any post/page

### ISSUE THREAD

**Issue by vdberto** [ahmedkaludi/accelerated-mobile-pages#1336]
Since the 0.9.66 update, I cannot open any edit page, nothing in wp-admin/edit.php is accessible.
Something went wrong with the update.

**Comment by MohammedKaludi** [comment]
Can you please explain what is not working properly, a screen shot will help a lot to understand the issue. 

Please do let me know the details and I will push a quick update, of possible.

Thank you
Mohammed kaludi

**Comment by vdberto** [comment]
When I click in Posts, Pages... anyway that I try to access wp-admin/edit.php, appear just a white screen! Just it.

**Comment by MohammedKaludi** [comment]
The whole dashboard has gone blank?

**Comment by vdberto** [comment]
When you click in Posts>All posts, or through the admin-bar to edit Page or Post... yes... all screen goes blank - in any way you try to access edit.php

**Comment by MohammedKaludi** [comment]
Actually we have tested on different environments before pushing the update and all the things were working as expected. can you please provide me some more details about the issue any error reported on the scene or debug log? This will help me understand what is the issue.

Also if you could share me the login info of your site(if possible)? So I can check what's what is the actual problem. You can send me the details at team@magazine3.com.

Mohammed kaludi

**Comment by vdberto** [comment]
I'm not that technical... Is there a way to chat with you?
I don't know how to see the debug log.
The screen is entirely blank, no error message.

**Comment by MohammedKaludi** [comment]
Yes we have a telegram community where you can join in and chat and learn more about ampforwp plugin https://ampforwp.com/community/

Also you can personal message me on telegram. It's very late here and I'm going to bed, but please do join in the chat group and share your issues any one who is online will help you or our team will help you when they are back online in morning. 
I 
Mohammed kaludi

**Comment by vdberto** [comment]
I turned "display_erros" on php.ini "on", so the error has just appeared in wp-admin/edit.php:

Fatal error: Uncaught Error: Call to undefined function wp_enqueue_editor() in /home/f1mania/public_html/wp-content/plugins/accelerated-mobile-pages/pagebuilder/functions.php:43 Stack trace: #0 /home/f1mania/public_html/wp-includes/class-wp-hook.php(298): amppbbase_admin_scripts('edit.php') #1 /home/f1mania/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #2 /home/f1mania/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/f1mania/public_html/wp-admin/admin-header.php(97): do_action('admin_enqueue_s...', 'edit.php') #4 /home/f1mania/public_html/wp-admin/edit.php(303): require_once('/home/f1mania/p...') #5 {main} thrown in /home/f1mania/public_html/wp-content/plugins/accelerated-mobile-pages/pagebuilder/functions.php on line 43

**Comment by ajeetku** [comment]
Fix error :  a194968

**Comment by MohammedKaludi** [comment]
@vdberto we have identified the issue and found that the function we are using "wp_enqueue_editor" in AMP page builder was introduced in WordPress's version 4.8 and later https://developer.wordpress.org/reference/functions/wp_enqueue_editor/#changelog

But we have fixed the issue and releasing an update very soon, I suggest you update your WordPress to the latest version as well.

Please do let me know if you need anything else.
Mohammed Kaludi

**Comment by ajeetku** [comment]
Resolved error: a194968

**Comment by ahmedkaludi** [comment]
@vdberto We have just released an update 0.9.66.1 - Please update. It should fix the issue.
