### ISSUE TITLE
Notice if a post has no author data

### ISSUE THREAD

**Issue by ob-ivan** [ahmedkaludi/accelerated-mobile-pages#1338]
Some posts in my WordPress database are created by a bot which doesn't set any particular author for them. Trying to get author data on these posts will return false.

In my regular template for these posts I don't call author data, and I have no problems. But when I request an AMP version of such post, the method `AMP_Post_Template::build_post_data` calls `get_userdata(...)->display_name` which is a notice:

```
PHP Notice:  Trying to get property of non-object in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 151
```

Plugin version: 0.9.66.0

**Comment by MohammedKaludi** [comment]
:+1:
