### ISSUE TITLE
Favicon only on the homepage

### ISSUE THREAD

**Issue by aashishpahwa** [ahmedkaludi/Accelerated-Mobile-Pages#134]
Hi 
the issue hasn't been addressed in the new update.

**Comment by nicholasgriffintn** [comment]
Hey,

The developers haven't added this option yet, however, I made a pull request to add favicon's, full icons and a manifest to AMP pages, you can find it here if you want to add it yourself:

#119

**Comment by ahmedkaludi** [comment]
Let's continue the discussion on #136

I'm closing this because it is really hard to manage so many issues.
