### ISSUE TITLE
Hide meta boxes as per the user level types

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1340]
How to do it please? It’s uncomfortable for a website admin to let its users take the control to some features such as AMP elements. Thanks for the help 😉

REF: https://wordpress.org/support/topic/disable-meta-boxes-for-specific-users/

NOTE: I have asked him about the specific user types which roles he want to hide and allow.

UPDATE: In my opinion, the 1st who should see this features must be the editor and, at least, the administrator, the others roles provide just content, not reflexion and web strategy… but, if we can choose who is able to see which option, it could be better 😉

**Comment by MohammedKaludi** [comment]
:+1:
