### ISSUE TITLE
Annoyance due to Update Notification Bar

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1342]
Some users are reporting that they are unable to close the notification bar.

https://wordpress.org/support/topic/cannot-close-the-notification-of-the-update/

We have to test it thoroughly and resolve it ASAP

**Comment by MARQAS** [comment]
#1321 is also related to this.

**Comment by ahmedkaludi** [comment]
👍 Working smoothly.
