### ISSUE TITLE
Ad below header is not centered in home. (design 2)

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1343]
ref: https://secure.helpscout.net/conversation/457656999/17659?folderId=1060551

**Comment by zabi332** [comment]
One more - After the last update, top and bottom banners are not centered anymore

Ref: https://secure.helpscout.net/conversation/460021611/17851/

**Comment by pegazee** [comment]
ref: https://secure.helpscout.net/conversation/461347074/17953?folderId=1680011, many users are reporting this issue, we need to fix ASAP

**Comment by MohammedKaludi** [comment]
:+1:
