### ISSUE TITLE
Sitenavigationelement has not been implemented correctly for footer menu. 

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1345]
version 0.9.66.1 - footer menu - the span on name should be present. Need to strip tags on ` <span>` or use your sanitizer. Also you have the `</div>` just before `</nav>` and it should be just after.  I asked the guys over at genesis and there doesn't need to be an @id on the secondary footer menu. 

```
<nav itemscope="" itemtype="https://schema.org/SiteNavigationElement">
			<?php
          	$menu = wp_nav_menu( array(
                                    'theme_location' => 'amp-footer-menu' ,
                                    'link_before'     => '<span itemprop="name">',
                                    'link_after'     => '</span>',
                                    'echo' => false) );
          echo strip_tags( $menu , '<ul><li><a><span>'); ?>
      	</nav>

```
I tested this and it works correctly. If you remove the `<span>` from the echo then will need to use your sanitizer code.

**Comment by MARQAS** [comment]
@Frenchomatic Can you check now?

**Comment by Frenchomatic** [comment]
I spoke to the guys over  in genesis and you don't need the id in the footer menu 

`<nav **id ="primary-amp-menu"** itemscope="" itemtype="https://schema.org/SiteNavigationElement">
`

**Comment by MARQAS** [comment]
But I guess it is not causing any issues, right? So why not keep it?

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Frenchomatic** [comment]
Well your footer menu is not your primary menu.  Better to either remove it or give it a different ID

**Comment by MohammedKaludi** [comment]
@Frenchomatic removed. :+1:
