### ISSUE TITLE
Need AMP only on new posts but not on my old posts

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1348]
I just need to add AMP on my new posts but I don't need AMP on my previous posts.

Ref: https://secure.helpscout.net/conversation/457296166/17633/

**Comment by MARQAS** [comment]
We will do it separately in a free extension

**Comment by MARQAS** [comment]
https://github.com/MARQAS/amp-hide-posts

**Comment by MARQAS** [comment]
Ahmed here,

This is possible to do, but again, it's not worth adding to the core because not sure how useful it is. 

We will close this one and continue the conversation.
