### ISSUE TITLE
compatibility with redux plugin

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1349]
If we enable the redux plugin then the options panel ( selecting the design ) is not working.

Ref: https://secure.helpscout.net/conversation/437066467/16409?folderId=1060551

**Comment by ajeetku** [comment]
584071d Added a new ext. select field in redux framework

**Comment by MohammedKaludi** [comment]
:+1: this is working and was able to recreate the issue and tested the fix and it is working smoothly.
