### ISSUE TITLE
Move the strip to AMP content

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#135]
Move the strip to AMP content

**Comment by MohammedKaludi** [comment]
@ahmedkaludi Fix the word stripping issue reported in https://wordpress.org/support/topic/stripping-out-content-on-certain-word/

And make sure its fixed by tonight or tomorrow morning.

**Comment by ahmedkaludi** [comment]
This was fixed in the recent update
