### ISSUE TITLE
PHP Notice: Undefined index: wordpress-comments-support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1350]
PHP Notice: Undefined index: wordpress-comments-support in wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-2/style.php on line 195

REF: https://wordpress.org/support/topic/php-notice-undefined-index-wordpress-comments-support/

**Comment by MohammedKaludi** [comment]
:+1:
