### ISSUE TITLE
Conflict with WP Bakery VC Plugin 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1351]
I've send allready a message to the makers of WPBakery Page Builder. I have to shut down the
Accelerated Mobile Pages plugin every time I want to write or edit an article on my website. Otherwise I can't open the green coloured text block. Nothing happens when AMP is active. Deactivated it works well and the file opens as always.

![screenshot_1 1](https://user-images.githubusercontent.com/16532359/32315972-4b47c278-bfd4-11e7-881c-df2543f3509c.jpg)

REF: https://secure.helpscout.net/conversation/459941699/17841?folderId=1060551

**Comment by KDBhimself** [comment]
[codecanyon-242431-visual-composer-page-builder-for-wordpress.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/1436933/codecanyon-242431-visual-composer-page-builder-for-wordpress.zip)
I tried an e-mail, but it bounced back. Included the file you need.

**Comment by MohammedKaludi** [comment]
All the things seems to be fixed.

**Comment by MohammedKaludi** [comment]
:+1: this also seems to be fixed, needs some testing before the push
