### ISSUE TITLE
Backend editor not working in latest version with some other plugins

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1352]
If I downgraded to 0.9.65.1 then backend editor working fine but not in the latest version ( 0.9.66.1 ).

Video: https://www.dropbox.com/s/h0hoemkxqhoekfr/AMP%20Plugin%20Error%20-%20Small.mp4?dl=0

Ref: https://secure.helpscout.net/conversation/458189134/17701?folderId=1060551

**Comment by MohammedKaludi** [comment]
This should work now.

**Comment by MohammedKaludi** [comment]
:+1: this seems to be working for now.
