### ISSUE TITLE
Structured data cannot be disabled

### ISSUE THREAD

**Issue by domantasg** [ahmedkaludi/accelerated-mobile-pages#1354]
Since last update, structured data cannot be disabled even if I turn it off (https://prnt.sc/h5ldns). As a result it displays different structured data than non-amp pages (we use scheme.org plugin for it).

**Comment by MARQAS** [comment]
Hi @domantasg ,
Can you tell me the exact need? 
You want to remove the whole structured data from your posts/pages? If yes, then please rethink again because it is recommended.

**Comment by MARQAS** [comment]
Why not make it compatible with the structured data plugin which you are using? so both non-amp and amp shows the same structured data

**Comment by domantasg** [comment]
@MARQAS your plugin adds it's own structured data to AMP pages. Unfortunately, it's different from what we have on non-AMP pages because your plugin does not support Article schema. 

- non AMP: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.000webhost.com%2Fblog%2Ffix-wordpress-500-internal-server-error%2F

- AMP: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.000webhost.com%2Fblog%2Ffix-wordpress-500-internal-server-error%2Famp

We are using https://wordpress.org/plugins/wp-structuring-markup/ plugin for structured data which has these option and can automatically include structured data to AMP pages: https://prnt.sc/h7r4xd

If there are no fix, any workaround would be appreciated

**Comment by MARQAS** [comment]
@domantasg will this work?
I have also added the plugin which you are using in our compatibility list, we will try our best to make it compatible with that plugin.

**Comment by domantasg** [comment]
@MARQAS 

yes, should do the trick. Will test it once new version is out and report my findings here.

**Comment by MARQAS** [comment]
Thanks
