### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1355]
Ref: https://secure.helpscout.net/conversation/460042074/17855?folderId=1680011

Screenshot > http://take.ms/MB6mk

But user didn't install and activate the Jetpack plugin but getting the fatal error. And for temporary I've removed the code of JetPack from the plugin http://take.ms/T4DjA

We need to test, check and resolve the issue.

**Comment by MohammedKaludi** [comment]
:+1:
