### ISSUE TITLE
Jetpack carousel not working smoothly between images in amp

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1358]
Jetpack carousel working perfectly on the non -AMP but in amp view carousel didn't go smoothly and have difficulty in go back or forward to next images.

Ref: https://secure.helpscout.net/conversation/459867345/17832?folderId=1060551

**Comment by zabi332** [comment]
One more gallery issue on Jetpack carousel.

Ref: https://secure.helpscout.net/conversation/462766284/18028?folderId=1060556

**Comment by MARQAS** [comment]
Tests: amp-carousel is not working well with
1: Our RTL support option
2: Images of large height and narrow width

**Comment by MohammedKaludi** [comment]
:+1:
