### ISSUE TITLE
Polylang images size with sanitization

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1360]
![image](https://user-images.githubusercontent.com/16532359/32403646-5d39ba44-c165-11e7-8d3c-3d3f8771fd6e.png)

https://wordpress.org/support/topic/css-errors-11/

**Comment by MohammedKaludi** [comment]
Also added style sanitization, so Styling added by the plugin will also be validated. 

Closing the ticket.
