### ISSUE TITLE
Jannah Theme Lazy Loading causes blank images

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1362]
Jannah Theme Lazy Loading causes blank images
https://wordpress.org/support/topic/featured-image-not-showing-63/

**Comment by zabi332** [comment]
Jannah theme zip file is downloaded

**Comment by zabi332** [comment]
https://secure.helpscout.net/conversation/461298844/17937?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:
