### ISSUE TITLE
Issues with galleries as well as gallery captions

### ISSUE THREAD

**Issue by trenzterra** [ahmedkaludi/accelerated-mobile-pages#1363]
Hi there,

I note that gallery captions were implemented a few weeks ago. However, in its current implementation, caption text gets easily truncated.

You can see my test over here: https://www.describee.com/2017/11/05/test-2/amp/

Especially when the screen size is small, the problem is worse.

Another issue I have been having with galleries is that that the amp-carousel doesn't show up when I use the new Gutenberg editor to create galleries. My test post is here: https://www.describee.com/2017/11/05/gallery-issues/amp/ vs the original gallery at https://www.describee.com/2017/11/05/gallery-issues

Given that Gutenberg will be the default Wordpress editor very soon, it would be great if work could be started on getting this AMP plugin to work with it.

Thank you.

**Comment by MohammedKaludi** [comment]
Looks good and large captions will be visible after the click.

**Comment by trenzterra** [comment]
It isn't. Only the first two lines of the caption show when there are supposed to be several more lines.

On the second example, captions don't show up at all.

**Comment by trenzterra** [comment]
Sorry I hadn't realise this was posted after a commit. Please ignore.
