### ISSUE TITLE
Debug Errors

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1366]
- [x] PHP Notice: Trying to get property of non-object in /wp-content/plugins/accelerated-mobile-pages/templates/structured-data.php on line 35

- [x] PHP Notice: Trying to get property of non-object in wp-content/plugins/accelerated-mobile-pages/templates/structured-data.php on line 39

- [x] HP Notice: Trying to get property of non-object in wp-content/plugins/accelerated-mobile-pages/templates/structured-data.php on line 27

- [x] PHP Notice: Trying to get property of non-object in wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-1/style.php on line 13

- [x] PHP Notice: Trying to get property of non-object in wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 3240

REF: https://wordpress.org/support/topic/php-notice-trying-to-get-property-of-non-object-in-3/

**Comment by ahmedkaludi** [comment]
Two latest ones after 0.9.67.0

- [ ] Notice: Undefined index: non-content in /app/public/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php on line 41
 

- [ ] Notice: Undefined index: non-content in /app/public/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php on line 41

 REF:  http://take.ms/qCAkz

**Comment by MARQAS** [comment]
Resolved the debug error issues which I was able to recreate.

**Comment by MohammedKaludi** [comment]
More debug errors found in debug log.

**Comment by MohammedKaludi** [comment]
Debug Looks clean, and all the warnings have been resolved.
