### ISSUE TITLE
Meta description tag in normal site unicode character is different from AMP site unicode character.

### ISSUE THREAD

**Issue by mayanksharma9033** [ahmedkaludi/accelerated-mobile-pages#1369]
User is asking that if we visit the normal site  link https://www.sportwettenanbieter.com/interwetten-erfahrungen/ and  the amp site link https://www.sportwettenanbieter.com/interwetten-erfahrungen/amp

If we compare both of the links and see the meta description tag then the characters   "Erfahrungen" and "wir" is separated by Unicode Chara ('-') in non-amp version and but in amp version it is so different,the meta description between the "Erfahrungen" and "wir" is separated by Unicode character(' &#8211;').

why these are so different?

Reference screenshots:-
1) http://take.ms/7Yp5P (amp version)
2) http://take.ms/vJypi (non-amp version)

**Comment by mayanksharma9033** [comment]
Reference ticket:-  https://secure.helpscout.net/conversation/459922991/17838?folderId=1680011

**Comment by MohammedKaludi** [comment]
:+1:  this is removing the shortcodes from the url
