### ISSUE TITLE
Navigate menu items are not the main menu items?

### ISSUE THREAD

**Issue by rodferris** [ahmedkaludi/Accelerated-Mobile-Pages#137]
It appears it's not showing my active menu for the navigate menu items?    I would assume that it would show those? 
![image](https://cloud.githubusercontent.com/assets/8339071/18925007/0c13f732-8567-11e6-971d-5326a034bc73.png)

**Comment by aashishpahwa** [comment]
It's the same for me. It shows the secondary menu here.

**Comment by ahmedkaludi** [comment]
@rodferris @aashishpahwa 

We have a separate navigation menu for AMP version, You can setup it from Dashboard > Appearance > Menus
