### ISSUE TITLE
Error in the latest version with other themes

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1370]
with 0.9.65.2 all works fine, no errors in debug mode but in latest version .09.66.1 many errors.

error log file is in attachment in helpscout
Ref: https://secure.helpscout.net/conversation/460001105/17846?folderId=1060551

**Comment by ahmedkaludi** [comment]
@zabi332 This one does not help us in the development. Please tell us the Helpscout URL so we can get more details on this issue.

**Comment by zabi332** [comment]
Ref: https://secure.helpscout.net/conversation/460001105/17846?folderId=1060551

**Comment by ajeetku** [comment]
Issue resolved on client side. Issue occurred due to theme customization.
Ref: https://secure.helpscout.net/conversation/460001105/17846?folderId=1060551

**Comment by MohammedKaludi** [comment]
Feedback from the user.

> Hey, i have to say thanks .. i will report this to the theme developer..
many thanks and have a nice day.
Milan
