### ISSUE TITLE
Fatal Error on pages with custom WP_Query Object

### ISSUE THREAD

**Issue by tchibomann** [ahmedkaludi/accelerated-mobile-pages#1372]
Hi all,

got a fatal error, think since the last update. Didn't noticed this until now, but it's a huge problem for me. It appears only on pages with custom WP_Query Object.

Do you know what happens here? Can't find any reason... Before the last update everything was working.

```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /var/www/vhosts/gamerz.one/htdocs/wp-includes/query.php:28

Stack trace:
#0 /var/www/vhosts/gamerz.one/htdocs/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php(404): get_query_var('amp', false)
#1 /var/www/vhosts/gamerz.one/htdocs/wp-content/plugins/accelerated-mobile-pages/templates/features.php(1898): ampforwp_is_amp_endpoint()
#2 [internal function]: ampforwp_the_content_filter_full('<!DOCTYPE html>...', 9)
#3 /var/www/vhosts/gamerz.one/htdocs/wp-includes/functions.php(3721): ob_end_flush()
#4 /var/www/vhosts/gamerz.one/htdocs/wp-includes/class-wp-hook.php(298): wp_ob_end_flush_all('')
#5 /var/www/vhosts/gamerz.one/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#6 /var/www/vhosts/gamerz.one/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /var/www/vhosts/gamerz.one/htdocs/wp-includes/load.php(677): do_action('shutdown')
#8 [internal function]: shutdown_action_hook()
#9 {main}  thr in /var/www/vhosts/gamerz.one/htdocs/wp-includes/query.php on line 28
```

**Comment by ahmedkaludi** [comment]
@tchibomann That's strange, I want to solve this problem immediately!

How can I re-occur this problem on my end?

If you can send us your wp-admin & Ftp on team@magazine3.com we can speedup this process and solve this faster.

**Comment by MohammedKaludi** [comment]
Hey @tchibomann,

Can you please apply the fix added in the commit and test it. So, we can make sure the issue gets fixed when we push the update this weekend.

Thank you,
Mohammed Kaludi

**Comment by MohammedKaludi** [comment]
Closing the ticket, above issue mentioned should be fixed after the changes. 
Still no response from the ticket creator.

MK
