### ISSUE TITLE
Add layout="responsive" to image module in page builder

### ISSUE THREAD

**Issue by nacm** [ahmedkaludi/accelerated-mobile-pages#1373]
Currently the image module in page builder builder does not add layout="responsive" within the amp-img.

**Comment by MARQAS** [comment]
@ajeetku @MohammedKaludi I think the Image module should take the default size.
How can one know the size of all the images? We should give an option to override the default size, so users can control the size only if they want.

**Comment by MARQAS** [comment]
Currently, we are giving an option to enter the size and that is by default 150x150 which is too small. for an image in content. And it can become a headache for some users.

What are your thoughts on this? @ahmedkaludi @ajeetku @MohammedKaludi
