### ISSUE TITLE
Featured Image from The Content

### ISSUE THREAD

**Issue by Dawars** [ahmedkaludi/accelerated-mobile-pages#1375]
Hi,
Under 'Advanced', I turned on 'Featured Image from The Content' which works as expected on the home page but even though 'Duplicate Featured Image' is off the featured image is shown on the single pages which makes it duplicated.

I'm using the  0.9.66.1 version of the plugin

p.s Thank you for continuously improving the plugin

**Comment by MohammedKaludi** [comment]
Updated code for inline related posts images with all image modification controls e74e42426aff6a40d9ebdde4ec272d0bc4d8cf05

**Comment by MohammedKaludi** [comment]
@Dawars thank you for your feedback, we have improved the code and it should now fix the image issue. 
Planning to push the code in the next update. Which will be pushed on Saturday.

Thank you,
Mohammed Kaludi
