### ISSUE TITLE
Problem with Displaying Tables with design 2

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1376]
Only 2 out of 3 table columns are shown in design 2 but tried with Design 1 and Design 3 the table is working fine,  

Ref: https://secure.helpscout.net/conversation/460983361/17922?folderId=1060551

**Comment by MARQAS** [comment]
Update from user: The issue is resolved in the last update.

**Comment by MohammedKaludi** [comment]
Reply from the User 

> Hello Marqas, 
The issue is resolved!. After the latest update the plugin is working absolutely fine.
Thank you so much for resolving the issue on a priority.
Best Regards,
Chaitanya
