### ISSUE TITLE
Youtube Shortcode embed with &rel=0 support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1378]
I’ve been having some issues embedding youtube videos with shortcodes using your plugin. Also unable to get the ‘&rel=0’ to disable related videos to work.
I suspect ‘&rel=0’ is part of the problem.

A short url like [youtube https://youtu.be/idididid&rel=0] does not work in AMP. The ‘&rel=0’ at the end seems to confuse the parsing of the video id and the plugin generates a wrong video id and no video is shown in the AMP page
<amp-youtube data-videoid="wrongid" layout="responsive" width="1000" height="563"></amp-youtube>

removing ‘&rel=0’ in the shortcode fixes the problem but then you get related videos both in your regular and in your AMP pages.

Using full url format in the shortcode like this:
[youtube https://www.youtube.com/watch?v=idididid&rel=0]
Works, however the generated AMP page is missing the data-param-rel=”0″

Thanks in advance!

REF: https://wordpress.org/support/topic/youtube-shortcode-issues/

**Comment by MohammedKaludi** [comment]
:+1:
