### ISSUE TITLE
How to ad AMP Ads on Custom Homepage?

### ISSUE THREAD

**Issue by anirudhpulikonda** [ahmedkaludi/accelerated-mobile-pages#1379]
My client has a Static Homepage and set the same for AMP homepage in the settings. Can anyone guide how to add Ads on Pages so that the homepage has ads in it?

**Comment by ahmedkaludi** [comment]
@anirudhpulikonda where exactly would you prefer to add the Ads, with in the content or any other location. Please let us know.

**Comment by anirudhpulikonda** [comment]
@ahmedkaludi Yeah, within the content for pages.

**Comment by anirudhpulikonda** [comment]
@ahmedkaludi 
[update] Ads are working on AMP pages when using Advanced AMP ads.

Issue: But not working on the page which is set as HomePage in the settings.

**Comment by ahmedkaludi** [comment]
@MohammedKaludi @MARQAS let's test this in the next update then.

**Comment by MARQAS** [comment]
@anirudhpulikonda 
Q1) Have you enabled the Custom Frontpage option from AMP options Panel?
Q2) Can you tell me which version of the Advanced AMP Ads are you using?

If you have already enabled the option and using the latest version, can you please try to make some change in the code? 
In ad-1.php file try to change the is_front_page() to  ampforwp_is_front_page() and check if that Ad is working or not on your Custom Frontpage.

**Comment by anirudhpulikonda** [comment]
@MARQAS 

A1) Yes, I've enabled the custom frontpage option and selected my homepage which I'm willing to display for domain.com/amp
A2) using the latest 0.6.80. 

Also using Advanced AMP ads. The ads are displaying on pages like " contact us ", " disclaimer ", " privacy policy " and other pages except for the page that I set on the homepage. 

Will check the ad-1.php hook and I'll confirm you.

**Comment by anirudhpulikonda** [comment]
@MARQAS Here's a test that I've done which might help you understand what is blocking the ads to display on HomePage

This test is performed on a fresh copy of wordpress with Amp For Wp + Advanced Ads Installed.

1. I've made a sample page and set it as homepage on AMP Settings.

![screenshot 14 _li](https://user-images.githubusercontent.com/20200408/32795892-2058d9f8-c993-11e7-8247-f085e847d36d.jpg)

2. Enabled an In content ads which should display after 3 paragraphs in advanced amp ads.

![screenshot 11 _li](https://user-images.githubusercontent.com/20200408/32796021-7dd4684a-c993-11e7-89a5-3d7a4c249c8f.jpg)

3. Ad is displaying perfectly, as it should on Homepage when it is set to custom page ( sample page in this test )

![screenshot 15](https://user-images.githubusercontent.com/20200408/32795995-6a237e1c-c993-11e7-95e8-fc597d1b25d8.png)

4. Later, I've set the same page as a static homepage for my non-amp version of the site. Which is normal because having a static page created the need for amp static homepage.

![screenshot 12 _li](https://user-images.githubusercontent.com/20200408/32796188-05925774-c994-11e7-8647-a5442d123ad1.jpg)

5. Now, the ad stopped displaying.

![screenshot 13](https://user-images.githubusercontent.com/20200408/32796235-29c05f7e-c994-11e7-8181-cac2ead88a64.png)

I think Wordpress Static Homepage setting is messing something up with Advanced AMP Ads. Hope this info helps.

**Comment by MARQAS** [comment]
It was due to is_front_page in Advance AMP Ads which has been changed to ampforwp_is_front_page.
@anirudhpulikonda We are going to release an update of Advanced AMP Ads very soon. Please wait for it or you can change the code.

And Thank you so much for reporting this issue

**Comment by MohammedKaludi** [comment]
This has been fixed in the advanced amp ads plugin and will be pushing the update on Tuesday or Wednesday.

**Comment by anirudhpulikonda** [comment]
Hi @MohammedKaludi 

Any update on this?
