### ISSUE TITLE
Error to display the homepage

### ISSUE THREAD

**Issue by Aurelien-1clickweb** [ahmedkaludi/accelerated-mobile-pages#1381]
Hello Team

When I set up the AMP module for wordpress, I selected a home page. This one is the same as on my site. But on the display, it is the page about which is displayed.

Could you tell me if this problem has already occurred? And how to correct it?

Thank you in advance for your assistance.

Best regards

Aurelien

**Comment by ahmedkaludi** [comment]
Hi @Aurelien-1clickweb I didn't quite get your question. Can you please elaborate it? 

This place is for the technical bugs, please ask support questions at https://wordpress.org/support/plugin/accelerated-mobile-pages/
