### ISSUE TITLE
The menu is not displayed on the smartphone browser

### ISSUE THREAD

**Issue by Aurelien-1clickweb** [ahmedkaludi/accelerated-mobile-pages#1382]
Hello Team

I selected the menu in the advanced settings of the AMP module for WP but it is not displayed in the browser of the smartphone.

Could you tell me how to make this menu appear?

Thank you in advance for your help.

Best regards

Aurelien

**Comment by ahmedkaludi** [comment]
@Aurelien-1clickweb can you please share the URL? We haven't faced this issue. 

Please understand that this place is for the validated issues and feature requests. If you have a support question, you need to ask at https://wordpress.org/support/plugin/accelerated-mobile-pages/

**Comment by Aurelien-1clickweb** [comment]
Hi Ahmed

The URL is https://www.1clickweb.fr

Best regards

Aurélien NOLLET

[cid:image001.jpg@01D35C64.29C3D020]

De : Ahmed Kaludi [mailto:notifications@github.com]
Envoyé : dimanche 12 novembre 2017 16:47
À : ahmedkaludi/accelerated-mobile-pages <accelerated-mobile-pages@noreply.github.com>
Cc : Aurélien Nollet <contact@1clickweb.fr>; Mention <mention@noreply.github.com>
Objet : Re: [ahmedkaludi/accelerated-mobile-pages] The menu is not displayed on the smartphone browser (#1382)


@Aurelien-1clickweb<https://github.com/aurelien-1clickweb> can you please share the URL? We haven't faced this issue.

Please understand that this place is for the validated issues and feature requests. If you have a support question, you need to ask at https://wordpress.org/support/plugin/accelerated-mobile-pages/

**Comment by Aurelien-1clickweb** [comment]
Hi Ahmed

Here is the URL of the site concerned : https://www.1clickweb.fr

Best regards and thank you in advance for your help.

Aurélien NOLLET

[cid:image001.jpg@01D35F86.E7083ED0]

De : Ahmed Kaludi [mailto:notifications@github.com]
Envoyé : dimanche 12 novembre 2017 16:47
À : ahmedkaludi/accelerated-mobile-pages <accelerated-mobile-pages@noreply.github.com>
Cc : Aurélien Nollet <contact@1clickweb.fr>; Mention <mention@noreply.github.com>
Objet : Re: [ahmedkaludi/accelerated-mobile-pages] The menu is not displayed on the smartphone browser (#1382)


@Aurelien-1clickweb<https://github.com/aurelien-1clickweb> can you please share the URL? We haven't faced this issue.

Please understand that this place is for the validated issues and feature requests. If you have a support question, you need to ask at https://wordpress.org/support/plugin/accelerated-mobile-pages/

**Comment by ahmedkaludi** [comment]
@Aurelien-1clickweb  was this issue resolved?
