### ISSUE TITLE
Display Child or sub categories on Category pages.

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1385]
Ref: https://secure.helpscout.net/conversation/462529357/18012?folderId=1680011

Screenshot> Currently we display like this >  http://take.ms/lPF97 but user want to display the sub category also on this page like > http://take.ms/k8HT5

**Comment by ahmedkaludi** [comment]
I think an option in the archives section would make sense.

**Comment by MohammedKaludi** [comment]
:+1:
