### ISSUE TITLE
Strip the short codes from Structure data area

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1389]
Screenshot > http://take.ms/FdH7I

URL >http://automotionapp.com/bill-cole-ford/amp/
 view-source:http://automotionapp.com/bill-cole-ford/amp/

Ref: https://secure.helpscout.net/conversation/459451630/17809?folderId=1514170

**Comment by MohammedKaludi** [comment]
:+1:
