### ISSUE TITLE
Facebook Sharing Not working 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#139]
Facebook Sharing Not working  - IT needs APP id

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi 
Yeah, I actually already added the issue #107 for this, with a fix in pull request #120.

**Comment by MohammedKaludi** [comment]
Pull merged  https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/pull/120

**Comment by MohammedKaludi** [comment]
Issue Fixed
