### ISSUE TITLE
Line number 1024 on features.php - Preg_replace a tag issue

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1392]
does not show images and content in the new update.

Line number may vary. Here is the precise code in features.php. If you comment it out: then the issue will be resolved:

```
  // Removing text-align, center, font-size from the a tag
 $content = preg_replace('/<a (href=".*?")(.*?)(rel=".*?").*?(text-align:=".*?").*?(center=".*?").*?(font-size:=".*?")>/', '<a $1 $3>', $content);
```

Ref: https://secure.helpscout.net/conversation/457958255/17673?folderId=1060551
Ref: https://secure.helpscout.net/conversation/463972956/18085?folderId=1060556
Ref: https://secure.helpscout.net/conversation/463480219/18063?folderId=1060551
Ref: https://secure.helpscout.net/conversation/464357752/18106?folderId=1060551

**Comment by mayanksharma9033** [comment]
I agree with @zabi332  User reported this issue on the helpscout that post content is not showing on some of posts after latest updation .

ticket no:- https://secure.helpscout.net/conversation/463444730/18062?folderId=1680011

I have tested out on my localhost and find the solution that, when I commented these three lines in the feature.php file of line no 999, 1000 and 1002  it will resolve.

999)  $content = preg_replace('/<a (href=".*?")(.*?)(target=".*?")(.*?)(sl-processed=".*?")>/', '<a $1$3>', $content);

1000.)   $content = preg_replace('/<a (href=".*?")(.*?)(rel=".*?")(.*?)(sl-processed=".*?")>/', '<a $1$3>', $content);

1002.)  $content = preg_replace('/<a (href=".*?")(.*?)(rel=".*?").*?(text-align:=".*?").*?(center=".*?").*?(font-size:=".*?")>/', '<a $1 $3>', $content);

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by jorgitobg** [comment]
This issue persist on your 0.9.69.1 version.... and its very anonying.
AGAIN back to 0.9.64 version .
