### ISSUE TITLE
Post Builder compatibility with the Hueman theme

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1393]
Post builder is not working in hueman theme nothing appears other than "save and publish" and when I hit save then redirecting to customize page

Ref: https://secure.helpscout.net/conversation/461638935/17969?folderId=1060551

**Comment by ajeetku** [comment]
For Resolve the issue with hueman theme
hueman\functions\czr\class-czr-init.php make line no:- 508
 if ( 'wp' == current_filter() ){
              global $wp_customize;
             $this -> hu_customize_factory (
                $wp_customize,
                $this -> hu_customize_arguments(),
                $_map
            );
     $wp_customize -> get_panel('widgets') -> title = __('Dynamic Sidebars and Widgets', 'hueman');
}

because some time $wp_customize is empty

**Comment by MohammedKaludi** [comment]
Reported to Hueman theme author. Closing the ticket.
