### ISSUE TITLE
Bold letters not having space

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1395]
copy the content from the pastebin > https://pastebin.com/nKZzEDcv and then ON the "Minify AMP Page" option then check that page, Look like this > http://take.ms/M8bom, there no space on the bold letters (before & after), if turn OFF the minify option, Problem was solved. So, we need to resolve this issue.

**Comment by MohammedKaludi** [comment]
:+1:
