### ISSUE TITLE
Optimize AMP Queries to load on only AMP pages 

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#1397]
Optimize AMP Queries to load on only AMP pages 
there is many queries are loaded on NON-AMP pages And takes too much time : [Query monitor Plugin](https://wordpress.org/plugins/query-monitor/)

![non- amp page amp queries started](https://user-images.githubusercontent.com/19512210/32658739-72600b18-c641-11e7-81c8-8c0fa8df7964.png)

**Comment by ahmedkaludi** [comment]
Here are some more findings behind the reason: 

 [ Photo ]
![image](https://user-images.githubusercontent.com/16532359/32662656-4b3a64ce-c651-11e7-8138-fbbccd613a56.png)

 All 300+ SELECT queries are related to each of the 300+ posts belonging to "Analisis" category.

For example "SELECT * FROM wp_posts WHERE ID = 85393 LIMIT 1" => 85393 is one of the 300+ posts with category Analisis

 If I untick that option, AMPforWP makes only 6 queries

We need to rework that 'exclude' option... It is not every efficient to make 
exclude' option... It is not every efficient to make a SELECT for *each* excluded post... a single query should be enough to know if it belongs to an excluded category, shouldn't it?

**Comment by teknofilo** [comment]
Even when there are no categories excluded, there are still queries related to WPforAMP

![teknofilo - 2017-11-10 - 008](https://user-images.githubusercontent.com/17863900/32670592-886b4230-c644-11e7-8721-08d749d3cec2.jpg)

![teknofilo - 2017-11-10 - 011](https://user-images.githubusercontent.com/17863900/32670644-b6f6ef00-c644-11e7-9d6d-789ba170ab89.jpg)
![teknofilo - 2017-11-10 - 010](https://user-images.githubusercontent.com/17863900/32670645-b710f7ba-c644-11e7-9b11-94adf74524f2.jpg)
![teknofilo - 2017-11-10 - 009](https://user-images.githubusercontent.com/17863900/32670646-b72b795a-c644-11e7-824f-d815f8750cc3.jpg)

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/525869215/21884?folderId=1060551

**Comment by teknofilo** [comment]
I still see some queries in non-AMP pages:

![teknofilo - image 001](https://user-images.githubusercontent.com/17863900/43310953-5b3f5dbc-9189-11e8-96e1-7f2521c2b61f.jpg)

**Comment by Zabi09** [comment]
@teknofilo 
We are extremely sorry for the inconvenience, Will you please share your wp-admin and FTP details on this email - team@magazine3.com and I will personally look into your issue and I make sure it will be fixed as soon as possible.

Please let me know and I will do everything to fix this issue.

**Comment by Zabi09** [comment]
@teknofilo 
Are you using the latest version and still having the same issue? Have you contacted us on team@magazine3.com? I have checked all the emails but unable to find it please let us know.

**Comment by teknofilo** [comment]
Thanks, that does not seem to be a problem now.

 

The problem I am experiencing now is that my Adsense banner below the Header is not centered. I am using the Advances AMP Ads Plugin. For example, here: https://www.teknofilo.com/el-sony-xperia-xz2-premium-llega-con-un-peso-y-grosor-fuera-de-lo-comun/amp/

 

Can you have a look?

 

Luis

**Comment by teknofilo** [comment]
BTW I have restored AMP Ads Plugin v1.9.9 and is centered again, so there must be a problem with v1.9.10

 

From: Luis Aguilar <teknofilo@teknofilo.com> 
Sent: lunes, 1 de octubre de 2018 22:05
To: 'ahmedkaludi/accelerated-mobile-pages' <reply@reply.github.com>; 'ahmedkaludi/accelerated-mobile-pages' <accelerated-mobile-pages@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [ahmedkaludi/accelerated-mobile-pages] Optimize AMP Queries to load on only AMP pages (#1397)

 

Thanks, that does not seem to be a problem now.

 

The problem I am experiencing now is that my Adsense banner below the Header is not centered. I am using the Advances AMP Ads Plugin. For example, here: https://www.teknofilo.com/el-sony-xperia-xz2-premium-llega-con-un-peso-y-grosor-fuera-de-lo-comun/amp/

 

Can you have a look?

 

Luis

**Comment by Zabi09** [comment]
@teknofilo 
Sorry for the delay in response, Will you please download the latest version that is 1.9.10.1 of Advanced AMP Ads extension and check once and if you still have issues then please contact us directly on team@magazine.com and we will make sure it will work perfectly in the latest version.
