### ISSUE TITLE
Publishing date problem on AMP post

### ISSUE THREAD

**Issue by marcogian** [ahmedkaludi/accelerated-mobile-pages#1398]
In single post on top of the single article (meta info) it shows "post_modified_gmt" date instead of "post_date_gmt".

**Comment by pegazee** [comment]
Hi @marcogian ,

Thank you so much for creating the ticket, we'll resolve this issue ASAP.

**Comment by MohammedKaludi** [comment]
Yes, valid issue and has been fixed :+1:
