### ISSUE TITLE
Junk "Listing" in Navigation Menu

### ISSUE THREAD

**Issue by Asif2BD** [ahmedkaludi/Accelerated-Mobile-Pages#14]
Look at this [screen-2](https://www.dropbox.com/s/2g1lq8rmgzd74o3/Screenshot%202016-07-05%2003.53.55.png?dl=1). Somehow the Navigation Menu creating this useless junk menu. Not sure what they are. They are not real page or post. And I do about 50 of them in source code, linked like this

https://domain.tld/listings-12/
https://domain.tld/listings-20/
https://domain.tld/listings-30/
.....

It could be caused by some other plugin as well. Let me know how I could help to debug.

**Comment by ahmedkaludi** [comment]
Hey Asif,

To me, it looks like you had used some plugin which has created a post type called listings but if that was the case, then it shouldn't display that post type in the default loop. 

Can you list down which plugins you are using at the moment?

That'll help me understand the issue.


Thanks,
Ahmed

**Comment by Asif2BD** [comment]
It seems the plugin responsible for it is "[Fetch Tweets](https://wordpress.org/plugins/fetch-tweets/)".

Still not sure how that could come in default category & page list loop. I will try to look deep as well.

**Comment by ahmedkaludi** [comment]
I see... I don't know if there is something that we can do to exclude it. What are your thoughts?

**Comment by ahmedkaludi** [comment]
I'll leave it for a week to hear your thoughts. After that, I will have to close this in order to manage issues properly.

I hope you understand.

**Comment by Asif2BD** [comment]
I found the issue, its not related to this plugin. Closing this.
