### ISSUE TITLE
Compatibility with new WP widgets

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1400]
They should get converted to respected AMP components

**Comment by ahmedkaludi** [comment]
@MARQAS new?

**Comment by MohammedKaludi** [comment]
Yes these new widgets are coming from WP 4.9 version

**Comment by MARQAS** [comment]
Yup, By new widgets I meant 4.9 widgets

**Comment by beingsmart3** [comment]
Category Widget is not performing the action.

Ref: https://secure.helpscout.net/conversation/632971076/31371/

**Comment by MARQAS** [comment]
All the widgets should work fine now. 
@RajuJeelaga can you give another glance at this?

**Comment by pegazee** [comment]
AMP Audio and AMP video are throwing the errors of Invalid URL protocol 'http:' for attribute 'src'.
-> We can remove the https and http like in the forms to avoid the validation errors. @ajeetku and @MARQAS  what do you say about this idea?

**Comment by pegazee** [comment]
I've tested these widgets in design 1,2,3 and swift theme. For archive and categories widgets, In D-1,2,3 getting "The tag 'FORM [method=GET]' requires including the 'amp-form' extension JavaScript" validation error. Screenshot > https://monosnap.com/file/5WNbXcisEiPGryymc3dZEPnueVG7Zb.

And for the swift theme, all widgets output are not in proper styling. Screenshot > https://monosnap.com/file/HaQSfzQ2lIJuCMclRA11B1LlQDsor9. As we can see in the D-1,2,3 styling are loading properly. Screenshot ( D-1 )> https://monosnap.com/file/IyLETXtVZLhllSQGIbAy7SojcbCYJe

**Comment by MARQAS** [comment]
We are not adding any styles for sidebars, In design1 2 3, it is taking the default designs, but not in Swift. 
Any solution for this @RajuJeelaga and @ahmedkaludi?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
@MARQAS, once @RajuJeelaga completes his work. Please check the code and add escaping to the text domain (https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8bfc9c24adbd97d414ec501d231726d1e700730e#diff-6aa5512f7dd8d5ce60fc97b0f340912cR5390) and if it is ready then add it directly into Approval Pipe so we can push it immediately.

**Comment by MohammedKaludi** [comment]
merged and will be pushed in 0.9.97.24

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.24
