### ISSUE TITLE
Debug Errors after 0.9.68

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1403]
FB like button error, I wasn't able to cache the screenshot

**Comment by mayanksharma9033** [comment]
please see the screenshots: 1) http://take.ms/os1Vg
2) http://take.ms/IO1bl
3) http://take.ms/pHaTo
4) http://take.ms/Xk3uR

**Comment by MARQAS** [comment]
I am unable to recreate the FB like button error. Maybe it was due to the URL option which we used in the 1st edition. If anyone finds it then please let me know. :)

**Comment by MohammedKaludi** [comment]
:+1:
