### ISSUE TITLE
OneSignal Push Notifications not working!

### ISSUE THREAD

**Issue by anirudhpulikonda** [ahmedkaludi/accelerated-mobile-pages#1404]
I've enabled push notifications and configured with right APP ID when it first released in 0.9.67

But unfortunately, I'm not seeing any popup to subscribe to notifications. Even in 0.9.68 update also, I'm not getting any popup.

Can you guys look into this? Thanks in advance!

**Comment by MohammedKaludi** [comment]
Hey @anirudhpulikonda,

We have fixed some issues that were seen for push notifications in the last update.
Can you please share the url of the site where you are adding?

Thanks,
Mohammed Kaludi

**Comment by anirudhpulikonda** [comment]
Hey @MohammedKaludi 

URL: https://www.watchmetech.com/

After 0.9.69 update also I'm not seeing any popup to the user which lets him subscribe to Onepush. I'm also seeing a weird URL popping up in my analytics whenever my readers open my blog's amp pages.

**Comment by MohammedKaludi** [comment]
This is strange, I can see the code is being added by out plugin http://take.ms/UK8SB and http://take.ms/55XIJ

But not sure why it is not triggering? Can you please pass me the login-info at team@magazine3.com so I can check the settings and find out why it is not triggering?

Thank you,
Mohammed kaludi

**Comment by anirudhpulikonda** [comment]
@MohammedKaludi I'm sharing the credentials via the email above-mentioned.

Please let me know the changes you've done after fixing the issue. 

Also, can you look into one more issue I was facing for many months with amp for wp? 

My server supports New relic tracking, but all others WordPress sites on my server removes new relic script when ampforwp is used. But, the current site which we're discussing doesn't bypass the new relic script and I'm facing validations issues.

**Comment by MARQAS** [comment]
@anirudhpulikonda Can you share the URLs of where you are having validation issues?

**Comment by anirudhpulikonda** [comment]
@MARQAS the same site which we're discussing here. URL: https://www.watchmetech.com/

I've sent the credentials via email. As of now, I've disabled the New Relic on my server, because this application is not able to disable the New Relic script when it's enabled.

So, If you can also look into this issue, I'll be very thankful. Please, let me know after fixing Onesignal issue so that I can enable New Relic in order check the issue.

**Comment by VizeyeBasvur** [comment]
Please inform in case any progress achieved. I have the same issue, Redirect plugin sees many of my some amp links that contains onesignal app id as 404.

**Comment by MARQAS** [comment]
It is working properly now. 
@anirudhpulikonda and @VizeyeBasvur You guys can clone this branch or can wait for Saturdays update.

**Comment by MARQAS** [comment]
Thank you so much for reporting this and supporting us

**Comment by anirudhpulikonda** [comment]
Thanks @MARQAS for looking into the issue, I'll wait for the update. BTW, my New Relic Script issue on AMP also fixed, It was Glue by Yoast which is causing the trouble. Once, Again thanks a ton for fixing issue with Advanced AMP Ads here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1379

**Comment by zabi332** [comment]
Ref: https://secure.helpscout.net/conversation/468321252/18320?folderId=1060556

**Comment by MohammedKaludi** [comment]
Push notification is working properly and above fix is tested on multiple sites.
Closing the ticket.
