### ISSUE TITLE
Facebook like Button improvements

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1405]
- [x] There's is no need for the URL field, so remove it, It's supposed to take non-amp url of current page.

- [x] make it look square and default look

**Comment by MARQAS** [comment]
@ahmedkaludi There is indeed a need for absolute URL. 
https://www.ampproject.org/docs/reference/components/amp-facebook-like
It is not for to like the current page but to like the Facebook page.

**Comment by ahmedkaludi** [comment]
@MARQAS Obviously, URL is needed. But Like I said, The URL must be the non-AMP's the_permalink!

**Comment by MARQAS** [comment]
Discussed internally, we will have the current post URL instead of the Facebook Page URL.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by gigidawg** [comment]
Can we have an option between the 2? On some sites I'd like the original implementation (like the facebook page) and on other, I like the new implementation (like the current page).

It'd be great if we could switch and choose between the 2 options. Thanks!
