### ISSUE TITLE
Date Format under Homepage improvements

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1408]
- [x]  It should be in global not in homepage

- [x]  It should be in the drop-down menu not a switch buttons it must have options like 

1 - ago
2 - Traditional view 

- [x] Changing in different languages such as " 2 days ago " is properly written in Spanish as  "ago 2 days".

Ref: https://secure.helpscout.net/conversation/465868073/18191?folderId=1060551

**Comment by MohammedKaludi** [comment]
To achieve dates as Spanish as "ago 2 days".
1. Delete the AGO from translation settings http://take.ms/ihakQ
2. Add the below css in custom css area.

`.featured_time:before {
    content: "ago ";
}`

Result: http://take.ms/7PGXm 

This should fix the Spanish language issue.

**Comment by MohammedKaludi** [comment]
Homepage and archive pages should reflect the date changes as well.

**Comment by MohammedKaludi** [comment]
Homepage and archive pages should reflect the date changes as well.

**Comment by MohammedKaludi** [comment]
Now working. :+1:
