### ISSUE TITLE
tracking the specific amp pages using Google Analytics.  

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1409]
we need to do some modifications so that the data can be recorded accurately. One of our users found the following documentation from Google:

https://support.google.com/analytics/answer/7486764

https://support.google.com/analytics/answer/6343176?hl=en&ref_topic=7378717

We need to add this to our plugin.

**Comment by MARQAS** [comment]
I created a post and add a new gallery to it and its working. I was able to find only one issue and that is 'space'

**Comment by MARQAS** [comment]
https://ampforwp.com/tutorials/article/set-google-amp-client-id-api/

**Comment by MohammedKaludi** [comment]
:+1:
