### ISSUE TITLE
Filter for Excerpt custom text in the AMP options

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1411]
Need to create the filters for Excerpt custom text in the AMP options without updating in the core.

Ref: https://secure.helpscout.net/conversation/464248327/18101?folderId=1060551

> How to remove tripple dot from excrpt

**Comment by MohammedKaludi** [comment]
ampforwp_modify_index_content filter added
so, if the user wants to remove the triple dot or modify any other thing he can use the above filter.
1411.

`
add_filter('ampforwp_modify_index_content', 'prefix_modify_index_content');
function prefix_modify_index_content( $content){
	return wp_trim_words( strip_shortcodes( $content ) ,  15, '  ' );
}`
