### ISSUE TITLE
Suggestion: Allow Hometitle to be changed from Translation Panel

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1414]
Right now, if you want to change the home title ($home_title), you need to edit the file bread-crumbs.php, and with every update the file is overwritten to default value. I suggest to allow to change it from the Translation Panel.

REF: https://wordpress.org/support/topic/suggestion-allow-hometitle-to-be-changed-from-translation-panel/

**Comment by MohammedKaludi** [comment]
:+1:
