### ISSUE TITLE
Remove the Separator "|" from the footer when "Back to Top link" is off

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1417]
Ref: http://take.ms/5loCx

**Comment by MohammedKaludi** [comment]
Back to top link and Link to Non-AMP page in Footer controls not working properly in D2 and D3

**Comment by MohammedKaludi** [comment]
@MARQAS Turn-on this control and check http://take.ms/Sr415

Whole area is turning off
