### ISSUE TITLE
Category base removal in AMP from url option is only working on the first page

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1418]
If we remove the category from our URL in non-amp and category base remove in AMP is enable then only first page in the category is working if we go to the next page then it is redirecting to the same first page.

Ref: https://secure.helpscout.net/conversation/462700270/18015?folderId=1060551

**Comment by zabi332** [comment]
One More - 
Ref: https://secure.helpscout.net/conversation/435531397/16347/

**Comment by MohammedKaludi** [comment]
:+1:  tested and its working correctly
