### ISSUE TITLE
WPBakery Page Builder Conflict

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1419]
I am using Accelerated Mobile Pages on a website that uses Jupiter WordPress Theme (already reached out to them). They are using a modified version of WPBakery Page Builder and I did a test with a standard WPBakery Page Builder and it works like it should. The only functions that seem to work is Copy, Delete and Add Text block.

Did the F12 and console isn’t reporting any conflicts. Any thoughts on what is causing it to disable the functionality for the builder?

REF: https://wordpress.org/support/topic/conflict-with-wpbakery-page-builder/#post-9687823

**Comment by MohammedKaludi** [comment]
Added the code in customers site and it is working correctly https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/62745b43deb1f54f883ed51c145fcb63c39695c7
