### ISSUE TITLE
New relic Support

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/Accelerated-Mobile-Pages#142]
New relic Support

**Comment by nicholasgriffintn** [comment]
Forgive me if I am wrong, but I'm pretty sure that New Relic isn't supported with AMP, you have to disable it for AMP pages. Well that's how it was when I looked a short time ago, I'm unsure if the AMP team have added that feature yet.

**Comment by MohammedKaludi** [comment]
Yes, it is not supported, we have to manually disable it as you mentioned. 

We are going to add that feature in our version. So users can disable if they want.

This will be added in next version. 

Also planning to merge few pull requests tonight.
