### ISSUE TITLE
AMP Compatibility with Unyson plugin

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1420]
Need to create AMP compatibility with the Unyson plugin because if we create anything by the unyson page builder then only the code is displaying in the AMP version

Ref: https://secure.helpscout.net/conversation/465829806/18189?folderId=1060551

**Comment by ahmedkaludi** [comment]
@zabi332 That's not a correct ticket. You can't just create a ticket for every page builder support out there.

**Comment by Zabi09** [comment]
Tested on my end and now the content is appearing perfectly in the amp as well - http://take.ms/BPEOO
