### ISSUE TITLE
AMP theme framework declaration 

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1421]
If you install the theme based on ATF without the core then there should be a notification to install the plugin along with documentation and it should be very easy.

Ref: https://secure.helpscout.net/conversation/467711986/18291?folderId=1060551

**Comment by zabi332** [comment]
This should be done within the theme not the core

**Comment by MARQAS** [comment]
@RajuJeelaga

**Comment by MohammedKaludi** [comment]
@RajuJeelaga  ask @ahmedkaludi about this one

**Comment by MohammedKaludi** [comment]
This ticket is related to child themes that are created on top of Accelerated Mobile Pages plugin. 

So Closing it from here.
