### ISSUE TITLE
Gallery inside the post is not working properly

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1422]
[gallery ids="771,770,769,768,767,766,757,759,758,760,761,762,807,763"]

added the gallery with above code and this is the output 

![japanese version of single post this is the title new](https://user-images.githubusercontent.com/16618009/32881011-b39dbc4a-cad5-11e7-91fd-704b9aac6c19.png)

but if i remove the filter it works fine
 `add_filter('amp_gallery_image_params','ampforwp_gallery_new_params', 10, 2);`

**Comment by osseonews** [comment]
How do we add or remove this filter? We have the same problem. Our image galleries no longer show on AMP. What should we add to our functions file for this to work again? We tried remove_filter('amp_gallery_image_params','ampforwp_gallery_new_params', 10, 2); - but that didn't work.

**Comment by MARQAS** [comment]
I just checked and that was due to wpautop filter. p tag is getting added before the carousel which is breaking the whole code of it. 

Just press enter before the gallery and the problem will be resolved

**Comment by MohammedKaludi** [comment]
Yes, wpautop is interfering with gallery output, so the solution found was if we press enter or give some space between gallery code and the text then `</p>` will be ended above the amp-carousel not inside the amp-carousel 

Mohammed Kaludi
