### ISSUE TITLE
Conflicts with Foogallery

### ISSUE THREAD

**Issue by osseonews** [ahmedkaludi/accelerated-mobile-pages#1424]
We use Foogallery to create image galleries on our website (https://wordpress.org/plugins/foogallery/) However, on our AMP pages the Foo Galleries are not displayed anymore when we use the shortcode. Example, regular page: https://www.osseonews.com/challenge-concavity-implant-site/ – see the gallery at end of post, and and the AMP page: https://www.osseonews.com/challenge-concavity-implant-site/amp/ None of the images show up. Just grey lines. In viewing the source code, it’s clear that none of the images are even in the code.

I was looking at the code and apparently, the entire HTML output for displaying images in Foogallery has changed with the latest release, so now for example instead of using SRC attribute to show an image, they use: data-src-fg in the img tag. My guess is that AMP has no clue this is an image because they don’t have the attributes your plugin is looking for in this tag. Which part of your code reformats images so they display in AMP? We’ll have to fix that code so that it properly displays images from Foogallery.

How do you suggest we fix this so that AMP recognizes the images from the gallery?

**Comment by MohammedKaludi** [comment]
@osseonews thank you for reporting the issue to us.
Yes, you are right it is because FooGallery guys have changed the structure and we are working on the solution.

I hope we will be able to fix the issue in the next update which releases every Saturday.

**Comment by zabi332** [comment]
One More with the same FooGallery issue

Ref: https://secure.helpscout.net/conversation/473357949/18586?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1: Working as expected
