### ISSUE TITLE
Logo height & width should dynamically used from the Logo

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#1429]
So, if I upload an image of 150 x 56. Then the it should not have 190 x 36 by default. http://take.ms/d2l8o

over riding the size is different thing but when i upload the correct size, the code should automatically adapt to my image.

**Comment by ahmedkaludi** [comment]
@MARQAS I have tested this and this one is not working. Have you tested this?

**Comment by ahmedkaludi** [comment]
we have spent aloooot of time on this. The logo uploading is now really good, but only thing we're having minor gaping in edge cases.

Other than, the problem that we wanted to solve is almost solved.
