### ISSUE TITLE
compatibilty with Envira Gallery Lazy Loading

### ISSUE THREAD

**Issue by romalino** [ahmedkaludi/accelerated-mobile-pages#1432]
Hello,

I use the Envira plugin to display my image galleries and when I activate the lazy load, the images don't load (logic).

I don't know who has to do anything, whether it's Envira or you, but it would be really cool if it worked.

**Comment by ahmedkaludi** [comment]
@romalino sure, Please send us the copy of Envira gallery on team@magazine3.com and we will see what we can do.

**Comment by romalino** [comment]
Ok thanks !!
It's done, I e-mailed you the archive.

**Comment by MohammedKaludi** [comment]
https://secure.helpscout.net/conversation/471166378/18429/?folderId=1060556

**Comment by MohammedKaludi** [comment]
not able to test the issue properly, on my system. I'm not able to recreate the issue. So, not closing it until properly tested.

**Comment by romalino** [comment]
Hello,
I just tested it by copying the extract from the last commit.
I've set `define(' ENVIRA_DEBUG', true);` in wp-config. php, it works !
Without the ENVIRA_DEBUG=true, Envira loads a transient and does not regenerate the gallery on the fly.
It may be detrimental to performance but at least it works !
