### ISSUE TITLE
Screw up

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1436]
AMP Menus with accented characters all mucked up and showing gibberish.  

Images in description box of tag pages all screwed up and floating full size across the page.

FIX REQUIRED URGENTLY

Using this filter for description text but a style is being forced in via javascript.  html links etc are fine but images are not being bound by their container.

foreach ( array( 'pre_term_description' ) as $filter ) {
    remove_filter( $filter, 'wp_filter_kses' );
}
foreach ( array( 'term_description' ) as $filter ) {
    remove_filter( $filter, 'wp_kses_data' );
}

**Comment by ahmedkaludi** [comment]
@Frenchomatic We're going to push an immediate update today to fix this.

**Comment by MohammedKaludi** [comment]
@Frenchomatic Can you please share the url also we are sanitizing the archive data here https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/design-2/archive.php#L9

> Images in description box of tag pages all screwed up and floating full size across the page.


I'm not able to understand the exact issue and if you please explain a bit we will be able to fix and push the update immediately.

Mohammed Kaludi

**Comment by Frenchomatic** [comment]
OK let me explain about this image issue. I use html in the description box to give my tag pages something on top. Often it is nice to put an image in 

https://goo.gl/N3hfYn

That comes from this source in the description box on a tag page

https://i.imgur.com/JbU9517.jpg

Iam fairly sure it is because a style="width:1024" is being pushed into the source in addition to the width="1024".  When I manually remove the style in firebug all is ok.

**Comment by Frenchomatic** [comment]
One way to partially solve this is to make a class with overflow:hidden and then apply that to the container holding the image in the description box which then flows into get_the_archive_description();. 

<p class="mysecialhidden"><img src=  ....

This kind of works but it is not nice and it is not treating the image like content gets treated in a post or page. 

Do you now see the problem - get_the_archive_description(); contains html (links, styles and images).
