### ISSUE TITLE
loading your CSS just on your plugin’s pages.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1441]
you do not care about loading your CSS just on your plugin’s pages. Could you please change that.

REF: https://wordpress.org/support/topic/your-admin-css-overwrites-default-components/

**Comment by ahmedkaludi** [comment]
This is still in your CSS code which gets loaded on the admin pages of my plugin:

.dashicons-warning, .dashicons-yes{
            font-family: dashicons;
            font-style: normal;
            position: relative;
            top: 1px;
            font-size: 32px;
            margin-right: 18px;
        }
        .dashicons-yes{
            margin-right: 25px;
        }
        .dashicons-yes:before {
            content: "\f147";
            background: #388e3c;
            color: #fff;
            border-radius: 40px;
            padding-right: 3px;
            padding-top: 1px;
        }
This changes the dashicons for your custom demand but also on other pages. You should be aware of this when you change the layout of standard components.

So I would suggest you add a custom CSS class to the dashicons where you use them and adjust the CSS code to only address your custom classes, like:

<span class="dashicons dashicons-amp dashicons-yes"></span>

And then:

.dashicons-amp.dashicons-yes { ...

I hope this can be made with the next update.

**Comment by MohammedKaludi** [comment]
:+1:
