### ISSUE TITLE
visual composer incompatibility

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1445]
- [ ]  **1** - Report Date 30 Oct 
https://secure.helpscout.net/conversation/457883714/17668?folderId=1060551

- [ ]  **2** - Report Date 22 Nov 
https://secure.helpscout.net/conversation/472785893/18557?folderId=1060551

- [ ]  **3** - Report Date 23 Nov 
https://secure.helpscout.net/conversation/472974129/18565?folderId=1060551

- [ ]  **4**  Report Date 24 Nov 
https://secure.helpscout.net/conversation/473663681/18603?folderId=1060551

- [ ]  **5** Report Date 24 Nov 
https://secure.helpscout.net/conversation/473590734/18598?folderId=1060551

- [ ] https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1547

Some users even said that it was working previously but now it's not working. It's a real issue and needs to fix.

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1547

**Comment by ahmedkaludi** [comment]
This has been fixed when we released the vue.js based Page builder
