### ISSUE TITLE
Amp carousel not displaying the images after update

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1446]
Two same issues about images not displaying in AMP carousel

1 - https://secure.helpscout.net/conversation/466564713/18248?folderId=1060551 ( WP-admin and ftp)
2 - https://secure.helpscout.net/conversation/466857588/18259?folderId=1060551

**Comment by MARQAS** [comment]
I created a post and add a new gallery to it and its working. I was able to find only one issue and that is 'space'

**Comment by MohammedKaludi** [comment]
:+1: working properly and tested the solution on customers site.
