### ISSUE TITLE
After 0.9.69.1 update - Call to undefined function mb_convert_encoding()

### ISSUE THREAD

**Issue by gigidawg** [ahmedkaludi/accelerated-mobile-pages#1447]
Seems like the latest update requires the server to have php mbstring installed. Otherwise, the AMP output is completely blank and it errors out:

[:error] [pid 28649] [client 172.30.1.102:13104] PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/html/wp-content/plugins/accelerated-mobile-pages/templates/features.php

To fix, all I had to do was install php70-mbstring. (sudo yum install php7.0-mbstring on amazon linux).

**Comment by MARQAS** [comment]
Hi @gigidawg 
Thank you so much for reporting this issue, it might help other users as well :)

**Comment by MohammedKaludi** [comment]
Fixed  :+1:
