### ISSUE TITLE
The images on homepage in AMP are not visible due to the src.jpg and alt are merged

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1450]
This is a valid issue on the forum
https://wordpress.org/support/topic/amp-img/#post-9704707

Need to put a space in the index.php on line number 61 in all three designs

Ref: https://secure.helpscout.net/conversation/471973120/18488?folderId=1060551

**Comment by MARQAS** [comment]
Resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1a10d57f8b971ef201711a9346deebce82687f22

**Comment by MohammedKaludi** [comment]
:+1:
