### ISSUE TITLE
Better AMP to AMPforWP migrater

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1452]
BetterAMP plugin has link structure to amp like domain.com/amp/postname and yours is domain.com/postname/amp

Ref: https://secure.helpscout.net/conversation/469856356/18386?folderId=1060551

**Comment by MohammedKaludi** [comment]
AMP Migrator created https://github.com/MohammedKaludi/amp-migrator
