### ISSUE TITLE
AMP url is not working when plain permalink is selected (Tech Theme)

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1454]
Every page and article are seen correctly. Just the homepage creates problems and doesn't work.

Ref: https://secure.helpscout.net/conversation/473061659/18570?folderId=1060551

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/tech-amp-theme #21](https://github.com/ahmedkaludi/tech-amp-theme/issues/21) via [**ZenHub**](https://www.zenhub.com/)
