### ISSUE TITLE
Gallery carousel showing blank grey background

### ISSUE THREAD

**Issue by trenzterra** [ahmedkaludi/accelerated-mobile-pages#1456]
Hi there,

I am having issues with my gallery carousel not even showing up from the latest update.

https://www.describee.com/2017/11/26/dsdsdsa/amp/

vs https://www.describee.com/2017/11/26/dsdsdsa

May I know what is wrong and if there is a fix for this?

Thank you.

**Comment by MohammedKaludi** [comment]
The above fix should fix the issue. 

Today we are pushing the code, so update to 0.9.70 and do let us know your feedback on the update.

Closing the ticket, for now, feel free to reopen if the issue persists.

Mohammed Kaludi

**Comment by trenzterra** [comment]
Apologies for the lack of update as I have been really busy lately.

I have just updated to 0.9.71 but I do not notice a difference. I am still getting a blank grey background.
