### ISSUE TITLE
Conflict with disabling Smart Quotes in WP

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1458]
Here is a test page that displays the issue:
http://techgenix.com/smart-quotes-example/

I don't know if I have stated it explicitly in my initial message, but this problem affects the *normal version* of the posts and pages, not just the AMP version. The AMP plugin should not change how the normal version of posts are displayed, this is my main concern.

And yes, we have many old tutorials on the site where we don't want the quotes to be automatically converted to these "pretty" quotes, but keep them as simple straight quotes.

The WP function that does this is automatic change:
https://codex.wordpress.org/Function_Reference/wptexturize

We disabled it as per:
https://codex.wordpress.org/Plugin_API/Filter_Reference/run_wptexturize

But after activating your AMP plugin the quotes are getting changed again.

You can easily replicate this on a fresh WP install:
1. add the below filter to functions.php
add_filter( 'run_wptexturize', '__return_false', 9999 );
2. create a new post with some straight U+0027 quotes
3. check the post to verify that they are rendered as straight quotes
4. enable AMP plugin
5. check the post again

Ref: https://secure.helpscout.net/conversation/473548186/18595?folderId=1060551

**Comment by MohammedKaludi** [comment]
create an option to TurnOff wptexturize support and it should only be Turned off in AMP environment.

**Comment by MohammedKaludi** [comment]
:+1:
