### ISSUE TITLE
PHP errors related to our plugin

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1459]
- [x]  [26-Nov-2017 08:48:45 UTC] PHP Notice: Undefined index: wordpress-comments-support in /var/www/vhosts/correrunamaraton.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-3/style.php on line 193

- [x] [26-Nov-2017 10:15:19 UTC] PHP Deprecated: Non-static method AMP_Customizer_Design_Settings::register_customizer_ui() should not be called statically in /var/www/vhosts/correrunamaraton.com/httpdocs/wp-includes/class-wp-hook.php on line 286

- [x] [26-Nov-2017 10:15:19 UTC] PHP Deprecated: Non-static method AMPFORWP_Customizer_Design_Contols::register_customizer_ui() should not be called statically in /var/www/vhosts/correrunamaraton.com/httpdocs/wp-includes/class-wp-hook.php on line 286

Ref: https://secure.helpscout.net/conversation/474867762/18703?folderId=1060551

**Comment by MARQAS** [comment]
I don't think 2 and 3 still exists, Those were resolved in earlier versions.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
CSS editor might not work, need to test it properly.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c74a3ac295eb79b71220fe9484f72d5675e6fcc7#diff-d2a448840c98f4c9bcf27aab39b04b83R452

**Comment by MohammedKaludi** [comment]
:+1:
