### ISSUE TITLE
Social Sharing Markup is visible even after we turn it off

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1460]
![gupotx](https://user-images.githubusercontent.com/16532359/33310817-de10bbf4-d448-11e7-923f-95eaa621a9de.jpg)

REF: https://wordpress.org/support/topic/social-icons-93/

**Comment by MARQAS** [comment]
We can create a new option to control the whole social sharing section, but I believe we don't need more and more option to make things complicated. 
We can make use of the options which we already have. It can be disabled with Customizer( or with our new option in AMP options panel which is currently in beta). 
Just disable the social icons from it and the whole section of Social icons will be gone.

**Comment by MARQAS** [comment]
@frenchomatic , Have you tried the option which I mentioned in the above comment?

**Comment by Frenchomatic** [comment]
Version 0.9.97.14 - Design 2 - Firstly I see an empty div for comments and post pagination meta on a static home page which shouldn't be present (comments are not turned on and there is no pagination on a static home page). Specifically this code :

<div class="ampforwp-comment-wrapper"> </div>
<div class="amp-wp-content post-pagination-meta"> </div>

Now on blog posts I do see another empty div which shouldn't be present

<div class="amp-wp-content post-pagination-meta ampforwp-social-icons-wrapper ampforwp-social-icons"> </div>

I see no way to turn that off. 


Finally, I still see an extra space being put in on the NON-AMP version link. 

<a class="view-non-amp" href="mydomain">Non-AMP VersionSPACE</a>

**Comment by MARQAS** [comment]
I guess the space issue in view non amp has been resolved in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2425
If its still causing the issue, can you please create a ticket for that with details attached to it?

**Comment by MARQAS** [comment]
And regarding the empty divs, sadly they are all connected with Customizer, and like you, there are many others who found it confusing, so we decided to remove it and add a better solution for it in the AMP options panel. 
And it has been already added in the beta. Soon will be added in the master as well.
