### ISSUE TITLE
& sign converted to & a m p ; This throws error “Unable to execute code: ” and reveals the PHP code

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1462]
The plugin converts & sign to & a m p;.

To reproduce the problem do this (please note: the spaces between characters here are only to prevent converting html entities to characters):

Try to insert && on any post. But not with WP editor which will convert characters to & a m p ;& a m p ;.
For example, use plugin Ad Inserter to insert && before content on posts.
On normal pages you will see in the source code what is inserted: &&.
However, on AMP pages you will see & a m p ;& a m p ; in the source code (without spaces).

REF: https://wordpress.org/support/topic/sign-converted-to/#post-9725446

**Comment by MARQAS** [comment]
I did the same thing but unable to recreate the issue. Can we ask the user to share the screencast or screenshot? @ahmedkaludi

**Comment by MohammedKaludi** [comment]
The filter created and the user can modify the output. For more details https://wordpress.org/support/topic/sign-converted-to/#post-9889347
