### ISSUE TITLE
AMP-Facebook-Like Was found but unused Validation Error.

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1463]
when the social Icons disabled from the customizer the issue occurs which should not be the case.

**Comment by ahmedkaludi** [comment]
@Sejiro-Hiko I have seen this issue on some sites but I was not able to figure out the root of it.

If what you are saying is right, then I would say we have to take care of it.

**Comment by MohammedKaludi** [comment]
@ahmedkaludi that's why added in 0.9.70 milestone. And will be fixed and pushed today.

**Comment by MohammedKaludi** [comment]
:+1:
