### ISSUE TITLE
Compatible with Revolution Slider 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1464]
AMP Carousal should be Compatible with Revolution Slider 

 https://secure.helpscout.net/conversation/466564713/18248?folderId=1060551 ( WP-admin and ftp)

**Comment by MohammedKaludi** [comment]
Originally reported as regular gallery not working here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1446
Fixed normal gallery issue but found out not working with Rev Slider galleries.

**Comment by MohammedKaludi** [comment]
:+1: can be merged into

**Comment by ahmedkaludi** [comment]
Why is this ticket blocked?

**Comment by MARQAS** [comment]
If we are merging this ticket before https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2287, then make sure to remove/modify the code related to the namespace.

**Comment by pegazee** [comment]
"Lightbox for Gallery" option from the single settings is not working.

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
