### ISSUE TITLE
Problem with commit #8782205

### ISSUE THREAD

**Issue by nicholasgriffintn** [ahmedkaludi/Accelerated-Mobile-Pages#147]
Hey,

So there is a problem with commit #8782205.

Although it fixes the issue about two URLs being shown on front pages, it will also bring back the issue that front pages show the "/amp" URL for the AMPHTML meta, instead of the actual "/?amp" URL, meaning that Google will just see a 404 after crawling.

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn 

Can you please check the latest version and share your review?

**Comment by khaledMohammed000** [comment]
@nicholasgriffintn I have tested with custom page types which is used as Front page , I could not recreate the issue .... Could you pull the latest code and double check it please :)
