### ISSUE TITLE
increase disqus height

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1471]
Disqus in the AMP version looks extremely small and you have to scroll too much in order to see them.

Ref: https://secure.helpscout.net/conversation/477020865/18810?folderId=1060551

**Comment by ahmedkaludi** [comment]
3 more users asked for this https://wordpress.org/support/topic/the-height-for-the-disqus-comments/#post-9732734

We need to solve this

**Comment by MohammedKaludi** [comment]
:+1:
