### ISSUE TITLE
Yoast seo breadcrumbs in our AMP

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1473]
if I active the shortcode [wpseo_breadcrumb] for implement breadcrumbs, google just no index my indexed amp pages.

Ref: https://secure.helpscout.net/conversation/477068095/18813?folderId=1060551

**Comment by MohammedKaludi** [comment]
Please use function_exists('yoast_breadcrumb') or the main class/function to check if it exists or not.
if ( is_plugin_active() ) can create issues in Multisites or Whitelabel or Pro or other versions of the plugin.

**Comment by ahmedkaludi** [comment]
@Zabi09 @MARQAS Can you tell me where is this Yoast option available? because I can't seem to find it.

**Comment by ahmedkaludi** [comment]
**REVIEW**

- [ ] Design of the breadcrumbs doesn't look correct. Turn off the Yoast, see how it looks, analyze it and enable the Yoast breadcrumbs. You will see a huge difference. Make sure they look same.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
