### ISSUE TITLE
[FEATURE REQUEST] Facebook Instant Articles (FBIA) Crawler Ingestion (ia:markup_url) tag

### ISSUE THREAD

**Issue by haneef95** [ahmedkaludi/accelerated-mobile-pages#1474]
Hi,

The [original FBIA plugin for WordPress](https://wordpress.org/plugins/fb-instant-articles/) implements this feature.

Can you add [crawler ingestion](https://developers.facebook.com/docs/instant-articles/crawler-ingestion/) as an option in your plugin as well please? Its basically a meta tag (ia:markup_url) that has an URL to the ia markup version of the post, just like http://postlink/amp

NOTE: I believe that FBIA features should be in a totally separate plugin, rather than loading it with the AMP plugin, anyway, your choice as developers.

Thanks,

**Comment by MohammedKaludi** [comment]
Please use esc_url function to escape url.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7d21dd631cd9fc5a5480db74c36078d9faff867a#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4314

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko why do we need `?ia_markup=1` in the url?
is it required?

**Comment by Sejiro-Hiko** [comment]
@MohammedKaludi the Facebook's official plugin does add it so I thought It's might be necessary even though what they said in the documentation is:
 The URL (self-hosted, public) containing the Instant Article markup for the respective page:
`<meta property="ia:markup_url" content="{URL}">`

**Comment by MohammedKaludi** [comment]
Yes, I read that and I don't think we need `?ia_markup=1` query args in the URL, as it says you just need the url of the content, but keeping like this has no harm.

I did not see any examples containing the query args, but as you mentioned Facebook's official plugin has, so keeping it in the url.

Otherwise, this feature is working correctly.
Closing the ticket.

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
