### ISSUE TITLE
[FEATURE REQUEST] Custom Facebook Instant Articles Ad option

### ISSUE THREAD

**Issue by haneef95** [ahmedkaludi/accelerated-mobile-pages#1475]
Hi,

Currently, there's only an option to enable Facebook Audience Network ads, however, the Facebook IA documentation also allows for ['directly sold ads'](https://developers.facebook.com/docs/instant-articles/monetization/direct-sold/).

This feature is also available in the [FBIA WP plugin provided by Automatic/Facebook](https://en-gb.wordpress.org/plugins/fb-instant-articles/), as shown below.
![image](https://user-images.githubusercontent.com/298208/33521530-e49029c0-d7cb-11e7-8692-08002505b05f.png)

Could you add this feature please?

Thanks,

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko Please use esc_url($custom_iframe_url) to escape the url.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by beingsmart3** [comment]
Need to create a Custom Embed code option in Instant Article.

Ref:  https://secure.helpscout.net/conversation/656699242/33421?folderId=1914712

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
