### ISSUE TITLE
[FEATURE REQUEST] Facebook Instant Articles (FBIA) API usage

### ISSUE THREAD

**Issue by haneef95** [ahmedkaludi/accelerated-mobile-pages#1476]
Hi,

It would be good if I can mange (see, create, edit and delete) all the FBIA articles on my WordPress admin back-end, instead of having to go to the Facebook Page Publisher Tools area. That way, I wouldn't have to give WP editors access to my FB page admin access.

This could be done through the [FBIA API](https://developers.facebook.com/docs/instant-articles/api).

Thanks,

**Comment by Zabi09** [comment]
Added in our tasklist (Trello Board) and it will be released in our extension in the future.
