### ISSUE TITLE
Content Views – Post Grid & List for WordPress generates Validation Issues

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1479]
They are using the data-src attribute in the iframe which in amp-iframe give validation issues.
Ref: https://flatroofdoc.com/scuppers-flat-roof-repair/amp/
http://take.ms/DN0nL

**Comment by Zabi09** [comment]
There is no text field for entering the content so I have put in the excerpt section which allows HTML - http://take.ms/HrdJb
Added the shortcode along with normal iframe - http://take.ms/mYidU
The output of the non-amp - http://take.ms/KLPA2
The output of AMP - http://take.ms/U39in

Lastly, everything looks good without any validation
