### ISSUE TITLE
Issues with PlayBuzz after update 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1481]
There are users who are getting validation issues after Playbuzz integration.

Try to add it with this code `<script type=”text/javascript” src=”//cdn.playbuzz.com/widget/feed.js”></script>
<div class=”pb_feed” data-embed-by=”8cf70c2e-252f-4323-8c0b-f1955adf6420″ data-item=”9704c7bf-4560-48c5-8647-c4ed66c3256b” data-game-info=”false” data-comments=”false” data-version=”2″></div>

`

It messesup the validation: see http://take.ms/azGiW

REF: https://wordpress.org/support/topic/i-have-problem-with-amp-playbuzz/

**Comment by MohammedKaludi** [comment]
:+1:
