### ISSUE TITLE
improving the facebook instant article support

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1484]
improving the facebook instant article support as requested by the user

Ref: https://secure.helpscout.net/conversation/479756040/19053?folderId=1060551

**Comment by MARQAS** [comment]
This ticket is covered in #1486 #1483 #1634 #1297 #1524 #1089 #1489 

I guess those features can cover this ticket, except one or two like adding code for specific posts, placement manager etc.. But I believe we should cover those things when more users ask for it and ready to use them.

**Comment by MohammedKaludi** [comment]
@ahmedkaludi need to discuss on this.

**Comment by ahmedkaludi** [comment]
Sure, @MohammedKaludi

**Comment by ahmedkaludi** [comment]
There's not a specific feature or bug mentioned, we will close this ticket.
