### ISSUE TITLE
Pagination not working after changing the pagination base

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1485]
The pagination is not working on AMP Version if I change the pagination base
For example from 'page/1' to 'halaman/1'

Ref: https://secure.helpscout.net/conversation/479424852/19036?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
