### ISSUE TITLE
Facebook Instant Articles Meta Tag

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1486]
Facebook wants me to add the meta tag <meta property="fb:pages" content="page ID #" /> and won't let me go any further until I do that.Can you tell me where I add the page ID number in the ampforwp plugin?

Ref: https://secure.helpscout.net/conversation/479375774/19034?folderId=1680011

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
