### ISSUE TITLE
 Shortcodes Ultimate compatibility

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1488]
Ultimate shortcodes compatibility

Ref:  https://secure.helpscout.net/conversation/480622460/19087?folderId=1060551

**Comment by MARQAS** [comment]
We are going to create an extension for this, check out our trello board for more info

**Comment by MohammedKaludi** [comment]
For more info about Shortcodes Ultimate compatibility with AMP.

Check this : https://ampforwp.com/shortcodes-ultimate/
