### ISSUE TITLE
Option to specify certain taxonomy only in Instant Article Feeds

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1489]
Can you please look into an option to specify certain taxonomy only to be included in the instant articles feed?
This can be useful if a website developer wants to have instant articles only for a category called “products” for example, or a tag called “new”…etc

Ref: https://wordpress.org/support/topic/option-to-specify-certain-taxonomy-only-in-instant-article-feeds/

**Comment by MARQAS** [comment]
The example links for instant articles feed of specific taxonomy is:
taxonomy: http://www.example.com/taxonomy/taxonomyname/feed/instants_articles

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
need to create an option where we can hide specific taxonomies.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
this code can be improved 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d05f30840159ccc3a27dcd0a5f9fcb86d7885b71#diff-bee4ec2582ddfa28459b806558a4b61eR21

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by wasimmagazine3** [comment]
Some of the commits were already merged in master

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
