### ISSUE TITLE
Gallery Image Width Issue

### ISSUE THREAD

**Issue by reasecret** [ahmedkaludi/accelerated-mobile-pages#1490]
Posted here:
https://wordpress.org/support/topic/how-can-i-change-images-sizes-in-the-carousel/

Image captions have full width but images don't. Full width images should look better.

A screenshot:
https://www.screencast.com/t/X2lC23Hf1zD

Live example:
https://modaduskunu.com/defileler/gucci-spring-2018-ready-to-wear/amp/

**Comment by Sejiro-Hiko** [comment]
@reasecret do you want to change the width of the images in the gallery right? how about we make the caption to be the same width as those original images which will be great in my view instead of changing the width of images which might affect the quality?

Let me know what you think..

**Comment by Sejiro-Hiko** [comment]
@reasecret we do have this filter `amp_gallery_image_params` which you can use to change the parameters of the images such as `width` and `height` of if you need our help in implement this on your end you can contact us through here `ampforwp.com/support/` of if you want to resize the caption width to that of original image sizes then we can help you in that also through `CSS`

**Comment by ahmedkaludi** [comment]
Waited long for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
