### ISSUE TITLE
Localization string for "% days ago" not working for non-Latin languages

### ISSUE THREAD

**Issue by chopinesque** [ahmedkaludi/accelerated-mobile-pages#1491]
It was tested with Greek and Designs 1 and 2.
I think you may need to add also the strings:

"% months ago" 
"% years ago" 

As explained here:
https://wordpress.org/support/topic/translation-of-string-ago-not-displaying/#post-9757033

Also, if one selects the standard date format ("Traditional view"), this does not appear to take localized values.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
> "% months ago" and "% years ago"
Months and year text is translating properly and Ago will now be translatable.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
