### ISSUE TITLE
Change Published Date to Last Updated Date

### ISSUE THREAD

**Issue by krisfannin** [ahmedkaludi/accelerated-mobile-pages#1496]
Per this post on the plugin page, include the ability to change "published date" to "last updated date" on both single posts and archive displays for template 3.

Although the ability to display 'last updated date' exists on single posts, it would be ideal to have an option to simply replace the published date with last updated date across the plugin.

**Comment by MohammedKaludi** [comment]
Added a new section to manage dates and ability to switch between Post published and modified dates.
