### ISSUE TITLE
Security Fixes – lack of sanitizing / wrong sanitizing functions

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1497]
There is a lack of sanitizing / wrong sanitizing functions on this plugin- a lack of security on the plugin

Missing a lot of escaping, lots of commented out code etc.
For reference, running some automated code checking, this is what needs fixing:

———————————————————————-
STANDARD CATEGORY SNIFF COUNT
———————————————————————-
[ ] WordPres XSS Escape output output not esca 2137
[ ] WordPres PHP Strict comparisons loose comp 1012
[ ] Squiz PHP Commented out code found 631
[ ] WordPres VIP Super global input usage acce 215
[ ] WordPres Variables Variable analysis unused vari 182
[ ] WordPres Files Including file including file 137
[ ] WordPres CSRF Nonce verification no nonce v 128
[ ] WordPres Variables Variable analysis variable re 94
[ ] WordPres PHP Strict in array missing true 89
[ ] WordPres VIP Validated sanitized input inp 78
[ ] WordPres Variables Variable analysis undefined v 51
[ ] WordPres XSS Escape output unsafe printing 46
[ ] WordPres VIP Restricted functions strip_ta 41
[ ] WordPres WP Alternative functions json_en 40
[ ] WordPres VIP Validated sanitized input inp 36
[ ] WordPres VIP Error control error control 16
[ ] WordPres WP Alternative functions curl_cu 13
[ ] WordPres VIP Restricted functions wp_remot 10

Are you able to get this fixed? Currently, you’ve focused on a lot of features but security isn’t great and this further prevents more downloads of your plugin. This is one area the official AMP plugin is stronger

REF: https://wordpress.org/support/topic/security-fixes-lack-of-sanitizing-wrong-sanitizing-functions/#post-9762922

**Comment by MohammedKaludi** [comment]
- [ ] Remove all the inline styling 
- [ ] Change Camel case variables and functions with Underscore ones
- [ ] From:  __(), _e(), _n(), _x(), _ex(), _nx(),  TO  esc_attr__(), esc_attr_e(), esc_attr_x(), esc_html__(), esc_html_e(), esc_html_x(), _n_noop(), _nx_noop(), translate_nooped_plural()
- [ ] escape src and href url
- [ ] remove unused code and files

**Comment by MohammedKaludi** [comment]
First Part Done for security cleanup.
