### ISSUE TITLE
Tagdiv's Loadmore on categories pages

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1499]
Tagdiv's  Load more and archives are not working together 

EDIT:

If we have the infinite scrolling enabled from tagdiv then the archive pages are not paged "/page/2/" and it goes to the 404.

but if we go via /?amp then the pagination works perfectly but then it would not update the canonicals so it would cause Major content mismatch error which will then be a validation issue.

So the option part would be to make it in a such way that it works with with clean permalinks.

REF: https://secure.helpscout.net/conversation/483151844/19213?folderId=1060551

**Comment by ahmedkaludi** [comment]
We will be adding this feature into https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1676
