### ISSUE TITLE
Change the ?amp to /amp

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#15]
My guess is that the '?' can give problems with caching. I still need to do some tests before coming to the conclusion. But if there is any such problems, then we need to change it from ?amp to /amp

**Comment by dayhawkkim** [comment]
In addition to caching, it could, though not very likely, be interpreted as a query string and/or parameter, by some. I look forward to the upcoming update. Thanks for all the great work!

**Comment by seoway** [comment]
already 4 August. really looking forward to the upgrade. "/amp"

**Comment by ahmedkaludi** [comment]
This was fixed after 0.8 update.
