### ISSUE TITLE
Missing structured data of homepage

### ISSUE THREAD

**Issue by aashishpahwa** [ahmedkaludi/Accelerated-Mobile-Pages#150]
Hi,
The plugin really good but it has few errors.
The homepage when tested on structured data tool shows it as a blogpost with the first post as a title. 
It should be shown as a website, right?
Non amp result -
https://search.google.com/structured-data/testing-tool#url=feedough.com%2F

Amp homepage result- 
https://search.google.com/structured-data/testing-tool#url=feedough.com%2F%3Famp

**Comment by ahmedkaludi** [comment]
I would suggest you to update it to 0.8.5 release. It should fix the issue and don't forget to flush rewrites and setup structured data options in settings.

**Comment by ahmedkaludi** [comment]
@aashishpahwa This should be fixed with the latest version update.
