### ISSUE TITLE
Compatibility with the Relevanssi Plugin

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1503]
Our AMP search is not working when Relevanssi plugin is activated

Ref: https://secure.helpscout.net/conversation/468444493/18334?folderId=1060551

**Comment by daanishd** [comment]
The search result shows the result and its content.

Ref: https://secure.helpscout.net/conversation/576223040/25804?folderId=1964340

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/583350308/26352?folderId=673452

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Proper integration of Relevanssi done in  #2307
