### ISSUE TITLE
URGENT: Table images missing / removed

### ISSUE THREAD

**Issue by apavlinovic** [ahmedkaludi/accelerated-mobile-pages#1504]
Hi,

I keep having this issue over and over with your plugin. In every table that contains images, the first image in the table disappears. Additionally, every image that's not initially visible (if the table has horizontal scroll) is also removed.

What is going on, this is not right? I'm a paying customer using several AMP Extensions.

How to reproduce:

https://pokemongohub.net/generation-3/absol/amp (check table at top and and bottom on normal and AMP version)

Facts:
- Design 1
- the image is not in the HTML
- this is a Page, not a Post

**Comment by ahmedkaludi** [comment]
Regarding the original issue, We have waited for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
