### ISSUE TITLE
Youtube Oembed Plyr plugin compatibility 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1505]
No option of removing the related video at the end of youtube video in the AMP version

Ref: https://secure.helpscout.net/conversation/479156591/19022?folderId=1060551

**Comment by vibhi19** [comment]
Please Also Add remove realted video when pause Which is basically by rel=0 and Annotations Like subscribe and playlist 
and you already added remove realated video in the end of the video

Thanks for the help

**Comment by pegazee** [comment]
Related videos are still showing. Screenshot: https://take.ms/rgA97

**Comment by syedimran22** [comment]
*** Review ***
- [ ] Imran 

- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
Rel=0 not working has been reported to Project AMP team
https://github.com/ampproject/amphtml/issues/21394

**Comment by pegazee** [comment]
pushed in 0.9.97.44
