### ISSUE TITLE
Simple Custom CSS and JS plugin is displaying errors in the AMP page

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1509]
This plugin is displaying errors in the AMP validator

Ref: https://secure.helpscout.net/conversation/458470419/17717?folderId=1060551

**Comment by MARQAS** [comment]
The errors were due to Social Share by Supsystic plugin.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
