### ISSUE TITLE
Favicon issue

### ISSUE THREAD

**Issue by aashishpahwa** [ahmedkaludi/Accelerated-Mobile-Pages#151]
Hi 
I recently rebranded my website and updated my favicon. 
The change in the favicon isn't updated on the amp website.
Plus,
The favicon is showing just on homepage

**Comment by CryssDOTnet** [comment]
Try to empty your browser cache. This might solve the problem. That was the culprit in my case.

**Comment by ahmedkaludi** [comment]
@aashishpahwa Any update on this?

For more support, please create a new support thread at the forums at https://wordpress.org/support/plugin/accelerated-mobile-pages
