### ISSUE TITLE
Structured data description should strip the shortcode

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1512]
Need to strip the shortcode in the description of the structured data

Ref: https://secure.helpscout.net/conversation/482601133/19191?folderId=1680011

**Comment by Sejiro-Hiko** [comment]
Update: Structure data's description isn't closing properly

In the description all the content is added which led to the blank of single.

NOTE: only one user faced the issue (Silegeanu Catalin)

**Comment by MARQAS** [comment]
Working perfectly fine here.

**Comment by MohammedKaludi** [comment]
:+1:
