### ISSUE TITLE
Avoid Calling attachment_url_to_postid() Unless Necessary

### ISSUE THREAD

**Issue by nash-ye** [ahmedkaludi/accelerated-mobile-pages#1517]
Calling attachment_url_to_postid() REALLY hit the performance of big sites. Please review the plugin codes and reduce the usage of this function unless necessary.

**Comment by nash-ye** [comment]
We had disabled the logo until you fix this issue in the plugin. Please consider it as very important.

**Comment by MohammedKaludi** [comment]
Closing the ticket more at #1518
