### ISSUE TITLE
Disable/Enable AMP pages for custom post types

### ISSUE THREAD

**Issue by GitKoda** [ahmedkaludi/Accelerated-Mobile-Pages#152]
I use a plugin called Charitable, it generates a custom post type called "campaigns", this plugin generate an AMP link for every "campaign" but that link with /amp postfix redirect the browser to the normal version,  so i'm having problems with Google Webmaster tools.

**Comment by ahmedkaludi** [comment]
@GitKoda You should try to rewrite flush rules, that should fix it. http://ampforwp.com/docs/flush-rewrite-urls/
