### ISSUE TITLE
inserting the author bio into the Instant Article feed on the top of the article

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1521]
Author bio should not be on the top of the new article it must be the bottom.
Need to remove the <address> tag of the Instant Article

Need to create an option of showing and hiding the author bio in the Instant Article

Ref: https://secure.helpscout.net/conversation/485589319/19319?folderId=1680011

**Comment by zabi332** [comment]
One More-

Ref: https://secure.helpscout.net/conversation/486945657/19378?folderId=1680016

**Comment by beingsmart3** [comment]
one more-

Ref:  https://secure.helpscout.net/conversation/498565939/20008?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:
