### ISSUE TITLE
Duplicate h1 tags in Design One

### ISSUE THREAD

**Issue by hongily25** [ahmedkaludi/accelerated-mobile-pages#1522]
There is an h1 tag inside the class "amp-logo" and also another h1 tag inside "ampforwp-title". There should only be one h1 on a page and it is causing validation errors in external third party tools. Is there a way to remove the h1 that is inside the class "amp-logo"?
![amptitle](https://user-images.githubusercontent.com/1762760/33965012-4e8c87c4-e00f-11e7-90e1-c86be36d7525.png)

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: Reviewed

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
