### ISSUE TITLE
Facebook Instant Articles in each Catagory

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1524]
Facebook Instant Articles in each Category

Ref:  https://secure.helpscout.net/conversation/486053814/19340?folderId=1060551

**Comment by MARQAS** [comment]
The example links for instant articles feed of specific category/tag are: 
category: http://www.example.com/category/categoryname/feed/instants_articles
tag: http://www.example.com/tag/tagname/feed/instants_articles

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
need to write a tutorial on how to get that.

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
