### ISSUE TITLE
AMP Page gets break in previous versions Of Wordpress before 4.9.1

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1525]
AMP Page gets break in previous versions Of Wordpress before 4.9.1

Ref:  https://secure.helpscout.net/conversation/479172898/19024?folderId=1060551

**Comment by santosh8793** [comment]
I have checked it in 4.8.5 version, there was no error, all pages are displaying properly

**Comment by MohammedKaludi** [comment]
:+1:
