### ISSUE TITLE
Google Analytics and Session Stitching

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1527]
This new feature takes care of the bounce rate issue.

I’m wondering if your plugin is taking care of the issues outlined in this article about Google Analytics and AMP. They outline code that needs to be in place to stop Analytics from counting sessions and referrers incorrectly.

https://www.stonetemple.com/amp-tech-guide/

I can implement their fix, but if your plugin is already taking care of the necessary items on the website, I don’t want to duplicate them

Ref https://wordpress.org/support/topic/google-analytics-and-session-stitching/

**Comment by MARQAS** [comment]
https://ampforwp.com/tutorials/article/set-google-amp-client-id-api/
