### ISSUE TITLE
Mobile Redirection not working

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1528]
Mobile redirection does not work 

- [ ] Pages are redirecting to the amp on mobile but homepage is not redirecting
Ref: https://secure.helpscout.net/conversation/487078244/19385?folderId=1060551

- [ ] If pages are off in the general settings then the mobile direction is not working on the homepage
Ref: https://secure.helpscout.net/conversation/487558100/19402?folderId=1060556

**Comment by ahmedkaludi** [comment]
If this was the case then we would be knowing about it by now
