### ISSUE TITLE
Backward Compatibility for AMP Preview 

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1529]
WordPress below 4.4 throws a fatal error.

Fatal error:  Call to undefined function get_preview_post_link() in /var/www/tekslate/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1302

function get_preview_post_link() was Introduced in 4.4.0 Version of WordPress.

**Comment by ahmedkaludi** [comment]
- [ ] add background:#fff to .ampforwp-preview-container > iframe http://take.ms/mLc1o
