### ISSUE TITLE
Web Share API - triggers OS share dialog option

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1530]
Option of sharing with web share API integration in our AMP

Ref: https://secure.helpscout.net/conversation/486940266/19377?folderId=1060551

**Comment by ahmedkaludi** [comment]
Native Share Dialog (Chrome on Android) is now available on 
https://ampbyexample.com/components/amp-social-share/

We need to build this functionality. Please refer me before proceeding with this feature.

**Comment by MARQAS** [comment]
I guess we should wait for it to become the full-fledged feature or else it can cause some problems.

**Comment by ahmedkaludi** [comment]
We will be adding this feature when it's fully out.
