### ISSUE TITLE
Do not work if the plugin is installed outside /wp-content/plugins.

### ISSUE THREAD

**Issue by pako69** [ahmedkaludi/accelerated-mobile-pages#1531]
Hi

I have 4 websites that are using common directories for plugins (It’s not a multisite installation), and this common directoris is outside the standard WP directories.

All is setup in wp-config.php like this:

```
define('WP_PLUGIN_DIR', '/home/domodeco/static.domodeco.fr/plugins');
define('WP_PLUGIN_URL', 'https://static.domodeco.fr/plugins');
```

But you are using this:

```
if ( empty( $this->extension_dir ) ) {
$this->extension_dir = trailingslashit( str_replace( '\\', '/', dirname( __FILE__ ) ) );
$this->extension_url = site_url( str_replace( trailingslashit( str_replace( '\\', '/', ABSPATH ) ), '', $this->extension_dir ) );
}
```

So, (for example) one of my websites: http://www.domodeco.fr, your plugin is trying to reach:
https://lyon.domodeco.fr/home/domodeco/static.domodeco.fr/plugins/accelerated-mobile-pages/…………..
instead of:
https://static.domodeco.fr/plugins/accelerated-mobile-pages/………………….

**Comment by MohammedKaludi** [comment]
@pako69 Thank you for letting us know about it, we will make this change and let you know.

**Comment by MohammedKaludi** [comment]
need a minor improvement, otherwise looks good.

**Comment by pegazee** [comment]
Working as expected.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
