### ISSUE TITLE
If There is no post /amp doesn't work 

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1533]
if There is no post /amp doesn't work 

Ref:  https://secure.helpscout.net/conversation/479172898/19024?folderId=1060551

**Comment by MARQAS** [comment]
So as suggested by @beingsmart3 I deleted all the posts and checked if amp is working on pages/FrontPage or not. 
It is working perfectly fine. Pages and FrontPage are working without any issues. 
I have tested with different WordPress versions as well ( 4.8.6 and 4.9.6)

**Comment by MARQAS** [comment]
I guess the user was talking about the Product categories and he didn't activate the AMP on products.

**Comment by ahmedkaludi** [comment]
If there are zero posts, then the AMP behaves weirdly, I did check it personally with @beingsmart3 on that ticket back in Dec. But I guess, we have to nail this one immediately the next time it occurs.
