### ISSUE TITLE
AMP Page Builder 2.0 not working

### ISSUE THREAD

**Issue by daniesy** [ahmedkaludi/accelerated-mobile-pages#1535]
I can't see the AMP Page Builder anywhere when creating a new page.
I'm using the [Extra theme](https://www.elegantthemes.com/gallery/extra/) (shouldn't matter) and Wordpress 4.9.1. 

Please help, thanks.
D.

**Comment by ahmedkaludi** [comment]
Thats strange, can you share the URL please?

**Comment by ahmedkaludi** [comment]
Try amp page builder 3.0
