### ISSUE TITLE
Alexa Metrics Compatibility With AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1536]
Alexa Metrics Compatibility With AMP

Ref:  https://secure.helpscout.net/conversation/478679619/18993?folderId=1060551

**Comment by MARQAS** [comment]
Tutorial: https://ampforwp.com/tutorials/article/add-alexa-metrics-amp/

**Comment by MohammedKaludi** [comment]
:+1:
