### ISSUE TITLE
Hide by default - creating new page

### ISSUE THREAD

**Issue by smerriman** [ahmedkaludi/accelerated-mobile-pages#1537]
I want to have AMP on for selected pages only. I used the 'Hide AMP Bulk Tools' option and set to hide by default. 

This appeared to work for existing pages, but as soon as I created a new page, it was set to 'Show' by default.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by bevasion** [comment]
how to solve this issue 
ampforwp-amp-on-off: hide-amp
ampforwp_custom_content_editor:
ampforwp_custom_content_editor_checkbox:
ampforwp-redirection-on-off: disable
![Amp error](https://user-images.githubusercontent.com/61060747/74558012-53830300-4f59-11ea-826f-0fa5acbc171d.jpg)
 or you can cheek on my site
http://evasiontrekking.com/english/
