### ISSUE TITLE
Appearance option for Related Posts

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1545]
Options should be the following.
1.List
2. Carousel

**Comment by ahmedkaludi** [comment]
- [ ] The excerpt should be turned off by default if the Verticle is selected

- [ ] Styling of excerpt

- [ ]

**Comment by MohammedKaludi** [comment]
Third / Carousel option is not working.

**Comment by RajuJeelaga** [comment]
Single Page Related Post --- Third option/ Carousel is working fine.....

**Comment by MARQAS** [comment]
The 3rd design is not looking good in my opinion. Not working in desktop and in mobile, no one will know its a slider until they slide it.

**Comment by MARQAS** [comment]
@ahmedkaludi what do you say about it? Can we make it look more like a carousel?

**Comment by MARQAS** [comment]
Use `ampforwp_get_setting` instead of `$redux_builder_amp`

**Comment by MARQAS** [comment]
Empty and throwing errors when the 3rd design is selected.
https://monosnap.com/file/01Nc07cFDbfPwZrrTnBr0ws5pKz3JF

**Comment by Zabi09** [comment]
Before merging this ticket make sure to remove this condition - https://monosnap.com/file/TNpmuAT2R7bpvPfVCCskglD1sx1KTV

to fix this issue as well - #2957

**Comment by pegazee** [comment]
Horizontal Scrolling bar is showing in the related posts carousel ( in Swift theme's third design of related post ).
Screenshot: https://take.ms/QTJhl

Discuss this with @ahmedkaludi

**Comment by RajuJeelaga** [comment]
- [ ] when Single design 2 is selected carousel is showing on the top, Please see the screenshot
https://monosnap.com/file/yaPBTTLUAn51ZepT8y0ObGQfjMeCdY

solution: Add the single-design-type condition properly in single page

**Comment by RajuJeelaga** [comment]
24eefb3 this commit belongs to this ticket #3091

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
scripts added incorrectly 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/84274403d1dc24e24a3812451193af66212d392c#diff-6aa5512f7dd8d5ce60fc97b0f340912cL7861

**Comment by MohammedKaludi** [comment]
Use any existing hook of `amp_post_template_data` instead of creating new one

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
