### ISSUE TITLE
Issue of thumbnail Pictures on AMP above the Loop (homepage)

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1548]
issues of thumbnail Pictures on AMP above the Loop because of Width. AMP takes full-size pictures instead of thumbnail size.
 
Ref: https://secure.helpscout.net/conversation/466857588/18259?folderId=1060551

**Comment by MARQAS** [comment]
The main concern was calling of full images instead of thumbnail size. And it has been resolved with Aq resizer. 
Approved by @ahmedkaludi as well.
