### ISSUE TITLE
Caption in the Gallery creating validation errors along with space between gallery and caption

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1549]
This is the error in the validation after adding the caption to the gallery - " the attribute ':openbrack:class:closebrack:' may not appear " 

Ref: https://secure.helpscout.net/conversation/486897877/19373?folderId=1060551

**Comment by zabi09** [comment]
One more - https://secure.helpscout.net/conversation/496783010/19848/?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:
