### ISSUE TITLE
AMP plugin is installed but its not funtioning

### ISSUE THREAD

**Issue by gulshanbajaj** [ahmedkaludi/Accelerated-Mobile-Pages#155]
Hi,

I have installed this plugin and configured at, http://mentalitch.com from last week. its working fine if I add /?amp after url.

but its not working if from mobile if I search for keyword and click on site link. Its opening actual site pages instead of google pages.

Can you let me know whats missing exactly?

Thanks,
Gulshan

**Comment by ahmedkaludi** [comment]
Hey Gulshan,

I have just checked your website, you have not installed this plugin. As far as the google is concerned, it will take some time before it start showing it on the results.

**Comment by ahmedkaludi** [comment]
For more support, please create a new support thread at the forums at https://wordpress.org/support/plugin/accelerated-mobile-pages
