### ISSUE TITLE
Disable AMP on Twitter

### ISSUE THREAD

**Issue by ibrahimmumcu** [ahmedkaludi/accelerated-mobile-pages#1555]
Hello,

I love your plugin but there is something I couldn't find how to fix. Whenever I share an url of one of our posts on Twitter, people who are using the mobile app (iOS / Android) always seeing AMP page instead of non-AMP one. 

Is it a bug or am I missing something? I was only expecting that people are are coming from Google Search is going to see AMP pages. 

Thank you so much.

**Comment by ahmedkaludi** [comment]
Twitter adds the AMP support so we cannot do anything about it
