### ISSUE TITLE
All In One SEO Compatibility WIth AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1557]
All In One SEO Compatibility WIth AMP

Ref:  https://secure.helpscout.net/conversation/494150587/19748?folderId=1060551

**Comment by beingsmart3** [comment]
1 more Ref:  https://secure.helpscout.net/conversation/496782189/19824?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:
