### ISSUE TITLE
Add Change Endpoint feature

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1561]

**Comment by ahmedkaludi** [comment]
Reasons for failing this commit: 

- [ ] http://take.ms/ACvo3

- [ ] /amp is loaded on the custom frontpage instead of ?amp (+ one debug error)

- [ ] We must use ?amp instead of ?amp=1

**Comment by ahmedkaludi** [comment]
- [ ] It makes the homepage into non-amp: http://take.ms/VrqHE (See output http://take.ms/vSN2Y )
