### ISSUE TITLE
Menu issues In Design 1 & Design 2

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1565]
Menu issues In Design 1 & Design 2,

- [x] See this screenshot of design 1:  http://take.ms/w5Zzk

- [x] See this screenshot of design 2:  http://take.ms/YgEuS

**Comment by beingsmart3** [comment]
One more

Ref:  https://secure.helpscout.net/conversation/499513486/20061?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:
