### ISSUE TITLE
SEO Post Content Links plugin is adding "alt" attribute in "a" tag which is creating the errors

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1569]
This plugin is causing errors in the AMP validation and need to remove the attribute of "alt" from "a" tag

Plugin URL - https://wordpress.org/plugins/content-links/

Ref: https://secure.helpscout.net/conversation/495063434/19771?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:
