### ISSUE TITLE
Canonical href removed

### ISSUE THREAD

**Issue by danielmrey** [ahmedkaludi/Accelerated-Mobile-Pages#157]
Canonical href is removed as is needed

From Google: Missing URL for attribute 'href' in tag 'link rel=canonical'

**Comment by ahmedkaludi** [comment]
That's strange, Can you post the URL of that?

**Comment by danielmrey** [comment]
This is the URL:

http://handmancleaning.co.uk/?amp

Thank you Ahmed


Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by ahmedkaludi** [comment]
That's very strange, I will check and make sure that this is fixed immediately.

**Comment by danielmrey** [comment]
Thank you!

Great Plugin!!!

Daniel



Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by danielmrey** [comment]
Which validator do you use?

I found this:

https://technicalseo.com/seo-tools/amp/




Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by MohammedKaludi** [comment]
we use https://validator.ampproject.org/ to validate the amp pages

**Comment by danielmrey** [comment]
Thank you.

I reinstalled all again and now I have other issue:

Works:
http://handmancleaning.co.uk/?amp

Does not work: (404)
http://handmancleaning.co.uk/amp/

Any idea?

Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by MohammedKaludi** [comment]
go to Settings-> permalink and hit save again, it will fix the 404 redirection

**Comment by danielmrey** [comment]
Thank you, the 404 redirection worked!

Now I need to solve why the home page:
http://handmancleaning.co.uk/amp/

Shows empty canonical:
<link rel="canonical" href="" />

But not the rest of the pages, ie:
http://handmancleaning.co.uk/about/amp/




Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by danielmrey** [comment]
This may help to solve the error:

I select as Front Page the Home page which is a page (not the Blog)

When a website does not have a Blog then the /amp/ canonical for the Front page is blank but when the website has a Blog the canonical is the first post (when it should be the Front page)

See it here:
http://www.medlar.in/amp/

Thanks

Daniel.
www.danielmrey.com

**Comment by danielmrey** [comment]
Thank you for solving the issue with the new version.

Now the canonical for the home does not show the first post but now is empty, it should point to the page itself.

This is what I get from the validator: The mandatory tag 'link rel=canonical' is missing or incorrect

Thanks you for working on this!... You have a great plugin!

Daniel.
www.danielmrey.com

**Comment by danielmrey** [comment]
In Wordpress:

> Setting > Reading > Front page displays > A static page > Front Page:
*Home*

> AMP > General > Front Page: ON
> AMP > General > Select Page as Frontpage: *Home*

And in /amp/ before the canonical was pointing at the first posts, but now
with the new version the canonical tag disapears, which is better that
before but I think this should be solved and point to home page

Thank you so much for taking your time on this.

Need to leave now but will check later or tomorrow

Daniel.



Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by ahmedkaludi** [comment]
This issue has been fixed in the version we updated last night.
