### ISSUE TITLE
Thrive content is not rendered ("blank" page)

### ISSUE THREAD

**Issue by tewfik-dj** [ahmedkaludi/accelerated-mobile-pages#1575]
Hi, 
Thanks for the great tool, really useful and properly built overall

We had issues with Thrive content being skipped on amp plugin, we managed to patch this.
When the amp plugin instantiates the Amp_content() class, it passe along content from post object but apparently using post_content before apply_filters.
Tried to reorganize the order in which plugins run (making amp run after thrive) but it didn't help

amp for wp : Stable tag: 0.9.71
Wordpress : 4.9.1
Thrive architect: 2.0.16

How to reproduce : Create post in wordpress, edit using Thrive content builder
Enable amp for wp plugin, and visit /amp page for that post, content from Thrive plugin won't appear (although the rest is perfectly formatted and placed on the page)

Interim patch : in file /wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php, at line 250

`// td 201801021446 debugging the 'thrive posts empty display on amp pages`
`//		if(!empty($this->post->post_content)){ // that was the original test`
`	if(!empty(apply_filters( 'the_content', $this->post_content ))){`
`//			$amp_content = new AMP_Content( $this->post->post_content, // td that's the original one`
`			$amp_content = new AMP_Content( apply_filters( 'the_content', $this->post_content ),`

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/561627017/24578?folderId=1914712

You will find the zip file on Magazine group and credentials in the above email

**Comment by gareththomasnz** [comment]
A large number of people are unable to render post content with thrivethemes & AMP. It works on most of my posts but some have header/footer & no content. Thrive currently does not plan to support AMP. Its not just  this plugin either - the other main one has similar issue with thrive.

**Comment by gareththomasnz** [comment]
thanks tewfik-dj  your fix seems to work

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko 
Content is still blank 
non-amp: http://take.ms/iUmLw
amp: http://take.ms/YmyPpY

**Comment by gareththomasnz** [comment]
works for me

**Comment by Sejiro-Hiko** [comment]
@MohammedKaludi works on all designs on my end with `0.9.98` branch, will test them again.

**Comment by Sejiro-Hiko** [comment]
@MohammedKaludi the front page is also working fine on my end without overriding the content of the latest post

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by gareththomasnz** [comment]
Every time the plugin updates it is broken again

**Comment by gareththomasnz** [comment]
Now the source has changed & I dont know how to fix it

	private function build_post_content() {
		if( !empty($this->post->post_content) && false === ampforwp_is_home() && false === is_archive() ){
	
			$new_post_content = $this->post->post_content;
			// #2001 Filter to remove the unused JS from the paginated post
			$new_post_content = apply_filters( 'ampforwp_post_content_filter', $new_post_content );

			$amp_content = new AMP_Content( $new_post_content,

**Comment by gareththomasnz** [comment]
Most articles seem to be OK - but I changed it back to tewfik-dj's suggestion - will see whathappens

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
