### ISSUE TITLE
session_start() warning in the non-amp when mobile redirection is active

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1576]
The session_start() warning when mobile redirection is activated and that warning is displayed in the non-amp version.

See this screenshots:
http://take.ms/Bw7wZ
http://take.ms/NM6c2

Ref: https://secure.helpscout.net/conversation/496922480/19905?folderId=1060551

**Comment by ahmedkaludi** [comment]
a user suggested that it might be because of PHP FPM:

If you have access to a WHM, disable PHP-FPM. This worked for me and now it works perfectly.

**Comment by ahmedkaludi** [comment]
its when a hosting is moved and a session is trying to access the path, I think it's nothing to do with the  plugin.

**Comment by abhishekmdb** [comment]
I recently migrated my hosting and I am getting a similar warning.
What should I do?
