### ISSUE TITLE
Should have a proper Style of Pre Tag 

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1577]
Should have a proper Style of Pre Tag

Because one user uses codeshare on the site that's why it does not look good.
Ref:  https://secure.helpscout.net/conversation/498416556/20000?folderId=1060551

**Comment by ahmedkaludi** [comment]
border color should be connected with global color scheme

**Comment by RajuJeelaga** [comment]
Raju Approved.
