### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by misuv** [ahmedkaludi/accelerated-mobile-pages#1579]
Hello

I tried your plugin, it does set AMP correctly but it give me an 500 error on blog page: 

**the page is shown but there are no post in it and I receive a 500 error in console.**

here is the server error log:

#0 /wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php(406): get_query_var(‘amp’, false)
#1 /wp-content/plugins/accelerated-mobile-pages/templates/features.php(3159): ampforwp_is_amp_endpoint()
#2 /wp-includes/class-wp-hook.php(286): ampforwp_remove_support_tagdiv_cateroy_layout(Object(WP_Query))
#3 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#5 /wp-includes/class-wp-query.php(1634): do_action_ref_array(‘pre_get_posts’, Array)
#6 /wp-in in m/wp-includes/query.php on line 28

I use php 7.0 + cloudflare

until this error is fixed I have to disable your plugin

**Comment by ahmedkaludi** [comment]
That's strange. Can you try the latest version? 

It should work perfectly
