### ISSUE TITLE
I have such problems - Thumbnails stretching

### ISSUE THREAD

**Issue by Ysery** [ahmedkaludi/accelerated-mobile-pages#1580]
I made two test sites to show the emerging problems visually 
https://best-sample.000webhostapp.com/amp/   Login: admin Pass: jhgjhg.675
https://poor-sample.000webhostapp.com/amp/   Login: admin Pass: fhjkdfgh3.44

If you look, you will understand why I chose this approach

![2](https://user-images.githubusercontent.com/24987252/34651744-3def885a-f3e5-11e7-970c-3ab826f3b6fd.PNG)

![default](https://user-images.githubusercontent.com/24987252/34651743-3a8055aa-f3e5-11e7-9e89-7a8d174e66a2.PNG)

![4](https://user-images.githubusercontent.com/24987252/34651796-4d74f23c-f3e6-11e7-9015-41c86b95da32.PNG)

![3](https://user-images.githubusercontent.com/24987252/34651794-48963b68-f3e6-11e7-8b0c-c6defd8d2be6.PNG)

![6](https://user-images.githubusercontent.com/24987252/34652263-f8e8ccaa-f3ec-11e7-9b59-d2c04fe9e24e.PNG)

![5](https://user-images.githubusercontent.com/24987252/34652265-ff1c4ca0-f3ec-11e7-88cc-e3c493d8fe32.PNG)

Sorry for My English.

**Comment by MohammedKaludi** [comment]
@Ysery thank you very much for explaining in detail. I have added this ticket in this weeks milestone and will make sure it gets fixed in this update.

Also, I will let you know if I or my team need anything I will let you know.

Thank you,
Mohammed Kaludi

**Comment by Ysery** [comment]
@MohammedKaludi 
Many thanks

**Comment by MARQAS** [comment]
Hi @Ysery , 
Can you check now? 
I just updated the plugin and it was smooth again.
Did you make any changes in 0.9.72 version of your plugin?

**Comment by Ysery** [comment]
Hi @MARQAS 
No changes were made to the plugin files. You can go to sites and compare them.

https://best-sample.000webhostapp.com/ FTP - Address: files.000webhost.com  Port: 21 Username: best-sample Password: YLg!ODY!MFj$2jxBp*H5 
https://poor-sample.000webhostapp.com/ FTP - Address: files.000webhost.com  Port: 21 Username: poor-sample Password: &6j$@sVjpQDXAy2*bV1d
----

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Ysery** [comment]
Hello.
Now do not appear at all

![default](https://user-images.githubusercontent.com/24987252/35292637-2c948ba6-0082-11e8-9937-4475577b012b.PNG)
![2](https://user-images.githubusercontent.com/24987252/35292641-31836dc6-0082-11e8-9ff1-0bd058cfd7b5.PNG)

**Comment by Ysery** [comment]
Hello
Unfortunately, everything is not displayed as it should

ver. 0.9.74.1 -> https://poor-sample.000webhostapp.com

![3](https://user-images.githubusercontent.com/24987252/35397058-7bfc651e-01ff-11e8-8779-752c211df2b0.PNG)

![2](https://user-images.githubusercontent.com/24987252/35397074-87afda9e-01ff-11e8-9ca5-4ddd30f2d9b3.PNG)

![default](https://user-images.githubusercontent.com/24987252/35397066-7f924b12-01ff-11e8-98f7-b2ff131ab212.PNG)

**Comment by Ysery** [comment]
Problems in the new version (0.9.81) remained https://poor-sample.000webhostapp.com

**Comment by Ysery** [comment]
Hello @ahmedkaludi

Nothing has changed in the version 0.9.83.1 https://poor-sample.000webhostapp.com/amp/

In version 0.9.69.1 everything is perfect https://best-sample.000webhostapp.com/amp/

**Comment by MARQAS** [comment]
@Ysery 
Can you check now?

**Comment by Ysery** [comment]
These pictures (xxxx-logo-big.jpg\png) are for social networks ONLY.
There can be anything you like, not necessarily a small copy of the picture that is placed in the article.

**Comment by Ysery** [comment]
As the "Featured image", must take the first image from the article, as it is done in the version of the plugin 0.9.69.1
xxx-logo-big.png and xxx-logo-big.jpg should not be used at all. They are ONLY for social networks.

**Comment by MohammedKaludi** [comment]
Hey @Ysery,

I have just logged in to your site and done some modifications.

1.  To solve the image stretch in related posts. I removed the custom CSS you added in in css editor http://take.ms/YbHbW and it fixed the issue  http://take.ms/PSuIl

2. To fix the featured image not loading issue, I activated "Duplicate Featured Image" from the options panel http://take.ms/b32uV
And it fixed this issue as well http://take.ms/OqP6u

I think all of your queries have been resolved, do let me know if you need anything else.

Thank you very much and I really appreciate your patience and co-operation,
Mohammed Kaludi

**Comment by Ysery** [comment]
I think I understand the cause of the problem

the code is processed correctly:
`<img class="alignleft" src="https://.....png" alt="Some Text" width="200" height="133">`


the code is not processed correctly:
`<img width="200" height="133" class="alignleft" alt="Some text" src="https://....png">`

**Comment by ahmedkaludi** [comment]
@ysery Has your problem been solved?

**Comment by Ysery** [comment]
No.  I have most of this code, and it is not handled correctly:

`<img width="xxx" height="xxx" class="alignleft" alt="Some text" src="https://....png">`

**Comment by Ysery** [comment]
The problem remains in the version 0.9.86
I can not update the plugin because of this

**Comment by Sejiro-Hiko** [comment]
@Ysery can you please check with version 0.9.97 and let us know?

**Comment by Sejiro-Hiko** [comment]
Current set up in the plugin for the thumbnail is what we needed by resizing the image and we'll not be changing that but as for the image clarity issue that will be resolved in the #1619
