### ISSUE TITLE
ampforwp_is_front_page() is not working in the newspaper theme

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1583]
Need to replace this "ampforwp_is_front_page()" with this function "is_home()" for displaying the content in the newspaper theme.

See this screenshot: http://take.ms/n8mnp

Ref: https://secure.helpscout.net/conversation/500481844/20107?folderId=1680011

**Comment by MohammedKaludi** [comment]
:+1:
