### ISSUE TITLE
Error in wp-includes/functions.php on line 4146

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1584]
This appears in the head section -

<b>Notice</b>: AMP_Post_Template::get was called <strong>incorrectly</strong>. Called for non-existant key ("amp_component_template"). Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 0.1.) in <b>/var/www/vhosts/emprunter-malin.com/staging.emprunter-malin.com/wp-includes/functions.php</b> on line <b>4146</b><br />.

The staging site is here:
https://secure.helpscout.net/conversation/500991652/20144?folderId=1680011

**Comment by MARQAS** [comment]
It is related to AMP Gravity forms, not the Core plugin.
