### ISSUE TITLE
Fatal error: Cannot redeclare ampforwp_add_admin_styling() 

### ISSUE THREAD

**Issue by hasan** [ahmedkaludi/accelerated-mobile-pages#1585]
Hello,

i am trying to install amp for wp to my web site but i am getting error like that 

"Fatal error: Cannot redeclare ampforwp_add_admin_styling() (previously declared in /site-path/wp-content/plugins/accelerated-mobile-pagessss/includes/includes.php:48) in /site-path/wp-content/plugins/accelerated-mobile-pagessss/includes/includes.php on line 55"

php version : 7.0

did anybody get this error ?

**Comment by ahmedkaludi** [comment]
@chelebi45 why does your directory has named like /accelerated-mobile-pagessss/ ?

Do you have the same plugin in two different directories?
