### ISSUE TITLE
Add Support for SeoPress

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1589]
So could you incluce in "templates/features.php" something like this for SeoPress:if (is_plugin_active('wp-seopress/seopress.php')) { $site_title = get_post_meta($post->ID,'_seopress_titles_title',true); } And also for a frontpage?I´ve added it manuelly because i am using SeoPress. Would be great if that implemented in one future update.

Plugin - https://wordpress.org/plugins/wp-seopress/

Ref: https://secure.helpscout.net/conversation/501787177/20180?folderId=1060551

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4f8aad5b6a7ea18ac4845fda469ba9f281b76d95#diff-6aa5512f7dd8d5ce60fc97b0f340912cR2526
 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/44ba264c34189112acc5e00cbd12b38dd22131e1#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4778

Use function_exists or class_exists in the place of is_plugin_active('wp-seopress/seopress.php')

**Comment by MARQAS** [comment]
No classes present and unable to use the functions

**Comment by ahmedkaludi** [comment]
need to discuss this one.

**Comment by MohammedKaludi** [comment]
This is the setup from Options panel: http://take.ms/7oBXE 

and this is the reflection: http://take.ms/JQKRn and http://take.ms/wKEnd

Also Structured Data is not correct: http://take.ms/LvaJYR

**Comment by pegazee** [comment]
Title for single is not working:

1)  settings for single: https://take.ms/JtWrD

2) non-amp version: https://take.ms/Uk4wU

3) AMP version: https://take.ms/SXWiq

**Comment by ajeetku** [comment]
Use escaping before print $option values, check in all other meta tags

**Comment by ajeetku** [comment]
2 more places $option need esc_attr, check while adding in master

**Comment by pegazee** [comment]
Still, Title is not working in single when I'm changing the settings from here: https://take.ms/7NMdp
And also when I'm changing the settings from the SEOPress meta box: https://take.ms/D6QC5 . In non-amp working perfectly but in the amp, not working. Screenshots: non-amp > https://take.ms/JYx69, amp > https://take.ms/62S4iy

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
use `class_exisits` or `function_exists` instead of `plugin_active`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/10ca3999656362b102a50f8114630a9657876063#diff-04b38a94ddf918855eed7a68ecaa512dR239

**Comment by MohammedKaludi** [comment]
escaping is missing 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7f66b79313b0f0d9d66d1cc3fe359e18df7a9fcd#diff-1301281de287d2aed98746fc9ba777b4R992

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
