### ISSUE TITLE
Divi Compatibility with AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1590]
Divi Compatibility with AMP

Ref:  https://secure.helpscout.net/conversation/502800167/20230?folderId=1060551

**Comment by zabi09** [comment]
One more - https://secure.helpscout.net/conversation/502773328/20226?folderId=1680011

**Comment by ajeetku** [comment]
Didn't find the issue, I checked with following modules: Image, Gallery, Text, Blurb, tabs, Slider, Testimonial and etc.

**Comment by MohammedKaludi** [comment]
:+1:
