### ISSUE TITLE
Front page blank in AMP with SiteOrigin

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1592]
From Reading settings, if we select the homepage as the sample page and the same page as the front page in the AMP settings then the AMP homepage is blank.

Ref: https://secure.helpscout.net/conversation/496953900/19908?folderId=1060551

**Comment by MARQAS** [comment]
Tested and working properly ( Tested on User website as well)

**Comment by MohammedKaludi** [comment]
New code is now working. Tested properly on customers site.
