### ISSUE TITLE
First post is appearing rather than the front page with SiteOrigin Widgets Bundle

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1593]
If we enable the SiteOrigin Widgets Bundle then the first post is appering not the front page.

Ref: https://secure.helpscout.net/conversation/496953900/19908?folderId=1060551

**Comment by MARQAS** [comment]
Tested on localhost and user website and its working perfectly fine
.

**Comment by MohammedKaludi** [comment]
New code is now working. Tested properly on customers site.
