### ISSUE TITLE
Custom template for post type and taxonomy in the AMP Theme Framework

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#1594]
I have 2 custom template
a) post-type=bingo-site , taxonomy=bingo-category , taxonomy-bingo-category.php
b) post-type=slot-site , taxonomy=slots, taxonomy-slots.php

The question is how i create a AMP template with different Taxonomy also same as single-bingo-site.php and single-slot-site.php in AMP . I am using AMP Theme Framework plugin and in plugin folder there is not taxonomy template only Archive.php

**Comment by ajeetku** [comment]
Changes committed on 906ec35 for custom post type

**Comment by MohammedKaludi** [comment]
All the single is breaking in ATF

**Comment by MohammedKaludi** [comment]
:+1:
