### ISSUE TITLE
Caption tag is not working properly with the images in the page builder text module

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1596]
Images are appearing along with the caption tag in the page builder text module in the latest version but in 0.9.67 it's working fine.

Ref: https://secure.helpscout.net/conversation/498814633/20031/?folderId=1060551

**Comment by MARQAS** [comment]
It has been resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/af0301f7b2de1a244e9b87dd416108a54d10f9af
