### ISSUE TITLE
Cannot see active visitors on google analytics

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1599]
The users cannot see any active visitors in google analytics real time because of addition space in the Google Analytics ID

Screenshot: http://take.ms/fDGbE

Ref: https://secure.helpscout.net/conversation/501965511/20192?folderId=1680016
Ref: https://secure.helpscout.net/conversation/488529697/19436/?folderId=1680016

**Comment by MARQAS** [comment]
It was due to users only.
They were adding an additional space.
There is no problem in the code.

**Comment by ahmedkaludi** [comment]
@MARQAS Yes, but that's the whole point. We need to strip spaces since we have seen some people doing that by mistake.

**Comment by ahmedkaludi** [comment]
nice!
