### ISSUE TITLE
Minor bug – structured data type

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1602]
There is a minor bug in the structured data selection of article, webpage etc.

Familiar set up –

Static home page + a blog posts page

Set the structured data type for posts to Article and for pages to Webpage. The static home page doesn’t get Webpage – it gets Article. In other words the static home page is being treated like it were a post and not a page. It is like the problem we had early on that static home pages are treated like archives when they are not.

As an aside – there also needs to be a third option (enhancement)

Archives, tags, blog posts page -> option to set this as a collection page.

https://wordpress.org/support/topic/minor-bug-structured-data-type/

**Comment by MARQAS** [comment]
Archives, tags, blog posts page -> option to set this as a collection page.
These granular options will come with Structured data update or extension may be.
