### ISSUE TITLE
AFS Analytics Integration 

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1605]
AFS Analytics integration in AMP

Ref:  https://secure.helpscout.net/conversation/504917754/20319?folderId=1060551

**Comment by MARQAS** [comment]
There is no sample code or documentation of it so contacted them regarding the same.
Let's wait for their response.

**Comment by MARQAS** [comment]
Response: https://secure.helpscout.net/conversation/515577461/21064/?folderId=1060551
