### ISSUE TITLE
TGMPA conflict  

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#161]
https://wordpress.org/support/topic/amp-killed-access-to-my-sites-admin-dashboard/

**Comment by khaledMohammed000** [comment]
@ahmedkaludi After some testing this has been found that its possibly due to outdated version being used in themes

**Comment by ahmedkaludi** [comment]
I have tested this multiple times, this seems to be an issue with the theme that also implements the TGM library, because Skin theme also has the TGM and it didn't threw any error.
