### ISSUE TITLE
Styling not loading on  Custom Front page

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1610]
When I select the custom front page with the swift theme, Styling was not loading properly.

Screenshot > http://take.ms/cRBOq
> http://take.ms/9eWDL

**Comment by Sejiro-Hiko** [comment]
need more to exactly what is missing as per my testing it seems the styling is properly getting added.

**Comment by ahmedkaludi** [comment]
Approved
