### ISSUE TITLE
Crayon Syntax Bug

### ISSUE THREAD

**Issue by iparrabb** [ahmedkaludi/accelerated-mobile-pages#1615]
Hi guys,

This plugin doesn't works with [Crayon Syntax](https://es.wordpress.org/plugins/crayon-syntax-highlighter/), the code not appears.

![captura de pantalla 2018-01-17 a las 7 06 37](https://user-images.githubusercontent.com/13960435/35028197-02a9872e-fb55-11e7-8867-d64d12b11dab.png)

The plugin does not work with [gist oembed](https://es.wordpress.org/plugins/oembed-gist/) either.

![captura de pantalla 2018-01-17 a las 7 10 43](https://user-images.githubusercontent.com/13960435/35028280-920a252c-fb55-11e7-9f63-75b985d93c51.png)

Any help?

**Comment by Sejiro-Hiko** [comment]
@iparrabb we've added the gist support you can check that and can you describe little more about the crayon issue?

**Comment by ahmedkaludi** [comment]
Regarding the original issue, We have waited for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
