### ISSUE TITLE
CSS quotes are not rendering in the AMP version (After 0.9.73)

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1616]
Quotes are displaying some other numbers 
First example - 
http://take.ms/HLvc9
Second example -
http://take.ms/KU80R
Output -
http://take.ms/fXgn2

Ref: https://secure.helpscout.net/conversation/506678216/20389?folderId=1680011

**Comment by ahmedkaludi** [comment]
https://wordpress.org/support/topic/errors-after-update-13/#post-9869751

**Comment by ahmedkaludi** [comment]
https://wordpress.org/support/topic/css-syntaxis-errors-in-amp-pages/

**Comment by MohammedKaludi** [comment]
:+1:
