### ISSUE TITLE
Should have an SRC set in the Featured Image

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1619]
Should have an SRC set in the Featured Image

Ref:  https://secure.helpscout.net/conversation/507485486/20438?folderId=1060551

**Comment by ahmedkaludi** [comment]
It's said that it's not added for swift, so then where is it added? because "components/loop/loop.php" is used for Swift.

**Comment by MohammedKaludi** [comment]
@ahmedkaludi `amp_loop_image()` is used in Design 1, Design 2 and Swift.

So we are using the common function.

Design 3 images are not generating srcset need to do that, also find the way to add this feature in Swift.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
src-set should apply only be for full images, if any other control is selected then srcset should not load.

**Comment by MohammedKaludi** [comment]
👍 ready to merge, marqas do consult with me before merging.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
