### ISSUE TITLE
AMP Publisher logo guidelines 

### ISSUE THREAD

**Issue by alexchuin** [ahmedkaludi/accelerated-mobile-pages#162]
Hello,

Thanks for the plugin !

Why don't you follow AMP Publisher Logo Guidelines ?
190x36 is not allowed. ("Be exactly 60px high (preferred), or exactly 600px wide. For example, 450x45px would not be acceptable, even though it fits in the 600x60px rectangle.")

Check "AMP Logo Guidelines" here: https://developers.google.com/search/docs/data-types/articles

Thank you !

**Comment by MohammedKaludi** [comment]
Tested.
