### ISSUE TITLE
Schema and metadata improvements

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1620]
My team did under plugins/accelerated-mobile-pages/templates/features.php this:

Líneas 2853 y 2854 - Structured Data
global $post;
$desc = strip_tags ( convert_chars( stripslashes(get_post_meta ( $post->ID, '_yoast_wpseo_metadesc' ,true) )) );

Lineas 3048 y 3049 - Metadata
global $post;
$desc = strip_tags ( convert_chars( stripslashes(get_post_meta ( $post->ID, '_yoast_wpseo_metadesc' ,true) )) );

Those changes boost SEO and solve problems with default post content with smarties and special codes and so on.

Ref: https://secure.helpscout.net/conversation/507765182/20449?folderId=1060551

**Comment by MARQAS** [comment]
This is used to get the description from Yoast. But we are already getting the description from Yoast. So no need for this according to my knowledge.
