### ISSUE TITLE
Premium  AMP Ads Plugin update

### ISSUE THREAD

**Issue by wrrr** [ahmedkaludi/accelerated-mobile-pages#1621]
Update Failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

I raised this on WP forums yesterday. Continues to be an issue. I have a premium license for this plugin.

**Comment by ahmedkaludi** [comment]
@wrrr This is a strange issue which only happens sometimes, Can you please download a fresh copy and install it on your website? That should fix it for now.

We are improving our update system, it will not be a problem after that.

**Comment by wrrr** [comment]
I downloaded yesterday and now it says version 1.8 is out and it throws the same error. 1.8 is not the version in my premium download area. This is a pain and we have it on 3 sites. We have php7 and I don't see any errors on our server when trying to update this.

**Comment by ahmedkaludi** [comment]
@wrrr I really apologize for the inconvince. We just updated the file in the Accounts area. Please download it from https://accounts.ampforwp.com - That should fix the issue.

Regards
