### ISSUE TITLE
Errors in features.php of the accelerated-mobile-pages when Advanced AMP Ads is active

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1622]
Errors in the features.php of the accelerated-mobile-pages when Advanced AMP Ads extension is activated
pdf: https://secure.helpscout.net/file/9a54d858aaf49a63/15580/1378773280/110220538/amp%2520error%2520after%2520troubleshooting/

Ref: https://secure.helpscout.net/conversation/505871565/20362?folderId=1680011

Ref: LocalHost

**Comment by MohammedKaludi** [comment]
:+1:
