### ISSUE TITLE
AMP_Post_Template::get was called incorrectly

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1623]
Notice: AMP_Post_Template::get was called incorrectly. Called for non-existant key ("amp_component_template"). Please see Debugging in WordPress for more information. (This message was added in version 0.1.) in C:\xampp\htdocs\wp\wp-includes\functions.php on line 4147

Screenshot: http://take.ms/3jqr9

Ref: LocalHost

**Comment by MARQAS** [comment]
Its not related to Core plugin but due to other extensions which uses amp-mustache

**Comment by MARQAS** [comment]
#1584

**Comment by amaherjr** [comment]
I have the same issue: AMP_Post_Template::get was called incorrectly on [mercatoday.com
](url)
What is the fix?

**Comment by Zabi09** [comment]
@amaherjr Are you using any of our paid extensions and maybe due to that you are facing this issue? Please let us know
