### ISSUE TITLE
A way to override any existing file directly from /amp folder of theme

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1625]
A way to override any existing file directly from /amp folder of theme 

- [x] 1 /amp in thme folder

- [x] 2 child plugin

Ref: https://secure.helpscout.net/conversation/496782970/19839?folderId=1060551

**Comment by aglipanci** [comment]
👍 Any information on this one?

**Comment by ahmedkaludi** [comment]
## Reasons

- [ ] It should allow us to override a single file, like moving "header" .php file to a /amp folder, then it should just over ride that one.

**Comment by ajeetku** [comment]
5a4acc5 changes added for header-bar file

**Comment by ahmedkaludi** [comment]
- [ ] It's working perfectly! But It doesn't override index.php for some reason. Let's see why it doesn't.
