### ISSUE TITLE
0.9.80 improvements

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1627]
Scroll for the tasks

**Comment by RajuJeelaga** [comment]
- [ ] amp_related_posts(); 
Show and Hide Options for the  Excerpt and Thumbnail Resizing, Make sure that once these options are done, Please add these in the Documentation.

**Comment by RajuJeelaga** [comment]
- [ ] Category Module AMP image Issue (MARQAS).

- [ ] Icons Library need to updates with New Icons (Raju/Ahmed).

- [ ] Globar Color Scheme (Raju/Ahmed).

- [ ] Screenshot of Swift & Demo URL.(Raju)

- [ ] Custom Logo Changes in the Options. (Raju)

**Comment by zabi09** [comment]
Case 1 - https://secure.helpscout.net/conversation/510016945/20590?folderId=1060551

- [ ] twitter icon not working - http://take.ms/hbeJg

- [ ] font are not loading

**Comment by ajeetku** [comment]
Related posts images are not displaying (no src width height) [869fd5b]
image crop compatible with Jetpack Photon

**Comment by ahmedkaludi** [comment]
## 0.9.80 Review Checklist 
- [ ] http://take.ms/MUY2j [Ahmed]

**Comment by MARQAS** [comment]
amp_component template is due to extensions but not from our core.

**Comment by ahmedkaludi** [comment]
Future: Use Case for Typography:
- [ ] Raleway for headings
- [ ] OpenSans for paragraphs

**Comment by MARQAS** [comment]
https://ampforwp.com/tutorials/article/related-posts/

**Comment by RajuJeelaga** [comment]
## After the Release .80 Update Bugs List..
