### ISSUE TITLE
We should have an option to display the business module

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1628]
We should have an option to display the business module like
- [x] Address
- [x]  Email
- [x] Phone call

For more details see this screenshot:  http://take.ms/neUSW

Ref:  https://secure.helpscout.net/conversation/507870482/20455?folderId=1060551

**Comment by MohammedKaludi** [comment]
http://take.ms/mHmTk

Links are not going to the proper location

All three items are going on the wrong location.

1. http://localhost/amp/
2. mailto:xyz@gmail.com/amp/
3. tel:+91%20123456/amp/

**Comment by ahmedkaludi** [comment]
make sure we don't have a debug issue like this:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3728d40d69aac3042b094a46eb5c80a731f74595
#2407

**Comment by RajuJeelaga** [comment]
Closed by @ahmedkaludi
