### ISSUE TITLE
We should have an option to display the Map Module

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1629]
We should have an option to display the Map Module like

See this screenshot:  http://take.ms/Yj3qi

Ref:  https://secure.helpscout.net/conversation/507870482/20455?folderId=1060551

**Comment by MohammedKaludi** [comment]
rename the files as we have discussed.

**Comment by MohammedKaludi** [comment]
1. Need to add a new field for API key: http://take.ms/NFnuM

2. http://take.ms/JzFvr when View mode is selected  http://take.ms/WrbjM

3. Remove your API key as default

**Comment by santosh8793** [comment]
d8ac867 Added changes to the map module Ticket no #1629

**Comment by ahmedkaludi** [comment]
- [ ] Name should with Map: http://take.ms/G0IMK

- [ ] Get API key link next to feild: http://take.ms/2liHQ

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Need to improve the message:
https://monosnap.com/file/G1NqzLcDIC21r17hM1I9HJl2InJCeA

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
