### ISSUE TITLE
Link to the categories in loop of Design 3 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1632]
Link to the categories in loop of Design 3  everywhere.

http://take.ms/CQBw4

I realized after reading this: https://wordpress.org/support/topic/link-to-the-categories-in-archive-php/#post-9884059

**Comment by ahmedkaludi** [comment]
- [ ] Category class was removed, http://take.ms/wZM5K - It's very important to have this one since it's been used by many people.

**Comment by ahmedkaludi** [comment]
You still need to add the proper class to the option: http://take.ms/eTvgj
