### ISSUE TITLE
Instant Article Support with Polylang 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1639]
How can generate multilingual posts as Instant articles? They are coming only in English which is default language.

REF: https://wordpress.org/support/topic/how-can-i-generate-instant-article-for-a-multilingual-site/#post-9887542

**Comment by iPNet** [comment]
Thank you for considering this request.

**Comment by ahmedkaludi** [comment]
This has been added in https://ampforwp.com/polylang-for-amp/
