### ISSUE TITLE
Wrong unicode font in Facebook Instant Articles

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1640]
Wrong Unicode font in Facebook Instant Articles

Screenshot: http://take.ms/bHFKC
Ref: https://secure.helpscout.net/conversation/509538023/20543?folderId=1060551

**Comment by MARQAS** [comment]
There are only 2 possibilities for this issue. 
1. mb encoding is disabled
2. Use mb_convert_encoding to encode such data.
We are using mb_convert_encoding so no issue from our end. And it seems that user has also enabled the Multibyte strings so no issue from his end as well. It is working fine. 

Tested on Localhost: 
Without mb_convert_encoding: http://take.ms/aNRpM
With mb_convert_encoding: http://take.ms/SJkGn

**Comment by ahmedkaludi** [comment]
@MARQAS Need to discuss this one.

**Comment by ahmedkaludi** [comment]
discussed. No need to go further on this.
