### ISSUE TITLE
If the post is in featured slider in design 3 then it should not be there in post below

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1644]
If the post is in featured slider in design 3 then it should not be there in post below so there is no duplicate post

See this screenshot: http://take.ms/1U8pw

Ref: https://secure.helpscout.net/conversation/509842928/20562?folderId=1060551

**Comment by Sejiro-Hiko** [comment]
This ticket will be on hold for now and will be added for later milestone

**Comment by MARQAS** [comment]
Ahmed here.

We're going to skip this for now. We don't want to have a lag in the perf.
