### ISSUE TITLE
Space dissaper in the URL in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1645]
Space disappear in the URL in AMP

Ref:  https://secure.helpscout.net/conversation/506608764/20387?folderId=1060551

**Comment by Sejiro-Hiko** [comment]
the issue was related to the search query and now it's seems working fine on the user's end as well just waiting for the user's confirmation.

**Comment by ahmedkaludi** [comment]
Regarding the original issue, We have waited for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
