### ISSUE TITLE
Disable Instant Articles on Pages

### ISSUE THREAD

**Issue by azzronulation** [ahmedkaludi/accelerated-mobile-pages#1650]
Our website uses the static page + page builder configuration for our homepage which poses problems when someone links to our site on Facebook. Rather than opening up the homepage it serves the page builder shortcodes, which you can imagine isn't very helpful.

It'd be awesome to be able to disable Instant Articles on pages as a whole, or specific pages.

**Comment by Sejiro-Hiko** [comment]
@azzronulation we do not generate the Instant Article on "pages" as well as on "Homepage" can you please share some url's or example of the issue.

you can reach us here if you like `https://ampforwp.com/support/` .

**Comment by MohammedKaludi** [comment]
Also if you are referring as turnoff instant articles on specific posts then, we created this feature a few days ago and that will be pushed in 0.9.98 update.

More about this ticket here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1297

**Comment by ahmedkaludi** [comment]
Regarding the original issue, We have waited for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
