### ISSUE TITLE
CSS Classes not being saved in AMP Page Builder

### ISSUE THREAD

**Issue by Aileron79** [ahmedkaludi/accelerated-mobile-pages#1651]
Content and CSS Classes are not being saved properly in AMP builder. Tried this with and without plugins disabled, same result. You might want to investigate this behaviour.

https://www.useloom.com/share/d07a167308f548c8ac8d5cae90d5db1f

Workaround:
Until this is fixed I would like to manually edit the code generated by the AMP Page Builder. Where exactly does the plugin store this code in the DB?

**Edit:** Did some further investigation, obviously it is NOT a problem when saving the page rather than the classes being removed when editing the AMP page with the editor. I've taken a much longer video here highlighting the issue:

https://www.useloom.com/share/78151f0fae7e4e098b50a925af3ec644

Further Edit:
Same applies to content:

https://www.useloom.com/share/76c939b3f12649799f265dc4df9fcdbe

**Comment by Aileron79** [comment]
Discovered the AMP structure in the postmeta table where meta_key ="amp_page_builder". When disassembling the JSON structure, I discovered some nonsense:

`
               "css_class":"Content%20Goes%20Here"
`

![ampshot](https://user-images.githubusercontent.com/16278437/35332494-6a0996d2-010b-11e8-9154-31793462adc4.PNG)

**Comment by ahmedkaludi** [comment]
with the new AMP page builder v3 and this should be fixed.
