### ISSUE TITLE
How to Show Last Modified Date in Amp Sites 

### ISSUE THREAD

**Issue by Swagatam1975** [ahmedkaludi/accelerated-mobile-pages#1656]
Dear Ahmed,

I am using your amp plugin, and it is working great for me. It seems to have most of the features included in it except a few such as the option to show Last Modified date in the posts.

Therefore I would request you to kindly create an option in your plugin where we can quickly implement this feature. Or alternatively you can provide us with an appropriate code which could be added in the universal "code snippets plugin" for the getting the same results.

Your kind help will be greatly appreciated.

Regards
Swagatam

**Comment by ahmedkaludi** [comment]
We already have this option in the single section
