### ISSUE TITLE
Featured image stretched vertically

### ISSUE THREAD

**Issue by danielmrey** [ahmedkaludi/Accelerated-Mobile-Pages#166]
Featured image stretched vertically

See it here:
http://www.tootingpharmacypractice.co.uk/about/amp/

Thank you!

Daniel.

**Comment by khaledMohammed000** [comment]
@danielmrey  Thanx for creating the issue what exactly did you mean when you said that the image is stretching vertically 

see it here:
http://take.ms/I0pVV

I could not recreate the issue , Please try it once more and let me know if the problem still exists

**Comment by MohammedKaludi** [comment]
@khaledMohammed000 Daniel has added some custom css to fix the issue. If you remove the styling it will recreate the stretch in featured image. http://take.ms/ZAsaJ

**Comment by khaledMohammed000** [comment]
@danielmrey Instead of you manually having to write Image size in custom CSS section I have given an option wherein when you opt for a featured Image you get to customize its dimensions ...By default the dimension set is 512 * 300 px

**Comment by khaledMohammed000** [comment]
@danielmrey what you did is causing Validation issues in your AMP Pages ..... Thanx for letting us know :)

**Comment by khaledMohammed000** [comment]
This <a href="https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/bf55f1f35deb684d71ab5ca1cc1f8d3d8d27c1c7">Commit</a> Solves your issue .... **Am closing this Issue as its solved**
