### ISSUE TITLE
structured data issues

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1660]
The structured page type for a blog posts page is not working - i.e. static home page is Webpage and posts are set to Article. A blog posts page is still being set to Article when it is a Webpage or more correctly a CollectionPage. 

Things I have asked about for a long time:

1. Scripts in header or footer option on a per page basis. This is needed so structured data can be added on a per page basis (for example, a webpage that contains a localbusiness or an event). It also allows people to define hreflang tags for multi language sites. Conditionally testing in functions.php for a specific AMP page and embedding additional structured data is a pain. 

2. Define structured page type on a per page basis (for example AboutPage, ContactPage or more specialized types like MedicalWebPage, etc).

**Comment by MARQAS** [comment]
Regarding the other things, we are working on them, they will be available soon.

**Comment by MohammedKaludi** [comment]
:+1: 
Other features will be added very soon as we are working on Structured data.
