### ISSUE TITLE
Integrating New Updates API for extensions

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1661]
Integrating New Updates API for extensions

**Comment by ahmedkaludi** [comment]
As discussed with @MARQAS

**Comment by ahmedkaludi** [comment]
## Task

- [ ] This was causing fatal error: http://take.ms/E9dEx "amp_ads_check_license" let's rename it to something else.

**Comment by MohammedKaludi** [comment]
:+1:
