### ISSUE TITLE
Add a slider / grid of images full width slider to the home page

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1665]
Is there any way to add a slider/grid of images, or use the page builder or widgets, for full width to the main blog homepage please, so it looks more like my current desktop blog homepage.
See this screenshot: http://take.ms/8DIRZ

Theme - Curated ( TF )

Ref: https://secure.helpscout.net/conversation/509932964/20579?folderId=1060551

**Comment by ahmedkaludi** [comment]
this will be added as a part of amp layouts
