### ISSUE TITLE
Shortcodes and Widgets do not appear in Amp version

### ISSUE THREAD

**Issue by danielmrey** [ahmedkaludi/accelerated-mobile-pages#167]
Shortcodes and Widgets do not appear in Amp version

> I use a Shortcode to display a form in my contact page
> I use Widgets in sidebar to show Subpages and Posts

Thank you!

Daniel.

**Comment by ahmedkaludi** [comment]
@danielmrey Can you please explain this issue?

**Comment by danielmrey** [comment]
Sorry, I am currently on hollidays, will come back to you shortly

Thank you

Daniel.



Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by danielmrey** [comment]
Hi:

SHORTCODE: 

In this contact page:
http://www.tootingpharmacypractice.co.uk/contact/

I am using this shortcode to generate the form:
[cscf-contact-form]

From this plugin:
https://wordpress.org/plugins/clean-and-simple-contact-form-by-meg-nicholas/

When you see the Amp page, the form does not show.

SIDEBAR WIDGET:

I use widgets in the sidebar to show contents, but in the Amp version they do not show, se it in this page: http://www.tootingpharmacypractice.co.uk/

The right column "Opening Hours"... does not appear in the Amp version

Thanks

Daniel.
