### ISSUE TITLE
Major Content Mismatch when using WeGlot with AMPforWP

### ISSUE THREAD

**Issue by SaiGonSeamus** [ahmedkaludi/accelerated-mobile-pages#1670]
We have started using WeGlot for our multilingual site. 

We never had any AMP errors with google before hand but now we do.

This is their position : 

Weglot doesn't create AMP indexation issue. 
We put HREFLANG tags and give you dedicated URLs to your website.
As advice by the Google SEO Best Practices, we optimize your SEO.

Get more info: 
WordPress - How does Weglot manage the SEO?

http://support.weglot.com/article/99-wordpress-how-weglot-manage-seo

Any advice on how we debug this to find the problem?

**Comment by SaiGonSeamus** [comment]
Hi, 

This and #1756 https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1756

have gotten so bad that Google is warning about the AMP implementation in search results.

any idea if these will be resolved in the next release? Otherwise we have no option but to pull the plugin.

**Comment by SaiGonSeamus** [comment]
This is still an issue for us.

**Comment by SaiGonSeamus** [comment]
We have disabled the weglot plugin for AMP and it still gives us the same errors.

**Comment by ahmedkaludi** [comment]
We glot has added the compatibility with our plugin! Try and let me know.
