### ISSUE TITLE
Cornerstone shortcode rendering in AMP version

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1671]
Cornerstone shortcode rendering in the AMP version
Ref: https://secure.helpscout.net/conversation/511534984/20766?folderId=1680011

**Comment by MARQAS** [comment]
It's working properly. The user is having this issue only in one post.
Contacted him, waiting for his reply

**Comment by MARQAS** [comment]
I guess #1738 will resolve this one as well.

**Comment by MohammedKaludi** [comment]
:+1:  yes @MARQAS I think the same.
