### ISSUE TITLE
AMP Swift Theme Beta creating errors

### ISSUE THREAD

**Issue by zabi09** [ahmedkaludi/accelerated-mobile-pages#1672]
We get errors on our site when trying to load AMP.
Using both Beta plugin and other latest version.

Screenshot: http://take.ms/c96J8

Ref: https://secure.helpscout.net/conversation/514454155/20970?folderId=1680011

**Comment by MARQAS** [comment]
These errors have already been resolved in Pre-0.80 versions.

**Comment by ahmedkaludi** [comment]
- [ ] http://take.ms/lVGoT
