### ISSUE TITLE
Enable Pagination Support in the AMP Category loop for adding Blog from Page builder

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1676]
Ref: https://bebemamae.com/quero-ser-mamae/sobre-gravidez/tudo-sobre-parto/

**Comment by ahmedkaludi** [comment]
We have a issue of carousel in category module, until that is fixed, then we cannot check it.

**Comment by ahmedkaludi** [comment]
- [ ] Infinite scroll option for this category module: https://secure.helpscout.net/mailbox/cfb9786cbb6b9b7c/chats/e0714903-bc37-4bdc-b967-babbaafd191f

**Comment by MARQAS** [comment]
@ahmedkaludi chat not available

**Comment by MARQAS** [comment]
Styling is pending.

**Comment by MARQAS** [comment]
@ahmedkaludi, We have added the infinite scroll option only for Posts and Homepage.

**Comment by ahmedkaludi** [comment]
Styling is pending, I'll work with @RajuJeelaga

**Comment by RajuJeelaga** [comment]
In the category Module, when loop pagination is enable starting and Middle pages are coming fine, when i switch to last pages, warning error is showing, Please see the screenshot.
https://monosnap.com/file/OTRsOfz3wP9XiBzGEjOhtK5LPidtVf

@MARQAS

**Comment by MARQAS** [comment]
The warnings are due to #2659, otherwise nothing wrong here

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
escaping missing  and the translation is missing in multiple areas

example: 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c0a0e492e0fe37339759646720bef487432753b5#diff-cb16861af9ff34ccd298041891008f49R459 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4bc995ff5d2cc6aa7cae8d5fbaf02ed33c6859ac#diff-cb16861af9ff34ccd298041891008f49R419

**Comment by MohammedKaludi** [comment]
Make sure we remove unwanted code while merging 

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/7afb769edf541d9caa804899bddcc2ff8cc69feb/pagebuilder/modules/contents-module.php#L458

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/7afb769edf541d9caa804899bddcc2ff8cc69feb/pagebuilder/modules/contents-module.php#L505

**Comment by RajuJeelaga** [comment]
- [ ] Instead of Pagination Number, Text is also appearing.
Please see the screenshot
https://monosnap.com/file/DOgisSobG6d3LZp9hxe8zZm3gYYr6B

**Comment by MARQAS** [comment]
@RajuJeelaga, this error is coming from your last commit, check: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7afb769edf541d9caa804899bddcc2ff8cc69feb#diff-cb16861af9ff34ccd298041891008f49R498

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
