### ISSUE TITLE
Improve .pot file for translations

### ISSUE THREAD

**Issue by crissoca** [ahmedkaludi/accelerated-mobile-pages#1678]
It seems the language translation still needs some work on the .pot file, this seems to be outdated or something else is happening.

See this example:

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/5ac0d2c2b2d126e054c8114a3cf8671f6501e7cb/templates/design-manager/design-2/elements/meta-info.php#L32

Here it should be "Categories" instead when translated it doesn't work because the text reads "accelerated-mobile-pages"

**Comment by MohammedKaludi** [comment]
:+1:
