### ISSUE TITLE
Performance issue because of Featured Image from Custom Fields option in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1679]
attachment_url_to_postid 
ampforwp_cf_featured_image_src

Featured Image from Custom Fields option takes much time to load the featured image from the custom field.

Ref:  https://secure.helpscout.net/conversation/514655793/20978?folderId=1060551

**Comment by MARQAS** [comment]
We have tested it and it's not the cause.
@beingsmart3 and @ahmedkaludi can you point me in the right direction on how to recreate this issue?

**Comment by ahmedkaludi** [comment]
@MARQAS Use this method: https://monosnap.com/image/9iW27jbhn2pUcMMjVw9cpPRue19jvc

and then use https://wordpress.org/plugins/query-monitor/

Try to compare 'Custom Feild Featured Image' on vs off. You will understand it.

**Comment by MARQAS** [comment]
Contacted the user, waiting for his reply.

**Comment by githubjabbar** [comment]
Huge resource usage because of this on an AMP WooCommerce Pro user's site (Sandeep). Almost 4s of loading time because of it.

**Comment by MohammedKaludi** [comment]
Updated the code https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0d811764de9bd0a277b75a590a885d0d73613f13

**Comment by MohammedKaludi** [comment]
Updated some code https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c146152841ec32f39dfa5c3e971d0e122c9507cc
