### ISSUE TITLE
No instagram

### ISSUE THREAD

**Issue by MisterRaj** [ahmedkaludi/accelerated-mobile-pages#1681]
There is no option for instagram icon on the social menus.

**Comment by ahmedkaludi** [comment]
@MisterRaj May I know which Design are you using?

**Comment by MisterRaj** [comment]
Are you asking for version, AMPforWP Options 0.9.73

**Comment by ahmedkaludi** [comment]
What I am asking is, which theme are you using for AMP.

In Design section of options panel, which design (or theme) are you using in AMP?

**Comment by MisterRaj** [comment]
Design one

**Comment by MisterRaj** [comment]
![design_one](https://user-images.githubusercontent.com/4678755/35731701-bc52c71e-083c-11e8-8548-95233806254c.png)

**Comment by Sejiro-Hiko** [comment]
@MisterRaj are you asking for the sharing option for Instagram?

**Comment by ahmedkaludi** [comment]
We have waited for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
