### ISSUE TITLE
amphtml is not working when homepage in reading and shop page in WooCommerce is same 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1682]
amphtml is not working when homepage in reading settings and shop page in WooCommerce is same

See this screenshots:
http://take.ms/DOtjm
http://take.ms/3IaEp

Ref: https://secure.helpscout.net/conversation/514884643/21009?folderId=1680011

**Comment by MohammedKaludi** [comment]
Use our extension [AMP WooCommerce Pro](https://ampforwp.com/woocommerce/).

:+1:
