### ISSUE TITLE
ScoopVersion: 1.4 By boostdevelopers

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1683]
ScoopVersion: 1.4 By boostdevelopers theme displaying the error only in the category.

See this screenshot:  http://take.ms/SGcuk

Ref:  https://secure.helpscout.net/conversation/515714362/21079?folderId=1060551

And we asked them to send the theme.

**Comment by MohammedKaludi** [comment]
`if ( function_exists( 'ampforwp_is_amp_endpoint' ) && ampforwp_is_amp_endpoint() ){` Added directly into the features.php will always return false.

so need to add it through any hook that is rendering in amp mode

You can test below code 
**with pre_amp_render_post hook**
`add_action('pre_amp_render_post', function(){
if ( function_exists( 'ampforwp_is_amp_endpoint' ) && ampforwp_is_amp_endpoint() ){
	add_action('pre_get_posts', function(){
		echo "string ------------------";
	});
}
});`

**directly**
`if ( function_exists( 'ampforwp_is_amp_endpoint' ) && ampforwp_is_amp_endpoint() ){
	add_action('pre_get_posts', function(){
		echo "string ------------------";
	});
};`

**Comment by Sejiro-Hiko** [comment]
7ae6113

**Comment by MohammedKaludi** [comment]
:+1:
