### ISSUE TITLE
Featured images distortion in related posts

### ISSUE THREAD

**Issue by marcogian** [ahmedkaludi/accelerated-mobile-pages#1684]
Single post --> Related Posts.
Images has their weight/height ratio distorted (_they are all featured images_).
You can see examples in these websites:
https://www.architetti.com/premio-medaglia-oro-architettura-italiana-2018-bando.html/amp
https://www.infobetting.com/blog/nazionale-femminile-italia/amp/

They both use Newspaper Theme by tagdiv.

Same issue reported here, but it didn't get fixed.
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1008

**Comment by ahmedkaludi** [comment]
@marcogian That's strange, As of now, both of those URL's have design 2.

Can you contact us directly via https://ampforwp.com/support/ with login info of the site, I will make sure our developers fix it immediatly for you.

**Comment by marcogian** [comment]
Done! let me know!

**Comment by zabi09** [comment]
@marcogian  Should we try to implement the Swift theme regeneration thumbnail method in design 2?

**Comment by marcogian** [comment]
@zabi09 no sorry, we can't add any plugin or make any "big changes" on that website.

I have found the solution changing this CSS class in this way:
`.i-amphtml-fill-content {
    display: block;
    height: auto;
    max-height: none;
    max-width: 100%;
    min-height: 0;
    min-width: 100%;
    width: 0;
    margin: auto;
}`

As long as I can see, the problem is in the CSS and not in the thumbnail image size.
Can you add the above code to the source code of the plugin?

**Comment by zabi09** [comment]
@marcogian I am sorry my above message about the thumbnail method ( implement the Swift theme regeneration thumbnail method in design 2? ) was to the lead developer @ahmedkaludi

**Comment by ahmedkaludi** [comment]
@marcogian we have created a new thumbnail method, which we can use in Design 2, I think if we apply that, then that would be a good solution for you.

**Comment by marcogian** [comment]
Ok!
Will the new thumbnail method be in the next release? Before Febraury 17?

**Comment by zabi09** [comment]
Our schedule for W7 is of February 17 and currently, we are working on other milestones and but if you want it immediately then let us know.

**Comment by marcogian** [comment]
Try sending us the fix for the latest release; if it's easy we will
    use it right now otherwise we will wait February 17. :)
    
    Thanks,
    Marco
    
    Il 07/02/2018 14:30, zabi09 ha scritto:
    
    
      Our schedule for W7 is of February 17 and currently, we are
        working on other milestones and but if you want it immediately
        then let us know.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ahmedkaludi/accelerated-mobile-pages","title":"ahmedkaludi/accelerated-mobile-pages","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ahmedkaludi/accelerated-mobile-pages"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zabi09 in #1684: Our schedule for W7 is of February 17 and currently, we are working on other milestones and but if you want it immediately then let us know. "}],"action":{"name":"View Issue","url":"https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1684#issuecomment-363769061"}}}</s
 cript>
</body>
</html>
</html></blockquote>
    <br>
  </body>
</html>

**Comment by marcogian** [comment]
Hello,
this issue has not been solved in latest release :-(
Example:
https://www.infobetting.com/blog/chelsea-barcellona-formazioni-2018/amp/

Let me know!

**Comment by MARQAS** [comment]
Hi @marcogian 

I believe your issue will be resolved with #1709 and I have already some changes in that.

Can you please test W7 branch which is the current beta version and check if your issue has been resolved or not.
If it's not resolved then we can check other methods on how we can resolve this issue of yours.

**Comment by marcogian** [comment]
You told me it would have been solved before 17 february :-)
How can i install the w7 branch?
I strongly prefer to wait an official release.

**Comment by MARQAS** [comment]
@marcogian Do you have staging site? We can test it there if you want.

**Comment by ahmedkaludi** [comment]
@marcogian is saying right. The Related Posts on the Design 2 isn't on the new method: see: http://take.ms/19NBn

It's the same on D2 and D1, also check for other places

**Comment by MohammedKaludi** [comment]
Now working nicely, checked. :+1:
