### ISSUE TITLE
Encoding properly not working in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1685]
Encoding properly not working in AMP, I personally tested and the issue is coming only in swift theme and design 3.

Ref:  https://secure.helpscout.net/conversation/515714430/21080?folderId=1060551

See this screenshot:  http://take.ms/nqwB3

See this screenshot:  http://take.ms/sEeKD

**Comment by Sejiro-Hiko** [comment]
The issue is related to the font-family of Design 3 as it uses 'PT Serif' if we changed it then it works perfectly.`.amp-wp-article-content {
    font-family: 'PT Serif',serif;
}`

**Comment by ahmedkaludi** [comment]
It's working on my tests and even on the user's website. Seems like it was fixed.
