### ISSUE TITLE
newspaper theme tagdiv and your plugin menu header problem

### ISSUE THREAD

**Issue by geniovi** [ahmedkaludi/accelerated-mobile-pages#1686]
hello,
I installed your recent update and receive error with amp validations. 
Problem is in a header menu of **newspaper theme of tagdiv.**
the error refers on a menu "ul" and "li"
this is a error:
Attribute "current-menu-parent" it may not appear in the tag "li".
Attribute "current-post-ancestor" it may not appear in the tag "li".
Attribute "menu-item-27612" it may not appear in the tag "li".

![errore_amp](https://user-images.githubusercontent.com/5128161/35767523-d2da1184-08ed-11e8-972e-0053a395997b.png)

**Comment by Sejiro-Hiko** [comment]
@geniovi are still facing this issue? and can you brief us on which version you are facing this issue?

**Comment by Sejiro-Hiko** [comment]
tested on my end, working fine..

**Comment by ahmedkaludi** [comment]
Waited long for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
