### ISSUE TITLE
Custom post type is appearing two types

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1688]
When we have the custom post extension then it is appearing two times along with the core plugin settings.

See this screenshot: http://take.ms/BoAX5

Ref: https://secure.helpscout.net/conversation/482533337/19186?folderId=1060551
Ref: LocalHost

**Comment by ahmedkaludi** [comment]
It's perfect! ....
But the correct place of this option should be under the "AMP Support" (under general settings), instead of a separate menu.

**Comment by ahmedkaludi** [comment]
Just remove the Switch and have it normal select area

**Comment by ahmedkaludi** [comment]
- [ ] It should say a better name, like "Custom Post Types" 

- [ ] Use the correct text domain http://take.ms/naiYK

**Comment by ahmedkaludi** [comment]
- [ ] http://take.ms/2ftHp
