### ISSUE TITLE
Frontpage The content 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#169]
If we setup the Frontpage from the options, then it's The content doesn't have AMP the_content. Try to add an image to the page and set it as frontpage, you'll see it.

**Comment by ahmedkaludi** [comment]
Another problem with the Frontpage option:

Have you discovered the problem? I have processed the latest plugin update (0.8.5.3) hoping the canonical fix would solve it, but I still have the problem.

I’ve now installed your plugin on a second site and the same problem exists.

(1) The blog thread meta data incorrectly appears in the browser of the Home page: https://snag.gy/1pFjaV.jpg

(2) The home page content incorrectly appears on the blog page:
https://snag.gy/aPXuct.jpg

This is happening on two different sites. Surely I can’t be the only one with this problem?

Please advise.

REPORTED: https://wordpress.org/support/topic/incorrect-meta-data-on-amp-pages/

**Comment by alexchuin** [comment]
Same problem here.
I have a static front page.
Metadata are always the latest article...

**Comment by ahmedkaludi** [comment]
Another Report: https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/issues/153

**Comment by MohammedKaludi** [comment]
FrontPage issue fixed 
https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/f06b51ee5ac6ee366f7f3460401388fae9c77b81

**Comment by jhit** [comment]
Uploaded the changed file to my 0.8.8 version plugin but startpage is still broken.
Anybody else having this issue?

**Comment by MohammedKaludi** [comment]
@jhit we have fixed this issue in 0.9.3 [reference link](https://ampforwp.com/custom-amp-content-editor/) Please reopen the ticket if the issue persists.
