### ISSUE TITLE
Improve Onesignal description

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1690]
Add this in the description that, For integrating the one signal push notification the website URL must be HTTPS
OneSignal still supports AMP web push for HTTP sites that use a subdomain of OneSignal (e.g. subdomain.os.tc), but when viewing the HTTP site as an AMP page, the site URL must be HTTPS.

When users view an AMP page on an actual mobile device, they are often directed by Google to a URL like "https://www.google.com/amp/www.site.com". This means that HTTP sites that don't ordinarily support HTTPS will actually support HTTPS thanks to Google, if the AMP page is cached by Google and navigated from Google's search results.

Ref: https://secure.helpscout.net/conversation/509924864/20570?folderId=1680011

**Comment by MARQAS** [comment]
https://ampforwp.com/tutorials/article/one-signal-in-amp/

**Comment by ahmedkaludi** [comment]
Reasons:
- [ ] the description needs to have "HTTPS (SSL) is required" in the options.
