### ISSUE TITLE
Remove layout tables for accessibility

### ISSUE THREAD

**Issue by steverep** [ahmedkaludi/accelerated-mobile-pages#1692]
*I just installed your plugin today, and I am forced to defer using it or deactivate it altogether because of inaccessibility when using assistive technology, such as a screen reader.  I'll try to create separate issues for the biggest offenses as I see them.*

Using tables for layout almost always comes with accessibility issues, and the admin area of this plugin is no different.  Just do a web search to find out why or dive into the Web Content Accessibility Guidelines (WCAG); I don't want to regurgitate all that information here.

Short term fix is to employ the `role="presentation` ARIA markup on non-data tables.  Longer term is to please, oh please, stop using tables for layout.  CSS is way too powerful to still be using such an archaic technique.  And, ironically, layout tables are a sure fire way to create mobile responsiveness issues!

**Comment by Sejiro-Hiko** [comment]
@steverep I've tested the accessible tables in AMP and they are working as it should so If you could give us more information on your use case so we can discuss more on this issue and works towards the solution or we'll be closing this ticket.

**Comment by ahmedkaludi** [comment]
Waited long for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
