### ISSUE TITLE
Error on using noindex on categories / tags

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1693]
First of all categories and tags should be treated separately in terms of whether they show or can be set as noindex. You may well want to index tags but not categories or visa versa.

However the real problem is normally you set (noindex, noarchive) but if you set the option for categories in the admin panel it actually does (noindex,nofollow).

The nofollow is not recommended SEOwise if you are using it on internal links within your site. It looks like page rank sculpting.

For those who wish to correct this immediately, you can edit templates/features.php line 2471

$message_to_robots = '<meta name="robots" content="noindex,noarchive"/>';

REF: https://wordpress.org/support/topic/error-on-using-noindex-on-categories-tags/

**Comment by ajeetku** [comment]
Remove no index, options are already present,
![accelerated mobile pages options amp wordpress](https://user-images.githubusercontent.com/19512210/36713641-addc58e0-1bb4-11e8-87e8-52d44c50409b.png)

**Comment by MohammedKaludi** [comment]
:+1:
