### ISSUE TITLE
Need Apester Support 

### ISSUE THREAD

**Issue by mayanksharma9033** [ahmedkaludi/accelerated-mobile-pages#1694]
When the user is using the code in the content.it will be stripped off by TinyMCE editor.

Ticket Reference :- https://secure.helpscout.net/conversation/518756247/21331?folderId=1060551

**Comment by MARQAS** [comment]
The user has resolved this issue, do we have to add this or should we close this ticket?

**Comment by MohammedKaludi** [comment]
Currently no need for this. So closing the ticket.
