### ISSUE TITLE
Squirrly SEO 2018 (Steve) is Outputting the Javascript code

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1696]
Squirrly SEO 2018 (Steve) is Outputting the Javascript code.

Ref:  https://secure.helpscout.net/conversation/518100998/21292?folderId=1060551

**Comment by MARQAS** [comment]
No issues at my end and on the user end.

**Comment by ahmedkaludi** [comment]
@marqas If it's not reoccuring on your end, then let me know. I will help you re-create the issue.

**Comment by Sejiro-Hiko** [comment]
unable to recreate the issue, keeping it waiting till figure out it.

**Comment by ahmedkaludi** [comment]
No, let's not sit on this @Sejiro-Hiko

**Comment by MohammedKaludi** [comment]
:+1:
