### ISSUE TITLE
Problem cursor on mobile input search bar

### ISSUE THREAD

**Issue by CarmineMolisso97** [ahmedkaludi/accelerated-mobile-pages#1698]
I noticed that when your try to use the search module by mobile browser, and you start to write, the cursor of the input text isn't in the correct position.
Thanks

**Comment by Sejiro-Hiko** [comment]
@CarmineMolisso97 can you please brief us on which "mobile browser" you are seeing this issue?

**Comment by Zabi09** [comment]
@CarmineMolisso97 Will you please send us the screenshot of your issue, So that we will check once and let you know

**Comment by ahmedkaludi** [comment]
It's fixed in iOS 11.3.

twbs/bootstrap#24835 (comment)
jgthms/bulma#1774 (comment)
