### ISSUE TITLE
Error while sharing the image in Pinterest

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1699]
Pinterest amp social share button does not work. Shows error; “Parameter ‘image_url’ with the value ‘https:’.$image.’ ‘ is not a valid URL format.”

https://wordpress.org/support/topic/pinterest-amp-social-share-button-does-not-work/

Also, if possible, let's enable the rich pin support as well.

REF: https://wordpress.org/support/topic/pinterest-amp-social-share-button-does-not-work/

**Comment by ahmedkaludi** [comment]
wow!

**Comment by Sejiro-Hiko** [comment]
👍
