### ISSUE TITLE
json-api plugin error

### ISSUE THREAD

**Issue by prosman** [ahmedkaludi/Accelerated-Mobile-Pages#17]
I used with json-api plugin but give an error

Warning: readdir() expects parameter 1 to be resource, boolean given in /home/xxx/public_html/wp-content/plugins/json-api/singletons/api.php on line 291

**Comment by ahmedkaludi** [comment]
Hey Osman,

I'll check it out of the weekend.

P.S. I really appreciate that you are helping us improve the plugin.


Regards,
Ahmed

**Comment by ahmedkaludi** [comment]
This was fixed after 0.8 update.
