### ISSUE TITLE
Home loop modifier 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1701]
In advance settings, there should be an option of including and excluding the homepage loop based on specific categories.

Ref: https://secure.helpscout.net/conversation/519928275/21427?folderId=1680011

**Comment by Zabi09** [comment]
And also create the custom post type option on the homepage loop

Ref: https://secure.helpscout.net/conversation/509983077/20585?folderId=1680011

**Comment by ahmedkaludi** [comment]
- [ ] These two will be in a section called "Homepage Loop Controls"

- [ ] Remove descriptions from options

- [ ] first option will be called "Post Type in Loop" second will be "Exclude Categories"

**Comment by ahmedkaludi** [comment]
- [ ] Change the heading to "Loop Display Controls"

- [ ] Except those two options, all the other options will be in the General Settings, 

- [ ] General will be first, "Loop Display Controls" will be second.
