### ISSUE TITLE
Fully Formed Compatibility with WPML

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1703]
- [ ] It is not possible to "Select Page as Front Page" in the other languages - the option gets empty after save!! ( https://docs.reduxframework.com/core/advanced/wpml-integration/ )

- [ ] The homepage shows a weird stream of posts if I do not set the option "Custom Front Page". Would be better if the homepage is handled like other pages.

**Comment by beingsmart3** [comment]
One more issue regarding WPML Multilingual CMS Plugin.

Ref:  https://secure.helpscout.net/conversation/547222209/23618?folderId=1914712

**Comment by ahmedkaludi** [comment]
This feature has been added in https://ampforwp.com/wpml-for-amp/
