### ISSUE TITLE
CSS is not rendering in the options panel ( Edge Case )

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1704]
CSS is not rendering in the options panel

screenshots: 
http://take.ms/sHOOjd
http://take.ms/HomNl

Ref: https://secure.helpscout.net/conversation/502976049/20237?folderId=1680011

**Comment by mayanksharma9033** [comment]
One Customer is waiting for this

**Comment by ahmedkaludi** [comment]
we have tackled this types of issues in the recent update
