### ISSUE TITLE
SEO Section Improvements

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1705]
Create a new section called compatibility it will have two plugins 

- [x] All in one SEO

- [x] YOAST SEO

Ref: https://secure.helpscout.net/conversation/519689513/21391?folderId=1060551

**Comment by ahmedkaludi** [comment]
- [ ] 1. What happens if I already set previously? will those be turned off? 

- [ ] 2. I just synced it, It shows me this; http://take.ms/D3wBh - What happens in this use case?

**Comment by MARQAS** [comment]
1: If Yoast settings are previously set then it will take it directly.
2: In that case, it will take the default values from our settings.

**Comment by ahmedkaludi** [comment]
- [ ] it should be "All" http://take.ms/8Ej78
