### ISSUE TITLE
Implement Swift Thumbnail Regeneration in all the designs

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1709]
Implement Swift Thumbnail Regeneration in all the designs so that they can control the output.

REF: https://wordpress.org/support/topic/version-0-9-74-1-using-big-image-on-homepage/#post-9946961

**Comment by ahmedkaludi** [comment]
#1684 related posts implementation is pending.

**Comment by MohammedKaludi** [comment]
:+1:
