### ISSUE TITLE
Provide advertisement or sponsored label on ads

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1710]
Please update or add one new option in advertisement tab. Give check box advertisement or sponsored label on above ads which is compulsory as per Google Ads TOC

REF: https://wordpress.org/support/topic/will-you-provide-advertisement-or-sponsored-label-on-ads/

**Comment by MohammedKaludi** [comment]
Two ads does not show labels http://take.ms/XzdXR

**Comment by MohammedKaludi** [comment]
Also Styling is not showing properly.

**Comment by MohammedKaludi** [comment]
Still not looking good. Need spacing around all the ads.
