### ISSUE TITLE
Featured Images are getting Stretched in Archives [Category & Tags]

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1714]
Featured Images are getting Stretched in Archives [Category & Tags]

Ref:  https://secure.helpscout.net/conversation/520436310/21463?folderId=1060551

Screenshot:  http://take.ms/QtcIm

**Comment by EstianH** [comment]
In AMPforWP theme design-3 the archive.php file renders the image out as:
`$thumb_url = ampforwp_get_post_thumbnail();
if($thumb_url){ ?>
<div class="home-post_image">
<a href="<?php echo esc_url( $ampforwp_amp_post_url ); ?>">
<amp-img layout="responsive" src=<?php echo esc_url($thumb_url); ?> <?php ampforwp_thumbnail_alt(); ?> width=450 height=270></amp-img>
</a></div><?php } `

It simply defaults all images to 450 * 270, and is the cause of the stretching for images with different dimensions.

It should be changed to the following:
`$thumb_url = ampforwp_get_post_thumbnail();
$thumb_width = ampforwp_get_post_thumbnail('width');
$thumb_height = ampforwp_get_post_thumbnail('height');
if($thumb_url){ ?>
<div class="home-post_image">
<a href="<?php echo esc_url( $ampforwp_amp_post_url ); ?>">
<amp-img layout="responsive" src=<?php echo esc_url($thumb_url); ?> <?php ampforwp_thumbnail_alt(); ?> width=<?php echo $thumb_width; ?> height=<?php echo $thumb_height; ?>></amp-img>
</a></div><?php } `

**Comment by MohammedKaludi** [comment]
:+1:
