### ISSUE TITLE
Post Pagination Should have two options like "Number of pages" and "Previous & Next"

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1716]
Post Pagination Should have two options like,

- [x]  Number of pages
- [x] < Previous and Next >

See this screenshot:  http://take.ms/P9FS5
Ref:  https://secure.helpscout.net/conversation/519085687/21353?folderId=1060551

**Comment by ahmedkaludi** [comment]
- [ ] Remove that description: http://take.ms/qpLM3
