### ISSUE TITLE
Tags label is not working properly when RTL Support on.

### ISSUE THREAD

**Issue by mayanksharma9033** [ahmedkaludi/accelerated-mobile-pages#1719]
One user is getting problem regarding the tags he just has inserted the Arabic text in the input via Translational Panel Setting but not reflecting which he wants on the right side.

Screenshots:-https://imgur.com/4VMzqmA

Reference Ticket:- https://secure.helpscout.net/conversation/517816755/21273?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:
