### ISSUE TITLE
To implement JobPosting Schema Rich Snippet in AMP version

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1721]
To add structured data, for Job posting schema in AMP version.

Ref:https://secure.helpscout.net/conversation/522326549/21581?folderId=1060551

**Comment by ahmedkaludi** [comment]
This will be added in [Structured Data for WordPress](https://ampforwp.com/structured-data-for-wp/) plugin
