### ISSUE TITLE
Social section improvements

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1722]
There are two options for social.
1 - social sharing icons
2 - social profile icons
( Already there in the design 3)

And now both must have the position feature like in the footer, below the title etc.

Ref: https://secure.helpscout.net/conversation/521010125/21490/?folderId=1060551

**Comment by ahmedkaludi** [comment]
Review:

- [ ] The label should be "Single Sidebar (left side)" http://take.ms/6Iib5

- [ ] This feature needs to be implemented in all the designs.

- [ ] Although the positions are in the correct place but design wise, it's not ready to push. (Frontend)

**Comment by MARQAS** [comment]
Other designs can use this: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2051

**Comment by Zabi09** [comment]
This should be in the capital - http://take.ms/N7U5B

**Comment by ahmedkaludi** [comment]
Reviewed.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
