### ISSUE TITLE
Need to create a tutorial of  How to Enter your Audience Network Placement ID of advertisement in the Instant Article

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1723]
Need to create a tutorial of  How to Enter your Audience Network Placement ID of advertisement in the Instant Article

Ref:  https://secure.helpscout.net/conversation/521494081/21523?folderId=1060556

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
