### ISSUE TITLE
How to display page template using custom post type  and ACF data?

### ISSUE THREAD

**Issue by hemantdewy** [ahmedkaludi/accelerated-mobile-pages#1727]
Hello,
Recently I installed this plugin, but I am unable to display page with having custom post type and ACF data, using page template. I have purchased Custom post type extension but still not able to display posts from that page template.

**Comment by ahmedkaludi** [comment]
@hemantdewy You can use the AMP Theme framework to do that or you can use AMP ACF plugin to do that.
