### ISSUE TITLE
Feature Request - clickable links on AMP site have /amp/ added

### ISSUE THREAD

**Issue by bondimedical3** [ahmedkaludi/accelerated-mobile-pages#1732]
I have an image on my webpage https://seoace.com.au/seo-packages/amp/ which links to our contact us page. However, the link goes to the non AMP version. Please add a feature in the plugin which adds /amp/ to the URL. I have another website which has many text links to other pages in my website so this will become a big problem.

**Comment by ahmedkaludi** [comment]
We have a feature called Internal Links feature in #1538
