### ISSUE TITLE
Swift Pending List 

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#1733]
## After the Release 0.9.80 Update, Bugs List..

- [x] Add the condition for the post thumbnail  http://take.ms/Kp0vp 

- [x] Global color scheme  default color is not applying at 1st Installation, and If reset  that, default color is applying. http://take.ms/fZ0zr

- [x] check the search icon, color is connected to element color or not, because  http://take.ms/FpBmP

- [x] search css is not loading http://take.ms/dC8l5 [Add the condition along with home and archive in style.css].

- [x] Footer margin problem in the pagebuilder  http://take.ms/6bm4y and swift http://take.ms/xqTZy [check the condition in the style.css]

- [x] ADD the condition for the featured images http://take.ms/pAbau

- [x] Check for extra div in single after < / html >

**Comment by MohammedKaludi** [comment]
Some minor issues popped up in the testing, separate ticket created for that.
:+1:
