### ISSUE TITLE
amphtml Conflict with Instant Article for Facebook

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1737]
Getting Conflict with Instant Article for Facebook because of its amphtml output 2 times on the site.

Ref:  https://secure.helpscout.net/conversation/523927326/21686?folderId=1060551

**Comment by ahmedkaludi** [comment]
@MARQAS How did you tested this?

**Comment by MARQAS** [comment]
By activating the instant articles plugin which is adding ?amp_markup=1. 
Before: Our amphtml was loading below its amphtml.
After: Our amphtml is loading above its amphtml.
