### ISSUE TITLE
Function is removing all the value and broke whole shortcode in Visual Composer

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1738]
There is issue when working with visual composer.

e.g. My content is as follows

[vc_row type="vc_default" bg_type="bg_color" bg_override="full" rowtype="fullw" padding="20px 0" css=".vc_custom_1478848968464{padding-top: 20px !important;padding-right: 0px !important;padding-bottom: 20px !important;padding-left: 0px !important;}" bg_color_value="#ebebeb"][vc_column][vc_empty_space height="12px"][vc_column_text css_animation="zoomIn"]
<h3 style="text-align: center;"><span style="color: #2a4a8f;">Certified translation of marriage certificates</span></h3>
[/vc_column_text][/vc_column][/vc_row]

But on plugins/accelerated-mobile-pages/templates/features.php there is one function "ampforwp_the_content_filter" which remove bg_colour_value and broke whole shortcode and it generate only

[/vc_column]

So This code has to be revise for line 

$content = preg_replace('/value=[^>]*/', '', $content);

so that it will generate proper output.

Ref: https://secure.helpscout.net/conversation/523836924/21679?folderId=1680011

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by mrunwal** [comment]
Thank you
