### ISSUE TITLE
Custom Front Page is noindex in yoast while it's not in AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1739]
Custom Front Page is noindex in yoast while it's not in AMP

Hi using Yoast SEO – whatever i set on the custom front page is not applied to the site. My main page is

<meta name=”robots” content=”noindex,follow”/>

and not indexed.

Please help. Page is: https://www.hagel-it.de/amp

REF: https://wordpress.org/support/topic/custom-front-page-is-noindex/

**Comment by MARQAS** [comment]
Working as expected, contacted the user and waiting for his reply

**Comment by ahmedkaludi** [comment]
Ticket closed. Not enough data.
