### ISSUE TITLE
Error with Vue

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1745]
https://screenshots.firefox.com/OaiGBvrUOp8VUrRS/null

https://wordpress.org/support/topic/connection-not-establish-error-in-articles-page-admin/

**Comment by azerphoenix** [comment]
Hello!
The first screenshot is mine)
May be some of the plugins conflict with AMP?
Below is the list of plugins installed on my website:
https://screenshots.firefox.com/EpowWtAIw0CFJp0q/md7.info
I use Jarida theme on my website and also use SSL. In error_log I don't see any errors about AMP.

There is conflict between Yoast SEO & AMP plugin. When I turn off the Yoast there is no any errors.

**Comment by ahmedkaludi** [comment]
@azerphoenix can you please send us the login credentials on team@magazine3.com ? I will personally fix this immediately!

**Comment by MohammedKaludi** [comment]
:+1:
