### ISSUE TITLE
Strange behavior with the latest version of AMP.

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1747]
Strange behavior with the latest version of AMP for those users who are using News Paper theme it certain loads the double stylesheet with this users gets validation error of 50kb limit cross.

Ref:  https://secure.helpscout.net/conversation/525296670/21810/

**Comment by MARQAS** [comment]
As we have improved the method of loading the styling we have to change the code in AMP NewsPaper theme as well.
https://github.com/ahmedkaludi/AMP-Theme/issues/68

**Comment by ahmedkaludi** [comment]
@pegazee Move this ticket to Review / Q&A when the update for Newspaper is released

**Comment by pegazee** [comment]
NewsPaper AMP theme released
