### ISSUE TITLE
For some reason, the <main> tag is not showing up in Design 2 which is breaking the style

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1751]
For some reason, the <main> tag is not showing up in Design 2 which is breaking the style
http://take.ms/iaSQ9

I have seen two people report this so far.

**Comment by MARQAS** [comment]
It's working properly.
https://www.foodstyling.be/conserve-de-tomates-cerise/amp/

**Comment by ahmedkaludi** [comment]
@MARQAS 
It's not, if you see the design of Design 2, we have a specific way of displaying post. That one, doesn't not have any <main> tag and the styling is not applying as well. Check the body tag, its empty and viewport repeats twice. 

Find out who that person is, contact him and understand what kind of page it is, we need to find this one and fix it

**Comment by MARQAS** [comment]
Viewport thing is fine now. 
The style was getting broken due to related posts plugin which is adding related posts in AMP as well.

**Comment by MARQAS** [comment]
@ahmedkaludi what should be done about that plugin? 
I have disabled the plugin on user site using plugin manager

**Comment by MARQAS** [comment]
User:
Since the last update every thing works fine again,
Thakns
ref: https://secure.helpscout.net/conversation/525708248/21864?folderId=1060556
