### ISSUE TITLE
Show What's new 'change log' section 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1753]
http://take.ms/4nfT7

**Comment by santosh8793** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c4e3048f2ce60814bc1bd5ecf3ccf2a955829f6b

**Comment by MohammedKaludi** [comment]
@ahmedkaludi  
http://take.ms/HE49Q
and need your feedback.

**Comment by ahmedkaludi** [comment]
- [ ] Align the welcome page properly. http://take.ms/nFGZT5

- [ ] Changelog section: we need to align the text to the left, and a separator between the two versions.

**Comment by Omair52** [comment]
Pushed in 0.9.97.16

**Comment by pegazee** [comment]
Getting blank space at changelog section: https://take.ms/lX12y

**Comment by pegazee** [comment]
Pushed in 0.9.97.44
