### ISSUE TITLE
New Google Search Console Error

### ISSUE THREAD

**Issue by SaiGonSeamus** [ahmedkaludi/accelerated-mobile-pages#1756]
This has started appearing since 0.9.82.1
```
The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?
First detected: Feb 18, 2018
Status: 
Error
```

**Comment by MARQAS** [comment]
@SaiGonSeamus can you share the URL where you are having this issue?

**Comment by SaiGonSeamus** [comment]
@MARQAS Hi, It's all pages now. Here's an example.https://vnvpn.club/vpn-vietnam/vpn-countries/amp/ I had to deactivate it. I'll turn it back on now.

**Comment by MARQAS** [comment]
How are you adding that product list in the bottom?

**Comment by SaiGonSeamus** [comment]
Swift footer widget
