### ISSUE TITLE
debug errors

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1757]
- [] http://take.ms/cfKNO
- [] in footer as well

**Comment by MARQAS** [comment]
@ahmedkaludi I am unable to recreate this issue.

Can you point me in the right direction?

**Comment by MohammedKaludi** [comment]
@ahmedkaludi... Waiting from your side.

**Comment by ahmedkaludi** [comment]
I have tested it again and there are no issues as of now.
