### ISSUE TITLE
show default gravatar for comments

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1758]

**Comment by pegazee** [comment]
show a default gravatar for comments when don't have their gravatar.
like this in AMP, Screenshot > https://www.screencast.com/t/GZ5eXGq0Xn73

**Comment by ahmedkaludi** [comment]
- [ ] The ID of the comment should not be displayed http://take.ms/qYRmJ

**Comment by MohammedKaludi** [comment]
:+1:
