### ISSUE TITLE
Wordpress comment form cannot load correctly

### ISSUE THREAD

**Issue by anwar1hidayat** [ahmedkaludi/accelerated-mobile-pages#1759]
Wordpress comment form cannot load correctly if install Swift theme and activated load AMP same on WP theme. Please help me, check my website: https://www.statistikian.com.

**Comment by MARQAS** [comment]
@anwar1hidayat are you talking about the comments or comments form where you can comment and give replies to comments?
Comments are working properly on your site. 
Can you give us more details if you are still facing this issue?

**Comment by anwar1hidayat** [comment]
give replies to comments

**Comment by MARQAS** [comment]
@anwar1hidayat are you using amp-comments extension?

**Comment by MohammedKaludi** [comment]
@anwar1hidayat We already have the comments form and reply feature in the AMP Comments Extension  https://ampforwp.com/amp-comments/
