### ISSUE TITLE
Random posts on the homepage loop

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1760]
Need an option of showing random posts on the homepage, not all posts.

Ref: https://secure.helpscout.net/conversation/525989957/21891?folderId=1680011

**Comment by MohammedKaludi** [comment]
Will create a filter to query args, so users can modify loop's query arguments.

**Comment by ajeetku** [comment]
This use-case does not align with our goals at the moment. We may consider this in the future.
