### ISSUE TITLE
AMP Options panel Not Working After Update (0.9.82.1) version

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1761]
Cannot see anything in the amp option after the latest update.

Ref: https://secure.helpscout.net/conversation/525002135/21778?folderId=1680011

DESC: After Update to and enable the takeover/wp conversion option, AMP option panel is not shows any options.

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/526672239/21957?folderId=1060551

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/527720560/22043/

**Comment by azlie1992** [comment]
Hai . Sory late

**Comment by azlie1992** [comment]
I have install and uninstall back still same sir. How?

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/527233123/22008?folderId=1060551

**Comment by ahmedkaludi** [comment]
@ajeetku What does https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/369335d95c3136a1c7f44d5de1c95326d148c40b has to do with the original issue?

How can I reproduce the issue on my end?

**Comment by ajeetku** [comment]
@ahmedkaludi 
 To Reproduce process: After 80 versions, 
1. Enable the Minify option
2. Enable takeover/wp convert option
When we do this 2 things, AMP Option panel not show any fields.
Reason: checking of ampforwp_end_points is gives true, when we enable takeover/wp convert options

**Comment by MohammedKaludi** [comment]
:+1:
