### ISSUE TITLE
 WordPress Comments appears with option disabled

### ISSUE THREAD

**Issue by adrianleira** [ahmedkaludi/accelerated-mobile-pages#1762]
The WordPress Comments appears in AMP with the option AMP > Comments > WordPress Comments disabled. 

![captura de pantalla 2018-02-20 a las 13 50 51](https://user-images.githubusercontent.com/9333094/36424845-17d6287c-1645-11e8-807d-72dab20fb545.jpg)
![captura de pantalla 2018-02-20 a las 13 50 29](https://user-images.githubusercontent.com/9333094/36424847-17f264f6-1645-11e8-9f76-5efd6a78a6f1.jpg)

**Comment by MARQAS** [comment]
Hi @adrianleira ,

I am unable to recreate this issue on my end, its working fine here.
Can you share the URL or contact us with admin details here: https://ampforwp.com/support/ ?

We will look into it and will resolve it for sure.

**Comment by MohammedKaludi** [comment]
Hi @adrianleira can you follow up with us on this so that we can help you fix it?

**Comment by ahmedkaludi** [comment]
@adrianleira can you follow up on this

**Comment by Sejiro-Hiko** [comment]
Hi @adrianleira ,

can you please update us on this issue? we're to tackle this issue if you are still facing it, please update us by 10th of July-2018 or we'll be closing this ticket as "resolved"

**Comment by ahmedkaludi** [comment]
We have waited for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
