### ISSUE TITLE
Problem with conversion of quotes

### ISSUE THREAD

**Issue by rockindolphin** [ahmedkaludi/accelerated-mobile-pages#1763]
For the Russian locale, wordpress uses `wptexturize` to convert opening curly double quote from symbol `'&#8220;'` into `'&#171;'`
enabling of the plugin breaks this behavior
I think this happens because variables` $opening_quote` and `$closing_quote` in `wptexturize` are static.
When i call `wptexturize('any text',false)` with some text and `$reset` set to `true` before plugin init - it fixes the problem
```
function initTexturizeBeforeAMP(){
    wptexturize('any text',false);
}
add_action('init','initTexturizeBeforeAMP',10);
```

**Comment by ahmedkaludi** [comment]
Waited long for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
