### ISSUE TITLE
PHP Warning:  A non-numeric value encountered in components/logo/logo.php on line 52

### ISSUE THREAD

**Issue by ob-ivan** [ahmedkaludi/accelerated-mobile-pages#1764]
WordPress: 4.9.4
AMP for WP: 0.9.82.1

This line pops up occasionally in error logs:

```
[Tue Feb 20 16:36:05.477480 2018] [php7:warn] [pid 6918] PHP Warning:  A non-numeric value encountered in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/components/logo/logo.php on line 52
```

Debug printing shows that this call on line 48:

```
$width = ampforwp_default_logo('width');
```

returns empty string which triggers the warning when attempting to multiply by `$max_width`.

**Comment by beingsmart3** [comment]
Another Ref:  https://secure.helpscout.net/conversation/526431775/21934?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1:  Tested in 7.1 and 7.2 php versions
