### ISSUE TITLE
Problem with shortcodes of AAWP plugin in AMP

### ISSUE THREAD

**Issue by nacubo** [ahmedkaludi/accelerated-mobile-pages#1766]
Hi,

I have a web and often we recommend products on Amazon using the plugin AAWP. This is the list of shortcodes: https://aawp.de/en/docs/article/shortcodes/

For example, this shorcode shows the price in non-amp version:

[amazon fields="B072NYVLXC" value="price"]

But in amp versión it appears like this as text:

[amazon fields=”B071YGVFNZ” >

Any solution?

Thanks!

**Comment by miguelgaton** [comment]
Same issue here. Any feedback please?

**Comment by Sejiro-Hiko** [comment]
hey guys @nacubo @miguelgaton, are you still facing this issue? if yes can you please reach us out here `https://ampforwp.com/support/` I'll look into the issue personally on your end and will resolve it.

**Comment by nacubo** [comment]
Thanks @Sejiro-Hiko 

I've sent you the ticket.

Best regards,

**Comment by Sejiro-Hiko** [comment]
@nacubo I've replied to you on the ticket please look into it.

**Comment by Sejiro-Hiko** [comment]
ref: https://secure.helpscout.net/conversation/618404764/29989/?folderId=1680011

**Comment by Sejiro-Hiko** [comment]
shortcodes are working on user's end so we can close this ticket

**Comment by MohammedKaludi** [comment]
Feedback from user.
> I've tested the problem and it is solved. 

:+1:
