### ISSUE TITLE
Ad Inserter and AMPForWP Conflict

### ISSUE THREAD

**Issue by MayankParmar207** [ahmedkaludi/accelerated-mobile-pages#1768]
Hey,
First of all, I don't have Ad Inserter Pro, so I'm not attempting to put ads in AMP pages with it, I'm using AMPForWP plugin for ads.

Problem is Ad Inserter is creating a blank space in AMP pages, I used Chrome inspect element, and it shows 'Code blocks'  from Ad inserter plugin, though ads won't show.

Please look into it.

**Comment by MARQAS** [comment]
Hi @MayankParmar207 ,
We are not adding any code from ad inserter plugin.
Can you contact them regarding this? maybe they are trying to add some code in AMP

**Comment by MARQAS** [comment]
Hi @MayankParmar207 , are you still facing this issue? Can you share the screenshot of it?

**Comment by MayankParmar207** [comment]
@MARQAS Yes. I reached out to Ad Inserter dev but he could not fix it, though he asked for admin credentials, something I couldn't share :) He said I can use Ad Inserter for inserting ads in AMP pages but I'd prefer AMPForWP's solutions since it's better, reliable and trusted.

Here's a screenshot: 
![image](https://user-images.githubusercontent.com/36712929/37293503-7c680fcc-2639-11e8-8ff7-49967414ae9f.png)

Thanks

**Comment by Sejiro-Hiko** [comment]
@MayankParmar207 are you still facing the issue? As I tried to recreate the issue as you've displayed in the setting and other ways but Unable to recreate this issue. are you sure that someone from your end tried to add the `code-block` html as a custom Ad for AMP? can you please share the url at `https://ampforwp.com/support/` otherwise we need to close this ticket.

**Comment by ahmedkaludi** [comment]
Waited long for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
