### ISSUE TITLE
Search console: Structured data invalid for AMP homepage

### ISSUE THREAD

**Issue by woutheijnen** [ahmedkaludi/accelerated-mobile-pages#177]
Hello,

My Google Search Console for my website is showing some errors for my homepage (I have assigned a page as homepage in your plugin). The search console says the following about line 5:
Author name invalid (which is null on the homepage)
The image (ImageObject) has an invalid width of 0
Headline which is empty...

This is the pasted line:
`<script type="application/ld+json">{"@context":"http:\/\/schema.org","@type":"BlogPosting","mainEntityOfPage":false,"publisher":{"@type":"Organization","name":"Brainobrain LYON - France","logo":{"@type":"ImageObject","url":"https:\/\/www.brainobrainlyon.fr\/fichiers\/uploads\/2016\/07\/logomid-e1473867964547.png","height":36,"width":190}},"headline":"","datePublished":"1970-01-01T00:00:00+00:00","dateModified":"1970-01-01T00:00:00+00:00","author":{"@type":"Person","name":null},"image":{"@type":"ImageObject","url":"https:\/\/www.brainobrainlyon.fr\/fichiers\/uploads\/2016\/09\/Abacus.jpg","height":0,"width":0}}</script>`

As you can see, there are multiple problems here:
The headline is empty
The date published is from 1970
Same goes for the date modified
The name of the author is null (which is not the case for my other pages)
The last imge has 0 height and 0 width

If you need to see the url, this is it: https://www.brainobrainlyon.fr/?amp

I hope you can resolve it :)!
Thank you for the amazing plugin!

**Comment by ahmedkaludi** [comment]
Hey, @woutheijnen
    
Thank you so much for using the plugin. What is the version of the plugin that you have installed on your site?

Regards,
Ahmed

**Comment by woutheijnen** [comment]
Hello,

The version of the plugin is: Version 0.8.6.1.
For the technical AMP from Automattic it's Version 0.4.2.
Also I use W3TC and the AMP extension is activated and each of the plugins & Wordpress are in the most recent version.

Regards,
Wout

**Comment by khaledMohammed000** [comment]
@woutheijnen Please update and let us know of you still get the issue

**Comment by woutheijnen** [comment]
Hello,

I have updated but still receive the same issue.
For now, I have desactivated the custom amp homepage as seo websites such as yoast do not have this too and because it would be unpractical to update the page text each time something changes on the homepage.

**Comment by ahmedkaludi** [comment]
@woutheijnen Can you please enable it for a day? so I can check and get to the root of the exact issue?

**Comment by woutheijnen** [comment]
@ahmedkaludi Alright I have activated it again :). I also updated and am on the latest version of your plugin. However, the strange thing now is that the AMP homepage doesn't show my page that I linked it to. Also the data structure and dates are still wrong and produce an error in the search console as before. In my server errorlog however I have nothing that has been logged. To be sure, I have enabled E_ALL now and will keep you informed here. Thanks!

**Comment by woutheijnen** [comment]
Those are the errors that were encountered in this hours both for your amp plugin and the amp plugin from automaticc which is necesary to run your plugin:
PHP Notice:  Use of undefined constant AMP_QUERY_VAR - assumed 'AMP_QUERY_VAR' in /web/brainobrainlyon/www/fichiers/plugins/amp/includes/amp-helper-functions.php on line 42
PHP Notice:  Undefined index: type in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1226
PHP Notice:  Undefined index: type in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1231
PHP Notice:  Undefined index: type in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1146
PHP Notice:  Undefined index: type in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1147
PHP Notice:  Undefined index: type in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1153
PHP Notice:  Undefined index: type in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1174
PHP Notice:  Trying to get property of non-object in /web/brainobrainlyon/www/fichiers/plugins/amp/includes/class-amp-post-template.php on line 222
PHP Notice:  Trying to get property of non-object in /web/brainobrainlyon/www/fichiers/plugins/amp/includes/class-amp-post-template.php on line 148
PHP Notice:  Trying to get property of non-object in /web/brainobrainlyon/www/fichiers/plugins/amp/includes/class-amp-post-template.php on line 172
PHP Notice:  Trying to get property of non-object in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/templates/features.php on line 505
PHP Notice:  Trying to get property of non-object in /web/brainobrainlyon/www/fichiers/plugins/amp/includes/class-amp-post-template.php on line 198
PHP Notice:  Undefined variable: post in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/templates/single.php on line 117
PHP Notice:  Undefined variable: args in /web/brainobrainlyon/www/fichiers/plugins/accelerated-mobile-pages/templates/single.php on line 149
