### ISSUE TITLE
Google Cache AMP Not Same as my AMP Template Setting

### ISSUE THREAD

**Issue by aziu** [ahmedkaludi/accelerated-mobile-pages#1770]
Google Index URL : 
https://www.sekutukeadilan.com/pengertian-interaksi-sosial-syarat-macam-jenis-contoh-dan-tujuan/?amp_markup=1

It's werid, im not use that AMP Template : 
- No NavBar
- No Related Post
- No Adsense 

--------------------------------------------------------------

My Real AMP Url : 
https://www.sekutukeadilan.com/pengertian-interaksi-sosial-syarat-macam-jenis-contoh-dan-tujuan/amp/

Im lost so many earing because Google Cache Index "`/?amp_markup=1`"

It's really annoying, can some one help me ?

---------------------------------------------------------------

**how to CHANGE Google Cache AMP Index** "`/?amp_markup=1`" to "`/AMP/`" or "`?AMP`" ?!

Search Console : http://bit.ly/2FvhCOz
Sorry for my bad English, i really not understand

AMPforWP v0.9.81

**Comment by ahmedkaludi** [comment]
For technical support, please contact us via https://ampforwp.com/support
