### ISSUE TITLE
URL parameters are removed when redirecting to the AMP version of a page

### ISSUE THREAD

**Issue by jrean** [ahmedkaludi/accelerated-mobile-pages#1771]
Hi,

AMPforWP Options 0.9.82.1
WordPress 4.9.4

Using google chrome dev tool ;

Desktop mode:
`https://blog.gotomalls.com/?foo=bar&baz=bad`
The page loads normally (non amp version) *and the parameters are kept*.

Desktop mode:
`https://blog.gotomalls.com/amp/?foo=bar&baz=bad`
Forcing the amp version (on a desktop) loads the page in amp normally **and the parameters are kept**.

Mobile mode:
`https://blog.gotomalls.com/amp/?foo=bar&baz=bad`
Forcing manually the amp version loads the page normally in amp **and the parameters are kept**.

**Where the bug happens**:

Mobile mode:
`https://blog.gotomalls.com/?foo=bar&baz=bad`
AMP is not present in the URL and the system will append the `amp` to the url  **but will remove all existing parameters**.

Am I missing something in the configuration? Is it a known bug?
Please help and share some light.

Cheers,

**Comment by MohammedKaludi** [comment]
@jrean Thank you for your feedback, we have added this feature to the plugin and this feature will be pushed in next update, which we are planning to release on 25th June.

Thank you very much for your feedback. 
Closing the ticket.
