### ISSUE TITLE
View Non-AMP should be usertrailingslashit

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1772]
Ref:  class="view-non-amp" href="https://www.lanaika.com/blog/lanaika/beau-bronzage-toute-lannee.html/" >View Non-AMP Version 

The Original url is "https://www.lanaika.com/blog/lanaika/beau-bronzage-toute-lannee.html"

**Comment by MohammedKaludi** [comment]
:+1:
