### ISSUE TITLE
AMP Newspaper theme Page Builder (AMP) [Legacy] is not working in the latest version

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1773]
The legacy page builder is not appearing in the widget area after enabling the AMP newspaper theme because this option is removed in the latest version.

Ref: http://take.ms/QFLLE

**Comment by Zabi09** [comment]
Ref: https://secure.helpscout.net/conversation/531260729/22330/?folderId=1680016

**Comment by MohammedKaludi** [comment]
Widgets option only be visible when AMP NewsPaper theme is active because it is depended on Widgets.

:+1:
