### ISSUE TITLE
AMPforWP Compatible with WPSSO

### ISSUE THREAD

**Issue by mayanksharma9033** [ahmedkaludi/accelerated-mobile-pages#1774]
Debug Error:- The tag 'link rel=canonical' appears more than once in the document

**Comment by MARQAS** [comment]
tested with different WPSSO plugins but unable to find the issue. It seems that they have added the compatibility of our plugin. 
They have mentioned it: https://wordpress.org/plugins/wpsso/

**Comment by MohammedKaludi** [comment]
:+1:
