### ISSUE TITLE
WPML compatibility with AMP Page builder

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1776]
Issue related to the Languages support and translation into AMP version by AMP page builder 

Ref:  https://secure.helpscout.net/conversation/529397230/22178?folderId=1514170

**Comment by beingsmart3** [comment]
Another Ref:  https://secure.helpscout.net/conversation/528284909/22085?folderId=1060551

**Comment by ahmedkaludi** [comment]
This feature has been added in https://ampforwp.com/wpml-for-amp/
