### ISSUE TITLE
Removed Strip tags from pagebuilder, content blank when only image in  content

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#1778]
Issue: In content of post or page, when we select only media and check amp page, pagebuilder detect it like empty tags and replace it with blank.
To resolve remove strip_tags while checking of content is blank or not
![image](https://user-images.githubusercontent.com/19512210/36774980-24d93626-1c86-11e8-90c4-0814970177a9.png)

**Comment by MohammedKaludi** [comment]
:+1:
