### ISSUE TITLE
Front page conflicts with Polylang plugin 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1779]
The front page is empty when Polylang plugin is activated even the custom AMP editor, AMP page builder and also ACF is not working. 

Ref: https://secure.helpscout.net/conversation/528753711/22126?folderId=1680011
Ref: LocalHost

**Comment by MohammedKaludi** [comment]
FrontPage is getting blank in AMP when Polylang is activated.

**Comment by MARQAS** [comment]
https://secure.helpscout.net/conversation/540358941/23082?folderId=1060551

**Comment by beingsmart3** [comment]
One more
Ref:  https://secure.helpscout.net/conversation/540358941/23082?folderId=1060551

**Comment by MARQAS** [comment]
Important Note:
Frontpage in AMP options panel and Frontpage in Reading settings should be same.
If both are different then AMP frontpage will still show the Frontpage from Reading Settings. 
Reason: Polylang is creating the Translated pages for Frontpage in page_on_front option and it can be retrieved using pll_get_post(get_option('page_on_front')). If we take the Frontpage id from the AMP options panel it will break the translated Frontpages created by Polylang.
So to use Polylang Frontpages efficiently with AMP keep the same Frontpage for Reading settings and AMP Settings.

**Comment by beingsmart3** [comment]
one more Ref:  https://secure.helpscout.net/conversation/541049564/23117?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1: Now Working smoothly. With and Without custom frontpages
