### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1785]
The error log goes wild since last update:

A non-numeric value encountered in /plugins/accelerated-mobile-pages/components/logo/logo.php on line 52

Could PHP 7.2 related .. any quick fix?

$max_width = ceil(($width*$max_width)/100)."px";

REF: https://wordpress.org/support/topic/a-non-numeric-value-encountered-5/#post-10018976

**Comment by MohammedKaludi** [comment]
This has been fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1764 

Closing the ticket.
