### ISSUE TITLE
Times Not showing correctly

### ISSUE THREAD

**Issue by SSDesigns** [ahmedkaludi/accelerated-mobile-pages#1792]
Hey, I am a Mobile developer on word press and using this plugin for quite a while I noticed a serious bug. Pay-to-win.com’s Posts Say

Excuse the dust
Please excuse the dust. Our web host has been making updates like adding an app and working on improving load…

48 years ago

But the Time is correct when i click on the post?

Any ideas on how to fix?

The page I need help with: https://Pay-to-win.com/amp/

**Comment by ahmedkaludi** [comment]
For the technical support, write us via https://ampforwp.com/support
