### ISSUE TITLE
AMP Validation issues with related posts

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1795]
AMP errors are showing up when no image is there in related posts.

Ref: https://secure.helpscout.net/conversation/534749812/22590?folderId=1680016

**Comment by Zabi09** [comment]
Screenshot: http://take.ms/wWTTOS

**Comment by Zabi09** [comment]
Ref: https://secure.helpscout.net/conversation/530041123/22234/?folderId=1060556

**Comment by MohammedKaludi** [comment]
:+1:
