### ISSUE TITLE
When RTl option is enable then side menu appear entirely on website...

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1796]
If we enable the RTL option then sidebar menu display on overall website.

reference: https://secure.helpscout.net/conversation/534302661/22553?folderId=1060551

Screenshot: http://take.ms/Nm7hg

**Comment by MohammedKaludi** [comment]
@ansaritalha thank you for reporting the issue. We have added this ticket to our next milestone and it will be fixed in the next update.

**Comment by MohammedKaludi** [comment]
:+1:  Nice work @RajuJeelaga
