### ISSUE TITLE
Performance Enhancement Suggestion

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1799]
So, the user asked this: https://wordpress.org/support/topic/slow-section-of-code/

After some code review by @ajeetku - We realized that the code mentioned by the user is loading on every page and not just that but the admin-config.php as well, so if we are able to fix this then it would be a BIG performance update.

**Comment by MohammedKaludi** [comment]
Checked and looks fine on the first, but need to test on multiple environments.

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f12f875e3ae02fc89245bd3c3ddf03b6d0c843fe

**Comment by MohammedKaludi** [comment]
:+1:
