### ISSUE TITLE
Url of posts is added in structured data

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1801]
When we test the data structure for the xyz.com everything works just fine but when we test xyz.com/amp it shows xyz/amp page data schema as an article with the URL being most recent post.

ref:  https://secure.helpscout.net/conversation/534166509/22539?folderId=1060551

**Comment by MARQAS** [comment]
Schema plugin is adding its own schema in AMP.
Contacted the user, waiting for her reply.

**Comment by MohammedKaludi** [comment]
We need to provide our structured data solution then we will review again

**Comment by MARQAS** [comment]
Currently, the schema is generated by our plugin. 
But It is generating Article for Homepage as well. Is it normal? I guess the main concern of the user is that only.
 @MohammedKaludi @ahmedkaludi

**Comment by MohammedKaludi** [comment]
Issue not related to our plugin, but it is a conflict with schema plugin by hashim
