### ISSUE TITLE
Cannot redeclare aq_resize()

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1805]
Hey guys, got an error upon activation:

Fatal error: Cannot redeclare aq_resize() (previously declared in /data/web/virtuals/51249/virtual/www/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php:235) in /data/web/virtuals/51249/virtual/www/wp-content/themes/flexform/includes/plugins/aq_resizer-2x.php on line 145

any idea how to make it work? Thanks Filip

https://wordpress.org/support/topic/cannot-redeclare-aq_resize/

**Comment by MohammedKaludi** [comment]
:+1:
