### ISSUE TITLE
noindex, noarchive per page test with Yoast and Genesis

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1806]
If Yoast and Genesis have a noindex or noarchive settings enabled per page then the AMP should also get those metas.

REF: https://wordpress.org/support/topic/noindex-noarchive-issue/

**Comment by Frenchomatic** [comment]
This is actually a critical issue.

**Comment by MARQAS** [comment]
Test with Yoast: It is working as expected

**Comment by MARQAS** [comment]
Test with Genesis: Working as expected.
It is resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2071

**Comment by MohammedKaludi** [comment]
> Test with Yoast: It is working as expected. It is resolved here: #1563

Not working,  its always showing incorrect value in robots tag. Do let me know if you are not able to recreate it.

**Comment by Frenchomatic** [comment]
Working for me on Genesis.

**Comment by MohammedKaludi** [comment]
Now it's working perfectly. :+1:
