### ISSUE TITLE
Blockquotes in AMP enabled page Showing as regular text

### ISSUE THREAD

**Issue by beingteja** [ahmedkaludi/Accelerated-Mobile-Pages#181]
**Blockquotes Showing as regular text in AMP enabled page.**

<img width="1130" alt="sample page _ just another wordpress site - google chrome 2016-10-28 15 11 35" src="https://cloud.githubusercontent.com/assets/23118284/19802995/103aaafc-9d24-11e6-8b94-ef92608c0c93.png">

**Comment by nicholasgriffintn** [comment]
That's just CSS, you need to add the styles for the quote in the custom CSS section of AMP.

**Comment by khaledMohammed000** [comment]
@ahmedkaludi Please let me know your thoughts on this

**Comment by nicholasgriffintn** [comment]
Just to help:

This is simply a CSS issue, you could add options to the plugin settings, however, all the user needs to do really is add CSS to their custom CSS section, such as:

`.amp-wp-content blockquote {
    background-color: #fff;
    border-left: 3px solid #000;
    border-top: 1px solid #ddd;
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
   color: #445;
}`

**Comment by khaledMohammed000** [comment]
Thanx @nicholasgriffintn I'll close this issue now :)

**Comment by khaledMohammed000** [comment]
@beingteja I have Understood your problem , as you can see in the <a href="https://cloud.githubusercontent.com/assets/23118284/19802995/103aaafc-9d24-11e6-8b94-ef92608c0c93.png">image</a> Even your Theme style is not displayed in the AMP page , We are working on this and will let you know once we have successfully put even theme styles in AMP pages and then i think you will not get any of this issue
