### ISSUE TITLE
PHP notice when the CTA extension is activated

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1810]
Notice: Undefined index: amp-frontpage-select-option-pages in /chroot/home/lancersk/lancerskincare.com/html/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 5328

Ref: https://secure.helpscout.net/conversation/533448893/22488?folderId=1680011

**Comment by MARQAS** [comment]
As far as I know, Its not connected to CTA and I am unable to recreate this issue. 
Might be the options problem? I guess he didn't save the option for the first time.

**Comment by MARQAS** [comment]
Ah!, There's not even a single page on his site

**Comment by MohammedKaludi** [comment]
:+1:
