### ISSUE TITLE
Compatibility for Photo Gallery [WordPress plugin] 

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1811]
When user displaying images in the posts (body) by using photo gallery plugin images are displayed in non amp but not appearing in amp so we have to make compatibility for photo gallery plugin.

Reference :https://secure.helpscout.net/conversation/535124420/22647?folderId=1060551

Plugin: https://wordpress.org/plugins/photo-gallery/

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master, but it has a dependency on a ticket.

**Comment by ajeetku** [comment]
It's working without dependency

**Comment by pegazee** [comment]
"Lightbox for Gallery" option is not working with this plugin.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
