### ISSUE TITLE
Meta Description Content is Mismatching in AMP

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1812]
Meta description Content is Mismatching in AMP.

Example:
 <meta name="description" content="Find the latest News news and analysis, headlines, blogs, pictures and videos from around Nigeria and world on TODAY.NG."/>

<script type="application/ld+json">{"@context":"http:\/\/schema.org","@type":"NewsArticle","mainEntityOfPage":false,"publisher":{"@type":"Organization","name":"TODAY.NG","logo":{"@type":"ImageObject","url":"https:\/\/www.today.ng\/wp-content\/uploads\/2017\/12\/today_amp.svg","height":"60","width":"600"}},"headline":"Archived Posts","datePublished":"1970-01-01T00:00:00+00:00","dateModified":"2018-03-06T07:34:01+00:00","author":{"@type":"Person","name":"admin"},"image":{"@type":"ImageObject","url":"https:\/\/www.today.ng\/wp-content\/uploads\/2017\/10\/today.ng_default.png","height":560,"width":700},"description":""}</script>

<meta property="og:description" content="Find the latest Nigeria and world news and analysis, headlines, blogs, videos and pictures from TODAY.NG."/> 

<meta name="twitter:description" content="Find the latest Nigeria and world news and analysis, headlines, blogs, videos and pictures from TODAY.NG."/>

Reference: https://secure.helpscout.net/conversation/533598320/22497?folderId=1060551

**Comment by MohammedKaludi** [comment]
:+1: this is working as expected. One things is still pending but will be fixed in #2159 
Closing the ticket.
