### ISSUE TITLE
disqus in amp page size

### ISSUE THREAD

**Issue by yeniugo** [ahmedkaludi/accelerated-mobile-pages#1813]
only in the 'theme one' and 'theme three' can show disqus,but 'theme two' and 'swift' can not.

in the 'theme one' and 'theme thress',it can not resize the right size.this is the error message in chrome,"Ignoring embed-size request because this iframe is not resizable".

**Comment by MARQAS** [comment]
Hi @yeniugo
Apologize for the delay. 
We are going to push an update today, please update it once the update is available and let us know if your issue is resolved or not.

**Comment by MohammedKaludi** [comment]
:+1:
