### ISSUE TITLE
Homepage Loading Issues

### ISSUE THREAD

**Issue by osseonews** [ahmedkaludi/accelerated-mobile-pages#1814]
I posted this on Wordpress, but didn't get a response. Upon upgrading to the newest version of this plugin (0.9.83), the homepage no longer loads. To recreate this error you can:
- Install 0.9.83
- Use Design 3 (which is what we use - other designs may have error also, but we didn't test)
- Enable Homepage from the front page (don't enable custom front page)
- Enable Posts for Homepage
When you click on the AMP Homepage it will not load. Just times out. All other AMP pages/posts function normally.

**Comment by ahmedkaludi** [comment]
For technical support, please write us on http://ampforwp.com/support
