### ISSUE TITLE
Advanced Comment Usecase

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1816]
- [x] Make sure that the no. of comments which are showing in Non-AMP are equal to the no. of comments in AMP.

- [x] Make sure that the canonical in AMP should reflects towards the same Non-AMP page.

Reference: https://secure.helpscout.net/conversation/535523544/22682?folderId=1060551

**Comment by MohammedKaludi** [comment]
Need to fix the Styling in comments Pagination http://take.ms/Q3c0G

**Comment by MohammedKaludi** [comment]
:+1:
