### ISSUE TITLE
Swift Design Improvements

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1818]
- [x] 1. How can I remove the line under the breadcrumbs?

- [x] 2. Is there a way to add another ‘>’ symbol between categories and subcategories in the breadcrumbs?

- [x] 3. Strange '1' coming: http://take.ms/4xcmi ( How can I remove the strange ‘1’ at the bottom, right above ‘DON’T BE A STRANGER’ on desktop. On mobile, the ‘1’ goes under the text, after CONTACT.

- [x] 4. search text color in https://www.bylauraiancu.com/launch-a-blog-checklist/amp#search is white - so where is it coming from and how can we use it?

- [x] Add Proper gaps in the content in single http://take.ms/7Ep9l.

- [x] Extra P margin causing issues in the pagebuilder.

REF: https://wordpress.org/support/topic/remove-line-under-breadcrumbs/#post-10042061

**Comment by MohammedKaludi** [comment]
- [ ] Scrollbar in Header area in firefox http://take.ms/r9YSI

**Comment by MARQAS** [comment]
- [ ] Button module showing twice
