### ISSUE TITLE
How can we override Style Sanitizer

### ISSUE THREAD

**Issue by rohittm** [ahmedkaludi/accelerated-mobile-pages#1819]
Is there any way we can override Style Sanitizer like this one: https://ampforwp.com/tutorials/article/override-blacklist-sanitizer ?

**Comment by Sejiro-Hiko** [comment]
@rohittm can you tell us what is your use case that you want to override the style sanitizer?

**Comment by ahmedkaludi** [comment]
We have waited for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
