### ISSUE TITLE
Resulting mobile site is not responsive

### ISSUE THREAD

**Issue by webspecials** [ahmedkaludi/Accelerated-Mobile-Pages#182]
Hi guys,

Good job with the AMP plugin.  The plugin installed fine and generated the AMP site.  The desktop and iPad resulting sites are fine.

Unfortunately, the mobile site is not responsive and it generates a post that is much smaller than the phone screen.  I can see that the Adsense ads are ok but the original post is not responsive.

I have attached three images.  
1.  The first screen of the AMP post
2.  The second screen that appears after tapping on the AMP post (this is the one that is not responsive)
3.  The screenshot of the normal mobile site without the AMP (which is mobile responsive and perfectly proportionate).

Congratulations on a great plugin.  When I tested the AMP site with Google Developers Speed Test it showed a mobile rating of 89,  the standard rating of the mobile resolution without AMP is 63 :-)

Best regards

Alex
![Uploading FIRSTAMPSCREEN - Copy.PNG…]()
![Uploading mobile - Copy.png…]()
![secondampscreen](https://cloud.githubusercontent.com/assets/23146513/19834695/ad05f6c0-9ebe-11e6-96d3-ce863498b287.PNG)
![firstampscreen](https://cloud.githubusercontent.com/assets/23146513/19834693/a7f17ab0-9ebe-11e6-847b-17d509b38749.PNG)
![Uploading SECONDAMPSCREEN.PNG…]()
![mobile](https://cloud.githubusercontent.com/assets/23146513/19834697/b26bfc5e-9ebe-11e6-9092-3d1a2b36f3d0.png)

**Comment by nicholasgriffintn** [comment]
Your ad is too large, change that to a responsive ad.

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn Thank you for helping :)

@webspecials This was related to non-amp version of the site. I am closing this issue.
