### ISSUE TITLE
Swift Image thumbnail resizing issue.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1828]
We're taking a smaller image and then stretching it instead of getting the cropped size. Download this image and set it as featured image and see the output: https://fargo1ife.com/wp-content/uploads/2018/03/B8B9A5E1-CD31-441F-8EE6-8525601ADBDF.jpeg

REf: Telegram (Sage)

**Comment by ahmedkaludi** [comment]
I don't see them anymore.

**Comment by MohammedKaludi** [comment]
:+1:
