### ISSUE TITLE
AMP for WooCommerce Integration

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#183]
I have installed “AMP for WooCommerce” plugin in Addition to the AMP for WP plugin Still the shop pages are missing Add to Cart buttons.I contacted theme developers and they advised to install AMP for WooCommerce.

I would highly appreciate your feedback on how to get this resolved. What is the right plugin or action to take? this is really hurting our website, I am getting too many errors on Google Webmaster. Here is the screeshot: http://imgur.com/a/IMs8A

Here is a screenshot: http://imgur.com/a/ddsyg

Link to one of the product page: https://ibabylabs.com/shop/ibaby-air/amp/

**Comment by khaledMohammed000** [comment]
Activate following plugins and see the Errors: 
1. AMP
2. AMP Woo Commerce
3. AMP for Incontents
4. Woo Commerce

and start solving issues in "AMP Woo Commerce"

**Comment by kevin25** [comment]
I got blank page and there is no error log. How can i solve it?

**Comment by khaledMohammed000** [comment]
@kevin25 lemme check and get back to you 👍
