### ISSUE TITLE
Content Is Not rendering in AMP because of accent marks

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1832]
Content Is Not rendering in AMP because of accent marks, and to render the accent marks content need to turn off the Minify Option.

Ref:  https://secure.helpscout.net/conversation/535312399/22666?folderId=1060551

**Comment by MARQAS** [comment]
Working properly on my end. Might be multibyte problem? Asked the user, let's see what he has to say.

**Comment by MohammedKaludi** [comment]
Issue Fixed, It was an issue from the user's site. http://take.ms/hJq8d
