### ISSUE TITLE
Frontpage not working with latest update

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1837]
https://wordpress.org/support/topic/static-homepage-not-working-in-latest-upgrade/#post-10059511

**Comment by MARQAS** [comment]
It was due to caching not AMP

**Comment by MohammedKaludi** [comment]
Testing and checking out this bug in the user's websites.

**Comment by MohammedKaludi** [comment]
:+1:
