### ISSUE TITLE
Posts are not displaying in AMP Homepage when user is using Jarida Theme

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1842]
Posts are not displaying in AMP Homepage when the user is using Jarida Theme,
In Non-AMP(Jarida Theme) the Home page is having 15 posts but in AMP homepage only 1 post is displaying.

Reference: https://secure.helpscout.net/conversation/536551883/22737?folderId=1914722

**Comment by MohammedKaludi** [comment]
:+1:
