### ISSUE TITLE
Improve the way we get thumbnails in Woo-widget.php 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1847]
http://take.ms/dQVjKG

Currently we are adding the images in static way
line no: 69 
             <amp-img src='<?php echo esc_url( $thumb_url ); ?>' width="150" height="150" layout="responsive"></amp-img> <?php

**Comment by ahmedkaludi** [comment]
- [ ] Height and width should be dynamic according to the image cropping method.

**Comment by MohammedKaludi** [comment]
:+1:
