### ISSUE TITLE
Set Pinterest parameters Properly.

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1853]
Can not able to see picture to share on mobile view but work perfectly on the desktop view.

Ref: https://secure.helpscout.net/conversation/531082114/22323?folderId=1914716

**Comment by MohammedKaludi** [comment]
@MARQAS Escape this $image variable as well esc_url($image);

**Comment by MohammedKaludi** [comment]
:+1:
