### ISSUE TITLE
Can you please update Advanced AMP Ads to support Ads on Homepage?

### ISSUE THREAD

**Issue by anirudhpulikonda** [ahmedkaludi/accelerated-mobile-pages#1857]
I've previously requested on this at #1379 but it was closed and my issue wasn't fixed. Kindly, look into to it.

**Comment by ahmedkaludi** [comment]
@anirudhpulikonda  I am sorry that you had to wait for such a long time. We will add this for you in the next update.

**Comment by ahmedkaludi** [comment]
@Sejiro-Hiko We will have to add this in Ads for WP.

**Comment by anirudhpulikonda** [comment]
Thanks a lot @ahmedkaludi

**Comment by Sejiro-Hiko** [comment]
@ahmedkaludi On it.

**Comment by Sejiro-Hiko** [comment]
@anirudhpulikonda we've Added the support in Ads for WP for more info check this [https://ampforwp.com/introducing-ads-for-wp/](url) or [https://ampforwp.com/ads-for-wp/](url)

**Comment by anirudhpulikonda** [comment]
Thanks, @Sejiro-Hiko , Updated the Plugin and the Ads are working.
