### ISSUE TITLE
AMP layouts & pagebuilder improvements

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#1861]
1. Show Amp-layout upcoming layout image when AMP-layouts plugin is not Activated
2. Pagebuilder Improve required Field show hide, within TAB switching
3. Added viewport for non-amp "While WP CONVERT is enabled"

**Comment by MohammedKaludi** [comment]
Missed out commit https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/1863/commits/ab6cbffe4f34359d1b0bbe799eed67d2c3d8b003

**Comment by MohammedKaludi** [comment]
:+1:
