### ISSUE TITLE
Published Date for posts is showing "48 years ago" in swift

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1864]
The publish date is showing "48 years ago" in swift, we have login details of the user.

ref: https://secure.helpscout.net/conversation/537676188/22864?folderId=1914716

**Comment by scorpaanon** [comment]
components-core.php

The Get_the_date is used and This was referenced in automatics plugin for amp 3 months ago this issue came up!

-KHII

**Comment by MohammedKaludi** [comment]
:+1:
