### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted ( FrontPage)

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1865]
https://secure.helpscout.net/conversation/540647066/23098?folderId=1060554
and  2,3 more

**Comment by MARQAS** [comment]
get_comments_number filter is causing the issue

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
TODO: Allowed memory size exhausted #1865	 

get_comments() was trying to access by Id and because the ID is not present on amp frontpages. It is getting exhausted. Need to recreate issue and validate the hypothesis
