### ISSUE TITLE
Hide AMP Bulk Tools Improvements

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1867]
- [x] Allow Tags to be excluded

- [ ] Improve the performance caused by this feature.

REF: https://wordpress.org/support/topic/hide-amp-from-tags-specific-posts-pages/

**Comment by ajeetku** [comment]
Allow Tags to be excluded #2147 24c76c8

**Comment by MohammedKaludi** [comment]
:+1:
