### ISSUE TITLE
Translation in Italian

### ISSUE THREAD

**Issue by marcopanichi** [ahmedkaludi/accelerated-mobile-pages#187]
Hi guys,

first of all thank you for creating this plugin. Very helpful!

To offer my small contribution **I have translated into Italian the "Read me" file** (it is the first time I submit a translation ... let me know if everything is ok!).

In addition to this work, **I can also translate the plugin**, but I see that the plugin is not properly prepared for localization.

If you will prepare the plugin for localization, I will provide to translate it into Italian.

Thanks again for your contribution!

Marco

**Comment by khaledMohammed000** [comment]
We have come up with a good solution ...You will find it in the next update 👍
