### ISSUE TITLE
hook for between related post

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#1874]
Ref: commit 36ef05a84a741fd35aa5cee523476f603a53584b

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko hook not added between the related post in accelerated-mobile-pages\components\related-posts/related-posts.php

As as result ads will not work in the swift theme.

**Comment by Sejiro-Hiko** [comment]
@MohammedKaludi hook is added in the following file.
accelerated-mobile-pages\templates\design-manager\swift\single.php

**Comment by MARQAS** [comment]
Working
