### ISSUE TITLE
amp-wistia--player support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1875]

**Comment by MARQAS** [comment]
https://secure.helpscout.net/conversation/541913202/23184?folderId=1060556

**Comment by emma-tuna** [comment]
Hello, I would just like to say that this is a very important issue to me. I am also looking to embed wistia videos. If I can help in any way, let me know. :)

**Comment by ansaritalha** [comment]
https://secure.helpscout.net/conversation/555969522/24161?folderId=1914716

**Comment by MARQAS** [comment]
Hi @emma-tuna, Can you tell us how are you embedding wistia videos? Can you share a code snippet and a link where you are adding the wistia videos?

**Comment by MARQAS** [comment]
Working at the user end as well. just need to check the styling of player

**Comment by MohammedKaludi** [comment]
:+1:
