### ISSUE TITLE
Allow users to change the /amp endpoint

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1877]
Allow users to change the /amp endpoint

an example, website.com/m would be a new AMP version

https://wordpress.org/support/topic/can-we-change-the-amp-page-url/#post-10077823

**Comment by netmente194** [comment]
Hello Team,

The above was the query which I had discussed. Is there any update on the same?
Please let me know when the query is resolved.

Thanks

**Comment by MARQAS** [comment]
Hey @netmente194 , 
I apologize for the delay. 
We can change the URLs of AMP easily, but the new rewrite rules can mess up the whole thing. Thousands of users are using the plugin and they are using the same endpoint and as you know very well most of the users are non-technical and they think that /amp/ is the AMP version. They don't know much about the canonicals. So in my view giving an option to change the endpoint can cause more confusion at the moment.
So we are thinking of a workaround which can help people like you without confusing other non-technical users.

**Comment by MARQAS** [comment]
If you want to do it without waiting, please contact us through https://ampforwp.com/support/

I will personally assist you to do so or I will do it for you.

Please let me know what do you think about it

**Comment by MARQAS** [comment]
Ahmed here, Since we're working on subdomain support, this ticket is out of relevance.
