### ISSUE TITLE
 fatal error

### ISSUE THREAD

**Issue by li76303** [ahmedkaludi/accelerated-mobile-pages#1879]
After installing and activating amp, the following error message pops up, help me.

Parse error: syntax error, unexpected T_FUNCTION in /home/soondesign86/www/wp-content/plugins/accelerated-mobile-pages/pagebuilder/inc/viewShowFrontData.php on line 766

**Comment by MohammedKaludi** [comment]
Thank you @li76303 for creating the ticket and apologize that you are facing this issue.

This is a strange issue. Can you please share more details about the issue?

Also if you can share the login-info of the site at Team@magazine3.com so we can login and check what exactly is causing the issue?

Please be assured we will help you resolve this and make sure your site gets the powers of AMP.

Thank you,
Mohammed Kaludi

**Comment by MohammedKaludi** [comment]
@li76303 follow up

**Comment by MohammedKaludi** [comment]
@li76303 
This is the final message. If we don't get a reply from you in one week, then we have to close this ticket.

**Comment by ahmedkaludi** [comment]
@li76303 

We didn't had enough data on this and we did not faced this issue from any other user.

I'm closing the ticket. If you are still having the issue, then email us on team@magazine3.com
