### ISSUE TITLE
Source is missing or invalid width/height in Images

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1881]
If Featured Image from The Content option is enabled and it through validation errors if there is no image in the content In Design 1,2 and in Swift theme.

Ref:  https://secure.helpscout.net/conversation/541949900/23196?folderId=1914712

**Comment by githubjabbar** [comment]
one more
Ref:  https://secure.helpscout.net/conversation/541330514/23128?folderId=1914712

**Comment by MARQAS** [comment]
The issue is due to ampforwp_aq_resize function. 
It was throwing an exception when the image is not local.

**Comment by MohammedKaludi** [comment]
#1869
