### ISSUE TITLE
When Takeover is on then the link to comments button should work properly 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1883]
http://take.ms/rTJDg

Comments button should link to the proper comment form.

https://ampforwp.com/demo/layouts-news/golden-state-warriors-skip-white-house-take-students-to-african-american-museum-instead/?nonamp=1#commentform

**Comment by ahmedkaludi** [comment]
@marqas @MohammedKaludi This Fix actually doesn't make sense because there's no support for comments without the addon, so how will it possible. 

So I have created a ticket #1924 to get this fixed up
