### ISSUE TITLE
Ads on the frontpage if the Pagebuilder is enabled

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1885]
Ads on the frontpage if the Pagebuilder is enabled

**Comment by MohammedKaludi** [comment]
global $redux_builder_amp, $post;
      $optimize   = '';
      $post_id    = '';
      $client_id   = $redux_builder_amp['enable-amp-ads-text-feild-client-1'];
      $data_slot   = $redux_builder_amp['enable-amp-ads-text-feild-slot-1'];
      $optimize   = ampforwp_ad_optimize();

      if ( ampforwp_is_front_page() ) {
        $post_id = $redux_builder_amp['amp-frontpage-select-option-pages'];
      }

      // If page builder is enabled then 'Return' and show no ads  
      if ( checkAMPforPageBuilderStatus( $post_id ) ) {
        return;
      }

**Comment by ahmedkaludi** [comment]
👍
