### ISSUE TITLE
Logo is Http, may cause issues.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1891]
Whan adding my custom logo on Settings -> General, we only can add a logo from the Gallery so we can only add an http logo (not secure). We want to choose the Logo from an httpS (secure), is there any way to do this? Maybe with a css code or a hook?

Thank you.

The page I need help with: https://photo-to-text.com/2018/03/05/picture-made-with-text/amp

REF: https://wordpress.org/support/topic/setting-logo-fails-https/

**Comment by MARQAS** [comment]
There is no such issue. I and @ahmedkaludi tested it and found out that it has nothing to do with our code.

It can be closed.
