### ISSUE TITLE
Compatibility With Muffin Builder

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1893]
The content is not rendering in AMP because user uses the Muffin Builder, so at least content should be rendered in AMP.

Ref:  https://secure.helpscout.net/conversation/539452249/23019?folderId=1914712

**Comment by githubjabbar** [comment]
Ref:  https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1455

**Comment by githubjabbar** [comment]
REF: https://secure.helpscout.net/conversation/555324397/24121?folderId=1914722

**Comment by MohammedKaludi** [comment]
:+1:
