### ISSUE TITLE
Co-Author Plus Compatibility

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1895]
Co-Author Plus Compatibility ( https://wordpress.org/plugins/co-authors-plus/ )

REF: https://wordpress.org/support/topic/compatibility-issue-with-co-authors-plus-plugin/

**Comment by ahmedkaludi** [comment]
- [ ] Debug error upon co-author activation: http://take.ms/4tLwi

**Comment by MARQAS** [comment]
1: Done
2: It was coming from the Co-authors plugin. Now: it will come from AMPforWP Translation Panel.
3: If archive support is enabled then Yes, it will go to AMP else Non-AMP.

**Comment by MohammedKaludi** [comment]
:+1:
