### ISSUE TITLE
Piwik ,StatCounter Analytics Validation Errors on AMP pages.

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1899]
When two or more Analytics are enabled on the same AMP pages then the Validation errors are countered.
For example: StatCounter Analytics, Piwik Analytics etc.,

Reference: https://secure.helpscout.net/conversation/538914356/22976?folderId=1914722

**Comment by MARQAS** [comment]
Unable to recreate this issue.

Contacted the user, waiting for his reply.

**Comment by MohammedKaludi** [comment]
:+1:
