### ISSUE TITLE
Menu's Game UP 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1901]
Menu's Game UP: See Telegram: 3:48

**Comment by RajuJeelaga** [comment]
c07eece, 6acfdeb, b5c102c Commited

**Comment by MARQAS** [comment]
Double border
![sample page _ weekly - google chrome 2018-03-27 11 35 51](https://user-images.githubusercontent.com/15303814/37949666-2e55da46-31b3-11e8-8aeb-c50b5ff01634.png)
