### ISSUE TITLE
Gives the support customizing facility for author, page etc

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#1902]
Add the support for as like wordpress customization
Front Page display: #front-page-display
Home Page display
https://developer.wordpress.org/themes/basics/template-hierarchy/#non-ascii-character-handling

Desc: 
page.php – When “front page” is set in the front page displays section.
author: author-{$author->user_nicename}, author-{$author->ID}.php, author.php

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/56f2b069b1a6949b2b2d8cabc9bcaa08d268db18
