### ISSUE TITLE
Create an option for user to uninstall the plugin completly and all plugins data

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#1903]
Create an option for user to uninstall the plugin completly and all plugins data

**Comment by ahmedkaludi** [comment]
@MARQAS This should be with-in the Advanced Tab  http://take.ms/HI0Kg

**Comment by MohammedKaludi** [comment]
@ajeetku and @MARQAS  All the post meta's that we create should also be removed.

**Comment by MohammedKaludi** [comment]
:+1:
