### ISSUE TITLE
Extend Menu dropdown design for UX

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1906]
Add the "onclick" functionality to parent item in the menu of design 3, when I click on the parent item it should display child item. and on the second click, it should hide the child item.

Ref:https://secure.helpscout.net/conversation/543260750/23356?folderId=1914716

**Comment by bondweb** [comment]
Hi any news about it?

**Comment by MohammedKaludi** [comment]
It is impossible to reach a submenu element if a previous menu has any child items http://take.ms/y0m0X

**Comment by ahmedkaludi** [comment]
We found the solution! 

We have already tackled this in the new ticket: #2148
