### ISSUE TITLE
Fatal error: Call to undefined method WP_Image_Editor_GD::get_error_message() 

### ISSUE THREAD

**Issue by ob-ivan** [ahmedkaludi/accelerated-mobile-pages#1908]
WordPress version: 4.9.4
AMP for WP version: 0.9.84.1

In our setup, development machines mount images folder from production with readonly permission level.

When the plugin tries to resize a picture on a development machine, it results in a **Fatal** error, the log follows.

```
PHP Fatal error:  Uncaught Error: Call to undefined method WP_Image_Editor_GD::get_error_message() in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php:162
Stack trace:
#0 /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php(263): Aq_Resize->process('https://www.slr...', 100, 75, true, false, true)
#1 /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/components/loop/loop.php(316): ampforwp_aq_resize('https://www.slr...', 100, 75, true, false, true)
#2 /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-1/index.php(91): amp_loop_image(Array)
#3 /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(433): include('/home/web/smith...')
#4 /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/clas in /path/to/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php on line 162
```

As far as I recognize, there is a typo in `aq_resizer.php` on line 162. Instead of:

```php
$editor->get_error_message()
```

it should read:

```php
$resized_file->get_error_message()
```

**Comment by ob-ivan** [comment]
It would also be nice to have some sort of control over how I'd like to handle this situation. While in some cases a warning is a perfectly valid response ("hey admin! shit happened with your file system! take some action NOW"), in this particular case I'd be happy to suppress the warning completely and return either the original image or some stub instead.

Even better if I could disable the resizing with a hook, something like:

```php
add_filter('ampforwp_should_resize_pictures', function ($shouldResize) {
    // No resizing in debug mode, the readonly FS is by design.
    return !DEBUG_MODE && $shouldResize;
});
```

**Comment by ahmedkaludi** [comment]
@marqas @ajeetku 

What are your thoughts?

**Comment by ahmedkaludi** [comment]
@ob-ivan So your image folder is read-only? 
@ajeetku do you think it could be due to the `$resized_file->get_error_message()` as he mentioned?

**Comment by MARQAS** [comment]
@ob-ivan Have you tried changing the code as you suggested?

**Comment by ob-ivan** [comment]
@ahmedkaludi Yes, the folder is read-only in some environments, while it is read-write in production environment.

@MARQAS Yes, I did that, and the fatal error goes away, but a warning remains:

```
PHP Warning:  imagejpeg(/path/to/public_html/system/samoe-dorogoe-elitnoe-zhile-v-mire-100x75.jpg): failed to open stream: Read-only file system in /path/to/public_html/wp-includes/class-wp-image-editor.php on line 402
[Wed Mar 21 16:10:15.234284 2018] [php7:notice] [pid 20371] [client 192.168.1.43:56501] Aq_Resize.process() error: Unable to save resized image file: \xd0\x9d\xd0\xb5 \xd1\x83\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xbe\xd1\x81\xd1\x8c \xd1\x81\xd0\xbe\xd1\x85\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x82\xd1\x8c \xd0\xb8\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5
```

I'm sorry to have confused you. My comment about the warning was a feature request, and I should have created a separate issue for that.

**Comment by MARQAS** [comment]
@ob-ivan Can you share your staging site with the same setup? So we can go deep into it?

We haven't written the whole code of aq_resizer, just made some modifications in it. So have to check the code for your use case.

I hope you can understand.

**Comment by Sejiro-Hiko** [comment]
@ob-ivan your pull request has been merged and all the issues related to the `aq_resizer` are resolved so I'm closing this ticket and if there's anything left out please create a new ticket.
