### ISSUE TITLE
Fonts support in all three designs one, two and three along with the swift Theme

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1914]
The option of Google Font API key should support all the designs one, two and three along with the swift theme.

Ref: https://secure.helpscout.net/conversation/544404891/23438?folderId=1680011

**Comment by Zabi09** [comment]
Including the AMP Newspaper Theme also along with all three designs.

**Comment by MARQAS** [comment]
I think there are some more changes we have to make. 
So need an in-depth review on this from @ahmedkaludi and @RajuJeelaga to make those changes.

**Comment by beingsmart3** [comment]
Need to implement this feature in the AMP Theme Framework.

Ref: https://secure.helpscout.net/conversation/689557384/37969?folderId=1914712

**Comment by MARQAS** [comment]
Why not use `ampforwp_get_setting` instead of global `$redux_builder_amp` ?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
Not Working in Design 1, 2 and 3

**Comment by syedimran22** [comment]
Yes It is not working in design 1,2 and 3.

**Comment by RajuJeelaga** [comment]
Default Font family need to add
1.https://monosnap.com/file/rLfv3eqPdKZOjgSf72yShMftdNjFvq
when this is disabled the output is coming like this
https://monosnap.com/file/vpgO9qiwfRMBcj897GrU8d8Pt8Qa3w

for this, we need to add the default as arial/helvitca/georgia sans serif font.

**Comment by Zabi09** [comment]
Some of the elements are not working in design one like - 
https://prnt.sc/ouh5me
https://prnt.sc/ouh72u
https://prnt.sc/ouh7aa
And these options are connected with - https://prnt.sc/ouhcx7

And also in design 3 author bio font is not working - https://prnt.sc/ouhack

**Comment by merajali294** [comment]
Fonts aren't applied to the Footer Area and Title in Design 3 https://prnt.sc/ov4o5g

**Comment by MohammedKaludi** [comment]
1. Use `sprintf()` to pass the vairable in the label 
 -> https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f663f9fe1406cab9e17c65064e403e329f80937e#diff-260eba6333c3222e59a6aed22ac5ab37R3618

**Comment by MohammedKaludi** [comment]
Incorrect usage of `sprintf()`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3fd5d9ee66841d5c040ea38643a1251d1032da9b#diff-260eba6333c3222e59a6aed22ac5ab37R3644

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
