### ISSUE TITLE
Template overriding is not working in child theme...

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1920]
In your documentation
https://ampforwp.com/tutorials/article/child-theme-amp/
You mentioned that:
Create a folder name “ampforwp” in your theme/child theme directory.

But it’s not working in the child theme, only in the parent.
Because lookup folder is hardcoded only for search in parent theme directory
in file thirdparty-compatibility.php at line 82:

function ampforwp_theme_template_directry(){
return get_template_directory() . ‘/ampforwp/’;
}

Please add support for child themes as well.
I fixed directly in your plugin but it will be broken after next plugin update.

Ref: https://wordpress.org/support/topic/template-overriding-is-not-working-in-child-theme/

**Comment by MohammedKaludi** [comment]
:+1:
