### ISSUE TITLE
AMP takeover - 404 error pages

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1922]
There is a problem with respect to error 404 pages. The 404 page never shows.

1.  The normal 404 page whatever is defined in WP doesn't show.

2.  Even if you define a 404.shtml with ErrorDocument 404 /404.shtml in .htaccess it gets ignored.

3. Would be nice to be able to create a 404 error page in the AMP template being used.

**Comment by Sejiro-Hiko** [comment]
Fixed in #2042 tested and works fine.

**Comment by MohammedKaludi** [comment]
All the 3 issues mentioned are fixed in the commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/74e948c905206c5aa3076ff48d2e833826bd8dae

Closing this ticket more about this here: #2042
