### ISSUE TITLE
Huge IT Slider Issue

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1927]
Huge IT Slider not working in AMP and before <!doctype it's showing the code instead slider

Ref:  https://secure.helpscout.net/conversation/547222209/23618?folderId=1914712
Screenshot:  http://take.ms/PfY5z

**Comment by Sejiro-Hiko** [comment]
Tested on my end there are no AMP related issues and the slider comes in the form list of Images one after the other but apart from that there is no AMP Validation issues or breaking of designs...

And It seems the user has disabled the slider through our plugin manager.

**Comment by Sejiro-Hiko** [comment]
WordPress Has Closed the Plugin: This plugin was closed on February 7, 2018 and is no longer available for download. Reason: Guideline Violation.

http://take.ms/frfWt

https://wordpress.org/plugins/slider-image/

**Comment by MohammedKaludi** [comment]
:+1:  Will reopen the ticket once the plugin is live on wp.org
