### ISSUE TITLE
Menu is appearing on left side instead of Right side when RTL support is ON for Design3

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1928]
Menu is appearing on left side instead of Right side when RTL support is ON for Design3.

REF: https://secure.helpscout.net/conversation/547760078/23643?folderId=1060551

**Comment by RajuJeelaga** [comment]
I have approved this ticket ~ Ahmed.

**Comment by MohammedKaludi** [comment]
RTL menu is not working in Swift menu as well.
Waiting for the confirmation from @daanishd.

**Comment by MohammedKaludi** [comment]
Told the users to update the plugin to the latest version.

Closing the ticket for now. Will reopen the ticket if the issue persists.
