### ISSUE TITLE
Possibility Rewrite Rule issue

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1933]
the Homepage 2ndPage and other Categories and Tag 2ndPages are same in the /amp, and when we add the ?amp its working fine.

Ref:  https://secure.helpscout.net/conversation/547138098/23609?folderId=1914712

**Comment by Sejiro-Hiko** [comment]
The Issue has already been fixed in the previous update in ticket #2023 and working fine on the users end as well.

**Comment by MohammedKaludi** [comment]
:+1:
