### ISSUE TITLE
Add {author_name} in Advance Analytics

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1936]
Add {author_name} in Advance Analytics

Ref: https://secure.helpscout.net/conversation/550142002/23767?folderId=1060551

**Comment by MARQAS** [comment]
Updated Tutorial: https://ampforwp.com/tutorials/article/add-advanced-google-analytics-amp/

**Comment by MohammedKaludi** [comment]
:+1:
