### ISSUE TITLE
Improvement in AMP take over

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1939]
Not showing 404 error page even wrong URL is used while AMP take over option is enabled.

Ref:https://secure.helpscout.net/conversation/549617427/23740/

**Comment by Frenchomatic** [comment]
Any quick fix?  It is causing me some trouble in google's console.

**Comment by beingsmart3** [comment]
Ref:  https://wordpress.org/support/topic/serious-amp-takeover-problem/

**Comment by Frenchomatic** [comment]
I have fixed this by hacking redirect.php so even in AMP takeover, 404s go to the normal 404 page.  Not a nice hack either. Needs to be done properly.

**Comment by Sejiro-Hiko** [comment]
Fixed in #2042 @Frenchomatic can you please pull the #2042 and see if things are working on your end.

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic can you also test this #2054 spaces issue and let me know.

**Comment by MohammedKaludi** [comment]
Closing this ticket. Continued to #2042
