### ISSUE TITLE
PHP 7.0 compatibility issues

### ISSUE THREAD

**Issue by nicholasgriffintn** [ahmedkaludi/Accelerated-Mobile-Pages#194]
I found these errors and warnings with the PHP Compatibility Checker plugin, just thought that I would report them.

`FILE: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/Accelerated-Mobile-Pages/includes/options/redux-framework/inc/browser.php
-------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------
 113 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
-------------------------------------------------------------------------------------------------------------------------------------

FILE: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/Accelerated-Mobile-Pages/includes/options/redux-framework/inc/fields/editor/field_editor_c.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/Accelerated-Mobile-Pages/includes/options/redux-framework/inc/validation/preg_replace/validation_preg_replace.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 30 | ERROR | preg_replace() - /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------`

**Comment by khaledMohammed000** [comment]
Thanx @nicholasgriffintn  Ill look into it :)

**Comment by khaledMohammed000** [comment]
@MohammedKaludi @ahmedkaludi I messaged the Redux Framework guy and he had to say that these are resolved in the present current version of Redux

Please have a look at this Issue i created with them : https://github.com/reduxframework/redux-framework/issues/3167
