### ISSUE TITLE
Use POT file method of Translation option issue

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1941]
When we enable Use POT file method of Translation option the text is getting attached to the category.

Ref:  https://secure.helpscout.net/conversation/551394172/23835?folderId=1060551

see this screenshot:  http://take.ms/bRlpK

**Comment by MohammedKaludi** [comment]
@MARQAS above spacing fix is looking good. 
While reviewing I found some strings that are untranslatable. Please connect it to proper functions

- [ ] components/breadcrumb/breadcrumb.php Line no: 182 and 202
- [ ] components/post-pagination/post-pagination.php Line no: 14 and 15
- [ ] design-1/elements/bread-crumbs.php Line no: 183 and 203
- [ ] design-2/elements/bread-crumbs.php Line no: 183 and 203
- [ ] design-3/elements/bread-crumbs.php Line no: 183 and 203
- [ ] features.php Line no: 4032 and 4033

**Comment by MohammedKaludi** [comment]
:+1:
