### ISSUE TITLE
Issues with 3rd party Redux builds

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1942]
- [x] The welcome is being attached to all the Redux's builds: http://take.ms/h8NPP

- [x] Since a 3rd party theme (Mobius) has customized the default switch to customize the design, it conflicts with our switch buttons. Results in no button in both applications: http://take.ms/DylwS

Ref: https://secure.helpscout.net/conversation/550722982/23797/

**Comment by MohammedKaludi** [comment]
:+1:
