### ISSUE TITLE
"Save Module" button of AMP page Builder not displaying in OSX  and in Safari

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1943]
"Save Module" button of AMP page Builder not displaying in OSX  and in Safari.

REF: https://secure.helpscout.net/conversation/551712758/23855?folderId=1060551

**Comment by ansaritalha** [comment]
Ref: https://secure.helpscout.net/conversation/560883704/24504?folderId=1060551

**Comment by githubjabbar** [comment]
Ref: https://secure.helpscout.net/conversation/572123413/25420?folderId=1680011

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
