### ISSUE TITLE
structured markup json

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1945]
It is more efficient to put this just before the closing boy tag as opposed to putting it in the head.

**Comment by ahmedkaludi** [comment]
@Frenchomatic if that doesn't effect on the tracking then sure,

**Comment by Frenchomatic** [comment]
ok - just a, idea. It shouldn't break anything as it is just json being moved. Looking at why AMP fails in page speed regarding 'prioritize visible content'. You can have an empty AMP page with only one single bit of text and it fails that test. If you just have an image and no text it doesn't fail - weird. Nothing really to do wit the plugin.

**Comment by Frenchomatic** [comment]
There is an easy way to do this for those using genesis and can probably be put even lower after the footer but this works for me - 

```
add_action( 'amp_post_template_footer', 'amp_schema_special'); 

function amp_schema_special() { 
genesis_footer_scripts();
}
```

**Comment by MohammedKaludi** [comment]
:+1:
