### ISSUE TITLE
?nonamp=1 doesn't have redirect

### ISSUE THREAD

**Issue by ditad** [ahmedkaludi/accelerated-mobile-pages#1947]
I have enabled AMP for my mobile users, but now Google is crawling ?nonamp=1 urls. These urls have no redirect to the proper url.

**Comment by ahmedkaludi** [comment]
@ditad By default we have /amp/ as the main urls. This might be a conflict due to a another plugin. can you share a list of all the plugins that you have active?

**Comment by MohammedKaludi** [comment]
not working, it is looping,

**Comment by MohammedKaludi** [comment]
also, session is not destroying.

**Comment by Zabi09** [comment]
I have tested a lot on my localhost and also on others but the option is working perfectly on my end,

**Comment by MohammedKaludi** [comment]
Still looping and do not use `$_REQUEST['*]`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b8723d39798f0f19f550d6c732137d4b4de8fe07#diff-ab576767b896423d184ddafe2ede2310R240

**Comment by pegazee** [comment]
Need to discuss this with @MohammedKaludi

**Comment by MARQAS** [comment]
@pegazee https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1947#issuecomment-445443437
Check `ampforwp_view_nonamp` function and improve the code likewise

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
append is incorrect.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4fa3280686046839dbb694ec1603257ff068b2f9#diff-ab576767b896423d184ddafe2ede2310R266

**Comment by MohammedKaludi** [comment]
also change the function name: Too big
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ef65fec74d6724849bde175d04532551af4f6fa8#diff-ab576767b896423d184ddafe2ede2310R265

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Let's check this one: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2537

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.97.33, closing the ticket.
