### ISSUE TITLE
Add Meta Description

### ISSUE THREAD

**Issue by Chekki** [ahmedkaludi/Accelerated-Mobile-Pages#195]
Hi,

I am missing the meta description within your great plugin.

For better understanding what I mean:
Please see metadata on [this page](https://search.google.com/search-console/amp?id=EaOAEpBSGSV0LnC38S1Xag). Here is the result in SERP´s:

[Picture 1
](http://fs5.directupload.net/images/161110/or9rg4br.png)

And that is the metadata of the AMP for WP Plugin:

[Metadata of AMP for WP](https://search.google.com/search-console/amp?id=UZEKOZfi2cRDmdTrYd-9ag)

And this is the screenshot of SERP´s of AMP for WP Plugin:

[Picture 2](http://fs5.directupload.net/images/161110/eu2uuk4r.png)

Your plugin would be much better if it could provide metadescription or even more metadata. Is there any possiblity to add it? Or even to access on the yoast metadata?

Best regards,

Chekki

**Comment by khaledMohammed000** [comment]
@Chekki Done you will receive this feature in our next update
