### ISSUE TITLE
Allow HTML in footer section of translation panel in design 3

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1950]
Allow HTML tags in the footer section of the design 3.

I’d like to be able to format the text better in the footer in design three. The text is currently placed in the Footer section of the translation panel and shows fine, but it strips all HTML tags.

Ref: https://wordpress.org/support/topic/translations-footer-html/

**Comment by MARQAS** [comment]
Added in master

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
