### ISSUE TITLE
Design 2 - meta info producing a block of empty html

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#1954]
<div class="amp-wp-article-header ampforwp-meta-info hide-meta-info "> <div class="amp-wp-content post-title-meta"> <ul class="amp-wp-meta amp-meta-wrapper"> <div class="amp-wp-meta amp-wp-byline"> </div> </ul> </div> </div>

This empty block of html should not be showing in the response on pages if meta info is set to off for pages or it is set to off for posts. 

The `$redux_builder_amp['meta_page']` should be tested around the main `<div class="amp-wp-article-header ampforwp-meta-info` to stop it printing an empty block of code.

**Comment by Frenchomatic** [comment]
see #1969

**Comment by MohammedKaludi** [comment]
:+1:
