### ISSUE TITLE
Custom Post and Custom Taxonomies Archives not working in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1957]
Custom Post and Custom Taxonomies Archives not working in /amp but its working fine on /?amp.

Ref:  https://wordpress.org/support/topic/custom-post-and-custom-taxonomies-archives-not-working/#post-10133295

**Comment by daanishd** [comment]
one more Request:  https://secure.helpscout.net/conversation/556023975/24167?folderId=1060551

**Comment by Sejiro-Hiko** [comment]
This Issue is particular for the Swift theme
https://secure.helpscout.net/conversation/552710422/23928?folderId=1680011

**Comment by MohammedKaludi** [comment]
Rewrite rules are still pending for custom taxonomies

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by akmal10** [comment]
Hi
Mine still not working with /amp only working on /?amp
Please advise.
