### ISSUE TITLE
The attribute ‘date’ may not appear in tag ‘time’.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#196]
We need to fix this validation issue: https://wordpress.org/support/topic/the-attribute-may-not-appear-in-tag-a/#post-8418988

REPORTED: https://wordpress.org/support/topic/the-attribute-may-not-appear-in-tag-a/#post-8418988

**Comment by khaledMohammed000** [comment]
#203
