### ISSUE TITLE
Table Styling in Swift

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1961]
Table is not Responsive in Swift

REF: https://secure.helpscout.net/conversation/553536242/23977?folderId=1060551

**Comment by beingsmart3** [comment]
One more Ref:  https://secure.helpscout.net/conversation/537278369/22810?folderId=1914712

**Comment by RajuJeelaga** [comment]
I have approved this ticket ~ Ahmed.
