### ISSUE TITLE
wp recipe maker outputs wrong incorrect json

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1963]
If we remove "<![CDATA[{" then the output detects recipe perfectly.

http://monosnap.com/image/JL3OHd9rgBLS5Mb7AbVHxfitCcWONQ/

**Comment by ahmedkaludi** [comment]
#1453 Same issue.

**Comment by ahmedkaludi** [comment]
**Note**
This was fixed by ajeet as I instructed him but we still need to test the output of the structured data code.
Consult with me, when it's done. I will review it.

**Comment by Sejiro-Hiko** [comment]
Tested on my end and works as expected

**Comment by MohammedKaludi** [comment]
:+1:
