### ISSUE TITLE
Need to create an option of sticky post on homepage in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1965]
When the user has a sticky lengthy informative post on the homepage in Non-AMP but in AMP it's coming like blog view.

Ref:  https://wordpress.org/support/topic/how-to-make-a-sticky-post-on-homepage-in-mobile/

**Comment by Sejiro-Hiko** [comment]
Currently, we do have a filter to show the full content of the sticky post apply_filters('ampforwp_modify_index_content', $content, $excerpt_length ); which you can use by add_filter in your theme’s functions .php

**Comment by MohammedKaludi** [comment]
:+1:
