### ISSUE TITLE
Extending Default Gallery designs 

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1968]
Default Gallery should be embedded into AMP with 3 to 4 designs 

Ref:  https://secure.helpscout.net/conversation/552669392/23923?folderId=1914712

**Comment by ahmedkaludi** [comment]
This is related to the gallery that is inserted with in the Visual editor through shortcode.

- [ ] 1. Make the Gallery shortcode output modifiable so that Frontend team can give multiple designs for the Gallery.

- [ ] 2. Give designs for the Gallery which can be selected from the Options panel

**Comment by MohammedKaludi** [comment]
@ahmedkaludi after you done with the checking please assign it back to me.

**Comment by MARQAS** [comment]
It seems that All the code related to Gallery has been moved to class-amp-gallery-embed, is it intentional? 
Can we do it by making minimal changes in that file? @santosh8793 @MohammedKaludi

**Comment by MohammedKaludi** [comment]
Keep it as it is, as we are not planning to update the core any time soon, so we can keep it there and just note it down in vendor changelog file.

**Comment by ahmedkaludi** [comment]
REVIEW:

- [ ] Discuss the code suggestion by @MARQAS 

- [ ] Carousel with Thumbnail is not working. The thumbnails are not showing, check and fix this @santosh8793

**Comment by ahmedkaludi** [comment]
**REVIEW**

- [ ] I selected Thumbnail from the gallery settings: http://take.ms/5yhBt - but it still shows the full thumbnail in the output. http://take.ms/GpRnr

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
