### ISSUE TITLE
Issues reported by @frenchomatic

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#1969]
Issues reported by @frenchomatic:

1. AMP takeover - genesis meta title doesn't get rendered because features.php function is now incorrect. I provided a hack on github to demonstrate the problem. is_home() no longer works with AMP takeover.
2. An extra space is put in the h1 tag because in design 2, title.php needs the php tags to be placed correctly around the html. This was solved a few versions back but someone has recoded it incorrectly again for the last 2 versions at least.
3. In AMP takeover, there is no way to generate a proper 404 page
4. In AMP takeover, /amp/ doesn't 301 redirect to / or at least throw a 404.
5. noindex, noarchive as defined by yoast or genesis doesn't get rendered.
6. meta info in design 2 gets rendered with a lot of empty html when it is set to off. A test on $redux_builder_amp['meta_page'] is needed on the outer div too.

**Comment by Frenchomatic** [comment]
Marqas - in the release this afternoon 9.5.8.1 - point 4. It is now doing 302 redirect. This should be a 404 really. The page doesn't exist. You can't account for people that may have had /amp/  before like me so using a 301 would be technically incorrect too - play safe with a 404.

**Comment by Frenchomatic** [comment]
Point 6 still remains iDesign 2 - meta info producing a block of empty html #1954 but Serious AMP takeover problem - title tags are incorrect #1955 can be closed as it is solved in the latest version.

**Comment by MohammedKaludi** [comment]
:+1:
