### ISSUE TITLE
Trying to get property of non-object in /var/www/html/wp-content/plugins/accelerated-mobile-pages/includes/welcome.php

### ISSUE THREAD

**Issue by manniamc** [ahmedkaludi/accelerated-mobile-pages#1970]
When i was trying to do AMP installation wizard which helps setup the Basic AMP and get started immediatly. As a NEW USER i was getting this notice error.
Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/accelerated-mobile-pages/includes/welcome.php on line 343

![screen shot 2018-04-04 at 6 47 36 pm](https://user-images.githubusercontent.com/21311054/38309992-0a3b75b2-3839-11e8-9007-17c21f6b5eec.png)

**Comment by MohammedKaludi** [comment]
Hey @manniamc,

Thank you for reporting the issue, I have added this ticket to the next milestone. We will fix it in our next update cycle.

Mohammed Kaludi

**Comment by MohammedKaludi** [comment]
:+1:
