### ISSUE TITLE
ADVANCED INDEX & NO INDEX OPTIONS

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#1978]
Need to create a description for the ADVANCED INDEX & NO INDEX OPTIONS.

Ref:  https://secure.helpscout.net/conversation/555511523/24133?folderId=1060551

**Comment by MohammedKaludi** [comment]
Enable this option and it should work : http://take.ms/w1voA

**Comment by MohammedKaludi** [comment]
:
