### ISSUE TITLE
plain permalink issue

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#1985]
In plain permalink /amp is added at the end of URL.

e.g :https://www.pnliafi.com.ar/?p=17025/amp/

**Comment by Sejiro-Hiko** [comment]
Tested on user's end as well as on my end working as expected

**Comment by MohammedKaludi** [comment]
@ahmedkaludi can you please check?

**Comment by MohammedKaludi** [comment]
:+1:
