### ISSUE TITLE
Add the Feature of Duplicating the Element or Row in the AMP Page Builder

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#1986]
Add the feature of Duplicating the Elements or Rows in the AMP Page Builder.

REF: https://wordpress.org/support/topic/duplicate-elements-in-builder/

**Comment by ajeetku** [comment]
TESTING STEPS:
After **Module** Duplicate: need to check **cell_id**
After **Row** Duplicate : need to check **id** & **cell_id**

**Comment by MohammedKaludi** [comment]
👍
