### ISSUE TITLE
issue with <!--nextpage-->

### ISSUE THREAD

**Issue by Tymvie** [ahmedkaludi/accelerated-mobile-pages#1988]
Hello,
The `ampforwp_modify_the_content` filter allows to modify content of a current page when the Swift theme is used. When other themes are used, this filter only allows to modify content of all pages together.
Is it possible to unify that behavior and make it work the way it works with the Swift theme?
Thanks

**Comment by Tymvie** [comment]
@Sejiro-Hiko hi,
yes, and this was fixed.
I found some problems while testing: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2253

**Comment by Sejiro-Hiko** [comment]
@Tymvie 

I'll try to recreate the issue you mentioned in the #2253 and will look into it

**Comment by MohammedKaludi** [comment]
:+1:
