### ISSUE TITLE
Date Format should change as per locality

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#1991]
Date Format should change as per locality

Ref:  https://secure.helpscout.net/conversation/554345090/24035/?folderId=1914712

**Comment by ahmedkaludi** [comment]
@MARQAS @Sejiro-Hiko Consult with me before starting on this one.

**Comment by Sejiro-Hiko** [comment]
We already got the option for it.
Ref: http://take.ms/57VvZ

**Comment by Sejiro-Hiko** [comment]
USER: Thanks a lot. I just did what I had suggested earlier and ran a grep over my plugins and themes. The sung shows up in my child theme.

**Comment by MohammedKaludi** [comment]
:+1:
