### ISSUE TITLE
Swift theme homepage (Non-AMP) image resizing issues in Mobile version

### ISSUE THREAD

**Issue by beingteja** [ahmedkaludi/accelerated-mobile-pages#1992]
Swift theme (Non-AMP) page mobile version home image is not resizing as per screen size (check the screenshots attached)
![screenshot_20180409-161317](https://user-images.githubusercontent.com/23118284/38494616-3592559e-3c14-11e8-9e12-cebaefc9813b.jpg)

**Comment by MohammedKaludi** [comment]
:+1:
