### ISSUE TITLE
Custom post type categories not showing in amp page builder 

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#1993]
Custom post type categories not showing in amp page builder categories. 

Ref: https://secure.helpscout.net/conversation/534940119/22605?folderId=1060551

**Comment by setxnow** [comment]
when trying to add categories element in a page using amp page builder .... only standard categories show up as choices... not the custom post type "items" that i use....also adsense ads not showing

**Comment by setxnow** [comment]
user: ampadmin
pass: ampadminpass

also 500 error is occurring again

**Comment by setxnow** [comment]
any luck?

**Comment by MohammedKaludi** [comment]
There are some UI problems.

1. If we change the Post type from the drop-down. http://take.ms/R7hc0 then as we are making the ajax call. there needs to some indication that we are doing an ajax call and user is supposed to wait.

2. When the ajax call is being made, the old values are still present in the drop down that and then automatically changes with the new value(at this time ajax data is available). 

3. connection not establish Alter is poping up, in some cases also needs to rename the alert with a better message. Like: Posts not found, please try again.

These issues must be addressed before we can merge this commit in the master.

**Comment by Zabi09** [comment]
And also the recent posts are not appearing when the custom post type is selected and showing blank

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
