### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by gputignano** [ahmedkaludi/accelerated-mobile-pages#1999]
I installed my site on Siteground and installed SG Optimizer cache plugin.
Now on frontend I get the error: 

`/home/myaccount/domains/ceglie5stelle.it/public/wp-content/plugins/sg-cachepress/class-sg-cachepress.php on line 315

Warning: Cannot modify header information - headers already sent by (output started at /home/myaccount/domains/ceglie5stelle.it/public/wp-includes/load.php:63) in /home/myaccount/domains/ceglie5stelle.it/public/wp-content/plugins/sg-cachepress/class-sg-cachepress.php on line 327`.

**Comment by ahmedkaludi** [comment]
@gputignano Those errors are coming from the sg-cachepress plugin. Has nothing to do with ours as far as I can see.

**Comment by gputignano** [comment]
I'm going to contact Siteground to solve.
