### ISSUE TITLE
oembed wordpress post renders as a full post in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2003]
When user embedding one of the Wordpress posts in another post, it renders correctly on the Desktop (i.e like an Embed) however on AMP it renders as a full post within that frame,

See this screenshot:  http://take.ms/LF2ze

Ref:  https://secure.helpscout.net/conversation/537278369/22810?folderId=1914712

**Comment by rohitdugar09** [comment]
Any update on this bug? It's affecting us too.

**Comment by grswawardekar** [comment]
Hey, any update on this?

**Comment by Nehanoesis** [comment]
Hey, Any update?

**Comment by ceejothomas** [comment]
We have been facing the same issue for long. Not just in AMP, but the same issue exists in facebook instant too but with a lesser severity. For each embed it show the logo of the site but no content will load. We need a fix urgently

**Comment by MohammedKaludi** [comment]
user `$wp->request` instead of `$_REQUEST`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7c3c02f8b44a65e74d73d9352ae404ef7182ced7#diff-ab576767b896423d184ddafe2ede2310R158

**Comment by Zabi09** [comment]
it was working fine with $_REQUEST but if we add $wp->request then it's not working

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by MohammedKaludi** [comment]
this will be pushed 0.9.97.37 on friday

**Comment by pegazee** [comment]
Pushed in 0.9.97.37
