### ISSUE TITLE
If we remove the selection from structured data then it should be removed

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2005]
http://take.ms/VnpI7

**Comment by Sejiro-Hiko** [comment]
`if ( isset( $post->post_type ) && $post->post_type == $post_type ) {
        		if ( empty( $redux_builder_amp['ampforwp-sd-type-'.$post_type.''] ) && $redux_builder_amp['ampforwp-seo-yoast-description'] == 0 ) {
					return;
				}
        		$metadata['@type'] = $redux_builder_amp['ampforwp-sd-type-'.$post_type.''];
        		return $metadata;
        	}`
This return of $metadata is only for the custom post type in the foreach post_type and the compatibility with others will not effect by it.

**Comment by MohammedKaludi** [comment]
:+1:
