### ISSUE TITLE
Search parameter issue in AMP Takeover

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2009]
The search field is getting blank in AMP takeover because it adding the parameter ?amp=1.

Ref:  https://secure.helpscout.net/conversation/559194348/24403?folderId=1060551

**Comment by Sejiro-Hiko** [comment]
#1990 Same Issue.

[Fixed] https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/43b883529f2aec5723765645c235e5f9ec901c9b

**Comment by Natieli** [comment]
I have the same problem. Are we going to have a return soon? Search is an important resource on my site.

**Comment by MohammedKaludi** [comment]
@Natieli We are going to push this fix in the next update, that is on 1-May-2018 with Version no 0.9.86
and 
@Sejiro-Hiko  Fix working fine.
:+1:
