### ISSUE TITLE
AMP ads show twice

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#201]
This is really strange, but two users have reported this

1. https://wordpress.org/support/topic/what-this-future-error-means/#post-8431770
2. https://wordpress.org/support/topic/error-version-0-8-7-mandatory_amp_tag_missing_or_incorrect/#post-8431766

**Comment by khaledMohammed000** [comment]
this is not our fault http://take.ms/AsXYz 

if we have that installed we get a warning that we have 2  Scripts pointing to the same thing
