### ISSUE TITLE
Sorting option for Repeater field for Pagebuilder 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2014]
Sorting option for Repeater field for Pagebuilder

**Comment by ajeetku** [comment]
Testing strategy
1. First create a repeater module: Add some data
2. Move to development branch
3. check Data is proper as previous and  sorting is working or not

**Comment by MohammedKaludi** [comment]
Code and Functionality wise is perfect.

@ahmedkaludi  Need to test the UX.

**Comment by MohammedKaludi** [comment]
@jasthilokesh some minor improvements required, please discuss it with @ahmedkaludi

**Comment by MohammedKaludi** [comment]
Color of the Marker for the first element is white and other elements are black

![Screen Shot 2019-12-10 at 6 56 17 PM](https://user-images.githubusercontent.com/16618009/70533310-db761680-1b7e-11ea-975a-6c4789afb68c.png)

**Comment by ahmedkaludi** [comment]
Tested and moved to ready

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
