### ISSUE TITLE
Fatal Error after updating the plugin from 0.9.73 to 0.9.83 version

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2017]
Fatal error: Cannot redeclare contentHtml() (previously declared in /home/nooitme6/public_html/piekerpoli.nl/wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/contents.php:62) in /home/nooitme6/public_html/piekerpoli.nl/wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/contents-module.php on line 182

Ref: https://secure.helpscout.net/conversation/521251024/21516?folderId=1680011

**Comment by ahmedkaludi** [comment]
We just need to test this one.

**Comment by MohammedKaludi** [comment]
:+1:
