### ISSUE TITLE
Swift featured image not getting Full screen

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2019]
Re-occure the issue
When we add image in content and enable get featured image from content.
Result: In single page , image is not showing full screen  
Ref: `https://secure.helpscout.net/conversation/558708654/24327?folderId=1060556`
To resolve add following code in featured_image component
`$amp_html = preg_replace('#sizes="(.*)"#', "layout='responsive'", $amp_html);`

Sample image: Added in link

https://myweightlossquest.net/wp-content/uploads/2019/03/Diastasis-Recti-In-Men.jpg

**Comment by MohammedKaludi** [comment]
:+1:
