### ISSUE TITLE
AMP analytics shows more than once

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#202]
check:https://validator.ampproject.org/#url=https%3A%2F%2Fwww.meilleursgadgetsdunet.com%2Frampe-acces-chien-voiture-trixie-petwalk%2F%3Famp

**Comment by khaledMohammed000** [comment]
@ahmedkaludi please ask this guy give the list of plugins he uses I think some plugin for google analytics is adding this line

**Comment by khaledMohammed000** [comment]
This is with Glue and AMp social share, we need to fix it but later on (added by AHmed)

**Comment by MohammedKaludi** [comment]
Fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/370
