### ISSUE TITLE
Social media icons settings not getting saved

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2020]
the issue with the social media settings on design 1 to 3 not saving to the page but the default settings of icons are visible on the pages.

Ref:  https://wordpress.org/support/topic/social-media-icons-settings-not-saving-on-page/

**Comment by Sejiro-Hiko** [comment]
It's not related to the issue but the master does not have the #1996 Fixed and tested on my end with W11 working perfectly fine

**Comment by MohammedKaludi** [comment]
:+1:
