### ISSUE TITLE
Call now button has disappeared in swift theme in new version

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2021]
Call now button has disappeared in swift theme in new version

Screenshot: http://take.ms/T1aUTW

Ref: https://secure.helpscout.net/conversation/560758358/24498?folderId=1680011
Ref: LocalHost

**Comment by ahmedkaludi** [comment]
@Zabi09 has some ideas about it. Let me know if you are unable to re-create this.

**Comment by MohammedKaludi** [comment]
:+1:
