### ISSUE TITLE
Author 'A' page has other authors posts on it's page from page 2 and above which result in non-existing author pages. 

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2023]
Author 'A' page has all the posts of other authors whereas it should've only author 'A' posts. 

Ref: https://secure.helpscout.net/conversation/560805846/24501?folderId=1060551

**Comment by beingsmart3** [comment]
one more
Ref:  https://secure.helpscout.net/conversation/564532317/24788?folderId=1060556

- [ ] Author

- [ ] Category

- [ ] Tags

**Comment by daanishd** [comment]
One more user has this kind of issue but on the Category page.

Ref: https://secure.helpscout.net/conversation/564947918/24823?folderId=1060551

**Comment by castroalves** [comment]
I have the same problem for weeks. Do you have an estimate to solve this issue?

**Comment by MohammedKaludi** [comment]
@castroalves we are planning to fix it and push the update on 1st-May-2018.
The deadline for this milestone is 30th-April-2018

**Comment by MohammedKaludi** [comment]
@castroalves We have just pushed an update 0.9.86.7 and fixed the pagination issue.

Please update to the latest version and do let me know your feedback.

Mohammed Kaludi
