### ISSUE TITLE
pagebuilder Improvement

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2024]
1. Row Setting option: On background image selection, If we export and put on other server its not working (In front). Because in json there store only ID of image
[Resolve]: Add image_data when we select image in row-setting

2. Minify node_modules files

**Comment by ajeetku** [comment]
1. 7ac1837 option is already created and it's working

**Comment by MohammedKaludi** [comment]
:+1:
