### ISSUE TITLE
Improvement of the License key activation

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2026]
- [x] Correct All the Slugs and make sure it should match with the GITHUB Repo. (Ahmed)

- [x] Zip file should match those slugs. (Ahmed)

- [ ] Second page of all extensions (NEED to discuss)

- [x] After activating the license key, still, need to refresh so the license key should be submitted in the plugin. (Ajeet)

- [x] After activating the license key, but still it shows to enter. (Ajeet) [Not Reoccured]

- [x] When we click on Enter license key, it's redirecting to Fix my error settings in AMP panel (Correct Slug)
- [x] Minimization or hide of other tabs Except First 3 "JS Code will run only when 'amp_options' page available" [Checked with mobius]
 - [x] Remove JS codes of Second page (Which comes in "All Extension") add it on Option panel branch[Ajeet]
 - [ ] Detect folder with our plugins "which contain some Extra text" [Ajeet] [SKIP]

 - [ ]  Need to Mention "Licence key is not mandatory"

**Comment by ahmedkaludi** [comment]
reviewed and works as expected. The unfinished tasks mentioned above will be done with future updates.
