### ISSUE TITLE
Gif in content + Lightbox feature throws validation issue.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2032]
just insert a Gif in the content and enable lightbox for images feature. You will see a validation issue. 

REF: https://secure.helpscout.net/conversation/562116899/24613/?folderId=1060554

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Sejiro-Hiko** [comment]
If there are no Images on pages then the following error will pop up on archive pages.
The tag 'amp-image-lightbox' requires including the 'amp-image-lightbox' extension JavaScript.
