### ISSUE TITLE
Improvement in Excerpt on small screen option

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2034]
while the Excerpt on small screen option is enabled its shows excerpt in the related post only on the homepage (if excerpt in related post option is enabled)

Connect it that way so it should show an excerpt in a related post on a single page too.

Ref:https://wordpress.org/support/topic/related-posts-excerpt-on-small-screens-possible/

**Comment by MohammedKaludi** [comment]
:+1:
