### ISSUE TITLE
aq_resizer.php is calling an undefined function WP_Image_Editor_Imagick::get_error_message()

### ISSUE THREAD

**Issue by devfunsho** [ahmedkaludi/accelerated-mobile-pages#2037]
I discovered the following error in my PHP error log

HP Fatal error:  Uncaught Error: Call to undefined method WP_Image_Editor_Imagick::get_error_message() in /home/web/wp/public/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php:161
Stack trace:
#0 /home/web/wp/public/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php(262): Aq_Resize->process('https://www.bel...', 346, 188, true, false, true)
#1 /home/web/wp/public/wp-content/plugins/accelerated-mobile-pages/components/loop/loop.php(319): ampforwp_aq_resize('https://www.bel...', 346, 188, true, false, true)
#2 /home/web/wp/public/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/swift/index.php(47): amp_loop_image(Array)
#3 /home/web/wp/public/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(433): include('/home/web/wp/pu...')
#4 /home/web/wp/public/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(137): AMP_Post_Template->verify_and_include('/home/web/wp/pu.. in /home/web/wp/public/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php on line 161

**Comment by MohammedKaludi** [comment]
More detail about the same issue is here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2038

**Comment by MARQAS** [comment]
Hi @devfunsho ,

Can you add the changes which I have done and check? #c96937e

**Comment by MohammedKaludi** [comment]
@devfunsho waiting for your reply.

**Comment by MohammedKaludi** [comment]
:+1:
