### ISSUE TITLE
Blog posts doesn't have " continue reading/ Read more "

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2039]
Ref: https://secure.helpscout.net/conversation/563031738/24664?folderId=1964340

**Comment by markifornia** [comment]
@daanishd did you ever find a fix for this? I'm running into the same issue. 

-Mark

**Comment by Sejiro-Hiko** [comment]
@markifornia are you still facing this issue? please do let us know.

**Comment by MohammedKaludi** [comment]
Duplicate ticket #2273
