### ISSUE TITLE
GDPR Compliancy

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2040]
Implement GDPR Compliancy

**Comment by TDESK** [comment]
Yeah we need it in Europe very soon or I we have to change the plugin 👎

**Comment by TDESK** [comment]
Sounds really good! Thank you!

Viele Grüße,
Torben

—
Torben Simon Meier
Founder, Managing Director &
Chief Operating Officer

0049 251 1498 2001
torben@raidboxes.de

raidboxes.de | WP-Magazin
Facebook | Twitter | Instagram

RAIDBOXES GmbH | Friedrich-Ebert-Straße 7 | 48153 Münster, DE
Geschäftsführer: Torben Simon Meier, Johannes Benz
HRB 16184 | Amtsgericht Münster | USt-IdNr. : DE306895091

**Comment by MARQAS** [comment]
Tested and working properly on my end 👍

**Comment by MohammedKaludi** [comment]
Facebook and disqus comments are not connected.

**Comment by MohammedKaludi** [comment]
also amp-instagram is showing posts even Rejected selected in Consent.

**Comment by MohammedKaludi** [comment]
@ahmedkaludi need your help on styling the GDPR Form.
