### ISSUE TITLE
javascript console error

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2045]
In console two error is showing when Divi theme is used.

1-type error: $ is not a function (screenshot: http://take.ms/Bqaui)

2- type error: can not read property 'hasClass' (screenshot: http://take.ms/zym8E)

Ref: https://secure.helpscout.net/conversation/558510015/24317?folderId=1914716

**Comment by Sejiro-Hiko** [comment]
The Issue was from the User's child theme JS file where the jQuery wasn't getting defined and caused our options panel to break.

Fixed on user's end.

**Comment by MohammedKaludi** [comment]
:+1:
