### ISSUE TITLE
Advanced CSS is not loading because the files are with hosting path

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2046]
It's a rare use case but happened to many users, It's ready to re-occur at: https://secure.helpscout.net/conversation/543436160/23370/?folderId=1680011

**Comment by MARQAS** [comment]
User changed the directory from wp to app due to which the js and css files of vendor extensions were unable to load. So I changed the URL to make it work properly

**Comment by ahmedkaludi** [comment]
👍
