### ISSUE TITLE
When 'Structure Data for WP' plugin active, Schema type in Structure section should hide

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2049]
When "Structure Data for WP" plugin active, Schema type in Structure section should hide & also take the schema type from the "Structure Data for WP" plugin, not from the core plugin.
Screenshot > http://take.ms/ibNaS

**Comment by MohammedKaludi** [comment]
@pegazee http://take.ms/7pa1I this part is still missing
