### ISSUE TITLE
Post meta UI issue

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#205]

**Comment by ahmedkaludi** [comment]
![photo_2016-11-14_09-59-17](https://cloud.githubusercontent.com/assets/16532359/20253394/14b8590a-aa51-11e6-86f0-611ee9d2d8ca.jpg)

**Comment by khaledMohammed000** [comment]
https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/issues/191

https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/issues/192
