### ISSUE TITLE
Space issue reported by @frenchomatic

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2054]
Similar problem in pages / posts. In index.php and archive.php – spaces are being inserted into h1 and h2 tags. Only looked at design 2. Please fix next update.

`<h1 class="page-title"><?php echo $blog_title ?>SPACE</h1>`
and 
`<h2 class="amp-wp-title"> SPACE <a href="<?php echo esc_url( $ampforwp_amp_post_url ); ?>"> <?php the_title(); ?></a></h2>
`

Ref:  https://secure.helpscout.net/conversation/566464046/24939?folderId=1060551

**Comment by Frenchomatic** [comment]
yes that looks better. You obviously saw it. Also exists in archive.php and in tittle.php

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic can you please test them again...and I've tagged you on other ticket related to 404 issue #2042 please see to it also.

thanks

**Comment by Frenchomatic** [comment]
Yes - on design2, H1s and H2s no longer have spaces. Well done.

**Comment by Frenchomatic** [comment]
The edited files for removing space do not seem to appear in the latest version today - 9.8.5.7 ???

**Comment by MohammedKaludi** [comment]
@Frenchomatic Yes, this code is not been pushed yet, it will be pushed on 1st-May-2018 and the version number of the plugin would be 0.9.86

**Comment by Frenchomatic** [comment]
OKE doke. You have to get up early to catch me out LOL. I will wait until that version before doing.

**Comment by MohammedKaludi** [comment]
:+1: Spaces are removed from all the areas.
