### ISSUE TITLE
Space issue reported by @frenchomatic #2054

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2055]
Similar problem in pages / posts. In index.php and archive.php – spaces are being inserted into h1 and h2 tags. Only looked at design 2. Please fix next update.
`<h1 class="page-title"><?php echo $blog_title ?>SPACE</h1>`
and
`<h2 class="amp-wp-title"> SPACE <a href="<?php echo esc_url( $ampforwp_amp_post_url ); ?>"> <?php the_title(); ?></a></h2>`

**Comment by MohammedKaludi** [comment]
Duplicate ticket 
More here: #2054
