### ISSUE TITLE
Filter in components of AMP theme framework

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2057]
Ref: https://wordpress.org/support/topic/filter-amp_loop_image/

**Comment by retroriff** [comment]
These filters will be very useful for AMP theme developers. 

I would suggest loop content to be filtered. That would allow us to exclude some categories or adding post_types to the loop.

Thanks.

**Comment by Frenchomatic** [comment]
I noticed that on blog pages and archives that the images in design 2 were not responsive. Instead there is a use of thumbs where a fixed size can be set from the admin panel or it just defaults. Having responsive images in the loop would allow better designs to be made. I vote for that.

**Comment by MohammedKaludi** [comment]
Sure, we will add filters so developers can modify the code according to their usage.

**Comment by MohammedKaludi** [comment]
FIlter added to modify Image Attributes in AMP Theme Framework called "ampforwp_query_args" 
and as @retroriff asked, we already have the a filter to modify the WP_Query called "ampforwp_query_args"

Filter is added and now can be modified according the use case.
👍

**Comment by retroriff** [comment]
Great, thanks!
