### ISSUE TITLE
AMP Pagination 2nd page is rendering into the normal page

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2058]
AMP Pagination 2nd page is rendering into the normal page, not in the AMP but when we enable the /?amp it's rendering perfectly into the AMP.

Ref:  https://secure.helpscout.net/conversation/566921715/25003?folderId=1060551

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/567037574/25020?folderId=1914712

**Comment by beingsmart3** [comment]
one more
Ref:  https://secure.helpscout.net/conversation/567607796/25061?folderId=1060551

**Comment by beingsmart3** [comment]
one more issue
The same content is rendering into the subpages
Ref:  https://secure.helpscout.net/conversation/567837522/25083?folderId=1060551

**Comment by Zabi09** [comment]
One more - https://secure.helpscout.net/conversation/567777158/25078?folderId=673457

I have debugged the issue and found that it was caused because of Gravity Form plugin of the non-amp version in my case but don't know about the rest

**Comment by beingsmart3** [comment]
One more
It shows the wrong content of the category and it makes a lot of paginations that canonicals are giving 404 errors on search console.
https://secure.helpscout.net/conversation/568436643/25130?folderId=1914712

**Comment by MohammedKaludi** [comment]
All the above-mentioned tickets have been fixed, except for the first one and for it, we are creating a new ticket for it.
