### ISSUE TITLE
Show settings page if the AMP is enabled

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#206]
Show settings page only if the AMP is enabled otherwise don't display it. http://take.ms/OJRaI

**Comment by MohammedKaludi** [comment]
@khaledMohammed000 New issue came after the fix http://take.ms/BmkKP

Parent plugin is auto-activating and showing error. Please don;t auto activate the plugin, just check if parent plugin is active and then show the settings button.
