### ISSUE TITLE
amp-facebook-like extension is missing

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2061]
Exact URL - https://worldofwaltdotcom-staging.qzigwtj6-liquidwebsites.com/live-video-up-a-great-bird-show-at-disneys-animal-kingdom.html/amp

Credentials - https://secure.helpscout.net/conversation/564937851/24821?folderId=673452

**Comment by MohammedKaludi** [comment]
:+1:
