### ISSUE TITLE
smooth scrolling to anchors links  and jumping links within a page

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2062]
Clicking on button initiates a smooth scroll to the corresponding section within a page

Ref: https://secure.helpscout.net/conversation/564937851/24821?folderId=673452

**Comment by Frenchomatic** [comment]
Not sure AMP supports that (saw one stackflow answser saying it doesn't) - closest thing I have seen is this but it is not quite what you are asking 

https://ampbyexample.com/visual_effects/basics_of_scrollbound_effects/

**Comment by MohammedKaludi** [comment]
> @Zabi09 , @MohammedKaludi, Can we rename the subtitle information? like "Enable this option if you want smooth scrolling for jumping links"

 yes @pegazee rename it

**Comment by JayHoltslander** [comment]
````css
html {
  scroll-behavior: smooth;
}
````

**Comment by pegazee** [comment]
I've renamed the subtitle information. And moving this ticket to Approval section.  

@JayHoltslander, I didn't get your query, please elaborate in more detail.

**Comment by MohammedKaludi** [comment]
@pegazee @JayHoltslander suggested a CSS way to add smooth scroll behavior.

@Zabi09 we should implement this simple method suggested by Jay.

**Comment by MARQAS** [comment]
Can we use `amp_post_template_css` and add it only once without repeating it in every design?

**Comment by MohammedKaludi** [comment]
Add it via conditions like the previous one and not via hook

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e1911d8d607e77f3cfde76528caca2e9dcb90eb6#diff-e57ec3310984798e175233ae89a68fdbL468

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
