### ISSUE TITLE
Category is resirecting to random past

### ISSUE THREAD

**Issue by informacione** [ahmedkaludi/accelerated-mobile-pages#2064]
My categories are redirecting to random posts. Cant open website.com/category because link redirects to website.com/cateroy-pots

**Comment by Frenchomatic** [comment]
Difficult to help or comment without a url.

**Comment by Sejiro-Hiko** [comment]
Hi @informacione ,

Are you using takeover or category base remover? if not 
Please correct me if I'm wrong, do you meant to say that `domain.com/category/post-name/amp` is redirecting to the `domain.com/category/random-post/amp`

**Comment by Sejiro-Hiko** [comment]
@informacione  please respond before the deadline that is 20-June-18 otherwise we'll be closing this issue and we'll reopen it for some another milestone if we get the response from you.

**Comment by MohammedKaludi** [comment]
Closing the ticket due to lack of response.
