### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by jb510** [ahmedkaludi/accelerated-mobile-pages#2065]
1. get_categories()
wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php:3756

Trying to get property of non-object

Also note, I'm seeing this on ALL admin pages.  Whatever that is, seems like it doesn't need to outside of AMP's own admin pages, yes I'm seeing it globally... even on the front end.

**Comment by MohammedKaludi** [comment]
:+1:
