### ISSUE TITLE
View Non-AMP Version In the footer link has an error

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2066]
View Non-AMP Version In the footer link has an error, it's removing the amp from the URL

Ref:  https://secure.helpscout.net/conversation/567643792/25064/

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko need some code improvements.

**Comment by MohammedKaludi** [comment]
:+1:  Now Working as expected.
