### ISSUE TITLE
Option of button module in the Feature module in AMP page builder

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2068]
Need to create the option of button module in the Feature module in AMP page builder

Screenshot: http://take.ms/O05Uz
Ref: https://secure.helpscout.net/conversation/568474210/25131?folderId=673452

- [x] New Button field is created in the Feature Module and connected to options.

**Comment by ahmedkaludi** [comment]
@ajeetku You need to help out @RajuJeelaga with the repeater feilds area.

**Comment by MohammedKaludi** [comment]
:+1:
