### ISSUE TITLE
Can't modify social sharing options. 

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2069]
Ref: https://secure.helpscout.net/conversation/566851480/24990/

Customizing the social sharing options is not possible.

**Comment by Frenchomatic** [comment]
See the wordpress forum where you can define your own social icons and insert them wherever you like  using an action. 

https://wordpress.org/support/topic/amp-on-google-lighthouse/

**Comment by ahmedkaludi** [comment]
Waited long for the reply. We're closing this for now.

If you are also having the same issue, then please contact us via https://ampforwp.com/support/
