### ISSUE TITLE
Two additional feature suggestions

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2070]
Ref: https://secure.helpscout.net/conversation/568526314/25138?folderId=1060551

1) A widget that displays posts from another subsite into the front page of the multisite. Currently, only RSS feed widget does that and you might be able to easily customize and incorporate it into your theme. (And sell it as an extension plugin if you wish)

2) Enriching the author bio with social media buttons and, if possible, the option to put it below the title. Putting the author photo & twitter handle on the top could give prominence to the author of the article when the website is multi-author.

**Comment by Frenchomatic** [comment]
1. Not sure that is going to pass validation
2. That would be a customization specific to you - you can do using an action in functions.php
