### ISSUE TITLE
Genesis index, follow options not being rendered

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2071]
The standard options of noindex, nofollow, no archive are not being rendered in AMP takeover or mixed systems. Someone also needs to test yoast too in case this is the same issue. 

A more specific thing is that header and footer scripts per page are not being rendered in genesis either. - genesis_footer_scripts() and genesis_header_scripts(); . Putting thse in too would make life a lot simpler for those in AMP takeover.

**Comment by MohammedKaludi** [comment]
@MARQAS need to improve the code

**Comment by MohammedKaludi** [comment]
:+1:
