### ISSUE TITLE
Responsive IMG Support in Swift 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2073]
Responsive IMG Support in Swift : https://fargo1ife.com/

**Comment by ahmedkaludi** [comment]
Not working as expected. Here's what you can do.

1. Insert a large featured image 
2. insert an image in the visual editor
3. Enable "Convert to WP" option
4. Now, match the amp and Non-amp images.

You will find the issue with the images. If you are not able to understand then let me know, i'll show on my localhost.

**Comment by santosh8793** [comment]
we have tested this from our end, it is working fine

**Comment by ahmedkaludi** [comment]
**REVIEW:**
The big image in the content gets stretches badly: http://take.ms/r52yD

**Comment by santosh8793** [comment]
Ahmed here, I have checked this personally on this computer and it's working fine.

**Comment by ahmedkaludi** [comment]
I'll close this one for now, so we can focus on important ones.
