### ISSUE TITLE
Vuukle Comments feature on AMP

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2075]
API key is needed for the integration.
Documentation ref: http://docs.vuukle.com/vuukle-amp-integration/

example site ref: https://www.telugu360.com/achari-america-yatra-review/

**Comment by ajeetku** [comment]
Implemented and test on cloudwaysapps Server

**Comment by MohammedKaludi** [comment]
Need option to add custom ad id https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/83b1e6886f00fcde464391fa64bc828edf07f557#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7321

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Validation issue on frontend when enabling this feature
