### ISSUE TITLE
Integrate SPOT IM with AMP

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2076]
Integrate SPOT IM with AMP

https://github.com/SpotIM/spotim-integration-docs/blob/master/google-amp/README.md

**Comment by MohammedKaludi** [comment]
Fatal Error: http://take.ms/nIn2g

**Comment by MohammedKaludi** [comment]
Please don't use PHP_INT_MAX and add proper priority and why the same styling is added twice?

**Comment by MohammedKaludi** [comment]
:+1:
