### ISSUE TITLE
Incontent Related Post Issues

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2078]
- [x] In Design 3, the images are not showing up

- [x] In Swift, we need to improve the styling of it.

- [x] We need to connect Related posts image option with In-content related post image.

**Comment by MARQAS** [comment]
Resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7632b04

**Comment by MARQAS** [comment]
The styling of Swift in-content related posts will be done by @RajuJeelaga
