### ISSUE TITLE
Categories & Tags Links option only display in the swift theme, not in other designs.

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2079]
Categories & Tags Links option only display in the swift theme, not in other designs.

Ref:  https://wordpress.org/support/topic/tags-are-not-linked/#post-10224663

**Comment by Sejiro-Hiko** [comment]
working fine on my end asked the user to check it once more and reach us at support for further investigation if the issue persists...

**Comment by Sejiro-Hiko** [comment]
Issue resolved on the user's end as well

**Comment by MohammedKaludi** [comment]
Waiting for the user's confirmation.

**Comment by MohammedKaludi** [comment]
Users reply.

> Hi Mohammed,
yes, this one is fixed.
For the others I’m in mail-contact with your colleague 🙂
