### ISSUE TITLE
Structured data - blog posting page

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2080]
Looks like this one slipped through the net as it was mentioned a long time ago. On design 2 but probably the others too, a blog posts or archive type page gets incorrect structured data - shouldn't be of type webpage or article (depends on what is selected in admin panel).

**Comment by Sejiro-Hiko** [comment]
@Frenchomatic what if we treat the blog posts or archive type page as a "WebPage" ?

**Comment by Frenchomatic** [comment]
You already treat is a webpage but it is more than that. Normally you would have a separate markup for blog and then the blog posts would be listed within it. 

http://schema.org/Blog  and within it http://schema.org/BlogPosting

This is going to be a pain for sure.

**Comment by MARQAS** [comment]
@Frenchomatic, I understand the use case and I also tried to implement it but there were some problems.
It is difficult to change the HTML markup of our AMP and we don't want to run another query due to performance issues. 

Do you have any opinion or solution to this?

**Comment by Frenchomatic** [comment]
No I don't really. The problem is that AMP was not designed to accommodate archive type pages or categories. As you know its main purpose was for posts. This means you are a bit stuck and will need to use WebPage and assign a default image as you do.  You do this for the main blog posting page already but for categories it is broken ( a category page doesn't take webpage and use the default image - needs fixing.) 

The use of Webpage will at least validate but the danger is that the structured data doesn't actually represent what is on the page (i.e. there is no default image actually showing). It may be better to set the image to the first one on the page in this case (the full image).

For example on design 2, you could use full images and not thumbnails.  Then select the first image with WebPage. 

Here is what Genesis do 

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fdemo.studiopress.com%2Fgenesis-sample%2F

You would need to do this but also add in WebPage and take the first image.

**Comment by MARQAS** [comment]
Ahmed here,

We will need to run another loop for this, and that may cause a lag in perf. This isn't the biggest priority right now.
