### ISSUE TITLE
AMP Pagination issue for  2nd page Still persists 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2081]
AMP Pagination 2nd page is rendering into the normal page, not in the AMP but when we enable the /?amp it's rendering perfectly into the AMP.

Ref: https://secure.helpscout.net/conversation/566921715/25003?folderId=1060551

Continued from https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2058

**Comment by Sejiro-Hiko** [comment]
Issue seems to be from envira plugins but now on the user's end the pagination is working without us doing anything on the site.

**Comment by MohammedKaludi** [comment]
👍
