### ISSUE TITLE
PHP warning

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2083]
[Tue May 01 17:11:14.934082 2018] [:error] [pid 29018] [client 66.249.69.159:52808] PHP Warning: Illegal string offset 'format' in /nas/content/live/transhighcorp/wp-content/plugins/accelerated-mobile-pages/components/components-core.php on line 427

**Comment by MohammedKaludi** [comment]
:+1:
