### ISSUE TITLE
Archive pages are not working on custom post type when the swift theme is active

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2085]
Archive pages are not working on custom post type when the swift theme is active and it's working on design one, two and three.

Refs: 
https://secure.helpscout.net/conversation/552710422/23928?folderId=1680011
https://secure.helpscout.net/conversation/556023975/24167?folderId=1060554

**Comment by MARQAS** [comment]
I have tested this with W11 branch and it is working perfectly fine on my end.
