### ISSUE TITLE
New Option panel Styling is getting conflicted with Extension Styling

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2086]
New Option panel Styling is getting conflicted with Extension Styling

**Comment by MARQAS** [comment]
![accelerated mobile pages options 46 wordpress - google chrome 2018-05-02 16 11 35](https://user-images.githubusercontent.com/15303814/39519278-c0511ae6-4e23-11e8-9a0d-3b144ab147d0.png)
