### ISSUE TITLE
Pagebuilder anchor tags are not shows properly

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2089]
The user wants to create a link button with the following URL 
https://spanishcitizenship.co.il/בדיקת-זכאות-לאזרחות-ספרדית-ופורטוגלי
But in page builder removed that complete <a> tag on the front end.

To resolve that issue need, replace "urldecode" to "esc_html" while replace the html

For reference ticket
https://secure.helpscout.net/conversation/569760201/25277/?folderId=1060554

**Comment by MohammedKaludi** [comment]
:+1:
