### ISSUE TITLE
Thumbnail issue in the Slider module of AMP Page builder

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2090]
Thumbnail issue in the Slider module of AMP Page builder.
If we add two or more slider modules in the AMP page builder then the thumbnail does not work.

REF: https://secure.helpscout.net/conversation/571290086/25384?folderId=1680011

**Comment by ajeetku** [comment]
For testing: Add multiple carousels in a single page issue will re-occur.

**Comment by MohammedKaludi** [comment]
:+1:
