### ISSUE TITLE
alt in <div> causing validation errors. 

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2093]
Ref: <div class="relpost-block-single-image" alt="Salon du mariage">

https://secure.helpscout.net/conversation/572849627/25463/

**Comment by Sejiro-Hiko** [comment]
The Issue has resolved in the last update (0.9.90) by updating our vendor

**Comment by MohammedKaludi** [comment]
working as expected. 👍
