### ISSUE TITLE
Is there a way to only disable the AMP support for pagination pages

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2094]
Is there a way to only disable the AMP support for pagination pages

Ref:  https://secure.helpscout.net/conversation/573053509/25478?folderId=1914712

**Comment by Frenchomatic** [comment]
This isn't a bug - Not sure why you would wish to do this. However, you could look at either doing 301 redirects in htaccess or create an action in functions.php to test the page and remove the amp from the url string.

**Comment by MohammedKaludi** [comment]
The ticket was wrongly described. 
Closed :+1:
