### ISSUE TITLE
Drop Down Menu Support in Swift Header Menu

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2095]
Ref:  https://secure.helpscout.net/conversation/571223728/25377/?folderId=1060556

**Comment by ahmedkaludi** [comment]
@RajuJeelaga I'm putting this ticket in failed. Let's discuss this, I'll show you how to fix it.

**Comment by RajuJeelaga** [comment]
@ahmedkaludi Can you please check from the option panel, It is working fine from my side, Just Now I check.

**Comment by ahmedkaludi** [comment]
We need to improve the design of this.
