### ISSUE TITLE
Check for Existence of Trailing Slash

### ISSUE THREAD

**Issue by dayhawkkim** [ahmedkaludi/Accelerated-Mobile-Pages#21]
Would you consider checking for the trailing slash in the URL before appending "/?amp" to the amphtml relationship?

For example, my pretty URL structure is:

https://domain.com/sample-post/

The amphtml rel tag is rendered as:

<link rel="amphtml" href="https://domain.com/sample-post//?amp" />

In the rendered AMP page, the canonical shows up correctly as:

<link rel="canonical" href="https://domain.com/sample-post/">

Since both URLs (https://domain.com/sample-post//?amp and https://domain.com/sample-post/?amp) work, it's not a huge concern, but it would be nice for me to keep it consistent.

[Sorry, I didn't see that you preferred GitHub. Didn't intend to duplicate. Thanks!]

**Comment by MohammedKaludi** [comment]
Double Trailing slash in the url fix #24

**Comment by MohammedKaludi** [comment]
Issue Fixed in commit https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/f395d451c52225a5f6840af09daff2f27c8f4dae
