### ISSUE TITLE
Image Caption is not displaying below the Image in design 1,2,3

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2101]
Image Caption is not displaying below the Image in design 1,2,3 and Swift when the "Featured image from the content option"  is enabled in the Advanced settings.

Instead of that the caption is displaying in between the content.

REF: https://secure.helpscout.net/conversation/574152040/25551?folderId=1680011

**Comment by Frenchomatic** [comment]
I am not seeing this problem on design 2.

**Comment by MARQAS** [comment]
Reason: When grabbing the image from the content it is neglecting the caption and just taking the image of it while leaving the caption as it is in the content. 
So the possible solution is to check if the caption is present in the first image or not. 
If a caption is there grab the image with the caption and remove that whole part from the content else just grab the image

**Comment by MohammedKaludi** [comment]
:+1: Working perfectly.
