### ISSUE TITLE
Improvement in styling of AMP option panel

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2102]
- [x] Search option

- [x]  Tooltip is not visible correctly in the RTL
see this screenshot:  http://take.ms/DJbh8

**Comment by RajuJeelaga** [comment]
- [ ] RTL part is done for the Option panel.

**Comment by MohammedKaludi** [comment]
@RajuJeelaga All the controls are not properly aligned. http://take.ms/LkQ7u
