### ISSUE TITLE
accelerated-mobile-pages-en_US.mo is not set to correct path.

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2103]
Using mts schema themewp-content\plugins\accelerated-mobile-pages/languages/accelerated-mobile-pages-en_US.mo) is not within the allowed path(s): (C:/Inetpub/vhosts/;C:\Windows\Temp\) in C:\inetpub\vhosts\iamsher.com\wp-includes\l10n.php on line

http://monosnap.com/image/BIW0UBlzC4fQ9KBUcSvEQZnOqFRbam/

Ref: https://secure.helpscout.net/conversation/570360294/25317?folderId=1680011

**Comment by ahmedkaludi** [comment]
It's because of the server config: https://theme-fusion.com/documentation/avada/knowledgebase/getting-php-is_readable-warning/
