### ISSUE TITLE
Border Option is created 2 times in Option panel 

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2104]
- [x] In Header type 4 Border option is created need to remove and connected to border option which is avaliable in the core..
 https://monosnap.com/file/OVZuA2ylS6viw1mf2QKujNK91XAf0K
 https://monosnap.com/file/vpIMPgH51MPvzflNYBisHoet74h4fA

**Comment by ajeetku** [comment]
Changes need to do in amp-layouts
