### ISSUE TITLE
Homepage of AMP is rendering instead of different AMP Pages in AMP.

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2108]
Homepage of AMP is rendering instead of different AMP Pages in AMP.

REF:
https://secure.helpscout.net/conversation/575700355/25721?folderId=1680011
 
https://secure.helpscout.net/conversation/561429796/24551?folderId=1680011

**Comment by ahmedkaludi** [comment]
This issue is fixed I believe? Did we tested this solution on these customers?

**Comment by MohammedKaludi** [comment]
Its fixed and properly working. 
👍
