### ISSUE TITLE
Bug: Conflict with Clearfy 1.2.1

### ISSUE THREAD

**Issue by SchDen** [ahmedkaludi/accelerated-mobile-pages#2110]
Empty the amp pages, when the Clearfy html compress is enabled

![image](https://user-images.githubusercontent.com/1484977/39719135-99a1515e-5238-11e8-9a01-a3ec9c954c9c.png)

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by SchDen** [comment]
Sorry, but after install 0.9.97.1 - it's not still not working for me. I have empty <body></body>
