### ISSUE TITLE
Hide AMP by categories option should hide by default in the backend of that specific post

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2112]
Hide AMP by categories should hide by default in the backend of that specific post just like the pages

Screenshots:
http://take.ms/nKSJQ
http://take.ms/azQ6c

Ref: https://secure.helpscout.net/conversation/575867479/25744?folderId=673452

**Comment by MohammedKaludi** [comment]
:+1:
