### ISSUE TITLE
In the Latest version of AMP 0.9.86 the Custom Post doesn't display properly in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2113]
In the Latest version of AMP 0.9.86 the Custom Post doesn't display properly in AMP but its working fine in the 0.9.85.7 version.

Here is the video link to understand this issue clearly:  https://drive.google.com/file/d/18DXjsoTNq5dfA88RCKvFbTxoj5aGyblE/view

Ref:  https://secure.helpscout.net/conversation/574233053/25562?folderId=1914712

**Comment by Sejiro-Hiko** [comment]
The issue was fixed the updates after the 0.9.86 and just got the confirmation from the user also.

**Comment by MohammedKaludi** [comment]
> The plugin is working fine!
You can close the ticket.
Thank you so much!
Jun


Closing the ticket.
