### ISSUE TITLE
/amp is getting added in the Category module of layout builder

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2114]
1. /amp is getting added in the Category module of layout builder

2. Getting blank page when /amp is added in the page

REF: https://secure.helpscout.net/conversation/576330899/25816/?folderId=1680011

**Comment by MARQAS** [comment]
The issue is related to AMP newspaper theme : https://github.com/ahmedkaludi/amp-newspaper-theme/issues/80

**Comment by MARQAS** [comment]
This ticket can be closed

**Comment by MohammedKaludi** [comment]
:+1:
