### ISSUE TITLE
Google Tag Manager not working

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2117]
Ref: https://secure.helpscout.net/conversation/576452651/25824/

**Comment by daanishd** [comment]
Ref: https://secure.helpscout.net/conversation/577547407/25959?folderId=1964340

**Comment by beingsmart3** [comment]
One more Ref:  https://secure.helpscout.net/conversation/577679008/25970?folderId=1914712

And we've to make sure that we should reply the users after fixing this issue.

**Comment by Sejiro-Hiko** [comment]
Fixed the issue in 0.9.90 Version

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Sejiro-Hiko** [comment]
working in 0.9.96
