### ISSUE TITLE
AMPforWP Option panel styles are overriding other theme's options panel if both use Redux Framework

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2121]
AMPforWP styles are overriding even in other theme options like Engrave theme

See this screenshot: http://take.ms/88UCr

Ref: https://secure.helpscout.net/conversation/564555609/24789?folderId=673452

**Comment by ajeetku** [comment]
only Need to check with redux core plugins, because this plugin load on top of all plugins function name : "load_first"

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by beingsmart3** [comment]
One more issue, the custom CSS option is not working when this plugin "Plethora Features Library" is active 

Ref:  https://secure.helpscout.net/conversation/613354574/29334?folderId=1914712
