### ISSUE TITLE
Child theme not rendering

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2124]
AMP takeover:

Created a directory `ampforwp` in the themes folder and placed a custom header-bar.php into it. Doesn’t render. Are these instructions correct?

https://ampforwp.com/tutorials/article/child-theme-amp/

**Comment by ajeetku** [comment]
@Frenchomatic, please describe which design are you using?

**Comment by Frenchomatic** [comment]
This is now resolved.

**Comment by MohammedKaludi** [comment]
Thank you @Frenchomatic for the quick feedback.
:+1:
