### ISSUE TITLE
option/feature for change language of Facebook comment

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2127]
We can change the comment language by specifying a locale.
[By default, the locale is set to user's system language; however, we can specify a locale as well]

Ref: https://wordpress.org/support/topic/is-there-any-way-to-change-language-of-facebook-comments/

**Comment by MohammedKaludi** [comment]
Remove the on/off switch and add tutorial link

**Comment by MohammedKaludi** [comment]
:+1:
