### ISSUE TITLE
Issues Found in Design #3

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2130]
- [x] RTL/LTR styling is loading even RTL is off D3 http://take.ms/SKJWR
- [x] Empty Div loading in D3 Homepage http://take.ms/s3X3J
- [x] amp-ad.js is missing when only Ad#5 and Ad#6 is Enabled http://take.ms/wXAlU

**Comment by MohammedKaludi** [comment]
@MARQAS 
Removing code does not always works.
Need to fix 1st and 2nd point properly

1. RTL/LTR styling is loading even RTL is off D3 - 
Instead of removing the code directly move the code in the RTL section. Removing code could break the ads on users site.

2. Empty Div loading in D3 Homepage
- User proper condition like  `has_action` to check if the action added to that hook and show the div. Again i'm saying this don't just remove the code directly, it is added some reason.

**Comment by MARQAS** [comment]
1. RTL/LTR styling is loading even RTL is off D3 -
   It is already added in RTL section, that's why I removed it from the normal styling.
2. My apologies. I thought it's an extra hook. I'll be careful next time.

**Comment by MohammedKaludi** [comment]
:+1:
