### ISSUE TITLE
Add twitter to author bio

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2133]
Ref: https://secure.helpscout.net/conversation/578533105/26020?folderId=1060551

**Comment by ahmedkaludi** [comment]
**REVIEW**

- [ ] **REPEAT:** - Still doesn't look correct, read the below info carefully.
  Ideally it should be looking like this:
"admin (@ahmed_kaludi) - Share a little biographical information to fill out your profile. This may be shown publicly."

**Comment by MohammedKaludi** [comment]
escaping required.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ae4f7266ebd5b869774296a10587c868596854d8#diff-1c658a072a9aabbdb42ca7c2d0972b8bR76

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
