### ISSUE TITLE
AMP Ads code are getting sanitized in the Custom AMP Editor

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2134]
AMP Ads code are getting sanitized in the Custom AMP Editor (0.9)

Ref:  https://secure.helpscout.net/conversation/579529334/26076/

Example:  http://take.ms/9AkX4

**Comment by MARQAS** [comment]
Resolved here: #2228

**Comment by MohammedKaludi** [comment]
@MARQAS have you tested it in the localhost?

**Comment by MARQAS** [comment]
Yes, I did.
Custom AMP Editor: http://take.ms/IDbaq
Output: http://take.ms/m9Yt3

**Comment by MohammedKaludi** [comment]
the advert code is working, but we need to preserve the ad code when we switch from Visual to Text in the post editor, currently, it is stripping out by the text editor.

@ahmedkaludi what do you say about this?

**Comment by MohammedKaludi** [comment]
this is good, but also need to add the placeholder for amp components in Visual View.

**Comment by MohammedKaludi** [comment]
:+1:
