### ISSUE TITLE
Add IP Anonymization 

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2135]
Ref: https://secure.helpscout.net/conversation/578815939/26031/

https://github.com/spotxchange/amphtml/blob/4378763ab358f2ceab5578ce862cf3f1eddd2251/examples/analytics-vendors.amp.html

Should be able to set True/False values for "anonymizeIP": ""

**Comment by MohammedKaludi** [comment]
need to add anonymousIP feature in GTM as well 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js#L773

**Comment by MohammedKaludi** [comment]
if "anonymizeIP" is off then it should not be added in Analytics json

**Comment by MohammedKaludi** [comment]
:+1:
