### ISSUE TITLE
Page featured Image is not displaying in the Swift theme

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2136]
Page featured Image is not displaying in the Swift theme

Ref:  https://wordpress.org/support/topic/featured-image-on-pages-5/#post-10261325

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Sejiro-Hiko** [comment]
Should have a different option in the option panel of "page"

**Comment by MohammedKaludi** [comment]
Page featured image is not working http://take.ms/gnbhQ

**Comment by MohammedKaludi** [comment]
:+1:
