### ISSUE TITLE
Custom Front page is not rendering in Latest Version 0.9.86.2 when the user Uses "Be theme Child"

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2137]
Latest Version 0.9.86.2 Conflict with "Be theme Child",
Custom Front page is not rendering properly when the user is using the "Be theme child" in the 0.9.86.2 version.

REF:https://secure.helpscout.net/conversation/564430089/24725?folderId=1680011
https://secure.helpscout.net/conversation/579514461/26073/?folderId=1680011

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/580487660/26157?folderId=673452

**Comment by Zabi09** [comment]
on Localhost also the front page is blank when the betheme is activated.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MARQAS** [comment]
Not working as expected. 

Current Scenario:  Muffin Builder is disable on Custom FrontPage.

Expected: It should work same as Posts/Pages.

**Comment by MohammedKaludi** [comment]
:+1:
