### ISSUE TITLE
amp is active on front page but I disabled it on the settings

### ISSUE THREAD

**Issue by faia20** [ahmedkaludi/Accelerated-Mobile-Pages#214]
Hi.
Just realized that amp is active for pages including front page and I just enabled it for posts. This is even worst in my case because the amp front page is showing latest posts instead of the content and my homepage is the most important page.
Please help

**Comment by khaledMohammed000** [comment]
Hello @faia20  Thanx for using our plugin and also reporting this but its not an issue , you simply have to do as [follow ](http://take.ms/C08Q8)

**Comment by faia20** [comment]
@khaledMohammed000 thanks for your reply. I would just want to don't have amp on the first page, just want amp for posts but when I disable amp on front page I get the amp version anyway as in your video.

**Comment by khaledMohammed000** [comment]
@faia20 this is my understanding .. "You completely want to remove AMP from pages, right ?"

**Comment by faia20** [comment]
@khaledMohammed000  Yes, or just from a specific page (front page).

**Comment by khaledMohammed000** [comment]
@faia20  for a specific page you can do as [follow](http://take.ms/bwyq8) , In the future we are planning to add the feature for disabling AMP on all pages just with a button click

**Comment by faia20** [comment]
Thanks @khaledMohammed000 I also did that, but then if I type the domain + /amp, like http://example.com/amp its going to show the amp version. Doesn't this means that google is going to use this version?

**Comment by khaledMohammed000** [comment]
@faia20 Exactly if you manually add that in your domain your page will become AMP page but if you look at http://example.com sourcecode you will not find 

`<link rel="amphtml" href="http://example.com/amp/" />`

Unless and until google finds the above line of code your page will not be Indexed for AMP version

**Comment by faia20** [comment]
@khaledMohammed000 I understand now. Thanks for your support! Google had me indexed for amp, but now that I disabled in the page they should re-index it and remove it from their searches.

I'm happy with the support. Thanks a lot for the help!!

**Comment by ahmedkaludi** [comment]
Hey @faia20 
I’m so glad to know that! If you like the plugin, then please support us by leaving a feedback at https://wordpress.org/support/plugin/accelerated-mobile-pages/reviews/

I will really appreciate that!

Regards,
Ahmed
