### ISSUE TITLE
Need to create Add support for AMP Content Update ping to Google

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2140]
Add a feature into the plugin's admin pages, where it would directly be possible to send an "update content"-request to Google for asking to re-index/update cache of certain indexed AMP pages. 

Ref- https://secure.helpscout.net/conversation/580786117/26168?folderId=1060551

**Comment by ahmedkaludi** [comment]
This is going to take a lot of time and it won't be a one click solution.

**Comment by ahmedkaludi** [comment]
I found a very easy solution for this, I'll come back to this.

**Comment by ahmedkaludi** [comment]
We have an extension coming for this.
