### ISSUE TITLE
AMP validation error in search module of widget

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2143]
if we add search module in the widget on above the footer it showing validation error.

i.g: the search box is not allowed

Ref:https://secure.helpscout.net/conversation/580784265/26167?folderId=1914716

**Comment by MohammedKaludi** [comment]
need to add the css of hidden field.

**Comment by MohammedKaludi** [comment]
:+1: Working smoothly
