### ISSUE TITLE
Icons do not load when coming through AMP CDN

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2144]
Social icons styling issue in the swift theme while going through the google search.

See this screenshot:  http://take.ms/ZoBK3

Ref:  https://secure.helpscout.net/conversation/579901517/26110?folderId=1914712

**Comment by beingsmart3** [comment]
Same issue in Design 3
see this screenshot:  http://take.ms/Qc49N
Ref:  https://secure.helpscout.net/conversation/591579790/27178?folderId=2075531

**Comment by beingsmart3** [comment]
@ahmedkaludi is solving the issue

**Comment by ahmedkaludi** [comment]
I have the solution but we will wait from the user's FTP and then commit on this.

**Comment by MARQAS** [comment]
continue at https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1735

**Comment by sunanda60** [comment]
in design 3, social icon issue still there
