### ISSUE TITLE
"Menu" option in Footer section when Swift is Used

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#2146]
The Option is unused right now, either we should connect it or remove it.
Redux ID is ` 'id'    => 'swift-menu'`

**Comment by Sejiro-Hiko** [comment]
@ahmedkaludi what should we do with this option which is right now not being used?

**Comment by MohammedKaludi** [comment]
:+1: Footer on/off is working.
