### ISSUE TITLE
Swift Theme Accelerated Mobile Pages Broken Sidebar Dropdown for sub-menu

### ISSUE THREAD

**Issue by cooperate** [ahmedkaludi/accelerated-mobile-pages#2148]
Two issues:
1) Dropdown arrows for buttons do not respond properly.  The menus will correctly drop down but will not slide up after the fact.
2) Console error 
element-service.js:76 Failed to load: [web_url]
ie @ element-service.js:76

Not sure if they are correlated but I tried a different theme, experienced no console error but still had dropdown menu problems in the sidebar.

**Comment by ahmedkaludi** [comment]
@cooperate Can you share the URL so that I can check?

**Comment by Sejiro-Hiko** [comment]
this will be resolved in #2167

**Comment by MohammedKaludi** [comment]
@ahmedkaludi need your opinion on what to do about this ticket?

**Comment by ahmedkaludi** [comment]
@Sejiro-Hiko @MohammedKaludi #2167 has nothing to do with this issue. 

The issue is that, You can open a sub menu in mobile but you can't close it. Try it on Mobile. It's a UX problem.

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko ask @ahmedkaludi and discuss the solution.

**Comment by Sejiro-Hiko** [comment]
sure

**Comment by ahmedkaludi** [comment]
We can use this method for implementing this feature: https://www.cssscript.com/demo/pure-css-mobile-compatible-responsive-dropdown-menu/#

**Comment by ahmedkaludi** [comment]
- [ ] Test this case: #2139

**Comment by santosh8793** [comment]
I have added responsive sidebar menu functionality using walker class, some commented styles are there in style.php and menu.php which are needed to be tested for any design issues

**Comment by RajuJeelaga** [comment]
- [ ] Issue number #2332 is connected to this ticket

**Comment by ahmedkaludi** [comment]
**REVIEW**
@RajuJeelaga The Design 3 child menu looks like parent menu. Let's maintain the original styling. See: http://take.ms/r52yD

**Comment by Omair52** [comment]
pushed in 0.9.97.17

**Comment by MohammedKaludi** [comment]
Name of the filter changed to 'ampforwp_nav_menu_css_class'

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b7f46bec86fe1ecbd893f3e10211388a597cefa3
