### ISSUE TITLE
Improvement in AMP take over option

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2153]
If AMP take over option is enabled and if I disabled the amp support on the specific page then it should work but it's showing this error: http://take.ms/xwASg

**Comment by MARQAS** [comment]
This should resolve it: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0d1139758f00b279cc0eb1322d7abdc4fa33c6fa

**Comment by MARQAS** [comment]
Only one issue is remaining.
Use case: Homepage support from AMP is OFF but Its showing the AMP page on the main homepage URL. 
It will only get disable if we turn the AMP off on that page.

**Comment by joyloan** [comment]
Hi!

I am eagerly waiting for this update (Page exception after AMP takeover). Can you suggest, when it is expected?

**Comment by MohammedKaludi** [comment]
@joyloan we are planning to release the update on Monday that is 25th June 2018.

**Comment by MohammedKaludi** [comment]
Custom frontpage is not working.

**Comment by MohammedKaludi** [comment]
:+1:
