### ISSUE TITLE
compatibility with Foogallary plugin

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2154]
The foogallary plugin replaces src attributes to src-fg because of this image disappears in the amp.

Ref:https://wordpress.org/support/topic/conflict-with-foogallery-2/

**Comment by MARQAS** [comment]
We have already added the compatibility of it

**Comment by MARQAS** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1424

**Comment by Sejiro-Hiko** [comment]
Just tested the plugin with our own and the images are displaying fine.
the ticket was created due to the misunderstanding of the user's query on the forum.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Sejiro-Hiko** [comment]
Working in 0.9.96
