### ISSUE TITLE
Need to create the option were Above the Post Content ads should display on post, pages and Custom post type

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2155]
Need to create the option were "Above the Post Content" ads should display on the post, pages, and Custom post type.

Ref:  https://secure.helpscout.net/conversation/570373633/25319?folderId=1914712
Why is ad unit # 3 just for posts?
"Above the Post Content (Single Post)"
I need to add it to all the pages and I currently do it by editing a file.

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko need to create a dropdown with an option that, 
Show in Single or Show Globally. And Default should be "Show in Single"

As not all users would prefer that.

**Comment by MohammedKaludi** [comment]
This is breaking the site

> ( ! ) Warning: Invalid argument supplied for foreach() in C:\wamp\www\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 787

Error Screenshot http://take.ms/XoiNw
Advert Settings: http://take.ms/VTEGp

**Comment by MohammedKaludi** [comment]
:+1:
