### ISSUE TITLE
Dropcap breaking the youtube embed code

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2157]
Dropcap breaking the youtube embed code because of the embed code pasted in the very beginning of the post.

see this screenshot:  http://take.ms/GVekd

**Comment by MohammedKaludi** [comment]
DropCap now working fine

But Controls is visible in all designs.
Selected design: Design3 and drop cap control is visible. http://take.ms/iCdXzY

**Comment by MohammedKaludi** [comment]
:+1:
