### ISSUE TITLE
Advanced Header Design Settings.

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2161]
- [ ] Need to add the condition for the header options like, when Advanced Header Design is Enable then only the options need to be work..
https://monosnap.com/file/LUTnCk4WszEUWX7uB6UC3lzxrG4bGT

- [ ] Need to create the same condition for the Advance Footer and Advance SIngle..

**Comment by Sejiro-Hiko** [comment]
The Advanced header issue was fixed when testing wp to amp conversion feature but due to some constraints faced by @RajuJeelaga the fixed was reverted.
Ref: 813c7e7371237b2b2b1e72309d47a63803ac6f25
