### ISSUE TITLE
Social icons for pages.

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2162]
In our plugin social icons are only for the post so made it for the page also[both sticky social icons, content social icons]

Ref: Ref: https://wordpress.org/support/topic/social-icons-on-pages/

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by beingsmart3** [comment]
Social icons of these companies ( facebook, twitter, Gplus, email, Pinterest, Linkedin ) are creating the validation error when we enabled the sticky social share icon only for pages.

Ref:  https://secure.helpscout.net/conversation/620148901/30196?folderId=1914712

**Comment by MohammedKaludi** [comment]
@MARQAS

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
