### ISSUE TITLE
Comments Button is not displaying

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2163]
- [x] In the Post, If the comments are not available, It should be , display like this.
https://monosnap.com/file/CdbLyBr4ObailqXW3NuiGxENFx5rDr

- [x] The comment Button is displaying when the comments are available.
 https://monosnap.com/file/q8IFujXQoRSQsLrD7xvoPA3NWTdlc1

**Comment by beingsmart3** [comment]
One more Ref:  https://secure.helpscout.net/conversation/577171106/25874?folderId=1914712

**Comment by MARQAS** [comment]
Only styling is left, wrapper css is not getting loaded. 
http://take.ms/IEtzx

**Comment by MohammedKaludi** [comment]
:+1:
