### ISSUE TITLE
Swift Menu improvement

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2167]
Swift menu is broken uder this use case: Enable the advanced footer design.. and select Footer 2 Menu Position as inline and disable the advanced footer design

![image](https://user-images.githubusercontent.com/15303814/40294145-fb01354a-5cf1-11e8-95b6-fa6e005cb113.png)

**Comment by Sejiro-Hiko** [comment]
one more #2148

**Comment by RajuJeelaga** [comment]
Marqas Approved this ticket.
