### ISSUE TITLE
Paginated Post not working

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2169]
Ref: https://secure.helpscout.net/conversation/582912755/26328?folderId=1964340

The content isn't showing up on Page 2 and so forth but the featured image does.

**Comment by MARQAS** [comment]
Resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2168

**Comment by MARQAS** [comment]
Yup, we already did and it fixed the issue on his end as well

**Comment by MohammedKaludi** [comment]
👍
