### ISSUE TITLE
Facebook Comment should not appear on the Checkout page, Add to cart page, or shop page

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2170]
Facebook Comment should not appear on the Checkout page, Add to cart page or any shop page.

Ref:  https://secure.helpscout.net/conversation/584344309/26462?folderId=1680011

**Comment by ahmedkaludi** [comment]
Isn't this for woocommerce pro?

**Comment by MohammedKaludi** [comment]
`ampforwp_framework_cmt_scripts` filter is not properly used and another commenting system will still load, like disqus and native comments.

**Comment by MohammedKaludi** [comment]
Facebook comments are not loading http://take.ms/oD2zW

**Comment by MohammedKaludi** [comment]
:+1:
