### ISSUE TITLE
Same Icons loading for some extensions 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2172]
Same Icons loading for some extensions in Options panel

http://take.ms/s8MPY

**Comment by ahmedkaludi** [comment]
waiting from myself

**Comment by ahmedkaludi** [comment]
- [ ] Need to add UTM tags to rest of the extensions in http://take.ms/ClMU8

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
