### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2173]
Warning: Invalid argument supplied for foreach() in /home3/pollux/public_html/stageefinancialmodels/wp-content/plugins/accelerated-mobile-pages/templates/custom-sanitizer.php on line 196

Ref: http://take.ms/gs5I2

Ref: https://secure.helpscout.net/conversation/556023975/24167?folderId=1964340

Sol: http://take.ms/d7BGL

**Comment by MohammedKaludi** [comment]
:+1:
