### ISSUE TITLE
External Links are appended with "amp" at the end of the url in content.

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#2174]
Example If you add the following anchor link in editor `www.youtube.com` it appears in AMP as `www.youtube.com/amp/` this also happens to the images wrapped in anchor links and causing object, not fount issue.

1.  Need to create an option to Convert NON-AMP links to AMP links And connect it.
2. If WP->AMP is NOT Enabled then check link convert is on or not

**Comment by Sejiro-Hiko** [comment]
@ajeetku does it work for all the designs at amp endpoint or only for the takeover or theme support?

**Comment by MohammedKaludi** [comment]
:+1:
