### ISSUE TITLE
Create a new function to get the settings instead of calling it directly from  global $redux_builder_amp everytime

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2177]
Create a new function to get the settings instead of calling it directly from  global $redux_builder_amp everytime

**Comment by ahmedkaludi** [comment]
Is this a priority?

**Comment by MARQAS** [comment]
Also made some changes in Single.php of Swift for example purpose.

**Comment by MohammedKaludi** [comment]
Need to make sure we get the values of nested data as well.

Example

$redux_builder_amp['opt-media']['url']
$redux_builder_amp['primary-menu-background-scheme']['rgba']

**Comment by MARQAS** [comment]
We can get it easily. Take an example of URL of the logo from our options. 
$logo = ampforwp_get_setting('opt-media');
Then $logo['url'] will give the url of the logo.

**Comment by MohammedKaludi** [comment]
Moved the code from features.php to accelerated-mobile-pages.php 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/15f227ad9a452442fa6bd52d84184358324212e9

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
