### ISSUE TITLE
Plugin manager should also work with /?amp=1 

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2178]
Ref: https://secure.helpscout.net/conversation/582912755/26328?folderId=1964340

Plugin manager works with /amp URL but not /?amp=1.

**Comment by MARQAS** [comment]
Resolved here: https://github.com/MohammedKaludi/plugin-manager/issues/3

**Comment by MohammedKaludi** [comment]
Fatal error: Uncaught Error: Class ‘ReduxCore’ not found […] the problem was found on the plugin manager .php file.
Fixed : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8a9950db792933524f29c6ec7df5077182685a40

**Comment by MohammedKaludi** [comment]
not working properly, 
Current check is not robust, need to use better way to check if amp is present in url
https://github.com/ahmedkaludi/amp-plugin-manager/commit/f64581bd1bfb07441a1071c3711c671157208f58#diff-fa31b69d47cb96842440c40e8f5ed595R15

**Comment by MARQAS** [comment]
Done: d9450ca8cae303c17a26a8a71f1e7cbc5aeb9ff7

**Comment by MohammedKaludi** [comment]
Issue fixed in AMP Plugin Manager.

Issue nothing to do with AMPforWP plugin, for more info please follow 
https://github.com/ahmedkaludi/amp-plugin-manager/issues/3
