### ISSUE TITLE
Fully compatibility with muffin page builder

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2180]
Hide The Content option should also reflect in the AMP version - http://take.ms/0SGuw

Ref: https://secure.helpscout.net/conversation/580487660/26157?folderId=673452

**Comment by MARQAS** [comment]
It should not override the Custom AMP Editor

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MARQAS** [comment]
It is not working as expected. 
Current Scenario: Custom AMP Editor is getting added with Muffin Builder content. There is no way to override Muffin Builder Content in AMP.

Expected: Muffin Builder should be connected to Main Editor only but not with Custom AMP Editor. 
Custom AMP Editor should be standalone and it should be able to override the Muffin Builder content as well.

**Comment by MohammedKaludi** [comment]
:+1: 
nice work @MARQAS on this. :+1:
