### ISSUE TITLE
Issue with Cookies and Sticky Ads

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2181]
Cookies notification bar and sticky ad getting conflicted with each other in New Advance AMP Ads. Cookies bar need to reflect the pop-up on title bar when both of them are enabled.

Ref: https://secure.helpscout.net/conversation/587232935/26719?folderId=1060551

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/amp-newspaper-theme #82](https://github.com/ahmedkaludi/amp-newspaper-theme/issues/82) via [**ZenHub**](https://www.zenhub.com/)
