### ISSUE TITLE
JSON Data tags broken

### ISSUE THREAD

**Issue by Cosrnos** [ahmedkaludi/accelerated-mobile-pages#2182]
It looks like you're relying on an old build of Automattic's AMP that is using XML instead of HTML  for serialization. As a result, JSON config for the new `amp-consent` tag is breaking across AMP Pages for people trying to use tags that rely on this data.

Original bug: Automattic/amp-wp#755
Original fix: Automattic/amp-wp#891

![cursor_and_hello_world____user_s_blog_](https://user-images.githubusercontent.com/5360729/40502211-e50f320e-5f4f-11e8-9381-25edb14f876f.png)

**Comment by Sejiro-Hiko** [comment]
@Cosrnos are you still facing this issue?

**Comment by Sejiro-Hiko** [comment]
@Cosrnos can you please reach us out here https://ampforwp.com/support/ along with your site url, I'll look into the issue on your end.

**Comment by Cosrnos** [comment]
@Sejiro-Hiko We don't have a site, we're actually developing a plugin and one of the behaviors is dropping an amp-consent and amp-geo tag onto the page, but anytime we try to do this via the sanitizer hook originally provided by the AMP plugin from automattic that you've forked, your plugin tries to wrap the JSON config for those objects in CDATA, which is because you haven't pulled in the changes from the AMP plugin since it was fixed in their 0.7.0 tag. I've already linked the bug and fix from that repo in my original issue.

You can test this yourself by adding a sanitizer and inserting an amp-geo tag into the page with some basic config.

**Comment by Sejiro-Hiko** [comment]
@Cosrnos can you please test this developmental version https://github.com/ahmedkaludi/accelerated-mobile-pages/archive/0.9.96.zip as we've resolved the issue already and if it still appears then with this one it should be gone please test and let us know so that we can merge this in the master and release it.

**Comment by MohammedKaludi** [comment]
@Cosrnos Can you please check and let us know if it fixed, because we are going to push the update on Monday, if we did not get any response from you till Monday, then we have to close the ticket.

You can reopen it again. But will be assigned into next milestone.

**Comment by MohammedKaludi** [comment]
@Cosrnos Closing the ticket for now. Please reopen if the issue persists.
