### ISSUE TITLE
Empty noscript tag is loading when Convert from WordPress Selected and WooCommerce plugin is activated

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2183]
Empty `<noscript></noscript>`  tag is loading when Convert from WordPress Selected and WooCommerce plugin is activated

**Comment by MohammedKaludi** [comment]
yes

**Comment by ahmedkaludi** [comment]
@MohammedKaludi That option is not available so we can close this ticket now.
