### ISSUE TITLE
Facebook like button to Sticky

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2186]
Add Facebook like button to Sticky, it is currently only available on the embedded.

Ref:  https://secure.helpscout.net/conversation/586096785/26631?folderId=1914712

**Comment by MARQAS** [comment]
Styling is broken. https://monosnap.com/file/bNcSUqajPDzA40OXeuwGqYLRYC61bl

**Comment by MARQAS** [comment]
In swift, it is breaking in Tablets and PC mode, and in other designs, it is still broken.

**Comment by MARQAS** [comment]
The tag 'amp-facebook-like' requires including the 'amp-facebook-like' extension JavaScript.

**Comment by MARQAS** [comment]
Why the script is getting added twice?

**Comment by MARQAS** [comment]
Please try to add it through only one condition

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
use `ampforwp_get_the_ID()` instead  `get_the_ID()`		
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bde3926fe9e08050474a93f785dd1e652b84b8e2#diff-6aa5512f7dd8d5ce60fc97b0f340912cR573

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
