### ISSUE TITLE
Issues found after 0.9.92 update

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2192]
- [x] Custom scripts are loading. if any scripts added via wp_print_scripts hook
- [x] Append amp in menu urls not working.

**Comment by ahmedkaludi** [comment]
- [ ] VC shortcode getting print

- [ ]

**Comment by sidneydemoraes** [comment]
- [ ] `img` tags in Custom Amp Editor not rendering

**Comment by MohammedKaludi** [comment]
Also need to merge #2194

**Comment by MohammedKaludi** [comment]
[ ] structured Data issue, it might be related to meta issue 

[ ] Post pagination issue https://wordpress.org/support/topic/plugin-bug-post-pagination-broken/

**Comment by ahmedkaludi** [comment]
- [ ] Fatal error: Uncaught Error: Call to undefined function ampforwp_is_non_amp() in /home/argentravel/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php:404

**Comment by MARQAS** [comment]
Yoast SEO plugin "On custom Frontpage setup with Meta Description ON"

Resolved it in W-13.

**Comment by Zabi09** [comment]
- [ ] I received this error message when I tried to access my installed plugins: Fatal error: Class 'AMP_Base_Sanitizer' not found in /home/massag01/public_html/vivanti.ca/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-blacklist-sanitizer.php on line 17

- [ ] Custom HTML is not working in AMP footer widget

- [ ] Category module of AMP page builder is not displaying images and getting validation issues of the width

**Comment by Zabi09** [comment]
- [ ] unable to activate plugin manager - http://take.ms/3JxJX

**Comment by ansaritalha** [comment]
AMP page builder modules get duplicate(rendering twice) when there is a content in WordPress editor.

**Comment by beingsmart3** [comment]
VC shortcode getting print
Ref:  https://secure.helpscout.net/conversation/590693894/27060/
