### ISSUE TITLE
V 0.9.92: Fatal error opening plugins.php

### ISSUE THREAD

**Issue by olivermaor** [ahmedkaludi/accelerated-mobile-pages#2193]
When opening the plugins.php, I get: Fatal error: Class 'AMP_Base_Sanitizer' not found in [Wordpress Path]/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-blacklist-sanitizer.php on line 17. The other pages, the website, and AMP appear not to be affected.

**Comment by olivermaor** [comment]
Included a pull request; additional code appears to solve the problem.

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/587367615/26735?folderId=673452
