### ISSUE TITLE
 AMP is not working on pages only on blog posts

### ISSUE THREAD

**Issue by matheushirota** [ahmedkaludi/accelerated-mobile-pages#2198]
Hello, I have a domain client: https://origen.com.br that has the AMP plugin installed, until yesterday everything was working correctly, but today the AMP is only working on blog posts like for example: https://origen.com.br/mito-ou-verdade-cafe-pode-provocar-aborto/amp/ this url works, however if I try to access a page like for example: https://origen.com.br/fiv-fertilizacao-in-vitro/amp/ it redirects to the normal version of the site, seeing in the inspect of Chrome I see that a 302 redirect is done, in the panel of the plugin AMP is enabled for pages!

**Comment by MARQAS** [comment]
Hi @matheushirota 

Thanks for reporting this issue. We have resolved this issue here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2199

I have added the fix to your website, please do check and let us know.

**Comment by nanhann** [comment]
I have the same problem as mentioned above on this sub-domain. 

https://info. aladvantage.com

Can you please advise how to fix it?

Thank you
