### ISSUE TITLE
onClick Events in anchor tags invalidate AMP pages

### ISSUE THREAD

**Issue by dayhawkkim** [ahmedkaludi/Accelerated-Mobile-Pages#22]
I found that onClick events tracking outbound links (via Google Analytics by MonsterInsights) were invalidating the AMP pages. For now, I have disabled outbound link tracking in the Google Analytics plugin.

This is more of a comment than a suggestion since an update is coming out. I'd think there has to be a way to track outbound links. But this is not urgent.

Thanks.

**Comment by ahmedkaludi** [comment]
Hey @dayhawkkim  

Please update to the new version 0.7.7 - It should fix this issue.

If you like the plugin then please help us by leaving a review in the plugin reviews section.

Regards,
Ahmed
