### ISSUE TITLE
Whatsapp share function not working on Google Search app

### ISSUE THREAD

**Issue by Chris00785** [ahmedkaludi/accelerated-mobile-pages#220]
When clicking the Whatsapp share button whilst on the Google Search app, it fails to load the Whatsapp screen to share the amp content.

To replicate, open this article on an iOS device using the Google search app:

http://www.telltalesonline.com/11634/one-direction-gifts-for-every-directioner/amp/

**Comment by khaledMohammed000** [comment]
@MohammedKaludi please let me know if this is getting replicated ?

**Comment by khaledMohammed000** [comment]
@Chris00785 Please update to the latest Update and let me know if the issue persists
