### ISSUE TITLE
When Cookies Consent is enabled the GDPR is not working

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2200]
When Cookies Consent is enabled the GDPR is not working

Ref:  https://secure.helpscout.net/conversation/589277286/26894?folderId=1914712

**Comment by Sejiro-Hiko** [comment]
Only a single `<amp-consent>` element is allowed on the page, and that element must specify a unique id.
If you also include an `<amp-user-notification>` element on the page, the UI associated with the `<amp-consent>` and `<amp-user-notification>` will not be deterministic. Avoid using `<amp-consent>` with `<amp-user-notification>` if this would be problematic.

Source: https://www.ampproject.org/docs/reference/components/amp-consent

**Comment by MohammedKaludi** [comment]
GDPR is working perfectly fine, closing the ticket.
