### ISSUE TITLE
feature of open related post internal link in non amp

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2201]
feature for Related post links to open in non-amp instead of the amp 

Ref: https://wordpress.org/support/topic/change-related-posts-internal-links/

**Comment by MohammedKaludi** [comment]
the code modified in  `amp_loop_permalink` is breaking the loop amp links in homepage and archive in Swift.

**Comment by MohammedKaludi** [comment]
:+1:
