### ISSUE TITLE
optimization in Ajax calling when GDPR is enabled

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2202]
When a user goes to an article, the GDPR option is doing a query POST admin-ajax.php

So, if the site has a few visits, that´s ok. But if the website has thousands, that is going to cause an overload on the server.

Ref: https://wordpress.org/support/topic/issue-in-the-last-update-gdpr-option/

**Comment by MARQAS** [comment]
There is no other option. 
We Will improve this once amp-consent and amp-geo gets more features/improved.
Closing this for now.
