### ISSUE TITLE
Custom post types with custom taxonomy not working in AMP

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2209]
Custom post types with custom taxonomy not working in AMP
It redirects to non-amp 404 page

**Comment by MohammedKaludi** [comment]
The code is written only for WooCommerce, what about other CPTs? 
@MARQAS?

**Comment by MARQAS** [comment]
Others are working fine.

**Comment by MohammedKaludi** [comment]
:+1:
