### ISSUE TITLE
Comments not showing any more also with Comments extension

### ISSUE THREAD

**Issue by olivermaor** [ahmedkaludi/accelerated-mobile-pages#2211]
Since the last update to 0.9.95, comments are not shown any more on AMP pages, even with the Comments extension installed.

The code for the comments field in the output of a post is only:
`<div class="cmts"> <div class="amp-comments"> </div> </div>`

Please do something about it, as the Comments extension is a paid solution.

Example page: [https://maor.de/wassersport-vereine-datenschutz-grundverordnung-vertraege-ausland-informationen?amp](https://maor.de/wassersport-vereine-datenschutz-grundverordnung-vertraege-ausland-informationen?amp)

**Comment by Sejiro-Hiko** [comment]
Hi @olivermaor can you please tell me which version you are using and did you enabled the option from the setting->comment area?

**Comment by Sejiro-Hiko** [comment]
@olivermaor  please respond before the deadline that is 20-June-18 otherwise we'll be closing this issue and we'll reopen it for some another milestone if we get the response from you.

**Comment by Sejiro-Hiko** [comment]
@olivermaor the issue you mentioned is strange as we're unable to recreate the issue on our end and nor the other user's reported such issue so what I suggest you is to report us here on the support and our team will debug the issue on your end and make sure that the comments work on your end.
Support Link: https://ampforwp.com/support/

**Comment by MohammedKaludi** [comment]
Closing the ticket due to lack of user response.
