### ISSUE TITLE
0.9.96

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2212]
- [x] GDPR with 2 designs

- [x] GTM not working

- [x] Add layout designs https://github.com/ahmedkaludi/accelerated-mobile-pages/compare/0.9.96#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69L323

- [x] Folder overwrite for themes https://github.com/ahmedkaludi/accelerated-mobile-pages/compare/0.9.96#diff-1301281de287d2aed98746fc9ba777b4L86 (need to cross check)

- [x] Apply this changes in welcome.php https://github.com/ahmedkaludi/accelerated-mobile-pages/compare/0.9.96#diff-1b98edde9332a5e4649db583249c268bL81

- [x] Fixes done in category module https://github.com/ahmedkaludi/accelerated-mobile-pages/compare/0.9.96#diff-cb16861af9ff34ccd298041891008f49L203

- [x] Need to test add /amp in the menu is working or not

- [x] Need to Free VS Pro in admin-config.php https://github.com/ahmedkaludi/accelerated-mobile-pages/compare/0.9.96#diff-260eba6333c3222e59a6aed22ac5ab37L384

- [x] Add ninja forms array https://github.com/ahmedkaludi/accelerated-mobile-pages/compare/0.9.96#diff-260eba6333c3222e59a6aed22ac5ab37L80

- [x] Blog title in homepage in all designs https://github.com/ahmedkaludi/accelerated-mobile-pages/compare/0.9.96#diff-8aecbbbcd33504681166e87f9a64758fL49

- [x] Meta Description

- [x] Meta Robots

**Comment by MARQAS** [comment]
Add proper URL for AMP options panel from welcome.php : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0ae211a
