### ISSUE TITLE
AMP not working for my Site

### ISSUE THREAD

**Issue by DevelopedByAnurag** [ahmedkaludi/accelerated-mobile-pages#2214]
Sir,
I recently installed amp and found that it is not working for my site

amp test by google is showing me an error that 
https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=T-H1kUUkQRmb6gUibGQePQ

Sir please help me in the regard to make my site amp freindly

**Comment by ahmedkaludi** [comment]
@DevelopedByAnurag the current version should fix your issue or please contact ampforwp.com/support
