### ISSUE TITLE
Consent component is not properly configured

### ISSUE THREAD

**Issue by zhouyx** [ahmedkaludi/accelerated-mobile-pages#2219]
There are a lot of components that have `data-block-on-consent` added, but there's not `<amp-consent>` component configured. The `data-block-on-consent` attribute doesn't do anything without the actually component set up.

**Comment by Sejiro-Hiko** [comment]
Hi @zhouyx,
Can you please brief me what issue you are facing with the above-mentioned scenario, is it similar to the issue mentioned here #2232 ?
please reach us out here https://ampforwp.com/support/ and I personally assist you with your issue.

**Comment by zhouyx** [comment]
@Sejiro-Hiko 

I worked on the `<amp-consent>` component. This is something that I found when I was looking at some random pages out there.

- I saw you configured `data-block-on-consent` on some AMP components without actually putting the `<amp-consent>` component. Those components won't be blocked, is that the expected behavior? 

- Another question I found `data-block-on-consent` attribute is added to components like `<amp-img>` but not `<amp-ad>` Is that expected?

**Comment by Sejiro-Hiko** [comment]
@zhouyx 

that's actually an improper implementation of the `<amp-consent>` and `data-block-on-consent` and whose behavior is preventing the data being load from components such as `<amp-ad>` for which I've created the ticket #2232 and we're currently working on it.

**Comment by Sejiro-Hiko** [comment]
@zhouyx 
Actually, I couldn't understand your initial reply when you stated "you worked on the `amp-consent ` component"
The answer to your earlier points are 

- yeah the components won't be blocked even if we put `data-block-on-consent` without setting the `<amp-consent>`
- we've put the `data-block-on-consent` on `<amp-ad>` as well.

**Comment by zhouyx** [comment]
@Sejiro-Hiko I worked on the design and the implementation of the `<amp-consent>` component, and the `data-block-on-consent` attribute that comes along with the component.

>that's actually an improper implementation of the <amp-consent> and data-block-on-consent and whose behavior is preventing the data being load from components such as <amp-ad> for which I've created the ticket #2232 and we're currently working on it.

This is exactly what the `<amp-consent>` component is designed for. 

>yeah the components won't be blocked even if we put data-block-on-consent without setting the <amp-consent>
we've put the data-block-on-consent on <amp-ad> as well.

As far as I found, you only put that on adsense ad. Still what's the point of adding `data-block-on-consent`? Guess I don't understand the real use case here. But from what I heard, you don't need the feature. Is there a reason why you want to add the `data-block-on-consent` attribute? Or is this a misconfiguration?

**Comment by MARQAS** [comment]
@zhouyx Is there any problem in using `data-block-on-consent` in all components? 
If a user enables the GDPR option then it will be added to almost all the components. Is there any problem with that? I found that it will block all components if a user select reject from consent and I guess that should be the case for GDPR compliancy, isn't it? 
Are there any components which don't need `data-block-on-consent` or will not get affected by it?

Thanks for all your help!

**Comment by zhouyx** [comment]
@MARQAS 
Technically you can use `data-block-on-consent` in all components. Although it may bring deadlock if you add the attribute to `<amp-consent>` or `<amp-geo>`
It's perfectly fine to add `data-block-on-consent` to all components. And it's really publisher's decision on which components to block when consent is not given or rejected. `data-block-on-consent` is simply a tool to help you achieve the blocking behavior. 

My origin question was not about adding `data-block-on-consent` to every components. But about using the attribute without `<amp-consent>` component. Without `<amp-consent>` configuration, no component will be blocked.

**Comment by MARQAS** [comment]
@zhouyx, Thanks for the detailed information! 
If there's no problem in having `data-block-on-consent`, then I guess we can keep it. 
Or is there a way to check the countries mentioned in amp-geo globally? Currently, we can use it amp-consent but is there a way to store it in a global variable to use it in anywhere?
As far as I know, it's not available but is it possible?

**Comment by zhouyx** [comment]
`<amp-geo>` generates css classes and applies them to the `body` for publishers to customize their content. Detail information can be found [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-geo/amp-geo.md#generated-css-classes).

**Comment by MohammedKaludi** [comment]
@zhouyx thank you for your help.

@MARQAS current GDPR settings seem to work properly for all the users, EU and NON-EU.
Nice work on this one @MARQAS
