### ISSUE TITLE
Space short codes cause lines in strange places

### ISSUE THREAD

**Issue by Acer10** [ahmedkaludi/accelerated-mobile-pages#2220]
Hi
I used space short codes in the PRO Theme and the result is lines in strange places on my home page. The resulting AMP page looks terrible, though it passes the AMP test
![amp page](https://user-images.githubusercontent.com/39934734/40951906-6c93425e-68bc-11e8-9e2e-42b7b7b9556f.jpg)
On the non AMP page there are no lines. I hope this is something that is easy to fix.

Acer10

**Comment by Sejiro-Hiko** [comment]
Hi @Acer10,
can you tell me how you are adding "space shortcode" is it from any plugin?
can you please reach us out here https://ampforwp.com/support/ with the detail about the issue?

**Comment by Acer10** [comment]
Hi,
I have done but the reply i received is as follows;

Hello Tom,

Hope you are doing good, thank you for writing to us.

With regards to your query about Theme short codes. Could you please tell me whether you have been invited by anyone's reference from our team. 

Do let me know if you have any further queries.

Regards,
Meraj Ali

AMPforWP Customer Sucess Team

**Comment by Sejiro-Hiko** [comment]
@Acer10  the file you sent is corrupted can you please look into it and send the correct file.

**Comment by Sejiro-Hiko** [comment]
@Acer10 please respond before the deadline that is 20-June-18 otherwise we'll be closing this issue and we'll reopen it for some another milestone if we get the response from you.

**Comment by Acer10** [comment]
Will upload through your support process as soon as I finish my evening meal

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sejiro-Hiko** [comment]
@Acer10 thanks

**Comment by Sejiro-Hiko** [comment]
@Acer10 Can you please test the above commit or you must've got an email from us you can follow that too.

**Comment by MohammedKaludi** [comment]
Working properly and confirmed by the user here: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a6bbd54a587117c4c537b6d79e9829b805dc9dcb#commitcomment-29430976
