### ISSUE TITLE
Forms Module 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2221]
Forms Module which allows users to integrate CF7, Gravity Forms, Ninja forms, etc 
which also gives the them the ability to change the design.

**Comment by ajeetku** [comment]
- [ ] Add option to give name or numbering to each module to identify

**Comment by ahmedkaludi** [comment]
http://take.ms/icQeI
add description like, this extension requires AMP Contact Form 7 or Gravity Forms Extension. 

both names should have the links to the extension page. and 

If none of the form plugin is activated then the select box should not the empty, it should be hidden.

**Comment by ahmedkaludi** [comment]
- [ ] Labels should have the style

- [ ] Duplicate icon on module should have a class

- [ ] The links of proper extensions should be added on the names: http://take.ms/p2kL1
