### ISSUE TITLE
UTM Parameters not working properly

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2223]
https://www.outdoorphoto.co.za/blog/fathers-day-giveaway/?utm_source=Facebook&utm_medium=Wallpost&utm_campaign=DJIGiveaway&utm_content=04-06-18

Whenever the above link is opened in Non-AMP it contains the UTM Parameters. 
When the same link is opened in AMP page, it is removing the UTM Parameters which is the major concern of the Client.

Reference: https://secure.helpscout.net/conversation/594165298/27439?folderId=2090441

**Comment by ahmedkaludi** [comment]
Similar https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1771

**Comment by MohammedKaludi** [comment]
We have added this feature to the plugin and this feature will be pushed in next update, which we are planning to release on 25th June.

Closing the ticket.
