### ISSUE TITLE
Feature Images are not displaying in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2224]
In some cases, the Feature Images are not displaying in AMP version.

- [x] https://secure.helpscout.net/conversation/589041734/26878?folderId=1914712

- [x] https://secure.helpscout.net/conversation/582856133/26318?folderId=1914712

- [x] https://secure.helpscout.net/conversation/594952265/27511?folderId=1914716

**Comment by MohammedKaludi** [comment]
:+1:
