### ISSUE TITLE
Forms Shortcodes are not Shows in in footer Widgets

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2226]
If we directly print dynamic sidebar it renders the Html form, but after sanitizing this output complete form elements are removed

**Comment by Sejiro-Hiko** [comment]
Still the same issue @ajeetku

**Comment by MohammedKaludi** [comment]
reuse `	add_filter('amp_blacklisted_tags','ampforwp_sidebar_blacklist_tags');`

**Comment by MohammedKaludi** [comment]
:+1:
