### ISSUE TITLE
Ads display error

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2227]
Adsense problem with RTL & menu in the Arabic language

Ref: https://secure.helpscout.net/conversation/590799201/27070?folderId=2075531

**Solution:** Add Source code -      .amp-ad-wrapper{direction:ltr;}       in Custom CSS

**Comment by Sejiro-Hiko** [comment]
apparently, the error is only in SWIFT while using RTL

**Comment by MohammedKaludi** [comment]
the condition added will only work for AD 1, not for all ads. suggest you to remove the condition so it can work with all ads.

**Comment by MohammedKaludi** [comment]
Fixed in #2138
