### ISSUE TITLE
AMP Carousel for AMP Page Builder

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2228]
This user is facing issues while adding the AMP Carousel code directly into the website. The code is given below   https://ampbyexample.com/components/amp-carousel/#supported-contents,

Reference: https://secure.helpscout.net/conversation/595508321/27559/?folderId=1060556

<amp-carousel width="450" height="300"><amp-img src="http://cm2.navazon.com/wp-content/uploads/2018/05/luxury-treatment-center-mobile.jpg" width="450" height="300"></amp-img><amp-img src="http://cm2.navazon.com/wp-content/uploads/2018/05/for-you-mobile.jpg" width="450" height="300"></amp-img><amp-img src="http://cm2.navazon.com/wp-content/uploads/2018/05/for-a-loved-one-mobile.jpg" width="450" height="300"></amp-img></amp-carousel>

I've updated the user that a ticket is createdand we are working on it.

**Comment by ahmedkaludi** [comment]
@merajali294 please share the reference link here

**Comment by ahmedkaludi** [comment]
@ajeetku Do consult with me when you are starting this ticket.

**Comment by ajeetku** [comment]
Need to add tags & attributes sanitizers so it will add scripts automatically

**Comment by MohammedKaludi** [comment]
:+1: Working perfectly, tested by adding many elements from https://ampbyexample.com/#components and its working smoothly.
