### ISSUE TITLE
Comments to be displayed on blog posts, but not in pages.

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2229]
need an option to disable the comments on non-blog pages. Comments to be displayed on blog posts, but not in pages.

Ref: https://secure.helpscout.net/conversation/594289164/27458?folderId=1060551

**Comment by ahmedkaludi** [comment]
We need to create an option to enable disable on posts and pages

**Comment by MohammedKaludi** [comment]
When turning off comments for one post type then its throwing an error, that script is loading but the component is not loading. To test enable facebook comments and check.

**Comment by MohammedKaludi** [comment]
Change the name of the function to `ampforwp_get_comments_status()`

Also when you  enable pagebuilder on particular page, extra fb comments script is loading.

**Comment by RajuJeelaga** [comment]
Are comments **Disabled** by default?  Because I just checked and they were disabled by default,

**Comment by MohammedKaludi** [comment]
👍

**Comment by MohammedKaludi** [comment]
As per AMP standards, we cannot use amp-notification and amp-consent togeather, so when GDPR is enabled then amp-notification is turned off.

Closing the ticket.
