### ISSUE TITLE
'''Google Tag Manager not working properly'''

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2230]
When the user is viewing non-AMP pages he is able to get the  bounce rate perfectly in analytics. But when the user is viewing the same content in AMP page the bounce rate is almost zero. He wants to get this fixed. Look into this matter immediately.

Reference: https://secure.helpscout.net/conversation/594151922/27434?folderId=2090441

**Comment by ahmedkaludi** [comment]
Please share the reference link

**Comment by ahmedkaludi** [comment]
Not enough data for this ticket. Contacting customer to debug this issue.
