### ISSUE TITLE
When GDPR enabled for EU then the data-block-on-consent is added for all countries

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#2232]
the above case causing the embedded components (such as Twitter, Instagram, etc) not to work.

**Comment by Zabi09** [comment]
Ref: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2240

**Comment by MohammedKaludi** [comment]
This has been fixed.
