### ISSUE TITLE
User requesting to create AMP page to be displayed as subdomain amp.website.com

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2236]
The user wants to make AMP pages displayed as amp.mboutiquehotels.com without affecting SEO.

Ref: https://secure.helpscout.net/conversation/596537482/27645/?folderId=1060551

**Comment by ahmedkaludi** [comment]
@MohammedKaludi @ajeetku @Sejiro-Hiko @MARQAS 

What do you guys think of this feature, How can we achieve this?

**Comment by ahmedkaludi** [comment]
**REVIEW:**

- [ ] once the option is enabled, there should be a field which allows them to change the subdomain name, for example (m.domain.com) - a lot of users wants to use this feature but with M.dot

**Comment by ahmedkaludi** [comment]
REVIEW:

- [ ] Pagination doesn't have the M dot: http://take.ms/yHZ8H - therefore, the AMP is not working on it.

**Comment by ahmedkaludi** [comment]
Reviewed.

**Comment by TMsravan** [comment]
Another user requesting for the same feature:
https://secure.helpscout.net/conversation/1031024372/102236?folderId=1060554

**Comment by ahmedkaludi** [comment]
its now available at https://ampforwp.com/addons/subdomain-endpoints-for-amp/
