### ISSUE TITLE
PHP 7 Compatibility WP Engine support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#224]
https://wordpress.org/plugins/php-compatibility-checker/

**Comment by khaledMohammed000** [comment]
#194

**Comment by khaledMohammed000** [comment]
@nicholasgriffintn Can you please check this and let me know if the files are PHP 7 compatible , I have added new files from Redux Core

I would really appreciate your comments 👍
