### ISSUE TITLE
Youtube videos are not rendering in AMP version

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2240]
Youtube video is not rendering in AMP - https://staging.osv.ltd.uk/new-test-amp/amp/

Ref: https://secure.helpscout.net/conversation/586257505/26644?folderId=673452

**Comment by ahmedkaludi** [comment]
https://www.scholarshubafrica.com/amp/ ads

**Comment by Zabi09** [comment]
Ref: https://secure.helpscout.net/conversation/595419076/27552?folderId=673452

**Comment by MohammedKaludi** [comment]
This is resolved in the recent update.
