### ISSUE TITLE
Pagination Issue in AMP.

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2241]
Pagination is not working in the AMP.

Additional observation: "amphtml" is not rendering in the Non-AMP of https://englishtown.staging.wpengine.com/blog/

REF: https://secure.helpscout.net/conversation/594277206/27456?folderId=1680011

**Comment by Sejiro-Hiko** [comment]
Fixed the issue on users end by using `init `hook instead of `admin_init` for the function `ampforwp_add_custom_rewrite_rules`

**Comment by MohammedKaludi** [comment]
:+1: This will fix the issue.
