### ISSUE TITLE
In page builder, Text module, when ever added the CF7 Shortcode in the module, Textarea is not showing.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2242]
In page builder, Text module, when ever added the CF7 Shortcode in the module, Textarea is not showing.

For Reference, check this....
https://monosnap.com/file/3RFP0MmACVu1ymHn23iFw6WKB2fIPy

**Comment by ahmedkaludi** [comment]
This was reported by @RajuJeelaga 

I am not sure if this is really related to the core or the CF7 form, @Sejiro-Hiko check and see how we can resolve this.

**Comment by Sejiro-Hiko** [comment]
@ahmedkaludi just tested on my end and it's working fine but will discuss with @RajuJeelaga about the scenarios where we can recreate the issue.

**Comment by MohammedKaludi** [comment]
:+1: Closing the ticket as the issue seems to be fixed.
