### ISSUE TITLE
Problem in Post Pagination in the last version

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2243]
Whenever the user is accessing this web page, when clicked on the next word the content is disappearing.

https://filforex.com/financial-mistakes/amp/

User wants the content to displayed on the AMP Page properly, updated User that ticket has been created and our team is working on it.

Reference: https://secure.helpscout.net/conversation/597290500/27715/

**Comment by Alpacah** [comment]
Exact same issue here: 
Working first page: https://risific.fr/bienvenue-en-prepa/amp
Any other page show a void content :(

**Comment by MohammedKaludi** [comment]
@Alpacah is the AMP plugin updated to the latest version?

As I'm not able to recreate the issue in my localhost.

**Comment by Alpacah** [comment]
@MohammedKaludi the current version is "Version 0.9.96", I think it's the lastest as I can't update it.

**Comment by MARQAS** [comment]
#2253 Should solve this issue as well.

**Comment by MohammedKaludi** [comment]
:+1:  Working perfectly with Custom Frontpage and with normal posts and pages with all designs.

**Comment by jeannieh** [comment]
[](https://www.hillwebcreations.com/) now has an additional ending of "amp/page/2/", which generates a 404. Any ideas on how to correct it and how it was generated in the first place?
