### ISSUE TITLE
User wants all the posts to be shown only on the current page. (Load more feature)

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2244]
Currently the posts are viewed by clicking on the Next Button here  https://www.yeniarabafiyati.com
but User wants it to be displayed continuously on scroll like : www.sozcu.com.tr

Reference: https://secure.helpscout.net/conversation/597335044/27734?folderId=2090441

Updated User about the ticket is created and our team is working on it.

**Comment by Zabi09** [comment]
Escaping is missing

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
