### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by nicenicepretty** [ahmedkaludi/accelerated-mobile-pages#2245]
This plugin is causing a 403 error for me. The web host has confirmed that it is this plugin that's causing the issues. When I edited the settings I got locked out the site, and when the host disabled the plugin and I cleared my cookies I no longer got a 403 error. I reactivated the plugin and tried editing the settings, and again was locked out with a 403 error. Help?

**Comment by nicenicepretty** [comment]
It appears the conflict was caused by Glue for Yoast not playing nice with AMP for WP. Is Glue for Yoast unnecessary to use with this plugin?

**Comment by MohammedKaludi** [comment]
@nicenicepretty Glue is not required as AMPforWP is fully compatible with Yoast SEO plugin
