### ISSUE TITLE
Read more button feature for post [single page]

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2246]
Read more button feature for the post.

Ref: https://secure.helpscout.net/conversation/592605980/27294?folderId=1914716

**Comment by MARQAS** [comment]
![sneak-peek](https://user-images.githubusercontent.com/15303814/42568125-aa7cc98a-8529-11e8-8502-d5523388b2a7.gif)

**Comment by MARQAS** [comment]
@MohammedKaludi and @ahmedkaludi, any idea on how to describe this feature or add this GIF in the options panel?

**Comment by MohammedKaludi** [comment]
@MARQAS need to make the text translatable
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4f5204fcfae5bbbf2d7e387892da94481ae19118#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7629

**Comment by ahmedkaludi** [comment]
**REVIEW:**

- [ ] We have .hide{display:none} in all the designs, except D3, so I think we can just add it when D3 is enabled, not for all the designs,

- [ ] fader-btn-container, rename this class to fd-b-c 

- [ ] fader-btn to fd-b

- [ ] .contentHidden to fd-h

**Comment by ahmedkaludi** [comment]
Reviewed

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
