### ISSUE TITLE
Content is not rendering in AMP when the Page of Non-AMP is built by using the WPBakery Page Builder

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2247]
Content is not rendering in AMP when the Page of Non-AMP is built by using the WPBakery Page Builder
REF: https://secure.helpscout.net/conversation/594435928/27482?folderId=1680011

**Comment by Sejiro-Hiko** [comment]
the issue was user using the "WPML for AMP" without using the "WPML" on his site.

**Comment by MohammedKaludi** [comment]
:+1:
