### ISSUE TITLE
The attribute 'onclick' may not appear in tag 'a'.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#225]
The attribute 'onclick' may not appear in tag 'a'.

https://search.google.com/search-console/amp?id=TEqtZ3MLz3M8uhvkM8F_Nw

https://wordpress.org/support/topic/google-amp-validation-errors/

**Comment by Abishekmaji** [comment]
I am also facing the same problem "The attribute 'onclick' may not appear in tag 'a'." ....how to solve this problem......Pls help me ....
