### ISSUE TITLE
Pagination issue/ displaying the same pages in every next page

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2250]
Can't browse to next page (pagination issue). Also, the same page is displaying when we moved to the next page. And do not show the posts of the third page and so on...

Ref: https://secure.helpscout.net/conversation/598632730/27856/

**Comment by Sejiro-Hiko** [comment]
unable to recreate the issue on my end ask the user to provide the staging environment.

**Comment by Sejiro-Hiko** [comment]
the issue could be similar that of #2241 but unable to confirm on the users end as there's no response from the user.

**Comment by MohammedKaludi** [comment]
Fixed in #2241.
Solution: added the function `ampforwp_add_custom_rewrite_rules` to `init` hook instead of `admin_init`
