### ISSUE TITLE
Feature for showing related items/post in paragraph wise

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2252]
Option for showing related post paragraph wise.

Ref: https://secure.helpscout.net/conversation/597567730/27761?folderId=673452

**Comment by merajali294** [comment]
Reference: https://secure.helpscout.net/conversation/583955720/26409?folderId=2090441

As the ticket is already created, another User wants to display the Inline Related Post above the last paragraph.

**Comment by ahmedkaludi** [comment]
**Reviewed**

- [ ] Inline Related Posts should not be a separate section, This feature should be inside Related Post section only: http://take.ms/jnilm

**Comment by ahmedkaludi** [comment]
Reviewed

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
