### ISSUE TITLE
Issues with pagination

### ISSUE THREAD

**Issue by Tymvie** [ahmedkaludi/accelerated-mobile-pages#2253]
Steps to reproduce:
Create a post, and a front page (and select the page in the General settings of the plugin):
```
one
<!--nextpage-->
two
```

|| swift| design 3 |
|-| ------------- | ------------- |
|the second page of the post|"two" (correct)|PHP Notice:  Undefined offset: 1 /design-3/elements/content.php on line 50 (incorrect) |
|front page|"one" (incorrect, no link to the next page)|"one two" (incorrect, pagination is ignored)|

**Comment by Alpacah** [comment]
I corrected the same problem, please see this post: [https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2243#issuecomment-398890600](https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2243#issuecomment-398890600)

**Comment by MARQAS** [comment]
This should now solve the problem.

**Comment by MARQAS** [comment]
@Alpacah Yup, that should solve half problem. 

If that code is removed then pagination will not work on Pages and FrontPage. 
Please check my last commit it will solve both the problems

**Comment by MohammedKaludi** [comment]
:+1: Working perfectly with Custom Frontpage and with normal posts and pages with all designs.

**Comment by MohammedKaludi** [comment]
#2168

**Comment by MohammedKaludi** [comment]
Post pagination is not working with posts. but working with pages and frontpage

**Comment by Tymvie** [comment]
Please pay attention to this comment https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2001#issuecomment-397790523 since this also related to pagination

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
