### ISSUE TITLE
/amp/ should not load when the category is disabled.

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2254]
When AMP support is off on Archives but still its load /amp/ at the recent article.

see this screenshot:  http://take.ms/pQbIIZ

Ref:  https://secure.helpscout.net/conversation/589143657/26886?folderId=1914712

**Comment by MARQAS** [comment]
Resolved: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4aa1b8170b7ba42d4edaf55a797c3cce1f4e9a1d#diff-d9e62bf7636c72ea611757e43f70c46e
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2279

**Comment by MohammedKaludi** [comment]
:+1:
