### ISSUE TITLE
Whenever user is trying to add the Marquee Code, he's getting the Validation Error

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2257]
Reference:  https://secure.helpscout.net/conversation/602863527/28151?folderId=1060551

User is getting error on the page as ""The tag 'marquee' is disallowed"" .
User Website Link : http://hunybunyworld.com/reality-behind-9999999-gems-coc/?amp

**Comment by MohammedKaludi** [comment]
@santosh8793 why it is in Review Q/A Queue directly?

**Comment by MohammedKaludi** [comment]
:+1: it's working properly.

`<marquee>` tag is converting into `<p>` tag and there is no validation error.
