### ISSUE TITLE
With Redux core plugin, AMP option panel design not loading

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2258]
redux core plugins load on top of all plugins function name: "load_first". this hook is load redux class on the top first.

**Comment by Sejiro-Hiko** [comment]
It appears that the issue has been resolved by namespace which was implemented by @MARQAS .

**Comment by ahmedkaludi** [comment]
we reviewed this on many customers sites, and it solved many of them's issue. Few errors came on the way but we seemed to tackle them, but this one still needs testing until the end.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
