### ISSUE TITLE
Additional image guidelines in structure data

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2259]
Ref:  https://secure.helpscout.net/conversation/590147328/27008?folderId=1914712

This is required by Google to be visible in all search results.
https://developers.google.com/search/docs/data-types/article#article_types

**Comment by ahmedkaludi** [comment]
REVIEW:

- [ ] AGAIN: the section name should be general structured data settings: http://take.ms/9j4Ch 

- [ ] You renamed the Default Structured data logo feild: http://take.ms/9j4Ch 

- [ ]

**Comment by MohammedKaludi** [comment]
Control is missing.

**Comment by pegazee** [comment]
"High-resolution Images" option is not working, If the image is less than 1200.

**Comment by MARQAS** [comment]
It is meant to be like that, that option will only work for large images, which are at least 1200px wide.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Read more text is not translatable 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f27eb2ab822630bc9ffbe5d3d1e9c17d70e73df0

**Comment by MohammedKaludi** [comment]
Done

**Comment by pegazee** [comment]
Pushed 0.9.97.44.2
