### ISSUE TITLE
The attribute 'value' may not appear in tag 'a' . 

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2262]
User is getting AMP Validation error  [[  The attribute 'value' may not appear in tag 'a'  ]] .
He uses Connections Business Directory plugin, gets Validation error.

Website Link : https://www.inhouseblog.com/legal-recruiter-directory/?amp

Helpscout reference:  https://secure.helpscout.net/conversation/598007085/27794/

**Comment by MohammedKaludi** [comment]
:+1:
