### ISSUE TITLE
Need to make the compatibility with The Voux theme

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2263]
The Voux theme and lazy load feature are not working in AMP as the images are not loading.

Ref:  https://secure.helpscout.net/conversation/601005121/28022?folderId=1914712

**Comment by ahmedkaludi** [comment]
Tested and working fine.

**Comment by MohammedKaludi** [comment]
@beingsmart3 if we are removing the code then why did we added it in the first place, and also if we just remove the code rightaway it will break the websites for which we added the code in the first place.

Need to find the proper solution.

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
