### ISSUE TITLE
Special character "|" issue in the twitter URL

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2264]
If there is any special character "|" in the title then the twitter URL is not working

Example:  http://take.ms/4a6mE
http://take.ms/zJOXI

Ref:  https://secure.helpscout.net/conversation/605075143/28324?folderId=1060551

**Comment by ahmedkaludi** [comment]
@ahmedkaludi can you have a look?

**Comment by ahmedkaludi** [comment]
@ahmedkaludi Yes, sure

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
