### ISSUE TITLE
Debug Error due to "AMP_QUERY_VAR" .

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2265]
Whenever the User is activating the AMP Plug-in he is getting the following Warning as Warning: Use of undefined constant AMP_QUERY_VAR - assumed 'AMP_QUERY_VAR' (this will throw an Error in a future version of PHP) in /home/oshers5/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/amp-helper-functions.php on line 44

Reference: 
https://secure.helpscout.net/conversation/605440518/28344/

**Comment by MohammedKaludi** [comment]
:+1:
