### ISSUE TITLE
Make the compatibility with the Author Simple Box Plugin

### ISSUE THREAD

**Issue by ghost** [ahmedkaludi/accelerated-mobile-pages#2268]
Make the compatibility with the "Author Simple Box" Plugin.
When the author is uploading his image from "Author Simple Box" Plugin then the author's image is not showing in AMP.

REF: https://secure.helpscout.net/conversation/599214245/27901/

**Comment by MohammedKaludi** [comment]
use a built in function
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e41e842df8cfb38716fb1eee9c636cdfdb24564f#diff-66456bcdcc1e8a0ec3147375393a64a0R71

**Comment by MohammedKaludi** [comment]
:+1: ready to push

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
