### ISSUE TITLE
In all the designs it should have the capability to display the full post

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2269]
In all designs, if a full post is set as a tag then it should have the capability to display the full post

Ref:  https://secure.helpscout.net/conversation/576223040/25804?folderId=1914712

**Comment by Sejiro-Hiko** [comment]
For now I've added only for D1,D2 and D3.

**Comment by MohammedKaludi** [comment]
@ahmedkaludi needs styling for all the designs

**Comment by Sejiro-Hiko** [comment]
@ahmedkaludi can you check it now?

**Comment by RajuJeelaga** [comment]
@MARQAS @ahmedkaludi In full post Design the gallery is not showing...
Please see this. https://monosnap.com/file/MYeFK9NMmVHrxpjFxGRFRxhVO1tenk

**Comment by ahmedkaludi** [comment]
**REVIEW:**

- [ ] ( @MARQAS ) Gallery is not showing in the full content: https://monosnap.com/file/MYeFK9NMmVHrxpjFxGRFRxhVO1tenk 
- [ ] ( @MARQAS ) Swift needs the loop to be added
- [ ] ( @RajuJeelaga ) after swift loop is added, we need to style it accordingly.

**Comment by MARQAS** [comment]
Breaking if there are components(iframe, video, audio, etc) in the content

**Comment by MohammedKaludi** [comment]
Further development has been stoped on this ticket. 

Will start again if we see any requirement or any feedback from the community to built this feature.
