### ISSUE TITLE
Text is not break into next line while there is no space between the text in custom AMP Editor

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2270]
if you write content [text] in the custom AMP editor without space between the text then the text goes out of the screen, it should break into next line so all text content should be visible.

screenshot: http://take.ms/cUwfO

Ref: https://wordpress.org/support/topic/bug-with-wrap-text-in-blog-posts/

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Breaking in related posts: http://take.ms/AEtlY
Design: Swift

**Comment by MohammedKaludi** [comment]
It still breaks design 2 and 3. Its now working fine in D1 and swift.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.12
