### ISSUE TITLE
When Notice bar and GDPR is enabled, user getting <amp-consent> error .

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2271]
Description: User is having issue with the GDPR is enabled in a theme created from scratch.

Reference:  
https://secure.helpscout.net/conversation/597523519/27755?folderId=2090441

**Comment by MARQAS** [comment]
Resolved here: #2275

**Comment by ahmedkaludi** [comment]
As per AMP standards, we cannot use amp-notification and amp-consent togeather, so when GDPR is enabled then amp-notification is turned off. 

Closing the ticket.

**Comment by MohammedKaludi** [comment]
As per AMP standards, we cannot use amp-notification and amp-consent togeather, so when GDPR is enabled then amp-notification is turned off.

Closing the ticket.
