### ISSUE TITLE
Create an option such that whenever a user wants to choose the elements to which he wants to add the "data-block-on-consent" attribute through filters, hooks.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2272]
Reference: https://secure.helpscout.net/conversation/597523519/27755?folderId=2090441

1. User has created his theme using Scratch whenever he is enabling GDPR and Notice Bar he is facing an error. 

2. Now he wants  to choose the elements to which he wants to add the "data-block-on-consent" .

**Comment by Sejiro-Hiko** [comment]
this filter `ampforwp_embedd_attrs_handler` can be used to add `data-block-on-consent`

**Comment by MohammedKaludi** [comment]
:+1:
