### ISSUE TITLE
Read more button for  post on blog page

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2273]
Read more button on the blog page for posts.

Ref: https://wordpress.org/support/topic/feature-requests-151/

**Comment by MohammedKaludi** [comment]
@ahmedkaludi need your review in design for read more text.

**Comment by ahmedkaludi** [comment]
- [ ] There should be an option under AMP > Design > Homepage > 'Loop Display Controls' called "Read More Link"

- [ ] by default, this option should be off, if they want, they can enable it

**Comment by ahmedkaludi** [comment]
- [ ] There should be a space between the excerpt and Read more link: http://take.ms/nAxXK

**Comment by MohammedKaludi** [comment]
:+1: code will be pushed in 0.9.97.16

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
