### ISSUE TITLE
Post Pagination is not working from 0.9.86 version in all 3 designs but working in Swift theme.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2278]
Whenever User clicks on the ""2nd page"" of the website, the text disappears.

Reference: https://secure.helpscout.net/conversation/597290500/27715?folderId=2090441

**Comment by Sejiro-Hiko** [comment]
The post pagination is working in All designs of the 0.9.97 developmental version will check this once the user updates to the latest version of the plugin.

**Comment by merajali294** [comment]
I've tested at User's end and on Ver 0.9.97, it's working and the issue is resolved.

**Comment by MohammedKaludi** [comment]
:+1:
