### ISSUE TITLE
Category Labels are Clickable on Swift Homepage even Archive support is off

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2279]
Category Labels are Clickable on Swift Homepage even Archive support is off

http://take.ms/I4Wj0

**Comment by santosh8793** [comment]
I have added responsive sidebar menu functionality using walker class, some commented styles are there in style.php and menu.php which are needed to be tested for any design issues

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: code will be pushed in 0.9.97.16

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
