### ISSUE TITLE
Above Loop and Below Loop Sidebar Widget area is not connected with Swift theme

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2280]
Above Loop and Below Loop Sidebar Widget area is not connected with Swift theme

http://take.ms/2ldtv

**Comment by MohammedKaludi** [comment]
http://take.ms/ZNFVC

**Comment by MohammedKaludi** [comment]
:+1: can be pushed in 0.9.97.16

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
