### ISSUE TITLE
Google Fonts deactivation

### ISSUE THREAD

**Issue by JWHBerlin** [ahmedkaludi/accelerated-mobile-pages#2283]
In the actual version, Google Fonts are loaded. In case of GDPR it is not allowed to use Google Fonts without opt-in. Is it possible to add a feature for local loading Fonts or deactivate Google Fonts?

**Comment by Sejiro-Hiko** [comment]
@JWHBerlin you mean that when GDPR is enabled the Google Fonts should be deactivated or you want an entirely separate option to deactivate Google Fonts irrespective of GDPR option?

**Comment by JWHBerlin** [comment]
In my opinion, in GDPR-Mode Google Fonts could be automatically disabled.

**Comment by Sejiro-Hiko** [comment]
@JWHBerlin thanks for the reply I got your point and will start working towards a good solution for such situations.

**Comment by ahmedkaludi** [comment]
**REVIEW:**
Google fonts is not behaving properly, We will tackle it in the #2283 - After that, we will review it.

**Comment by Zabi09** [comment]
We will tackle it in the #2122 - After that, we will review it.

**Comment by ahmedkaludi** [comment]
We are going to have an option to turn off Google fonts in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2122

As far as the GDPR for Google fonts, we are considering a better solution in the future, but there's no ticket for it yet.
