### ISSUE TITLE
Aq_Resize.process() errors for images hosted on CDN

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2285]
Ref:  https://wordpress.org/support/topic/aq_resize-process-errors-for-images-hosted-on-cdn/

https://secure.helpscout.net/conversation/605631781/28381?folderId=1914712

**Comment by Sejiro-Hiko** [comment]
the issue seems to from the theme called "bitz" as they too have the file `aq_resize.php` where they throw the exception. asked user to change the theme for debugging purpose and check the error logs.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
