### ISSUE TITLE
AMP by Automattic Compatibility 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2287]
AMP by Automattic Compatibility

**Comment by MARQAS** [comment]
Earlier the Priority of 'amp_render' was set to 0 to avoid conflict with AMP, but it was causing errors with PageBuilders as it getting rendered very early. To avoid such errors Priority is changed to default and removed the 'amp_render' of AMP.
Also made some changes to resolve warnings.

**Comment by ahmedkaludi** [comment]
@MARQAS Need to discuss it with you. Let me know when you are working on this.

**Comment by MohammedKaludi** [comment]
Throwing error


( ! ) Fatal error: Call to undefined function AMPforWP\AMPVendor\ampforwp_findInternalUrl() in C:\wamp\www\1\wp-content\plugins\accelerated-mobile-pages\includes\vendor\amp\includes\sanitizers\class-amp-blacklist-sanitizer.php on line 39
--

**Comment by Zabi09** [comment]
Fatal error: Uncaught Error: Call to undefined function ampforwp_levelup_compatibility() in C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\admin-config.php:3292 Stack trace: #0 C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php(449)

**Comment by syedimran22** [comment]
@MARQAS  Everything is working fine except one validation error The extension 'amp-next-page' was found on this page, but is unused. Please remove this extension. 
If Infinity scroll option is enabled before activating amp plugin.

**Comment by pegazee** [comment]
- [ ] Fatal error: Uncaught Error: Call to undefined function ampforwp_wp_kses() in C:\newxampp\htdocs\wp-2\wordpress-4.8.1\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\change-log.php:80 Stack trace: #0 C:\newxampp\htdocs\wp-2\wordpress-4.8.1\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\welcome.php(72): require() #1 C:\newxampp\htdocs\wp-2\wordpress-4.8.1\wordpress\wp-includes\class-wp-hook.php(286): ampforwp_welcome_screen_content('') #2 C:\newxampp\htdocs\wp-2\wordpress-4.8.1\wordpress\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 C:\newxampp\htdocs\wp-2\wordpress-4.8.1\wordpress\wp-includes\plugin.php(465): WP_Hook->do_action(Array) #4 C:\newxampp\htdocs\wp-2\wordpress-4.8.1\wordpress\wp-admin\admin.php(253): do_action('amp_page_ampfor...') #5 {main} thrown in C:\newxampp\htdocs\wp-2\wordpress-4.8.1\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\change-log.php on line 80

Screenshot: https://take.ms/ASo6O

**Comment by syedimran22** [comment]
- [ ] [ @MARQAS ] [AMP-Woocommerce-pro] 
Warning: Use of undefined constant AMP__DIR__ - assumed 'AMP__DIR__' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\imran\wp-content\plugins\amp-wc-pro\include\class-amp-wc-blacklist.php on line 2

Fatal error: Uncaught Error: Class 'AMPFORWP_Content' not found in C:\xampp\htdocs\imran\wp-content\plugins\amp-wc-pro\include\single-page-cart-form.php:143 Stack trace: #0 C:\xampp\htdocs\imran\wp-content\plugins\amp-wc-pro\templates\content.php(25): include_once() #1 C:\xampp\htdocs\imran\wp-content\plugins\accelerated-mobile-pages\includes\vendor\amp\includes\class-amp-post-template.php(445): include('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\imran\wp-content\plugins\accelerated-mobile-pages\includes\vendor\amp\includes\class-amp-post-template.php(143): AMPforWP\AMPVendor\AMP_Post_Template->verify_and_include('C:\\xampp\\htdocs...', 'amp-wc-the-cont...') #3 C:\xampp\htdocs\imran\wp-content\plugins\amp-wc-pro\templates\single.php(32): AMPforWP\AMPVendor\AMP_Post_Template->load_parts(Array) #4 C:\xampp\htdocs\imran\wp-content\plugins\accelerated-mobile-pages\includes\vendor\amp\includes\class-amp-post-template.php(445): include('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\imran\wp-content\plugins in C:\xampp\htdocs\imran\wp-content\plugins\amp-wc-pro\include\single-page-cart-form.php on line 143

Fatal Error:  Uncaught Error: Call to undefined function ampforwp_url_controller()  
Fatal Error : Uncaught Error:  Call to undefined function ampforwp_amp_nonamp_convert() 

- [ ] [@MARQAS ] [Newspaper-AMP-Theme]

Isssue occuring when ampforwp, amp, amp newspaper theme active.

<b>Fatal error</b>:  Uncaught Error: Call to undefined function is_socialshare_or_socialsticky_enabled_in_ampforwp() in C:\xampp\htdocs\imran\wp-content\plugins\amp-newspaper-theme\template\style.php:574
Stack trace:
#0 C:\xampp\htdocs\imran\wp-includes\class-wp-hook.php(286): ampforwp_additional_style_custom_design(Object(AMPforWP\AMPVendor\AMP_Post_Template))
#1 C:\xampp\htdocs\imran\wp-includes\class-wp-hook.php(310): WP_Hook-&gt;apply_filters(NULL, Array)
#2 C:\xampp\htdocs\imran\wp-includes\plugin.php(465): WP_Hook-&gt;do_action(Array)
#3 C:\xampp\htdocs\imran\wp-content\plugins\amp-newspaper-theme\template\single.php(10): do_action('amp_post_templa...', Object(AMPforWP\AMPVendor\AMP_Post_Template))
#4 C:\xampp\htdocs\imran\wp-content\plugins\accelerated-mobile-pages\includes\vendor\amp\includes\class-amp-post-template.php(445): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\imran\wp-content\plugins\accelerated-mobile-pages\includes\vendor\amp\includes\class-amp-post-template.php(143): AMPforWP\AMPVendor\AMP_Post_Template-&gt;ver in <b>C:\xampp\htdocs\imran\wp-content\plugins\amp-newspaper-theme\template\style.php</b> on line <b>574</b><br />

After solving the above issue Site is getting blank.

- [ ] [@MARQAS ] [AMP-CF7]
Notice: AMPforWP\AMPVendor\AMP_Content_Sanitizer::sanitize was called incorrectly. Sanitizer (AMPFORWP_CF7_Blacklist) must extend `AMP_Base_Sanitizer` Please see Debugging in WordPress for more information. (This message was added in version 0.1.) in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 4196

- [ ] [@MARQAS ] [AMP-GRAVITY-FORMS]
Warning: Use of undefined constant AMP__DIR__ - assumed 'AMP__DIR__' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\wordpress\wp-content\plugins\amp-gravity-forms\amp-gravity-forms.php on line 38

Warning: Use of undefined constant AMP__DIR__ - assumed 'AMP__DIR__' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\wordpress\wp-content\plugins\amp-gravity-forms\class-amp-gravity-forms-

Notice: AMPforWP\AMPVendor\AMP_Content_Sanitizer::sanitize was called incorrectly. Sanitizer (AMP_GRAVITY_Blacklist) must extend `AMP_Base_Sanitizer` Please see Debugging in WordPress for more information. (This message was added in version 0.1.) in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 4196

- [ ] [@MARQAS ] [AMP-Wpforms]
Notice: AMPforWP\AMPVendor\AMP_Content_Sanitizer::sanitize was called incorrectly. Sanitizer (AMPFORWP_Wpforms_Blacklist) class does not exist Please see Debugging in WordPress for more information. (This message was added in version 0.4.1.) in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 4196

- [ ] [@MARQAS ] [AMP-OPT-IN]
Notice: AMPforWP\AMPVendor\AMP_Content_Sanitizer::sanitize was called incorrectly. Sanitizer (AMPFORWP_Blacklist_Sanitizer) must extend `AMP_Base_Sanitizer` Please see Debugging in WordPress for more information. (This message was added in version 0.1.) in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 4196   (in ampbyautomatic site)

**Comment by ahmedkaludi** [comment]
- [ ] When we activate the "AMP by Automattic" then it should give a notice: AMP by Automattic is activated so the AMPforWP is now in the "Addon Mode".

**Comment by MARQAS** [comment]
- [ ] Add frontend styling in master

**Comment by pegazee** [comment]
- [ ] Need to add "Available in Standalone Mode" ( Screenshot: https://take.ms/9PUrG ) option on 'Settings' tab.
Screenshot: https://take.ms/e0KXT

**Comment by MohammedKaludi** [comment]
All the code has been merged into master will push this ticket in 0.9.97.47

**Comment by pegazee** [comment]
Pushed in 0.9.97.47

**Comment by nicopujol** [comment]
Just seeing this update on the latest build. 
- When used standalone (no Automattic AMP plugin), what version of the core AMP plugin are you embedding in AMPforWP?
- Do I understand correctly that AMPforWP can be used as an add-on with core AMP plugin as primary? If so, does it leverage the latest core plugin files instead of the embedded files?

**Comment by ahmedkaludi** [comment]
@nicopujol 
1. Standalone has 0.4 with few tweaks
2. Absolutely correct! It leverages the latest version of AMP core

**Comment by nicopujol** [comment]
Great. Given how much progress AMP core has done since 0.4, it seems that starting now it makes sense to load the Automattic plugin + AMPforWP at the same time to benefit from all the advances in AMP core?

**Comment by ahmedkaludi** [comment]
Yes

**Comment by nicopujol** [comment]
We'll give it a try. It's potentially a huge upgrade in how AMPforWP can be used.
