### ISSUE TITLE
Pagination is not working on date archive

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2289]
Pagination is not working on date archive [showing the same posts]

Ref: https://secure.helpscout.net/conversation/608230947/28728/?folderId=673452
Ref: localhost

**Comment by MohammedKaludi** [comment]
There is the static code in year and month https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/55f5fbf3de467e8a2af6d3c5b5c75121853b445b#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R187

**Comment by MohammedKaludi** [comment]
Pagination working but content not loading in swift theme http://take.ms/3kcKQ

**Comment by Sejiro-Hiko** [comment]
@MohammedKaludi doesn't that require a different issue ticket than this one?

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko Query is not working properly, please contact me so I can show what is breaking.

**Comment by MohammedKaludi** [comment]
Working now after resaving the permalink.

**Comment by MohammedKaludi** [comment]
:+1: Can be pushed.

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
