### ISSUE TITLE
Need to show index/noindex when enabling the options in SEO

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2290]
- [x] The user should get to know the usage of enabling the option when the options in Advanced Indexing is enabled. (Should get a message of index/no-index on hovering the options)

- [x] Archive subpages (sitewide) option is not working in design 3

- [x] Validation issue on noindex.
When  we are doing noindex to index the validation issue gets fix, but what about the others users who dont want to index those pages? they will get the missmatch validation error then they have to turn off the amp on that page.

**Comment by ahmedkaludi** [comment]
reviewed.

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
