### ISSUE TITLE
Convert to WP Option is displayed in Swift Theme, but not in Design 3.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2291]
Reference: https://secure.helpscout.net/conversation/607273110/28535?folderId=2090441

This user was using Swift Theme and enabled Convert to WP Option then forgot to disable it and switched to Design 3 in which Convert to WP Option  is not available due to which he was facing lot of errors.

Now Disabled the Convert to WP Option in Swift Theme , enabled AMP Takeover and again switched to Design 3.

Everything is working fine.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: can be pushed in 0.9.97.16

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
