### ISSUE TITLE
Need to have only one text-domain in the string of the plugin 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2292]
Need to have only one text-domain in the string of the plugin 
Screenshot: http://take.ms/PFJiU
Ref: https://secure.helpscout.net/conversation/605624575/28380?folderId=673457

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: can be pushed in 0.9.97.16

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
