### ISSUE TITLE
Subscribe to Notification.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2295]
Option to be created is User should get the Push Notification in the Header part and also in the Sticky Part as well.

Reference: https://secure.helpscout.net/conversation/608104433/28668?folderId=2090441

**Comment by MARQAS** [comment]
Lot of Frontend work is required.
And let me know when the frontend part is done, so I can test it on the live server.

**Comment by ahmedkaludi** [comment]
- [ ] Debug error in this ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2555

**Comment by ahmedkaludi** [comment]
we won't be working on this.
