### ISSUE TITLE
compatibility for YouTube embed plugin 

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2298]
compatibility for youtube embed plus plugin [https://wordpress.org/plugins/youtube-embed-plus/]

Ref: https://wordpress.org/support/topic/is-youtube-pro-12-working-with-amp/

**Comment by beingsmart3** [comment]
One more issue:   https://secure.helpscout.net/conversation/671959096/35441?folderId=1914712

**Comment by Zabi09** [comment]
Tested the issue on the users end also and it was working fine.
