### ISSUE TITLE
Performance issues.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2299]
1. Reference: https://secure.helpscout.net/conversation/606583543/28481?folderId=2090441

**Comment by beingsmart3** [comment]
2. https://secure.helpscout.net/conversation/599346811/27907?folderId=1914712

Performace issue and there are 87,211 posts and he is excluding the certain categories.

see this screenshot:  http://take.ms/mzL1m

**Comment by Sejiro-Hiko** [comment]
the first issue has been addressed in the following ticket #2148
