### ISSUE TITLE
Embedded YouTube Fails Validation for "iframe" Tag Use

### ISSUE THREAD

**Issue by dayhawkkim** [ahmedkaludi/Accelerated-Mobile-Pages#23]
I have one YouTube video that was embedded using [youtube ...] shortcode from Jetpack. (I've also tried the [embed ...] shortcode.) They render eventually with an iframe tag. 

I'm getting the following message: 

The tag 'iframe' is disallowed. DISALLOWED_HTML_WITH_AMP_EQUIVALENT

AMP is asking for <amp-youtube..../> plus the .js snippet.

The routine YouTube embed, without any shortcode, returns the same error. 

In addition, both embed methods results in: 

The attribute 'style' may not appear in tag 'span'. DISALLOWED_HTML

Thanks.

**Comment by ahmedkaludi** [comment]
iFrame support added. Thank you so much for reporting!
