### ISSUE TITLE
CSS fix for Cookies

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/Accelerated-Mobile-Pages#230]
Have a look at this http://take.ms/HLwE5

**Comment by khaledMohammed000** [comment]
@ahmedkaludi I need a bit of help from you on this

**Comment by nicholasgriffintn** [comment]
@khaledMohammed000 I'm unsure what the problem is for the CSS here, looking at it myself, it seems to work as it should.

**Comment by khaledMohammed000** [comment]
@nicholasgriffintn Thanx for commenting i didnt like the way the notification was getting shown ... I wanted to improve the CSS ....One more thing please try the new beta  and try to find bugs and Suggestions  https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/archive/0.8.9-beta.zip

**Comment by khaledMohammed000** [comment]
Obviously the user wont go till footer and then accept the notification or for that matter whenever the page loads it does not load from bottom ...
