### ISSUE TITLE
Bug in Facebook comments.

### ISSUE THREAD

**Issue by praderj** [ahmedkaludi/accelerated-mobile-pages#2300]
Hello Team.
Thank you for the awesome plugin. I have been using this plugin ever since I started using AMP. With the recent update, facebook comment seems to be not working. Google webmaster tools show this error "The mandatory attribute 'data-href' is missing in tag 'amp-facebook-comments'.". Kindly fix this issue. Thank you!

**Comment by ahmedkaludi** [comment]
Can you share the URL?

**Comment by praderj** [comment]
The Problem was resolved in an update and with the latest update, the problem is back again. You can see an example here https://www.catholicgallery.org/mass-reading/170220/amp/ .

**Comment by praderj** [comment]
I tried the AMP validator and it shows the following error.
![image](https://user-images.githubusercontent.com/5558747/42333456-66a95768-8098-11e8-84f7-70f3c265df64.png)

**Comment by MohammedKaludi** [comment]
@praderj we have just pushed an update, can you please update to the latest version and do let us if the issue is fixed?

**Comment by MohammedKaludi** [comment]
@praderj ping...

**Comment by MohammedKaludi** [comment]
Issue fixed and pushed the code.

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
