### ISSUE TITLE
Need to create an option to hide all posts (Individual AMP Post (Bulk Edit))

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2301]
Need to create an option to hide all the post naming Individual AMP Post (Bulk Edit) similar like which is made for Individual AMP Pages(Bulk Edit), where the bulk of posts should get hidden. Also, make sure to highlight the difference between them so that the users do not get confused.

Ref: https://secure.helpscout.net/conversation/610630499/29052?folderId=2075531

**Comment by MohammedKaludi** [comment]
Also, commit this ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2420

**Comment by Zabi09** [comment]
only few posts are hiding in amp not all the posts

**Comment by MARQAS** [comment]
We can add https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2433 instead of this which includes this option for all CPTs.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MARQAS** [comment]
Make sure to fix this typo when merging this ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b7c3b255f34959040e90feb22d0a56421b8ada7c

**Comment by MohammedKaludi** [comment]
Need to improve the method as the update should be done via AJAX and it should show the progress bar.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by WasimM3** [comment]
We are going to implement it on https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3571
