### ISSUE TITLE
No Index issue

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2303]
- [x] Find the value of the Seo Plugin Integration.

- [x] Need to add one more option of sequence integration in such a way that the user can select no integration option if they do not want to use it.

- [x] When both the third party SEO plugins and Advanced Indexing are in enabled status, the noindex issue should get fixed.

**Comment by Frenchomatic** [comment]
I agree - the button should be off by default so the SEO options already set for canonical pages in yoast, genesis or all in one SEO get rendered.

**Comment by MohammedKaludi** [comment]
DO NOT COPY THIS COMMIT "https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/756f7e0846e3dbe625462d93a90c521bd67c21a2" IN MASTER.

As we are remaining the control name globally, refixed it in this commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7c4192ce7113d1f9aa240b6dc0e61156de91ace5

**Comment by MohammedKaludi** [comment]
and use proper 'placeholder' key name in admin-config file

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cad34a4fe1d31baa4a6bba2158d3caf890cb66a3 need escaping

While merge need check https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9984a7ae33ff96c270678d06c1ab601a2a726825#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6194
`elseif ( 2 == ampforwp_get_setting('ampforwp-seo-selection')` there is no option with 2, its change in `aioseo`

**Comment by MohammedKaludi** [comment]
Ready to merge, but make sure this(check link) while merging.
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2303#issuecomment-522205673

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
