### ISSUE TITLE
AMP Take over is applying even on product when this option is enabled only for posts.

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2304]
REF: https://secure.helpscout.net/conversation/609140913/28874/?folderId=1680011

Steps to recreate the issue:
1)Enable the AMP take over only on Posts.
2)Disable the AMP on Pages and Archives
3)There should be no AMP woocommerce plugin.

Note: Whoever is working on this ticket please notify the customer that in which update version this issue is going to be fixed.

**Comment by MohammedKaludi** [comment]
:+1: ready to be pushed.

**Comment by MohammedKaludi** [comment]
:+1: can be pushed in 0.9.97.16

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
