### ISSUE TITLE
PageBulider getting following notices in old module

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#2305]
Notice: Undefined variable: repeaterUniqueId in C:\xampp\htdocs\wordpress496\wp-content\plugins\accelerated-mobile-pages\pagebuilder\inc\viewShowFrontData.php on line 901

Notice: Undefined variable: repeaterUniqueId in C:\xampp\htdocs\wordpress496\wp-content\plugins\accelerated-mobile-pages\pagebuilder\inc\viewShowFrontData.php on line 904

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: code will be pushed in 0.9.97.22

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
