### ISSUE TITLE
Sort Related Posts Randomly Not Working in Swift theme

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2308]
Sort Related Posts Randomly Not Working in Swift theme
Ref: https://secure.helpscout.net/conversation/601895491/28074?folderId=1932625

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
