### ISSUE TITLE
Fatal error in contact form module while ninja form or gravity form plugins is not available 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2310]
Fatal error in contact form module while ninja form or gravity form plugins is not available 
Screenshot: http://take.ms/bTiUJ
Ref:https://secure.helpscout.net/conversation/611670034/29168/?folderId=1932625

**Comment by MohammedKaludi** [comment]
:+1: well done @Zabi09 
Use single quote in `class_exists `
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/eeb2c143f6320b22ef9d327c98c930a34836f51e#diff-47ce7951ebd6ff204ab69e728e853983R48

**Comment by MohammedKaludi** [comment]
:+1:
