### ISSUE TITLE
In swift theme, when user ads the ad Above the Related Posts (Single Post); the content doesn't display

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2311]
In swift theme, when the user enables the ad **Above the Related Posts (Single Post)**; the content doesn't display. When disabled, the content displays.

Ref: https://secure.helpscout.net/conversation/611871311/29203?folderId=2075531

**Comment by Zabi09** [comment]
Duplicate ticket - #2318

**Comment by ahmedkaludi** [comment]
reviewd.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.12
