### ISSUE TITLE
Custom Fields with AMP

### ISSUE THREAD

**Issue by shtefcs** [ahmedkaludi/accelerated-mobile-pages#2312]
Hi Ahmed, 

Awesome plugin man. I am so excited to push my experiment to the productions. 

However, I got stuck with replacing *thumb link* with custom field, which is in this case url.

I am using **[Advanced Custom Field](https://wordpress.org/plugins/advanced-custom-fields/)s** and created custom field called `source_url`. I want to use it instead of thumbnail default post url. 

I figured that i need to edit *loop.php* file and located the `href` line.  
From the *Advanced Custom Field* documentation i found that i need to use this pieace of code  to show it in custom templates or where I want. `<?php the_field('source_url'); ?>`. I managed to make it work on other WP templates, but not with AMP. 

When I replace `'.amp_loop_permalink(true).'` with `<?php the_field('source_url'); ?>` I am getting  http error 500 on site.

This is how it looks. 

```
		if ( $thumb_url ) {

			echo '<'.$tag.' class="loop-img '.$tag_class.'">';

			echo '<a href="<?php the_field('source_url'); ?>">';

			echo '<amp-img src="'. $thumb_url .'" width="'.$thumb_width.'" height="'.$thumb_height.'" '. $layout_responsive .' class="'.$imageClass.'"></amp-img>';

			echo '</a>';

			echo '</'.$tag.'>';

		}

     } 

} 
```

I think this is basic syntax error, but since I didn't learn PHP and not writing the code (expect to edit some), I am not able to make it work.

I would appreciate for your guidance  @ahmedkaludi 

Peace,

**Comment by shtefcs** [comment]
This was the fix `echo '<a href="'.get_field('source_url').'" rel="nofollow">';` by the awesome @entrptaher

**Comment by MohammedKaludi** [comment]
great closing the ticket.
