### ISSUE TITLE
Beta Issues

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2315]

**Comment by merajali294** [comment]
- [ ] 1. https://monosnap.com/file/FDEOLShMQt23pfaTQqTBRJwsdKi5zq : 
Display should be called Visibility and it should be below the "Discussion Section"

**Comment by merajali294** [comment]
- [ ] 2. Header Design should not be displayed if it doesn't have Header designs (currently it's set to D3)

**Comment by merajali294** [comment]
- [ ] 3. Same thing with Footer Design as with Number 2 https://monosnap.com/file/JGMpmWDF1wgkftzjGkmk0D50IY5DCr

**Comment by merajali294** [comment]
- [ ] 4. Why is this outside https://monosnap.com/file/bJZB1n2byDsfe8QnBTS09y7UdhiwJX ?

**Comment by beingsmart3** [comment]
- [ ] 5. Warning: in_array() expects parameter 2 to be array,
see this screenshot:  http://monosnap.com/image/1HnrVdOMTwOWXjqhBQMoN8FNwAbZV4/

**Comment by ahmedkaludi** [comment]
We will continue this ticket in #2332
