### ISSUE TITLE
Need to solve the issue of json+ld with wprm plugin

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2316]
Resolve the error of Json+ld with WPrm plugin json

Ref:  https://secure.helpscout.net/conversation/611765346/29181?folderId=1914712

see this screenshot:  http://take.ms/3CHEO

`<script type="application/ld+json">{"@context":"http:\/\/schema.org\/","@type":"Recipe","name":"\u9ec4\u74dc\u7c89\u4e1d (hu\u00e1nggu\u0101 f\u011bns\u012b) - chinesischer Gurkensalat mit Glasnudeln","author":{"@type":"Person","name":""},"datePublished":"2018-06-22T16:06:57+00:00","description":"","image":["https:\/\/i1.wp.com\/einfachchinesischkochen.de\/wp-content\/uploads\/2018\/06\/chinesischer-Gurkensalat-mit-Glasnudeln-6.jpg?fit=600%2C400&ssl=1","https:\/\/i1.wp.com\/einfachchinesischkochen.de\/wp-content\/uploads\/2018\/06\/chinesischer-Gurkensalat-mit-Glasnudeln-6.jpg?resize=500%2C400&ssl=1","https:\/\/i1.wp.com\/einfachchinesischkochen.de\/wp-content\/uploads\/2018\/06\/chinesischer-Gurkensalat-mit-Glasnudeln-6.jpg?resize=500%2C375&ssl=1","https:\/\/i1.wp.com\/einfachchinesischkochen.de\/wp-content\/uploads\/2018\/06\/chinesischer-Gurkensalat-mit-Glasnudeln-6.jpg?resize=480%2C270&ssl=1"],"recipeYield":"2 Portionen","recipeIngredient":["50 g Glasnudeln","1  Salatgurke","3-4 Zehen  Knoblauch","5-8 K\u00f6rner  Szechuan Pfeffer","1-2 EL Pflanzen\u00f6l","1 EL Reisessig","1\/2 EL helle Sojasauce","1 Prise Zucker","1\/2 TL Salz oder noch weniger","1\/2 TL Sesam\u00f6l","optional: Chili\u00f6l oder Chilipaste"],"recipeInstructions":[{"@type":"HowToStep","text":"Die Glasnudeln im lauwarmen Wasser 10 Minuten einweichen. Dann im kochenden Wasser f\u00fcr 1 Minute kochen. Kalt abschrecken und abtropfen lassen."},{"@type":"HowToStep","text":"Knoblauch fein hacken oder pressen. Die Salatgurke waschen, in lange d\u00fcnne Streifen schneiden. Wenn es geht, d\u00fcnner als 5 mm, 6 cm \u2013 8 cm lang."},{"@type":"HowToStep","text":"Alle Zutaten f\u00fcr die Sauce zusammenmischen. In einer Sch\u00fcssel die abgetropften Glasnudeln und Gurke geben. Die Sauce darauf gie\u00dfen. Den fein gehackten Knoblauch am Ende darauf in die Mitte legen."},{"@type":"HowToStep","text":"Pflanzen\u00f6l im Wok oder in der Pfanne erhitzen, den Szechuan Pfeffer darin bis fast schwarz braten. Denn alles auf den Knoblauch gie\u00dfen."},{"@type":"HowToStep","text":"Den ganzen Salat durchmischen. Nach Bedarf noch mit Chili\u00f6l oder Chilipaste abschmecken. Fertig und guten Appetit!"}]}</script>`

**Comment by MohammedKaludi** [comment]
Fixed in #2346. Closing the ticket.
