### ISSUE TITLE
In swift theme, main content (texts) are not visible due to "Responsive ad unit"

### ISSUE THREAD

**Issue by StubRavi** [ahmedkaludi/accelerated-mobile-pages#2318]
In swift theme, After enabling the 'Responsive Ad Unit' (under the advertisement position setting), the content of the post doesn't show. Ads are visible and related posts are also visible ( with the thumbnail more than the screen size), but main content (texts) are not visible. I disabled the "Responsive ad unit" and now it is working like before.

**Comment by Sejiro-Hiko** [comment]
the issue is related to the div `sp-lt` should have `max-width`

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.12
