### ISSUE TITLE
Image light-box is being added in the footer section which is creating validation error.

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2319]
In Widget area, Image light-box trying to generate the lightbox to the social icons that are in the footer section and creating Image light-box validation error.

Ref: https://secure.helpscout.net/conversation/492871180/19662?folderId=2075531

**Comment by santosh8793** [comment]
I have tested this, it is working fine in our system, maybe we need to check this from the user end

**Comment by ahmedkaludi** [comment]
This was a one-off issue, which has been resolved on user's end.
