### ISSUE TITLE
Color picker for Footer Area

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2320]
People are demanding for Color picker for Footer Area

Ref:  https://secure.helpscout.net/conversation/612647582/29279?folderId=1914712

**Comment by MohammedKaludi** [comment]
missing default value, it is breaking when Empty is selected http://take.ms/Ovg3e 
and design specific defaults needed.

**Comment by MohammedKaludi** [comment]
1. http://take.ms/8FqZ6 and http://take.ms/z55gu
2. Use ampforwp_get_setting() to fetch the value instead $redux_builder_amp['ampforwp-footer-background-color-3']['color'] https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6171509267965c879ec1f644f1346cc5c7d4d3ad#diff-d2a448840c98f4c9bcf27aab39b04b83R149

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/670205f199c84e09c27234b4b8682d98b22ffd8d#diff-e57ec3310984798e175233ae89a68fdbR89


Empty check should be done above

**Comment by MohammedKaludi** [comment]
Need to sanitize color output.

**Comment by MohammedKaludi** [comment]
need to change the sanitization function, as the values from the options panel can be rgba and the function `sanitize_hex_color` will only work with hexadecimal values.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1fccc68167735a978a2b39b2cf2c2503defc8a7c#diff-b6b75f4287e169753316befbe71522b8R150

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: pushed in 0.9.97.41
