### ISSUE TITLE
if String in Structured data breaking the page and throwing fatal error (lance)

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2321]
if String in Structured data breaking the page and throwing a fatal error (lance ).

> Both of the pages that were not working because of the wrong Structured data value. You can see in this screenshot http://take.ms/gzXTc the same value is shown in both of the pages.  What AMPforWP plugin doing was, it was trying to add the values like publisher logo and other values in Structured Data. The current value in the Structured Data was "Walse" (I don't know where it came from), it was not able to add the value and hence throwing a fatal error.

line number 1489:
	        $metadata['publisher']['logo'] = array(
	          '@type'   => 'ImageObject',
	          'url'     =>  $structured_data_logo ,
	          'height'  => $ampforwp_sd_height,
	          'width'   => $ampforwp_sd_width,
	        );

need to wrap this code in `if ( isset( $metadata['publisher'] ) &&  $metadata['publisher'] ) {`

**Comment by MohammedKaludi** [comment]
:+1: code Pushed in 0.9.97.4

**Comment by MARQAS** [comment]
It was causing some issues. But it was resolved here #2360
