### ISSUE TITLE
The Lazy load images not loading in the AMP version when the user activate Customizr Theme. Need to add its compatibility.

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2322]
Lazy load images not loading in AMP when the Customizr Theme is Activated. Need to add its compatibility. No option of lazy load displays for the specific theme

Ref: https://secure.helpscout.net/conversation/612231120/29235?folderId=2075531

**Comment by Zabi09** [comment]
The issue was from the Lazy Load of "JPG, PNG Compression and Optimization" Plugin, So recreated the same on our localhost and also implemented the same on users end.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
