### ISSUE TITLE
AMP Pagebuilder modules and settings are loading By default

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2323]
Need to Resolve Performance:
1. All modules and settings are loading default. [Currently No restriction on modules] 
     Ex: Category module is loading all times and runs a gives a slow query
2. Backend: We can load get categories by AJAX [Result: If we do with ajax field will load easily ]

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/204ae39e28b934e7af661ffff48bcfae9dd9f25b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6629

**Comment by ajeetku** [comment]
Need to improve https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/204ae39e28b934e7af661ffff48bcfae9dd9f25b#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R719
1. BACKEND: is_admin() && On Edit Posts
2. FrontEND: is_singular[For both post & page]

**Comment by MohammedKaludi** [comment]
ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.54
