### ISSUE TITLE
When WooCommerce Product Slider is Installed , the Picture of Icons is not being displayed.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2325]
Reference: https://secure.helpscout.net/conversation/610623510/29051?folderId=2090441

When WooCommerce Product Slider is Installed, the Picture of Icons is not being displayed such as given below: https://monosnap.com/file/zVenNVeH5qQpcJviZYQnQhHJKJYMo5

When WooCommerce Product Slider is de-activated the Icons Tray Pictures are again displayed.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
