### ISSUE TITLE
Found Fatal error and Warnings in the debugging section.

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2327]
Here are the errors and working details.

[03-Jul-2018 12:27:07 UTC] PHP Warning:  Illegal string offset 'publisher' in /var/sites/c/counterinteriors.co.uk/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1403
[03-Jul-2018 12:27:07 UTC] PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in /var/sites/c/counterinteriors.co.uk/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php:1403
Stack trace:
#0 /var/sites/c/counterinteriors.co.uk/public_html/wp-includes/class-wp-hook.php(286): ampforwp_update_metadata('fasle', Object(WP_Post))
#1 /var/sites/c/counterinteriors.co.uk/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters('fasle', Array)
#2 /var/sites/c/counterinteriors.co.uk/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(216): apply_filters('amp_post_templa...', Array, Object(WP_Post))
#3 /var/sites/c/counterinteriors.co.uk/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(96): AMP_Post_Template->build_post_data()
#4 /var/sites/c/counterinteriors.co.uk/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/amp.php(86): AMP_Post_Template->__construct(294)
#5 in /var/sites/c/counterinteriors.co.uk/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1403

Ref: https://secure.helpscout.net/conversation/610400683/29039?folderId=2075531

**Comment by beingsmart3** [comment]
One More Ref:  https://secure.helpscout.net/conversation/616069391/29601?folderId=1914712

Fatal error: Cannot use string offset as an array in /home/trilliumeyecare/public_html/trilliumeyecare.com/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1489
