### ISSUE TITLE
WP Bakery Page builder is not working on Pages and Post in the Latest version of 0.9.97.3

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2330]
REF: https://secure.helpscout.net/conversation/609750688/28967?folderId=1680011

**Comment by githubjabbar** [comment]
https://secure.helpscout.net/conversation/609750688/28967?folderId=1680011#thread-1690428132

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by beingsmart3** [comment]
One more Ref:   https://secure.helpscout.net/conversation/623856477/30568?folderId=1914712

I've tried the beta 0.9.98 version also, but still, the wp baker content is not rendering in on the post.
