### ISSUE TITLE
“Recent Posts” padding is messed up, 

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#2331]
“Recent Posts” padding is messed up, no space between title and posts.
Also no space on left side. 
![0087d65e-fce5-4d13-951c-aca58a86a658](https://user-images.githubusercontent.com/40724154/42410715-184aae36-81f7-11e8-9dc5-cbd1418f927c.jpeg)
![51a64ea2-e4b8-4a71-9460-4410fbdba383](https://user-images.githubusercontent.com/40724154/42410731-59b366e2-81f7-11e8-99da-c9d81595c9bc.jpeg)

**Comment by SageFargo** [comment]
Open photo* thumbnail makes it look like there’s is space. View the full photo.

**Comment by SageFargo** [comment]
This issue is in-post, under “Related Posts.” It is the “Recent Posts” block.

**Comment by RajuJeelaga** [comment]
@SageFargo Hi Sage, Please check related post design in this Branch https://github.com/ahmedkaludi/accelerated-mobile-pages/tree/0.9.98 it is working, I test it. But this branch is still development, it is not released at, If you want to upload this, please go via FTP, (or) If you want to wait for a week the update will be release..

**Comment by SageFargo** [comment]
I heard it’ll be fixed with the next update, I’ve just updated and no luck :/
Could you look into this?

**Comment by MohammedKaludi** [comment]
@SageFargo this code will be pushed in 0.9.98 version.

**Comment by SageFargo** [comment]
Why so long tho?

**Comment by RajuJeelaga** [comment]
@SageFargo I think you didn't read my previous reply. 

I want you to test this code, get the beta version from: https://github.com/ahmedkaludi/accelerated-mobile-pages/tree/0.9.98

and then let us know if this fixes that specific issue on your end or not?

Once you confirm, then we will proceed with pushing the update.

**Comment by SageFargo** [comment]
Can you walk me through, real quick?

**Comment by ahmedkaludi** [comment]
@SageFargo Try it from: https://github.com/ahmedkaludi/accelerated-mobile-pages/archive/0.9.98.zip

**Comment by ahmedkaludi** [comment]
@SageFargo Any update?

**Comment by Zabi09** [comment]
@SageFargo Have you downloaded and install the 0.9.98 version? Is your issue fixed?

Please let us know.

**Comment by SageFargo** [comment]
No I haven’t, I was waiting for the full update

**Comment by RajuJeelaga** [comment]
@ahmedkaludi Please check this, once form your end, It is working fine with Master branch as well.. I Checked from my end,
