### ISSUE TITLE
Woo Commerce Category page is not working

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2333]
Woo Commerce Category page is rendering to the Homepage.

URLs:
http://music.rushisbiz.com/product-category/pdf/
http://music.rushisbiz.com/product-category/pdf/amp/

Extension Trello card URL > https://trello.com/c/9Vmj4QC6/273-homepage-is-rendering-on-the-product-pagerushis-biz

**Comment by MohammedKaludi** [comment]
This has been tested and pushed in 0.9.97.4
