### ISSUE TITLE
Retina featured images support

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#2334]
After creating page with “Page Builder” and adding category, featured images are blurry, no retina support on them. 
On homepage and category archives retina support work.

**Comment by SageFargo** [comment]
![3f42c5a6-5824-4286-8001-fbc527206f92](https://user-images.githubusercontent.com/40724154/42411556-6947c38c-8206-11e8-9330-d6fff0ae1014.png)
![14286ed6-b782-4ab5-9522-4d2e03359cca](https://user-images.githubusercontent.com/40724154/42411557-6cbcdc28-8206-11e8-96da-7484b7d5df72.png)

**Comment by MohammedKaludi** [comment]
need to have an empty variable. 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2d0f5c4c04a11d7143d3a95f9edce444b41afa09#diff-cb16861af9ff34ccd298041891008f49R293

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
