### ISSUE TITLE
Whenever "Show By Default" with any Category is Enabled, then the Content in EXCERPT is Disappeared.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2335]
Have a look at this Video for a clear Idea!!!

https://youtu.be/RlF8b4r1EsA

Reference: https://secure.helpscout.net/conversation/615784369/29589?folderId=2090441

When  "Show By Default" with any Category is Enabled in Options Panel, I suppose there shouldn't be any    " X " Option because there is no Call taken in WP Settings.

**Comment by MohammedKaludi** [comment]
:+1:
