### ISSUE TITLE
amp-image-lightbox extension

### ISSUE THREAD

**Issue by BeknSeattle** [ahmedkaludi/accelerated-mobile-pages#2338]
Hello,
Still having validation problems with the amp-image lightbox extension. I disable the lightbox image option and added the .js manually to the header option of the plugin. It cleared one error when it is stating that the JavaScript is needed. 9 warning appeared saying the js appears more than once on some post and pages. See attached image from Google's Search console.
<img width="1067" alt="screen shot 2018-07-09 at 12 51 02 pm" src="https://user-images.githubusercontent.com/40809189/42474194-a70a8d50-837b-11e8-96bc-eaff068b0215.png">
<img width="1437" alt="screen shot 2018-07-09 at 12 56 27 pm" src="https://user-images.githubusercontent.com/40809189/42474214-b9c873e4-837b-11e8-86cb-600f483e602e.png">

**Comment by Zabi09** [comment]
@BeknSeattle 
I have checked your website - http://www.joygibek.com/2016/07/sprites/?amp and currently, you don't have any warnings at the moment and it seems that you have also disabled the lightbox option, Will you please enable it and let me know at team@magazine3.com
I will do everything to fix your issue.

**Comment by BeknSeattle** [comment]
Good morning Syed,

With regards to the ‘amp-image-lightbox’. Thank you for doing everything you can with this problem

I removed in the advanced settings: html in head the script below: and enabled the lightbox option on Aug 13, 2018.

<script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>

I checked this morning for changes since the update of amp and checked the Gooogle search console: below are the data: The error appeared again after your suggested fix. Any thoughts on why it is happening? 


Thank you for your help!

MARIA VICTORIA REYES
Front End Web and Graphic Designer
https://www.joygibek.com

**Comment by Zabi09** [comment]
@BeknSeattle I have tested some of your pages - 
https://www.joygibek.com/2018/04/basic-bleeds-margin-posters-flyers/?amp
https://www.joygibek.com/2018/01/happy-new-year/?amp
https://www.joygibek.com/2017/06/2017-event-book-design/?amp

BUT all your pages are showing as validated only in the AMP validation, 

Will you please check once and let us know.

**Comment by Zabi09** [comment]
@BeknSeattle Are you still have any errors regarding 'amp-lightbox'? because I have checked some of your pages but I am unable to find the error. Please let us know.
