### ISSUE TITLE
Show notice in Plugin Manager page if the site is using 1.0

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2339]
- [x] Show notice in Plugin Manager page that site has an older version of AMP Plugin Manager and upgrade it to the newer version

http://take.ms/lOzh2

**Comment by ahmedkaludi** [comment]
- [ ] why two plugin manager? http://take.ms/aKwbf

**Comment by MohammedKaludi** [comment]
Because there is a confusion, the previous version that were distributed was plugins-manager and then we renamed it to AMP-plugin-manager.

That's why there are two copies and the code is written to handle both of them

**Comment by MohammedKaludi** [comment]
Also released this code in 0.9.97.6
:+1:
