### ISSUE TITLE
When Google Tag Manager is enabled, only Google Analytics should get disabled but not other analytics.

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2340]
When Google Tag Manager is enabled, all the other analytics gets turned off. Instead, only Google Analytics should get turned off.

Ref: https://secure.helpscout.net/conversation/613130890/29318?folderId=2075531

**Comment by MohammedKaludi** [comment]
:+1:
