### ISSUE TITLE
Title of page No Longer visible

### ISSUE THREAD

**Issue by osseonews** [ahmedkaludi/accelerated-mobile-pages#2341]
Upon update to Version 0.9.97.3, and 0.9.97.4 , all of the titles disappeared from any single pages. This happens on every design, Design 1, Design 2 and Design 3, but not on the Swift design (which we don’t use anyway). The title of the post, simply is not displayed in the page and the h1 tag that used to be used to display the title of the post (<h1 class=”amp-wp-title”>POST TITLE</h1>), is simply no longer there. Needed to downgrade to get the page back to normal again.

Can you please let us know what code has changed in the filters and functions that display the post title, so we can locate what is causing this bug? Which files controls the filters and functions that display the title?

**Comment by ahmedkaludi** [comment]
I don't know, it's really strange, Can you please share your wp-admin and FTP information on team@magazine3.com ?

i will look into this issue and fix the issue with the help of you and push the update so that everyone can get the solution!

**Comment by Sejiro-Hiko** [comment]
@osseonews can you please follow-up on this #1435 or we'll be closing that ticket

**Comment by osseonews** [comment]
@ahmedkaludi Just sent you a ticket at team@magazine3.com. As noted above, the Title issue occurs even when no other plugins are used and the standard Wordpress theme is used. Also, I should also mention that title issue maybe related to another bug we found with the latest update: Comments don't appear under AMP posts when you update the plugin. To fix this, you must actively  resave your design option in the settings to get it working again. This is strange behavior, which might be related to the title bug.

**Comment by geniovi** [comment]
I also confirm the bug in my site after install update  0.9.97.4
