### ISSUE TITLE
Compatibility issues with Site Origin Page builder.

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2342]
when the page is created by using site origin page builder then in amp version the content is not rendered and page appear blank.

but when we checked the custom AMP editor[with at least single alphabet then the content is rendering in AMP version]
see this video clip: http://take.ms/N4LTf

and some other compatibility issue like the "accordion is not working AMP version".
URL: https://haskewlaw.com/business-investor-visas-australian-immigration-options-explored/

Ref: https://secure.helpscout.net/conversation/617683373/29876?folderId=673452

**Comment by Zabi09** [comment]
The user was using siteorigin page builder by "thinkup" and the content was blank unless enabling the custom AMP editor but we have fixed it on user's end by creating a custom plugin to call the content.

**Comment by MohammedKaludi** [comment]
:+1:
