### ISSUE TITLE
rel="next" & rel="prev" pagination meta tags

### ISSUE THREAD

**Issue by shtefcs** [ahmedkaludi/accelerated-mobile-pages#2343]
Since the AMP is lot about **SEO** you are missing one very important stuff and that is `rel="next"` and `rel="prev"` paginations meta tags.

According to Google and other SEO experts, pagination pages should not be `<noindex>` , `nofollow` etc.

Check the screenshot:
![](https://i.imgur.com/BYULyhT.png)

Source: https://www.contentkingapp.com/academy/pagination/
Read more on Google Blog: https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html

You should definitely consider adding this in next update @ahmedkaludi since its very important aspect of SEO,  know asn *duplicate content* and *cannibalization*

It should be included in all paginations pages, posts, searches, homepage, etc.

Edit:
This is how what paginated pages should have:
![](https://i.imgur.com/o8UkYxV.png)

**Comment by Frenchomatic** [comment]
Yes this has been missing for quite some time. It would need to work properly in AMP takeover too.

**Comment by nomakeup** [comment]
This is exactly what i`m looking for...i hope that problem with pagination will be fixed in next update...cheers

**Comment by jelenajjo** [comment]
Is there anyway you can give us information on this issue? Whether you planning for next release or not. I can see from previous comments you stated will be released in previous update, but now as I can see it's not even labelled as *Next Update* issue.

I would appreciate your response @MohammedKaludi @ahmedkaludi

**Comment by ahmedkaludi** [comment]
@jelenajjo I'm moving this ticket to the priority, I will make sure that this feature is built faster and it gets added in the next release cycle.

**Comment by Frenchomatic** [comment]
That is a good move as it effects SEO

**Comment by Frenchomatic** [comment]
Just tested this using this in functions.php . It works for me on AMP takeover scenarios and on hybrid systems the AMP version gets the next and previous links. You may like to try it until it goes into the plugin

```
function amp_head_special() {
	global $paged;
  if ( get_previous_posts_link() ) { ?>
  <link rel="prev" href="<?php echo get_pagenum_link( $paged - 1 ); ?>">
  <?php
  }
  if ( get_next_posts_link() ) { ?>
  <link rel="next" href="<?php echo get_pagenum_link( $paged + 1 ); ?>">
  <?php
  }
}
add_action( 'amp_post_template_head', 'amp_head_special');
```

**Comment by Frenchomatic** [comment]
This explains why this needs to be released in the very next update - https://yoast.com/pagination-seo-best-practices/

hope the code above helps someone. Solved it for me.

**Comment by Frenchomatic** [comment]
I am not sure your commit will work properly. It will put a next link on a static home page.

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
