### ISSUE TITLE
Where did the excerpt go?

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2344]
1. roll back to .96.1 and reset the options
2. set D2
2. update to the latest version
3. check homepage excerpt.

Do the same test in all the designs.

**Comment by RajuJeelaga** [comment]
Same issue i notice in this https://ampforwp.com/demo/amp-pagebuilder/blog/amp/

**Comment by merajali294** [comment]
Team have a look at this:

https://wordpress.org/support/topic/0-9-97-3-breaks-excerpts-and-disables-comments-by-default/

**Comment by ahmedkaludi** [comment]
If it's not a proper solution, then let's discuss the proper one? 

@MohammedKaludi @Sejiro-Hiko

**Comment by MohammedKaludi** [comment]
It is working perfectly and also pushed in master many days ago.

:+1:
