### ISSUE TITLE
ld+json is getting a break when a special character is getting added in the image.

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2346]
Ref:  https://secure.helpscout.net/conversation/611765346/29181?folderId=1060556

Screenshot:  http://monosnap.com/image/naVB2C7uVdsOQG1UMehDYJ2qx4mcLO/

Issue:   `$element->nodeValue = $element->textContent;`

Solution:  `$element->nodeValue = htmlspecialchars($element->textContent);`

**Comment by santosh8793** [comment]
#2316 this issue has been resolved here

**Comment by santosh8793** [comment]
#2316 Made changes based on the solution provided by the ticket #2346

**Comment by MohammedKaludi** [comment]
:+1:
