### ISSUE TITLE
Addition of new button option under the Notice Bar (Cookie Consent)

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2347]
Description: Addition of new button option (Such as Read more option which takes the user to the privacy policies.)  under the Notice Bar (Cookie Consent)
Ref: https://secure.helpscout.net/conversation/617694056/29881/
See this screenshot: http://take.ms/z9cLI

**Comment by MARQAS** [comment]
Can you take care of the styling part? @RajuJeelaga

**Comment by ahmedkaludi** [comment]
- [ ] Convert it to the Text Feild: http://take.ms/8CNqZ with # as the default.

**Comment by MARQAS** [comment]
Escaping?

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Remove commented code while merging 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c25ac2e5560dcc422f477c1dc74490c8a29113be#diff-37bae116ac9cf436a51457288caf804fR74

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
