### ISSUE TITLE
User Experience Issue with Custom Home Page

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2348]
Description: User Experience using  a link of tutorial how to set the custom home page  

Ref: https://secure.helpscout.net/conversation/618228872/29974/

Screenshot: http://take.ms/EBjjd

**Comment by MohammedKaludi** [comment]
text is not translatable https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/33007f28ac9ee807b5fc6ad3d80d4d47d8f865b9#diff-6aa5512f7dd8d5ce60fc97b0f340912cR1789

**Comment by MohammedKaludi** [comment]
@ahmedkaludi need to make the design better.

**Comment by ahmedkaludi** [comment]
Me & @githubjabbar is working on it.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
Need to rewrite the message: https://take.ms/48Jkw
to this : `We have detected that you have not setup the FrontPage for AMP, Click here to setup`

Add the same notice here as well.
https://take.ms/BfI4P

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
