### ISSUE TITLE
Remove “Top ” and display it as “Top”.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2349]
The Back to “Top” page link on AMP pages is displayed as “Top ” rather than “Top”.

Forum Ref: https://wordpress.org/support/topic/back-to-top-link-minor-typo-on-amp-page/

Example: https://monosnap.com/file/fgFKRegFt4Midj0QNcrwrtHMjP8HpV

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
