### ISSUE TITLE
problem when switching on desktop version

### ISSUE THREAD

**Issue by fikryans** [ahmedkaludi/Accelerated-Mobile-Pages#235]
i have problem with this plugin.
when i try to switching on dekstop version using link on footer i've got this problem.
how i can fix that url ?

![screenshot_212](https://cloud.githubusercontent.com/assets/8897997/20650038/db8a4882-b4ff-11e6-9fde-671f8fa610df.png)

![screenshot_213](https://cloud.githubusercontent.com/assets/8897997/20650047/f9fa659a-b4ff-11e6-9995-8474e9c2e1f6.png)

**Comment by khaledMohammed000** [comment]
Hello @fikryans Thank you for using our plugin and also posting this issue , we have already identified this issue and have solved it here #215

So in our next update which we will do soon you can get those changes or if your in a hurry just look at the file that got modified in the Ticket #215 and make similar changes to your plugin code :)

**Comment by khaledMohammed000** [comment]
Please have a look here at line 199 https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/5e43ad00db1462fb1995102162e93945de1ca0ee

**Comment by fikryans** [comment]
yes fixed..thankss
