### ISSUE TITLE
Homepage build with AMP PageBuilder is displaying only when the checkbox of the Custom AMP editor is enabled.

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2350]
REF: https://secure.helpscout.net/conversation/618164218/29968?folderId=1680011

 Homepage content build with AMP PageBuilder is displaying only when the checkbox of the Custom AMP editor is enabled.

See this video: http://take.ms/klkKZ

**Comment by ahmedkaludi** [comment]
working as per the user's issues are concerned.

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
