### ISSUE TITLE
Swift theme header type is always the same

### ISSUE THREAD

**Issue by maysanmingorance** [ahmedkaludi/accelerated-mobile-pages#2353]
I'm trying to change the type of header on this theme (Swift) and it's impossible. As much as I try, it always shows the one with the "Sign up free" button and I'm not able to remove it.

**Comment by ahmedkaludi** [comment]
@maysanmingorance Can you share the URL?

Also, we're unable to recreate the issue on our end, so kindly share the wp-admin credentials on team@magazine3.com so I can personally look into this issue and help you fix this one.

**Comment by Zabi09** [comment]
@maysanmingorance 
Have you tried to change from the header type option of the AMP panel - http://take.ms/NAtuR ?
And still, you have the issue?
Please let me know

**Comment by Zabi09** [comment]
@maysanmingorance 
This is your last chance and if you don't reply to our previous messages then we will go ahead and close this ticket.
