### ISSUE TITLE
AMP Facebook Page like box implimentation

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2355]
User Want to display the facebook page in the amp but we have asked for the exact path where the user wants to display the facebook page.

Normally the facebook page is displaying in the header below the address bar.
see this screenshot:  http://monosnap.com/image/q9ugvr9Of4gasEU1vEVxUrNaieFw2F/

Ref:  https://secure.helpscout.net/conversation/616909160/29780?folderId=1914712

**Comment by MARQAS** [comment]
The user was trying to add the amp-facebook-page but didn't know where to add the script, we gave him the instructions. 
After recent updates, he can even add the code in the Text editor as well. 
https://secure.helpscout.net/conversation/617869986/29919/
