### ISSUE TITLE
Error in Errorlog

### ISSUE THREAD

**Issue by Omair52** [ahmedkaludi/accelerated-mobile-pages#2356]
User is facing errors in errorlog

Ref: https://secure.helpscout.net/conversation/617688717/29880?folderId=2090528

If you have any doubts feel free to ask me.

**Comment by Zabi09** [comment]
No condition in master - http://take.ms/frePQ and this issue is already fixed in beta version - http://take.ms/xP3Qe

**Comment by MohammedKaludi** [comment]
:+1:
