### ISSUE TITLE
Ads are breaking  above the footer in RTL mode 

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2357]
Description: Ads are breaking just above the footer in RTL mode

REF: https://secure.helpscout.net/conversation/617805606/29900?folderId=2169251

Screenshot: http://take.ms/kBK9o

**Comment by ahmedkaludi** [comment]
Not breaking, it should be in center

**Comment by RajuJeelaga** [comment]
- [ ] I check in my localhost and User Live site as well, From my end it is working fine, I didn't see ad problem in the User live site.
