### ISSUE TITLE
AMP compatibility with Table of content plugin.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2359]
Description: Should make the Table of content plugin AMP compatibility mainly with the themes and Hide and show table contents.

Ref: https://secure.helpscout.net/conversation/617694056/29881?folderId=2169251
Screenshot: https://prnt.sc/k5590h

**Comment by merajali294** [comment]
User needs

- Show/Hide Option

- CSS for Border color,Link color

**Comment by MohammedKaludi** [comment]
Will release a separate extension for this as there are few features that are still pending.

**Comment by MohammedKaludi** [comment]
Remove code from beta

**Comment by ahmedkaludi** [comment]
Added the compatibility at https://ampforwp.com/table-of-content-plus-is-now-compatible-with-amp/
