### ISSUE TITLE
Author Bio above related posts [Thanx Jana B for Suggestion]

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#236]
![author](https://cloud.githubusercontent.com/assets/16471728/20660311/fd2493b6-b56e-11e6-83ea-553876854463.jpg)

**Comment by khaledMohammed000** [comment]
This was done in https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2e8802e144a8f25ef0909aceb5003dd8b4edddd3

**Comment by khaledMohammed000** [comment]
But it does not come above Related Posts but Above meta-info.php

**Comment by MohammedKaludi** [comment]
Working on #732
