### ISSUE TITLE
Error and Warning on Structured Data for Logo.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2360]
1. Many Users getting this error.

https://imgur.com/DoPYEB4

Reference: https://wordpress.org/support/topic/google-search-console-error-error-in-required-structured-data-element/

2. I've tested at my end we are getting Warning as shown in the Screenshot only in 0.9.97.5, not in previous Versions: 

https://monosnap.com/file/Oa8ZE9IVEVBXSrkVctUzb3rfgsM9y8

**Comment by beingsmart3** [comment]
One More issue:  https://secure.helpscout.net/conversation/589841540/26956?folderId=1914712

**Comment by ToufiqSuhail** [comment]
Some more user: https://secure.helpscout.net/conversation/616275469/29679?folderId=2075531

https://secure.helpscout.net/conversation/619985439/30166?folderId=2075531

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/618952792/30055?folderId=1914712

**Comment by beingsmart3** [comment]
one more:  https://secure.helpscout.net/conversation/620510131/30218?folderId=1914712
JSON-LD	Syntax error: value, object or array expected.
see this screenshot:  http://take.ms/yIDlV

**Comment by ToufiqSuhail** [comment]
https://secure.helpscout.net/conversation/620541148/30225?folderId=1060551

**Comment by MohammedKaludi** [comment]
Pushed in V0.9.97.6
:+1:
