### ISSUE TITLE
AMP renders with ?q after the /amp

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2361]
In the AMP version, the site renders to the link in this way

https://bestmvno.wpstage.net/apn-settings/cricket-wireless-apn-settings/amp/?q=/apn-settings/cricket-wireless-apn-settings/

Ref: https://secure.helpscout.net/conversation/608344231/28742?folderId=2075531

WP already inside it. Let's not wait for the FTP.

**Comment by Zabi09** [comment]
the error is due to the following code
`if ( is_singular() && !empty($_SERVER['QUERY_STRING']) ) {
	$url = add_query_arg( $_SERVER['QUERY_STRING'], '', $url);
}`
it was added in the following tickets #1771 #2223 

@MARQAS can you look into it.

**Comment by ToufiqSuhail** [comment]
Regarding the same issue, 
https://monosnap.com/file/lj67g3XwsndqycWBqJTKyG3Sr6OZug - The ftp is also available,

**Comment by MohammedKaludi** [comment]
ampforwp_findInternalUrl loading many times, need to check.

**Comment by MohammedKaludi** [comment]
Updated some code and tested on users website.

Commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b63be8bbee3524e8234ac7c46fad139b29b028a7

Issue details: https://secure.helpscout.net/conversation/630761121/31143/?folderId=1060556

**Comment by MohammedKaludi** [comment]
“ It`s very nice plugin I have only one problem so far. if I turn all links to auto add /AMP I cant use MAILTO:example@example.com when link is clicked is example@example.com/AMP ”


@Zabi09 can you please do a test?

**Comment by Zabi09** [comment]
Working on our end in beta version and also contacted the user for more info - 
https://secure.helpscout.net/conversation/638761924/31892/

**Comment by beingsmart3** [comment]
Need to add this code to get the issue fixed properly

`if( ampforwp_is_query_post_same( $_SERVER['QUERY_STRING'],$query_name) && isset( $query_arg['q'] ) ){
			unset($query_arg['q']);
        } else if ( $query_name && isset( $query_arg['q'] ) ){
			unset($query_arg['q']);			
		}`

Ref:  https://secure.helpscout.net/conversation/624660130/30639?folderId=1914712

**Comment by MohammedKaludi** [comment]
:+1: can ber merged.

**Comment by MohammedKaludi** [comment]
:+1: will be pushed in 0.9.97.22
