### ISSUE TITLE
When an /?amp is enabled visit AMP is redirecting to dashboard

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2363]
When an endpoint  is enabled Visit amp option is redirecting to Xyz.com/wp-admin, not the homepage

Ref:  https://secure.helpscout.net/conversation/617783401/29897?folderId=1914712

**Comment by MohammedKaludi** [comment]
The issue still persists. 

Enable amp-endpoint, turn-off homepage-support and test the homepage with ?amp and check where it is redirecting.

For me, it is redirecting to one directory.
Like: if I'm testing on localhost/wordpress/?amp then it will be redirecting me to localhost not localhost/wordpress

Hope I'm clear if not then please contact me.

**Comment by MohammedKaludi** [comment]
need improvement in the code
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ac533f3d7a675e53449e37c7708b9ea25a89c1d8#diff-ab576767b896423d184ddafe2ede2310R10

**Comment by beingsmart3** [comment]
https://secure.helpscout.net/conversation/758214577/51250/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: can be merge into master

**Comment by MohammedKaludi** [comment]
New issue reported https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2904

Closing this ticket as this code is Pushed in 0.9.97.36
