### ISSUE TITLE
Debug warnings in error logs

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2367]
Hi I am having a problem in constant error logs. I ask you to help me with the solution, thank you.

Problem : /wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4801
/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 248

https://wordpress.org/support/topic/amp-features-php-on-line-4801-error/

**Comment by MohammedKaludi** [comment]
One more warning 

( ! ) Notice: Undefined index: page in C:\wamp\www\1\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php on line 433
--

**Comment by MohammedKaludi** [comment]
On debug.log I have this error with version Versión 0.9.97.6 of the plugin and wordpress Versión 4.9.7

[17-Jul-2018 06:47:00 UTC] PHP Notice: Undefined variable: wp in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6853
[17-Jul-2018 06:47:00 UTC] PHP Notice: Trying to get property ‘request’ of non-object in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6853
[17-Jul-2018 06:47:00 UTC] PHP Notice: Trying to get property ‘ID’ of non-object in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-2/style.php on line 11

and more often this errors
[17-Jul-2018 06:47:00 UTC] PHP Notice: Undefined index: query in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/classes/class-ampforwp-youtube-embed.php on line 105
[17-Jul-2018 06:47:00 UTC] PHP Notice: Undefined offset: 1 in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/classes/class-ampforwp-youtube-embed.php on line 116

Ref: https://wordpress.org/support/topic/error-on-debug-log-2/

**Comment by syedimran22** [comment]
Description: Errors reflecting on the pages

 Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397

Notice: Undefined index: query in /home/uazfychz/public_html/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 397


Ref: https://secure.helpscout.net/conversation/622228882/30409?folderId=2169251

**Comment by Sejiro-Hiko** [comment]
If there's no menu set up then the following errors shows up
~
PHP Notice:  Trying to get property 'before' of non-object in C:\wamp64\www\animegate\wp-content\plugins\accelerated-mobile-pages\classes\class-ampforwp-walker-nav-menu.php on line 57

PHP Notice:  Trying to get property 'link_before' of non-object in C:\wamp64\www\animegate\wp-content\plugins\accelerated-mobile-pages\classes\class-ampforwp-walker-nav-menu.php on line 60

PHP Notice:  Trying to get property 'after' of non-object in C:\wamp64\www\animegate\wp-content\plugins\accelerated-mobile-pages\classes\class-ampforwp-walker-nav-menu.php on line 67~

**Comment by Sejiro-Hiko** [comment]
If there's no menu set up then the following errors shows up

PHP Notice:  Trying to get property 'before' of non-object in C:\wamp64\www\animegate\wp-content\plugins\accelerated-mobile-pages\classes\class-ampforwp-walker-nav-menu.php on line 57

PHP Notice:  Trying to get property 'link_before' of non-object in C:\wamp64\www\animegate\wp-content\plugins\accelerated-mobile-pages\classes\class-ampforwp-walker-nav-menu.php on line 60

PHP Notice:  Trying to get property 'after' of non-object in C:\wamp64\www\animegate\wp-content\plugins\accelerated-mobile-pages\classes\class-ampforwp-walker-nav-menu.php on line 67

**Comment by Sejiro-Hiko** [comment]
( ! ) Notice: Undefined index: page in C:\wamp\www\1\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php on line 433 

To avoid this error `$screen = get_current_screen();` is being used ref to some other commit.

**Comment by Sejiro-Hiko** [comment]
Undefined variable: categories_array in C:\wamp64\www\animegate\wp-content\plugins\accelerated-mobile-pages.0.9.97.6\includes\options\admin-config.php on line 4927

when there are no posts on site.

**Comment by beingsmart3** [comment]
[error_log.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/2253041/error_log.txt)

Ref:  https://secure.helpscout.net/conversation/632389161/31327?folderId=1914712

**Comment by MohammedKaludi** [comment]
More debug errors found 

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ampforwp_new_gallery_images' not found or invalid function name in /web/htdocs/www.cosenzachannel.it/home/news/wp-includes/class-wp-hook.php on line 286

https://www.cosenzachannel.it/2018/05/22/i-ragazzi-del-liceo-telesio-orgoglio-della-provincia-di-cosenza/amp

**Comment by MARQAS** [comment]
Notice: Undefined index: pagename in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 6066

**Comment by MohammedKaludi** [comment]
One more warning reported 

![photo_2018-08-18_15-59-02](https://user-images.githubusercontent.com/16618009/44298406-3e93c800-a300-11e8-9c40-0c3723767bdc.jpg)

**Comment by Zabi09** [comment]
PHP Notice:  Uninitialized string offset: 1 in D:\xampp\htdocs\magzine\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\extensions\checkbox_hierarchy\checkbox_hierarchy\field_checkbox_hierarchy.php on line 166

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: code will be pushed in 0.9.97.22

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22

**Comment by dilshadahmad1** [comment]
on my site show this error now 
plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 657
