### ISSUE TITLE
AMP page builder is not working even after enabling it

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2370]
wp-admin - https://secure.helpscout.net/conversation/616195389/29666?folderId=1060554

FTP details are ready!

**Comment by Sejiro-Hiko** [comment]
the issue was resolved in 0.9.97.7 and after the update on the user's end, the page builder is working.

**Comment by MohammedKaludi** [comment]
:+1:
