### ISSUE TITLE
 404 error when custom post type and page having same slug [Bug for the Rare use case]

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2374]
If the custom post type and the page having the same slug then its giving 404 error in AMP version.

For example, if we have a portfolio custom post type and if we create the page with the same name then its give 404 error in AMP version.

**Comment by MARQAS** [comment]
@Zabi09 can you please look into it? 
'ampforwp_cpt_and_post_name_conflict_resolve' is running on non-amp as well which is causing some errors.
And also try to rename it to a better name.

**Comment by ahmedkaludi** [comment]
Another case: Category base remover with post, shows the category instead of the post but user is not cooperating. Let's figure this out ourselves.

**Comment by MARQAS** [comment]
Category with base removal is working fine

**Comment by MARQAS** [comment]
> If the custom post type and the page having the same slug then its giving 404 error in AMP version.

We don't have any reference for this.

**Comment by Zabi09** [comment]
How to recreate - 
Create a new page with the same name as a category 
Remove the category base from the permalink and also enable the category base remove in AMP then in default wp it is showing page - https://monosnap.com/file/OcNsDzr8TzdNYKVYq7TCuiUoA3iGib and in the amp, it is showing category - https://monosnap.com/file/WCzUPjY1mRdTq4FAE8jVPs2CYye81n

**Comment by MARQAS** [comment]
I just tested it and its working fine for me. Can you please test it again? @Zabi09

**Comment by Zabi09** [comment]
Working fine as expected as I was not removing the base properly it was rendering the page instead of archive.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
I dont think this ticket needs merging, please do consult me before merging.

**Comment by pegazee** [comment]
Working perfectly on my end in the latest versions
