### ISSUE TITLE
Posts are not display and getting hidden in Blog page even when AMP is in show status

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2375]
When new posts are added in the categories section, the posts are not displaying and are taking the null value. But when we on re-updating by visiting the specific post; the posts displays.

Ref: https://secure.helpscout.net/conversation/621244671/0/?folderId=2075531
WP available, waiting for FTP

**Comment by syedimran22** [comment]
Description: Around 500 posts in NonAMP site user can see only 3 posts on the AMP pages.

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
