### ISSUE TITLE
Options Panel not showing, says "You are not allowed to access this page"

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2377]
Options Panel not showing, says "You are not allowed to access this page"

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/621120036/30315?folderId=1060556

**Comment by syedimran22** [comment]
Ref: https://secure.helpscout.net/conversation/619268464/30092?folderId=1060556

**Comment by ToufiqSuhail** [comment]
https://secure.helpscout.net/conversation/608314238/28740?folderId=2075531 

FTP is available.

**Comment by syedimran22** [comment]
When JetPack plugin is activated, it is throwing the error

"Fatal error: Uncaught Error: Class 'AMPforWP\AMPVendor\Jetpack' not found in /var/www/vhosts/****/stage.****/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/jetpack-helper.php:13 Stack trace: #0 /var/www/vhosts/****/stage.****/wp-includes/class-wp-hook.php(286): AMPforWP\AMPVendor\amp_jetpack_mods(0) #1 /var/www/vhosts/****/stage.****/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /var/www/vhosts/****/stage.*****/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /var/www/vhosts/****/stage.****/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/amp.php(84): do_action('pre_amp_render_...', 0) #4 /var/www/vhosts/*******/stage.*****.com/wp-includes/class-wp-hook.php(286): AMPforWP\AMPVendor\amp_render('') #5 /var/www/vhosts/****/stage.****/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 in /var/www/vhosts/*****/stage.*****.com/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/jetpack-helper.php on line 13"

**Comment by MARQAS** [comment]
Resolved in #2287

**Comment by MohammedKaludi** [comment]
Don't use anonymous functions

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/42d5fc122f6f65c40797ec4d779c05e1d50b4613#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R717

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by zarapico** [comment]
> 👍

Hi @MohammedKaludi 

I have this same problem in my production environment
Do you know when this new version will be released?
Thank you!

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

**Comment by priidutammeorg** [comment]
I have same problem, can't access settings. When will be the fixed release?

**Comment by pegazee** [comment]
One more user reported: https://secure.helpscout.net/conversation/773224702/54738?folderId=1914712

**Comment by beingsmart3** [comment]
https://secure.helpscout.net/conversation/792980126/57929?folderId=1914712

**Comment by MohammedKaludi** [comment]
:+1: the code is ready and properly tested, @MARQAS and @pegazee let's push the code on Monday's update.

**Comment by MohammedKaludi** [comment]
the code will be pushed in 0.9.97.41 on Monday 11th March

**Comment by MohammedKaludi** [comment]
@MARQAS 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/67fdb14e31c02b6e7ab916558643e825ddab54f9#diff-1a0e52b2651cea85b13d1cbf4f2198b0R641

Why changed the text-domain to `redux-framework`?

**Comment by pegazee** [comment]
Pushed in 0.9.97.43
