### ISSUE TITLE
AMP Page Builder not working on Front page

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2378]
Reference:

https://secure.helpscout.net/conversation/618829565/30048?folderId=1680011

Waiting for FTP Details, as the details currently present are not working.

Fixed on the users website via ftp.

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/621374086/30339?folderId=1914712

**Comment by MohammedKaludi** [comment]
Fixed and tested on multiple sites, also the code will be pushed in 0.9.97.7
