### ISSUE TITLE
Ads placement correction

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#2379]
This is the Home Page, ad doesn't sit in it's place.
![screen shot 2018-07-17 at 2 48 18 pm](https://user-images.githubusercontent.com/40724154/42815702-d35f5362-89d0-11e8-8455-f5fbb1c94939.png)

**Comment by ahmedkaludi** [comment]
@SageFargo May I know which ad location is this?

**Comment by SageFargo** [comment]
Hi,
It is showing on Homepage.

**Comment by ahmedkaludi** [comment]
how did you added it?

**Comment by SageFargo** [comment]
Like Marqas explained with the google auto amp ads. It was working fine, I noticed this today. Haven’t done any tweaking it just appeared there, or maybe it’s the in-content ad I don’t know. 
But the codes are in the html settings

**Comment by SageFargo** [comment]
![screen shot 2018-07-17 at 6 54 36 pm](https://user-images.githubusercontent.com/40724154/42829921-067b4522-89f3-11e8-86dc-e2822cce8e4b.png)
appears also in-post. in the "Recent Posts" block

**Comment by Zabi09** [comment]
@SageFargo 
Are you adding the ads by using our advance AMP ads extension with "Ads Inbetween Loop" option - http://take.ms/OMx04
If yes then please contact us at team@magazine3.com and one of our developers will definitely fix your issue.

**Comment by SageFargo** [comment]
No, just added the code to the amp html code from google

**Comment by ahmedkaludi** [comment]
Auto ads behave automatically, we do not have any control over it. No solution at the moment. We have no option but to close this one unless Google adsense team gives ideal positions where we can add show the ads.

**Comment by beingsmart3** [comment]
Another issue
Ref: https://secure.helpscout.net/conversation/662156192/34111?folderId=1914712
