### ISSUE TITLE
disturbing notification : trendyblog theme (This theme causes irritating messages on DashBoard)

### ISSUE THREAD

**Issue by fikryans** [ahmedkaludi/Accelerated-Mobile-Pages#238]
when i activated this plugin.. notification about installing woocommerce alwasy show up in my dashboard, this is very disturbing. how i can deactivated this notification??. if close the dialog, this notification always show up when i reload my pages.
![screenshot_214](https://cloud.githubusercontent.com/assets/8897997/20671994/420d00b0-b5b2-11e6-90f6-737e92104042.png)

**Comment by khaledMohammed000** [comment]
@fikryans Thank You for using our plugin , we never recommend in our plugin to use WooCommerce 
![420d00b0-b5b2-11e6-90f6-737e92104042](https://cloud.githubusercontent.com/assets/16471728/20672713/39c55448-b5a8-11e6-864e-b98ca2c9eaea.png) This is caused by your Theme as you can see it in the image , Please let me know what Theme you are using

**Comment by fikryans** [comment]
i use trendyblog theme..
but this notification didn't show up when i deactivated AMP plugin.
can you help me??
this is gif image for my problem
https://s5.postimg.org/v48y4hh5z/plugin.gif

**Comment by khaledMohammed000** [comment]
Hello @fikryans , Thanx for the GIF but you can look at our entire Code we never recommend WooCommerce , We can help you in a better way please provide your login details here http://ampforwp.com/contact/ and we will get back to you with the cause of this issue :)

**Comment by fikryans** [comment]
do you mean, i give you username and password my dashboard administrator?
how about my data? it will be safe?

**Comment by khaledMohammed000** [comment]
Yes , Your data will be safe with us , You can look into the support forum several people have given us their data and are satisfied that their issue got resolved

**Comment by fikryans** [comment]
allright. i've been send you a details. please checkout your mailbox..my email is fikry.dome10@gmail.com
I waiting for information from you soon.

**Comment by khaledMohammed000** [comment]
Give us some time , we will sort the issue and we received your mail :)

**Comment by khaledMohammed000** [comment]
@fikryans We have open the URL that you gave us but it does not give us the wp-admin page....can you send the URL for the Admin panel ...Here is a screenshot of what we are getting : <a href="http://take.ms/WvgQU">img</a>

**Comment by fikryans** [comment]
i've already fixed that's issue..thanks for your offering

**Comment by khaledMohammed000** [comment]
@fikryans Awesome 👍  Can you please share the solution so if anytime any other User gets the same issue we can look at you solution

**Comment by fikryans** [comment]
i didn't do any special thing, just change the themes :D

**Comment by khaledMohammed000** [comment]
@fikryans Thanx for your reply 👍  It was helpful
