### ISSUE TITLE
iThemes Sync  can not connect to the site. 

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2380]
User updated the website with our latest update and the iThemes Sync console cannot connect to his site.

Reference: 
https://secure.helpscout.net/conversation/614387369/29433?folderId=1680011

**Comment by Sejiro-Hiko** [comment]
the conflict is with the way redux is adding should look for the other action to load it instead of `after_setup_theme`

**Comment by MohammedKaludi** [comment]
Working and tested with 0.9.97.8
