### ISSUE TITLE
Getting Error 404 in Archives Pages !!

### ISSUE THREAD

**Issue by 4mr3y** [ahmedkaludi/accelerated-mobile-pages#2381]
Already enable Archives [Category & Tags] option in general setting, but still get 404.

**Comment by ahmedkaludi** [comment]
THat's really strange, Can you please share your url here? and WP-admin & FTP on team@magazine3.com ? 

I will personally check and help you fix it.

**Comment by 4mr3y** [comment]
thanks for respon :)
already send all your request on that mail

**Comment by ahmedkaludi** [comment]
this was fixed with category base remover as an option
