### ISSUE TITLE
H1 to H6 styling is not reflecting in the Swift theme  

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2383]
Description: H1 to H6 styling is not reflecting in the Swift theme amp 

Ref: https://secure.helpscout.net/conversation/620053457/30182/

Screenshot: http://take.ms/24lel

**Comment by RajuJeelaga** [comment]
Fixed and Ready to be pushed

- Ahmed

**Comment by MohammedKaludi** [comment]
Code shipped in 0.9.97.8
