### ISSUE TITLE
The Option Facebook App ID not necessary in the social icons of AMP panel when using Swift

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2384]
The Option Facebook App ID not necessary in Design- Social of AMP panel when using Swift Design. 

Ref: https://secure.helpscout.net/conversation/622216964/30408?folderId=1060556

screenshot: https://monosnap.com/file/j7tp0RtKiIKolSRhhixnwXmBnCooSm

**Comment by ahmedkaludi** [comment]
**REVIEW:**

- [ ] "you can register one here: https://developers.facebook.com/apps." this whole thing should be a link.

**Comment by Zabi09** [comment]
The position should be a different section: http://take.ms/JfaBA

This check was by mistake and the position is okay

**Comment by ahmedkaludi** [comment]
Reviewed.

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
