### ISSUE TITLE
amphtml tag is getting wrong defined in pagination which is giving 404 error

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2385]
Ref:  https://secure.helpscout.net/conversation/623834894/30564?folderId=1914712

Wp and FTP are in

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/620922213/30270?folderId=2075531

**Comment by MohammedKaludi** [comment]
Fixed in #2396 and applied the fix on both the above mentioned tickets.

This is the feedback from both the ticekts.
> It's working. Thank you :-) 
regards,
Jiri

> Thanks for your support. thanks again for your valuable support sir.


Closing the ticket, more info about this issue can be found on #2396
