### ISSUE TITLE
Genesis SEO settings

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2386]
Not a bug but in the drop down you list Yoast and All in one but I thnk you should also put Genesis in the list. At present Genesis works fine if the filed is not set (empty).

**Comment by Zabi09** [comment]
@Frenchomatic 
I have checked the Genesis SEO settings and it is only working in non-amp version and not in the AMP version.
For example - I have checked the title - http://take.ms/7sKNt and here is the result 
non-amp - http://take.ms/wHNuk
AMP - http://take.ms/FzXQT

Will you please elaborate exactly what is working fine, So that we can check that and create the feature.

**Comment by Frenchomatic** [comment]
First of all I am only talking about the drop down box in the admin panel - to actually set Genesis as an option (at present nothing, yoast or all in one SEO is offered). If you set nothing then the Genesis SEO settings work fine for me page by page.  **I don't use the sitewide SEO settings and only do things page by page.** 

So the Genesis SEO settings are working for me on a page by page basis. I can set a meta description and a document title for a specific page and they get rendered correctly in the html of the AMP page. I see no issues or problems at all. 

Robots meta settings per page also work and get rendered correctly. This allows me to use noindex, noarchive on say a legal or privacy page. Yes I know the page will longer be AMP valid but I don't want such a page indexed anyway so it becomes irrelevant. So this is fine too. In order for the robots settings to be picked up the URL inspection tool compatibility option needs to be set to off (don't really understand why those two things are connected but it works that way).

**Comment by MohammedKaludi** [comment]
:+1: can be merged.

**Comment by pegazee** [comment]
K

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
pushed in 0.9.97.44
