### ISSUE TITLE
few elements needs to be added inline styles

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2387]
- [x] If the width is set to 100% then it's been automatically be added to the width. Use this code as an example: 
https://pastebin.com/KL0w4aFq

- [x] overflow-x: hidden; overflow-y: scroll;  is not been added to inline styles. To test, use this as an example:  https://pastebin.com/g2uSXaqJ
https://secure.helpscout.net/conversation/622592327/30443?folderId=2075531

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MARQAS** [comment]
Can be merged into master

**Comment by beingsmart3** [comment]
- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Fully fixed in 0.9.97.33, closing the ticket.
