### ISSUE TITLE
Sidebar option as a global one

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2388]
Have the sidebar option in the global section and allow them  to show / hide from homepage or single.

In short, stack two options into one with parent option under global section.

>  Frankly, you should consider the option of putting on the sidebar for Front Page and Single pages. I don't use the front page with a sidebar any longer but I do use the sidebar on single pages. You could put the follow social icons where you have the share social icons and then move the share social icons at the end of each post, which is where every other major website puts them; though some put it in the header but that becomes an issue with load time and having the javascript having to be made asynchronous.

REF: https://secure.helpscout.net/conversation/623940506/30581?folderId=2169251

**Comment by ahmedkaludi** [comment]
Reviewed

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.12
