### ISSUE TITLE
All the Images are Adding AMP at the End of their URL.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2391]
Desc: All my images are adding AMP at the end of their URL and it results in error 404 and showing as blocked URL on Adsense.

Ref: https://secure.helpscout.net/conversation/624750312/30644?folderId=2169251
Screenshot: http://take.ms/hFTp4

**Comment by MohammedKaludi** [comment]
ampforwp_findInternalUrl loading many times, need to check.

**Comment by MohammedKaludi** [comment]
Why so many calls are being made and why the function is going through these files http://take.ms/f8Sul

**Comment by ajeetku** [comment]
Function Calling from Sanitizer, for every "a href" tag its calling ampforwp_findInternalUrl.  So its loading many times

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31
