### ISSUE TITLE
Tables overflow in swift theme when adding the tables to the site [TEST + ALT solution]

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2392]
Tables overflow when created with more than 2 columns in the swift theme.

Ref: https://secure.helpscout.net/conversation/624072219/30594/

**Comment by MARQAS** [comment]
No clear option for this because we've tried alot on responsive, not possible in the current scenario.

However an alternative would be to create a new PB module called table and make it responsive enabled.

**Comment by MohammedKaludi** [comment]
:+1: can be merged.

**Comment by MohammedKaludi** [comment]
:+1:  code will pushed in 0.9.97.22

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
