### ISSUE TITLE
Homepage is not rendering to AMP until we select the posts type from the reading settings.

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2393]
The homepage is not rendering to AMP until we select the posts type from the reading settings.

Ref: https://secure.helpscout.net/conversation/616973431/29787?folderId=2075531
WP admin and FTP details available

Another user: https://secure.helpscout.net/conversation/626894324/30833?folderId=1060554
WP admin and FTP are available.

**Comment by MARQAS** [comment]
Unable to recreate the issue. 
The issue of the 1st user is resolved and no one knows how ( I guess the option was not updated and he just saves the settings and boom!)

the second one was having the issue with Homepage and Pagebuilder, he wants to modify the homepage with AMP which is not related to this issue. 
Moving this ticket.

**Comment by MohammedKaludi** [comment]
:+1: Issue not related to any bug. This was just a installation issue with the user.
