### ISSUE TITLE
Getting the warnings in Error log of Inc42

### ISSUE THREAD

**Issue by githubjabbar** [ahmedkaludi/accelerated-mobile-pages#2395]
REF: https://secure.helpscout.net/conversation/626137517/30777/

Undefined variable: wp in htdocs/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6848

Waiting for the credentials.

**Comment by MohammedKaludi** [comment]
:+1:  Ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
