### ISSUE TITLE
Wrong AMPHTML when using static page in reading settings

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2396]
Wrong AMPHTML when using the static page in reading settings BUT creating it as a blog page by using page builder or by theme feature.

Reading settings - http://take.ms/4eBGR
Creating a blog - http://take.ms/OiMlR
Page of non-amp - http://take.ms/CmzWz
AMPHTML - http://take.ms/7jbkU

Currently, it's website.com/page/2/amp/ BUT needs to be website.com/amp/page/2/

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/66ff0a0fcc884f4ce6e290c3b423807413089b4f#diff-6aa5512f7dd8d5ce60fc97b0f340912cR371

 Need to rewrite the function name

**Comment by MohammedKaludi** [comment]
Need to remove the switch, and need to update the conditions to check on which page need to modify the url.

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
