### ISSUE TITLE
Problems with categories again. something/amp/404

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2398]
This canonical page doesn’t exist - it is meaningless

mydomain/cat/my-category/page/

but this one seems to

mydomain/cat/my-category/amp/page/

This of course produces an error in google console.

The general problem is you have not fixed 

mydomain/something/amp/rubbish

This just redirects and it should be a 404.

**Comment by Frenchomatic** [comment]
This has now been going round on various versions but never solved once and for all.

If a page doesn’t exist then it is naturally a 404. What you don’t want is an infinite number of 301 redirects. Think about the load on a server if someone spams mydomain.com/amp/xxx mydomain.com/amp/xxxx etc All of these will redirect and load the home page mydomain.com/amp/ . This occurs with every amp url.

There are two scenarios

1. AMP takeover – mydomain.com/rubbish/ is a 404 (generated by the AMP plugin) – it currently works, mydomain.com/good-path/amp/ currently 301 redirects to mydomain.com/good-path/ but it should be a 404 generated by the AMP plugin. So this is broken.

2. A mixed system of AMP and non AMP pages. mydomain.com/amp/rubbish/ should be a normal wordpress system 404 but it simply shows the content of mydomain.com but on the url mydomain.com/amp/rubbish/ This is very bad. It is like that for all urls – e.g. mydomain.com/goodpath/amp/rubbish/. Finally, mydomain.com/rubbish/amp/ does work correctly and gives a normal wordpress 404.

It seems to me that the way to solve this is to test the normal wordpress system to see if a url is a good one in the first place. If not then it is a 404 and the AMP plugin only has one choice to make – either issue a wordpress canonical 404 or a AMP plugin variation if the site is in AMP takeover.

**Comment by ToufiqSuhail** [comment]
Needs to get that fix as we have a valid reason where people can spam you by placing a link and Google will consider that as a valid URL. 

Ref: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2398

**Comment by MARQAS** [comment]
Hi @Frenchomatic, I contacted you through the mail, please do check

**Comment by Frenchomatic** [comment]
I have responded.

**Comment by ahmedkaludi** [comment]
I guess the point is the 404 should be 404, period.

**Comment by keshavsharma333** [comment]
One more user getting this issue:
https://secure.helpscout.net/conversation/937368014/79178?folderId=3044500

**Comment by MohammedKaludi** [comment]
Removing `/amp/`with str_replace is not a good idea, it will break the urls with the text like `amplifiers`, this has happened  in past.

use any alternative method to remove it from the url.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/815353e8657f80fb5227f2727f00f60ee29ca76b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR515

**Comment by MohammedKaludi** [comment]
check if only numbers are passed through the `get_query_var()`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/815353e8657f80fb5227f2727f00f60ee29ca76b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR561

**Comment by wasimmagazine3** [comment]
Commit processed it e4c2f4b6

**Comment by MohammedKaludi** [comment]
Not working in the test.

**Comment by Zabi09** [comment]
While merging need to add one condition in ampforwp_check_404_url function -
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/809dc835b9266bab5bb6edb523ac1838572668e9

**Comment by Zabi09** [comment]
While merging need to another condition in ampforwp_check_404_url function -
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0f436f836e1176c2e7bd9030f1a0699122c98616

**Comment by ahmedkaludi** [comment]
![image](https://user-images.githubusercontent.com/16532359/69947490-beed3500-1513-11ea-9d90-2044acde2297.png)

![image](https://user-images.githubusercontent.com/16532359/69947500-c44a7f80-1513-11ea-8cfe-561e67307a4a.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Frenchomatic** [comment]
seems ok nowadays
