### ISSUE TITLE
Embeds not working in Archive Description

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2402]
Reference: https://secure.helpscout.net/conversation/624645185/30636?folderId=2090438

A user is trying to add the Video in Category Description through " Add Media Option " and the Embed Video is not rendering in the AMP Page.

**Comment by Zabi09** [comment]
The script is loading only when the video is present in the category description.
post - http://take.ms/bRvng
page - http://take.ms/5TN8y
another category - http://take.ms/t59o7
if we add the content with iframe - http://take.ms/X3y9D

**Comment by MohammedKaludi** [comment]
Wrap it in `if ($description)`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ef460829579c86a2b1c3bbd7b795eff9aecdd08c#diff-b6438fc932bdcf0c8a01c3c146505c9eR297


Might throw the error in debug log.

**Comment by MohammedKaludi** [comment]
:+1: can be merged in master.

**Comment by Omair52** [comment]
Pushed in 0.9.97.16
