### ISSUE TITLE
When Google Analytics is ON ... (Parallelize downloads)

### ISSUE THREAD

**Issue by shtefcs** [ahmedkaludi/accelerated-mobile-pages#2405]
I just noticed when i turn on Google Analytics in AMP plugin, the Pindgdom Tool reports **Parallelize downloads across hostnames**

https://i.imgur.com/EgouRTr.png

Is there fix for that?

**Comment by ahmedkaludi** [comment]
@shtefcs I don't think that has anything to do with the Analytics.

Can you share the URL that you are checking so that I can check and let you know.

**Comment by shtefcs** [comment]
Okay, here is the url to the website, (**NSFW Content**) https://goo.gl/bk2M8D and here is the [Pingdom](https://tools.pingdom.com/#!/bm42zF/https://smuted.com/?s=teen+beauty)

**Comment by shtefcs** [comment]
Also, noticed this warning as well when Google Analytics is turned ON. 

![](https://i.imgur.com/2ZrtEWo.png)

Is it possible to combine?

**Comment by Zabi09** [comment]
@shtefcs 
That's really strange to hear that, Will you please a staging website which doesn't have the NSFW Content and then you can send the credentials to us on team@magazine3.com and let me know

Once I receive your info I will start working on it.

**Comment by MARQAS** [comment]
This has nothing to do with the analytics. It's pingdom who doesn't know how to test an AMP page.
