### ISSUE TITLE
Notice: Undefined index: amp-rtl-select-option

### ISSUE THREAD

**Issue by meno010** [ahmedkaludi/accelerated-mobile-pages#2407]
1 - I have these errors

Notice: Undefined index: amp-rtl-select-option in /home/bestcop2/public_html/wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/blurb-mod-module.php on line 59

Notice: Undefined index: amp-rtl-select-option in /home/bestcop2/public_html/wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/counter-mod-module.php on line 39

Notice: Undefined index: amp-rtl-select-option in /home/bestcop2/public_html/wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/testimonial-mod-module.php on line 26

Notice: Undefined index: amp-rtl-select-option in /home/bestcop2/public_html/wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/cta-mod-module.php on line 22

2-Why I can't use the plugin with the theme that uses Redux Framework as a panel?

**Comment by Zabi09** [comment]
@meno010 
That's really strange, Will you please contact us on team@magazine3.com I will personally take a look at those notices and also I will fix your problem of the redux framework.
Please let me know

**Comment by Zabi09** [comment]
@meno010 
Will you please contact us on team@magazine3.com to debug your issues, Please let me know

**Comment by Zabi09** [comment]
We have fixed both of your issues and it will be released in the next update but if you need instantly then contact us on team@magazine3.com, I will personally fix that on your end.

**Comment by MohammedKaludi** [comment]
:+1: ready to push

**Comment by Zabi09** [comment]
the business module is still in beta so added in 4 files
