### ISSUE TITLE
Wrong implementation of load_plugin_textdomain function

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2408]
Firstly there are two load_plugin_textdomain functions loading on the main file - http://take.ms/UIPJL and both have the different paths and names and there is also no "Domain Path" path in the main file header and also TinyMCE's "load_textdomain" function is loading which is not necessary.
We are testing on "Display text domains" plugin.

**Comment by MohammedKaludi** [comment]
:+1: ready to push.

**Comment by Omair52** [comment]
pushed in 0.9.97.17
