### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#2409]
Fatal error: Out of memory (allocated 2097152) (tried to allocate 110592 bytes) in C:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\admin-config.php on line 4957

**Comment by ahmedkaludi** [comment]
@Zabi09 what is this?

**Comment by Zabi09** [comment]
This is because of PWA and if we rename it the error is gone

**Comment by Zabi09** [comment]
Closing this ticket approved by @ahmedkaludi
