### ISSUE TITLE
Exclude post part Big issue : Posts that should not have AMP get showed as AMP

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#241]
https://wordpress.org/support/topic/some-issues-with-plugin/#post-8494214

Video : http://take.ms/yLWKf

**Comment by MohammedKaludi** [comment]
right, the post who's amp version is deactivated, should also be excluded from amp.

Possible solution: We can save the value in meta field and get the post ID and exclude the posts from the loop.

**Comment by ahmedkaludi** [comment]
The code was a bit mess, so had to revert:
- https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/9dcc9f052d26c18c325b6413d8666121c7d179a3
- https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/065bef9c0dc15c451ecfde20cf905716fca9ca04

**Comment by ahmedkaludi** [comment]
We're removing this from the milestone for now.

**Comment by khaledMohammed000** [comment]
@ahmedkaludi ok .... I had @MohammedKaludi Bhai's permission to mess up that code....He said he would fix that issue 👍
