### ISSUE TITLE
Need to make a space in meta information and published date is not getting translated.

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2411]
Need to make a space in meta information and published date is not getting translated.

Ref:  https://secure.helpscout.net/conversation/631114274/31175?folderId=1914712

see this screenshot:  https://prnt.sc/kcxcjy

see this screenshot:  https://prnt.sc/kcxcak

Wp and FTP are in

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Omair52** [comment]
pushed in 0.9.97.17
