### ISSUE TITLE
Collision with WP REST API

### ISSUE THREAD

**Issue by nash-ye** [ahmedkaludi/accelerated-mobile-pages#2412]
Starting from version 0.9.97.3, the plugin causes a blank page on `wp-json/wp/v2/posts` end-point with no error message or log. Although 0.9.97.3 is a minor update. However, there are 107 edited files compared to 0.9.97.2 and no proper changelog about it!. Do you know what may cause the collision with WP REST API? I couldn't reproduce the problem yet.

https://plugins.trac.wordpress.org/changeset?old=1904015&old_path=accelerated-mobile-pages&new=1901262&new_path=accelerated-mobile-pages

**Comment by Zabi09** [comment]
@nash-ye 
We have tested the same on our end with the latest as well as the old versions and it's working perfectly - http://take.ms/1S1TI

Will you please share the URL of your website, So that we will check and let you know.

**Comment by nash-ye** [comment]
Yes, I know, it's a strange problem, I tried to reproduce it on a new WP instance but with no luck. Currently, we are using the version 0.9.97.2 on production. What you suggest?

**Comment by ahmedkaludi** [comment]
@nash-ye try to use the latest version and see if it works?

**Comment by nash-ye** [comment]
Nope, it doesn't work, all the versions starting from v0.9.97.3.

**Comment by Zabi09** [comment]
One of our developers have replied to you on this issue on our support ticket #5769, Will you please check that once and let us know,

**Comment by nash-ye** [comment]
Thank you.
I had replied on him.

Please, let this issue open until we fix it, maybe someone else is facing the same problem.

**Comment by syedimran22** [comment]
Desc:  WP REST API Isn't Working with AMP plugin
Ref: https://secure.helpscout.net/conversation/631581381/31223/?folderId=1060556

**Comment by Zabi09** [comment]
@nash-ye is your issue solved? Will you please reply back on our support ticket #5769
