### ISSUE TITLE
AMP should remove spaces from GTM ID automatically.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2413]
Desc: Spaces in Google Tag manager ID from the options panel should be removed automatically.

ref: https://secure.helpscout.net/conversation/622297628/30415?folderId=1060556
Screenshot:  http://take.ms/F1HYe

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
