### ISSUE TITLE
Add a switch option of AMp page builder in the page builder section.

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2414]
Need to create an option of AMP page builder in page builder section of AMp panel, in which user can be enabled or disabled the page builder from the settings. and the option should be enabled by default.

(Junaid) Ref:  https://secure.helpscout.net/conversation/626844858/30823/?folderId=1914712

**Comment by MARQAS** [comment]
means if somebody wants to turn off the page builder then they can do so.

**Comment by MohammedKaludi** [comment]
:+1: can be merged in master.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
escaping is missing 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/46a6b7215bdea2b9ed6e29eb2fdc6c048877fa19#diff-260eba6333c3222e59a6aed22ac5ab37R1361

and


 use ampforwp_get_the_ID() instead this chunk of code
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/46a6b7215bdea2b9ed6e29eb2fdc6c048877fa19#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6655

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
