### ISSUE TITLE
Blank lines inserted into code

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2415]
OK so further investigation shows that if you have `><` in the editor then a blank line gets inserted. Minmisation afterwards produces a space but the problem occurs before that part of the process. 

example 

`<li><strong>`  and this gets put in the source

```
<li>
<strong>
```

**Comment by Frenchomatic** [comment]
Look at class AMP_Content_Sanitizer in class-amp-content.php

$content containing `><` from the editor is fine up until where it gets sanitized. Blank lines do not get inserted.  You can see that if $content contains `><` which is in the editor then $sanitized_content will have a blank line inserted. If you trace it through you will see class AMP_Content_Sanitizer is where the problem occurs with this being called class-amp-dom-utils.php which is doing something strange. In other words 

`<li><strong>` is in $content but in $sanitzed_content you get `<li>BLANK LINE<strong>` and other examples too where `><` meet each other.

**Comment by Frenchomatic** [comment]
see this https://github.com/Automattic/amp-wp/issues/1304#issuecomment-409682855

**Comment by Zabi09** [comment]
This ticket will be fixed in #2445
