### ISSUE TITLE
Addthis Support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2416]
https://www.addthis.com/blog/2018/07/23/addthis-is-now-available-for-amp/#.W2GW7NgzbSx

**Comment by MohammedKaludi** [comment]
Why add this only for design 3? Why not for all designs.

**Comment by WebSwiftSEO** [comment]
Looking forward to seeing how this comes out on my new funny video website [Funny Flix Videos](https://funnyflix.video) :) Combination of the 'best wordpress AMP plugin' with the 'best share tools'

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MARQAS** [comment]
Ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.49
