### ISSUE TITLE
Conflict with Layouts Header Options

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2418]
https://github.com/ahmedkaludi/amp-layouts/issues/16

**Comment by RajuJeelaga** [comment]
@ahmedkaludi Sir, Need to review and check all the Headers and after that @MohammedKaludi  sir will see the code and he close this ticket.

**Comment by ahmedkaludi** [comment]
Failed very badly, because the layouts are not showing in the properly.

**Comment by ahmedkaludi** [comment]
**REVIEW:**

- [ ] We have a issue of carousel in category module, until that is fixed, then we cannot check it.

**Comment by MARQAS** [comment]
Escaping is required

**Comment by MARQAS** [comment]
I activated the plugin, selected one header or import one design, it was all working fine, then I deactivated the AMP layouts and the result is this: https://monosnap.com/file/FkCXx0Uf3PxTJeBzaZYCb53it2J5t4

**Comment by ahmedkaludi** [comment]
discuss with me if you are going to work on this
