### ISSUE TITLE
Latest post title is displaying in the AMP homepage instead of site title

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2419]
When the user sets the static page in reading settings and homepage in AMP, then the homepage title is displaying the latest post title.

Also unable to recreate the issue on the local host.

Ref:  https://secure.helpscout.net/conversation/631689534/31247?folderId=1060554

Asked for the FTP

**Comment by Zabi09** [comment]
FTP is here - https://secure.helpscout.net/conversation/631689534/31247?folderId=1060554

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
