### ISSUE TITLE
More Structure data [Recommended by Park West]

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#242]

**Comment by Timbral** [comment]
Hi Mohammed,

I'd like to recommend that you add additional inputs to the structured data panel. I have noticed that many users on the WordPress support forums are receiving SD errors from Google's AMP test. If users were able to input SD values in the settings panel, that could take care of missing data and/or values where defaults fail. I hope this makes sense, but I imagine this could be a useful feature for many many users... I also believe you guys should take a new branch of premium features in an effort to monetize this extraordinary extension.

**Comment by ahmedkaludi** [comment]
Continuing this ticket in #323
