### ISSUE TITLE
Typo in "Hide AMP for Posts from All pages" (0.9.98)

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2420]
You have a small mistake in the text for the "info" tooltip. It's written "Hide AMP for Posts from All pages…" when you should have written "Hide AMP from all Posts"

Screenshot:  https://monosnap.com/direct/cuDLMx6BmlDRynNkFHn0Cf3FnJipbn

**Comment by ahmedkaludi** [comment]
Reviewed.

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge, but this ticket is blocked by #2301

**Comment by MARQAS** [comment]
It will be merged in master with #2301
