### ISSUE TITLE
IP Anonymization

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2421]
The Value for the anonymizeIP is currently set to " True " which should be changed to " Set ".

Reference 1: https://secure.helpscout.net/conversation/632279261/31301?folderId=1060554

Reference 2: https://wordpress.org/support/topic/google-analytics-ip-anonymization/

**Comment by ahmedkaludi** [comment]
Reviewed.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.12
