### ISSUE TITLE
To make the Compatibility with Gutenberg

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2427]
https://wordpress.org/support/topic/gutenberg-wordpress-5-0-is-not-far-away/

GutenBurg:

https://wordpress.org/plugins/gutenberg/

**Comment by MohammedKaludi** [comment]
breaking the category module, converting it to the gallery.

The code is applying everywhere, this should only effect on Gutenberg modules.

**Comment by MohammedKaludi** [comment]
@MARQAS as we have added files in vendor folder. Need to update the vendor log.

**Comment by MohammedKaludi** [comment]
What can we do to get the styling?

NON-AMP: http://take.ms/y5d1q
AMP without Styling: http://take.ms/kZTAF

In the amp, Unicorn image is loading on the page, but because it is not getting the stylings, the Block is not loading. Block is called "Cover Image". http://take.ms/H36o0

**Comment by pegazee** [comment]
The "cover image" block is working on my end but the shadow on the image is not loading properly on AMP.

Screenshots:
non-amp > http://take.ms/oPKLl
amp > http://take.ms/rzeeS

**Comment by pegazee** [comment]
** REVIEW **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by pegazee** [comment]
** REVIEW **

 - [ ] Kaleem

- [ ]  Imran

- [ ]   Talha

**Comment by beingsmart3** [comment]
Cover Image Issue
Master: http://take.ms/iwpcAq
Beta:  http://take.ms/JkMwr

**Comment by syedimran22** [comment]
Cover Image is getting zoom-in compared to the non-amp cover image.

**Comment by MARQAS** [comment]
It is working as expected. 
@beingsmart3 @syedimran22, we have not yet added this ticket in the master

**Comment by MohammedKaludi** [comment]
Page Breaking with Gutenberg.

**Comment by MARQAS** [comment]
Can you check again @MohammedKaludi?

**Comment by MohammedKaludi** [comment]
gallery throwing validation errors
https://monosnap.com/file/zg7MnPFWy1X9oOtD7iy5TcIvMe1Gm6

**Comment by MARQAS** [comment]
It is working as expected on my end, can you share the content which you are trying to add?

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
