### ISSUE TITLE
Amp not working for wordpress static page templates

### ISSUE THREAD

**Issue by raunakhajela** [ahmedkaludi/accelerated-mobile-pages#2428]
I create a page and used amp page builder to design my custom page. It is working fine as usual but when I use that same page for homepage display from settings>reading it doesn't work.

**Comment by MohammedKaludi** [comment]
Have you setuped the custom frontpage from amp options panel?

**Comment by raunakhajela** [comment]
Yes

**Comment by MohammedKaludi** [comment]
You need to setup a custom frontpage from "AMP Options Panel". 

I have checked the link you have mentioned and I think it is not setuped from AMP option panel. 

Can you once please check and let me know?

**Comment by raunakhajela** [comment]
It's working now. Had some issue with page cache and server. Thanks :+1:
