### ISSUE TITLE
Need to implement the Facebook live chat feature in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2430]
Ref:  https://secure.helpscout.net/conversation/633102221/31382?folderId=1914712

Here are the hints which help to implement this feature:

https://www.amp-blogger.com/2018/02/add-facebook-messenger-live-chat-to.html

https://blogr-amp.blogspot.com/2018/02/facebook-messenger-live-chatbox-for-amp.html

**Comment by ahmedkaludi** [comment]
**REVIEW**

- [ ] This should be in a different section called "Facebook Like Chat" on the top: http://take.ms/zWZm2

**Comment by ahmedkaludi** [comment]
**REVIEW**
- [ ] when we enable this feature, it should have a sticky icon on the bottom right side of the screen: like this: http://take.ms/GdPcW - Should not be attached with the social sharing icons.

**Comment by beingsmart3** [comment]
- [ ] Live chat position should be like this see this screenshot:  http://take.ms/sKGSe

- [ ] Live Chat Feature is not working on Convert AMP to WP theme (Beta) option.

**Comment by MARQAS** [comment]
Some frontend crafting is required. @RajuJeelaga please take care of it.

**Comment by RajuJeelaga** [comment]
when click on the icon, on the popup overlay it is showing blank, It need to show configure message.. if it is empty....
@ahmedkaludi

**Comment by Zabi09** [comment]
Escaping is missing

**Comment by ahmedkaludi** [comment]
We will add it in https://trello.com/c/6iwWx4q3/1021-facebook-live-chat-feature
