### ISSUE TITLE
Allow SVG format Logo in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2431]
Ref:  https://secure.helpscout.net/conversation/632971076/31371?folderId=1914712

**Comment by Zabi09** [comment]
- [ ] SVG logo needs to work with flexible width also - http://take.ms/YcSjG

- [ ] Should also work on AMP page builder

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
