### ISSUE TITLE
Some improvements for better enhancement

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2432]
- [x] Save button of the AMP panel should be in the absolute position - http://take.ms/6k2XP

- [x] AMP icon must also be there in post edit as well (Admin Bar) - http://take.ms/XFlkF

- [x] Should be opened in the new tab if click visit AMP - http://take.ms/PLSsW

**Comment by ajeetku** [comment]
For this we need to add js code in min file also: check last commit

**Comment by pegazee** [comment]
@zabi please communicate with @ajeetku

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
not looking good in big screens

https://monosnap.com/file/9jgAQAeduVJ4oOv98SGaJVH4a4Z11e

DO CONTACT ME BEFORE WORKING ON THIS.

**Comment by MohammedKaludi** [comment]
Still shifting to left

**Comment by MohammedKaludi** [comment]
Still shifting to the right
https://monosnap.com/file/sbsBD04IFx2CiLm6PTjP791CDftsJA

Please check once before adding to the review,

**Comment by MohammedKaludi** [comment]
minifying broke the panel.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
