### ISSUE TITLE
Page Float to right and showing menu content when page scroll horizontally in iPhone device

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2434]
in the iPhone the page showing menu content when its scroll horizontally.

solution: add this CSS it will fix the problem.
.m-ctr {
position: fixed;
overflow: scroll;
}
.m-scrl
{
display: inline-block;
width: 100%;
max-height: 94vh
}
Ref: https://secure.helpscout.net/conversation/626900191/30835?folderId=673457

**Comment by MohammedKaludi** [comment]
:+1: ready to push.

**Comment by Omair52** [comment]
pushed in 0.9.97.17
