### ISSUE TITLE
Yoast analysis is giving false readings for the SEO

### ISSUE THREAD

**Issue by ToufiqSuhail** [ahmedkaludi/accelerated-mobile-pages#2435]
User-created an AMP site with amp layout framework. But, the Yoast is not reading the amp layout framework
It is showing:
1. 0 words and there are certainly not 0 words
2. Internal and external links are not showing up on Yoast

Ref: https://secure.helpscout.net/conversation/633089991/31380?folderId=2075531
WP available

**Comment by MohammedKaludi** [comment]
function name `ExamplePlugin` ?? 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6f0756dc490e33702609aa785e6b8ee43e9261c6#diff-d370dd8bcc4152f09fdb55faebb56676R915

**Comment by MohammedKaludi** [comment]
make sure this code is added 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3d7612be7c53de4949eb5dc50db4a9752b24c812#diff-d370dd8bcc4152f09fdb55faebb56676

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Still 0 words 

https://monosnap.com/file/EYFPeVvA6sd4uwq4gmFNig1vkAr5WF

**Comment by MohammedKaludi** [comment]
:+1: ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.36

**Comment by MARQAS** [comment]
Options is added here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2944
