### ISSUE TITLE
Detect tablets separately, not consider it as mobile.

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2436]
We can use a lightweight mobile detection script  http://mobiledetect.net/
that can differentiate between mobiles and tablets.

This will also help resolve this ticket as well https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1444

**Comment by MohammedKaludi** [comment]
One more request: https://wordpress.org/support/topic/configure-for-different-android-devices/

**Comment by Rkroy** [comment]
Desc : When tablet mobile redirection is enabled, site is not getting redirected to AMP when viewed through mobile view, it is redirecting to AMP pages only through tablet view.
Ref : https://secure.helpscout.net/conversation/683624383/37212?folderId=2322652

**Comment by MARQAS** [comment]
Not working as expected, I've disabled the tablets option, but it is still redirecting to AMP in Tabs.

**Comment by MohammedKaludi** [comment]
rename the to a better one
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ba5c1b102e2e0b2ae7bc1437572e3f8c42c59982#diff-ab576767b896423d184ddafe2ede2310R156

use `amp-tablet-redirection` instead

**Comment by MohammedKaludi** [comment]
Credits added b03639e55c9e08f1f40ae9aab52fb8a65e3f4802

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.36
