### ISSUE TITLE
Audio Playlist Support 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2437]
Need to make the audio playlist compatibility - http://take.ms/PhxED 
just like this - http://take.ms/yugsJ

**Comment by pegazee** [comment]
Need proper testing from others system. 

@MARQAS @ajeetku @Zabi09 please make sure that testing is done properly.

**Comment by MARQAS** [comment]
It is working as expected, but I believe some styling is required to make it look better.

**Comment by MARQAS** [comment]
@ajeetku after you review it, please move it to the issues so that @RajuJeelaga can style it

**Comment by pegazee** [comment]
Backend code is done, need styling. Moving this to issue section, so that @RajuJeelaga can style it.

**Comment by MARQAS** [comment]
Unable to see the play button.
Screenshot: https://monosnap.com/file/POwoBB7yZaOiF5dPXa9pLvYhnbY90s

**Comment by MARQAS** [comment]
Why new file for CSS? Can we add in it in the same file?

**Comment by pegazee** [comment]
Yes, we can

**Comment by pegazee** [comment]
Need styling from @RajuJeelaga side

**Comment by MARQAS** [comment]
It is still breaking, try to add a long title.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
