### ISSUE TITLE
Add AMP consent in AMP Theme Framework

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2440]
We need to add amp consent code in the amp theme Framework.

**Comment by ansaritalha** [comment]
a  priority customer facing a couple of issue because of the GDPR.

**Comment by ansaritalha** [comment]
Ref:https://secure.helpscout.net/conversation/586257505/26644?folderId=673457

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.10, closing the ticket
