### ISSUE TITLE
words are breaking and not readable

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2441]
words are breaking and not properly readable in the beta version [0.9.98] because of the 
{word-break:break-all} CSS property.

Solution: use  {word-wrap: break-word} instead of {word-break:break-all} it will solve the issue.

**Comment by ahmedkaludi** [comment]
Reviewed

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.12
