### ISSUE TITLE
Vc Shortcode issue in beta 0.9.98

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2442]
Ref:  https://secure.helpscout.net/conversation/623856477/30568?folderId=1914712

Screenshot:  http://take.ms/QLd1T

**Comment by MARQAS** [comment]
More details can be found here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2287

**Comment by MohammedKaludi** [comment]
:+1: ready to push but it is depended with #2287

**Comment by MARQAS** [comment]
Resolved and added in #2287
