### ISSUE TITLE
Blank Lines in HTML Source code : Beta test

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2445]
I have tested the beta version and this is not solved 

#2425  The logo part - please see how I have coded it which fixes the issue. 

#2422 Blank lines are added when serializing HTML between elements that should not have whitespace  - solution given here #2422 (just need the utils folder) and here https://github.com/Automattic/amp-wp/pull/1309#issuecomment-410081948 .  An AMP folder is offered in its entriety here https://github.com/Automattic/amp-wp/files/2255287/amp.zip

**Comment by Frenchomatic** [comment]
@MARQAS Glad to see you are back - you disappeared. To clear up any confusion, I wrote to Automattic and they recognized the problem (see links above). One of the core WP developers provided a solution for the whole of the vendor AMP plugin. I simply extracted the utils folder containing the files dealing with the DOM and replaced it into your plugin AMP for WP.  The serialization within $content disappeared. The blank lines were correctly taken out.

**Comment by MARQAS** [comment]
Hi @Frenchomatic.
I will test this properly and will add the necessary code in our plugin.
Thank you so much for all your help

**Comment by MARQAS** [comment]
@Frenchomatic, I have added the necessary code, can you test now?

**Comment by Frenchomatic** [comment]
For some reason when I replace your file f2f8d31 it crashes my site - blank screen. The one offered by automatic doesn't.  You may like to do a diff on your file with there one. I actually use the whole of their utils folder.

**Comment by MARQAS** [comment]
@Frenchomatic I guess you have directly added the file in the master version of our plugin. 
Can you please try it by adding in the Beta version. 
Actually, we made some changes in the Beta version to avoid errors with other plugins which uses AMP by Automattic as vendor or the plugin itself. 

Or you can just download the beta version ( 0.9.98 branch ) in which I have updated this file.

**Comment by Frenchomatic** [comment]
yes - let me try the beta version.

**Comment by Frenchomatic** [comment]
OK - the beta-test version appears to resolve the serialization issue. However, on design 2 it is not picking up my ampforwp folderwhich sits in my main theme (I use my own menu file header-bar.php).

**Comment by MARQAS** [comment]
Thanks for pointing this out, Let me test this and resolve it

**Comment by Frenchomatic** [comment]
And did you get the same issue with the beta plugin?

**Comment by MARQAS** [comment]
@Frenchomatic Both things are working fine on my end, can you test it again? We made several changes recently.

**Comment by Frenchomatic** [comment]
Which download because I just tried the beta-test folder again and it is still not picking up the ampforwp folder in design 2.

**Comment by Frenchomatic** [comment]
0.9.98-beta -> OK - serializing HTML between elements that should not have whitespace is resolved and the ampforwp folder is now also being recognized. However, the logo.php file is still not correct but I guess you know that.

**Comment by Frenchomatic** [comment]
Thanks @MohammedKaludi  that works for the logo and the spaces are no longer present.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.12
