### ISSUE TITLE
Save settings button not showing in builder

### ISSUE THREAD

**Issue by Tjasaz** [ahmedkaludi/accelerated-mobile-pages#2446]
I have a WordPress website with Avada theme. Tried to use the AMP plugin builder, but it doesnt show any save buttons when I add any module and try to edit it. Any suggestions? Thanks!

<img width="1407" alt="screen shot 2018-08-09 at 07 28 52" src="https://user-images.githubusercontent.com/42230166/43879796-ee2aa8d6-9ba5-11e8-9412-ea7d7c9a66e6.png">

**Comment by Zabi09** [comment]
@Tjasaz Are you using the Safari and in that the Save Module is not working?

Will you please provide your wp-admin and FTP details on team@magazine3.com I will personally look into your issue and fix it on your end.

Please let us know,

**Comment by Tjasaz** [comment]
Yes, this is Safari. Unfortunately, our company security rules don't allow sharing any login data. Tried it with Firefox, the button shows.

**Comment by Zabi09** [comment]
@Tjasaz ok no problem,

Just add this code - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3f163b0049c3c96d92667083d62cb9712d6611a2

And let us know, your issue is fixed or not.

**Comment by Tjasaz** [comment]
Hey! Works as a charm. Thanks

**Comment by MohammedKaludi** [comment]
Need to push this in next update

**Comment by MohammedKaludi** [comment]
Need to push this in next update

**Comment by MohammedKaludi** [comment]
Closing the ticket, 
Added in master in #1943 the code will be pushed in 0.9.97.14
