### ISSUE TITLE
Need to Make the Compatibility with the footnotes plugin.

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2447]
Plugin: https://wordpress.org/plugins/footnotes/

Ref:  https://secure.helpscout.net/conversation/637233890/31766?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
