### ISSUE TITLE
To change the Icon of Telegram in all the Designs

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2448]
A user request is to change the official icon of the Telegram messenger.

Reference :https://wordpress.org/support/topic/the-official-icon-of-the-telegram-messenger/

Screenshot: http://i100.fastpic.ru/big/2018/0807/57/39d38c5ad28d6a18a1025be391cdf457.png

**Comment by ahmedkaludi** [comment]
**REVIEW**

- [ ] align these social icons with the layout: http://take.ms/68de5

**Comment by ahmedkaludi** [comment]
Reviewed

**Comment by ahmedkaludi** [comment]
Failed:

- [ ] Telegram Icon too small in D3

**Comment by Ysery** [comment]
When is it planned to add this icon?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
