### ISSUE TITLE
AMP-Mustache Warning

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2449]
For Ex:

https://www.screencast.com/t/X7mXe4l1

Users have reported that they're facing these Warnings on their Pages.

**Comment by Zabi09** [comment]
We are dynamically adding amp mustache latest scripts that is - 
<script custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-latest.js" async></script>
http://take.ms/fP0cD
http://take.ms/GnCfJ

And this warning is not coming from our AMPforWP plugin and so closing this ticket approved by @ahmedkaludi
