### ISSUE TITLE
Homepage title on amp pages

### ISSUE THREAD

**Issue by fikryans** [ahmedkaludi/Accelerated-Mobile-Pages#245]
i think this is a new problem for me after update new version amp plugin. because the title didn't show up my default title for homepage.
you can checkout my website https://www.tutorialpedia.net
can i disable amp pages for homepage?

![screenshot_218](https://cloud.githubusercontent.com/assets/8897997/20739843/e0c4c74e-b6f0-11e6-8d64-9951d46bcedf.png)
![screenshot_219](https://cloud.githubusercontent.com/assets/8897997/20739885/36a57df2-b6f1-11e6-9c7d-37ce8e8de93b.png)

**Comment by khaledMohammed000** [comment]
Yes we have observed this Error .. Give us some time and we will solve it :)

**Comment by MohammedKaludi** [comment]
@khaledMohammed000 if the issue was reported twice, make sure you add the reference of that ticket as well.

**Comment by khaledMohammed000** [comment]
#240

**Comment by iamrahulsethi** [comment]
I am facing same error in https://educationbhaskar.com AMP homepage

**Comment by ahmedkaludi** [comment]
Reviewed, and checked
