### ISSUE TITLE
Need to show alphabetical order all Extension part

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2451]

**Comment by RajuJeelaga** [comment]
I added all extension statically in an alphabetical order, @ajeetku need to work on some back end part.

**Comment by MohammedKaludi** [comment]
this has been fixed, please talk with @Zabi09 before merging it into master.

**Comment by Zabi09** [comment]
Sorting is working fine in master and I think there is no need to add this code in master?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
this is working fine in master as well. This ticket can be closed.
