### ISSUE TITLE
Preview of AMP feature is not Functioning.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2452]
Desc: Preview of AMP feature is not functioning

Ref: https://secure.helpscout.net/conversation/637261670/31769?folderId=2169251

**Comment by ahmedkaludi** [comment]
Its' a little complex for a small ticket, so we will skip from the sprint.

**Comment by ahmedkaludi** [comment]
Normal preview is not working either

**Comment by MohammedKaludi** [comment]
Preview is Working properly on my setup, the issue might be due to a JavaScript error blocking the preview to run, as the issue seems to be resolved.

I'm moving this ticket from backlog to testing, if everything works in the testing then this ticket can be closed directly.

**Comment by pegazee** [comment]
Preview is Working properly on my setup. I'm moving this ticket to @Rkroy 's pipeline. @Rkroy  If it's working on your end, you can close this ticket.

**Comment by pegazee** [comment]
AMP Preview feature is working perfectly, we can close this ticket.
