### ISSUE TITLE
Navigation disabled in AMP Version

### ISSUE THREAD

**Issue by maqbul2033** [ahmedkaludi/accelerated-mobile-pages#2457]
Hello
Sir, I have a jobs listing blog[ [https://www.allinonejobs.com](https://www.allinonejobs.com) ]. It's working well but coming to amp version right clicks disabled and navigation links [ internal + external ] links are not clickable event AdSense ads also. So users cant not goto home page from any of the pages. And I could get any click even I got 10k views also. I purchased the premium plugin for absence ads also. Please reply must

AMP Version:  [https://www.allinonejobs.com/amp](https://www.allinonejobs.com/amp)

**Comment by maqbul2033** [comment]
Hi
Sir, I am getting many problems with amp plugin so I deactivated even I purchased premium version also. But with my other sites its working well.

**Comment by Zabi09** [comment]
Will you please send me your website credentials on this email - team@magazine3.com and I will look into it and make sure the AMP will work on this site also.

**Comment by Zabi09** [comment]
@maqbul2033 
This is your last chance and if you don't reply to our previous messages then we will go ahead and close this ticket.
