### ISSUE TITLE
Categories Pagination issue

### ISSUE THREAD

**Issue by cosmin-serbanescu** [ahmedkaludi/accelerated-mobile-pages#2458]
Hey guys, 
I'm developing an AMP theme for my website but there's a strange issue regarding the categories pagination - apparently when you click on 'Older Posts' it opens up the blog page 2 and not that specific category page 2. It's like the pagination on the category doesn't modify the query.

Btw... tried also with the already existing themes in AMP -> Design -> Themes and the behavior is the same.
Any advice on how to get this  one fixed?

**Comment by Zabi09** [comment]
@cosmin-serbanescu 
That's really strange, Will you please send us the exact URL of your website, So that we will check once and let you know.

**Comment by cosmin-serbanescu** [comment]
Sure - here is the link of a category: https://www.codeinwp.com/blog/category/wordpress-tutorials/amp/ just click on 'Show More Posts' on the bottom and you'll see it's going on the second page of the blog query but the URL kind of looks good.
Thanks!

**Comment by Zabi09** [comment]
I have checked the issue and yes your issue is really a valid one that the category page is redirecting to the latest articles of the blog page BUT I have also noticed that in the category "WordPress-tutorials" your first post is "How to Adapt Your Plugin for Gutenberg: Part 1 (Block API)" and the same post is the 5th post in non-amp. Are you manually adding this or it's a bug?

And will you please provide me a temporary credential of your website on team@magazine3.com and let me know So that I will check the code and I will make sure that this issue will be fixed as soon as possible on your end.

**Comment by cosmin-serbanescu** [comment]
Good catch regarding that post! The query on the categories page is actually set up to display posts by updated date instead of published date and AMP probably removes that .. this is why there are different results.

One thing I noticed now is that https://www.codeinwp.com/blog/category/blogging-tips/page/2/?amp actually displays the good results instead of https://www.codeinwp.com/blog/category/blogging-tips/amp/page/2/ (the link that's on 'Show More Posts'). Maybe I can adjust the link somehow.

Unfortunately I cannot give you access to it as it's not my personal website but what I can do is provide a staging where the theme & the AMP theme will be installed. Let me know if you want that or if you can provide an easier solution.

Many thanks once again!

**Comment by Zabi09** [comment]
Yeah sure you can provide me the credentials(wp-admin and FTP) of staging website on team@magazine3.com and I will start my work

**Comment by cosmin-serbanescu** [comment]
Working like a charm now, @Zabi09! Simply changed the URL endings from /amp to ?amp and since this doesn't affect SEO we'll leave it like this.

Thank you so much for your help and keep up the good work!

**Comment by ahmedkaludi** [comment]
@cosmin-serbanescu but we still want to find out what went wrong!

**Comment by cosmin-serbanescu** [comment]
seems legit, I'll set up a staging site and send the credentials to team@magazine3.com

**Comment by Zabi09** [comment]
@cosmin-serbanescu We haven't received any credentials on team@magazine3.com? Will you please provide us and we will go deep into the issue and we will make sure it is fixed.

**Comment by cosmin-serbanescu** [comment]
@Zabi09 , nevermind, got it working, it was a problem on my end, so sorry for the delay!
