### ISSUE TITLE
Need to add domain when we're using redux for translating the field

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2460]
We need to add the domain when declaring the redux array. So, that user can translate the redux with WPML.

ref: https://secure.helpscout.net/conversation/629316836/31032?folderId=2206768

example: 

Screenshot > http://take.ms/EQdmr

Here, we're just calling the $redux_builder_amp array. Instead of this, we need to call like this > http://take.ms/ykRbm

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Tested on my end, working properly.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
