### ISSUE TITLE
Yandex Support integration in AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2461]
Yandex Support integration in AMP.

Ref:  https://secure.helpscout.net/conversation/623856477/30568?folderId=1914712

https://yandex.ru/support/webmaster/turbo/connection.html?lang=en

**Comment by Zabi09** [comment]
https://ampforwp.com/tutorials/article/how-to-add-yandex-metrika-analytics-in-amp/
