### ISSUE TITLE
Images are not aligned center when published with Gutenberg Editor

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2462]
Desc: User has provided a solution for that we have to test it on our End.
Solution: 
Before Gutenberg, "aligncenter" class is added to <amp-img> tag (<amp-img
class="*alingcenter* more-classes" />
But from Gutenberg, every <amp-img> tag is nested inside <figure> tag like
this
<figure class="wp-block-image *aligncenter*">
> <amp-img class="more-classes" />
> </figure>
If you notice "aligncenter" class is moved to <figure> tag from <amp-img>
tag.
So I added this CSS rule to fix the problem
.wp-block-image.aligncenter amp-img {
> margin: 0 auto;
> }

Ref: https://secure.helpscout.net/conversation/642619504/32138?folderId=2169251

**Comment by Omair52** [comment]
pushed in 0.9.97.17
