### ISSUE TITLE
Version 0.9.97.10 

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2464]
Disappointing that the main issue of _Blank lines are added when serializing HTML between elements that should not have whitespace #2445 has not been fixed in version 0.9.97.10 . Downgrading back to the previous version.

**Comment by Frenchomatic** [comment]
Yes I see that now - sorry for the emotive post title. I will continue testing the beta version of 0.9.98

**Comment by MohammedKaludi** [comment]
@Frenchomatic I totally understand it, No need to apologize.

Thank you very much for testing out and reporting the issues.

Mohammed Kaludi
