### ISSUE TITLE
Anchor Tag is not working because there is a space in between link. 

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2465]
Ref:  https://secure.helpscout.net/conversation/641820204/32092/

Anchor Tag is not working because there is a space in between link.

Example: `<h3 class="DWPxHb" style="padding-left: 30px;"><a href="https://dl.xdaapps.in/Pet paradise mod(xdaapps.in).apk">Download pet paradise mod apk</a></h3>`

**Comment by Omair52** [comment]
pushed in 0.9.97.17
