### ISSUE TITLE
amp-img Validation issue from 0.9.97.4 - Current Latest version

### ISSUE THREAD

**Issue by anirudhpulikonda** [ahmedkaludi/accelerated-mobile-pages#2466]
So, I noticed this issue on 0.9.97.4 update. But thought It'll get automatically fixed by the team in next update.

But, on 0.9.97.10 I'm seeing the same bug and wanted to get to your notice.

So let's talk about the issue:

After I've updated to 0.9.97.4, I've received a couple of messages from search console saying your blog has amp validation issues and found the issue is:

![image](https://user-images.githubusercontent.com/20200408/44301083-f93abf00-a32e-11e8-8296-efc35b67a51a.png)

I've tested the consecutive update x.5, x.6 upto the latest 0.9.97.10. I'm facing the same issue and I've not only observed this issue on a single blog. But I've seen couple of my other blogs facing the same issue after the update.

For the time being, I've rolled out to 0.9.97.3 and was using the AMP as is. Once, we remove the logo from the AMP Settings and revert to Text Heading. I'm not seeing any AMP Validation issues

![image](https://user-images.githubusercontent.com/20200408/44301162-e5438d00-a32f-11e8-935b-96aad10716c2.png)

Logo is also missing along with validation issue on x.3 - x.10 update

![image](https://user-images.githubusercontent.com/20200408/44301189-381d4480-a330-11e8-94a1-e43701a2e1c7.png)

URL: [https://www.watchmetech.com/amp/](https://www.watchmetech.com/amp/)

**Comment by Zabi09** [comment]
@anirudhpulikonda 
I have visited your website - https://www.watchmetech.com/amp/ and the logo is appearing without any errors.
Have you reverted to the previous version?
Are you facing the issue only when you update the latest plugin?

Will you please provide me the temporary credentials on team@magazine3.com, I will personally look into it and I make sure the logo will work perfectly in the latest version

**Comment by anirudhpulikonda** [comment]
Yes, I've reverted to 0.9.97.3, Let me create a clone of the site and share the credentials to the mail ID you just provided.

**Comment by Zabi09** [comment]
Okay, please create a clone of the site and let me know So that I can start my work

**Comment by anirudhpulikonda** [comment]
Done. Please check the email for credentials and the cloned app URL.
