### ISSUE TITLE
Fix social shares icons

### ISSUE THREAD

**Issue by johnpkeek** [ahmedkaludi/accelerated-mobile-pages#2467]
The Social share icons at the bottom of the AMP page should link to the amp page not the actual page. Please use clean and canonical urls while sharing these links.
![ampforwp](https://user-images.githubusercontent.com/6235208/44320165-e2df5100-a45d-11e8-897e-87cd25a6f5fb.JPG)

**Comment by MohammedKaludi** [comment]
incorrect usage of esc_url

**Comment by MohammedKaludi** [comment]
:+1: can be merged

**Comment by Omair52** [comment]
pushed in 0.9.97.17
