### ISSUE TITLE
'style amp-custom' is exceeding  the limit of 50000 when more Modules are used in AMP PAGE BUILDER

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2469]
Desc: 'style amp-custom' is exceeding  the limit of 50000 when more Modules are used in AMP PAGE BUILDER

Ref: https://secure.helpscout.net/conversation/642907934/32171?folderId=2169251

**Comment by Zabi09** [comment]
Going to fix in #2470
