### ISSUE TITLE
JetPack Support

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#247]
several people areasking JetPack Support

**Comment by khaledMohammed000** [comment]
Have a look at this http://take.ms/ZHa4W

**Comment by dwien** [comment]
Since AMP 0.3.2 there is a Jetpack Stats support

**Comment by ahmedkaludi** [comment]
@MohammedKaludi What do you think we should do with this ticket?

**Comment by ahmedkaludi** [comment]
Jetpack has been working properly with the recent AMPforWp release.
