### ISSUE TITLE
If AMP page builder is enabled then unnecessary CSS is also integrated 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2470]
The styles of breadcrumbs, amp comment, amp post pagination and author etc which is causing the validation errors of the limit of 50K bytes of style in AMP, So we need to remove that unnecessary styles in swift theme as well as in others themes

**Comment by RajuJeelaga** [comment]
In this ticket, only amp comment css are loaded extra, need to write the condition for that, other than that,
1.post pagination,
2.breadcrumbs
3.Author 
These all CSS are loaded on condition in pagebuilder.

**Comment by MARQAS** [comment]
Use `ampforwp_get_setting`

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
use `ampforwp_get_the_ID()` instead of `get_the_ID`

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
