### ISSUE TITLE
Improvements in AMP page builder code

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2471]
- [x] 1. Need to rename the "amppb-fluid" class dynamically - http://take.ms/ooJ1O

- [x] 2. Need to rename the ".amppb-fixed" class dynamically - http://take.ms/BN04m

- [x] 3. Need to rename the "slant" class dynamically - http://take.ms/eVCA9

- [ ] https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2711

- [ ] 5. The margin and padding should have two 2 values if the same values are repeating  - http://take.ms/0od2q (This Css Pregmatchs are not working)

**Comment by syedimran22** [comment]
Desc: Almost 3-4 Users are facing this kind of validation errors "The author stylesheet specified in tag 'style amp-custom' is too long - document contains 58521 bytes whereas the limit is 50000 bytes." and their pages are not getting indexed so these issues has to be fixed immediately.

Ref: https://pastebin.com/JyUkmihA

**Comment by syedimran22** [comment]
Desc: One more user is facing the author style sheet issue  'The author stylesheet specified in tag 'style amp-custom' is too long - document contains 59764 bytes whereas the limit is 50000 bytes. Debug. Learn more."
Ref: https://secure.helpscout.net/conversation/677705782/36283?folderId=2169248

**Comment by Zabi09** [comment]
4 and 5 points will be fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2711

**Comment by MohammedKaludi** [comment]
:+1: looks great, merging into master.

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
