### ISSUE TITLE
Debug errors in beta

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2472]
http://take.ms/dLwT0

**Comment by Zabi09** [comment]
<b>Notice</b>:  Undefined index: id in <b>\plugins\accelerated-mobile-pages\templates\features.php</b> on line <b>6391</b><br />

**Comment by MohammedKaludi** [comment]
:+1: can be merged

**Comment by Omair52** [comment]
pushed in 0.9.97.17
