### ISSUE TITLE
Infinity Scroll Option is not working when ?amp option is enabled in beta

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2475]
Desc: Infinity Scroll Option is not working when ?amp option is enabled in beta and it is also reflecting Undefined at the end of URL when it scrolled back to 1st page.

Ref: https://secure.helpscout.net/conversation/649790686/32709?folderId=2169251

**Comment by syedimran22** [comment]
Desc: User has found these issue too while using infinity scroll option
 1) "dont detect if we change the size of feature image or the container don't update for the new size on infinite scroll!" 
2) "custom css don't apply correctly when activate in the global under appereance!"
3)"google analytics don't show the new page open or article open."

**Comment by MARQAS** [comment]
It is working properly with ?amp 
http://take.ms/ekPWg

**Comment by MARQAS** [comment]
1: "dont detect if we change the size of feature image or the container don't update for the new size on infinite scroll!"
Answer:  It is working as expected

2: "custom css don't apply correctly when activate in the global under appereance!"
Answer: It is working as expected.

3)"google analytics don't show the new page open or article open."
Answer: This feature is still in experimental by AMPHTML, so we can't say on this much at the moment.

**Comment by Zabi09** [comment]
For some posts, only the titles are appearing on single - https://prnt.sc/mbdybo and on some posts only one post is appearing fine and other two posts are showing only titles - https://prnt.sc/mbdy83

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
