### ISSUE TITLE
Unable Access the Wp-admin page when Amp takeover option is Enabled.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2476]
Desc: Unable Access the Wp-admin page when Amp takeover option is Enabled. and also the design is also changed.

Ref: https://secure.helpscout.net/conversation/627370493/30882?folderId=1680011

**Comment by ahmedkaludi** [comment]
@syedimran22 Can you look into this @zabi09 ?

**Comment by ahmedkaludi** [comment]
@ahmedkaludi Let's fix this as soon as possible

**Comment by Zabi09** [comment]
This issue was coming from the Theme My Login plugin - https://wordpress.org/plugins/theme-my-login/ but now it is fixed.

**Comment by MohammedKaludi** [comment]
can we improve the code here?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d5b0b900879f5055e229cc1d862749c1156147df#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6778

@Zabi09 
I have some ideas, do let me know when you start the work on it.

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master.

**Comment by MohammedKaludi** [comment]
Need to update the way we get the current page url
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/73bc859b2d838b379b590c5cbcf54fc431331f21#diff-ab576767b896423d184ddafe2ede2310R103

**Comment by MohammedKaludi** [comment]
:+1: code will be pushed in 0.9.97.22

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
