### ISSUE TITLE
FTP Link being generated in Non-AMP but not in AMP

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2477]
< a href="ftp://download.epson-europe.com/pub/download/6306/epson630619eu.exe">Download</a>

https://wordpress.org/support/topic/link-to-ftp/

The Link for FTP isn't being generated in AMP Version so, need to solve this.

**Comment by MohammedKaludi** [comment]
:+1: can be merged.

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
