### ISSUE TITLE
Changes in ?amp : Re-direct  " /amp " to " ?amp "

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2480]
Whenever a user has enabled " ?amp " and if the URL opens with " /amp " then it should be redirected to   
 " ?amp ".

Ref:
https://secure.helpscout.net/conversation/641312486/32057/

https://somoslibros.net/book/hotel-de-las-musas/

**Comment by MohammedKaludi** [comment]
wrong hook used

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: pushed in 0.9.97.41
