### ISSUE TITLE
'amp_post_template_footer' and 'amp_post_template_css' hooks are Global or not?

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2481]
Desc: As 'amp_post_template_footer' and 'amp_post_template_css' hooks are global hooks so why we are removing it in Swift theme.

See this Screenshot: https://monosnap.com/file/pyHuEnIaz11oQ21PWBMSJSNCq0SGWE

**Comment by Zabi09** [comment]
It's there and verified.
