### ISSUE TITLE
Is there a way to change the domain or URL value for the rel="canonical" link on AMP pages?

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2482]
Desc: The user wants to change the domain or URL value for the rel="canonical" link on AMP pages for the specifics post.

Ref: https://secure.helpscout.net/conversation/650786766/32789?folderId=2206768

**Comment by Zabi09** [comment]
We already have this option so discussed with @ahmedkaludi and created the tutorial for it - https://ampforwp.com/tutorials/article/how-to-change-the-canonical-link-on-amp-pages/

**Comment by MohammedKaludi** [comment]
This ticket can be closed directly.
