### ISSUE TITLE
Report Bug Menu page disappears

### ISSUE THREAD

**Issue by AtagonL** [ahmedkaludi/accelerated-mobile-pages#2485]
Menu page disappears 
If you can fix or explain. Contact me please folkegm@gmail.com

https://www.xn--12clj5bwa4dc9icc9a.com/%E0%B8%81%E0%B8%A3%E0%B8%A1%E0%B8%AD%E0%B8%B8%E0%B8%95%E0%B8%AA%E0%B8%B2%E0%B8%AB%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%A1%E0%B8%9E%E0%B8%B7%E0%B9%89%E0%B8%99%E0%B8%90%E0%B8%B2%E0%B8%99%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%80%E0%B8%AB%E0%B8%A1%E0%B8%B7%E0%B8%AD%E0%B8%87%E0%B9%81%E0%B8%A3%E0%B9%88/amp/

![s__10944518](https://user-images.githubusercontent.com/42388944/44835190-9e259800-ac5d-11e8-9656-905d291002ca.jpg)

**Comment by Zabi09** [comment]
@AtagonL 
Hi, Have you enable the option of the menu in Appearance => Menus => AMP menu.
See this screenshot: http://take.ms/1JRXc

And still, you have the issue? Please let me know

**Comment by AtagonL** [comment]
Don't work menu is *distorte*d <https://dict.longdo.com/search/distorted>


2018-08-30 17:35 GMT+07:00 Syed Zabiuddin <notifications@github.com>:

**Comment by Zabi09** [comment]
@AtagonL I have sent you the message on folkegm@gmail.com will you please check that once and let me know

**Comment by Zabi09** [comment]
@AtagonL 
This is your last chance and if you don't reply to our previous messages then we will go ahead and close this ticket.
