### ISSUE TITLE
Wrong parent tag 'body' of javascript tag 'amp-form extension .js script'

### ISSUE THREAD

**Issue by SysAdminNWM** [ahmedkaludi/accelerated-mobile-pages#2487]
Wrong parent tag 'body' of javascript tag 'amp-form extension .js script'

**Comment by SysAdminNWM** [comment]
??

**Comment by SysAdminNWM** [comment]
https://networkwestmichigan.com/amp/

----- Message from Syed Zabiuddin <notifications@github.com> ---------
    Date: Thu, 30 Aug 2018 22:23:52 -0700

**Comment by Zabi09** [comment]
@SysAdminNWM I have checked your website - https://networkwestmichigan.com/amp/ and it's valid without any errors - http://take.ms/c0zjo and also the amp-form script is placed in the head section only not in the body - http://take.ms/38sTG

Will you please elaborate more on your issue, So that I can help you.

**Comment by SysAdminNWM** [comment]
Simply put, Google is issuing AMP error notices (got one today, the  
error seems to be persistent for some time now) witht the root domain  
url.

You can see the error that came from Google.

----- Message from Syed Zabiuddin <notifications@github.com> ---------
    Date: Fri, 31 Aug 2018 05:56:57 -0700

**Comment by SysAdminNWM** [comment]
Syed,

Let me run the validation in the Google Amp console to see if it  
re-evaluates. If it goes away, so be it. If it doesn't, I'll get back  
to you guys.

----- Message from Syed Zabiuddin <notifications@github.com> ---------
    Date: Fri, 31 Aug 2018 05:56:57 -0700

**Comment by Zabi09** [comment]
@SysAdminNWM Okay sure, please run the validation again and if you face any errors now or in the near future we are always here for your help.
