### ISSUE TITLE
Google Analytic issue while setting up Run Installation wizard

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2491]
That said, I have at least one possible bug to point out. If you run through the wizard at the very beginning and add in the Google Analytics tracking code, the settings then default to Google Tag Manager being active without anything filled in. It then has to be deactivated and Google Analytics selected, unless you want to configure GTM.

Ref:  https://wordpress.org/support/topic/cant-disable-related-posts-on-free-version/#post-10640975

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
