### ISSUE TITLE
homepage is getting blank when "Convert To WP" is enable only for posts

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2493]
Ref:  https://secure.helpscout.net/mailbox/cfb9786cbb6b9b7c/chats/b1cb2bd8-7b4a-40d4-9166-7f77ed83bb2c

**Comment by MohammedKaludi** [comment]
:+1: can be merged

**Comment by Omair52** [comment]
pushed in 0.9.97.17
