### ISSUE TITLE
Auto Recommendation Support for ads

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2495]
Auto Recommendation Support

**Comment by Omair52** [comment]
- [ ] After clicking "Activate" It shows two icons

- [ ] After it's enabled, Go to Settings Doesn't perform the action

- [ ] After reload of installation, button becomes link

**Comment by ahmedkaludi** [comment]
- [ ] http://take.ms/6Q3Cc

**Comment by ahmedkaludi** [comment]
Add support for ads

**Comment by ahmedkaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2724
