### ISSUE TITLE
Bug - Notice: Undefined index: extension in thirdparty-compatibility.php on line 401 - 406

### ISSUE THREAD

**Issue by msziyou** [ahmedkaludi/accelerated-mobile-pages#2496]
I'm getting these error message all over the AMP pages of my site, displaying on the webpage.

All coming from wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php

There are many lines of this above the menu bar, header, above and below the footer.

Please help!

Using AMP 0.9.97.13  and WordPress 4.9.8 running Nordic theme.

**Comment by MohammedKaludi** [comment]
:+1: can be merged

**Comment by msziyou** [comment]
Thanks  - dropping you an email.

I managed to get rid of the lines by going through every option in AMP and getting them to disappear!

**Comment by Zabi09** [comment]
@msziyou You no need to worry now we have fixed the issue and added the code on our end and it will be updated in our next update for sure.

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
