### ISSUE TITLE
Getting validation Error when using the Ivory Search Plugin

### ISSUE THREAD

**Issue by ghost** [ahmedkaludi/accelerated-mobile-pages#2497]
Getting the validation error in AMP when the Ivory Search plugin is used.
This validation error: "The mandatory attribute 'target' is missing in tag 'FORM [method=GET]"

REF: https://secure.helpscout.net/conversation/631450240/31196?folderId=673452

**Comment by MohammedKaludi** [comment]
http://take.ms/orgz7 Search not working.

**Comment by vinoddalvi** [comment]
@MohammedKaludi You can get support for Ivory Search plugin from https://ivorysearch.com/support/

**Comment by MARQAS** [comment]
Validation error: Invalid URL protocol 'http:' for attribute 'action' in tag 'FORM [method=GET]'.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.49
