### ISSUE TITLE
Got an issue that, <p></p> tag auto added in amp-accordion tag

### ISSUE THREAD

**Issue by carlharriss** [ahmedkaludi/accelerated-mobile-pages#2498]
After updating AMP plugin to version 0.9.97.13, i got an issue that it adds <p></p> p tag as child tag of <amp-accordion>amp-accordion tag which shows an error in google webmaster that "Tag 'p' is disallowed as child of tag 'amp-accordion'. Child tag must be one of section.... " . This problem does not occur when i revert the plugin to previous version.
I tried a lot of thing to get rid of that empty p tag, it does disappear in non AMP version of post but shows in AMP. Kindly help fixing it. Find it here.
https://www.screencast.com/t/p7GWkU3J63

**Comment by Zabi09** [comment]
@carlharriss I am really sorry for the inconvenience which you have faced and I have also tested to recreate the same issue on my end - http://take.ms/PfZ72 but I am unable to recreate the same on my end.

Will you please send your temporary admin access on team@magazine3.com, I will personally check on your end and I will make sure everything will work perfectly in the latest version as well.

Please let us know.

**Comment by MohammedKaludi** [comment]
also post id check should be added otherwise,
if one condition is matched then, it will remove `<p>` from all the posts.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/18d47eb3f5ff90806231da2b784d82909e338fd4#diff-67677c038d3b8306e6c37f4507daaa17R213

**Comment by MARQAS** [comment]
It is checking for the particular post only.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
