### ISSUE TITLE
Sidebar Improvement and Option for Pages

### ISSUE THREAD

**Issue by Omair52** [ahmedkaludi/accelerated-mobile-pages#2499]
- [when the single without the sidebar layout is selected, then it should still show an option called "Single Sidebar" - upon enabling, it should enable the "Single with Sidebar" layout. Turning it off should get them back to the normal single layout. ]

- [ also an option for Pages] 

Reference: https://secure.helpscout.net/conversation/656455552/33405?folderId=2090528

**Comment by MohammedKaludi** [comment]
issue explained to zabi.

Sidebar child on-off are not connected with parent control and it is breaking Homepage and Single sidebar.

**Comment by pegazee** [comment]
Review 

- [ ] Sidebar Styling not loading on pages.

- [ ] Shuffle the "sidebar for page" option in Global settings ( discussed this scenario with @MohammedKaludi  ).

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
