### ISSUE TITLE
AMP validation error because of share button

### ISSUE THREAD

**Issue by Asif2BD** [ahmedkaludi/Accelerated-Mobile-Pages#25]
I can't seems to get past the AMP validation error in any of the site I tested this plugin. And error are mostly occurring for share button. I do see those type error

> `The attribute 'style' may not appear in tag 'div'.`
> 
> The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'. (see https://www.ampproject.org/docs/reference/spec.html#stylesheets)
> 
> The tag 'script' is disallowed except in specific forms.
> 
> The parent tag of tag 'head > style[amp-boilerplate] - old variant' is 'div', but it can only be 'head'. (see https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md)

The error `The tag 'script' is disallowed except in specific forms.` appears many times.

Could we solve it in this coming release? Otherwise just add an option to disable sharing option. Maybe its time to add a simple option menu.

The plugin will be mostly unusable if we can't get past the validation error, and will result in a lot of negative review in .org.

**Comment by MohammedKaludi** [comment]
@Asif2BD Can you please tell me which sharing plugin you are using?

If you are using Jetpack sharing, I'm working on the fix and it will be fixed in next update.

**Comment by Asif2BD** [comment]
@MohammedKaludi  No, here I was talking about the sticky share button you added on single page. I think there is a separate ticket for Jetpack sharing plugin issue.

**Comment by MohammedKaludi** [comment]
@Asif2BD Thanks for the quick response. We have fixed this in the previous update and currently there are no errors while sticky sharing is active.

So, I'm closing this ticket.

Thank you for your valuable feedback, as it will improve the plugin to serve you better.
