### ISSUE TITLE
Improvement in displaying the list of posts, pages, and categories.

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2502]
Where ever we are displaying the list of posts, pages, and categories in AMP Option Panel need to use the below method.
For eg: Hide AMP Bulk tool list

The method needs to follow:  http://select2.github.io/select2/#data

Ref:  https://secure.helpscout.net/conversation/654742757/33155?folderId=1060554

**Comment by Omair52** [comment]
Once the issue is resolved, please inform the customers too

**Comment by MARQAS** [comment]
Styling @RajuJeelaga ?

**Comment by MARQAS** [comment]
Added in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2762.
Can be closed.

**Comment by ajeetku** [comment]
Assure in master have proper escaping  `$_GET['q']` and nonce

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
nonce is added in master

> Assure in master have proper escaping `$_GET['q']` and nonce

nonce is added in master
