### ISSUE TITLE
“Featured Image from The Content” option should not override the default Set featured image.

### ISSUE THREAD

**Issue by ghost** [ahmedkaludi/accelerated-mobile-pages#2503]
Description: When the user has set the featured image for the post and also has enabled the option of "featured image from the Content" then the default featured image which is set should be displayed.

REF: https://wordpress.org/support/topic/featured-image-from-the-content-overrides-user-set-featured-image/

**Comment by MohammedKaludi** [comment]
Empty/No Featured image in Swift theme

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
