### ISSUE TITLE
Issues with Content Sneak Peak Feature.

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2504]
Need to Style the "Show Full Article" Button.

![](https://user-images.githubusercontent.com/15303814/42568125-aa7cc98a-8529-11e8-8502-d5523388b2a7.gif)

@RajuJeelaga you can discuss this with Me and @ahmedkaludi if you have any confusion

**Comment by MohammedKaludi** [comment]
@MARQAS 

Two issues found regarding functionality.

1. Button Should apply only to Posts. 

2. It should not apply on custom front page

3. Posts that have less content it's not looking good. http://take.ms/wg81W

4. As mentioned above it should only add on Posts, WooCommerce is not looing good http://take.ms/xzu5q

**Comment by SageFargo** [comment]
is it fixed?

**Comment by MohammedKaludi** [comment]
Yes it is fixed but it is under review. Once it is checked properly, then will release it for public.

This process usually takes around 2weeks.

**Comment by MohammedKaludi** [comment]
proper translation required

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e8d1caa68a8d42100e9b985060ce74dbc5d62a37#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6064

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
escaping missng 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a0c15301bb1cf52dbf532df9b0234345eeb10a0c#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6081

**Comment by MohammedKaludi** [comment]
ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
