### ISSUE TITLE
Custom post type is showing a blank page in the swift theme

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2512]
Custom post type is showing a blank page in the swift theme but it displays all posts in other designs

Issue recreated on localhost

Ref:  https://secure.helpscout.net/conversation/656585818/33407?folderId=1914712

**Comment by merajali294** [comment]
Fatal error: Uncaught Error: Call to undefined function ampforwp_get_all_post_types() in C:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages-0.9.98\accelerated-moblie-pages.php:217

**Comment by mlt0882** [comment]
So if we wanted our custom posts to be blank (I have a custom plug-in that basically strips away the theme to a blank page to do landing pages), would I just undo the code added into #2512? 

Not super well-versed in PHP but that looks like it is merging the Swift theme post style that we select with our custom post style, so it seems like that would make sense. Please advise.

**Comment by MARQAS** [comment]
@mlt0882, I am unable to understand what you want to achieve, can you please elaborate your issue more?
Do you want to keep the Custom Post Types blank?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
