### ISSUE TITLE
More debug errors

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2513]
( ! ) Warning: Cannot modify header information - headers already sent by (output started at C:\wamp\www\1\wp-content\plugins\accelerated-mobile-pages\includes\options\admin-config.php:4189) in C:\wamp\www\1\wp-admin\includes\misc.php on line 1126

( ! ) Notice: Undefined variable: tags_array in C:\wamp\www\1\wp-content\plugins\accelerated-mobile-pages\includes\options\admin-config.php on line 4189

**Comment by MohammedKaludi** [comment]
:+1: can be merged

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
