### ISSUE TITLE
Date Archive not working with Swift Design 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2514]
Date archive posts are not loading in Swift theme

http://take.ms/2Bhvi

**Comment by Zabi09** [comment]
Not working in master but working in beta version

**Comment by MohammedKaludi** [comment]
:+1: can ber merged in to master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
