### ISSUE TITLE
PageBuilder Dynamic Classes

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2515]
### Bugs

- [x] Dynamic class names are not showing in the modules. see the link below
 because of this the Design makes the problem..
1.https://monosnap.com/file/BtR13m6PzDS5hprJqmm2WfYsIjbjKY
2.https://monosnap.com/file/jnefABIpamU193Wk4mgLw3Qmnk7sQr
3.https://monosnap.com/file/ag70y23BnRwCivZP20vcJMMV7LeT9K

**Comment by MohammedKaludi** [comment]
the class name is correct, but need to rewrite the function name `rowData`

**Comment by MohammedKaludi** [comment]
the class name is correct, but need to rewrite the function name `rowData`

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/527a36c46501636e7a95952a23a0be202bf4782f#diff-45752acf5e8ea05d2224fa9a73c54c7aR542

this also needs escaping

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
