### ISSUE TITLE
WP bakery Content is not rendering in AMP version

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2516]
Even we tried the beta version 0.9.98 but still, the issue exists. 

(Фирсов Николай) Ref:  https://secure.helpscout.net/conversation/623856477/30568/
https://secure.helpscout.net/conversation/659298487/33795?folderId=1060551

**Comment by Zabi09** [comment]
The issue was occurring due to Yandex scripts in WP bakery and all the posts are working perfectly except one.
