### ISSUE TITLE
The Consent.php path is getting index in Webmaster tool

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2518]
The consent.php path is getting index in Webmaster tool need to add the noindex tag.

Ref:  https://secure.helpscout.net/conversation/642619504/32138?folderId=1914712

**Comment by Zabi09** [comment]
Need to remove this file - accelerated-mobile-pages/includes/amp-consent/consent.php

**Comment by Omair52** [comment]
Pushed in 0.9.97.15
