### ISSUE TITLE
hello, sometime i see amp and sometime not what should i do?

### ISSUE THREAD

**Issue by gwebsite** [ahmedkaludi/accelerated-mobile-pages#252]
hello, sometime i see amp and sometime not what should i do? 

my web: [http://gwebsite.co.il/](http://gwebsite.co.il/)

**Comment by gwebsite** [comment]
ps.. why in search consul i see error? 

thanks

**Comment by khaledMohammed000** [comment]
Hello @gwebsite I went through your website , I can see you dont have AMP plugin Enabled

**Comment by khaledMohammed000** [comment]
Please Activate so i can have a look at the issue 👍
