### ISSUE TITLE
Footer menu design 2 - spurious spaces

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2521]
Version 0.9.97.14 - Design 2 - Blank lines are added when serializing HTML between elements that should not have whitespace - issues are still present in the footer and side menus with spurious spaces being injected into the html. Same problem as was present in the content #2445

**Comment by MohammedKaludi** [comment]
Added in master and will be pushed in 0.9.97.16

**Comment by Omair52** [comment]
Pushed in 0.9.97.16

**Comment by MARQAS** [comment]
This ticket will be resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2561
