### ISSUE TITLE
Pagination div on article posts - spurious spaces

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2522]
Version 0.9.97.14 - Design 2 - Blank lines are added when serializing HTML between elements that should not have whitespace - issues are present in `<div id="pagination"> `.  Same problem as was present in the content #2445

**Comment by MohammedKaludi** [comment]
@Frenchomatic can you please point me to the more specific area?

**Comment by Frenchomatic** [comment]
It is the enclosing div on previous and next links on blogs , archives, categories etc.  I think it is in index.php, archive.php, post-naviation.php, search.php and content.php. Look at a blog page for example and then look at the source created for the next and previous links.

**Comment by MohammedKaludi** [comment]
@Frenchomatic thank you for the heads up.

**Comment by MohammedKaludi** [comment]
[accelerated-mobile-pages.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/2393809/accelerated-mobile-pages.zip)

Fixed all the pagination issues in this zip, can you please test this? And let me know if it is alright so I can push the update tomorrow morning.

Thank you for the feedback @Frenchomatic

**Comment by Frenchomatic** [comment]
Looks ok to me. It is not a major issue so I would wait to push until you are ready for the major release of 0.9.98

**Comment by Omair52** [comment]
Pushed in 0.9.97.16

**Comment by Frenchomatic** [comment]
I just uploaded version 0.9.97.16 and it has not removed this problem from pagination where additional lines get put into the html within the div holding next and previous links.

**Comment by MohammedKaludi** [comment]
>  within the div holding next and previous links

in Single?? and in which design?

**Comment by Frenchomatic** [comment]
No on blog posts page on design 2 at least for me I see this for example 

`<div id="pagination"> <div class="next"><a href="https://www.mydomain.com/blog/page/3/">Next »</a></div> <div class="prev"><a href="https://www.mydomain.com">« Previous</a></div> <div class="clearfix"></div> </div>`

**Comment by MARQAS** [comment]
It will be resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2561
