### ISSUE TITLE
div id=footer - spurious empty <p></p>

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2524]
Version 0.9.97.14 - Design 2 - If you don't use the option 'back to top of the page' or 'non-amp version', a spurious `<p></p>` is still injected into the html. I see this on my AMP only version web sites where I do not use those options.

**Comment by MARQAS** [comment]
Closing this ticket, more info can be found here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2561
