### ISSUE TITLE
When image attribute is set to Float:left or right then in amp version it should be changed to float: none or float: center in responsive (mobile vesion)

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2525]
Ref: https://secure.helpscout.net/conversation/654997170/33202?folderId=2206768

Desc: The image having the float: left and float: right attribute but in the AMP version it should be float: none or float: center and image will come in the center (in mobile responsive).

Here are the screenshots;
>  https://monosnap.com/file/r6SAANRRJJ4XyeogKPqyEq7NpPnw0F
>  https://monosnap.com/file/jgCPIUqq8kcGyE5MwEpMqtesFMy15Y

**Comment by MohammedKaludi** [comment]
use `is_singular` instead

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5d67b06a3643c16446a73786293554cd762fabee#diff-b6b75f4287e169753316befbe71522b8R381

**Comment by MohammedKaludi** [comment]
:+1: this can be merged into master

**Comment by arin0404** [comment]
Hi guys. I am still seeing images that I have assigned in desktop as float left or float right not be centered in mobile. Is this request still being worked on? here is an example page http://s695776046.onlinehome.us/how-to-beat-alcohol-addiction/amp/

**Comment by MARQAS** [comment]
Why not AMP frontpage?

**Comment by MohammedKaludi** [comment]
Add this condtion while merging into master

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
