### ISSUE TITLE
License key is visible in Source code

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2528]
the license key can be seen from the source code, we need to make sure that it is not visible from that area too.

Ref: https://secure.helpscout.net/conversation/663347805/34207?folderId=2322652

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
It is still visible from the sourcecode.
Do contact me personally be starting the work.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59

**Comment by MohammedKaludi** [comment]
License key becomes very long after encryption it needs to be short #3361

HelpScout Link: https://secure.helpscout.net/conversation/885649004/71460?folderId=2770545

redux_file.txt

Need To Fix it Urgently

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
