### ISSUE TITLE
" Top " Button functionality to be improved.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2529]
Reference: https://secure.helpscout.net/conversation/662249094/34121?folderId=2090438

A user request is to make the Top Button appear when we do a little scroll, down towards the right side of the screen.

**Comment by ahmedkaludi** [comment]
https://ampbyexample.com/visual_effects/scroll_to_top/

**Comment by RajuJeelaga** [comment]
In Design 3 Scrolling animation is not applying, Showing error in console
https://monosnap.com/file/c5kJnjbDLnhW333wsQrdXnYiJvjjHk

**Comment by beingsmart3** [comment]
when Back to Top link option is disabled it still loading The extension 'amp-animation' was found on this page, but is unused. the error also the same issue occurring in Newspaper theme.

Ref:  https://secure.helpscout.net/conversation/701865618/39607?folderId=1914712

**Comment by MARQAS** [comment]
@beingsmart3 please add the latest beta and check, it has been resolved

**Comment by Zabi09** [comment]
> when Back to Top link option is disabled it still loading The extension 'amp-animation' was found on this page but is unused. the same issue occurring in Newspaper theme.
> the issue was occurring in Beta and gets fixed
> 
> Ref: https://secure.helpscout.net/conversation/701865618/39607?folderId=1914712

This error is still appearing in latest version

**Comment by MohammedKaludi** [comment]
Styling is not good. @RajuJeelaga need improvements.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
