### ISSUE TITLE
Whenever Responsive AD is enabled then the AD should load on the screen without any effect to the normal mode AD in D1,2,3, and Swift

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2531]
Reference:

https://secure.helpscout.net/conversation/657500450/33506?folderId=2090438

**Comment by MohammedKaludi** [comment]
Conditions not added properly, if responsive is enabled on 1st advert then styling is added to all of the ads, this is not correct.

All the controls should be properly connected.

**Comment by MohammedKaludi** [comment]
:+1: moving the ticket to testing department.

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] talha

- [ ] Imran

**Comment by syedimran22** [comment]
Sitewide ads are not loading in homepage in beta whereas in master it is rendering perfectly.

@beingsmart3 : when enabling below the footer ads option the ads are loading in both above & below the footer.

**Comment by pegazee** [comment]
Regarding the Sitewide ads on Homepage, It's working on my end and I've checked on all designs ( D- 1,2,3 and swift ). @syedimran22 please check once on your end or else consult me.

And regarding the "Below the Footer" ads, Yes it's loading above the footer and below the footer which is not correct. @ajeetku please check it once.

**Comment by ajeetku** [comment]
@pegazee I this issue is not related to this ticket, please create a new ticket for it

**Comment by pegazee** [comment]
Sure

**Comment by pegazee** [comment]
I've created the ticket #2778

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
