### ISSUE TITLE
Quesiton about AMP on WooCommerce

### ISSUE THREAD

**Issue by shtefcs** [ahmedkaludi/accelerated-mobile-pages#2533]
I am thinking of buying AMP for WooCommerce for [UX Store](https://uxstore.com), but I am concerning will I have valid AMP page with all current scripts I am using for conversions tracking, retargeting and advertising. 

Like Facebook pixels, Googles scripts, MouseFlow and other.

**Comment by Zabi09** [comment]
@shtefcs Firstly the scripts are not allowed in AMP version and if you purchase our AMP Woocommerce extension then your shop page and all the single product pages will automatically convert to AMP version and it will appear like this - 
Shop - http://ampforwp.magazine3.com/shop/
Single Product - http://ampforwp.magazine3.com/product/polo/

And after this, you can style it as you want from the Global settings of the AMP panel if you need additional CSS but all this functionally will be generated by the AMP Woocommerce Extension.

Hope it help and if you need more info or if you have any issues then you can directly reach us at team@magazine3.com and our team will help you.

**Comment by shtefcs** [comment]
Thanks for the response @Zabi09 .

Is there any other way that we can use Facebook Pixel, and other tracking tools within AMP? Cause without that AMP for ecommerce is almost unuseful.

**Comment by Zabi09** [comment]
@shtefcs If you need to ask questions then you can contact us on team@magazine3.com and also you can do a live chat at https://ampforwp.com/ and our support team will definitely help in answering all your questions.

**Comment by shtefcs** [comment]
hey @Zabi09 are you sure the linsk to AMP woocommerce is up to date ? The cart page doesnt work, and when i check into AMP test tool, its says it cant be reached https://i.imgur.com/HIrCdcq.png.
