### ISSUE TITLE
Need to remove the Gap between Header and AMP Pagebuilder module

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2534]
Need to remove the Gap between Header and AMP page builder module but how?

Ref:  https://secure.helpscout.net/conversation/629028982/31000?folderId=1914712

**Comment by MohammedKaludi** [comment]
Few things that need to be fixed.

1. Need to check only if the data is present or is new data then only, update in the database, in the current state it will save every time regardless if the data is changed or not. This will decrease unnecessary calls into the database. 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b6d5de83cb1b8b9f53455b4f4881788a6b5c28c6#diff-87c43b470f3b99b8c555b44a41693219R34

2. Escaping required
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b6d5de83cb1b8b9f53455b4f4881788a6b5c28c6#diff-45752acf5e8ea05d2224fa9a73c54c7aR527

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b6d5de83cb1b8b9f53455b4f4881788a6b5c28c6#diff-4843e96614746699a4b981cbdf995aedR120

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b6d5de83cb1b8b9f53455b4f4881788a6b5c28c6#diff-005cc14f54c130b73e541644f5ba12baR147

**Comment by RajuJeelaga** [comment]
When ever, this ticket is going to release, we need to push the update of AMP Layouts as well 
https://github.com/ahmedkaludi/amp-layouts/issues/30

**Comment by MARQAS** [comment]
Escaping is required

**Comment by ahmedkaludi** [comment]
**!! When ever, this ticket is going to release, we need to push the update of AMP Layouts as well
ahmedkaludi/amp-layouts#30

 !! **

**Comment by ahmedkaludi** [comment]
> ** ! When ever, this ticket is going to release, we need to push the update of AMP Layouts as well
> [ahmedkaludi/amp-layouts#30](https://github.com/ahmedkaludi/amp-layouts/issues/30) **

**Comment by MohammedKaludi** [comment]
This has been fixed with the Update of AMP-Layouts Extension, We have updated the Design Json.

But the issue(margin-top:-20px) might come for the users who have imported the design from v1.4 

Need to Create a tutorial for the older version users on how to update that code from the options panel and which control to modify.

**Comment by MohammedKaludi** [comment]
After the article is done: we can directly close this ticket.

**Comment by RajuJeelaga** [comment]
Please see the Article: https://ampforwp.com/tutorials/article/how-to-remove-the-gap-between-header-and-amp-pagebuilder-module/
