### ISSUE TITLE
Bridge Qode SEO Compatibility

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2538]
Ref:  https://secure.helpscout.net/conversation/657594784/33517?folderId=1914712

**Comment by MARQAS** [comment]
How about other things? Like og tags, canonical and meta?

**Comment by Zabi09** [comment]
I have checked the theme options but unable to find the open graph etc.. Will you please check that once and let me know if there is an option for that

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
