### ISSUE TITLE
Short code issue [not working in AMP] with visual composer  [ WP bakery page builder]

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2539]
in AMP shortcode on page/post not working which is created by using Visual composer[wp- bakery page builder] and showing as text.

screenshot: http://take.ms/zJoXD

Ref: https://secure.helpscout.net/conversation/659321816/33800?folderId=673457

**Comment by Zabi09** [comment]
Issue fixed on users end.

**Comment by MohammedKaludi** [comment]
:+1: closed as this issue is not with the core plugin.
