### ISSUE TITLE
Can you please add siteorigin builder support to pages?

### ISSUE THREAD

**Issue by anbadmin** [ahmedkaludi/accelerated-mobile-pages#254]
Hi,
Thanks for the wonderful plugin. It's working well! Kudos to your team.. I use siteorigin template and page builder plugin. The home page I have created does not show up at all :( I had to create a  page to make it amp compatible... Any way II can fix this? I'm a newbie newbie and still learning b basics.. Thanks.

**Comment by ahmedkaludi** [comment]
@anbadmin It is certainly not easy... How does the output looks like with the current version?

**Comment by ahmedkaludi** [comment]
It depends on the authors of the plugin or theme to make their product compatible with AMP. We are closing this to stay focused.
