### ISSUE TITLE
Images are blur in 0.9.98 in design 2, may happen with other designs as well

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2541]
Branch 0.9.98: http://take.ms/pHeLu
Master : http://take.ms/ixlHb

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
move the code inside the 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d6ba5598c3c725a0e08ce87fbb9160ef71c4b7a0#diff-124aaba5bb04f0c209fee076b85b13b2R26

`if ( $thumbnail_srcset  )`

also escaping is missing 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d6ba5598c3c725a0e08ce87fbb9160ef71c4b7a0#diff-d9e62bf7636c72ea611757e43f70c46eR418

**Comment by Zabi09** [comment]
Before merging in master add this commit of srcet - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/df0d1fcd521616dc3ce9b59516dedc7b9db70258

**Comment by MohammedKaludi** [comment]
Ready to merge, consult me before merging

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
