### ISSUE TITLE
genertor

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2543]

**Comment by MohammedKaludi** [comment]
Generator not working with Convert AMP to WP theme (Beta)

**Comment by Zabi09** [comment]
The source code will not change if convert AMP to WP theme option is enabled. Do we need to put the generator?

**Comment by MohammedKaludi** [comment]
yes, we need the generator.

**Comment by MohammedKaludi** [comment]
Also, need to show the current version number in the generator, without version number generator is useless.

**Comment by MARQAS** [comment]
Escaping?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
