### ISSUE TITLE
Logo resize should only apply when Resize setting is enable

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2544]
Resize is OFF http://take.ms/seX0Z

But the styling is applying : http://take.ms/wxVtU

**Comment by Zabi09** [comment]
I have tested the same on my end with both in master and beta and unable to recreate the issue and here is the result.
Added the logo - http://take.ms/qdW1H
Same width and height - http://take.ms/rIRTA
After enabling the resize option - http://take.ms/4Cyhi

**Comment by pegazee** [comment]
Tested on my end, working perfectly.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: can be merge into master

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.36
