### ISSUE TITLE
 Make an option to our Membership Bundle user to activate all extensions at only one place.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2545]
Desc: Make an option to our Membership Bundle user to activate all extensions by entering key at only one place.
Ref : https://secure.helpscout.net/conversation/663136896/34188?folderId=2322652

**Comment by JayHoltslander** [comment]
This seems like a no-brainer to have. Entering 15 different license numbers is kind of ridiculous.
One license key is the method that [Delicious Brains](
https://deliciousbrains.com/) uses for their plugin "[WP Migrate DB Pro](
https://deliciousbrains.com/wp-migrate-db-pro/)" and all of it's related add-ons.

**Comment by ahmedkaludi** [comment]
it's now available to use from the user accounts area
