### ISSUE TITLE
Add support for AMP Linker 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2546]
Add support for AMP Linker 

For more references please check: 

https://amphtml.wordpress.com/2018/09/17/measuring-user-journeys-across-the-amp-cache-and-your-website/amp/

**Comment by MohammedKaludi** [comment]
the output is incorrect.

it should like this 
`     “linkers”: {
       ”enabled”: true
     }
`
Docs:https://amphtml.wordpress.com/2018/09/17/measuring-user-journeys-across-the-amp-cache-and-your-website/amp/

But in the source code, it is like this  http://take.ms/9uTg6X
`linkers":"true"`

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.49
