### ISSUE TITLE
Implementation/add of Feature like jQuery Pin It Button for Images plugin

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2547]
jQuery Pin It Button for Images plugin provides a pint it button for images ON HOVER when the button is clicked it redirects users to Pinterest.

see this: http://take.ms/VlcPc

Ref: https://secure.helpscout.net/conversation/663509058/34221?folderId=1914713

**Comment by MARQAS** [comment]
Styling is required.

**Comment by RajuJeelaga** [comment]
To get the above Design, Little bit of Markup need to change, Please check this screenshot
https://monosnap.com/file/bKALxkSqaX36qztKPI3CrnZE6jCRfh

**Comment by ahmedkaludi** [comment]
This will come out as an extension on ampforwp.com/extension
