### ISSUE TITLE
When navigation menu option is disabled then amp menu checkbox should be removed from menu appearance.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2548]
Desc:  When the user is disabling the navigation menu option then the amp menu checkbox should be removed from menu appearance.

Screenshot: https://monosnap.com/file/jMZGMWVlzRpM0r3BsgoFvWzbS2BEx3
https://monosnap.com/file/1BdZuxW2t9rfNcNQzjmA8M1HpfzZ2p

**Comment by MohammedKaludi** [comment]
Need to do some changes in the Menu structure. Do let me know when you are working on this ticket.

**Comment by MARQAS** [comment]
Escaping is required

**Comment by pegazee** [comment]
Not working for the "Footer menu".

Screenshot:
* https://take.ms/wh350
* https://take.ms/jXbzY

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
When Using Design 1, 2 or 3 AMP Alternative Menu - Below the Header option from the menu section should disappear.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
