### ISSUE TITLE
improve how we handle Hide Bulk Tools

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2549]
use  `has_category` and `has_tag` function in hide AMP bulk tools and improve the code

**Comment by MARQAS** [comment]
It has been improved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2903

**Comment by Rkroy** [comment]
Can we improve the performance of Hide AMP Bulk tools?
Here is the feedback from our user: 
Select2 is best tolls only for few data...
But when data is in thousand then performance will decrease and select not work properly.
So if you can provide me those data using Ajax search then it will work better.
Ref: https://secure.helpscout.net/conversation/771106739/54332?folderId=2322652

**Comment by ajeetku** [comment]
I think there is no issue because when a user searches some string for cat/tag, based on those text search results showing.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MARQAS** [comment]
We will keep #2903 and this one different, #2903 is not ready yet and not a fully developed solution. 
So we will resolve the things and improve the current one first.

**Comment by Zabi09** [comment]
Not working.
Added category - https://prnt.sc/nkxpdw 
But still, AMP is showing - https://prnt.sc/nkxpmm

**Comment by MARQAS** [comment]
@Zabi09, the changes made in beta are not working properly, can you test this with the performance branch?

**Comment by Zabi09** [comment]
Working fine in performance branch

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.54
