### ISSUE TITLE
Need to add the amphtml tag while AMP Takeover option is enabled

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2550]
Ref: https://secure.helpscout.net/conversation/646913616/32485?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Use existing hooks instead of creating new every time. This will improve performance.

We can use this: https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php#L2927

This is just an example, feel free to use any other hook as well.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
pushed in 0.9.97.44
