### ISSUE TITLE
Create category option in Swift theme

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2551]
Desc : Need to create category option in Swift theme in order to hide or show categories in each page/posts.
Refer : https://secure.helpscout.net/conversation/665166221/34416?folderId=2322652

**Comment by MohammedKaludi** [comment]
dont use css to hide, instead use php instead to remove it.

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
Ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
