### ISSUE TITLE
Add the compatibility when short codes are added in AMP widgets

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2552]
Desc: Add the compatibility when shortcodes are added in AMP widgets (using Custom Html)

Ref: https://secure.helpscout.net/conversation/664519239/34341?folderId=2169248

**Comment by MohammedKaludi** [comment]
Need code improvements and use `ampforwp_modify_sidebars_content` filter to add `do_shortcode` function and there is some code improvements.

need to pass one more parameter in `ampforwp_modify_sidebars_content` filter

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
