### ISSUE TITLE
Widgets going out of alignments in Design 1,2 and 3

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2553]
Widgets going out of alignments in Design 1,2 and 3

http://take.ms/P00m0

**Comment by MohammedKaludi** [comment]
Don't create a new div, instead add class to the parent element 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/11b04ed1bcecfebae43798272a48b25c3c6bd5fd#diff-6aa5512f7dd8d5ce60fc97b0f340912cR2289

and add clear:both div before closing the `div`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/11b04ed1bcecfebae43798272a48b25c3c6bd5fd#diff-6aa5512f7dd8d5ce60fc97b0f340912cR2291

**Comment by MohammedKaludi** [comment]
use `.cb div` instead of the static div
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c43721ae76f09299aba4d30fbf18b15b33933675#diff-6aa5512f7dd8d5ce60fc97b0f340912cR2290

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
