### ISSUE TITLE
Multibyte string links aren't working in AMP Version.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2556]
Reference: https://secure.helpscout.net/conversation/662249094/34121?folderId=2090438

URL's are working in the Non-AMP Version but not in the AMP Version.

for ex: 
https://xn--decorandouas-jhb.net/unas-acrilicas-guia/

https://xn--decorandouas-jhb.net/unas-acrilicas-guia/amp/

**Comment by MARQAS** [comment]
Had to remove the filter_var part.
Reason: filter_var is not multibyte capable.
https://d-mueller.de/blog/why-url-validation-with-filter_var-might-not-be-a-good-idea/
http://php.net/manual/en/filter.filters.validate.php

**Comment by MohammedKaludi** [comment]
removing the filter is not an option, we need to improve and some other URL validation method.

**Comment by MARQAS** [comment]
Whitelist sanitizer is also running, we are good to go with the removal of this code.

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master.

**Comment by merajali294** [comment]
Uploaded Beta on User's end but he said that links in the table of contents, which lead to each internal H2 of the post, do not work.

**Comment by MohammedKaludi** [comment]
can't we add a check if the text is MBString then ignore or else keep the `filter_var` as it is?

**Comment by pegazee** [comment]
I've given the condition MBString on filter_var part [here](https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2967). @MohammedKaludi and @MARQAS , Please check the condition

**Comment by MARQAS** [comment]
Added the condition of multibyte string here:https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/15f08f5e8b892ef3e113876f469c77caa9e66756#diff-9253027ab0fd0dc36f48733d5f042541R185

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
