### ISSUE TITLE
No message if the search didn't find anything. in Swift

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2557]
Working on other designs: http://take.ms/UrCnV
Not working on Swift theme: http://take.ms/VugJG
No message if the search didn't find anything.

**Comment by MohammedKaludi** [comment]
Container missing

Need to create a container and show the message in the Paragraph tag like this: http://take.ms/qu1BL

**Comment by MohammedKaludi** [comment]
text is not translatable 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5305e00de78fb60a4ee79336b3aa1732779f338a#diff-7964598fe38e4ae3a7307748186b215dR13

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Escaping is missing for message and font family

**Comment by MARQAS** [comment]
Need improvement

**Comment by MARQAS** [comment]
Use `ampforwp_get_setting` instead of global

**Comment by MARQAS** [comment]
Font family is not escaped, any suggestion about how we can do that @MohammedKaludi?

**Comment by MohammedKaludi** [comment]
Do the escaping when setting the settings,

**Comment by MohammedKaludi** [comment]
:+1:  ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
