### ISSUE TITLE
Amp Compatibility of Featured video with SmartMag theme

### ISSUE THREAD

**Issue by ghost** [ahmedkaludi/accelerated-mobile-pages#2559]
Add the Amp Compatibility of Featured video with the SmartMag theme.

REF: https://wordpress.org/support/topic/featured-video-available-but-does-not-appear/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
escaping missing https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/91ebf5e73fe3397379d791ba6e4ed774902a3a2e#diff-124aaba5bb04f0c209fee076b85b13b2R63

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
