### ISSUE TITLE
Additional Spaces in main sidebar menu 

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2561]
Version 0.9.97.16  - Would like to to reopen #2521 and #2522. You will also see it is doing this with the main sidebar menu too where spaces are being put between the `</li>SPACE<li>` menu items. It says pushed but I don't think it has been.

**Comment by MohammedKaludi** [comment]
reopened and regarding the menu is concerned we will talk about menu in this ticket.

**Comment by Frenchomatic** [comment]
ok. Serialization is a real nuisance. The main thing is we no longer see it in the main content.

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/667794759/34799?folderId=1914712.

**Comment by MARQAS** [comment]
Related tickets.
Footer: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2524
Footer Menu: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2521
Pagination: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2522

**Comment by MohammedKaludi** [comment]
This issue is irrelevant, search engines are smart enough to understand.
