### ISSUE TITLE
"Change Internal Links to AMP" not working properly for anchor tags (internal links)

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2562]
Desc : Whenever we enable "Change Internal Links to AMP", the page internal links (anchor tags) are being malfunctioned and re-directed to other AMP page, 
When the option is disabled, then the internal links (anchor tags) are working fine.
Ref : https://thebettervacation.com/metropolitan-museum-of-art-new-york/amp/

**Comment by beingsmart3** [comment]
Another problem:  https://secure.helpscout.net/conversation/677203231/36238?folderId=1914712

**Comment by MohammedKaludi** [comment]
Keep `$name_attr = $node->getAttribute( 'name' );` and create a new variable `$id_attr = $node->getAttribute( 'id' );`


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/83d19d14a5004f6a83296efeb6e286939ebc5de1#diff-9253027ab0fd0dc36f48733d5f042541L143

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
