### ISSUE TITLE
404 error pages from the AMP are not showing

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#2565]
It seems that 404 error pages no longer work either in a hybrid system or a web site in AMP takeover. They have been working perfectly well but now they don't.  Version 0.9.97.16 . 

This requires immediate attention or it will create significant problems for users in terms of google console and indexing. It is exactly the type of problem which should go into a standard set of tests before any release is made. 

And why are there two error 404 boxes under the translation panel - this is only going to confuse users.

**Comment by Frenchomatic** [comment]
Any fix on this - I have 6 sites in AMP takeover and all of them are displaying a 404 page which is not the AMP version.

**Comment by Frenchomatic** [comment]
Version 0.9.97.18 Still not showing the AMP version of the 404 page in AMP takeover

**Comment by Frenchomatic** [comment]
Version 0.9.97.19 Still not showing the AMP version of the 404 page in AMP takeover

**Comment by Frenchomatic** [comment]
I confirm that this commit fixes the 404 issue. Thank you.

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.97.20, closing this ticket.
