### ISSUE TITLE
custom Id and class for Rows and modules in AMP PB

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2566]
custom Id and class for Rows and modules in AMP PB

**Comment by MARQAS** [comment]
Added in Master with  #2730

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
this ticket can be closed now code already Pushed in 0.9.97.31
