### ISSUE TITLE
Header with CTA doesn't have the right options and defaults

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2567]
![accelerated mobile pages options wp foundation community wordpress](https://user-images.githubusercontent.com/16532359/45893940-85d31400-bdea-11e8-8e8f-1c57f76a0e44.png)

**Comment by Zabi09** [comment]
The option of "Button Customize" was there in master but in beta, it was "Call To Action" and with the proper name of subitems also, So I made them proper child item in AMP option panel.

**Comment by pegazee** [comment]
checked on my end.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
What about the defaults?

**Comment by MARQAS** [comment]
Escaping is required.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
