### ISSUE TITLE
In features.php file there is a space for the function which has to be removed if( ! function_exists(' ampforwp_onesignal_notifications_widget') )

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2569]
Desc: In features.php file there is a space for the function which has to be removed if( ! function_exists(' ampforwp_onesignal_notifications_widget') )

Screenshot: https://monosnap.com/file/LeZSkScqkEne4SapjGu76aBtU2zPVJ

**Comment by MohammedKaludi** [comment]
:+1: can be merged. but it is depended on AMP by Automattic Compatibility ticket  https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2287

**Comment by ahmedkaludi** [comment]
Lets fix this directly in master and close it.

**Comment by pegazee** [comment]
Pushed in 0.9.97.44.2
