### ISSUE TITLE
Undefined index: fb-instant-page-id error in features.php line no 4396

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2570]
Undefined index: fb-instant-page-id (View: /home/goool/public_html/evaluation/resources/views/layouts/app.blade.php) (View: /home/goool/public_html/evaluation/resources/views/layouts/app.blade.php)

Ref: https://secure.helpscout.net/mailbox/cfb9786cbb6b9b7c/chats/34ca8377-65dd-4dc0-b28f-6eabe73eb513

**Comment by MohammedKaludi** [comment]
just use `$fb_page_id = ampforwp_get_setting('fb-instant-page-id');`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9096586b1af2fe26e2ff4f48f10eeec1184509f4#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3375

**Comment by MohammedKaludi** [comment]
Update this condition as well.

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/6f228d7997362f187a495e58a8023e341c926714/templates/features.php#L3404

**Comment by MohammedKaludi** [comment]
:+1: can be pushed in master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
