### ISSUE TITLE
Issue with Recent Blog and Recent Blog slider module in Js composer

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2575]
If we are inserting the Recent Blog and Recent Blog slider module in wp bakery then the amp page builder and custom amp editor content is not rendering.

Ref:  https://secure.helpscout.net/conversation/662236063/34119?folderId=1914712

**Comment by Zabi09** [comment]
This issue is fixed on the user's end.
