### ISSUE TITLE
 AMP Flying Carpet ads

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#258]
I was wondering if it would be possible to add AMP Flying Carpet ads to the AMP Advanced Ad
Plugin.

**Discussion pending**

**REF** : https://secure.helpscout.net/conversation/286640485/9979/?folderId=1060556

**Comment by khaledMohammed000** [comment]
https://ampbyexample.com/components/amp-fx-flying-carpet/

**Comment by ahmedkaludi** [comment]
https://github.com/ahmedkaludi/amp-ads-google-adsense/issues/18
