### ISSUE TITLE
Need to separate categories & tags with ( / or , ) in AMP theme framework single page.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2580]
Desc : In AMP theme framework single page, categories & tags are listed inline without any space, which we need to separate the categories & tags lists with ' / ' or ' , '.
Ref : https://secure.helpscout.net/conversation/670689987/35232/
Screenshot: https://monosnap.com/file/5GPRwcLOl0gFb6W9wm1MktZzNIA3Ep

**Comment by MARQAS** [comment]
We intentionally haven't added the separator, to let users choose whatever separator they want. 
Few people don't even use the separator, they are happy with just space ( which is default ). 
We are using '/' as a separator in our Swift design. 
So I believe let's not restrain the users to use a single separator.

**Comment by ajeetku** [comment]
update on https://ampforwp.com/tutorials/article/categories-tags/

**Comment by pegazee** [comment]
I guess documentation is updated. @ajeetku can you please check

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
On my local server Categories are getting separated but the tag is still the same: http://take.ms/Zfy8i

**Comment by MohammedKaludi** [comment]
make sure code to escape the code before merging.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
