### ISSUE TITLE
Need to add Featured Video Compatibility in Featured video plus plugin

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2583]
Reference: 

https://secure.helpscout.net/conversation/671878467/35409?folderId=2090438

**Comment by Zabi09** [comment]
Continuation of #2394

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
The featured video is not displaying in any AMP design

**Comment by MARQAS** [comment]
Not working, validation errors on other designs and blank on Swift

**Comment by MARQAS** [comment]
Working

**Comment by MohammedKaludi** [comment]
@Zabi09 Where did you find the info that we needed to integrate with Featured Video Plus Plugin?

The user was asking about newspaper theme.

**Comment by MohammedKaludi** [comment]
Ready to merge. Need to test with the plugin after merging

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
