### ISSUE TITLE
itemprop="image" is being removed from the AMP Pages, need to fix this and should be displayed in AMP(Source code).

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2585]
Reference:

https://secure.helpscout.net/conversation/669721556/35043/

User is using Total Recipe Generator plugin

**Comment by MohammedKaludi** [comment]
:+1: can be merged into the master

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
