### ISSUE TITLE
Link to Non-AMP page in Footer points to 404

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2586]
Ref:  https://secure.helpscout.net/conversation/671262082/35309?folderId=1914712

The plugin doesn’t link to the appropriate AMP URL. It seems the plugin is removing any occurrences of “amp” in the URL in order to decide what the canonical page is and ends up breaking the path.

See this screenshot:  http://take.ms/MfEED

To recreate this issue on a local server you can follow the steps which are mentioned in the email.

**Comment by MohammedKaludi** [comment]
Create empty variables 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3a8939e8f010b3e77037a7807ed356e2af5d2076#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3364

Otherwise it will show the warning of undefined index

**Comment by MohammedKaludi** [comment]
:+1: can be merged.

**Comment by MohammedKaludi** [comment]
Update the `$_SERVER['REQUEST_URI']` with  `global $wp; echo home_url( $wp->request )`

OR use an appropriate WordPress function as `$_SERVER['REQUEST_URI']` is not considered as a safe way to retrieve current url

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
