### ISSUE TITLE
After the new update of the Yoast the amp metadata is showing the wrong timestamp.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2587]
Desc: When the user deploy the Youst new version updated in the amp matadata, the timespan is showing wrong and before the update, it was showing 12:47+00.00 but after an updated it is showing 12:47 +03.00 in the amp metadata. 

Ref: https://secure.helpscout.net/conversation/657665823/33536?folderId=2206768

**Comment by MARQAS** [comment]
Unable to recreate the issue, contacted the user, waiting for his message

**Comment by MARQAS** [comment]
The change is due to the Yoast update, it's even occurring on non-amp. Updated the user about this.

**Comment by mdsam10** [comment]
In the latest version of the Yoast the timestamp is showing correct in the head metadata but in the footer the timestamp is incorrect and we need some more time to debug this issue

**Comment by ahmedkaludi** [comment]
Not a valid issue.
