### ISSUE TITLE
Ads are not appearing in home page, it is displayed only in single pages.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2588]
Desc : In Ads for WP , Ads are not displayed in home page, it is only displaying in the single pages.
Ref : https://secure.helpscout.net/conversation/670484464/35203?folderId=2322652

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/ads-for-wp #81](https://github.com/ahmedkaludi/ads-for-wp/issues/81) via [**ZenHub**](https://www.zenhub.com/)
