### ISSUE TITLE
Custom Front page is breaking in 0.9.97.16

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2589]
If the custom front page is made with Divi page builder and Thrive Architect plugin is activated then the custom front page is getting a break.

Issue recreated on the local host.

Ref:  https://secure.helpscout.net/conversation/671483037/35353?folderId=1914712

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
