### ISSUE TITLE
using get_avatar()

### ISSUE THREAD

**Issue by dwien** [ahmedkaludi/Accelerated-Mobile-Pages#259]
your plugin use get_avatar_url() to get the avatars. This is not working with the all local avatar plugins I have tested. Is there a workaround for this issue? Is it possible to use get_avatar() in the amp template?

**Comment by khaledMohammed000** [comment]
Hello there I am able to get the URL on my Machine , Can you please tell me the Plugins that you have tested with ?

**Comment by khaledMohammed000** [comment]
Also let me know the version of WordPress you are using

**Comment by dwien** [comment]
I use Basic User Avatars: https://wordpress.org/plugins/basic-user-avatars/

and WordPress 4.7

**Comment by ahmedkaludi** [comment]
Reviewd working fine,

**Comment by dwien** [comment]
There is one error. When you have a (displayed) username with an blank character there is no avatar displayed. 

It is just possible when you use `&nbsp;` in the username instead of spaces...
