### ISSUE TITLE
Need to Use Ajax to fetch all Categories and tags in Featured Slider in D3

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2590]
Need to Use Ajax to fetch all Categories and tags in Featured Slider in D3

The current method is not that efficient.

http://take.ms/4fegT

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Controls are not ajax.
https://monosnap.com/file/YGz5b7nViIyXAadGnA7C50JHsochFn

**Comment by MohammedKaludi** [comment]
Category data is not available in Ajax search

**Comment by MohammedKaludi** [comment]
Working now.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
