### ISSUE TITLE
Url Issue "/page/2/amp/" gives 404 error.

### ISSUE THREAD

**Issue by abhishek-0510** [ahmedkaludi/accelerated-mobile-pages#2591]
Hi @ahmedkaludi,
Please have a look on the following url:
**https://www.forcetalks.com/amp/page/2/ .**
And as by seeing the link I believe you have already guessed the issue. I am trying to make the above url like: **https://www.forcetalks.com/page/2/amp/** , but it takes me to 404 page.
I have gone through all the comments, and issues posted here related to this. And I have come to know by your comments that you have already fixed this issue in some earlier release, my current plugin version is **Version 0.9.84.1** 

![screenshot from 2018-09-28 17-28-11](https://user-images.githubusercontent.com/43673577/46207141-eced4d00-c343-11e8-82b5-315d3a1d2e55.png)

But as you can see I am still facing this issue. Can you please help me resolve this issue.
Thank You!

**Comment by MARQAS** [comment]
@abhishek-0510 can you give us the confirmation that your issue has been resolved with the latest version of the plugin?

**Comment by MARQAS** [comment]
Oh, I think I understood your issue now, you want to change the current pagination URL to something else, right? 
For example, this: https://www.forcetalks.com/amp/page/2/ into this: https://www.forcetalks.com/page/2/amp/, right? 
Please correct me if I am unable to understand your issue.

**Comment by abhishek-0510** [comment]
Yes @MARQAS ! you are right, I am trying to do exactly that, you just mentioned.

**Comment by MARQAS** [comment]
Have you tried using this option 'Change End Point to ?amp' ?

**Comment by abhishek-0510** [comment]
Yes I tried that but it was working with a "?". url was like:  https://www.forcetalks.com/page/2/?amp . But thye desired url : https://www.forcetalks.com/page/2/amp/ still take me to 404 page.

**Comment by luan03** [comment]
Hi, I'm having the same error as @abhishek-0510 on my website. 

`<link rel="amphtml" href="http://localhost/page/20/amp/">`

Thus, I'm getting lots of 404 in my website.

**Comment by MARQAS** [comment]
@luan03 that's strange, by any chance are you using any plugin which can change the amphtml? or maybe you are changing pagination base?

**Comment by luan03** [comment]
@MARQAS I'll remove all my plugins and keep only AMPWP and test again to validate this hypothesis.

**Comment by ahmedkaludi** [comment]
@abhishek-0510 @luan03 This issue is at the troubleshooting stage and not a valid bug which can be fixed.

Kindly reach out to our Tech team via https://ampforwp.com/support/
