### ISSUE TITLE
Need to get the scrolling bar in chrome.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2593]
Desc: Need to get the vertical scrolling bar in chrome for a site as the scrolling bar is perfectly working in Microsoft edge browser.

Ref: https://secure.helpscout.net/conversation/644328658/32261?folderId=2169248

Screenshot: https://monosnap.com/file/w8TPwLhLo10masn8Pnxal5Auv54uKQ

**Comment by MohammedKaludi** [comment]
this is not working properly

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: 
remove double instance of ::-webkit-scrollbar {display: none;} in the swift/style.php in master branch.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.36
