### ISSUE TITLE
Font style getting change on Custom Front page

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2594]
Font style getting change on Custom Frontpage also when going to the same page as single page font style is different from the custom front page.

Ref:  https://secure.helpscout.net/conversation/670843157/35250?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: pushed in 0.9.97.41
