### ISSUE TITLE
Sort the modules properly

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2595]
The sorting of modules was breaking the modules array due to which some modules were missing and some were repeating twice. 
![image](https://user-images.githubusercontent.com/15303814/46293010-ee22b200-c5af-11e8-8275-1cb64b86fa33.png)

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Zabi09** [comment]
This issue is fixed in #2725 and we can close this ticket
