### ISSUE TITLE
Google auto ads

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#2596]
For some reason the ads are starting to appear everywhere they please, one time above header, next time between the featured image and post title. Is there any fix to that or we have to wait till the next update?
![45f5584e-d6fe-4118-a9e4-68f8f66b6c6a](https://user-images.githubusercontent.com/40724154/46406466-4bd00f00-c714-11e8-8753-80db16804ffe.png)

**Comment by SageFargo** [comment]
More examples:

![5663cb1b-d169-4040-8b0e-39a2807e80da](https://user-images.githubusercontent.com/40724154/46454904-38bf4c80-c7b1-11e8-97f2-9e48a887c2b2.png)

**Comment by Zabi09** [comment]
@SageFargo I have checked your website and found that currently your website has 4 ads - https://fargo1ife.com/kevin-gates-drops-his-third-project-luca-brasi-3/ and one is above the content and second is after the content and 3rd is above the recent posts and 4th ad in above the footer and have you placed the ads on that position only and are you using Auto AMP ads as well?

Please let us know.

**Comment by SageFargo** [comment]
@Zabi09 hello, I’m using the auto ads and I also have the #4 ad option on, which is below the post content. 
![37df12d3-e4bc-41fe-98f1-1354e4b51e57](https://user-images.githubusercontent.com/40724154/46455327-2cd48a00-c7b3-11e8-862f-4d5c9dff571c.png)

**Comment by Zabi09** [comment]
@SageFargo 

I have checked your website and found that currently your posts have only one Ad and that is after the content. Have you disabled the Auto AMP Ads option?

**Comment by SageFargo** [comment]
Yes I did, I haven’t closed the ticket my bad I’ve forgot. The problem isn’t fixed however I just disabled it.

**Comment by Zabi09** [comment]
@SageFargo 

Will you please enable the amp auto ads now for me to check again and please note that if you enable that the ads will appear automatically on your website header, footer, content etc and in addition to this the ads may appear one, two or three automatically by Google only.

**Comment by SageFargo** [comment]
Yeah, but hopefully they won’t appear in a weird spots like before, I have enabled the auto ads. Waiting for update. @zabi09

**Comment by SageFargo** [comment]
@zabi09 will it appear in-post only? Or even on homepage and other pages?

**Comment by SageFargo** [comment]
I have checked and the ads still won’t work properly.

**Comment by Zabi09** [comment]
@SageFargo The Ads can also appear on the homepage and other pages as well and the position will be automatcilly generated by Google only.

**Comment by SageFargo** [comment]
@zabi09 yes I’ve noticed, but the problem is the ads appear between the title and featured image. Anyway I’ve disabled it, I’ll stick to the default ad options.
