### ISSUE TITLE
Page 404

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#2599]
Whenever I get thrown to the 404 page, it seems that the amp doesn't support it anymore. Any way to fix it? or do I need to create a new from scratch? 
![screen shot 2018-10-05 at 3 46 05 am](https://user-images.githubusercontent.com/40724154/46510368-390f2480-c851-11e8-9cf1-688a848f6019.png)

**Comment by Zabi09** [comment]
We have already fixed this issue on this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2565 Please install our beta version and check again and we are sure that this issue will be fixed.

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.97.20, closing this ticket.
