### ISSUE TITLE
Allow HTML in footer like before

### ISSUE THREAD

**Issue by woutheijnen** [ahmedkaludi/Accelerated-Mobile-Pages#260]
Hello there,

I would like to ask if you could allow again to add HTML code in the translation panel of your amazing AMP plugin. I used to add my own HTML code, but I see now that the code is being translated to the code corresponding to the special characters such as < becomes &lt;. Could this be allowable again?

Also I want to ask you if the plugin is compatible with All in one SEO pack which I prefer over Yoast as it doesn't require a load of information which Yoast needs. (Should I desactivate Add Meta Tags from Yoast and Yoast Custom Description for AMP page with AIO SEO?)

Next I went to ask if it's possible to toggle the from and date on pages as I see it's on my page: https://www.brainobrainlyon.fr/quest-ce-que-brainobrain/amp/ .

And finally I would like to point towards a bug that I discovered on the Amp homepage (the older bug I mentioned a month before seems to be corrected by the way! Great work!): The image width is of 0, which generates an error in the Google Search Console.

Thank you for your wonderful plugin,
Cheers!

Wout Heijnen

**Comment by khaledMohammed000** [comment]
Done :)
