### ISSUE TITLE
Vuukle AMP integration

### ISSUE THREAD

**Issue by vuukle** [ahmedkaludi/accelerated-mobile-pages#2600]
Hi Support team,

Thanks for making Vuukle a part of your integration, we really appreciate it.

We have seen some issues with the way our plugin has been implemented and wondering if you can help fix it:

1. The title param needs to be encoded
2. the host param needs to be like this &host=site.com without any HTTP or www.

We are available on support@vuukle.com if you have any further questions.

**Comment by Zabi09** [comment]
Thank you so much for letting us know about the errors we will look into it and we will make sure it is fixed and are you trying to give us the URL of that page and forgot to write in our message because in the last line you just wrote - 'The page I need help with' without the proper URL?

**Comment by vuukle** [comment]
@Zabi09 thanks for your quick response. 

That was a typo, here is an example implementation which is affected because of the incorrect host and title param

<amp-iframe width="600" height="350" layout="responsive" sandbox="allow-scripts allow-same-origin allow-modals allow-popups allow-forms" resizable frameborder="0" src="https://cdn.vuukle.com/amp.html?url=https%3A%2F%2Fdoyouremember.com%2F59945%2F20-things-look-watching-christmas-story&**host**=https%3A%2F%2Fdoyouremember.com&id=59945&apiKey=45e74a80-4a92-4e89-8a8a-4b4449edb14d&**title**=20 Mistakes To Look For While Watching  "A Christmas Story"">

https://doyouremember.com/85476/best-airport-in-the-world-for-five-years/amp

**Comment by Zabi09** [comment]
https://docs.vuukle.com/vuukle-amp-integration/

**Comment by Zabi09** [comment]
I was checking your concern and I found that the comments are working fine without the encoding of the title and with HTTP also - http://take.ms/lMBUY

Will you please elaborate more about it exactly when you are facing this issue? So that we will understand and make the best solution for you.

Please let us know.

**Comment by MohammedKaludi** [comment]
Need to escape the url 
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/e66d663d8737e21315cd775d2acc42237124d244/templates/features.php#L5904

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22

**Comment by vuukle** [comment]
Hey guys it seems someone has changed the integration of Vuukle in your plugin and our plugin is not working on AMP pages:

`https://cdn.vuukle.com/amp.html?url={}&host={no_www._no_protocol}&id={postID}&apiKey={apikey}&title={encoded_title}&img={image}&tags={one_section}`

Can you help do a fast resolution please?

**Comment by MohammedKaludi** [comment]
Reopening the ticket.

@Zabi09 or @pegazee can you please check what is wrong and why it is not working anymore?

**Comment by pegazee** [comment]
@vuukle can you please elaborate in details what issue you're facing? I've checked on my end and it's working perfectly.

**Comment by vuukle** [comment]
Can you please share the AMP URL you have tested Vuukle on so I can confirm where the confusion might be?

**Comment by pegazee** [comment]
@vuukle 

Here is the screenshot: https://take.ms/8O5E6

And her is the URL: http://wordpress-amp.000webhostapp.com/2018/08/hello-world/amp

**Comment by vuukle** [comment]
@pegazee the page is not loading http://prntscr.com/moj9w2 can you please re-check and send so I can point out the missing variables:

All the variables in the curly brackets are needed https://cdn.vuukle.com/amp.html?url={}&host={no_www._no_protocol}&id={postID}&apiKey={apikey}&title={encoded_title}&img={image}&tags={one_section}

**Comment by vuukle** [comment]
@pegazee i was finally able to open the test url the article image (img) and section(tag) param is still missing, would that be possible to add please? Also, I am checking if the client has the latest version of your plugin installed.

**Comment by pegazee** [comment]
Hi @vuukle,

We've integrated the comments by using this tutorial > https://docs.vuukle.com/vuukle-amp-integration/. It seems that in the tutorial, img & tags param are missing. However, I'll add the article image (img) and tags (section) in param. And also could you please let me know what should I add in the tags parameter?

**Comment by vuukle** [comment]
Hi @pegazee sorry for the delayed response. For the tags we need just the first section tag (strictly only one). Please note they would have to be encoded the same way as the **Title** field. 
Please do share an example page so my team can confirm.

**Comment by pegazee** [comment]
Hi @vuukle I'm sharing the URL and also the example page, please check and confirms us. so that we can add this in the upcoming update.

* http://wordpress-amp.000webhostapp.com/2018/08/hello-world/amp
* https://cdn.vuukle.com/amp.html?url=http%3A%2F%2Fwordpress-amp.000webhostapp.com%2F2018%2F08%2Fhello-world&host=wordpress-amp.000webhostapp.com&id=1&apiKey=45e74a80-4a92-4e89-8a8a-4b4449edb14d&title=Hello+world%21&img=https%3A%2F%2Fi0.wp.com%2Fwordpress-amp.000webhostapp.com%2Fwp-content%2Fuploads%2F2018%2F08%2Ffavicon.png%3Fresize%3D512%2C510&tags=hello

**Comment by vuukle** [comment]
@pegazee looks great thanks 👍

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by pegazee** [comment]
Pushed in 0.9.97.44.1
