### ISSUE TITLE
In the swift theme the Sticky social icons overlaps. 

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2601]
Desc: In the swift-theme when placed a link to the GDPR / Cookie Settings in the footer of the page and The Z-index of the link is too high so that it overlaps with the social-sharing icons.

Ref: https://secure.helpscout.net/conversation/671946891/35437?folderId=2206768

Here is the screenshot: http://take.ms/zFXqQ

**Comment by MohammedKaludi** [comment]
:+1: code will be pushed in 0.9.97.24

**Comment by HANEEFRIYAZ** [comment]
Pushed in  0.9.97.24
