### ISSUE TITLE
Vuukle comments Improvement

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2602]
Ref:  https://secure.helpscout.net/conversation/678112565/36392?folderId=1914712

Description: 
1) Host should not contain http:// or htps:// or www. 
2) The title should be encoded

**Comment by Zabi09** [comment]
This will be fixed in #2600

**Comment by MohammedKaludi** [comment]
Closing this ticket more info about this issue can be found at #2600
