### ISSUE TITLE
AMP Option panel in mobile view

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2603]
http://take.ms/EXIxQ

**Comment by sardarui** [comment]
Another issue: AMP setting page in a mobile device is broken.
Ref: https://secure.helpscout.net/conversation/934684387/78857?folderId=3126461

**Comment by KinG-InFeT** [comment]
Follow +1

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
