### ISSUE TITLE
Need to fix the menu issue which is coming from the latest version of AMP core plugin

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2604]
Ref:  https://secure.helpscout.net/conversation/678733632/36484?folderId=1914712

Need to remove this check box
See this screenshot: http://take.ms/Nv3ka
http://take.ms/bV0qX

**Comment by beingsmart3** [comment]
One More :  https://secure.helpscout.net/conversation/679253396/36530?folderId=1060551

**Comment by cosmin-serbanescu** [comment]
hey @Zabi09, do you happen to know when will be the next AMP layouts release? I have version 1.4.2 right now and unfortunately I have the same checkbox issue: http://prntscr.com/l4huws

**Comment by Zabi09** [comment]
Hi @cosmin-serbanescu,

You are using AMP theme framework and your issue is going to fix in  #2618

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Ticket resumed in #2618
