### ISSUE TITLE
Menu cannot be seen and AMP pages are crashing

### ISSUE THREAD

**Issue by lioneltan** [ahmedkaludi/accelerated-mobile-pages#2605]
After the updates 3 days ago, my page view fell by almost 100%. This is because the update is buggy and crash my whole website.
<img width="307" alt="screen shot 2018-10-08 at 1 11 51 pm" src="https://user-images.githubusercontent.com/29434929/46593116-beb5fd00-cafb-11e8-9805-029839c51052.png">
The menu/navigation bar is not working

**Comment by Zabi09** [comment]
@lioneltan We are extremely sorry for the inconvenience, Will you please provide us the exact URL and a temporary wp-admin access. I will personally check it and I make sure it is fixed as soon as possible.

**Comment by lioneltan** [comment]
> @lioneltan We are extremely sorry for the inconvenience, Will you please provide us the exact URL and a temporary wp-admin access. I will personally check it and I make sure it is fixed as soon as possible.

Hi @Zabi09 to what email do i send it to?

**Comment by lioneltan** [comment]
Hi,
The wp-admin access is https://hoppervalley.com/wp-admin/?wtlwp_token=04cfa4061afd7bb516539062adf23fab




Attached are pictures of some of the errors.

**Comment by Zabi09** [comment]
@lioneltan Thank you for providing the URL and I have checked your website and the menu is appearing perfectly on my end.

See this screenshot: https://monosnap.com/file/NVgatl49zJJF0NXpVwFS9bPaTlXaiH

If you still have this issue then please contact us on team@magazine3.com and if you provide access here then everyone can access your WordPress dashboard so I have deleted it.

Please check once and let us know.

**Comment by lioneltan** [comment]
Hi,
If u click on jobs the menus will not show

**Comment by Zabi09** [comment]
@lioneltan You don't have any submenu in the "jobs" item of your menu and you have also disabled the amp on that.
See this screenshots:
http://take.ms/TgoW5
http://take.ms/w561v

**Comment by MARQAS** [comment]
Hi @lioneltan ,
Any update on this?

**Comment by lioneltan** [comment]
Hi,
I am still unable to access acelerared page on my jobs page.When I turn on,the jobs can’t be shown.
Regards

**Comment by Zabi09** [comment]
Hi @lioneltan,

Will you please tell us how you are making the jobs page? is that by BBPress plugin? and that the reason it's not rendering in AMP and if you want that page to render in AMP also then please have a look at our BBPress extension - https://ampforwp.com/bbpress/

**Comment by Zabi09** [comment]
Hi @lioneltan 

Will you please answer my question and if you have any problem then please let me know.
