### ISSUE TITLE
Vertical words in table on mobile 

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2606]
The issue is occurring because of word-break property which should not apply inside of the table.

Ref:  https://secure.helpscout.net/conversation/679354626/36582?folderId=1914712

screenshot:   http://take.ms/hV0N4

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
