### ISSUE TITLE
View Non-AMP version link is not working when Mobile Redirection option is enabled.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2607]
Desc: View Non-AMP version or View Desktop site link is not working when Mobile Redirection option is enabled.

Ref: https://secure.helpscout.net/conversation/679970464/36695?folderId=2206768

**Comment by Zabi09** [comment]
This issue has been already fixed in #2586 and it is not working in master but working perfectly in beta.

**Comment by Zabi09** [comment]
Fixed in #2586

**Comment by MohammedKaludi** [comment]
More info about this ticket in #2586
