### ISSUE TITLE
Featured image in design 1 in single

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/Accelerated-Mobile-Pages#261]
Featured image in design 1 in single

Reported at https://wordpress.org/support/topic/bugs-no-featured-image-and-broken-social-icon-in-design-1/

**Comment by khaledMohammed000** [comment]
Issue 1 fixed here : https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/22a86ddf6ef250603f8300fea752b8e6a863e94d

Featured image working properly : http://take.ms/U6LEx

**Comment by MohammedKaludi** [comment]
User want to have featured image on the home / index page.

**Comment by ahmedkaludi** [comment]
Checked, working fine
