### ISSUE TITLE
Glue for Yoast SEO & AMP plugin is removing Canonical link in single pages.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2611]
Desc : When Glue for Yoast SEO & AMP plugin is used, in single pages Canonical link is breaking and throwing a validation error because Yoast AMP and AMP for WP is conflicting as both is rendering AMP.
Ref : https://secure.helpscout.net/conversation/680300142/36753?folderId=2322652

**Comment by MARQAS** [comment]
It was due to users custom code, He removed the Yoast and was trying to add the custom code due to which canonical in Yoast was getting blanked. 
Resolved on his end and informed him as well.
