### ISSUE TITLE
AMP menu not working in the latest version [redirecting to non-amp]

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2612]
in the 0.9.97.19 the AMP menu is not working and redirecting to non-amp even though the add /amp in the menu URL option is enabled in the advance setting.

working well in 0.9.97.18 version
 
not working in 0.9.97.19/ 0.9.98 versions.

Ref: https://secure.helpscout.net/conversation/675724363/36024?folderId=1914713

**Comment by beingsmart3** [comment]
One More:  https://secure.helpscout.net/conversation/681186694/36862?folderId=1914712

**Comment by Rkroy** [comment]
Same issue : https://secure.helpscout.net/conversation/675781663/36034?folderId=2322652

**Comment by beingsmart3** [comment]
One More: https://secure.helpscout.net/conversation/676150374/36070?folderId=1914712

**Comment by MohammedKaludi** [comment]
:+1:  code already pushed in 0.9.97.19

Closing the ticket
