### ISSUE TITLE
Use Static page as Blog

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2614]
Some themes are using Templates for Blog. 
Example:
Reading settings: http://take.ms/ysIqL
Page settings: http://take.ms/BEQjK

Possible solution: Setting which allows the users to select which page they want to have as a Blog in AMP.

Ref: https://secure.helpscout.net/conversation/667937606/34837?folderId=1914712

**Comment by beingsmart3** [comment]
Ref: https://secure.helpscout.net/conversation/695016415/38647?folderId=1914712

**Comment by mdsam10** [comment]
https://secure.helpscout.net/conversation/696265416/38836?folderId=2206768

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
The issue seems to be fixed and the code will be pushed in 0.9.97.37

**Comment by pegazee** [comment]
Pushed in 0.9.97.37
