### ISSUE TITLE
alt is not working

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2617]
alt of image is not working when the image is inside the anchor tag. 

ref: https://wordpress.org/support/topic/alt-missing/

**Comment by Ysery** [comment]
Problem actual in ver 0.9.97.23

**Comment by Ysery** [comment]
Problem actual in ver 0.9.97.24

**Comment by MohammedKaludi** [comment]
> Problem actual in ver 0.9.97.24

are you still facing the issue?

**Comment by MohammedKaludi** [comment]
@Ysery this ticket is not pushed in this update. This will be pushed in the next update that is 0.9.97.25

So please be patient and this will be pushed in next update for sure.

**Comment by MohammedKaludi** [comment]
:+1: this can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25

**Comment by Ysery** [comment]
Thanks more for fixing.
