### ISSUE TITLE
Need to remove the checkbox from menu listings in AMP theme framework.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2618]
Ref : https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2604
User Ref : https://secure.helpscout.net/conversation/670689987/35232?folderId=2322652

**Comment by Zabi09** [comment]
Not working in master as well as in beta

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
