### ISSUE TITLE
Yoast Sitemap showing an error due to our plugin. 

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2619]
Desc :When our plugin is active yoast sitemap has been throwing following error.
Error : " error on line 1 at column 7: XML declaration allowed only at the start of the document "
Ref : https://secure.helpscout.net/conversation/679434172/36619?folderId=2322652

**Comment by MARQAS** [comment]
It is due to the beta version

**Comment by Zabi09** [comment]
Actually, there was a space in accelerated-mobile-pages/includes/features/functions.php but space is not there in master as well as current beta version - http://take.ms/VxTJe
