### ISSUE TITLE
 social icon doesn’t appear in one row

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/Accelerated-Mobile-Pages#262]
social icon doesn’t appear in one row

https://wordpress.org/support/topic/bugs-no-featured-image-and-broken-social-icon-in-design-1/

**Comment by khaledMohammed000** [comment]
https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/22a86ddf6ef250603f8300fea752b8e6a863e94d

**Comment by ahmedkaludi** [comment]
It was corrrect, but Had issue in design two, so fixed
