### ISSUE TITLE
Issue with Post Pagination ( Single )

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2624]
Post pagination of single is not working as expected, it's giving only 1st page content when the option is disabled.

ref: https://wordpress.org/support/topic/removing-pagination-3/

Recreated on localhost as well

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.38
