### ISSUE TITLE
Enter HTML in Head Advanced setting not working

### ISSUE THREAD

**Issue by mlt0882** [ahmedkaludi/accelerated-mobile-pages#2625]
This feature doesn't seem to be working. Trying to input that portion of my AMP GTM container snippet as well as the HTML tag tests so that I can verify my search console account but no matter what I put in there it doesn't seem to actually show up on the source code for the site. 

Please assist.

**Comment by mlt0882** [comment]
www.hearitall.us

**Comment by MARQAS** [comment]
Hi @mlt0882,
Where are you checking after adding the code? It will work only in the AMP site and will not have any effect on the non-AMP and check it on the live site but not the one which Google has already indexed. 
And make sure to clear the cache if has any.

**Comment by MARQAS** [comment]
Can you share the snippet which you are trying to add? And also please share the URL where you have enabled the AMP

**Comment by Zabi09** [comment]
Hi @mlt0882,
It seems you have enabled the Convert AMP to WP theme (Beta) option and because of that, the HTML in the head is not working because if you enable that option then your source code will be same as non-amp and only the frontend will be changed to the amp.

**Comment by Zabi09** [comment]
@mlt0882 
We have two options for converting your non-amp version into AMP version - https://monosnap.com/file/8shovMdFAkXJFcYDGj3v26G3gvvn3U

1 - Convert AMP to WP theme - When you enable this option then your non-amp version will convert to the amp but the source code will not change and only the front end will be the amp.

2 - AMP Takeover - And when you enable the takeover option then all your source code and frontend will convert to the amp.

So will you please enable the takeover option and check once.

**Comment by mlt0882** [comment]
@Zabi09 done. This has actually fixed a multitude of issues for me so thank you very much for your help!
