### ISSUE TITLE
Disable the Custom AMP Editor in the Posts/Pages

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2626]
Reference: 

https://secure.helpscout.net/conversation/686773343/37652?folderId=2090438

A user request is to disable the Custom AMP Editor and the AMP Pagebuilder but as we have already disabled the Page Builder in Beta Version, now we need to disable only the Custom AMP Editor.

**Comment by MARQAS** [comment]
Pagebuilder: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2414

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MARQAS** [comment]
We don't need this feature at the moment, we can reopen it when it requires. 
Closing this ticket for now.
