### ISSUE TITLE
Debug Errors

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2627]
- [x] https://wordpress.org/support/topic/undefined-varible-and-warning-messages/

**Comment by MARQAS** [comment]
Some of the errors were coming on Bruno's site which has been resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2654.

This ticket can be closed now.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ajeetku** [comment]
Debug issues of admin config resolve by ajax select2 already added in master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
