### ISSUE TITLE
Iframe is not loading when Convert AMP to WP theme (Beta) option is enabled.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2628]
Desc:  Can't seem to get the Google map embed to work properly. It is converting it to the amp-iframe tag but that causes it not to show up. When I go in the inspect tool and remove the amp- part of the tag, it shows up just fine.

Ref: https://secure.helpscout.net/conversation/686090628/37552?folderId=2169248

**Comment by MohammedKaludi** [comment]
Double check if URLs are being escaped or not, add esc_url and use preg_replace_callback for the safer side

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6daf000a26803acd26b79957aa7f442120a57289#diff-1301281de287d2aed98746fc9ba777b4R78

**Comment by ajeetku** [comment]
The **regular expression** is failed when Iframe is like 
<iframe width="560" height="315" src="https://www.youtube.com/embed/EXwYd0g0Cbc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
