### ISSUE TITLE
Instagram Posts not rendering in AMP

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2629]
Reference:

https://secure.helpscout.net/conversation/686895473/37663/

Instagram Posts (Embed-code) not rendering in AMP.

**Comment by ahmedkaludi** [comment]
I think he is using embed code.

**Comment by EM-MiguelRosas** [comment]
Still no update here, my IG embeds are broken.

**Comment by EM-MiguelRosas** [comment]
> Still no update here, my IG embeds are broken.

do I need to post a new issue ?

**Comment by EM-MiguelRosas** [comment]
> > Still no update here, my IG embeds are broken.
> 
> do I need to post a new issue ?

`<amp-instagram data-shortcode="?utm_source=ig_embed&amp;utm_medium=loading" width="400" height="400" layout="responsive" data-captioned="" class="i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-layout"><i-amphtml-sizer style="padding-top: 100%;"></i-amphtml-sizer><div placeholder="" class="amp-hidden"><amp-img noprerender="" src="https://www.instagram.com/p/%3Futm_source%3Dig_embed%26utm_medium%3Dloading/media/?size=l" layout="fill" referrerpolicy="origin" class="i-amphtml-element i-amphtml-layout-fill i-amphtml-layout-size-defined i-amphtml-layout amp-notsupported"><img decoding="async" referrerpolicy="origin" src="https://www.instagram.com/p/%3Futm_source%3Dig_embed%26utm_medium%3Dloading/media/?size=l" class="i-amphtml-fill-content i-amphtml-replaced-content i-amphtml-ghost"></amp-img></div><iframe scrolling="no" frameborder="0" allowtransparency="true" title="Instagram: null" src="https://www.instagram.com/p/%3Futm_source%3Dig_embed%26utm_medium%3Dloading/embed/captioned/?cr=1&amp;v=9" class="i-amphtml-fill-content" style="opacity: 1;"></iframe></amp-instagram>`

**Comment by EM-MiguelRosas** [comment]
data-shortcode is getting the wrong section of the Embed URL, is getting the last item on the array, when is on posisition 4, for the explode donde on sourcecode.

file: ..plugins/accelerated-mobile-pages/classes/class-ampforwp-instagram-sanitizer.php
line: 32

**Comment by MohammedKaludi** [comment]
Hey @EM-MiguelRosas,

Can you please add this code and test it? https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/004707899d280a1165ccce24778ab967adbf20e9

Because we are going to push this ticket in the month of March.

If you need the instructions on how to add it on your website, I can help you with it.

**Comment by EM-MiguelRosas** [comment]
Hi @MohammedKaludi,

Yes, I had a similar temp fix, just tried commit [0047078](https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/004707899d280a1165ccce24778ab967adbf20e9) and it works ok.

Thank you.

**Comment by beingsmart3** [comment]
- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
