### ISSUE TITLE
GTM analytics code appears twice in the beta version.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2631]
Ref: https://secure.helpscout.net/conversation/678672381/36467?folderId=2206768
Ref: Localhost

**Comment by MohammedKaludi** [comment]
why it fixed after changing the hook?
can you dig into the issue, please?
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4c93cd8b22609a2613aebcc75af862b3bc0b2aa7#diff-9f65b1edeb6d18b3cc5f9f2a21bfd824R83
