### ISSUE TITLE
How to remove “Powered by WordPress” from Design-1 of AMP

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/Accelerated-Mobile-Pages#264]
How to remove “Powered by WordPress” from Design-1 of AMP

https://wordpress.org/support/topic/how-to-remove-powered-by-wordpress-from-design-1-of-amp/

**Comment by khaledMohammed000** [comment]
This was manually coded previously ... now we are adding it in default footer text .. You can get rid of it Just by replacing it what ever you want from Footer Section of Translation Panel ...
