### ISSUE TITLE
Social Share “LINE” does not show up in swift theme

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2641]
Ref: https://wordpress.org/support/topic/social-share-line-does-not-show-up/

**Comment by MohammedKaludi** [comment]
wrong usage of `esc_url` 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/017e87d3fc0dbef8e894bd742d48641a58b28750#diff-18e7a4ed2f3df1181e013bcc7fbdd406R101

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
use `add_query_args` instead of directly appending.

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0e6e56f2c359d9c92c1873c3db51f3a6c1ce8e6b#diff-7d3a92ac5e6165548bf9bc556f4f887aR267

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
