### ISSUE TITLE
Caption is not displaying in images of gallery and page builder.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2644]
If we add any caption for the gallery image, then it is not displaying in AMP pages, however it was working in previous update. Also the caption is not displaying in AMP page builder.

**Comment by Zabi09** [comment]
The Gallery caption issue is fixed in the beta version #2576 and currently, we don't have the feature of the caption in page builder but we will add that in future updates for sure #2645
