### ISSUE TITLE
Lightbox feature for Gallery Slider to be built for Slider module

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2646]
Reference:

https://secure.helpscout.net/conversation/689629142/37985?folderId=2090438

User requested a feature to add this in our next update.

**Comment by pegazee** [comment]
Already fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2731

**Comment by Zabi09** [comment]
Escaping is required

**Comment by Zabi09** [comment]
Lightbox is working after disabling the option also

**Comment by pegazee** [comment]
** review  **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
