### ISSUE TITLE
Create posts offset option on category module in the AMP Page Builder.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2647]
Ref: https://secure.helpscout.net/conversation/693524200/38463?folderId=2206768

**Comment by pegazee** [comment]
One more user request: https://wordpress.org/support/topic/offset-14/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
