### ISSUE TITLE
Time stamp support in category module of AMP pagebuilder

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2648]
The user can add the timestamp, author, etc in AMP page builder 
Ref: https://wordpress.org/support/topic/amp-builder-questions/

**Comment by Zabi09** [comment]
Previous/Next links support in AMP page builder

**Comment by MARQAS** [comment]
Add this filter as well. `ampforwp_modify_post_date`

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
escaping missing 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/058427d7d0d7939252feb9ad38c2b28d17d63508#diff-cb16861af9ff34ccd298041891008f49L396

**Comment by MohammedKaludi** [comment]
:+1: ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
