### ISSUE TITLE
call-now component is being used?

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2652]
Check the usage of call-now component, or we are using #55 from features.php

Remove unwanted.

**Comment by MARQAS** [comment]
Please update the tutorial as well. https://ampforwp.com/tutorials/article/call-now/

**Comment by Zabi09** [comment]
Updated

**Comment by MARQAS** [comment]
Make sure to add the fallback: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2782

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
pushed in 0.9.97.44
