### ISSUE TITLE
Convert Ads code into arrays and then convert it to json

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2653]
Convert analytics code from direct json print to array format for all ad companies, and add a filter after the array is complete and use `json_encode` to convert it to json, this will sanitize all the code as well.

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
all the filter names are same https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5bb9bd217e0e3ed060d1ef2a1d0fba4ad6d1ea63#diff-b27b16759fae0fb0d94cc6e00107c8efR203

`ampforwp_advance_google_analytics` filter names should be according to the ads company.

**Comment by MohammedKaludi** [comment]
:+1: good to go

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28
