### ISSUE TITLE
Fatal error when Polylang(Core) is activated.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2657]
Reference:
https://secure.helpscout.net/conversation/689092515/37924

Whenever we activate the Polylang Plugin and not create any Language, then it happens to be Fatal Error. Once the (any) Language is created it works perfectly.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.23
