### ISSUE TITLE
Author Box and Archives

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#2658]
Hi, It would be great if you guys took some time to work on the author box and author archives, as seen in the screenshots below; the author box shows the bio & photo properly but it’s missing social media links, There should be a twitter handle below the bio. 

On the Author archives page, it only shows the bio without the picture for some reason, also the social links are missing as well, my recommendation is to add social media icons in the author box and on the archive page add an option to list the location of the author, and social media links such as google+ and twitter.

I’m trying to enlist our website on the Google news platform, but it requires the authors archives page and author box to work properly.

Thank you.
![62552f1a-19d9-40ca-bfc6-79644563f716](https://user-images.githubusercontent.com/40724154/47887219-df494c80-de46-11e8-85f8-0b7252d67b13.png)
![c2c4e823-11d3-400a-aea8-ce7f4e6fc2a0](https://user-images.githubusercontent.com/40724154/47887220-df494c80-de46-11e8-9d52-a025a64be4df.png)

**Comment by SageFargo** [comment]
When will the W15 will come? Any news regarding this feature?

**Comment by Zabi09** [comment]
@SageFargo Will you please tell us how you are adding social icons meaning which plugin you are using to get the social icons in author bio So that we will check it and make it compatible with AMP.

**Comment by Zabi09** [comment]
@SageFargo reply - There is no plugin, it should be working by default, user’s social links should be showing in bio.

But there’s a plugin called “Simple Author Box” which has almost the same design with social media icons

**Comment by Zabi09** [comment]
Hello @SageFargo,

We have found that the Simple Author Box plugin has recently created the AMP compatibility and will you please use the latest version of that plugin and check once and I am sure that the social icons, avatar etc will appear perfectly,

**Comment by SageFargo** [comment]
Hi @zabi09, I know this plugin works, to edit it you have to buy it because it’s a premium feature and I don’t think it’s convenient to use different plugins for issues like this one. It’s an easy fix you’re right, but the text is quite big and there’s no way to edit it unless you buy the premium version.

Will you pleased simply edit the amp code of the author box, so we won’t need to use plugins to tweak the AMP Plugin?

**Comment by Zabi09** [comment]
@SageFargo Will you please enable it again and send us your website URL and I will check the issue of "the text is quite big" and then I will provide the proper CSS and then you can add that in Global section of our AMP panel.

**Comment by Zabi09** [comment]
@SageFargo Please contact us on team@magazine3.com and our team will help you in fixing your CSS issues.

**Comment by SageFargo** [comment]
@zabi09, why CSS issue? You said this will be implemented in the next update.
