### ISSUE TITLE
Image URL replacement on AMP page not correct and aq_resizer not working with cdn images

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2659]
Ref: https://wordpress.org/support/topic/image-url-replacement-on-amp-page-not-correct/

**Comment by MohammedKaludi** [comment]
Testing info: https://secure.helpscout.net/conversation/751564352/49677?folderId=2322652

**Comment by RajuJeelaga** [comment]
In the category Module, when loop pagination is enable starting and Middle pages are coming fine, when i switch to last pages, warning error is showing, Please see the screenshot.
https://monosnap.com/file/OTRsOfz3wP9XiBzGEjOhtK5LPidtVf

@Zabi09 and @ajeetku please check this.
#1676

**Comment by beingsmart3** [comment]
Litespeed testing info: https://secure.helpscout.net/conversation/787282956/56872?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
