### ISSUE TITLE
 Google Tag Manager Advanced Option

### ISSUE THREAD

**Issue by mlt0882** [ahmedkaludi/accelerated-mobile-pages#2660]
Why can we not just use the Analytics tag through Google Tag Manager? It's pretty annoying that it forces you to input your Analytics ID to be able to even use the GTM option. This forces me to decide between being able to set up event tracking through advanced analytics without GTM or using GTM without setting up the events and just having to use the basic "pageview" tracking. Either way, not being able to use analytics through my GTM is causing me a lot of trouble. 

Please assist in how I can use GTM without being required to use the Analytics JSON you guys are forcing us into.

**Comment by Zabi09** [comment]
You can enable the option of "Google Tag Manager" in the analytics section of the AMP panel and in that you just need to add three fields and without any code, your AMP tracking and GTM will work perfectly.

Here is screenshot - https://monosnap.com/file/P2llgR9R6FXtkVtNTYa3JvRpsXMGRK

**Comment by mlt0882** [comment]
I think we're getting some things lost in communication here. So the first screenshot outlines the event tracking JSON that I would like to utilize through Google Analytics. Which is only available to show whenever I disable the "Google Tag Manager" option. 

Unfortunately, whenever I enable the "Google Tag Manager" option, it only includes the first portion (that tracks pageviews). If I try to do it through Google tag manager (ie adding the triggers for pageviews/event tracking, etc. through GTM), I end up with duplicate tags on the website. 

![screenshot 92](https://user-images.githubusercontent.com/38636643/48092672-eec3ef00-e1d2-11e8-897a-a421c045a3fa.png)

Please let me know if there is any way I can include the above JSON tracking code through Google Tag Manager without the automatic creation of tags from the AMP Plugin.

**Comment by Zabi09** [comment]
@mlt0882 Does Google Tag Manager allow the custom code also? and if yes then currently we don't have the option of displaying advance code in GTM. But I will discuss this use case if the lead developers and let you know

**Comment by mlt0882** [comment]
GTM allows for me to do event tracking, yes. The issue at hand is that the plug-in forces me to input only my Google Analytics ID whenever I enable Google Tag Manager, which results in either double tagging issues (if I enable pageview tracking through GTM) or the more simple plug-in Analytics (where you input the UA-XXXXXXXX in the plug-in) takes over and only allows for pageview tracking, effectively cancelling out my GTM tags. 

I hope that makes sense.

**Comment by ajeetku** [comment]
Notice:  Undefined variable: gtm_fields in accelerated-mobile-pages\templates\features.php on line 1846
Please verify this variable has used but not initialized.

**Comment by MARQAS** [comment]
Escaping is required and use `ampforwp_get_setting`

**Comment by pegazee** [comment]
Need proper escaping, please see the screenshots:

* https://take.ms/97ZK7
* https://take.ms/0l0W6

**Comment by MARQAS** [comment]
Translation required

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
https://take.ms/DE8YN

**Comment by MohammedKaludi** [comment]
Google Tag Manager "Analytics Code in JSON Format" is not loading in AMP

**Comment by MohammedKaludi** [comment]
amp-analytics script not loading. Created the issue in localhosst.

**Comment by MohammedKaludi** [comment]
return $analytics;

 not 
return ;

**Comment by MohammedKaludi** [comment]
Looks good now

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59

**Comment by MohammedKaludi** [comment]
test and merge into master if it is not already added.

**Comment by MohammedKaludi** [comment]
Remove the comments as discussed while mergeing.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
