### ISSUE TITLE
Misplaced Tags

### ISSUE THREAD

**Issue by mlt0882** [ahmedkaludi/accelerated-mobile-pages#2661]
It would seem that the plug-in is putting the information that is supposed to be in my head tag inside of the body tag. This is leading to a white line at the top of every page that literally says "HEAD" and when you inspect it, this is where all the styling, tracking ID, etc. are found. 

Please fix immediately, this is making my website look ridiculous. See attached for visual.
![screenshot 91](https://user-images.githubusercontent.com/38636643/48017562-290a8f00-e0f4-11e8-90fd-0ca276c36c69.png)

**Comment by Zabi09** [comment]
@mlt0882 

It seems you are adding text "HEAD" in HTML in head option and because of that you are facing this issue,

Will you please check your HTML in head option in advance setting or maybe you are adding it seo section.

Please check both options once and let us know.

**Comment by mlt0882** [comment]
You would be correct. Apparently the comment part of my analytics installation was removed so it just left that behind. 

Issue is fixed, thank you for your help.
