### ISSUE TITLE
Video thumbnail is not rendering in mobiles for self hosted videos.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2663]
Desc: Video thumbnail is not rendering in mobiles for self-hosted videos.
Ref: https://secure.helpscout.net/conversation/699864463/39321?folderId=2169248

**Comment by ahmedkaludi** [comment]
1 week deadline

**Comment by ahmedkaludi** [comment]
not a valid issue, so ticket will be closed. Need to continue the communication on Team@magazine3.com
