### ISSUE TITLE
Need to add filters for links of breadcrumbs, comment button and the non-amp version link in footer

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2664]
Def: Need to add filters for links of breadcrumbs, comment button and the non-amp version link in footer.
Ref: https://secure.helpscout.net/conversation/696714419/38892?folderId=2169248

**Comment by rvencu** [comment]
thanks

**Comment by MohammedKaludi** [comment]
need to change the name of the filter

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8cfe4df430623f35002265e3ba5aa97a52f7ed88#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3579 

change the name of the filter

**Comment by MohammedKaludi** [comment]
ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
