### ISSUE TITLE
"Justify" Option to be added in Page builder options

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2665]
Reference:

https://secure.helpscout.net/conversation/699360012/39251/

A user request is to add Justify Option in Page builder option - -> Design - -> Align.

Currently, we've Center/left/Right and now need to add Justify.

**Comment by MohammedKaludi** [comment]
:+1: look alright, can be merged into master

**Comment by pegazee** [comment]
Working as expected.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.35
