### ISSUE TITLE
AMP pagebuilder module doesn't have proper "Need Help" link and it is going to 404 page

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2666]
https://imgur.com/eni0TGF

https://wordpress.org/support/topic/the-plugin-will-be-back-online-and-will-be-much-better-so/

**Comment by MohammedKaludi** [comment]
add text domain and esc_url 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5bc87f69b163dd9148f1d339dffdcc6c0ac0635f#diff-127111884d3c28aa16350c990b990201R127

**Comment by ahmedkaludi** [comment]
Link is already redirected to the new place.
