### ISSUE TITLE
Menu is Not working in Minimal Blogging theme (0.9.97.20)

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2667]
Ref:   https://secure.helpscout.net/conversation/707628999/40308?folderId=1914712

**Comment by Zabi09** [comment]
Fixed on users end but need to discuss before committing - http://take.ms/Y1AQg

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/708732176/40462?folderId=1060554

**Comment by Zabi09** [comment]
And also in the AMP theme framework - https://awesomestufftobuy.com/sprout-pencils/amp/

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 0.9.97.21
