### ISSUE TITLE
Menu Colors Messed Up After Recent Update

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#2668]
Hello,

After the recent AMP Update the menu colors have been changed; Top Menu links turned red while there were black.

Footer Menu Background color went from black to white. 

Is there any way to fix this?

See examples below:

![57bef428-1516-4286-8b2a-5116a88ae1e9](https://user-images.githubusercontent.com/40724154/48467141-be8ed880-e7f0-11e8-8875-f31ba9c4f7ef.jpeg)

——————————————————-

![535409d6-5a6f-4a32-a28d-6e7e8287621f](https://user-images.githubusercontent.com/40724154/48467400-6c01ec00-e7f1-11e8-815f-2971c6bb4d2b.jpeg)

**Comment by Zabi09** [comment]
@SageFargo 

The color is coming from the global section of the global color schema option in the AMP panel - https://prnt.sc/lia4q9  

Will you please check once and let us know.

**Comment by SageFargo** [comment]
But will it change the links color? Even though I’ll change it the footer menu’s background was changed to white.

**Comment by SageFargo** [comment]
I have just tried, and it changes the link colors, boxes and much more settings, the problem is in the menu itself I don’t want to change the whole color scheme. Please look into to this instead of offering simple techniques.

Even with this option the BAKCGROUND of the footer menu doesn’t change from white to black. 

The color should stay red on links and buttons. Inspect the screenshots I’ve added.

**Comment by Zabi09** [comment]
Will you please go to AMP => Design => Global => add these code on the Custom CSS 

ul#menu-menu-3 li a {
    color: #000;
}

Will you please add this code and let us know.

**Comment by SageFargo** [comment]
Yes! It worked! Thank you!
