### ISSUE TITLE
Stylesheet exceeds limit erorr

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2669]
Desc: Author stylesheet specified in tag 'style amp-custom' exceeds limit of 50000 bytes

Ref: https://secure.helpscout.net/conversation/695294617/38688?folderId=2169248
https://www.teacher4us.com/2017/02/ts-gurukulam-7306-posts-all-posts-paper-12-syllabus.html/amp
https://www.teacher4us.com/2017/03/palamuru-university-degree-exams-time-table.html/amp

**Comment by ahmedkaludi** [comment]
not a valid issue, so ticket will be closed. Need to continue the communication on Team@magazine3.com
