### ISSUE TITLE
Need to add the compatibility with the SEO Framework Plugin

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2670]
Ref: https://wordpress.org/support/topic/the-seo-framework-support-2/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Need to change the way we check 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/88f92bb8d33d3124ff6a9bc025e8f14adbe9f71e#diff-260eba6333c3222e59a6aed22ac5ab37R1446

**Comment by MARQAS** [comment]
Already added

**Comment by MohammedKaludi** [comment]
👍 ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
