### ISSUE TITLE
CSS is getting breaked in GoodLife theme.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2673]
In GoodLife theme, the CSS is getting breaked.
Ref : https://secure.helpscout.net/conversation/707158828/40250?folderId=2322652

**Comment by MohammedKaludi** [comment]
move this code in thrid-party-compatiblity

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/381673b0dc7b9fe14124fcf408476fc6aa61c3ab#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6822

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by syedimran22** [comment]
@Zabi09 Design1 header CSS is not loading apart from that everything is properly loading.

**Comment by pegazee** [comment]
Search widget styling is not properly rendering in all designs.
D-1: https://take.ms/6ej6Q
D-2: https://take.ms/KNj3n
D-3: https://take.ms/xU7uhE
Swift: https://take.ms/zadwd

Note: I've added the widgets in the above the footer

**Comment by Zabi09** [comment]
Search widget styling will be fixed in #3000

**Comment by ansaritalha** [comment]
Review

- [ ] Talha
- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.47
