### ISSUE TITLE
Ads by Google Adsense not shown

### ISSUE THREAD

**Issue by wichaksono** [ahmedkaludi/accelerated-mobile-pages#2675]
i'm tried to add my adsense code in my website but my ads never shown. and in my console log i found error like this
![image](https://user-images.githubusercontent.com/11472981/48747468-1a040f00-eca6-11e8-9622-64680ed18aeb.png)

**Comment by Zabi09** [comment]
Hi Wichaksono,

Will you please share the URL and also tell us how many ads you are using on your website and how you are adding these ads? So that we will check once and let you know.

**Comment by Zabi09** [comment]
@wichaksono 
Will you please provide us the exact url? we will check the ads and fix it. please let us know.

**Comment by ahmedkaludi** [comment]
@wichaksono Kindly reach out to our tech team at https://ampforwp.com/support/

Our team will help  you.
