### ISSUE TITLE
The featured slider is not displaying properly images using the Firefox browser with the design 3 theme.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2677]
Ref: https://secure.helpscout.net/conversation/711535036/41012?folderId=2206768

Screenshot: http://take.ms/B7ved

**Comment by Rkroy** [comment]
In design one as well, slider is functioning correctly in Firefox browser.
Ref : https://secure.helpscout.net/conversation/707636496/40309?folderId=2322652

**Comment by MohammedKaludi** [comment]
:+1: added in master and will be pushed in 0.9.97.22
