### ISSUE TITLE
Extra CSS is getting added from Rehub theme and causing stylesheet error when 2 or more extensions are used

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2678]
Desc: Extra CSS is getting added from Rehub theme and causing stylesheet error when 2 or more extensions are used in woocommerce product page.

REF: https://secure.helpscout.net/conversation/711737053/41106?folderId=2169248

**Comment by MARQAS** [comment]
The error is due to his rehub theme, the user or his developer was trying to add lots of CSS in AMP on single pages but it was also affecting his product pages. 
Added the condition on his site to load that CSS only on posts and the issue is resolved. 
Waiting for users confirmation

**Comment by ahmedkaludi** [comment]
Not a valid issue.
