### ISSUE TITLE
The attribute 'rel' may not appear in tag 'div'

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/Accelerated-Mobile-Pages#268]
**Ref** : https://validator.ampproject.org/#url=http%3A%2F%2Flemontrend.com%2Fbeauty%2Fredken-heatcure-treatment%2Famp%2F.
http://lemontrend.com/beauty/redken-heatcure-treatment/amp/.
https://wordpress.org/support/topic/prohibited-or-invalid-use-of-html-tag-2/#post-8528933

**Comment by ahmedkaludi** [comment]
Reviewed. Working fine
