### ISSUE TITLE
When there is no match for the query in amp search then it is renderring the non-amp template when amp-takeover is enabled

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2681]
Desc: When there is no match for the query in amp search then it is renderring the non-amp template when amp-takeover is enabled
There is an issue with the internal search function. When there is no match for the query (example: "abc") the theme malfunctions and brings up the old (parent)

Ref: https://secure.helpscout.net/conversation/712019228/41176?folderId=2169248

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.38
