### ISSUE TITLE
Need to fix bugs in Infinite Scroll feature.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2682]
Need to fix below bugs in Infinite Scroll feature : 

- Navigation/Header bar is repeating in AMP infinite scroll.
- Only 3 posts showing in AMP infinite scroll.

Ref : https://secure.helpscout.net/conversation/683624383/37212?folderId=2322652

**Comment by MARQAS** [comment]
Note: For performance reasons amp-next-page will currently load and display a maximum of three pages on screen at once, so cannot be used to provide a true infinite scroll.
ref: https://ampbyexample.com/components/amp-next-page/

**Comment by RajuJeelaga** [comment]
- [ ] Loop is repeating from body, when infinite scroll is added 
Please see the screenshots
https://monosnap.com/file/PewZfwzWggKSI1e6vsgPziyY9yLk4b

Please see the HTML Markup how it is showing when infinite scroll is enable....
<body>
  <header></header>
   <wrapper></wrapper>
   <footer></footer>
   <div>
           <div class="amp-next-page-libks">
                  <body>
                        <header></header>
                       <wrapper></wrapper>
                        <footer></footer>
                             ------------- ---
                             ------------------- the process is going.
                   </body>
           </div>
   <div>
</body>


@MARQAS , @MohammedKaludi

**Comment by MARQAS** [comment]
@RajuJeelaga Use CSS like this: 
```
.amp-next-page-links+div {
    background: red;
}

```
And Discuss with @ahmedkaludi about it.

**Comment by RajuJeelaga** [comment]
@ahmedkaludi Need to discuss with you regarding the styling..

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Below header Widgets are reloading in Infinite Scroll option

https://monosnap.com/file/k7yoRQNlwDoncKMsoOUPo8Tm6044Ks

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
