### ISSUE TITLE
CF7 not displaying notification messages

### ISSUE THREAD

**Issue by mlt0882** [ahmedkaludi/accelerated-mobile-pages#2683]
Whenever I hit submit on my contact form, nothing happens. If it is filled out correctly, the email will send but there is no message confirming that pops up after it is submitted (likely Javascript issue). This is leading people to believe that their contact form hasn't been sent, which has obvious conversion rate optimization consequences. See attached for console log
![screenshot 98](https://user-images.githubusercontent.com/38636643/48791045-648d8780-ecb6-11e8-8761-b85bd1a1c5ce.png)
.

Please advise.

**Comment by Zabi09** [comment]
@mlt0882 One of your team members "Talha Ansari" has emailed you a few days back will you please check that and get back to us.

**Comment by mlt0882** [comment]
I haven't received any emails. Could you have them resend it?

**Comment by Zabi09** [comment]
Is this your email ID - matthew@hearitall.us ?
