### ISSUE TITLE
AMP for current page not working.

### ISSUE THREAD

**Issue by Navotas** [ahmedkaludi/accelerated-mobile-pages#2684]
I have published 2 post since last update.
When I change to SHOW (show AMP for Current Page?) and update the post, it returns to HIDE button.
Are there any limitation of number of post with AMP?
Thanks in advance...

**Comment by Zabi09** [comment]
Hi Navotas,
Sorry for the delay in response, No there is no limitation and you can create as many posts as possible in the AMP version. Will you please share your wp-admin credentials at team@magazine3.com and we will check on your end and make sure it will show on all your posts.

**Comment by Zabi09** [comment]
@Navotas 
Have you contacted us on team@magazine3.com? Please let us know

**Comment by Navotas** [comment]
Dear  syed,
Not yet.  I will try to send mail this afternoon

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Navotas** [comment]
I have a new error in AMP pages:  
https://www.perdidosenlaweb.com/alisado-brasileno/ 
https://www.perdidosenlaweb.com/robot-aspirador/ 
https://www.perdidosenlaweb.com/dieta-para-adelgazar/ 

{"@type":"Organization","name":"Perdidos en la web","logo":{"@type":"ImageObject","url":"","height":"60","width":"600"}},"headline":"Dieta para adelgazar","datePublished":"2018-04-24T19:54:44+00:00","dateModified":"2018-11-30T21:12:47+00:00","author":{"@type":"Person","name":"JJ"},"image":

The url is empty

I give permissions to team@magazine3.com

**Comment by Zabi09** [comment]
@Navotas 
Okay thank you

**Comment by Navotas** [comment]
About this error:
I have a new error in AMP pages:
https://www.perdidosenlaweb.com/alisado-brasileno/
https://www.perdidosenlaweb.com/robot-aspirador/
https://www.perdidosenlaweb.com/dieta-para-adelgazar/

{"@type":"Organization","name":"Perdidos en la web","logo":{"@type":"ImageObject","url":"","height":"60","width":"600"}},"headline":"Dieta para adelgazar","datePublished":"2018-04-24T19:54:44+00:00","dateModified":"2018-11-30T21:12:47+00:00","author":{"@type":"Person","name":"JJ"},"image":

The url is empty

Is in AMP / structured data - Blogposting.

**Comment by Navotas** [comment]
About this error:
I have a new error in AMP pages:
https://www.perdidosenlaweb.com/alisado-brasileno/
https://www.perdidosenlaweb.com/robot-aspirador/
https://www.perdidosenlaweb.com/dieta-para-adelgazar/

{"@type":"Organization","name":"Perdidos en la web","logo":{"@type":"ImageObject","url":"","height":"60","width":"600"}},"headline":"Dieta para adelgazar","datePublished":"2018-04-24T19:54:44+00:00","dateModified":"2018-11-30T21:12:47+00:00","author":{"@type":"Person","name":"JJ"},"image":

The url is empty

Is in AMP / structured data - Blogposting.

**Comment by Zabi09** [comment]
One of our team members is working on your issue, Will you please check his message and get back to us.

**Comment by ahmedkaludi** [comment]
@Navotas This ticket is not relevant for Github. Kindly handle this with our Tech team on team@magazine3.com
