### ISSUE TITLE
Performance issue as user has 29,484 tags (Beta)

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2685]
user has 29,484 tags because of that AMP and Non-amp is having very less
performance https://prnt.sc/llfysa

Ref: https://secure.helpscout.net/conversation/710303945/40697?folderId=1914712

**Comment by MARQAS** [comment]
Added in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2762
Can be closed

**Comment by MohammedKaludi** [comment]
Ticket can be closed as all the reported fixed.
