### ISSUE TITLE
The AMP for WP plugin(Version 0.9.97.20) bug are notice-error :undefine index and Unused code.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2687]
Notice: Undefined index: type in /wp-content/plugins/redux-framework/ReduxCore/framework.php on line 1247
Notice: Undefined index: type in /wp-content/plugins/redux-framework/ReduxCore/framework.php on line 1252
Notice: Undefined index: type in /wp-content/plugins/redux-framework/ReduxCore/framework.php on line 1167
Notice: Undefined index: type in /wp-content/plugins/redux-framework/ReduxCore/framework.php on line 1168
Notice: Undefined index: type in /wp-content/plugins/redux-framework/ReduxCore/framework.php on line 1174
Notice: Undefined index: type in /wp-content/plugins/redux-framework/ReduxCore/framework.php on line 1195.

And these errors and found that problem is in Your plugin AMP for WP in this file /includes/options/admin-config.php on line 1061.

Redux::setSection( $opt_name, array(
'title' => esc_html__( 'Basic Field', 'accelerated-mobile-pages' ),
'id' => 'basic',
'desc' => esc_html__( 'Basic field with no subsections.', 'accelerated-mobile-pages' ),
'icon' => 'el el-home',
'fields' => array(
array(
'id' => 'opt-blank',
'title' => esc_html__( 'Example Text', 'accelerated-mobile-pages' ),
'desc' => esc_html__( 'Example description.', 'accelerated-mobile-pages' ),
'tooltip-subtitle' => esc_html__( 'Example subtitle.', 'accelerated-mobile-pages' ),
)
)
) );

Solution:  remove this section (from line 1061 to line 1074) because it is never used. Or You can just add 'type' argument in an array which is on line 1067.

Ref: https://secure.helpscout.net/conversation/713601951/41403?folderId=2206768

**Comment by mdsam10** [comment]
Notice: Undefined index: pagename in D:\xampp\htdocs\magzine\wp\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 5957

**Comment by MARQAS** [comment]
Others have already been resolved in Beta

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
