### ISSUE TITLE
WooCommerce Products

### ISSUE THREAD

**Issue by shtefcs** [ahmedkaludi/accelerated-mobile-pages#2689]
WooCommerce features seems confusing and limited. There is not much in documentation about WooCommerce and how to properly setup a home page, shop page.

I am trying to use AMP builder and its **products** component.  This component offer very limited features as you can see on [screenshot](https://i.imgur.com/ofZAkr4.png).  

It should have all possible features like it have in [WooCommerce Shortcodes](https://i.imgur.com/QBfmbwF.png). 

Also, I am aware that I could use that woocommerce short code `[best_selling_products per_page="12" columns="4" orderby="date" order="ASC"]` as a text component in amp builder, but its very haotic styled [as you can see](https://i.imgur.com/A5F79Ck.png) and **add to cart** button is reloading whole page, which should not be part of **AMP UX**

WooCommerce features are built only for mobile in mind in terms of design and UI. You should extend to the web version as well.  

WooCommerce *products* component in AMP Builder should have option similar to BackeryBuilder (Apus Products component) which looks like this https://i.imgur.com/dXiqvSN.png. 
It should contain:
- Title of the block/component
- Get products by: (Recent, Best, Featured, Top, etc)
- Get products by category
- Number of products to display
- Number of columns (very important cause you should support web version, and on mobile it will automatically be displayed in 2 columns)

I mainly bought all extension package because of WooCommerce plugin, cause I want my store to be fast and provide great experience both on web and mobile. 

I think very little people use AMP on WooCommerce or E-commerce overall. So I am here to test and use ur features as test and experiment on my established business [UX Store](https://uxstore.com) and help you make a great plugin via feedback and suggestions.

**Comment by shtefcs** [comment]
Also, it would be best that **convert your theme to AMP** feature works. It never worked for me, i tested on few projects, all I get is blank white page. 

This would save me lot of time by not needing to rebuild new theme in AMP from scratch to match original store design.

**Comment by beingsmart3** [comment]
@shtefcs I've replied to your previous email please check and Contact me directly on team@magazine3.com

**Comment by shtefcs** [comment]
I sent you email, but I am not sure why you don't wanna keep conversation here? It should be helpful so other people having some questions, problems, getting lost can see and find it. And you can point people to this issues, in case resolved they can find solution.

**Comment by shtefcs** [comment]
> @shtefcs I've replied to your previous email please check and Contact me directly on [team@magazine3.com](mailto:team@magazine3.com)

Btw, those two issues i opened are different. 

Here I suggest the features for AMP Page Builder and WooCommerce, which you should consider extend it.

**Comment by Zabi09** [comment]
@shtefcs 
One of our team member 'Meraj Ali' was working on your issue and will you please tell us whether all your issues have been fixed or not?

And we have created the option for the users also to request their modules in their page builders so that we can make it compatible in AMP and you can also request for more modules on  - https://prnt.sc/lo06tm
https://ampforwp.com/page-builder-compatibility-for-amp/

**Comment by shtefcs** [comment]
Thanks for a 5 day response buddy .... 

Lets see what you will do and will this be another promise like last time your founder did, where he said will push the changes in next updated for one of the old issues, which actually ended after month and more and after  who knows how many updates.

**Comment by Zabi09** [comment]
@shtefcs 

Sorry for the inconvenience and yes currently some of the components are not rendering in AMP and we will make those components compatible for you and we need your feedback on your experience after using our AMP page builder extension and I promise you that we will make the compatibility for you and even give you the deadline for it.

Will you please get in touch with us on skype and we will have a call and we will understand your use case and will help you in setting it up and my skype id is "matt.kaludi"

**Comment by shtefcs** [comment]
Thanks for that message @Zabi09 . Its looks really promising and I am happy to work with you guys on that and provide you feedback.

I am adding you on Skype now.

**Comment by ahmedkaludi** [comment]
@shtefcs You had some custom Woocommerce modules and integrations which will be fixed with the AMP WooCommerce Pro updates. 

As far as the Core AMPforWP Github repo is concerned, this ticket does not have a valid bug or issue. 

Kindly reach out to our tech team via https://ampforwp.com/support.

**Comment by shtefcs** [comment]
> @shtefcs You had some custom Woocommerce modules and integrations which will be fixed with the AMP WooCommerce Pro updates.
> 
> As far as the Core AMPforWP Github repo is concerned, this ticket does not have a valid bug or issue.
> 
> Kindly reach out to our tech team via https://ampforwp.com/support.

Thanks for letting me know Ahmed. Do you know when the *WooCommerce Pro* Updates are coming?

Peace,
