### ISSUE TITLE
Polishing after 0.9

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/Accelerated-Mobile-Pages#269]
**Design Two:** 

- [x] Next- Prev- Article not correct linked/ lead to error page
- [x] Click on logo leads to AMP front page even if selected “Custom AMP front page = OFF"

- [x] Next- Prev- Article not deselectable anymore

- [x] Tags link link to AMP-version of archive pages even if selected “Hide AMP on Archive Pages”

- [x] Footer Ad gets covered by Sticky Social Icons (a little bit more scrolling down would be good, ok with design one)
- [x] Featured image caption missing (already reported in #263)

**Design One:**

- [x] How to remove “Powered by WordPress”?
- [x] Related article excerpt sometimes a little bit too long (jumps below the image)
- [x] Click on left logo leads to strange AMP version of the front page (selected “Custom AMP front page = OFF”)

- [x] No tags available

- [x] Bullseye logo on the right side leads correct to front page but the logo itself is totally squeezed

- [x] Date translation is incorrect. (German)

**REF:**https://wordpress.org/support/topic/issues-open-points-v-0-9/

**Comment by khaledMohammed000** [comment]
@MohammedKaludi 

Please do the following 👍 

1. Footer Ad gets covered by Sticky Social Icons (a little bit more scrolling down would be good, ok with design one)

2. Featured image caption missing (already reported in #263)

**Comment by ahmedkaludi** [comment]
Done and dusted.
