### ISSUE TITLE
How to use WPBakery builder with AMP?

### ISSUE THREAD

**Issue by shtefcs** [ahmedkaludi/accelerated-mobile-pages#2690]
Guys, I am really confused on how to use WPBakery builder with your AMP plugin? I downloaded plugins, have license for all extension, but not sure how to use it.

Am I actually using WPBakery Page Builder https://i.imgur.com/iRbacWL.png or AMP Builder (which I don't know where/how its related to WPBakery).

Please guide on this, since there is no single showcase in docs and videos on how to actually and exactly use with WPBakery.

You just mentioned its compatible, which does not show how to use. And you should be aware the people using your plugin first time can get reallllly lost and confused cause of the bad UX, hierarchy and lack of documentation, examples and videos.

Don't get me wrong, I am not here to objurgate on you , but just trying to give you real feedback from real user lost in action.

I consider myself as heavy tech user with 12+ hardcore years of experience, but somehow I managed get lost with your plugin multiple times.

If you managed to make that good BFCM promo page and all that stuff, I believe you can put more efforts in creating more materials, guides, tutorials, videos, examples, demos. 

Peace,

**Comment by beingsmart3** [comment]
@shtefcs 

Hi, I would like to clarify that our AMPforwp plugin and WP Bakery Page builder is compatible and it renders the content automatically you need not to use our AMP page builder unless you want to redesign for AMP pages.

If you are facing any other issues while implementing the AMP on your website then you can contact me directly on team@magazine3.com

I will personally make sure that your issues get resolved immediately.

**Comment by shtefcs** [comment]
Hi @beingsmart3. Thanks for the quick replay. 

Honestly I am still not sure what you mean. I think you guys really need to create some video/post about specific feature and show all this multiple way using it.

Again, I am not sure are you saying that if I use [this](https://i.imgur.com/nIglaJK.png) or [this](https://i.imgur.com/ysKjj6J.png) it will be rendered as AMP page ?

**Comment by Zabi09** [comment]
@shtefcs We have the list of modules on this page - https://prnt.sc/lo09fs and all these modules will automatically render in AMP and you no need to do anything and you just need to download and install the page builder plugin from here - https://ampforwp.com/page-builder-compatibility-for-amp/ and all these modules which are listed are rendered in AMP as well without doing anything.

Have you set up all these things and still you are facing issues? and thank you for your feedback on the tutorial of AMP page builder and I have also contacted the team and there are making the documentation for it.

Please let me know and I will do everything to fix your issues.

**Comment by shtefcs** [comment]
>all these modules will automatically render in AMP and you no need to do anything and you just need to download and install the page builder plugin

Well, I thought it was like that but that is actually not true. We need to do re-write complete website CSS since your plugins created an mess with our theme.

You guys are missing some basic components like **Testimonials, Team Members, etc**.

We opened issue yesterday and still waiting for your response. https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2696

**Comment by Zabi09** [comment]
Will you please get in touch with us on skype and we will have a call and we will understand your use case and will help you in setting it up and my skype id is "matt.kaludi"

**Comment by shtefcs** [comment]
Sure @Zabi09 adding you.
