### ISSUE TITLE
Advertisement section Ads are not working through Google search result

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2693]
Ref:   https://secure.helpscout.net/conversation/712900374/41306?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
This Ticket is such a waste of time.

**Comment by ahmedkaludi** [comment]
- [ ] responsive container

- [ ] data loading stratergy = 1

**Comment by Zabi09** [comment]
The responsive container has fixed in #2531

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Before merging this, we have to first merge this ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3142
