### ISSUE TITLE
Images are stretched whenever Convert AMP to WP theme (Beta) Option is enabled.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2694]
Reference:
https://secure.helpscout.net/conversation/690864360/38119/

Whenever a user is uploading images in WP Editor and enables the Convert AMP to WP theme (Beta) Option then all the images are stretched(without this option it works properly).

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
