### ISSUE TITLE
testimonials component using amp-carousel

### ISSUE THREAD

**Issue by jelenajjo** [ahmedkaludi/accelerated-mobile-pages#2696]
I want to add testimonials component on my site, and I thought that using [this amp-carousel](https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/) would be a good fit for that. Of course, if you have better idea, I am open for suggestions. :+1: 

However, I have hard time to understand how to implement this and any guidance will be really helpful! Basically if you have tutorial or some documentation on how to implement any of those components from **ampbyexample** site. I couldn't find any proper guide and I am pretty much lost at this point.

Thanks in advance!

**Comment by shtefcs** [comment]
Let me add up. 

The problem here is that we bought AMP premium packages expecting it gonna work with WPBakery Builder, but instead the elements from Bakery is **chaos**. 

Not any of sliding elements is working like Testimonials, Instagram widget. 

Not sure how you guys mean this is ready and working for WooCommerce, when its apparently not?

**Comment by Zabi09** [comment]
@jelenajjo 

If you create the image gallery in the non-amp version then it will automatically render in AMP as well and if you want it to appear only in AMP then you need to enable the AMP page builder and then you need to add the gallery module - https://prnt.sc/lpcagr and that's it you no need to worry about the code and all.

Hope it helps and if you have any questions then feel free to ask.

**Comment by Zabi09** [comment]
@jelenajjo 
Currently, we only have one layout for the testimonials that is - https://monosnap.com/file/mebWwX4N3BmzZ3kXbLKTFjxokJ1Uj2 and we are working to implement the testimonials like that carousel also,

**Comment by shtefcs** [comment]
@Zabi09 its inappropriate , cause we need carousel

**Comment by Zabi09** [comment]
@shtefcs Our team is working on adding the carousel for testimonials on your request and it will be added very soon and the code will be added on this ticket only.

**Comment by Zabi09** [comment]
@jelenajjo 

If you want the amp-carousel for the testimonials then you can use that with the help of our AMP theme framework and also I just want to know whether are you working on the same project with @shtefcs ? because we have discussed this on skype. 

Please let us know,

**Comment by shtefcs** [comment]
hey @Zabi09 yes we are working on same project.

**Comment by Zabi09** [comment]
Okay then we are development team and I am closing this ticket but you can continue your discussed with Ahmed on skype
