### ISSUE TITLE
Exclude categories - excluding all posts

### ISSUE THREAD

**Issue by TomLeeMS** [ahmedkaludi/accelerated-mobile-pages#2698]
Hi ...
I'm wondering if its corect to exclude all posts if it will appear in one of selected category to exclude...

If i will have post in 2 categories like "newest" and "movies"  and i'll exclude category "movies" (couse i want to show all post from "newest") ... than my post will not appear... :/

Any idea how to resolve this?

**Comment by Zabi09** [comment]
@TomLeeMS 

Yes, you can exclude the AMP from the specific category if you don't want AMP for that and to do that you just need to go to "Hide AMP Bulk Tools" and select that category - https://prnt.sc/lpbq0y and AMP will be removed from that.

And if you have any issues then let me know.

**Comment by TomLeeMS** [comment]
Hi…


I cannot see any category to hide AMP:

**Comment by MARQAS** [comment]
Hi @TomLeeMS, can you contact us at team@magazine3.com? Our team will personally look into it and will resolve it for you.

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22

**Comment by TomLeeMS** [comment]
Thank you very munch!

**Comment by TomLeeMS** [comment]
Still no categories to choose:

**Comment by MARQAS** [comment]
Hi @TomLeeMS, I apologize for the inconvenience. This has not been resolved yet. My colleague confused this one with other ticket.

**Comment by TomLeeMS** [comment]
oh…. i see

**Comment by MARQAS** [comment]
Can you please let me know more details about it? What I understood is, you got 2 categories on a single post ( for example movies and music) and you want to hide music category but due to that the post present in both categories is also getting hide, am I right?
If not can you please explain me more about it?

**Comment by TomLeeMS** [comment]
Yep you understand it right! :)

**Comment by MARQAS** [comment]
Even if I try to resolve it, what if you have a post in both categories but you want to hide it?

**Comment by TomLeeMS** [comment]
Let me think ...

**Comment by TomLeeMS** [comment]
many it will be easier when you select „distinct” posts from specified categories only… ???


Show only posts in categories 1, 45, 33, and select unique… ?

**Comment by MARQAS** [comment]
Yes, we already have that option, you can select the category which you want to hide from Hide AMP Bulk Tools, and then enable the post which you want to show. We have the option for individual posts as well, can you please try like this and let me know?

**Comment by TomLeeMS** [comment]
ok but i can’t see categories anyway….

**Comment by MARQAS** [comment]
Hi @TomLeeMS, sorry for the delayed response, where are you not seeing any categories?

**Comment by TomLeeMS** [comment]
in back office -> AMP -> Hide Amp Bulk Tools -> „select categories to hide"

**Comment by ahmedkaludi** [comment]
@TomLeeMS Please contact us on https://ampforwp.com/support/ so our Tech Team can help you fix this.
