### ISSUE TITLE
Table class is getting removed in AMP pages.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2699]
Table class is getting removed in AMP pages. 
Ref : https://secure.helpscout.net/conversation/719734344/43162/

**Comment by MohammedKaludi** [comment]
Delete the unused code
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/160114b3d712615a030d34d27a563971609989c4#diff-6aa5512f7dd8d5ce60fc97b0f340912cR621

**Comment by MohammedKaludi** [comment]
:+1: code will be pushed in 0.9.97.22

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
