### ISSUE TITLE
$this object for design 1,2,3  is not properly working for single content

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2700]
I'm using the amp gravity form plugin with dynamic populating feature and it's working for swift theme. Due to $this object in design 1,2,3 that feature is not working.

ref: https://secure.helpscout.net/conversation/676426850/36103?folderId=2169248
> https://trello.com/c/bpLMRA7X/416-conditional-logics-of-gravity-form-using-dynamic-populating-via-shortcode-is-not-working-in-design-123

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
