### ISSUE TITLE
Custom front page Meta description and content are not rendering for ALL in SEO plugin.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2702]
Desc: Custom front page Meta description and content are not rendering for ALL in SEO plugin.
Ref: https://secure.helpscout.net/conversation/720724936/43333?folderId=2169248

**Comment by MohammedKaludi** [comment]
:+1: this will be pushed in 0.9.97.24

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
