### ISSUE TITLE
Remove the span tag in all 404.php files of the 4 designs.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2704]
Ref: https://secure.helpscout.net/conversation/628369315/30965?folderId=2206768

Screenshot: http://take.ms/khhI9

**Comment by Frenchomatic** [comment]
Take out the h1 or everything gets that html regardless of the html you put into the admin box for content. 

see the end of this #2671

**Comment by MohammedKaludi** [comment]
:+1: added in master and will be pushed in 0.9.97.22

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22

**Comment by Frenchomatic** [comment]
This is still wrong - why put everything within `<h2 class="amp-wp-title">` .  In addition, whatever I put in the admin box for the page title doesn't display either. 

```
**<h2 class="amp-wp-title">**
			<?php global $redux_builder_amp; 
			$allowed_tags = '<p><a><b><strong><i><u><ul><ol><li><h1><h2><h3><h4><h5><h6><table><tr><th><td><em><span>';
			echo strip_tags(ampforwp_translation($redux_builder_amp['amp-translator-fourohfour'],'Oops! That page can’t be found.'),$allowed_tags); ?>
            **</h2>**
			<?php do_action('ampforwp_post_after_design_elements') ?>
```

The output is this

<article class="amp-wp-content the_content"> <h2 class="amp-wp-title"> </h2><h1>Error 404</h1>The page you are looking for no longer exists. Perhaps you can return back to the site's <a href="http://www.mydomain.com/">homepage</a> and see if you can find what you are looking for.  </article>
