### ISSUE TITLE
Unable to update posts and access meta boxes in Gutenberg edit posts (in beta).

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2705]
In posts if we click on update, then the page is just loading, hence unable to access other meta boxes in edit posts (in beta).
Ref : https://secure.helpscout.net/conversation/707636496/40309?folderId=2322652

**Comment by MohammedKaludi** [comment]
:+1: can be pushed into master

**Comment by Zabi09** [comment]
This issue is properly fixed in #2725 so we can directly close it
