### ISSUE TITLE
The gutenberg button doesn't work in amp

### ISSUE THREAD

**Issue by dev-indonesiamicrosystem** [ahmedkaludi/accelerated-mobile-pages#2707]
The gutenberg button doesn't work on amp. The button only appears in text mode but not in button visual

**Comment by Zabi09** [comment]
@dev-indonesiamicrosystem 
We are going to add the compatibility for all the modules of Gutenberg in this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2719

And in the meantime, you can go to AMP => Design => Global => add the Custom CSS code for those buttons.

**Comment by Zabi09** [comment]
I was not adding the link for the button and due to that, it was not working.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31
