### ISSUE TITLE
Related posts and Recent posts on custom posts types

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2708]
More info - https://wordpress.org/support/topic/related-post-only-custom-post-type/

**Comment by pegazee** [comment]
Working as expected.

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by syedimran22** [comment]
@pegazee related post are not rendering in design1,2,3.

**Comment by pegazee** [comment]
I've checked on my end, Related posts are working in all designs. @syedimran22  check again on your end.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
