### ISSUE TITLE
Export option of page builder is not working in latest version

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2709]
In the latest version, the export option of AMP page builder is not working because of & i.e esc_url

if we remove esc_url then it's working: http://take.ms/vn8m8

**Comment by MohammedKaludi** [comment]
:+1: added in master and it will be pushed in 0.9.97.22

**Comment by HANEEFRIYAZ** [comment]
pushed in 0.9.97.22
