### ISSUE TITLE
TGMPA improvements

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#271]
**jrf:** When I originally responded, I’d done a search on the GH repo and did not find a function hooked into the tgmpa_register action, so to me, it looks like you forgot to execute step 4 of the installation procedure for TGMPA.

When you downloaded TGMPA, it came with an example.php file which shows an example implementation of step 4. The hook-in and the related function don’t have to be in a separate file, but should be somewhere in your codebase, otherwise TGMPA does not know what to do.
For more detailed information on the options available and how to provide them to TGMPA, please have a look at the configuration help page.

On a separate note – I also looked at the code in SVN/trac here on wordpress.org and found some oddities with duplicate files and such, but that is probably unrelated to this issue.

**REF** https://wordpress.org/support/topic/parent-plugin-url-access-denied/

**Comment by curious-jim** [comment]
any updates on this?

**Comment by khaledMohammed000** [comment]
@curious-jim We have removed TGMPA completely and have solved the same issue from scratch 👍 now you wont be getting any issues with our plugin and TGMPA
