### ISSUE TITLE
Rewrite ampforwp_view_nonamp function

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2710]

**Comment by pegazee** [comment]
1. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bd1da14b81377bc6d1292a412c1394ad022edbd4#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3312

2. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bd1da14b81377bc6d1292a412c1394ad022edbd4#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3335

3.https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bd1da14b81377bc6d1292a412c1394ad022edbd4#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3339

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to push.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
