### ISSUE TITLE
Need full excerpt length in single posts

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2712]
https://wordpress.org/support/topic/excerpt-unnecessarily-cut/

**Comment by MARQAS** [comment]
Excerpt is not working. And why it is not connected to an option?
It can break the design if the excerpt is very long.

**Comment by Zabi09** [comment]
The issue was coming due to some other ticket but it is fixed now, Please check now.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.38
