### ISSUE TITLE
Need some basic amp components to work in the content

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2713]
Need some of the amp-components to work in the content like - 
amp-accordion
amp-carousel etc

**Comment by MARQAS** [comment]
Working perfectly in Master, Custom AMP Editor is not working properly in Beta when AMP components are added into it. unable to find the reason. 
Any reason you may know of @MohammedKaludi?

**Comment by MohammedKaludi** [comment]
Due to black list sanitizer, because ajeet built allowed tags sanitizer and that is not connected with custom amp editor?

**Comment by MARQAS** [comment]
AMP components are working very fine, the only issue I found while working on this ticket was the issue with Custom AMP editor. But it is due to this ticket #801, so I am adding a dependency to it.

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by cvlab** [comment]
There are missing attributes `animate` and `expanded` for **amp-accordion** https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/7b4283798daabd0508b7e81c4ac2133fba3a7b7b/includes/vendor/amp/includes/sanitizers/class-amp-allowed-tags-generated.php#L114 Attributes

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
