### ISSUE TITLE
Creating a Custom Template for Frontpage & Home page is not working.

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2714]
user want to override the Frontpage & homepage of AMP by creating the custom template in AMP Theme Framework but it's not working.
https://www.silverthorneattorneys.com/bicycle-accident/

**Comment by pegazee** [comment]
** Review **

- [ ] Talha

- [ ] Imran

- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
