### ISSUE TITLE
Reviews option in plugins page

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2715]
like - https://prnt.sc/lqwxf2

**Comment by ahmedkaludi** [comment]
**REVIEW:**

- [ ] Talha

- [ ] Imran 

- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
Explained to zabi ajeet and azeem about why the ticket got failed in review

**Comment by pegazee** [comment]
REVIEW:

- [ ] Talha

- [ ] Imran

- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
