### ISSUE TITLE
When added the background video in the page builder the markup is not coming properly.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2716]
Ref: https://secure.helpscout.net/conversation/724405942/43953?folderId=1060551
Ref: https://secure.helpscout.net/conversation/724450206/43957?folderId=1060556

screenshot: http://take.ms/d8y1N
screenshot: http://take.ms/7Twb4

**Comment by MARQAS** [comment]
The video is loading in amp-iframe so it can't be loaded within the first 75% of the viewport.

**Comment by pegazee** [comment]
** REVIEW **

- [ ] Talha

- [ ] Imran 

- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1f4529dd5a2b26f52fc633b8e4b640cd9301f3a1#diff-1a22e45a9ee4bfe1e933fb1936074cb3R434 

Label should be translatable

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
