### ISSUE TITLE
Serialization problem with AMP settings data.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2717]
Serialization problem with Accelerated Mobile Pages settings data.
Ref : https://secure.helpscout.net/conversation/723858763/43858?folderId=2322652

**Comment by MARQAS** [comment]
Unable to recreate the issue. 
Settings are getting saved without any issues. 
Contacted the user, waiting for his reply

**Comment by pegazee** [comment]
** REVIEW **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.23
