### ISSUE TITLE
Levelup Compatability

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2718]
- [x] Create a condition called if_is_levelup{} which detects if the levelup theme is active
- [x] Create a condition called if_levelup_has_builder{} which detects if the levelup theme is active and the Elementor is enabled
- [ ]  Elementor full width support..
NON-AMP: http://take.ms/ojlAr
AMP:  http://take.ms/HqrEn
Let's make them look the same. 

- [ ] Create a page which does not have a Elementor enabled, yet it tries to get that current post's css and add it in the source: http://take.ms/tEQ1U

- [x] List of Tasks in AMP
1.poppins font family need to remove on condition in levelup.
2.Header and footer markup and css need to remove if levelup is active
3.Markup of breadcrumbs, comments, title and css need to remove, if levelup is active.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ]

**Comment by MohammedKaludi** [comment]
Incorrect function name 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/586422c6b48ebae78d6223e197a85afc39f064d5#diff-2ae5550e31f40c1962ca69d373af6b93R3

Improve the check
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6fe14d7a39f1be5bd0f8afc8acab1524a2090e85#diff-cf7375f9a9abbfe99507b5389df317acR5

**Comment by MohammedKaludi** [comment]
- [ ] why removed core condition?
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a981d701e89a46319a3291ac9b55c6cfa8c0a970#diff-18e7a4ed2f3df1181e013bcc7fbdd406R5

- [ ]  use better function name `levelup_check_hf_builder`

- [ ] use wp_get_theme in a better way and only call when it is required, this will improve the performance 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8dccdafb763b6d751c6d321c7ed536a32e68f00c#diff-2ae5550e31f40c1962ca69d373af6b93R20

- [ ] escaping is missing
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8dccdafb763b6d751c6d321c7ed536a32e68f00c#diff-2ae5550e31f40c1962ca69d373af6b93R24

**Comment by MohammedKaludi** [comment]
- [ ] room for improvement
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4d526ea57c4dbff44897410de333be14070d098a#diff-2ae5550e31f40c1962ca69d373af6b93R60

and same here
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8dccdafb763b6d751c6d321c7ed536a32e68f00c#diff-2ae5550e31f40c1962ca69d373af6b93R60

we can create a global function that checks everything and justs sends the boolean value, this will help us and other who will develop themes/plugins in the long run.

**Comment by ajeetku** [comment]
change in condition 314c3b1

**Comment by MohammedKaludi** [comment]
:+1: can be merged now.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.35
