### ISSUE TITLE
The content/text with any other colour also showing the black/grey

### ISSUE THREAD

**Issue by iamrahulsethi** [ahmedkaludi/Accelerated-Mobile-Pages#272]
I am facing many issues with AMPforWP plugin.

1. The Meta title for the homepage is the title of the recent post.
2. Whatsapp share is showing error- Failed to share
3. The content/text with any other colour also showing the black/grey.

blogs are

https://educationbhaskar.com
https://brutallyhonest.in

**Comment by khaledMohammed000** [comment]
@iamrahulsethi Thanx for Pointing it out Rahul

1. I have solved here https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/6cf52d072890d8e3c3d140038ae70fc5af97cc0f

2. I need to check and will fix it if this is an Issue 👍

3. I need to check and will fix it if this is an Issue 👍

**Comment by khaledMohammed000** [comment]
2. fixed here : https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/bbbe1392ff19d609e3c5ef63a3a9d0bf51cfe239
