### ISSUE TITLE
BlogPost Rating In Featured Snippet

### ISSUE THREAD

**Issue by HANEEFRIYAZ** [ahmedkaludi/accelerated-mobile-pages#2720]
Hi,
We are in the process of adding blogpost rating as per a customers request and will be released in the near future.
We will let you know if there is any help needed.

Thanks!!

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/schema-and-structured-data-for-wp #82](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/82) via [**ZenHub**](https://www.zenhub.com/)
