### ISSUE TITLE
When the Mobile Redirection option is enabled then the fr is removed from the URL.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2721]
Ref: https://secure.helpscout.net/conversation/724055282/43887?folderId=2206768

**Comment by MARQAS** [comment]
The homepage is getting redirect to some other page and single is getting stuck in the loop of redirects.

**Comment by MARQAS** [comment]
Working as expected

**Comment by pegazee** [comment]
** REVIEW **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1: ready

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.32
