### ISSUE TITLE
Reset all & Reset section are not working.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2722]
Reset Reset all & Reset sections are not deleting the data and not resetting to default.

**Comment by MARQAS** [comment]
Working as expected, tested on several systems. 
This issue is only coming to @Rkroy. Maybe due to some issues on his server?
@Rkroy please let us know when you tested it on another system of yours

**Comment by MohammedKaludi** [comment]
@marqas Ravi was able to recreate the issue on his localhost, please contact him he will explain you the issue

**Comment by Rkroy** [comment]
There was some issue with my WordPress, when i installed other WordPress and tested it, it started working, now reset functionalities are working perfectly at my end.

**Comment by MARQAS** [comment]
We can close this ticket

**Comment by ajeetku** [comment]
When reset section/All there is need some alert to confirm action with user

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master, good job @ajeetku and @pegazee on this ticket.

**Comment by MARQAS** [comment]
It's already working in master, the issue was in Beta only.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28
