### ISSUE TITLE
Ads upgrade

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2724]
Withs adsforwp

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] imran

**Comment by beingsmart3** [comment]
Need to Add the "New" tag on Advertisement option
http://take.ms/xySOm

**Comment by pegazee** [comment]
- [ ] need to move the box on the right

- [ ] need to update the message

- [ ] no relatd with the advanced amp ads banner

**Comment by ahmedkaludi** [comment]
We will push #2902 with this one as well

**Comment by MARQAS** [comment]
Escaping? 
example: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a15bd75aec5ca46f690cea19b335c169fef87326#diff-d794f55e3ee0aead59adf8c61f67f9edR520

**Comment by pegazee** [comment]
Getting blank space After the "Advertisement Positions" accordion and "Ad Performance" accordion.

Screenshot: https://take.ms/lYKNA

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by syedimran22** [comment]
When ads for wp plugin is activated need to show a message that ads for wp plugin is active so that ads will be served not the below ads.

Also, remove the box on the right which will show ads for wp upgrade message.

**Comment by pegazee** [comment]
Pushed in 0.9.97.44.1
