### ISSUE TITLE
Improve coding in amp-page-builder.php

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2725]
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/pagebuilder/amp-page-builder.php

**Comment by beingsmart3** [comment]
** REVIEW **

- [ ]  Kaleem

- [ ]  Talha

**Comment by MohammedKaludi** [comment]
:+1: looks good. Can be merged into master and this ticket will be pushed in 0.9.97.23

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.23
