### ISSUE TITLE
Whenever Convert AMP to WP theme (Beta) option is enabled Logo Image is being stretched.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2726]
the resize Option is also not working when Convert AMP to WP theme (Beta) option is enabled

**Comment by pegazee** [comment]
** REVIEW **
- [ ] Talha

- [ ] Imran 

- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.23
