### ISSUE TITLE
Need to create an option for Id's for all the modules and column in AMP Page builder.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2730]
Need to create an option for Id's for all the modules and column in AMP Page builder.
Ref : https://secure.helpscout.net/conversation/728322457/44637?folderId=2322652

**Comment by MARQAS** [comment]
Can we delete the old modules @ajeetku @MohammedKaludi

**Comment by pegazee** [comment]
** review **

- [ ] kaleem

- [ ] Imran

- [ ] talha

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31
