### ISSUE TITLE
Lightbox feature for Carousel

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2731]
Ref:   https://secure.helpscout.net/conversation/717252694/42428?folderId=1914712

**Comment by syedimran22** [comment]
** Review  **
- [ ] Imran 

- [ ] Kaleem

- [ ] Talha

**Comment by syedimran22** [comment]
Lightbox gallery Carousel is not working when Convert AMP to WP theme (Beta) is enabled.

**Comment by pegazee** [comment]
@syedimran22 We've already created a ticket here #2771

**Comment by MohammedKaludi** [comment]
:+1: this can be merge into master.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28
