### ISSUE TITLE
The Subtitle is not rendering using with Jannah theme.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2732]
Ref: https://secure.helpscout.net/conversation/721277232/43420?folderId=2206768

URL: https://www.glasbanjaluke.net/2018/11/28/dnevni-horoskop-za-29-novembar-2018-bik-nepovjerljiv-lavu-konacno-mirniji-poslovan-dan-jarac-u-novim-komplikacijama/

The Jannah theme is attached.

**Comment by MohammedKaludi** [comment]
dont use h2, use h4 unstead

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7cad5cd847348bd7e5d66871399eb18dc04d4a2a#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6823

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] talha

- [ ] imran

**Comment by MohammedKaludi** [comment]
Wrong escaping done.

**Comment by boyan-sharic** [comment]
Done for AMP?
What about FBIA?

**Comment by MohammedKaludi** [comment]
@boyan-sharic that will be added in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2746

Thank you for following up.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
