### ISSUE TITLE
Need to create an Option in AMP Pagebuilder where a user can provide Excerpt Length.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2733]
Reference:

https://secure.helpscout.net/conversation/713938475/41461?folderId=2090438

In Pagebuilder, with Category Module user needs an option wherein he can provide Excerpt Length.

For Example:
https://prnt.sc/ltvylq

**Comment by pegazee** [comment]
** REVIEW **

- [ ] Kaleem

- [ ] Talha

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
