### ISSUE TITLE
When Hide AMP Option is enabled in PageEditor with Convert AMP to WP theme (Beta) enabled it's providing output as AMP Page

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2735]
Reference:
https://secure.helpscout.net/conversation/690864360/38119/

If we enable Hide AMP Option with AMP takeover enabled it's hiding the AMP Version.
But if same done by keeping Convert AMP to WP theme (Beta) enabled it's displaying the AMP Version instead of hiding the AMP.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1: ready, @Zabi09 go ahead and merge it immediately

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
