### ISSUE TITLE
Allow amp-translator-non-amp-page-text transable for other plugins like wpml etc

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2737]
Users requested - 
In your main plugin, file "/templates/features.php"
Line 4276
You have echo esc_html( $redux_builder_amp['amp-translator-non-amp-page-text'] )
But should be
echo esc_html__( $redux_builder_amp['amp-translator-non-amp-page-text'], 'accelerated-mobile-pages' )
Without this change, we cannot change the value with WPML and other text in your plugin seem to have the "__" after the escaping.

https://secure.helpscout.net/conversation/729411751/44810?folderId=1914712

**Comment by fhfournier** [comment]
Thanks for opening my issue! Next time i will open the issue here :)

**Comment by MARQAS** [comment]
Thanks @fhfournier, yes you can open tickets here and we will be very glad if you contribute as well. 
:)

**Comment by pegazee** [comment]
** REVIEW **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1: this can be merged into master
nice work @MARQAS

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28
