### ISSUE TITLE
Properly Differentiate titles of 404 Error and Error 404 text box of amp translation panel.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2738]
Desc: Properly Differentiate titles of  404 Error and Error 404 text box of amp translation panel as user will be confused with those titles.

Screenshot: http://take.ms/QYhWy
http://take.ms/9B5qS

**Comment by pegazee** [comment]
** REVIEW **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
why the condition `is_404` is added if not used?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3ba1351625a3d05aeafe0e14b97077d56c2e1468#diff-d69695bf16addd334de42e22bef775c6R230

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
