### ISSUE TITLE
Need to add a filter $thumb_url_array, where users can modify thumbnail.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2739]
Need to add a filter $thumb_url_array, where users can modify thumbnail. 
Ref : https://secure.helpscout.net/conversation/718057420/42661/
Refer screenshot : 
![thumb_url](https://user-images.githubusercontent.com/43204388/49943876-0a778f00-ff0f-11e8-99c0-200ac18b5e54.png)

**Comment by ajeetku** [comment]
@Zabi09 If the user wants to change the cropping size of the image, then there is no filter for it.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.32
