### ISSUE TITLE
Design 1 with ad codes

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#274]
Would like to use design 1 but it doesn’t come with ad codes on it

**REF** https://wordpress.org/support/topic/ads-not-appearing-on-design-1/
http://www.thebudgetfashionista.com/?amp

**Comment by MohammedKaludi** [comment]
Add the ads and make sure all 4 ads are working in design 1.

**Comment by ahmedkaludi** [comment]
@MohammedKaludi @khaledMohammed000 Please update on these issues.

**Comment by ahmedkaludi** [comment]
Do we have the Ad codes in the design 1 ?

**Comment by khaledMohammed000** [comment]
In design 1

Ad#1 Works Perfectly fine
Ad#2 Works Perfectly fine
Ad#3 Works Perfectly fine
Ad#4 Works Perfectly fine
