### ISSUE TITLE
/amp Is getting added in the telephone link when we enabled Change Internal Links to AMP

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2742]
"Change Internal Links to AMP" you can see that the /amp/ is also added to all telephone links (tel:). and the telephone links are placed in  Button Module.

Issue recreated on the Local server.
http://take.ms/lL4un

Ref: https://secure.helpscout.net/conversation/731955262/45328?folderId=1060551

**Comment by ajeetku** [comment]
Use filter_var($string, FILTER_VALIDATE_URL) to validate a tag has contain link or not

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
when `wp_http_validate_url` function is used then this condition will break `strpos($url, "#")!==false`

you will need to add that check as well. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3dc9103d9b896f6d85508b1e768da7dbfbeacf1a#diff-1301281de287d2aed98746fc9ba777b4L427

to test create a jumplink like this: https://wordpress.org/plugins/accelerated-mobile-pages/#developers and it will append amp at the end.

**Comment by MARQAS** [comment]
I have tried and its working fine.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
