### ISSUE TITLE
Add an option for Font Display to Control Font Performance.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2743]
Add an option for Font Display to Control Font Performance.
Ref : https://developers.google.com/web/updates/2016/02/font-display

**Comment by pegazee** [comment]
** REVIEW **

- [ ] kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
