### ISSUE TITLE
if there's and apostrophe in the post title, it is published as random characters In twitter

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2744]
When I share a post to Twitter using the social share icon/s, if there's and apostrophe in the post title, it is published as random characters and doesn't look good.

Ref: https://secure.helpscout.net/conversation/732736508/45462?folderId=1060554

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
do you remember why we added `rawurlencode? And removing directly is not a soultion.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c7d0a4d6ade8836128bcfebd2423d82503a23544#diff-cf7375f9a9abbfe99507b5389df317acL69

**Comment by MohammedKaludi** [comment]
Test once with this 
http://www.codetable.net/decimal/8216
and 
http://www.codetable.net/decimal/8217

**Comment by MARQAS** [comment]
The solution which we have added for https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2264 is working fine for this as well, so will keep the code for now.

**Comment by MohammedKaludi** [comment]
> The solution which we have added for #2264 is working fine for this as well, so will keep the code for now.

then what about the original issue for which the ticket is created, apostrophe published as random characters In twitter ? 

Seems like we have circled back to the very beginning of the issue.

**Comment by MohammedKaludi** [comment]
not working properly with all the elements.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
