### ISSUE TITLE
Button Module color is not getting changed

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2745]
Button Module color is not getting changed In the Master and Beta as well.

Issue replicated in the local server.

**Comment by pegazee** [comment]
** REVIEW **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by beingsmart3** [comment]
On my end color is not getting changed

**Comment by MARQAS** [comment]
That is due to the wrong URL, button module runs through sanitizers and if the URL is not valid then it will not print it as an anchor tag. Please check the URL and try again @beingsmart3

**Comment by syedimran22** [comment]
Review

- [ ] Talha

- [ ] Imran

- [ ] Kaleem

**Comment by beingsmart3** [comment]
@MARQAS indeed it's working perfectly if we insert correct url

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31
