### ISSUE TITLE
The Subtitle is not rendering in the Facebook Instant Artical(FBIA) using of the Jannah Theme.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2746]
Ref: https://secure.helpscout.net/conversation/721277232/43420?folderId=2206768

The Jannah Theme Attached.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.38
