### ISSUE TITLE
The error message can not show when I post a empty comment

### ISSUE THREAD

**Issue by leftshine** [ahmedkaludi/accelerated-mobile-pages#2747]
The error message can not show when I post a empty comment.
I think there is some conflict with ajax

**Comment by ahmedkaludi** [comment]
@leftshine Can you please share the URL of your site?

**Comment by leftshine** [comment]
[https://8lhx.com/others/8lhx-gravatar/](https://8lhx.com/others/8lhx-gravatar/)
My website is not in English.
And now I have closed the AMP plugin.
Need I to open it again?

**Comment by RajuJeelaga** [comment]
@leftshine Yes please!

Kindly open the AMP so we can test and help you fix the issue.

**Comment by leftshine** [comment]
OK，I opened the AMP plugin. 
And you can visit this url：[https://8lhx.com/others/8lhx-gravatar/](https://8lhx.com/others/8lhx-gravatar/)

**Comment by Zabi09** [comment]
@leftshine Sorry for the delay in response and I have checked the URL which you have provided and it seems that you have not activated the AMP comment extension, Will you please enable the AMP comment and let us know and you can directly contact us on team@magazine3.com and our team will find the instant solution and you no need to wait like this.
