### ISSUE TITLE
Whenever an image inserted, has width="100%" and height="100%", its giving Validation error.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2748]
Reference:
https://secure.helpscout.net/conversation/730874054/45074?folderId=2090438

If we give the height and width in terms of px then it solves our concern.

**Comment by MohammedKaludi** [comment]
:+1: looks good, moving to testing department.

**Comment by MohammedKaludi** [comment]
:+1: ready, @Zabi09 go ahead and merge it immediately

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
