### ISSUE TITLE
The tag 'amp-iframe extension .js script' appears more than once in the document.

### ISSUE THREAD

**Issue by prkirby** [ahmedkaludi/accelerated-mobile-pages#2749]
Hello! 

After the most recent update, about 4,000 of our articles are showing this amp validation issue: 

`The tag 'amp-iframe extension .js script' appears more than once in the document.`

Here is one of the articles so you can check source code: https://doyouremember.com/15586/guess-grown-violet-beauregarde-blueberry

I see that the script is included twice, once with all of the other extension scripts, and once by itself near a bunch of script tags. I am using a custom theme (in its most basic form) via the amp-theme-framework-master, but I've done a regex search and we are not injecting any amp-extension scripts manually. 

Please let me know what I can do to help or explain the issue further, it is a new issue so we would love to get it snuffed out as soon as possible. 

As an aside, we are also using the advanced-amp-ads extension. 

Regards, 

Paul

**Comment by Zabi09** [comment]
@prkirby 

I have checked all our emails but unable to find your email. Have you contacted us on team@magazine3.com?

**Comment by Zabi09** [comment]
it was in the advanced settings options panel and now it is fixed so closing this ticket.
