### ISSUE TITLE
If twitter embed code is added then other blockquotes tag are not working

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2750]
More info - https://wordpress.org/support/topic/problem-blockquote-tags-and-embed-twits/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ] Talha

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Talha

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
