### ISSUE TITLE
Swift Hover Color Changes

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2751]
Swift/Style.php has 
a:hover, a:active, a:focus{}

This is incorrect, Consult with @ahmedkaludi and correct it.

**Comment by MohammedKaludi** [comment]
escaping missing and use `ampforwp_get_settings()`

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: as @ajeetku mentioned in the comments, sanitize the color code with `ampforwp_sanitize_color` while merging into master

**Comment by MohammedKaludi** [comment]
sanitizing is missing here: https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/design-1/style.php#L58

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/swift/style.php#L74 and others

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.97.33, closing the ticket.
