### ISSUE TITLE
Swift Homepage Blog CSS is loading on the custom frontpage

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2754]
Swift Homepage Blog CSS is loading on the custom frontpage

http://take.ms/yj3rm

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

- [ ] Talha

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28
