### ISSUE TITLE
Comments Issues

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2755]
Design = Swift
Custom Frontpage = Yes
Editor = WP Editor
Comments Enabled in the WP (http://take.ms/Jz0st) = Yes
Behavior: Comments are not displaying

- [x] Comments should load when the comments are enabled

- [x] If the comments are off then markup and it's css should not load.

Consult with @ahmedkaludi for more information.

**Comment by pegazee** [comment]
** Review **

- [ ] Imran

- [ ] Kaleem

- [ ] Talha

**Comment by beingsmart3** [comment]
I don't know what went wrong, but know it's working fine.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31
