### ISSUE TITLE
ampforwp_wc_shortcode_title is loading globally, why?

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2756]
.ampforwp_wc_shortcode_title{
	margin-top: 12px;
    display: inline-block;
}
.ampforwp_wc_shortcode_excerpt{
	font-size:15px;
	line-height:1.4;
}

please consult with @ahmedkaludi for more details.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
removing is not an option, need to load conditionally, as we are using it in category-widget, this  will break the css of the page if the widget is loaded

**Comment by MARQAS** [comment]
We are not using that widget for Swift, that's why I removed its CSS from Swift styling.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.36
