### ISSUE TITLE
Sidebar CSS should only load if the Sidebar markup is loading

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2757]
/*** Sidebar CSS ***/
  .sdbr-right{

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

- [ ] talha

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
No sidebar is loading on Pages, even after enabling it from the options panel.

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.97.33, closing the ticket.
