### ISSUE TITLE
Ads CSS is loading even though the ads are not enabled

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2758]
Options panel has all the ads disabled: http://take.ms/IaAwU

The source has this css on every page: 
.amp-ad-wrapper{width:100%;text-align:center;}
.amp-ad-wrapper span { display: inherit; font-size: 12px; line-height: 1;}
.amp-ad-wrapper {margin-top: 10px; margin-bottom: 10px}

**Comment by pegazee** [comment]
** Review **

- [ ] Talha

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: this can be merged into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28
