### ISSUE TITLE
Plugins Upgrade code in Beta

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2759]
The code of plugins upgrade(PWA and Schema) is not present or having an older version in Beta. 
Need to update/add the code in Beta

**Comment by pegazee** [comment]
** REVIEW **

- [ ] kaleem

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
is this required? @MARQAS and @ahmedkaludi need to discuss this ticket.

**Comment by MARQAS** [comment]
Previously, We have added the code in Master but not in Beta, so I added the same newest code in beta. 
Closing this ticket.
