### ISSUE TITLE
AMP for WC recheck with new codebase

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#276]
https://wordpress.org/plugins/amp-woocommerce/

**Comment by kevin25** [comment]
How to know if it works for WooCommerce?

**Comment by khaledMohammed000** [comment]
@kevin25 gimme some time this will start working very soon 👍

**Comment by kevin25** [comment]
Thank you. Please make it work with variant products and show the Add To Cart.

**Comment by khaledMohammed000** [comment]
Please be patient , its already on my list , will try to fix it ASAP 👍
