### ISSUE TITLE
In Search Console Crawl Errors ?nonamp=1/ is listed in Access denied 

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2760]
In Search Console Crawl Errors ?nonamp=1/ is listed in Access denied 
Ref :: https://secure.helpscout.net/conversation/728267001/44624?folderId=2322652

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] talha

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by jwbats** [comment]
Search console says that this crawl issue is caused by an error on their side, that it is solved and that the issue will disappear in a few days.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.29
