### ISSUE TITLE
Need to add amp endpoint filter

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2761]
Need to add amp endpoint filter "ampforwp_is_amp_endpoint"

**Comment by ajeetku** [comment]
Inside this function "ampforwp_is_amp_endpoint" need to add filter before return in  else part
		`return #apply_filters('ampforwp_is_amp_endpoint', false !== get_query_var( 'amp', false ) );`

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

- [ ] Talha

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
