### ISSUE TITLE
Urgent Performance issue

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2762]
Ref: https://secure.helpscout.net/conversation/735911014/46098/

**Comment by Zabi09** [comment]
Added #2502 and #2685 in this ticket

**Comment by MARQAS** [comment]
@Zabi09 please restrict the categories and tags to 500.

**Comment by ajeetku** [comment]
@Zabi09  Cannot use directly get of post inside query before passing it to filter. So first filter users data after that use it.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
