### ISSUE TITLE
When Convert AMP to WP theme (Beta) is enabled GDPR popup isn't closing

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2763]
Reference:
https://secure.helpscout.net/conversation/690864360/38119?folderId=2090438

https://newsite.totalconnect.it/wp/

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8be422a6cb818e5541b398fe19bc134322c54c13#diff-1301281de287d2aed98746fc9ba777b4R62

prefix missing `getCookie`

**Comment by pegazee** [comment]
-> Zabi just committed the code and removed the console.log();
-> Moving this ticket to next pipeline.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
