### ISSUE TITLE
Need to add like & share feature for every image in instant_articles

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2764]
Desc: Need to add like & share feature for every image and video in instant_articles

Ref: https://secure.helpscout.net/conversation/732127907/45361?folderId=2169248

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
pushed in 0.9.97.44
