### ISSUE TITLE
Posts are not full width in AMP pagebuilder

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2765]
In a page (full width): https://imgur.com/PzwQ2tl
In a post (not full width): https://imgur.com/JII8cAZ

**Comment by drducmanh** [comment]
I have upgraded plugin to version 0.9.97.24, but the post using amp page builder still not full width. I am using swift theme.

**Comment by MohammedKaludi** [comment]
Hello @drducmanh,

This ticket is still under development and not yet pushed in 0.9.97.24 this will be pushed in future updates.

You can check here https://wordpress.org/plugins/accelerated-mobile-pages/#developers#changelog-header which tickets got pushed in the last update.

**Comment by drducmanh** [comment]
Thank you for reply! I hope it'll be fixed soon.

**Comment by MohammedKaludi** [comment]
> Thank you for reply! I hope it'll be fixed soon.

Yes, it has been fixed and we are planning to push it in 0.9.97.26

**Comment by drducmanh** [comment]
> > Thank you for reply! I hope it'll be fixed soon.
> 
> Yes, it has been fixed and we are planning to push it in 0.9.97.26

I've upgraded plugin to version 0.9.97.27, but it doesn't fixed

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:  can be merge into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28
