### ISSUE TITLE
Drop down support in Alternative Menu in Mobile view.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2768]
Drop down support in Alternative Menu in Mobile view.
Ref : https://secure.helpscout.net/conversation/740259133/47122?folderId=2322652

**Comment by RajuJeelaga** [comment]
After discussion with @ahmedkaludi
Drop down menu with scroll bar in mobile is not possible in AMP,
But we have an option to do that, like an experimental with light box,
https://monosnap.com/file/oaEQHtcEqTTj75yM26z1Ckr2BCorQf
on click menu, light box will open and sub menu will display in the light box.

**Comment by MohammedKaludi** [comment]
Dropdown menu positining is not correct if the bigger logo is added.

**Comment by MohammedKaludi** [comment]
There should the dropdown when Hover in Big Screens and Click on Smaller Screens.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
