### ISSUE TITLE
Yoast Custom Description for AMP page 

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/Accelerated-Mobile-Pages#277]
Hi, I Check On Add Meta Tags from Yoast and Yoast Custom Description for AMP page but i view source and see it not add

**REF:** https://wordpress.org/support/topic/yoast-seo-115/
http://mostspotlight.com/pope-francis-never-forget-smile-even-life-hard.html/amp

**Comment by khaledMohammed000** [comment]
1. Static page  - > takes side wide description
2. In Single Posts - > Works Perfectly
3. In Index Page - > takes side wide description

**Comment by ahmedkaludi** [comment]
Checked, working fine.

**Comment by vagu71** [comment]
Checking this on version 0.9.97.52. Yoast custom description is not getting pulled from AMP page. It creates the description from the content and displays that. Also, in case visual composer is being used, it does not remove VC shortcodes and also on one of the sites, the closing " of twitter: description is not there and this breaks all the tags thereafter.

**Comment by MohammedKaludi** [comment]
Hey @vagu71 

This is a very old ticket, if you feel the issue is still there then please create a new ticket or add it to the one that you just created.

**Comment by vagu71** [comment]
Done, https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3207

Thanks @MohammedKaludi
