### ISSUE TITLE
gallery/slider module is not working when Convert AMP to WP theme (Beta) option is enabled.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2771]
DESC: gallery/slider module is not working when Convert AMP to WP theme (Beta) option is enabled. Issue recreated in localhost too.

REF: https://secure.helpscout.net/conversation/741633193/47426?folderId=2169248

**Comment by MARQAS** [comment]
Need modifications in Styling.

**Comment by MARQAS** [comment]
@ajeetku and I have one suggestion, if we want to improve this feature more then we should make an extension for this.

**Comment by RajuJeelaga** [comment]
- [ ] Gallery/Slider Module Design 3 Image Thumbnails are not showing....

**Comment by RajuJeelaga** [comment]
- [ ] AMP and NON-AMP Gallery/Slider all Designs markups are coming properly, Need to add some js functionality to work properly in Design 1,2 and 3  will look Both AMP and NON AMP should be same..
1.Design -1 : https://monosnap.com/file/Z1PRw5AdWsaeWeVRMV11NXfTxt3L6n
2.Design -2 : https://monosnap.com/file/IQK1EdmLBAhvnow7Nqgdm8yuMUtGFc
3.Design -3 : https://monosnap.com/file/UwrUEJy5tkcdI2938jNp7c7woclK8R

@ajeetku

**Comment by MohammedKaludi** [comment]
Escaping missing.

for both `ampforwp_non_amp_gallery()` and `ampforwp_non_amp_gallery_testimonial()`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9b7120fbdbd6c1427c3a2afaa7338bce58dc4d3b#diff-1301281de287d2aed98746fc9ba777b4R70

**Comment by MohammedKaludi** [comment]
Move the comments after the SemiColon While merging
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1fab81f22bdcc04b3b66a686e14453854a469216#diff-1301281de287d2aed98746fc9ba777b4R70

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
