### ISSUE TITLE
Need to add WP User Avatar plugin compatibility in amp as to show the gravatar

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2772]
Desc: Need to add WP User Avatar plugin compatibility in amp as to show the gravatar.

Ref: https://secure.helpscout.net/conversation/734787991/45868?folderId=2169248

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: pushed in 0.9.97.41
