### ISSUE TITLE
performance related issue calling template_redirect hook

### ISSUE THREAD

**Issue by dws122** [ahmedkaludi/accelerated-mobile-pages#2773]
Hi

Around Nov 20th, we noticed a huge increase in processing by the plugin on a high volume site. This site always has 1500 active users, and often 6,000 to 10,000 active users as measured by Google Analytics.

We run New Relic monitoring on the site. Sorry I'm just getting to document this now.

![amp-issues](https://user-images.githubusercontent.com/12969150/50562335-2c2f8f00-0ce1-11e9-80d8-f4945a4c07f3.jpg)

As you can see from the chart below, at any given time your processing is extremely high. There were 3261 users on the site when this screen shot was taken.

![top-5-plugins](https://user-images.githubusercontent.com/12969150/50562423-c55ea580-0ce1-11e9-8f2b-fdf202c1e9fd.jpg)

It appears you are calling the template_redirect many times.

![top-hooks](https://user-images.githubusercontent.com/12969150/50562449-f939cb00-0ce1-11e9-8328-bddee1a6bf61.jpg)

Here's stats on the hook:

![hook--template-redirect](https://user-images.githubusercontent.com/12969150/50562534-80873e80-0ce2-11e9-96df-88df15a859d2.jpg)
![hook-call-count](https://user-images.githubusercontent.com/12969150/50562536-82510200-0ce2-11e9-8384-7937491a8928.jpg)

Why do you think this began happening? It appears to worsen when new posts are added. Here you can see the spikes the last 24 hours when new posts were added.

![plugins-last-24-hours](https://user-images.githubusercontent.com/12969150/50562568-cba15180-0ce2-11e9-8267-0e4cbe3a9c02.jpg)

Drilling down into the New Relic data shows the exact same hook being called during those peaks.

![same-hook-during-peaks](https://user-images.githubusercontent.com/12969150/50562584-03a89480-0ce3-11e9-82e0-d797621aa110.jpg)

This has happened from late November to now. We are on Version 0.9.97.22

Please let me know if you need any additional information.

**Comment by Zabi09** [comment]
@dws122 
Sorry for the inconvenience, we need to check on your end for testing it and find out exactly what hooks and which priority of hooks you are having this issue and for further debugging, Will you please share your website credentials along with New Relic details on team@magazine3.com and we will check everything and we will make sure all your issues will be fixed.

**Comment by Zabi09** [comment]
@dws122 We have improved performance related issues in the current version but we have not pushed it yet, Will you please download this zip folder and install it and check once,
https://github.com/ahmedkaludi/accelerated-mobile-pages/archive/master.zip

And if you still have issues then please let us know.

**Comment by dws122** [comment]
I downloaded and installed Version 0.9.97.23 from the link above. That version didn't solve the issue. Was it supposed to have?

![amp-version_0_9_97_23](https://user-images.githubusercontent.com/12969150/50606915-65a8fb80-0e95-11e9-9d1f-93091309fa08.jpg)

**Comment by Zabi09** [comment]
@dws122 that's really strange, Will you please share your website credentials along with New Relic on team@magazine3.com and we will check it and fix it immediately.

**Comment by dws122** [comment]
Can you compare your code for that hook now versus before US Thanksgiving? Something had to change during that time period, as it was fine before then.

I cannot share New Relic credentials as that is one of our production servers where we host many sites for our clients.

**Comment by Zabi09** [comment]
@dws122 
So you mean the zip folder which I send you has more errors than the current version live on wordpress.org? and if you cannot provide us the New Relic credentials then can we do a team viewer and in that we will check your issue and fix it.

Please let us know,

**Comment by Zabi09** [comment]
@dws122 
We are also not sure exactly which versions you are talking about because we normally push the update in every week so we cannot guess exactly which versions to compare. Will you please let us know and can we do a team viewer so that we can check on your end and once we got aware of from where this issue is started then we can go deeper and fix it.

**Comment by dws122** [comment]
Sorry I didn't have a chance to respond. The issue still exists as of Version 0.9.97.36

It looks like the issue is related to calling the `template_redirect ` hook.

Please setup a time to review with me here: https://bizbudding.com/go/david

![plugins](https://user-images.githubusercontent.com/12969150/53145197-43fef300-356d-11e9-9403-e8d8b222755b.jpg)
![webhooks](https://user-images.githubusercontent.com/12969150/53145198-43fef300-356d-11e9-8da5-58bb7ac0e595.jpg)

**Comment by dws122** [comment]
Just checking in to have this ticket re-opened.

**Comment by pegazee** [comment]
@dws122 We have improved performance related issues in the beta version but we have not pushed it yet, Will you please download this zip folder and install it and check once,
https://github.com/ahmedkaludi/accelerated-mobile-pages/archive/0.9.98.zip

And if you still have issues then please let us know.

**Comment by pegazee** [comment]
However, I'm forwarding this ticket to review section. Meanwhile, we can continue the conversation with the user.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MARQAS** [comment]
Check with AMP takeover by disabling AMP on a particular post

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.54
