### ISSUE TITLE
Make the compatibility with UseAnyFont Plugin

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2774]
Reference:
https://secure.helpscout.net/conversation/741302041/47367?folderId=2090438

https://wordpress.org/plugins/use-any-font/
Using this Plugin, users can apply any Font-Family to their websites.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
1. `!important` will break the AMP validation https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7398d7f51c3a90b4d0a0f15f4009482ed3feb288#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7000
2. escaping is missing 
3. Use any existing `amp_post_template_css` hook https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7398d7f51c3a90b4d0a0f15f4009482ed3feb288#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6962

**Comment by MohammedKaludi** [comment]
escaping missing 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/01d0a1af45b322281c8a4357d3f635e16d3bff53#diff-1301281de287d2aed98746fc9ba777b4R766

**Comment by MohammedKaludi** [comment]
Escaping still missing.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ab3a3415ab15bc8a50a2d4151848102bff5b949e#diff-1301281de287d2aed98746fc9ba777b4R683

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ab3a3415ab15bc8a50a2d4151848102bff5b949e#diff-1301281de287d2aed98746fc9ba777b4R692

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
