### ISSUE TITLE
Non-existing image is adding invalid height & width values on AMP.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2775]
When Non-existing image is added then invalid values of height & width is appearing on AMP, hence fix this issue either to display 404 image or set width, height values to "0".
Ref : https://secure.helpscout.net/conversation/711947296/41164?folderId=1060556

**Comment by ahmedkaludi** [comment]
it was a one off issue, solved on user's end.
