### ISSUE TITLE
Confilict with the Schema and Structure data plugin.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/accelerated-mobile-pages#2777]

**Comment by mdsam10** [comment]
https://secure.helpscout.net/conversation/744272001/47982?folderId=2206768

Screenshots available in the helpscout ticket.

**Comment by mdsam10** [comment]
https://secure.helpscout.net/conversation/732775034/45469?folderId=1060556

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.24
