### ISSUE TITLE
"Below the Footer" ads showing above the footer and below the footer

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2778]
When enabling this option, ads are showing above the footer and below the footer which is not correct.

Screenshot > https://monosnap.com/file/AjKFTYwvyT6I9qN61FpPTbtDZ29kNu , For debugging purpose, I've added the background color of amp-ad-wrapper class

**Comment by Zabi09** [comment]
But still, the Ad is appearing above the Footer only not below the footer

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.35
