### ISSUE TITLE
In Design 3's Slider the quality (clarity) of the image is being reduced, so need to display the images with good quality.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2779]
Reference:
https://secure.helpscout.net/conversation/740152647/47078?folderId=2090438
Example:
Slider Pic: https://prnt.sc/m2krvf
Actual (Normal) Pic: https://prnt.sc/m2ks2s

**Comment by ahmedkaludi** [comment]
Please clarify this issue with @merajali294 and @ahmedkaludi

**Comment by MohammedKaludi** [comment]
Can be merge into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
