### ISSUE TITLE
How to load Disqus comment in AMP Theme Framework

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2780]
Ref:  https://secure.helpscout.net/conversation/744259003/47978?folderId=1914712

**Comment by MARQAS** [comment]
It can be done using Comments component: https://ampforwp.com/tutorials/article/comments/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
Closing the ticket.
