### ISSUE TITLE
Indentations are getting removed in lists of ul & ol tags.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2781]
Indentations are getting removed in lists of ul & ol tags.
Ref : https://secure.helpscout.net/conversation/745380253/48235/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
