### ISSUE TITLE
AMP Theme Framework getting conflicted in beta.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2782]
AMP Theme Framework getting conflicted with beta and throwing fatal error.
Ref : https://secure.helpscout.net/conversation/737726241/46513?folderId=2322652
Error : https://monosnap.com/file/SatQfdc7evDA2lmNtnn6Wg1Boutn3b

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MARQAS** [comment]
This can be added in master after this ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2652

**Comment by pegazee** [comment]
pushed in 0.9.97.44
