### ISSUE TITLE
Maps not Zooming In & out on AMP Pages on Mobile

### ISSUE THREAD

**Issue by saksham7** [ahmedkaludi/accelerated-mobile-pages#2783]
My embedded map [here](https://directory.edugorilla.com/coaching/amp-solutions-pvt-ltd-sector-34a-chandigarh-fee-structure-syllabus-address-admission-form-contact-number/?amp) donot zooms in & out amp mode on mobile.

**Comment by ahmedkaludi** [comment]
@saksham7 Please contact team@magazine3.com so that our team can debug this issue before we can confirm this as a bug.
