### ISSUE TITLE
Need to Implement Breadcrumbs feature for pages 

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2788]
Ref:  https://wordpress.org/support/topic/breadcrumbs-80/

**Comment by ajeetku** [comment]
use this function to get options `data ampforwp_get_setting()`

**Comment by pegazee** [comment]
It would be better if we add an option for this. 

@ahmedkaludi  and @MohammedKaludi what do you say?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
> It would be better if we add an option for this.
> 
> @ahmedkaludi and @MohammedKaludi what do you say?

Yes option is required and by default it should be turned off

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
escaping required https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c4f8b8bcc69eb4c71351a4718cabbf2d4192477f#diff-2ae5550e31f40c1962ca69d373af6b93R1759

**Comment by MohammedKaludi** [comment]
> It would be better if we add an option for this.
> 
> @ahmedkaludi and @MohammedKaludi what do you say?

yes we need the option.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
