### ISSUE TITLE
Need to make compatibility with jetpack "shortcode-embeds".

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2789]
Need to make compatibility with jetpack "shortcode-embeds".
Ref : https://secure.helpscout.net/conversation/749443055/49190?folderId=2322652

**Comment by ahmedkaludi** [comment]
we already tested this one, It's irrelevant, Until we have proper details on this issue, the ticket will be remained closed.
