### ISSUE TITLE
Need to add Caption option for gallery/slider module in pagebuilder.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2790]
Desc: Need to add Caption option for gallery/slider module in pagebuilder.

Ref: https://secure.helpscout.net/conversation/721691111/43509?folderId=2169248

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
move `get_post` inside the `if($imageDetails)` check that will reduce the call to improve the performance.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6f0a92df45128e010d0cafbbbf72d6b5156b4f75#diff-45752acf5e8ea05d2224fa9a73c54c7aR1092

**Comment by MohammedKaludi** [comment]
can we wrap`$imageDetails = wp_get_attachment_image_src($attachment_id, $imagetype, false);` with a check `if( $attachment_id )`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6f0a92df45128e010d0cafbbbf72d6b5156b4f75#diff-45752acf5e8ea05d2224fa9a73c54c7aR1091

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
pushed in 0.9.97.44
