### ISSUE TITLE
Just remove the Merriweather deafult font

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2792]
The plugin works great.
The only thing I would remove is the Merriweather font, or at least make it optional.
Despite the fact that it’s served via CDN, Google Speed tests recognizes it and suggest the removal.
So, it’s not a very good idea to make it de default font, specially when you load 4 styles, regular, bold, italic, italic bold making it extremely slow.

Just a suggestion!

REF: https://wordpress.org/support/topic/excellent-plugin-just-remove-the-merriweather-deafult-font/

**Comment by ahmedkaludi** [comment]
We need to create an option for Design one
by default the fonts will be on, they can turn it off

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
why NOT equal is used?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2300c7da799a9447489fd22fd988f2297d38a7c0#diff-6aa5512f7dd8d5ce60fc97b0f340912cR5063

**Comment by MARQAS** [comment]
We are removing it from all the designs except from Design-1 which is connected to an option

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
