### ISSUE TITLE
Default value for Swift Color Scheme

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2793]
Update default value of Swift Color scheme, I have added for hover, need to add it everywhere where color scheme is used

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.35
