### ISSUE TITLE
WP Product Review Lite plugin is not getting deactivated in the AMP Plugin Manager

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2794]
WP Product Review Lite plugin is not getting deactivated in the AMP Plugin Manager which occurs author stylesheet error.

Ref: https://secure.helpscout.net/conversation/747902074/48853?folderId=1914712

**Comment by MARQAS** [comment]
WP Product Review Lite plugin has given an option named "Enable AMP CSS" through which one can enable/disable its CSS in AMP.

**Comment by MARQAS** [comment]
![wp product review weekly wordpress - google chrome 2019-01-11 12 21 50](https://user-images.githubusercontent.com/15303814/51017869-91b23400-159b-11e9-9411-23ff1c036fe1.png)
