### ISSUE TITLE
AMP Error: Undefined index and Undefined variable

### ISSUE THREAD

**Issue by chandangunjan** [ahmedkaludi/accelerated-mobile-pages#2795]
Hi Ahmad,
I have installed the latest version of amp for wp (0.9.97.24 ) on a wordpress site..but once I navigate a post..on top of the page I am getting 2 errors 
1.  "Notice: Undefined index: hide-amp-tags-bulk-option2 in /home/yoksx7pe4wpv/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4698" .
2. Notice: Undefined variable: inline_related_posts in /home/yoksx7pe4wpv/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 5546
 Ref url: http://bhojpurifilms.co.in/simmba-movie-review-story-trailer/?amp
Could you help me please?

**Comment by MohammedKaludi** [comment]
Hey @chandangunjan thank you for reporting the issue.

This is just a warning reported by WordPress and it seems that debugger is enabled on your site.

It is not recommended to enable debugging on production sites, so by following this you can disable the warnings https://www.youtube.com/watch?v=LwgezC86FWI

and as far as fixing the warnings we are going to fix this in the future updates.

Do let me know if you need any thing else from us.

**Comment by chandangunjan** [comment]
> Hey @chandangunjan thank you for reporting the issue.
> 
> This is just a warning reported by WordPress and it seems that debugger is enabled on your site.
> 
> It is not recommended to enable debugging on production sites.
> 
> Set WP_DEBUG to false line this `define('WP_DEBUG', false);`, so by following this you can disable the warnings https://www.youtube.com/watch?v=LwgezC86FWI
> 
> and as far as fixing the warnings we are going to fix this in the future updates.
> 
> Do let me know if you need anything else from us.

Hey,
You are awesome Ahmad.
I really couldn't figure it out. I am a .net developer and an absolute beginner in php and wordpress because of which I got stuck and with your help it is fixed now. I really appreciate your quick help.
Thank you..Thank you so much for your guidance .

But there are another issues got piled up in google search console.
1. Referenced AMP URL is not an AMP. (failed)
2. Invalid URL protocol in attribute 'permission-dialog-url' of tag 'amp-web-push'.

Plesae tell me How should I resolve it?

**Comment by MARQAS** [comment]
Hi @chandangunjan, can you share those URLs?

**Comment by chandangunjan** [comment]
HI Marqas,
Thank you so much for taking initiative to help me.
There are four types of error in googles search console under amp of enhancements tab.,
The errors and the ref urls are below.

1. Invalid URL protocol in attribute 'permission-dialog-url' of tag 'amp-web-push'.
Ref URl:  http://bhojpurifilms.co.in/bairi-kangna-2-movie-review/?amp
2. Invalid URL protocol in attribute 'service-worker-url' of tag 'amp-web-push'.
Ref URl:  http://bhojpurifilms.co.in/bairi-kangna-2-movie-review/?amp
3. Invalid URL protocol in attribute 'helper-iframe-url' of tag 'amp-web-push'.
 Ref URl:  http://bhojpurifilms.co.in/bairi-kangna-2-movie-review/?amp
4. Referenced AMP URL is not an AMP
Ref Url: http://bhojpurifilms.co.in/chhapra-express-movie-review-and-story/?amp

**Comment by pegazee** [comment]
Moving this ticket to the Approval section.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
