### ISSUE TITLE
AMP is not compatible with Click Mag WP Theme

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2796]
We need to do AMP Compatible with Click Mag Theme...
Reference Ticket
https://secure.helpscout.net/conversation/719903374/43203/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.47
