### ISSUE TITLE
If twitter link is embed and it has an twitter link (like a hashtag or a user mention), twit it is not shown 0.9.97.24

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2798]
If you embed a twit and it has a twitter link (like a hashtag or a user mention), twit it is not shown.

Ref: https://wordpress.org/support/topic/problem-embed-twits-with-links/

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2750

**Comment by Zabi09** [comment]
Added the twitter link but it's not working - 
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">In theaters July 5. <a href="https://twitter.com/hashtag/SpiderManFarFromHome?src=hash&amp;ref_src=twsrc%5Etfw">#SpiderManFarFromHome</a> 🕷️ <a href="https://t.co/QC7ib7SrO8">pic.twitter.com/QC7ib7SrO8</a></p>&mdash; Spider-Man (@SpiderManMovie) <a href="https://twitter.com/SpiderManMovie/status/1085172249093582848?ref_src=twsrc%5Etfw">January 15, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
