### ISSUE TITLE
aq_resizer with cdn?

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2799]
Let's return the original array when CDN is used.

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
This solution is not the ideal one, need to improve the method and try to serve images in correct dimensions as sending the original image without resizing is stretching the images.

More info about this ticket in #2659
