### ISSUE TITLE
Disable amp versions of some pages

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#28]
Option to disable amp versions of some pages 

Suggested by https://wordpress.org/support/topic/is-there-a-way-to-disable-amp-versions-of-some-pages?replies=2#post-8730673

**Comment by MohammedKaludi** [comment]
Fixed in commit : https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/ae5427a6ac24d0a1632114ca6f84eeccb1a4255f

More details of this ticket at #8
