### ISSUE TITLE
<i> tag not working in Title

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2800]
`<i>COWGIRL</i> In Love: Beautiful Brides`

For example: http://take.ms/V0SKP

**Comment by MARQAS** [comment]
Added in master

**Comment by pegazee** [comment]
Moving this ticket to the Approval section

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
