### ISSUE TITLE
Need to add an option to delete the saved layouts in pagebuilder.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2801]
Desc: Need to add an option to delete the saved layouts in page builder.
screenshot: https://monosnap.com/file/0huZeZezmDKzvgs3gONPo4jxKCNaqt

Ref: https://secure.helpscout.net/conversation/751241015/49632?folderId=2169248

**Comment by MohammedKaludi** [comment]
need to improve the styling of a button

https://monosnap.com/file/jzzMa5tt11l8JON1frjHFmYrRVy5sj

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
