### ISSUE TITLE
This is commonly undefined and doesn't have an isset();

### ISSUE THREAD

**Issue by cedernet** [ahmedkaludi/accelerated-mobile-pages#2803]
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/7efa747cea000c16fa292cac4412a1fcb27ad578/templates/features.php#L6089

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
use `if ( $query_name )` 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/94984bab1febb61ff01e351768bf6be3bd81777d#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4955

**Comment by MARQAS** [comment]
Its already been added in other ticket

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.49
