### ISSUE TITLE
Integration with EWWW IO and ExactDN.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2805]
Integration with EWWW IO and ExactDN.
Ref : https://secure.helpscout.net/conversation/751564352/49677?folderId=2322652

**Comment by nosilver4u** [comment]
See this for example integration that I put together: https://github.com/nosilver4u/ewww-image-optimizer/blob/0e60fa73d79913c089f1f7f5286636b1f4357224/classes/class-exactdn.php#L2465

Note that I don't intend to keep that code in EWWW IO, I only put it there to ensure that it actually worked and so you could see what it should look like.

**Comment by MARQAS** [comment]
Hi @nosilver4u, 
Thank you so much for the snippet. Do you have any staging where ExactCDN is enabled, so I can test this code?

**Comment by nosilver4u** [comment]
Yeah, I have ExactDN on a couple test sites, your support folks have my email, or you can get in touch via https://ewww.io/contact-us/

**Comment by ahmedkaludi** [comment]
Emailed

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
