### ISSUE TITLE
Need to add FB Messenger Icon in social share icons.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2806]
Need to add FB Messenger Icon in social share icons.
Ref : https://secure.helpscout.net/conversation/752555871/49894?folderId=2322652

**Comment by MARQAS** [comment]
Escaping is my missing, and why the required value changed for this option 'amp-facebook-app-id'?

**Comment by MARQAS** [comment]
What about the option? @Zabi09

**Comment by MARQAS** [comment]
Escaping require at some places.

**Comment by pegazee** [comment]
** review **

- [ ] Imran

- [ ] Kaleem

**Comment by MohammedKaludi** [comment]
Not working properly in other designs.
1) Icon is not looking good.
2) Script loading issue, throwing validation errors https://take.ms/hzDzFS 
3) No APP ID section for D1, D2 and D3.  https://take.ms/gPciz

**Comment by MohammedKaludi** [comment]
URL appending and escaping is done incorrect.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/60d509e55546d32c93a42849c20b4db209bf10b0#diff-9cbf83e0d21caa7d8505ed4a8d03b158R50

**Comment by MohammedKaludi** [comment]
Styling of icons are still pending in D1, D2 and D3
Regarding styling please consult ahmed I have explained him everything.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
