### ISSUE TITLE
When back to top link option is enabled view non-amp link content is rendering twice.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2807]
Desc: When back to top link option is enabled view non-amp link content is rendering twice.
https://monosnap.com/file/uttjMKtiU9uRFxMdLag6CEJJ4KUpWh

Ref: https://secure.helpscout.net/conversation/719838989/43192?folderId=2169248

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
