### ISSUE TITLE
Position of social sharing buttons “above content” not appearing on pages.

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2809]
Link: https://wordpress.org/support/topic/social-share-button-2/

Also, I've re-created the issue on my end.

**Comment by ajeetku** [comment]
use this function to get options data `ampforwp_get_setting`

**Comment by pegazee** [comment]
Moving this ticket to the Approval section

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.25
