### ISSUE TITLE
Facebook like button is not aligned at the same level with other button.

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2811]
ref: https://wordpress.org/support/topic/social-share-button-2/

Screenshots:
 > https://i.imgur.com/bOIPZh3.jpg
>  https://monosnap.com/file/W6GLWNPMBp1ranun1O86TUCUHRFlHs

**Comment by MARQAS** [comment]
@Zabi09, please correct it in other designs as well.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
Working perfectly on Single sidebar as well.

**Comment by MohammedKaludi** [comment]
> Icons are not displaying when selecting single sidebar (left side)

and what about the icons misalignment below author box?

**Comment by MohammedKaludi** [comment]
:+1: 

This was due to another ticket, Order of Elements(#2051). Reverted that code and now its working as expected.
 
> > Icons are not displaying when selecting single sidebar (left side)
> 
> @beingsmart3 and what about the icons misalignment below author box?
