### ISSUE TITLE
Jetpack stats pixel inserted twice since Jetpack 6.9

### ISSUE THREAD

**Issue by aheckler** [ahmedkaludi/accelerated-mobile-pages#2812]
Since Jetpack 6.3, we've attempted to load our own stats pixel on AMP pages. Here's where we do that:

https://github.com/Automattic/jetpack/blob/6.9/3rd-party/class.jetpack-amp-support.php#L14

However, due to some bugs, it didn't always load. Those were fixed in 6.9:

https://github.com/Automattic/jetpack/pull/10945

... so now our pixel loads correctly. 

However, this means that people using Jetpack Stats and AMP for WP now have *two* pixels loading, since AMP for WP also loads it here:

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/includes/vendor/amp/jetpack-helper.php#L14

This results in people seeing a illusory 2x increase in stats on their AMP pages! 😛 

Now that we're loading it correctly ourselves, AMP for WP should probably check for our pixel before loading one.

**Comment by pegazee** [comment]
** Review**

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: can be merge into master

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28
