### ISSUE TITLE
Blog title is displaying on Homepage when custom front page is selected in All in one SEO & Yoast.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2816]
Blog title is displaying on Homepage when custom front page is selected in All in one SEO.
Ref : https://secure.helpscout.net/conversation/753715841/50230?folderId=2322652

**Comment by pegazee** [comment]
Yoast ref:  https://wordpress.org/support/topic/another-error-3/

**Comment by syedimran22** [comment]
Another user using Yoast SEO: https://secure.helpscout.net/conversation/757331412/51098?folderId=2169248

**Comment by Rkroy** [comment]
Another user with Yoast : https://secure.helpscout.net/conversation/757454634/51135?folderId=2322652

**Comment by Meshuggah2018** [comment]
Me too, sorry for starting a new thread.   Yoast, must be deactivated for now if I want titles correct on static front.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by Meshuggah2018** [comment]
Installed today's update,  still static front age title showing blog title example http://newhampshirestripper.com/amp/

without amp, New Hampshire Stripper agency VIP Entertainment Inc.
with /amp,   Blog - New Hampshire Stripper
I am using yoast.

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.98.28

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.29
