### ISSUE TITLE
Space missing in categories list [ Design-3]

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2817]
In breadcrumbs categories need to be separated with coma & space (currently only coma is displaying).
Ref : https://secure.helpscout.net/conversation/750468406/49418?folderId=1060556

**Comment by ajeetku** [comment]
To re-occure: Enable "Minification option"

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.38
