### ISSUE TITLE
Need to align the Radio Button (Show/Hide) in the Arabic language

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2818]
Reference:
https://secure.helpscout.net/conversation/756066318/50845?folderId=2090438
Pic:
https://prnt.sc/m8d0op

When the Arabic Language is set, need to align the radio button as shown in the below screenshot.
https://prnt.sc/m8d20k

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
