### ISSUE TITLE
Need to solve amp-animation error in amp theme framework and tech blogging amp theme

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2819]
Desc: Need to solve amp-animation error in amp theme framework and tech blogging amp theme

Ref: https://secure.helpscout.net/conversation/753898328/50288?folderId=2169248

**Comment by ajeetku** [comment]
need to update Themes of amp framework

**Comment by MARQAS** [comment]
Its getting reflected twice in Swift.
Please find another proper solution as this is not feasible.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.29
