### ISSUE TITLE
Big Bug : always Parent Plugin activation for extensions break

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#282]
I think its because 9.1 branch has weird file name

**Comment by khaledMohammed000** [comment]
This works perfectly in the WP installation in which i dont develop and this has the version that every user uses

**Comment by ahmedkaludi** [comment]
@khaledMohammed000 Can you please update on this, what's an issue?

**Comment by khaledMohammed000** [comment]
the issue is that we have a different name for our Github repo and the Code on SVN/ wordpress.org

**Comment by khaledMohammed000** [comment]
@MohammedKaludi has renamed files so that this issue does not occur
