### ISSUE TITLE
'Call Button Color' option not working

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2820]
Select Swift theme and in header section enable 'Call Now Button' option. After that select color from 'Call Button Color' option from Global section. 

Screenshots:
> https://monosnap.com/file/A0d2mqXkKSK9qJnXgmCY6tsrUuVYhY
> https://monosnap.com/file/boiMiRkCWoMkp0BDcj9qq7hbIwOMTE

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
need to sanitize color otherwise its ready to push.

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31

**Comment by MARQAS** [comment]
We can add the sanitization directly in master

**Comment by MohammedKaludi** [comment]
> We can add the sanitization directly in master

add it directly into master and move the ticket into the ready section.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.32
