### ISSUE TITLE
WP_Widget_Text missing in SiteOrigin Pagebuilder Conflict after v0.9.97.24

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2821]
Ref: https://wordpress.org/support/topic/siteorigin-conflict-after-v0-9-97-24/

**Comment by beingsmart3** [comment]
One More Ref:  https://secure.helpscout.net/conversation/755965917/50831?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MARQAS** [comment]
Pushed in 0.9.97.26
