### ISSUE TITLE
Pre tags not rendering properly on pages.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2823]
Pre tags not rendering properly on pages, hence need to add styling.
Ref : https://secure.helpscout.net/conversation/748424370/48982?folderId=2322652

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
Pre tag is rendering properly :+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.36
