### ISSUE TITLE
Validation error when uploading YouTube video in Comments

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2827]
When embedding youtube video in a comment this error is occurring 
The tag 'iframe' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-iframe'?

Issue recreated on Local Server

Ref: https://secure.helpscout.net/conversation/757341924/51102?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

* Note: 

@syedimran22 , We need to add this code in the NewsPaper AMP theme plugin. When reviewing this ticket, please create another ticket in Extension trello section and this code.

**Comment by syedimran22** [comment]
@pegazee ticket created in trello to add the code in newspaper theme and I will commit the code.

**Comment by MohammedKaludi** [comment]
:+1: good to go

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.32

**Comment by MohammedKaludi** [comment]
Hello, there are error after update wordpress plugin
Fatal error: Can't use method return value in write context in /home/**********/www/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 7900

there are code on features.php:7900:
if(!empty($sanitizer->get_amp_scripts()))
it's logically equivalent to:
if ($sanitizer->get_amp_scripts())

**Comment by MARQAS** [comment]
The error was due to this: https://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context
So a little bit change in code to avoid error

**Comment by pegazee** [comment]
pushed in 0.9.97.32
