### ISSUE TITLE
Wouldn’t have to re-save permalink when ‘Show Instant Article on Current Post’ is disabled.

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2829]
Every time, we need to re-save the permalink when disabling the ‘Show Instant Article on Current Post’. It would be great if wouldn’t have to resave permalinks every time.

Ref: 
* https://wordpress.org/support/topic/does-show-instant-article-on-current-post-work/
* https://secure.helpscout.net/conversation/760250155/51733/

**Comment by MARQAS** [comment]
It is working as expected, but don't know why it is not working on users end

**Comment by ahmedkaludi** [comment]
we will close this ticket until we have a clarity.
