### ISSUE TITLE
Footer widgets are not properly aligned when tag and categories added

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2830]
https://prnt.sc/ma2shh
https://prnt.sc/ma2sv6

Ref: https://secure.helpscout.net/conversation/758160081/51238/

**Comment by RajuJeelaga** [comment]
Default WordPress Category and Tags Design is properly Coming in all AMP Designs 1,2,3 and Swift... 
No need to do styling for that....

**Comment by pegazee** [comment]
On my end, styling was showing perfectly. 

Screenshot: https://take.ms/Ptxnd

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge
