### ISSUE TITLE
Hide by default option from bulk tools is not working when amp takeover option is enabled.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2832]
Desc: Hide by default option from bulk tools is not working when amp takeover option is enabled.

Ref: https://secure.helpscout.net/conversation/759333453/51543?folderId=2169248

**Comment by MARQAS** [comment]
Why not make `ampforwp_is_non_amp` a function with a filter of its own name? And if this condition is only for Takeover then why not keep it inside takeover condition?

**Comment by pegazee** [comment]
I've selected the "Individual AMP Page (Bulk Edit)" as a 'Hide by default'. Seems, AMP template is removed on this but rel=amphtml is showing.

screenshot: 
* http://take.ms/ypDKj
* http://take.ms/npRsa

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.44.2
