### ISSUE TITLE
whatsapp post title

### ISSUE THREAD

**Issue by iamkingsleyf** [ahmedkaludi/accelerated-mobile-pages#2833]
Hello;

The whatsapp share button does not pick the title for the post just the URL..

**Comment by Zabi09** [comment]
@iamkingsleyf Will you please provide us the url of your website and we will check once and let you know

**Comment by Zabi09** [comment]
I have checked your issue and it is showing the post title along with the url. 
See this screenshot: https://monosnap.com/file/xCjHruVMUllwFGmTFApSoVUupZ66r4

Will you please check once again and let us know

**Comment by Zabi09** [comment]
And if you face the same issue again then please contact us on https://ampforwp.com/support/ and our team will help you in fixing your issue.

**Comment by iamkingsleyf** [comment]
That is not showing the title, what its showing there is whatsapp picking a snippet of the article like it does on facebook and google+ when you try to share a post there.

Try sharing on your STATUS then you will know if its showing title or just URL
