### ISSUE TITLE
JSON Charbeat Tag broken.

### ISSUE THREAD

**Issue by EM-MiguelRosas** [ahmedkaludi/accelerated-mobile-pages#2834]
File: features.php -> 10.10 Analytics Support added for Chartbeat Analytics
`Results
Error: Parse error on line 1:
{	'vars': {		'account
--^
Expecting 'STRING', '}', got 'undefined'`

line: 1287

You're using single comma to build the JSON, this invalidates the JSON data.

Update:
`{'vars': {'accountId':"<?php echo $redux_builder_amp['amp-Chartbeat-analytics-code']; ?>",'title': "<?php the_title(); ?>",'authors': "<?php the_author_meta('display_name');?>",'dashboardDomain': "<?php echo site_url();?>"
}}`
To:
` {
     						"vars": {
        							"accountId":"<?php echo $redux_builder_amp['amp-Chartbeat-analytics-code']; ?>",
        							"title": "<?php the_title(); ?>",
      								"authors": "<?php the_author_meta('display_name');?>",      
        							"dashboardDomain": "<?php echo site_url();?>"        
     								  }
   						 }`

**Comment by Zabi09** [comment]
@EM-MiguelRosas 
Thank you so much for your details and we have updated all our analytics code and you can follow this ticket for that - #2653 and we will make sure that this ticket will be pushed in the next update.
