### ISSUE TITLE
Need to make compatible with clyp it iframe embed.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2836]
Need to make compatible with clyp it iframe embed.
Ref : https://secure.helpscout.net/conversation/760854495/51805?folderId=2322652
<iframe src="https://clyp.it/hkojyqcv/widget" width="100%" height="200" frameborder="0"><span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start">&#65279;</span></iframe>

**Comment by MARQAS** [comment]
Why not add it in Iframe sanitizer itself?

**Comment by MARQAS** [comment]
Please update the Vendor changelog as well

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
