### ISSUE TITLE
Google Font is not getting saved

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2839]
Google Font is not getting saved and throwing errors in Console 

issue replicate on the local server

Ref:  https://secure.helpscout.net/conversation/759249301/51526?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Still error in console log
https://monosnap.com/file/OgWyxD27BCzzd7PIeaby9NHDHuUtTI

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.97.33, closing the ticket.
