### ISSUE TITLE
Please add a display embedded photos and videos from Facebook and twitter

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#284]
Please add a display embedded photos and videos from Facebook and twitter
Twitter don't display photo in ver 0.9

https://wordpress.org/support/topic/which-one-feature-will-make-this-plugin-perfect-for-you/

reported by @xissufospace.

**Comment by ahmedkaludi** [comment]
It's already possible https://ampforwp.com/tutorials/how-to-embed-instagram-images-videos/
We are closing this to stay focused
