### ISSUE TITLE
Rare issue with Yoast SEO Premium

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2840]
On AMP custom front page is not working when Yoast seo premium activated 9.5.0
The issue occurs only in design 1,2,&3 but in the swift theme its working fine

Issue not replicated on local server

Ref:  https://secure.helpscout.net/conversation/760887832/51834/

**Comment by ahmedkaludi** [comment]
We have to talk to the customer when we are working on this ticket because the issue is only re-occurring on their end.

**Comment by pegazee** [comment]
I've talked to the user, and he confirms that the issue has been fixed in the latest version v0.9.97.36
