### ISSUE TITLE
When the custom front page has a custom pagination then the AMP pagination returns 404

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#2843]
When the custom front page has custom pagination then the AMP pagination returns 404

Also recreated on localhost by @ahmedkaludi 

REF: https://secure.helpscout.net/conversation/760091522/51669?folderId=2632030

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/31604e190e25c43c020b6e14ed8525e655b97054#diff-6aa5512f7dd8d5ce60fc97b0f340912cR398
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/31604e190e25c43c020b6e14ed8525e655b97054#diff-6aa5512f7dd8d5ce60fc97b0f340912cR396
use amp query var constant instead 'amp' 
and check `http://` its gives proper URL while implode

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
