### ISSUE TITLE
Background image of pagebuilder is zooming in IOS devices when when parallax effect is enabled.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2844]
Desc: Background image of page builder is zooming in IOS devices when parallax effect is enabled.

Ref: https://secure.helpscout.net/conversation/749987974/49319/

However, the issue has been fixed just need to commit the code.
Path:  accelerated-mobile-pages/pagebuilder/config/moduleTemplate.php
variable $front_css
line number 88 need to replace background-attachment: fixed; with **background-attachment: initial;**

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
