### ISSUE TITLE
Text widget img element are overlapping with banner ads (Below the header)  in design 3

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2845]
I had an ad below the header (site-wide) enabled (via AMP plugin settings), and I also had a simple image banner via a widget (in APM Below The Header sidebar) active.  The image banner was overlapping the ad when the design-3 theme is selected.

Ref: https://wordpress.org/support/topic/update-issues-had-to-roll-back-to-v0-9-97-23/

Screenshots: 
* https://imgur.com/a/dg4qTpX
* http://take.ms/4ZdXF

Note: Need to check on design 1 and 2.

**Comment by pegazee** [comment]
Widget Image is not in the centered and upper part of the image is overlapping with the header. And space between the image & Ad is too much, need to decrease the space.

Screenshot: https://take.ms/lMkH4

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
