### ISSUE TITLE
Need to add description field in VideoObject Schema type

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2846]
Ref: https://secure.helpscout.net/conversation/761618632/51984?folderId=1914712

**Comment by MARQAS** [comment]
check if the description is present, then only add the description

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1a9e655663314000b323bcb30b7d900d95a614d1#diff-b7c53bc2fbd4c72dbfdc941d2e719d24R327
1. why passed 30 as string check wp_trim_words function second parameter should integer
2. this line should be inside of if condition

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by Nitesh221194** [comment]
**Description of the post added into the Video Object tag.**

Ref: https://secure.helpscout.net/conversation/834357018/63800/

**Comment by MARQAS** [comment]
Why only for FrontPage? https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5bde809ddd458a7e6dc41cf5c26614115ef57d0a#diff-b7c53bc2fbd4c72dbfdc941d2e719d24R335

**Comment by Zabi09** [comment]
It will work on the front page and also on posts or pages and if the front page is not selected then it was taking the last post description on the homepage and to fix that I have added that condition.

**Comment by MARQAS** [comment]
Check the condition again, it will add the description only for the `ampforwp_is_front_page`. 
Please check and improve the condition.

**Comment by Rkroy** [comment]
The description field is already showing in the VideoObject schema in the master and the VideoObject schema is getting removed in the beta due to WP Recipe Maker plugin.

**Comment by MohammedKaludi** [comment]
Few code is added in the past merging, so need to make sure all the code is added properly in while merging.

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.57
