### ISSUE TITLE
Gutenburg column support

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2847]
It should be according to the screenshot: https://prnt.sc/mbzzmr

But It is coming to this type of result in the screenshot: https://prnt.sc/mbzy1u

**Comment by MARQAS** [comment]
@RajuJeelaga can you review this once?

**Comment by MARQAS** [comment]
It is working as expected

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
