### ISSUE TITLE
Undefined variable warning in class-amp-img-sanitizer.php

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2848]
Undefined variable: class in /home/chantrem/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-img-sanitizer.php on line 105

**Comment by pycarlos** [comment]
I have this issue too.

**Comment by pegazee** [comment]
Hi @pycarlos ,

We've fixed this issue and it's forwarded to the testing department. Once the testing is done, we'll add the solution in the upcoming updates.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Zabi09** [comment]
Pushed in 0.9.97.37 - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2893

**Comment by pegazee** [comment]
Pushed in 0.9.97.38
