### ISSUE TITLE
Yoast showing /blog title on static front page 

### ISSUE THREAD

**Issue by Meshuggah2018** [ahmedkaludi/accelerated-mobile-pages#2849]
I think this is a new issue, I hadn't noticed it till yesterday. On all my wp sites with yoast, The /amp Static front page is pulling the /blog title. I have disabled yoast on 3 sites, which corrects it. I have toyed with the SEO options in amp plugin, turning things on and off didn't help. Yoast must be deactivated 

examples can be site can be sites I haven't gotten to. such as 
http://newhampshirestrippers.com/  you see title.
now the amp
http://newhampshirestrippers.com/amp/
pulling my blog post title which comes from 
http://newhampshirestrippers.com/bachelor-party

I'll leave this as is for now, I'll deactivate yoast on my other sites, don't want google seeing the amp title being different from static front pages.

**Comment by ahmedkaludi** [comment]
@Meshuggah2018 Can you please contact us through https://ampforwp.com/support/ so our team can verify this issue on your end?
