### ISSUE TITLE
Flexible ad spots which allow to past the code of every AMP-accepted ad.

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#285]
Thanks for asking! My personal wishlist (order by priority, 1 = most important):

- [ ] Flexible ad spots which allow to past the code of every AMP-accepted ad.
- [ ]  Add AMP accordion. (I’m currently using Collapse-O-Matic ( https://wordpress.org/plugins/jquery-collapse-o-matic/) shortcode (e.g.:[expand title=”trigger text”]hidden content[/expand]) to hide and expand content e.g.(http://starzip.de/fack-ju-goethe-2). On AMP this function gets removed but it should be possible, more info (https://ampbyexample.com/components/amp-accordion/).
- [ ]  AMP Search (not sure if possible in AMP, otherwise make search-toggle clickable and link to default WordPress search result page /?s=)
- [ ]  Possibility to switch menu (+ menu toggle in layout one) to the left side.

https://wordpress.org/support/topic/which-one-feature-will-make-this-plugin-perfect-for-you/
reported by @loano1.

**Comment by ahmedkaludi** [comment]
Already tickets are made for these.
