### ISSUE TITLE
Getting Validation error due to Slider Module of Fusion Builder

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2851]
Reference:
https://secure.helpscout.net/conversation/753167221/50099?folderId=2090438

An extra bracket ")" is being added which needs to be removed by using str_replace.
Solved on the User's end.

Solution:
function amp_avada( $content ) {
    $content = str_replace( ';)',';',$content );
     return $content;
}

$string=$this->amp_avada( $string );

NOTE: To re-create the issue(error) need to Activate Avada Theme, Fusion Core, Fusion Builder-->Add Slider.

**Comment by MARQAS** [comment]
The error is due to the old Style sanitizer. 
And it has been resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2387
Tested it again. Can be closed

**Comment by beingsmart3** [comment]
- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
ticket closed more info at #2387
