### ISSUE TITLE
Compatibility issues with subtitles plugin

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#2853]
Here Subtitle is not compatibility with AMP
https://wordpress.org/plugins/subtitles/

**Comment by MARQAS** [comment]
Check for FrontPage and Blog

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: can be merged into master

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31
