### ISSUE TITLE
Need to append UTM Parameters(GCLID) in the Mobile when Mobile Redirection is enabled.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2854]
Ref:
https://secure.helpscout.net/conversation/759249301/51526?folderId=2090438

When the URL is opened on Desktop in the Google.com with Keyword(Traductor Jurado en Valencia) it opens up with the GCLID appended to it.
Need to add GCLID Parameter appended to the URL when accessed from the Mobile as well.

Video Explanation:https://monosnap.com/file/3fQBS7jllW6FpXAGyWYTSrgfuMiVlH

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
avoid the usage of `$_SERVER` super global variable use $wp_request instead

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/29c4a4151040fa0d1878acca11b0e0f485129fdf#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4982

**Comment by MARQAS** [comment]
Query strings will not work in $wp->request

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Fully fixed in 0.9.97.33, closing the ticket.
