### ISSUE TITLE
Issue with amp menu converting & ASCII code to X 

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2855]
If mb_convert_encoding is not enabled, Its &amp; converted to X because of here we replaced all ASCII codes to X

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: good to go

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31
