### ISSUE TITLE
Sidebar option is off, do not show widget area in admin panel

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2856]
Sidebar option is off, do not show widget area in admin panel
or show some suggestion on there

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
