### ISSUE TITLE
Issue after upgrading analytics code

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2859]
Issue rise after https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2653

syntax error, unexpected '[' in /data/************/htdocs/sandbox/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1218

Conversation:  https://secure.helpscout.net/conversation/766840358/53271/

**Comment by HANEEFRIYAZ** [comment]
Pushed in 0.9.97.29
