### ISSUE TITLE
Rare issue in Gutenberg image

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2860]
https://secure.helpscout.net/conversation/761985542/52101?folderId=2614130

Here's a screenshot of image: https://prnt.sc/mf3w8r

**Comment by MohammedKaludi** [comment]
Thank you for reporting the issue, our team will check and get back to you.

**Comment by MARQAS** [comment]
Contacted the user and asked him to clear the transients, once he'll do that I am sure his issue will get resolved.

**Comment by ahmedkaludi** [comment]
We will keep this closed until we hear from the customer.
