### ISSUE TITLE
html code <div class="w-bl"> </div> on the homepage

### ISSUE THREAD

**Issue by erdie** [ahmedkaludi/accelerated-mobile-pages#2861]
Hi, I see unwanted html code appearing on the homepage

I don't know why the code appears
Does anyone know it's a bug or not?

```
<div class="w-bl"> </div>
```

My site is mariviu.com/amp

**Comment by MohammedKaludi** [comment]
Hey @erdie,

I have just checked your site and it looks good, also I have attached the screenshot of it.


![bahas one piece chapter 931 big mom amnesia mariviu-min](https://user-images.githubusercontent.com/16618009/52134992-d6952c00-266a-11e9-859e-93adc3e28bd6.png)

**Comment by MohammedKaludi** [comment]
I see no issues on the website. Closing the ticket. If the issue persists, then please reopen the ticket and a screenshot would be very much appreciated.
