### ISSUE TITLE
External links are getting skiped

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2862]
Ref: https://secure.helpscout.net/conversation/762239675/52166?folderId=1914712

Issue recreated In localhost

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
