### ISSUE TITLE
data-loading-strategy attribute is double quoted

### ISSUE THREAD

**Issue by zhouyx** [ahmedkaludi/accelerated-mobile-pages#2863]
Hello there, 

Found the attribute `data-loading-strategy` 's value is double quoted. I saw 
`<amp-ad data-loading-strategy=""prefer-viewability-over-views"">` on the page, and received user error because of that. 

Could you please take a look, thank you.

**Comment by Zabi09** [comment]
@zhouyx Thank you so much for letting us know and I will fix it immediately and make sure it will be pushed in the next update for sure.

**Comment by MohammedKaludi** [comment]
fixed and pushed in 0.9.97.30

**Comment by zhouyx** [comment]
Thank you @Zabi09 and @MohammedKaludi for the quick fix
