### ISSUE TITLE
The home page displays the title of the first post in All in one SEO

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2865]
The issue is occurring from 0.9.97.29 version 
#2816 
Ref:  https://secure.helpscout.net/conversation/768589958/53818?folderId=1914712

**Comment by MARQAS** [comment]
It is breaking the titles of single

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.32
