### ISSUE TITLE
Need to show the Attention message when custom AMP editor box checked but there is no content in it

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2866]
Ref:  https://secure.helpscout.net/conversation/764101671/52687?folderId=1914712

**Comment by Zabi09** [comment]
Not working - https://prnt.sc/phamkx

**Comment by MohammedKaludi** [comment]
Ready to merge, but need to make sure to add prefix in the function name `check_custom_content_status ` while merging.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22
