### ISSUE TITLE
Create a dedicated function called ampforwp_get_the_ID()

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2867]
Create a function called `ampforwp_get_the_ID()`, this will have the post id of the current page including the custom front page.

This is happening again and again and this function should resolve the issue.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ea602978e72a4325217f647d0802c11e0a72b457#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7317

**Comment by MohammedKaludi** [comment]
> How about blog?

you suggest??

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
