### ISSUE TITLE
Gallery Designs for Gutenberg Galley

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2868]
Implement our default gallery designs for Gutenberg Gallery.

**Comment by MohammedKaludi** [comment]
Please read the conversion once in the #2691 's helpscout reply before starting the work on this ticket.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
In Design 1 Gallery looks like this:  http://take.ms/n13uh
http://take.ms/qRteW

**Comment by MohammedKaludi** [comment]
Let's mergeit in to the  core

**Comment by MARQAS** [comment]
Added more code in master here: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/42faf4da342cf0830cfd6101be514c0bdb91064c

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
