### ISSUE TITLE
Homepage Title compatibility with Yoast SEO option

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2869]
I've set the title in non-amp by using the Yoast plugin ( Screenshot: http://take.ms/qT7vF ) but in AMP, It's rendering as Title | Blogname ( Screenshot: http://take.ms/e2jNk ).

Screenshots: 

In AMP: http://take.ms/e2jNk
In non-amp: https://take.ms/fzK4A

**Comment by ajeetku** [comment]
Codes are completely changed but not associated with this ticket

**Comment by pegazee** [comment]
tested on my end, homepage title from Yoast settings is working perfectly.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
The ticket can be closed, code is updated and pushed in #2871
