### ISSUE TITLE
Click-Through-Galleries in AMP

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#287]
One thing I forgot to add: The possibility to see Click-Through-Galleries, in my theme named “smartlists”. For such galleries, every click trough the gallery counts as a page impression and is especially interesting if ads are paid by impression. Currently not visible on AMP. E.g. here: http://starzip.de/die-schoensten-shirin-david-bilder-von-dsds-2017/3

https://wordpress.org/support/topic/which-one-feature-will-make-this-plugin-perfect-for-you/
reported by @loano1

**Comment by ahmedkaludi** [comment]
really good thought but not on the practical radar: We are closing this to stay focused
