### ISSUE TITLE
Category Module from Page Builder not displaying.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2870]
Category Module from Page Builder not displaying with version 0.9.97.31, however its displaying on Version 0.9.97.30
Ref : https://secure.helpscout.net/conversation/767537863/53465?folderId=2322652

**Comment by Bendjii** [comment]
I have the same problem with this same version of the plugin !!!!

**Comment by SageFargo** [comment]
@ahmedkaludi Please look into this, I believe we're experiencing the same problem.
![screen shot 2019-02-05 at 9 12 14 pm](https://user-images.githubusercontent.com/40724154/52298064-c478fd80-298a-11e9-8a3f-8d2c96435df3.png)

**Comment by pegazee** [comment]
This issue is occurring in the master only, and in Beta working perfectly. I've committed the code in the master

**Comment by pegazee** [comment]
** review **

- [ ] kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.32

**Comment by drducmanh** [comment]
Category Module doesn't display if **Select Category** is "**Recent Posts"**
I'm using wordpress version 5.1.1 and Accelerated Mobile Page version 0.9.97.47
