### ISSUE TITLE
Huge improvement needed in Performance 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2873]
We are doing a lot of unnecessary calls in Single post (non-amp version) which is causing immense pressure on the servers. 
Optimizations required:

- [x] ampforwp_stylesheet_file_insertion https://pastebin.com/LCZdTbUq

- [ ] Use Query Monitor plugin and Debug plugin to see which hooks and queries of AMP loads on the non-amp and resolve them.

- [x] Image preview is still breaking in options panel @ajeetku 

This would be one of the biggest improvement of the year!

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by ajeetku** [comment]
Need is admin ampforwp_deactivate_amp_plugin

**Comment by MARQAS** [comment]
Design 1, 2 and 3 are getting blanked. 
`ampforwp_design_elements` are not running (design-manager.php)

**Comment by beingsmart3** [comment]
We found duplicate query http://prntscr.com/mtb4ma
https://secure.helpscout.net/conversation/788178774/57027?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Working code taken from this ticket and pushed in 0.9.97.54
