### ISSUE TITLE
Extra options are being displayed after the search is completed in the AMP Options Panel

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2874]
When we type and search(Search Bar) in the AMP Options Panel, extra options are being displayed/added after the search is completed.
-->Before Search (https://prnt.sc/mhrh80)
-->After Search (https://prnt.sc/mhrgtg)
If we refresh the Page then it's reset.

**Comment by ajeetku** [comment]
Why added this loop again in 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4a39a30a5871e2bc1214a37b73704d2d784f667c#diff-152f06e54fb448fb0758e80ad911fa88R1497

**Comment by pegazee** [comment]
Not Working on my end.

I've search "Color Scheme" and then after getting the result, I've removed the "Color Scheme" from the search box. And still, I'm seeing the extra options. Screenshot: https://monosnap.com/file/bSdz6xOLaA7zs97pUWUs3OuVYqwOPR

**Comment by Zabi09** [comment]
The search icon is not displaying in master because the search code is not present in the redux.js file - https://monosnap.com/file/RfqZeMLVzifyyGOkDAC4smwhRGI4vH 

So please make sure the search code is added while merging into master

Ref: #3372

**Comment by ajeetku** [comment]
While testing make sure debug mode Enabled of wordpress.
In deployment: add this code in redux.min.js also

**Comment by sonaliramteke** [comment]
The search icon is not showing when WP_DEBUG is false

**Comment by MohammedKaludi** [comment]
Ready to merge it and add it in approval section again.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
