### ISSUE TITLE
custom Homepage Title compatibility with All in One SEO option

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2875]
I've added the custom title for the homepage in non-amp by using the All in One SEO plugin ( Screenshot: https://take.ms/STcqQ ) but in AMP, It's rendering as default homepage title ( Screenshot: https://take.ms/sGWQh  ).

Screenshots:

In AMP: https://take.ms/sGWQh
In non-amp: https://take.ms/JpNnS

**Comment by Zabi09** [comment]
Fixed in #2865
