### ISSUE TITLE
GDPR consent is not working on ios

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2876]
GDPR consent is not working on ios.

youtube video is not appear for ref: https://prnt.sc/mhswcy

**Comment by beingsmart3** [comment]
Ref:  https://secure.helpscout.net/conversation/760284318/51738?folderId=1914712

**Comment by MARQAS** [comment]
https://github.com/ampproject/amphtml/issues/20738

**Comment by ahmedkaludi** [comment]
We will close this until we have a path.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready and can be pushed

**Comment by MohammedKaludi** [comment]
https://github.com/ampproject/amphtml/issues/20966

**Comment by MARQAS** [comment]
The solution which He provided is not working

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MARQAS** [comment]
https://github.com/ampproject/amphtml/issues/20966#issuecomment-477725936
We have to check again and see if it's really the issue. And also @beingsmart3 is checking on users end

**Comment by beingsmart3** [comment]
I've tested the issue on two live servers and it's working perfectly without any issues.

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
