### ISSUE TITLE
PHP Notices after the v0.9.97.32

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2879]
I am using the latest version of AMPforWP – v0.9.97.32 on my site. When I proceed to the AMP>Settings on my WP Dashboard, I get 50 PHP Error notices on the Query monitor plugin.
All notices are similar messages like “Uninitialized string offset: XX” where XX denotes multiple line nos.

In addition, when I checked Google Dev console, it also showed 2 errors.

Ref: https://wordpress.org/support/topic/php-notices-uninitialized-string-offset-errors-in-dev-console/

Screenshot: https://imgur.com/a/tAHgXXZ

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.37
