### ISSUE TITLE
 add the schema markup in AMP versions as well.

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#288]
Your plugin is excellent and your team too.
I wish that it should be compatible with all (schema data plugins) which add the JSON-LD markup on posts.
I’m using WP Review Pro by MyThemeShop & Schema
1. The first plugin is used to create reviews, and it adds correct schema data in JsonLD format, so I request you to add the output JSON-LD markup created by this plugin to AMP versions of posts.
2. The second plugin is also awesome, and I think it’s best Schema plugin. Thank to
This plugin adds the all required schema data like Article type, knowledge graph, author, image, etc. in correct JSON-LD format. So I request you to make your plugin compatible with this one so that it can add the schema markup in AMP versions as well.
( Sorry if my words hurt you. I’m not a developer 😀 )

https://wordpress.org/support/topic/which-one-feature-will-make-this-plugin-perfect-for-you/
Reported by @amazingdropout

**Comment by amazinghacker** [comment]
Thanks TEAM!

**Comment by ahmedkaludi** [comment]
Continuing this ticket in #323
