### ISSUE TITLE
Hide AMP option is not working when AMP take over is enabled

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2880]
Hide AMP for a specific page option is not working when AMP take over is enabled. amp take over should not reflect on those pages where show amp support for the current page is set to hide.

Ref: https://secure.helpscout.net/conversation/773800302/54816?folderId=1914713

**Comment by MARQAS** [comment]
This has been resolved in Beta here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2735
So I added the code directly in Master.

**Comment by MohammedKaludi** [comment]
this will not work with custom frontpage

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bdab5f30bfb40013fd2688c6593029eee627281b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6956

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.97.33, closing the ticket.
