### ISSUE TITLE
User is facing issue when site url is different from home url.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2881]
Reference:
https://secure.helpscout.net/conversation/772623640/54619?folderId=2090438
The user is facing error when site url is different from home url.
At user's end:
home url is https://www.ballon.gr
site url is https://admin.ballon.gr

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
