### ISSUE TITLE
CM Tooltip Glossary custom post types are not working with /amp.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2882]
CM Tooltip Glossary custom post types are not working with /amp, however, the page working with ?amp.
Ref : https://secure.helpscout.net/conversation/772947797/54677?folderId=2322652

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
