### ISSUE TITLE
/amp at the beginning of the URL

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2883]
Need to create an option which helps users to change the URL structure to 
www.xyz.com/amp/urladdress

Ref:  https://secure.helpscout.net/conversation/773801877/54817?folderId=1914712

**Comment by ahmedkaludi** [comment]
another request https://wordpress.org/support/topic/change-relamphtml/#post-11602238

**Comment by ahmedkaludi** [comment]
choose

**Comment by MARQAS** [comment]
Fatal error: Using $this when not in object context in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\classes\class-ampforwp-afterdomain-rewrite-rules.php on line 78

**Comment by pegazee** [comment]
It seems your PHP version is below v7.0

**Comment by ajeetku** [comment]
its not with php version
Fatal error: Using $this when not in object context
-----------------------------------------------------------------
`append_post_type_archive_rules` This function is not static  function ,
 `add_action( 'init', array( $this, 'add_rewrite_rules_hooks' ), 9e4 );` 
1. here add_rewrite_rules_hooks  is static function but called with $this operator 
2. priority is 9e4?
3. at commit 509da1c , `append_post_type_archive_rules` & `register_generator_hooks` this function is not static function but called self::register_generator_hooks ?

And check properly other classes also

**Comment by ajeetku** [comment]
- [ ] Notice: Undefined variable: delimiter in ...\plugins\accelerated-mobile-pages\classes\class-ampforwp-afterdomain.php on line 37

- [ ] class-ampforwp-afterdomain.php "str_replace('/amp', '', $url);" instead of amp, use var constant (LIne 20, 71)

**Comment by ajeetku** [comment]
- [ ] Need to check with Custom taxonomies/ Post types / pagination

- [ ] old add rewrite rules will not register

- [ ]  check with category base removal

- [ ] Woocommerce tags & language switchers

**Comment by TMsravan** [comment]
Another user requested for the same.

https://secure.helpscout.net/conversation/929192221/78333?folderId=2632030

**Comment by pegazee** [comment]
I've checked all the list which is listed above and it's working fine. Let me know if anybody got any errors regarding this ticket

**Comment by MohammedKaludi** [comment]
Minor code improvement required and moving the ticket in backlog. Will release this feature in sometime.

**Comment by sardarui** [comment]
Another User reporting the same that, he wants to change the URL structure.

Ref Ticket: https://secure.helpscout.net/conversation/1060780020/107436?folderId=3126461#thread-3001065907

**Comment by MohammedKaludi** [comment]
This feature is added in https://ampforwp.com/addons/subdomain-endpoints-for-amp/
