### ISSUE TITLE
Failed to parse <script> contents. Is it valid JSON

### ISSUE THREAD

**Issue by AhmadTy** [ahmedkaludi/accelerated-mobile-pages#2884]
<amp-analytics  type="googleanalytics" id="analytics1">
<script type="application/json">*********
                          
								{
    "vars": {
        "account": "UA-133326163-3"  //Replace this with your Tracking ID
    },
    "triggers": {
        "trackPageview": {
            "on": "visible",
            "request": "pageview",
            
        },
    }
}							</script>********* 
						</amp-analytics>
should be no scripts ?

**Comment by Zabi09** [comment]
@AhmadTy No, actually it consists of HTML comments and addition "," so due to that it was showing warnings and now we will immediately fix it.

**Comment by AhmadTy** [comment]
thanks for the support!

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.37

**Comment by jansu7** [comment]
I get the same error when I try to add this code for amp-analytics. 
The line that causes the error is: "eventAction": videoSpec.percentages
Has anyone had a similar issue?

`"myVideoPercentagePlayed": {
            "on": "video-percentage-played",
            "request": "event",
            "selector": "#videoName",
            "videoSpec": {
              "percentages": [5, 25, 50, 75, 100]
            },
            "vars": {
              "eventCategory": "video",
              "eventAction": **videoSpec.percentages**
            }
          }`

**Comment by AhmadTy** [comment]
@jansu7 try to disable the advanced Google Analytics option
