### ISSUE TITLE
Debug error undefined index comments

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2887]
Notice: Undefined index: comments in /home/azads5nt/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 7916

Ref: https://www.azadsoch.in/2019/01/29/jio-celebration-pack/amp/
https://secure.helpscout.net/conversation/775899531/55111/

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.35
