### ISSUE TITLE
Safari and iOS Safari: AMP Pages not working correctly (links unclickable, search and menu not working, etc.)

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [ahmedkaludi/accelerated-mobile-pages#2888]
Please also see support forum post: https://wordpress.org/support/?post_type=topic&p=11200061 (has not been released form moderation yet for some reason)

This is the second wordpress site I am encountering this issue on, when making use of this plugin. On the other project I went back to using Automattic's AMP plugin as it's pages work fine in Safari.

This is the support forum post:

Hello there,

when viewing our test page (only single page where AMP has been activated so far: https://www.eimsig.de/alltagshelfer/amp/ )  using a mobile device (iphone XS and iphone 7 with latest iOS in this case) there seem to be various issues:

1. Logo
No matter what logo image size I upload, the image is always being displayed stretched oder is overlapping the header container or what not. Quite annoying. Even if I set it to fixed width and enter the logo dimensions, when they differ from recommended logo dimensions. Only way to solve this was to add custom css:

```
.amp-logo amp-img {
    max-height: 36px; /* my logo file's height */
    max-width: 88px; /* my logo file's width */
}
```

This needs some debugging.

2. When I visit the test page with an actual mobile device (iphone with latest iOS on Safari) none of the header links work. So search icon is disfunctional, menu won't open, no links in content work at all, footer links don't work. 
When I try tapping any of the header icons I am always redirected to the page's desktop version.

I tried using another AMP theme, but same issues on any of the free options. I haven't tested with Pro AMP theme versions, because of the issues in this plugins, I decided not to buy the Pro version of the  plugin yet.

This needs some debugging.

3. When using Google Tag Manager ID, I see errors in browser console regarding CORS. On desktop version this is not an issue at all.

This needs some debugging.
There is W3Total Cache with AMP Extension running in this site.
However even when deactivating the issues persist.

Before I have been using the official AMP Plugin by Automattic and it worked fine on this site, however it lacks support for pages, which is why I decided to try out your plugin.

EDIT: OK, while further investigating, I found out that above described issues (see 2.) seem to be Safari related. Your developers should test in Safari at least before deploying updates. All above mentioned issues are present when visiting the site on Desktop Safari on a mac. Also present on iOS Safari.
Please fix this,
Thanks

EDIT 2: I removed AMP for WordPress and reverted to AMP plugin by Automattic, as this issue is crucial at the moment for any mobile user on iOS devices.

**Comment by ahmedkaludi** [comment]
@s-a-s-k-i-a I would recommend you to create a support request from https://ampforwp.com/support so our technical support developers can troubleshoot and help you fix them.

The Github issues are for valid and clear issues which can be tackled and be merged into the core of the plugin.
