### ISSUE TITLE
BridVideo plugin, add script twice

### ISSUE THREAD

**Issue by davideprevosto** [ahmedkaludi/accelerated-mobile-pages#2889]
Hi there,
we are using Brid Video plugin (https://brid.tv/) and we are notice two differents references to the same script, in our AMP pages html.

`<script custom-element="amp-brid-player" src="https://cdn.ampproject.org/v0/amp-brid-player-latest.js" async></script>`

AND

`<script type="text/javascript" src="https://cdn.ampproject.org/v0/amp-brid-player-0.1.js" async custom-element="amp-brid-player"></script>`

Google Search Console is marking these issue as warning.

Thank you

**Comment by davideprevosto** [comment]
This issue was solved by plugin author:

https://wordpress.org/support/topic/amp-issue-5/#post-11201001

**Comment by MohammedKaludi** [comment]
Closing the ticket as it is fixed by the bird.tv plugin author.
