### ISSUE TITLE
Compatibility with Slide Anything plugin.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2891]
Compatibility with Slide Anything plugin.
Ref: https://secure.helpscout.net/conversation/768217280/53730?folderId=2322652

**Comment by littlemisslionheart** [comment]
Hi, just curious when you expect that the slide anything plug in will be compatible with AMP?

**Comment by ajeetku** [comment]
currently, it's running for all contents, if there is plugin is inactive. Need to add a condition for plugin active

**Comment by littlemisslionheart** [comment]
I'm not sure what this means. I have a slider on my home page. It is  
active. But on amp pages it just displays the short code. I would  
really like for it to show my slider. I thought that was what you guys  
were working on doing. How do I get the slider to show on the amp  
version of my page?



Quoting Ajeet kumar <notifications@github.com>:

**Comment by MARQAS** [comment]
@littlemisslionheart This code is still in beta, we will add it in next versions. 
Please have some patience, or you can check with Beta.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
