### ISSUE TITLE
class are repeating number of times when image (icon) added  in .svg format 

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2893]
amp-wp-unknown-height, amp-wp-unknown-width class are repeating a number of times when .svg format image are added. also added class added in the img tag is not reflecting in the source code.

See this screenshot: https://monosnap.com/file/0HBKn4mx374gSs1HnDm1epJgr4Sc6B

Ref: https://secure.helpscout.net/conversation/726344474/44285?folderId=1914713

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.37
