### ISSUE TITLE
php warning issue in latest version of php

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2895]
Page created with AMP page builder throwing warning "A non-numeric value encountered in"..
https://monosnap.com/file/WMNuxc4h41XAflcttM4Clvs1wOBUpe

solution: pass the (int) before the $ampforwp_excerpt_length function in contents.module.php
currently : 
<p>'.wp_trim_words( strip_tags( strip_shortcodes( $content ) ) , $ampforwp_excerpt_length  ).'</p>';

this will solve the issue:
<p>'.wp_trim_words( strip_tags( strip_shortcodes( $content ) ) , (int) $ampforwp_excerpt_length  ).'</p>';

Ref: https://secure.helpscout.net/conversation/778976210/55568?folderId=1914713

**Comment by MohammedKaludi** [comment]
need to make sure all `wp_trim_words` instances have been updated

1. https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/components/loop/loop.php#L314


2. https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/pagebuilder/modules/contents-module.php#L301

3. https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php#L4929

4. https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php#L5630

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.36
