### ISSUE TITLE
single featured image needs to have a filter

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2896]
https://secure.helpscout.net/conversation/777028320/55299?folderId=2614130

**Comment by MARQAS** [comment]
Why not for other Designs?

**Comment by MARQAS** [comment]
Please update the Vendor as well.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
improve the name of the filter, 'ampforwp_featured_image' use `ampforwp_featured_image_size` instead.

**Comment by MohammedKaludi** [comment]
change the name of the filter to `ampforwp_featured_image_size`

**Comment by pegazee** [comment]
@MohammedKaludi, I've already changed the name of the filter to `ampforwp_featured_image_size`. Please see this commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/fb51a2794b2638e679d6d6ab8da8b6b0d184139a

**Comment by MohammedKaludi** [comment]
:+1: Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
