### ISSUE TITLE
For Menu pages where AMP support is off /amp still getting added due to Auto Add AMP in Menu URL

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2897]
For Menu pages where AMP support is off /amp still getting added due to Auto Add AMP in Menu URL
screenshots: http://take.ms/pRRl1
http://take.ms/uSY5g
http://take.ms/bceYSN

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
also need to check for category and tag as well, 

https://monosnap.com/file/QVCSn6imeorjES5HHVhwneVVI56Z45

https://monosnap.com/file/oJDyAqmSGVxFTYvVqzRfAL72Gv5fvg

**Comment by MohammedKaludi** [comment]
ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
