### ISSUE TITLE
Single Images are cutting of in AMP

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/Accelerated-Mobile-Pages#29]
Content is cutting after image in the single for some reason.

Issue reported on : https://wordpress.org/support/topic/cut-off-at-more
Working amp page : http://www.draggedy.com/wp-content/uploads/2016/07/Sal-with-AMP-working-ok.png

Not working amp page on the same site : http://www.draggedy.com/wp-content/uploads/2016/07/Anuj-page-cut-off-with-AMP.png
Original page : http://www.draggedy.com/wp-content/uploads/2016/07/anuj-page-working-no-amp.png

**Comment by ahmedkaludi** [comment]
This was fixed after 0.8 update.
