### ISSUE TITLE
Load static page template in AMP

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2900]
Need an option to load static function
like https://prnt.sc/mluiyf
AMP theme framework need to load/overwrite static templates files in AMP

**Comment by ajeetku** [comment]
Solution is added in 7f7f3ad
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2614

**Comment by MARQAS** [comment]
Working as expected.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by Zabi09** [comment]
Working fine on my end.

**Comment by MohammedKaludi** [comment]
Can be merged

**Comment by pegazee** [comment]
Pushed in 0.9.97.37
