### ISSUE TITLE
Custom AMP Editor Content is Not rendering when Elementor Activated 0.9.97.31

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2901]
Ref:  https://secure.helpscout.net/conversation/780576457/55807?folderId=1914712

similar issue occur on local server on 0.9.97.35

**Comment by MohammedKaludi** [comment]
Not working with custom homepage

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
