### ISSUE TITLE
Hiding and showing Post's categories not working

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2903]
I've Select Category to Hide in AMP by using the "Select Categories to Hide AMP" option and Open the one of my post which was hide & selected “Show” in the sidebar and update the post, but option will change to “Hide” after it and post will not be available in AMP.

Ref: https://wordpress.org/support/topic/showing-hided-categories-posts/

Note: 
* issue was re-created on my local server.

**Comment by MARQAS** [comment]
It's not working as expected. 
1: I selected the categories to hide, Categories and its posts are updated to hide(working as expected).
2: I removed those categories from the option, Categories are updated to show but Posts are still hidden(Not working as expected.) It should again get updated to show condition.

**Comment by pegazee** [comment]
Not working.
I've selected the category to hide from the " Select Categories to Hide AMP", and the archive page ( category page) was hiding not the posts.

**Comment by MARQAS** [comment]
We will tackle this with #3052 and #3026

**Comment by MARQAS** [comment]
This solution is not working properly according to our use case. The better solution has been added in this ticket. Follow here for more info: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2549
