### ISSUE TITLE
When AMP support is disabled on Homepagepage ?nonamp=1 redirect to random pages(blog)

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2904]
Issue start occurring from 0.9.97.33. when AMP support enabled only on the post, and by clicking on the logo it redirects to the random page (blog) page, not the homepage.

However, when we enabled the AMP support on the homepage then the logo redirects to the Non-AMP homepage perfectly.

Ref: https://secure.helpscout.net/conversation/780551834/55800?folderId=1914712
Issue Not recreated on my local server

**Comment by MARQAS** [comment]
Broken when Non-amp link and homepage support is enabled

**Comment by ajeetku** [comment]
use esc_attr on attribute before output the value : ref check-in master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready, but escaping in `rel="nofollow"` need improvement

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
