### ISSUE TITLE
Debug warning in backtotop css

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2905]
https://monosnap.com/file/qJRRWLMK1MeFiJcAN1FwbeXWsYJoaF

https://wordpress.org/support/topic/linked-amp-version-is-invalid-5/

**Comment by pegazee** [comment]
Fixed in the latest version v0.9.97.36

The ticket is https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2895 and the fix commit is https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/fd66a4055d92bb84156d50099b75805e1c9b1608
