### ISSUE TITLE
No space/ minify option is removing space from the css psudo element thus scrollbar not removing

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#2907]
No space/ minify option is removing space from the css psudo element thus scrollbar not removing

CSS should be:  .hamb-mnu ::-webkit-scrollbar{display: none;}

but it is like this:  
![image](https://user-images.githubusercontent.com/46995400/53086731-acc57b80-352b-11e9-9512-fd390f5f24dd.png)

Scroll bar: https://monosnap.com/file/xRPNRyDSO7RuZVMajyMNco8UvC8nDq

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
