### ISSUE TITLE
Excerpt length feature request for related post

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2908]
Ref:  https://secure.helpscout.net/conversation/783471271/56251/

**Comment by ms-hasan** [comment]
Also add read more label in related post

**Comment by MARQAS** [comment]
Take the default value first in the variable.

**Comment by pegazee** [comment]
as the user requested to add the "read more" label/text in the excerpt but the code is not written for the "read more".

Note: Read @ms-hasan comment.

**Comment by pegazee** [comment]
Excerpt on a small screen not working in D-1,2,3. Can we create an option in related post section for this?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
dont use id 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f4af782cc3f3df18713ecc604969e159bfef0c8e#diff-4df5c887c9bf062e619962dc7e2c804eR186

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Styling is not good,

https://monosnap.com/file/2bHGBxfCHIlOWLILWxDg1XNi2ASplG

**Comment by MohammedKaludi** [comment]
it's not about the BR tag, styling is not as per design aesthetics

**Comment by MohammedKaludi** [comment]
do let me know when you start the work on it.

**Comment by MohammedKaludi** [comment]
Design one styling not looking good, font too small to read.
https://take.ms/QLBcp

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
