### ISSUE TITLE
Histats Not working

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2909]
Check this screenshot:  http://take.ms/tBQnF

**Comment by MohammedKaludi** [comment]
use function called `add_query_args`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6c188db1ace1ff324ebf994af8e83006d1f2c2c8#diff-b27b16759fae0fb0d94cc6e00107c8efR137

**Comment by ajeetku** [comment]
Modify typo error feild -> field

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ab7b5115a40fabe1dac3dbc69a6d4199818221ae#diff-8ada183a565e41de5b9a91a8047b98adL417

this will break HiStat counter those who are using

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
