### ISSUE TITLE
Google tag manager

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/accelerated-mobile-pages#291]
Since Google Tag Manager now supports AMP, is there a way of enabling this support within the plugin in lieu of Google Analytics?

https://wordpress.org/support/topic/google-tag-manager-19/

Reported by @lsilver

**Comment by khaledMohammed000** [comment]
Check in branch 0.9.38-root

**Comment by ahmedkaludi** [comment]
This feature was added in 0.9.38
