### ISSUE TITLE
Issue with yoast content reading while amp pagebuilder image module selected

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2910]
This code need to improve, its running always not only with yoast (Improvement)
`<textarea class="hide" id="amp-page-builder-ready"> <?php echo stripcslashes( amppb_post_content('') ); ?></textarea>`

and its if_image_layout this field is not replacing in post edit page 
layout exported @ajeetku name with layout-22022019.json

**Comment by pegazee** [comment]
Pushed in 0.9.97.37
