### ISSUE TITLE
Add more parameters for ampforwp_get_setting functions

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2911]
Add more parameters for ampforwp_get_setting functions.

The idea here is to add 2 more parameters from which we can call the values of color, margin and padding property directly from `ampforwp_get_setting` and we can pass the sanitization type as well in the third parameter.

the current method to get the color data from the options panel is 

`global $redux_builder_amp;`
`$color: $redux_builder_amp['swift-color-scheme]['color'];`

OR 

`
$swift_cs_color = '#005be2';`
`$swift_cs = ampforwp_get_setting('swift-color-scheme');`
`$swift_cs_color = $swift_cs['color'];`
`body a:hover{`
	`color: <?php echo ampforwp_sanitize_color($hovercolor); ?>;`
`}
`

But instead idea is to pass the sub array items as a parameter so we can get the data directly in one call and pass the callback for sanitizer in the 3rd paramerter.

So the function should look like this 
`ampforwp_get_setting('swift-color-scheme','color', 'ampforwp_sanitize_color')`

if we are getting the fonts data then it should look like this.
`ampforwp_get_setting('swift-head-size','', 'esc_html')`

I hope this explains the idea and we will save alot of extra lines of code and this will become single way to get and sanitize the options panel data.

**Comment by ajeetku** [comment]
we can check function exists or not
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/100a42d84b396c32f1c54cad3edf522a92ce4933#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R798

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
need to make sure this commit is merged when this ticket is merging 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c9abf002681c51bbdc34925ee82f2374571f41fa#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R779

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
