### ISSUE TITLE
when the user is directed to the AMP version of the page it changes the URL slighltly (swaps out characters).

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2913]
Desc:  where "&" was being changed to "#038;" on the redirect

https://creditconcierge.com.au/lp/car-finance-cr/?utm_source=canstar&utm_medium=mrec&utm_campaign=ccproduct
amp url

https://creditconcierge.com.au/lp/car-finance-cr/amp/?utm_source=canstar#038;utm_medium=mrec&utm_campaign=ccproduct

Ref: https://secure.helpscout.net/conversation/767558301/53512?folderId=2169248

**Comment by syedimran22** [comment]
Need to change the code only in master in the file redirect.php

In this two lines need to remove esc_url as wp_safe_redirect already sanitize the URL.
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/includes/redirect.php#L24
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/includes/redirect.php#L119

In this below line need to change esc_url with esc_url_raw
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/includes/redirect.php#L278

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
:+1: pushed in 0.9.97.41
