### ISSUE TITLE
Need to place page builder in custom homepage even amp support is off on pages.

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2914]
Ref: https://secure.helpscout.net/conversation/786774910/56801?folderId=2614130

**Comment by ajeetku** [comment]
Add condition properly  `and` `or` condition

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Page builder is visible, but all the other amp related controls are not visible. 
Need to make sure 2 things.

1) All the amp related post meta controls should be available for Custom Homepage page.  
2) When Pages are turned off, then AMP on custom frontpage  is getting disabled, this should not be the case, Custom FrontPage should work independent.

**Comment by MohammedKaludi** [comment]
Use the better function to get the frontpage id

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e2bfafca16de96196d79d1b199f7e7e83396aeff#diff-6aa5512f7dd8d5ce60fc97b0f340912cR793

Use `ampforwp_get_frontpage_id()`


And are you sure it will work for all meta controls?

**Comment by Zabi09** [comment]
Yes the meta-controls of AMP page builder, custom AMP editor, and show/hide AMP meta box

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
