### ISSUE TITLE
When Sticky Header is enabled then Jump link's Title is getting hidden under the header.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2915]
When Sticky Header is enabled then Jump link's Title is getting hidden under the header.
Ref: https://secure.helpscout.net/conversation/770628217/54247?folderId=2322652

**Comment by MARQAS** [comment]
Add condition for Frontpage as well

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Why only in design 3 and swift?
why the code is not in design 1 and 2 ?

**Comment by Zabi09** [comment]
I have not added in design 1 and 2 because there is no option of the sticky header in those designs

**Comment by MohammedKaludi** [comment]
Then let's merge it

**Comment by pegazee** [comment]
Pushed in 0.9.97.52
