### ISSUE TITLE
Need another menu for alternative menu which separate from main menu

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2916]
For Swift:
(1) Can I use another menu for alternative menu which separate from main menu?
(2) How can I change the background and text color for dropdown support of alternative menu?

Ref: https://wordpress.org/support/topic/use-another-menu-for-alternative-menu-in-swift/

**Comment by MARQAS** [comment]
Why there is a second parameter for `amp_menu` ?

**Comment by Zabi09** [comment]
Removed the second parameter of amp_menu in this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2958

**Comment by pegazee** [comment]
Dropdown support for the alternative menu is showing but the styling is not working. I've selected the background color & text color for Alternative menu and the dropdown is showing like this : https://take.ms/eX1TV

**Comment by RajuJeelaga** [comment]
- [ ] when Header design 2 is selected CSS are not loading
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/62deb605c8132e66eae90768fbffd8f92cc2073b#diff-037f48d1f4ebe70736221163d899a20b

https://monosnap.com/file/FOdABWo569V0SPDhG4UL31hchuyJUB

**Comment by RajuJeelaga** [comment]
After discussion with @Zabi09 , he will take care of this issue, when he is working.
on history, https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/62deb605c8132e66eae90768fbffd8f92cc2073b#diff-037f48d1f4ebe70736221163d899a20b

**Comment by MohammedKaludi** [comment]
When Turned off from options panel https://monosnap.com/file/Am8cWuS9S1lZ8xNP7ZBFAqFDXhCTkP

Menu settings are still visible  https://monosnap.com/file/YFvMpzJOg62qucrxSnutKAstKeDtK3

**Comment by MohammedKaludi** [comment]
Improve the condition https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d02239fb0ac7c13be32a0edfdb362a92556c40dc

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
