### ISSUE TITLE
API URL conflict with Mobile redirection

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2917]
if mobile redirection is enabled then API URL is not working as /amp get added to API URL.

Ref: https://secure.helpscout.net/conversation/787857204/56947?folderId=673452

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
