### ISSUE TITLE
Date archive pages are not working in AMP version

### ISSUE THREAD

**Issue by WasimAlam93** [ahmedkaludi/accelerated-mobile-pages#2918]
Ref:  https://secure.helpscout.net/conversation/787453133/56903?folderId=2728743

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2514

**Comment by MARQAS** [comment]
The code is added in beta and it is working fine in beta. We can directly add this ticket in master
