### ISSUE TITLE
Update Schema for author image

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2919]
Ref: https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/2369/

**Comment by MARQAS** [comment]
Please update the Vendor as well.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
