### ISSUE TITLE
pricing module content is not center in page builder

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2921]
Here's the screenshot: https://prnt.sc/mqp5l2

Ref: https://secure.helpscout.net/conversation/787328476/56884/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
