### ISSUE TITLE
itms-services link not working

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2922]
You can visit this URL follow Link1 & Link2 text using amp mode and switch to desktop mode to check it.

Link: http://bit.ly/2GPA8og

Screenshot: https://take.ms/BeFL9

Ref: https://wordpress.org/support/topic/ios-itms-services-link-cant-work/

* Recreated on my local server

**Comment by Zabi09** [comment]
It is giving validation error - Invalid URL protocol 'itms-services:' for attribute 'href' in tag 'a'

**Comment by MohammedKaludi** [comment]
Itms-services protocol is not supported on AMP pages, created a ticket on amp's GitHub repo.

**Comment by pegazee** [comment]
Created a ticket on amp's GitHub repo : https://github.com/ampproject/amp-wp/issues/1948

**Comment by MARQAS** [comment]
https://github.com/ampproject/amphtml/issues/21225

**Comment by MARQAS** [comment]
We can do it only after they allow it and I don't think that's gonna happen very soon.
Let's revert it for now to avoid errors.

**Comment by honeybadgerdontcare** [comment]
Just fyi, this was added in June 2019 via https://github.com/ampproject/amphtml/pull/22925
