### ISSUE TITLE
When switching from Master to Beta Version the AMP Pagebuilder check box is getting unchecked

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2923]
You guys have given me a beta version Version 0.9.98-beta which we have installed and tested on a development site. But all our previously made AMP pages are no longer configured properly. To enable, we actually have to disable, enable the AMP Page Builder for every page that was previously created. Looking at the database, it seems you all have changed how you store the settings for each amp page. I have two questions on this part:

Ref:  https://secure.helpscout.net/conversation/773224702/54738?folderId=1914712

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by syedimran22** [comment]
@MARQAS the issue is still occurring at my end.

**Comment by Zabi09** [comment]
Not working on my end

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
This ticket is not relevant with the new codebase
