### ISSUE TITLE
Needs to re-write function ampforwp_add_custom_rewrite_rules

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2924]
ampforwp_add_custom_rewrite_rules function is running on init, this function runs on every refresh and trying to modify rewrite rules on every refresh. Needs to modify and create proper function to modify rewrite rules. same as for woocommerce supprot also.

**Comment by MARQAS** [comment]
Need to discuss with @MohammedKaludi

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
1) Logic needs to be improved 

-> For Category https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9df22791c44563bbfe9442c2c41f938b2aaca159#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R129

-> For Permastrcture  https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9df22791c44563bbfe9442c2c41f938b2aaca159#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R153

-> For Tags https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9df22791c44563bbfe9442c2c41f938b2aaca159#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R171

-> For Taxonomies https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9df22791c44563bbfe9442c2c41f938b2aaca159#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R213

and 

-> For WooCommerce https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9df22791c44563bbfe9442c2c41f938b2aaca159#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R228

2) Transients are not resetting, what will happen if someone change the Category base name or Tag base name, it will not update according to the current code.

**Comment by MohammedKaludi** [comment]
This is still pending. 

Transients are not resetting, what will happen if someone change the Category base name or Tag base name, it will not update according to the current code.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
