### ISSUE TITLE
Need to add default height & width values for amp-img

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2925]
* User using the  ‘All in One Rich Snippets’ plugin to add the 'Rich Snippet' like this: https://take.ms/Ykr3R and the height value is not defined because of this getting validation issue.

Ref: https://wordpress.org/support/topic/latest-amp-errors/

Note:
Recreated the issue on local server

Non-amp version: https://take.ms/jd8YEr
AMP version: https://take.ms/9z8yu

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
