### ISSUE TITLE
Yoast meta data are not renderring correct content for custom home page.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2928]
Desc: Yoast metas are not renderring correct content for custom home page in single pages/post the content is loading 
example twitter description content or twitter title content.

Ref: https://secure.helpscout.net/conversation/756655532/50960?folderId=2169248

**Comment by Zabi09** [comment]
Not working when "latest posts" is selected in reading settings

**Comment by pegazee** [comment]
og:image, twitter:image and twitter:creator metas are not showing in amp

Screenshots:

og:image: 
* non-amp version: https://take.ms/r7fak
* amp version: https://take.ms/hMBqX

twitter:image:
* non-amp version: https://take.ms/I4Ay1
* amp version: https://take.ms/UFZ5p

twitter:creator: 
* non-amp version: https://take.ms/xZOUC
* amp version: https://take.ms/5pMSu

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ad66e2942a760c32a3a582b6e01df64d6c94286d#diff-6aa5512f7dd8d5ce60fc97b0f340912cR1505

`ampforwp_is_frontpage` condition is missing

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2962

**Comment by MohammedKaludi** [comment]
Failed : 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4740759edebac78982c0ccf949bd61c82acb66e5

**Comment by pegazee** [comment]
Pushed in 0.9.97.44.2

**Comment by vagu71** [comment]
Checking this on version 0.9.97.52. Titles, descriptions and og information is not being pulled up correct from Yoast.
