### ISSUE TITLE
instant articles Image issue

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2929]
in instant article, images are showing above the content even though the image is added after the content.

Ref: https://secure.helpscout.net/conversation/763070366/52337?folderId=1914715

**Comment by beingsmart3** [comment]
- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
