### ISSUE TITLE
AMP URL redirect to the normal URL

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/accelerated-mobile-pages#293]
The expected behavior would be to have the AMP URL redirect to the normal URL. Is there a function I can reference in order to use your checkbox with the amp_skip_post hook(https://wordpress.org/support/topic/function-to-disable-amp-on-specific-post/)?

https://wordpress.org/support/topic/hide-amp-on-specific-post-not-working/
Reported by @talkstory

**Comment by MohammedKaludi** [comment]
There are lot of issues after this commit, Rel=canonical are missing on the AMP pages

**Comment by MohammedKaludi** [comment]
Double reported Fixed in #332 
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/332
