### ISSUE TITLE
the nonamp link redirect me to an empty page ! 

### ISSUE THREAD

**Issue by AhmadTy** [ahmedkaludi/accelerated-mobile-pages#2930]
I checked all the files from the old similar issues and tried to put it once in the footer and once in the header but the redirect is still the same.
https://www.pack-und-wasch.de/
only on the homepage went to an empty page otherwise it repeats itself as amp I think it has something to do with the conditional logic of the redirects? 
Thanks a lot!

**Comment by Zabi09** [comment]
@AhmadTy I would recommend you to create a support request from https://ampforwp.com/support so our technical support developers can troubleshoot and help you fix them.

The Github issues are for valid and clear issues which can be tackled and be merged into the core of the plugin.

**Comment by AhmadTy** [comment]
Thank you will do

**Comment by AhmadTy** [comment]
Actually, I figured it out by myself and that was by deleting these functions  from the includes/redirect.php 

 // #1947 when nonamp=1 it should redirect to original link so that Google

it might be helpful for someone facing the same problem!
