### ISSUE TITLE
Rare Disorted image aspect ratio issue with gutenberg editor.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2931]
desc : Rare Distorted image aspect ratio issue with Gutenberg editor and users also provided wp-admin & FTP credentials.

URL: https://www.bmcars.pl/wizyta/amp/

Ref: https://secure.helpscout.net/conversation/789724216/57379?folderId=2169248

**Comment by beingsmart3** [comment]
Case Two

Ref:  https://secure.helpscout.net/conversation/755621603/50725?folderId=1914712
screenshot: http://take.ms/JMqvC

**Comment by beingsmart3** [comment]
Case Three:

Ref: https://secure.helpscout.net/conversation/755078719/50585?folderId=1914712
Screenshot: http://take.ms/QRtGY

**Comment by nicopujol** [comment]
Thanks for looking into this bug. More information at https://github.com/ampproject/amp-wp/issues/1838. Happy to test it for you when you have a plugin file.

**Comment by MARQAS** [comment]
@nicopujol can you update this function in our plugin and check if the issue is resolved or not? https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cf5970b0c2f021daa350fa389a52ef2ac70aa4e4#diff-9403c03929c0726e9201dac8cf66cbdcR223

**Comment by nicopujol** [comment]
Not sure I am reading the edits you are linking to correctly. I see accelerated-moblie-pages.php and *extractor.php. What do you want me to edit? If you can send me a link to the actual files to replace it would much easier. Thanks

**Comment by MARQAS** [comment]
Can you update the code of this( `accelerated-mobile-pages/includes/vendor/amp/includes/utils/class-amp-image-dimension-extractor.php` ) file with this one: https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/cf5970b0c2f021daa350fa389a52ef2ac70aa4e4/includes/vendor/amp/includes/utils/class-amp-image-dimension-extractor.php

**Comment by beingsmart3** [comment]
One more ref:  https://secure.helpscout.net/conversation/800661410/59398/
Screenshot:  http://take.ms/jR2Yr
actual image size:  http://take.ms/bwMnY

**Comment by nicopujol** [comment]
@MARQAS thanks for the file. I saved the Raw from link into PHP file and replaced it in the plugin, but got an error 500 on AMP pages. Something crashes the server. Perhaps I did not save it correctly?

**Comment by MARQAS** [comment]
I guess you have directly added the file, that file is in beta and with namespaces. 
You have to do some modifications. Remove the namespaces from the top and from the function names. 
Or if you are having some difficulty with it then please contact our team they will help you with it.

**Comment by nicopujol** [comment]
We'll wait for your next beta or GA build or if Support can send us one we can give you feedback right away.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
