### ISSUE TITLE
Need hyperlink option on the slider module image

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2932]
https://secure.helpscout.net/conversation/790992837/57641?folderId=2614130

**Comment by ahmedkaludi** [comment]
we have a easier way of doing this

**Comment by MohammedKaludi** [comment]
The hyperlink is working correctly but, 
Empty FigureCaption tags are loading 

https://monosnap.com/file/i2fbGaFm3B3IcLTXhIaWk1JUftLHbF

**Comment by MohammedKaludi** [comment]
No need to create a new control, 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b06344f0cfdcb2eb8196f5057d2321cf18b86f95#diff-b348b69191cd6a1782d8bf896214ff06R633


Check if existing caption is available then only it should add it.

**Comment by MARQAS** [comment]
@MohammedKaludi, it is developed as an Image module, suggested by @ajeetku. As far as I know, we can't control the markup based on the content inside of it.
We write the markup based on the options, then change it with the content.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
