### ISSUE TITLE
Issue with pagebuilder when yoast plugin is active.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2933]
Desc: issue with contact form module when yoast plugin is active.

https://monosnap.com/file/Q6NqgSwiJ3tkflQPo6qj0iFCPc3CYR

Ref: https://secure.helpscout.net/conversation/790892333/57615?folderId=2169248

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/784738765/56458/
this is also the same issue please look into this. It's urgent.

**Comment by beingsmart3** [comment]
https://secure.helpscout.net/conversation/791871548/57799?folderId=1914712

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.39
