### ISSUE TITLE
When Gutenberg active left sidebar is not visible in page builder modules

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2934]
Ref: https://secure.helpscout.net/conversation/788170548/56998/

Screenshot of issue: https://prnt.sc/mtdl4x

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
