### ISSUE TITLE
Custom fields meta data is getting blank after version 0.9.97.36

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2935]
Def: Custom fields metadata is getting blank after version 0.9.97.36
screenshot: https://monosnap.com/file/l05UfO9dJ0tMbuENUuMxuoOGXg1nu4  (0.9.97.35)
screenshot: https://monosnap.com/file/L1iSEF1ER4Fxjpi7fYSIi3GbeXp1oE (from 0.9.97.36 onwards)

Ref: https://secure.helpscout.net/conversation/756655532/50960?folderId=2169248

**Comment by MARQAS** [comment]
A one-off issue, occurred only once on the user's end and unable to reoccur it again. 
We are closing this for now. We can reopen it when we get more insights on this.
