### ISSUE TITLE
AMP Theme Framework Multisite issue

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2936]
AMP Theme Framework Doesn't appear in the Theme Selector When it's activated in Network.
So We need to add the compatibility for Multisite Activate theme Frameworks.

Make sure that if it's Network Activate/Deactivated Works perfectly. 

`if(is_multisite()){
            $activePlugins_multi = get_site_option('active_sitewide_plugins');
            $activePlugins_multi = array_keys($activePlugins_multi);
            $activePlugins = array_merge($activePlugins, $activePlugins_multi);
        }`

Ref:  https://secure.helpscout.net/conversation/789987318/57439?folderId=1914712

**Comment by pegazee** [comment]
**  Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
