### ISSUE TITLE
404 issue on custom post type pagination

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2937]
Custom post type pagination is giving 404 error when we redirect to page/2 while the endpoint is /amp.
 screenshot: https://monosnap.com/file/sXzPdmidmiBtLzF0pz4K0716exSXei

solution: there is no rewrite rule is written for custom post type pagination 
add this code in accelarated-mobile-pages.php file to solve the issue

                                  add_rewrite_rule(
				      $post_type.'\/amp/'.$wp_rewrite->pagination_base.'/([0-9]{1,})/?$',
				      'index.php?amp&post_type='.$post_type.'&paged=$matches[1]',
				      'top'
				   );
https://monosnap.com/file/MPZGB0Bf9qJUCn7J2A2wTh9foS6rIm
https://monosnap.com/file/vZVYXNzn5RNLePOBzi44mxPywmabTP

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
