### ISSUE TITLE
Sidebar Styling is not properly appearing in the Blog Page

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2938]
Ref:  https://secure.helpscout.net/conversation/781213665/55924?folderId=1914712

screenshot:  http://take.ms/eQKa7

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
