### ISSUE TITLE
Controls under swift design should display when selected design is AMP theme framework

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2939]
Create a function where the user can control the setting options from the setting panel like sidebar, typography etc.

currently is not showing when the selected design is AMP theme Framework
https://monosnap.com/file/oOgTBZMHGZOBTH6WsBA2qJ7N37QHna

**Comment by MARQAS** [comment]
With the help of this, users can enable the required options in the AMP Options Panel when AMP Theme Framework is activated. 
Example Code: 
`
add_filter('ampforwp_options_enabler','ampforwp_new_options');
function ampforwp_new_options($options){
	$options = array('header-type');
	return $options;
}`

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by ansaritalha** [comment]
if we are adding parent array id to show an option it's child array also get calling and showing child item.

example: if we are adding sidebar array id then it's child item are also showing in AMP option panel.
https://monosnap.com/file/QvPPSAYKy2oq4XT4izrxUrKM6xvzA5

Create a filter so we can remove the child options.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55

**Comment by MohammedKaludi** [comment]
need to improve the documentation before closing the ticket.

**Comment by pegazee** [comment]
Created card for the documentation:
https://trello.com/c/nut1nUFP/384-need-to-create-documentation-for-unwanted-amp-options-when-using-the-amp-theme-framework
