### ISSUE TITLE
validation issue in enfold theme

### ISSUE THREAD

**Issue by aleemahmed2003** [ahmedkaludi/accelerated-mobile-pages#294]
Hi Ahmed

The AMP validator throws up some errors that you may be interested in:

a. On this page https://hi-flyfoto.de/luftaufnahmen-kontakt-angebot?amp I use the plugin “WP Mailto Links – Manage Email Links” to protect the email address. This leaves a javascript error in the AMP version.

b. On the start page https://hi-flyfoto.de/?amp there are many “CONTAINER” errors. It looks like this is related to the layout element “Grid Row” of the Enfold theme I use.

Perhaps these issues can be addressed in a future version
Kind regards
Michael

https://wordpress.org/support/topic/some-errors-found-by-google/
Reported by @camelotcamel

**Comment by khaledMohammed000** [comment]
a. can be solved but i cant guarantee that the Plugin you use will work in AMP : https://www.ampproject.org/docs/reference/spec#links

b. This looks like a small issue 👍

**Comment by ahmedkaludi** [comment]
The only possible solution to this is the Alternative Editor or AMP version. See #309
