### ISSUE TITLE
I got the following error message when I uploaded and activated AMP for WP

### ISSUE THREAD

**Issue by GailMP** [ahmedkaludi/accelerated-mobile-pages#2941]
I installed then activated AMP for wp and received the following error message:

![screen shot 2019-03-06 at 5 16 36 pm](https://user-images.githubusercontent.com/43189741/53920953-d35fd800-403c-11e9-834e-a8acc3324be3.png)

I deactivated the app and the files have remained... I'm not sure if this will impact the rest of the website or if the visitors will get any errors, etc. 
Please help to get this up and running or to remove it entirely from my website.

Thank you
Gail
panzigdesigns@yahoo.com

**Comment by Zabi09** [comment]
@GailMP Sorry for the inconvenience will you please provide us wp-admin and FTP details to check the issue and fix it on your end.

**Comment by GailMP** [comment]
Hello Syad.Sorry for the delay; I have someone working on code in the website and it probably isn't a good idea to have two people in there at the same time.They should be done Monday afternoon- I will send you the access info then.Many thanks for the quick reply, I'll be in touch then.Gail 

    On Thursday, March 7, 2019, 7:14:22 AM EST, Syed Zabiuddin <notifications@github.com> wrote:  
 
 
@GailMP Sorry for the inconvenience will you please provide us wp-admin and FTP details to check the issue and fix it on your end.
