### ISSUE TITLE
issue in display on User Avatar option

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#2942]
We are using @get_headers() method - https://monosnap.com/file/bo5n78RaOajmImBzb9H5rC7EgTlwmW and due to that it is breaking and can we remove it and add this method of get_avatar_data() - https://monosnap.com/file/2hQZrq4JfNDdsPziW155QzB3avsHjT instead

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/789830991/57412/

**Comment by MARQAS** [comment]
It can cause some performance issue, try to use wp_remote_get - @ajeetku

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
1. Remove unused code https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/953cb73e19e3de7cc708a35c43f36595b77043f2/templates/features.php#L4943

2. Create an empty variable `$url`

3. wrap it with if statement  like: `if ($url)` https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/953cb73e19e3de7cc708a35c43f36595b77043f2/templates/features.php#L4955

**Comment by MohammedKaludi** [comment]
add response code as well insdide the condition
$response_code = wp_remote_retrieve_response_code($response);

**Comment by MohammedKaludi** [comment]
👍

**Comment by pegazee** [comment]
Pushed 0.9.97.44.2
