### ISSUE TITLE
Home page displays latest posts instead of custom page. issues is occurring due to enfold theme when we select the option display blog post then it occurs if we keep it default it doesn't

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#2943]
Ref this link: https://secure.helpscout.net/conversation/788178829/57031?folderId=2632030

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by Zabi09** [comment]
Enable this option to recreate the issue in blog layout option - https://prnt.sc/n8x467

**Comment by MohammedKaludi** [comment]
:+1: Ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
