### ISSUE TITLE
Edit page is getting blank when product module is used.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2944]
Desc: Edit page is getting blank when product module is used and the conflict is rendering when Yoast plugin and ampforwp 0.9.97.39 version activated if we rollback to 0.9.97.35 edit page is displaying correctly.

Ref: https://secure.helpscout.net/conversation/791544799/57718?folderId=2169248

And the issue is with this  line of code so need to add an option for this. https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/928b70774208bf5ade7c7906feaee70af64c3c00/pagebuilder/amp-page-builder.php#L136

**Comment by syedimran22** [comment]
Check the required condition of the option @MARQAS

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
The issue is not replicated on the local server while testing

**Comment by MohammedKaludi** [comment]
Looks good 👍

**Comment by pegazee** [comment]
Pushed 0.9.97.44.2
