### ISSUE TITLE
YoastSEO post analysis broke & getting Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2948]
Ref: https://wordpress.org/support/topic/yoastseo-post-analysis-broke/

Note: Need to test on the local server.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
Issue not recreated on the local server while testing

**Comment by MohammedKaludi** [comment]
Looks good 👍

**Comment by pegazee** [comment]
Pushed 0.9.97.44.2
