### ISSUE TITLE
Need to implement Tree Shaking feature to remove access css from the AMP pages

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2949]

**Comment by MARQAS** [comment]
Not working if I add Additional CSS in Custom CSS option through the class of the element. 
Steps to recreate: 
1. Select the Custom FrontPage in AMP
2. Add Additional styling in Custom CSS option through the class name of the element
3. for example: `.amp-frontpage{background:red;}`

**Comment by pegazee** [comment]
Working perfectly on my end

**Comment by pegazee** [comment]
But there is an issue when we're on the swift theme and tree shaking option is enabled. And I've changed the swift theme to design-2, the styling is breaking.

**Comment by pegazee** [comment]
When tree shaking ON and added some extra CSS by using the Custom CSS option, the CSS is not rendering.

**Comment by ajeetku** [comment]
Run customizer, to remove the fatal error, and the new codes will need to update from the master of PHP-CSS-Parser.

**Comment by ajeetku** [comment]
1. Put this complete tree shaking feature in a folder
2. This feature is not working with AMP by Automattic
3. remove unwanted code "processing link" element CSS urls / set_transient / get_transient style sanitizer
4. `if( ampforwp_get_setting('ampforwp_css_tree_shaking') ){`  Why this check is on add_filter
And this `ampforwp_purify_amphtml` function in features.php

**Comment by santosh8793** [comment]
Need a filter to replace or minify the name of classes and id, and also notify https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3320

**Comment by pegazee** [comment]
The changed are made in this commit. When committing this I didn't mention the ticket number sorry for this :-( 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9be14f21

**Comment by MohammedKaludi** [comment]
Need to rename the label, "CSS Tree Shaking" to Optimize CSS

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
