### ISSUE TITLE
Upgrade amp-sticky-ad sticky component to 1.0"

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#295]
Google systems have detected that your site uses the library version amp-sticky-ad-0.1.js.This version will be deprecated on January 15, 2017, at which point the version of the JS library will be automatically upgraded to amp-sticky-ad-1.0.js. This automatic upgrade may prevent serving ads on your site. Please upgrade the usage of amp-sticky-ad on your site to use the new version to avoid any issues.

**REF:** https://secure.helpscout.net/conversation/292063671/10088/?folderId=1060551

**Comment by MohammedKaludi** [comment]
Fixed in Advance amp ads in version 1.3
