### ISSUE TITLE
Need to implement amp-video-docking feature 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#2950]

**Comment by MARQAS** [comment]
Error: The attribute 'dock' requires including the 'amp-video-docking' extension JavaScript.

**Comment by MARQAS** [comment]
Notice: Undefined index: amp-video in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 7802
--

**Comment by ajeetku** [comment]
Use the proper approach to add docking script
In this current situation, if any amp-video tag exists, it will also add dock script, without checking dock attribute exists or not. 
Check AMP_Video_Sanitizer Class to checking attributes

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Not working.

**Comment by Zabi09** [comment]
Will you please add this video and check again - https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

I have tested it and working on my end.

Added - https://prnt.sc/nk7x63
Output - https://prnt.sc/nk7x99

**Comment by MohammedKaludi** [comment]
Not working with YouTube.

**Comment by MohammedKaludi** [comment]
Docking is working perfectly fine, on-off control is needed and by default it should be on.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by WasimM3** [comment]
This ticket is moved in #4352. So closing this one
