### ISSUE TITLE
Warning: Illegal string offset When AMP layout plugin activate

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2951]
Ref: https://wordpress.org/support/topic/amp-layouts-not-works/

`Warning: Illegal string offset 'amp-on-off-for-all-pages' in /home/xxx/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 69

Warning: Illegal string offset 'ampforwp-homepage-on-off-support' in /home/xxx/wp-content/plugins/accelerated-mobile-pages/install/index.php on line 74`

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.47
