### ISSUE TITLE
Duplicate SiteNavigationelement

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2952]
When Schema and structured plugin is getting activated the SiteNavigationelement should be removed which is generating from the AMPforwp plugin.

Check this screenshot: http://take.ms/55pT0

Ref:  https://secure.helpscout.net/conversation/744272001/47982?folderId=1914712

**Comment by MARQAS** [comment]
Let's do it with hooks/filters instead of adding it statically.

**Comment by Zabi09** [comment]
If the Schema plugin is disabled then it is showing twice - https://prnt.sc/my54bn

**Comment by MARQAS** [comment]
One is for the main menu and other for the footer menu.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
What will happen if the schema plugin is deactivated? Because the static schema has been removed?

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
