### ISSUE TITLE
Notice errors in design-1 sidebar menu when amp menu is unchecked.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2953]
Desc: Notice errors in design-1 sidebar menu when amp menu unchecked.

Notice: Trying to get property 'before' of non-object in C:\xampp\htdocs\imran\wp-content\plugins\accelerated-mobile-pages\classes\class-ampforwp-walker-nav-menu.php on line 69

**Comment by MARQAS** [comment]
Use the conditional operator

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
