### ISSUE TITLE
Heading module is having same heading type text size H1 to H6

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2955]
Ref: https://secure.helpscout.net/conversation/798780908/58896?folderId=2614130
 Screenshot: https://monosnap.com/file/rHOX4GtT5FivzFs7jihrTTkL0sOu1Y
                    https://monosnap.com/file/cy73YNN9Xv7ayYlsGf57LxFb8SkRul

**Comment by RajuJeelaga** [comment]
We already have an option for that https://monosnap.com/file/2YONKq9ofClKkQg5mbgfX9bbYNRugn
informed the user as well.... closing this ticket..
