### ISSUE TITLE
AMP Posts-type pages being created, But not AMP Pages

### ISSUE THREAD

**Issue by nanhann** [ahmedkaludi/accelerated-mobile-pages#2956]
I see that this issue came up before, but it's still happening on our site.

We made some adjustments to our Accelerated Mobile Pages plugin to get optimal performance out of it, but noticed that even though the option to serve your site’s Pages is selected, Pages will not serve up in AMP versions. Blog Posts do but not Pages. 

Please advise.

Thank you.

**Comment by MARQAS** [comment]
Hi @nanhann, Can you tell me what are the changes you have made in the Plugin? Maybe it is causing this issue. 
Because you are the only use-case who is facing this issue.

I suggest you, to contact our team at team@magazine3.com and discuss this with them and I am sure they will help you with it.

**Comment by nanhann** [comment]
Hello Mohammed,

By changes, do you mean settings? Is there a particular section of the settings that you think may impact it? I’m including a screenshot of the general section.


        [cid:image003.png@01D4D98B.598818C0]





Thanks so much!
Nancy

**Comment by MARQAS** [comment]
@nanhann, I am talking about the code changes, as you have mentioned that you are making some changes in code. 
If you are making any changes in the code then please let us know.
Or else I will suggest you to contact us at team@magazine3.com

**Comment by nanhann** [comment]
-- Please reply above this line --


            Hi Nancy,

Hope you are doing good.

This the only settings have you changed or else you have made the
changes in coding also?

Please let me know so that I can help you to resolve the issue ASAP.

Thanks and Regards,
Sravan
AMPforWP Customer Sucess Team 
(About Our Team [1])

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://bit.ly/2q5UQW9
[2]
https://secure.helpscout.net/satisfaction/243069142/record/2233928951/1/
[3]
https://secure.helpscout.net/satisfaction/243069142/record/2233928951/2/
[4]
https://secure.helpscout.net/satisfaction/243069142/record/2233928951/3/

**Comment by nanhann** [comment]
Hi Mohammed,

We haven’t made any changes to the code.

Thanks,
Nancy

**Comment by nanhann** [comment]
-- Please reply above this line --


            Hi Nancy,

We are working on your GitHub ticket -
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2956
[1] and for testing purpose will you please provide us wp-admin and
FTP details and we will check your issue and we will fix it on your
end,

Warm Regards,
Syed Zabiuddin

Links:
------
[1]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2956

AMPforWP Customer Sucess Team 
(About Our Team [1])

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://bit.ly/2q5UQW9
[2]
https://secure.helpscout.net/satisfaction/243069142/record/2263073417/1/
[3]
https://secure.helpscout.net/satisfaction/243069142/record/2263073417/2/
[4]
https://secure.helpscout.net/satisfaction/243069142/record/2263073417/3/

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/800884505/59446?folderId=1060556

**Comment by nanhann** [comment]
Hello Syed,

Is this what you need?

https://info.aladvantage.com/wp-login.php?loggedout=true
User: TempSupport
Pw: U*N$qZN6f*AgulY$)oCvQIh6


FTP User: Tempsupport@info.aladvantage.com
PW: ALAtemp032019
FTP Server: ftp.info.aladvantage.com
The default FTP port is 21.

Let me know if you need more info.

Thanks,
Nancy Hann

From: support.8223.cfb9786cbb6b9b7c@helpscout.net <support.8223.cfb9786cbb6b9b7c@helpscout.net> On Behalf Of AMPforWP
Sent: Wednesday, March 27, 2019 6:54 AM
To: Nancy Hann <nancy@aladvantage.com>
Cc: reply@reply.github.com; accelerated-mobile-pages@noreply.github.com; mention@noreply.github.com; david@searchrank.com; team@magazine3.com
Subject: RE: [ahmedkaludi/accelerated-mobile-pages] AMP Posts-type pages being created, But not AMP Pages (#2956)

Hi Nancy,

We are working on your GitHub ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2956 and for testing purpose will you please provide us wp-admin and FTP details and we will check your issue and we will fix it on your end,

Warm Regards,
Syed Zabiuddin

AMPforWP Customer Sucess Team
(About Our Team<https://bit.ly/2q5UQW9>)

How would you rate my reply?
Great<https://secure.helpscout.net/satisfaction/243069142/record/2263073417/1/>    Okay<https://secure.helpscout.net/satisfaction/243069142/record/2263073417/2/>    Not Good<https://secure.helpscout.net/satisfaction/243069142/record/2263073417/3/>
{#HS:800884505-59446#} [https://secure.helpscout.net/notification/convo/read/800884505/2263073417/]
On Fri, Mar 15, 2019 at 11:34 AM IST, AMPforWP <team@ampforwp.com<mailto:team@ampforwp.com>> wrote:
Hi Nancy,

Hope you are doing good.

This the only settings have you changed or else you have made the changes in coding also?

Please let me know so that I can help you to resolve the issue ASAP.

Thanks and Regards,
Sravan

AMPforWP Customer Sucess Team
(About Our Team<https://bit.ly/2q5UQW9>)
On Wed, Mar 13, 2019 at 8:26 PM IST, Nancy Hann <nancy@aladvantage.com<mailto:nancy@aladvantage.com>> wrote:
Hello Mohammed,

By changes, do you mean settings? Is there a particular section of the settings that you think may impact it? I'm including a screenshot of the general section.


[https://d33v4339jhl8k0.cloudfront.net/inline/8223/66221b55d2f4e24d0114d9382c91e3b2bbee1cd6/6da9fed29ee001486e551c02d52a52263d99687e/image003.png]






Thanks so much!
Nancy

**Comment by MARQAS** [comment]
Hi @nanhann, I am sorry I have just deleted your comment, please don't share your admin details in the public, We have received your email and we will work on it. Thank you.

**Comment by nanhann** [comment]
OH, so sorry. I didn’t realize that the email posted to the support site.

Thanks so much!
Nancy

**Comment by nanhann** [comment]
How do I send the login info privately?

Thanks

From: Nancy Hann
Sent: Thursday, March 28, 2019 10:19 AM
To: 'ahmedkaludi/accelerated-mobile-pages' <reply@reply.github.com>; ahmedkaludi/accelerated-mobile-pages <accelerated-mobile-pages@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ahmedkaludi/accelerated-mobile-pages] AMP Posts-type pages being created, But not AMP Pages (#2956)

OH, so sorry. I didn’t realize that the email posted to the support site.

Thanks so much!
Nancy

**Comment by nanhann** [comment]
I just want to be sure I’m using the right email.

Thanks so much!
Nancy

From: Nancy Hann
Sent: Thursday, March 28, 2019 10:34 AM
To: ahmedkaludi/accelerated-mobile-pages <reply@reply.github.com>; ahmedkaludi/accelerated-mobile-pages <accelerated-mobile-pages@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ahmedkaludi/accelerated-mobile-pages] AMP Posts-type pages being created, But not AMP Pages (#2956)

How do I send the login info privately?

Thanks

From: Nancy Hann
Sent: Thursday, March 28, 2019 10:19 AM
To: 'ahmedkaludi/accelerated-mobile-pages' <reply@reply.github.com<mailto:reply@reply.github.com>>; ahmedkaludi/accelerated-mobile-pages <accelerated-mobile-pages@noreply.github.com<mailto:accelerated-mobile-pages@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [ahmedkaludi/accelerated-mobile-pages] AMP Posts-type pages being created, But not AMP Pages (#2956)

OH, so sorry. I didn’t realize that the email posted to the support site.

Thanks so much!
Nancy

**Comment by Zabi09** [comment]
You can send it directly to our email - team@magazine3.com and we will test it and let you know

**Comment by Zabi09** [comment]
Fixed the issue on the user's end.
