### ISSUE TITLE
Published Date Disappear When selecting Horizontal Design in Related Post

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2957]
Ref:  https://secure.helpscout.net/conversation/794268044/58139?folderId=1914712

Screenshot:  http://take.ms/Xnz0N

**Comment by Zabi09** [comment]
Not working in master but working in beta #1545

**Comment by MARQAS** [comment]
Can we do something about it @Zabi09?
Can we resolve it without referring to that ticket?

**Comment by MohammedKaludi** [comment]
Good to go

**Comment by pegazee** [comment]
Pushed 0.9.97.44.2
