### ISSUE TITLE
When Debug is true appearing more notices.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#2958]
Ref: https://secure.helpscout.net/conversation/798211875/58800?folderId=2632030

**Comment by pegazee** [comment]
One more user requested regarding the illegal string offset notices here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1077

**Comment by pegazee** [comment]
One more: 

ref: https://wordpress.org/support/topic/cant-use-plugin-5/

**Comment by pegazee** [comment]
Notice: Undefined variable: seopress_social_og_title in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\thirdparty-compatibility.php on line 1120

Notice: Undefined variable: seopress_social_og_desc in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\thirdparty-compatibility.php on line 1142

**Comment by pegazee** [comment]
Notice: Undefined variable: seopress_social_og_title in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\thirdparty-compatibility.php on line 1120

Notice: Undefined variable: seopress_social_og_desc in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\thirdparty-compatibility.php on line 1142

Notice: Undefined variable: post_types in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\pagebuilder\modules\contents-module.php on line 180

Notice: Undefined variable: post_types in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\pagebuilder\modules\contents-module.php on line 181

Notice: Undefined variable: categoriesArray in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\pagebuilder\modules\contents-module.php on line 194

Notice: Undefined variable: type in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\design-manager\swift\header.php on line 433

Notice: Undefined variable: type in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\design-manager\swift\header.php on line 435

Deprecated: define(): Declaration of case-insensitive constants is deprecated in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 1113

**Comment by MARQAS** [comment]
And also remove second parameter $type, when calling `amp_menu`.

**Comment by pegazee** [comment]
One more debug notice:

Notice: Undefined variable: post in C:\newxampp\htdocs\wp-2\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\redirect.php on line 185

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
Debug Notice Still appearing: http://take.ms/ZLXWt

@syedimran22 check at your end

**Comment by MARQAS** [comment]
Debug errors related to SEOPress will be resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3003

**Comment by syedimran22** [comment]
When feature image is not set getting notice error in design 2, 3.

Notice: Undefined variable: post_id in C:\xampp\htdocs\imran\wp-content\plugins\accelerated-mobile-pages\templates\design-manager\design-2\elements\featured-image.php on line 51

**Comment by pegazee** [comment]
@syedimran22 , 

Notice: Undefined variable: post_id, fixed in #2996

**Comment by syedimran22** [comment]
Ok @pegazee

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
