### ISSUE TITLE
Need to create Testimonial slider in AMP Page Builder

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#2960]
Ref: https://secure.helpscout.net/conversation/799574863/59040?folderId=2632030

Referer this ticket for more info.

**Comment by Garcicasti** [comment]
Thanks for having this request into account! can't wait to have it

**Comment by MohammedKaludi** [comment]
Design not looking good in 2 columns
Backend: https://take.ms/pvf4f 
Frontend: https://take.ms/MAXreX

**Comment by RajuJeelaga** [comment]
@MohammedKaludi sir, 
This ticket is for new design in the testimonial Module called "Testimonial slider", but you are checking in old testimonial design, Please see this
https://monosnap.com/file/NJTKiyvqUVQKaPN7gGgLUqFo6MQAnl

**Comment by RajuJeelaga** [comment]
After Discussion with @MohammedKaludi sir, 
Testimonial Module, the other design(other than testimonial design) need to fix the problem and we will push that code in this ticket only

**Comment by MohammedKaludi** [comment]
Design not looking good in responsive mode.
https://take.ms/mS9Nf

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
