### ISSUE TITLE
AMP validation error after 0.9.97.37 version

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#2961]
If we are adding the background image (as inline style) URL in the SVG/XML format in WordPress editor as it's giving an AMP validation error. https://monosnap.com/file/Mj8qqioSEK9a2FPUP5J0umvR1wmAP5

as "CSS syntax error in tag 'style amp-custom' - bad url" but in 0.9.97.37 and earlier version there is no validation error is occurring but in 0.9.97.38 and later version it's giving an amp validation error.

Ref: https://secure.helpscout.net/conversation/716672052/42245?folderId=1914715

example URL: 
https://www.protagonista.com.co/actores/video-tremendo-susto-la-pesada-broma-que-saco-de-casillas-al-actor-fabian-rios/amp/
https://ahealthyeatinglifestyle.com/what-is-hydrogen-water/amp

**Comment by MARQAS** [comment]
Error still persists

**Comment by Zabi09** [comment]
This issue is fixed in #2974 and the changes which we have made here are properly added in that ticket only. So closing this ticket.
