### ISSUE TITLE
Title issue on Homepage with Yoast if we select custom front page.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2962]
Title issue on Homepage with Yoast if we select custom front page.
Ref: https://secure.helpscout.net/conversation/788368328/57099?folderId=2322649
Ref: https://secure.helpscout.net/conversation/787612363/56914?folderId=2322649

**Comment by pegazee** [comment]
** review  **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.45
