### ISSUE TITLE
Nav & alternate menu css is not loading when directory plus theme is active.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2963]
Def: Nav & alternate menu css is not loading when directory plus theme is active.
screenshot: https://monosnap.com/file/7WPGBovrsu0HP9m0VL81jYOdH4Vi8f
issue recreated in localhost
Ref: https://secure.helpscout.net/conversation/801173117/59480?folderId=2169248

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by ansaritalha** [comment]
When I activate the directory plus theme and add the search widget above the footer it's giving AMP validation error.
see this screenshot: https://monosnap.com/file/diJg42IjpzgvyjuVqLP9pL3cgNb7de

**Comment by Zabi09** [comment]
Search widget error will be fixed in #3000

**Comment by MohammedKaludi** [comment]
Use an existing hook instead of creating a new one.   

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3732648f84c7fd2d85bda5624e0793ca925d013a#diff-1301281de287d2aed98746fc9ba777b4R1434

**Comment by MohammedKaludi** [comment]
Ready :+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
