### ISSUE TITLE
$ is not defined in the function AmpForWpYoastAnalysis

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#2964]
Ref: https://secure.helpscout.net/conversation/785138166/56497?folderId=2632030

All the details are in the ticket.

**Comment by pegazee** [comment]
Solved in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2948, We can tackle the ticket there. I'm closing this ticket.
