### ISSUE TITLE
Thumbnails not displaying in Design 1, 2 & Swift

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2966]
Ref:  https://secure.helpscout.net/conversation/800661410/59398/

The images on the homepage and related articles are not showing when I use theme 1, theme 2 and swift theme. They only show at theme 3.

for more details feel free to contact me.

**Comment by Zabi09** [comment]
Fixed in - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2659

**Comment by MARQAS** [comment]
Not fixed, it is still in failed, what's the solution?

**Comment by Zabi09** [comment]
The main issue is fixed in that ticket and now it fails due to a debug warning but the code of that ticket is working fine on the user's end.

**Comment by MARQAS** [comment]
Yes, but we have to resolve the debug warning. And if it is related to that ticket, close this one.

**Comment by Zabi09** [comment]
Fixed in - #2659

So closing this ticket
