### ISSUE TITLE
Hyperlink in amp pages including emoji

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2967]
Ticket No:  #8769 - Hyperlinks Did Not Appear on the AMP Pages

**Comment by MARQAS** [comment]
ref: https://secure.helpscout.net/conversation/805349965/60215/

**Comment by pegazee** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2556

**Comment by MohammedKaludi** [comment]
in class, it is not required to add a prefix

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/15f08f5e8b892ef3e113876f469c77caa9e66756#diff-9253027ab0fd0dc36f48733d5f042541R233

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52

**Comment by MohammedKaludi** [comment]
Tested on users webiste. Working as expected.
Ready to merge into master.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.53
