### ISSUE TITLE
Disquss comment is not scrollable in IOS device

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2970]
Ref: https://secure.helpscout.net/conversation/798530320/58861?folderId=2614130

Screenshot: https://prnt.sc/n1eehy

**Comment by RajuJeelaga** [comment]
Discuss Comments scroll-able is working fine in IOS

@ms-hasan Please check properly and let me know.

**Comment by MARQAS** [comment]
It was one off issue which seems to be resolved, we can reopen this ticket when we found the actual cause.

**Comment by ms-hasan** [comment]
Disqus Comment is not the scrollable issue.

Solution of this issue:
.amp-disqus-comments amp-iframe, .amp-disqus-comments iframe{
    overflow: auto; overflow-y:scroll;
    -webkit-overflow-scrolling: touch;}
.amp-disqus-comments iframe{
width:100%;
height:300px;
}

**Comment by MohammedKaludi** [comment]
use `get_setting` while merging

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
