### ISSUE TITLE
The tag meta name 'viewport' appear more than once in the document in Zox news theme.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2971]
Desc: The tag meta name 'viewport' appear more than once in the document in Zox news theme.

Ref: https://secure.helpscout.net/conversation/804183573/60052?folderId=2169248

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Instead of removing our viewport, remove the code added by zox theme instead

**Comment by Zabi09** [comment]
Zox theme is adding the viewport statically and due to that, we cannot remove it, So removing our viewport.
https://monosnap.com/file/8ojoyJSg6yipcLtC6Es3viWodCqYAK

**Comment by MohammedKaludi** [comment]
Okay

**Comment by pegazee** [comment]
Pushed in 0.9.97.49
