### ISSUE TITLE
Rare issue with Romanian diacritics in settings panel.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2973]
If we add Romanian diacritics in the settings panel, then some fields like CSS, translation, fonts are getting empty.
Ref: https://secure.helpscout.net/conversation/792413049/57868?folderId=2322649

**Comment by pegazee** [comment]
The issue is occurring due to the user's site database. The utf-8 character is not converting in the wp_option table on the user side. 

Closing this ticket.

**Comment by bogdancraznic** [comment]
Ok. Thank you very much.

Bogdan C., 0760238051, centraletermicecluj.ro
