### ISSUE TITLE
Space after the "data:image/png" part of the base64 encoded CSS background image 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2974]
Ticket No. : #8811

HelpScout Link: https://secure.helpscout.net/conversation/807961850/60648?folderId=2770545

Use this code to solve this issue:

add_filter( 'the_content', 'fix_amp_space' );

function fix_amp_space( $content ) {
if ( is_amp_endpoint() ) {
return str_replace('data:image/png; base64,', 'data:image/png;base64,', $content);
}
return $content;
}

**Comment by MARQAS** [comment]
The code provided above may not be valid in all conditions and it is not a safe practice. Check style sanitizer.

**Comment by MARQAS** [comment]
Is this related to https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2961?

**Comment by nevma** [comment]
Actually this is a code provided as a fix on top of the error. The error should not be there in the first place from the core.

**Comment by pegazee** [comment]
To test Please add below the code in the post editor:

`<div style="background: #F8F8F8; line-height: 0; margin-top: 40px; padding: 62.5% 0; text-align: center; width: 100%;" >
<div style="background: url(data:image/png; base64,ivborw0kggoaaaansuheugaaacwaaaascamaaaapwqozaaaabgdbtueaalgpc/xhbqaaaafzukdcak7ohokaaaamuexurczmzpf399fx1+bm5mzy9amaaadisurbvdjlvzxbesmgces5/p8/t9furvcrmu73jwlzosgsiizurcjo/ad+eqjjb4hv8bft+idpqocx1wjosbfhh2xssxeiyn3uli/6mnree07uiwjev8ueowds88ly97kqytlijkktuybbruayvh5wohixmpi5we58ek028czwyuqdlkpg1bkb4nnm+veanfhqn1k4+gpt6ugqcvu2h2ovuif/gwufyy8owepdyzsa3avcqpvovvzzz2vtnn2wu8qzvjddeto90gsy9mvlqtgysy231mxry6i2ggqjrty0l8fxcxfcbbhwrsyyaaaaaelftksuqmcc); display: block; height: 44px; margin: 0 auto -44px; position: relative; top: -22px; width: 44px;"></div>
</div>
<p><a href="https://www.ampforwp.com" target="_blank">A post shared by Zoro</a></p>
</div> `

**Comment by MARQAS** [comment]
Try to add this code and some text after it, everything after it is getting blanked. 
https://pastebin.com/W1qdyMJ8

**Comment by pegazee** [comment]
I've checked on my end by using this code: https://pastebin.com/1pVXD9Mz. And also I've analyzed that inline style for background URL ( with base 64) is not working when minify option is enabled

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pra85** [comment]
Is there an ETA for the release of version 0.9.98? 

Mainly asking because the commit which fixes this problem has been tagged with 0.9.98

**Comment by pegazee** [comment]
@pra85, It will be added in the v0.9.97.48 and we're planning to release this update in this week.

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
