### ISSUE TITLE
More than one canonical issue with Rank Math SEO Plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2975]
Ticket No.: #59422

Helpscout Link: https://secure.helpscout.net/conversation/800849463/59442?folderId=2770545

**Comment by showmetech** [comment]
Hey guys, any news?

**Comment by Zabi09** [comment]
The problem appears again if we enable AMP support in rank math seo - https://prnt.sc/n3h0sm

**Comment by MARQAS** [comment]
@Zabi09, It is not working in Localhost. can you check again on garage?

**Comment by Zabi09** [comment]
Tested on 000webhost and it was working.

**Comment by ahmedkaludi** [comment]
another issue: https://wordpress.org/support/topic/duplicate-relcanonical-tags/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.46

**Comment by zheive** [comment]
Have the same issue in my websites with last version.
![Captura de pantalla_2019-10-01_07-42-46](https://user-images.githubusercontent.com/8024464/65937128-20632b80-e41f-11e9-977f-749063a69c6d.png)

**Comment by kaustubhk24** [comment]
Hello I have just found solution
See If you this AMP plugin and Rank math seo . then you will see this problem.

Just Go WP Dashboard--> Rank Math Seo -->Dashboard-->Scroll down --> Turn on AMP option  
and then clear cache if you have any plugin for caching. and test your problem will be solved :)

**Comment by MohammedKaludi** [comment]
> Have the same issue in my websites with last version.
> ![Captura de pantalla_2019-10-01_07-42-46](https://user-images.githubusercontent.com/8024464/65937128-20632b80-e41f-11e9-977f-749063a69c6d.png)

yes @zheive,
As @kaustubhk24 mentioned RankMath might not be configured properly from the options panel.

Please follow the above instructions and also make sure the RankMath is selected in AMP options panel as well. Check this screenshot: https://monosnap.com/file/UXpDF1BzqJ8ftY15Gsuk6iZ8ZKA8Pb
