### ISSUE TITLE
Fatal Error with Plugins manager

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#2976]
The recent updates are causing Fatal error with the older version of the Plugins Manager. 
Solution: Deactivate the older plugins manager and suggest user to update to the latest version of it.

**Comment by ajeetku** [comment]
If any user has directly downloaded from GitHub and installed then `-master` is added in the folder name.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
looks good can be merged into master

**Comment by pegazee** [comment]
Pushed in 0.9.97.44.1
