### ISSUE TITLE
Need to improve AMP panel tabs & Enhance the Support tab

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#2980]
Screenshot: https://take.ms/CVsSL

- [x] Need to remove the 'Get Stable Update' section in the "Setup AMP Feature" tab ( as we discuss this with @ahmedkaludi ), Screenshot: https://take.ms/8wsA6

- [x] Need to rewrite or update the numerical points and the links in the "Setup AMP Feature" tab ( as links are not properly redirecting to its destination & as we discuss this with @ahmedkaludi ). Screenshot: https://take.ms/nqRrN

- [x] What is the use of these tabs ( screenshot: https://take.ms/Wu3N8 , https://take.ms/sfSA2 ). Need to discuss this with @ahmedkaludi 

- [x] Need to update the changelog section on "Welcome to AMP" tab. Screenshot: https://take.ms/pS3eX, Issue connected to this  ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1753

- [x] Need to change the description of a plugin which appeared in the Wordpress site.
             - [ ] Change "community" link ( https://take.ms/WDSDsZ )
             - [ ] change " Premium Support" to Support & also add a description for free support (https://take.ms/RJpk0)
             - [ ] Change "GETTING STARTED" section

- [ ] Need to enhance or create a Support/Need help tab/button ( as we discuss this with @ahmedkaludi ), it will open a popup/lightbox and it will show 3 accordions/tabs [ We can resolve it here: #405] (
- Video Tutorial 
- Documentation/knowledge base
- Get Support )
And in the Documentation/knowledge base accordion/tab, add search engine like this: https://take.ms/HWEfK . When we search it should show links of tutorials like this: https://take.ms/gDyxd

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by pegazee** [comment]
5 task lists are pushed in 0.9.97.44 and I'm not closing this ticket because we need to do last task list issue.

**Comment by MARQAS** [comment]
We can do that part in #405, closing this ticket.
