### ISSUE TITLE
Footnotes not working properly bug reported

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2982]
Help Scout Link: https://secure.helpscout.net/conversation/813393398/61420/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50

**Comment by akashagrjsr** [comment]
Help Scout Link: https://secure.helpscout.net/conversation/865281819/68977?folderId=2770545

The issue is still at the user end. We have users wp-admin credentials.

**Comment by MohammedKaludi** [comment]
Styling of plus mark is broken.

https://take.ms/olOV0

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
