### ISSUE TITLE
 Automatically placing a "\" before the "/" and "\"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2984]
Help Scout Link: https://secure.helpscout.net/conversation/813779880/61558?folderId=2770545

**Comment by akashagrjsr** [comment]
In Alexa Analytics, What seems to be happening is that the system is automatically placing a "\" before the "/". For acc no.  "xyzzzyzx08xx/z" it is appearing like this in the code: "xyzzzyzx08xx\/z".

**Comment by MohammedKaludi** [comment]
Ready to merge, also need to notify the user once the issue is pushed.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Wrong variable

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/572bf92a9d32517abdc77830ecefa41c8b1c2b6b#diff-b27b16759fae0fb0d94cc6e00107c8efR211

**Comment by MohammedKaludi** [comment]
Failed:

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bfdb72f6274f2b4bb9925e31079425b1c2d074af#diff-b27b16759fae0fb0d94cc6e00107c8efR217

**Comment by MARQAS** [comment]
Resolved in #2287

**Comment by MohammedKaludi** [comment]
Merged with #2287 and the code will be pushed in 0.9.97.47

**Comment by pegazee** [comment]
Pushed in 0.9.97.47
