### ISSUE TITLE
Change Homepage Thumbnail size in design three theme

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2986]
Help Scout Link: https://secure.helpscout.net/conversation/815909062/61926?folderId=2770545
In design three themes there is no option to change the thumbnail Image size for the homepage.

**Comment by ahmedkaludi** [comment]
Make sure the size changes on the frontend as well,

**Comment by MARQAS** [comment]
Width and height are changing, but the image is cropped with the old values only. 
https://monosnap.com/file/prl8QzhGnCVeawoIajCufS5XJzVFo3

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
1. Position of the control. https://take.ms/N4WJX
2. Labeling should be "Override Homepage Thumbnail Size" -> "Change Image Size"

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
