### ISSUE TITLE
Bootstrap min overriding modal body style.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2987]
Bootstrap min overriding modal body style, because of which page builder module section is sliding towards right.
Ref: https://monosnap.com/file/wiEiQ73QOGCX6XWi1cbAbl5mleuMsS

**Comment by Zabi09** [comment]
Download this plugin to recreate the issue on localhost - https://wordpress.org/plugins/font-awesome-shortcodes/

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
