### ISSUE TITLE
Issue with Minify Javascript File option in WP ROCKET plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2988]
Help Scot Link: https://secure.helpscout.net/conversation/808220504/60691?folderId=2770545

When the user checks the Minify Javascript File option in WP ROCKET PLUGIN, then gets the errors in Google Search Console.

**Comment by MARQAS** [comment]
It will break the non-amp as well.

**Comment by Zabi09** [comment]
Reverted the code because it is properly fixed in #3062
