### ISSUE TITLE
Rare issue: Validation errors occur when Wordpress Comments Option is enabled

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2989]
Ref:
https://secure.helpscout.net/conversation/805098877/60168?folderId=2090438

The errors occur due to this function get_comment_text( ) in Features.php

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
Issue Not recreated on the local server.

**Comment by MohammedKaludi** [comment]
Can be merged into master.

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
