### ISSUE TITLE
Have problem with homepage title

### ISSUE THREAD

**Issue by fikryans** [ahmedkaludi/Accelerated-Mobile-Pages#299]
my problem not resolved in this new version,
please read my issue #245 
![screenshot_1](https://cloud.githubusercontent.com/assets/8897997/21265703/31f01632-c3d5-11e6-80cc-52bbb1219bd6.png)

**Comment by fikryans** [comment]
i try to modify features.php like  #299
but the description still didn't show up.. this screenshot of my website
![screenshot_5](https://cloud.githubusercontent.com/assets/8897997/21273562/b95ab8b8-c3f6-11e6-9bb2-4cf9fc144c10.png)

**Comment by fikryans** [comment]
on single post
![screenshot_6](https://cloud.githubusercontent.com/assets/8897997/21273644/1d32b336-c3f7-11e6-9f9e-7b6f73450f61.png)

**Comment by khaledMohammed000** [comment]
@fikryans we will push an update in few hours you will be able to get  this solved then 👍
