### ISSUE TITLE
Make AMP for WP plugin compatible with Lazy Load of Smush and Smush Pro  plugin 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2990]
Help Scout Link: https://secure.helpscout.net/conversation/816374449/62000?folderId=2770545

The unnecessary margin is added at the top because of the Lazy Load Plugin. The Lazy Load plugin is adding the featured image automatically in AMP which causes the unnecessary spacing at the top.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.48

**Comment by MohammedKaludi** [comment]
The issue still persists for one user

**Comment by MARQAS** [comment]
Another user with Smush compatibility issue https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3075

**Comment by pegazee** [comment]
Discussed this ticket with @MohammedKaludi and moving to the ready pipeline.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
