### ISSUE TITLE
Issue with end point to ?amp

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2991]
When the enable "change end point to ?amp" option, it's adding question mark if the post title start with "AMP" word.
Ref: https://secure.helpscout.net/conversation/818306459/62244?folderId=1060556

https://youtech.ooo/?amp-blogger-template-free-2019

**Comment by MARQAS** [comment]
Not working as expected
![image](https://user-images.githubusercontent.com/15303814/56117844-97e2f280-5f86-11e9-8b61-899daab74806.png)

**Comment by ajeetku** [comment]
We can improve this method properly, 
line 32 & 33 here why hardcode `amp`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d697a06ef64936ae77cd0499d9c93d7331b6bbba#diff-ab576767b896423d184ddafe2ede2310R32

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
