### ISSUE TITLE
Allow user to switch between swift icon and font awesome icon

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#2992]
HelpScoutLink: https://secure.helpscout.net/conversation/818906292/62300?folderId=2770545

**Comment by RajuJeelaga** [comment]
When social icon > StumbleUpon  option enable  from the option panel, 
1.https://monosnap.com/file/oWyxpgiCjh2AyK6ptW2hJtaLfOX1oc
on frontend error is showing
2.https://monosnap.com/file/vQPk0Y36uURjRiv7NNaV2P9PXTto6K
3.https://monosnap.com/file/6AnC83VKr0xbBSNfkcnyn2DDB14GhF

**Comment by Zabi09** [comment]
We have fixed the above issue on this ticket #2999

**Comment by MARQAS** [comment]
Needs improvement. Please check comments while working on it and discuss with @MohammedKaludi on code improvement

**Comment by RajuJeelaga** [comment]
@MARQAS I already use the ampforwp_get_setting, please check

**Comment by pegazee** [comment]
I think the option will show in the Global section ( General accordion tab) ( Screenshot: https://take.ms/KDj1S ). Right now, it's placed in the Advanced Setting tab.

Please discuss this with @ahmedkaludi

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
