### ISSUE TITLE
Issue with adding backgroud image or color in Pagebilder

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#2994]
Adding background image or color in 1st row of pagebuilder is applied to all below row which are empty.

Ref: https://secure.helpscout.net/conversation/817215509/62118/

**Comment by Zabi09** [comment]
The issue for only in master and if is properly fixed in beta so directly committed in master

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready and check once again the code in master

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
