### ISSUE TITLE
AMP endpoints outputting odd characters

### ISSUE THREAD

**Issue by clickblipclick** [ahmedkaludi/accelerated-mobile-pages#2995]
Hi, I am seeing an issue on my pages where apostrophes and other special characters are being output as `Ă˘ÂÂ`, etc.

The following change seems to resolve it, but I'm not sure if this is the right way to approach:

In `class-amp-dom-utils.php` change line 140 from:
`$result = $dom->loadHTML( $document );`
to:
`$result = $dom->loadHTML( mb_convert_encoding( $document, 'HTML-ENTITIES', 'UTF-8' ) );`

Is there a reason this is a bad idea to do?

**Comment by MARQAS** [comment]
Hi @clickblipclick, Can you give us more insights on it? A link or the content which you are trying to add so that I can recreate the same on my end?

**Comment by clickblipclick** [comment]
Hi @MARQAS, sorry for the lack of information. I don't have a link to send you but here's an example of what I'm seeing:

On the regular non-AMP page, if I view source, I see the following:
```
<h1>Yes, we’re hiring</h1>
<p>We’re building an extraordinary team—come join us.</p>
```

On the AMP version, I see the following:
```
<h1>Yes, weâre hiring</h1>
<p>Weâre building an extraordinary teamâcome join us.</p>
```
Essentially it's the same thing that happens when I force the browser character encoding to iso-8859-15, instead of UTF-8. I hope that gives you something to look into - let me know if there's any more information I can provide.

**Comment by Zabi09** [comment]
@clickblipclick I have tested your issue and it is working fine on our end, 
See these screenshots:
Added the code - https://monosnap.com/file/wwmjK17o9ZaR4ZjQRaB6rQkwr5EnLK
NON-AMP source code - https://monosnap.com/file/sQqaaVAPaRbCct68yQSrogtNs8XdXw
AMP source code - https://monosnap.com/file/Zj9cilE4MYvND00sZ98gCSCTl9nF9t

Will you please contact us on team@magazine3.com and our team will look at your issue and come up with the proper solution.

**Comment by clickblipclick** [comment]
@Zabi09 I did some further investigation and I believe I figured out what was causing it.

In our source code, we had an HTML comment that included an emoji character _before_ our meta charset tag, like so:

```html
<!--
👋 Hello friend!
-->
<!doctype html>
    <html lang="en-US" prefix="og: http://ogp.me/ns#">
        <head>
            <meta charset='UTF-8' />
```

It seems that this was causing the above issue. I'm not sure if this is something the plugin should address or if adding an emoji there is unsupported.

Thank you!

**Comment by Zabi09** [comment]
@clickblipclick 
Are you sure that after adding that HTML comment with emoji causing this issue because we have tested the same and we are unable to recreate it on our end?
And if yes then will you please contact our team on team@magazine3.com and our team will help you.

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/833864876/63739/

**Comment by Zabi09** [comment]
Unable to recreate the issue and the user is not responding so closing the ticket and if anyone has the same issue then please contact us on team@magazine3.com and our team will help you
