### ISSUE TITLE
Webp as featured image is not working in the single posts

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2996]
https://wordpress.org/support/topic/amp-pages-dont-show-webp-images-format/#post-11384580

Tested on localhost as well

**Comment by MARQAS** [comment]
Why there is a need for another `get_post_thumbnail_id` when it is already getting called in `class-amp-post-template.php`? 
Instead of adding extra code, can we do it with the existing one?

**Comment by Zabi09** [comment]
We cannot add the get_post_thumbnail_id of the class-amp-post-template.php because this is only working for normal featured images and not WebP format.

**Comment by MARQAS** [comment]
Try to wrap it in a function

**Comment by MARQAS** [comment]
Notice: Undefined variable: post_id in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 7806

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by beingsmart3** [comment]
Issue not replicated on my local server.
@ansaritalha what about you?

**Comment by MohammedKaludi** [comment]
escaping missing

**Comment by MohammedKaludi** [comment]
also, this is a very nice suggestion from @MARQAS https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2996#issuecomment-481124849

How can we implement this.

**Comment by Zabi09** [comment]
The WebP images don't have a width and height and due to that the image sanitizer is striping it and So I have discussed with @MARQAS and created a function for that.

**Comment by MohammedKaludi** [comment]
Incorrect escaping

**Comment by MARQAS** [comment]
Causing error when featured image and the content image is the same ( other than swift)

**Comment by MohammedKaludi** [comment]
Why removed scrset and alt from the code?

**Comment by Zabi09** [comment]
Due to debug warnings I removed the scrset and alt because the webP images were not giving any scrset and alt attributes

**Comment by MARQAS** [comment]
Blank when 'Duplicate Featured Image' option is enabled

**Comment by pegazee** [comment]
While merging this ticket in master, make sure this code is available or not: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/fb51a2794b2638e679d6d6ab8da8b6b0d184139a#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7807

**Comment by Rkroy** [comment]
Not working in the single posts of all the designs and working only on swift.

**Comment by MARQAS** [comment]
Featured image is repeating when `Featured Image from The Content` or `Featured Image from Custom Fields` option is enabled.

**Comment by MARQAS** [comment]
It is still repeating. 
Add a Featured Image and check in Design1,2 and 3

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58

**Comment by jeremymoore** [comment]
Our custom theme's amp (single) template calls `amp_featured_image()` and in doing so seems to generate two featured images. This wasn't occurring before so I'm trying to understand if we need to adjust our settings or change our template. 

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/958a40dfa3c0734bc8d129848bda7460360cd97f/components/featured-image/featured-image.php#L24

The above line seems to be where the duplication occurs best I can tell.

**Comment by MohammedKaludi** [comment]
> Our custom theme's amp (single) template calls `amp_featured_image()` and in doing so seems to generate two featured images. This wasn't occurring before so I'm trying to understand if we need to adjust our settings or change our template.
> 
> https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/958a40dfa3c0734bc8d129848bda7460360cd97f/components/featured-image/featured-image.php#L24
> 
> The above line seems to be where the duplication occurs best I can tell.
> 
> I just updated to 0.9.97.58 which is when the problem started.

Thank you @jeremymoore Will check it and will take necessary action.

**Comment by MohammedKaludi** [comment]
@Zabi09 Check this issue in the first thing in the morning.

**Comment by jeremymoore** [comment]
Thanks, for now, we'll bump back down to the previous version. Thanks!

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
