### ISSUE TITLE
Performance Issue with queries

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#2997]
https://monosnap.com/file/40NZtQZvBWkpvREwJPbmiHztEy0P14

**Comment by MARQAS** [comment]
This is causing the performance issue: https://monosnap.com/file/V9Q7EzyqPFHFcL8lhBVP3icg6eOrYN

**Comment by ajeetku** [comment]
In Screenshot, we can add a condition is its `ajax=1` is not set then go inside
Check while adding in master

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.54
