### ISSUE TITLE
Create filter in page builder Enable/disabled check

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#2998]
Create a filter in page builder Enable/disabled check
`checkAMPforPageBuilderStatus`

Change the text from "compatible" to Compatibility

**Comment by ahmedkaludi** [comment]
- [ ] Test with Page builder compatibility addon

**Comment by MARQAS** [comment]
When merging it in master, Make sure to add the meta in the master way.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.46
