### ISSUE TITLE
Need to add rel = "nofollow" to the links  of social platforms in menu and footer, in all designs

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#2999]
Ref:
https://secure.helpscout.net/conversation/819064322/62312?folderId=2632028

Add no-follow and improve the social section settings

**Comment by MARQAS** [comment]
Try to improve the label

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by ansaritalha** [comment]
rel="no follow" is not adding in swift working well in design 1,2,3
https://monosnap.com/file/9ZyzvpUOUroH4PASOPAbHjoCjuLkTk

**Comment by ansaritalha** [comment]
In design 1,2 ,3 rel="nofollow" is added in the anchor tag for all the social icons i.e in the menu sticky, after the post content icons, but in swift rel="no follow" getting added to the menu and sticky social icons but not for after the post content icons.
https://monosnap.com/file/XzHgpQntCPH16Xxqjb0aCJzTBgqq9J

**Comment by MohammedKaludi** [comment]
this function can be improved 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/431bb0d55e3006e2395f8ad0a51743ca59c4bfe8#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8033

**Comment by MohammedKaludi** [comment]
email missing the nofollow 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/431bb0d55e3006e2395f8ad0a51743ca59c4bfe8#diff-f95fa8043d381296f821d6461669ed11R53

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
