### ISSUE TITLE
Improvements in Search form widget

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3000]
The design of the search form widget is changing depending on the theme which we are using. need to make sure that our search form widget should appear always.

our default search form - https://prnt.sc/n87qc1
if good life theme is active  - https://prnt.sc/n87r7i
if some other theme is active - https://prnt.sc/n87rd1

**Comment by Zabi09** [comment]
Not Working

**Comment by ajeetku** [comment]
<b>Notice</b>:  Undefined variable: aria_label in <b>accelerated-mobile-pages\templates\features.php</b> on line <b>7816</b><br />

**Comment by pegazee** [comment]
Search widget form is not showing.
Screenshot: https://take.ms/QhK4r

**Comment by MohammedKaludi** [comment]
Two issues.
1) amp-form script is not adding in the other designs. 
2) undefined variable `$aria_label` called in the code https://take.ms/jhI37

https://take.ms/tlGQc

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
