### ISSUE TITLE
Create a fliter in contents-module file in line no. 368

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3001]
Help Scout Link:https://secure.helpscout.net/conversation/818606338/62277?folderId=2770545

Create a filter in the file path:  accelerated-mobile-pages > pagebuilder >modules > contents-module.php in line number 368 so that the user can override and customize some functionality of AMPFORWP plugin through his plugin.
 Filter to add : 
    Screenshot:https://monosnap.com/file/pq6r5F5oibnQwGUP8El7S44FQGPqy9

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.47
