### ISSUE TITLE
Link to non amp feature not works for thumbnail in design one and two

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3004]
HelpScout Link: https://secure.helpscout.net/conversation/820771333/62482?folderId=2770545

When the user hovers over thumbnail image in the related link while using design one and two it is redirecting to AMP pages instead of NON-AMP Pages.

Screenshot: https://monosnap.com/file/vqnx1L596y77RUuZbxKaFUW4vuDobL

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
this can be improved https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7a276123e2088ada9a27015aed1f23a76457e8c2#diff-d9e62bf7636c72ea611757e43f70c46eR376

**Comment by MohammedKaludi** [comment]
:+1: ready to merge, also notify the documentation team about this new function.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
