### ISSUE TITLE
In NewsArticle > ArticleBody and Description are missing from the AMP page.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3005]
The issue is from the AMP default structure data.

**Comment by MARQAS** [comment]
Try using this function for description: `ampforwp_generate_meta_desc`

**Comment by MARQAS** [comment]
use `get_the_content` and why `wp_strip_all_tags`?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Remove the unused post_id

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cb463f77d96b6dbeb369929b41e3506eedb4aeb4#diff-b7c53bc2fbd4c72dbfdc941d2e719d24R296

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
