### ISSUE TITLE
Facebook comment and Facebook  Like option gives error when using bbpress plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3006]
Help Scout Link: https://secure.helpscout.net/conversation/821797223/62575?folderId=2770545

When the user enables Facebook comment and Facebook Like option while using the bbpress plugin, the validator shows the following error message: 
"The extension 'amp-facebook-comments' was found on this page, but is 
unused. Please remove this extension. Debug."

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
