### ISSUE TITLE
Fatal error: Call to undefined method WPSEO_Options

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3008]
Here see the screenshot:
https://monosnap.com/file/5dFP1OfP71mBVudNX37L9gT6FUrFW7

Ref:https://secure.helpscout.net/conversation/819487759/62355?folderId=2770543

**Comment by MARQAS** [comment]
The issue was occurring only on users end as he was using a very old and nulled version of the plugin.
Closing this ticket for now. If anyone faces the same issue, please feel free to reopen it.

**Comment by ahmedkaludi** [comment]
I saw another website today, Yoast has alot of users, we need to create a fallback instead of Fatal error.

**Comment by ansaritalha** [comment]
one more user-facing this issue.
https://monosnap.com/file/mAYce46z2c6LIPjENzO0D1LvnOLqTv

Ref: https://secure.helpscout.net/conversation/827476847/63258?folderId=1914715

**Comment by amer07** [comment]
One more user: https://secure.helpscout.net/conversation/828726509/63370/

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.47
