### ISSUE TITLE
Strip CSS with i-amphtml- name prefix because its causing validation errors

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3009]
The text inside tag 'style amp-custom' contains 'CSS i-amphtml- name prefix', which is disallowed.

**Comment by MARQAS** [comment]
Is it related to Custom CSS @ahmedkaludi?

**Comment by MARQAS** [comment]
Instead of this code: `if(empty($data)){
        return $data;
    }`,
we can use `!empty` and do the activity in it.

**Comment by pegazee** [comment]
working as expected

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
