### ISSUE TITLE
Dropcap extra features

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3010]
Hi, is there anyway to change by css the size and color of DropCap?

REF: https://wordpress.org/support/topic/dropcap-font-size-e-color/

**Comment by pegazee** [comment]
Need escaping
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/59ee58576c964e6af01bacd140e0214583980528#diff-2ae5550e31f40c1962ca69d373af6b93R877

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
use `ampforwp_sanitize_hex_color ` instead

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/59ee58576c964e6af01bacd140e0214583980528#diff-2ae5550e31f40c1962ca69d373af6b93R881

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
