### ISSUE TITLE
Debug errors in .46

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3011]
[09-Apr-2019 16:43:51 UTC] PHP Notice: Undefined property: ReduxCore\ReduxFramework\ReduxFramework_extension_demolink_image_select::$field_name in /…/wordpress/wp-content/plugins/accelerated-mobile-pages/includes/options/extensions/demolink_image_select/extension_demolink_image_select.php on line 66
[09-Apr-2019 16:43:51 UTC] PHP Notice: Undefined property: ReduxCore\ReduxFramework\ReduxFramework_extension_checkbox_hierarchy::$field_name in /…/wordpress/wp-content/plugins/accelerated-mobile-pages/includes/options/extensions/checkbox_hierarchy/extension_checkbox_hierarchy.php on line 66

https://wordpress.org/support/topic/php-notices-in-v0-9-97-46/#post-11409699

**Comment by syedimran22** [comment]
One more user is getting fatal error from latest updated version 0.9.97.46.1 and also debug warnings however user rolled back to the previous version.

Fatal error: Class 'ReduxCore\ReduxFramework\Redux_VendorURL' not found in /home/ziggicig/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/extensions/vendor_support/vendor_support/extension_vendor_support.php on line 58

Warning: include_once(AMPFORWP_EXTENSION_DIR/vendor_support/vendor_support/class.vendor-url.php): failed to open stream: No such file or directory in /home/ziggicig/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/extensions/vendor_support/vendor_support/extension_vendor_support.php on line 56

Warning: include_once(): Failed opening 'AMPFORWP_EXTENSION_DIR/vendor_support/vendor_support/class.vendor-url.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/ziggicig/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/extensions/vendor_support/vendor_support/extension_vendor_support.php on line 56

**Comment by ahmedkaludi** [comment]
Notice</b>:  Undefined property: ReduxCore\ReduxFramework\ReduxFramework_extension_checkbox_hierarchy::$field_name in <b>D:\xampp\htdocs\magzine\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\extensions\checkbox_hierarchy\extension_checkbox_hierarchy.php</b> on line <b>66</b><br />

**Comment by syedimran22** [comment]
One more user is getting this following below error.
( ! ) Notice: Undefined property: ReduxCore\ReduxFramework\ReduxFramework_extension_demolink_image_select::$field_name in /var/www/mulberrys/wp-content/plugins/accelerated-mobile-pages/includes/options/extensions/demolink_image_select/extension_demolink_image_select.php on line 66

REF: https://secure.helpscout.net/conversation/823260842/62685/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by andsnake** [comment]
Ok so a quick "hot fix" for this would be to define the $this->field_name befor it actually gets called, since if you dump $this right before line 66, such a field does not exist. 

so i.e 


 if ( empty( $this->extension_dir ) ) {
                **if(!isset($this->field_name))
                {
                    $this->field_name = 'checkbox_hierarchy'; //this is the "hotfix"
                }**
                $this->extension_dir = trailingslashit( str_replace( '\\', '/', AMPFORWP_EXTENSION_DIR.'/'.$this->field_name ) );
                $this->extension_url = site_url( str_replace( trailingslashit( str_replace( '\\', '/', ABSPATH ) ), '', $this->extension_dir ) );
            }

**Comment by MohammedKaludi** [comment]
Need to update the code as discussed 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ec436ef09e8f49faa505911cad876d96b221a871#diff-d6cec796802bd8da3b846547aaea91cdR121

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.47
