### ISSUE TITLE
remove the free woo extension link from the E-commerce section

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3012]
- [x] Move E-commerce section above Advanced section

- [x] Change the Woo WP.org link to Woo Pro

**Comment by MARQAS** [comment]
Can we improve the condition?
I think it's repeating, try to do it in one condition

**Comment by Zabi09** [comment]
No, it's not repeating the first condition is when there is no free and pro version of woocommerce and the second is when the only free version is activated and the third condition is when the pro is activated

**Comment by pegazee** [comment]
Need proper escaping:
 https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d4c8202ed4664a099323991b219d8040b188b1a4#diff-260eba6333c3222e59a6aed22ac5ab37R1763

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
