### ISSUE TITLE
issues with paragraphs

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3013]
https://wordpress.org/support/topic/bug-enter-between-paragraph-is-gone-after-update-to-0-9-97-46/#post-11417553
https://t.me/amp_community/6153
https://wordpress.org/support/topic/amp-pages-not-showing-in-content-ads-anymore/#post-11417552

**Comment by akashagrjsr** [comment]
Screenshot regarding paragraph issues
In Non-Amp Version: https://monosnap.com/file/AJ8y20HsRFxAHDTV9CXqKihvKN1vsK
In Amp Version:  https://monosnap.com/file/J4icPkcXEzSL7Y9EhQ5P9hoqDA5LH5

**Comment by MARQAS** [comment]
Unable to recreate and users who have reported it also reported that it has been fixed in recent updates. 
Closing this ticket. If anyone faces this issue again, feel free to reopen it.
