### ISSUE TITLE
change the pagebuilder section word's as per installed plugin

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3014]
change the pagebuilder section word's as per installed plugin, I.e, divi, elementor.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
