### ISSUE TITLE
Archive support needs to grow with Category and Tags as separate option

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3016]
People want to enable AMP only on category but not on the tag, so we need to allow that.

REF: https://wordpress.org/support/topic/remove-all-tags-amp-version/#post-11413510

**Comment by MARQAS** [comment]
After disabling, it should redirect to non-amp from amp when one visits '/amp'

**Comment by pegazee** [comment]
** review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge. Nice work @pegazee on this ticket.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
