### ISSUE TITLE
Chartbeat Tag Has Incorrect Variables

### ISSUE THREAD

**Issue by jsm386** [ahmedkaludi/accelerated-mobile-pages#3017]
The Chartbeat variables in https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php include:

- accountId
- dashboardDomain

According to [Chartbeat's documentation](http://support.chartbeat.com/docs/integrations.html#amp) for AMP, they should be:
- uid
- domain

**Comment by ahmedkaludi** [comment]
Thanks, My dev team will fix this ASAP

**Comment by jsm386** [comment]
One other note in debugging this with Chartbeat folks. On line 1338 you use site_url() which returns eg https://example.com but the correct value should be eg example.com (no protocol)

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
