### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3018]
accelerated-mobile-pages/feeds/instant-article-feed.php
<link><?php bloginfo_rss('url') ?></link>

**Comment by ahmedkaludi** [comment]
https://wordpress.org/support/topic/missing-semicolon-2/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
