### ISSUE TITLE
To show post title after breadcrumb navigation in post

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3019]
Help Scout Link: https://secure.helpscout.net/conversation/824612348/62856?folderId=2770545

Implement a child option for breadcrumb to show the page title below the breadcrumb. By default it is disabled. If the user enabled it then his page title will show below the breadcrumb.

**Comment by MARQAS** [comment]
Consult @ahmedkaludi for Frontend

**Comment by pegazee** [comment]
Discussed with @ahmedkaludi and the styling was perfect. We can move this ticket to another pipeline

**Comment by ajeetku** [comment]
Escaping required please check in master

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
