### ISSUE TITLE
When I set “By Tags” doesen’t swow Related post.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#302]
I write private message via form with attachment. The issue i think is in the “Design One”. The “Design Two” work fine only with category. When I set “By Tags” doesen’t swow Related post.

REPORTED: https://wordpress.org/support/topic/related-post-page-non-found/

**Comment by khaledMohammed000** [comment]
I have properly tested it , I have found that the output is correct on both the designs , Please review this @MohammedKaludi and close this issue

**Comment by MohammedKaludi** [comment]
OK I will check this and will get back to you.

**Comment by MohammedKaludi** [comment]
Twitter sharing is working properly, Title and url are added while sharing..
Tested on Both the designs and on Both Sharings (post sharing and sticky sharing)

**Comment by MohammedKaludi** [comment]
Working Properly tested in multiple environments.
