### ISSUE TITLE
Add button of MEWE social network

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3020]
https://secure.helpscout.net/conversation/824701206/62861/

**Comment by MARQAS** [comment]
Is this the correct icon? https://monosnap.com/file/5J2glButIb8PBpo3T8Pk2ml6wQnzvV

**Comment by Zabi09** [comment]
Yes that is the correct icon

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
