### ISSUE TITLE
Issue with moblie redirection with non-amp link

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3021]
Here see the screenshot: https://monosnap.com/file/l55NLdvWMWecxB8cR3H3taJLbImcBf
Ref:https://secure.helpscout.net/conversation/819666601/62363/

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
