### ISSUE TITLE
Code is showing in place of user name of comment when select the theme one, two and three

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#3022]
Ref: https://secure.helpscout.net/conversation/825399778/62981?folderId=2614130

Here is a screenshot: https://prnt.sc/naypvs

**Comment by ajeetku** [comment]
here issue with <b>& <span> tags
need to remove __()

**Comment by pegazee** [comment]
Need to remove the extra open & close bracket
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ed8b2dc824910afc5b43771a077a087ea7c8c0f8#diff-3358181277138e309fc94ee4e552f7feR57

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ed8b2dc824910afc5b43771a077a087ea7c8c0f8#diff-cd0d03dc3132fd549b56d6f151b719c7R43

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ed8b2dc824910afc5b43771a077a087ea7c8c0f8#diff-0e8a285c04e176fa871a31f2f411184bR43

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ed8b2dc824910afc5b43771a077a087ea7c8c0f8#diff-07cff8d347cd0f5582fc5cfef40abe76R44

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ed8b2dc824910afc5b43771a077a087ea7c8c0f8#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3474

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
current sprintf usage is incorrect.
Check the example on WordPress https://codex.wordpress.org/I18n_for_WordPress_Developers#HTML

**Comment by MARQAS** [comment]
Are you talking about the whole plugin or just the comments part? Because we are not using sprintf in the comments part.

**Comment by MohammedKaludi** [comment]
Specifically in this commit.

`p>
<?php
$url = 'http://example.com';
$link = sprintf( wp_kses( __( 'Check out this link to my <a href="%s">website</a> made with WordPress.', 'my-text-domain' ), array(  'a' => array( 'href' => array() ) ) ), esc_url( $url ) );
echo $link;
?>
</p>
`

Check this example. 

We are escaping the code inside of it, but i dont think it makes any difference.
We can merge it into master and make sure to use `ampforwp_get_setting` while merging 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0e524543dd60440fa5ef59c13315d9a027167832

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
