### ISSUE TITLE
If he is a first time user, then we should give a notice to run a installation wizard

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3023]
If he is a first time user, then we should give a notice to run a installation wizard

**Comment by MARQAS** [comment]
Is this not enough: https://monosnap.com/file/Z0dg60ULmBGSfu5ad36fcAwYEncE3L

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
1, nonce missing, 
2. use any existing hook `admin_notices` if possible

**Comment by MohammedKaludi** [comment]
1. Styling is not good.
2. Once Clicked on Run Wizard, notice should not appear again.

![image](https://user-images.githubusercontent.com/16618009/58547283-b8a89400-8224-11e9-9fb5-ff8514e3920e.png)

**Comment by ahmedkaludi** [comment]
not relavant after ux update
