### ISSUE TITLE
Cntr class removed after activate elementor

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3025]
Cntr class removed after activate elementor/ elementor pro

**Comment by MARQAS** [comment]
Can you provide more details @ajeetku?

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
