### ISSUE TITLE
Allow people to enable or disable the AMP from the categories

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3026]
Allow people to enable or disable the AMP from the categories

REF: https://wordpress.org/support/topic/add-select-categories-to-show-amp-option/

**Comment by pegazee** [comment]
We will tackle this with #3052 and #2903

**Comment by ahmedkaludi** [comment]
We have to work on this now

**Comment by MohammedKaludi** [comment]
Will be fixed in #4326
