### ISSUE TITLE
AMP preview functionality is not working,showing blank in the preview mode

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3029]
Ref: https://monosnap.com/file/7tL60Iem4zY6f4yUH7qokrDggLvv8K

Even in local also facing the same issue.

https://secure.helpscout.net/conversation/824957636/62914?folderId=2632028

https://secure.helpscout.net/conversation/825342051/62980?folderId=2632028

**Comment by amer07** [comment]
Here one more user-facing same problem

Ref: https://www.dropbox.com/s/yy4agv9vg5ujmsn/Screenshot%202019-04-17%2009.52.13.png?dl=0

 https://secure.helpscout.net/conversation/829890550/63472?folderId=2770543

**Comment by Rkroy** [comment]
Another user: https://secure.helpscout.net/conversation/767559878/53535?folderId=2322649

**Comment by MARQAS** [comment]
Notice: Undefined variable: amp_custom_content_enable in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 1097

**Comment by MARQAS** [comment]
Notice Resolved here https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/44bee4ac930166c0fa32ffdf6a53842fe9ee7932

**Comment by pegazee** [comment]
** Review **

- [ ] Imran

- [ ] Talha

**Comment by MohammedKaludi** [comment]
:+1: ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.50
