### ISSUE TITLE
[Testing] Notice some bugs on the menu, Tag of AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#303]
1. “Hide AMP on Archive Pages
Enable / Disable AMP in the categories and tags pages”

When I enable AMP for categories, the menu not update (no “?amp”) and user click on Category Menu is not link to AMP.

2. ‘Front Page
Custom AMP front page”

In Front Page, 2 first banner (position 1, 2) are joined together, this is a violation of AdSense policies.

3. Another error, the related artiles with Tags is not work.

4. In addition, I would appreciate you can insert the Facebook Like button, Facebook Comments at the end of the article.

https://wordpress.org/support/topic/notice-some-bugs-on-the-menu-tag-of-amp/

**Comment by MohammedKaludi** [comment]
All the issues have been fixed. 
Enhancement about Facebook was added as new ticket #313
