### ISSUE TITLE
Add Extension list for the events calendar for amp

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3030]
Add Extension list for the events calendar for amp: the-events-calendar-for-amp
Name: The Events Calendar For Amp
page:  the-events-calendar-for-amp
path: the-events-calendar-for-amp/the-events-calendar-for-amp.php

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
