### ISSUE TITLE
Facebook comments not displaying if we add number more than 100 in the number of comments.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3032]
Facebook comments not displaying if we add number more than 100 in the number of comments. 
Ref: https://secure.helpscout.net/conversation/825603534/63005?folderId=1680016

**Comment by pegazee** [comment]
We've reported a bug in the amp project repo to look into this issue
https://github.com/ampproject/amphtml/issues/22062

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
