### ISSUE TITLE
Errors in AMP social Icons

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3033]
Help Scout Link: https://secure.helpscout.net/conversation/803888338/59986?folderId=2770545

- [x] .Lists do not contain only <li> elements and script supporting elements (<script> and <template>).
Screenshot: https://monosnap.com/file/USEU7LwnlSsB0p4raYIfLM9yjzLXYi

- [ ] . List items (<li>) are not contained within <ul> or <ol> parent elements.
Screenshot: https://monosnap.com/file/9SbHlWUiGkF46rjVUoM8ZC8atoBEpJ

**Comment by Zabi09** [comment]
Please use ampforwp_get_settings function

**Comment by pegazee** [comment]
Pushed in 0.9.97.53
