### ISSUE TITLE
Request to implement the new options for to change the Navigation part background color and element color for Design 3

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3034]
https://secure.helpscout.net/conversation/825417076/62983?folderId=1680016

**Comment by MARQAS** [comment]
1. Escaping is required.
2. Use ampfowp_get_setting
3. Sanitize the color when echoing it

**Comment by MARQAS** [comment]
check for 'color' before echoing it directly

**Comment by MohammedKaludi** [comment]
as in wordpress we use the concept of late escaping/sanitizing.

I suggest you to remove the sanitization argument from the code https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f0ba6b727222ab987a60286dccec745bb7265055#diff-d2a448840c98f4c9bcf27aab39b04b83R564

and add sanitization while echoing https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f0ba6b727222ab987a60286dccec745bb7265055#diff-d2a448840c98f4c9bcf27aab39b04b83R564

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
