### ISSUE TITLE
Create an option for H1-H6 Heading Font Sizes for all the designs.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3035]
Create an option for H1-H6 Heading Font Sizes for all the designs, referencing #2059 where we've added this option only for swift design.
Ref: https://secure.helpscout.net/conversation/824032622/62757?folderId=2322649

**Comment by MARQAS** [comment]
Escaping is required and use `ampforwp_get_setting` instead of global redux_builder_amp

**Comment by Zabi09** [comment]
Added - https://monosnap.com/file/jrNw88ql8OPwGC6HsZ6V5FBm9FNc2M
Not working - https://monosnap.com/file/OTDMxa3HZHQPpe7XDrXEKIyrGktCRY

**Comment by MohammedKaludi** [comment]
use `get_setting()` while merging 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/785951dcf9bc0e8f8e6afd8167e0e1495536aa9d#diff-2ae5550e31f40c1962ca69d373af6b93R612

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.57
but wrong styling/lineheight applying on homepage as well. Resulting breaking the design

**Comment by MohammedKaludi** [comment]
👍 ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
