### ISSUE TITLE
Custom Taxonomy support issue

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/accelerated-mobile-pages#3036]
Ref: https://secure.helpscout.net/conversation/820084105/62406/

**Comment by pegazee** [comment]
try to wrap the option when the custom taxonomy is exists

**Comment by MARQAS** [comment]
( ! ) Fatal error: Call to undefined function ampforwp_generate_taxonomies_transient() in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php on line 212

**Comment by pegazee** [comment]
When I'm enabling the "Custom Taxonomy Category" option disabled the "Custom Taxonomy tag" option. the custom category page doesn't have the amphtml.

Screenshot: https://take.ms/QqHII
> https://take.ms/1jxjK

**Comment by MohammedKaludi** [comment]
Not working.

https://take.ms/BXUCO

**Comment by merajali294** [comment]
https://prnt.sc/oahhnu
UI should be improved

**Comment by MohammedKaludi** [comment]
Need to change the control type.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
