### ISSUE TITLE
Extra option in Analytics section?

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3037]
In the Analytics section, When all switches are disabled, this select type array is showing. Screenshot: https://take.ms/hqDE7

Check and remove this option if it's not in use.

**Comment by MohammedKaludi** [comment]
Consult @MARQAS regarding this

**Comment by Zabi09** [comment]
If I remove the complete array also which we are not using now, the analytics are working fine but that may remove some defaults - https://monosnap.com/file/WCK1YUqczRQFCeTwVmB0RhFgzTJKQC 

Will you please check once and let me know,

**Comment by MohammedKaludi** [comment]
> If I remove the complete array also which we are not using now, the analytics are working fine but that may remove some defaults - https://monosnap.com/file/WCK1YUqczRQFCeTwVmB0RhFgzTJKQC
> 
> Will you please check once and let me know,

ok lets keep it then.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
