### ISSUE TITLE
Unnecessary css is loading in single amp product pages and also on cart pages.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3038]
DESC: Unnecessary CSS is loading in single amp product pages and also on cart pages. Need to remove all the unnecessary CSS on product pages even amp page builder is enabled on product pages.
such as  .single-post .sdbr and even more 

REF: https://secure.helpscout.net/conversation/822020921/62588?folderId=1680016

**Comment by pegazee** [comment]
why not in other designs?

**Comment by MohammedKaludi** [comment]
its breaking the design completely 

https://take.ms/ikk6F

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
