### ISSUE TITLE
The attribute 'onclick' may not appear in tag 'a'.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#304]
https://wordpress.org/support/topic/the-attribute-onclick-may-not-appear-in-tag-a-2/

**Comment by khaledMohammed000** [comment]
This was solved along time back in commit : https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/commit/3fb9e4515833c0cc01ebb588f9299f153e5e70fb
