### ISSUE TITLE
Add Extension list for table of content

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3040]
Add Extension list for the table of content for amp: 
Page: table-of-content-for-amp
Name: Table Of Content For AMP
Path: table-of-content-for-amp/table-of-content-for-amp.php

**Comment by ajeetku** [comment]
replace url link with below link
`'url_link'=>'https://ampforwp.com/table-of-content-for-amp/#utm_source=options-panel&utm_medium=extension-tab_shortcodes_ultimate&utm_campaign=AMP%20Plugin',`

**Comment by ahmedkaludi** [comment]
- [ ]  https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a8eb26e4453ecf10934727eb464781e995a7a674

- [ ]  https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3cdcdceea275691028f756e7910ca6757dd83c4b

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
