### ISSUE TITLE
Matemo Switch UI issue (Piwik)

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3041]
When enabling the "Matomo (Piwik) Analytics" option, the switches are getting weird UI.
Screenshots:
Before: https://take.ms/O5zZC
After: https://take.ms/yivM1

**SOLUTION**
There should be a tutorial link on the documentation

**Comment by MARQAS** [comment]
Escaping: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ae0a2f90082bea7ec69192679dcdff74d295f093#diff-8ada183a565e41de5b9a91a8047b98adR321 ?

**Comment by MohammedKaludi** [comment]
Remove unused code 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f53784f912979bce20bdcd42b70db8b92cdb6ac3#diff-8ada183a565e41de5b9a91a8047b98adR320

Move the link inside of ToolTip
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f53784f912979bce20bdcd42b70db8b92cdb6ac3#diff-8ada183a565e41de5b9a91a8047b98adR320

**Comment by MohammedKaludi** [comment]
This should be the child control.
https://monosnap.com/file/3vfvyiXHCHRXqVncNi7uRKo7bF8aYg

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
