### ISSUE TITLE
WP Recipe Maker & WP Recipe Maker PRO Schema should be attached to the "Recipe" setting of our schema option

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3043]
WP Recipe Maker & WP Recipe Maker PRO Schema should be attached to the "Recipe" setting of our schema option

https://secure.helpscout.net/conversation/827863559/63296?folderId=2322649

**Comment by MARQAS** [comment]
Check for archives as well, and also move the code in the beginning of the function

**Comment by Rkroy** [comment]
Other schemas are also getting removed, please check.

**Comment by MohammedKaludi** [comment]
Need to discuss.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
