### ISSUE TITLE
Can't edit the page or post through Elementor page builder when AMPtakeover beta is enabled.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3044]
Ref: https://secure.helpscout.net/conversation/828751997/63373?folderId=1680016

The process to test:

1)Activate the Elementor page builder.
2)Enable the AMP takeover beta option.
3)Then edit the page or post by using Elementor.

**Comment by Zabi09** [comment]
Fixed in #3284
