### ISSUE TITLE
Swift Theme has doublequotes in related Post quotes issue

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#3045]
- https://monosnap.com/file/dZX2du9a3LySwl1110i8u33QJbKFPg
- https://monosnap.com/file/HWfYVWnVRM6VjgxdfDTt6uENDvtgiD

Reference:
https://secure.helpscout.net/conversation/826711640/63165

NOTE:::::
Once this ticket is ready to push, email the user to update the Plugin and check whether the issue is fixed or not.

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/832702237/63642?folderId=1680016

This user is also facing the same issue

**Comment by RajuJeelaga** [comment]
This problem is coming only in master, Beta it is working fine

Solution:
please check the amp_loop_title function in components/loop/loop.php
just replace this code --- New code
echo '<'.$tag.' '.$attributes.'>';
with current code --- old code
echo '<'.esc_attr($tag).' '.esc_attr($attributes).'>';
it will work.

see the screenshot https://monosnap.com/file/ijmDO87vyzvz3xICEefyv5xU7grYYn

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Why this ticket as moved to the approved pipe?
@pegazee @MARQAS @ajeetku @RajuJeelaga

**Comment by MARQAS** [comment]
@MohammedKaludi, it is working fine in Beta but not in Master, so we have to add it directly in master

**Comment by MohammedKaludi** [comment]
But I don't see any fix in this ticket.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2f760808eca44a80a2d5d49d2068ecee5d2083ae#diff-d9e62bf7636c72ea611757e43f70c46eR281
its not proper solution, `$data['attributes']` stands for complete attribute key with value ex: `data-abc="example"`
but in the current situation, all attributes values are assigned in class attr
discuss with @MARQAS he knows this feature

**Comment by MohammedKaludi** [comment]
Need to implement a better solution.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
