### ISSUE TITLE
Logo on the top of the menu shade looks strange.

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#3046]
Reference:
https://wordpress.org/support/topic/possible-graphical-bug/

https://www.liesenfeld.de/amp/
https://monosnap.com/file/sdcZRx1TIERgn5u0xXUo8uw9X99AGJ

**Comment by pegazee** [comment]
**Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
