### ISSUE TITLE
Problem for showing homepage in AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3047]
Help Scout Link: https://secure.helpscout.net/conversation/823628845/62715?folderId=2770545
 Screen Shot: https://monosnap.com/file/awACTrjQGWRrJ2wKJSdNkqXxEcp5sW
If the user didn't select any option for publication page then website showing different homepage.
In our local, I tried but not able to create the same issue.

**Comment by Zabi09** [comment]
This issue was coming from the Polylang plugin and need to buy the "Polylang Integration with AMP" extension to get it fixed.
