### ISSUE TITLE
Facebook button need width option

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3051]
The Facebook button need width option people can another language they can use it.

https://secure.helpscout.net/conversation/830245224/63506/

I mean that the "Like" button does not show how much I like it, it is cut, the whole button is not seen as you will see in the following image.

![image (2)](https://user-images.githubusercontent.com/49484856/59339219-5f129000-8d21-11e9-952a-57909c4b9777.png)

**Comment by Nitesh221194** [comment]
**Vkontakte Share does not open in a new tab unlike others**

Ref:
https://secure.helpscout.net/conversation/834721178/63827?folderId=2844667

**Comment by ahmedkaludi** [comment]
we are already working on this: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3241
