### ISSUE TITLE
 PERFORMANCE HUGE  (​URGENT)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3052]
Here you see the screenshots:
https://monosnap.com/file/jX4Rt7rKaKERvrC9v6y8isH4BFjCBV
https://monosnap.com/file/LsVLzV49Vytj8OqRDYPUqXA86GtBKK
Here you see the link:https://pastebin.com/szAJVi2h
Ref link:https://secure.helpscout.net/conversation/830841959/63545?folderId=2770543

**Comment by ahmedkaludi** [comment]
IndianFantasy performance issues found. We need to fix them with this ticket

**Comment by amer07** [comment]
here one more user #3
User name: Bruno Ayres Martinez
ref:https://secure.helpscout.net/conversation/834324964/63799?folderId=2770543

**Comment by akashagrjsr** [comment]
here one more user #4
 User Name: Carlos
Ref: https://secure.helpscout.net/conversation/832579374/63634?folderId=2770545

**Comment by beingsmart3** [comment]
another case everything is working perfectly but some extra things are getting loaded due to that edit page loads slightly slow when the amp is activated.

Ref: https://secure.helpscout.net/conversation/804855935/60148?folderId=673455

user has provided staging site details.

**Comment by MARQAS** [comment]
WP_Query in loop.php

**Comment by MohammedKaludi** [comment]
Also Menu transient should delete when designs are changed.

**Comment by MohammedKaludi** [comment]
Structured data is vanished in Performance Branch
No `SiteNavigationElement` elements can be found in Performance Branch

**Comment by MohammedKaludi** [comment]
All the above codes are added in the master.
This ticket does not require any merging.
