### ISSUE TITLE
Notice to be removed after dismissing it after installing AMP

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3053]
Notice to be removed after dismissing it after installing AMP - https://prnt.sc/ne4tsg

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
1. if you are updating the value then why delete and again set the value 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/58a7d02fa672140f777db61c73dbfd5f4f96eedd#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1086

2. Exit or die after the ajax call. Open ajax call is a major security flaw
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/58a7d02fa672140f777db61c73dbfd5f4f96eedd#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1083

3. Make sure the transient is deleted while uninstalling as well ampforwp_automattic_activation_notice

**Comment by Zabi09** [comment]
1 - To make it work for both ways we have added that two times that is if someone already has AMP and then install our AMPforWP or if someone already has AMPforWP and then install AMP
2 - exit has added by @pegazee - #3094 
3 - yes we are deleting the transient on register_deactivation_hook

**Comment by MohammedKaludi** [comment]
> 1 - To make it work for both ways we have added that two times that is if someone already has AMP and then install our AMPforWP or if someone already has AMPforWP and then install AMP
> 2 - exit has added by @pegazee - #3094
> 3 - yes we are deleting the transient on register_deactivation_hook

There is no need to delete the value to reset it again, just use set_transient with new value and it will update the new value.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/58a7d02fa672140f777db61c73dbfd5f4f96eedd#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1085

**Comment by MohammedKaludi** [comment]
Nonce missing

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
