### ISSUE TITLE
Notice errors after activating amp-woocommerce plugin.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3054]
Notice: Undefined index: amp-woocommerce-pro in C:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\admin-config.php on line 532

**Comment by pegazee** [comment]
Resolved code is already added in the beta 8 months ago.

**Note:**

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by pegazee** [comment]
Pushed in 0.9.97.49
