### ISSUE TITLE
is_amp_endpoint issue

### ISSUE THREAD

**Issue by davideprevosto** [ahmedkaludi/accelerated-mobile-pages#3055]
Hi there,
is `is_amp_endpoint()` function no more available on your last version?
Thanks

**Comment by MARQAS** [comment]
Hi @davideprevosto, we make some changes in the last update related to our core and that function is coming from the core. Are you sure that it is not working? Can you try `ampforwp_is_amp_endpoint()`

**Comment by davideprevosto** [comment]
Hi @MARQAS,

I know is_amp_endpoint() is a core function, but maybe your last update change the priority necessary to fire this hook. I already changed my codebase, using `ampforwp_is_amp_endpoint()`, and it seems it works.

**Comment by MARQAS** [comment]
@davideprevosto, can you tell me where you were trying to use `is_amp_endpoint()`?

**Comment by davideprevosto** [comment]
@MARQAS for example in `pre_get_posts` hook.

**Comment by MARQAS** [comment]
@davideprevosto Thanks for the info, please use `ampforwp_is_amp_endpoint` which is more stable and advanced.

**Comment by MARQAS** [comment]
@davideprevosto, I have added the Fallback as well, please do check the updated code and let me know if you face the same issue again.

**Comment by MohammedKaludi** [comment]
Missing debug warning.

**Comment by MARQAS** [comment]
Which debug warning @MohammedKaludi?

**Comment by MohammedKaludi** [comment]
Only Not working with this one plugin: Schema & Structured Data for WP

**Comment by MohammedKaludi** [comment]
Also, the warnings only have to log in the debug and should not print it.

**Comment by MohammedKaludi** [comment]
This code needs improvements 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1e63fe6815d5753665fe41aa7b971cd1cfffcf24#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R999

**Comment by ahmedkaludi** [comment]
We have to remove this log.

**Comment by MohammedKaludi** [comment]
will be pushed in 0.9.97.55

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
