### ISSUE TITLE
Sidebar breaks the blog page design

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3056]
- [ ] When Homepage sidebar is enabled, blog page design is breaking.
Please see the screenshot
1.https://monosnap.com/file/powM69kspGOOyJqNbvfTARAaKwWDTg
2.https://monosnap.com/file/t4pBhlDkkQ6k80yCOcPSHHKGx12iTq

**Comment by RajuJeelaga** [comment]
### Sidebar breaks the blog page design problem is showing only in master, In beta the problem is fixed,
Need to add this condition ampforwp_is_blog in sidebar css to fix the problem.

**Comment by RajuJeelaga** [comment]
This is the code that need to add in style.php file in swift, line number ---- 1199 (just adding this condition, then it will work)

<?php if ( ( true == ampforwp_get_setting('gbl-sidebar') && (ampforwp_is_front_page() || ampforwp_is_home()) || ampforwp_is_blog() ) || ( true == ampforwp_get_setting('swift-sidebar') && is_singular() )  ) { ?>
/*** Sidebar CSS ***/
...........

<?php } ?>

**Comment by MARQAS** [comment]
Archives are having an issue in beta as well, please add the code for Archives in beta

**Comment by RajuJeelaga** [comment]
Archive page condition is added for the sidebar in Beta, Need to added the same condition in the Mater
@MARQAS

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
