### ISSUE TITLE
Need to add colour changing feature in nav bar in a design-2

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3059]
ref:https://secure.helpscout.net/conversation/833434836/63695/
add color changing feature in nav bar in design-2

**Comment by MohammedKaludi** [comment]
Need to create a fallback for empty value.
https://take.ms/Ll8G8

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
