### ISSUE TITLE
"WP Forms for AMP" setting link is incorrect.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3060]
Ref: https://secure.helpscout.net/conversation/828718896/63368?folderId=2632028

Occurring in localhost also.

**Comment by pegazee** [comment]
WP forms work Out of the box didn't need any setting for this,  it will take non-amp WP form & render into the AMP. So, I've removed the setting button.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
