### ISSUE TITLE
 After Update all AMP Pages Do Not Load and are Not Validated

### ISSUE THREAD

**Issue by ArtFl-2** [ahmedkaludi/accelerated-mobile-pages#3062]
I have found the cause – it’s incompatibility with the WP Rocket plugin!

Last week WP Rocket had 2 big updates (https://wp-rocket.me/changelog/), alongside with AMP for WP. I don’t know whose update has led to incompatibility but after those updates my AMP pages stopped loading and were not validated by Google any more.

After it happened, I tried to disable most wp plugins, including WP Rocket, with the AMPforWP Plugin Manager but it didn’t work.

I’ve also made a rollback to the previous major version of WP Rocket but it helped only partly. 
The AMP pages started to load in all browsers but Google still didn’t want to validate them.

Now it’s clear that to make AMP for WP work correctly as before, you need to completely deactivate WP Rocket.

Ahmed, you have to do something with that! WP Rocket is a popular plugin, and it should be compatible with AMP for WP.

Taking this opportunity, I should say that a couple of days ago, my Ad Inserter Pro - after its own update last week – was also incompatible with AMP for WP. I was shocked to see 10 Adsense ads (!) on my small post: all the ads from Ad Inserter were displayed simultaneously with AMP for WP and Advanced AMP ads. Fortunately, Ad Inserter Pro has quickly improved the situation with a new update on Sunday. 

Today there are only a few incompatibilities and bugs that I still can see on my desktop:

1/ Jetpack’s Related Posts stopped showing on AMP pages. On my pages, only their title “Check These Out!” has survived (produced by a code in my theme’s functions file). It’s a pity!

2/ In AMP for WP options => Design => Single => Single design, there are two pictures to select – one with a sidebar, another without. They work the wrong way: if you need a design without sidebar, you have to choose a picture with sidebar :)

3/ In AMP for WP options => Design => Single => Categories & Tags Links, if you switch it off, the links are still shown on your page but only stop being interactive. Normally, they should go away.

Hope you can improve all these.

**Comment by Zabi09** [comment]
@ArtFl-2 
Yes recently the WP Rocket plugin made some changes and due to that the validation errors were appearing on the AMP pages but we have already fixed the issue and currently, our testing team is reviewing it and will you please provide us your website credentials so that we will apply the solution on your website also and in addition to this we will also debug your issues related to jetpack, single design, and categories tags links,

Please provide us on team@magazine3.com and our team will help you in fixing all your issues.

**Comment by ArtFl-2** [comment]
Hi Zabi09, thank you for your kind proposal. Actually, after finding out why my AMP pages do not load and are not validated, I have deactivated my purchased WP Rocket plugin and installed a free WP Super Cash instead. The problem was solved. When AMP for WP and WP Rocket become compatible again, I will probably return to WP Rocket again :)

**Comment by Zabi09** [comment]
@ArtFl-2 
We have already fixed the issue of wp-rocket in this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2988 and you can follow this ticket for update and we will make sure it will be pushed in this week for sure.
And once that ticket is closed you can go ahead and update our plugin and also install the wp-rocket.

**Comment by ArtFl-2** [comment]
Hi Zabi09, thank you for the good news! I'll do that. Have a good day!

**Comment by Zabi09** [comment]
We will fix this ticket in #2988 please track that So closing this one

**Comment by MARQAS** [comment]
I believe It is different from #2988. We will look into it more

**Comment by ArtFl-2** [comment]
Great, thank you for your carefulness!

**Comment by Zabi09** [comment]
@ArtFl-2 
We have fixed your validation errors which were coming from the wp-rocket plugin and will you please provide us more information and screenshots about your other issues of Ad Inserter Pro, Jetpack’s, and other issues So that we check again and get back to you,

**Comment by pegazee** [comment]
** Review **

- [ ] Imran

- [ ] Talha

**Comment by ArtFl-2** [comment]
Zabi09,

Thank you for fixing, I have installed the update but haven't tested it with WP Rocket yet.

At the moment I don’t have any problems with AdInserter Pro because they have quickly removed the incompatibility with AMP for WP with their update 2.4.15 of 2019-04-19.

As for the other bugs:

1.  Jetpack’s Related Posts stopped showing on AMP pages.
Normally they were displayed after the headline “Check These Out!”, right before the AdSense links. 
Now only the Related Posts’ headline is left (Screenshot 1), changed by a code in my theme’s functions file (Screenshot 2).

2.  In AMP for WP options => Design => Single => Single design, there are two pictures to select – one with a sidebar, another without. They work the wrong way: 
-	If you chose the picture without sidebar, you get a page with sidebar (Screenshot 3, Screenshot 4, the blank space is the ad);
-	If you need a page without sidebar, you have to choose a picture with sidebar (Screenshot 5, Screenshot 6, the blank space is the ad)

3.  In AMP for WP options => Design => Single => Categories & Tags Links:
a/ If you switch it on, the links are shown on your posts and loops and they are interactive (Screenshot 7, Screenshot 8); 

b/ If you switch it off, the links don’t go away. They are still shown on your posts but they stop being interactive (Screenshot 9, Screenshot 10).
As for your category pages/loops, nothing changes if you switch it off. The links don’t go away and they remain interactive (Screenshot 11).

c/ Whether you switch it On or Off, the Tags links are not displayed on the pages.

BTW, it would be great, if you could separate Categories from Tags. On my pages, for example, I would prefer to have tags links only (without categories links).

![Screenshot 1](https://user-images.githubusercontent.com/49853569/56726976-15112300-6750-11e9-881e-76875ec213bc.png)

![Screenshot 2](https://user-images.githubusercontent.com/49853569/56726977-15a9b980-6750-11e9-8d9b-881e11d668ff.jpg)

![Screenshot 3](https://user-images.githubusercontent.com/49853569/56726978-15a9b980-6750-11e9-86cd-6481244f1447.jpg)

![Screenshot 4](https://user-images.githubusercontent.com/49853569/56726979-15a9b980-6750-11e9-80aa-acb724f78634.jpg)

![Screenshot 5](https://user-images.githubusercontent.com/49853569/56726968-14788c80-6750-11e9-8a4b-6b8c32d06f24.jpg)

![Screenshot 6](https://user-images.githubusercontent.com/49853569/56726969-14788c80-6750-11e9-988e-ca5071677088.jpg)

![Screenshot 7](https://user-images.githubusercontent.com/49853569/56726970-14788c80-6750-11e9-9545-f3d536446b53.jpg)

![Screenshot 8](https://user-images.githubusercontent.com/49853569/56726971-15112300-6750-11e9-9261-70bc50a76bd0.jpg)

![Screenshot 9](https://user-images.githubusercontent.com/49853569/56726972-15112300-6750-11e9-80a1-cbbdc9f51764.jpg)

![Screenshot 10](https://user-images.githubusercontent.com/49853569/56726974-15112300-6750-11e9-8729-3c924bdfb93b.jpg)

![Screenshot 11](https://user-images.githubusercontent.com/49853569/56726975-15112300-6750-11e9-89a4-4be8562fb74b.jpg)

**Comment by Zabi09** [comment]
@ArtFl-2 
1 - Will you please tell us exactly after which version your jetpack’s related posts stopped showing on AMP pages? and the screenshot (jetpack function) which you have shared with us is only for outputting the headline? is that function outputs the posts also?

2 - Yes we have two designs in the single section and in which the first one will be by default and it will have a design like this - https://prnt.sc/nk9yqz that is the additional things like social share, author, date, etc on the left and the content on the right and the second design that is - https://prnt.sc/nk9yg5 it will have sidebar on the right and once you enable that you also need to add the widgets in amp sidebar widget - https://prnt.sc/nk9zjt and then it will appear like - https://prnt.sc/nk9ylg

3 - We have already fixed the issues which you have mentioned in this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2885 and if you only want the tags on the single then you can enable the tags option from the single and it will be displayed after the  author like - https://prnt.sc/nka7gq

Please check and let us know and for faster communication, you can directly contact us on team@magazine3.com and our team will get back to you as soon as possible.

**Comment by ArtFl-2** [comment]
Hello,

1/ Unfortunately, I can’t tell exactly when it happened. I mentioned it about two weeks ago, a couple of days before I opened the issue #3062.

The jetpack function is only for changing/customizing the headline for jetpack related posts. After your last updates this custom headline stopped showing on AMP pages too.
It’s good because without related posts it doesn’t make sense. I guess that you’ve done something with that.

2/ Thank you for explaining how the design selector works. I don’t need any sidebar for AMP pages so I have to choose the second design without using widgets.

There is some confusion for a user though, because the picture of the first design doesn’t show the sidebar at all, and the user thinks that it is a no-sidebar design.

I think you should change this picture to show the left sidebar and additionally explain that the second design should be used with widgets.
It would be great if there’s a no-sidebar design option as well :)

3/ Thank you for fixing the problem with the categories and tags, now it works fine.

Best,
@ArtFl-2

**Comment by Zabi09** [comment]
@ArtFl-2 
1 - We have not done any specific changes related to jetpack’s related posts but don't worry we will fix your issue on your end,
2 - We have also created the ticket for changing the screenshots of the single designs and it will be updated soon - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3140

**Comment by ArtFl-2** [comment]
Thank you :)

**Comment by ArtFl-2** [comment]
-- Please reply above this line --


            Hi,

Regarding the issue, will you share us wp-admin access and FTP
details, so that our developer will solve your issue.

Warms Regards,
Amer.
AMPforWP Customer Success Team 
(About Our Team [1])

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://bit.ly/2q5UQW9
[2]
https://secure.helpscout.net/satisfaction/253839367/record/2359863253/1/
[3]
https://secure.helpscout.net/satisfaction/253839367/record/2359863253/2/
[4]
https://secure.helpscout.net/satisfaction/253839367/record/2359863253/3/

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/845078996/64777/

**Comment by MARQAS** [comment]
Can we close this ticket @ArtFl-2 and @MohammedKaludi?

**Comment by ArtFl-2** [comment]
Yes, please close it.
@ArtFl-2
