### ISSUE TITLE
featured images or article images not showing in latest version

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3063]
Ref.
https://secure.helpscout.net/conversation/833038860/63669/

We have the credential of this user.
https://secure.helpscout.net/conversation/833038860/63669?folderId=2844667

**Comment by pegazee** [comment]
User is using the "Publisher" theme by a better studio. And they providing the lazy load feature.

**Comment by pegazee** [comment]
** review **

- [ ] Imran

- [ ] Talha

**Comment by pegazee** [comment]
Pushed in 0.9.97.49
