### ISSUE TITLE
post not redirecting to amp version with /amp when custom permalink is set

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#3064]
when custom permalinks are set (.htm) post are not redirecting to AMP version with /amp.

Ref: https://secure.helpscout.net/conversation/787325745/56883/

**Comment by MARQAS** [comment]
Unable to reoccur, it's happening only on users end. Ask the user for more info.

**Comment by MARQAS** [comment]
As far as our findings It is occurring only on Users end due to server-side caching.

**Comment by MARQAS** [comment]
We will tackle this ticket here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3166.
Follow that ticket for more info
