### ISSUE TITLE
We should work on our defaults

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3065]
Ideally, homepage, post, pages, Archives should be on,.

and other such defaults.

**Comment by Zabi09** [comment]
- [ ]  Logo should be automatically deducted from customize  - https://prnt.sc/o4dvt6
- [ ] Archives [Category & Tags] should be ON
- [ ] Convert AMP to WP theme (Beta)  should be Advance Settings
- [ ] Minify should be ON
- [ ] Logo should be automatically deducted from customize in 'Default Structured Data Logo' also
- [ ]  Rename 'Display on User Avatar' to User Avatar

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
