### ISSUE TITLE
Version V0.9.97.46.1 - AMP takeover not working

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#3067]
Latest version of this plugin now breaks my sites – WP 5.5.1, Genesis framework 2.9.1, Design 2 and in AMP takeover. Looks like AMP takeover is no longer working – I just get non-amp pages. Very simple sites too with no interfering plugins.

All works on prior release of the AMP plugin.

AMP plugin version V0.9.97.46.1 doesn’t work (tried this yesterday)
AMP plugin version V0.9.97.47 doesn’t work (tried this just now)
AMP plugin version V0.9.97.44 works fine

**Comment by ahmedkaludi** [comment]
Can you please send us the WP details via https://ampforwp.com/support/

I will personally look into this issue and fix it ASAP.

**Comment by Frenchomatic** [comment]
Just sent details - please be quick as it is on cloudflare (dev mode so only 2 hours)

**Comment by Frenchomatic** [comment]
Have you looked yet?

**Comment by Frenchomatic** [comment]
OK it works on version V0.9.97.47 - I found the problem. You have to also have Individual AMP Page (Bulk Edit) set to "Show by default" or the AMP takeover doesn't work.  So now my sites are running ok again.  Ticket can be closed.

**Comment by MARQAS** [comment]
Hi @Frenchomatic, Yes it is connected to that option, so if anyone wants to disable the AMP takeover option from the pages they can easily do so.
