### ISSUE TITLE
AddThis is causing validation error after Update

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3068]
AddThis is causing validation error after Update

It's still not clear, we will go ahead and create the ticket for this: https://wordpress.org/support/topic/amp-pages-are-not-valid/#post-11456756

**Comment by pegazee** [comment]
The issue is occurring from the other plugin, not from our plugin. And also I've tried to recreate the same issue on my end but it's not created. I think AddThis authors resolve the issue in the latest version.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Use any existing filter While pushing the code.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/78fc4619cedd05c08db0fecf2c37bbf6c2a6c8e2#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6750

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
