### ISSUE TITLE
Logo size for Google News AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#307]
Hey guys,

My site is listed in Google news and I am using AMP for WP since the last few months. Recently, I noticed that the logo that is appearing in the top stories section (for my site) is smaller than it should be.

While Google says the size should be 600×60, the AMP page displays a different size. So, even though I added a logo with height 60 pixels, it seems extremely small in the top stories section compared to everyone else.

Could you please look into this. It might be affecting other sites as well.

Reference: http://prnt.sc/dk6edr
Site: localpress.co.in

P.S: You had asked me for my contact details in a earlier post. I saw it today and shared the details on that post. Sorry for the delay.

REF: https://wordpress.org/support/topic/main-logo-size/

**Comment by MARQAS** [comment]
I guess this is same as #162 and #817 and they have been resolved in the previous version.

Am I right @ahmedkaludi ?
