### ISSUE TITLE
warning message while on WP customizes

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3070]
Ref.
https://secure.helpscout.net/conversation/834209489/63788?folderId=2844667

Warning: Use of undefined constant AMP_CUSTOMIZER_QUERY_VAR - assumed 'AMP_CUSTOMIZER_QUERY_VAR' (this will throw an Error in a future version of PHP) in /homepages/3/d667962170/htdocs/clickandbuilds/WordPress/freetopicsforuni/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/admin/class-amp-customizer.php on line 169

Warning: Use of undefined constant AMP_CUSTOMIZER_QUERY_VAR - assumed 'AMP_CUSTOMIZER_QUERY_VAR' (this will throw an Error in a future version of PHP) in /homepages/3/d667962170/htdocs/clickandbuilds/WordPress/freetopicsforuni/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/admin/class-amp-customizer.php on line 169

**Comment by MARQAS** [comment]
Customizer not working

**Comment by pegazee** [comment]
** Review **

- [ ] Imran

- [ ] Talha

**Comment by pegazee** [comment]
Pushed in 0.9.97.49
