### ISSUE TITLE
Unspecified Type in Structured data in cats/tags

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3071]
Ref: https://www.penserchanger.com/mot-clef/competences-sociales/amp

**Comment by ajeetku** [comment]
Escape before assignment if the title contains any quote, it will break schema JSON

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
