### ISSUE TITLE
Https Missing in the URL

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3072]
Help Scout Link: https://secure.helpscout.net/conversation/833048988/63670?folderId=2770545

Screenshot: https://monosnap.com/file/6WlNPI4pYEMsgQu4ZsvkB9t99Z8mL8

Due to enable relative agreement option in WP Rocket > Cloudfare >Relative Agreement "https" from the URL get removed.

Screenshot: https://monosnap.com/file/m7rmjWXfPMPWvINhS8xCwl1ND5MDOi

**Comment by pegazee** [comment]
Already solved in #3062
