### ISSUE TITLE
Due to Enable image replacement option in optimole plugin images get removed in AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3073]
Help Scout Link: https://secure.helpscout.net/conversation/833048988/63670?folderId=2770545

ScreenShot: https://monosnap.com/file/q6jY4HglDYk7xvlEQ1esYgTyALZuBB

**Comment by Zabi09** [comment]
Unable to recreate the issue on localhost.
Without enabling the option - https://monosnap.com/file/pCnpUUGdxB5xhRcgKvHQ2FX1Yc24Ji
After enabling the option - https://monosnap.com/file/cE1d79K9t2LWXqps3iEqz3evLoONEI

Waiting for FTP details.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
