### ISSUE TITLE
Error in Article schema automatically generate by Yoast SEO in non-amp

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3074]
Ref:https://secure.helpscout.net/conversation/813146702/61378?folderId=2770543
 localhost same error

**Comment by Zabi09** [comment]
Will be going to fix in - https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/231 and going to push in 1.7 version of the schema and structured data for wp
