### ISSUE TITLE
fatal error with 0.9.97.47 on M3 Garage

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3076]
<b>Fatal error</b>:  Can't use function return value in write context in <b>/home/mattk/public_html/garage/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/swift/style.php</b> on line <b>293</b><br />
 
https://monosnap.com/file/iCk9ruwGD2BdSwZVzrDdPQ36JKJsix

**Comment by pegazee** [comment]
This issue was fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3087

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.49
