### ISSUE TITLE
0.9.97.48 has a bug, which shows extra bracket [Pre-Release BUG]

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3077]
There are extra symbols that are displaying in the head while testing. and that's being displayed in the non-AMP. See this: https://monosnap.com/file/IVaLvNeV6sYFm2INTV4B7Nb1krVjzB

It's coming from here: https://monosnap.com/file/l9v5VyG1gm3uNevKMWPjbgLjChCcFx

I rolled back to 0.9.97.47 and it seems to be working fine.

**Comment by pegazee** [comment]
Pushed in 0.9.97.48
