### ISSUE TITLE
Debug Warnings AUTH_KEY & SECURE_AUTH_KEY

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3078]
http://prntscr.com/ne5j64

Warning: Use of undefined constant AUTH_KEY – assumed ‘AUTH_KEY’ (this will throw an Error in a future version of PHP) in /var/www/vhosts/—-/httpdocs/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/inc/class.redux_instances.php on line 67

Warning: Use of undefined constant SECURE_AUTH_KEY – assumed ‘SECURE_AUTH_KEY’ (this will throw an Error in a future version of PHP) in /var/www/vhosts/—.–/httpdocs/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/inc/class.redux_instances.php on line 67

REF: https://wordpress.org/support/topic/error-after-activating-the-plug-in/#post-11451811

**Comment by MARQAS** [comment]
AN older or incorrect install of WordPress. See this and take the appropriate actions as necessary: https://www.wpbeginner.com/glossary/security-keys/
