### ISSUE TITLE
After Update to Version 0.9.97.47, Unable to Install New Plugins

### ISSUE THREAD

**Issue by vagu71** [ahmedkaludi/accelerated-mobile-pages#3081]
After updating the AMPforWP plugin to version 0.9.97.47, we're unable to install any new plugins on the site. In order to install any new ones, we have to deactivate AMP, then install the plugin we're trying to install, and after activation of the new plugin, we activate AMP again.

**Comment by MohammedKaludi** [comment]
This is very strange, do you get any error or what exactly happening when you are trying to activate other plugins?

**Comment by vagu71** [comment]
There isn't an error as such. It does nothing. New plugins do not install. The console shows this when the Install button next to a new plugin is pressed: 

```
ReferenceError: contentChanged is not defined[Learn More] dependencyScript.js:7:6
    <anonymous> /wp-content/plugins/accelerated-mobile-pages/base_remover/dependencyScript.js?ver=5.1.1:7

```

**Comment by MohammedKaludi** [comment]
Okay, thank you very much for reporting the issue we will check and fix this on a very high priority basis.

**Comment by MohammedKaludi** [comment]
Related to#3079

**Comment by MARQAS** [comment]
Hi @vagu71 Thanks for reporting it, we have resolved this issue here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3079
And it will be released in a few hours. Please do check for the update.

**Comment by MARQAS** [comment]
As this is a duplicate issue, I am closing this one. One can track this issue here: #3079
