### ISSUE TITLE
Tags are also displaying in the category selection in the AMP page builder

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3082]
Ref: https://secure.helpscout.net/conversation/834980402/63849?folderId=1680016

Even In localhost, the issue persists.

https://monosnap.com/file/TTEkPwiL90Dn4ECWfMucF4RrAfGteV

**Comment by ajeetku** [comment]
Check Prior to 4.5.0/ Since 4.5.0
the deprecated function will give a notice, Use version condition here
https://developer.wordpress.org/reference/functions/get_terms/

**Comment by pegazee** [comment]
I've checked the debug log and didn't get any notice or warning. 

Note: I'm using the WordPress v5.1.1

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
