### ISSUE TITLE
Label names and position of the single article elements in swift

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3083]
### List 

- [x] Light box and Drop cap should be in General tab

- [x] Recent posts label should be [Recent posts below Related] and it should be in single elements Tab

- [x] Link to author should be single elements tab

- [x] Advanced single option will be the last in General tab and sub child should be in proper way.

- [x] Get the images side by side in option panel in Design > single 
Current images - https://monosnap.com/file/L4B212iaYUdJ5Gh6KGu0DN1VczoA0n
Need to get - https://monosnap.com/file/CwqO57ftIjmPJmDhT9jG9Xyh9NKiUn

**Comment by MARQAS** [comment]
Where is the Dropcap child option?

**Comment by pegazee** [comment]
Escaping missing
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/acb57f7ba2b7a028ade10142ccbca42fca7065a7

**Comment by pegazee** [comment]
Need more escaping:

- [ ] https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/acb57f7ba2b7a028ade10142ccbca42fca7065a7#diff-260eba6333c3222e59a6aed22ac5ab37R5218

**Comment by RajuJeelaga** [comment]
@pegazee Please check the code, escaping  is added properly

**Comment by MohammedKaludi** [comment]
Why Dropcap is visible for all designs? DropCap should only be for swift, but if we apply for all designs then the Styling is not applying on D1, D2 and D3.

**Comment by MohammedKaludi** [comment]
Read to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
