### ISSUE TITLE
Add the layout="fill" in the  the amp_loop_image

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#3084]
- [x] Add the layout="fill" in the amp_loop_image function so third party plugin can change the layout="Responsive" to layout="fill" while passing the value in $args.

example: we have this code in loop/loop.php
if ( isset($data['responsive']) && $data['responsive'] != "" ) {
			$layout_responsive = 'layout=responsive';
			}
So to change the layout to "fill" we have to add this code in loop/loop.php
elseif ( isset($data['fill']) && $data['fill'] == true ) {
			$layout_responsive = 'layout=fill';
		}

- [x] Also for the inline related post we are adding static layout="Responsive" so allow the third-party plugin to override it with layout="fill" 

Also in else condition, we are adding 150/150 width and height it should be full image width and height as upload by the user (full image).
See this screenshot: https://monosnap.com/file/cQoA9WEBaTGtcP333lmbUH1f6lgMRY

**Comment by MohammedKaludi** [comment]
Need lot of improvements in this code.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2aea4fcad4822e1353c0e8b28880507964635eb8#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4793

**Comment by pegazee** [comment]
For testing purpose, Please add the below code:
`add_filter('ampforwp_modify_inline_rp_loop_image','dummy_function');
function dummy_function($args){
    $thumb_url_2 = ampforwp_get_post_thumbnail('url');
    list($width, $height) = getimagesize($thumb_url_2);  

   $custom_img = preg_replace(
     '/<amp-img src=(.*?)\s(.*)width=(.*?)\s(.*)height=(.*?)\s(.*)layout=(.*?)\s><\/amp-img>/',
      '<amp-img src='.$thumb_url_2.' width='.$width.' height='.$height.' layout="responsive" class="img-cover"></amp-img>', $args);
    

  $custom_changes .= '<div class="image-container-rltd">';
  $custom_changes .= $custom_img;
  $custom_changes .= '</div>';
  $args = $custom_changes;
  return $args;
}`

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58 need to write the tutorial.

**Comment by pegazee** [comment]
Created a ticket in a tutorial department
