### ISSUE TITLE
Undefined variable: wp

### ISSUE THREAD

**Issue by alberto-segura** [ahmedkaludi/accelerated-mobile-pages#3085]
I just updated to V.0.9.97.48 and I get the following: 
Undefined variable: wp in /var/www/html/spotmegirl/public/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php on line 322
Notice: Trying to get property 'request' of non-object in /var/www/html/spotmegirl/public/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php on line 322

I think it is missing: **global $wp;** inside the function ampforwp_page_template_redirect_archive()

**Comment by MohammedKaludi** [comment]
also  @MARQAS  `ampforwp_redirect_to_orginal_url` also missing the global wp variable.

**Comment by MARQAS** [comment]
More debug issues:
amp_custom_content_enable

**Comment by MARQAS** [comment]
Notice: Undefined property: WP_Error::$cat_ID in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 4158

**Comment by MARQAS** [comment]
Notice: Undefined index: amp-analytics-select-option in /Volumes/Storage/MAMP/htdocs/wp-test/wp-content/plugins/accelerated-mobile-pages/includes/features/analytics/analytics-options.php on line 6
(this errors appears few times in some loop)

Notice: Undefined index: amp-opt-color-rgba-colorscheme in /Volumes/Storage/MAMP/htdocs/wp-test/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 3326
Notice: Undefined index: amp-design-selector in /Volumes/Storage/MAMP/htdocs/wp-test/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 5941

Still get some old errors that I reported before:

Notice: Undefined index: ampforwp-homepage-on-off-support in /Volumes/Storage/MAMP/htdocs/wp-test/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 38
Notice: Undefined index: amp-frontpage-select-option in /Volumes/Storage/MAMP/htdocs/wp-test/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 41
Notice: Undefined index: ampforwp-homepage-on-off-support in /Volumes/Storage/MAMP/htdocs/wp-test/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 38
Notice: Undefined index: amp-frontpage-select-option in /Volumes/Storage/MAMP/htdocs/wp-test/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 41

**Comment by MARQAS** [comment]
Undefined index: ampforwp-amp-on-off in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 5807

**Comment by pegazee** [comment]
** Review **

- [ ] Imran

- [ ] Talha

**Comment by Zabi09** [comment]
Ready to merge:

**Comment by pegazee** [comment]
Pushed in 0.9.97.49

**Comment by MohammedKaludi** [comment]
//AMP theme framework and AMP layouts and this is required

The unnecessary text was visible with the amp-menu component.
