### ISSUE TITLE
How to Remove unused js from amp pages

### ISSUE THREAD

**Issue by kashifali12** [ahmedkaludi/accelerated-mobile-pages#3086]
How to Remove unused js from amp pages please tell me in detail

**Comment by MARQAS** [comment]
Hi @kashifali12, Can you share an example of unused JS on your website?
We add only the necessary ones, please share an example like a URL or a screenshot.

**Comment by kashifali12** [comment]
![unused-js](https://user-images.githubusercontent.com/16741317/56731063-320d1c80-6777-11e9-889e-d598e674784e.png)

**Comment by MARQAS** [comment]
@kashifali12, amp-animation is used in back-to-top functionality.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
