### ISSUE TITLE
Fatal error -  can't use function return value in write context

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3087]
https://secure.helpscout.net/conversation/834769284/63830/

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.49

**Comment by MohammedKaludi** [comment]
Fatal error: Can't use function return value in write context in /home/rakhesh/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/structure-data/structured-data-functions.php on line 16

**Comment by MohammedKaludi** [comment]
👍 Looks good.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
