### ISSUE TITLE
AMP Customizer not working

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3088]
Is this because of #2287 or even before that? we need to check and resolve it ASAP.

**Comment by MARQAS** [comment]
Another ticket related to this: #3069

**Comment by pegazee** [comment]
In beta, we've decided to remove the customizer. So, I've committed the solution code in the maser to run the customizer in master, not in beta.

**Comment by MohammedKaludi** [comment]
Ready to push. The code will be pushed in 0.9.97.51

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.51
