### ISSUE TITLE
**Vkontakte Share(social icon) does not open in a new tab **

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3089]
Ref:
https://secure.helpscout.net/conversation/834721178/63827?folderId=2844667

**Comment by pegazee** [comment]
- why not in design -2?
- And also the color of the icon was different in design -2 & design-1 when comparing to the other designs.
Screenshot: Design -2 & 1: https://take.ms/SKEQo, https://take.ms/JVKPW
Design-3: https://take.ms/oiHRl

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
