### ISSUE TITLE
Related Posts Design is coming in all the single page designs in AMP Layouts

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3091]
- [x] Related Posts Design is coming in all single page designs in AMP layouts and AMP single page Design 2 as well.
and it is showing only when we select Related post design 2 and design 3
please see the screenshot single page from AMP layouts.
https://monosnap.com/file/MvWOJw42Q9BHRfypEc992JaBVdHnff

**Comment by RajuJeelaga** [comment]
It is appearing only in master, Beta it is coming fine

solution:
add the condition for the related post design in swift single page
$redux_builder_amp['single-design-type'] == '1'
https://monosnap.com/file/5t7oKLrIku3FhBF1Snhnp07wMC9SlP

**Comment by pegazee** [comment]
Use ampforwp_get_setting instead of $redux_builder_amp
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/24eefb3663e4cee4020a3a3d19e02b8736e1a6df

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
