### ISSUE TITLE
Leave Comment Not working with ?amp

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3093]
Help Scout Link: https://secure.helpscout.net/conversation/837317337/64033?folderId=2770545

Issue recreated in local.

When the user clicks on the leave comment it taken to the top of the website instead of the comment box.

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
