### ISSUE TITLE
Improvements if the users is on the Older versions of WordPress

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3094]
- [x]  Create a notice if the user is using the older version of WordPress then 4.6 and do not activate the plugin

- [x]  Update `Requires at least: 3.0` to 4.6 in readme.txt 

- [x]  add `if class_exists` while adding calling the class in /accelerated-mobile-pages/includes/vendor/amp/includes/lib/fasterimage/FasterImage.php on line 85

Referance: https://wordpress.org/support/topic/fatal-error-class-requests-not-found-2/

**Comment by MARQAS** [comment]
Some improvement in the message is needed, https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/436082b606f3ac80c64ffc2d13b2963f167173ec#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1108

**Comment by pegazee** [comment]
@MARQAS can you tell me what message is needed?

**Comment by MohammedKaludi** [comment]
ready to merge.
Do consult me before mergring.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
