### ISSUE TITLE
 we want the amp menu showing from left or right side both.

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3095]
Ref.
https://secure.helpscout.net/conversation/837762366/64069?folderId=2844667

**Comment by MohammedKaludi** [comment]
in Design 3 -> menu X mark is on the Search button 
https://take.ms/nB0Im

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
