### ISSUE TITLE
Issue with video post type in format

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3096]
Ref:https://secure.helpscout.net/conversation/835632754/63885?folderId=2770543
Here user wants to create a video post as a feature video on the page

**Comment by MARQAS** [comment]
Duplicate issue: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3317
Tutorial: https://ampforwp.com/tutorials/article/how-to-add-featured-video-in-place-of-featured-image/
