### ISSUE TITLE
Undefined variable 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3103]
Notice: Undefined variable: srcet in C:\xampp\htdocs\wp\wp-content\plugins\accelerated-mobile-pages\components\featured-image\featured-image.php on line 53

https://monosnap.com/file/K0obJkOMozpXa6O6yaIMlQ8kTs3lJG

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3028#issuecomment-487478492


Notice: Undefined index: amp-design-selector in /Volumes/Storage/MAMP/htdocs/wp-test/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 5995

**Comment by Zabi09** [comment]
Undefined index: amp-design-selector - Added in master
Notice: Undefined variable: srcet - Not added in master

**Comment by MohammedKaludi** [comment]
Undefined index: amp-design-selector - pushed in 0.9.97.50

**Comment by pegazee** [comment]
We've given this ticket reference on this ticket: #2541. We can close this ticket.
