### ISSUE TITLE
Formcraft compatibilty

### ISSUE THREAD

**Issue by AlvinASaputra** [ahmedkaludi/accelerated-mobile-pages#3104]
Hi Ahmed,

I am using wordpress plugin for form called Formcraft in my wordpress. It seem not compatible with AMPforWP. The form looks normal in original page but not in AMP version.

This is the original page : https://ibb.co/fDGGSLV
This is the AMP page : https://ibb.co/z5V4dK1

We are using that form in many post. Can you develop a new feature regarding this issue?

Thanks

**Comment by MARQAS** [comment]
Hi @AlvinASaputra, Thanks for requesting the feature. We have added it in the list, but I am sorry to say that this has low priority for us at the moment as the list of features is very much big and their priority is very high when compared to this plugin. So it's not going to come in the near feature. You can either wait for this compatibility or you can hire us to do this on a priority basis(https://ampforwp.com/hire/N).
