### ISSUE TITLE
Dropcap functionality is not working for infinite scroll post

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#3105]
Ref:  https://secure.helpscout.net/conversation/804855935/60148?folderId=1914715

**Comment by RajuJeelaga** [comment]
@ansaritalha 
Dropcap functionality is working fine, from my end on infinite scroll, 
Please see this https://monosnap.com/file/iHZFjyTtCBDHROmhD9KN2w9zT3iJL0
can you recreate this issue on your end...?

**Comment by Zabi09** [comment]
Working as expected

**Comment by pegazee** [comment]
Working perfectly on my end, @Rkroy check once on your end.

**Comment by Rkroy** [comment]
Working fine at my end,

**Comment by MohammedKaludi** [comment]
If correctly working in master then ticket can be closed

**Comment by RajuJeelaga** [comment]
Drop cap functionality is working fine on infinite scroll post, in Master
