### ISSUE TITLE
Disqus comments are not loading in the multilingual slug.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3106]
Disqus comments are not loading in the multilingual slug.
Ref: https://secure.helpscout.net/conversation/820928299/62490?folderId=2322649

**Comment by nakib4tech** [comment]
Please resolve this issue ASAP as I am expiring this issue for about 40 days on my site: https://nakib4tech.com/
Cheers.

**Comment by Rkroy** [comment]
Not working at user's end, please check.

**Comment by Zabi09** [comment]
I have debugged a lot and it seems that it's not working due to cache because I am updating the code in cpanel but there are no changes on the frontend,

**Comment by Rkroy** [comment]
No issue with cache, the comments are not loading, please check.

**Comment by MohammedKaludi** [comment]
👍 Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
