### ISSUE TITLE
Close Button is not coming in iphone in swift theme

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3107]
HelpScout Link: https://secure.helpscout.net/conversation/838948671/64149?folderId=2770545

When the user is using an iPhone then the close button is not appearing. User is using 

Screenshot: https://monosnap.com/file/HvkwHJT0fPeOfkXcLheTZsZZmb5Sz8

**Comment by RajuJeelaga** [comment]
Reference Link: https://taiwanjin.com/freetalk-exchange/amp/

**Comment by RajuJeelaga** [comment]
- [ ] cross button is properly connected to color option panel

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
