### ISSUE TITLE
Lighthouse score should be 90+ in all designs

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3108]
Lighthouse score should be 90+ in all designs in all your areas.

**Comment by Zabi09** [comment]
Notice: Undefined variable: imagCelass in C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\components\loop\loop.php on line 472

**Comment by amer07** [comment]
1. [user-scalable="no"]
2.<meta name="viewport">
3.[maximum-scale]

Note: add this attribute

**Comment by Zabi09** [comment]
User was saying - on the normal screen I can increase or decrease text and image size y means of zoom.
I cannot do the same for the amp version for the mentioned page or any other page for that matter.

So user-scalable=yes is correct for lighthouse and also for user

**Comment by MohammedKaludi** [comment]
Alt text should contain the Author name, not the general text.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4aa11180b1bb805070f0203f16cdadc5003d4643#diff-d9e62bf7636c72ea611757e43f70c46eR10

**Comment by MohammedKaludi** [comment]
Why used wp kses??

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/aeda137c55251603472ce69b05fe6781f5eb2dd5#diff-d9e62bf7636c72ea611757e43f70c46eR502

**Comment by MohammedKaludi** [comment]
Remove `ampforwp_get_the_ID` from  `esc_html(get_the_title(ampforwp_get_the_ID()))`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4baee11ddfee518453b7252ce4ad38ebc8395fa6#diff-d9e62bf7636c72ea611757e43f70c46eR502

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
