### ISSUE TITLE
In content related posts in Design 3 images are not showing

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3109]
Ref.
https://secure.helpscout.net/conversation/839924878/64220?folderId=2844667

**Comment by RajuJeelaga** [comment]
In this ticket Need to fix the images stretching problem in Design 1,2  and in Design 3 images are not there, need to add the images.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
