### ISSUE TITLE
Breadcrumbs issue with Rankmath in structured data

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3111]
https://wordpress.org/support/topic/error-after-upgrade-to-version-0-9-97-48/

**Comment by Zabi09** [comment]
False deduction confirmed by @ahmedkaludi and closing this ticket

**Comment by TMsravan** [comment]
This is the user help scout URL: https://secure.helpscout.net/conversation/830894769/63548?folderId=2632028

**Comment by MARQAS** [comment]
@Zabi09 Please remove the code and close this ticket
