### ISSUE TITLE
Improvement in image sanitizer

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3112]
Help Scout Link: https://secure.helpscout.net/conversation/839427313/64178?folderId=2770545

User has added below code to fix it but he is not satisfied with this code

In the plugin file "class-amp-img-sanitizer.php" on line 115.
from:
$height = round( ( floatval( $node->getAttribute( 'width' ) ) * $dimensions['height'] ) / $dimensions['width'] );

to:
$height = round( ( floatval( $node->getAttribute( 'width' ) ) * $dimensions['height'] ) / ($dimensions['width']+1) );

**Comment by MohammedKaludi** [comment]
Fix not working, do let me know if you want to test. Issue is recreating in my localhost.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
