### ISSUE TITLE
Addthis option UX issues

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3114]
- [x] the name of a feature should not be "Enable XYZ".. https://monosnap.com/file/CZl4dz8yIak8NXqLiBHNv6ZwBbqPLG - Pick a better userfriendly name

- [x] the "Click here" to know thing... below the image should go into the tooltip, not below the option. and the description of the tooltip also needs to be good.

- [x] Implement the Pub ID and Widget ID provided by the Chad https://secure.helpscout.net/conversation/834276860/63795/ - No need to give options for this

- [x] They have two features, Floating and Inline Share Buttons tool, Check properly on what they provide in the AddThis AMP support and check if we are providing all of it and then get a confirmation from me.

- [x] Make sure the documentation improves accordingly

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Need to make sure its compatible with Layouts.
For more info please check below comment from Imran.

**Comment by syedimran22** [comment]
Default we should load above content position and sidebar position option should be available only for swift single design not for amp layouts single designs.

**Comment by pegazee** [comment]
before releasing this ticket, we need to release the update of AMP layout plugin

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4e16b044af4f970794274b0d384d0a8db4bcc5e0#diff-260eba6333c3222e59a6aed22ac5ab37R6213


add `$addthis_pos_opt['default'] = 'Single Sidebar (left side)';` inside the array and set the default afterward

Like this:

$addthis_pos_opt = array(   
'default' 		=> 'Single Sidebar (left side)',
'above-content' => 'Above Content',
'below-content' => 'Below Content'
);

 if(ampforwp_get_setting('single-design-type') == '1'){
        $addthis_pos = 'default';
 }

**Comment by pegazee** [comment]
In some use-case scenario, like I've selected the single-design-type 1 and then the default value will be the sidebar. And after that to test, I've selected the single-design-type 2 & I've not reset the social section to get the default value so the value is getting blank and in the frontend, validation occurred for single-design-type 2.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
