### ISSUE TITLE
Reduce the size of auto inline css.

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3115]
Ref:
https://secure.helpscout.net/conversation/839401244/64175?folderId=2844667

Pastebin:
https://pastebin.com/mYst4r2L

**Comment by MohammedKaludi** [comment]
Ready.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/932927184/78693?folderId=2632030

This ticket has reopened as the .amp-wp-inline-522ed57 CSS shorten has no resolving the user issue.

Still need to get compress.

Below is the user case:

Ref: https://monosnap.com/file/GKkKcPPNc6VV7dx8qCJMoCKrZ6CKBx

https://www.yeniarabafiyati.com/2019-agustos-ayi-guncel-ve-hesapli-araba-fiyatlari/amp/

https://monosnap.com/file/S77FbLKqOhcfBxn4tIwSh4WTnpQHez

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.6
