### ISSUE TITLE
Issue with product type schema

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3116]
Help Scout Link: https://secure.helpscout.net/conversation/827668050/63273?folderId=2770545

In Product schema type two warnings related to MPN and images

Structured Data Testing Tool Link:  https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fchefconditor.co.il%2Fproduct%2F%25D7%2590%25D7%2592%25D7%25A8-%25D7%2590%25D7%2592%25D7%25A8%2F

**Comment by pegazee** [comment]
@akashagrjsr by mistake created this ticket in this repo. It should be created in the Schema & Structured Data for WP repo. And I've also discussed this scenario with @akashagrjsr, we can close this ticket.
