### ISSUE TITLE
ampforwp_exclude_post option

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3118]
Is this option important? If yes then we need to improve it.

**Comment by MARQAS** [comment]
It is related to performance as well #3052

**Comment by MARQAS** [comment]
We should improve it as it is causing some milliseconds of damage to performance

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3199/files#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1016

Improvements in the code required.

**Comment by MohammedKaludi** [comment]
👍 pushed in .0.9.97.54
