### ISSUE TITLE
Fatal error: Class 'AMP_Base_Embed_Handler' not found(Due to mediavine plugin)

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3119]
Help Scout Link: https://secure.helpscout.net/conversation/837548149/64051?folderId=2770545

Fatal error: Class 'AMP_Base_Embed_Handler' not found in /nas/content/live/ptmoney/wp-content/plugins/mediavine-control-panel/extensions/amp/embeds/class-mvamp-iframe-embed.php on line 3

**Comment by amer07** [comment]
Here another user-facing same issue
Ref:https://secure.helpscout.net/conversation/832385603/63625?folderId=2770543
Here you see the screenshot;https://monosnap.com/file/egn9NHwLEgJhhN0dQC6U61WoMXZRtP

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
