### ISSUE TITLE
If GTM gets enabled after Enabling the Analytics, then both codes load in the frontend.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3121]
Is this the correct use-case? I'm 90% sure, just check and confirm properly. I have tested it but is it the right way?

If GTM gets enabled after Enabling the Analytics, then both codes load in the frontend.

REF: https://wordpress.org/support/topic/when-selecting-google-tag-manager-as-active-google-analytics-option-is-hidden/#post-11484178

**Comment by gabu69** [comment]
Even **if** google analytics **tracking id is empty** it will show at the end of footer like this

`<amp-analytics type="googleanalytics" id="analytics1"> <script type="application/json">{"vars":{"account":""},"triggers":{"trackPageview":{"on":"visible","request":"pageview"}}} </script> </amp-analytics>`

So you need to disable first google analytics and then enable tag manager. 

I think by default when enabling tag manager the plugin should disable by default google analytics. Or **if** google analytics **tracking id is empty** then disable google analytics to show up in the html

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
