### ISSUE TITLE
P tag is missing when copy the content option is used in custom AMP editor

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3122]
P tags are disappearing when we use `<blockquote class="twitter-tweet" >` in custom AMP editor

https://prnt.sc/nj1ppb

**Comment by akashagrjsr** [comment]
Another user is also facing the same issue. 
Help Scout Link: https://secure.helpscout.net/conversation/838865870/64143?folderId=2770545

**Comment by MARQAS** [comment]
Have you checked with all the components of AMP?

**Comment by MohammedKaludi** [comment]
Seems to be working fine, tested with multiple amp components and its working fine.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
