### ISSUE TITLE
Need to AMP compatible with this plugin HTTP / HTTPS Remover

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3123]
Need to AMP compatible with this plugin HTTP / HTTPS Remover.

Ref: https://secure.helpscout.net/conversation/835144942/63857/

It is removing the HTTP to the scripts and it is causing validation errors in the AMP.

**Plugin Link: https://wordpress.org/plugins/http-https-remover/**

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/846704326/65288/

**Comment by MARQAS** [comment]
Check for `class_exists` at the beginning of the function

**Comment by MARQAS** [comment]
What if a person uses endpoint option?

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
