### ISSUE TITLE
Content not rendering on AMP with the Enfold theme version 4.5.6

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3124]
Content not rendering on AMP with the shortcode added, in Enfold theme version 4.5.6, also issue recreated at localhost.
Ref: https://secure.helpscout.net/conversation/828093798/63319?folderId=2322649

**Comment by MohammedKaludi** [comment]
Use any existing hook instead of creating a new one
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9e6ccdfa38c77484a4e688bf5d1d8ed11feb3456

**Comment by MohammedKaludi** [comment]
Function name incorrect 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9e6ccdfa38c77484a4e688bf5d1d8ed11feb3456#diff-1301281de287d2aed98746fc9ba777b4R1269

and 
can't you use `ampforwp_is_endpoint()`?

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52
