### ISSUE TITLE
AMP will prioritize tags over posts

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#3125]
This bug existed for at least a year now. If you have a post with URL

domain.com/amazing-cats and a tag called amazing-cats, AMP will show wrong content

domain.com/amazing-cats - post
domain.com/amazing-cats/amp/ - will show tag

**Comment by pegazee** [comment]
@djixas,
I'm trying to recreate the issue on my end but it's not created. Can you please share the exact URL where you're getting this issue? I'll check and let you know the solution.

**Comment by pegazee** [comment]
And also may I know how you're removing the tag base from the tag URL?

**Comment by djixas** [comment]
I am removing tag base by just renaming on wordpress, is there any way i can send URL privately?

**Comment by pegazee** [comment]
You can contact us here: https://ampforwp.com/support/#contact.

**Comment by ahmedkaludi** [comment]
@pegazee

We have a Test site with the proper usecase available at https://secure.helpscout.net/conversation/850350337/65652?folderId=1680014

**Comment by pegazee** [comment]
okay, I'll check and resolve the isssue

**Comment by pegazee** [comment]
I've been gone through the debug process and found that due to the configuration setup, a user is facing this kind of issue. And we've resolved & set up the proper configuration on the user end. We can close this ticket.

**Comment by djixas** [comment]
Can you please tell me what was changed and how it was fixed, please?
