### ISSUE TITLE
Social sticky icons to show on top as well as it is getting hidden behind sticky ads.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3126]
Social sticky icons to show on top as well as it is getting hidden behind sticky ads.
Ref: https://secure.helpscout.net/conversation/832702237/63642?folderId=2322649

**Comment by MohammedKaludi** [comment]
Remove Sticky position from the settings : https://take.ms/jHZS2
and add Padding-bottom according to the design and the size of the Social-bar only when sticky ads are active,

**Comment by MohammedKaludi** [comment]
Not working in banner in Swift: https://take.ms/gMvJP
Also not working with Design 1, 2 and 3

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
