### ISSUE TITLE
Showing google search console error in amp pages after activation of the plugin

### ISSUE THREAD

**Issue by civilenggnotes** [ahmedkaludi/accelerated-mobile-pages#3127]
Hello sir, i was using the official amp plugin by AMP Project Contributors. First time, there were some error in the google search console for amp pages. Later i solved them and validated. Few days earlier i started using your plugin. Again i faced 5 errors, of which 3 is started validating, but another two is not happening. I tried so many times to solve them. But could not find the solution. I am sharing the errors below. Please help to solve them. I just loved your plugin, and don’t wanna go back to any other plugin. Errors are below-
1. Referenced AMP URL is not an AMP – affecting 21 pages
2. Disallowed attribute or attribute value present in HTML tag – affecting 11 pages.

**Comment by MohammedKaludi** [comment]
Can you please share more information about the issue?
like the URL of the site and the pages on which Search Console is showing an error.

If you are not comfortable sharing the URL in public then you can email us at team@magazine3.com with the reference to this ticket so we can check and understand the issue.

**Comment by civilenggnotes** [comment]
Here are two example of url
https://www.civilenggnotes.in/introduction-to-building-construction/amp/

https://www.civilenggnotes.in/is-code-soil-and-foundation-engineering-code-free-download/amp/

**Comment by civilenggnotes** [comment]
I am getting another problem in the following url. It should shold the full content. But it is showing Excerpt. Conical version is working fine.
 https://www.civilenggnotes.in/150-autocad-command-and-shortcut-list-with-pdf/amp/

**Comment by MohammedKaludi** [comment]
> Here are two example of url
> [civilenggnotes.in/introduction-to-building-construction/amp](https://www.civilenggnotes.in/introduction-to-building-construction/amp/)
> 
> [civilenggnotes.in/is-code-soil-and-foundation-engineering-code-free-download/amp](https://www.civilenggnotes.in/is-code-soil-and-foundation-engineering-code-free-download/amp/)

Regarding this issue, turn off amp-auto-ads and test it. I see this strange issue with AMP-auto-ads url to be at http://1

**Comment by MohammedKaludi** [comment]
> I am getting another problem in the following url. It should shold the full content. But it is showing Excerpt. Conical version is working fine.
> [civilenggnotes.in/150-autocad-command-and-shortcut-list-with-pdf/amp](https://www.civilenggnotes.in/150-autocad-command-and-shortcut-list-with-pdf/amp/)

and regarding this, could you turn off Infinite Scroll (Experimental) feature and test.

**Comment by civilenggnotes** [comment]
But if i stopped the auto ads, it will reduce my earnings. So, if there any other method to fix it

**Comment by civilenggnotes** [comment]
I turned off the infinite scroll, and tested from two different browser. Still it did not work

**Comment by civilenggnotes** [comment]
I uninstalled the plugin and delete all data, and reinstalled and set up a fresh, the second problem was solved. I don't know what was the problem. And i need to set up the auto ads. So please support in your plugin or fixed the amp validation error

**Comment by MohammedKaludi** [comment]
> I uninstalled the plugin and delete all data, and reinstalled and set up a fresh, the second problem was solved. I don't know what was the problem. And i need to set up the auto ads. So please support in your plugin or fixed the amp validation error

Thank you very much for the followup, we have taken this ticket as a high priority and we will check and will fix the issue on a high priority.

But please give us some time to review and understand the issue so we can fix.

I assure you that your issue will be fixed very soon.

**Comment by civilenggnotes** [comment]
Okk.. no problem. Take your time.. hope to fix the problems soon..

**Comment by Zabi09** [comment]
@civilenggnotes 
We have tested your website and now all your pages are AMP validated with no errors, Will you please go to your search console and click on "validate fix" button and that will start indexing our pages - https://prnt.sc/nkagt3

and if you face any issues then please let us know and we will help you.

**Comment by civilenggnotes** [comment]
Thank you so much, only 6 errors are left, hope they will also be validated soon. But now the valid with warning is increased much, affacting 18 pages, with 3 issue. Will not that affact the search results??

**Comment by Zabi09** [comment]
Are you manually adding any scripts in HTML in head section - https://prnt.sc/nkyrpp

Please check and let us know and for faster communication, you can directly contact us on team@magazine3.com and our team will get back to you as soon as possible.

**Comment by civilenggnotes** [comment]
Yes. I inserted some code for adsense auto ads and amp form javascript link from the plugin's custom header code section

**Comment by Zabi09** [comment]
@civilenggnotes 
I have checked your website and now all your pages are AMP validated with any errors and warnings,
You can add the Adsense auto ads script in HTML in the head section but if you are adding some other scripts then let us know because we dynamically add scripts which your AMP page needs and you no need to add them manually.

**Comment by civilenggnotes** [comment]
Please check it now

**Comment by Zabi09** [comment]
@civilenggnotes
I have checked your website and now all your pages are AMP validated.
Will you please check once again and let us know and if everything seems to be fixed then we can close this ticket.

**Comment by MARQAS** [comment]
I have checked it again and whatever page I have checked, it is AMP Validated. 
Closing this ticket, for now, if the issue reoccurs then please feel free to reopen it.
