### ISSUE TITLE
Date is posted twice on swift theme

### ISSUE THREAD

**Issue by gabu69** [ahmedkaludi/accelerated-mobile-pages#3130]
I see, sorry about the shortlink, ill recontext the problems either way

When using SWITFT theme, theres 2 problems i noticed:

The date posted is posted twice at the beggining:
30-Apr-2019 6:20 PM | Publicado: 30-Apr-2019 6:20 PM

For example in:
https://www.okchicas.com/noticias/joe-jonas-sophie-turner-casados-vegas/amp/

**Comment by ahmedkaludi** [comment]
@gabu69 it seems like you are not using the AMP on that post, 

You were using AMP layouts I guess?

**Comment by gabu69** [comment]
Yes, its fixed now
