### ISSUE TITLE
Author name won´t show if you disable author bio in swift theme

### ISSUE THREAD

**Issue by gabu69** [ahmedkaludi/accelerated-mobile-pages#3131]
Also if you **enable Author Name** and **disable Author Bio** 

Author name won´t show at top.  

It should appear on top and dissapear only the author bio box at the end of the article, but both dissapear.

**Comment by Zabi09** [comment]
If someone wants only author name - https://prnt.sc/nkxdc0 without the author bio then?

**Comment by MohammedKaludi** [comment]
:+1: ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.52

**Comment by gabu69** [comment]
Im sorry but this bug is still there, now even author names wont appear 
Example: https://www.okchicas.com/entretenimiento/tv/game-of-thrones-final-dividio-todos/amp/

Also if i disable Author Bio, author name or photo wont even appear

**Comment by jsm386** [comment]
Using 0.9.97.53 can confirm this bug as well (author Bio disabled, author name will not appear). Example at https://vinepair.com/booze-news/study-cork-screwcap-wine-consumer-value/?amp

**Comment by MARQAS** [comment]
@jsm386, are you using AMP Layouts? The issue is due to AMP Layouts and it has been resolved in 1.5.3, please update it.

**Comment by gabu69** [comment]
Hi @MARQAS, I just updated,  Theres still a bug

if I enable Author name and disable autho bio 

Author name wont show at top still

**Comment by MARQAS** [comment]
Can you please contact us at team@magazine3.com? We will look into this issue of yours and will resolve it immediately
