### ISSUE TITLE
Infinite scrolling will display 3 times the footer

### ISSUE THREAD

**Issue by gabu69** [ahmedkaludi/accelerated-mobile-pages#3132]
When using infinite scrolling experimental feature, the footer of article 2 and 3 will show and at the end of article 1.

It´s pointless to show up article 2 and 3 footer

example:
https://www.okchicas.com/curiosidades/hermosos-jumpsuits-que-debes-tener-en-tu-armario/amp/

**Comment by ahmedkaludi** [comment]
@gabu69 please create a ticket on ampforwp.com/support

Our team will troubleshoot deeply for you

**Comment by pegazee** [comment]
Issue is coming from the AMP layout extension. We've created a ticket in the AMP layout repo. And it's added in the top prior to resolve the issue.
