### ISSUE TITLE
 font JavaScript is loading everywhere and breaking things in dashboard

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3133]
Ref:https://secure.helpscout.net/conversation/843725881
Here you can see image:https://monosnap.com/file/6GfUDPJWEeAXoSqFohULKd6ILwLpdX

**Comment by ajeetku** [comment]
Its not proper solution
you need to check google font is enabled or not, at the entry of the main function {Make proper solution}

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
