### ISSUE TITLE
Debug error in installation process

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3134]
categories_array in C:\inetpub\wwwroot\getupspain.es\wp-content\plugins\accelerated-mobile-pages\includes\options\admin-config.php on line 4023

And the same error in the backoffice section.

Server: IIS
PHP: 7.2.7
MySQL: 5.7.24
Wordpress: 5.1.1
AVADA: 5.9.1

Thank you!

REF: https://wordpress.org/support/topic/error-undefined-variable-categories_array/

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51
