### ISSUE TITLE
Debug error on Homepage

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3135]
I’ve installed the plugin but it’s not working on homepage giving me this errors:

Notice: Trying to get property ‘ID’ of non-object in C:\inetpub\wwwroot\getupspain.es\wp-content\plugins\accelerated-mobile-pages\includes\features\functions.php on line 174

Notice: Undefined offset: 0 in
C:\inetpub\wwwroot\getupspain.es\wp-includes\class-wp-query.php
on line
3227

I’ve the following system:

PHP Version:	7.2.7
Server Software:	Microsoft-IIS/10.0
MySQL: 5.7.24
WordPress Version:	5.1.1
Avada Version:	5.9.1

Thank you!!

The page I need help with: https://www.getupspain.es/amp

REF: https://wordpress.org/support/topic/error-homepage-not-working/

**Comment by MohammedKaludi** [comment]
Another User: https://wordpress.org/support/topic/error-homepage-not-working/#post-11493915

**Comment by Zabi09** [comment]
Notice: Undefined index: ampforwp-redirection-on-off in D:\xampp\htdocs\magzine\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 817

Notice: Undefined index: ampforwp-ia-on-off in D:\xampp\htdocs\magzine\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 818

**Comment by MARQAS** [comment]
Remove unwanted code: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/849c6d48c50b731dda32351e9ee2b9291e6cabd3#diff-04b38a94ddf918855eed7a68ecaa512dR161

**Comment by MARQAS** [comment]
There is still some unwanted code, for example, $post_id is getting assigned multiple times.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MARQAS** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/849c6d48c50b731dda32351e9ee2b9291e6cabd3#diff-04b38a94ddf918855eed7a68ecaa512dR341

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
