### ISSUE TITLE
Issue with dt-the7 theme (Images are not loading) in AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3137]
When the user enables Images Lazy Loading option then images are appearing in Blog Page. 

Themes Option >Advance > Performance > Images Lazy Loading Enable >Save Options

Screenshot: 
https://monosnap.com/file/M3DsMIwUWHbsexBIBUC8xV1ol9CING 
https://monosnap.com/file/tH2oYZV8A9EWo46X4HJZcHhay8ShPZ

dt-the7 theme is available on Mazagine3 telegram group for testing

**Comment by akashagrjsr** [comment]
Help Scout Link: https://secure.helpscout.net/conversation/842161106/64417?folderId=1060556

**Comment by MARQAS** [comment]
This issue was one off and unable to recreate it again on the user's end, So closing this ticket, we will reopen it again once we find the issue.
