### ISSUE TITLE
sahifa theme  featured video compatibility

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3138]
Ref.
https://secure.helpscout.net/conversation/843974475/64579?folderId=2844667

**Comment by pegazee** [comment]
Check Function name & the ticket's theme name

**Comment by Zabi09** [comment]
No need of this code now we can implement this - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3444

When sahifa is active then it should automatically add the custom field name

**Comment by santosh8793** [comment]
Added sahifa theme compatibility in Featured Video Ticket through meta key video provide by the theme 
Reference Ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3444
