### ISSUE TITLE
Facebook instant article not working properly in AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3143]
Help Scout Link: https://secure.helpscout.net/conversation/843592508/64542?folderId=2770545

**Comment by akashagrjsr** [comment]
Facebook instant article guidelines: https://developers.facebook.com/docs/instant-articles/reference/slideshow/

**Comment by MARQAS** [comment]
Gallery design in IA.

**Comment by MARQAS** [comment]
2nd user is having an issue with Analytics in Instant Articles, contacted him for more details on the issue.

**Comment by MARQAS** [comment]
Update: 
1st user is having an issue with Slideshow of Instant Articles, only on one of his website, but working properly on another. I tried to recreate it but unable to recreate this issue, its working fine on my end as well.

**Comment by MARQAS** [comment]
But We can add it as a feature for Gallery design in IA.

**Comment by MARQAS** [comment]
It's breaking the normal Gallery: https://monosnap.com/file/i5vO9Y6F1LjP4YcegGtm4MlU5FH2RF

Please make sure to run it only in Instant article scenario. 

And also why this filter is commented out: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/45dec517c6a4ab543aebc501db268ed4e52fc350#diff-810b0a0ef5832a51ef0ad2d39557d601R9

**Comment by MARQAS** [comment]
It's still breaking the normal Gallery: https://monosnap.com/file/i5vO9Y6F1LjP4YcegGtm4MlU5FH2RF

Please make sure to run it only in Instant article scenario.

**Comment by MARQAS** [comment]
Please use prefix such as `ampforwp_ia`:  https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/05198a79539f97321ac898f11749dd0f584381f7#diff-810b0a0ef5832a51ef0ad2d39557d601R2

**Comment by pegazee** [comment]
I've tried to create a gallery without Gutenberg, the parent figure tag was not showing.
Screenshot: https://take.ms/shmcR

By using the Gutenberg gallery markup showing perfectly.

**Comment by santosh8793** [comment]
it is working fine

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Removing filter is not a correct solution
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a4c4a5cfc525820ead721488f799ef1449b9113f#diff-810b0a0ef5832a51ef0ad2d39557d601R4

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
