### ISSUE TITLE
AMP Email Extension need to add

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3144]
AMP Email Extension need to add config

**Comment by MARQAS** [comment]
Link @ajeetku?

**Comment by pegazee** [comment]
Link is not working. Need to update the link. Meanwhile, I'm moving this ticket to "fail section"

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
