### ISSUE TITLE
Author name not  comes in AMP due to "Simple Author Box" plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3145]
Screenshot: https://monosnap.com/file/seNwM7fdMJzbxLu9zNgXtT9aUyrKpw

Issue recreated in local also.

Help Scout Link: https://secure.helpscout.net/conversation/838316722/64102?folderId=2770545

**Comment by MARQAS** [comment]
We have already added its compatibility in #2268, is not working? If not, then why not add it for other designs as well?

**Comment by MARQAS** [comment]
Use 'author_info' instead of published by

**Comment by MohammedKaludi** [comment]
👍

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
