### ISSUE TITLE
Yoast SEO Cannot read the content from AMP page builder

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3146]
DES: Yoast SEO Cannot read the content from AMP page builder

Ref: https://monosnap.com/file/eWRVSfGhVFdEoobxaNn0YUHHbRnCka

Ref: https://secure.helpscout.net/conversation/843373281/64521/

**Comment by MARQAS** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2435

**Comment by ahmedkaludi** [comment]
It was just a configuration issue from the user's end. 

Closing the ticket.
