### ISSUE TITLE
When "Change End Point to ?amp" in enabled View NON-AMP is not working

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3147]
Des: When "Change End Point to? amp" in enabled View NON-AMP is not redirecting to NON-AMP page.
The issue is also reoccurred in localhost.
Ref: https://secure.helpscout.net/conversation/843368827/64519?folderId=2632028

**Comment by MARQAS** [comment]
I guess https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2710 ticket will solve this as well, just need some testing.

**Comment by pegazee** [comment]
@MARQAS Nope, this issue has been solved in this #3093 ticket

**Comment by pegazee** [comment]
We can close this ticket.
