### ISSUE TITLE
Create a filter to modify the Whole options array

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3152]
Create a filter to modify the Whole options array, so anyone can modify/add the controls according to the usage.

**Comment by MARQAS** [comment]
We are talking about changing the main array of options, not inside `ampforwp_get_setting`. 
That function is just to get the value from the array but has no power to change the array.

**Comment by MARQAS** [comment]
Check `ampforwp_redux_options_enabler` and try to do it like that

**Comment by MARQAS** [comment]
The following is the example of adding/modifying redux options:

`add_filter( 'redux/options/redux_builder_amp/sections', 'ampforwp_redux_options_modifier',15,1 );
function ampforwp_redux_options_modifier($sections){
	// For multiple options
	$new_options = array();
	$new_options[] = array(
                        'id'       => 'amp-text',
                        'type'     => 'info',
                        'desc'    => esc_html__('Text-1', 'accelerated-mobile-pages'),
                        );
	$new_options[] = array(
                        'id'       => 'amp-text-2',
                        'type'     => 'info',
                        'desc'    => esc_html__('Text-2', 'accelerated-mobile-pages'),
                        );
	// For single option
	$new_option = array(
                        'id'       => 'amp-text-3',
                        'type'     => 'info',
                        'desc'    => esc_html__('Text-3', 'accelerated-mobile-pages'),
                        );
	foreach ($sections as $key => $section_value) {
    	if(count($section_value['fields'])>0){
    		// Check in which section you want to add/modify the field
    		if ( 'opt-text-subsection' == $section_value['id'] ) {
    			// Adding
				// For single option
				array_push($sections[$key]['fields'], $new_option);
    			// For multiple options
    			if ( sizeof($new_options)>1 ) {
					foreach ($new_options as $new_option ) {
						array_push($sections[$key]['fields'], $new_option);
					}
				}

	    		// Modifying
	    		foreach ($section_value['fields'] as $fieldkey => $field_value) { 
	    			if(isset($field_value['required']) && 'amp-frontpage-select-option' == $field_value['id'] ){
						unset($sections[$key]['fields'][$fieldkey]['required']);
	    			}
	    		}
    		}
    	}
    }
    return $sections;
}`

**Comment by MARQAS** [comment]
Closing this ticket for now[ Confirmed with @syedimran22 ]
