### ISSUE TITLE
Analytics not working due to Glue for Yoast SEO & AMP plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3153]
Help Scout Link: https://secure.helpscout.net/conversation/845397653/64830/

**Comment by MARQAS** [comment]
My suggestion would be to remove this code completely. 
The above solution will work only when AMP+AMPFORWP+GLUE is activated. But none of our analytics is going to work in that scenario. So it would be better to remove this code and run our analytics as we have more and easy options for analytics

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
