### ISSUE TITLE
Search results not showing for "Select Categories to Hide AMP" option inHide Amp Bulk Tool

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3154]
Help Scout Link: https://secure.helpscout.net/conversation/845906075/65194?folderId=2770545

**Comment by atish-31** [comment]
HiI am Using AMPforWP on my wordpress wesbite. i want to exclude particular category from amp. but plugin doesn't detect category. can you help me to solve this problem? | HiI am Using AMPforWP on my wordpress wesbite. i want to exclude particular category from amp. but plugin doesn't detect category. can you help me to solve this problem?
-- | --
HiI am Using AMPforWP on my wordpress wesbite. i want to exclude particular category from amp. but plugin doesn't detect category. can you help me to solve this problem?

**Comment by MohammedKaludi** [comment]
Hey @atish-31,

Thank you for using our plugin, we have fixed the issue and we are pushing the update as we speak.

After 30-40 mins, please update the plugin to the latest version i.e. 0.9.97.51.1 and it should fix the issue.

**Comment by MohammedKaludi** [comment]
Pushing the code in 0.9.97.51.1

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51

**Comment by akashagrjsr** [comment]
One more user is facing this issue: https://secure.helpscout.net/conversation/847552683/65356/
