### ISSUE TITLE
Fatal Error Since Update

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3155]
Just updated the plugin and I am getting this error, have had to disable the plugin completely.

Fatal error: Can’t use function return value in write context in /home/username/public_html/flourish-taiwan.com/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4536

Tried disabling all other plugins but no success.
Also tried changing the Theme to a standard WordPress Theme still no success.
https://wordpress.org/support/topic/fatal-error-since-update-5/

**Comment by Zabi09** [comment]
Also added in master with reference to this ticket because it was added in this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2503

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.51.1
