### ISSUE TITLE
Fatal error after update 0.9.97.51

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3156]
- [x] PHP Fatal error: Uncaught Error: Call to undefined function ampforwp_is_non_amp() in /srv/users/maco/apps/macocaribbeanliving/public/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php:498

https://wordpress.org/support/topic/call-to-undefined-function-ampforwp_is_non_amp-2/#post-11506086

- [x] Warning: require(/home/kellyca1/public_html/wp-content/plugins/accelerated-mobile-pages//templates/category-widget.php): failed to open stream: No such file or directory in /home/kellyca1/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 551

Fatal error: require(): Failed opening required ‘/home/kellyca1/public_html/wp-content/plugins/accelerated-mobile-pages//templates/category-widget.php’ (include_path=’.:/usr/lib/php:/usr/local/lib/php’) in /home/kellyca1/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 551

https://wordpress.org/support/topic/error-after-upgrade-to-version-0-9-97-48/page/2/#post-11506863

**Comment by MohammedKaludi** [comment]
One more reported #3163

**Comment by pegazee** [comment]
**PHP Fatal error: Uncaught Error: Call to undefined function ampforwp_is_non_amp()**

This issue is occurring due to the other plugin called "Advanced Ads – Responsive Ads" By Thomas Maier. And they have been fixed this issue in the version 1.8.7.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7abc4015d76dfdb8d6eb25959b92fd27b6bcdb2f#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R533 use `require_once` in place of require

**Comment by MohammedKaludi** [comment]
Rename the function from `ampforwp_file_exists` to `ampforwp_require_file`

**Comment by MohammedKaludi** [comment]
:+1: ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
