### ISSUE TITLE
amp-next-page script of infinity scroll shouldn't load on other custom post type pages

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3157]
Desc: amp-next-page script shouldn't load on other custom post type pages such as product page.

**Comment by MARQAS** [comment]
Use `'post' == get_post_type(ampforwp_get_the_ID()` with `is_single` condition instead of adding this much code.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
