### ISSUE TITLE
AMP Pages Became Not Valid (Posts are OK)

### ISSUE THREAD

**Issue by ArtFl-2** [ahmedkaludi/accelerated-mobile-pages#3159]
Today Google Search Console has informed me of the new issue with my AMP pages:
"An AMP component 'script' tag is present, but unused"

I’ve checked the pages with AMP validator that said “The extension ‘amp-addthis’ was found on this page, but is unused. Please remove this extension.”
https://validator.ampproject.org/#url=https%3A%2F%2Fwww.russiandog.net%2Fcaucasian-shepherd-breeders-in-the-us%2Famp

I’ve checked with Google AMP test and the result was the same.

It affects only pages, not posts.

Today already three persons (@jorgitobg @hugopoiret59 @pro99) have reported this issue on  AMPforWP support forum.

Random Page:
https://www.russiandog.net/caucasian-shepherd-breeders-in-the-us/amp
Random Post (no problems):
https://www.russiandog.net/siberian-husky-temperament-facts-dog-for-me.html/amp

**Comment by AnimationOne** [comment]
Hello, yes this problem is for Addthis extension, I also report this bug till then please enable, AMP>Design>Social>Enable AddThis (Enable this) then your issue resolved.

**Comment by MohammedKaludi** [comment]
This will be fixed in the next update which we are planning to push it tomorrow
Ticket already created at #3068

**Comment by ArtFl-2** [comment]
Thank you so much!

**Comment by michaelsaves** [comment]
I am having the same issue, two weeks later. I have the updated plugin. Support isn't responding. Any other tips on what to do? 

AMP ERROR: An AMP component 'script' tag is present, but unused

Highlighted section for the 52 pages of errors: 

</script>
<amp-analytics>
</body></html><!--[selectron:done]
