### ISSUE TITLE
When AMP take over beta is enabled leave a comment option doesn't work

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3160]
Des: When AMP take over beta is enabled leave a comment option doesn't redirect to NON-AMP page. It redirects to the same page.

REF: https://monosnap.com/file/cZ9bmrbGTxs2vxbw8N5395YmaxkB0C

**Comment by Helpp1** [comment]
I have a same but again my comments not worked.
![Comment](https://user-images.githubusercontent.com/26200989/57434663-c37e9300-723b-11e9-8bbd-99ed60ef59e4.png)

**Comment by Helpp1** [comment]
I´m still waiting for any answer? Here are my website [https://fanyit.com/](url) (for example) you can check my comments they doesn't work. Please inform me about that.

**Comment by pegazee** [comment]
@Helpp1, We can do this feature in this ticket #3129
