### ISSUE TITLE
Problem with Enable AddThis extension

### ISSUE THREAD

**Issue by AnimationOne** [ahmedkaludi/accelerated-mobile-pages#3161]
Hi, when you disabled **"addthis extension"** Then google search console or amp validator shows an error that "Not a valid AMP page" **The extension 'amp-addthis' was found on this page, but is unused. Please remove this extension.** 
If we enable this extension then the problem is solved, Google says this is a valid amp page.
Please look into this matter.
Note: I checked with my both websites and found that this problem is only for pages, not for posts.

**Comment by MohammedKaludi** [comment]
This will be fixed in the next update which we are planning to push it tomorrow
Ticket already created at #3068

**Comment by AnimationOne** [comment]
Thanks.
