### ISSUE TITLE
Incorrect escaping done on author name when Link to Author Pages is enabled along with the Co-Authors plugin activate.In Swift Design

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3162]
Description: Incorrect escaping done on author name when Link to Author Pages is enabled along with the Co-Authors plugin activate.In Swift Design

Issue recreated in local.

Ref the screenshot: https://monosnap.com/file/epOkQqOLvg4HBJhuZWE1uj3mopm59j

https://secure.helpscout.net/conversation/843368827/64519?folderId=2632028

https://wordpress.org/plugins/co-authors-plus/

**Comment by MohammedKaludi** [comment]
Removing escaping is not the solution.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/eb8539a41260dc9350361b777c2d19a714fc50f1#diff-66456bcdcc1e8a0ec3147375393a64a0R87

Use better method to escape the variable.

**Comment by Zabi09** [comment]
We have already created the compatibility of co author plugin and if that plugin is active then we are taking the author link from their function - https://monosnap.com/file/WAAHqQApX10doUWvi74qJJDfrrT5x2

And there are escaping it - https://monosnap.com/file/vehrKB7t3LicPjfvQSs4zGSbzp1Yn7

So I have removed the extra escaping which was causing error.

**Comment by MohammedKaludi** [comment]
Relying on third party for escaping and sanitization  is not a good practice.
Use strip_tags function to make sure only allowed tags are passed.

Example : https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/eb8539a41260dc9350361b777c2d19a714fc50f1/components/author-box/author-box.php#L117

**Comment by MohammedKaludi** [comment]
👍

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
