### ISSUE TITLE
Fatal Error with Advanced_Ads and Multisite Environment.

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3163]
Fatal error: Uncaught Error: Call to a member function get() on null in xxx/xxx/xx/xx/public/wp-includes/query.php:28 Stack trace: #0 /xxx/xxx/xxx/public/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/amp-helper-functions.php(44): get_query_var('amp', false) #1 /xxx/xxx/xxx/public/wp-content/plugins/advanced-ads/includes/functions.php(102): is_amp_endpoint() #2 /xxx/xxx/xxx/public/wp-content/plugins/advanced-ads-responsive/public/public.php(74): advads_is_amp() #3 /xxx/xxx/xxx/public/wp-includes/class-wp-hook.php(286): Advanced_Ads_Responsive->wp_admin_plugins_loaded('') #4 /xxx/xxx/xxx/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 /xxx/xxx/xxx/public/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #6 /xxx/xxx/xxx/public/wp-settings.ph in /xxx/xx/xxx/public/wp-includes/query.php on line 28

User Ref:
https://secure.helpscout.net/conversation/847540261/65355?folderId=2844667

**Comment by pegazee** [comment]
This issue is occurring due to the other plugin called "Advanced Ads – Responsive Ads" By Thomas Maier. And they have been fixed this issue in the version 1.8.7.
