### ISSUE TITLE
Publishing with MarsEdit won't create the AMP 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3165]
https://www.red-sweater.com/marsedit/
https://wordpress.org/support/topic/missing-post-on-homepage-2/#post-11512138

**Comment by pegazee** [comment]
Tested & working perfectly in the latest version v0.9.97.58. I'm closing this ticket if still anyone getting the issue feel free to re-open the ticket :-)
