### ISSUE TITLE
Need to add functionality to show parent category items when any of the child category is added in 'Hide AMP Bulk Tool' option

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3166]
Step to recreate the issue with `Hide AMP Bulk Tool`

1). Create a parent category with 2 to 3 child category.
2). Add some post in a child category, parent category post will be 0
3) Add one of the child category in `Hide AMP Bulk tool`
Now the result of these steps needs to show post of the categories which are not hidden. 

For example 
Category A
 --Category B 
 --Category C
 --Category D
Now we hide `Category C` in `Hide AMP Bulk Tool`, the parent category `Category A` should display the post of `Category B` and `Category D` in AMP.

**Comment by pegazee** [comment]
I've hide Category C in Hide AMP Bulk Tool, but in the parent category Category A  is displayed the post of Category B, C and D. It should display the post of Category A, B and D.

Note: I've checked in the master as the code is committed in the master branch

**Comment by MARQAS** [comment]
Added in master

**Comment by Rkroy** [comment]
If we hide Category C in Hide AMP Bulk Tool, then the posts with Category C is still showing on AMP and those posts are displaying on Category A archive pages.

**Comment by MohammedKaludi** [comment]
Fixed in Performance Update.

As there is no changes in the code, this ticket is closed directly.
