### ISSUE TITLE
Improvement in Video Module

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3167]
Ref:
https://secure.helpscout.net/conversation/847111541/65331?folderId=2844667

Add one more feature for our next update. Please include an extra field in our AMP video widget so that we can include a custom POSTER or ARTWORK image. Both are allowed in AMP.

**Comment by pegazee** [comment]
We've already had these option in the AMP video module. See this screenshot: https://take.ms/iedC8
