### ISSUE TITLE
WhatsApp number should not have + (before country) in CTA Contact Bar

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3168]
When inserting the phone number (in CTA Contact bar) says:
"You must fill the number in the international model + country code and full number."
But it will not work that way with the + inserted.

As per:
https://faq.whatsapp.com/en/android/26000030/

"Use: https://wa.me/15551234567
Don't use: https://wa.me/+001-(555)1234567"

**Comment by Zabi09** [comment]
@olddoc It seems you are talking about our CTA for AMP extension, So I have created the ticket for it on our board - https://prnt.sc/nrt27l because we only deal with the core AMPforWP plugin issues here.
