### ISSUE TITLE
Need to make sure AMP strings are translatable as currently, some strings are not working.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3169]
Need to make sure AMP strings are translatable as currently, some strings are not working.
Ref: https://secure.helpscout.net/conversation/848215601/65440?folderId=2322649

**Comment by ajeetku** [comment]
are we need `https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5534427a52a81186573d9f87af6c31b0cf5b9878#diff-04b38a94ddf918855eed7a68ecaa512dR382` 
translation on this __esc_html for translation

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
