### ISSUE TITLE
Archive and Tag pages generating incorrect AMP HTML

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3170]
Archive and Tag pages generating incorrect AMP HTML

https://ampforwp.com/author/mohammed/

https://monosnap.com/file/Kf7kOekm8VX4EGg2bqSTbArXppgJHD

**Comment by MARQAS** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/af14150b50bb7360394ed98eddde387079c7235a#diff-04b38a94ddf918855eed7a68ecaa512dR630
Why adding '?amp' when '/amp' is already there?

**Comment by pegazee** [comment]
You can go to this URL: https://ampforwp.com/tag/amp, It is not in the amp. Here the tag name is "amp". So, instead of adding the /amp, I've added the ?amp to render into AMP version

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Remove this line while merging: 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3a189dfc0233a2b768a71233e873d7c055147a23#diff-04b38a94ddf918855eed7a68ecaa512dL631

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
