### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by injainja** [ahmedkaludi/accelerated-mobile-pages#3171]
Please check this thread

https://wordpress.org/support/topic/possible-graphical-bug/#post-11507332

**Comment by MARQAS** [comment]
We have already resolved it here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3046
And Pushed in 0.9.97.51, can you please update it to the latest version and test?

**Comment by injainja** [comment]
Thank you for the fast reply. I already updated to the latest version and the problem is still there.
I am using Version 0.9.97.51.2 atm.
![amp1](https://user-images.githubusercontent.com/50479393/57565658-e6d34a80-73c1-11e9-93fc-2e818745a21b.jpg)
![amp2](https://user-images.githubusercontent.com/50479393/57565665-1bdf9d00-73c2-11e9-8d59-39c3a990e6cb.jpg)

**Comment by MARQAS** [comment]
Are you using any cache plugin? I just checked and the styling is present in the latest version but not on your site.

**Comment by ahmedkaludi** [comment]
Kindly send me your website details on https://ampforwp.com/support

I will check and fix it for you

**Comment by injainja** [comment]
> Are you using any cache plugin? I just checked and the styling is present in the latest version but not on your site.
Nope - no cache...

**Comment by injainja** [comment]
> @injainja Kindly send me your website details on https://ampforwp.com/support
> 
> I will check and fix it for you

That is very kind of you. What do you need? Do you need an Admin-Login for WP?

**Comment by ahmedkaludi** [comment]
@injainja Yes, those details please.

**Comment by injainja** [comment]
O.K. I created an admin-login for you and sent you the credentials via support form. Please tell me how you fixed the problem after you fixed it ;-)

**Comment by MARQAS** [comment]
The issue was due to AMP-Layouts and we have resolved it in that as well. Closing this ticket
