### ISSUE TITLE
Check all the tooltips and make sure the content render properly

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3172]
![image](https://user-images.githubusercontent.com/16532359/57568079-038e7300-7400-11e9-8615-380c9f2b70d0.png)

**Comment by MohammedKaludi** [comment]
Failed : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3087b3984ac0df0d12ddd146c97f1e2cbecf1162#diff-260eba6333c3222e59a6aed22ac5ab37R6435


Error : 

Warning: sprintf(): Too few arguments in /Applications/MAMP/htdocs/wp/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 6435

**Comment by MARQAS** [comment]
No Escaping: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3087b3984ac0df0d12ddd146c97f1e2cbecf1162#diff-260eba6333c3222e59a6aed22ac5ab37R2230

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
