### ISSUE TITLE
Debug errors on search page

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3173]
Notice: Trying to get property of non-object in /home/s/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 174
  

Вы искали: Empty
Notice: Undefined offset: 0 in /home/s/public_html/wp-includes/class-wp-query.php on line 3227
Notice: Undefined offset: 1 in /home/s/public_html/wp-includes/class-wp-query.php on line 3227

**Comment by Zabi09** [comment]
This issue is already fixed in #3135

**Comment by MARQAS** [comment]
Are you sure it will resolve this issue? I guess it is unable to get the content from $post->post_content. 
Try to return from the beginning if there is no $post

**Comment by MohammedKaludi** [comment]
👍 fixed in #3135
