### ISSUE TITLE
Debug error after enabling redirection ( Undefined index: nonamp )

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3174]
https://ibb.co/ScYZ4rB
https://ibb.co/p2QdS0k

https://wordpress.org/support/topic/undefined-index-nonamp-in/#post-11519401

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by Zabi09** [comment]
Already there in Master

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
