### ISSUE TITLE
Subtitle should be H2 instead of H4

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3175]
REF: https://ampforwp.com/forum/topic/use-h2-as-subtitle-instead-of-h4/

Originally added in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2831

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
