### ISSUE TITLE
AMP Pages are blank

### ISSUE THREAD

**Issue by m0sagal** [ahmedkaludi/accelerated-mobile-pages#3176]
AMP stopped working since update.
We just converted from Hostgator to Siteground hosting.

Cache plugins:
WP Rocket
JCH Optimize
SG Optimizer

https://beassistance.com/destinations/asia/repatriation-of-decesed-to-china-beijing/amp/

**Comment by ahmedkaludi** [comment]
@m0sagal Can you please send me the details on https://ampforwp.com/support/

I will immediately have a look.

**Comment by m0sagal** [comment]
sent.

**Comment by MARQAS** [comment]
The issue is due to JCH Optimize Pro plugin and we will tackle it here: #3185
