### ISSUE TITLE
Errors on script custom-element

### ISSUE THREAD

**Issue by taichimiwa** [ahmedkaludi/accelerated-mobile-pages#3178]
`<script custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-latest.js' charset='UTF-8" async></script>
<script custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js' charset='UTF-8" async></script>
<script custom-element="amp-position-observer" src="https://cdn.ampproject.org/v0/amp-position-observer-0.1.js' charset='UTF-8" async></script>
<script custom-element="amp-animation" src="https://cdn.ampproject.org/v0/amp-animation-0.1.js' charset='UTF-8" async></script>
<script custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js' charset='UTF-8" async></script>
<script custom-element="amp-social-share" src="https://cdn.ampproject.org/v0/amp-social-share-0.1.js' charset='UTF-8" async></script>
<script src="https://cdn.ampproject.org/v0.js' charset='UTF-8" async></script>`

My site generate the code above.
I think “‘ charset=’UTF-8” is unnecessary code.
AMP test in Google Search Console points those lines error.

These are plug-ins activated on my site.

Akismet Anti-Spam 4.0.1
Breadcrumb NavXT 5.5.1
Contact Form 7 4.5
Contact Form 7 Google Analytics Integration 1.8.4
Google XML Sitemaps 4.0.8
No Category Base (WPML) 1.2
PS Disable Auto Formatting 1.0.10
WP-DBManager 2.78.1

**Comment by ahmedkaludi** [comment]
Can you please send us the website details on https://ampforwp.com/support ?

I will personally troubleshoot your issue.

**Comment by ahmedkaludi** [comment]
@taichimiwa Did you contacted us? I'm waiting to solve it for you

**Comment by ahmedkaludi** [comment]
@taichimiwa please create a support request here https://ampforwp.com/support

The ticket will be closed until we have full clarity
