### ISSUE TITLE
Add 'How To' Schema 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3179]
Help Scout Link: https://secure.helpscout.net/conversation/851470681/65817/

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/schema-and-structured-data-for-wp #268](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/268) via [**ZenHub**](https://www.zenhub.com/)
