### ISSUE TITLE
Follow semver for versioning in order to manage plugin via wpackagist properly

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3182]
Hi,

Very often falling in such scenario: when AMP plugin fix gets a non-standard [semantic versioning](https://semver.org/) such as (0.9.97.51.2) there is no chance to update it via composer using WordPress [packagist](https://wpackagist.org/search?q=accelerated-mobile-pages&type=any&search=)

You can check this [issue](https://github.com/outlandishideas/wpackagist/issues/293) as well.

This is the only plugin, we are having issues right now, when comes update process of non-standard release.

Hope you can look into this and fix.

Thank you.

**Comment by pegazee** [comment]
@kevinmrl 

Thank you for the reporting the issue, We've consider this issue and in upcoming updates we'll improve the versioning scheme & follow the semver for versioning. This versioning scheme will apply after 3 to 4 updates of the plugin
