### ISSUE TITLE
500 errors on posts that don't use WP Bakery 

### ISSUE THREAD

**Issue by kscott29** [ahmedkaludi/accelerated-mobile-pages#3183]
Hello,

All of the AMP versions of blog posts that don't utilize wp bakery page builder (normal posts) recently started throwing 500 errors. Here's the error code:

Fatal error: Uncaught Error: Class ‘AMPforWP\AMPVendor\WP_Error’ not found in /home/123/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php:259 Stack trace: #0 /home/123/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php(339): AMPforWP\AMPVendor\AMP_Style_Sanitizer->get_validated_css_file_path(‘https://compone…’) #1 /home/123/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php(192): AMPforWP\AMPVendor\AMP_Style_Sanitizer->process_link_element(Object(DOMElement)) #2 /home/123/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(129): AMPforWP\AMPVendor\AMP_Style_Sanitizer->sanitize() #3 /home/123/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(94): AMPforWP\AMPVendor in /home/123/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php on line 259

You can see the original thread here: https://wordpress.org/support/topic/500-errors-after-recent-update/

**Comment by ahmedkaludi** [comment]
@kscott29 we have found the solution, can you please contact us via https://ampforwp.com/support/ - 

So we will implement it on your end and help you solve this.

**Comment by kscott29** [comment]
@ahmedkaludi I contacted you early yesterday at the url above but haven't heard back. Anything you can do to help prioritize this? This is impacting my site as all of my posts without the WP Bakery plugin are throwing 500s right now.

**Comment by ahmedkaludi** [comment]
I'm unable to locate any recent active email with your name or error names,

Can you share the ticket id or your email address?

Or just send a reply to that email with the github ticket url in it so I can trace it?

**Comment by kscott29** [comment]
I'd prefer to not to share my email here if at all possible. I just submitted another support request on https://ampforwp.com/support/. 
The ticket number is 9709

**Comment by ahmedkaludi** [comment]
@kscott29 replied via my personal email

**Comment by kscott29** [comment]
Thanks @ahmedkaludi  I replied via my other email so that you would receive it. Please let me know if you don't receive it

**Comment by EmilianoMaina** [comment]
Same HTTP 500 error on all AMP pages of my blog:

Fatal error: Uncaught TypeError: Argument 1 passed to DOMNode::replaceChild() must be an instance of DOMNode, string given in /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php:136 Stack trace: #0 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php(136): DOMNode->replaceChild('', Object(DOMElement)) #1 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(129): AMPforWP\AMPVendor\AMP_Gallery_Block_Sanitizer->sanitize() #2 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(94): AMPforWP\AMPVendor\AMP_Content_Sanitizer::sanitize('<p><strong>IP c...', Array, Array) #3 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(54): AMPf in /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php on line 136

**Comment by MARQAS** [comment]
@EmilianoMaina, We have a different ticket for this: #3203

**Comment by kscott29** [comment]
@ahmedkaludi @MARQAS any update on this issue here 3183? Can you please help with this error, I've replied to @ahmedkaludi last week with user information for my site and haven't heard anything back.

**Comment by MohammedKaludi** [comment]
@kscott29,  we have pushed this ticket in the last update (released couple of hours ago) 

so please update the plugin to the latest version and do let us know if the issue has been resolved.

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.53
