### ISSUE TITLE
Lightbox Improvements

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3184]
- [x] The more text always appears in the caption

- [x] the icon at the top left (to minimise the image) shows up only as a grey box. Is this how it is supposed to appear? I was wondering if it’s possible to change that box to a cross as it doesn’t look very good currently. 
![image](https://user-images.githubusercontent.com/16532359/57683499-6f1b4f00-7651-11e9-88a9-874fdd2e73de.png)

REF: https://wordpress.org/support/topic/how-to-edit-lightbox-view/

REF: https://wordpress.org/support/topic/how-to-edit-lightbox-view/

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
