### ISSUE TITLE
AMP is not working due to JCH Optimize Pro plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3185]
The AMP URLs are not working due to JCH Optimize Pro plugin. The issue is not reoccurring at local, it's occurring only at users end.

Help Scout Link: https://secure.helpscout.net/conversation/851117896/65778?folderId=2770545

**Comment by MARQAS** [comment]
Can you please rename this function as well? 'schema_lazy_load_remover'

**Comment by MohammedKaludi** [comment]
`ampforwp_remover` is not good name. Use better naming, function names should have to be self explanatory

**Comment by MohammedKaludi** [comment]
Ready 👍

**Comment by MohammedKaludi** [comment]
contact me while merging this ticket.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
