### ISSUE TITLE
 Images are appearing twice

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#3186]
If the featured image and content images are same then both the images are appearing.

https://monosnap.com/file/ZoLqYI43HqRwDW2esabk854mL64U55

**Comment by MARQAS** [comment]
We already have an option for this, let's see why it's not working

**Comment by Soenke2** [comment]
Hallo,

my Problem is similar.

I added this in my function.php to enable featured image only after third paragraph. This works in amp. Thanks! But how is it possible to disable the featured image shown at the top of the page?

//Insert ads after third paragraph of single post content.
add_filter( ‘the_content’, ‘prefix_insert_post_ads’ );
function prefix_insert_post_ads( $content ) {
$ad_code = ‘[thumbnail]’;
if ( is_single() && ! is_admin() ) {
return prefix_insert_after_paragraph( $ad_code, 3, $content );
}
return $content;
}

// Parent Function that makes the magic happen
function prefix_insert_after_paragraph( $insertion, $paragraph_id, $content ) {
$closing_p = ”;
$paragraphs = explode( $closing_p, $content );
foreach ($paragraphs as $index => $paragraph) {
if ( trim( $paragraph ) ) {
$paragraphs[$index] .= $closing_p;
}
if ( $paragraph_id == $index + 1 ) {
$paragraphs[$index] .= $insertion;
}
}
return implode( ”, $paragraphs );
}

Thanks for help!

Greetings
Sönke

**Comment by MARQAS** [comment]
@Soenke2, can you share the URL and also the design which you are using?

**Comment by Soenke2** [comment]
Hallo,

the URL is:

https://rechtsanwalt-und-sozialrecht.de/...

The design? - genesis framework with genesis sample.

Greetings
Sönke

**Comment by Soenke2** [comment]
excuse ... the design is  design two ...

**Comment by Zabi09** [comment]
When I enable Featured Image from The Content option then both the images are getting disappear

**Comment by MARQAS** [comment]
Working fine on my end, can you check again @Zabi09?

**Comment by Zabi09** [comment]
Now it's working

**Comment by Soenke2** [comment]
Sorry - here it does not work.

 I disabled "get featured image from the content" but two images are still shown.

**Comment by MARQAS** [comment]
@Soenke2, which version are you using?
Can you contact us through https://ampforwp.com/support/ our team will help you to find the issue and fix this issue of yours?

**Comment by MohammedKaludi** [comment]
Not working in Swift.

**Comment by MARQAS** [comment]
@MohammedKaludi can you please explain in details?

**Comment by MohammedKaludi** [comment]
Working as expected, my bad, was testing on Wrong branch.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
