### ISSUE TITLE
Strange issue with date displaying wrongly on the homepage.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3188]
Strange issue with dates displaying wrongly on the homepage.
Page1: https://monosnap.com/file/dIp1yfyjCXgsx1mhJORWdRw32A0HZi
Page2: https://monosnap.com/file/qS0BUdurzjtobVhGXskSyvN1h0elx5
Ref: https://secure.helpscout.net/conversation/804855935/60148/

**Comment by MARQAS** [comment]
The issue has been resolved, we will reopen this if it reoccurs again
