### ISSUE TITLE
PROPER TESTING AND FIXING

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#319]
- [x] Test if tags, categories and archives have the right amphtml tag, if not then fix it

- [x] By default, the amphtml tag on categories and tags should be hidden.

**Comment by MohammedKaludi** [comment]
Fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/93103e15cc48b4f8c4577dc124089a82ac8f538d
