### ISSUE TITLE
0.9.97.52 fatal error on posts with comments present

### ISSUE THREAD

**Issue by szmigieldesign** [ahmedkaludi/accelerated-mobile-pages#3191]
it seems that 0.9.97.52 introduced a fatal error while trying to render AMP page when comments are present.

I get:

`Fatal error: Uncaught Error: Class 'AMP_Rev_Slider_Embed_Handler' not found in ***/public_html/wp-content/plugins/accelerated-mobile-pages/templates/custom-sanitizer.php:71 Stack trace: #0 ***/public_html/wp-content/plugins/accelerated-mobile-pages/templates/custom-sanitizer.php(46): AMPFORWP_Content->register_embed_handlers() #1 ***/public_html/wp-content/plugins/accelerated-mobile-pages/templates/custom-sanitizer.php(27): AMPFORWP_Content->transform() #2 ***/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php(6542): AMPFORWP_Content->__construct('<p>Bardzo cieka...', Array, Array) #3 ***/public_html/wp-includes/class-wp-hook.php(286): ampforwp_comments_sanitizer(3892) #4 ***/public_html/wp-includes/ in ***/public_html/wp-content/plugins/accelerated-mobile-pages/templates/custom-sanitizer.php on line 71`

While I use Revolution Slider on my site, it’s nowhere to be found on posts.

Posts without comments (0) render fine. Posts with comments render fatal error.

I’m also using wpDiscuz for comments. However, disabling wpDiscuz doesn’t fix the problem.

Original post:
https://wordpress.org/support/topic/0-9-97-52-fatal-error-on-posts-with-comments-present/

**Comment by ahmedkaludi** [comment]
I'm Sorry for the inconvenience.

The problem is that we are not able to recreate this issue, only you can help us fix this one.

Can you please help me fix this issue?

Can you please contact me via ampforwp.com/support ?

I'll personally help you fix this issue

**Comment by MohammedKaludi** [comment]
Tested on users website directly.

**Comment by EmilianoMaina** [comment]
It's the same HTTP 500 error on all AMP pages of my blog:

Fatal error: Uncaught TypeError: Argument 1 passed to DOMNode::replaceChild() must be an instance of DOMNode, string given in /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php:136 Stack trace: #0 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php(136): DOMNode->replaceChild('', Object(DOMElement)) #1 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(129): AMPforWP\AMPVendor\AMP_Gallery_Block_Sanitizer->sanitize() #2 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(94): AMPforWP\AMPVendor\AMP_Content_Sanitizer::sanitize('<p><strong>IP c...', Array, Array) #3 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(54): AMPf in /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php on line 136

**Comment by Itsmevinay** [comment]
I am having same issue "Uncaught Error: Class 'AMP_Rev_Slider_Embed_Handler'" massage error as mentioned above. Rollback to older version of the plugin seems temporary fix the issue (slider not visible in the post) cause Rev Slider module introduced in latest version and looks like it causing the issue.
I raised support ticket on official website, Let me know if I can help to troubleshoot solution, Thanks for your efforts.

**Comment by styleplusnz** [comment]
I'm having the same issue also. "Fatal error: Uncaught Error: Class 'AMP_Rev_Slider_Embed_Handler' ".

**Comment by MohammedKaludi** [comment]
We are going to push an update tomorrow that will have the fix for revolution slider.

So please wait for few hours.

Thank you very much for your cooperation

**Comment by styleplusnz** [comment]
Thanks Mohammed.

 

Regards

 

Jan

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.53 update.
