### ISSUE TITLE
copy the content stop working

### ISSUE THREAD

**Issue by morgankbarraco** [ahmedkaludi/accelerated-mobile-pages#3193]
Hi there, i update to last release and the button "copy the content" stop working

**Comment by MARQAS** [comment]
Can you please contact us via ampforwp.com/support ?

We will personally help you fix this issue

**Comment by Rkroy** [comment]
The issue is with Yoast SEO plugin and also its recreated at localhost, check screenshot.
User: https://secure.helpscout.net/conversation/860820396/68355?folderId=2322649
Ref: https://monosnap.com/file/homcPULE93GRvcAe6S16EvlJMlaDdk

**Comment by Rkroy** [comment]
Not working.

**Comment by Rkroy** [comment]
After re-checking copy the content is working.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57

**Comment by gioenjoy** [comment]
Still does not work in my website after update it. :(
