### ISSUE TITLE
Liveblog For AMP Extension need to add 

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3194]
Liveblog For AMP Extension need to add in the extension area

**Comment by pegazee** [comment]
When merging into the master, make sure that URL link should be replaced

**Comment by MohammedKaludi** [comment]
Live Blog has the Icon for Gravity forms.

**Comment by pegazee** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/72865cd9431ca5f439b50636236f508e1e05dee1#diff-260eba6333c3222e59a6aed22ac5ab37R351

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
