### ISSUE TITLE
Pinterest for AMP Extension need to add

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3195]
Pinterest for AMP Extension need to add in the extension area

**Comment by pegazee** [comment]
When merging into the master, make sure that URL link should be replaced

**Comment by MohammedKaludi** [comment]
Wrong icon for pinterest 

![Accelerated Mobile Pages Options ‹ 1 Development webstie — WordPress 2019-05-29 15-28-39](https://user-images.githubusercontent.com/16618009/58548360-cb23cd00-8226-11e9-8173-287bf49fd2be.png)

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
