### ISSUE TITLE
Fatal error to function mb_check_encoding()

### ISSUE THREAD

**Issue by ixnaypt** [ahmedkaludi/accelerated-mobile-pages#3197]
2019/05/17 08:53:29 [error] 1516#1516: *78668 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function AMPforWP\AMPVendor\mb_check_encoding() in (...)/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-blacklist-sanitizer.php:229

Version  0.9.97.52

**Comment by ahmedkaludi** [comment]
@ixnaypt  Please send us the WP information through https://ampforwp.com/support/

I will check and help you

**Comment by ixnaypt** [comment]
Thank you @ahmedkaludi .

Just submitted a ticket.

**Comment by MARQAS** [comment]
Resolved in #2967 and will be added in 0.9.97.53
