### ISSUE TITLE
Strange issue with featured images

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3202]
When we set the featured image then that post is showing 500 error and if there is no featured image in the post then it's working fine.

This issue is coming after 0.9.97.26 version

https://secure.helpscout.net/conversation/852348323/66362/

**Comment by MARQAS** [comment]
The issue has been resolved and the User confirmed it as well, we will reopen it if this issue reoccurs again,
