### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to DOMNode::replaceChild() 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3203]
https://secure.helpscout.net/conversation/856050937/67764?folderId=2770545

**Comment by EmilianoMaina** [comment]
All my AMP pages have HTTP 500 error with the following reason:

Fatal error: Uncaught TypeError: Argument 1 passed to DOMNode::replaceChild() must be an instance of DOMNode, string given in /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php:136 Stack trace: #0 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php(136): DOMNode->replaceChild('', Object(DOMElement)) #1 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(129): AMPforWP\AMPVendor\AMP_Gallery_Block_Sanitizer->sanitize() #2 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(94): AMPforWP\AMPVendor\AMP_Content_Sanitizer::sanitize('<p><strong>IP c...', Array, Array) #3 /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(54): AMPf in /home/lamiacas/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer.php on line 136

Current AMPforWP version is 0.9.97.52

**Comment by ajeetku** [comment]
Why added if ( empty( $images ) ) {
it means only one time it will go inside
$images not using any where in this function

**Comment by MohammedKaludi** [comment]
Pushing the code in next update

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.97.53 update.
