### ISSUE TITLE
Table style is not loading in AMP Page

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3204]
A table style is not loading in AMP Page, it is working for posts.
I have used given CSS code in Global CSS

table {width: 100%;margin-bottom:25px;}
td {padding: 0.5em 1em;border: 1px solid #ddd;}
tr:nth-child(odd) td {background: #f7f7f7;}

Help Scout Link: https://secure.helpscout.net/conversation/855675766/67729?folderId=2770545

Reference Link:https://www.wedlockindia.com/today-gold-rate-in-chennai/

**Comment by wedlockideas** [comment]
Please resolve this issue ASAP

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
