### ISSUE TITLE
Remove Unnessesary sections from the options panel

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3205]
This is just an example: https://monosnap.com/file/oM5yZqLbQvJcntWP1g1RhxNRzCCorh

There are many such things, properly check them and display those sections only if they are available with options.

**Comment by Rkroy** [comment]
Amp Layouts Translation Text section in the translation panel.

**Comment by pegazee** [comment]
@Rkroy That Amp Layouts Translation Text section code is written in the AMP layout plugin. So to improve the code, need to do in the AMP layout repo. Create a ticket in the AMP layout private repo to improve the code.

**Comment by MohammedKaludi** [comment]
Ready but seems it already merged into master.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
