### ISSUE TITLE
SVG images not rendering in AMP 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3208]
ref: https://secure.helpscout.net/conversation/801603829/59567?folderId=2770543
same issue in localhost

**Comment by MARQAS** [comment]
Its documentation can be found here: https://ampforwp.com/tutorials/?s=svg&ht-kb-search=1.

Closing this ticket for now.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
