### ISSUE TITLE
Google Analytics stopped working after update

### ISSUE THREAD

**Issue by DFC005** [ahmedkaludi/accelerated-mobile-pages#3209]
Since updating to the latest version (I was a few versions behind), Google Analytics seems to have stopped working. It had been working flawlessly before that for many, many months.

I now no longer see any results for my `/amp/` pages in both the real-time and site content etc.

Example: https://www.zerotackle.com/details-around-guthersons-new-deal-revealed-44234/amp/

Is there something obviously broken or incorrect with my setup?

**Comment by ahmedkaludi** [comment]
@DFC005 That's extremely strange, Do you happen to use Glue by Yoast plugin?

The Analytics tag seems to have loaded properly in the source. Just confirm that above question.

**Comment by DFC005** [comment]
@ahmedkaludi I was using it but have disabled it since finding the error. Doesn't seem to have resolved the issue though.

**Comment by ahmedkaludi** [comment]
I would recommend you to contact us directly on https://ampforwp.com/support/ - I will personally have a look there.
