### ISSUE TITLE
Alt code &#0128; is getting stripped out in amp when it is coming from Elementor modules.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3211]
Desc: Ascii Alt code &#0128; is getting stripped out in amp when it is coming from Elementor modules you can place it in any text module to check.
REF: https://www.linkinfluent.com/coach-professionnel-emploi/amp/
Screenshot: https://monosnap.com/file/BAEP3Ih3X2IvUjrHNxqfWpFGE1Jowc

**Comment by pegazee** [comment]
The solution would be applied on the elementor plugin as I've discussed the scenario and use case with @ajeetku .

**Comment by MARQAS** [comment]
Can we close this ticket then?

**Comment by pegazee** [comment]
This ticket is created in private repo of "AMP Page Builder Compatibility" plugin.
