### ISSUE TITLE
Unable to edit settings in Edit page / AMP Page Builder - JS Error

### ISSUE THREAD

**Issue by csloz** [ahmedkaludi/accelerated-mobile-pages#3213]
[Error] TypeError: undefined is not an object (evaluating 'app.mainContent.rows')
	openModulePopup (admin-amp-page-builder.js:396)
	showModulePopUp (admin-amp-page-builder.js:351)
	showModulePopUp
	click (Anonymous Script 1 (line 22:3349))
	_withTask (vue.min.js:6:44583)

Any suggestions?

**Comment by ahmedkaludi** [comment]
@csloz Can you please send us the WP information on https://ampforwp.com/support

So our team can have a look and help you?
