### ISSUE TITLE
The tag 'amp-next-page with inline config' appears more than once in the document

### ISSUE THREAD

**Issue by sudhakarsukumar** [ahmedkaludi/accelerated-mobile-pages#3214]
The tag 'amp-next-page with inline config' appears more than once in the document.

facing this issue while validating. 

https://www.nungu.io/gentleman-jack-the-moment-suranne-jones-makes-the-audience-upset/?amp

Please help us to resolve this issue.

**Comment by ahmedkaludi** [comment]
**Valid Issue**

You can re-occur this on localhost by enabling the Infinite scroll and the Single Design 2.

![image](https://user-images.githubusercontent.com/16532359/58222773-d1044480-7d34-11e9-866e-eea78e650b72.png)

**Comment by sudhakarsukumar** [comment]
Thanks for your quick action

**Comment by pegazee** [comment]
This ticket is merged in the #1545

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55

**Comment by MohammedKaludi** [comment]
This fix is breaking the AMP layout and all the designs are added through AMP layouts are getting blank page.

**Comment by MohammedKaludi** [comment]
Another issue reported #3243

**Comment by pegazee** [comment]
Pushed in 0.9.97.56
