### ISSUE TITLE
Not cleaned Featured Images

### ISSUE THREAD

**Issue by arct33** [ahmedkaludi/accelerated-mobile-pages#3215]
https://krasunja.ru/amp/
Do not disable double photo. 
Checkbox with  “Featured Images” removed.
![Screenshot_1](https://user-images.githubusercontent.com/42709823/58183765-8c3ac800-7cb8-11e9-9358-05ccddef407a.png)

In the advanced settings, “Featured Images” are also disabled
![Screenshot_2](https://user-images.githubusercontent.com/42709823/58184113-2864cf00-7cb9-11e9-8977-0c6188d07930.png)

**Comment by ahmedkaludi** [comment]
@arct33 Can you please send me the WP information on https://ampforwp.com/support ?

I will personally check and help you fix this issue for you.

**Comment by arct33** [comment]
Sent WP information to you in support.

**Comment by ahmedkaludi** [comment]
@arct33 What's your email or name? I can't seem to track this issue on our support system

**Comment by arct33** [comment]
for GitHub-  rokky977@gmail.com  

for support forum-  name- arct3
email- resistr@mail.ru 



>Воскресенье,  9 июня 2019, 13:40 +03:00 от Ahmed Kaludi <notifications@github.com>:
>
>@ arct33 Какой у тебя адрес электронной почты или имя?  Я не могу отследить эту проблему в нашей системе поддержки
>- 
>Вы получаете это, потому что вы были упомянуты. 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  отключите тему .

- 
СЕ ГЕЙ поном ЭНКО

**Comment by ahmedkaludi** [comment]
Sure, we got your email and I'm sending you the solution via email. 

I'm closing this ticket, we will continue the conversation on email
