### ISSUE TITLE
Change Hover / On Tap color of button in Swift

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3216]
Change Hover / On Tap color of button in Swift

![image](https://user-images.githubusercontent.com/16618009/58195594-f322a600-7ce5-11e9-9510-43b1483b2909.png)

Check this video 
https://gofile.io/?c=wUvrMv

**Comment by RajuJeelaga** [comment]
- [ ] Global option for the Button Text color,

- [ ] Need to connect to backed option

- [ ] Default color is white for the button text color

**Comment by MohammedKaludi** [comment]
Sanitization missing

**Comment by MohammedKaludi** [comment]
Not sanitized proprly

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
