### ISSUE TITLE
Horizontal scrolling on the homepage

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3217]
https://wordpress.org/support/topic/remove-side-scroll/

https://www.seoulinspired.com/amp/

**Comment by RajuJeelaga** [comment]
In swift Homepage the horizontal scroll, we are unable to recreate the issue, on our side homage is working fine with out any scroll.
If any one facing this problem, please contact here https://ampforwp.com/support/

**Comment by SayyadF** [comment]
REF: https://secure.helpscout.net/conversation/879361164/70736?folderId=3008055

A user-facing issue on mobile horizontal scrolling  on the homepage, here you can see this video
https://monosnap.com/file/EsFkcBIemscztU08Em5O8pikskpWcJ

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
