### ISSUE TITLE
External URL not working with Revolution Slider

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3218]
Ref.
https://secure.helpscout.net/conversation/858160593/68036?folderId=2844667

Screenshot:
http://take.ms/GsVez

**Comment by MARQAS** [comment]
It is working now.
But why External URL image is always coming as the first image in the carousel?

**Comment by MohammedKaludi** [comment]
ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
