### ISSUE TITLE
Need to add 'By Last X Days' option for "In-Content Related Posts"

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3219]
Need to show in the "In-Content Related Posts" only the latest articles published in the last 30 days.

Ref.
https://secure.helpscout.net/conversation/859821362/68216/

**Comment by santosh8793** [comment]
Please add the 'date query' argument only when date switch is enable, you can check the related post date query

**Comment by MohammedKaludi** [comment]
While merging into master need to do three thing.

1. Need to rename the ID https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e3a50e03963a6e62f617297cb9bc6da2328abd4c#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4864

2. escape the `$date_range` variable https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e3a50e03963a6e62f617297cb9bc6da2328abd4c#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4869

3. OL numbering is applying to inline related posts https://take.ms/j9HhH

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
