### ISSUE TITLE
Liststyle (Circle) added beside Published by in Design3 in 0.9.97.53

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#3222]
1. list style type beside Publishedby (https://prnt.sc/nsbm6y)
2. On hover, Menu Item should be full-width in Design 3(https://prnt.sc/nsbn4n)
3. Menu's background color need to be changed in Design 1(https://prnt.sc/nsbnro)

**Comment by RajuJeelaga** [comment]
- [ ] list style type beside Publishedby (https://prnt.sc/nsbm6y)
This above list style type problem will be fixed in #3247

**Comment by RajuJeelaga** [comment]
1) list style type beside Publishedby (https://prnt.sc/nsbm6y)
The above problem is coming only in master

**Comment by MohammedKaludi** [comment]
Ready.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
