### ISSUE TITLE
Eembed Videojs IMA Player - Custom Javascripts are not allowed issue.

### ISSUE THREAD

**Issue by sudhakarsukumar** [ahmedkaludi/accelerated-mobile-pages#3223]
As am trying to embed the videojs ima player in every posts. 

am getting this error that the custom java scripts are not allowed. so please help us to embed the video player plugin to our website. also please assist with the procedures to add the player to our website.
https://www.nungu.io/algeria-declared-malaria-free-by-world-health-organisation/?amp

**Comment by MARQAS** [comment]
Hi @sudhakarsukumar, You can't add custom JavaScripts in AMP, it is not allowed. 
Please check if they provide the AMP support or let us know how that works, so we can try to make a workaround for it if it's possible for us.

**Comment by ahmedkaludi** [comment]
We can implement amp-ima-video

**Comment by santosh8793** [comment]
Hi @sudhakarsukumar, can you tell us how you are using IMA player in non-amp, are you using any plugin or theme to display the IMA video Player, if you are using any , please share the name of the plugin or theme so that we can debug the issue in AMP.

**Comment by Zabi09** [comment]
@sudhakarsukumar I have checked your website and found that you are not using our AMPforWP plugin, Will you please use our AMP plugin and check once and also if you tell us exactly which plugin you are using for displaying the ima videos on the non-amp version we will create the compatibility for that plugin for you.

**Comment by MohammedKaludi** [comment]
This is for the Ads served via video format 

> "Embeds a video player for instream video ads that are integrated with the [IMA SDK](https://developers.google.com/interactive-media-ads/docs/sdks/html5/)."
