### ISSUE TITLE
AMP Page Builder options not working due to Groovy Menu Plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3226]
Screenshot: https://monosnap.com/file/CsmHC1y9HEkDJwpKWJQAeZt2Y9VRmm

The issue is recreated in local. Groovy menu plugin, Grooni Themes Addons Plugin, and Crane theme is available in Magazine three Telegram group for testing.

To install Crane theme we need to first install Grooni Themes Addons Plugin otherwise it will give Fatal error.

Help Scout Link: https://secure.helpscout.net/conversation/858613119/68080?folderId=2770545

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
