### ISSUE TITLE
AMP Blurb Module shows code on frontend

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3228]
I have some problems with the AMP Blurb Module. On the frontend it shows:

<div class="widget-10 w-bl">
</div>
IMAGE: https://monosnap.com/file/BXopsKPx1J5QAgLhA5djZglipxRyFa

**Comment by MARQAS** [comment]
It's working properly in Beta, sanitization is used in a bad way in master. We can directly do it in master.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.55
