### ISSUE TITLE
Need to make officially compatibility with WPML.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3229]
Need to make officially compatibility with WPML.
https://wpml.org/documentation/support/language-configuration-files/
https://wpml.org/documentation/theme-compatibility/go-global-program/
Ref: https://secure.helpscout.net/conversation/836970731/63999?folderId=2322649

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/890163616/72044?folderId=2632028

Need to show AMP Page builder content in the WPML Translation Management.

**Comment by MohammedKaludi** [comment]
Moved to : https://ampforwp.com/compatibility/idea-board/
