### ISSUE TITLE
Compatibility with Cloudflare stream.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3230]
Compatibility with Cloudflare stream.
Ref: https://secure.helpscout.net/conversation/825157240/62961?folderId=2322649

**Comment by itseoconsulting** [comment]
Cloudflare sent me this morning this AMP sample snippet for stream.

Is there a temporary workaround while working on common solutions?

Please advise.

<amp-iframe
  width="600"
  height="400"
  title="Video title"
  layout="responsive"
  sandbox="allow-scripts allow-same-origin allow-popups"
  frameborder="0"
  allowfullscreen
  src="https://iframe.cloudflarestream.com/<videoid">
</amp-iframe>

**Comment by Zabi09** [comment]
@itseoconsulting Yes you can use that amp-iframe but don't worry we have created the compatibility for that just follow this ticket and once this ticket is closed you can update plugin and your video will automatically appear in AMP also

**Comment by MohammedKaludi** [comment]
Ready

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
