### ISSUE TITLE
H1 on Logo in Swift

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3231]
Ref:
https://secure.helpscout.net/conversation/861725773/68454/

https://d33v4339jhl8k0.cloudfront.net/inline/8223/161ea0a024857f9f6a4e13f125064adad875ed21/afaddad210333d4ef420711086ec402f4921e1b4/image.png

**Comment by MohammedKaludi** [comment]
Need to talk on this.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
