### ISSUE TITLE
Logo is not loading from Site Accelerator (formerly photon) CDN

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3232]
Images are not loading from Site Accelerator (formerly photon) CDN
Ref: https://secure.helpscout.net/conversation/823395556/62699?folderId=2322649

**Comment by santosh8793** [comment]
The Logo is getting displayed from Site Accelerator CDN
![log-site-accelerator](https://user-images.githubusercontent.com/40556903/58781814-bc744780-8591-11e9-83a3-23a12565ef45.png)

**Comment by MARQAS** [comment]
The root of this issue is unknown as it got resolved itself without making any changes. Maybe because of caching but we don't know the exact cause. We will close this issue for now.
Feel free to reopen it if anyone faces the same issue.
