### ISSUE TITLE
Images and text does not Zoom in & out with mobile devices in amp version

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3233]
Ref: https://secure.helpscout.net/conversation/858450360/68062?folderId=2770543

**Comment by RajuJeelaga** [comment]
For Testing/Checking on Real device you can check on our garage 2 live server,
the same Zoom in & out functionality for Mobile, I added here
Please Check https://wordpress-123147-852156.cloudwaysapps.com/amp/

**Comment by MohammedKaludi** [comment]
Its breaking the website:
https://take.ms/HX3N4

Remove the class and file inclusion.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/37adb1f29ac37d0ef594129ab18bc64cb0e852f1#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3425

and use only `ampforwp_get_settings('amp-mobile-redirection)` to check the mobile redirection.

**Comment by MohammedKaludi** [comment]
Need to add `minimum-scale=1`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/129d857f2237e2f7e8e6555552fcc1fa46bf2706#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3433

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
