### ISSUE TITLE
Variables replacing in Advanced Google Analytics config code don't work

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3237]
Variables like `{url}` or `{title}` are not replaced because after applying `ampforwp_advance_google_analytics` filter (which replaces variables) value is overriden by next line of code (here /includes/features/analytics/analytics-functions.php:33, Plugin version: 0.9.97.52)

**Comment by kevinmrl** [comment]
You should change this file:  /includes/features/analytics/analytics-functions.php. 

These lines 32-38:

`
$ampforwp_ga_fields = apply_filters('ampforwp_advance_google_analytics', $ampforwp_ga_fields );
$ampforwp_ga_fields = json_encode( $ga_fields);
if($ampforwp_ga_fields && ampforwp_get_setting('ampforwp-ga-field-advance-switch')){
	$ampforwp_ga_fields = ampforwp_get_setting('ampforwp-ga-field-advance');
	$ampforwp_ga_fields = preg_replace('!//.*!', '', $ampforwp_ga_fields);
	$ampforwp_ga_fields = preg_replace('!/\*.*?\*/!s', '', $ampforwp_ga_fields);
}
`

should be changed to these ones:

`
$ampforwp_ga_fields = json_encode( $ga_fields);
if($ampforwp_ga_fields && ampforwp_get_setting('ampforwp-ga-field-advance-switch')){
	$ampforwp_ga_fields = ampforwp_get_setting('ampforwp-ga-field-advance');
	$ampforwp_ga_fields = preg_replace('!//.*!', '', $ampforwp_ga_fields);
	$ampforwp_ga_fields = preg_replace('!/\*.*?\*/!s', '', $ampforwp_ga_fields);
}
$ampforwp_ga_fields = apply_filters('ampforwp_advance_google_analytics', $ampforwp_ga_fields );
`

**Comment by MARQAS** [comment]
Hi @kevinmrl, I have improved the code and added here: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6985a270efa8498db699459f4f5404455b819c2f
Can you make those changes and check?

**Comment by kevinmrl** [comment]
Yes, I will check

**Comment by MohammedKaludi** [comment]
Closing this ticket, we can move conversion in Pull Request (#3239)

**Comment by MARQAS** [comment]
The proper solution is added in this ticket, so we can close the PR https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3239

**Comment by kevinmrl** [comment]
Should I still check it?

**Comment by kevinmrl** [comment]
So I've checked. Now I got an error

`PHP Fatal error:  Cannot redeclare checkAMPforPageBuilderStatus() (previously declared in /app/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php:781) in /app/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6976`

**Comment by kevinmrl** [comment]
Guys, will you fix it? Just add my changes from Pull Request #3239 and it will work, I've checked

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
