### ISSUE TITLE
Updates disabled, Title of amp page shows amp url of the page, notification issues

### ISSUE THREAD

**Issue by kdpuvvadi** [ahmedkaludi/accelerated-mobile-pages#324]
After the latest update Version 0.9.1.2.1, Many things have messed up on my site. First thing is not a single notification from other plugins is going of, Even though updates are available for other plugins, they aren't showing up, and AMP home and archive pages shows amp url like example.com/?amp. If i disable the plugin, notifications and Updates are fine.  

Additional Info:  TML, WP Rocket, Yoast SEO, ACF Pro and contact form are installed if it makes any sense..

**Comment by ahmedkaludi** [comment]
@kdpuvvadi can you updated the latest version and see if that fixes the issue.

**Comment by kdpuvvadi** [comment]
@ahmedkaludi as i've already mentioned latest version only installed

**Comment by ahmedkaludi** [comment]
Hey @kdpuvvadi Can you confirm if this was fixed?
