### ISSUE TITLE
Debug errors

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3240]
Ref: https://secure.helpscout.net/conversation/863987827/68788?folderId=1060556
Here you see the screenshot: https://monosnap.com/file/aLbkZdqiM8JaNWUtDkmKmLFbPiuGP3

**Comment by MARQAS** [comment]
Unable to recreate, unable to see either on users end. Asked the user for more info.

**Comment by amer07** [comment]
Here one more user-facing same issue 
Ref:https://secure.helpscout.net/conversation/865482351/68992?folderId=2770543
Here you see the screenshot: https://monosnap.com/file/CbKOXp7P1nbmGB07NHAn7GmXbIECRp

**Comment by MARQAS** [comment]
Resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3128
commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b39d2319b7ab61095ba5ec11cb8b4fe3cf2b31a7

**Comment by MohammedKaludi** [comment]
Code committed in #3128 so we can close this ticket.
