### ISSUE TITLE
Add feature to increase width for facebook like button and also add feature of data-action="recommend"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3241]
Help Scout Link: https://secure.helpscout.net/conversation/854310122/67566?folderId=2770545

**Comment by MARQAS** [comment]
I made some changes in this markup while resolving this ticket:https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3427

Make sure to merge it properly by taking the full code but not just with the above commit

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
