### ISSUE TITLE
Uncaught Error: Call to undefined function ampforwp_get_frontpage_id()

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3242]
If AMP by Automattic plugin is active, getting the below error.
Ref: https://secure.helpscout.net/conversation/859760561/68207?folderId=2322649
Ref: https://monosnap.com/file/1rnbNpPNUVbVg3bdOXDd5AJGuxa8Sj

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
