### ISSUE TITLE
Amp Version of Posts showing up Blank after the update!

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3243]
![Screenshot (245)](https://user-images.githubusercontent.com/51126159/58486712-01f4d700-8184-11e9-820e-9ddbc8ec221e.png)

**Comment by ahmedkaludi** [comment]
@Omnitos that's extremely strange. Can you please revert to an older version for now?

I will personally help you fix this Tomorrow morning

**Comment by Omnitos** [comment]
Yeah already tried to roll back to .4, it still persists even after clearing cache! It is only to just 2 recent posts, other posts are working fine!

**Comment by Omnitos** [comment]
So, can u fix it?

**Comment by MohammedKaludi** [comment]
> So, can u fix it?

We have fixed the issue and we are pushing the update as we speak(files are uploading). 

The new update(0.9.97.56) will be available to you in 30-40 mins. 

Please update the plugin to the latest version and let us know if the issue has been fixed.

Thank you very much for your feedback.

**Comment by Omnitos** [comment]
FIXED.

**Comment by MohammedKaludi** [comment]
Closing the ticket.
