### ISSUE TITLE
Failed to parse <script> contents. Is it valid JSON Error

### ISSUE THREAD

**Issue by jansu7** [ahmedkaludi/accelerated-mobile-pages#3245]
I get the “_Failed to parse <script> contents. Is it valid JSON_” error when I try to add this code for amp-analytics. The line that causes the error is: **"eventAction": videoSpec.percentages**

Has anyone had a similar issue?

```
"myVideoPercentagePlayed": {
  "on": "video-percentage-played",
  "request": "event",
  "selector": "#videoName",
  "videoSpec": {
  "percentages": [5, 25, 50, 75, 100]
  },
  "vars": {
    "eventCategory": "video",
    "eventAction": videoSpec.percentages
  }
}
```

**Comment by MARQAS** [comment]
Please check these out: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md
https://amp.dev/documentation/components/amp-analytics#triggers
https://github.com/ampproject/amphtml/issues/10855

**Comment by jansu7** [comment]
@MARQAS thanks a lot for the resources.

According to documents there's not a variable substitution for video percentages spec. 

I replaced the line below. Even though I don't get an error anymore, event label returns empty in the network hit.

`"eventLabel": "${percentages}" `

**Comment by ahmedkaludi** [comment]
I recommend you to continue the support on http://ampforwp.com/support ?

**Comment by cristhian-florez** [comment]
I just want to let you know that there is an AMP variable for it, normalizedPercentage, in case someone has the same question and don't waste much time trying to find it out, like me.

The correct way, in this case, should be

´´´
"eventLabel": "${normalizedPercentage}"
´´´
