### ISSUE TITLE
Menu font color bug 

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#3246]
I was using a CSS code to change the menu font color, now after the new update/s the code doesn’t work, I’m Trying to make it black, please let me know about a fix.
![30A90601-3BCE-44C6-BA53-6DCB8CCBB63F](https://user-images.githubusercontent.com/40724154/58507571-b7cb2000-819a-11e9-83c3-18b3d92c61a3.jpeg)
![8FC87A38-5027-4709-A760-B69A3CA79A6A](https://user-images.githubusercontent.com/40724154/58507576-b7cb2000-819a-11e9-8675-73ffa4e3ae05.jpeg)

**Comment by MARQAS** [comment]
I suggest you use static IDs instead of Dynamic ones. If you want to target the items of the Primary menu. Use this code: `.p-menu ul li a {color:#000}`
Let me know if you stuck anywhere

**Comment by SageFargo** [comment]
Thank you @marqas, issue been solved.

**Comment by SageFargo** [comment]
Thank you @marqas, issue been solved.
