### ISSUE TITLE
Need to add quotes for attribute layout=responsive in amp-img.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3248]
Desc: Need to add quotes for attribute layout=responsive in amp-img.
example: https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/components/featured-image/featured-image.php#L43

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
