### ISSUE TITLE
The tag <amp-ad> inserted via widget becomes <amp> (and the page doesn’t validate)

### ISSUE THREAD

**Issue by marcopanichi** [ahmedkaludi/accelerated-mobile-pages#3249]
**PREMISE**
I’ve set a system to inject advertising to amp pages, via widget. You can see that here:
https://pasteboard.co/IfHltaJ.png
(Note: I’ve set the rule “is_single(46334)” in order to not unvalidate all amp pages)

**WHAT I DO**
I insert this code on the widget that will be printed on the amp post:
`<amp-ad width=300 height=250
    type="doubleclick"
    data-slot="/5966054/BraviBimbi/BraviBimbi_amp_ATF"
    rtc-config='{"vendors": {"prebidappnexus": {"PLACEMENT_ID": "16057439"}}, "timeoutMillis": 1000}'>
</amp-ad>`

**WHAT I EXPECT**
That the code will be printed in the amp post

**WHAT HAPPENS INSTEAD**
The `<amp-ad>` tag become `<amp>` (you can check this [viewing the code](view-source:https://www.bravibimbi.it/news-bimbi/bimba-invita-la-regina-elisabetta-al-suo-compleanno/amp/) and searching for "<amp width") and the page doesn't validate: https://validator.ampproject.org/#url=https%3A%2F%2Fwww.bravibimbi.it%2Fnews-bimbi%2Fbimba-invita-la-regina-elisabetta-al-suo-compleanno%2Famp%2F

**WHAT I'VE TRIED**
- the Classic Text Widget plugin
- the Custom HTML widget
- the Text widget
- looking under the AMP settings for something that could cause the problem
- I posted the problem on the support forum https://wordpress.org/support/topic/the-tag-inserted-via-widget-becomes-and-the-page-doesnt-valida/ where Ahmed redirected me here

PS: Other oddities
- if I put the snippet between comments <!– … –>, the snippet <!–<amp-ad>…</amp-ad>–> became <!–<amp-ad>…–> ; in other words, the <amp-ad> doesn’t change, but the closing tag will be removed
- on the post https://www.bravibimbi.it/news-bimbi/papa-inventa-dispositivo-anti-soffocamento-per-i-bambini/ there is a video; the respective amp page https://www.bravibimbi.it/news-bimbi/papa-inventa-dispositivo-anti-soffocamento-per-i-bambini/amp/ doesn’t validate because the video is changed to a <amp> tag

**Comment by marcopanichi** [comment]
I want to add other informations

The system I've created is structured in that way, in functions.php:

	// ----------------------- WIDGETS

	add_action( 'widgets_init', 'ads_areas' );
	function ads_areas()
	{

		...

		// articolo NON AMP dopo 2 paragrafi
		register_sidebar( array(
			'name'			=> "Articolo (NON AMP) - Dopo 2 paragrafi",
			'id'			=> 'ads-area-articolo-dopo-2-p',
			'before_widget'	=> '<div id="%1$s" class="%2$s ads-area ads-area-articolo-dopo-2-p">',
			'after_widget'	=> '</div>',
			'before_title'	=> '<h3>',
			'after_title'	=> '</h3>',
		) );
		
		...
		
	}

	// ----------------------- ADS INJECTION

	add_filter( 'the_content', 'ads_area_inject', 20 );
	function ads_area_inject($content)
	{
		...
		
		// AMP
		if( function_exists('is_amp_endpoint') && is_amp_endpoint() )
		{
			$POSIZIONE_SECONDO_PARAGRAFO .= fawola_get_dynamic_sidebar('ads-area-articolo-amp-dopo-2-p');
			...
		}
		
		...
		
		// INJECTION
		$paragraphs = explode( '</p>', $content );
		$i = 1;
		$content = '';
		$quarto_paragrafo_piazzato = false;
		foreach( $paragraphs as $paragraph )
		{
			if( $i == 2 )
			{
				$paragraph = '<div class="inpost-adv" style="margin: 10px 0;">'.$POSIZIONE_SECONDO_PARAGRAFO.'</div>'.$paragraph;
			}
			elseif( $i == 4 or $i==5 )
			{
				if( strpos($paragraph,'<img')===false and $quarto_paragrafo_piazzato==false )
				{
					$paragraph .= '<div class="inpost-adv quarto-paragrafo" style="margin: 10px 0;">'.$POSIZIONE_QUARTO_PARAGRAFO.'</div>';
					$quarto_paragrafo_piazzato = true;
				}
			}		
			$i++;
			$content .= $paragraph.'</p>';
		}
		$content .= $POSIZIONE_IN_FONDO;
		
		// RETURN
		return $content;
	}

	// ----------------------- AUXILIARY FUNCTION

	function fawola_get_dynamic_sidebar( $id )
	{
		$sidebar_contents = "";
		ob_start();
		dynamic_sidebar( $id );
		$sidebar_contents = ob_get_clean();
		return $sidebar_contents;
	}


That said, I've tried to replace the row

`$POSIZIONE_SECONDO_PARAGRAFO .= fawola_get_dynamic_sidebar('ads-area-articolo-amp-dopo-2-p');`

with

`$POSIZIONE_SECONDO_PARAGRAFO .= "<div-some class='test'></div-some>".fawola_get_dynamic_sidebar('ads-area-articolo-amp-dopo-2-p');`

As result, I got that the tag <div-some> becames <div>

So, the problem is after the widget system of wordpress.

**Comment by marcopanichi** [comment]
Update: I solved rising the priority of the filter:

	add_filter( 'the_content', 'ads_area_inject', 2000 );

**Comment by ahmedkaludi** [comment]
Glad to hear that
