### ISSUE TITLE
next page on homepage

### ISSUE THREAD

**Issue by fikryans** [ahmedkaludi/accelerated-mobile-pages#325]
problem with next page in homepage.. let the gif image explain this
![amp](https://cloud.githubusercontent.com/assets/8897997/21380174/c8a07398-c785-11e6-8a15-7d84dc614f0f.gif)

**Comment by fikryans** [comment]
@ahmedkaludi please fixing this

**Comment by ahmedkaludi** [comment]
I have added this in our milestone. We're working on this.

**Comment by khaledMohammed000** [comment]
@fikryans Please update plugin and this will solve the issue :)
