### ISSUE TITLE
mandatory tag 'link rel=canonical' is missing or incorrect on Homepage- when RankMath is active

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#3250]
Screenshot: https://monosnap.com/file/Ps3HW5wjlmr1567EQxDYdgyBWYaF9u

**Comment by Rkroy** [comment]
On archive and single pages, the below error is showing.
The tag 'link rel=canonical' appears more than once in the document.

**Comment by pegazee** [comment]
It seems you've not selected the "RankMath SEO" from the 'Select SEO Plugin' option.

**Comment by MohammedKaludi** [comment]
Ready to mereg

**Comment by pegazee** [comment]
Pushed in 0.9.97.57
