### ISSUE TITLE
When auto add amp in menu option is enabled it is rendering the cache version menu for WPML site.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3251]
Desc: When auto add amp in menu option is enabled it is rendering the cache version menu for WPML site not different menu.

REF: https://secure.helpscout.net/conversation/849398731/65563?folderId=2322649

**Comment by MARQAS** [comment]
Added in master

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
