### ISSUE TITLE
Need to add template-mode

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3252]
This functionality Enables group users to work on the main/AMP theme

**Comment by MARQAS** [comment]
Fatal error: require(): Failed opening required 'O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages/includes/change-log.php' (include_path='.;C:\php\pear') in O:\wamp64\www\weekly\wp-content\plugins\accelerated-mobile-pages\includes\welcome.php on line 75
--

**Comment by MohammedKaludi** [comment]
Infinite Scroll was turned on previously  so it is giving validation errors 
https://take.ms/xadvx

**Comment by RajuJeelaga** [comment]
Bugs

- [ ] Video widget is not working in sidebar

**Comment by MohammedKaludi** [comment]
1. Escaping missing $comment_nonce
 https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bb0dabba01e0b538e99d90dc1f6de874b3059d96#diff-a936e64eb1612e51d694f2989f419d1eR146

2. escaping missing for $submit_url $mustache, $content 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bb0dabba01e0b538e99d90dc1f6de874b3059d96#diff-a936e64eb1612e51d694f2989f419d1eR156

**Comment by MohammedKaludi** [comment]
ready  to ship

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
