### ISSUE TITLE
Add feature to go to non AMP page on next and previous links

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3253]
The user wants to go to the non-AMP link when he clicks on the next and previous button.
Help Scout Link: https://secure.helpscout.net/conversation/854310122/67566/

**Comment by MARQAS** [comment]
I guess we can use these filters. `ampforwp_next_link` & `ampforwp_prev_link`, right?

**Comment by Zabi09** [comment]
With the help of those filters, we cannot change the next/previous links as there are for changing only the text

**Comment by santosh8793** [comment]
Please check with below filters to change the next/previous links

**Comment by ajeetku** [comment]
We need to change just links but here added to condition and duplicate the anchor tag
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c8e5839982869fbec37d4d236e39f4fcabb05e74#diff-b694fc4d98681b6f22c1e98c6d09c131R18 $redux_builder_amp change it to ampforwp_get_setting

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
