### ISSUE TITLE
Images are getting distorted in AMP when the lazy loading option is enabled in the WoodMart theme settings

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3254]
DES: Images are getting distorted in AMP when the lazy loading option is enabled in the WoodMart theme settings
https://secure.helpscout.net/conversation/854866366/67623?folderId=2632028

**Comment by MohammedKaludi** [comment]
This will remove the lazy loading functionality from non-amp as well.

**Comment by MARQAS** [comment]
Can we use our previous functions instead of creating new one? https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2c6d38819777c5e74f7b73d069eeec0881f49af2#diff-6aa5512f7dd8d5ce60fc97b0f340912cR1242

**Comment by MARQAS** [comment]
Try to use a different hook as it is affecting the non-amp as well.

**Comment by MARQAS** [comment]
1. What about paginated pages? eg: website.com/amp/page/2 
2. What if its a category page with category name as amp? eg: website.com/category/amp

**Comment by MARQAS** [comment]
Use `AMPFORWP_AMP_QUERY_VAR` instead of just `amp`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ee9766b3a189cb4c8c6b88c26b52f7e63e2ccee5#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6426

**Comment by MohammedKaludi** [comment]
@MARQAS and @santosh8793 are you sure this is the best way to check if we are in AMP mode?

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
