### ISSUE TITLE
WordPress Content Gallery should work with D1, 2 & 3

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3255]
https://monosnap.com/file/tXA3QhHj5U3kOHPRyaO5FaQPvnmP34

**Comment by MARQAS** [comment]
Where is the solution @santosh8793? He mentioned that Gallery designs option is not working with D1 2 and 3. 
Please check in master you will understand.

**Comment by Zabi09** [comment]
Working as expected but need to add this section in all designs - https://prnt.sc/nzwtoc

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
