### ISSUE TITLE
Allow users to register scripts in proper way in AMP Theme Framework

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3257]
Allow them to register scripts instead of them adding in the header.php so that it doesn't get duplicated at all.

**SCENARIO**
The plugin adds scripts based on the elements that are added to the pages using the page builder.

So for example, lets assume that there is an accordion element added on the homepage of the website using the page builder, the plugin will add the accordion js to the homepage.

Now, the issue is that say there is an accordion added to the header of the theme (not the page content) (the accordion markup is added to the header.php file in /wp-content/plugins/amp-theme-framework-master), in order to make this accordion work on the site, the accordion js script needs to be added on all pages (because the accordion would appear on each page as it’s in the header). Once this is done, the homepage shows an error, as there are duplicate accordion js files, one added by the plugin because there was an accordion added to the homepage content using page builder, and another was added manually because of the accordion in the header.php file.

https://wordpress.org/support/topic/duplicate-scripts/

**Comment by vagu71** [comment]
@ahmedkaludi thank you for creating this ticket. Eagerly waiting on this getting fixed.

**Comment by MohammedKaludi** [comment]
need to improve the code where user ads the Markup and script should automatically add it in the header.

**Comment by Zabi09** [comment]
If the script is added manually then it should be removed - https://prnt.sc/pp3czc

**Comment by prkirby** [comment]
Hey everyone, just wondering if this is resolved and when it will be pushed live? This is crushing our score on over 1000 pages right now, as we need amp-iframe for our comments, and its being added for pages with embedded youtube as well. Thanks!

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
