### ISSUE TITLE
Auto Append AMP in Menu doesn't work for the Category items

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3258]
1. In the settings set: Auto Add AMP in Menu URL. For pages – this works and sends to the AMP page. For categories – does not work and sends a page to a regular page.

- Re-Occurs in Localhost as well. 

REF: https://wordpress.org/support/topic/amp-menu-and-icons/

**Comment by pegazee** [comment]
It seems the "Archives [Category & Tags]" option disabled in the AMP panel section.
