### ISSUE TITLE
Need to Add Compatibilty with Impreza Theme's lazyLoad Option

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#3259]
Href:
https://secure.helpscout.net/conversation/859504827/68169?folderId=2632028

User is facing a Validation error when this option is enabled.
https://prnt.sc/nvbctm

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
