### ISSUE TITLE
Fatal error  : when remove author meta name and date on AMP posts/articles in design-2

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3260]
When we need to remove the author meta name and date on AMP posts while using design -2.
I have try to recreate in localhost so i follow these steps.
Customizing > AMP> Design >Meta info
But same think i observe in local 
Here see the screenshots: 
1.https://monosnap.com/file/KbvEkhOlr3CCXVisFqyXCzpwm1LODg
2.https://monosnap.com/file/78gJTuHvYuyW9MQhowgDTcRIjc5aeJ

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
