### ISSUE TITLE
OpenGraph Support in AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3261]
OpenGraph Support in AMP

https://wordpress.org/support/topic/featured-image-not-working-49/#post-11582488

**Comment by ajeetku** [comment]
Warning: array_key_exists() expects parameter 2 to be array, null given in ***plugins\accelerated-mobile-pages\includes\features\opengraph.php on line 267

**Comment by Zabi09** [comment]
Notice: Undefined variable: wp in C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\features\opengraph.php on line 262

Notice: Trying to get property 'request' of non-object in C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\features\opengraph.php on line 262

Notice: Undefined variable: wp in C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\features\opengraph.php on line 266

Notice: Trying to get property 'query_vars' of non-object in C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\features\opengraph.php on line 266

Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\features\opengraph.php on line 267

Notice: Undefined variable: page in C:\xampp2\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\features\opengraph.php on line 270

**Comment by MohammedKaludi** [comment]
Ready to ship.

**Comment by MohammedKaludi** [comment]
conditions are incorrect.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/76578fc54d472c082978ae4bbdea1446a9c78078#diff-260eba6333c3222e59a6aed22ac5ab37R1634

**Comment by MohammedKaludi** [comment]
Ready

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
