### ISSUE TITLE
Content sneak-peak won’t work properly 

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#3262]
Props on fixing the content sneak-peak, however it won’t work on every article, it only works in a few. 

I have tried to lower the size, and still no results, on the articles that it’s working it reduces the height/weight but on other articles there’s no effect 
![DB94F7D8-7629-42FA-B218-FA7932F815B5](https://user-images.githubusercontent.com/40724154/58648135-b3754300-8311-11e9-9c85-0f3fdeb59d6b.jpeg)

**Comment by SageFargo** [comment]
![0940F0FD-AC10-412C-9569-35CF051252AA](https://user-images.githubusercontent.com/40724154/58648252-f9320b80-8311-11e9-9f0b-6acef3c9cae6.jpeg)

**Comment by MARQAS** [comment]
@SageFargo Maybe because of less content?

**Comment by MARQAS** [comment]
Can you share the URLs?

**Comment by SageFargo** [comment]
@marqas https://fargo1ife.com
Pretty much every url

**Comment by ahmedkaludi** [comment]
@SageFargo please send this request on ampforwp.com/support/
Let the support team debug this issue then we can have the full clarity

**Comment by SageFargo** [comment]
@Marqas content length play no role, I already checked other posts, set the content height to 150px and yet similar content length posts won’t run the script.

@ahmedkaludi I have sent a request, please look into this for a quick fix as soon as possible

**Comment by SageFargo** [comment]
Fixed.
