### ISSUE TITLE
Featured image appearing in content after update

### ISSUE THREAD

**Issue by kolli1337** [ahmedkaludi/accelerated-mobile-pages#3263]
Cross post from [Support Forum](https://wordpress.org/support/topic/featured-image-in-post-content/) as requested by @ahmedkaludi :

Since updating from v0.9.97.50.1 to v0.9.97.51.2 (and meanwhile to 0.9.97.56), the featured image is suddenly displayed on my AMP pages above the remaining content. I haven’t turned on either the “Featured Image from The Content” or the “Duplicate Featured Image” feature. Actually I didn’t change any settings, just updated the plugin.

Check this links for an example - the only difference between these environments right now is the mentioned update of this plugin:

- [Live](https://www.urfair.shop/magazin/muttertag-2019-angebote-geschenksets/amp)
- [Staging](https://urfairstaging.wpengine.com/magazin/muttertag-2019-angebote-geschenksets/amp)

Best regards,

kolli

**Comment by ahmedkaludi** [comment]
can you please send us the WP details on https://ampforwp.com/support/ ?

**Comment by ahmedkaludi** [comment]
@kolli1337 can you please send us the details?

**Comment by kolli1337** [comment]
@ahmedkaludi 

Done! Although, the issue doesn't occur anymore after updating to version 0.9.97.58 and beyond, so apparently it has been fixed already... :)

I'll leave the staging env on version 0.9.97.57 for now though, in case you want to check anything.

Best regards,

kolli

**Comment by ahmedkaludi** [comment]
if it's fixed, then it needs no testing. So I'll close this ticket. If it's still the case then create a new ticket
