### ISSUE TITLE
Archive and Categoy not working properly with Swift design

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3265]
Archives are not working in some usecases.
1. https://wordpress.org/support/topic/category-archives-not-working-2/
2. Not Working on Akash's localhost
3. Some posts are missing in all designs (re-creating in my localhost)

**Comment by MARQAS** [comment]
Added in master

**Comment by MohammedKaludi** [comment]
Ready and tested.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
