### ISSUE TITLE
 link=" next" is appearing in the custom front page

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3266]
link=" next" is appearing in the static custom front page, 
https://secure.helpscout.net/conversation/863277844/68657?folderId=2632028
https://monosnap.com/file/ODXZY1HolPEEsxy9Gc6IqJvds8dE5q

**Comment by MohammedKaludi** [comment]
Ready 👍

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
