### ISSUE TITLE
Site's Robots.txt redirecting to random Amp post after the update

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3267]
The site's robots.txt file is redirecting to a post after this update. Please Fix it  ASAP! Site name omnitos.com

**Comment by ahmedkaludi** [comment]
@Omnitos Can you please provide me a little more details on this?

how can I see the issue?

**Comment by Omnitos** [comment]
https://omnitos.com/robots.txt

**Comment by Omnitos** [comment]
Any other detail needed?

**Comment by Omnitos** [comment]
?

**Comment by ahmedkaludi** [comment]
This may or may not be an issue with the AMP, please create a ticket on ampforwp.com/support

I'll have a look at it

**Comment by Omnitos** [comment]
Yes, it is amp related! I deactivated the plugin and the robots.txt was fine and then when I reactivated it got the same issue! please solve it, the email support replies late, please u create the ticket! RKroy already have login details!

**Comment by Omnitos** [comment]
messaged on the support too! please fix it!

**Comment by Omnitos** [comment]
Why it is taking so much time?

**Comment by Omnitos** [comment]
Fixed it!

**Comment by pegazee** [comment]
@Omnitos,

How did you fixed the issue? what was the solution, can you please elaborate in detail?

**Comment by Omnitos** [comment]
deleted all amp plugins and reinstalled every single one of them!

**Comment by Omnitos** [comment]
Especially amp cache plugin
