### ISSUE TITLE
?nonamp=1 should redirect to normal url 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3269]
When we click on the View non-AMP link, then it should redirect to the website.com without ?nonamp=1
https://secure.helpscout.net/conversation/835038788/63852?folderId=2770545

Use case: 
1. Semrush and SEO tools are taking them as urls
2. People who have built the custom homepage, they are having issues, see: https://monosnap.com/file/b9LtkFP6t3lKaWr6942fdfVJHRauj2

**Comment by Omnitos** [comment]
Same here, see a validation error!
see ss
![Screenshot (255)](https://user-images.githubusercontent.com/51126159/58784253-98038400-8600-11e9-9ee8-f7054e8cd065.png)

**Comment by Omnitos** [comment]
?

**Comment by Taran0007** [comment]
I am Having Same Issue. Whenever i click "View Non-AMP Version" It Doesn't Work as it Should. Rather it is loading PWA. Which i am not using and Plugin is removed. i think PWA Edited Files of AMP For WP and Now It is Requesting PWA files.

**Comment by pegazee** [comment]
Working perfectly on my end.

**Comment by MohammedKaludi** [comment]
Also check this fix is valid and the redirection code is added twice 
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3326

**Comment by Zabi09** [comment]
Yes, the code is repeating in master only and I have just checked by removing the additional code - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ddd02239a0d31d84c383ab1f6daa5bdc0b1e862e and it's working fine.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
