### ISSUE TITLE
Error with get_avatar()

### ISSUE THREAD

**Issue by dwien** [ahmedkaludi/accelerated-mobile-pages#327]
There is one error with get_avatar(). When you have a (displayed) username with an blank character there is no avatar displayed.

It is just possible when you use `&nbsp;` in the username instead of spaces, but it should also work when you have a name with blank character

**Comment by khaledMohammed000** [comment]
Hey @dwien, can you please elaborate the issue

**Comment by MohammedKaludi** [comment]
Fixed #365
