### ISSUE TITLE
 pages redirect to /amp/amp after last update

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3270]
After update 0.9.97.57 when you visit a page (whatever.com) in mobile it redirects to whatever.com/amp/amp (instead of  whatever.com/amp)
Easy to see with google page speed insights, insert the name of the page and see the mobile url it redirect to.
I bet this is not good for SEO at all

**Comment by ahmedkaludi** [comment]
That's strange! 

Do you have a site where this is occurring?

Can you please send those WP details on https://ampforwp.com/support ?

So we can fix this ASAP

**Comment by MohammedKaludi** [comment]
Hey @olddoc,

Thank you for creating the ticket, I have tested the latest update on multiple WordPress installations after going through your ticket, but I'm not able to re-create the issue as it is working fine on all those websites.

As Ahmed mentioned if you able to provide us the info, we will be able to identify the issue and fix the bug immediately and will push an update to tackle the issue.

**Comment by olddoc** [comment]
www.nexustraductions.com (your team already has access)

**Comment by MohammedKaludi** [comment]
> www.nexustraductions.com



> [www.nexustraductions.com](http://www.nexustraductions.com) (your team already has access)

Checking it rightnow.

**Comment by MohammedKaludi** [comment]
There was some conflict with WPML and AMPforWP. I have fixed that in your website.

Can you please test and let me know that everything is working as expected?

If everything is working fine, then I'll push an quick update to everyone.

Thank you very much for your co-operation.

**Comment by olddoc** [comment]
I see it is back to version 0.9.97.56. It seems fixeed but is this redirection normal?
-- | --
(Initial: https://www.nexustraductions.com/) | 0 ms
/amp(www.nexustraductions.com) | 780 ms
/amp/(www.nexustraductions.com) | 180 ms

**Comment by olddoc** [comment]
Solved! Thank you =)

**Comment by MohammedKaludi** [comment]
Issue fixed, need to push this code in next update.

@olddoc, Im glad that issue has been resolved, but please don't close the tickets as issue is not pushed in the master.

**Comment by Rkroy** [comment]
Posts are not redirecting to AMP on mobile.

**Comment by pegazee** [comment]
This ticket is related to the WPML and Homepage amphtml conflict issue, not the Mobile redirection issue.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
