### ISSUE TITLE
Indexing Issue of Plugin File

### ISSUE THREAD

**Issue by mehulboricha** [ahmedkaludi/accelerated-mobile-pages#3271]
Kindly add noindex tag. This is getting indexed in google

https://www.techrrival.com/addic4-content/plugins/accelerated-mobile-pages/includes/onesignal-integration/amp-helper-frame.html

**Comment by ahmedkaludi** [comment]
Sure, this makes sense

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
