### ISSUE TITLE
Amp for wp Version 0.9.97.57 error can't disable featured image

### ISSUE THREAD

**Issue by line2share** [ahmedkaludi/accelerated-mobile-pages#3272]
Amp for wp Version 0.9.97.57 error can't disable featured image in single post.

I've already uncheck featured image on Appearance > amp > design > featured image. But featured image still showing. 

I can disable if used the previous version.

I used wp version 4.9.4

Thanks for your great amp

**Comment by ahmedkaludi** [comment]
This was a fatal error in the customizer

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
