### ISSUE TITLE
Social Sticky icons bar appearing even when not manually enabled

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3273]
Social Sticky icons bar is appearing in SWIFT theme News layout even not manually enabled it. Just behind the amp sticky ad, after closing it you can see a sticky social icons bar see ss below.

![Screenshot (248)](https://user-images.githubusercontent.com/51126159/58782967-75bc3700-85fd-11e9-98e4-eb6ca0a839d0.png)

**Comment by ahmedkaludi** [comment]
@RajuJeelaga can you test and let me know if this layouts or core issue?

**Comment by Omnitos** [comment]
@RajuJeelaga, please check

**Comment by RajuJeelaga** [comment]
@Omnitos  Do you want the sticky social icons in the single......?

**Comment by Omnitos** [comment]
They are existing even if disabled I wanna remove them

**Comment by RajuJeelaga** [comment]
@Omnitos 
I have removed the sticky social icons through options in single page, please check
so, if you do any option changes, please clear the AMP cache as well, because you are using AMP cache.
If you need any help, please let me know.

**Comment by ahmedkaludi** [comment]
@Omnitos any feedback?

**Comment by Omnitos** [comment]
It's fine
