### ISSUE TITLE
Parallax Effect not working in Advanced Amp Ads

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3274]
Parallax Effect not working in Advanced Amp Ads for Adsense for any post! Even when enabled! You can check it yourself: Site link: omnitos.com/amp

**Comment by Omnitos** [comment]
It's probably a bug, it used to work 3 months earlier

**Comment by ahmedkaludi** [comment]
Just report to our team on https://ampforwp.com/support -  they will have a look, verify and then we will work on the bug.
