### ISSUE TITLE
Google Lighthouse Test shows Tap targets are not sized appropriately in SEO score

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3275]
Google Lighthouse Test audit shows Tap targets are not sized appropriately in SEO score. You can check the screenshot below, for the lighthouse test of this amp URL: https://omnitos.com/spider-man-far-from-home-final-trailer-just-got-leaked-new-details/amp/
Here is the attached ss below for the problem!
![Screenshot (252)](https://user-images.githubusercontent.com/51126159/58783340-4e199e80-85fe-11e9-9e3c-ff62bef67ceb.png)

**Comment by ahmedkaludi** [comment]
This one is valid but it's a part of AMP layouts so it's created under our private extension bugs list: https://trello.com/c/a2OxWZWf/728-google-lighthouse-test-shows-tap-targets-are-not-sized-appropriately-in-seo-score-3275

Thanks for helping us improve
