### ISSUE TITLE
Google Lighthouse Audit Best Practices show Links to cross-origin destinations are unsafe

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3276]
Google Lighthouse Audit Best Practices show Links to cross-origin destinations are unsafe. Means they require Adding `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities on external referrer links see ss below:
![Screenshot (254)](https://user-images.githubusercontent.com/51126159/58783611-f3cd0d80-85fe-11e9-9c55-65b0ba76bb13.png)

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ea24411180c8f6bffb79a650bb709c91b1159b3c#diff-9253027ab0fd0dc36f48733d5f042541R45
is this function out of the Namespace or inside Namespace?

**Comment by Rkroy** [comment]
rel="noreferrer" not getting added to external links, please check.

**Comment by MARQAS** [comment]
@Rkroy Please check again, it is working properly on everyone's end.

**Comment by Rkroy** [comment]
Working fine now.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
