### ISSUE TITLE
Is there a way to return to 0.9.97.55?

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3277]
Conflicts with WPML multiply themselves;
-in 0.9.97.56 menus broke so you can't save any changes (it gives an Apache error, already reported to Imran but no reply yet). 
-And url /amp/amp problem since 0.9.97.57 which I posted here on 01/06/19
- So I would like to return to 0.9.97.55 which was stable enough for me if it is possible until these conflicts are solved, is it possible?

**Comment by MohammedKaludi** [comment]
For reverting back to older version please check this tutorial
