### ISSUE TITLE
Enhancement suggestion: add [alt] attributes to Image elements

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3278]
Good for SEO and disabled people...

**Comment by ahmedkaludi** [comment]
@olddoc we are already adding alt tags in the site. Can you share the exact place which area are you talking about?

**Comment by olddoc** [comment]
ALL of the pictures shown in the website..... (That was easy, lol)

Regards

Carlos Derqui

**Comment by ahmedkaludi** [comment]
@olddoc can you share the URL so I can test?

because alt tag works perfectly on my end.

**Comment by olddoc** [comment]
Of course: www.nexustraductions.com

Try this test to see what I am talking about:
https://www.seoptimer.com/alt-tag-checker/www.nexustraductions.com
https://www.seoptimer.com/alt-tag-checker/www.nexustraductions.com/amp
<https://www.seoptimer.com/alt-tag-checker/www.nexustraductions.com/amp>

Kind reagrds

Carlos Derqui

**Comment by ahmedkaludi** [comment]
Thanks, Carlos, it's because of the contact bar, https://monosnap.com/file/WDHNfn8qWO8hEjmokXNhinXfoJQnuP

I have created a ticket for that internally and we will fix it with the extension release.

It's not a bug of the core, therefore the ticket will be closed.
