### ISSUE TITLE
When Parmalinks in "/index.php/%year%/%monthnum%/%day%/%postname%/" format category not working

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3279]
Screenshot: https://monosnap.com/file/NY0wOOIokwNPhX84hapdO03l2VX07W
Help Scout Link: https://secure.helpscout.net/conversation/867659792/69274?folderId=2770545

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
