### ISSUE TITLE
AAWP plugin in AMP

### ISSUE THREAD

**Issue by azira1984** [ahmedkaludi/accelerated-mobile-pages#3280]
Hello the plugins of the aawp plugin do not look properly, it comes out a very long spacing before looking like the products [https://www.peluqueriacanina.online/dormir-con-mi-perro-gato/amp/] although it is also true that the call to the amazon api sometimes fails

**Comment by ahmedkaludi** [comment]
We are going to release compatibility of AAWP in the near future as a part of the extension: https://ampforwp.com/extensions/
