### ISSUE TITLE
Need to add more variables support in Advanced Google Analytics.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3281]
Ref: https://secure.helpscout.net/conversation/868671637/69418?folderId=2322649
Need to add more variables support in Advanced Google Analytics, check the following variables.
Category
Published at
Tags
SEO Score
Focus Keyword

**Comment by MARQAS** [comment]
Check for function or class exist: 1. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0c26bcfd56ba1276613596e37b34eacdb5b7eb25#diff-b27b16759fae0fb0d94cc6e00107c8efR376
2. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0c26bcfd56ba1276613596e37b34eacdb5b7eb25#diff-b27b16759fae0fb0d94cc6e00107c8efR401

check if categories are present or not: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0c26bcfd56ba1276613596e37b34eacdb5b7eb25#diff-b27b16759fae0fb0d94cc6e00107c8efR370

Use ampforwp_get_the_ID: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0c26bcfd56ba1276613596e37b34eacdb5b7eb25#diff-b27b16759fae0fb0d94cc6e00107c8efR368

**Comment by MARQAS** [comment]
Don't use `is_plugin_active`, Use `class_exists or function_exists` to check the availability of the plugin.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/baca92fb59c800452f3ca952e7acdcdfbf91c7fb#diff-b27b16759fae0fb0d94cc6e00107c8efR396
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/baca92fb59c800452f3ca952e7acdcdfbf91c7fb#diff-b27b16759fae0fb0d94cc6e00107c8efR424

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
