### ISSUE TITLE
Amp Cache 1.7 breaks Menu save (WPML conflict)

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3282]
When trying to save a menu (from the Wordpress menu) gives an Apache error (Note that If you disable the plugin it does not happen anymore, same as if you disable "WPML string translation" plugin -but in this case you cannot add menus in other languages):

"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log."

Apache Error log:
"[Mon Jun 03 17:38:22.782313 2019] [fcgid:warn] [pid 32498] [client 90.169.74.65:10362] mod_fcgid: read data timeout in 41 seconds, referer: https://www.nexustraductions.com/wp-admin/nav-menus.php
[Mon Jun 03 17:38:22.782338 2019] [core:error] [pid 32498] [client 90.169.74.65:10362] End of script output before headers: nav-menus.php, referer: https://www.nexustraductions.com/wp-admin/nav-menus.php
[Mon Jun 03 17:38:34.547935 2019] [fcgid:warn] [pid 32504] (32)Broken pipe: [client 54.38.122.253:34004] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: https://www.google.com/"

**Comment by MohammedKaludi** [comment]
Thank you for raising the ticket, I will assign this to the concern person

**Comment by ahmedkaludi** [comment]
@MohammedKaludi Don't you think it's better if we look at this with FTP and WP and properly debug it?

**Comment by olddoc** [comment]
You've got all accesses, the web is a stage copy of my main, feel free to
torture it as you like, I can have it back in minutes if you break it ;)
By the way our wpml license is for unlimited sites, if you want one to test
on your side just tell me the name of the domain you want it for and I'll
set it up for you...


Regards

Carlos Derqui

**Comment by ahmedkaludi** [comment]
We are working on the support system. For now, we will keep the ticket closed from here.
