### ISSUE TITLE
Originally Block quoted text doesn't show up quoted in amp

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3283]
Originally quoted text doesn't show quoted in the amp version. That is the text or paragraph which is quoted using the 'Blockquote' in WordPress classic editor, doesn't show up in amp for any post, it just shows as normal text!
Example URL: https://omnitos.com/news/2019/06/04/leaked-spider-man-far-from-home-post-credit-scene-breakdown/
Amp version: https://omnitos.com/news/2019/06/04/leaked-spider-man-far-from-home-post-credit-scene-breakdown/amp/

**Comment by MohammedKaludi** [comment]
It is related with the styling issue with AMP Layouts.
I have created the ticket in proper department and notified to them. They will get back to you.
https://trello.com/b/7sqqvELu/extension-execution-milestone-ssse

**Comment by Omnitos** [comment]
Trello says not found!

**Comment by MohammedKaludi** [comment]
> Trello says not found!
It is a private board, thats why. 
Please be assured your issue has been noted and it will be resolved very soon.
