### ISSUE TITLE
Elementor stops working when AMP Take Over is enabled

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3284]
Screenshot: https://monosnap.com/file/S66eUj2zHl3B47sQ5d9ZOY8rQMNkID

Elementor stops working when the AMP Takeover is enabled with users settings. When Amp Take Over is off it is working properly. We need to find out the issue from the given settings file.

The user's settings file is available in Mazazine3 Telegram group.

Help Scout Link: https://secure.helpscout.net/conversation/863345581/68672?folderId=2770545

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
