### ISSUE TITLE
Issue with rank math,index should be same in both AMP and in Non-AMP in custom front page

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3285]
Des: Issue with rank math, the index should be same in both AMP and in Non-AMP in the custom front page

Ref: https://secure.helpscout.net/conversation/857663247/67968/

The below settings file is the rank math settings file at the user end, the issue is created in the local also.

[rank-math-settings-2019-06-04-08-12-18.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3251330/rank-math-settings-2019-06-04-08-12-18.txt)

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 0.9.97.58

**Comment by pegazee** [comment]
As I've discussed this ticket scenario with @MohammedKaludi and decided to close this ticket.
