### ISSUE TITLE
On twitter share Via twitter handle name is not shown in the tweet beside Url in the swift design.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3286]
On twitter share Via twitter handle name is not shown in the tweet beside Url in the swift design.
Ref: https://secure.helpscout.net/conversation/866798708/69156?folderId=2322649

**Comment by MohammedKaludi** [comment]
What if the option is turned off, then `&via` will still be present in the url

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/74cd1eb5110482ad267665e481e736fa939c23a6#diff-7d3a92ac5e6165548bf9bc556f4f887aR288

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
