### ISSUE TITLE
To many redirection issue with hidden post in IOS

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3287]
When enabling automatic mobile redirection and clicking from an AMP post to a post that is hidden/does not have an amp version, iOS responds "Too many redirections". It seems to go into an endless loop.

Steps to recreate:
 Using a mobile device, go into this article http://staging.flashpacker-travelguide.de/indien-reise- tipps-erfahrung/amp/ and click on internal the text link "keine Gebühren beim Abheben bezahlen" within the post to reproduce.

Login credentials are available in the helpscout link:
https://secure.helpscout.net/conversation/818906292/62300?folderId=2770545

**Comment by MARQAS** [comment]
Use proper meta values in Beta.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
But only merge the first commit, consult me or Razzak while merging.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
