### ISSUE TITLE
Featured image caption not working properly with font awesome 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3288]
Screenshot: https://monosnap.com/file/361qHo8GgArnIvyxo2NA7VIBqTfw0X
It should be like
Screenshot: https://monosnap.com/file/X76eqWYklBsDODnlwM5VdwtvgBlGRa

HelpScout Link: https://secure.helpscout.net/conversation/818906292/62300?folderId=2770545

Screenshot: https://monosnap.com/file/u8uafpu6mZ2nxdjxzC3JF1E7auaOzq

**Comment by RajuJeelaga** [comment]
Featured image caption icon problem is coming only in Master, In Beta it is working fine,
So after discussion with @MohammedKaludi i added the solution for this ticket in Master

**Comment by ahmedkaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ticket pushed in 0.9.97.62
