### ISSUE TITLE
Gravity Forms plugin

### ISSUE THREAD

**Issue by paulkirspuu** [ahmedkaludi/accelerated-mobile-pages#3289]
Hey

I'm getting `One or more fields have an error. Please enter required fields and try again.` error on every submit, with any form setup.

I am using Automattic AMP plugin, but this shouldn't matter as you have stated in plugin page: `This extension does not require the dependency of AMPforWP plugin, meaning you can use it with any AMP plugin in the world.`.

If I deactivate your plugin, form submits but no success message gets displayed so I would rather use your plugin. Can you give a diagnose what might be the issue?

**Comment by ahmedkaludi** [comment]
@paulkirspuu That must be because of a bug, I would recommend you to create a ticket in https://ampforwp.com/support/ - Our extension team will help you fix this issuel
