### ISSUE TITLE
Yoast Meta Description not being picked up

### ISSUE THREAD

**Issue by vagu71** [ahmedkaludi/accelerated-mobile-pages#3290]
Similar drill as https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3207. Will need to have a fallback to 

`$desc = trim( WPSEO_Meta::get_value( 'twitter-description', $page_id ) );`

and

`$desc = trim( WPSEO_Meta::get_value( 'opengraph-description', $page_id ) );`

**Comment by vagu71** [comment]
Current Code: 
`
function ampforwp_yoast_social_desc($type) {
	if(ampforwp_is_front_page() || ampforwp_is_blog()){
		$desc = $page_id = '';
		if ( ampforwp_is_front_page() ) {
			$page_id = ampforwp_get_frontpage_id();
		}
		if ( ampforwp_is_blog() ){
			$page_id = ampforwp_get_blog_details('id');
		}
		if ( 'og' == $type ) {
			$desc = trim( WPSEO_Meta::get_value( 'opengraph-description', $page_id ) );
		}
		if ( 'twitter' == $type ) {
			$desc = trim( WPSEO_Meta::get_value( 'twitter-description', $page_id ) );
		}
		if (empty($desc)){
			$desc = wp_trim_words(get_post_field('post_content', $page_id), 26);
		}
		return esc_attr($desc);			
	}	
	return  esc_attr( get_bloginfo( 'description' ) );
}
`

New code that solves the issue: 
`function ampforwp_yoast_social_desc($type) {
	if(ampforwp_is_front_page() || ampforwp_is_blog()){
		$desc = $page_id = '';
		if ( ampforwp_is_front_page() ) {
			$page_id = ampforwp_get_frontpage_id();
		}
		if ( ampforwp_is_blog() ){
			$page_id = ampforwp_get_blog_details('id');
		}
		if ( 'og' == $type ) {
			$desc = trim( WPSEO_Meta::get_value( 'opengraph-description', $page_id ) );
		}
		if ( 'twitter' == $type ) {
			$desc = trim( WPSEO_Meta::get_value( 'twitter-description', $page_id ) );
		}
		if (empty($desc) ){
			$desc = get_post_meta($page_id, '_yoast_wpseo_metadesc', true);
		}
		if (empty($desc)){
			$desc = wp_trim_words(get_post_field('post_content', $page_id), 26);
		}
		return esc_attr($desc);			
	}	
	return  esc_attr( get_bloginfo( 'description' ) );
}`

**Comment by Omnitos** [comment]
same issue

**Comment by MohammedKaludi** [comment]
Will be pushed in next update that is scheduled for next friday.

**Comment by MohammedKaludi** [comment]
👍 ready to mereg.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
