### ISSUE TITLE
Polylang for AMP - Frontpage content is removed in other languages 

### ISSUE THREAD

**Issue by mendor** [ahmedkaludi/accelerated-mobile-pages#3291]
I have three languages on my website. I bought Polylang for AMP extension. 
I created a layout in AMP builder for one (1), then the other (2), saved and on the first page (1) disappeared all content in AMP Builder. 
No matter how many times I'm trying to add content it is removed in other languages
[https://pasteboard.co/Ii8G4it.png](url)

**Comment by ahmedkaludi** [comment]
@mendor We have a special team for premium customers like you. Please write to us directly via https://ampforwp.com/support and we will help you immediately. 

This channel is for the bugs, so I'll close this one for now.
