### ISSUE TITLE
When AMP takeover and  yoast seo is activated,AMP page builder is not working

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3292]
https://secure.helpscout.net/conversation/843373281/64521?folderId=2632028

Des: When AMP takeover and  Yoast SEO is activated, the AMP page builder is not working

To reoccur the issue:
1.AMP takeover should be enable
2. Yoast SEO should be activate
3.
<script type="text/javascript">
var script=document.createElement("script");
var prefix=document.location.protocol;
script.async=true;script.type="text/javascript";
var target=prefix + "//app.clixtell.com/scripts/latest.js";
script.src=target;var elem=document.head;
elem.appendChild(script);
</script>

Put the above code in the code module

**Comment by MohammedKaludi** [comment]
👍

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
