### ISSUE TITLE
Internal Links redirecting to AMP version Even after AMP is disabled on POSTS and PAGES

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3295]
Screenshot:https://monosnap.com/file/GDPpUsTdvV0VIemmR2tcYEKzRRt5ju
https://monosnap.com/file/Y2ICiussCb8CqLZPuXjeeby0YcpYmL
Screenshot: https://monosnap.com/file/vTPBISDPClTuxIkmYS2aFXO7PqqWpy

Help Scout Link: https://secure.helpscout.net/conversation/870575058/69633?folderId=2770545

**Comment by ahmedkaludi** [comment]
we are closing this ticket until we have full clarity on this.
