### ISSUE TITLE
ampforwp_new_gallery_images called multiple times resulting  Fatal Error 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3296]
Hi, since one of the latest updates, if you have revslider and slide anything on the same page, the AMP page throws a fatal anything. Google Search Console has been flagging these as server errors.

The error is inclass-ampforwp-slide-anything-embed.php + class-ampforwp-rev-slider.php

And it has to do with the functions have been declared twice in the files.ampforwp_new_gallery_images and ampforwp_new_thumbnail_images

If we roll back the versions, or add the if function_exists to one of the sets, it works.Just FYI if someone could look into this and fix in new versions.
--
This function is being created 4 times. Need to improve it ASAP.
https://take.ms/Eo6rr
https://secure.helpscout.net/conversation/869268706/69506/

**Comment by ajeetku** [comment]
What about class-ampforwp-rev-slider.php implementation

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
