### ISSUE TITLE
Need to create a filter to add the classes which have to be excluded in infinity scroll.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3297]
Desc: Need to create a filter to add the classes which have to be excluded in infinity scroll.

**Comment by ajeetku** [comment]
Before put inside `json_encode` add some check `is_array()`

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
