### ISSUE TITLE
Need to create an option for Leverage Browser Caching in the performance settings.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3298]
Need to create an option for Leverage Browser Caching in the performance settings.

**Comment by MohammedKaludi** [comment]
Need code improvements, consult  me before starting the work.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
