### ISSUE TITLE
Design Bug in Swift Theme

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#3299]
Hello, for some reason the “X” which you click on to close the menu, appears only on pages, but not in single post, making users to click on the side of the screen which doesn’t help either. 

I’ve checked it and the “X” is functional, it does close the menu but it won’t show up like on pages. Hopefully this will get resolved soon.
![52BA83EB-717F-4BED-A775-317B934452F3](https://user-images.githubusercontent.com/40724154/59148388-2026c680-8a11-11e9-80c3-cc2c8c877d48.jpeg)
![20E7692C-CD28-4383-991C-DAA768AD2AC4](https://user-images.githubusercontent.com/40724154/59148389-2026c680-8a11-11e9-9420-ee0c75694f89.jpeg)

**Comment by ahmedkaludi** [comment]
Can you share the URL which is shown in the screenshot?

**Comment by SageFargo** [comment]
@ahmedkaludi I assume this only happens in iOS Safari browser, because on

**Comment by SageFargo** [comment]
@ahmedkaludi visit fargo1ife.com then try and press the menu you’ll see the “X” on the right side, but if you try this in-post you won’t see it there but it’ll still function.
