### ISSUE TITLE
Change static amp to AMP_QUERY_VAR 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#330]
Change static amp to AMP_QUERY_VAR 

http://take.ms/gPhKY

**Comment by khaledMohammed000** [comment]
This is not a good idea.....we have few debug issues because our code cant identify AMP_QUERY_VAR at places

**Comment by ahmedkaludi** [comment]
This was already done. We are closing this to stay focused
