### ISSUE TITLE
No ads.txt found

### ISSUE THREAD

**Issue by gabu69** [ahmedkaludi/accelerated-mobile-pages#3300]
While checking Google Ad Manager, found this on my ads.txt management (https://admanager.google.com/XXXXXXXXXXXXX#admin/adstxt)

ampproject.org
No ads.txt found
FIX

No ads.txt found
No ads.txt file was found when the domain was last crawled. Learn more about how ads.txt files can be crawled.

Should this be part of the plugin?

**Comment by ahmedkaludi** [comment]
We will be adding Ads.txt support in Ads for WP: https://wordpress.org/plugins/ads-for-wp/

Here's a feature request for it: https://github.com/ahmedkaludi/ads-for-wp/issues/198
