### ISSUE TITLE
Enable multi-size ad requests on your AMP inventory to increase ad auction pressure and drive revenue.

### ISSUE THREAD

**Issue by gabu69** [ahmedkaludi/accelerated-mobile-pages#3301]
Have *Advanced Ads AMP* but I cant find a multi site option for each of my ads. And per 
https://amp.dev/documentation/guides-and-tutorials/develop/monetization/

One of the best practices to increased bidding is:
[Enable multi-size ad requests](https://github.com/ampproject/amphtml/blob/master/ads/README.md#support-for-multi-size-ad-requests) on your AMP inventory to increase ad auction pressure and drive revenue.

Could this feature be taken into account, it´s really important for users who monetize with ads their site

**Comment by ahmedkaludi** [comment]
Sure, we will add this in the Advanced AMP Ads and Ads for WP.

**Advanced AMP Ads** - The ticket for this is in a private issue tracker board
**Ads for WP** - the request for that is in https://github.com/ahmedkaludi/ads-for-wp/issues/199
