### ISSUE TITLE
Center ads when using Advanced ADS AMP

### ISSUE THREAD

**Issue by gabu69** [ahmedkaludi/accelerated-mobile-pages#3302]
If you have 300x250 or 336x250 ads while using some layouts and Advanced ADS amp 

The padding of <div class="cntr"> makes the ad start from the left padding position, so in some mobiles it will look like its aligned to the right or will not be centered.

Best solution is in CSS to add:
`    .amp-ad-wrapper {
    	display: block;
    	position: relative;
    	width: 100vw;
    	left: calc(-50vw + 50%);
    }
    .ampforwp-incontent-doubleclick-incontent {
        display: block;
        margin: 0 auto!important;
    }`

Only problem is many people dont notice or know how achieve this. 

this would be a good function aside of having to add it manually in the Customs CSS

**Comment by ahmedkaludi** [comment]
@gabu69  Can you share the URL where it doesn't go in the center? so that I can make a proper bug report of this?

**Comment by ahmedkaludi** [comment]
please create a new request on https://ampforwp.com/support/ 

We will close this ticket for now.
