### ISSUE TITLE
Gallery with GIF is not working

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3304]
The issue is: https://wordpress.org/support/topic/gallery-is-not-displaying-images-gif/

**Comment by MohammedKaludi** [comment]
Need to make sure that gallery code is working as expected in other designs as well.

And Update the Vendor Change log as well.

**Comment by MohammedKaludi** [comment]
Warning appears in Gallery:

<b>Warning</b>:  implode(): Invalid arguments passed in <b>/Applications/MAMP/htdocs/wp/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/embeds/class-amp-gallery-embed.php</b> on line <b>264</b><br />

**Comment by MohammedKaludi** [comment]
Warning coming in master, need to make sure it is fixed while mergeing.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
