### ISSUE TITLE
Sticky sidebar / Sticky bottom or sticky bar

### ISSUE THREAD

**Issue by joyloan** [ahmedkaludi/accelerated-mobile-pages#3305]
Can you add a sticky sidebar, sticky bottom or sticky bar option for higher conversion?

A click on this sidebar will open on screen/modal. 

We can put a quarry form or anything else that can increase conversion.

**Comment by ahmedkaludi** [comment]
We have a call to action feature on https://ampforwp.com/call-to-action/

Is this what you are looking for?

**Comment by joyloan** [comment]
Yes, I am looking something like CTA Bar, Or sidebar (Which sticks to a particular location in the browser throughout the website). 

I want clicking on this CTA will not take the user to a new (landing) page. 

But a click on it will trigger a form modal on this page itself. So user can submit details on this page itself, It will have a better user experience and better conversion.

If you look at your demo page, there is an icon on the bottom, so a user can send interaction to you.

![demo page](https://user-images.githubusercontent.com/36277375/59175208-4c0d8d80-8b72-11e9-832a-23afb6067281.png)

Or is we look at, this page, http://www.loansolution.co.in/index.php . They have a widget on the side. when we click, it brings a quarry form on this page. 

When my website was not on AMP, I had a very clean and better "sticky bottom (plugin)" on the website. In settings, I had a shortcode for my Ninja form. A click on the sticky bar used to bring up the form on this page itself.

**Comment by ahmedkaludi** [comment]
@joyloan Your feedback is great! I have added this as a feature requests and we will release this feature very soon.

for now, you can use the CTA bar instead ( https://ampforwp.com/call-to-action/ ) ?

**Comment by ahmedkaludi** [comment]
Closing this, please communicate further on https://ampforwp.com/support/ - We have a team who helps you with these issues.
