### ISSUE TITLE
Fatal Error - structured-data-functions.php - line 74

### ISSUE THREAD

**Issue by tanujdamani** [ahmedkaludi/accelerated-mobile-pages#3306]
Recent update caused the website to be unusable, including the Admin and Front-end

Fatal error: Can't use function return value in write context in _"BASEURL"_/wp-content/plugins/accelerated-mobile-pages/includes/features/structure-data/structured-data-functions.php_ on line 74

**Comment by ahmedkaludi** [comment]
@tanujdamani Can you send me the WP details on https://ampforwp.com/support/

We will personally debug this one for you

**Comment by tanujdamani** [comment]
@ahmedkaludi appreciate the quick response, but I figure out the issue.
I have updated my PHP version. The crash happened with PHP 5.2, I have updated to 5.6 and the plugin words.
