### ISSUE TITLE
Need to remove error message comes after search  in post or page in Swift theme

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3309]
Ref: https://secure.helpscout.net/conversation/874294018/70074/
Here you see the screenshot: https://monosnap.com/file/mhEJnSkN1ZsRmxxYqluzl9FUyhRicG

**Comment by Rkroy** [comment]
Not working at my end.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
