### ISSUE TITLE
Taxonomy support in AMP Page Builder category module

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3310]
Des: Taxonomy support in AMP Page Builder category module

**Comment by MohammedKaludi** [comment]
Functionality is working as expected, but labelling needs improvement.
https://take.ms/4yNvn

**Comment by MohammedKaludi** [comment]
1. Need to  Capitlize the text from 'post' to 'Post'
2. Need to have the update effect (ajax loading effect something like this: https://take.ms/32rQP) when the value is changing https://take.ms/hocLF

**Comment by MohammedKaludi** [comment]
1. Warning in console  https://take.ms/GDu5z

2. UX of spinner needs improvement.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
