### ISSUE TITLE
Activating Thrive lead plugin AMP Page builder doesn't  work on the custom front page 

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3312]
Steps to recreate the issue in local

1. Activate the thrive lead plugin
2. Setup the custom front page
3. After  enabling AMP  page builder on the custom front page  i cannot get modules that i have created using page builder on custom front page
  
Ref: https://secure.helpscout.net/conversation/874835262/70134?folderId=3004564

 Thrive lead plugin is available in Magazine3 Telegram group.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
