### ISSUE TITLE
Problem with pagination links in AMP

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3313]
Des: Problem with pagination links in AMP
https://secure.helpscout.net/conversation/876197405/70318?folderId=2632028

plugin generates:
`<link rel="amphtml" href="https://sportklan.ru/page/12/amp/" />
`
but it should be:
`<link rel="amphtml" href="https://sportklan.ru/amp/page/12/" />`

**Comment by akashagrjsr** [comment]
One more user is facing the same issue

Ref: https://secure.helpscout.net/conversation/869178524/69488?folderId=2770545

**Comment by akashagrjsr** [comment]
One more user is facing the same issue in search console

Ref: https://secure.helpscout.net/conversation/878483762/70609?folderId=2770545

**Comment by Nitesh221194** [comment]
One more user-facing same issue:
(We have wp-admin)

Ref:
https://secure.helpscout.net/conversation/876168406/70314?folderId=2844667

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.58
