### ISSUE TITLE
Show Video instead of feature image when post format is video

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#3317]
When the format of the post is video then the video should be displayed in the place of feature image.

Ref: https://secure.helpscout.net/conversation/872116232/69813?folderId=673457

**Comment by pegazee** [comment]
Post Formats is a theme feature which is built by the theme authors, And here, a user is using the 'Newspaper' theme by tagdiv & we've already added this feature in the 'NewsPaper AMP Theme' extension.
