### ISSUE TITLE
Can’t find the webpage

### ISSUE THREAD

**Issue by Gentleman-s** [ahmedkaludi/accelerated-mobile-pages#3318]
Only the AMP address can’t be found.
When I deactivate the plugin the mobile address is available. 
The AMP shows a blank page:
https://www.gentlemansthinking.com/amp

**Comment by MARQAS** [comment]
Hi @Gentleman-s, Can you contact us through https://ampforwp.com/support, our team will help you to look into this issue?

**Comment by ahmedkaludi** [comment]
@Gentleman-s We are waiting to hear on the SUpport form

**Comment by Gentleman-s** [comment]
I wrote in the support forum. You said to make a bug report.
https://wordpress.org/support/topic/cant-find-the-webpage/#post-11634194

**Comment by ahmedkaludi** [comment]
Yes, we have to debug this further, so please send us the WP details via https://ampforwp.com/support 

Our developers will debug the code and fix the issue for you
