### ISSUE TITLE
Auto Add AMP in Menu URL  option is is not working for the product category

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3319]
Des: Auto Add AMP in Menu URL  option is not working for the product category
Also please check for product pages
https://secure.helpscout.net/conversation/875705582/70244?folderId=2632028

**Comment by ahmedkaludi** [comment]
@MARQAS Sravan is able to re-occur on his end.

**Comment by pegazee** [comment]
When custom taxonomy is enabled then it should add the /amp at the end of the URL for the custom category or tag else it shouldn't.

Please discuss this scenario with @ahmedkaludi & @MohammedKaludi

**Comment by pegazee** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4e2b8b9e9ded5dac69febd972012c5cf5cfe4be8#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R929

**Comment by MohammedKaludi** [comment]
Explained the issue to santosh.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
