### ISSUE TITLE
Need to add wordpress default Gutenburg editor 'Block' settings Compatibility in AMP

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3320]
![gutenburg-editor-settings](https://user-images.githubusercontent.com/40556903/59432695-978b9a00-8e05-11e9-8ab5-54d926517319.png)

**Comment by santosh8793** [comment]
Unwanted Static CSS has been added due to Gutenburg Block editor settings which needs to be reduced by adding tree shaking to remove the unwanted CSS from page or post.

**Comment by santosh8793** [comment]
User is waiting for this feature, need to add this feature as soon as possible

**Comment by pegazee** [comment]
Not working, even tree-shaking option is enabled

**Comment by MohammedKaludi** [comment]
Cache the  data with the transient, calling wp_remote_get on every refresh is not good.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5e837f210490da7c8225cbac3a29dfcab888bd70#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7976

**Comment by MohammedKaludi** [comment]
code improvement required

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7a22e579facf90e79cbedcaf5f511ca6800489d6#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8053

**Comment by MohammedKaludi** [comment]
and escaping and sanitization required.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by sardarui** [comment]
Another user reported this issue.

https://secure.helpscout.net/conversation/1020969034/100429?folderId=3126461

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2

**Comment by Arihantkankariya09** [comment]
Below ticket is related to the same issue where wp-block-editor CSS is loading in latest version 1.0.2 update.
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3994

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.4 Update
