### ISSUE TITLE
Click events of analytics are not working since version 0.9.97.47

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3321]
Click events of analytics are not working since version 0.9.97.47
Ref: https://secure.helpscout.net/conversation/874184506/70068?folderId=2322649

**Comment by Rkroy** [comment]
Steps to be followed.
Add any advanced analytics click events variables eg: "title": "{title}", then the title is not displaying in analytics.
O/p shown: 
![view-source_localhost_wordpress_divi-test_amp_ - Google Chrome 2019-06-14 12 44 44](https://user-images.githubusercontent.com/43204388/59490635-d7ed2580-8ea2-11e9-89d5-36b94b47e87e.png)
O/p to be shown: 
![view-source_localhost_wordpress_divi-test_amp_ - Google Chrome 2019-06-14 12 51 54](https://user-images.githubusercontent.com/43204388/59490903-6e214b80-8ea3-11e9-9aea-1a0855cbce51.png)

**Comment by MohammedKaludi** [comment]
Fixed in #3281 
For more information contact me and santosh
