### ISSUE TITLE
AMP page builder is not showing when the AMPforWP plugin is activated from Network admin panel in Multisite

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3322]
Des: AMP page builder is not showing when the AMPforWP plugin is activated from Network admin panel in Multisite.

Issue recreated in local.

Steps to recreate.
1. Deactivate the AMPforwp plugin in the Network Admin Panel

2. Make it activate in the website's Dashboard panel

3. Click the new post or page and in it, AMP page builder will find.

4.Activate the AMPforwp plugin in the Network Admin Panel

5. Click the new post or page and in it, AMP page builder will not find when the core plugin is activated from the Network Admin Panel

**Comment by Rkroy** [comment]
AMP page builder is showing but it is not functioning, when we click on the builder to add modules, getting an error as "connection not establish", the error is on both post/page editor, please check.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
