### ISSUE TITLE
Need to improve the redirection code(saw repeated code in master)

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3326]
Need to debug repeated code ( at line no. 33 and 291)
Reference Ticket URL : https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2940
![repeated-code-mobile-redirect](https://user-images.githubusercontent.com/40556903/59516611-92b2fe80-8e76-11e9-9e56-4b3ac393d169.png)

**Comment by MohammedKaludi** [comment]
Ready to remove.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
