### ISSUE TITLE
Add this should be default.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3327]
Ref: https://secure.helpscout.net/conversation/834276860/63795?folderId=2770543

**Comment by MohammedKaludi** [comment]
1. Default should be after post 
2. position of the control should be below the social settings.

**Comment by Zabi09** [comment]
Need Escaping

**Comment by MohammedKaludi** [comment]
READY to merge,

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
