### ISSUE TITLE
Plugins manager showing twice in options panel

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3328]
Plugins manager showing twice in options panel

https://monosnap.com/file/aqCSErirml0ApPmz98SH6nINOz3aBn

**Comment by MARQAS** [comment]
Don't remove the option, check for the plugin.

**Comment by MARQAS** [comment]
Escaping is required: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/62037839df32737b08de34fe7a1bed88eb857f3b#diff-260eba6333c3222e59a6aed22ac5ab37R7422

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
