### ISSUE TITLE
Post/page throwing an error on hiding AMP for that particular post/page if AMP takeover option is enabled.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3329]
Post/page throwing an error on hiding AMP for that particular post/page if AMP takeover option is enabled. 
Ref: https://secure.helpscout.net/conversation/878180151/70552?folderId=2322649

**Comment by pegazee** [comment]
try to use "ampforwp-post-metas" and then called the 'ampforwp-amp-on-off' meta from that array

**Comment by MohammedKaludi** [comment]
> try to use "ampforwp-post-metas" and then called the 'ampforwp-amp-on-off' meta from that array

`ampforwp-post-metas` is only in Beta, so need to make sure the code is added according to Current Master.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.59
