### ISSUE TITLE
Mobile redirect bug with pages

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#333]
Shukhrat Namanov:
it's page

when page redirected, in url twice add  amp/amp/  to URL.

https:\\example\category\page redirect to->  https:\\example\category\pageamp\amp\

**Comment by MohammedKaludi** [comment]
Fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8d0fd28b55a71ddd2a596ede3df5c0ee0a008686

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c3f961179957dd69156caadc665771adfbcd95b0
