### ISSUE TITLE
Error 500 - PHP 5.3.3 Fallback support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3333]
I’m using PHP v.5.3.3 and when I tried to activate the AMP module all the WordPress site went down with a weird 500 error. I managed to fix it changing some lines from the file /accelerated-mobile-pages/includes/features/structure-data/structured-data-functions.php

line 16:
FROM
if (! empty( ampforwp_get_setting(‘amp-structured-data-logo’,’url’) ) ) {
TO
$aux_res = ampforwp_get_setting(‘amp-structured-data-logo’,’url’);
if (! empty( $aux_res ) ) {

line 74:
FROM
if (! empty( ampforwp_get_setting(‘amp-structured-data-placeholder-image’,’url’) ) ) {
TO
$aux_res = ampforwp_get_setting(‘amp-structured-data-placeholder-image’,’url’);
if (! empty($aux_res ) ) {

line 166:
FROM
if (! empty( ampforwp_get_setting(‘amp-structured-data-placeholder-image’,’url’) ) ) {
TO
$aux_res = ampforwp_get_setting(‘amp-structured-data-placeholder-image’,’url’);
if (! empty( $aux_res ) ) {

line 166:
FROM
if (! empty( ampforwp_get_setting(‘amporwp-structured-data-video-thumb-url’,’url’) ) ) {
TO
$aux_res = ampforwp_get_setting(‘amporwp-structured-data-video-thumb-url’,’url’);
if ( ! empty( $aux_res ) ) {

REF: https://wordpress.org/support/topic/error-500-for-php-5-3-3/

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
