### ISSUE TITLE
Dynamically change accordion-mod class name

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3334]
Ref: https://secure.helpscout.net/conversation/878492343/70611?folderId=2770543
here you see the screenshot: https://monosnap.com/file/dL8BvR6o8HcBTcjNR7JAPqruFSwPCu

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
