### ISSUE TITLE
Separator Character's of Rank math plugin is not working on AMP pages.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3335]
Separator Character's of Rank math plugin is not working on AMP pages. 
Ref: https://secure.helpscout.net/conversation/881467578/71025?folderId=2322649
![SEO Titles   Meta ‹ wordpress — WordPress - Google Chrome 2019-06-18 16 54 25](https://user-images.githubusercontent.com/43204388/59678388-eb252b80-91e9-11e9-93e1-e6756d98c800.png)

**Comment by MARQAS** [comment]
It is also not working for Yoast.
But only when the default WordPress title is used.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
