### ISSUE TITLE
Performance improvement ! SELECT SQL_CALC_FOUND_ROWS

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3336]
Ref: https://wpartisan.me/tutorials/wordpress-database-queries-speed-sql_calc_found_rows
https://core.trac.wordpress.org/ticket/41278

[SELECT SQL Found rows file.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3301579/SELECT.SQL.Found.rows.file.txt)
SELECT SQL Found rows file.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3301575/SELECT.SQL.Found.rows.file.txt)

**Comment by MARQAS** [comment]
Added in master

**Comment by MohammedKaludi** [comment]
ready and code looks good.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
