### ISSUE TITLE
ALL Yoast SEO Data should load in AMP source code as it is loading in non AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3338]
Screenshot: 

https://monosnap.com/file/H7LplePi9htKeYvHkzhc8IoGMcq2be

https://monosnap.com/file/06UB6DNdo9osd28H2v3R3dMlmZSe96

Helpscout Link: https://secure.helpscout.net/conversation/876733579/70399?folderId=2770545

**Comment by MohammedKaludi** [comment]
👍 ready to merge, consult me before merging.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
