### ISSUE TITLE
Create an option to change featured image size in the single settings.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3339]
Create an option to change featured image width and height in single settings so users can change image size as per their requirement.
Ref: https://secure.helpscout.net/conversation/882174191/71090?folderId=2322649

**Comment by MARQAS** [comment]
What about srcset? Please discuss with @ahmedkaludi

**Comment by MohammedKaludi** [comment]
srcset should only apply for when Full is selected. and it should not apply for other sizes.

**Comment by MohammedKaludi** [comment]
- [ ] default should be full with src set

- [ ] other sizes should be normal without the srcset

**Comment by MohammedKaludi** [comment]
Some code improvements required.

**Comment by pegazee** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3e463a83b7ef552cac8a60396ba629a93873386f
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b6466ab3d8c5a8f28f0d463428a01a99d5b2be9d

Above commits are related to this ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3384

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
