### ISSUE TITLE
HTML in Archive Title 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#334]
HTML in Archive Title http://take.ms/RUAk2

**Comment by pppdog** [comment]
Hi..
At this time, I've disabled accelerated mobile pages
Please see the diagram[ link ](https://wp.moneytw.com/wp-content/imgs/wp-amp.png)

One of my sites is https://pppdog.me
Zeng pppdog

**Comment by pppdog** [comment]
iHi
I opened the plugin
The problem has been solved
So perfect!!
 https://pppdog.me/amp
About ld + json
Custom ld + json (not using yosat seo community function)
How should I use it correctly?

**Comment by ahmedkaludi** [comment]
Hey @pppdog Can you please let me know if this was fixed for you?

**Comment by khaledMohammed000** [comment]
Hey @pppdog 
**Custom ld + json (not using yosat seo community function)**
regarding this we will have structured data support soon
