### ISSUE TITLE
One signal push notification should work properly on AMP if any CDN plugin is used.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3340]
One signal push notification should work properly on AMP if any CDN plugin is used.
Eg: Below is the scenario where the user is using BunnyCDN plugin on the site mysite.com,
so here if we change the Domain Name to static.mysite.com then the push notification does not work.
Ref: https://secure.helpscout.net/conversation/871155602/69720?folderId=2322649

**Comment by MARQAS** [comment]
Try to wrap it in one of the existing `pre_amp_render_post` 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b3e7efa6ffd0a68c4d26c5e0525c9a36f08ef18d#diff-6aa5512f7dd8d5ce60fc97b0f340912cR2295

**Comment by MohammedKaludi** [comment]
Add a check for a if a plugin function/class is exists
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/71a403d9b608929e3b4f7eb26addeefa0573e2fe

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to push,

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
