### ISSUE TITLE
Improper amphtml on HomePage when WPML is activate

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#3341]
When we select the "Language URL format" as type-1 from the WPML settings, amphtml is generating non-amp URL.

Ref: https://vivanti.ca/

**Comment by MohammedKaludi** [comment]
the above code is pushed 0.9.97.59 but need to update the code as discussed.

**Comment by MohammedKaludi** [comment]
incorrect condition
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b6ebabff9640e86b037c9162a586f7aa7581e248#diff-04b38a94ddf918855eed7a68ecaa512dR725

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
