### ISSUE TITLE
Spanish lang. does not showing "Design" tab

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3342]
Ref:
https://secure.helpscout.net/conversation/878659838/70648?folderId=2844667

Screenshot:
http://take.ms/C8i2A

**Comment by pegazee** [comment]
The issue has occurred on the user end. I've tried to re-create the issue on the local server but it's not created  & everything is working perfectly.

**Comment by ahmedkaludi** [comment]
It's reoccurring on my localhost

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
