### ISSUE TITLE
When AMP Comments is disabled then its div should not load

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3345]
When AMP Comments is off then its .cmts and .sp-lt class is loading in CSS which cause unnecessary spacing. 

Screenshot: https://monosnap.com/file/dIPAN7Gd3QFpuoz9a7I5czu9yGZnJU

HelpScout Link: https://secure.helpscout.net/conversation/851510401/65822?folderId=2770545

**Comment by MARQAS** [comment]
I disabled the comments option and everything got disabled it seems: https://monosnap.com/file/cRk7Z2A8lI248gpiPJKV5cJDnK5m5J

**Comment by MARQAS** [comment]
It was my mistake, it is working fine now

**Comment by pegazee** [comment]
By mistake, I've committed the code of another ticket. I've also reverted it back, Please ignore my commit.

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
