### ISSUE TITLE
Tittle attribute not generates  in related posts and also add tittle attribute in every post

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3346]
https://secure.helpscout.net/conversation/879827610/70778?folderId=2770543

**Comment by pegazee** [comment]
In Swift theme, on the recent post, not working. Please discuss this once with @ahmedkaludi

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
