### ISSUE TITLE
We need to add Flipboard as a social sharing option in AMP

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3348]
Ref:
https://secure.helpscout.net/conversation/862813311/68603/

**Comment by MARQAS** [comment]
Escaping for the title?

**Comment by Rkroy** [comment]
In swift design, the flipboard share is not showing in the social icons section, please check screenshot.
![Bill gates _ wordpress - Google Chrome 2019-07-10 13 15 54](https://user-images.githubusercontent.com/43204388/60950610-185e8880-a315-11e9-8c05-4f6c4b67f8e5.png)

**Comment by MohammedKaludi** [comment]
Icon not centered also the container is also not round in D3
https://take.ms/RzlH0

**Comment by MohammedKaludi** [comment]
Position of icon is not correct in D1 
https://take.ms/Na4Sw

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
