### ISSUE TITLE
Single post main title should be H1 and sub title should be H2 or H3 in design-1

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3350]
Ref:https://secure.helpscout.net/conversation/882175727/71091?folderId=2770543
Here you see the screenshot regarding this : 
1.https://monosnap.com/file/3ldXCUFCNlDTChuOTIDO22XuztEEb4

**Comment by MohammedKaludi** [comment]
Custom Frontpages in Design 2 and 3 also has  this issue, need to make sure the styling is looking exact.

**Comment by MohammedKaludi** [comment]
Why changes done in single's styling??

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e6230a482b5ec662705781331aa869741fb6eabb

**Comment by Zabi09** [comment]
We are adding some CSS like " h2.amp-wp-title " and if we changed the h2 to h3 then the CSS was not appearing to those headings that's the reason I made changes.

**Comment by MohammedKaludi** [comment]
Fonts are different. https://take.ms/SiOhu

But i'm not able to understand is that why you reduced the fontsize from 20 to 17? https://take.ms/EFgTt

**Comment by MohammedKaludi** [comment]
Same styling issue for design 3 as well

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
