### ISSUE TITLE
Indexing issues with custom front page and pagination

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3352]
Desc: When the static page is set without pagination and custom front page in amp then we should load page2 content in amp if it is loading in non-amp with default WordPress loop. 

Ref: https://secure.helpscout.net/conversation/880886332/70930/

Page/2 pagination is not there

https://www.watanserb.com/amp/

Like this https://www.watanserb.com/amp/page/2372
https://monosnap.com/file/c2LtlUyhRrK7uj3ADTe18TAUXizLTR

**Comment by MARQAS** [comment]
He is creating the Non-AMP frontpage with WP-Bakery and AMP's frontpage with category module of AMP  Pagebuilder.
This is the reason the AMP frontpage is unable to get the content of paginated content of Non-AMP.

**Comment by syedimran22** [comment]
https://trello.com/c/sHrnemkf/783-in-amp-layout-homepage-doesnt-have-the-pagination

**Comment by MohammedKaludi** [comment]
This ticket is not relevant now.
