### ISSUE TITLE
Page is not working if the page name is the same as the site name.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3353]
The page is not working if the page name is the same as the site name.
Eg Url: https://vietnamrehberi.com/vietnam/
Ref: https://secure.helpscout.net/conversation/884386962/71354?folderId=2322649

**Comment by ahmedkaludi** [comment]
Closed this ticket until we have some data on this.

**Comment by MARQAS** [comment]
I tested the same but it is working on my end, maybe it is conflicting with some other thing?
