### ISSUE TITLE
Comment Not Working and View Non-AMP Link

### ISSUE THREAD

**Issue by Taran0007** [ahmedkaludi/accelerated-mobile-pages#3354]
From past 2 Months i am Experiencing few Issues. 
1. Comment Button Doesn't Work.
2. View Non-AMP Version Not Working.
-------------------
**1 ISSUE** -  I am using default WordPress Comment Option and i am able to see comments but whenever me or anyone click on "Comment" under every post it just reload the page and nothing happens.
**2 ISSUE** - Recently i activated PWA Option via AMP for WP Plugin. I deleted it instantly and from that day whenever i click on **view non amp version**. I am keep Getting Redirected to same page as AMP Version. 
**3 ISSUE** - I Added an Subscribe Widget in AMP footer and it Loads as it should but when i add email and click on subscribe button nothing happens. (This Issue is not very big)

My Website's  Link is - [CLICK HERE](https://www.real-tips.xyz) 

Hope These Issues would be fixed.

**Comment by ahmedkaludi** [comment]
Both issues are connected with the session breaking problem of Mobile redirection. 

Can you tell me if you are using LiteSpeed, if yes, then how have you implemented it (On the DNS level)?

**Comment by Taran0007** [comment]
Yes i am Using Litespeed Server, If you are asking How i connected domain to hosting it was easy my hosting company did it.. i think it's CNAME. Also, i am using Cloudflare. I Am not much clear about implementation.

**Comment by ahmedkaludi** [comment]
In the Litespeed Server, do they have any Mobile caching option?

**Comment by Taran0007** [comment]
Not on my watch. I didn't see any of this option in my cpanel. Also, i use W3 total cache Plugin. Can You please Take a look? Let me Know Which Details you need and little info where that detail should be. I will Send You Screenshots or i can share Cpanel Details if required.

**Comment by Zabi09** [comment]
@Taran0007 
1 ISSUE - I have checked your website and found that you are using Disqus comments in the non-amp version and due to that only it is not redirecting to the proper non-amp comment link, So I recommend you to use Disqus in AMP also
2 ISSUE - I have checked your website and found that the "view non-amp" is properly redirecting to non-amp version and we have also improved the code of it in #3269 (which you already know) and that will be pushed in 0.9.97.61
3 ISSUE - Have you removed the Subscribe Widget in AMP footer? I have checked and found only the text widget in footer.

**Comment by Taran0007** [comment]
Thanks, Comment Issue is Resolved, I Think That was Fault of Rocket Lazy Load and i Didn't Enable that Option of Host API. 
----------
Now New Issue is i tried Advanced Header Design Option. at First it worked as it should. But Now When i disabled it and also cleared cache data the colors and settings remain same (Only on Homepage). I Try Re-enabling it and no luck for homepage but on other pages it works fine. (This is a Bug Report)

**Comment by Zabi09** [comment]
@Taran0007 
Happy to hear that your issues are fixed and if you find any new bugs then you can contact us directly on https://ampforwp.com/support/ and our team will help you in fixing all your issues.
