### ISSUE TITLE
Need to change the hook to work minify option in amp cache.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3355]
Desc: Need to change the hook of ampforwp_the_content_filter_full function to work minify option in amp cache.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
