### ISSUE TITLE
Anchor links found in my body get placed at the top of the html document

### ISSUE THREAD

**Issue by jeremymoore** [ahmedkaludi/accelerated-mobile-pages#3356]
When my content includes a link like `<a href="#some-anchor-tag">Click Me</a>`, the value of the href `#some-anchor-tag` appears at the very top of the document. 

<img width="256" alt="Screen Shot 2019-06-22 at 12 50 34 PM" src="https://user-images.githubusercontent.com/1245814/59967260-36428580-94ed-11e9-9913-79a0ba6bc3d0.png">

**Comment by ahmedkaludi** [comment]
That's really strange, 

Are you able to re-create this issue on your localhost?
can you share the URL where it's occuring?

**Comment by jeremymoore** [comment]
@ahmedkaludi here's an example on a staging site: healthmarkets.staging.wpengine.com/resources/medicare/help-with-medicare-premiums/?amp=1

You'll find the word `#income` at the top of the page.

**Comment by ahmedkaludi** [comment]
@jeremymoore This is extremely strange, Can you please share the credentials of that staging environment via https://ampforwp.com/support/ ?

I will personally help you fix this.

**Comment by jeremymoore** [comment]
Perfect, just opened a ticket.

**Comment by jeremymoore** [comment]
I sorted this out... ended up being a recent addition to our main theme with a bug in a `the_content` filter.
