### ISSUE TITLE
Template mode improvements

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3357]
- [x] need to have this

`/* Disable WordPress Admin Bar for all users but admins. */
show_admin_bar(false);
add_filter('style_loader_tag', 'codeless_remove_type_attr', 10, 2);
add_filter('script_loader_tag', 'codeless_remove_type_attr', 10, 2);

function codeless_remove_type_attr($tag, $handle) {
    return preg_replace( "/type=['\"]text\/(javascript|css)['\"]/", '', $tag );
}`

- [ ] extra scripts are loading

- [x] https issue in search

**Comment by ahmedkaludi** [comment]
Get my help, because the reference is in my pc

**Comment by ahmedkaludi** [comment]
- [ ] if we insert add_theme_support, and use it, the old options should be intact for people to switch back

**Comment by ahmedkaludi** [comment]
- [ ] The Css is repeating twice which is causing 50 kb validation issue

**Comment by ajeetku** [comment]
To test:
in theme -> function.php 
add_theme_support( "amp-template-mode" );
In theme -> header.php after wp_head
<?php ampforwp_head(); ?>

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
