### ISSUE TITLE
Page title is changing when Rank math plugin active

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3358]
REF:https://secure.helpscout.net/conversation/884374984/71353?folderId=3008055

If select custom front page then it will display diff title.
And if not selected then also it display diff title.

**Comment by ahmedkaludi** [comment]
let me know if you need more testing on this

**Comment by iamkingsleyf** [comment]
The site is www.healthtian.com/amp/ use PC to see the title

**Comment by ahmedkaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ticket pushed in 0.9.97.62

**Comment by iamkingsleyf** [comment]
Is there a fix now? because you guys said you could not find any issue with the plugin

**Comment by MohammedKaludi** [comment]
We found the issue and fixed it also just now pushed the update as well.
Please update the plugin to the 0.9.97.62 version and it should work. 
I have uploaded the files just now so wait for few mins and then you will be able see the update in your WordPress dashboard. 

Please do let us know if your issue has been resolved in this update.

**Comment by iamkingsleyf** [comment]
working now
