### ISSUE TITLE
Need to make compatibility with Calendarize It plugin

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3360]
REF:https://secure.helpscout.net/conversation/886256909/71544?folderId=3008055

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/schema-and-structured-data-for-wp #354](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/354) via [**ZenHub**](https://www.zenhub.com/)
