### ISSUE TITLE
Create an option to remove date from Homepage and also in Recent posts

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#3363]
- [x] Remove date from Homepage

- [x] Remove date from Recent posts

https://wordpress.org/support/topic/how-to-remove-date-on-swift-theme/#post-11670097

**Comment by MARQAS** [comment]
Use `ampforwp_get_setting` here: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3a3bea93e07577774a302d6cd7235d8d8a6de6bb#diff-d9e62bf7636c72ea611757e43f70c46eR337

Can we improve the title name?: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3a3bea93e07577774a302d6cd7235d8d8a6de6bb#diff-260eba6333c3222e59a6aed22ac5ab37R7244

What if the user wants to hide the date only on Homepage but not on recent posts?

**Comment by MARQAS** [comment]
Why Default is false? https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/62a6905d9e3b41d20d292b73c58c4847b48c9d81#diff-260eba6333c3222e59a6aed22ac5ab37R7277

**Comment by MARQAS** [comment]
And why the Global date settings like `Date Format` is also connected with loop option?

**Comment by MARQAS** [comment]
When I hide the Date on the Homepage loop, it is still showing the date for the first post of the Homepage.

**Comment by MohammedKaludi** [comment]
Positioning of the controls and the Labelings seems to be incorrect.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
