### ISSUE TITLE
Need to improve import/export option.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3364]
Ref:https://secure.helpscout.net/conversation/874226901/70069?folderId=1060556
Many users are confused about how to import or export data or URL.

**Comment by MohammedKaludi** [comment]
1. Existing data should be visible https://take.ms/2Qhj3
2. The textfield is hiding after the click it should always be visible.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
