### ISSUE TITLE
Need to make compatibility with a basix theme

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3366]
Ref: https://secure.helpscout.net/conversation/866852968/69161/
Note:
If basix theme is active in amp setting and saves option is not showing 
See this screenshot:https://monosnap.com/file/Ajve2csoxBMgvwrwtev63ErFeFJPCZ

**Comment by MARQAS** [comment]
It is working fine on my end, please ask the user to update the plugin to the latest version and check again

**Comment by MARQAS** [comment]
Please remove it only where it is causing the error, for example only on the AMP options page. otherwise, it will cause errors.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2feb2916e03046804defb7a59babe8dcb0e5c5f2#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6420

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
