### ISSUE TITLE
When amp takeover is enabled remove /amp from the end of category module url.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3367]
Desc: When amp takeover is enabled remove /amp from the end of the category module URL.

Ref: https://secure.helpscout.net/conversation/886081729/71515/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
