### ISSUE TITLE
Usecase: i want to add custom field above the content, how to find the hook for it?

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3368]
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/swift/single.php

**Comment by MARQAS** [comment]
Are you looking for this hook, `ampforwp_before_post_content`?

**Comment by Zabi09** [comment]
https://ampforwp.com/tutorials/article/hooks-in-ampforwp/

**Comment by MohammedKaludi** [comment]
Ready to merge, While merging add the link of the article as well in the comments.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.6
