### ISSUE TITLE
Change prefix class of whatsapp to Api 

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3369]
Ref:https://secure.helpscout.net/conversation/887986395/71760?folderId=2770543
After updating our plugin WhatsApp not working.
see this screenshot: https://monosnap.com/file/bjGTrcafLgHZJ7oxw1nRZVw59ORg5U

**Comment by MohammedKaludi** [comment]
Remove http protocol from white list.

**Comment by MARQAS** [comment]
Are you talking about `$valid_protocols` of Blacklist sanitizer @MohammedKaludi? If yes any particular/valid reason for it?

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
