### ISSUE TITLE
Need to create options for amp-youtube Embed video attributes in row module of AMP Pagebuilder

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3373]
Need to add an option to hide show controls of the amp-youtube video
![1561027245228](https://user-images.githubusercontent.com/40556903/60327202-e4947200-99a8-11e9-9845-ec83b1dd4b78.jpg)

**Comment by MARQAS** [comment]
Escaping is required at many places like this: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/45c4e5d5c69dbec840b03afdc044955b1b1bbbc5#diff-1a22e45a9ee4bfe1e933fb1936074cb3R602

**Comment by MohammedKaludi** [comment]
Correct the spelling while merging.
https://take.ms/wmyDu

**Comment by MohammedKaludi** [comment]
Need a review from Ahmed

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
