### ISSUE TITLE
Yoast Description does not output 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3374]
Yoast Description does not output. Tested on my localhost.

Added description from here: https://monosnap.com/file/RxP8eXCo3B2RaQDMWVU1NQpJXjLGOh

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.61
