### ISSUE TITLE
Need to add external link option for images in Gallery(Logo) module of AMP Pagebuilder

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3375]
Need to add External link for image in gallery module ![dead_logo_gallery](https://user-images.githubusercontent.com/40556903/60327143-c4fd4980-99a8-11e9-88d9-0e1684b82cfc.jpg)

**Comment by MARQAS** [comment]
Currently, it looks like this: 
![image](https://user-images.githubusercontent.com/15303814/60570992-521d1580-9d90-11e9-84f6-3fe4996bda23.png)

Please check the Image module and Slider Module and make it like that.

**Comment by pegazee** [comment]
1) Remove these codes:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3bfde389d0e174e4ece3d5dd9e69bb1cd335e726#diff-eec326ce4f210ef2917f21cff48fd80aR698

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3bfde389d0e174e4ece3d5dd9e69bb1cd335e726#diff-eec326ce4f210ef2917f21cff48fd80aR601

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3bfde389d0e174e4ece3d5dd9e69bb1cd335e726#diff-eec326ce4f210ef2917f21cff48fd80aR592

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
