### ISSUE TITLE
Conflict with Themify Builder.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3376]
Conflict with Themify Builder.
Ref: https://secure.helpscout.net/conversation/887982313/71759?folderId=1680016

**Comment by MARQAS** [comment]
Check this function in the theme: `add_action('wp_enqueue_scripts', array(__CLASS__, 'enqueue_stylesheet'), 14);`

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
