### ISSUE TITLE
Comscore new variable for AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3378]
Can you please add to Comscore analytics a new paremeter they are requiring for AMP pages?

Now we have vars C1 and C2 , but they require now an extraUrlParams: comscorekw= amp

 
 
Code example is at https://wordpress.org/support/topic/comscore-new-variable-for-amp/

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
