### ISSUE TITLE
Homepage title issue with Rank Math SEO plugin

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3379]
When the rank math plugin is activated then recently published post title showing as homepage title. tried to recreate the issue on localhost but it's working fine, but a couple of users are facing this issue.

Ref: https://secure.helpscout.net/conversation/866443694/69122?folderId=1914715
https://monosnap.com/file/dOyNcCDm7lDFynQGHS2SYZHhklylEa

**Comment by MARQAS** [comment]
Duplicate issue.
Original: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3358
