### ISSUE TITLE
Compatibility issue with Wp-rocket cdn

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3380]
Compatibility issue with Wp-rocket cdn

Images are loading from the CDN but the gif is not loading from CDN

https://secure.helpscout.net/conversation/886954665/71634?folderId=2632028

https://www.fixcrunch.com/mobile-problems/android-problems/there-was-a-problem-parsing-the-package-17/amp

**Comment by Zabi09** [comment]
Will be going to fix in - https://github.com/wp-media/wp-rocket/issues/1844
