### ISSUE TITLE
Improper amphtml is getting created in the ngg_tag Url when NextGEN Gallery is used.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3381]
When NextGEN Gallery is used, then amphtml is getting created in the ngg_tag Url which is not correct, so it is throwing a validation error as 404 URL not found for AMP.
Ref: https://secure.helpscout.net/conversation/881389715/71021?folderId=2322649

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
