### ISSUE TITLE
Modified Date option not working when Date Format Traditional view is selected.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3383]
Modified Date option not working when Date Format Traditional view is selected.
Ref: https://secure.helpscout.net/conversation/891561438/72235?folderId=2322649

**Comment by MohammedKaludi** [comment]
Date escaping is missing, https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/54d88ba5ecfd8e689d83dcf6a39434153908baf6#diff-b6438fc932bdcf0c8a01c3c146505c9eR586

**Comment by MohammedKaludi** [comment]
Im not able to recreate the issue, @Rkroy / @pegazee can you help?

**Comment by MohammedKaludi** [comment]
Ready 👍

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
