### ISSUE TITLE
Design3 need to proper alignment of description.

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/accelerated-mobile-pages#3385]
Ref: https://secure.helpscout.net/conversation/888627071/71840?folderId=1060556

Desc:
1. Design3 need to proper alignment of description.
2. An issue occurred from the local system also.
3. Images are displayed out of the container.

Please check with design 1 and design2.

screenshot:
http://take.ms/0eicC

http://take.ms/U8rSn

**Comment by MohammedKaludi** [comment]
👍 ready to merge,

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.63
