### ISSUE TITLE
Need to make compatibility with Wistia Plugin.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3386]
Need to make compatibility with Wistia Plugin.

https://wordpress.org/plugins/wistia-wordpress-oembed-plugin/

https://secure.helpscout.net/conversation/888558657/71825?folderId=2632028

Mainly this format needs to support:
https://pastebin.com/s59wQ8kp

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
