### ISSUE TITLE
"Defragmentation" in schema plugin not working

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3390]
https://secure.helpscout.net/conversation/892308385/72320?folderId=3044500

His setup is in this format:

![Mono123](https://user-images.githubusercontent.com/27533027/60497819-30aa2400-9cd3-11e9-9b08-f1d7b4f106fa.png)

**Comment by MARQAS** [comment]
This issue is related to the Schema plugin, for more info follow this ticket: https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/367
