### ISSUE TITLE
Other Schema should not  Work when Our Schema is active

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3391]
https://secure.helpscout.net/conversation/892308385/72320?folderId=1060556

![mono1234](https://user-images.githubusercontent.com/27533027/60498282-ed9c8080-9cd3-11e9-9f15-8e3b9310ce4d.png)

**Comment by MARQAS** [comment]
Related to Schema plugin: https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/366
