### ISSUE TITLE
Performance Update 2.0

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3392]
- [x] Meta Value Queries
The issue below is using a meta value query which is not allowed due to performance reasons. The fix here would probably be to get back the results from _menu_item_menu_item_parent and filter out the unneeded results since this is a menu list.
classes/class-ampforwp-walker-nav-menu.php:46

**Comment by RajuJeelaga** [comment]
Everything is working fine with the current changes in the menu design, as like an old menu design.

**Comment by MohammedKaludi** [comment]
👍  ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
