### ISSUE TITLE
amp-addthis script is loading on WooCommerce product pages.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3393]
amp-addthis script is loading on WooCommerce product pages and throwing a validation error.
Ref: https://secure.helpscout.net/conversation/886642144/71590/

**Comment by MARQAS** [comment]
@Zabi09 Please check properly, it is even loading on normal pages

**Comment by pegazee** [comment]
While merging make sure to add this function `ampforwp_woocommerce_conditional_check`

**Comment by ahmedkaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ticket pushed in 0.9.97.62
