### ISSUE TITLE
Need to add color scheme and Color Scheme Font Color in design one and two

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3395]
Screenshot: https://monosnap.com/file/w7LwVRVUM3ZgJNiRY4srvfrhTgoEsU

HelpScout Link: https://secure.helpscout.net/conversation/894057128/72519?folderId=2770545

**Comment by MohammedKaludi** [comment]
Color schemes are not connected properly.

**Comment by RajuJeelaga** [comment]
After discuusion with @ahmedkaludi sir and @MohammedKaludi sir, 
In Design 1 and Design 2 color options are created and connected with its own color option field (like:header colors and footer colors),  so no need of creating Global color scheme in Design 1 and 2.
