### ISSUE TITLE
Image size values are not rendering form the block editor

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3396]
image size values are not rendering form the block editor.

https://secure.helpscout.net/conversation/883917384/71296?folderId=1680016

Please Discuss this with Ahmed sir.

**Comment by MARQAS** [comment]
The problem is with the Transients. Please clear the transient once and it will get resolved automatically.
If not then please contact the support team @ ampforwp.com/support

**Comment by MARQAS** [comment]
https://ampforwp.com/tutorials/article/what-if-image-size-values-are-not-rendering-properly/
