### ISSUE TITLE
Getting Warning: Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3397]
Des: "Warning: Invalid argument supplied for foreach() in /home/prabhjot2991/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/utils/class-amp-html-utils.php on line 11"

Ref: https://monosnap.com/file/WEpIUZrKoCNPV9RJb6E3lzb510LWAE

https://secure.helpscout.net/conversation/892537661/72351?folderId=2632028

**Comment by MARQAS** [comment]
This and #3398 are due to the same reason. 
I am closing this ticket, more info can be found here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3398
