### ISSUE TITLE
Related Posts below Single 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#34]
Related Posts below Single

**Comment by ahmedkaludi** [comment]
Yes, we need this https://wordpress.org/support/topic/support-for-related-posts/

**Comment by MohammedKaludi** [comment]
https://wordpress.org/support/topic/support-for-related-posts/#post-8273456

**Comment by ahmedkaludi** [comment]
It has been added in the latest version.
