### ISSUE TITLE
Close menu button is not showing when user comes from Google search

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3401]
https://secure.helpscout.net/conversation/892335956/72325?folderId=3044500

![Cidadania Italiana para Filhos Maiores de Idade _ Consultoria Passaporto - Google Chrome 2019-07-04 17 23 45](https://user-images.githubusercontent.com/27533027/60664947-cdf68b00-9e80-11e9-85e6-19f610f5acdb.png)

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
