### ISSUE TITLE
Need to add menu sidebar  background and elements color changing option for Design 1, 2

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3402]
REf: https://secure.helpscout.net/conversation/874226901/70069/
See this screenshot: https://monosnap.com/file/SW8d7yDUplusFcQDRqiGSMI5WO8N1y

**Comment by Zabi09** [comment]
This option should be on top - https://prnt.sc/ofm1o6 (check in master for more info)

**Comment by MohammedKaludi** [comment]
Add Default in menu settings as well 
https://take.ms/s2GbO

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
