### ISSUE TITLE
Image is not loading when source of it starting from ../wp-content

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3403]
https://secure.helpscout.net/conversation/894419892/72567?folderId=3044500

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/40f50612c3a72f0debf7d5008a97a1b5a88e25c7#diff-e7f6ca8ce090f4ff7573a4eec8ccf52dR62
please use `content_url();` or `WP_CONTENT_URL` 
For reference https://codex.wordpress.org/Function_Reference/content_url

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
