### ISSUE TITLE
Amp scripts not appending in head in Search pages when added in sidebar 

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3404]
To recreate: add a search widget or a gallery or video in widget area and test it on search pages 

ref: https://take.ms/tlGQc

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3000

**Comment by MohammedKaludi** [comment]
Also test with adding a YouTube video in the widget to make sure all the scripts are loading as well

**Comment by MARQAS** [comment]
It's adding the form script even when it is not required.

**Comment by MARQAS** [comment]
Where is the `data` getting updated?https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7e59baf75fbdeecf420e1c6cbe7f119e22ca9694#diff-04b38a94ddf918855eed7a68ecaa512dR1048

**Comment by MohammedKaludi** [comment]
why are we adding it separately for search and why not adding with other Archive:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/67deedf5b2f7bb632c992027a3b1723484315df0#diff-04b38a94ddf918855eed7a68ecaa512dR1044

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
