### ISSUE TITLE
The amp menu encoding becomes XXX

### ISSUE THREAD

**Issue by khaderhan** [ahmedkaludi/accelerated-mobile-pages#3405]
I am facing a problem with the encoding for the AMP menu and the amp page itself.
I have uploaded 2 screenshots to explain more.

A while ago, when i was using php 7.2 i was able to solve the problem by installing mbstring extension, but when i upgraded to php.7.3 and enabling mbstring again, it didn't work anymore.

Can you please help me?

![Capture](https://user-images.githubusercontent.com/47462919/60754101-fdbea380-9fe4-11e9-97ac-0d47c96a5f6b.JPG)
![Capture2](https://user-images.githubusercontent.com/47462919/60754102-fdbea380-9fe4-11e9-860b-619ed24053e7.JPG)

**Comment by MohammedKaludi** [comment]
@khaderhan This is strange, are you sure mbstring is enabled?
Can you please double check? 
If it is not working then i'll dig-deep and why it is not working.
Thank you

**Comment by khaderhan** [comment]
@MohammedKaludi It is enabled, its so weird. Check the phpinfo report: http://pnn.ps/khader.php

**Comment by MohammedKaludi** [comment]
Have you downgraded to 7.2.19? https://take.ms/Dgurz

**Comment by khaderhan** [comment]
@MohammedKaludi It is back now php7.3, i was just trying to go back to the old version to make the menu work again, but it is not working at all now haha :smile:

**Comment by MohammedKaludi** [comment]
Thank you for the info, I'll check the issue.

I'll install php 7.3, test and check why the strings are not converting.

I'll let you know if I have any questions or need further information on this issue.

**Comment by khaderhan** [comment]
Sounds good. And thank you so much for the extreme fast response, and thank you for the great efforts you have done on this great plugin. Best of luck. And looking forward to hearing from you.

**Comment by Zabi09** [comment]
@khaderhan 
There are some users who told us the menu is showing weird characters and most of the times it was fixed when there enable mbstring extension and we know you already knows about it but still, will you please follow this tutorial - https://ampforwp.com/tutorials/article/troubleshooting-the-problems-with-the-menu-navigation/ and let us know whether your issue is fixed or not.

And also will you please add this code in our main file and tell us what it is showing on your end.
var_dump( function_exists( 'mb_convert_encoding' ) );

So that we will check once and we can help you.

**Comment by khaderhan** [comment]
@Zabi09 Thank you for your response. I have checked all the steps and they are done as well.
I have added the var_dump code, and this is the outcome: bool(true)

**Comment by Zabi09** [comment]
@khaderhan 
I have checked your website and you are currently using PHP version 7.3.6 and now also it is showing proper menu - https://prnt.sc/obyb0w
Will you please tell us how you have fixed it?

**Comment by khaderhan** [comment]
@Zabi09 Thank you for the follow up. What i have done is i recompiled the PHP7, and restarted the server and cleared the cloudflare cache while the restart was working. And everything went correct.
Hopefully this action will help other people if they face the same issue.

**Comment by MohammedKaludi** [comment]
@khaderhan Thank you very much for your swift reply, yes this will help the other users as well.

I'm glad that your issue has been resolved.
