### ISSUE TITLE
default schema is not getting generated (Rare issue )

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3407]
The default schema is no generating at the user end.

The issue only occurring at the user end.

https://secure.helpscout.net/conversation/846726115/65291/

**Comment by MARQAS** [comment]
Scenario: The user did not want the schema generated by rank math SEO, rather he wanted the default AMPforWP schema. But he is using rank math. 
Solution: Disable the `Rank Math ld+json data` option present in the SEO section when rank math is selected.
![image](https://user-images.githubusercontent.com/15303814/60948840-7d17e400-a311-11e9-844e-e8cd09ef23f4.png)
