### ISSUE TITLE
After 0.9.97.62 update google insights says there is a redirection to /amp

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3408]
After 0.9.97.62 update Google insights lowers the score to 83-85 (from 90-91) saying there is a redirection to /amp. And I am quite sure this was not mentioned before...

**Comment by olddoc** [comment]
After clearing caches, amp cache and wprocket everything back to normal...

**Comment by MohammedKaludi** [comment]
Closing the ticket as the issue has been resolved.
