### ISSUE TITLE
Twitter URL  is dispalying instead of icon

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3409]
Twitter URL is displaying instead of a twitter icon.

The Twitter icon is from the Zox news theme.

Ref:https://monosnap.com/file/otWk4lWwfKZkc80CGzMRVMArzXjffM

https://monosnap.com/file/7OGFkyWw3pPvCOPHXMYfSAMNedIbIL

https://secure.helpscout.net/conversation/883917384/71296?folderId=2632028

**Comment by MARQAS** [comment]
Zox theme is independent of Yoast then why our plugin is dependent on Yoast for this icon?

**Comment by MohammedKaludi** [comment]
Need to add Icon Family for both types, fontawesome-icons and swift-icons

Currently its only for one Icon Family.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d82cb8d93a641c70517bb7e35c9820952deaf51e#diff-2ae5550e31f40c1962ca69d373af6b93R1633

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
