### ISSUE TITLE
Twitter Shares website description?

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#341]
When you share with social buttons, is it possible to share “tittle + link”? For example, on Twitter shares “tittle + website description” and tweets exceed the characters …

**Comment by ahmedkaludi** [comment]
REF: https://wordpress.org/support/topic/some-issues-29/

**Comment by MohammedKaludi** [comment]
Twitter sharing is working properly, Title and url are added while sharing..
Tested on Both the designs and on Both Sharings (post sharing and sticky sharing)
