### ISSUE TITLE
Need to add AMP footer widget in design 1,2 and 3

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3411]
Need to add AMP footer widget in design three

https://secure.helpscout.net/conversation/896759685/72869?folderId=3081347

**Comment by MARQAS** [comment]
Need styling.
And also remove this text to make it look global. 
![image](https://user-images.githubusercontent.com/15303814/61202630-a9fb3b00-a705-11e9-8c14-7e40895641d4.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
