### ISSUE TITLE
<g> tag from Non-AMP content should be skipped in AMP

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3412]
<g> tag from Non-AMP content should be skipped in AMP

https://monosnap.com/file/svHZQ5O12LO3LfKfzVyiOWLzLoClRx
https://monosnap.com/file/ywdIza7f3CzQmoSicrLFAkbTItXV88
https://secure.helpscout.net/conversation/883917384/71296?folderId=2632028

**Comment by ahmedkaludi** [comment]
Another issue: https://wordpress.org/support/topic/tag-g-issue/#post-11711067

**Comment by Zabi09** [comment]
Unable to recreate the issue on our end, So closing this ticket and if anyone faces this issue in future then you can reopen this ticket

**Comment by Zabi09** [comment]
This issue is not creating now, issue verified by Ahmed and closed
