### ISSUE TITLE
Pretty Links plugin incompatibility issue

### ISSUE THREAD

**Issue by gigidawg** [ahmedkaludi/accelerated-mobile-pages#3413]
Hi,

The Pretty Links (prettylinks.com) plugin's automatic keyword replacement does not work with the AMP plugin. I reached out to the devs and they said that he automatic replacements happen during the_content filter, so my guess is AMP does not run the_content filter correctly when generating the pages.

Can you please take a look?

Thanks!

**Comment by ahmedkaludi** [comment]
@gigidawg  The Github repository is for valid and tested bugs. 
Currently, you are asking for support which is provided by our team at https://ampforwp.com/support/

I recommend you to create a support ticket there, if the issue is valid then we will reopen this ticket with the proper data.
