### ISSUE TITLE
Extra CSS are loading in swift and AMP Layouts

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3414]
Extra CSS [AMP Theme Frame CSS] are Loading in Swift and AMP Layouts. 
Please see the screenshot
1)Swift ---- https://monosnap.com/file/i0cgtK5tcJWZul5TsITVBN6FoLZbX7
2)Layouts ----https://monosnap.com/file/WQvkAW6NaHuYOq4LyURypxOlqCHxe1

solution: The below screenshots code of lines needed for the all layouts, and rest of the CSS we can added in condition
https://monosnap.com/file/Su6usMswkoGxuRnTPtjszbtazLm0Ut

**Comment by MohammedKaludi** [comment]
No need to add the extra code this will be fixed when Tree Shaking Feature #2949  will be added into the core.

**Comment by MohammedKaludi** [comment]
@RajuJeelaga can you make sure that the css is loading when tree shaking is enabled ?

**Comment by RajuJeelaga** [comment]
@RajuJeelaga  @MohammedKaludi After discussion with mohammed sir,
We both need to sit together and Review this ticket, so after that merging process will start.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
