### ISSUE TITLE
Fatal error: Cannot redeclare is_amp_endpoint() (previously declared

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#3415]
Fatal error: Cannot redeclare is_amp_endpoint() (previously declared in D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php:1104) in D:\XAMPP\htdocs\wordpress\wp-content\plugins\amp\includes\amp-helper-functions.php on line 345

This error occurs when we activate AMP by automatic on previously activated ampforwp

**Comment by MohammedKaludi** [comment]
Please ignore  the commit : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7ac9b2da30cbfd53e469d849391d5fca5328dcd5

as it was for #3417

**Comment by MARQAS** [comment]
The error is coming only when Shapely theme is activated.

**Comment by MARQAS** [comment]
And also when Ads for WP is activated.

**Comment by ajeetku** [comment]
This fix only with  Ads for wp but the issue still there with **shapely theme**.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
