### ISSUE TITLE
Need to add a filter to remove options in sidebar in AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3416]
Screenshot: https://monosnap.com/file/L7i25F09OzA66EhksgEbUNnxiUuqyF

Help Scout Link: https://secure.helpscout.net/conversation/897994545/73077?folderId=2770545

**Comment by pegazee** [comment]
Didn't find example code, Please mention the example code, how to remove this side tabs and also make sure to add the ticket in the tutorial board card.

**Comment by Zabi09** [comment]
https://ampforwp.com/tutorials/article/how-to-remove-unused-sections-from-amp-options-panel/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
