### ISSUE TITLE
Breadcrumbs icons are not connected to icons font family

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3418]
Breadcrumbs icons are not connected to icons font family,
https://monosnap.com/file/RngtTElLFvVcQQvVgW07q4eFny7MHy
This is appearing only in Master, Beta it is working fine

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
