### ISSUE TITLE
Need to fall back the header type code in backend if user have not selected any header type

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3419]
Screenshot: https://monosnap.com/file/VkQVGOH8l9oMSMd5YenndiMvKqbMal

When the user enables the theme and if he has not selected the header design then CSS styles are not loading properly. Please see the screenshot:
https://monosnap.com/file/Uwt7esmwx2LFF2u25Vh3C6eWujTIoT

If the user is using design one two and three then also header type code should load in the backend.

The issue is occurring in a rare situation. 
Steps to recreate:

1. Select design one, two or three
2. Install rehub theme

If using swift design then test it without selecting any header type.

Help Scout Link: https://secure.helpscout.net/conversation/897948560/73067?folderId=2770545

I have attached rehub theme file in Magazine3 Telegram group.

**Comment by MohammedKaludi** [comment]
Failed and explained to santosh.

**Comment by MohammedKaludi** [comment]
use ampforwp_sanitize_color instead of sanitize_hex_color

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
