### ISSUE TITLE
Call to action option should be automatically enabled if the user selected header type 2

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3420]
Screenshot: https://monosnap.com/file/emSsqstfs2AvP05deG7vZ0KlWvQgwr

https://monosnap.com/file/QmnlSWXXlCK9WLn7yfUcd5TqEmF4F4

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
