### ISSUE TITLE
Need To add compatibility with image-slider in AMP sanitizer

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3422]
Help Scout Link: https://secure.helpscout.net/conversation/898915740/73205?folderId=2770545

**Comment by MARQAS** [comment]
We have to add its feature as well as its compatibility in Content. 
When the user is trying to add the `amp-image-slider`, it is getting sanitized and removed from the content, we have to add it in the whitelist sanitizer to allow users to be able to `amp-image-slider` in the content.

**Comment by MohammedKaludi** [comment]
Test with AMP-accordion and amp-carousal component as well/

**Comment by ajeetku** [comment]
Remove of the global is not a solution, Because its working properly for Divi page builders. if its changed its will break the page builders designs.
make a conditional on it.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
