### ISSUE TITLE
Need to add Addthis floating share button in amp

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3424]
Need to add AddThis floating share button in amp
Amp>design>social>Add this share button

REF:https://secure.helpscout.net/conversation/899178136/73242?folderId=1060556

**Comment by Zabi09** [comment]
When I enable "Smart Sorting Share Buttons" and disable two-child options then also the addthis script is loading.
https://prnt.sc/og8jry
The extension 'amp-addthis' was found on this page, but is unused. Please remove this extension.

**Comment by ajeetku** [comment]
Please use `esc_attr ` for attributes not `esc_html`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
