### ISSUE TITLE
Improve the Search form (Sidebar) design

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3425]
ref: https://wordpress.org/support/topic/search-form-disapear-after-version-0-9-97-61-2nd-july-2019-update/#post-11720109

**Comment by pegazee** [comment]
Need some styling for the swift single design-2.
Screenshot: https://take.ms/VA9Sz

@RajuJeelaga, please check this one

**Comment by RajuJeelaga** [comment]
@MARQAS Why two buttons are coming ..?
https://monosnap.com/file/Mo7vrA4x2ofQW6fR6VINYq7jK7itAX

**Comment by MohammedKaludi** [comment]
Need a review from Ahmed otherwise its good

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
