### ISSUE TITLE
Sticky Social Icons should be moved to Social Tab and some changes

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3426]
- [x] Social tab should be renamed to Social Sharing

- [x] Sticky Social Icons should be moved from Single to Social Sharing tab

- [x] Rename the Sticky Social Icons to Sticky Social Sharing bar

**Comment by MARQAS** [comment]
Escaping is required: 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4076d599b8e8f0ac7e23b8831874fec2b034bd56#diff-260eba6333c3222e59a6aed22ac5ab37R6399

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4076d599b8e8f0ac7e23b8831874fec2b034bd56#diff-260eba6333c3222e59a6aed22ac5ab37R6401

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4076d599b8e8f0ac7e23b8831874fec2b034bd56#diff-260eba6333c3222e59a6aed22ac5ab37R6993

And remove unwanted code: 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4076d599b8e8f0ac7e23b8831874fec2b034bd56#diff-260eba6333c3222e59a6aed22ac5ab37R6995

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
