### ISSUE TITLE
Validation error due to amp-facebook-like

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3427]
When the AMP facebook like is enabled but Social Icons are off from the single and Sticky social is also off, then the FB like script is loading. We need to fix this.
https://wordpress.org/support/topic/amp-for-wp-error-an-amp-component-script-tag-is-present-but-unused/#post-11718982

**Comment by MARQAS** [comment]
Improve the condition in social-icons.php files. Confirmed error in Design3, need to check with others as well

**Comment by santosh8793** [comment]
Facebook like amp error issue with single design layouts
Below is the screenshot of layout where facebook issue is getting
![facebook-like-issue-with-layouts](https://user-images.githubusercontent.com/40556903/61216904-1c7f1180-a72c-11e9-8345-a7e8cc9f2fa7.png)

**Comment by santosh8793** [comment]
Need to add condition for 'amp-facebook-like' tag to avoid javascript error
https://trello.com/c/qhv7I2jp/873-need-to-add-condition-for-the-tag-amp-facebook-like-to-avoid-javascript-required-error-in-amp

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
