### ISSUE TITLE
Need to create an optional option for the side menu when people click on the text the links should be dropped. links  sub links 

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3428]
ref: https://secure.helpscout.net/conversation/900427767/73378?folderId=3004564
screenshot: https://monosnap.com/file/wLiYBikDj42uAWwkuyA9PqMEiXZB5A

**Comment by ahmedkaludi** [comment]
currently, people have to click on the arrow to expand.

We need to give them an option so that people can allow users to click on the whole menu item in order to expand the sub-menu.

**Comment by Zabi09** [comment]
https://ampforwp.com/tutorials/article/how-to-expand-sub-menu-by-clicking-on-the-text-and-not-by-arrow/

**Comment by MohammedKaludi** [comment]
If there is a link in the menu it should go to the link, but if menu has # or no link then it should behave like clickable dropdown.

**Comment by akashagrjsr** [comment]
Make Sure to fix this in design one, two and three

**Comment by Zabi09** [comment]
Not working in design 1 2 and 3

**Comment by MohammedKaludi** [comment]
escaping missing
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4baae4c8f056347852eec4e89180bc6609b0416b#diff-4f07dbb4930a3f627addf815e3f7de3bR42

**Comment by MohammedKaludi** [comment]
Hover: pointer effect is missing while hovering on the text.
https://monosnap.com/file/zKS6g26aqxOAhnm5t5hHDks17BIxs4

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
