### ISSUE TITLE
Notification of amp is showing in every page,It should only show on AMP options panel.

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3429]
![Screenshot](https://user-images.githubusercontent.com/44563327/61042326-9db76b00-a3f1-11e9-854b-fb3a6cca492b.png)

AMP by Automattic is activated so the AMPforWP is now in the "Addon Mode". Learn More

**Comment by MohammedKaludi** [comment]
This will be resolved in this ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3053
