### ISSUE TITLE
In swift Single Design 2 sidebar css are not loading in archives

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3430]
Ref: https://secure.helpscout.net/conversation/900657552/73418?folderId=2770543

Note: when select design-2 in swift theme, CSS is not loading in archives.

See this screenshots

1.https://monosnap.com/file/GymQyjdb3qW4uwFW9TusIug6cnRItw

2. https://monosnap.com/file/2D0g2EwGmWRIjpcWoASV6bGRBTSS10

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 0.9.97.64
