### ISSUE TITLE
Need to add MGID support in AMP FOR WP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3431]
Help Scout Link: https://secure.helpscout.net/conversation/897976215/73073?folderId=2770545

**Comment by MARQAS** [comment]
MGID is an Advertisement company and we need to add options which allow users to add MGID ads with ease
https://github.com/ampproject/amphtml/blob/master/ads/mgid.md
Contact @ahmedkaludi before developing it for further info.

**Comment by pegazee** [comment]
For testing purpose used the below code
`<amp-ad width="600" height="600"
type="mgid"
data-publisher="site.com"
data-widget="372883"
data-container="M87ScriptRootC372883">
</amp-ad>`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Escaping missing on all places  Example`data-widget="'.$data_wid.'"`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/fe7352c8a9242d4f1f847dc23ec46c181df2c27f#diff-a1f269ece061d59e2040b9aeb7e9c722R197

**Comment by MohammedKaludi** [comment]
use esc_attr

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
