### ISSUE TITLE
Add Powerkit lazy loading compatibility 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3435]
https://wordpress.org/plugins/powerkit/
It's powered in Authentic theme and all Codesupply Co themes,

REF: https://wordpress.org/support/topic/first-image-of-article-in-amp-not-displaying/

**Comment by pegazee** [comment]
Tried to recreate the issue on the local server, It seems the issue is not occurring.
