### ISSUE TITLE
Compatability issue with ShortPixel Image Optimizer

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3439]
When AMP take over beta is enabled the post images are not displaying.

All details are mentioned in the helpscout link:https://secure.helpscout.net/conversation/898905457/73204?folderId=2632028

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
