### ISSUE TITLE
Titles in Related Topic

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#344]
Option… How can I see only Titles in Related Topic?

**REF:** https://wordpress.org/support/topic/image-missing-error-blogposting/

**Comment by ahmedkaludi** [comment]
this can be a part of snippet perhaps.. or maybe the design 1's responsive version do not remove the  description under related post

**Comment by ahmedkaludi** [comment]
we're closing this one to stay focused
