### ISSUE TITLE
Not an Array on accelerated-moblie-pages.php on line 224

### ISSUE THREAD

**Issue by jammayer** [ahmedkaludi/accelerated-mobile-pages#3440]
![2019-07-14_0148](https://user-images.githubusercontent.com/52858901/61172536-ecbff480-a5d9-11e9-986e-e40f414f045e.png)

Argument #1 is not an array in /home/socia715/conversologie.com/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 224

**Comment by pegazee** [comment]
The issue has been solved in this ticket #3434 and it will push in the v0.9.97.64 update.

**Comment by jammayer** [comment]
Thank you.

**Comment by MohammedKaludi** [comment]
yes, will be fixed in #3434 in 0.9.97.64 update (which is going to be pushed today).
