### ISSUE TITLE
When High-resolution Images option is enabled images link should be generate from higher order to lower order in schema markup

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3442]
Des: When High-resolution Images option is enabled images link should be generated from higher order to lower order in the schema markup

But it is generating from lower to higher

https://secure.helpscout.net/conversation/846726115/65291?folderId=2632028

Ref:https://monosnap.com/file/3EXTSh9GNSsTtMrcWuS3we7WuqdgT3

**Comment by MohammedKaludi** [comment]
👍  ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
