### ISSUE TITLE
add support for add-amp-script

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3443]
add support for add-amp-script for AMP theme framework so people can call necessary scripts in header\

https://secure.helpscout.net/conversation/900781560/73455?folderId=2770543

**Comment by ahmedkaludi** [comment]
- [ ] this must be refelcted on the documentation

- [ ] AMP Framework landing page

**Comment by pegazee** [comment]
Step by step to add the custom script in AMP:

1) Activate the AMP Theme Framework plugin.
2) Use the below functions in a set of the block where you want to use the custom script:

`amp_start_custom_script('$custom_js_url');`
set of a block ( example <button>Hello amp-script!</button> )
`amp_end_custom_script(); `

* Here $custom_js_url is the URL of the js ( eg: https://example.com/hello-world.js )
* I'm adding above code in the single.php file of AMP Theme Framework.

3) For js and experimental token of amp-script, In functions.php file of AMP Theme Framework, add below code:

`add_action('amp_experiment_meta','amp_custom_script_js');
if(!function_exists('amp_custom_script_js')){
	function amp_custom_script_js(){
		if( is_single() ){
			if( ampforwp_get_setting('ampforwp-custom-amp-script') && !checkAMPforPageBuilderStatus(ampforwp_get_the_ID()) ){
				$amp_script = '<meta name="amp-experiment-token" content="amp-script">
				<script async custom-element="amp-script" src="https://cdn.ampproject.org/v0/amp-script-0.1.js"></script>';
				echo $amp_script;
			}
		}
	}
}`

* Here I'm using the `if( is_single() ){}` condition to display only on the single pages. If you want to display on the other template pages, you can customize this condition and also make sure that the code which I've added in the single.php is also added in the other template pages.

**Comment by MARQAS** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b2545c18c406735c9d70e078e8e54c49d52da540#diff-260eba6333c3222e59a6aed22ac5ab37R2306
This condition can break the themes which have different folder name, try to check with headers.

**Comment by MARQAS** [comment]
Not working. 
I have added this code to test both with localhost js file and also with external js file, but both are not working. 
`<?php $custom_js_url2 = 'https://github.com/MARQAS/amp-hide-posts/blob/master/new-js.js' ?>
<?php amp_start_custom_script($custom_js_url2);?>
<?php amp_title(); ?>
<?php amp_end_custom_script();?>`
and this is the JS file https://github.com/MARQAS/amp-hide-posts/blob/master/new-js.js

nothing is changing in the output.

**Comment by MohammedKaludi** [comment]
Incorrect ticket and incorrect solution.
