### ISSUE TITLE
Featured Video Compatibility

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3444]
for loop as well as single.

Use case: using video tutorials on homepage so people can easily view the videos from the homepage itself.

REF: a meeting with https://secure.helpscout.net/conversation/894220896/72538/

**Comment by ahmedkaludi** [comment]
Can we speed up the release of this ticket?

**Comment by Zabi09** [comment]
Added Video Format - https://prnt.sc/ooj60c
Getting Validation Error - The tag 'amp-youtube' requires including the 'amp-youtube' extension JavaScript.

**Comment by Zabi09** [comment]
Not working when there is no featured image for the post

**Comment by Zabi09** [comment]
Video not coming if it is the first post - https://prnt.sc/oq0vcn and also not working in the related posts and in recent posts - https://prnt.sc/oq0viy

**Comment by MARQAS** [comment]
Not working on Single when `Video in Loop` option is disabled.

**Comment by MARQAS** [comment]
Can we create a single function for loop videos? Currently is getting repeated.

And videos are coming only on Homepage but in every loop.

**Comment by MARQAS** [comment]
Working properly on Homepage and Single but not in loops.
Swift: https://monosnap.com/file/11lbqmSJivyaeMhFMc8LHsfkUnPyHR
Design One: https://monosnap.com/file/kqiRKpBX7iEvgwkd9hxNmjOE1GC1uv
Design Two: https://monosnap.com/file/fVP6vdZcMSDiqGW55j7Bzzijz5D35Y
Design Three: https://monosnap.com/file/RWRiVpAaId10kFSfe4fRWbmDHYqWUv

**Comment by Zabi09** [comment]
If I disabled the option of Video in Loop then video is showing in related post loop - https://prnt.sc/otshji

**Comment by pegazee** [comment]
Before releasing this ticket, need to publish the tutorial.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by santosh8793** [comment]
Merged code into 9.98.5

**Comment by MohammedKaludi** [comment]
Need lot of code improvement.

**Comment by MohammedKaludi** [comment]
This issue will be fixed in #3668
