### ISSUE TITLE
Need to add the option date below the content

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3445]
Need to add the date below the content button in the design.
design>date
https://monosnap.com/file/ALmls3pqTsTl1TuYvsoywfAcfhs4jJ

REF:https://secure.helpscout.net/conversation/901003280/73512?folderId=3008055

**Comment by Zabi09** [comment]
Why only in swift?

**Comment by MohammedKaludi** [comment]
Why two dates are showing.
https://take.ms/8aYPM

**Comment by pegazee** [comment]
failed:
1) https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/014444542e94fd2a13a4871b9e13cc5541ee769f#diff-260eba6333c3222e59a6aed22ac5ab37R7945

2) https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/014444542e94fd2a13a4871b9e13cc5541ee769f#diff-d9e62bf7636c72ea611757e43f70c46eR357

**Comment by pegazee** [comment]
1) In Master "Modified Date Notice" option is available need to create the same option in version 0.9.98.
2) Once you enable "Modified Date Notice" child option will display "Date Notice".
3) In "Date Notice" option there are two options need to rename -
    -  "Modified date" rename with "Modified Date Notice"
    -  "Below content" rename with "Publisher date Notice"
4) If you select "Modified Date Notice" or "Publisher date Notice" option one child one will be shown "Time" this option always enabled.
5) Once you select "Publisher date Notice" message should be like this "This Post was last published  on.."

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
