### ISSUE TITLE
Disqus comment is not working after version 0.9.97.63

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3446]
Disqus comment is not working after version 0.9.97.63 in the previous version ie. 0.9.97.62 it was working.

Ref: https://secure.helpscout.net/conversation/902966190/73745?folderId=3081347

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.65
