### ISSUE TITLE
Uncaught Error: Call to undefined method WPSEO_Options::get()

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3447]
1. The fatal error is thrown when Yoast SEO Premium plugin is selected in the AMP settings. 
Uncaught Error: Call to undefined method WPSEO_Options::get() in C:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php:1608
2. Yoast SEO Premium is conficting with URL Inspection Tool Compatibility settings panel.
Ref: https://secure.helpscout.net/conversation/900922985/73476?folderId=2322649

**Comment by MARQAS** [comment]
https://monosnap.com/file/hXp35f9IoVf8Tm1t5dwyOMbpMsZIxe

**Comment by MohammedKaludi** [comment]
👍 ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.65
