### ISSUE TITLE
User wants Wordpress admin toolbar in the AMP area

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3450]
User wants to access all the functionalities of Admin tool bar such as dashboard, posts, etc in the AMP area.

https://secure.helpscout.net/conversation/903594661/73911?folderId=3044500

**Comment by Zabi09** [comment]
There is a lot of CSS with "wpadminbar" and due to that every post/page has the validation error

The author stylesheet specified in tag 'style amp-custom' is too long - document contains 98825 bytes whereas the limit is 50000 bytes. Debug. Learn more.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d4d305871a48064374046cbb855a05bee54902c7#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7004 Use: ` includes_url`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
