### ISSUE TITLE
Lightbox effect not working with "Tablepress" when "Link To" option is selected in Attachment display settings

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3451]
Helpscout Link: https://secure.helpscout.net/conversation/899646080/73277?folderId=2770545

Steps to recreate:

1. Install the Tablepress plugin and see the given video link:

https://monosnap.com/file/wdK9AZrBeFwf8JQv5eMlKIqMFh6vF1

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by pegazee** [comment]
3451
