### ISSUE TITLE
Sticky Social Icons and cookies banner is having design problem

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3452]
Des: Sticky Social Icons and cookies banner is active both at a time then the ACCEPT button doesn't see

https://secure.helpscout.net/conversation/903501874/73850?folderId=2632028

https://hospitalcruzrojacordoba.es/noticias/informe-pericial-por-accidente-indemnizacion-valoracion-dano-corporal-cordoba-hospital-cruz-roja-y-legal-trauma/amp/

**Comment by RajuJeelaga** [comment]
After discussion with @ahmedkaludi regards the above screenshots issues, in Design 1,2 and 3 the notification bar will show on the top of sticky social icons in Mobile screens.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
