### ISSUE TITLE
Need to hide time in traditional view option.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3453]
Ref:https://secure.helpscout.net/conversation/885986744/71499?folderId=2770543
Note: want to remove the time in Traditional view.if select traditional view it shows time and date here, just hide the time. No one wants to know the time a post was published.
See this screenshot: https://monosnap.com/direct/lU5zX69siJkVl5iMQ3p4pVcsh53p5H

**Comment by sonaliramteke** [comment]
1) In Master "Modified Date Notice" option is available need to create the same option in version 0.9.98.
2) Once you enable "Modified Date Notice" child option will display "Date Notice".
3) In "Date Notice" option there are two options need to rename -
    -  "Modified date" rename with "Modified Date Notice"
    -  "Below content" rename with "Publisher date Notice"
4) If you select "Modified Date Notice" or "Publisher date Notice" option one child one will be shown "Time" this option always enabled.
5) Once you select "Publisher date Notice" message should be like this "This Post was last published  on.."

**Comment by pegazee** [comment]
We need to add the option to hide the time, not to completely removed. Please concern or discuss this with @ahmedkaludi

**Comment by MohammedKaludi** [comment]
Date on off not working in Design 3.
1. when Published data selected -> no time at all
2. When Modified date selected -> Time is Always present.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16618009/64608141-a6272480-d3e7-11e9-82ad-8532cac9e31a.gif)

**Comment by MohammedKaludi** [comment]
conditions can be improved https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c2b163d24b4c279fed882a5c7e68b95f3f6a567d#diff-503090f77db7d3dbcfca835cfff9ba43R44

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
