### ISSUE TITLE
Need to add $depth parameter in filter 'nav_menu_item_id'

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3454]
Missing depth parameter in id need to add depth parameter 
Here Screenshots:
https://monosnap.com/file/RhcQc74dnEBu9Qks9jggUvdGKFSnPl

Link:
https://developer.wordpress.org/reference/hooks/nav_menu_item_id/

REf:https://secure.helpscout.net/conversation/902931901/73735?folderId=3008055

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.65
