### ISSUE TITLE
HotWP PRO: when this theme is active, it is showing validation errors in amp category page.

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3455]
https://secure.helpscout.net/conversation/897317203/72953?folderId=3004564

**Comment by MARQAS** [comment]
Don't use undefined functions

**Comment by ajeetku** [comment]
add_filter('single_cat_title' , true ); 
instead of callable function written true, why ?

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
