### ISSUE TITLE
Add a tooltip to show description about "Social Share links to AMP" and "No Follow All Your Social Links"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3456]
Screenshot:https: //monosnap.com/file/eSR3Nu7gR5uvD8ChEKiioUaaTebaKu

When the user hovers over the "?" symbol then it should show the  Description box about what "Social Share links to AMP" and "No Follow All Your Social Links" option will do. When the user clicks on the "?" symbol then it should redirect to the tutorial link for this.

**Comment by MohammedKaludi** [comment]
Ready

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
