### ISSUE TITLE
"amphtml" is not generatiing in sorce code when it comes to search results pages in non AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3458]
Ref: https://secure.helpscout.net/conversation/905670380/74361?folderId=2770545

When the user searches the pages in non-AMP then "amphtml" is not generating in the source code. 

For example, if the user search "economy" in the search box of this website "https://easyconomy.com/" then it should show "https://easyconomy.com/amp-1?s=economy" in the source code of search results.

**Comment by MohammedKaludi** [comment]
merge the code into 98.5 branch.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
