### ISSUE TITLE
Mobile redirection causing extra redirects from /amp to /amp/

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3459]
Happens from 0.9.97.63 and still in 0.9.97.65

Google insights lowers the score from 89-91 to 67-70 (double redirect)

"URL
Duración
(Initial: https://www.nexustraductions.com/)    0 ms    
/amp(www.nexustraductions.com)                780 ms
/amp/(www.nexustraductions.com)               180 ms

Same as https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3270  
(as per my comment of 2nd of Jun, not the first one), maybe something you fixed there is gone in these last updates?

Cleared all caches and even disabled them to no avail:
As per https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3408, but this time no way to fix it clearing or even disabling caches.

**Comment by ahmedkaludi** [comment]
@olddoc Thanks for helping us see this. We will test this internally and get back to you.

**Comment by MARQAS** [comment]
Hi @olddoc, Can you share how your permalinks structure looks?

**Comment by olddoc** [comment]
Sorry for the late answer as I was away from the office for a week,
I enclose a picture of my permalinks structure.

Kind regards

**Comment by MohammedKaludi** [comment]
Ready 👍

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.98.4
