### ISSUE TITLE
compatibility issue with WP Offload Media Lite.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3460]
Thumbnail images are not rendering from this plugin related URL's  WP Offload Media Lite.

https://secure.helpscout.net/conversation/869405163/69528?folderId=2632028

**Comment by pegazee** [comment]
When adding the featured image by using the featured By URL plugin, getting PHP debug error

( ! ) Notice: Trying to get property 'post_excerpt' of non-object in C:\wamp64\www\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\vendor\amp\includes\class-amp-post-template.php on line 364
--
Screenshots:
1. https://take.ms/X8rub
2. https://take.ms/4TnvL

**Comment by MohammedKaludi** [comment]
Ready .

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
