### ISSUE TITLE
Need to improve color picker library in AMP FOR WP Plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3461]
Need to use the color picker in which we don't need to click on choose option. It should select the color automatically that the user selects from the color picker box.

Screenshot: https://monosnap.com/file/0dwsQ8ToyroD3AhfOD29fcofHTs7aa

**Comment by ajeetku** [comment]
need to add it in redux-spectrum.min.js file also

**Comment by pegazee** [comment]
check above comment

**Comment by MohammedKaludi** [comment]
Need to update min.js file as well.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
