### ISSUE TITLE
Need to shift the Header Background Option and Header Elements option on top in Swift theme

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3462]
Screenshot: https://monosnap.com/file/irNEC1If7cSuwLkEa3JngOucxi6f6R

We need to shift the options of Header Background and Header Elements on top in Swift theme.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
