### ISSUE TITLE
Validation error: The extension 'amp-next-page' was found on this page, but is unused. Please remove this extension

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3463]
This error is coming in the archives pages of Swift when Infinite scroll is enabled
ref: telegram.

**Comment by MARQAS** [comment]
Added in master: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/86e03fb775d48d0269a68c518f944c7c8c912bdd

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98
