### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function ampforwp_is_non_amp()

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#3464]
Fatal error: Uncaught Error: Call to undefined function ampforwp_is_non_amp() in D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php:570 Stack trace: #0 D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\structured-data-for-wp.php(48): ampforwp_is_amp_endpoint() #1 D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\function.php(865): saswp_non_amp() #2 D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\function.php(742): saswp_global_option() #3 D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\function.php(30): saswp_remove_yoast_product_schema() #4 D:\XAMPP\htdocs\wordpress\wp-includes\class-wp-hook.php(286): saswp_schema_markup_hook_on_init('') #5 D:\XAMPP\htdocs\wordpress\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 D:\XAMPP\htdocs\wordpress\wp-includes\plugin.php(465): WP_Hook->do_action(Array) #7 D:\XAMPP\htd in D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php on line 570

**Comment by Sanjeevsetu** [comment]
this issue comes, when AMPforWP is on addon mode with AMP by automatic. 

When you save any post via gutenburg, post will not be saved due to this error

**Comment by MohammedKaludi** [comment]
`ampforwp_get_featured_image_from_content()` is also not working in AddOn Mode.

**Comment by eb-ina** [comment]
having the same issue, and it reflected to amp newspaper themes.

**Comment by merajali294** [comment]
@eb-ina, With regards to AMP Newspaper Theme, it has been fixed in the latest version(1.14).

**Comment by MARQAS** [comment]
` Fatal error: Uncaught Error: Call to undefined function ampforwp_is_non_amp` is resolved in #3487

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
