### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method RevSliderFunctionsWP::check_for_shortcodes()

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3465]
Fatal error: Uncaught Error: Call to undefined method RevSliderFunctionsWP::check_for_shortcodes() in /home/coiffure-saint-raphael/public_html/wp-content/plugins/accelerated-mobile-pages/classes/class-ampforwp-rev-slider.php:39 Stack trace: #0 /home/coiffure-saint-raphael/public_html/wp-includes/shortcodes.php(325): AMP_Rev_Slider_Embed_Handler->shortcode(Array, '', 'rev_slider') #1 [internal function]: do_shortcode_tag(Array) #2 /home/coiffure-saint-raphael/public_html/wp-includes/shortcodes.php(199): preg_replace_callback('/\\[(\\[?)(rev_sl...', 'do_shortcode_ta...', '[rev_slider ali...') #3 /home/coiffure-saint-raphael/public_html/wp-content/plugins/js_composer/include/templates/shortcodes/rev_slider_vc.php(28): do_shortcode('[rev_slider ali...') #4 /home/coiffure-saint-raphael/public_html/wp-content/plugins/js_composer/include/classes/shortcodes/core/class-wpbakeryshortcode.php(267): require('/home/coiffure-...') #5 /home/coiffure-saint-raphael/public_html/wp-content/plugins/js_composer/include/classes/shortcodes/core in /home/coiffure-saint-raphael/public_html/wp-content/plugins/accelerated-mobile-pages/classes/class-ampforwp-rev-slider.php on line 39

---------------------------------------------------------------------------------------
https://secure.helpscout.net/conversation/907381860/74634?folderId=3044500

**Comment by MARQAS** [comment]
This is just a temporary solution, Detailed solution will be added in next update

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
