### ISSUE TITLE
Multiple H1 Tag Issues in AMP Version on Home and Category Pages in Design 3

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3466]
Multiple H1 Tag Issues in AMP Version on Home and Category Pages in Design 3

https://secure.helpscout.net/conversation/908220145/74774?folderId=1060551

**Comment by pegazee** [comment]
On Homepage, looping design is breaking. Screenshot: https://take.ms/L3Ym2

In master: https://take.ms/czyqC

**Comment by Zabi09** [comment]
added in 0.9.98.5

**Comment by MohammedKaludi** [comment]
Ready

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
