### ISSUE TITLE
 Row module settings popup header is overlapped while scrolling the options in AMP Page Builder

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3467]
Below is the screenshot of the row module settongs popup with overlapping issue in AMP Pagebuilder
![row-module-settings-popup](https://user-images.githubusercontent.com/40556903/61579627-63527a00-ab25-11e9-8915-361958aa2a37.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Z index value is incorrect.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bb5b0cb4e4d001abe540918056c89f59078b2ce1#diff-b38a42c9d6310dc57bb8661dfacb2257R675

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
