### ISSUE TITLE
Need to improve the labeling of the 'Text font' option in 'Row module settings' of AMP Page builder

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3468]
![row-module-settings-font](https://user-images.githubusercontent.com/40556903/61579702-410d2c00-ab26-11e9-9269-b46dec4dbb9e.png)

**Comment by MohammedKaludi** [comment]
👍 ready

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
