### ISSUE TITLE
Check Design 1 Notifications Issue and Amp for WP compatibility on Social Locker

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#347]
I Wish That you add in Amp for WP compatibility on Social Locker is a great plugin for my website. Also i wish that fix “Desing Two” cant see any notifications like cookies. Thanks!

**REF:** https://wordpress.org/support/topic/please-add-compatibility-with-social-locker/

**Comment by khaledMohammed000** [comment]
Notifications working perfectly look here : http://take.ms/o7YyN

**Comment by khaledMohammed000** [comment]
Am renaming the above issue since : http://take.ms/BH7HY

**Comment by khaledMohammed000** [comment]
@MohammedKaludi http://take.ms/Tqb96

**Comment by MohammedKaludi** [comment]
Cookie Notification working on both designs
