### ISSUE TITLE
Logo and headline comes togeather after .98 update

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3472]
issue re-occured on the localhost as well.

https://wordpress.org/support/topic/after-updating-amp-latest-version-0-9-98/

![image](https://user-images.githubusercontent.com/16532359/61619435-76338e80-ac8c-11e9-90d0-ab9f01fd09d0.png)

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.98.1
