### ISSUE TITLE
Undefined index: ampforwp-amp-on-off

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#3474]
D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 807

D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 813

**Comment by ozumoo** [comment]
I have the same issue , too

**Comment by MohammedKaludi** [comment]
This will be fixed in Friday's update.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 0.9.98.2
