### ISSUE TITLE
Allow href attribute value  with associated apps property

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3475]
Need to allow href contents to open associated apps like ( href="skype:abc?add" )

Ref: https://dev2.discoverbrazil.com/author/discoverbrazil/

**Comment by pegazee** [comment]
Not working

`Thank you for using AMPforWP plugin! Run a <a rel="nofollow" href="https://www.ampforwp.com" >installation</a> wizard`

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
