### ISSUE TITLE
Default loading message as '1'  in search bar  after latest update (.98)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3476]
Ref:https://secure.helpscout.net/conversation/909048078/74890?folderId=2770543
Same in localhost also:
See this screenshot: https://monosnap.com/file/mH75X44OGy3yZ3Y3SzcHiXqKc77zYT

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Fixed in 0.9.98.1
