### ISSUE TITLE
Need to remove featured title as H1 when featured slider is enabled

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3477]
Screenshot: https://monosnap.com/file/MihoMFmzYJYrKrMx4htHmu0BIjhXST

Ref: https://secure.helpscout.net/conversation/908191818/74764?folderId=2770545

When Featured Slider is enabled it shows featured title in H1 on the home page which is against the SEO rules. We need to remove h1 tags from the featured title.

**Comment by MohammedKaludi** [comment]
Will be fixed.
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3477
