### ISSUE TITLE
There is closing tag "</a>" in header-bar.php of design bar, for which there is no opening tag

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3479]
Ref :  https://secure.helpscout.net/conversation/908757844/74859?folderId=3044500

In line no: 10 of header.php of Design 1 there is no opening for closing tag "</a>"

**Comment by Zabi09** [comment]
Already removed extra </a> by mistake in - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bc0549ee2c39d35e492bd02f62c126a8e025927e

**Comment by MohammedKaludi** [comment]
Merge this in 98.5 then

**Comment by MohammedKaludi** [comment]
And when it is added move the ticket directly to ready section

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
