### ISSUE TITLE
shortcode not removed in amp home page

### ISSUE THREAD

**Issue by Digital-Trends** [ahmedkaludi/accelerated-mobile-pages#348]
Hi,
your plugin remove all shortcode from all your pages except home page

I fixed the error by add this code ( accelerated-moblie-pages.php ) : 

`function remove_shortcode_from_index($content) {    
	if( is_home() ) {
		if ( is_amp_endpoint() ) {        
			$content = strip_shortcodes($content);    
		}
	}
	return $content;
}
add_filter('the_content', 'remove_shortcode_from_index'); `

Image before add my function:
https://s23.postimg.org/9zunuf76z/amp_for_amp.png

after added my dunction
https://s24.postimg.org/ufk1krfl1/22222.png

Regards,
Mohammed

**Comment by MohammedKaludi** [comment]
@Digital-Trends 

This issue will automatically be fixed in this commit https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/331f303440985616135e30f02f109b1faf744047

After this update, you don't need to the above code.

Thank you,
Mohammed Kaludi
