### ISSUE TITLE
Add Role based Access to all the options

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3480]
Ref :  https://secure.helpscout.net/conversation/909905306/75055?folderId=3044500

User wants to give some access to his Editors

**Comment by Zabi09** [comment]
Do we need this option now - https://monosnap.com/file/ZuEmbnM4wcQHCpTOQ3fwuFzsaAZaxR

Will you please check once whether if it's not necessary then we can remove it

**Comment by Zabi09** [comment]
Please hide this option - https://prnt.sc/ovlt59

**Comment by MohammedKaludi** [comment]
escaping missing.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ef3eb27fb1c79dae5b804b8e6185cdb8e2510592#diff-260eba6333c3222e59a6aed22ac5ab37R1364

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
