### ISSUE TITLE
rel=”nofollow” is getting replaced by rel=”noreferrer in links

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3483]
Added "no follow" - https://monosnap.com/file/xwXn52HVNAydnWTUImar1KRNu07y3l
Getting replaced by "noreferrer"  - https://monosnap.com/file/U0WyaeElKjhSpGZZfJvIENavOw43zo

https://wordpress.org/support/topic/link-with-attribute-relnofollow-it-is-unwanted-replaced-by-relnoreferrer/

**Comment by ahmedkaludi** [comment]
Instead of replacing one by another, why don't you add rel="noreferrer" to whatever it is written by default? If the defaul is rel="nofollow" it will be something like this → rel="nofollow noreferrer"

**Comment by MohammedKaludi** [comment]
Ready

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
