### ISSUE TITLE
Search bar is not showing in design three after enabling the search option in header option panel

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3484]
Screenshot: https://monosnap.com/file/cD6HJU5VFi0sKWnClOmORciFV06DAC

Help Scout Link: https://secure.helpscout.net/conversation/909627952/75006?folderId=2770545

After the latest update search bar is not showing in the header after enabling search option in design three.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.2
