### ISSUE TITLE
Serach option should be enabled by default when user comes in design three

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3485]
Screenshot: https://monosnap.com/file/QWe2aqOqGq9MLYurc6sD9AQXVmfkyf

When the user changes the design swift to design three then search option should be enabled by default.

**Comment by MohammedKaludi** [comment]
Ready

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
