### ISSUE TITLE
In Archives Category & Tags option  is disable, link should go to non-amp

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3486]
Ref: https://secure.helpscout.net/conversation/910190289/75087?folderId=2770543

Note:

1. If the tag is disabled in the archives category & tags option it should go to non-amp version. nowhere link is not showing. it should show link and that link should redirect to non-amp version.
See this screenshot: https://monosnap.com/direct/JA24p1GpX1CAN2ArqyhqVzlQmCi0gg

2. In the archives category & tags option, when tag option is disabled, tag shows in the amp page, then click on the tag, it will redirect to non-amp version, in that page amp is not loading.
See these screenshots:
1.https://monosnap.com/direct/7uA9AL83ukscEOdZ2ny73y0jQS95Ha
2.https://monosnap.com/direct/0T5pr5BfHYjRRbOggpqpxkugDWA6Op

**Comment by MARQAS** [comment]
Use case: I enabled the Archives option but disabled the Categories option in it.
Expected result: Categories of Breadcrumb and Recent posts should also point towards non-amp.
Current: It is pointing towards AMP link, i.e, website/category/amp

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
