### ISSUE TITLE
Fatal error: when  Smush pro plugin activated 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3487]
Ref:https://secure.helpscout.net/conversation/904579974/74175?folderId=2770543
I have recreated the issue in local, it happens with the latest version of smush pro.
See this screenshot:https://secure.helpscout.net/conversation/904579974/74175?folderId=2770543

**Comment by ahmedkaludi** [comment]
this is definitely a real issue.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.2
