### ISSUE TITLE
When AMP Page builder is checked with Empty Content,Container is missing on AMP view

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3488]
Des: When AMP Page builder is checked and then it has empty columns then the container is missing on the AMP view of the particular post or page
https://secure.helpscout.net/conversation/909187927/74917?folderId=2632028

**Comment by MohammedKaludi** [comment]
The Fix is incorrect.

**Comment by MohammedKaludi** [comment]
Improve directly inside the `checkAMPforPageBuilderStatus()` and do not use any filter.

Also fix it in 0.9.98.5 branch

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/76e975720882efc28cafa49d6df9c8c5c209a6fc#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6908

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
