### ISSUE TITLE
Menu design issue in Design 3

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#3489]
Ref: https://secure.helpscout.net/conversation/911555682/75317?folderId=1060551
https://monosnap.com/file/CiRsvWxLtiP6x1WjmbI6BbnQ30TbTL

**Comment by Rkroy** [comment]
Another user: https://secure.helpscout.net/conversation/911579009/75336/

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.2
