### ISSUE TITLE
error: The tag 'iframe' is disallowed [ youtube player in amp page ]

### ISSUE THREAD

**Issue by Digital-Trends** [ahmedkaludi/accelerated-mobile-pages#349]
Hi,
Error on youtube player ( The tag 'iframe' is disallowed. ) **on home page only**
I embed video from wordpress editor

I want just to mention that i am using WPML in this website

none home page with youtube player ( no error )
https://goo.gl/TdxDzt

home page with youtube player ( error )
https://goo.gl/9ux2Ov

Regards,
Mohammed

**Comment by MohammedKaludi** [comment]
@Digital-Trends 

Thank you for reporting the issue, I have fixed this issue in commit https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/331f303440985616135e30f02f109b1faf744047 

And it will be pushed in the next update which we are planning to release today.

Thank you once again,
Mohammed Kaludi
