### ISSUE TITLE
After Version 0.9.98 update options are not showing in Background Type gradient

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3490]
Screenshot: 
1.https://prnt.sc/ojflvl
2. https://prnt.sc/ojfn3m

AfterVersion 0.9.98 update options(Background Gradient) options are not showing in Background Type gradient in Row settings of AMP Page Builder

Ref: https://secure.helpscout.net/conversation/897110597/72932?folderId=2770545

**Comment by Zabi09** [comment]
Background Gradient is working fine but will you please check why color is showing two times - https://prnt.sc/oju86t and this is only in master

**Comment by pegazee** [comment]
Notice: Undefined variable: parts in C:\wamp64\www\wordpress\wp-content\plugins\accelerated-mobile-pages\pagebuilder\inc\viewShowFrontData.php on line <i>540</i></th></tr>

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.2
