### ISSUE TITLE
Search bar is messed up after #3425 and #3000

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3491]
Search bar is messed up after #3425 and #3000

need to fix it and make sure it is working as expected.

Fonts: https://take.ms/Gextb
Label: https://take.ms/mOohw

This is totally unacceptable. Currently we are Breaking 2 things for Fixing one.

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
