### ISSUE TITLE
In alt attribute's content single quotes should be removed

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3492]
REf:https://secure.helpscout.net/conversation/909187927/74917?folderId=2632028

https://monosnap.com/file/TLsG2WElpsTuA7robcOtuX02qlppGE

**Comment by Zabi09** [comment]
Please update it in the vendor log as well

**Comment by Zabi09** [comment]
I have applied the solution on user's end but the issue is not fixed

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
