### ISSUE TITLE
Rare issue AMP settings are not getting saved showing popup error "There was a problem with your action. Please try again or reload the page."

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3494]
https://secure.helpscout.net/conversation/906301807/74451?folderId=2632028

Issue resolved at this user end.

**Comment by Rkroy** [comment]
Another user with an issue while saving AMP settings.
Error: There was a problem with your action. Please try again or reload the page.
Ref: https://secure.helpscout.net/conversation/910472518/75130?folderId=2322649

**Comment by sushmarachakonda** [comment]
Another user with the same issue.
https://secure.helpscout.net/conversation/910123642/75077?folderId=3004564

**Comment by sushmarachakonda** [comment]
Another user having the same issue.
https://secure.helpscout.net/conversation/895447795/72678?folderId=3004564

**Comment by TMsravan** [comment]
Another user with the same issue.
https://secure.helpscout.net/conversation/843373281/64521?folderId=2632030

**Comment by TMsravan** [comment]
One user gets resolved this issue by contacting there hosting provider.

"There was a mod security hit for the website. So They have whitelisted the IP manually."

The issue gets resolved for this user.

https://secure.helpscout.net/conversation/906301807/74451?folderId=1060556

**Comment by HF-Suhail** [comment]
I have faced two types of errors. one is I have nothing save any changes in my AMP and second is on my website no any single product is open they show me the error of too many redirects/
https://readingglasseswholesale.com/product/sl15-classic-unisex-bifocal-tinted-lens-reading-sunglasses-spring-hinges-5-color/amp/

**Comment by amer07** [comment]
Another user with an issue while saving AMP settings.
Error: There was a problem with your action. Please try again or reload the page
Ref: https://secure.helpscout.net/conversation/922845229/77693?folderId=1060556

**Comment by keshavsharma333** [comment]
One more user with this issue.
Ref:  https://secure.helpscout.net/conversation/933778448/78736?folderId=3044500

**Comment by keshavsharma333** [comment]
Another user with this issue.
Ref: https://secure.helpscout.net/conversation/933800787/78742?folderId=3044500

**Comment by akashagrjsr** [comment]
The AMPFORWP option panel is not getting saved due to code inside "ampforwp-ga-field-advance" and "ampforwp-ga-field-advance". The issue is occurring due to comments written inside the JSON in the /*\n format.

User is getting 406 error in the console.

We need to fix the issue in two scenarios:

1. If the user has already install the plugin and facing the issue, we need to override the code saved in the database.

2. If the user installs the plugin first time then he should not get the same error.

We have fixed the issue at the end of this user:

Ref: https://secure.helpscout.net/conversation/931199465/78508?folderId=1060554

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.6

**Comment by MohammedKaludi** [comment]
Issue still persists on specific use case.

**Comment by MohammedKaludi** [comment]
This issue has been fixed and pushed in 0.9.98.7 update,
If someone is facing the issue, please check it with the latest version.
And if issue still persists then reopen the ticket.
