### ISSUE TITLE
If title is loading then only its markup should load otherwise not

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3495]
Help Scout Link: https://secure.helpscout.net/conversation/908191818/74764?folderId=2770545

If the title is loading then its markup(h1> tag) should load else not.

User is waiting for this so need to push it soon.

**Comment by MohammedKaludi** [comment]
Ready

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
