### ISSUE TITLE
Content blank if Color Attribute is in Span tag

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3497]
Regex is making the content blank in Featrues.php

`$content = preg_replace('/<span(.*?)(color=".*?")(.*?)>/', '<span class="test" $1$3>', $content);`

is making the content blank till the body.

**Comment by Rkroy** [comment]
No Content is showing and getting blank on AMP pages.
Ref: https://secure.helpscout.net/conversation/910882540/75207?folderId=2322649

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.2
