### ISSUE TITLE
Need to create a basic tutorial for each elements of single in Swift

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3499]
Need to create a basic tutorial/article for each elements in the single 
See: https://monosnap.com/file/v0mraHg7vdHJENftVaLYoN4nqM4bgh

**Comment by Zabi09** [comment]
Added "#" links for now and once all the tutorials are ready we will change that.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
