### ISSUE TITLE
Icons not loading When Icon Font Library is selected to  Font Awesome 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3501]
Icons not loading When Icon Font Library is selected to  Font Awesome 

1. Options panel : https://take.ms/JezS0
2. Post Editor : https://take.ms/POazZ6 
3. Output : https://take.ms/gTz9k

**Comment by MARQAS** [comment]
The issue is with Pagebuilder icons only

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
