### ISSUE TITLE
As I use AMP takeover, the sites are the same

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3502]
Ahmed, is there any way not to display the "visit amp"?

As I use AMP takeover, the sites are the same

 ![B57C383D-9534-4094-B36B-3AED73F4AE94](https://user-images.githubusercontent.com/16532359/61891751-fcb7cc80-af27-11e9-90be-fb4501903338.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
