### ISSUE TITLE
AMP Page builder is not working showing a pop up connection not establish

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3503]
Des: AMP Page builder not working showing a pop-up connection not establish. when we click AMP page builder a pop is getting connection not establish

https://secure.helpscout.net/conversation/904536997/74170/

**Comment by pegazee** [comment]
Actually, there is a third party plugin called "WP All Import Pro" in which the user is adding the unwanted code when calling the ajax because of this getting 500 internal server error. As of now, I'm closing this ticket. If anyone finds the same issue feel free to open this ticket.
