### ISSUE TITLE
Homepage amphtml not getting generated when there are no posts added.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3504]
If we do not create any posts and set up a custom front page, then no amphtml is created on the homepage.
Ref: https://secure.helpscout.net/conversation/911411024/75266?folderId=2322649

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
