### ISSUE TITLE
Meta description option should be enabled by default SEO

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3505]
Screenshot: https://monosnap.com/file/h6FOAb7UuWEpwSv9QG856RQuoLBdqT

- [x] Meta Description option should be enabled by default.

- [x] If anyone has disabled it then it should override it and it should be enabled.

**Comment by MohammedKaludi** [comment]
Ready

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
