### ISSUE TITLE
After the upgrade, AMP Page Builder is not working!

### ISSUE THREAD

**Issue by EltonDanielOliv** [ahmedkaludi/accelerated-mobile-pages#3506]
Prior to this last update, AMP Page Builder was working perfectly. Now it's not working!

Please correct it as soon as possible because my site needs it so badly!

**Comment by MARQAS** [comment]
Hi @EltonDanielOliv, Can you show me what is the problem you are facing? A screenshot or video will help me to resolve this ASAP.

**Comment by EltonDanielOliv** [comment]
Ok, I will make a video to clearly show the problem.

I will describe a bit of the problem so you can already take a look until I upload the video:

I enter the page, set Page Builder options, place columns, then buttons, feature, catergory, and advertisement, and mark the option to use Page Builder instead of the default Wordpress page.
When I refresh the page, every configuration I made on Page Buider goes away, it looks like I've never set it up.

Understand me?

**Comment by EltonDanielOliv** [comment]
Here is the video with the problem!

As you can see, when I leave the default Page Builder settings, it works.
But when I configure it according to my need, it clears all the settings.

Video: https://youtu.be/SnD6Iott1rU

**Comment by keshavsharma333** [comment]
One more user has this issue

Ref : https://secure.helpscout.net/conversation/915692970/76845?folderId=3044500

**Comment by nommanshaik18** [comment]
one more user facing this same problem

ref: https://secure.helpscout.net/conversation/916091598/76884?folderId=3081347

**Comment by nommanshaik18** [comment]
Another user

Ref: https://secure.helpscout.net/conversation/916770835/76975?folderId=3081347

**Comment by nommanshaik18** [comment]
Another user with this issue

Ref: https://secure.helpscout.net/conversation/917521657/77050?folderId=1060556

**Comment by keshavsharma333** [comment]
Another user with this issue

Ref: https://secure.helpscout.net/conversation/915873755/76867/

**Comment by TMsravan** [comment]
Another user facing the same issue

https://secure.helpscout.net/conversation/843373281/64521/

**Comment by MohammedKaludi** [comment]
Ready

**Comment by EltonDanielOliv** [comment]
The problem has not been fixed yet!

I did some tests to try to identify exactly what is conflicting.
I noticed that the problem only occurs when I insert links in the Feature or Text block.

**Comment by MohammedKaludi** [comment]
> The problem has not been fixed yet!
> 
> I did some tests to try to identify exactly what is conflicting.

@EltonDanielOliv The fix is not yet pushed, we are testing it final time before pushing the update. 

I'm plan to push the update with in 1 hour

Please do update to 0.9.98.3 and do let us know if the issue was fixed or not.

Please do wait for few more hours and you will see the code live.

**Comment by EltonDanielOliv** [comment]
Ok, I'll be waiting! Thank you so much for your attention and support!

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
