### ISSUE TITLE
In add on mode when amp is in standard mode frontend is getting blank screen.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3508]
Desc: In add on mode when amp is in standard mode frontend is getting blank screen.

**Comment by MohammedKaludi** [comment]
Need to add the check for standard mode.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/876cdea97dcdc55e6c78c2887496f062c24ed251#diff-04b38a94ddf918855eed7a68ecaa512dR174

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Incorrect conditions, 
The function `add_action('wp', function(){ ob_start('ampforwp_the_content_filter_full'); }, 999); ` 
will not run unless the other amp plugin is installed.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5a6810ab5fbd04ccf84c0f677f6fe902a91439c0#diff-04b38a94ddf918855eed7a68ecaa512dR184

**Comment by MohammedKaludi** [comment]
Ready  to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
