### ISSUE TITLE
Category module pagination is not working.

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3509]
when clicking on page 2 it is opening a single page rather than page 2 loop.
 
https://secure.helpscout.net/conversation/895447795/72678?folderId=3004564

**Comment by santosh8793** [comment]
Due to some issues the above code is added in 0.9.98 which is suppose to be added in 0.9.99 beta, need to make sure to add properly in master

**Comment by MohammedKaludi** [comment]
Code working in 9.9.98 branch. 
Ready to merge in 98.5 branch.

**Comment by MohammedKaludi** [comment]
ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
