### ISSUE TITLE
Double comments

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#351]
@khaledMohammed000 tested, this is a valid issue.

**REF:** https://wordpress.org/support/topic/comment-reply-error/

**Comment by khaledMohammed000** [comment]
hi there! :) Happy new year! Ahmed, can u please make full show comments on amp page, or in setting do a check to enable or disable comments. And sort comments by date. Thanks, after each update, to have to manually change the code.

**Comment by khaledMohammed000** [comment]
All done now the only issue is styling the children comments @ahmedkaludi @MohammedKaludi  , Its CSS :)

**Comment by khaledMohammed000** [comment]
@MohammedKaludi Please style the children : http://take.ms/ipKtk

**Comment by MohammedKaludi** [comment]
Proper Styling added for children comments

**Comment by MohammedKaludi** [comment]
Error after the new fix 
testing url http://magazine3.com/garage/microsoft-sets-feb-22-as-windows-7-sp1-public-launch/amp/

**Comment by MohammedKaludi** [comment]
Everything is working on khaled's test area and even looking good on my system 
http://take.ms/OMxFe

Double comment button here http://magazine3.com/garage/hands-on-dolphin-hd-browser-for-android-is-swimmingly-good/amp might be the cache issue.

Will wait for some time and test properly before closing the ticket

**Comment by MohammedKaludi** [comment]
Tested multiple environments and it seems working
