### ISSUE TITLE
 Need to add Read more link in excerpt for category module

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/accelerated-mobile-pages#3510]
https://secure.helpscout.net/conversation/895447795/72678?folderId=3004564

**Comment by MARQAS** [comment]
Escaping requires. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f35bb0f4cf3a47954487080c8f4b0119400c5567#diff-cb16861af9ff34ccd298041891008f49R255

**Comment by MohammedKaludi** [comment]
escaping missing
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f35bb0f4cf3a47954487080c8f4b0119400c5567#diff-cb16861af9ff34ccd298041891008f49R426

**Comment by MohammedKaludi** [comment]
Ready to merge in 0.9.98.5 branch,

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.98.4
