### ISSUE TITLE
Rare issue with Yoast SEO/Excerpt

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3511]
Yoast SEO Version 11.7 ----------AMPforWP Version 0.9.98.2

Ref: https://secure.helpscout.net/conversation/910603965/75155?folderId=3044500

Error: Warning: count(): Parameter must be an array or an object that implements Countable in homepages/30/d553713751/htdocs/www/wp-includes/post-template.php

**Comment by MARQAS** [comment]
https://core.trac.wordpress.org/ticket/42814

https://github.com/Automattic/jetpack/issues/8420

https://github.com/Automattic/jetpack/pull/8510

**Comment by ajeetku** [comment]
need to change `get_post_meta(ampforwp_get_the_ID())['_yoast_wpseo_metadesc'];` code

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
