### ISSUE TITLE
Page builder content getting blank when we hit save.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3513]
Page builder content is getting blank while adding a text module with the anchor tag, issue recreated at the local host.
Note: Not tested with previous versions.
Ref: https://secure.helpscout.net/conversation/914093066/76616?folderId=2322652

**Comment by Rkroy** [comment]
If we add image tag in the text module, the same issue of blank content after saving, please check.
Also, there is a warning displaying after saving:
Another user: https://secure.helpscout.net/conversation/913621392/76057?folderId=2322652

Warning: count(): Parameter must be an array or an object that implements Countable in /home/boominte/public_html/toocooltrafficschool.com/wp-content/plugins/accelerated-mobile-pages/pagebuilder/functions.php on line 66

**Comment by CG-TEAM** [comment]
Hi,
I have this issues and create ticket in wordpress.org forum support
https://wordpress.org/support/topic/amp-page-builder-problem/

When i add any element's in page builder that create it in previous version and update post/page all them gone.

**Comment by amer07** [comment]
> If we add image tag in the text module, the same issue of blank content after saving, please check.
> Also, there is a warning displaying after saving:
> Another user: https://secure.helpscout.net/conversation/913621392/76057?folderId=2322652
> 
> Warning: count(): Parameter must be an array or an object that implements Countable in /home/boominte/public_html/toocooltrafficschool.com/wp-content/plugins/accelerated-mobile-pages/pagebuilder/functions.php on line 66

We have another user with re-creatable situation. https://secure.helpscout.net/conversation/914856964/76723/https://secure.helpscout.net/conversation/914856964/76723/

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
