### ISSUE TITLE
Fatal error: Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3514]
Ref: https://secure.helpscout.net/conversation/914940407/76738?folderId=2770545

Fatal error: Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /www/htdocs/w018d9a7/citizenz.de/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php:545 Stack trace: #0 /www/htdocs/w018d9a7/citizenz.de/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php(443): AMPforWP\AMPVendor\AMP_Tag_And_Attribute_Sanitizer->validate_cdata_for_node(Object(DOMElement), Array) #1 /www/htdocs/w018d9a7/citizenz.de/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php(275): AMPforWP\AMPVendor\AMP_Tag_And_Attribute_Sanitizer->process_node(Object(DOMElement)) #2 /www/htdocs/w018d9a7/citizenz.de/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(132): AMPforWP\AMPVendor\AMP_Tag_And_Attribute_Sanitizer->sanitize() #3 /www/htdocs/w018d9a7/citizenz.de/wp-content/plugins/acce in /www/htdocs/w018d9a7/citizenz.de/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php on line 545

**Comment by MohammedKaludi** [comment]
Ready

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
