### ISSUE TITLE
Need to create compatibility with CDN enabler

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3515]
Thumbnail images of product not showing on home page when CDN enabler is active

Ref : https://secure.helpscout.net/conversation/912511426/75544?folderId=3044500

**Comment by ahmedkaludi** [comment]
Removing the CDN functionality is not the solution here. 

Can you please look into this @MohammedKaludi ?

**Comment by MohammedKaludi** [comment]
Code improvements needed that has been explained to @santosh8793

**Comment by MohammedKaludi** [comment]
Merge the code into 0.9.98.5 branch.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
