### ISSUE TITLE
Audio not working when Uploaded from Gutenberg editor

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3516]
Ref : https://secure.helpscout.net/conversation/915171152/76772?folderId=3044500

Post: https://itapunjabi.com/ice-cream-khan-wale-ho-jaao-saavdaan-with-audio/

Play button is showing but audio not working

**Comment by pegazee** [comment]
The URL of the audio must be the HTTPS, not the HTTP. If we add the HTTP, the amp-audio will not work.

**Comment by pegazee** [comment]
The URL of the audio must be the HTTPS, not the HTTP. If we add the HTTP, the amp-audio will not work.
