### ISSUE TITLE
Wp editor not loading when Using Page builder (with Gutenberg)

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3517]
This occures when we add a text module in the pagebuilder: TypeError: wp.editor.initialize is not a function

See: https://monosnap.com/file/XhFJbVVRSrBDAT3QKYCHvRQQMpIwew

**Comment by MohammedKaludi** [comment]
Ready.

**Comment by pegazee** [comment]
Pushed in 0.9.98.3
