### ISSUE TITLE
Rare issue with mb_convert_encoding

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#3521]
ref: https://secure.helpscout.net/conversation/915567449/76823?folderId=3008055

https://monosnap.com/file/eJIcqXhTbmpXpjcrjN7ffbgTsEsZcz

**Comment by MohammedKaludi** [comment]
Issue fixed from users end by enabling mb string encoding.
If anyone is facing the issue again then, we can reopen the ticket.
