### ISSUE TITLE
 AMP Page builder area getting blank (whole modules remove) when i hit update button

### ISSUE THREAD

**Issue by gdotmurtaza** [ahmedkaludi/accelerated-mobile-pages#3523]
Page builder area is getting blank while updating whole page modules when i click on page update button

**Comment by Zabi09** [comment]
@gdotmurtaza We are extremely sorry for the inconvenience we have already fixed this issue in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3506 please wait for one day and we are going to push the update by today and we are sure your issue will be fixed for sure

**Comment by gdotmurtaza** [comment]
I hope you have understand AMPforWP page builder issue and will resolve it soon
Thanks

**Comment by Zabi09** [comment]
@gdotmurtaza Have you updated our plugin to 0.9.98.3 version? is your issue fixed or not? Please let us know

**Comment by pegazee** [comment]
@gdotmurtaza , Can you please let us know whether the issue has been resolved or not

**Comment by pegazee** [comment]
This issue has been fixed v0.9.98.3 version, if anyone got the issue please contact our technical support team. We're closing this ticket.
