### ISSUE TITLE
Need to make compatibility with amp-connatix-player component

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3524]
https://amp.dev/documentation/components/amp-connatix-player/

https://secure.helpscout.net/conversation/912469527/75536?folderId=1060556

For more information:
https://pastebin.com/RUFhzUv5

**Comment by TMsravan** [comment]
Data has been added

**Comment by Zabi09** [comment]
For testing just add this code and it will work in non-amp version and also in AMP
<script>
!function(n){if(!window.cnx){window.cnx={},window.cnx.cmd=[];var t=n.createElement('iframe');t.display='none',t.onload=function(){var n=t.contentWindow.document;c=n.createElement('script'),c.src='//cd.connatix.com/connatix.player.js',c.setAttribute('async','1'),c.setAttribute('type','text/javascript'),n.body.appendChild(c)},n.head.appendChild(t)}}(document);
</script><br><script id="3a6f0cc4c9084034961205bbbb4ea926">
cnx.cmd.push(function() {
cnx({
playerId: '09c1d8b3-dfbe-406c-bc87-b658dae25642'
,      mediaId: '9eccf284-8067-42d6-b4ee-15739bf1a9c2'
}).render('3a6f0cc4c9084034961205bbbb4ea926');
});
</script>

**Comment by santosh8793** [comment]
Need to add script when 'amp-connatix-player' is loading in post or page

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
