### ISSUE TITLE
When using JNews AMP Extender, It makes posts blank

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/accelerated-mobile-pages#3526]
Ref: https://secure.helpscout.net/conversation/916909556/76984?folderId=3044500

The user when activating JNews AMP Extender, It makes AMP posts blank 

Plugin related to this ticket shared in the group

**Comment by ajeetku** [comment]
put this codes on correct place thirdparty-compatibility

**Comment by Zabi09** [comment]
Without adding the extra action hook, I have added the code here only because we need to remove with earlier execution of plugins_loaded

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
