### ISSUE TITLE
In swift theme  Navigation Menu Design issues in RTL mode

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3527]
desc: In swift theme  Navigation Menu Design issues in RTL mode
Screenshot: https://monosnap.com/file/4nqEwPOub1bvM3SeD8eO3WVGNhtkGU

ref: https://secure.helpscout.net/conversation/919426448/77297?folderId=3126461

**Comment by Zabi09** [comment]
Not working - https://prnt.sc/op0hlg

**Comment by MohammedKaludi** [comment]
👍 ready to push
