### ISSUE TITLE
"Recent Posts below Related Posts" option should show only when it is available for theme

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3528]
Screenshot: https://monosnap.com/file/dSnCMlAAwheqeLniDqU2krnzTRPKgT

"Recent Posts below Related Posts" option should show only when Swift theme it is available for the theme or else it should not show

**Comment by MohammedKaludi** [comment]
Ready

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.98.4
