### ISSUE TITLE
qtranslate-XT compatibility with AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3529]
https://wordpress.org/support/topic/menu-not-passing-translation-locale-w-qtranslate-xt/

**Comment by MohammedKaludi** [comment]
Issue reported: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3522

**Comment by MohammedKaludi** [comment]
Issue moved to https://ampforwp.com/compatibility/idea-board/
