### ISSUE TITLE
Structure data settings need testing

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#353]
The testing of structured data settings is needed.

**REF:** https://wordpress.org/support/topic/amphtml/
https://wordpress.org/support/topic/structured-data-values/

**Comment by Lofesa** [comment]
File templates/features.php

   
    584                                         $metadata['headline'] = $structured_data_archive_title;
    585                         }
    586 New                 if ($metadata['image']['width'] < 696) {
    587 New                    $metadata['image']['width'] = 700;
    588 New                  }
    589
    590                         return $metadata;
    591         }

**Comment by ahmedkaludi** [comment]
@MohammedKaludi I need to your updates on this

**Comment by Lofesa** [comment]
Hi @ahmedkaludi 
This is done, are the lines 698,699 and 700 in features.php. The PR was merged. You can close this

**Comment by ahmedkaludi** [comment]
thanks @Lofesa
