### ISSUE TITLE
Validation error when width and height is empty in the logo

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3530]
When the logo is at fixed width and the height and width is empty then the issue is happening.

See: 
![image](https://user-images.githubusercontent.com/16532359/62383059-9d336f80-b56c-11e9-9bbd-ba0949177e51.png)

https://wordpress.org/support/topic/amp-errror-amp-html-tag-has-an-invalid-layout-specified-by-its-attributes-2/#post-11791802

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.98.4
