### ISSUE TITLE
Validation error when adding featured video with Authentic theme

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3535]
Validation error when adding featured video with Authentic theme

![image](https://user-images.githubusercontent.com/16532359/62421169-2062db80-b6bb-11e9-9149-4e2085c7a4be.png)

https://wordpress.org/support/topic/two-issues-with-amp-implementation/#post-11797180

**Comment by MARQAS** [comment]
@Zabi09, Please check first if it is related to https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3444, If Yes, then we can close this ticket

**Comment by ahmedkaludi** [comment]
@MARQAS We don't need to close this ticket, we need to make it compatible with #3444's feature so the users of this theme can automatically add it.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
