### ISSUE TITLE
Gallery Captions not working 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3536]
check with 

- [x] Gallery captions

- [x] single image captions

Issue re-occurred on our testing envionrment: https://wordpress-123147-847862.cloudwaysapps.com/test/amp/

Issue reported on https://wordpress.org/support/topic/gallery-has-same-fig-caption/#post-11793611

**Comment by MARQAS** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ae9669e46efdf734bdda76eecdc23996273e8a6c#diff-810b0a0ef5832a51ef0ad2d39557d601R105
Please change it back to `post_excerpt`.

Also, remove the unwanted code: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ae9669e46efdf734bdda76eecdc23996273e8a6c#diff-55ac4f44eaa7f586b3210e4f1ac95fb2R228

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
