### ISSUE TITLE
If permalinks is set as "/index.php/%year%/%monthnum%/%day%/%postname%/" then not working properly with Pagination

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3537]
Ref: https://secure.helpscout.net/conversation/913825680/76331?folderId=2770545

When we set permalinks as "/index.php/%year%/%monthnum%/%day%/%postname%/" and if we remove the index.php from Permalinks then it is not working perfectly with permalinks.

Steps to recreate:

1. Change the permalinks as "/index.php/%year%/%monthnum%/%day%/%postname%/" 

2. Enable Pagination on AMP

3. Go For Second Page

4. Remove index.html from the URL

5. After refreshing it you will get 404 error

Screenshot: https://monosnap.com/file/4ZHX9BNIZtdnCk8dHCIzAd42CRl0tp

**Comment by Zabi09** [comment]
Not working on homepage loop

**Comment by MohammedKaludi** [comment]
With this permalink structure, working with master and not working with 0.9.99-beta

**Comment by MohammedKaludi** [comment]
Need to write the rewrite-rule  as well for the paginations to work in index and archive pages.

**Comment by MohammedKaludi** [comment]
pagination Still not working.

**Comment by MohammedKaludi** [comment]
Pagination is now working, but AMPHTML is not correctly generated.
https://take.ms/EXWtT

**Comment by MohammedKaludi** [comment]
Update user while merging.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/fb58abea04a5a64637b7e7fbce384a2cac5d51f2#diff-6aa5512f7dd8d5ce60fc97b0f340912cR314

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
