### ISSUE TITLE
Upgrade the analtyics integration with gtag.js

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3538]
https://developers.google.com/analytics/devguides/collection/amp-analytics/
https://developers.google.com/analytics/devguides/collection/gtagjs/

REF: https://wordpress.org/support/topic/google-analytics-issues/

**Comment by MohammedKaludi** [comment]
The Previous settings saved in the data base will break.
Need to improve the code.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
