### ISSUE TITLE
Need to add unique class name custom post type

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3539]
Ref: https://secure.helpscout.net/conversation/914408303/76664?folderId=2770543
We need to add a unique class in the custom post type.
When we see in amp version it showing like this: https://www.zuaneducation.in/php-training-courses/amp/
When we see in the non-amp version it showing like this: https://monosnap.com/file/lyZ3RTlzB6cp4bHj3NbLFywsPpAll9

Note: try this with a testimonial

**Comment by pegazee** [comment]
It would be better to add for the custom taxonomy. Currently, I've 2 custom taxonomy called "car" & "vehicle" and it shows only custom post type name.
Screenshot: 
1) https://take.ms/fpj3W

**Comment by pegazee** [comment]
Getting post name on the taxonomy
Screenshot: https://take.ms/9SjeD

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
