### ISSUE TITLE
menu no longer works

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#354]
After the last update today the amp menu no longer works. I’m going back a version until this new issue is resolved
**REF:**https://wordpress.org/support/topic/amp-homepage-shows-envira-id/

**Comment by ahmedkaludi** [comment]
We need to the testing of this to understand what's not working in the Menu?

**Comment by MohammedKaludi** [comment]
Fixed in previous updates
