### ISSUE TITLE
yoast breadcrumb making all ul list in capital letters

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3540]
when user enabled yoast breadcrumb making all ul list in capital letters on pages

Ref: https://secure.helpscout.net/conversation/918328944/77183?folderId=3081347

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
