### ISSUE TITLE
Image is not aligned properly 

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3542]
Image is not aligned properly showing after the sidebar on pages

screenshot https://take.ms/KrAd2C

Ref: https://secure.helpscout.net/conversation/918328944/77183?folderId=3081347

**Comment by ahmedkaludi** [comment]
**TESTING**

- [ ] Make sure the content comes first and the sidebar comes second in the mobile responsive as per Sidebar #3541

**Comment by pegazee** [comment]
on desktop, the sidebar shows after the content.
Screenshot: https://take.ms/ijJYn

**Comment by MohammedKaludi** [comment]
not working properly, markup seems to be broken.

**Comment by MohammedKaludi** [comment]
Add this not aligned correctly.

**Comment by MohammedKaludi** [comment]
1. Add this position is still incorrect. https://take.ms/ebk7c
2. Custom front-page showing sidebar incorrectly https://take.ms/b3cbD

**Comment by MohammedKaludi** [comment]
no content visible due to incorrect condition.

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
