### ISSUE TITLE
Not able to update to version 0.9.98.4

### ISSUE THREAD

**Issue by rahul4u2019** [ahmedkaludi/accelerated-mobile-pages#3544]
The website goes in maintenance mode when I try to update the plugin and even after few minutes the mode does not change. It never finishes updating. I tried updating 2-3 times after removing cache and tried on different machines as well.

**Comment by pegazee** [comment]
@rahul4u2019 

Could you please check now?

**Comment by rahul4u2019** [comment]
It is quite strange as I am still facing similar issue. I have update other plugins yesterday and today as well, but not facing long down time during their update. I have to delete the maintenance file via ftp to make the website up again.

I got the following error after waiting for 15-20 minutes today - 

`Update Failed: <!DOCTYPE html> <!--[if lt IE 7]> <![endif]--> <!--[if IE 7]> <![endif]--> <!--[if IE 8]> <![endif]--> <!--[if gt IE 8]><!--> <!--<![endif]--> | 504: Gateway time-out <!--[if lt IE 9]><![endif]--> body{margin:0;padding:0} Error 504 Ray ID: 50283a603f2b703c &bull; 2019-08-07 09:30:28 UTC Gateway time-out <!-- /.error-overview --> You Browser Working Singapore Cloudflare Working Host Error <!-- /.status-display --> What happened? The web server reported a gateway time-out error. What can I do? Please try again in a few minutes. <!-- /.section --> Cloudflare Ray ID: 50283a603f2b703c &bull; &bull; Performance &amp; security by Cloudflare <!-- /.error-footer --> <!-- /#cf-error-details --> <!-- /#cf-wrapper -->`

**Comment by rahul4u2019** [comment]
@pegazee I tried again and even after showing the same error (as mentioned in my previous comment), the plugin is updated. It is not showing any update notification anymore. Thanks for your time & efforts :)
