### ISSUE TITLE
Delete button gone in page builder in RTL language

### ISSUE THREAD

**Issue by CG-TEAM** [ahmedkaludi/accelerated-mobile-pages#3545]
Hi,
In my Arabic site  Delete button in element of page builder is gone. i found this class:
.modal-footer .del-btn-modal {left: 215px;}
The value for position of delete element button. If they change to
.modal-footer .del-btn-modal {right: 80%;}
The position in RTL language delete button is appeared again.
Please review this issue for next plugin update.

Thank you.

**Comment by MohammedKaludi** [comment]
Use default class instead of creating a new div.

Remove the newly created markup and align using default class with css.

https://take.ms/qQq4I

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
