### ISSUE TITLE
h1 was changed to h2 in the custom frontpage title after update

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3546]
recreated on localhost.
https://wordpress.org/support/topic/home-page-title-changed-from-h1/

**Comment by MohammedKaludi** [comment]
use function exists or class exists. 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1fc2139de5bbf76522c7736a3ec3e010e47a91e4#diff-faa0de5ca21c9b30acb415cc2d0334b4R349

**Comment by MohammedKaludi** [comment]
code improvement required in `ampforwp_design_3_frontpage_title()`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1fc2139de5bbf76522c7736a3ec3e010e47a91e4#diff-faa0de5ca21c9b30acb415cc2d0334b4R345

**Comment by MohammedKaludi** [comment]
Alignment is incorrect in D2  https://take.ms/vjum1

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
