### ISSUE TITLE
Need to save Post Meta Field Revisions in WordPress

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3548]
Ref: https://johnblackbourn.com/post-meta-revisions-wordpress/

Help Scout Link: https://secure.helpscout.net/conversation/919368029/77293?folderId=2770545

We need to save Post Meta Field Revisions in WordPress. If the user is using AMP Page Builder and if he changes the layouts then his previous layouts information should be saved in Post Meta Fields Revision.

**Comment by ajeetku** [comment]
add user security `current_user_can` scurity before save post content

Sanitize before insert in `add_metadata`

**Comment by MohammedKaludi** [comment]
Need to check if user has the permission or not.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3bd55557e1dc6da5892fb18ca5c699b7305f4127#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7133

Like this: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3548#issuecomment-526031026

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
