### ISSUE TITLE
Table is not aligning properly in amp version

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3549]
Ref: https://secure.helpscout.net/conversation/922751856/77679?folderId=2770543
Note: 
The table is not aligned properly in amp,
I have created a post in that I have added some table code than I view post in the non-version table is alignment is perfect in the center, whereas in amp version alignment is missing it goes to the right side, below I will provide screenshot it may be useful 
See this screenshot:
1. http://tinyurl.com/yy4hctec
2.http://tinyurl.com/y2z3wo82

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
