### ISSUE TITLE
Need to make compatible with yoast seo primary category option

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3551]
Need to make compatible with Yoast primary category, when Yoast plugin is active when the primary category is selected then it's not taking that.
Need to make compatible with all design along with AMP Newspaper theme.

please see these screenshots:
https://monosnap.com/file/oZyao4lLLYeYTUyP7Em7z6IwURrrgy

REF:https://secure.helpscout.net/conversation/920928937/77449?folderId=3008055

**Comment by ajeetku** [comment]
use: get_post_meta(ampforwp_get_the_ID(), '_yoast_wpseo_primary_category', true) in place of if condition

**Comment by ajeetku** [comment]
Need to change in all design `get_post_meta`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
