### ISSUE TITLE
Getting Debug error ( cdn_url_main )

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3555]
Ref: Notice: Undefined variable: cdn_url_main in /home/sa18823y/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php on line 142

https://monosnap.com/file/kWFQTCJ7OvwPSycI3WzisOMZ12bVEB

https://secure.helpscout.net/conversation/924358049/77826?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
