### ISSUE TITLE
SSR support in Amp for wp 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3557]
Ref:https://secure.helpscout.net/conversation/924639848/77893?folderId=2770543
Url: https://blog.amp.dev/2019/08/07/faster-amp-on-the-origin-amp-ssr/

**Comment by ahmedkaludi** [comment]
https://secure.helpscout.net/conversation/1013687099/99157?folderId=3243584

**Comment by MohammedKaludi** [comment]
will be fixed in #5034
