### ISSUE TITLE
Woocommerce archives and shop page support should not be dependent on Archives [Category & Tags] option.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3558]
Desc: Woocommerce archives and shop page support should not be dependent on Archives [Category & Tags] option.

**Comment by MARQAS** [comment]
Can we improve the conditions @syedimran22?

**Comment by santosh8793** [comment]
Not getting redirected to non amp when AMP woocommerce pro is deactivated and archive support is off

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
