### ISSUE TITLE
Add Avia page builder(Enfold) support in pagebuilder section

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3559]
Add Avia page builder support in a page builder section
Notice to the user we are supporting AVIA(Enfold page builder) support

**Comment by MohammedKaludi** [comment]
Inconsistant labeling
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d2c267b2aab63706bc3b7f78b37f3ab6005d94a0#diff-5895a61b30d9c99c1599b6776fbeecacR123

**Comment by MohammedKaludi** [comment]
Same with #3550

**Comment by MohammedKaludi** [comment]
ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
