### ISSUE TITLE
allow option to change the heading tag of Featured module 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3560]
https://wordpress.org/support/topic/change-h3-tag-2/

**Comment by Zabi09** [comment]
The headings tags are working as expected but the CSS is not appearing on other headings
H3 output - https://monosnap.com/file/OJ7jtAyShMAhQ7VjnKxZnK3RKdLdxS
H1 output - https://monosnap.com/file/5zjAy5FeitFTppKYZK9fS8ozeSSXlk

and also please change the label - https://monosnap.com/file/MLTFh5p2sUE4UsOlZT0CVgLoAEn9Do

**Comment by MohammedKaludi** [comment]
if no option is selected then default should be loaded. https://take.ms/p3iw2
https://take.ms/TpMEn

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
