### ISSUE TITLE
Change Internal Links to AMP

### ISSUE THREAD

**Issue by luan03** [ahmedkaludi/accelerated-mobile-pages#3561]
Hi guys,

The option **Change Internal Links to AMP** is changing my links to subdomains as well.

example: pebmed.com.br/amp has an external link to events.pebmed.com.br in which is added /amp. This generates a broken link as bellow:

events.pebmed.com.br/amp

**Comment by MohammedKaludi** [comment]
Need to retest the issue.

**Comment by wasimmagazine3** [comment]
Tested the issue. It is working as expected

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8

**Comment by luan03** [comment]
When this fix will be available?

**Comment by luan03** [comment]
It's working guys! thank very much.

**Comment by MohammedKaludi** [comment]
sub.doamin.com to doamin.com
