### ISSUE TITLE
Template-mode: admin settings need filters to show or hide option

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3562]
In template-mode, create a filter to hide/show for options tab. 
User can add and remove as there need by the filter.

Improvement:
1. in place of remove options from Redux use hidden, so other options will not reset

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
