### ISSUE TITLE
Improvement in iframe

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3563]
- [x] add "allow-forms" sandbox  attribute in the amp-form

- [x] automatically add the script of the iframe when adding code in custom amp editor

Code to test iframe: 
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe6X3Ni7kRR6Nmqx56zEJsacD7sB2-7cwEj1tDoyYovzTw64g/viewform?embedded=true" width="420" height="579" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe> 

Ref: https://secure.helpscout.net/conversation/931501996/78562/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Update the vendor changelog while merging

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/962fc70c6074eb9beaf2f405a507f8651700388a#diff-2e23528863132d335b0def5ce68b9cc9R10

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
