### ISSUE TITLE
noreferrer is getting added automatically, it should have what ever the user passes.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3566]
To recreate, add the below content
`<a href="https://google.com" rel="nofollow">Vous voudriez vous ouvrir un peu plus aux autres ? Ou bien développer vos compétences</a> sociales ? Si c'est le cas, vous devez d'abord apprendre à être plus conscient(e) de votre image personnelle.`

in the output, you will see noreferrer with the nofollow as well, see: https://monosnap.com/file/tOV2nC8hClzVgGBsH4PfsfUShMyF2E

REF: https://wordpress.org/support/topic/relnoreferrer-issue-in-affiliate-link-in-amp-for-wp/#post-11841642

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.5
