### ISSUE TITLE
Structured Data improvements.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3567]
- [x] If we choose "X" then it should turn off the schema on that post type: https://monosnap.com/file/RJr1PlPHMemtwpDofkSnhm6Q6TLkp2

- [x] Need to add an option to fetch schema from the Yoast: https://imgur.com/a/qiHqL9U

**Comment by iamkingsleyf** [comment]
following

**Comment by Zabi09** [comment]
The default schema is not getting generated when we deactivate the Yoast, Will you please check once

**Comment by MohammedKaludi** [comment]
Escaping missing 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8faf2c6587af6889196dddabd323fa2d770ab688

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by iamkingsleyf** [comment]
Nice
👍🏿👍🏿👍🏿👍🏿👍🏿👍🏿👍🏿👍🏿

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.6

**Comment by iamkingsleyf** [comment]
please check #3607
