### ISSUE TITLE
Spot.IM Comments not working on all designs.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3568]
Spot.IM Comments not working on all designs.
Ref: https://secure.helpscout.net/conversation/872116232/69813?folderId=2322651

O/p: https://monosnap.com/file/dQfCq3UB4hllAPD6Z7MWwfUGuacOwx
Expected O/p: https://monosnap.com/file/bEsUvkpm7MhgnH4kwX2yScQc8fmRUi

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/935813422/78974/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.6
