### ISSUE TITLE
Login Redirect Loop

### ISSUE THREAD

**Issue by mehulboricha** [ahmedkaludi/accelerated-mobile-pages#3569]
After enabling the plugin I am unable to login to the WordPress admin panel. It just keeps redirecting to the login page. This is a very critical issue kindly fix this ASAP.

**Comment by ahmedkaludi** [comment]
The Github is meant for known issues. Kindly check on a staging site and see if the issue occurs. If it does then try to deactivate the plugins one by one to see which one is causing it, you should be finding your problem by then.

**Comment by mehulboricha** [comment]
Hello Ahmed,

I have posted this here because this is happening with multiple sites I have the plugin installed not just a single one.
