### ISSUE TITLE
Post comment button

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#357]
post comment button clicking on which it will take the user to the main page to post comments

**REF:** https://wordpress.org/support/topic/have-a-few-questions-regarding-comments/

**Comment by khaledMohammed000** [comment]
The button now appears on both the Designs even if the Comments are deselected from Design Manager

**Comment by ahmedkaludi** [comment]
There are some problems with this solution:

1. We don't need two comments button to appear, see: http://take.ms/3L8vF
2. The position of the static comment button should not be at the end the page.

@khaledMohammed000 Can you suggest any other solutions for this?
@MohammedKaludi I would appreciate your input on this.

**Comment by khaledMohammed000** [comment]
@ahmedkaludi am on it

**Comment by MohammedKaludi** [comment]
Looks ok, working on both designs.
