### ISSUE TITLE
Infinite scroll script is adding in woocommerce archive pages

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3570]
Infinite scroll script is adding in woocommerce archive pages 

Ref: https://secure.helpscout.net/conversation/921493365/77530?folderId=3081347

Screenshot: https://monosnap.com/file/Ut3RIib4wivtONxeq5lNVn5FT8QwvF

**Comment by santosh8793** [comment]
Need to add condition for is_product_tag() archive

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
