### ISSUE TITLE
No Icon in Facebook Message when Font Awesome Icon type selected

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3572]
No Icon in Facebook Message when Font Awesome Icon type selected

https://take.ms/897y1 

Also need to update the Label: https://take.ms/xtwWx

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
