### ISSUE TITLE
caption design is different when comparing Gutenberg and classic editor 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3573]
Gutenberg Image Block: https://monosnap.com/file/1602abXhXp9O5Q2Q9wihe8ZHb0yuz9
Classic Editor: https://monosnap.com/file/iQuKHJrQuHnQiqlAOUtyJiZc87uR5m

REF: https://wordpress.org/support/topic/titles-of-images-arent-centered/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
