### ISSUE TITLE
The "redirect chain" report taking extra steps to process.

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3575]
"redirect chain" report taking extra steps to process. When clicking on view on non-amp then it will take 3-4 steps to reach the page.

see this screenshot:
https://monosnap.com/file/AHDDC1bWqA11Pz7xtorGOpvMa1SFSS

REF:https://secure.helpscout.net/conversation/936061034/79016?folderId=3008055

**Comment by MohammedKaludi** [comment]
can we use `user_trailingslashit` instead of `trailingslashit` ?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/14fb0dd47d0c6fddd38c46d041e2af0f18ac84d3#diff-ab576767b896423d184ddafe2ede2310R64

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
