### ISSUE TITLE
Tags are appearing below the comments section in mobile view

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3576]
Tags are appearing below the comments section in the mobile view, It needs to show below the post content.

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/932256832/78631?folderId=2632030

**Comment by ahmedkaludi** [comment]
Discuss the ticket with me when you are working on this.

**Comment by TMsravan** [comment]
This ticket will be closed by this ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3140
