### ISSUE TITLE
 Telegram links removed

### ISSUE THREAD

**Issue by Agon2299** [ahmedkaludi/accelerated-mobile-pages#3577]
Hi guys,

Links of telegram remove on amp pages. Links of telegram have format:
tg://resolve?domain={namedomain}

I know that your plugin has a validate_a_node function and there is an array of valid protocols there. Could you add the tg protocol, or add a filter for valid protocols.

Thanks.

**Comment by ahmedkaludi** [comment]
We are going to implement this in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3578
