### ISSUE TITLE
Plugin removes Telegram links

### ISSUE THREAD

**Issue by shchedrakov** [ahmedkaludi/accelerated-mobile-pages#3578]
Plugin removes links to Telegram channels like `tg://resolve?domain={chanel}`. Are you planning to allow using such links? When?

Telegram is one of the best and most popular world's messengers. I think it's wrong that the plugin removes such links.

**Comment by ahmedkaludi** [comment]
Yes, this is one of the most important one! We will definitely add this.

I'm adding this to our dev roadmap, it'll be added to the next milestone very soon and pushed in few weeks.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.6
