### ISSUE TITLE
Optimize amp pages 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3579]
Few things we can adapt to improve ourselves. From https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/optimize_amp/

**Comment by wasimmagazine3** [comment]
Performance optimization for hero images is pending if loading dynamically.

**Comment by MohammedKaludi** [comment]
> Performance optimization for hero images is pending if loading dynamically.

this will be fixed in #3688

**Comment by MohammedKaludi** [comment]
Update the vendor change log while merging.

**Comment by MohammedKaludi** [comment]
Need to make sure that this still works after the scripts code that we changed.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d0cf5d86a7d3f4570397d97778ba3a474f548a93#diff-9f65b1edeb6d18b3cc5f9f2a21bfd824R30

and update the code in 1.0+ branch.

**Comment by MohammedKaludi** [comment]
Need to add fallback for Hook  `ampforwp_last_head`  to `amp_post_template_head` to make sure that if `ampforwp_last_head` is not available then the it should append to fallback hook, 

If we do not add it, then it will break layouts, custom designs and lot of AMP themes.


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2270280439fb161bd72abb5fd99888acf14b2735#diff-9f65b1edeb6d18b3cc5f9f2a21bfd824R82

**Comment by MohammedKaludi** [comment]
Ready to merge.

need  to make sure we add only this code 


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2270280439fb161bd72abb5fd99888acf14b2735#diff-9f65b1edeb6d18b3cc5f9f2a21bfd824R43

not the hooks.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
