### ISSUE TITLE
Title of the page should be displayed on the FrontPage

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#358]
Title of the page should be displayed on the FrontPage

**Comment by khaledMohammed000** [comment]
Please use this ID : title

I have styled the above title using the above ID for both the Designs

**Comment by MohammedKaludi** [comment]
- [ ] Realignment  of the Controls http://take.ms/sEMdg

- [ ] Use the correct markup as single http://take.ms/tJiW5 and it should be http://take.ms/cC7or

- [ ] Remove the styles you added
