### ISSUE TITLE
amp-addthis validation error on pages

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3580]
Getting this validation error: _The extension 'amp-addthis' was found on this page, but is unused. Please remove this extension_

**To re-create**
1. Reset all settings
2. Setup these options
![image](https://user-images.githubusercontent.com/16532359/63633670-adb9a000-c669-11e9-97e0-1524c46164f0.png)
![image](https://user-images.githubusercontent.com/16532359/63633673-b0b49080-c669-11e9-88ba-8afcd376295c.png)
3. Check the pages.

If not re-creating then let me know, I will help you recreate the issue.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.6
