### ISSUE TITLE
optimize the TEL link to remove validation and provide better UX

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3581]
If the "https://tel:878957026/" found, the output should automatically remove "http or https" and show the proper tel

**Comment by Zabi09** [comment]
It should remove only on tel protocol, but it is removing in all "tel" text 
https://prnt.sc/oymnu7

**Comment by MohammedKaludi** [comment]
Ready to merge. 
But need to discuss with me and ahmed before merging.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
