### ISSUE TITLE
Create a filter to Exclude Posts from Related Posts

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#3582]
I have some pages which just don’t fit as related posts. I just would like to decide to have them removed for various reasons.

jetpack gives me this

function jetpackme_exclude_related_post( $exclude_post_ids, $post_id ) {
// $post_id is the post we are currently getting related posts for
$exclude_post_ids[] = 1037; // Exclude post_id 1037.
$exclude_post_ids[] = 1038; // Also exclude post_id 1038.
return $exclude_post_ids;
}
add_filter( ‘jetpack_relatedposts_filter_exclude_post_ids’, ‘jetpackme_exclude_related_post’, 20, 2 );

similar i need for ampforwp?

**Comment by ajeetku** [comment]
Before put in query check variable is an array or not

**Comment by Zabi09** [comment]
Here is the tutorial link - https://ampforwp.com/tutorials/article/how-to-exclude-posts-from-related-posts/

**Comment by MohammedKaludi** [comment]
The approach to the fix can be improved, instead of providing a filter for every item create a filter to modify all the `$args` at the end before passing it in `wp_query`

**Comment by MohammedKaludi** [comment]
incorrect position of the filter.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a23644fbf3747284e47876dab0cccfef50ae909b#diff-4df5c887c9bf062e619962dc7e2c804eR65

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
