### ISSUE TITLE
Need to check function exist get_cart_url as it is getting fatal error when only amp woocommere  is active.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3584]
Desc: Need to check function exist get_cart_url as it is getting fatal error when only amp woocommere pro is active.
Line :  https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php#L5286

**Comment by ajeetku** [comment]
This fix will not work please check 
https://docs.woocommerce.com/wc-apidocs/annotation-group-deprecated.html this function is 
 deprecated in `get_cart_url` version 2.5.0
`$link = function_exists( 'wc_get_cart_url' ) ? wc_get_cart_url() : $woocommerce->cart->get_cart_url(); `

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
