### ISSUE TITLE
Need to connect with Collapse references by default option of the footnotes plugin.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3586]
Need to connect with Collapse references by default option of the footnotes plugin.
Note: This user has been facing issue since long time, please treat this issue as a high priority.
Ref: https://secure.helpscout.net/conversation/927154014/78145?folderId=2322651

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
