### ISSUE TITLE
Show the number of shares with Sassy Social Share

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3588]
REF: https://wordpress.org/support/topic/share-count-with-social-media-sharing/

**Comment by SayyadF** [comment]
Another one customer asking for this feature.
REF:https://secure.helpscout.net/conversation/950445427/81375?folderId=3008055

**Comment by MohammedKaludi** [comment]
Save the css in the transient 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0f436f836e1176c2e7bd9030f1a0699122c98616#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7394

**Comment by MohammedKaludi** [comment]
Need to improve the function name:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a878959d9e28b91545768ab78fb3d30077229302#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7428


`css_sanitizer` to `ampforwp_css_sanitizer`.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
