### ISSUE TITLE
Facebook like button is not aligned properly 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3589]
Facebook like button is not aligned properly when we click Facebook like it is moving a little bit up.

Before click:https://monosnap.com/file/ghu4qUzuQjueSboUSM48kiSqjZ0na0

After clicking it: https://monosnap.com/file/ZHy2JTwyzT0UkmV3mHSqo56TwiF9EY

Also In the social sticky bar, Facebook like button has its number cut off when it goes more than 3 digits.

Please see this screenshot: https://monosnap.com/file/LOugHLBDn544E7jriASPqnqXGkI6Gm

https://secure.helpscout.net/conversation/935902612/78984?folderId=2632030

**Comment by ajeetku** [comment]
Why inline style used here?

**Comment by MohammedKaludi** [comment]
Still alignment issue, shown to Zabi

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Now its looking good.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
