### ISSUE TITLE
Template mode: Need to changes/fixes

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3590]
- [x] Template mode will not load in preview mode like: elementor editing any page
 check with divi also
- [x] Fix: on form sanitation function in post method, do not change if action-xhr already present

**Comment by RajuJeelaga** [comment]
Make sure we need to push this update in 0.9.98.7

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
