### ISSUE TITLE
AAWP plugin for AMP compatibility in Extension list

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3591]
AAWP plugin for AMP compatibility in Extension list

slug: aawp-for-amp
name: AAWP for AMP
URL: http://ampforwp.com/addons/aawp-for-amp/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
