### ISSUE TITLE
Rank math Titles & Meta compatibility

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3592]
Rank math Titles not viewed in AMP

Ref: https://secure.helpscout.net/conversation/941871486/79570?folderId=3081347

![Screenshot_20190829-091057](https://user-images.githubusercontent.com/44563327/63940053-51e68100-ca86-11e9-8245-6040bc9607b2.png)

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
