### ISSUE TITLE
Comments should be removed in the out put of Analytics Code 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3593]
Comments should be removed in the output of the Analytics Code. Comments should not render in the output of the Analytics Code.

Because of this waring is appearing in the AMP validator

Please see this screenshot:

https://monosnap.com/file/wljTUrQv18fzCiITB3paLMA96BfcPm

Before comment in the code: https://monosnap.com/file/EqCfMCP49yaUtkMPhubQ81q4C1fZcL

After removing comment: https://monosnap.com/file/EPf0vrriQUkKpeAMADLKweXEmZ6jEf

**Comment by brateanugeorgeflorin** [comment]
Thank you for the clarification. 
I have successfully removed that comment inside Analytics Code in JSON Format.
Now it's green, no more warnings.

Now I will try to check if AMP pages are tracked in Google Analytics.
I will be back with a response if every AMP article page is tracked in GA.

**Comment by MohammedKaludi** [comment]
This ticket will no longer be required to fix in #3494 
Need to test it once before closing

**Comment by Zabi09** [comment]
in #3494, We are removing our default comments but in this ticket, we are removing the comments which are added by the user manually.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
