### ISSUE TITLE
Webp feature image not working.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3594]
Ref:https://secure.helpscout.net/conversation/941671607/79542?folderId=2770543
this type of issue already closed #2996,
Issue is recreated in local as well as user
See these screenshots:
1.https://prnt.sc/oz5mef
2.https://prnt.sc/oz5mst

**Comment by Zabi09** [comment]
This issue is with the AMP Newspaper theme and it is going to fix in - https://trello.com/c/28qfxbpg/1005-webp-feature-image-not-working
