### ISSUE TITLE
 Related post excerpt is not working with horizontal design

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3595]
See this screenshot:
https://monosnap.com/file/3azBnpiOelhwVJjq7v7LrC40KSCCHX

REf:
https://secure.helpscout.net/conversation/941832864/79567?folderId=3008055

**Comment by nakib4tech** [comment]
It is not showing with the Newspaper Theme also, please check:)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by merajali294** [comment]
@nakib4tech, the feature of horizontal design is built only for the Swift Design which is basically the Design 4

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
