### ISSUE TITLE
Need to add the controls in Related posts settings same as Recent posts in Swift

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3596]
See this screenshot:
https://monosnap.com/file/VLz7l9cu1IjYUsZFbEweBLeymTR6nW

**Comment by pegazee** [comment]
I've added the 'excerpt' and 'link to non-amp' options in recent post section as I've discussed these with @ahmedkaludi.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
