### ISSUE TITLE
Gutenberg Audio Module not working

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3597]
Bug reported by user and also recreated in localhost.

REF: https://wordpress.org/support/topic/embedded-audio-not-working/#post-11877111

**Comment by Zabi09** [comment]
HTTP is not allowed in amp-audio
Getting this error - Invalid URL protocol 'http:' for attribute 'src' in tag 'amp-audio'.

Ref: https://amp.dev/documentation/examples/components/amp-audio/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
