### ISSUE TITLE
Issue in Breacrumb if category has a comma

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3598]
I have a category name with a comma, but in AMP version where there is the comma, the link in the breadcrumb is broken. It replace the “,” with a “►”.

Recreated in the local as well
https://wordpress.org/support/topic/issue-in-breacrumb-if-category-has-a-comma/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.8
