### ISSUE TITLE
The lightbox should not work for the image if any external link is added in its anchor tag.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3599]
The lightbox should not work for the image if any external link is added in its anchor tag.
Ref: https://secure.helpscout.net/conversation/940704858/79423?folderId=2322651

**Comment by TMsravan** [comment]
Another user facing the same issue: https://secure.helpscout.net/conversation/946317891/80143?folderId=2632030

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9

**Comment by ahmedkaludi** [comment]
https://focusingonwildlife.com/test-platform5/petition-ban-hunters-from-killing-hibernating-bears-and-cubs/amp/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.11

**Comment by Zabi09** [comment]
Pushed in 0.9.98.11
