### ISSUE TITLE
AMP errors in Google Search Console

### ISSUE THREAD

**Issue by rooie1971** [ahmedkaludi/Accelerated-Mobile-Pages#36]
Hi,

Just recently started to explore amp, and using your plugin in our site, however the search console gives errors about a facebook tag...

Details:	
The tag 'fb:like' is disallowed.
The tag 'fb:comments' is disallowed.
AMP URL:	
http://www.pfx.nl/maandag-tot-maandag/?amp
Canonical URL:	
http://www.pfx.nl/category/geen-categorie/page/2

Is this something that can be stripped by the plugin, it's just a facebook like button.

Regards,
Richard

**Comment by ahmedkaludi** [comment]
Hey Richard,

Thank you so much for reporting the bug, it allows us to help you and help the community.

We will fix this bug and release an update very soon.

Regards,
Ahmed

**Comment by MohammedKaludi** [comment]
@rooie1971 are you using any plugins to add the facebook comments in the single post?

**Comment by rooie1971** [comment]
Yes I'm using sider facebook to add the facebok buttons.

**Comment by ahmedkaludi** [comment]
Hey @rooie1971  Please update to the new version 0.7.7 - It should fix this issue. 

If you like the plugin then please help us by leaving a review in the plugin reviews section.

Regards,
Ahmed

**Comment by rooie1971** [comment]
Thank you, seems ok as far as i can see.
