### ISSUE TITLE
too many error

### ISSUE THREAD

**Issue by fikryans** [ahmedkaludi/accelerated-mobile-pages#360]
what's going on with accelerated mobile pages after new update??
thats too many error in google console!
![selection_014](https://cloud.githubusercontent.com/assets/8897997/21583960/9377cce2-d0c8-11e6-87e4-1350c7d87c34.png)

**Comment by nicholasgriffintn** [comment]
Use an amp validator like this one:

https://validator.ampproject.org/

Simply copy in one of your AMP URLs and it will show the errors that occurring and the place in the code that they are occurring in.

**Comment by ahmedkaludi** [comment]
Hey @fikryans 
Can you please post the website URL? it would allow us to help.

**Comment by fikryans** [comment]
https://www.tutorialpedia.net
the problem always show up when i updated new version of amp

**Comment by nicholasgriffintn** [comment]
I tested validator with five of your pages, all of them passed, so it's either a case of only some pages have an issue, or the issue is still fixed.
