### ISSUE TITLE
Need to move "Breadcrumbs From Yoast" to SEO option Panel section.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3600]
Screenshot: https://monosnap.com/file/nmpkslbZwTP8S18FYFWdSANEFPVKCj
  
 We need to move the "Breadcrumbs From Yoast" from Single option panel to SEO option Panel section.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
