### ISSUE TITLE
Need to allow the user to navigate if user is using iframe

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3601]
Console Error: Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://www.thecorporatethiefbeats.com' from frame with URL 'https://corporatethief.infinity.airbit.com/?config_id=2325&embed=1#amp=1'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

HelpScout Link: https://secure.helpscout.net/conversation/940768169/79433?folderId=1060554

Need to add this attribute in the sandbox to allow the user to navigate properly:
"allow-top-navigation"

**Comment by keshavsharma333** [comment]
One more user has this issue. Get price button is not working.
https://taxi-brussels.com/amp/
Ref: https://secure.helpscout.net/conversation/939686170/79347?folderId=3044500

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9
