### ISSUE TITLE
Small sized images are getting stretched in the lightbox.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3602]
Small-sized images are getting stretched in the lightbox.
Ref: https://secure.helpscout.net/conversation/927154014/78145?folderId=2322651
Reference code: 
![lightbox](https://user-images.githubusercontent.com/43204388/64020299-e74d4800-cb4e-11e9-84fc-e7127f5c79df.png)

**Comment by Zabi09** [comment]
https://github.com/ampproject/amp.dev/issues/2913

**Comment by ajeetku** [comment]
For grab extension/name usw `wp_check_filetype` or `wp_check_filetype_and_ext`  
to get appropriate result

**Comment by MohammedKaludi** [comment]
Fix  not working, breaking the image/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
