### ISSUE TITLE
AMP takeover is not working for homepage if page support for AMP is disabled

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3604]
A user experience that while applying AMP takeover beta when the custom front page is enabled for AMP then if page support for AMP is disabled. In this scenario, AMP takeover beta is not working need to improve on this.
(user using DIVI page builder plugin)
Ref: https://secure.helpscout.net/conversation/936591104/79072?folderId=3126461

**Comment by Zabi09** [comment]
Unable to recreate the issue, So closing this ticket - approved by @ahmedkaludi
