### ISSUE TITLE
Notice: Undefined variables

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#3605]
Notice: Undefined variable: cdn_url_main in D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\vendor\aq_resizer.php on line 142

Notice: Undefined variable: cdn_url_main in D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\vendor\aq_resizer.php on line 142

Notice: Undefined variable: cdn_url_main in D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\vendor\aq_resizer.php on line 142

Notice: Undefined variable: cdn_url_main in D:\XAMPP\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\vendor\aq_resizer.php on line 142

**Comment by Zabi09** [comment]
Fixed in - #3555
