### ISSUE TITLE
Custom post description migrates to image description

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3606]
Excerpts are showing in captions 

To re-occur, import WordPress.2019-08-28.xml from the attachments,

and see the post "Стратегии на E3 2019"

and then view it's AMP version. You will find this text added below the image as caption "Обзор всех новостей стратегий с выставки" - THis text is actually the excerpt of the post.

[Downloads.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3562443/Downloads.zip)

REF: https://wordpress.org/support/topic/custom-post-description-migrates-to-image-description/#post-11875201

**Comment by MohammedKaludi** [comment]
is this connected with #3536?

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
