### ISSUE TITLE
Structured Data improvements

### ISSUE THREAD

**Issue by iamkingsleyf** [ahmedkaludi/accelerated-mobile-pages#3607]
Hi

It stopped showing the ERROR and its not picking up YOAST SCHEMA either. Here is the first issue #3567 

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fhealthtian.com%2Fpreparing-your-child-for-a-new-school%2Famp

**Comment by MohammedKaludi** [comment]
Have you enabled the structured data inside yoast seo option?

**Comment by iamkingsleyf** [comment]
@MohammedKaludi its enabled by default...

**Comment by iamkingsleyf** [comment]
@MohammedKaludi its working now, i did not know there is an OPTION to TURN on. i have done that

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fhealthtian.com%2Ftop-sexual-enhancement-products-for-men%2Famp%2F
