### ISSUE TITLE
My site is completely blank after the upgrade!

### ISSUE THREAD

**Issue by EltonDanielOliv** [ahmedkaludi/accelerated-mobile-pages#3608]
After the last update of the AMPforWP 0.9.98.6 Plugin, my site got buggy without displaying any features, showing only one blank page.

Please correct as soon as possible!

My website: https://androidfinal.com/

**Comment by EltonDanielOliv** [comment]
I wonder how I go back to the previous version when such problems happen?

**Comment by MohammedKaludi** [comment]
@EltonDanielOliv This is strange, can you please share some more information about the issue?
If you can share the Debug log that would be a great help to pin point the issue.

Meanwhile you can revert back to previous version using this tutorial.
https://ampforwp.com/tutorials/article/how-to-rollback-the-amp-to-an-older-version/

**Comment by EltonDanielOliv** [comment]
Where do I find the debug log?

**Comment by EltonDanielOliv** [comment]
I've already disabled all plugins, and it's still bugged. The problem is your plugin itself.

**Comment by MohammedKaludi** [comment]
> Where do I find the debug log?

Paste this in your wp-config.php file 

`define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
define( 'WP_DEBUG_LOG', true );`

then visit the website the  WordPress should generate some logs. 

And you can  find the debug.log file inside wp-content folder.

If you could send that file that would help us pin point the issue and we will fix it immediately and push an update.

**Comment by MohammedKaludi** [comment]
Also please check out this screenshot on where to add the debug code in wp-config.php.

https://take.ms/IqNDp

<img width="1136" alt="wordpress_wordpress-debugging-3 png (1409×705) 2019-09-03 17-46-54" src="https://user-images.githubusercontent.com/16618009/64172615-03185d00-ce73-11e9-96a4-e6dbb55863c2.png">

**Comment by EltonDanielOliv** [comment]
> Também verifique esta captura de tela sobre onde adicionar o código de depuração no wp-config.php.
> 
> https://take.ms/IqNDp
> 
> <img alt="wordpress_wordpress-depuração-3 png (1409 × 705) 2019-09-03 17-46-54" width="1136" src="https://user-images.githubusercontent.com/16618009/64172615-03185d00-ce73-11e9-96a4-e6dbb55863c2.png">

Done!

**Comment by EltonDanielOliv** [comment]
You have not generated any logs for me!

**Comment by EltonDanielOliv** [comment]
Here did not generate any logs!

**Comment by MohammedKaludi** [comment]
are you able to log inside your website?
I'm mean are you able to access wp-admin area?

**Comment by EltonDanielOliv** [comment]
Yes, I can access every site control panel!

**Comment by EltonDanielOliv** [comment]
I access your plugin and try to make some changes, and it gives me the error: There was a problem with your action. Please try again or reload the page.

**Comment by MohammedKaludi** [comment]
I think you are using AMP Takeover, if you are able to access AMP options panel then can you please Disable and test. 

Also can you please check again if the debug.log file or any other log file is created?

**Comment by EltonDanielOliv** [comment]
I put all the code you requested in the wp-config.php file, where can I find the log file created?

**Comment by MohammedKaludi** [comment]
you can find the debug.log file inside wp-content folder.

**Comment by EltonDanielOliv** [comment]
What is AMP Takeover? and where do I find it?

**Comment by EltonDanielOliv** [comment]
> você pode encontrar o arquivo debug.log dentro da pasta wp-content.
v0.0.9 - September 27, 2017
* Stats fixes wrong log requests

v0.0.8 - September 02, 2017
* Timeout fixes for downloading plugins and themes

v0.0.7 - August 28, 2017
* Fixed user information displayed on console

v0.0.6 - August 22, 2017
* Auto import parameter for fresh installs

v0.0.5 - August 2, 2017
* Item count set to 48 for initial request as pagination affect
* Email address not accepting for different TLD

**Comment by EltonDanielOliv** [comment]
> você pode encontrar o arquivo debug.log dentro da pasta wp-content.

Just found this one!

**Comment by EltonDanielOliv** [comment]
![2017-05-21 (4)](https://user-images.githubusercontent.com/53355283/64174028-f40fbb80-ce2e-11e9-92ab-7995cfa80d4b.png)
![2017-05-21 (5)](https://user-images.githubusercontent.com/53355283/64174029-f4a85200-ce2e-11e9-894e-67f28f01224d.png)
![2017-08-13](https://user-images.githubusercontent.com/53355283/64174030-f4a85200-ce2e-11e9-8d2d-61828f6a0de3.png)
![2017-09-19 (4)](https://use
![Uploading 2017-12-21 (2).png…]()
![Uploading 2017-12-21 (3).png…]()
![Uploading 2017-12-21 (4).png…]()


r-images.githubusercontent.com/53355283/64174031-f4a85200-ce2e-11e9-8c93-dc21e994e3d5.png)
![2017-10-04](https://user-images.githubusercontent.com/53355283/64174032-f540e880-ce2e-11e9-939a-3b75da3c8431.png)
![2017-10-17](https://user-images.githubusercontent.com/53355283/64174033-f540e880-ce2e-11e9-86c8-b0a24e7408fd.png)
![2017-10-19](https://user-images.githubusercontent.com/53355283/64174034-f540e880-ce2e-11e9-84f0-6194cef12adc.png)
![2017-11-08 (1)](https://user-images.githubusercontent.com/53355283/64174035-f5d97f00-ce2e-11e9-850d-239fa885bbce.png)
![2017-11-15 (7)](https://user-images.githubusercontent.com/53355283/64174036-f5d97f00-ce2e-11e9-89a7-cb2911d98cb0.png)
![2017-11-15 (8)](https://user-images.githubusercontent.com/53355283/64174037-f5d97f00-ce2e-11e9-8b24-95e8e2af3659.png)
![Uploading 2017-11-15 (9).png…]()
![Uploading 2017-11-15 (10).png…]()
![Uploading 2017-11-15 (11).png…]()
![Uploading 2017-11-19.png…]()
![Uploading 2017-11-21 (1).png…]()
![Uploading 2017-11-21 (2).png…]()
![Uploading 2017-11-21 (3).png…]()
![Uploading 2017-11-21 (4).png…]()
![Uploading 2017-11-21 (5).png…]()
![Uploading 2017-11-21 (6).png…]()
![Uploading 2017-11-21 (7).png…]()
![Uploading 2017-11-21 (8).png…]()
![Uploading 2017-11-21.png…]()
![Uploading 2017-12-05 (1).png…]()
![Uploading 2017-12-05 (2).png…]()
![Uploading 2017-12-05 (3).png…]()
![Uploading 2017-12-05 (4).png…]()
![Uploading 2017-12-05.png…]()
![Uploading 2017-12-06.png…]()
![Uploading 2017-12-08.png…]()
![Uploading 2017-12-11.png…]()
![Uploading 2017-12-21 (1).png…]()

**Comment by MohammedKaludi** [comment]
> > você pode encontrar o arquivo debug.log dentro da pasta wp-content.
> 
> Just found this one!

This is 

> > você pode encontrar o arquivo debug.log dentro da pasta wp-content.
> > v0.0.9 - September 27, 2017
> 
> * Stats fixes wrong log requests
> 
> v0.0.8 - September 02, 2017
> 
> * Timeout fixes for downloading plugins and themes
> 
> v0.0.7 - August 28, 2017
> 
> * Fixed user information displayed on console
> 
> v0.0.6 - August 22, 2017
> 
> * Auto import parameter for fresh installs
> 
> v0.0.5 - August 2, 2017
> 
> * Item count set to 48 for initial request as pagination affect
> * Email address not accepting for different TLD

No this is not the debug.log that we are looking for. Can you please check in some  other folders?

**Comment by MohammedKaludi** [comment]
From here you can find the AMP Takeover Settings.

![Accelerated Mobile Pages Options ‹ Test WP Installtion — WordPress 2019-09-03 18-09-38](https://user-images.githubusercontent.com/16618009/64174404-d2d2bd80-ce76-11e9-95e9-0a2ccce3d0e8.png)

**Comment by EltonDanielOliv** [comment]
> A partir daqui, você pode encontrar as configurações de controle do AMP.
> 
> ![Opções de páginas móveis aceleradas ‹Testar instalação do WP - WordPress 2019-09-03 18-09-38](https://user-images.githubusercontent.com/16618009/64174404-d2d2bd80-ce76-11e9-95e9-0a2ccce3d0e8.png)

Yes I found it!

I am using this option, however, I can't disable it!

When I try to save the change, the following message appears: There was a problem with your action. Please try again or reload the page.

**Comment by EltonDanielOliv** [comment]
> > > você pode encontrar o arquivo debug.log na pasta wp-content.
> > 
> > 
> > Apenas encontrei este!
> 
> Isto é
> 
> > > você pode encontrar o arquivo debug.log na pasta wp-content. 
> > > v0.0.9 - 27 de setembro de 2017
> > 
> > 
> > 
> > * Estatísticas corrigem solicitações de log incorretas
> > 
> > v0.0.8 - 02 de setembro de 2017
> > 
> > * Correções de tempo limite para baixar plug-ins e temas
> > 
> > v0.0.7 - 28 de agosto de 2017
> > 
> > * Informações do usuário corrigidas exibidas no console
> > 
> > v0.0.6 - 22 de agosto de 2017
> > 
> > * Parâmetro de importação automática para novas instalações
> > 
> > v0.0.5 - 2 de agosto de 2017
> > 
> > * Contagem de itens definida como 48 para solicitação inicial, pois a paginação afeta
> > * Endereço de email não aceito para TLD diferente
> 
> Não, este não é o debug.log que estamos procurando. Você pode verificar outras pastas?

I did not find it! I rummaged through everything, and didn't find it. = \

**Comment by MohammedKaludi** [comment]
Can you please revert back to older version of the plugin and see if the problem is resolved?

**Comment by EltonDanielOliv** [comment]
> Você pode voltar à versão mais antiga do plug-in e ver se o problema foi resolvido?

I will do this now, but could not return with the indicated plugin. Then I will use the default method.

Will my settings be deleted when uninstalling and installing the plugin again?

**Comment by MohammedKaludi** [comment]
> Will my settings be deleted when uninstalling and installing the plugin again?

If you are updating the plugin through FTP then reupload all the files in the same directory then all your data will be saved it will not be deleted.

Do not deactivate the plugin from the Plugins page, just re-upload the files from Cpanel or FTP.

**Comment by EltonDanielOliv** [comment]
> > Minhas configurações serão excluídas ao desinstalar e instalar o plug-in novamente?
> 
> Se você estiver atualizando o plug-in através do FTP, reenvie todos os arquivos no mesmo diretório, todos os seus dados serão salvos e não serão excluídos.
> 
> Não desative o plug-in na página Plug-ins, apenas faça o upload dos arquivos do Cpanel ou FTP.

Ok, I am replacing the plugin folder via FTP. Already I speak if solved the problem.

Because I was using these settings in the previous version, and the site was working normally. Only after updating to the new version did the site get an error.

**Comment by MohammedKaludi** [comment]
Can you please check the email one of our developer has emailed you.

**Comment by EltonDanielOliv** [comment]
This email here?

Em ter, 3 de set de 2019 às 10:22, Mohammed Kaludi <notifications@github.com>
escreveu:

**Comment by EltonDanielOliv** [comment]
I returned the plugin to the old version, and the site returned to normal.

**Comment by MohammedKaludi** [comment]
Reinstalled the plugin and issue is resolved.
