### ISSUE TITLE
Need to remove Legacy Pagebuilder option Safely

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3609]
Screenshot: https://monosnap.com/file/H4hHNfPCeKbFD8ORL2Anf3KL6FbyOr

Need to discuss with Ahmed sir for more info.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
