### ISSUE TITLE
Individual AMP Page (Bulk Edit) "hide by default" option not working

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3610]
Individual AMP Page (Bulk Edit) hide by default option not working since 0.9.98.2 

Ref: https://secure.helpscout.net/conversation/935592076/78942/

screenshot of 0.9.98.1 https://prnt.sc/p18mg2

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.9

**Comment by Thakur25** [comment]
Not working in my pc

**Comment by AmiOta** [comment]
Hi,

I reopen this, on version 1.0.32 is only working for pages, but no for posts, I followed the guide https://ampforwp.com/tutorials/article/allow-amp-only-on-few-posts-or-pages/ but the results are:

On Post (Not working):

![image](https://user-images.githubusercontent.com/46223934/76429219-b8752180-637c-11ea-8ac9-8c65ecd2487d.png)

On Page (Working):

![image](https://user-images.githubusercontent.com/46223934/76429256-c75bd400-637c-11ea-970f-515cd8159592.png)
