### ISSUE TITLE
Different meta description between AMP and None AMP.

### ISSUE THREAD

**Issue by buivien** [ahmedkaludi/accelerated-mobile-pages#3611]
Hello!

I’m having a problem with the meta description. It’s not the same.
When I create a new post, it doesn’t get this error.
But the current posts are different, there is a disturbance of the content described between the posts.

Meta description: Inox scrap- AMP
https://drive.google.com/open?id=15-r_tpTSu3belV5hgjwS6Z2miMd5ECcn
None-AMP
https://drive.google.com/open?id=19HaIB7eDrZKAPzbUExf4xgco5BHNAUcV

copper scrap- AMP
https://drive.google.com/open?id=19R20XSMjhxksF15bCgSPT6PQp_N1NVva

copper scrap- None AMP
https://drive.google.com/open?id=1qAKA8K5Es8vQWzvu6s63EF5dEjsfatBZ

I think I have the right setup.
https://drive.google.com/open?id=12ZmK1eop9Ig0iK13UnELxyZNSsgpIRjX

How to fix this problem.
Thank you in advance for your answers.

**Comment by ahmedkaludi** [comment]
The Github is for verified issues, The technical support is available on https://ampforwp.com/support/ 

They will help you fix it.
