### ISSUE TITLE
Need to add nofollow feature in notification option

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3612]
Need to add Nofollow feature in notification option

Screenshot:
https://monosnap.com/file/TV2lOrqEsWLvepW0TSoelzCITXzHNf

REF:https://secure.helpscout.net/conversation/945973540/80103/

**Comment by Zabi09** [comment]
Need to change the position of control - https://prnt.sc/parj4t

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.20
