### ISSUE TITLE
We need to allow people to turn off the social section fully

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3613]
![image](https://user-images.githubusercontent.com/16532359/64239725-5d222c80-cf1e-11e9-92d0-2791b0e4c573.png)
https://wordpress.org/support/topic/how-to-delete-social-sharing/

**Comment by MohammedKaludi** [comment]
Need to add required on sub-controls.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
