### ISSUE TITLE
AMP WPBakery Compatibility (BETA)

### ISSUE THREAD

**Issue by hoopsrich** [ahmedkaludi/accelerated-mobile-pages#3615]
AMP WPBakery Compatibility (BETA) no longer working

Fatal error: Cannot redeclare background_css_row() (previously declared in /home/credit4/public_html/wp-content/plugins/amp-pagebuilder-compatibility/includes/vc_templates/vcr.php:171) in /home/credit4/public_html/wp-content/plugins/amp-pagebuilder-compatibility/includes/vc_templates/vcr.php on line 181
The site is experiencing technical difficulties.

**Comment by ahmedkaludi** [comment]
This feature is not part of the core. Please create a ticket at technical support on https://ampforwp.com/support - we will help you
