### ISSUE TITLE
Ui Design issues 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3616]
1. Theme selector box is full widht: https://monosnap.com/file/1Aa2ykULfFrkj68ShLEn5NKxPEcqwE

2. Layouts theme need to be three in a row but there are only two:

https://monosnap.com/file/B59rV9CS6HoaH8PjrPBHBXj2vOR1xB

3. By default, the general bar is closed in the single tab:

https://monosnap.com/file/G5LW3vAdFzLFAWgyNiLmRhLCLzhUqB

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/50b2a4e0ed5c9ef2764578315b8eaf11838534e2#diff-ec2b9328f0c0a238b30ee631ba69c30bR1301
For this selector add proper selection.
Eg. if some other plugins use select2, current CSS will apply on there also. make it accurate

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
