### ISSUE TITLE
jwplayer support

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#362]
Add jwplayer support

**REF:**
https://secure.helpscout.net/conversation/299385709/10239/?folderId=1060551

https://ampbyexample.com/components/amp-jwplayer/

**Comment by ahmedkaludi** [comment]
https://www.ampproject.org/docs/reference/components/amp-jwplayer

**Comment by pegazee** [comment]
The progress of this ticket can be viewed in #691 as both are same.
So @MohammedKaludi please close this ticket.

**Comment by ahmedkaludi** [comment]
It would not make sense to add this as a core feature, we should rather add it as an extension. Added on my Dashboard Trello board as an extension request. Close this one.
