### ISSUE TITLE
Post date always shows 3 hours ago

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3624]
conflict with plugin Event Calendar WD.
1. Install Accelerated Mobile Pages
2. Create a new post and check the publish date in AMP page
3. Install and activate Event Calendar WD
4. Check the publish date of that page – it will become “3 hours ago”.
REF: https://wordpress.org/support/topic/always-3-hours-ago/#post-11898480

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
We need this filter.

**Comment by MohammedKaludi** [comment]
need to improve the code as discussed.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
