### ISSUE TITLE
Tooltip alignment is missing in Advertisement 

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#3625]
Tooltip alignment is missing in AMP option panel ->Settings -> Advertisement -> Ad type 

https://take.ms/VnMPo

Note: Please check all the Tooltip alignment in AMP option panel

**Comment by sonaliramteke** [comment]
Tooltip alignment issue -> https://take.ms/htkXi

**Comment by MohammedKaludi** [comment]
Please  do not use !important and fix it without it.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
