### ISSUE TITLE
AMP for WP conflict with the CDN Enabler plugin

### ISSUE THREAD

**Issue by wayansuadnyana** [ahmedkaludi/accelerated-mobile-pages#3631]
Dear Admin,

I find out on KeyCDN Enabler Plugin Version 1.0.9, on Exclusions setting (Enter the exclusions (directories or extensions) separated by,) I can’t remove wp-content.

I have removed several times the wp-content from exclusions directories and save. However, there are no changes occurs, and the wp-content are remaining on exclusions directories as you may see on the screenshot. Therefore, at this moment all my websites serve the wp-content from origin server instead of CDN.

I check with KeyCDN support, and they told me there is a conflict with KeyCDN Enabler Plugin with AMP for WP latest update.

So I conduct a test with one of my websites with KeyCDN Enabler Plugin Version 1.0.9 install without AMP for WP plugin install. The result, there is no issue to remove wp-content exclusions directories. Therefore all wp-content lists serve through CDN.

Hopefully, with your kind heart help me to solve the issue.

Regard from Bali

Wayan Suadnyana

![Screenshot-(73)](https://user-images.githubusercontent.com/55057783/64490915-9ea33680-d294-11e9-96ac-072039c34165.jpg)

**Comment by ahmedkaludi** [comment]
Thanks for reporting, we will start working on this

**Comment by besirkurt** [comment]
I have the same problem, a new update will come

**Comment by wayansuadnyana** [comment]
Dear Admin,

I have updated the plugin to Version:0.9.98.9, and I hope it solves the issue with AMP for WP conflict with the CDN Enabler plugin. Unfortunately, the problem not resolved. 

Regard,

Wayan Suadnyana

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by besirkurt** [comment]
problem still persists
![cdn](https://user-images.githubusercontent.com/55351934/65146524-b319c880-da24-11e9-8e19-aa8d41be04a3.jpg)

**Comment by MohammedKaludi** [comment]
It will be pushed in today's update

**Comment by MohammedKaludi** [comment]
It will be pushed in today's update

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10

**Comment by pymntsweb** [comment]
This still doesn't work.. I'm running wordpress 5.2.7 and AMP version 0.9.98.14
