### ISSUE TITLE
menu peekaboo problem

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3633]
Menu opens and closes immediately when `#` is part of url.

Happening only with Design One.

Recreated on https://ampforwp.com/demo/one/amp/#
https://wordpress.org/support/topic/menu-peekaboo-problem/

**Comment by MohammedKaludi** [comment]
Javascript attributes are not allowed in AMP
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e0683950e2883fadd97f9aa53e61987eae53bd58#diff-b31bea623b1182cf3e79029262fe3e47R14

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.13

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.13
