### ISSUE TITLE
Images and Videos with Gutenberg does not have proper spacing

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3634]
Images and Videos with Gutenberg does not have proper spacing, See: https://imgur.com/gQqbmXu ( Actual url as per the image is [this](https://xn--b1afnsoec8e.xn--80agfnksgkikc.xn--p1ai/2019/09/06/%d0%ba%d0%b0%d1%80%d1%82%d0%be%d1%87%d0%bd%d1%8b%d0%b9-%d0%b2%d0%bb%d0%b0%d1%81%d1%82%d0%b5%d0%bb%d0%b8%d0%bd-%d0%ba%d0%be%d0%bb%d0%b5%d1%86/amp/))

REF: https://wordpress.org/support/topic/no-margin-before-images/#post-11906571

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.17 update
