### ISSUE TITLE
Big white space before related post

### ISSUE THREAD

**Issue by iamkingsleyf** [ahmedkaludi/accelerated-mobile-pages#3635]
Hi,

We are having BIG WHITE space on all our site just before the related post. I don't know if its from the settings page or something else.

https://techcrub.com/uber/amp/
https://animalespedia.com/can-dogs-eat-pepper/amp/
https://healthtian.com/bacteria/amp/

I am guessing what should be there is the comment form but its not displaying, we use disqus and it seems not to display

**Comment by ahmedkaludi** [comment]
Github is for the valid and recreatable bugs. Yours looks like the ones that are yet to troubleshoot.

Kindly reach out to technical support team first.
