### ISSUE TITLE
Single  Sidebar data is visible in Homepage

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3636]
Swift Single Design 2 is a mess, need to restructure the code if possible.
https://take.ms/iXED4

**Comment by MohammedKaludi** [comment]
Position of the hook seems can break the layout.

**Comment by Zabi09** [comment]
I have checked it and it is appearing fine after changing the hooks also

**Comment by MohammedKaludi** [comment]
Need to do a discussion before merging.
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
