### ISSUE TITLE
Design improvements of D2

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3637]
- [x] https://monosnap.com/file/ygiqDVAoxbS3zPtzb6U6VqSEXxpl0o

- [x] https://monosnap.com/file/TMm4KuYnjj07nA9ftIxXzaKcGcubRX

https://bit.ly/2malFdI

**Comment by MohammedKaludi** [comment]
What about Post Navigation?

**Comment by Zabi09** [comment]
Alignment not looking good on desktop
Master - https://prnt.sc/phryk1
Beta - https://prnt.sc/phry61

**Comment by MohammedKaludi** [comment]
Design not looking consistent https://take.ms/Ng7fv

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
