### ISSUE TITLE
Width of the recent posts and related posts thumbnail image should be same 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3639]
Screenshot: https://monosnap.com/file/AKGQ8Zo5Jcx9xT2sRbChsN4qIWaJlI

Width of the recent posts featured image thumbnail image and related image are not same when the user is selecting Single post design two.

Screenshot: https://monosnap.com/file/EAJIyu9uibEdwrvUUGCTpL0FF3mPNg

Ref: https://secure.helpscout.net/conversation/950852344/81430?folderId=1060554

**Comment by MohammedKaludi** [comment]
Alignment is still not correct. 
https://take.ms/LcXv4

**Comment by MohammedKaludi** [comment]
Alignment still not correct.
https://take.ms/c6dvo

**Comment by MohammedKaludi** [comment]
Breaking in other mobile view https://take.ms/TcNHk

**Comment by MohammedKaludi** [comment]
Needs improvement.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
