### ISSUE TITLE
Proper title for custom front page

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#364]
When defining a front page for AMP, it should give proper title for front page.

**REF:** https://wordpress.org/support/topic/front-page-has-no-title/

**Comment by ahmedkaludi** [comment]
Test it properly before making changes.

**Comment by MohammedKaludi** [comment]
Fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/384
