### ISSUE TITLE
Need to Add an option for showing no. of words in the excerpt of Recent Posts and Related Posts

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3640]
We need to add an option which will provide the user the facility to show the no. of words in recent posts and related posts

Ref: https://secure.helpscout.net/conversation/950852344/81430?folderId=1060554

Screenshot: https://monosnap.com/file/nV53royllAFiNrvf5ZcpFfHaIC1HJt

We need to implement as per the given scenarios:

2) The number of words in the excerpts should be the same.
3) There should be an option to vary the number of words in the excerpt.

**Comment by Zabi09** [comment]
Please make the default excerpt length '15' and also make it as a sub child - https://prnt.sc/pf62n8

**Comment by wasimmagazine3** [comment]
Excerpt length is already a child element

**Comment by Zabi09** [comment]
Except length for related posts has been fixed in #2908

**Comment by MohammedKaludi** [comment]
sanitizing required. Make sure only integers are assigned on to variables.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4b0f1c19fbfccb3f2784ff20110041ff83028feb#diff-7d3a92ac5e6165548bf9bc556f4f887aR250

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
