### ISSUE TITLE
Issue with the post titles in single page (two H2 tags if logo is not inserted)

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3641]
There is an issue with the post titles in the single pages changed from H1 to H2, 

If the logo is inserted then it is working fine if not h1 is replaced with h2 tag in a single page.

Ref link: https://moldedeletras.com/opake/amp/
Ref ticket: https://secure.helpscout.net/conversation/950861414/81433?folderId=3126461

**Comment by TMsravan** [comment]
One more issue 

- [ ] Test it with post and pages 

- [ ] Swift 

- [ ] D3

- [ ] D2

- [ ] D1

**Note**: Get review from Ahmed sir after this ticket has done.

**Comment by MohammedKaludi** [comment]
Condition improvement required.
if and else both have same values 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d2e6b567627948acbe32231e5a7731c4fd12a06d#diff-960aae38d5f005bdd6060bf9ae8f5c8fR30

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
