### ISSUE TITLE
Improvements in Design 1 2 and 3 option panel in Header section

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3642]
Need to improvements in Design 1 2 and 3 option panel in Header section

**Comment by Zabi09** [comment]
Escaping is missing

**Comment by sonaliramteke** [comment]
1) This section remove in 0.9.99 (beta) need to add in all design - https://prnt.sc/p9rbgz
2) alignment issue in the Swift theme - https://prnt.sc/p9rc7i

**Comment by RajuJeelaga** [comment]
@sonaliramteke 
1).Actually the header design options section i removed from the AMP option panel because,
We need to connect that colors as like Global colors, so on that basis i removed that section, and this is the ticket #3643

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
