### ISSUE TITLE
AMP text module is not working in Widget area

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3644]
The Amp text module does not work (in widget area) don't show the visual and renders the HTML code (tested in localhost too).

Ref Ticket:
https://secure.helpscout.net/conversation/951941226/81550?folderId=3126461

Screenshot: https://monosnap.com/file/32gfCkR9rxls4VbLYsRFF9FIAC1EaY

**Comment by ajeetku** [comment]
Why not uses `wp_specialchars_decode`
Check it with this function

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
