### ISSUE TITLE
Gutenberg Design Bugs

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3645]
**Note from @ahmedkaludi  All of the issues are valid, if you are unable to re-create then let me know, I will help you to see it.**

**Bug Info**
Amp page: https://xn--80agfnksgkikc.xn--p1ai/anno-1800/amp/
Original page: https://xn--80agfnksgkikc.xn--p1ai/anno-1800

- [ ] 1. ON original page the green button “Читать обзор” is centered and has white text in hover. On amp page it isn’t centered and has yellow text in hover.

- [ ] 2. On amp page list markers from RSS (standard block in Gutenberg) are above the text. Screenshot

- [ ] 3. On this amp page a yellow-colored block (the bottom) doesn’t have padding and looks ugly. Screenshot On the standard page, it looks good. It’s just a colored block from standard Gutenberg editor, you can add a color background to any text block in block settings on the right of the editor.

- [ ] 4. AMP doesn’t see if video or images are in columns from Gutenberg Editor.

Look at original and amp: https://стратегикон.рф/total-war-warhammer-ii

**Comment by wasimmagazine3** [comment]
This will be fixed in #3320

**Comment by MohammedKaludi** [comment]
Will test it once the dependent ticket is done.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
