### ISSUE TITLE
 search results pages are showing up as 'no index'

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3646]
search results pages are showing up as 'no index' in design 1, design 2, design 3 & swift

Ref: https://secure.helpscout.net/conversation/950689921/81408?folderId=3081347

https://github.com/ahmedkaludi/accelerated-mobile-pages/search?q=noindex%2Cnofollow&type=Code

**Comment by MohammedKaludi** [comment]
Need to add the condition for URL inspection tool is enabled or not 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8310b2a946b30cc237a1f5f7e5c54857d168b44d#diff-aa1bfacb57d08a971b74e88c5638b06cR7

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
