### ISSUE TITLE
Social media icons and comments should be below the post content on pages

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3647]
Social media icons and comments should be below the post content and but above the sidebar in mobile views on pages.

Currently, it is showing below the sidebar.

Ref: https://secure.helpscout.net/conversation/950852344/81430?folderId=1060554

Screenshot: https://monosnap.com/file/DbgYfGnE6yV4al914KSGHaPwyKTe5Z

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
