### ISSUE TITLE
Breadcrumbs are breaking after enabling ""Post title on Breadcrumb" option

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3648]
Ref: https://secure.helpscout.net/conversation/941826687/79566?folderId=2770545

Screenshot:  https://monosnap.com/file/Le7T0OceEV9EaEU0pLF6dvsbXYEZbJ

Steps to recreate:

1. Create one parent category
2. Inside the parent, category create two child category having the name with a comma
3. Select any post and select any child category for the post.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
