### ISSUE TITLE
Need to add compatibility of Breadcrumb NavXT, Breadcrumb NavXT Paths, and Order Bender plugin.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3649]
Ref: https://secure.helpscout.net/conversation/941826687/79566/

Need to add compatibility of Breadcrumb NavXT, Breadcrumb NavXT Paths, and Order Bender plugin in AMP.

**Comment by ahmedkaludi** [comment]
it was moved to compatibility section
