### ISSUE TITLE
Need to optimize css classes

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3650]
- [ ] .cat_mod 

- [ ] when along with .cat_mod classes like  .cat_mod_l

- [ ] .pagination

Please ref this: https://www.siasat.com/amp/page/295/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
