### ISSUE TITLE
Default heading tag should load if no option is selected in Header Module 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3651]
In Page builder Heading Module: https://take.ms/53Tyn

If no option is selected then default should be loaded. https://take.ms/p3iw2
https://take.ms/TpMEn

As this is breaking the markup

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/11582a5110ad24bedd01228cd73bdcccb0f054de#diff-c58433ff51f95196f5b439704500ee21R4
Conditions are not properly added

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
