### ISSUE TITLE
Extension license dashboard improvements

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#3654]
1. After Activation `From: PRICE` is showing. Need to remove this label
![screencapture-localhost-wordpress522-wp-admin-admin-php-2019-09-13-12_51_39](https://user-images.githubusercontent.com/19512210/64844679-0c998600-d626-11e9-95f2-c6f91d773acc.png)

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
