### ISSUE TITLE
Warning in Error Log 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3655]
- [ ] [11-Sep-2019 19:30:24 UTC] PHP Notice: Undefined index: caption in /home/macmagazine/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4726

https://wordpress.org/support/topic/php-notice-140/

**Comment by MohammedKaludi** [comment]
Referring to this line number: https://plugins.trac.wordpress.org/browser/accelerated-mobile-pages/tags/0.9.98.8/templates/features.php#L4726

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
