### ISSUE TITLE
 In social sharing Twitter Handle and Pretty Permalinks for Twitter Share? need to display child option of Twitter

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3656]
In the social sharing option, Twitter Handle and Pretty Permalinks for Twitter Share? need to display child option of Twitter.

Screenshot:
https://monosnap.com/file/R59cbHnRAX99zyLOw7mOV3msz4lqx7

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
