### ISSUE TITLE
The GDPR consent solution isn't working because of a coding error.

### ISSUE THREAD

**Issue by x1024** [ahmedkaludi/accelerated-mobile-pages#3658]
Currently, the GDPR consent solution always returns an error because of an invalid AJAX response.

The problem is here:
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/components/gdpr/gdpr.php#L261

Pull request is here: 
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3657

**Comment by MohammedKaludi** [comment]
Thank you for creating the issue and sending an PR I'll review it and hopefully if the fix is ready then we will push it in next update.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.9
