### ISSUE TITLE
Youtube embeded isn't working because of missing script tag

### ISSUE THREAD

**Issue by jeremycoppey** [ahmedkaludi/accelerated-mobile-pages#366]
Hi,
I have a issue with my embeded youtube video:
AMP version: no video showed
![image](https://cloud.githubusercontent.com/assets/13691266/21603680/60e2b2ba-d19f-11e6-803e-2945e6f52fd0.png)
Code inspector: see the amp-youtube  tag is present but I miss the amp-youtube script tag in the head:
![image](https://cloud.githubusercontent.com/assets/13691266/21603724/95952dc6-d19f-11e6-86b6-c6a303928193.png)

What should have been in the script tag:
<script async custom-element="amp-youtube" src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js"></script>

Link to site: http://www.zuunsekarpers.be/amp/

Kind regards
Love the project BTW!!

**Comment by nicholasgriffintn** [comment]
Videos work fine in my install, it might actually be a problem with CSS, I can remember having that problem myself and having to add in some CSS.

**Comment by ahmedkaludi** [comment]
@jeremycoppey Can you please let us know if you are still having this issue?

**Comment by jeremycoppey** [comment]
The issue still persist, just tested it on my mobile and on my desktop after I ran the updates on my site.
you can check for yourself on : [http://www.zuunsekarpers.be/amp/](http://www.zuunsekarpers.be/amp/)

**Comment by ahmedkaludi** [comment]
@jeremycoppey How are you adding the Youtube video? Through a shortcode?

**Comment by jeremycoppey** [comment]
Its added like this right under the text:

> [embed]https://www.youtube.com/watch?v=70w_CqOz8fg[/embed]

**Comment by ahmedkaludi** [comment]
Tell you what @jeremycoppey, I will make sure that this is done in the next few updates. 

THANKS!

**Comment by khaledMohammed000** [comment]
Hey @jeremycoppey 

editor
![image](https://cloud.githubusercontent.com/assets/16471728/22976017/fa44c3a4-f3ae-11e6-9720-d2b5002daa17.png)

output
![image](https://cloud.githubusercontent.com/assets/16471728/22975962/a59579de-f3ae-11e6-90fe-6987cf1ef7d5.png)

**Comment by khaledMohammed000** [comment]
If you still get this error please use the following code instead

`<iframe width="584" height="438" src="https://www.youtube.com/embed/70w_CqOz8fg" frameborder="0" allowfullscreen></iframe>`

**Comment by jeremycoppey** [comment]
@khaledMohammed000 Thanks I didn't work so I used your code!
thanks for the assist!

**Comment by nicholasgriffintn** [comment]
@jeremycoppey You can just post links into posts within the visual editor and Wordpress will automatically convert that into an embed for you, that works for me and it's a lot simpler.
