### ISSUE TITLE
Back in 0.9.98.9: Mobile redirection causing extra redirects from /amp to /amp/

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3660]
Same as: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3459
Got fixed in 0.9.98.4 (tested) https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3543
But it seems it keeps coming back...
By the way this adds almost one second to the loading time, and it is worse than bad for SEO...

**Comment by MohammedKaludi** [comment]
@olddoc waiting for the reply/

**Comment by olddoc** [comment]
Dear Mohamed,

Sorry for the late answer, we are changing to a new host with nginx, http2,
plesk, etc... The stage copy is already there And everything is a bit
fucked up,

1- We also updated to  0.9.98.10 and the redirection continues* with a
small twist*:
Evita que haya varias redirecciones de página
0,96 s
Las redirecciones provocan retrasos adicionales antes de que la página se
pueda cargar. Más información
<https://developers.google.com/web/tools/lighthouse/audits/redirects?utm_source=lighthouse&utm_medium=unknown>
URL
Duración

(Initial: https://www.nexustraductions.com/)

0 ms
/amp <https://www.nexustraductions.com/amp>
(www.nexustraductions.com)
780 ms
*/?amp* <https://www.nexustraductions.com/?amp>
(www.nexustraductions.com)
180 m

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.nexustraductions.com%2F



2- Also, Do you have any docs with guidelines/help about the best way to
configure *nginx*? (now it is running apache until we figure out how not to
get some stability) maybe some *Plesk *help? Because actually it does not
work half as well as it should...
(Actually, I know now it is not running smooth at all), some issues we are
facing:
- gzip  compression does not seem to be working on AMP (it is working in
non AMP ) -even now on Apache
- Can't use AMP on nginx, it just stops working and delivers the non AMP
page

Login details as requested:

> www.nexustraductions.com
>> user:   AmpforWP
>>
> pass:  rRXVCnqrYLpZU0Nw1@xNeLfY
>>
>

> ftp.nexustraductions.com
>> user: nexustraductions.amp4wp
>> pass: Amp4wp321
>>
> Thanks in advance, Kind regards

Carlos Derqui
Nexus Traducciones

**Comment by olddoc** [comment]
answered by mail

**Comment by MohammedKaludi** [comment]
@olddoc we have fixed this issue and @Zabi09 will commit on it very shortly.

We will push an update very soon with this fix.

Thank you very much for creating the ticket.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.11
