### ISSUE TITLE
Table (thead-th) styling issue after update

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3661]
https://wordpress.org/support/topic/table-thead-th-styling-issue-after-update/
https://ibb.co/fxTgRbH

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
