### ISSUE TITLE
Pretty Permalinks for Twitter Share? option is not working 

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3662]
Tested with all design:
- [ ] Design 1
- [ ] Design 2
- [ ] Design 3
- [ ] Swift
- [ ] News paper theme

Screenshot:
https://monosnap.com/file/uZqQz4lubuoZ0IOYNJ3O4w32aLs1b2

Note: Need to do a test at your end properly If we did something mistake.

REF:https://secure.helpscout.net/conversation/950453278/81376?folderId=3008055

**Comment by MohammedKaludi** [comment]
Else part can be removed.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e77ef7d57d78dd50b71fee11b48fdc9628674e11#diff-9cbf83e0d21caa7d8505ed4a8d03b158R17

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
