### ISSUE TITLE
Incorrect placeholder "Select the SEO Plugin" in drop-down in AMP option Panel

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3663]

**Comment by akashagrjsr** [comment]
IN AMP option Panel anywhere with a drop-down, it says Select the SEO Plugin in the placeholder. 

Screenshot: https://monosnap.com/file/jk4OHaTgVy6YAd6bctBXeG9B7UwVB5

Ref: https://secure.helpscout.net/conversation/953318354/82086?folderId=1514170

**Comment by Zabi09** [comment]
Pushed in 0.9.98.10
