### ISSUE TITLE
Need to improvment in table code

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3664]
**When the custom front page selected table screwed up**
https://monosnap.com/file/54IKXtnlN6k2BvWCxytVuJ0edtv1iq

- [ ] Swift theme 
   https://monosnap.com/file/47sqY0JWwAkjoz7gyjNttkwDlWSBZm

- [ ] Design 2
    - [ ]  The table is not overriding color 
    - [ ]  Need to decrease unnecessary CSS in table
    - [ ] Need to check this by adding this code at your end https://pastebin.com/cZLnXkxD

Note: Take this ticket review from Ahmad sir.

**Comment by Zabi09** [comment]
To overide the color of the table you can add this css - 
.amp-wp-content.the_content table strong {
    color: #000;
}

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
