### ISSUE TITLE
When enabling Treeshaking it removes the Swift icons TTF 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3665]
When Swift Icons selected from Font Icon Library: https://take.ms/kYnea

It removes the TTF fonts elements: https://take.ms/htolD

**Comment by TMsravan** [comment]
Another issue font icons are not loading when Optimize CSS (beta) is enabled.

https://secure.helpscout.net/conversation/951862882/81538?folderId=2632030

**Comment by MohammedKaludi** [comment]
Not working when font-awesome selected with Page builder enabled.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.13
