### ISSUE TITLE
Data is not saving while Importing options from the json file

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3667]
Data is not saving while Importing options from the json file 

This is happening sometimes, if we reupload the file then it updates the data

**Comment by Zabi09** [comment]
Not working when WP_DEBUG is true

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.14
