### ISSUE TITLE
Need To move CTA button in header two in sidebar if the website layout is in mobile view

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3669]
Screenshot 1: https://monosnap.com/file/DLjsa269AqTDR6JQCWPbjgbHM8IMSP

Screenshot 2: https://monosnap.com/file/M9W3fVfLxMzkL8ncKgxE6vbPKGZckD

We need to improve CTA button in header2 in mobile view. If the website is in mobile view it should show in the sidebar.

Also, need to improve the UI of the button in mobile view

Ref: https://secure.helpscout.net/conversation/947653087/80315?folderId=1060554

**Comment by ajeetku** [comment]
Use Escaping: esc_url and in place of __() use esc_html__() https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cf1948516cb60092b5843cabfd10eebd7295e5bc#diff-037f48d1f4ebe70736221163d899a20bR161

**Comment by MohammedKaludi** [comment]
I dont think the switch is required for this type of fix
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cf1948516cb60092b5843cabfd10eebd7295e5bc#diff-260eba6333c3222e59a6aed22ac5ab37R4680

**Comment by Zabi09** [comment]
I have discussed with @ahmedkaludi bhai and he told me create the switch because if we don't add the switch then by default the CTA button will go in the menu in a responsive view but many of our users want the CTA in header only

**Comment by MohammedKaludi** [comment]
> I have discussed with @ahmedkaludi bhai and he told me create the switch because if we don't add the switch then by default the CTA button will go in the menu in a responsive view but many of our users want the CTA in header only

I think there was some miscommunication, we don't need a switch. It should automatically adapt the markup according to the screen size.

**Comment by MohammedKaludi** [comment]
Need to improve the label to "CTA Position on Mobile"

**Comment by MohammedKaludi** [comment]
Incorrect usage of the ` __()` function 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cf1948516cb60092b5843cabfd10eebd7295e5bc#diff-037f48d1f4ebe70736221163d899a20bR161

**Comment by Zabi09** [comment]
Already fixed in - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5109ab52a7f29d8394f977e6a39c2666f7b395cc

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
While merging need to add this code - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f81f790935567e7b9fb94c65af367879de67ad1d

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
