### ISSUE TITLE
#335 and Index page 1st post issue

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#367]
Steps to create the bug : 
1. go to all posts
2. go to the first post (edit mode)
3. then select Hide AMP
4. save and update
5. go to URL : localhost/<you wp directory>
6. now you can see that rel canonical is removed....it can be done for all page's 1st post and you will find rel canonical is removed for each

Reason 👍 
use get_permalink() on index page and you will observe that 1st post url is returned...which is wrong and its the same with page 2,3,4,5.....

Solution : 
First Exclude posts that have show amp hidden true
then fix the get_permalink() for index page

**Comment by Asif2BD** [comment]
Need quick solution.
