### ISSUE TITLE
Allow user if form is valid

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3670]
- [ ] Allow user if action get is used and the form is valid 

- [ ] This is the scenario https://pastebin.com/n0BZYi6H and there are other scenarios at https://amp.dev/documentation/components/amp-form/

- [ ] Allow easy procedure for action-xhr users so that they can use easily.

Ref: https://secure.helpscout.net/conversation/947205040/80247?folderId=3081347

**Comment by wasimmagazine3** [comment]
This issue has been fixed in #3689.

**Comment by MohammedKaludi** [comment]
Fixed in #3689
