### ISSUE TITLE
User facing in Debug mode  "error exception:undefined index" in features.php

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3671]
As per user when debug mode is on facing "error exception: undefined index" in the features.php.

Screenshot: https://monosnap.com/file/7GbIGjlICTnlsMaVesMtFbPw4KHf9R
Ref Ticket: https://secure.helpscout.net/conversation/950785618/81421?folderId=3126461

**Comment by MohammedKaludi** [comment]
This is fixed in #3655 and pushed in 0.9.98.10
