### ISSUE TITLE
Fatal error: require_once(): Failed opening required '/wp-content/plugins/accelerated-mobile-pages/templates/report-bugs.php'

### ISSUE THREAD

**Issue by efierros** [ahmedkaludi/accelerated-mobile-pages#3672]
**Warning**: require_once(/wp-content/plugins/accelerated-mobile-pages/templates/report-bugs.php): failed to open stream: No such file or directory in **/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php** on **line 510**

**Fatal error**: require_once(): Failed opening required **'/wp-content/plugins/accelerated-mobile-pages/templates/report-bugs.php'** (include_path='.:/opt/php54/lib/php') in /wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on **line 510**

I get this error on admin page, and the next one on the client side:

**Fatal error**: Can't use function return value in write context in **/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php** on **line 975**

**Comment by ahmedkaludi** [comment]
Can you please tell us which scenario does this error happen on?

Because we haven't faced this, nor we heard about this from other people.

This Github is for valid and re-creatable bugs. I suggest you to contact our technical support team to get support on this.
