### ISSUE TITLE
AMP pages loading slowly.

### ISSUE THREAD

**Issue by shreen2008** [ahmedkaludi/accelerated-mobile-pages#3677]
Hello.
My GTMetrix results are - https://gtmetrix.com/reports/www.windowstechit.com/TvsYzxzG
As you can see for that AMP page, the fully loaded time is 6.2 s and page size is 1.61MB.
When I disable your AMPforWP plugin, it is lot less like 3 to 4s.

I am using Thesis Framework with Effectus skin.
The following plugins are used.
Active Plugins: Accelerated Mobile Pages, Akismet Anti-Spam, Advanced AMP ADS, Classic Editor, Lightweight Subscribe To Comments, Cookie Notice, Easy Affiliate Links, Easy Table of Contents, Inline Related Posts, Link Juice Keeper, PageSpeed Ninja, Quick Adsense, Redirection, Code Embed, TablePress, Ultimate Category Excluder, Yoast SEO, WP Review Pro, WP Shortcode Pro by MyThemeShop, WP-Sweep, Yet Another Stars Rating

My AMP pages are very slow for the whole site when your plugin is enabled. 
But I like your plugin for its simplicity.

What is causing the slow issue.

**Comment by ahmedkaludi** [comment]
The best place to get the technical help is on https://ampforwp.com/support/
