### ISSUE TITLE
Breadcrumb icommon symbol direction should be changed when RTL is enabled in Swift.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3678]
Desc: Breadcrumb icommon symbol direction  should be changed when RTL is enabled in Swift.

And also ordered list numbers are displaying in the top.

https://prnt.sc/p8pho2

**Comment by MohammedKaludi** [comment]
is this the fix for inline related posts's ol?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/587948a27409b42fe0b699317cf327b7fd91ef49#diff-2ae5550e31f40c1962ca69d373af6b93R656

**Comment by Zabi09** [comment]
We will fix only the breadcrumb icon symbol issue in this ticket and ordered list numbers will be properly fixed in #3704

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
