### ISSUE TITLE
Need to create an option to clear the cache in tree shaking

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3680]
https://prnt.sc/p8zpbv

**Comment by MohammedKaludi** [comment]
User authorization required.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cde6d5ed1656a4ba380f34e8c0bb1e7eb73995e5#diff-54dac7dab9dd460d137d86d279822cc5R248

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.13
