### ISSUE TITLE
Upgrade to AdsforWP button not working properly.

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3681]
if the Ads for wp plugin installed but not active, "Upgrade for Free" button show in below screenshot will not  work, it will try to redownload the plugin as plugin directory is already available then it will wait forever.

https://take.ms/Ml3HN

**Comment by djixas** [comment]
For me, I did not even get a single notification on any of my sites to update amp ads or amp cache for 4 months or so

**Comment by ahmedkaludi** [comment]
@djixas I'm sorry to hear about the issue, The best place to get the technical support help is on https://ampforwp.com/support/

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/71677de97bfab26000999462e944b6fbe38fbb3e#diff-d794f55e3ee0aead59adf8c61f67f9edR1044 use esc_attr

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
