### ISSUE TITLE
kk star rating plugin incompatible after update

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#3682]
Hello,

Been using 0.9.97.60 and did not upgrade for a while as there are far too many bugs introduced with every release until today's 0.9.98.11, which did not focus on 20 new features, but improved stability instead.

Turns out, I was wrong. After upgrade, kk star plugin is no longer properly working and looks all messed up:

https://www.airytea.com/blog/top-10-green-tea-health-benefits-effects/amp/

The stars take over full screen now.

Can this be solved, thank you

P.S. How does one disable that "x [ close]" for sticky ads? I don't see option. Using premium

**Comment by djixas** [comment]
The issue is gone WHEN I disable sticky social icons. Is this related somehow?

**Comment by ahmedkaludi** [comment]
@djixas This happened after the KK Star rating update, we have fix this with the AMP Ratings recent updates.  Are you using that plugin?

**Comment by djixas** [comment]
Hi, I need separate plugin to fix kk ratings plugin? I have not installed any extra plugins.

Is there any way to fix this without installing a plugin?

**Comment by djixas** [comment]
Installed and issue is solved now, screw kk rating authors

**Comment by ahmedkaludi** [comment]
Glad to hear it
