### ISSUE TITLE
Lightbox not working for single images

### ISSUE THREAD

**Issue by ItsAnilSingh** [ahmedkaludi/accelerated-mobile-pages#3683]
Lightbox is not working for attached single images.

https://imgur.com/a/25aiFbE

Check here - https://tricksmash.com/mudra/amp/

**Comment by MohammedKaludi** [comment]
This is a valid issue, this happens when we have cropped image in the img-src.

@ItsAnilSingh this issue will be fixed in a very priority basis and will be pushed in next update.

**Comment by MohammedKaludi** [comment]
add escape url 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/fdf6fcb80bd5a11ba23df97ca3850f0f289b5fea#diff-6aa5512f7dd8d5ce60fc97b0f340912cR5807

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12

**Comment by ItsAnilSingh** [comment]
Updated to v0.9.98.12 and it is still not working on my blog's amp posts. Am I doing something wrong?

**Comment by MohammedKaludi** [comment]
@Zabi09 can you please look into it.

**Comment by MohammedKaludi** [comment]
Use better methods to get the image source. We will not go far if we are taking the value statically.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/da454e34d1080af6f0a1d9c426ab58c7b94998f5#diff-6aa5512f7dd8d5ce60fc97b0f340912cR5821

**Comment by Zabi09** [comment]
I have tried by adding different scenarios that may break but it is not breaking and the lightbox is working fine

**Comment by ItsAnilSingh** [comment]
I noticed something while checking chrome dev tools.
This is happening only when the amp-img tag is enclosed with a link i.e, html element 'a'. Normally, we link the attachment with its media file while uploading the image. Maybe this can help solve the issue.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
