### ISSUE TITLE
Need to make compatibility of Advance setting options of yoast seo into AMP

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3684]
Need to make compatibility of Advanced setting options of Yoast SEO into AMP.

These options are present on the edit post or pages section.

Ref: https://monosnap.com/file/mCC4tVzYp3nU0Fv6vvF9zePomKoraU

https://secure.helpscout.net/conversation/961168998/84841?folderId=2632030

**Comment by Zabi09** [comment]
Meta robots are showing twice - https://monosnap.com/file/xlHaMc6Eyjn9drEltV4CxRJJsyivDI and it should not be connected with this option - https://prnt.sc/pd82fv

**Comment by MohammedKaludi** [comment]
If there is a link in the menu it should go to the link, but if menu has `#` or no link then it should behave like clickable dropdown.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
