### ISSUE TITLE
Ongoing issue with AMP blank page and Cache

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#3686]
Hello,

This has been happening for as long as I've been using AMP Cache (close to two years), and would love to know if other people are experiencing the same thing. The AMP pages will randomly become blank and will only work after a forced cache refresh.

Not all pages, just one or two, I have tested this on different sites and different servers, same issue (happend with latest build of amp for wp + cache + advanced ads), very random and I cannot find the cause.

Apache, PHP 7.3

The only giveaway is Google that then just sends invalid AMP pages error, but by that time it's too late as pages don't get traffic / money.

> Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site: Referenced AMP URL is not an AMP

**Comment by ahmedkaludi** [comment]
When you say cache, you mean AMP cache?

I would love to help you improve this but the Github is for tried and tested bugs, I suggest you to get help from our technical team via https://ampforwp.com/support/
