### ISSUE TITLE
Removing trbidi attribute

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3687]
trbidi attribute is getting added n div section it may be due to Gtraslate 

Ref: https://secure.helpscout.net/conversation/959521987/83953?folderId=3081347

https://prnt.sc/p9uan6

**Comment by MohammedKaludi** [comment]
Use any exsisting filter, instead of creating a new one.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bdfa72ffa3299bc65697ec25c9b006a80b2aa6e2#diff-1301281de287d2aed98746fc9ba777b4R1044

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
