### ISSUE TITLE
AMP LIVE List

### ISSUE THREAD

**Issue by themeenanaresh** [ahmedkaludi/accelerated-mobile-pages#3688]
I am using your AMP plugin. We have designed a live blog. Also implemented schema.

 But Big Problem 

How to Setup AMP Live List On AMP Version. Please Provide Step by Step Guide.

**Comment by ahmedkaludi** [comment]
We have the LiveBlog extension which could help you.

Github is for the re-creatable issues, I suggest you to ask for the support on ampforwp.com/support/
