### ISSUE TITLE
Image height and width are ignored if specified with decimal

### ISSUE THREAD

**Issue by friskiu** [ahmedkaludi/accelerated-mobile-pages#369]
@ https://webenglish.se/hobbies-and-interests-5-6 and https://webenglish.se/hobbies-and-interests-5-6/amp/

Source:
`<img title = "WebEnglish.se Hobbies and Interests, 5-6  "src="https://webenglish.se/wp-content/uploads/2017/01/eslways20poster20ad.png?x44512" alt = "WebEnglish.se Hobbies and Interests, 5-6  " width="70.739549839228" height="100"></a>
`
AMP Result
`<amp-img src="https://webenglish.se/wp-content/uploads/2017/01/eslways20poster20ad.png?x44512" alt="WebEnglish.se Hobbies and Interests, 5-6  " width="" height="100" sizes="(min-width: 0px) 0px, 100vw" class="amp-wp-enforced-sizes"></amp-img></a>&#13;
`

**Comment by friskiu** [comment]
Source

![clip1](https://cloud.githubusercontent.com/assets/929613/22006853/c7b904f6-dc6e-11e6-8e15-399f435fbdab.JPG)

Result
![clip2](https://cloud.githubusercontent.com/assets/929613/22006852/c7b85362-dc6e-11e6-84d8-6f5638f84699.JPG)

**Comment by ahmedkaludi** [comment]
Hey @friskiu I'm trying to access your AMP URL but it's not working.

**Comment by ahmedkaludi** [comment]
we are closing this to stay focused
