### ISSUE TITLE
Homepage posts image alignment issue 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3691]
https://monosnap.com/file/QNBA9FSuFVsZuPkvL4jyyxuYIPaZJm

To re-create, import the json settings. Make sure we understand where the issue is coming from and why did it start suddenly before making the fix.

[redux_options_redux_builder_amp_backup_22-09-2019.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3645649/redux_options_redux_builder_amp_backup_22-09-2019.zip)

**Comment by Zabi09** [comment]
To create the issue enable this - https://prnt.sc/pb9y4o and check the homepage thumbnail images

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
