### ISSUE TITLE
Toolbar AMP link bug

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3692]
Few problems with the link in the toolbar: https://monosnap.com/file/cQZfDMU2VpsHa5wYiYqIiQeh1bzYdQ

- [x] It always points to the wrong link from homepage

- [x] it should be just a AMP icon just like in the backend https://monosnap.com/file/sEYaCDBi1I2fpB2intngswgEcFsHK7

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
