### ISSUE TITLE
Canonical url is changing in cateogry pages when cateogry name start with amp

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3694]
Canonical url is changing in category pages when category name starts with amp, Example when we add category post name "Ample" then in canonical url it just shows "le".

You can check this url:
https://exopetguides.com/amphibians/amp/

REF:https://secure.helpscout.net/conversation/893365069/72422?folderId=3008055

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
