### ISSUE TITLE
When Convert AMP to WP theme (Beta) option is enabled Back to Top link functionality is not working

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3695]
Convert AMP to WP theme (Beta) option is enabled Back to Top link functionality is not working

https://secure.helpscout.net/conversation/962935704/85310/

Issue recreated in local

**Comment by nommanshaik18** [comment]
Another user with same issue 
https://secure.helpscout.net/conversation/964850580/85864?folderId=3081347

**Comment by MohammedKaludi** [comment]
Use css to implement this

`{ scroll-behavior: smooth;} `


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4e5e6c3a8f9055813a259fc9a503d64ec22fbe5a#diff-b6438fc932bdcf0c8a01c3c146505c9eR504

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
