### ISSUE TITLE
Logo is not resizing when using fixed width

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/accelerated-mobile-pages#3696]
- [x] Logo is not resizing when using fixed width it is taking default value 190px

https://monosnap.com/file/rjzR5RUVx1IKAka8o2WDycUldeWCtN

https://prnt.sc/panqud

- [x] Displaying of size value should be removed from flexible width https://prnt.sc/panr70

Ref: https://secure.helpscout.net/conversation/963860324/85640?folderId=1060556

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b030825cb530d39d824d22aeaa85ca4b198fbe7b

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b030825cb530d39d824d22aeaa85ca4b198fbe7b#diff-960aae38d5f005bdd6060bf9ae8f5c8fR45

Condition wrong 
on a time , single variable checked with 2 values

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.17 update
