### ISSUE TITLE
Remove broken link on source code like "<link rel="dns-prefetch" href="https://cdn.ampproject.org">."

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3697]
Remove broken link on source code like "<link rel="dns-prefetch" href="https://cdn.ampproject.org">."

https://secure.helpscout.net/conversation/963872630/85648?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
