### ISSUE TITLE
amp scripts are not getting generated when custom amp editor is enabled for the post and sticky ads added from adsforwp

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#3698]
Ref: https://github.com/ahmedkaludi/ads-for-wp/issues/248
Steps to Recreate
1) Activate adsforwp plugin and create one amp-sticky ads of type adsense.
2) Enable custom amp editor.
3) view the post which has custom amp editor enable in amp, you will get the error saying amp sticky ads requires amp sticky script.

**Comment by Zabi09** [comment]
Fixed in - #4040
