### ISSUE TITLE
Yoast Glue & Analytics shows the code twice 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#370]
http://take.ms/yc3mG

**Comment by khaledMohammed000** [comment]
Yoast code ...as in meta tags only shows up once....yes i agree that the second part is valid

**Comment by MohammedKaludi** [comment]
Fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2dad4781410edac749ef763dad7dc2d691eaf7e3

**Comment by MohammedKaludi** [comment]
Issue still persists Analytics js is loading twice, with Yoast
http://take.ms/NyYDc
http://take.ms/ZPDlM

**Comment by MohammedKaludi** [comment]
Fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f5889e5c8093813be8f8f230f0396df128d80162

**Comment by AlvinASaputra** [comment]
Hi, I still got this problem even though I dont use Glue Yoast.
