### ISSUE TITLE
amp-image-lightbox markup is loading in paginated post even the image is not present

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3700]
When the image is present in the 2nd paginated post then the markup is being added in 1,2 etc
The tag 'amp-image-lightbox' requires including the 'amp-image-lightbox' extension JavaScript
https://prnt.sc/pau32f

**Comment by MohammedKaludi** [comment]
This is not the correct solution, this will add the script every where/

**Comment by Zabi09** [comment]
If we enable the lightbox option then we are adding the markup on every page(in master also) so I have added the script wherever there is a markup of it to fix the validation error

**Comment by MohammedKaludi** [comment]
Need to improve the condition of the  code.

**Comment by MohammedKaludi** [comment]
Still not good, please consult me when you are doing this ticket.

**Comment by MohammedKaludi** [comment]
This was the proper fix.  👍 

Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.17 update
