### ISSUE TITLE
Allow people to use captions below thumbnails in gallery

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3702]
https://secure.helpscout.net/conversation/963491088/85532/

**Comment by MohammedKaludi** [comment]
No caption is visible.

https://take.ms/HZhOU

**Comment by Zabi09** [comment]
Will you please enable this option and check the caption - https://prnt.sc/phsrxc

**Comment by MohammedKaludi** [comment]
> Will you please enable this option and check the caption - https://prnt.sc/phsrxc

Already selected as design type 3 in Gallery Design.

**Comment by MohammedKaludi** [comment]
After merging, text the gallery caption in design 2, and check if the styling is messing or not.

In 99-beta branch the styling looks like this: https://take.ms/gyfa6

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
