### ISSUE TITLE
List numbers are not in position

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3704]
https://monosnap.com/file/DuLgi3MY8y0YSbIS9fRXpPVIcoKPqE

https://wordpress.org/support/topic/the-compatibility-issue-when-list-style-is-sat-on-the-decimal/#post-11962914

**Comment by Zabi09** [comment]
Remove the CSS code because that issue was already fixed in - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6ac872bbdb3c1e99f6fd543077aa0c5991537076

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.13
