### ISSUE TITLE
AMP-Carousel – Upgrade to 0.2

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3705]
Can you please upgrade your plugin with latest version of amp-carousel because 0.2 version also supports autoplay and loop.

<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.2.js"></script>

https://wordpress.org/support/topic/upgrade-to-0-2/#post-11969936

**Also, can we do this?**

It will also best if you can provide some hook so that i can use latest version of any AMP JS component instead of the JS component version provided by the plugin.

**Comment by MohammedKaludi** [comment]
Need to make sure need to  test with these parameters:

### Differences from <amp-carousel> 0.1
`autoplay` is allowed on `type="carousel"`
`loop` is allowed on `type="carousel"`

### Migration Notes

- Update the required script from amp-carousel-0.1 to amp-carousel-0.2.

- Ensure any CSS for positioning next/previous arrows is still valid. See the styling for more information on arrow positioning.

- Ensure any CSS used to style the carousel is still valid. The internal DOM structure of <amp-carousel> 0.2 differs from 0.1, effecting CSS selectors targetting internal elements such as amp-carousel > div. Any selectors using the .amp-class-name format should still work.

For more info check this : https://amp.dev/documentation/components/amp-carousel/?format=websites#differences-from-%3Camp-carousel%3E-0.1

**Comment by satindersinghsidhu** [comment]
Thanks for adding this inside your update list

**Comment by wasimmagazine3** [comment]
Changed the amp-carousel version 0.1 to the latest and added the option of autoplay. we have the hook to override custom-script using filter "amp_post_template_data", even though I have created a separate filter to modify custom-script named "ampforwp_set_amp_custom_type_script".

**Comment by Zabi09** [comment]
Please add the autoplay and loop for the type "slides" also

**Comment by MohammedKaludi** [comment]
Gallery not loading properly.

**Comment by WasimM3** [comment]
It is working as expected with the new imported settings.

**Comment by satindersinghsidhu** [comment]
> Changed the amp-carousel version 0.1 to the latest and added the option of autoplay. we have the hook to override custom-script using filter "amp_post_template_data", even though I have created a separate filter to modify custom-script named "ampforwp_set_amp_custom_type_script".

it is still showing https://cdn.ampproject.org/v0/amp-carousel-0.1.js instead of https://cdn.ampproject.org/v0/amp-carousel-0.2.js

**Comment by WasimM3** [comment]
Hi @satindersinghsidhu, this ticket is in the testing phase, it is not pushed to live. So, please follow the ticket until the ticket is closed.

**Comment by MohammedKaludi** [comment]
Gallery not working properly for type 1 and 2
https://take.ms/5GuOk

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.30
