### ISSUE TITLE
When the image is added from ThirstyAffiliate image block from Guntenber editor facing validation error

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3706]
when the image is added from ThirstyAffiliate image block from Gutenberg editor facing validation error as The tag 'ta' is disallowed.

To get that image block we need to activate this  plugin :

https://wordpress.org/plugins/thirstyaffiliates/

The tag <ta> is getting geneated.

https://etramping.com/transport-in-europe-on-the-cheap/?amp

https://secure.helpscout.net/conversation/910588375/75150?folderId=2632030

**Comment by Zabi09** [comment]
<ta><div class="pint-img-con"><amp-img src="http://localhost/wp/wp-content/uploads/2019/10/beach-sand-summer-46710-300x200.jpg" width="760" height="505"></amp-img></div></ta>

Just add this code to recreate

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
