### ISSUE TITLE
When Yoast SEO plugin is activated the same excerpt shows

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3708]
When Yoast SEO plugin is activated the same excerpt shows, This issue occurs only at users end and this rare issue.

See this screenshot:
https://monosnap.com/file/uVbuRWAKt1i45wVBFZdlUnDdsBwE75

REF:https://secure.helpscout.net/conversation/954738315/82268?folderId=3008055

**Comment by SageFargo** [comment]
Any update on the issue?

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
