### ISSUE TITLE
Remove Digg and Google plus option form Social Sharing 

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#3709]
Need to remove Digg option from Social Sharing ->https://take.ms/xWfeg

**Comment by MohammedKaludi** [comment]
Instance of Digg and GPlus are still present in components/social-icons/social-icons.php.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
