### ISSUE TITLE
Dns-prefecht? Why not preconnect?

### ISSUE THREAD

**Issue by Lofesa** [ahmedkaludi/accelerated-mobile-pages#371]
In desing-2/single.php, index.php and desing-1/index.php you put "`<link rel="dns-prefetch" href="https://cdn.ampproject.org">`".
Why don´t put "`<link rel="preconnect" href="https://cdn.ampproject.org">`"?
dns-prefetch pre-allocate the dns search but preload do this plus the ssl negotiation and the connect stages

**Comment by nicholasgriffintn** [comment]
This is a good idea, I'm not sure if preload should be used though, that's more for loading specific resources, preconnect might be a better option for general domains.

https://css-tricks.com/prefetching-preloading-prebrowsing/

**Comment by Lofesa** [comment]
@nicholasgriffintn yes, my mistake, you are rigth. I will refer to preconnect not preload. Change the title and so. Thx you

**Comment by Lofesa** [comment]
This can be closed as far as it is done with PR #401

**Comment by nicholasgriffintn** [comment]
@Lofesa  you can close it yourself, there should be a button near the comments section.

**Comment by Lofesa** [comment]
Ok. But this PR is not merged in master branch thus is not in the last release
