### ISSUE TITLE
Facebook comment is not changing language when we select another language

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3710]
The Facebook comment is not changing language when we select another language then its appear only in English and 

https://monosnap.com/file/GsnPIP3UKbzZ08pC0qwnPJrXSmNbfn
https://monosnap.com/file/IgyJiiqaQ5iYkiRPTLah1MADfWJD4s
https://monosnap.com/file/NFdVfT3QB6r1oyGmbAwNtWOGoi95YZ

REF:https://secure.helpscout.net/conversation/961111377/84811?folderId=3008055

**Comment by MohammedKaludi** [comment]
Code improvement required.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/09099f06066ac027442c1defb70bb4a912450657#diff-3358181277138e309fc94ee4e552f7feR148 

Directly add Attributive in the markup.
`data-locale = "'.esc_attr($lang).'"`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
