### ISSUE TITLE
Search Console error

### ISSUE THREAD

**Issue by Robbo55** [ahmedkaludi/accelerated-mobile-pages#3712]
Hi
I have an error for 715 AMP of my pages/posts on Search Console today
It reads as follows:
"A tag on this page requires an AMP component 'script' tag, which is missing."
Please could you look into this
Thanks
Robert

**Comment by MohammedKaludi** [comment]
@Robbo55 This has been fixed in the latest update, please update the plugin to the latest update and it should fix the issue.

here is the reference ticket.
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3711
