### ISSUE TITLE
Removal of LegacyBuilder option breaks the newspaper custom frontpage design

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#3713]
AMP Newspaper Theme's custom front page images are highly stretched.

**Comment by MohammedKaludi** [comment]
Issue came after this ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3609

**Comment by Zabi09** [comment]
Fixed in 1.19 version of newspaper amp theme
