### ISSUE TITLE
youtube oembed video on google search console

### ISSUE THREAD

**Issue by liberonaleon** [ahmedkaludi/accelerated-mobile-pages#3714]
Most of my videos inserted via oembed in the content, generate errors in the Google search console. The problem in the code is:

`<amp data-videoid = "Go2jbER0wk0" layout = "responsive" width = "1000" height = "563"> </amp>`

and the right way would be:

`<amp-youtube data-videoid = "Go2jbER0wk0" layout = "responsive" width = "1000" height = "563"> </amp-youtube>`

Or is it just me?

**Comment by MohammedKaludi** [comment]
Can you please let us know when it's happening since?

**Comment by liberonaleon** [comment]
i think since always. because i have the same error on older and newest post

**Comment by ahmedkaludi** [comment]
We don't see this issue at the moment on our end, I request you to get help from our technical team over at http://ampforwp.com/support - Github is for tried and tested re-creatable bugs
