### ISSUE TITLE
AMP CTA plugin keeps updating from 2.1 to 2.2

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3715]
I think this is not the right place to report this, but I know you'll get this message where it belongs...
The thing is when you update the plugin it appears to update perfectly but as soon as you return to the plugins screen it asks you to update again from 2.1 to 2.2 (in a loop)
regards

**Comment by merajali294** [comment]
@olddoc, thanks for reporting this to us, I see that the version number isn't updated in the Version 2.2 and yes I've noted it down and will solve this in the next upcoming update.
