### ISSUE TITLE
Need to add leave comment feature in amp comment section

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3716]
Need to add leave comment feature in the amp comment section, Need to make sure that it will work in all design.

https://monosnap.com/file/4A8Bf8K6G4h0tfwGSGWWoFCcNompJQ
https://monosnap.com/file/GoGJMWoCN9c2zP5rF35UtMiH9mEhMJ

REF:https://secure.helpscout.net/conversation/966410224/86145/

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/559fe91ad5986fb885e4488826361e1cbe7c2978#diff-6aa5512f7dd8d5ce60fc97b0f340912cR2262 missing `Text Domain`

**Comment by MohammedKaludi** [comment]
1. Border not looking good.  https://take.ms/QVKc9

2. If empty set in the Title section: https://take.ms/hUJYM Mark up is loading https://take.ms/PhAhQ

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.38
