### ISSUE TITLE
Wrong amphtml when static page is selected in reading settings along with ?amp endpoint

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3717]
Wrong amphtml when static page is selected in reading settings along ?amp endpoint

https://monosnap.com/file/6hvaPtPU6yLaNNEmaMQ04DbAgXxws4

**Comment by ajeetku** [comment]
Wrong way for conditions. 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/464a03714ffc21540eacb2877c1936bcc103b27b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR347
Add those conditions properly

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
