### ISSUE TITLE
admin toolbar is not showing on custom amp page

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3718]
admin tool bar is not showing on amp page created with AMP framework.
https://secure.helpscout.net/file/cfb9786cbb6b9b7c/420112/2723062323/221894364/
https://secure.helpscout.net/file/cfb9786cbb6b9b7c/420112/2723062323/221894365/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.17
