### ISSUE TITLE
how to show default fallback images as a parameter

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3719]
USE Case: The user is creating a custom theme with AMP Theme framework.
https://secure.helpscout.net/conversation/968281408/86940?folderId=3257665

if the features image for the particular block is not uploaded.
then how to show default fallback images rather than showing blank space. 
links:
https://scrn.li/0oFBh71y59dOm2
https://scrn.li/KuNM98hZU9fFpR

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
