### ISSUE TITLE
The tag ‘amp-social-share extension .js script’ is missing or incorrect

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#372]
**Ref:** https://wordpress.org/support/topic/social-tag-missing/
https://wordpress.org/support/topic/plugin-not-working-468/
https://wordpress.org/support/topic/social-share-not-working-on-home-page/

**Comment by cvvcremodel** [comment]
I am using version 9.53 and still seeing - Invalid usage of AMP tags on home page only
The tag 'amp-social-share' requires including the 'amp-social-share' extension JavaScript.
6 instances

Line 761:12
<amp-social-share type="facebook" width="50" height="28"></amp-social-share>
Line 762:21
<amp-social-share type="twitter"
Line 768:20
<amp-social-share type="gplus" width="50" height="28"></amp-social-share>
Line 769:20
<amp-social-share type="email" width="50" height="28"></amp-social-share>
Line 770:20
<amp-social-share type="pinterest" width="50" height="28"></amp-social-share>
Line 771:20
<amp-social-share type="linkedin" width="50" height="28"></amp

**Comment by MARQAS** [comment]
Hey @cvvcremodel,
Please update to the latest version, we have resolved this issue.
