### ISSUE TITLE
My AAWP table is not working when I install AMP

### ISSUE THREAD

**Issue by mdmaksud** [ahmedkaludi/accelerated-mobile-pages#3720]
My AAWP table is not working when I install AMP. How can I solve this issue? 
Any suggestion? 

Please check the screen short full table is broken. 
![1569868922644](https://user-images.githubusercontent.com/55998945/65906521-bbf98b00-e390-11e9-881a-d793792e0173.JPEG)
![1569868922663](https://user-images.githubusercontent.com/55998945/65906523-bc922180-e390-11e9-8737-3ecb125cc613.JPEG)
![1569868922692](https://user-images.githubusercontent.com/55998945/65906524-bc922180-e390-11e9-8ea4-709bfd0c8178.JPEG)
![1569868922623](https://user-images.githubusercontent.com/55998945/65906525-bd2ab800-e390-11e9-8bb6-add665c0615d.JPEG)

**Comment by ahmedkaludi** [comment]
we don't have the AAWP support at the moment.  I suggest you to take help from our technical team first at http://ampforwp.com/support
