### ISSUE TITLE
Problem with duplicated "link rel=canonical" with Rank Math

### ISSUE THREAD

**Issue by zheive** [ahmedkaludi/accelerated-mobile-pages#3721]
I have this issue with with versión 0.9.98.13  and latest Rank Math version.
![Captura de pantalla_2019-10-01_07-42-46](https://user-images.githubusercontent.com/8024464/65937235-8f408480-e41f-11e9-9e44-77a7c4e26f0a.png)

**Comment by ahmedkaludi** [comment]
The Github is for tried and tested bugs, this could be in some rare setting conflict, I suggest you to take help from our technical team first at http://ampforwp.com/support
