### ISSUE TITLE
Stuck with the google font typographies even after turning them off

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3722]
I was trying to use arial as my main and only font, but it seems there is no way to turn "raleway" font off (it's a google font), even after turned google fonts off.
My Theme is swift. 
Strange thing though is that in the stage site I run does not happen and fonts are ok...
Contact me for site/pass/etc...
Maybe it is related to some issues I had some months ago where I could not change the font in swift (font settings did not save properly...) and the default swift-theme font could not be changed...

**Comment by ahmedkaludi** [comment]
The Github is for tried and tested bugs, this could be due to some 3rd party conflict, I suggest you to take help from our technical team first at http://ampforwp.com/support
