### ISSUE TITLE
AMP Update to Version 0.9.98.13 causes an error

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3723]
Error message
Warning: strpos(): Empty needle in /home/statecer/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 5776

Ref: https://secure.helpscout.net/conversation/967806549/86811?folderId=1060554

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.98.14
