### ISSUE TITLE
The post title appears 2 times: after the parent category and after the child on breadcrumb.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3724]
Screenshot: https://monosnap.com/file/dQA04cRKfXQPC60rlIijWYL5srJm2k

The Post Titles are appearing more than once on the breadcrumb. 
Ref: https://secure.helpscout.net/conversation/941826687/79566?folderId=2770545

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22
