### ISSUE TITLE
Compatibility of PenNews theme featured video with amp

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/accelerated-mobile-pages#3726]
Ref : https://secure.helpscout.net/conversation/964228173/85759?folderId=3250553

Need to add compatibility of PenNews theme's featured video with "ampforwp" as the featured video is not coming in amp version.

Website: https://qnthb.flywheelstaging.com/wp-login.php

**Comment by wasimmagazine3** [comment]
This enhancement is done in #3668

**Comment by MohammedKaludi** [comment]
Fixed in below mentioned ticket.

Ticket : #3668 

Commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/85aa8cf13634a3d6820b4c2df9d3e0f7caae86d0
