### ISSUE TITLE
Inline style width is changing to max-width.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3727]
`<span style="width: 46.6%;">TEST</span>
<span style="width: 80%;">Hello</span>`
output :  
span.acssaebc1 {
    max-width: 46.6%;
}
span.acss38b77 {
    max-width: 80%;
}

**Comment by ahmedkaludi** [comment]
is https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3741 related to this ticket?

**Comment by MohammedKaludi** [comment]
Not the proper solution. This is not the correct fix.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/51e0ef96ddf014296a37a8d93a91abf7c0cdb03b#diff-ed45a2516e7139734f28a770b4e7afd7R543

**Comment by Zabi09** [comment]
Added in CSS in V3 layout of AMP WooCommerce PRO and that has fixed this issue, So reverted the code from here
