### ISSUE TITLE
In template mode Need to show extension setting panel.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3728]
Desc: In template mode Need to show extension setting panel now it is showing only settings

**Comment by wasimmagazine3** [comment]
It's working fine in beta. Issue with master. I think need to review #3562 for this issue.

**Comment by sonaliramteke** [comment]
Extension setting panel not coming

**Comment by sonaliramteke** [comment]
When we click on Enter license button it is not properly redirecting to extensions menu for entering license key when we click on Enter license button second time it appearing properly.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
