### ISSUE TITLE
Debug warnings after recent update

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3730]
Notice: Undefined index: ampforwp_amp_mode in /var/www/vhosts/klippenbosch.co.za/httpdocs/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php on line 264

http://klippenbosch.co.za/

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.14
