### ISSUE TITLE
Need to fix the notice and warning message issue when WP_DEBUG is true

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3731]
Message:

pages/includes/features/structure-data/structured-data-functions.php on line 283

Notice: Trying to get property 'post_type' of non-object in /nas/content/live/fightingdads33/wp-content/plugins/accelerated-mobile-pages/includes/features/structure-data/structured-data-functions.php on line 285

Notice: Trying to get property 'ID' of non-object in /nas/content/live/fightingdads33/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4918

Ref: https://secure.helpscout.net/conversation/951340481/81492?folderId=2770545

**Comment by sonaliramteke** [comment]
Warning: DOMDocument::loadHTML(): Empty string supplied as input in C:\xampp\htdocs\Demowpsite\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 7131 (in 99 beta)

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.14
