### ISSUE TITLE
Performance issues in AMP FOR WP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3732]
- [ ] YOAST SEO Table

- [ ] Long List of numbers(get_posts())

- [ ] update_option()

- [ ] get_instance()

- [ ] update_meta_cache()

- [ ] Optimising Post meta Rows, as we are saving all the data individually, Need to store all AMP related post-meta info in one array. #801 

Ref: https://secure.helpscout.net/conversation/967068200/86296?folderId=1060554

**Comment by TMsravan** [comment]
Another performance issue: https://secure.helpscout.net/conversation/992392988/95261?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
