### ISSUE TITLE
Rank Math and link rel="canonical" twice

### ISSUE THREAD

**Issue by thindpls** [ahmedkaludi/accelerated-mobile-pages#3734]
I receive a google AMP version, "not valid warning" when using Rank Math plugin. The warning shows duplicate -link rel="canonical" .

**Comment by ahmedkaludi** [comment]
can you share the URL where you are facing this?

**Comment by ahmedkaludi** [comment]
We don't see this issue at the moment on our end, I request you to get help from our technical team over at http://ampforwp.com/support - Github is for tried and tested re-creatable bugs
