### ISSUE TITLE
Content Sneak Peak Bug

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#3737]
Hello,

After some testing I’ve found out that the word count doesn’t affect the content sneak peak feature. I think it’s the amount of items displayed that matters. On one post the word count is 95 and the Content Sneak Peak is working fine, on the other post the word count is 158 and the Content Sneak Peak doesn’t work, which is weird. 

Looking forward for a fix to this issue, and hopefully it’ll make it to the next update. @ahmedkaludi  @Zabi09 please take some time and look into this.

**Comment by ahmedkaludi** [comment]
We don't see this issue at the moment on our end, I request you to get help from our technical team over at http://ampforwp.com/support - Github is for tried and tested re-creatable bugs
