### ISSUE TITLE
I am unable to get Add to Bookmark popup in mobile PWA

### ISSUE THREAD

**Issue by koushikch7** [ahmedkaludi/accelerated-mobile-pages#3738]
Hi i am using PWA that is recommended by you, but i am not getting add to bookmark or download app popup in mobile view, my website is https://chkoushik.com please check this issue.

**Comment by ahmedkaludi** [comment]
we would love to help you with the issue, but kindly ask our PWA support team on https://pwa-for-wp.com/contact-us/
