### ISSUE TITLE
The tag 'thrive_headline' is disallowed.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#374]
The Thrive builder has it's own tag which doesn't complient with AMp, for example use this html in the content,
 
<a href="http://roadbikehub.com/best-road-bikes-women-review/amp"><thrive_headline click tho-post-1789 tho-test-9>Best Road Bikes For Women Review</thrive_headline></a>

We need to strip thrive_headline tag but not remove the text under it, just remove that tag, so the text is still visible.

**Comment by Lofesa** [comment]
Hi @ahmedkaludi 

I use Visual Composer in some pages but remove the shortcodes for amp version whit these function:

function remove_shortcode_vcomposer($content) {
	if ( is_amp_endpoint() ) {
	$patterns = "/\[[\/]?vc_[^\]]*\]/"; 
	$replacements = "";
	return preg_replace($patterns, $replacements, $content);
	} 
} 
add_filter('the_content', 'remove_shortcode_vcomposer');

Perhaps some like this help you in this issue

**Comment by MohammedKaludi** [comment]
Tested
