### ISSUE TITLE
Need to link Comments section with comments order

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3740]
Screenshot: https://monosnap.com/file/FkVqXdm5JeJfpS2hG6K7ImVUlhKk0e

Ref: https://secure.helpscout.net/conversation/969111009/87148?folderId=1060554

We need to link our Comments section with Comments order in-dashboard panel of Wordpress.

**Comment by MohammedKaludi** [comment]
Comments position not changing in Design 1 1

**Comment by MohammedKaludi** [comment]
escaping required.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3896558bfdb63db83605ec6d2da1e813dc52cb2c#diff-3358181277138e309fc94ee4e552f7feR36

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
