### ISSUE TITLE
Facebook like button is not showing correctly after last update in design3

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3742]
Screenshot: https://monosnap.com/file/qpa9OU3vHzi6FKL5G809GZ2qNyMvOC

Ref: https://secure.helpscout.net/conversation/972890430/88022?folderId=1060554

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
