### ISSUE TITLE
Add Link of tutorial in pop up notification field in "Add new ad" section

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3743]
We need to add link of tutorial in the pop up notification box according to the Ad type selected in Add new ad section.
https://prnt.sc/pfwwgj

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/ads-for-wp #258](https://github.com/ahmedkaludi/ads-for-wp/issues/258) via [**ZenHub**](https://www.zenhub.com/)
