### ISSUE TITLE
Menu closer icon is getting overlapped by the header part of firefox web browser

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3744]
https://secure.helpscout.net/conversation/973055460/88062?folderId=2632030

Ref: https://monosnap.com/file/XUHVIlZI24V3JWByCF1PFx4pCEqsKm

Menu closer icon is getting overlapped by the header part of the firefox web browser when we open the amp site in swift theme

**Comment by MohammedKaludi** [comment]
Need to keep : `height:-webkit-fill-available;`


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6cf5fa6202aeca47e46ef9170658be599eba19bf#diff-2ae5550e31f40c1962ca69d373af6b93L240

**Comment by RajuJeelaga** [comment]
After Discussion with @MohammedKaludi sir, regards the above commit, i am moving this ticket.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
