### ISSUE TITLE
Non-Responsive tables after version 0.9.98.9

### ISSUE THREAD

**Issue by 7bhabesh** [ahmedkaludi/accelerated-mobile-pages#3746]
I am still using **0.9.98.9** version because TablePress plugin became non-responsive from version 0.9.98.10 (18th SEPTEMBER 2019). I added a table (via TablePress) with 4 columns here [https://www.dealntech.com/exynos-9611-vs-snapdragon-712-vs-helio-g90t/amp/](url), but if I update to 0.9.98.10 or any other newer versions, I can't scroll the table left or right (Non-Responsive). Please solve the issue as soon as possible.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by 7bhabesh** [comment]
Hey, Mohammed when you are going to add this patch to the plugin? Version 0.9.98.15 hasn't came with the fix.

**Comment by Zabi09** [comment]
@7bhabesh Sorry for the delay and we are going to push this ticket in 0.9.98.16 which we are going to release today

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.

**Comment by 7bhabesh** [comment]
Thanks for the fix Mohammed
