### ISSUE TITLE
Spell check tag is now allowed

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#375]
Here is the html which has this code spellcheck tag, it is not compliant with amp. So we need to strip it and make sure that it doesnt remove any content inside it but just this tag.

`<ul class="tve_ul tve_ul1 tve_green"><li class="" spellcheck="false">An extremely bright 1200 lumen output.</li><li class="" spellcheck="false">3 easy light modes: high (1200 lumens), medium (800 lumens), and strobe.</li><li class="" spellcheck="false">If you hold the power button for 3 seconds while the light is off, the light transforms into a five mode light, which gives you two more modes: low mode (350 lumens) and an SOS pattern.</li><li class="" spellcheck="false">Lasts for about 3 hours on high mode, 5 hours on medium, and 26 hours on low mode.</li><li class="" spellcheck="false">Maintains a 1200 lumen output level until the battery is fully drained, which means no dimming during use.</li><li class="" spellcheck="false">Rechargeable waterproof battery.</li><li class="" spellcheck="false">Comes with a high-quality LED lamp and a free head harness mount for biking, hiking, running, and camping.</li><li class="" spellcheck="false">Comes with a lifetime insurance guarantee on the bicycle headlight and a 1-year warranty on the battery.</li>
`

**Comment by MohammedKaludi** [comment]
Tested and its working
