### ISSUE TITLE
Comment closed opion need to be removed.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3750]
If the user doesn't want to use comments or else didn't enable the below options then the "comments closed" div should be removed. 

options: https://monosnap.com/file/XZt4vbd6Jl7V40b3qMT4eYXzJZeinj
need to remove: https://monosnap.com/file/rXxTFGB5Uj6xLGwVcLpMyAO1Wljkql

Ref URL: https://mister-striptease.com/stripteaseurs-yonne/amp/

**Comment by MohammedKaludi** [comment]
Wrong stying removed.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7b85bc7e5cf43b931d37e474ebc7a8d5198816ce#diff-2ae5550e31f40c1962ca69d373af6b93L484

only remove the styling of `. nocomments` class not the whole buton.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
