### ISSUE TITLE
After 0.9.98.13, my AMP post cannot show in google search

### ISSUE THREAD

**Issue by ngconghuan** [ahmedkaludi/accelerated-mobile-pages#3751]
Please see screenshot to understand more what im talking about.. now all my post back to normal link in google search, i try to roll back to 0.9.98.11 but no luck at all!

![Screenshot (9)](https://user-images.githubusercontent.com/4292578/66669831-8901a200-ec82-11e9-8f42-e5fec12f54ee.png)

**Comment by ahmedkaludi** [comment]
Our technical team will help you with validation errors. Just write them at https://ampforwp.com/support/

The GitHub for tested and recreatable bugs.
