### ISSUE TITLE
Need to add preload key requests for font icons

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3752]
User faced speed performance issue that needs to add preload key requests for font icons,

For example please refer to the below screenshot.
Ref: https://monosnap.com/file/8xI9XmTcFShDNeE1zfSjM7NuhHZFpX

User ticket: https://secure.helpscout.net/conversation/968055694/86907?folderId=1060556
Documentation: https://developers.google.com/web/tools/lighthouse/audits/preload

**Comment by MohammedKaludi** [comment]
Escaped too early, late escaping  has to be done.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e359c608bbcbf9423c5d66f8ede1dfe6e6d6c001#diff-9f65b1edeb6d18b3cc5f9f2a21bfd824R51

**Comment by MohammedKaludi** [comment]
Add the preload for FontAwesome icons as well

**Comment by wasimmagazine3** [comment]
Moved the font awesome prefetch location to the top of CSS.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.0
