### ISSUE TITLE
Page should be full width if the page builder is used

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3756]
Page should be full width if the page builder is used in Design 1, 2 and 3

**Comment by MohammedKaludi** [comment]
Remove post navigation if  pagebuilder is Enabled. https://take.ms/nuPi5

**Comment by MohammedKaludi** [comment]
Condition needs improvements 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/abffc400f800b177b5912315e9c11ecc32c94283#diff-e57ec3310984798e175233ae89a68fdbR115

**Comment by MohammedKaludi** [comment]
Padding top and bottom is broken. https://take.ms/qGWiq

remove the `! ampforwp_is_home()` instead use ` (is_singular() || ampforwp_is_front_page() )`

**Comment by MohammedKaludi** [comment]
Validation Error in the Homepage.

https://take.ms/M9bVp

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
