### ISSUE TITLE
Improve Matemo analytics integration

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3757]
Our current solution isn't tracking data but there's no data available online but two new ways of integration which supposedly works. 

- [x] https://forum.matomo.org/t/how-to-add-piwik-to-amp-pages/18424/6

- [x] https://pastebin.com/DWq7bnnQ  https://monosnap.com/file/CbKiiNNW0FNRi8senypiKGFiMwvyOp

- [x] create new piwik installation and verify

**Comment by Zabi09** [comment]
Escaping is missing

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
