### ISSUE TITLE
Proper solution to exclude the AMP feature

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#376]
I’ve tried to disable AMP on certain pages by switching to Amp – Hide.
It still has the link to the AMP document in the header?

I’ve put a web.config redirect in to blog the amp homepage for now, but would appreciate a proper fix.

https://ampforwp.com/exclude-page-post-amp/#comment-924

**Comment by MohammedKaludi** [comment]
Fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/332
