### ISSUE TITLE
Recent Posts are not showing on  pages

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3760]
User details :https://secure.helpscout.net/conversation/966165799/86088?folderId=2770543

Most recent posts are not showing pages. its picks randomly post and it does not pick very most recent posts in pages. 
This issue recreates in local as well.

**Comment by Zabi09** [comment]
The user was adding the offset of "3" in the category module and due to that the most 3 recent posts were not showing up in AMP
