### ISSUE TITLE
 Meta description are not showing properly in genesis

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3761]
Ref: https://secure.helpscout.net/conversation/979604511/90735?folderId=3257665
So it worked in the last version but not this version of the plugin.

**Comment by MohammedKaludi** [comment]
Always escape when calling from database.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b28f47ab25a2e12eb4be2a1bdc505d545be924bd#diff-04b38a94ddf918855eed7a68ecaa512dR307

**Comment by MohammedKaludi** [comment]
dont fix the  tickets in hurry.
escaping still pending on few areas/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
