### ISSUE TITLE
Hide button always showing on page

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/accelerated-mobile-pages#3762]
Even if we turn off "hide" then, after an update of the page again it returns back to "hide".

This is encountered on "page".

Ref : https://secure.helpscout.net/conversation/979909210/90918?folderId=1060556

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
