### ISSUE TITLE
AMP Page-builder bug  

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#3763]
Hi,

I’ve created a slider with the AMP Page builder and it works just fine, but when you start scrolling the slider goes crazy, it slides images as you scroll. 
And also I’d like to know if there’s an option or css code to increase the image caption in the slider.

**Comment by ahmedkaludi** [comment]
GitHub is for tried and tested bugs, to get support on technical issue, kindly raise a support ticket
