### ISSUE TITLE
Need to add filter in "wp_localize_script" 

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3764]
Need to add filter in "wp_localize_script" ,In that need to modifiey $redux_data file is (funtion.php/includes/feature)

REF:https://secure.helpscout.net/conversation/965050797/85890?folderId=3008055

**Comment by MohammedKaludi** [comment]
We need the filter to modify the redux data 

The solution done is incorrect.

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/4950acf259dfafcce4d19750a4582bb919456742/includes/features/functions.php#L40

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.0
