### ISSUE TITLE
Icons are not loading when creating theme compatibility

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#3766]
I have debug and found that the path is not correct when we add font folder inside themes

This scenario issue occurring  - https://ampforwp.com/tutorials/article/how-to-make-your-theme-compatible-with-amp/ 

http://localhost/wp-1/wp-content/plugins/C:/xampp/htdocs/wp-1/wp-content/themes/twentyseventeen/ampforwp/fonts/icomoon.ttf

It should be like this -  http://localhost/wp-1/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/swift/fonts/icomoon.ttf

**Comment by MohammedKaludi** [comment]
if sonali is not available and if you are not able to recreate the issue the do let me know.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2e380506cdecd047bdf8090b9d6e8fda46f0ae4b#diff-e57ec3310984798e175233ae89a68fdbR71,  https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2e380506cdecd047bdf8090b9d6e8fda46f0ae4b#diff-e57ec3310984798e175233ae89a68fdbR79 Use here Constant `AMPFORWP_PLUGIN_DIR_URI`

**Comment by MohammedKaludi** [comment]
Not able to recreate.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.13
