### ISSUE TITLE
If hide amp hide on post or pages from anywhere then that needs to redirect to 301

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3767]
If hide amp hides on post or pages from anywhere then that needs to redirect to 301, not in 302.

REF:https://secure.helpscout.net/conversation/893365069/72422?folderId=3008055

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.0
