### ISSUE TITLE
Option Panel not saving in AMP FOR WP, it is giving 404 error

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3768]
Ref: https://secure.helpscout.net/conversation/963646478/85592?folderId=2770545

**Comment by wankhedekomal** [comment]
- [ ]  Bluehost cPanel is not showing a mod_security option. 
we need to find from where our code is affecting the mod security. and the user is getting this error: https://monosnap.com/file/LdVHJbXQjWVRJoqDWo7dLX5M0ng7w6

Ref: https://secure.helpscout.net/conversation/985403331/92983?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
