### ISSUE TITLE
Breadcrumb breaks when '/' is present in category name

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3769]
https://secure.helpscout.net/conversation/981488684/91457?folderId=2632030

Example category name like:  1/8 Scale Figures

https://monosnap.com/file/W0uF2roQVzIWwsMYB7AJSxisw9cKGH

**Comment by MohammedKaludi** [comment]
Ticket failed: Reason explained to zabi.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21

**Comment by LuchaBeast** [comment]
Can this ticket be reopened? This did not fix the bug. It actually made it worse.
![image](https://user-images.githubusercontent.com/307840/70205155-03293280-16d8-11ea-9dd3-27eaaaa28326.png)

The breadcrumb in this example should read **Anime Figures > Scale Figures > 1/7 Scale Figures > _{Post Title}_**
