### ISSUE TITLE
AMP page specific css class

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#377]
**Ref:**https://wordpress.org/support/topic/hide-prevnext-on-amp-pages-only-not-posts/

**Comment by MohammedKaludi** [comment]
On pages "amp-single-page" class added in the body, so pages can be styled with more detail.

@MARQAS  tell the use to Use this css to hide pagination in Pages
.amp-single-page #pagination { display: none; }
