### ISSUE TITLE
Gravity form plugin quiz addon conflict with AMP Plugin

### ISSUE THREAD

**Issue by ranavaqar** [ahmedkaludi/accelerated-mobile-pages#3773]
after submit form paragraph breaks. 

non amp: https://studykorner.com/gravity-form-quiz-plugin-post/

amp: https://studykorner.com/gravity-form-quiz-plugin-post/amp/

**Comment by ahmedkaludi** [comment]
GitHub is for tested and recreatable bugs, I recommend you to write to our technical team at https://ampforwp.com/support  and they will help with this.
