### ISSUE TITLE
Need to make compatibility with FV Flowplayer Video Player

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3775]
One thing to note is that at the user's end, the video is getting played without any error. Only he is facing an issue when the AMP takeover beta option is enabled at his end.

https://wordpress.org/plugins/fv-wordpress-flowplayer/
https://secure.helpscout.net/conversation/982815879/92143?folderId=2632030

### Tasks

- [ ]  Flowplayer Video Player should work in AMP when added in the post content

- [ ]  FV Flowplayer Video Player not working when AMP takeover(beta) is active #3805

**Comment by wankhedekomal** [comment]
users suggestion for code improvement:
https://github.com/foliovision/fv-wordpress-flowplayer/blob/master/models/flowplayer-frontend.php#L333-L378

Ref: https://secure.helpscout.net/conversation/1049571003/105601?folderId=3257665

**Comment by MohammedKaludi** [comment]
> users suggestion for code improvement:
> https://github.com/foliovision/fv-wordpress-flowplayer/blob/master/models/flowplayer-frontend.php#L333-L378
> 
> Ref: https://secure.helpscout.net/conversation/1049571003/105601?folderId=3257665

Code Needs improvements.

**Comment by MohammedKaludi** [comment]
Reported on: https://ampforwp.com/compatibility/idea-board/
