### ISSUE TITLE
Internal links are breaking in Persian language

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3777]
Ref: https://secure.helpscout.net/conversation/969243683/87191?folderId=3126461 Ref Text: https://www.diffchecker.com/jkwNvYF4

When user is clicking on internal links in AMP version it is redirecting to 404 page

**Comment by MohammedKaludi** [comment]
this is not the correct fix.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.17 update
