### ISSUE TITLE
Warning: preg_match() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by heisfullstacked** [ahmedkaludi/accelerated-mobile-pages#3778]
Wordpress version: 4.6.12
AMP for WP Plugin version: 0.9.98.7

Getting this warning for '/amp' pages: 
Warning: preg_match() expects parameter 2 to be string, array given in /var/www/html/blog/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php on line 1207

Example: https://pharmeasy.in/blog/can-power-naps-help-you-become-smarter/amp/

Started seeing this error from 5 September and the number of pages affected by this error in Google Search Console has been increasing over time.

Tried deleting the plugin but the '/amp' pages are still available.

**Comment by MohammedKaludi** [comment]
This fix looks incorrect. 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d9997ab1731d575831d73d0c17dc5bfd9caf8a57#diff-67677c038d3b8306e6c37f4507daaa17R1208

**Comment by heisfullstacked** [comment]
> This fix looks incorrect.
> [d9997ab#diff-67677c038d3b8306e6c37f4507daaa17R1208](https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d9997ab1731d575831d73d0c17dc5bfd9caf8a57#diff-67677c038d3b8306e6c37f4507daaa17R1208)

The issue is because of Wordpress `wp_parse_url()` function not accepting the second `$component` argument before version 4.7. The solution would be on the lines of finding the wordpress `version` and accordingly interpret the response.

Can I create a PR for the same?

**Comment by ahmedkaludi** [comment]
Yes, we would love to have your contribution

**Comment by heisfullstacked** [comment]
Okay taking it up.

**Comment by heisfullstacked** [comment]
Waiting for review on the PR: https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3842
@ahmedkaludi @MohammedKaludi

**Comment by MohammedKaludi** [comment]
@Zabi09 fix is done here, can you please take a look at it
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3842

**Comment by Zabi09** [comment]
Fixed in - https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/3842
