### ISSUE TITLE
Issue with AMP page builder tool when images are inserted in slider module.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3780]
When user inserting images trough the AMP page builder-slider module then the image query is loading multiple times as we can observe in query monitor and this effect on page speed.

Steps to recreate the issue:

1) Import home page from the user and upload it to our localhost.

2) Now in AMP page builder, we can find the slider module in that user is inserting images 

Plugin need to download :
Query monitor(Version 2.17.0)

There in query monitor, we can observe how many times an image query is loading.

User ticket: https://secure.helpscout.net/conversation/930210811/78409?folderId=3126461
URL: https://entrepreneurscan.com/amp

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22
