### ISSUE TITLE
image transients should clear automatically

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3781]
image transients should clear automatically

**Comment by ahmedkaludi** [comment]
Images with unknown Dimensions optimization suggestions
Maybe you can refer to this method
https://amp.dev/documentation/examples/style-layout/how_to_support_images_with_unknown_dimensions/?format=websites

If an article has a lot of images without a defined size, the current plugin will have too many getimagesize calls, sometimes causing PHP Fatal error: Allowed memory size of 314572800 bytes exhausted

**Comment by MohammedKaludi** [comment]
Improve the Filter name 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/fc574949973dc4ae2292808df995577d283d52ae#diff-9403c03929c0726e9201dac8cf66cbdcR86

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
