### ISSUE TITLE
Yoast Separator is converting from Hyphen to Dash 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3783]
the title tag not work correctly in AMP page
Original = <title>Pecahan Sederhana | 4 Cara Menyederhanakan Pecahan – Advernesia</title>
AMP = <title>Pecahan Sederhana | 4 Cara Menyederhanakan Pecahan – Advernesia</title>

Make problem in Google Analytics and so in SEO i think

the original using Hyphen (-)
the AMP replace it to En Dash (–)

If we use Yoast SEO we can choose the separator using hyphen, en dash, and other character that available. As we know it can accessed via SEO > Search Appearance. Actually i don’t know the effect of SEO.

If we running Google Analytics, the view report will different in title page AMP and NOT AMP. But, if the user have basic knowledge in Google Analytic, this is not a problem. We can create filter of view that replace En Dash to Hyphen in page title report.

REF: https://wordpress.org/support/topic/how-to-change-title-separator-in-tag/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
