### ISSUE TITLE
Varnish and Mobile Redirection Compatibility

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3784]
Here's how we can do this:
- https://spin.atomicobject.com/2013/02/11/varnish-cache-mobile-devices/
- https://gist.github.com/benclark/3176314
- https://varnish-cache.org/docs/trunk/users-guide/devicedetection.html

REF: https://wordpress.org/support/topic/varnish-compatibility-issue-with-session-keys/#post-12043783

**Comment by ahmedkaludi** [comment]
Quoting from the user: 

You're right, the Varnish issue no longer exists. In the past week, I have
removed some plugins and tags, and one of those must have been affecting
the AMPforWP plugin and causing the issue. I am not able to replicate.
Sorry for the inconvenience.


-- So we will close the ticket for now

**Comment by AndreiG6** [comment]
How was this resolved? The issue still seems to persist. Out of all my plugins, the only one that has a session_start() is yours, in wp-content/plugins/accelerated-mobile-pages/includes/redirect.php and wp-content/plugins/accelerated-mobile-pages/includes/options/extensions/vendor_support/vendor_support/vendor/ace_editor/mode-php.js

**Comment by AndreiG6** [comment]
Redirect should be done using js not php

**Comment by ahmedkaludi** [comment]
@andreiG6 

Can you please send us an email on team@ampforwp.com? 
So we can discuss this issue and figure out the solution

**Comment by AndreiG6** [comment]
For anyone who ends up here due to the initial cache issues reported, #3844 has been created to address the redirect method
