### ISSUE TITLE
CSS issue.

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#3785]
We are adding a CSS by targeting all the id's in .cntn-wrp when sticky header is enabled which causing an issue in AMP form where some field of from is not enterable. because the unnecessary CSS is applying to all the ID's inside the .cntn-wrp class.

we are adding this CSS when sticky header is enabled so please make necessary changes so it will not affect others and make sure it works perfectly with sticky header functionality as well.

Here is the css in style.php of swift theme.
<?php
if(is_singular() && true == ampforwp_get_setting('amp-sticky-header')){?>
.cntn-wrp *[id]:before { 
  display: block; 
  content: " "; 
  margin-top: -75px; 
  height: 75px; 
  visibility: hidden;}

**Comment by RajuJeelaga** [comment]
Reviewed by Ahmed

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
