### ISSUE TITLE
Search results on/off option in amp

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/accelerated-mobile-pages#3786]
Need to add search results on/off option in amp so that the search page does not take to "?amp" in mobile phone even if the mobile redirection is on.

Ref: https://secure.helpscout.net/conversation/985814445/93236?folderId=3250553

URL: https://www.hiig.de/

Screenshot: https://monosnap.com/file/D1eDEwj0HFvH5gLCfN5JWderyDCxRH https://monosnap.com/file/hWsAvjQomGbGrbB71xk1nvcY9ScQL2

**Comment by amer07** [comment]
Case-II

https://secure.helpscout.net/conversation/993625081/95648?folderId=1060556

**Comment by MohammedKaludi** [comment]
The fix is incorrect.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.17 update
