### ISSUE TITLE
Amp Page builder is not working when DFD theme activated 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3787]
Ref ;https://secure.helpscout.net/conversation/983917978/92612?folderId=2770543
Also, recreate this issue in local as well.

**Comment by Zabi09** [comment]
Fixed on users end by adding the code in the theme itself - https://prnt.sc/pph1hd and it seems that the AMP page builder is now working as aspected.- https://prnt.sc/pph1di

**Comment by Zabi09** [comment]
Also contacted the theme developers to add those changes, So closing this ticket
