### ISSUE TITLE
hreflang conflicts within page source code

### ISSUE THREAD

**Issue by olddoc** [ahmedkaludi/accelerated-mobile-pages#3789]
Seems to be in every AMP page created (does not happen with the not AMP pages). We use WPML. 

It seems hreflang is there in the heading but poorly implemented which gives two errors:

1- Conflicting hreflang and rel=canonical 
The canonical tag on the page points to a different language URL. When using canonical tags on your website along with hreflang attributes, you should make sure to specify a self-referential canonical tag.

2- No self-referencing hreflang 
If your page doesn’t contain a self-referencing hreflang in its set of hreflang attributes, those attributes may be ignored or interpreted incorrectly.
Include this page’s URL and language code in your set of hreflang attributes.

Semrush flags it as an error (also see their page checker at:
(https://www.semrush.com/features/site-audit/?utm_source=blog&utm_medium=hreflang-research&utm_campaign=international-seo))

Also as you know hreflang is really important for SEO if you are running a multilingual site...

ABOUT THIS ISSUE
If you're running a multilingual website, it is necessary to help users from other countries find your content in the language that is most appropriate for them. This is where the hreflang (rel="alternate" hreflang="x") attribute comes in handy. This attribute helps search engines understand which page should be shown to visitors based on their location. It is very important to properly synchronize your hreflang attributes within your page's source code, otherwise you may experience unexpected search engine behavior. For more information, see this article.

HOW TO FIX IT
To avoid any conflicts, we recommend that you review your hreflang attributes within your page's source code and fix any of the following issues:
- Conflicting hreflang and rel=canonical URLs
- Conflicting hreflang URLs
- No self-referencing hreflang URLs

**Comment by ahmedkaludi** [comment]
We do this already,

GitHub is for tested and recreatable bugs

Please contact our support team for quick help in this
