### ISSUE TITLE
Add support of fallback images in AMP

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3790]
AMP should support image fallback feature.
User requirement :- `<amp-img src="URL"><amp-img>
                                <amp-img fallback src="URL2"></amp-img>`

Currently we have :- `<amp-img alt="Mountains"
width="550"
height="368"
src="/wp-content/uploads/2019/10/mountains.jpg">
</amp-img>`

Modified should be like :- 
`<amp-img alt="Mountains"
width="550"
height="368"
src="/wp-content/uploads/2019/10/mountains.jpg.webp">
<amp-img alt="Mountains"
fallback
width="550"
height="368"
src="/wp-content/uploads/2019/10/mountains.jpg"></amp-img>
</amp-img>`

**Comment by ggloveswp** [comment]
User requirement : 
**Enhance amp-img tag with a fallback, in case a webp file is being used**

Currently we have : 
```
<amp-img alt="A view of the sea"
  src="/wp-content/uploads/2019/10/1.jpg"
  width="900"
  height="675">
</amp-img>
```

Modified should be like : 
```
<amp-img alt="A view of the sea"
  width="900"
  height="675"
  src="/wp-content/uploads/2019/10/1.webp">
  <amp-img alt="A view of the sea"
    fallback
    width="900"
    height="675"
    src="/wp-content/uploads/2019/10/1.jpg">
  </amp-img>
</amp-img>
```

**Comment by Zabi09** [comment]
https://monosnap.com/file/hACFufT7clYwT8989PqdHI5O5FR6na

**Comment by Zabi09** [comment]
Added a "webp" which doesn't exist but still, it is showing jpg on amp-img and also on fallback

**Comment by sonaliramteke** [comment]
fallback images not added properly like this screenshot - https://monosnap.com/file/i7fdV5BAvntJXPXryoL3L0ru8jfsvI

**Comment by MohammedKaludi** [comment]
need to discuss the fix also need to add a filter to modify the fallback image value.

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/aa2f52399274a330a30ed17d9232a8df925d8d69#diff-f0e1f733035b4437575d3172e86526dfR357

Escpaing missing

**Comment by MohammedKaludi** [comment]
As the text will be in the alt="' esc_attr will not be the best method to escape the text 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/33c51b89176887e97cc918b8991591bea6f3f4d2#diff-f0e1f733035b4437575d3172e86526dfR383

**Comment by MohammedKaludi** [comment]
esc_html is not correct one. as it will not work properly with single and double quotes.

**Comment by WasimM3** [comment]
We can use esc_attr() for the alt tag for the reference 
https://developer.wordpress.org/reference/functions/esc_attr/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
