### ISSUE TITLE
[URGENT] Vuukle API KEY missing 

### ISSUE THREAD

**Issue by vuukle** [ahmedkaludi/accelerated-mobile-pages#3792]
There seems to be an issue, when client installs Vuukle platform, the api key is missing. 

Example: client has entered Vuukle api key in settings page http://prntscr.com/pmysi1

but when you open production url the query param is missing - https://www.ccn.com/u-s-yield-curve-devastating-recession-unavoidable/

Please fix this asap as it is affecting majority of our clients on your platform.

**Comment by froutsis** [comment]
Adding 
`$srcUrl = add_query_arg('apiKey', $apiKey, $srcUrl);` here fixes the issue
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/components/comments/comments.php#L224

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d83fa9726e225616b5f5e06eb8a969b02373be19#diff-3358181277138e309fc94ee4e552f7feR221
Add this as conditionally if `$apiKey` is blank then do not add `apiKey=` key in URL

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
