### ISSUE TITLE
Compatibility with Social Pug plugin.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3793]
Compatibility with Social Pug plugin.
Ref: https://secure.helpscout.net/conversation/986755533/93475?folderId=2322651

**Comment by MohammedKaludi** [comment]
1. Add class exists at the hook 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5482b691cb0b2c797b10c5f0b053ba1fd2b94f5c#diff-1301281de287d2aed98746fc9ba777b4R1045 

2. Style is loading on every page, it should load only on the singular pages not everywhere https://take.ms/20q2W

**Comment by MohammedKaludi** [comment]
this is not fixed yet.

Style is loading on every page, it should load only on the singular pages not everywhere https://take.ms/20q2W

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
This ticket is moved in https://ampforwp.com/compatibility/idea-board/
