### ISSUE TITLE
Validation field in CF7 is not working

### ISSUE THREAD

**Issue by IOEchai** [ahmedkaludi/accelerated-mobile-pages#3795]
Hi,

I have an issue in regards with Contact form 7 in AMP page. The required fields validation is not working. Even though the field is required, when I hit submit button even if the required field is empty it redirects me to the thank you page. It shouldn't be that way. It must have an error message saying "The field is required." just like the original page.

Original page is working fine only the amp page is not working. Please advice.

Below are the links of the page
Original Page: https://www.hdbrandedfoods.com/catering
AMP Page: https://www.hdbrandedfoods.com/catering/amp/

Looking forward in your prompt response.

**Comment by ahmedkaludi** [comment]
GitHub is for tested and recreatable bugs

Please contact our support team for quick help in this at ampforwp.com/support
