### ISSUE TITLE
Need to adding gaping for col 2 in AMP Pagebuilder

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3796]
When ever the 2 columns section are used, the design is looking like this
https://monosnap.com/file/IcH8CLqpHZ4ekE1xYRVxSKKFqDsc08
Need to add gaping for that.

**Comment by Zabi09** [comment]
Not looking good in desktop view - https://prnt.sc/ps8wjk

**Comment by RajuJeelaga** [comment]
@Zabi09 Actually the ticket is for adding the gaping for 2 columns, so after Adding gap, 2 modules are breaking so i fix that 2 modules you can check on above commit, after discussion with @ahmedkaludi  sir, i did this changes, so i don't want to do the changes in all modules, Please consult @ahmedkaludi reagrds the comment that you added.

**Comment by Zabi09** [comment]
Consult with @ahmedkaludi, So moving the ticket

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
