### ISSUE TITLE
Media queries are removing automatically in media queries merging process

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3797]
When media queries are merging, some of the media queries are automatically removing,
Ref: Check with the Galley/slider Module in 0.9.98 version

1)With Media Query -- https://monosnap.com/file/tPPlrtnbOOT40FbAWWmhoNvl0YGs05
2)Removing the Media query -- https://monosnap.com/file/9jJYQDkyyd4DVUxppNNpsPl5NwNG83
3)Media merging process file --- https://monosnap.com/file/NxCSAIdjd0aT5Dfib2wZjdn5pFdoEs

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
