### ISSUE TITLE
CTA button in header could be made no follow

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/accelerated-mobile-pages#3798]
The CTA button in the header could be made Nofollow.

Ref:https://secure.helpscout.net/conversation/984779561/92767?folderId=3250553

URL:https://auratoto.com/amp/

Here is the screenshot:
https://monosnap.com/file/liXp52YWn7PJIW3X32swucWgI0dIK4

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
