### ISSUE TITLE
Mobile redirection: front page taking too much time to load

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#380]
when i enable redirection for mobile visitor it take a lot of time to redirect

**REF:**https://wordpress.org/support/topic/on-post-page-next-button-is-not-working/

**Comment by MohammedKaludi** [comment]
Custom Rewrite Rule added to make sure pagination & redirection is working correctly.
Commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ae0aac27d2773e1051c6ac396676afd8b1de9b84
