### ISSUE TITLE
Warning when trying to save the option

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3800]
warning when trying to save the option: Generating in error log

 Warning: trying to save option 'ampforwp_ia_exclude_post' with the size of 75767 bytes

Details are in the help scout link: 

https://secure.helpscout.net/conversation/952916959/82015?folderId=2632030

**Comment by MohammedKaludi** [comment]
Read to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.16 update.
