### ISSUE TITLE
Missing URL for attribute 'srcset' in tag 'amp-img' after Latest update of Divi Theme (From version 4.0.2)

### ISSUE THREAD

**Issue by AhmadTy** [ahmedkaludi/accelerated-mobile-pages#3803]
i don't know why i'm keep getting this message on almost each IMG<amp-img> on this Page and on the Landingpages .

the page : 
https://www.pack-und-wasch.de/die-teppichpflege-braun/amp/

one of the landingpages : 
https://www.pack-und-wasch.de/teppichreinigung-aach-2/amp/

**Comment by akashagrjsr** [comment]
Ref: https://secure.helpscout.net/conversation/989568679/94443?folderId=2770545

In the latest version of Divi Theme (From version 4.0.2), an empty srcset is serving in the non-AMP version of the website which causes "Missing URL for attribute 'srcset' in tag 'amp-img'" validation error in AMP version.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.17 update
