### ISSUE TITLE
Need to add compatibility of Embed Plus for YouTube plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3807]
Ref: https://secure.helpscout.net/conversation/966165799/86088?folderId=2770545

Ref: https://wordpress.org/plugins/youtube-embed-plus/

**Comment by MohammedKaludi** [comment]
Reported in https://ampforwp.com/compatibility/idea-board/

**Comment by Bielousov** [comment]
Created a bug issue, not the compatibility request: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5215
