### ISSUE TITLE
In IOS screen, Menu cross button is not appearing in Swift design 

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3809]
In IOS screen Menu cross button is not appearing in Swift design and overlay background color is not applying when header is sticky and Sticky social icons are visible, need to get the overlay at the top of the icons.
https://monosnap.com/file/Zk49x86p0wotYSmq6fl8U0Ib9jwEcA

Note: The problem is appearing in IOS screen single design

**Comment by akashagrjsr** [comment]
Ref: https://secure.helpscout.net/conversation/986857199/93525?folderId=2770545

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
