### ISSUE TITLE
Error amp-iframe extension .js appears more than once

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3810]
1. If the user adds iframe in footer then its js should be automatically added to the code.
https://monosnap.com/file/BorfxRwfL2eEfARNWPZBhDpq985xZ8

2. User should not allow adding script more than once in site.
https://monosnap.com/file/KkMoPH1Xx8Pirr8OpC2NyUF2CpDH4x

Ref: https://secure.helpscout.net/conversation/985515976/93089?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
