### ISSUE TITLE
Change internal links to AMP is not working when custom permalink having the extenison.html

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3811]
Change internal links to AMP is not working when custom permalink having the extenison.html
https://secure.helpscout.net/conversation/992593354/95339?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
