### ISSUE TITLE
Instagram TV videos are not rendering into AMP

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3812]
Instagram videos are not rendering into AMP, throwing console errors.

Ref: https://monosnap.com/file/5XKM18jhqoxHgi3JfHaqXH4ihB66rz

This is the URL of Instagram: https://www.instagram.com/tv/B4VIucBgkUE/

Issue recreated in the internal system.

https://secure.helpscout.net/conversation/987573040/93791?folderId=2632030

**Comment by MohammedKaludi** [comment]
Need to update the vendor log.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f10007f720908375813e5fd07a84693596d4585b

**Comment by MohammedKaludi** [comment]
link to the commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/54353bf8106fb206dd57d037f00ed95defc888d6

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
