### ISSUE TITLE
Need to make compatibility with wpDataTables plugin

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3814]
https://secure.helpscout.net/conversation/995483424/96071?folderId=2632030
https://wordpress.org/plugins/wpdatatables/

**Comment by HANEEFRIYAZ** [comment]
Hi Development Team,

We have given ETA to the customer as either the last week of Feb 2020 or the first week of March 2020 this will be taken care of. 

Please do the needful.

**Comment by MohammedKaludi** [comment]
Reported in https://ampforwp.com/compatibility/idea-board/
