### ISSUE TITLE
Need to make compatible with Page scroll to id plugin 

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3815]
Need to make compatible with "Page scroll to id plugin "

https://un-tour-dans-le-sac.fr/bali-autrement/amp/

https://wordpress.org/plugins/page-scroll-to-id/

REF:https://secure.helpscout.net/conversation/992158479/95205?folderId=3008055

**Comment by MohammedKaludi** [comment]
Reported in https://ampforwp.com/compatibility/idea-board/
