### ISSUE TITLE
Need to add compatibility with LuckyWP Table of content with AMP.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3817]
As per user using LuckyWP Table of content and which is not supported with AMP, so need to built compatibility with our core plugin.

Ref: https://secure.helpscout.net/conversation/991043674/94946?folderId=3126461

**Comment by SirLouen** [comment]
Has this already been implemented? It would be great, since the other TOC plugins (Easy & Plus) are a little bit discontinued and this seems to be most active one lately.

**Comment by ahmedkaludi** [comment]
@SirLouen 

This plugin already shows the list with proper jump links, that's why we slowed down a little on this.

Do you think there's something there which needs to be built?

**Comment by SirLouen** [comment]
@ahmedkaludi the hide button is not working.
Also not sure if it shall have some extra styling options. It looks bad. Not sure if the other supported TOC plugins (simple and easy) look the same.

**Comment by MohammedKaludi** [comment]
Moved to https://ampforwp.com/compatibility/idea-board/
