### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function amp_header() 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3819]
Case-I
https://secure.helpscout.net/conversation/969692658/87300?folderId=2770543
Note: Rare issue.
See this screenshot: https://prnt.sc/ps981z

**Comment by Zabi09** [comment]
I have checked your website and I don't see any fatal error now and yes you were having a fatal error 3 days back and maybe at that time you have removed the "amp_header" function from the components-core.php file.

Check these screenshots:
https://prnt.sc/pskqiy
https://prnt.sc/pskr0j

But anyway you don't have any errors and if you find any errors now or in future then let us know
