### ISSUE TITLE
Post id of recent post is always passed

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#382]
Post id of recent post is Always passed in all pages of amp and if alternate content is being used and if Alternate content has any scripts it may load in all the pages and show warnings.

Please address this issue.

**Comment by ahmedkaludi** [comment]
@MohammedKaludi what's up with this one?

**Comment by MARQAS** [comment]
After a lot of testing, I can say now that this has been resolved.
Post ID of the recent post is not getting passed on archives and Home. 
Archives and FrontPage are taking their own IDs and HomePage is taking the ID as 0. 

So no scripts are getting loaded from recent post/first post

**Comment by MohammedKaludi** [comment]
:+1: I also think the same way as @MARQAS mentioned.

Closing the ticket.
