### ISSUE TITLE
Need to implement Reading Progress Bar in AMP

### ISSUE THREAD

**Issue by raju-jeelaga** [ahmedkaludi/accelerated-mobile-pages#3820]
Need to implement Reading Progress Bar in AMP in Good Way

**Comment by Zabi09** [comment]
Not working when admin toolbar is present - https://prnt.sc/ptpviy

**Comment by MohammedKaludi** [comment]
Page Scroll Progress Indicator position of the control is incorrect.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by ahmedkaludi** [comment]
its' available at https://ampforwp.com/addons/reading-progress-bar-for-amp/
