### ISSUE TITLE
Content is updated programatically on /amp/ page view, bad revision is created

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3822]
Hello, 

We are facing one case. To begin with, AMP version is the latest 0.9.98.15, though the problem exist in some previous versions as well. 

**Case**
1. We have a page without a content (empty) and using some custom fields instead.
2. When user visits that AMP page via /amp/.

We find out that our content is updated, and even revision is crated for an author which id is  0. After debuging and backtracing - we find out in your plugin such place:
```
wp-content/plugins/accelerated-mobile-pages/pagebuilder/inc/viewShowFrontData.php:31

if (ampforwp_empty_content(get_post($postId)->post_content) && $ampforwp_pagebuilder_enable=='yes') { 
        $arr['ID'] = get_post($postId)->ID;
        $arr['post_content'] = '&nbsp;';
        wp_update_post($arr);
    }
```

On user page visit, If content is empty, you add `&nbsp;`and save it. But the check is also made with 

```
function ampforwp_empty_content($str) {
    return trim(str_replace('&nbsp;','',$str)) == '';
}
```

Meaning `&nbsp;` is ignored anyway, and it will be added again..and again. So almost endless loop when each time user visits the page. 

It is not only inefficient from performance-wise (to update content on user visit), but also creates revisions of updates, but actually nothing is changed.

Plase fix it. Thank you

**Comment by Zabi09** [comment]
If the WordPress editor is empty - https://prnt.sc/ptq3aw then the AMP page builder is not working.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.1
