### ISSUE TITLE
Cannot use a scalar value as an array in /wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php on line 2256

### ISSUE THREAD

**Issue by jasontucker** [ahmedkaludi/accelerated-mobile-pages#3823]
I'm getting this error message in my logs:
Cannot use a scalar value as an array in /wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php on line 2256

When using the following plugins and themes:

accelerated-mobile-pages
codepress-admin-columns
ads-txt
advanced-ads-adsense-in-feed
advanced-ads
advanced-ads-pro
advanced-ads-geo
advanced-ads-layer
advanced-ads-responsive
advanced-ads-slider
advanced-ads-sticky-ads
advanced-ads-tracking
akismet
ari-adminer
bb-plugin
bb-theme-builder
better-search-replace
blog-time
classic-editor
cloudflare
yikes-inc-easy-mailchimp-extender
yikes-inc-easy-mailchimp-form-customizer-extension
facebook-comments-plugin
favicon-by-realfavicongenerator
google-analytics-for-wordpress
hide-my-site
imsanity
ios-images-fixer
jetpack
mailoptin
mashshare-google-analytics
mashshare-responsive
mashshare-networks
mashsharer
jetpack-module-control
nxs-snap-pro-upgrade
social-networks-auto-poster-facebook-twitter-g
pdfembedder-premium
plugin-detective
bbpowerpack
query-monitor
regenerate-thumbnails
resmushit-image-optimizer
show-current-template
simple-author-box
twitter
ultimate-facebook-comments
use-google-libraries
wp-accessibility
wp-better-emails
wp-crontrol
wp-missed-schedule-posts
wp-notification-center
wp-scroll-depth
wp-user-avatar
wp-user-avatars
wordpress-seo
wordpress-seo-premium
object-cache.php

and I'm using Beaver Builder for my theme.

**Comment by MohammedKaludi** [comment]
`$redux_val['ampforwp-gtm-field-advance'] = $jsonstr;`
Issue is here: https://take.ms/lxNPA

**Comment by akashagrjsr** [comment]
The Github is for re-creatable bugs but we are not able to re-create the issue at our end. Could you 
 please contact us on the given link:
 https://ampforwp.com/support/

**Comment by MohammedKaludi** [comment]
I think I found the way to recreate the issue, I'll recreate and will send you the export of my options panel

**Comment by MohammedKaludi** [comment]
https://wordpress.org/support/topic/error-in-amp-dashboard/

**Comment by MohammedKaludi** [comment]
Hey @jasontucker,

Thank you for creating the ticket, I'm trying to recreate the issue and i'm not able to recreate the error.

Can you please do let me know if the error still persists?  and if yes, then can you please update to the latest version of the plugin and test.

Also try to reupload the logo of the website and test once (https://take.ms/Kk3hj)

Waiting for your reply.

**Comment by MohammedKaludi** [comment]
Ready for merging.

**Comment by MohammedKaludi** [comment]
@jasontucker 

The Github is for re-creatable bugs but we are not able to re-create the issue at our end. 

Other warning fixed and pushed in 1.0.01
