### ISSUE TITLE
AMP Dev mode when disabled throwing a fatal error in mobile mode for blog.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3824]
Fatal error: Uncaught Error: Call to undefined function session_id() in /app/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php:261 Stack trace: #0 /app/wp-includes/class-wp-hook.php(286): ampforwp_redirection('') #1 /app/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /app/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /app/wp-includes/template-loader.php(13): do_action('template_redire...') #4 /app/wp-blog-header.php(19): require_once('/app/wp-include...') #5 /app/index.php(17): require('/app/wp-blog-he...') #6 {main} thrown in /app/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php on line 261

The given function code is missing in the core:-  `if(function_exists('session_id')){}`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
