### ISSUE TITLE
Notice: Undefined variable: amp_url

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3825]
`/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/amp-helper-functions.php in AMPforWP\AMPVendor\amp_get_permalink at line 21`

In: `return apply_filters( 'amp_get_permalink', $amp_url, $post_id );`

**Comment by Zabi09** [comment]
Already fixed in #3776
