### ISSUE TITLE
Google Tag manager not firing properly

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3826]
No need to add Analytics type in the google tag manager. Now the user needs to add only the Tag manager ID to use it.
https://documentation.unbounce.com/hc/article_attachments/360022719252/GTM_AMP_copy_script.png

Ref: https://secure.helpscout.net/conversation/994917440/95901?folderId=3257665

**Comment by ajeetku** [comment]
use escaping https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bcedd0491265bfa0f272d485698b3010754657d1#diff-b27b16759fae0fb0d94cc6e00107c8efR417

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21

**Comment by MohammedKaludi** [comment]
Need lot of code improvements.

**Comment by Arihantkankariya09** [comment]
Another use case with this issue:- https://secure.helpscout.net/conversation/988151385/94046?folderId=3243584
We can test it here also.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
