### ISSUE TITLE
Notice: Undefined variable: category_name

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3827]
`/wp-content/plugins/accelerated-mobile-pages/includes/features/analytics/analytics-functions.php in ampforwp_add_advance_ga_fields at line 442`

in

```$ampforwp_adv_ga_fields = str_replace('{category}', $category_name, $ampforwp_adv_ga_fields);```

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.16 update.
