### ISSUE TITLE
Need to modify "Want to clear the Cache?" option in Performance section

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3828]
- [ ] Instead of checkbox it should be like a button
It should be like this
Screenshot: https://monosnap.com/file/0PPEFJR90zfKrz1WM8XLCSELiq82PD

- [ ] Please make sure that after updating any posts or pages it should clear the cache automatically.

**Comment by MohammedKaludi** [comment]
Infinite "please wait" when clicking on clear cache button before saving the settings.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 0.9.98.15 update
