### ISSUE TITLE
Make header Unsticky not working when Infinite scrolling is turned on.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3831]
The user's scenario is:- the header is unsticky even if the Unsticky header feature is turned off. He has the Infinite scrolling turned on. During testing, when the infinite scrolling is turned off the header becomes sticky and when it is turned on the header becomes unsticky.

Ref :-https://secure.helpscout.net/conversation/999607482/97011?folderId=3243584

**Comment by ahmedkaludi** [comment]
The ticket is not describing the concern I had. Discuss with me before working on this.

**Comment by jasthilokesh** [comment]
Fixed here by mistake 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bfb6f9da2ec7d74260298c68cec09aeebdf93a56

**Comment by MohammedKaludi** [comment]
Not working as expected.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22
