### ISSUE TITLE
An issue with Code module in AMP page puilder.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3833]
As per the User, creating his own layout and in the Code module inserting HTML script when the user imports the same layout on another page then HTML tags strips and displaying plain text without tags.
Tested in localhost too.

Screenshot:
https://monosnap.com/file/jDVv9ryJtGbDRvbkbWIZJltIcvx42S

Ref ticket: https://secure.helpscout.net/conversation/1001601808/97274?folderId=3126461

**Comment by MohammedKaludi** [comment]
need to discuss why we used ``

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.1
