### ISSUE TITLE
AMP Page apears blank after adding script tag in Head Section of AMP Page Builder

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3834]
Screenshot: https://monosnap.com/file/m6OUH2RNo3VrKuWpZapeGo5lacfxd9

Ref: https://secure.helpscout.net/conversation/997673006/96703/

When the user is adding any script tag in the "Enter HTML in Head" option of Page Builder then the amp pages appear blank.

**Comment by MohammedKaludi** [comment]
Not the correct fix.

**Comment by WasimM3** [comment]
We can achieve it like the following ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3257.

**Comment by MohammedKaludi** [comment]
Escape it while merging.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f0df0005fd1bbb427eee0b8de283ee6a910e287c#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7958

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
