### ISSUE TITLE
Back to top button CSS loading twice in Design 1,2,3.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3835]
The Back to top button CSS is loading twice in Design 1,2,3 (one is from global function and other is added manually).
Global function:- ![Path](https://user-images.githubusercontent.com/23516562/68585510-74464300-04a8-11ea-81fb-f2158c5c58ae.png)

Manually in Design 1,2,3:- ![path2](https://user-images.githubusercontent.com/23516562/68585619-c2f3dd00-04a8-11ea-8b2f-e1dc0c700099.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
