### ISSUE TITLE
In Swift theme Table are not responsive in mobile devices

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/accelerated-mobile-pages#3837]
link: https://wordpress.org/support/topic/in-swift-theme-table-are-not-responsive-in-mobile-devices/

test it with this code: https://pastebin.com/ZewgVG2Q

using swift theme tables are not able to scroll in AMP but using remaining three designs it's working.

screenshot:
[AwesomeScreenshot-2019-11-11-1573480833612.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3831649/AwesomeScreenshot-2019-11-11-1573480833612.zip)

**Comment by RajuJeelaga** [comment]
The swift Table issue is already fixed in this update 0.9.98.16 #3746
So after discussion with Ahmed sir, i am closing this ticket.
