### ISSUE TITLE
getting error while searching words having spaces

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/accelerated-mobile-pages#3838]
Link: https://wordpress.org/support/topic/error-search-amp/

 while searching words (having spaces), as a result spaces are removed from words and word is not searched

screenshot:
[AwesomeScreenshot-2019-11-12-1573557183693.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3835815/AwesomeScreenshot-2019-11-12-1573557183693.zip)

**Comment by ahmedkaludi** [comment]
we will close the ticket until we receive the response: https://secure.helpscout.net/conversation/967276283/86378/
