### ISSUE TITLE
Hidden posts in AMP should not show in related posts

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3839]
Ref: https://secure.helpscout.net/conversation/1004393617/97599?folderId=3126461

If the user has disabled AMP support for some posts and when he is seeing another AMP posts then these posts are showing in related posts section.

Screenshot: https://monosnap.com/file/M4DlVLLuonhziA3rRs5wqYXNXAhqS1

**Comment by Zabi09** [comment]
Not working in design 1,2 and 3

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22
