### ISSUE TITLE
Fatal Error: After adding Video module in Footer widget

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3841]
Ref: https://secure.helpscout.net/conversation/1005558914/97749?folderId=2770545

 Uncaught Error: Call to a member function setAttribute() on null in /var/www/vhosts/stuffplaceone.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/templates/features.php:2663 Stack trace: #0 /var/www/vhosts/stuffplaceone.com/httpdocs/wp-includes/class-wp-hook.php(288): ampforwp_modified_search_sidebar('<div class="w-b...') #1 /var/www/vhosts/stuffplaceone.com/httpdocs/wp-includes/plugin.php(206): WP_Hook->apply_filters('<div class="w-b...', Array) #2 /var/www/vhosts/stuffplaceone.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/swift/footer.php(17): apply_filters('ampforwp_modify...', '<div class="w-b...') #3 /var/www/vhosts/stuffplaceone.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(469): include('/var/www/vhosts...') #4 /var/www/vhosts/stuffplaceone.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(155): AMPforWP\AMPVendor\AMP_Post_Templ in /var/www/vhosts/stuffplaceone.com/httpdocs/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 2663

Screenshot of local: https://monosnap.com/file/ydafRdcmKJRlCHayuaQ0GtDcF6OkfU

When the user is adding a video module in the footer widget then the user is getting a Fatal error.

**Comment by MohammedKaludi** [comment]
incorrect solution done, 
YouTube not working.

**Comment by MohammedKaludi** [comment]
Videos not loading properly.

**Comment by MohammedKaludi** [comment]
need to discuss

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
