### ISSUE TITLE
Need to implement the Mobile redirection functionality using Javascript method

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3844]
https://secure.helpscout.net/conversation/1004403204/97601?folderId=2632030

**Comment by ahmedkaludi** [comment]
Let me know before you start implementing this ticket.

**Comment by udiudiudiudi** [comment]
once you release something in this regards, i will be happy to test it on saveatrain.com/blog/ as i have varnish and i have this issue

**Comment by MohammedKaludi** [comment]
@udiudiudiudi Thank you, we are ready with the fix (some minor improvements required) and if you are ready to test then please use this zip and let us know if it is working properly or not.

Also please use FTP or file manager to upload the code, if anything breaks(as this is still under development) you can revert back to the working copy of the plugin.

Please use this attached zip to test.
[accelerated-mobile-pages.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3910376/accelerated-mobile-pages.zip)

Thank you very much, we really appreciate your contribution.

**Comment by MohammedKaludi** [comment]
@jasthilokesh need to update only when the value is changed. not on every save.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c964be36bad13a52f368d07d84892d268ab2a055#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1458

**Comment by udiudiudiudi** [comment]
Hi MohammedKaludi,
Do you have a new version for me to try during the weekend?
When did you plan to push this fix to the actual release?

**Comment by udiudiudiudi** [comment]
any update on this task please?

**Comment by MohammedKaludi** [comment]
> Hi MohammedKaludi,
> Do you have a new version for me to try during the weekend?
> When did you plan to push this fix to the actual release?

Hey @udiudiudiudi 

The Zip is available for the testing, do let me know if you need so I can attach with next reply for testing.

**Comment by MohammedKaludi** [comment]
If the testing is done and the fix is working properly then we can release it with in a week.

**Comment by MohammedKaludi** [comment]
Function names improvement required.

**Comment by udiudiudiudi** [comment]
hello, any estimate when this will be released?

**Comment by MohammedKaludi** [comment]
@udiudiudiudi the fix is ready, can I send you a zip to test the code?

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by udiudiudiudi** [comment]
mohammed, how do i activate this new method of redirect? or it will take over the current way of redirecting?

**Comment by bb665** [comment]
@MohammedKaludi Hi, has it been fixed and published? We have this issue for a very long time. That's why we did not push this AMP feature live. So, if it has been fixed, we are ready to use this plugin. Thanks!

**Comment by udiudiudiudi** [comment]
how do i activate this once i install, or its updated for the whole of ampforwp routing for all users automatically instead of the current redirect?

**Comment by MohammedKaludi** [comment]
Did not pushed in 1.0.19 update due to some improvement in the code required.

**Comment by udiudiudiudi** [comment]
how do i activate this once i install, or its updated for the whole of ampforwp routing for all users automatically instead of the current redirect?

**Comment by MohammedKaludi** [comment]
There are few improvements still required, this current fix is not correct. 

We will fix this by end of next week and push it once it is ready.

**Comment by udiudiudiudi** [comment]
hi mohammed, any update?

**Comment by MohammedKaludi** [comment]
> hi mohammed, any update?

@udiudiudiudi this code now seems to be ready, I'm attaching the zip with the fix if you want to test the plugin.

Once it is ready after the testing, we will push it hopefully on 15th march.

[accelerated-mobile-pages.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4287721/accelerated-mobile-pages.zip)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by udiudiudiudi** [comment]
will it change automatically to support varnish, or i have to activate something?

**Comment by MohammedKaludi** [comment]
> will it change automatically to support varnish, or i have to activate something?

it will automatically start supporting the cache, you just have to enable mobile redirection, and clear the varnish cache once.

**Comment by udiudiudiudi** [comment]
when will it be available?

**Comment by MohammedKaludi** [comment]
If you test and let me know if it is working then I can push it in the next update.

**Comment by MohammedKaludi** [comment]
You can find the zip from this comment 

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3844#issuecomment-594550646

**Comment by udiudiudiudi** [comment]
just to clarify, once i install it, i just have to clear varnish?
look my site is www.saveatrain.com/blog/
so amp is activated on most of the site, but there are some parts which are not amp like /blog/timezone/ for those i didn't enable amp, but enabled mobile, will it hurt them?

**Comment by MohammedKaludi** [comment]
> just to clarify, once i install it, i just have to clear varnish?
Yes,

> so amp is activated on most of the site, but there are some parts which are not amp like /blog/timezone/ for those i didn't enable amp, but enabled mobile, will it hurt them?
That should not have any effect, if something breaks, you can always reinstall the plugin that is live on WP.org


Please do let me know your feedback.

**Comment by udiudiudiudi** [comment]
OK i downloaded it and copied the directory.

can you give me 1-3 or more points what to check and report to you once I override the current plugin to see if it works correctly or not

**Comment by MohammedKaludi** [comment]
> OK i downloaded it and copied the directory.
> 
> can you give me 1-3 or more points what to check and report to you once I override the current plugin to see if it works correctly or not

1. Activate the new version of AMPforWP plugin.
2. Enable Mobile redirection and clear your varnish cache 
3. Check on your mobile phone if mobile redirection is working fine or not.

If the mobile redirection is working properly or not do let me know.

Thanks for the doing the testing 😊

**Comment by udiudiudiudi** [comment]
i do not understand what do you mean by activate mobile redirection.
please go to [https://www.saveatrain.com/blog/](https://www.saveatrain.com/blog/)
it is already working, unless you mean something else

**Comment by udiudiudiudi** [comment]
to be honest i would prefer if you make the test with varnish on your end, since I am afraid I break something I don't have the knowledge to fix

**Comment by MohammedKaludi** [comment]
Nevermind,I already tested it many times and wanted to make sure the fix is working fine.

I'll mark the fix as working as I have done multiple tests and its working fine.

**Comment by udiudiudiudi** [comment]
i saw it wasn't pushed in today's version :(

**Comment by udiudiudiudi** [comment]
when is this pushed please?

**Comment by MohammedKaludi** [comment]
@Zabi09 
incorrect commit was merged
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/715c09f613b3afa5c4ba3cfca311f01881ada0d7

**Comment by Zabi09** [comment]
Pushed in 1.0.77.1

**Comment by MohammedKaludi** [comment]
pushed in 1.0.77.2
