### ISSUE TITLE
When pagination is enabled in Category Module,translation option should be given in Advanced.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3847]
When the category module has its pagination feature on then there should be translation text (First, Last, Next, Previous) options in the advanced section.
1. Pagination https://monosnap.com/file/LN7ot3GhPiFKMLKkoFchEmn40rbLqJ
2. Advanced https://monosnap.com/file/OAxG1qDcYTjBl3RZiP0KBPTnXhsn7n

**Comment by Zabi09** [comment]
Last is not working
Added - https://prnt.sc/pzjetu
Output - https://prnt.sc/pzjeyp

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.1
