### ISSUE TITLE
Optimize the size of id/number applying at the end of a class in CSS

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3848]
Need to optimize the size of the id applying after the class name in the CSS and hence reducing the size of the stylesheet.
https://monosnap.com/file/CU6NDrWJwVXiBWHsi9vTp3B7v1iJOy

This will solve validation error:- The author stylesheet specified in tag 'style amp-custom' is too long - the document contains 52697 bytes whereas the limit is 50000 bytes.

**Comment by ahmedkaludi** [comment]
Move this ticket to trello
