### ISSUE TITLE
Ability to enable/disable AMP on Homepage

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#385]
Option which will allow users to enable/disable AMP on Homepage.

**REF:**https://wordpress.org/support/topic/shopisle-theme-wrong-landing-page/

**Comment by khaledMohammed000** [comment]
https://wordpress.org/support/topic/statics-pages-without-amp/

**Comment by MARQAS** [comment]
Many people are asking for it. We have to do this.

**Comment by ahmedkaludi** [comment]
This was added in the update
