### ISSUE TITLE
Add Hyperlink option to Gallery module images.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3850]
Gallery module images in the page builder should have hyperlink https://monosnap.com/file/zRo1jiNX335kvYoKUupifTAEktDn5I

Ref  https://secure.helpscout.net/conversation/1007943998/98126?folderId=3243584

**Comment by Zabi09** [comment]
1 - Hyperlink option should be there inside the field that is after/before the responsive option - https://prnt.sc/pyxpi5
2 - No need to add the select option just add the just add one checkbox for "new tab" - https://prnt.sc/pyxq85

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.17 update
