### ISSUE TITLE
Need to make compatibility with this plugin Stop Generating Image Sizes

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3851]
When using this plugin "Stop Generating Image Sizes" need to stop the working of Aqua Resizer  in AMP
https://wordpress.org/plugins/image-sizes/

https://secure.helpscout.net/conversation/1007651830/98075?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by dhevilz** [comment]
Nice

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
