### ISSUE TITLE
Tree-shaking issue when user using "Clearfy optimization plugin" plugin(need to build compatibility).

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3853]
When a user using the "Clearfy optimization plugin" plugin then clear cache in performance is not working properly. Need to build compatibility with Clearfy cache plugin.

Note: In order to recreate the issue enable users Clearfy optimization plugin's settings.

Ref URL: https://secure.helpscout.net/conversation/1008388028/0/?folderId=3126461

**Comment by Zabi09** [comment]
Unable to recreate on local and also on the user's end, So closing this ticket.
