### ISSUE TITLE
Issue with page load speed for the first time.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3854]
As per the user scenario, Semrush reported a few pages and if we look into the issue pages for the first it takes 7to8 sec load later it loads within 0.5sec.

Example URL: https://www.peterdarcy.com.au/autism-adhd-dyslexia-down-syndrome/amp/

Ref Ticket: https://secure.helpscout.net/conversation/1008181259/98190?folderId=3126461

**Comment by ahmedkaludi** [comment]
put on hold until the user activates the plugin back
