### ISSUE TITLE
Need to remove WPBakery Page Builder Support Option

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#3855]
We're halting the support with WPBakery Page Builder in the AMP Pagebuilder Compatibility Extension. So, need to remove WPBakery Page Builder Support Option from the Settings Panel.
https://prnt.sc/pyzwex

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.17 update
