### ISSUE TITLE
Need to improve UI when "Saved" notification displays.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3856]
Need to improve UI when "Saved" notification displays, Please check with the below screenshot.

Screenshot: https://monosnap.com/file/8zi8DGczh77tnfRJVYwfSIV7vNCHwT

**Comment by RajuJeelaga** [comment]
In 0.9.98.18 AMP option panel design is little bit breaking and class names are also Removing, so in 0.9.98.17 the design is properly working. Please see the screenshots
 
1)0.9.98.18
https://monosnap.com/file/YAgyG5TXULI3ONVT4ADr0haifLGMUR

2)0.9.98.17
https://monosnap.com/file/FfgOQU45iew3MW7MvxVEXRtUaSYC7K

**Comment by MohammedKaludi** [comment]
Ready to push

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22
