### ISSUE TITLE
Verify button of Google Font API key is not working after update

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#3858]
Verify button of Google Font API key is not working after update version 0.9.98.16 - 
https://monosnap.com/file/CQuW0CMAhLhyrA8OszQvrvUTKwprAs

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
