### ISSUE TITLE
In page builder need to make improvements in slider

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3859]
Ref:https://secure.helpscout.net/conversation/1005567534/97751?folderId=3008055

- [x] Autoplay
In that, we have to improve that there should be option for off autoplay.
- [x] Improvements in arrow
In this, some time arrows unvisible when refreshing the page check-in mobile view also.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.14
