### ISSUE TITLE
Cache is not clearing after clicking clear cache button

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3863]
Users are facing a problem of clearing cache.  after clicking clear cache button in Optimize CSS(Beta) cache is not clearing. 

https://monosnap.com/file/CTXEBqLVTB7FO6tIvXjRycDcWKq7UX

Ref: https://secure.helpscout.net/conversation/1009870614/98565?folderId=3257665

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.18 update
