### ISSUE TITLE
MGID Ads are not loading because it is unable to fetch attributes when the Flexible AMP widget option is enabled in the AMP>>Advertisement Section.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3864]
1. When the Flexible AMP widget option is turned on, the Ads are not loaded as it is not getting the attributes. 
Screenshot:- https://monosnap.com/file/HPWy6SMgTB3VkcfCRpA8cgUh0pMrS9
2. When the Flexible AMP widget option is turned off, the ads will be fixed on the same height-width in the mobile view too.
Screenshot:- https://monosnap.com/file/Ftn8tNSl2Lzl4Q5t0SJyJjdxmi19Kw

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Code improvement required: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3864

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
