### ISSUE TITLE
Allow users to add custom script in amp by using amp theme frame work plugin or without plugin

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3865]
Ref:https://secure.helpscout.net/conversation/1011547319/98813/

Allow users to add a custom script in amp by using the amp theme framework plugin or without a plugin.

**Comment by jasthilokesh** [comment]
Notes: Need to include/update the meta tag on the changing the script.
meta content generated from the google developer console. 
EX: <meta name="amp-script-src"content="sha384-xuyADSRCtkm-N1f9r41yhgdVtOOFvZCCZ0dddkWAxyiOyoq_3VnbL9uLu_3AxbE7 ">

Need to update same on the document

**Comment by Zabi09** [comment]
Getting console error after adding the meta also - https://monosnap.com/file/alozqNi79Yy10GaSFcyfZ4kXXEMZEy

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
https://ampforwp.com/tutorials/article/how-to-add-custom-scripts-in-amp/

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
