### ISSUE TITLE
Excerpt on homepage is not working properly.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3866]
When the user enables Excerpt on the small screen then excerpt is not showing in large as well as on small screen. and when the user disables it then excerpt showing on both the screen. the same thing happening in the localhost. It is happening only when the user is selecting Design three theme.

Ref: https://secure.helpscout.net/conversation/1011995724/98896?folderId=3257665

**Comment by MohammedKaludi** [comment]
Improve the code while merging as discussed.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
