### ISSUE TITLE
Fatal error: Uncaught Error: Cannot use object of type stdClass as array (after 98.15)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3867]
Case: I

https://secure.helpscout.net/conversation/1012351305/98941?folderId=2770543

See this screenshot: https://prnt.sc/q0exrw

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
