### ISSUE TITLE
Gutenberg Gallery Images are not displayed correctly when any option is selected in WordPress Content Gallery.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3868]
The Gallery images are displayed wide with bullet points.
https://monosnap.com/file/NYOzKpLLRpudiSdVxLZS9qnjDzU1RG
 Option selected in Gallery:- 
https://monosnap.com/file/l8LsBeMCw7pJoIbQI52OWeQF0EEjAz

**Comment by MohammedKaludi** [comment]
add code
`if ( ! defined( 'ABSPATH' ) ) {`
    `exit;`
`}`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/45cc52dd6fc5e261fba7add3302168ab66cf2120#diff-a019e0b6d9b0c2552c18c4f849c9a770R2

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
