### ISSUE TITLE
Multiple UX related modifactions

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3869]
- [x] Button of "Want to clear the Cache?" is not showing the first time.

Screenshot: https://monosnap.com/file/BjHI50EQwbGfLUlzIzsKExrqXxdNzc

- [x] "Want to clear the Cache?" UX should look as a child option should be the child option

- [x] Child options for "Mobile Redirection" UX should be improved. The extra spacing should be removed

Screenshot: https://monosnap.com/file/0RY4tR2lWZnTvQyuUfExOfVGbR1ljh

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
