### ISSUE TITLE
Compatibility with Social Share Boost plugin

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#387]
Code:
function amp_endpoint_checker() {
if( is_amp_endpoint() ) {
remove_filter(‘the_content’,’ssb_in_content’);
}
}
add_action(‘init’,’social_sharing_removal_code’, 9);
function social_sharing_removal_code() {
add_action(‘pre_amp_render_post’,’amp_endpoint_checker’);
}

**Ref:**https://wordpress.org/support/topic/social-share-boost-buttons-create-big-gap/#post-8629175

**Comment by ahmedkaludi** [comment]
Don't just copy & paste. We need to check this properly as well.

**Comment by ahmedkaludi** [comment]
This was fixed in 0.9.40.
