### ISSUE TITLE
Warning: strpos(): Empty needle in /home/statecer/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 5788

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3870]
Ref: https://secure.helpscout.net/conversation/1012349212/98940?folderId=1060554

**Comment by akashagrjsr** [comment]
One more user: https://secure.helpscout.net/conversation/1012701443/99010?folderId=1060554

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.19
