### ISSUE TITLE
Getting an error while validating page when using Disqus comments with W3 Total Cache

### ISSUE THREAD

**Issue by saranshkataria** [ahmedkaludi/accelerated-mobile-pages#3871]
The AMP validator throws no errors when Disqus is disabled, but I get a Disallowed attribute or attribute value present in HTML tag for <amp-iframe> when Disqus is enabled.

Sample page: https://www.wisdomgeek.com/development/web-development/introduction-css-grid/amp/

**Comment by Zabi09** [comment]
Add function/class exists

**Comment by saranshkataria** [comment]
This was a W3 Total Cache issue and I had notified them about it. They have a potential fix which they will update the code soon with hopefully. In the meantime, I have made the corresponding change in my installation and it works now.

**Comment by MohammedKaludi** [comment]
dont use anonymous functions
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4125ed08533eae2fa99f4e0e8bebb80bb0fa1285#diff-54dac7dab9dd460d137d86d279822cc5R11

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/24370d004e66c6cebb774ebe369f81e1967689b7#diff-54dac7dab9dd460d137d86d279822cc5R11 


create a function and then add it as if required we cannot remove the function from remove filter.

**Comment by MohammedKaludi** [comment]
> This was a W3 Total Cache issue and I had notified them about it. They have a potential fix which they will update the code soon with hopefully. In the meantime, I have made the corresponding change in my installation and it works now.

@saranshkataria Do you have any idea when  W3 Total Cache guys will be fixing this? Also do you have any link to the public issue where we can check the progress of the issue.

Thank you very much for raising the ticket, and i'm glad that fix is working for you.

**Comment by MohammedKaludi** [comment]
Do contact me before merging the ticket.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.1
