### ISSUE TITLE
Need to remove one signal push notification button in pages.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3874]
One signal push notification button should be displayed only in posts.

Ref Ticket: https://secure.helpscout.net/conversation/1014550133/0/?folderId=3126461

Screenshot: https://monosnap.com/file/Duko4dudfg05uUnSsSIJ0w4tQ6fLYK

**Comment by sonaliramteke** [comment]
Also please remove the script, markup, and CSS from the source code on pages

**Comment by MohammedKaludi** [comment]
1. Update the `$redux_builder_amp[]` with `ampforwp_get_setting` 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3a2f6c063e28f0edc1c801999af5302f5d7dcd1a#diff-7d6877c810fb733c65e0e21cc6c96d61R101

2. on 2 places we are using `( ampforwp_is_front_page() || is_single())` and while adding the element it is only in `is_single()`  why? then script and styling will load in front page as well.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.0
