### ISSUE TITLE
Author links are redirecting to AMP even when the Archives is turned off. 

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3875]
Ref :- https://secure.helpscout.net/conversation/1015545109/99527?folderId=3243584

When the Author links are visited, it is throwing to the AMP page while the Archive feature is turned off.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
