### ISSUE TITLE
After Update AMP option panel design is changing

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3877]
In 0.9.98.18 AMP option panel design is little bit breaking and class names are also Removing, so in 0.9.98.17 the design is properly working. Please see the screenshots
 
1)0.9.98.18
https://monosnap.com/file/YAgyG5TXULI3ONVT4ADr0haifLGMUR

2)0.9.98.17
https://monosnap.com/file/FfgOQU45iew3MW7MvxVEXRtUaSYC7K

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.21
