### ISSUE TITLE
strpos() debug error after 19 update

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/accelerated-mobile-pages#3878]
After updating the latest version (0.9.98.19) also empty needle issue occurs

For reference: https://wordpress.org/support/topic/google-error-amp-url-is-not-an-amp/

https://secure.helpscout.net/conversation/1014285664/99249/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
