### ISSUE TITLE
Category module has minor bugs after the update.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3880]
- [x] Spacing between the content and images in categories.
 Version (0.9.98.19):- https://monosnap.com/file/HdWb1SmMG5S4yOFP2R1htTrDKnzrfh
 Version (0.9.98.15):- https://monosnap.com/file/E9FGzYu7N9iZg9IhdJmZNW1oWy1CRw

- [x] An empty `<a>` tag is added https://monosnap.com/file/4YyIWHzJSmR0VmZDrjw3f1p4N0O5iW

Review this with Ahmed Sir.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/796515866ca67c0800cd6d39881bf4539ceaaf8e#diff-cb16861af9ff34ccd298041891008f49R315 please add Default value

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
