### ISSUE TITLE
When RTL is enabled,the menu in header is going to right but the elements in right are not moved to left.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3881]
Ref:- https://secure.helpscout.net/conversation/1014757627/99359?folderId=3243584

https://monosnap.com/file/eirRrVEmUhjWi4aNmpzMkAM8nhZwYt

**Comment by MohammedKaludi** [comment]
use `.rtl` parent class added in body to modify the css

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2a7cf476d9dc005f3b907070f2e5aeef2e63eb88#diff-d2a448840c98f4c9bcf27aab39b04b83R692

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.0
