### ISSUE TITLE
When Mobile redirection is On,the View Non-AMP link in the footer does not redirect to Non-AMP.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3884]
[video_2019-11-28_18-09-43.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3901686/video_2019-11-28_18-09-43.zip)

The link to Non-AMP is redirecting to AMP only.

Ref:- https://secure.helpscout.net/conversation/1005961095/97814?folderId=3243584

**Comment by MohammedKaludi** [comment]
if unset is done, why added again?
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/058ea06548b36d9dbf0207662dbfa76f370d6a16#diff-ab576767b896423d184ddafe2ede2310R70

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
