### ISSUE TITLE
When Schema Plugin is activate Upgrade to Pro option is not showing in AMP Option Panel

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3885]
When Schema Plugin is activate Upgrade to Pro option is not showing in AMP Option Panel
Please see the Screenshot:
Before Scheme activate:  https://monosnap.com/file/Q7Vc0vh6AgsJ2rIwX7r2KGSWqbFAlw

After Schema Activate:  https://monosnap.com/file/4mcmjJwsugWptIDMtSbvNHCq5HXwa3

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.20
