### ISSUE TITLE
After enabling AMP page builder compatibility also user getting message "ONE LAST STEP REQUIRED: This feature requires Page Builder For AMP extension. (Click here for more info)"

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3886]
User getting message like "ONE LAST STEP REQUIRED: This feature requires Page Builder For AMP extension. (Click here for more info)" when he is trying to enable option DIVI builder support or any builder support. and the AMP page builder compatibility plugin is already active.
the same thing showing on localhost also.
https://monosnap.com/file/3ek8U9xd7e1HiKXHfZVfGKQOeeI6yl

Ref: https://secure.helpscout.net/conversation/1018267264/99951?folderId=3257665

**Comment by ahmedkaludi** [comment]
Please discuss with me before starting the issue

**Comment by wankhedekomal** [comment]
Ticket moved to the trello
