### ISSUE TITLE
If there is no Sticky ad code, then script should not load

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#389]
If there is no Sticky ad code, then script should not load
http://take.ms/S4JCO
http://take.ms/QIWgk

**Comment by khaledMohammed000** [comment]
This ticket is invalid , Tested this by having sticky OFF and remaining all ads from standard ampforwp and advance ads plugin...still no amp-sticky-ad JS was added.....it was correctly added when Sticky was ON
