### ISSUE TITLE
Bug in Instant article's Single option

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/accelerated-mobile-pages#3891]
- [x] If we disable "Instant articles" from the posts in editor, then it is still showing in the instant article feed 
For reference: https://wordpress.org/support/topic/problems-with-instant-articles-feed-filter/

- [x] when clicking on "enable" or "disable" in Instant article Metabox, it is effecting in "Show AMP for Current page" metabox. See for more info: https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3910093/AwesomeScreenshot-2019-12-2-1575273846587.zip

**Comment by sonaliramteke** [comment]
Posts are disabling but need to click on update to show in instant_articles

**Comment by antoniomanco** [comment]
Hi, this problem has not yet been solved.

The button from Gutenberg "does not show the current entry in Instant Articles (IA)" does not work. Although we click on "Disable", the publication appears in the Instant Articles feed.

`https://imgur.com/4GGCFaR`

**Comment by MohammedKaludi** [comment]
2 more issues discovered.

1. Undefined index https://take.ms/Ekd0M
2. Enable/ Disable control is not working properly. for more info check this video https://take.ms/cF7fn

**Comment by MohammedKaludi** [comment]
Undefined index https://take.ms/Ekd0M still persists

`Notice: Undefined index: ampforwp-ia-on-off in /Applications/MAMP/htdocs/wp48/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6530`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.17

**Comment by antoniomanco** [comment]
Hello, again I have this problem with the latest AMPForWP updates.

The AMPForWp plugin filter to not display articles in Instant Articles does not work. Even though I click on “No” for the posts that I don’t want to show in Instant Articles (For monetization policies), all of my site’s publications appear in my site’s feed https://antoniomanco.com/instant_articles

This has caused me to receive several AI alerts. I did tests by deactivating all the caches and the problem remains.

You guys solved this problem a few months ago, so I include the support link here and on Github.

- https://wordpress.org/support/topic/problems-with-instant-articles-feed-filter/

- https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3891

Thanks for the support
