### ISSUE TITLE
WP-admin and css code is showing on non-AMP for logged out users

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/accelerated-mobile-pages#3892]
In non-amp page wp-admin and amp is showing (https://prnt.sc/q4xbid) for logged out users

For reference: https://wordpress.org/support/topic/view-amp-button-showing-css-on-frontend/

**Comment by ahmedkaludi** [comment]
We will continue the ticket on https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3890
