### ISSUE TITLE
Advanced AMP Ads Don't Utilize AMP Iframe 

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#3893]
Hi,

Latest Advanced AMP Ads 1.17 version 

I can't use iframe code (or amp iframe) for amp advanced ads as it does not auto insert AMP IFRAME javascript, if I add it manually, script removes such content from the ad code.

Custom header code does same, it never appears.

`<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>`

**Comment by ahmedkaludi** [comment]
GitHub is for rested recreatable bugs, technical support is provided at ampforwp.com/support
