### ISSUE TITLE
structured data issue with search result pages

### ISSUE THREAD

**Issue by 7bhabesh** [ahmedkaludi/accelerated-mobile-pages#3894]
I'm not sure is this a bug from amp plugin or Yoast that why I'm submitting the issue on both sides.
Here are a few example links where this issue happens:
https://www.dealntech.com/page/12/?amp=1&s
https://www.dealntech.com/page/10/?amp=1&s
https://www.dealntech.com/page/13/?amp=1&s

If you check these URLs using Google's structured data tool you will find 1 error in "SearchResultsPage" Schema where @id value is missing and other two errors are Uncategorized Errors because of invalid type in JSON-LD (id value is showing "False")

Kindly fix this issue if this is created by the amp plugin or please add a reply to this thread if this issue is created by Yoast. Thanks

**Comment by ahmedkaludi** [comment]
GitHub is for tested recreatable bugs, technical support is provided at https://ampforwp.com/support
