### ISSUE TITLE
<amp-iframe not validate because missing attribute at frameborder

### ISSUE THREAD

**Issue by giovanni-ctmobi** [ahmedkaludi/accelerated-mobile-pages#3897]
From this content from the editor 
<iframe allowfullscreen="" frameborder="0" height="315" src="//www.youtube.com/embed/MejXXEE0sho" width="420"></iframe></p>

I get this result in the amp page:

<amp-iframe allowfullscreen="" frameborder="" height="315" src="https://www.youtube.com/embed/MejXXEE0sho" width="420" sandbox="allow-scripts allow-same-origin allow-popups allow-forms allow-top-navigation" sizes="(min-width: 420px) 420px, 100vw" class="amp-wp-enforced-sizes i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-layout" i-amphtml-layout="responsive" style="width: 420px;"><i-amphtml-sizer style="padding-top: 75%;"></i-amphtml-sizer><div placeholder="" class="amp-wp-iframe-placeholder amp-hidden"></div><i-amphtml-scroll-container class="amp-active"><iframe class="i-amphtml-fill-content" name="amp_iframe0" allowfullscreen="" frameborder="" allow="" sandbox="allow-scripts allow-same-origin allow-popups allow-forms allow-top-navigation" src="https://www.youtube.com/embed/MejXXEE0sho#amp=1" style="z-index: 0;"></iframe></i-amphtml-scroll-container></amp-iframe>

and at the beginning there is  frameborder="" that google from his amp validation console doesn't validate because the frameborder attribute is not valid.

This is the actual link:

https://www.techcompany360.it/news/svolta-rosa-per-plantronics-ilaria-santambrogio-e-la-nuova-country-manager/amp/

**Comment by ahmedkaludi** [comment]
The GitHub is for valid and tested issue, kindly ask the technical support at https://ampforwp.com/support 


I think the issue could be with other plugins, kindly test it with them

**Comment by djixas** [comment]
I have same issue with GFYCAT iframe embed! This is new issue and all our pages are now invalid

It now turns

```
iframeborder="0" height="400 "

irameborder height=400
```

**Comment by MohammedKaludi** [comment]
Issue has been fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3871

and Pushed in 1.0.1
