### ISSUE TITLE
After reloading 'Select Categories to Hide AMP', it shows empty

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/accelerated-mobile-pages#3898]
If we select a category in 'Select Categories to Hide AMP' option and reload the page then 'Select Categories to Hide AMP' option shows empty but the functionality works.

For reference: https://wordpress.org/support/topic/all-the-settings-automatically-resetting/

**Comment by MohammedKaludi** [comment]
Performance can be improved, as `ampforwp_get_categories()` and `ampforwp_get_all_tags()` loads everytime on the backend, it is not required. 

Also it will slowdown the websites with large number of categories and tags.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.1
