### ISSUE TITLE
Need to change the description of AMP page builder compatibility options when plugin is activated. 

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#3899]
Users getting messages like "ONE LAST STEP REQUIRED: This feature requires Page Builder For AMP extension. (Click here for more info)".when Divi/Elementor builder support enabled. https://monosnap.com/file/3ek8U9xd7e1HiKXHfZVfGKQOeeI6yl

instead of that, it should show the concerned theme/plugin is required notice.

**Comment by sonaliramteke** [comment]
Also please add for Avia and Avada options

**Comment by MohammedKaludi** [comment]
Are you sure this is the correct fix.

**Comment by MohammedKaludi** [comment]
Not properly fixed

**Comment by sonaliramteke** [comment]
Title not changing when Avia Theme is active

**Comment by MohammedKaludi** [comment]
Conditions can be improved.

**Comment by MohammedKaludi** [comment]
Label not uploading for Divi and Avada. https://take.ms/qBZuz

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
