### ISSUE TITLE
page=amp_options: Redux debug mode conflicts with Query Monitor plugin

### ISSUE THREAD

**Issue by lkraav** [ahmedkaludi/accelerated-mobile-pages#390]
Due to Redux deciding to start display all queries at the bottom of the screen, this causes a massive `<pre>` tag data explosion at the bottom of `page=amp_options`, causing browsers to completely hang trying to render the options screen.

https://github.com/johnbillion/query-monitor is an integral part of any developer's toolbelt, so there is no way to disable this plugin. Redux debug mode needs to be disabled or some other cooperative mode workaround implemented.

**Comment by khaledMohammed000** [comment]
go to file query-monitor/dispatchers/Html.php

http://take.ms/vNifM
http://take.ms/4hiGU
