### ISSUE TITLE
In exclude Categories option the "No items of this type were found." message is displaying

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3900]
Case-I
https://secure.helpscout.net/conversation/1018749474/100077?folderId=2770543

Exclude categories option not showing categories,  instead of this it shows "No items of this type were found." message. also, recreate in local and user 

User end screenshot:
https://prnt.sc/q604h3

Local end screenshot:
https://prnt.sc/q604za

**Comment by jasthilokesh** [comment]
Need to move #3898 ticket before this.

**Comment by MohammedKaludi** [comment]
Also,  need  to make sure that "Featured Slider Content" in design 3 is also connected with the new function.

**Comment by MohammedKaludi** [comment]
Update the method as discussed in this ticket as well.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/726c8065ac0d7aed263db4b8303892086234b141#diff-260eba6333c3222e59a6aed22ac5ab37R1598

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.1
