### ISSUE TITLE
PHP Warnings from redux filesystem

### ISSUE THREAD

**Issue by kaikutzki** [ahmedkaludi/accelerated-mobile-pages#3901]
AMP for WP Version: 0.9.98.20
WP Version: 5.3
PHP Version: 7.3 and 7.4

Hi! When I updated to PHP 7.4 I got theses error messages. I don't know if this is a compatibility issue with WP Super Cache but deactivating AMP for WP removed them. I then tried PHP 7.3 and got the same warnings. In 7.2 it seems to work.

![Bildschirmfoto 2019-12-04 um 10 36 11](https://user-images.githubusercontent.com/58510366/70133830-2c6da280-1687-11ea-9534-e7b9e5190e90.jpg)
![Bildschirmfoto 2019-12-04 um 10 36 48](https://user-images.githubusercontent.com/58510366/70133831-2d063900-1687-11ea-8a0d-422f5cc0794e.jpg)

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22

**Comment by kaikutzki** [comment]
Thank you for the quick fix!
