### ISSUE TITLE
A Table is created trough Gutenberg then CSS of that Table is failing to load in AMP.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3902]
As per the user is inserting table and it's content trough Gutenberg but its CSS("Text-align: Left" is an example) failing to load in AMP.

Tested in localhost too.

Screenshot: https://monosnap.com/file/pI23tuRWKu67VT5hLzAzFC8qRQE074

Ref Ticket: https://secure.helpscout.net/conversation/1020969034/100429?folderId=3126461

**Comment by Zabi09** [comment]
Also add alignment of table also

**Comment by sonaliramteke** [comment]
not working - https://monosnap.com/direct/uwYhfAgXE5KPHYQVMGBINseSs1oGkM

**Comment by MohammedKaludi** [comment]
Table is not looking correct.
https://take.ms/pytcc

**Comment by MohammedKaludi** [comment]
This is the table view: 

Backend : https://take.ms/Bnqg9 
non-amp : https://take.ms/rOZEM
AMP : https://take.ms/gm8w0

**Comment by MohammedKaludi** [comment]
Design 1 : https://take.ms/Bf4x6

**Comment by MohammedKaludi** [comment]
Ready to merge, please get back to me while merging.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
