### ISSUE TITLE
Custom taxonomies option should be only visible when Archives is enabled

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3903]
https://monosnap.com/file/UQXNcnt6sclsab7aXyOglmueg1frAg

When the Archives (Category and tags) are disabled then Custom Post types and taxonomies should not be visible.

**Comment by MohammedKaludi** [comment]
Custom post types should not be dependent on "Archives (Category and tags)" control.

Only Custom taxonomies should be hidden.  There is some confusion while creating the ticket.

**Comment by MohammedKaludi** [comment]
This code is not removed: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e43aba985aec48df0a761395d1771e6f3a3d0529#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1073

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.1
