### ISSUE TITLE
After enabling Mobile Redirection, above the tablet size non-amp pages are redirected to AMP pages

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/accelerated-mobile-pages#3906]
When 'Mobile Redirection'  is enabled,

- [ ]  If 'Tablet' option is disabled within 'Mobile Redirection' then also non-AMP pages are automatically redirected to AMP pages for Tablet sizes
- [ ]  after 768 x 1024px also non-AMP pages are automatically redirected to AMP pages.

For reference: https://wordpress.org/support/topic/amp-activating-on-desktop-screens/

**Comment by ahmedkaludi** [comment]
We have some doubts about this ticket, It will be closed until we hear from the user.

**Comment by ahmedkaludi** [comment]
We already have the reply from the user. 
https://secure.helpscout.net/conversation/1034842204/102812/
