### ISSUE TITLE
Improvement of jetpack social icons

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/accelerated-mobile-pages#3907]
Need to improve jetpack social icons. It is not showing properly (https://imgur.com/a/Fztu9QJ). 

For reference: https://wordpress.org/support/topic/problem-with-social-network-icons-jetpack/

**Comment by Zabi09** [comment]
Properly going to fix in jetpack 14217 ticket

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
