### ISSUE TITLE
Should ampforwp_allow_featured_image apply to the ampforwp_webp_featured_image function?

### ISSUE THREAD

**Issue by andyadams** [ahmedkaludi/accelerated-mobile-pages#3909]
Hi team,

I was testing an update to the plugin from 0.9.97.51.1 -> 0.9.98.21, and I noticed that Featured Images were suddenly being added to the top of AMP posts, where they were not previously.

We have posts that have Featured Images set, but (as far as I can tell) they did not show on the old version because the `ampforwp_allow_featured_image` filter prevented them from displaying. In the latest version, there is an additional call to `ampforwp_webp_featured_image` in `design-3/elements/featured-image.php`, which is inserting the Featured Image at the top of the post, and cannot be turned off as far as I can tell.

1. Is there a way to turn off the featured image generated by `ampforwp_webp_featured_image` I'm overlooking - either by a setting or a filter?
2. If not, shouldn't the `ampforwp_allow_featured_image` filter apply to this function as well?

Thanks!

**Comment by WasimM3** [comment]
We have the option to hide or remove featured image. follow the tutorial https://ampforwp.com/tutorials/article/how-to-hide-or-remove-featured-images-from-amp/ to hide or remove the featured image.

**Comment by andyadams** [comment]
Thank you - this did it!
