### ISSUE TITLE
data-block-on-consent missing in GTM code

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3911]
data-block-on-consent missing in GTM code

**Comment by MohammedKaludi** [comment]
escaping missing for ` echo $ampforwp_adv_gtm_fields `

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0c5b9ce08bd99ae42e00ef51c872aee98d7fd5eb#diff-b27b16759fae0fb0d94cc6e00107c8efR420

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22
