### ISSUE TITLE
Sidebar Widgets Default CSS should load on Woo commerce Sidebar

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3912]
Sidebar Widgets Default CSS should load on Woo commerce Sidebar for Default Word press Widget
[like:Archives, Meta , etc....]

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22
