### ISSUE TITLE
Images get streched in new version of the AMP FOR WP Plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3914]
In the latest update of DIVI, images get stretched. 
[test.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/3931823/test.zip)
If I rollback to 0.9.98.14 version then the images are not stretching. I have attached the JSON file to test the issue.

**Comment by Zabi09** [comment]
Just add class="aligncenter" to recreate the issue on local

**Comment by MohammedKaludi** [comment]
issue came after this fix. 
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3741

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 0.9.98.22

**Comment by Zabi09** [comment]
Issue not fixed in Tech Blogging AMP Theme

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.0
