### ISSUE TITLE
Breadcrumbs are not properly displaying and working in updated version 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3917]
Breadcrumbs are not properly displaying and working in an updated version, in 0.9.98.18 working good.

Category and its subcategories are getting club and forming one URL.

It should be like this: https://monosnap.com/file/L6kkOfxxuQJsvNcldbrXBW4pIMLHsg

It is displaying like this: https://monosnap.com/file/9yqaDCA8SDgby8FcY0lbXZYPZomETQ

https://secure.helpscout.net/conversation/1013013187/99052?folderId=2632030

**Comment by sonaliramteke** [comment]
It is not working in Design 1, 2, 3

**Comment by MohammedKaludi** [comment]
Removing this code is not the correct fix:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1635cc73c7df53cb2d173d3d4e15c00543e0d0f8#diff-9324dae989d0e611874f6bc4f1d6d2beL119

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.7
