### ISSUE TITLE
when user is not an admin and the admin bar is getting displayed as gap on the site

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3918]
https://secure.helpscout.net/conversation/1020344803/100345?folderId=2632030

**Comment by MohammedKaludi** [comment]
Code improvement required in `ampforwp_front_admin_menu_bar()` function

**Comment by WasimM3** [comment]
This was occurring because of tree-shaking.

**Comment by MohammedKaludi** [comment]
The current fix is incorrect also need to add this in proper way.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c25e77e8b5ae49ab1c68741ea7ad861731cb1137#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7259

Correct way-> `#wpadminbar + header #headerwrap{top:32px}` 

also need to improve the code. Do consult me while fixing this issue.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
