### ISSUE TITLE
AMP pages displaying previous gallery images with the current gallery images.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3919]
When user inserting multiple galleries using Gutenberg editor the previous gallery images also getting displayed with the current gallery images.

Issue recreated in localhost.

Ref: https://secure.helpscout.net/conversation/1025085086/101205?folderId=3257665
https://www.minimeenroute.com/rarotonga-accommodation-family-with-kids/
https://www.minimeenroute.com/rarotonga-accommodation-family-with-kids/amp/

**Comment by WasimM3** [comment]
This issue has been fixed the ticket #3923
