### ISSUE TITLE
TablePress support for AMP

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#392]
**Ref:**https://wordpress.org/support/topic/tablepress-support/

**Comment by khaledMohammed000** [comment]
I have gone through the tutorial https://www.youtube.com/watch?v=h8k5p8Fqepk and have come to following observations:

1. It can add links 
2. style like(bold, italic)
3. images

all this is getting added to the_content, so if it gets added need to be properly filtered

**Comment by MohammedKaludi** [comment]
Closing this ticket, continue on #574
