### ISSUE TITLE
when images are placed along with the anchor tag in gallery module of guntenberg editor the image src is getting unknown in AMP

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3923]
when images are placed along with the anchor tag in gallery module of Gutenberg editor the image src is getting unknown in AMP
https://secure.helpscout.net/conversation/1025613962/101300?folderId=2632030

Ref: https://monosnap.com/file/K5XbwG1huI7OMri93CSBwP6or9lRGD

https://secure.helpscout.net/conversation/1025613962/101300?folderId=2632030

**Comment by MohammedKaludi** [comment]
captions not working properly, explained to lokesh.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.0
