### ISSUE TITLE
Sub-Category Archives on AMP page should be connected to Change internal links to AMP option.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3924]
On an AMP page, the subcategories are not directed to the AMP page. 
https://monosnap.com/file/XTr3n9j2rahHDfXv0iTsK301o650Mu
Ref:- https://secure.helpscout.net/conversation/1019762589/100254?folderId=3243584

So, therefore, the subcategories should be connected to Change internal links to the AMP option.

**Comment by MohammedKaludi** [comment]
Ready  to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
