### ISSUE TITLE
Featured video width

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#3926]
Featured video player won't show properly on desktop, the player width is too small, making it poor experience in desktop. However, on mobile phones/smaller screens it shows perfectly fine. 
![screen1121](https://user-images.githubusercontent.com/40724154/70452815-6c31f100-1ab0-11ea-8450-22c49fc139fc.png)

**Comment by Zabi09** [comment]
Going to fix in - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3668
