### ISSUE TITLE
Google search console error   The attribute '=""' may not appear in tag 'nav'.

### ISSUE THREAD

**Issue by aiyayala** [ahmedkaludi/accelerated-mobile-pages#3928]
Footer nav is not working properly, the error code looks like this
![image](https://user-images.githubusercontent.com/45225968/70554929-1579f500-1b4c-11ea-84cc-f8da2ab7fa8b.png)

Found this <nav  itemscope="" itemtype="https://schema.org/SiteNavigationElement"
 form plugins/amp-layouts/extended/swift-footer-extended.php 

Pass GSC test after removing   itemscope="" itemtype="https://schema.org/SiteNavigationElement"

**Comment by Zabi09** [comment]
Going to fix in - https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/632
