### ISSUE TITLE
Adsense Ads not aligned properly for Above the Post Content and Below the Post Content (Single Post)

### ISSUE THREAD

**Issue by yogeshbeniwal** [ahmedkaludi/accelerated-mobile-pages#3929]
While using AD 3 Above the Post Content and AD 4 Below the Post Content (Single Post) for Adsense, Alignment of Ads is overlapping with left sidebar on Desktop, Rather than remaining within post content width.

ideally both of these ads should remain within post content width

Below is screenshot for reference:

![Screenshot](https://user-images.githubusercontent.com/7325107/70597432-4547fc00-1c23-11ea-9f06-ac05b9f22f60.png)

**Comment by Zabi09** [comment]
@yogeshbeniwal Will you please tell us how you are adding the Advertisement in AMP because I have checked with our AMP options and it was working fine, Will you please help us to recreate this on our end so that we can fix as soon as possible

**Comment by yogeshbeniwal** [comment]
@Zabi09 Advertisement are added to AMP pages by using Advertisement options available under Settings section. Below listed 2 Advertisement Options are used for Adsense:
Position: Above the Post Content, AD Type: Adsense (Responsive Ad unit)
Position: Below the Post Content (Single Post), AD Type: Adsense (Responsive Ad unit)

**Comment by ahmedkaludi** [comment]
Github is for tested and re-creatable bugs, for the technical issues, we will help you via https://ampforwp.com/support

**Comment by yogeshbeniwal** [comment]
@ahmedkaludi Isn't this a bug, Ads slot for Above the Post Content and Below the Post Content (Single Post) with Swift Theme are not aligned properly, and are overlapping with Sidebar
