### ISSUE TITLE
Add support for Discourse comment

### ISSUE THREAD

**Issue by yogeshbeniwal** [ahmedkaludi/accelerated-mobile-pages#3930]
Hi There,

Is there a way to add support for Discourse comments. This may be a major hindrance to encourage AMP Takeover.

**Comment by Zabi09** [comment]
@yogeshbeniwal If Discourse comments add the support for AMP then we will definitely add it in our plugin and if there is any way we can add it then let us know we will make compatible for you.

**Comment by yogeshbeniwal** [comment]
@Zabi09 May be at this point, support for discourse can be added by just adding hyperlink from "Leave a Comment" button to Discourse topic URL. This will also be helpful as not many people would want to show comments in case of using Infinite Scroll (Experimental)
