### ISSUE TITLE
Minor issues with amp need to fix

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3931]
REF:https://secure.helpscout.net/conversation/1027598984/101659?folderId=3008055

See this video:
https://www.youtube.com/watch?v=hn1DvTcyapU&feature=youtu.be

Need to verify every module with custom amp editor, amp page builder and basic editor of WordPress.

Now, these issues found:

- [ ] Underline link not working in amp page builder at both pages and posts.

- [ ] In custom amp editor underline link and font size of heading doesn't work at the page.

Before working on this ticket discuss with Ahmad sir

**Comment by sonaliramteke** [comment]
On the pages underline link is not working

**Comment by sonaliramteke** [comment]
AMP Pagebuilder is not working in design 1 2 and 3 (only in 99 beta ) Will you please check that

**Comment by Zabi09** [comment]
The page builder is not working due to this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2810, So you can just remove the "ampforwp_sanitize_twitter_title " function temporary and check

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.13
