### ISSUE TITLE
Debug warnings.

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#3932]
1. Warning: A non-numeric value encountered in : https://wordpress.org/support/topic/warning-a-non-numeric-value-encountered-in-8/

2. Trying to access array offset on value of type bool : https://wordpress.org/support/topic/trying-to-access-array-offset-on-value-of-type-bool/
![debug-warning](https://user-images.githubusercontent.com/16618009/70687475-52252800-1cd5-11ea-869f-8f45f758d5c5.jpg)

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3c179eed964f287fd8042e8e40e41a28a727d759#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3417-R3419

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3c179eed964f287fd8042e8e40e41a28a727d759#diff-caeb2e54b33d2d164c9e50b9731eb751R22-R24

use `get_option()` second parameter for default value

And https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f40fd9c4e76d97aad4d4debe3e312b2ec025d424#diff-e7f6ca8ce090f4ff7573a4eec8ccf52dR118 this solution will not solve the 1st issue

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.1
