### ISSUE TITLE
Search translate text option is visible in swift but unused

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/accelerated-mobile-pages#3934]
- [ ] In Design 3 Search translate text option is available.
1)https://monosnap.com/file/6mtRYkvItdiylrgmUmUyVOKp7bVulY
2) https://monosnap.com/file/4nFb4l7A451CGtMSXWmNpyuoyWknJc

but in Swift this option is not required. as per the design, Need to add the condition for the search translate option.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
