### ISSUE TITLE
Need to add proper way of styling for Header right side icons in Design 1,2 and 3

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3935]
Ref:- https://secure.helpscout.net/conversation/1023947988/100956?folderId=3243584

- [ ] Header wrap size overlapping the breadcrumbs which makes them unclickable]https://monosnap.com/file/E36uSyIGkdquKSqZdf4Lvwwd05wYY5   --- ### need to work on this.[This problem will fix on this ticket #3129]

- [ ] Header icons odd positioning https://monosnap.com/file/ofgkwbbrRNpHLjINEjpNbwiCQjGu0i
------###  this will fix in the below comment

- [ ] Header icons unwanted CSS https://monosnap.com/file/tCcVsEwOzXhHL47X6f9lCNHticQ5LP 
--- ### these css are not unwanted css that are actually icon css

**Comment by RajuJeelaga** [comment]
Need to add Proper styling for the search icon, call button, CTA and Cart, previously the styling is not done in proper way in Design 1,2 and 3

**Comment by RajuJeelaga** [comment]
When this ticket is ready to release, we need to release AMP Woo-commerce  Pro[3.4] also, because cart icon css changes are done on this.
Regards AMP Woocomerce updates consult @syedimran22

**Comment by amer07** [comment]
Case:II
https://secure.helpscout.net/conversation/1039131179/103504?folderId=2770543

**Comment by Zabi09** [comment]
Search is breaking in design 2 - https://prnt.sc/qftrco and also please use ampforwp_get_setting function - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/aecab3e2e38dfc84dae82ef6dfe62f17607741bb#r36578333

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Need to fix one thing at a time.

**Comment by syedimran22** [comment]
Design 3 fixed commit  https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c8a5829f9

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Design 3 done.

D2 and D1 improvements required

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.67
