### ISSUE TITLE
Video doesn't work on AMP when inserted from Siteorigin pagebuilder (Video player widget)

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3936]
Ref:- https://secure.helpscout.net/conversation/1024384647/101052?folderId=3243584
Description:- The video gets stuck on the cover image and does not play, when autoplay is off.
Note:- The autoplay is working fine.

1. https://monosnap.com/file/hqNjHNxqjgTajP3XAgSKtoVFtRhW7D
2. https://monosnap.com/file/1l9vmWNCQiwr5oUt1uICgbzyo3M7DR
3. https://monosnap.com/file/7R4liopptNjgruYGHTRTu0owlt8QzN

**Comment by MohammedKaludi** [comment]
Spacing required between autoplay and other items.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/32ca4d1511ef0ce58e68bd8cf3ab42e41cd7825c#diff-54dac7dab9dd460d137d86d279822cc5R11

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.13
