### ISSUE TITLE
In Amp struture data option if we added any schema then description generated in html format

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3937]
REF:https://secure.helpscout.net/conversation/1027679082/101669/

1.Recreated in localhost:
  -Create multiple paragraphs post
  -Set up schema amp>struture data>newsarticle
  -After that check source code of a page you will see 
https://monosnap.com/file/K3Mk9VrTDspaxwysHjlqpiPnnxxSQl

2.  At the user end, he also added schema using the above procedure and at the schema testing tool, he is getting HTML in the description.

**Comment by MohammedKaludi** [comment]
when the `$metadata['description']` and `$metadata['articleBody']`  are generating then again why did we added again?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ade53df71bcf073557957bd26b4703db465eaebf#diff-9f65b1edeb6d18b3cc5f9f2a21bfd824R100

**Comment by MohammedKaludi** [comment]
Add isset or something similar to check `description` and `articleBody` exists.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/061ebeaf41c10f2464d49bf1df765a90e405ac16#diff-9f65b1edeb6d18b3cc5f9f2a21bfd824R96

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
