### ISSUE TITLE
Improvements required in RTL support in AMP

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3938]
1. When RTL is enable amp-carousel images are not working properly.

https://secure.helpscout.net/conversation/1002743521/97396/
Solution: Add this CSS code.

.rtl amp-carousel {
    direction: ltr;
}

2. If RTL support is enabled then the dropdown icon in sidebar should show in left
Screenshot: https://monosnap.com/file/6HojFrylO1wTZBZW4jttYqWdJcQBUb

3. Month date should show in preferred language not in English in related articles.
Screenshot: https://monosnap.com/file/ZQL40BcwgQ3KSncUT4O0rwVDQoLa5m

For issue 2nd and 3rd reference link: https://secure.helpscout.net/conversation/1027912725/101691?folderId=2770545

**Comment by MohammedKaludi** [comment]
What about the 3rd point?

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
