### ISSUE TITLE
General code improvements part 3

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#3941]
General code improvements part 3

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8d0247f0c938f12318ac431e488115016edef6b6#diff-1a0e52b2651cea85b13d1cbf4f2198b0R1763 use add_query_var

**Comment by MohammedKaludi** [comment]
Remove this code:

`$tracking = Redux_Tracking::get_instance();` 

do contact me while fixing this one.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
