### ISSUE TITLE
From the  updated version 0.98.21 console errors are occuring from google tag manager

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3942]
https://monosnap.com/file/G4CXPHrYI7hM1cvhAZgZhb1UlrjOLR

https://secure.helpscout.net/conversation/1019473560/100208?folderId=2632030

https://smartmow.com/?amp

**Comment by MohammedKaludi** [comment]
Issue fixed in #3826
and 
Pushed in 1.0.1
