### ISSUE TITLE
Need to add one more parameter in filter(ampforwp_modify_rel_canonical) by which we can show or hide any pages.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3943]
Desc: Need to add one more parameter in the filter(ampforwp_modify_rel_canonical) by which we can show or hide any pages and will be helpful for any third party plugin to manage particular pages to show/hide in amp.

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php#L348

**Comment by Zabi09** [comment]
You can use "amp_skip_post" filter to show/remove the AMP
