### ISSUE TITLE
Icomoon.ttf is preloaded in Design 1 and Design 2.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3945]
Ref:- https://secure.helpscout.net/conversation/1031536963/102298?folderId=3243584

Screenshot:- https://monosnap.com/file/QR2fFRqkNB3ceZ1OwDiiVInnKoWQwV

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
