### ISSUE TITLE
Warring in console : [DOM]  Found 2 elements with non-unique id #amp-search

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3946]
Case:I
https://secure.helpscout.net/conversation/1028603581/101799?folderId=2770543

Make it sure has one id for both.
Screenshot:https://monosnap.com/file/k5oC9yCN6bh3dS4xtZmaYdKezfuYJW

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Search button still has the issue: https://take.ms/tOnvC

**Comment by MohammedKaludi** [comment]
Multiple ID's are still present : https://take.ms/kH7JxA

**Comment by MohammedKaludi** [comment]
issue still persists in 1.0+ branch.

https://take.ms/4fPFM

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
https://take.ms/TuABy 

and removed from the next update.

**Comment by samuelmarkno** [comment]
Multiple non-unique id still present in the Swift theme. In the other subjects (design one, two and three) the warning does not persist.

**Comment by MohammedKaludi** [comment]
@Zabi09  Ready to merge

and 
@samuelmarkno  this will be pushed in tomorrows update.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.20
