### ISSUE TITLE
Please Fix Errors in Google Lighthouse audit in Accessibility (using Swift, Amp Layouts)

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3949]
Please Fix Errors in Lighthouse Test in Accessibility which says 

- Background and Foreground colors do not have a sufficient contrast ratio
- Some links do not have a discernible name.
(using Swift, Amp Layouts) URL test for [https://omnitos.com](url)
or more into this  see screenshot below:
![Screenshot (410)](https://user-images.githubusercontent.com/51126159/70852688-6a11cd00-1eca-11ea-8049-0ae131d925bf.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.13
