### ISSUE TITLE
ThriveHeadlines tag from related posts

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#395]
http://take.ms/iLFQb

**Comment by Lofesa** [comment]
Hi @ahmedkaludi 
Test if this regex works
$content = preg_replace("/<[\/]?".$tag.".*?>/",'',$content);
in templates/features.php line 487

**Comment by ahmedkaludi** [comment]
This was fixed in the recent update. Thanks @Lofesa
