### ISSUE TITLE
Please Fix Errors in Google Lighthouse audit in Best Practices

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3950]
Please Fix Errors in Google Lighthouse audit in Best Practices which says

- Links to cross-origin destinations are unsafe
(using Swift, Amp Layouts) URL test for https://omnitos.com
For more refer to this screenshot:
![Screenshot (408)](https://user-images.githubusercontent.com/51126159/70852729-e7d5d880-1eca-11ea-9708-2908e325ea11.png)

**Comment by Zabi09** [comment]
@Omnitos It's showing 100 in Best Practices - https://monosnap.com/file/TV0cVJDKfJvrst1jXFNZj3bHdLosKv

Have you done any changes?

**Comment by Omnitos** [comment]
Yes I have removed the search icon in the head bar and author link

**Comment by Zabi09** [comment]
@Omnitos Will you please add those icons again which you have removed for us to check and once we find the issue then we will definitely fix it

**Comment by Omnitos** [comment]
I reactivated the search icon and the issue is fixed automatically, Though
now only accessibility and performance are left to be fixed!

**Comment by Zabi09** [comment]
Yeah, those issues will be fixed in their respected tickets, So closing this one
