### ISSUE TITLE
Please Fix Errors in Google Lighthouse audit in SEO

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3951]
Please Fix Errors in Google Lighthouse audit in SEO which says

- Tap targets are not sized appropriately
(using Swift, Amp Layouts) URL test for https://omnitos.com
For more refer to this screenshot:
![Screenshot (405)](https://user-images.githubusercontent.com/51126159/70852767-63d02080-1ecb-11ea-8ad7-bb7d41b28cfc.png)

**Comment by Zabi09** [comment]
@Omnitos It's showing 100 in SEO - https://monosnap.com/file/Nc2wORMhZGe0xWNSpB9l0PeXJQ9WOp

Have you done any changes?

**Comment by Omnitos** [comment]
Yes removing some of the icons like search bar or so

**Comment by Zabi09** [comment]
@Omnitos Will you please add those icons again which you have removed for us to check and once we find the issue then we will definitely fix it

**Comment by Omnitos** [comment]
I reactivated the search icon and the issue is fixed automatically, Though
now only accessibility and performance are left to be fixed!

**Comment by Zabi09** [comment]
Yeah, those issues will be fixed in their respected tickets, So closing this one
