### ISSUE TITLE
Please Fix Errors in Google Lighthouse audit in Performance

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3952]
Please Fix Errors in Google Lighthouse audit in Performance which says

- Preconnect to required origins
- Also, try to improve performance scores more.
(using Swift, Amp Layouts) URL test for https://omnitos.com
For more refer to this screenshot:
![Screenshot (409)](https://user-images.githubusercontent.com/51126159/70852799-b7db0500-1ecb-11ea-9ebf-8f4653336223.png)

**Comment by Zabi09** [comment]
We are creating an option for DNS prefetching in this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3997 and once this ticket is pushed then you can add these URLs - https://monosnap.com/file/OdL1SqrRAA1AaVk49KL43Peq8hYYbs and that will fix your issue

**Comment by Zabi09** [comment]
Going to fix in - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3997
