### ISSUE TITLE
Add expiry of cache Leverage browser caching for the following cacheable resources:

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3953]
Got this error in GTMetrix
(using Swift, Amp Layouts) URL test for https://omnitos.com/?amp
For more refer to this screenshot:
![Screenshot (412)](https://user-images.githubusercontent.com/51126159/70852878-89115e80-1ecc-11ea-8644-a30d5e546705.png)

**Comment by ahmedkaludi** [comment]
We already do this for all the resources. AMP project js files cannot have expiry headers.
