### ISSUE TITLE
Linked amp version is invalid on pages

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3955]
Custom HTML is not allowed probably after an update or by Schema plugin or wp fastest cache. 
Url: https://omnitos.com/boruto-chapter-41-spoilers-release-mega-thread/
Using Amp Layouts
Please Check Screenshot:
![Screenshot (421)](https://user-images.githubusercontent.com/51126159/70865287-b53ae700-1f81-11ea-981d-c5265766b80b.png)
.

**Comment by ahmedkaludi** [comment]
Github is for valid & re-creatable bugs. Technical support is provided at https://ampforwp.com/support/
