### ISSUE TITLE
Time is not working in published date notice 

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3956]
In date notice, if we select published date notice then date published to date and year showing correctly just time changes.

See this screenshot:
https://monosnap.com/file/eRvDMOPmxprPb8eVvvuYicadnUsrY1
https://monosnap.com/file/K9WIORSbBu3YpPHZhWpGZvcKat6KpF

REF:https://secure.helpscout.net/conversation/1027679082/101669?folderId=3008055

**Comment by Zabi09** [comment]
It should be connected to this - https://prnt.sc/qdeb9c and also connect it with "Time" option

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
