### ISSUE TITLE
GDPR popup appears once agin after accepting it

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3957]
it is occurring when we go through the google search first the gdpr policy is occurring form the cache version of the site and once we click any post on the site it gets redirects to the main site server and again from there the gdpr policy is getting appear. 

https://secure.helpscout.net/conversation/1013151975/99067?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
