### ISSUE TITLE
Debug warning : Undefined index element

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3958]
Fetching debug warning in our latest update(1.0.1)

Warning:
Notice: Undefined index: elements in C:\xampp\htdocs\myhosti\wp-content\plugins\accelerated-mobile-pages\templates\design-manager.php on line 23

Ref Ticket: https://secure.helpscout.net/conversation/1032658100/102499?folderId=3126461

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
