### ISSUE TITLE
Undefined index: elements

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3960]
AMP version: 1.0.1
`/wp-content/plugins/accelerated-mobile-pages/templates/design-manager.php in require at line 23`

![image](https://user-images.githubusercontent.com/45454204/70901165-8876e600-1ffa-11ea-8668-30e5d53bcfba.png)

**Comment by MohammedKaludi** [comment]
@kevinmrl Thank you for creating the ticket, 
Issue is already reported and fixed in #3958 and will be pushed in next update on Wednesday.

**Comment by kevinmrl** [comment]
Thank you. Tried to look before reporting but for some reason didin't find
