### ISSUE TITLE
Undefined variable: designCss

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3961]
AMP version: 1.0.1
`wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/testimonial-mod-module.php at line 93`

![image](https://user-images.githubusercontent.com/45454204/70901361-eb687d00-1ffa-11ea-9082-4d2440c397c0.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
