### ISSUE TITLE
Undefined variable: amp_cur_url

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3962]
AMP version: 1.0.1

`/wp-content/plugins/accelerated-mobile-pages/templates/features.php in ampforwp_view_amp_admin_bar at line 5002`

![image](https://user-images.githubusercontent.com/45454204/70905865-4e5f1180-2005-11ea-835e-ce5a179d9739.png)

**Comment by WasimM3** [comment]
The issue was resolved under this https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3806

**Comment by MohammedKaludi** [comment]
Will be fixed in #3806
