### ISSUE TITLE
AMP theme framework GDPR module should be connected to GDPR Compliancy in option panel.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3963]
Ref:- https://secure.helpscout.net/conversation/1031728797/102370?folderId=1060556

When a user adds the GDPR module in the AMP theme framework then it should be connected to GDPR switch in the options panel.
Otherwise, when the module is added, GDPR is turned off then markup is loaded but the script is missing which creates a validation error.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.7
