### ISSUE TITLE
The Close bar is not appearing menu check in mobile Iphone

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3964]
REF:https://secure.helpscout.net/conversation/1018035819/99900?folderId=3008055
The close bar is not appearing menu check-in mobile iPhone,

See this screenshot:
https://monosnap.com/file/3JOoczVL0fUdJNOCW77XnO81v6ZAvB

https://www.saveatrain.com/blog/london-paris-train/amp/

**Comment by udiudiudiudi** [comment]
i wanted to add, that once you fix this, please also test the button on the rtl languages:
[https://www.saveatrain.com/blog/london-paris-train/amp/?lang=he](https://www.saveatrain.com/blog/london-paris-train/amp/?lang=he)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.2
