### ISSUE TITLE
The tag 'amp-auto-ads extension .js script' appears more than once in the document

### ISSUE THREAD

**Issue by scavin** [ahmedkaludi/accelerated-mobile-pages#3965]
The tag 'amp-auto-ads extension .js script' appears more than once in the document. Debug. Learn more. 1 7562 https://www.appinn.com/joplin/amp/

**Comment by ahmedkaludi** [comment]
It's definitely due to some 3rd party plugins. Github is for recreatable bugs, I suggest you to get help on the technical support from https://ampforwp.com/support/
