### ISSUE TITLE
Warning issue with  "$amp_emplate->get('metadata')" undefined metadata

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3967]
Warning issue with  "$amp_emplate->get('metadata')" undefined metadata

Ref screenshot: https://monosnap.com/file/GIdRY0lMBqSZy8xp8pgUKgZKoZoVK1

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
