### ISSUE TITLE
Recoverable fatal error: Object of class DOM Node List could not be converted to string

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3968]
Case:I

https://secure.helpscout.net/conversation/987490810/93749?folderId=2770543

 "Recoverable fatal error: Object of class DOMNodeList could not be converted to string in /home/kalmaror/domains/kalmar.org.il/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-gallery-block-sanitizer-5-3.php on line 378"

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b19bea09057dbc12f880fcf9e0f5eb1839bad4a6#diff-a019e0b6d9b0c2552c18c4f849c9a770R402 Check here is_object. because "isset" can pass if there is nothing also

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
