### ISSUE TITLE
kk star validation issues

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#397]
With AMPforWP and kk star rating enabled together, pages are showing validation issues.

Ex: The attribute ‘property’ may not appear in tag ‘span’

**Ref:**https://wordpress.org/support/topic/star-rating-error-with-amp/
http://www.aquascaping-blog.com/2641/wabi-kusa/amp

**Comment by alexchuin** [comment]
Same problem here.

Any quick fix to disabled kk star in AMP mode ?

**Comment by khaledMohammed000** [comment]
Fixed Here : https://github.com/ahmedkaludi/amp-rating/commit/ab172762323808af62bb2c16e0cecc1fd34e195f

**Comment by alexchuin** [comment]
Thanks ! But the commit is not found

**Comment by MohammedKaludi** [comment]
@alexchuin the commit was push in Rating extension, https://ampforwp.com/amp-ratings/

It's private repo and that's why its showing 404

**Comment by MohammedKaludi** [comment]
Issue fixed, Now AMP site Fully compatible with KK star Rating.
