### ISSUE TITLE
Need to add Rankmath's "Nofollow External Links" feature.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3970]
Need to add Rankmath's "Nofollow External Links" feature.
Ref: https://secure.helpscout.net/conversation/1035728509/102938/

**Comment by MohammedKaludi** [comment]
Update the code while merging.

1. Class Exists position 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f91e88a4314bd06687dab7c533fc99c47ca5dbf9#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7970

This is better method for performance.
`if(class_exists('RankMath')){`
`add_filter('ampforwp_modify_the_content','ampforwp_rank_math_nofollow_to_external_link');`
`}`

2. Escaping URL.
`$url` https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f91e88a4314bd06687dab7c533fc99c47ca5dbf9#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7980

**Comment by WasimM3** [comment]
Merged

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.7
