### ISSUE TITLE
Need to add a Filter in amp tree shaking for adding custom CSS.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#3971]
Desc: Need to add a Filter in amp tree shaking for adding custom CSS so that we can add CSS for amp-bind classes.

**Comment by MohammedKaludi** [comment]
Add Typecasting as `$white_list = (array) apply_filters('ampforwp_tree_shaking_white_list_selector',$white_list);` to make sure we are only getting array, as  we are using `count($white_list) ` just below that.

This is for safeside to prevent warnings.


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/df1cb0fa8a5fdfcb2d96ccd24775fe264c1eb7f9#diff-54dac7dab9dd460d137d86d279822cc5R196

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
