### ISSUE TITLE
Need to add Categories Images plugin compatibility

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#3973]
Case:I
https://secure.helpscout.net/conversation/1020071282/100289?folderId=2770543

plugin url:https://wordpress.org/plugins/categories-images/

See this screenshot: https://prnt.sc/qcxaqj

**Comment by Zabi09** [comment]
Image not appearing when there is no description

**Comment by MohammedKaludi** [comment]
Code improvement required.

**Comment by MohammedKaludi** [comment]
default is missing.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cd6b428209f7b6c924eca99fbf239e64fc4d7380#diff-1301281de287d2aed98746fc9ba777b4R1089

**Comment by MohammedKaludi** [comment]
code improvement required.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a9b03c1a99bb06cde6be2ab7e40076905cf30100#diff-1301281de287d2aed98746fc9ba777b4R1089-R1096

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.72 update
