### ISSUE TITLE
Need to built compatibility with "Mistape" plugin.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3974]
The user using "Mistape" plugin and in AMP version fetching "The tag 'path' may only appear as a descendant of tag 'SVG'" validation issue.

Plugin: https://wordpress.org/plugins/mistape/
Ref Ticket: https://secure.helpscout.net/conversation/1035247651/102888?folderId=3126461

Recreating the issue:
- install the plugin and go to Mistape settings
- in settings need to enable it on page or post.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f80c63543e0aecd256b4602a1eb66a155cd938c6#diff-1301281de287d2aed98746fc9ba777b4R1162
is this correct is we get any other span inside outer span then https://regex101.com/r/bNoj5S/1

**Comment by WasimM3** [comment]
Grabbing the <path></path> from the match and replacing it with the anchor and SVG.

**Comment by ahmedkaludi** [comment]
it's good to go

**Comment by MohammedKaludi** [comment]
Need to check if function exists at the hook.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f80c63543e0aecd256b4602a1eb66a155cd938c6#diff-1301281de287d2aed98746fc9ba777b4R1152

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
