### ISSUE TITLE
If the user adds the social share link in the users section then we need to show social share icon

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3976]
Ref: https://secure.helpscout.net/conversation/1029628579/101984?folderId=2770545

1. If the user adds the social share link in the user's settings then we need to convert that links into the social share icon.

Screenshot1: https://monosnap.com/file/FATWx8LB0WV3fL4brBqY49toeXay5c
Screenshot2: https://monosnap.com/file/HzEa4luNnOZEIZVLi3fwgXfSbAhAv4

The fields to insert the social share links will come when we install the YOAST SEO plugin.

2. If the user is giving a full Twitter link in the user's settings then it creates an issue in AMP post because we are already adding "https://twitter.com/" before the URL which goes to a 404-page error on AMP after clicking the link. If we remove  "https://twitter.com/" from the user's settings then it creates problem for the author page.

Screenshot: 1. https://monosnap.com/file/kUdCpSmX6zW9ENrkr5VOS7hMh48PRS
2. https://monosnap.com/file/AYydilqMpAuzW2b9ZvFCX33Yck2K1w

So, We need to detect first what URL user has entered.

**Comment by sonaliramteke** [comment]
It is not working in Desing 1, 2, 3

**Comment by sonaliramteke** [comment]
styling issue - underline coming when we hover on the social share icon

**Comment by sonaliramteke** [comment]
underline is coming now also will you please check once

**Comment by MohammedKaludi** [comment]
This is not the correct fix:

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e3b3acaaa2953222b79cb560fde9345e532117fb#diff-2ae5550e31f40c1962ca69d373af6b93R759


Don't break old things for fixing the new ones.

**Comment by MohammedKaludi** [comment]
need code improvement.

**Comment by MohammedKaludi** [comment]
need to add `isset()` 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/fdf85e383c4a8e78f3c6d14539ca74d010d0a770#diff-1301281de287d2aed98746fc9ba777b4R969

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.17
