### ISSUE TITLE
When user search from the AMP site then results page should be in non-AMP.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#3977]
When a user search from the AMP version site then the results page should redirect to the non-AMP.

This option is related to AMP > Advance settings > Mobile redirection > Search pages

And when the user turns off the search feature then there should be no search related files on the user site.

Ref Ticket: https://secure.helpscout.net/conversation/1034942069/102842?folderId=3126461

**Comment by Zabi09** [comment]
Please remove the option from here - https://prnt.sc/qft9w0 and add it advance settings and also I think we need to create a new child option inside the "Search Pages" to fix this issue

**Comment by Zabi09** [comment]
Not working will you please check once

**Comment by MohammedKaludi** [comment]
Tooltip text is incorrect: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2bca8e78a7a22427c369c28e828859a9b73b54db#diff-260eba6333c3222e59a6aed22ac5ab37R2930

**Comment by MohammedKaludi** [comment]
`$current_url` cleaning required,  direct usage of `$_SERVER` or any other super global variables should be avoided, because we do not have any control on the data so it is a good practice to clean the received data.


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c7ca255c37c8612da70bf6978fe693aed1b6c274#diff-ab576767b896423d184ddafe2ede2310R50

**Comment by WasimM3** [comment]
Improved code for #3939 and #3269. @WasimM3 needs to test it while merging.

**Comment by MohammedKaludi** [comment]
Title and Tooltip still needs to be updated:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/15c63749ae71b3379bcdf25df42e1ca4a601d341#diff-260eba6333c3222e59a6aed22ac5ab37L2929

Do let me know while merging.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
