### ISSUE TITLE
I got warnings from Google Webmaster

### ISSUE THREAD

**Issue by kevin25** [ahmedkaludi/accelerated-mobile-pages#398]
Please take a look at the attachment.
![screen shot 2017-01-10 at 2 36 14 am](https://cloud.githubusercontent.com/assets/2909982/21798315/a89132d4-d6e1-11e6-8273-883d83959682.png)

**Comment by ahmedkaludi** [comment]
Can you provide some more details on this please?

**Comment by ahmedkaludi** [comment]
@kevin25 Please provide this or I have to close this issue.
