### ISSUE TITLE
When from amp page builder adding text module then space is not coming in paragraph 

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#3982]
REF:https://secure.helpscout.net/conversation/1034055360/102716?folderId=3008055

When from amp page builder adding text module then space is not coming in paragraph 

See this screenshot:
https://monosnap.com/file/1iGkvmZexTD9iFO5HHr5M5BW8O4T3m
https://monosnap.com/file/gOdD6PLoR5cnRkv6vBNOfoWojdmKml
https://monosnap.com/file/2ECwygPf3skegp1Yo4WJudjR17Dk6r

**Comment by ahmedkaludi** [comment]
**before committing the code, get a review from me**

**Comment by MohammedKaludi** [comment]
do not use general `p` 

please be specific `p`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9ba7b25b421abf0090681d503120dba214cea11c#diff-2ae5550e31f40c1962ca69d373af6b93R2040

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.13
