### ISSUE TITLE
404 error in console with Images having webp extension.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3983]
1. Ref:- https://secure.helpscout.net/conversation/1037798712/103260?folderId=3243584
The user is using the Imagify plugin.
https://monosnap.com/file/PAcQlrqe9Z5A98WBHrdINvhItmLAOb

2. Same issue in safari browser to this user:- https://secure.helpscout.net/conversation/945238081/80010?folderId=1060556
Images are working in chrome browser but not in safari.
User is using Webp express for image conversion.

**Comment by WasimM3** [comment]
Issue 2. Same issue in safari browser to this user:-
     Images are working in chrome browser but not in safari.
     User is using Webp express for image conversion. 
     
Webp express Plugin itself is not allowing to showing the image on safari.
Ref link - https://wordpress.org/plugins/webp-express/#blank%20images%20in%20safari%3F

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4615551fd988a6e866b8a8c4592bba9da2a8c03d#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8045
Add isset in `$headers[0]` For safe case

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.9
