### ISSUE TITLE
EWWW Image Optimizer plugin Compatibility

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3984]
https://secure.helpscout.net/conversation/1033511356/102651?folderId=2632030

**Comment by ruaconx11** [comment]
Hope for a new update!

**Comment by ruaconx11** [comment]
Hope for new update ! :(  15 day ago :(

**Comment by MohammedKaludi** [comment]
pushed in 1.0.17

**Comment by MohammedKaludi** [comment]
Issue seems to be fixed, but need to test once again before merging.

Do let me know when you are ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
