### ISSUE TITLE
Select Taxonomy and Select Category is getting blank in the category module of AMP page builder

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3986]
REf: https://secure.helpscout.net/conversation/1034755140/102796?folderId=2632030

Select Taxonomy and Select Category is getting blank in the category module of AMP page builder.

Initially, Select Category is appearing once the page is load

For detail information view please see this video: 
https://monosnap.com/file/b5kvemKbN0HRXnDXmjZV4yoax5GDkk

Also, we are getting notices which are mentioned below:

Ref: https://monosnap.com/file/83Ne9EMbNAMC1LWEUQUc9SAjVCwDI1

Notice: Undefined offset: 0 in /home/fotogra9/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 389

Notice: Undefined offset: 0 in /home/fotogra9/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 380

Notice: Undefined offset: 0 in /home/fotogra9/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 389

**Comment by TMsravan** [comment]
For another user getting notices:

Notice: Trying to get property of non-object in /home/ucokcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 1090

Ref: https://monosnap.com/file/7hIGY8fnoSj6nR6axsUTO4ESjFEVpE

https://kuistoto.com/amp/

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
