### ISSUE TITLE
Add support for Syntax Highlighting

### ISSUE THREAD

**Issue by yogeshbeniwal** [ahmedkaludi/accelerated-mobile-pages#3988]
Hi There, Consider adding support for Syntax Highlighting as done for non-AMP pages by SyntaxHighlighter Evolved plugin https://wordpress.org/plugins/syntaxhighlighter/

**Comment by ahmedkaludi** [comment]
We will certainly try to add more compatibilities but the syntax highlighting can be only be done with Javascript and I don't think that is available in AMP.
