### ISSUE TITLE
Notice: Undefined offset: 0

### ISSUE THREAD

**Issue by kevinmrl** [ahmedkaludi/accelerated-mobile-pages#3989]
Newest AMP: 1.0.2

`/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php in AMPforWP\AMPVendor\AMP_Post_Template::ampforwp_add_fallback_element at line 380`

![image](https://user-images.githubusercontent.com/45454204/71263546-5c34cf80-2342-11ea-89c1-90bf570426f5.png)

**Comment by MohammedKaludi** [comment]
Fixed in #3992 and will be pushed in next update.
