### ISSUE TITLE
Redux not working with the following theme

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#399]
When we activate the engrave(lite) theme , options panel disappears.

**Comment by khaledMohammed000** [comment]
Author's from "thinkupthemes" completely removes The code from framework.php , these lines are really important for our settings page to be shown 👍  
http://take.ms/nhxS6

Solution : Simply add those lines and our Settings page will be visible (Code in Function_options_page() line 2123 )

**Comment by khaledMohammed000** [comment]
https://github.com/reduxframework/redux-framework/issues/3213
