### ISSUE TITLE
Add support for Katex

### ISSUE THREAD

**Issue by yogeshbeniwal** [ahmedkaludi/accelerated-mobile-pages#3990]
Add Katex Support for AMP pages as supported by https://wordpress.org/plugins/katex/ plugin for non-AMP pages. It will be more useful if syntax supported by non-AMP plugin is automatically converted and rendered by AMP page, rather than writing separate text for AMP and non-AMP pages

**Comment by ahmedkaludi** [comment]
we can use it using https://amp.dev/documentation/components/amp-mathml/

**Comment by MohammedKaludi** [comment]
Moved on : https://ampforwp.com/compatibility/idea-board/
