### ISSUE TITLE
AMP for WP incompatible with Jetpack Lazy Image Loading

### ISSUE THREAD

**Issue by careerbreakadventures** [ahmedkaludi/accelerated-mobile-pages#3991]
When I installed AMP for WP a week ago, my website suddenly stopped lazy loading images on non-AMP pages (I use Jetpack). I contacted Jetpack and they could see that Lazy Loading was trying to initialize when a page was opened but was then being blocked. After deactivating each of my plugins and clearing my cache, I was able to find that the AMP for WP plug was the one blocking lazy loading from all of my pages (AMP pages lazy loaded fine, only issues with non-AMP). With the plug in turned off, everything works fine. It would be great if there were a fix to allow Jetpack lazy load to be compatible with AMP for WP.

For reference, I use Jetpack CDN / Lazy Loading for images and static files. I also use Fastest Cache and Autoptimize for load speed improvements. This issue has been checked with both of caching / optimization plugins cleared and deactivated, which did not stop the problem.

Thank you!

**Comment by ahmedkaludi** [comment]
We would love to help you solve the problem. 
Github is for clear and re-creatable issues, our technical support team helps you with debugging the issues. Kindly ask them on https://ampforwp.com/support/
