### ISSUE TITLE
Notice: Undefined offset: 0 in /home/ankararesimkursu/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php on line 378

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3992]
Notice: Undefined offset: 0 in line no. 378,379,380,388,389

Ref: https://secure.helpscout.net/conversation/1037985799/103302?folderId=2770545

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
incorrect conditioning 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/02f26b068b496ff3726ff337ca6febb72fc7a7da#diff-f0e1f733035b4437575d3172e86526dfR391

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.3
