### ISSUE TITLE
Caption of image gallery not displaying

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#3993]
when we are adding a caption by the option(as shown in the screenshot) is not displaying on AMP pages.
https://monosnap.com/file/Zjp7v9Srvq1zFf4PGquc43oZ6PAsOk

Ref: https://secure.helpscout.net/conversation/1025085086/0/?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
