### ISSUE TITLE
when Optimize CSS (beta) option is enabled AMP page is getting blank, wp-blocks css is loading heavily

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3994]
when Optimize CSS (beta) option is enabled AMP page is getting blank, wp-blocks CSS is loading heavily 

https://secure.helpscout.net/conversation/1037796566/103259?folderId=2632030

**Comment by MohammedKaludi** [comment]
1st part is fixed and Pushed in 1.0.4 

2nd part wp-blocks css is loading heavily  is this fixed ?

**Comment by WasimM3** [comment]
2nd part wp-blocks CSS is loading heavily is this fixed?
 - This has been fixed as well.
