### ISSUE TITLE
Menu arrow icon not showing properly in mobile version

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3995]
Ref: https://secure.helpscout.net/conversation/1018805340/100085?folderId=2770545

- [x] Case1: if the Custom link is empty of the parent menu, then the arrow icon is showing on the menu name of the parent menu.

Screenshot: https://monosnap.com/file/hLqRtHHWJ17qcU9ob8ya7TumGpiJ4t

- [x] Case 2: If the parent menu text is greater than 35 characters then the arrow icon is not showing in the mobile version. In the desktop version, it is showing. 

Screenshot: 
1. https://monosnap.com/file/UQVKEsD76rrtFXoeGDzEJZTDbqVL3t
2. https://monosnap.com/file/7uVJ3JHCkjuD8UTKZEPticDmii39yx

**Comment by MohammedKaludi** [comment]
Ready to push,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.5
