### ISSUE TITLE
Custom Header Code Removes Iframe Custom JS

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#3996]
Hello,

If I add the following code via Advanced settings > Head Section

`<script custom-element=amp-iframe src=https://cdn.ampproject.org/v0/amp-iframe-latest.js async></script>`

It's not displayed in any AMP posts. However, anything else works, like

```
<script custom-element=amp-iframe src=https://cdn.ampproject.org/v0/amp-iframe-latest.js async></script>
LALALAL
```

Will output just LALALAL but not AMP Custom Iframe JS.

How do I fix this? I need to use iframe amp for advanced ads plugin. but as per ticket 12568, it's not auto adding AMP IFRAME javascript to headers, causing validator errors

Workaround: if I add IFRAME into post itself (not advanced ads), your plugin will automatically include

`<script custom-element=amp-iframe src=https://cdn.ampproject.org/v0/amp-iframe-latest.js async></script>`

Which removes all validator errors. The problem is that my posts don't have iframe code by default and I use iframe code for ads only.

**Comment by ahmedkaludi** [comment]
Github is for tested & re-creatable bugs, Technical support on https://ampforwp.com/support

**Comment by djixas** [comment]
> Github is for tested & re-creatable bugs, Technical support on https://ampforwp.com/support

This is a tested and retested bug, did you even read the post?
