### ISSUE TITLE
Create an option for DNS prefetching which allows users to enter URLs to prefetch.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#3997]
Create an option for DNS prefetch which allows users to enter URLs which they need to prefetch.
Or any other automated method which does not require to enter URLs manually.

Ref:- https://secure.helpscout.net/conversation/1031536963/102298?folderId=3243584

**Comment by Zabi09** [comment]
Once this ticket is completed then need to test this ticket also - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3952

**Comment by MohammedKaludi** [comment]
code improvement required.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a1d116abb573a8f3ff5b51b18c59b106c4d171c3#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6918

**Comment by MohammedKaludi** [comment]
How we are making sure that the user only adds URL in the field?

**Comment by MohammedKaludi** [comment]
Two issues found: 
1. Position of the field is incorrect, the field should be after "Enter HTML in Footer": https://take.ms/3PWbW
2. Tooltip text needs to be improved.
3. Tutorial link needs to be added.

**Comment by MohammedKaludi** [comment]
Always getting the last url.
Dashboard: https://take.ms/kI75A
Frontend: https://take.ms/K0pzM

**Comment by MohammedKaludi** [comment]
Will improve this:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/de2c1294c96b8ca10c65e9f9b5a5c081e1874b6a#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6947

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by sonaliramteke** [comment]
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 6972

**Comment by WasimM3** [comment]
Tested in a different system working as expected

**Comment by MohammedKaludi** [comment]
Warning is valid :  https://take.ms/afdG0

when empty field is added :  https://take.ms/B7Jf1

**Comment by MohammedKaludi** [comment]
UX needs improvements, do contact me i'll explain you the issue,

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
