### ISSUE TITLE
Fix Google Lighthouse Test issues in Newspaper amp theme

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#3998]
There are lots of errors in general which are needed to be fixed and an update to the plugin is needed for the Newspaper amp theme by you. Like accessibility, best practices, Seo and some icons issue in performance. It needs improvements.
Check ss below 
https://prnt.sc/qeszvu
For example, you can use this URL to see the general issues: https://omnitos.com

**Comment by ahmedkaludi** [comment]
I have moved this ticket to the Private Trello board where we manage the Newspaper AMP issues
