### ISSUE TITLE
when row Wrapper is set to 100%,static css of max width 90% is getting applied from tablet view mode to below

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3999]
when row Wrapper is set to 100%, static CSS of max-width: 90% is getting applied from tablet view mode to below view mode.

This is the CSS which is getting applied: 

.col-2-wrap{max-width:100%;}

https://secure.helpscout.net/conversation/1040069344/103645?folderId=1060556

Please see this screenshot:Ref: https://monosnap.com/file/YB6yla3debkqSUlwOsvm1U6TCnfJTn

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
