### ISSUE TITLE
Advanced AMP ADS - Custom Incontent Ad - Issue

### ISSUE THREAD

**Issue by loano** [ahmedkaludi/accelerated-mobile-pages#400]
Incontent ads not working when Advertisement Type = Custom Advertisement. Tested with Adsense AMP code. Result: Article content gets cut off after the ad placement(s)

**Comment by khaledMohammed000** [comment]
I have tested this Locally, seems fine to me . Are you Sure you have Version 1.4 ? If you feel the issue is still there please share us a URL :)

**Comment by loano** [comment]
Hm, I can reproduce this on desktop server and on our live test site. Version 1.4. Please have a look here: http://lustaufeinbier.de/streetscore-scores-a-street-view-based-on-how-safe-it-looks-to-a-human
vs.
http://lustaufeinbier.de/streetscore-scores-a-street-view-based-on-how-safe-it-looks-to-a-human/amp

**Comment by khaledMohammed000** [comment]
Hey @loano am presently fixing this... can you gimme a screenshot of your settings page

**Comment by loano** [comment]
Hey @khaledMohammed000 please have a look here: https://www.dropbox.com/s/i23zf0ryzsp1f4h/Advanced%20AMP%20Ads%20issue.PNG?dl=0

**Comment by khaledMohammed000** [comment]
Hey @loano I just saw the Ad code....please close <amp-ad> tag in both the ad areas and recheck

**Comment by loano** [comment]
Sorry for any inconvenience, @khaledMohammed000 , totally overlooked this. Works perfect, now.

**Comment by khaledMohammed000** [comment]
No Problemo bro, It happens with every one of us 👍
