### ISSUE TITLE
Need to add option to hide "AMP version" in view source page(generator).

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4000]
Need to add the option in Advanced settings that user can hide to reveal the version of
plugins used in view source page.

Ref Ticket: https://secure.helpscout.net/conversation/1039568019/103593?folderId=3126461
Screenshot: https://monosnap.com/file/MVc8V9NGEZioI8Wef2dFNDaeFWUoFy

**Comment by beeriz** [comment]
This is indeed an important feature. Thanks Sardarui

**Comment by Zabi09** [comment]
I think the user wants to remove the generator meta tag not just the version

**Comment by beeriz** [comment]
> 
> 
> I think the user wants to remove the generator meta tag not just the version

Yes, this is what I intend to do, remove the entire generator meta tag.

Thanks

**Comment by MohammedKaludi** [comment]
conditions not added in the proper place.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7f75914d568bb691f84c81f31ded81b2f6f3f331#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6832

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
