### ISSUE TITLE
WPFORMS BUG

### ISSUE THREAD

**Issue by marbaz** [ahmedkaludi/accelerated-mobile-pages#4002]
When using AMP and the WPforms plugin "file upload" field is not working in the form. (webversion is working, AMP is not showing the field or the field is shown as a normal text field and upload of a file is impossible.

**Comment by ahmedkaludi** [comment]
GitHub is for the AMPforWP core issues, we would love to help you with this issue but you have to contact us via https://AMPforWP.com/support
