### ISSUE TITLE
Swift theme Icons are not working on the cached version by Google for a few days

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#4003]
Swift Icons are not working on the cached version by Google for a few days. Using amp layouts.
I contacted your support but they changed to font-awesome icons but they really slow down the site and have performance issues. Can you please see what the actual issue is? It is only not working on the Google's Cache. This was working fine but from a week facing this issue. Even if I disable Cloudflare amp or enable it, they don't work at all. Even after disabling plugins it doesn't work. Please don't forward it to email support and close the ticket, do check this issue. See this screenshot below:
See the cached version of this post: https://omnitos.com/demon-slayer-kimetsu-no-yaiba-chapter-189-spoilers-release-date/
![80859148_977736329256516_482920144167763968_n](https://user-images.githubusercontent.com/51126159/71448502-94814700-2762-11ea-9dfc-ef932e541942.jpg)

**Comment by ahmedkaludi** [comment]
The issue is a rare issue occurred Due to Cdn conflict on some servers. The solution is to switch to font awesome icons.
