### ISSUE TITLE
Mobile Redirection isn’t working with cloudflare

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#4004]
I have contacted the email support but they are unable to fix it, please help, I am losing revenue.
Mobile Redirection isn’t working properly with Cloudflare see ss below. PLEASE HELP.

https://prnt.sc/qfw8ui

**Comment by ahmedkaludi** [comment]
The Cloudflare is not compatible with Mobile Redirection. They have to improve their caching system. 

It's nothing to do from our side.
