### ISSUE TITLE
Need to connect retina image functionality to In-content Related post thumbnails.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4007]
One of our user-facing blur images in related post thumbnails. in order to overcome this issue, we need to add retina image functionality to related post thumbnails. 

Ref Ticket: https://secure.helpscout.net/conversation/1040217829/103670?folderId=3126461

Ref URL: https://theunlockr.com/best-investment-apps/amp/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
