### ISSUE TITLE
Query monitor is not working in our latest version.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4008]
Need to load Query monitor data in the latest version, so that users can use it and it will be easy for us to debug the slow queries issues.

Query monitor data is loading in AMP pages if users have the below versions:

AMP version: 0.9.97.65
Query monitor version: 2.17.0

**Comment by MohammedKaludi** [comment]
Issue  came due to #3706

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
