### ISSUE TITLE
amp-auto-ads script is loading in AMP-pages when Google site kit plugin is enable.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4009]
AMP pages showing validation error as "amp-auto ads script found on this page but is unused" when Google site kit plugin is enable.
Ref: https://secure.helpscout.net/conversation/1039304484/0/?folderId=3257665

**Comment by Zabi09** [comment]
We will test this ticket once this ticket is pushed - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3257

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.7
