### ISSUE TITLE
Need to update the Form Sanitizer to allow only the required from

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4010]
Need to update the Form Sanitizer to allow only the required froms

Like we did here: https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/679

**Comment by Rkroy** [comment]
Need to add class name **ampforwp-form-allow** for sanitizing the form.

**Comment by Zabi09** [comment]
Also need to update this tutorial - https://ampforwp.com/tutorials/article/override-blacklist-sanitizer/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.9
