### ISSUE TITLE
RECENT POSTS label visible if no posts are available

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4011]
RECENT POSTS label visible if no posts are available

https://take.ms/qzTzX

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/96de9892bfd1fcd74e9b5547b86bf4ec2e071cfa#diff-7d3a92ac5e6165548bf9bc556f4f887aR232
wrong escaping

**Comment by MohammedKaludi** [comment]
this is not the correct fix.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5698afe9d16c64ab2c101caefaebd9871a0c6708#diff-7d3a92ac5e6165548bf9bc556f4f887aR226

**Comment by MohammedKaludi** [comment]
Still not the correct fix.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8fb7e02e0891c0f0329d003d77ab4578d4365e88#diff-7d3a92ac5e6165548bf9bc556f4f887aR229

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
