### ISSUE TITLE
Need to update Sabberworm/CSS folder.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4012]
Desc: Need to fix Fatal Error: Uncaught Error: Call to undefined function Sabberworm\CSS\Parsing\iconv()  and update Sabberworm/CSS folder

line number: https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/includes/vendor/css-parser/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parsing/ParserState.php#L93

fatal error Fix : 
```
if(function_exists('iconv')){
        return iconv('utf-32le', $this->sCharset, $sUtf32);
      }else{
        return $sUtf32;
      }
```

Ref: https://secure.helpscout.net/conversation/1023686457/100927?folderId=3243584
https://www.quality-control-plan.com/shop/amp/

The issue has already fixed at the user End.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
