### ISSUE TITLE
Math formula is not responsive in mobile device

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4013]
When user adding math formula using <amp-mathml> tag then formula is not displaying properly on a mobile device. 
screenshot: https://monosnap.com/file/zcxuZJrnuvDt0TE2TOKCA0zZNtnzig

Ref: https://secure.helpscout.net/conversation/1026105057/101363?folderId=3257665

**Comment by ahmedkaludi** [comment]
ticket moved to: https://github.com/ampproject/amphtml/issues/26167
