### ISSUE TITLE
In AMP page, Other site links should not redirect to /amp pages.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4015]
In AMP pages if the link is from another domain then it should go to the Non-AMP site, not on the AMP site.
the same issue created on the localhost. 
1. created a menu item: https://monosnap.com/file/b4ZtqL7lOB22Aa1xPS3AbnT5YizfeC
2. enabled auto AMP ads in menu URL: https://monosnap.com/file/CKZuYUyxzJpGA5DlIHsqlogBvXvwaV
3. Then menu item "Google" redirecting to google/amp. but it should redirect to www.google.com only.

Ref: https://secure.helpscout.net/conversation/1043141795/104223?folderId=3257665

**Comment by bantikuamr** [comment]
This is not work.

**Comment by Zabi09** [comment]
Fixed in #4016
