### ISSUE TITLE
AMP links Error.

### ISSUE THREAD

**Issue by bantikuamr** [ahmedkaludi/accelerated-mobile-pages#4016]
External links in the amp footer are also going into the amp. How to do them non-amp?

[View this Urls Footer link called "Other Websites"](https://www.bkpkvideo.com/amp) 

#4015 

`<a href="https://bantikumarpks2.blogspot.com/amp/" itemprop="url">Portfolio Site</a><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5149"><a href="https://kabirgod.wordpress.com/amp/" itemprop="url">Kabir GOD</a></li> | <a href="https://bantikumarpks2.blogspot.com/amp/" itemprop="url">Portfolio Site</a><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5149"><a href="https://kabirgod.wordpress.com/amp/" itemprop="url">Kabir GOD</a></li>
-- | --
<a href="https://bantikumarpks2.blogspot.com/amp/" itemprop="url">Portfolio Site</a><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5149"><a href="https://kabirgod.wordpress.com/amp/" itemprop="url">Kabir GOD</a></li>`

**Comment by bantikuamr** [comment]
> External links in the amp footer are also going into the amp. How to do them non-amp?
> 
> [View this Urls Footer link called "Other Websites"](https://www.bkpkvideo.com/amp)
> 
> #4015
> 
> `[Portfolio Site](https://bantikumarpks2.blogspot.com/amp/)
> * [Kabir GOD](https://kabirgod.wordpress.com/amp/)
> [Portfolio Site](https://bantikumarpks2.blogspot.com/amp/)
> * [Kabir GOD](https://kabirgod.wordpress.com/amp/)
> [Portfolio Site](https://bantikumarpks2.blogspot.com/amp/)
> * [Kabir GOD](https://kabirgod.wordpress.com/amp/)
> `

**Comment by MohammedKaludi** [comment]
add condition that if ($url) 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/990ee5a4ee69c73c867f218802671f5d17767e51#diff-6aa5512f7dd8d5ce60fc97b0f340912cR2963

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
