### ISSUE TITLE
Need to enhance infinite scroll option for specific categories. 

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4017]
As per the user's request, we need to add another option to 'infinite scroll' for specific categories.

Ref Ticket: https://secure.helpscout.net/conversation/1043784109/0/?folderId=3126461

**Comment by akashagrjsr** [comment]
one more user-requested for this: https://secure.helpscout.net/conversation/1422902865/180293?folderId=2770545

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.11
