### ISSUE TITLE
New Relic script is getting added in AMP and causing validtion error

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4018]
1. New Relic script is getting added in AMP and causing validation error.

2. Validation errors are occurring only when we are logged off.

3. New Relic has implemented on this site by following this document.

https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian.
https://docs.newrelic.com/docs/agents/php-agent/php-agent-api/newrelic_disable_autorum#requirements

3. Already a work has been done in this ticket for removing it.

https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php#L924

https://secure.helpscout.net/conversation/1034790038/102804?folderId=2632030

**Comment by Zabi09** [comment]
Added the script - https://prnt.sc/qj7479 but it's not working

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.13
