### ISSUE TITLE
CCPA(California Consumer Privacy Act) support in AMP

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4019]
Need to create CCPA(California Consumer Privacy Act) support in AMP pages.

Ref: https://blog.amp.dev/2019/12/20/ccpa-support-in-amp/
https://github.com/ampproject/amphtml/issues/24910

https://secure.helpscout.net/conversation/1043999260/104376?folderId=3257665

**Comment by MelSumner** [comment]
Is there a status update for this issue? Thank you!

**Comment by wpquads** [comment]
@MelSumner we are infact working on this today.

We will be releasing it this week

**Comment by ahmedkaludi** [comment]
@MelSumner we are infact working on this today.

We will be releasing it this week

**Comment by MohammedKaludi** [comment]
Released as an extension: https://ampforwp.com/addons/ccpa-for-amp/

**Comment by jonasborchgrevink** [comment]
Hello @MohammedKaludi, this is not for California, this is for the entire United States. Can you update the plugin accordingly? Thank you.

**Comment by MohammedKaludi** [comment]
The component is built in a way that it will work with entire USA.
