### ISSUE TITLE
Test with divi theme

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#402]
Users are saying previous versions of AMP used to work with divi theme, but are not working from the past few updates.
Test which version was working with divi

ref : https://wordpress.org/support/topic/amp-version-not-showing-category-posts-ads/page/2/#post-8645077

**Comment by khaledMohammed000** [comment]
test 1 - Product Features - PASS
test 2 - Case Study - PASS
test 3 - Sales Page - PASS
test 4 - Our Team - PASS
test 5 - Creative Agency - PASS
test 6 - Contact US - PASS - MAP and Form Removed
test 7 - About Me - PASS
test 8 - About US - PASS
test 9 - Coming Soon - PASS
test 10 - Landing Page - PASS
test 11 - Shop Extended - PASS - Divi could not render 2 short codes even in Normal Page - renders when woocommerce active and carousel not getting added
test 12 - Splash Page - Pass
test 13 - Maintenance Mode - Pass
test 14 - Shop Basic - Pass - requires Woocommerce to pass
test 15 - Blog Standard - Pass - amp carousel missing
test 16 - Project Extended - pass - amp carousel missing 
test 17 - Project Extended 2 - Pass - amp carousel missing
test 18 - Blog Masonry - pass - amp carousel missing
test 19 - Protfolio fullwidth carousel - Pass
test 20 - Protfolio fullwidth Grid - Pass
test 21 - Page dual SIdebars - Pass 
test 22 - Portfolio Grid - Pass
test 23 - portfolio 1 column - Pass
test 24 - Page RIght Sidebar - Pass
test 25 - Page Left SIdebar - Pass
test 26 - Homepage corporate - Pass
test 27 - Homepage Extended - Pass
test 28 - Page Fullwidth - Pass
test 29 - Homepage portfolio - Pass
test 30 - Homepage Company - Pass
test 31 - HOmepage Shop - Pass - if woocommerce on
test 32 - Homepage Basic - Pass

**Comment by khaledMohammed000** [comment]
Commit : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/304bd798dbf7d0d6fc3b4d4eb2222783633ab7dd

**Comment by MohammedKaludi** [comment]
Works Fine for now and I'm closing this ticket
