### ISSUE TITLE
Need to make compatibility with  the LuckyWP Table of Contents plugin

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4020]
https://wordpress.org/plugins/luckywp-table-of-contents/

https://secure.helpscout.net/conversation/1044191121/104396?folderId=2632030

**Comment by MohammedKaludi** [comment]
Already reported on #3817 
and https://ampforwp.com/ideas/luckywp-table-of-content/
