### ISSUE TITLE
Undefined variable block_css

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4021]
User getting this issue : [28-Dec-2019 13:37:10 UTC] PHP Notice: Undefined variable: block_css in /var/www/html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 7387

Reference : https://wordpress.org/support/topic/undefined-variable-block_css/

**Comment by MohammedKaludi** [comment]
Ready to push,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.6
