### ISSUE TITLE
When Featured Image from The Content is turned on,the image is not displayed when Creating post from Gutenberg.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4022]
Ref:- https://secure.helpscout.net/conversation/1043936712/104361?folderId=3243584

In this case, the user is using a newspaper theme with D3.
On localhost this feature is not working with swift and design3.

**Comment by Zabi09** [comment]
Working fine but its align to left - https://prnt.sc/qj797g Will you please check that

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.10
