### ISSUE TITLE
The pages in AMP are disfigured on my site

### ISSUE THREAD

**Issue by popcyber** [ahmedkaludi/accelerated-mobile-pages#4025]
Hello, how are you? I use the Diginex theme in Wordpress but the pages are all unconfigured by the plugin, I contacted the developers and they told us that the theme supports AMP.

What would be the problem with this layout deconfiguration?

https://www.portalpopcyber.com/amp/

**Comment by ahmedkaludi** [comment]
GitHub is for the AMPforWP core issues, we would love to help you with this issue but you have to contact us via https://AMPforWP.com/support
