### ISSUE TITLE
Getting error at home page when push notification option is enabled.

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/accelerated-mobile-pages#4026]
REF:https://secure.helpscout.net/conversation/1036544004/103081?folderId=3008055

Error: The extension 'amp-web-push' was found on this page, but is unused. Please remove this extension.

Recreated at localhost and at localhost also issue noticed.
Design2>select custom front page>Enable push notification
https://monosnap.com/file/fnhd52el7yOAblKGzyZg545nyRlTA6

Screenshot:https://monosnap.com/file/3l3RahHxwoMyimVDtlOjaYW55HDdAK

The user did not add script at the head section and then also he is getting for this.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.13
