### ISSUE TITLE
error after 1.0.7

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4029]
Warning
: preg_replace(): Unknown modifier '/' in
/home/newsoncl/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php
on line
7556
What should I do?
https://secure.helpscout.net/conversation/1045755101/104673?folderId=1060554

**Comment by MohammedKaludi** [comment]
pushed in 1.0.8
