### ISSUE TITLE
YOAST SEO Analysis is not working properly with AMP Page Builder.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4030]
Ref: https://secure.helpscout.net/conversation/847834383/65380?folderId=2770545

If the user is using the AMP Page builder and enabled the AMP Takeover then also the YOAST SEO analysis is not getting the content information for the analysis purpose. It's showing the red dot.

Screenshot: https://monosnap.com/file/pmahLf3W3pMctzTSlwZqDefL7ikRDb

**Comment by TMsravan** [comment]
Facing issue when a gravity form is inserted in contact form module of amp page builder along with  Yost when AMP take over the beta option and the Yoast Analysis for AMP PageBuilder is enabled AMP page builder is getting disappear from the view in page edit section.
REf: https://secure.helpscout.net/conversation/1043158689/104227?folderId=2632030

**Comment by MohammedKaludi** [comment]
Avoid using the code `amppb_post_content('')`,  as this has some issues regarding performance.

Please consult wasim in this regards, as he has improved this code.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ec314fcf106538465ddb69f8f0d50f7b95714168#diff-005cc14f54c130b73e541644f5ba12baR132

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
