### ISSUE TITLE
Need to show the same title in AMP and NON AMP Homepage.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4031]
Case: 1

https://secure.helpscout.net/conversation/1043887165/104351/

See these screenshots:

1.https://monosnap.com/file/LAb6fQjStjvZwt2buIbH7jMNYPHcQT
2.https://monosnap.com/file/ZHSVxwjKW0JM9Mi8dKPh5Wf6vFvN30

Note: Need to add the same title in amp and non-amp, whereas in amp it shows the homepage of the amp, remove this and add title as like non-amp homepage.

**Comment by Zabi09** [comment]
Invalid ticket discussed with @ahmedkaludi bhai and closing it
