### ISSUE TITLE
fallback feature is not working on SVG images

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4033]
The fallback feature is not working on SVG images due to that we are getting validation error.
Reference: https://wordpress.org/support/topic/missing-url-for-attribute-src-in-tag-amp-img-7/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.9
