### ISSUE TITLE
After enable the Tree shaking feature the CSS not loading properly

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4034]
Ref: https://secure.helpscout.net/conversation/1029628579/101984/

If the user enables the Tree shaking feature then the CSS on some of your pages not loading properly. The issue is strange and occurs only for one user end and it is not happening every time.

**Comment by ahmedkaludi** [comment]
https://wordpress.org/support/topic/related-posts-82/#post-12289172
![image](https://user-images.githubusercontent.com/16532359/71763002-ce89e000-2efc-11ea-8ef4-aa22427cb473.png)

**Comment by ahmedkaludi** [comment]
![image](https://user-images.githubusercontent.com/16532359/71763015-f6794380-2efc-11ea-8111-2fe68fe118c7.png)

**Comment by Arihantkankariya09** [comment]
Another issue recreated on the localhost.
Steps to recreate:- 
1. Enable to newspaper theme and directly visit the homepage for AMP. It will show the design3 layout.
2. Clear cache from Optimize CSS and visit the page now it is perfect.
3. Do the vice versa, deactivate the newspaper theme and visit the Homepage design3 display is odd.
4. Clear cache and visit now the design3 layout is perfect.

**Comment by sardarui** [comment]
Another user reporting the same, having a style sheet exceed issue and tried all options in performance.

Note: User using the 'newspaper theme'.

Ref-Ticket: https://secure.helpscout.net/conversation/1048456451/105168?folderId=3126461

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.9
