### ISSUE TITLE
Set the priority to high of the icomoon CSS to override every other CSS,in AMP page builder.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4035]
Ref:- https://secure.helpscout.net/conversation/1046669277/104818?folderId=3243584

User's end:- In AMP page builder the blurb and icon module was not loading the icons due to the theme CSS was overriding.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
