### ISSUE TITLE
Audio alignment is not working on AMP

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4037]
Audio alignment(center) is not Working on AMP.
The audio blog width is not working properly.
Audio Caption is not showing on AMP

Reference: https://wordpress.org/support/topic/audio-and-image-caption-not-below-respective-files/

**Comment by Zabi09** [comment]
Fixed in #4038

**Comment by MohammedKaludi** [comment]
will be fixed in #4038
