### ISSUE TITLE
Image alignment and Name is not showing AMP

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4038]
Image alignment(center) is not working properly.
The image name is not showing AMP.

Reference: https://wordpress.org/support/topic/audio-and-image-caption-not-below-respective-files/

**Comment by sonaliramteke** [comment]
It is not working in design 1

**Comment by MohammedKaludi** [comment]
@sonaliramteke 
While testing this ticket, need to make sure that the current fix is working for this issue as well -> **Audio alignment is not working on AMP #4037**

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
