### ISSUE TITLE
Need to allow the users to use internal links if users embedding it through oEmbed

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4039]
Ref: https://secure.helpscout.net/conversation/1018805340/100085?folderId=2770545

If users are embedding the content through the oEmbed and if he wants to use the internal links in AMP, then it's giving an error in console. So, we need to allow the links to be open in AMP as well.

Screenshot: https://monosnap.com/file/cyKWAbDbwLciXBpLi7wdpBI1R4tsTA

**Comment by WasimM3** [comment]
One more scenario for this https://www.vapeowave.co.za/product/vaporesso-swag-2-starter-kit-80w/amp/
