### ISSUE TITLE
Scripts are not adding properly if user is adding the content through embed

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4040]
If the user is adding the youtube video for the embed then for some products it is not adding and it's giving the validation error of the iframe.

Screenshot: https://monosnap.com/file/oDFOa0FjU50UauknllE1Oaiivj1Vy5

If we add the script in advance setting even after it is showing the same validation error.

Ref: https://secure.helpscout.net/conversation/1018805340/100085?folderId=2770545

**Comment by syedimran22** [comment]
Another user amp-anim script is not loading even though amp-anim tag is present. 
https://delhidarshan.com/product/delhi-deluxe-hotels

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.10
