### ISSUE TITLE
easytoc-icon.png

### ISSUE THREAD

**Issue by andrei-long** [ahmedkaludi/accelerated-mobile-pages#4041]
getting an 404 status from wp-content/plugins/accelerated-mobile-pages/images/easytoc-icon.png

**Comment by ahmedkaludi** [comment]
I’ll move this to Eazy TOC issue tracker, and we will make sure it’s fixed in upcoming update

**Comment by MohammedKaludi** [comment]
First-of-all this issue should not come, @Zabi09 You have to keep this in mind while adding items in the list you need to make sure all the links/images/assets are properly added. If any thing is not present then add a fallback for it.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
