### ISSUE TITLE
Matomo (Piwik) Analytics generating errors in Console.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4042]
https://monosnap.com/file/EH0ZygbpkXYXhFyxoXqRGK4t0emjGh

accelerated-mobile-pages\includes\features\analytics\analytics-functions.php
Code line :- 114-116

**Comment by Arihantkankariya09** [comment]
Change the Piwik test base URL to live URL in amp-analytics JSON format.

**Comment by sonaliramteke** [comment]
Errors in Console - https://monosnap.com/direct/IXtmZb4XhCNhPxODDgnVQIWFO5q4JE 
will you please check once.

**Comment by MohammedKaludi** [comment]
escaping missing:

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/641cfede63f4bfaf509277b20a7542d2eca0b056

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b11fbbd0f9f85cfaf29f7f874595da84b67aa9b5#diff-b27b16759fae0fb0d94cc6e00107c8efR113 

if escaped above then add note that `//  XXS ok, escaped above` 

Something like this: https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/9f5c9c6e6ee13e2b2b9aca5e899a9714509a38c7/components/search/search.php#L32

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.13
