### ISSUE TITLE
Facebook like icon is not showing correctly in AMP version

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4043]
Screenshot: https://monosnap.com/file/9paO4BoN70BeymHq6QFH1JNB6Iqy5Z
Screenshot: https://monosnap.com/file/DyrzcMYOhXykMjKlVTGMwRBNFstQcJ

Ref: https://secure.helpscout.net/conversation/1046703573/104827?folderId=2770545

Facebook like icon is not showing correctly in the AMP version. We need to improve some CSS code for this.

URL: https://fossbytes.com/tesla-model-3-1000-km-challenge-10-hours-blistering-cold/amp/

**Comment by akashagrjsr** [comment]
One more user having the same issue: https://secure.helpscout.net/conversation/1047421806/104936/

**Comment by Zabi09** [comment]
Unable to recreate in local and also looks like fixed in users end. So closing the ticket
