### ISSUE TITLE
Need to sanitize amp-mowplayer tag when added in the content.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4044]
Need to sanitize amp-mowplayer tag when added in the content.
Ref: https://secure.helpscout.net/conversation/1047271486/104911?folderId=2322651

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
