### ISSUE TITLE
Calculated fields form plugin is generating validation error on AMP pages.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4047]
Missing URL for attribute 'src' in tag 'amp-img'.

Ref;-https://secure.helpscout.net/conversation/1049505523/105584?folderId=1060556

**Comment by Arihantkankariya09** [comment]
Another user facing the issue with this plugin.
Ref:- https://secure.helpscout.net/conversation/1050139062/105694?folderId=3243584

**Comment by Zabi09** [comment]
Fixed in - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4033
