### ISSUE TITLE
Make the chat bubble into a email box for faster input

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#405]
Create a System Info Area from where there will be the list of all the active - inactive plugins and other useful information from which we can debug.

Example : http://take.ms/Xmn0y

**Comment by MARQAS** [comment]
Waiting for the reply from Helpscout team.

**Comment by MARQAS** [comment]
https://secure.helpscout.net/conversation/699687475/39294?folderId=2206768

**Comment by ahmedkaludi** [comment]
- [ ] Debug errors fixed for this ticket: in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2654

**Comment by MARQAS** [comment]
#2980

**Comment by pegazee** [comment]
Need some proper styling.
Screenshot: https://take.ms/MLVXk

@wasimmagazine3 please discuss this ticket with @RajuJeelaga

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.98.12
