### ISSUE TITLE
Table heading style is not working properly

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4050]
The table heading style is not working properly.
Reference: https://wordpress.org/support/topic/table-header-without-box/
                  https://monosnap.com/file/AgZAy3r8WShGDYEnfNcoQqeGJA8saQ

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
