### ISSUE TITLE
Picture-tag is not working in AMP

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4051]
Fetching validation error '' The parent tag of tag 'picture > source' must be 'picture'. '' when the user using picture tag.

Recreating issue:
1) Add picture tag related script in custom HTML

Example code: 
https://www.w3schools.com/tags/tag_picture.asp

2) Now open your AMP site 'picture tag' won't work and validation errors will occur.

Reference Ticket: https://secure.helpscout.net/conversation/1048969248/105269?folderId=3126461

Ref URL: https://www.7upsports.com/football/2019/08/25/fc-utrecht-vs-vvv-venlo-live-streaming-kick-off-prediction-preview-and-more/amp/

Non-AMP images screenshot: https://monosnap.com/file/knHP4OHb9f6PgmPWVNkT65mOW4LwFx

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f51046b0f15785ad94675a93d9f875a69ab35ea9#diff-54dac7dab9dd460d137d86d279822cc5R13
this line will conflict with other `source` tags. for example https://amp.dev/documentation/components/amp-video/ this amp-video tag also contains source tags. 
make it unique replacement for pictures.

**Comment by nisiwi** [comment]
Please bear in mind that the <picture> tag method is only supported on a few modern browsers.

To support others you need some additional JS for fallback like this > 
https://scottjehl.github.io/picturefill.

The only complete solution is to replace the image source with an image CDN to determine if webp should be served like OptiMole or Shortpixel CDN service.

**Comment by Arihantkankariya09** [comment]
Ref:- https://secure.helpscout.net/conversation/1059285657/107143/
User is getting validation error 
The parent tag of tag 'picture > source' is 'a', but it can only be 'picture'.

**Comment by ajeetku** [comment]
current solution will not work with https://prnt.sc/qtb5xw scenario, because there is no amp-img tag.
for this issue, preg_replace is not a proper solution.

**Comment by akashagrjsr** [comment]
https://secure.helpscout.net/conversation/1064357962/107982?folderId=2770545

In the alt attribute, the image is missing. It showing empty.

**Comment by MohammedKaludi** [comment]
@nisiwi 

Yes, we understand that picture tag is a bit tricky and it the fix can only handled by code improvements either in `amp-img` or crate a new tag called `amp-picture` like `amp-amin` to handle the gif.

But in the old method we were removing the image, that is not the correct solution, instead we are picking the first image in the picture tag and showing it.

Once there is some improvements in handling the picture tag from AMP team then we will improve our code as well.

**Comment by MohammedKaludi** [comment]
1. Code placement is incorrect. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7fea671033171ebc2154239819c516185aec012b#diff-54dac7dab9dd460d137d86d279822cc5L7

2. Pre_replace has incorrect regex not working with this type of picture tags.


`<picture>`
 ` <source media="(min-width: 650px)" srcset="https://www.w3schools.com/tags/img_pink_flowers.jpg">`
`  <source media="(min-width: 465px)" srcset="https://www.w3schools.com/tags/img_white_flower.jpg">`
`  <img src="https://www.w3schools.com/tags/img_orange_flowers.jpg" alt="Flowers" style="width:auto;">`
</picture>`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.27 update.
