### ISSUE TITLE
The "for" attribute is removing in AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4054]
The user wants to add accordion in AMP.

There are two scenarios:
1. In local if we enable the AMP Page builder compatibility plugin then the accordion icon is showing as well as the accordion code is loading but the for the attribute is missing in AMP. Due to which accordion is not working.

2. In the second scenario if we deactivate the AMP Page builder compatibility plugin then the accordion is not loading. 

For the testing purpose, I have added HTML code in the txt file in the attachment. Please find it.

[accordiontest.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4040688/accordiontest.txt)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
