### ISSUE TITLE
AMP take over is not working on home page when user have no posts.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4056]
AMP HTML is not generating on the homepage when the user has no posts on his site.

Note: Checked in localhost and it is occurring at my end.

Ref Ticket: https://secure.helpscout.net/conversation/1046855636/104848?folderId=3126461

**Comment by MohammedKaludi** [comment]
Warning on custom frontpage: https://take.ms/OOJ19

Otherwise working fine.

**Comment by MohammedKaludi** [comment]
condition improvement required: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e6f56a3b59cc1fb5394f2751aa68dbbd958cb893#diff-04b38a94ddf918855eed7a68ecaa512dR1092

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.17
