### ISSUE TITLE
In amp-pixel script adding automatically.

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4057]
In amp-pixel script adding automatically. 
Reference: https://wordpress.org/support/topic/the-amp-pixel-latest-js-custom-script-appears-after-updating-to-1-0-8/
https://amp.dev/documentation/components/amp-pixel/

**Comment by MohammedKaludi** [comment]
more code improvement required.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.11
