### ISSUE TITLE
GTM tags are not working in the updated version 1.0.9 but Google Analytics is working,Also in version 1.0.0 both are working fine

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4059]
GTM tags are not working in the updated version 1.0.9 but Google Analytics is working, also in version 1.0.0 both are working fine.

when GTM is enabled code should load in the format as per this document:

https://support.google.com/tagmanager/answer/9205783?hl=en

When Google Analytics is enabled code should load in the format as per this document:

https://developers.google.com/analytics/devguides/collection/amp-analytics

https://secure.helpscout.net/conversation/1043095360/104214?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Need to re-review the whole thing.

**Comment by MohammedKaludi** [comment]
Working properly, will reopen if issue arise.
