### ISSUE TITLE
Debug Errors in Customizer

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#406]
https://camo.githubusercontent.com/37b46df963a784306309c7eb46f02d23901d173b/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f35306632643732333263343534666136623765363764626132316564323965372e706e67

Previosly reported in #246

**Comment by khaledMohammed000** [comment]
Issue are there even in standard AMP plugin in this section
http://take.ms/YGWPr

**Comment by ahmedkaludi** [comment]
Same as #248 - closed
