### ISSUE TITLE
Need to improve the CSS loading condition on Woocommerce pages mainly for header and footer elements.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4060]
Desc: Need to improve the CSS loading condition on Woocommerce pages mainly for header and footer elements.

**Comment by sonaliramteke** [comment]
In Design 3 alignment issue -> https://prnt.sc/qnikah

**Comment by sonaliramteke** [comment]
In Design 3 alignment issue -> https://prnt.sc/qozduz
This ticket discussed with Ahmed sir and now Imran is working on this ticket.

**Comment by ahmedkaludi** [comment]
Not relevant anymore
