### ISSUE TITLE
Scripts added from Options panel should have higher priority

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4064]
Scripts added from Options panel -> Advanced-> Enter HTML in Head (https://take.ms/B4v5v)

Should load first instead of default ones as discussed with @WasimM3 

So anyone can overwrite the scripts according to their usecase.

**NOTE:** amp-form is loading every time, not throwing any error, but need to test why it is happening and it should be removed if the component is not present in the DOM.

**Comment by MohammedKaludi** [comment]
Fixed in this commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/860004893720a2a831dd297e5d7805c5742314c6

Issue fixed in #4067  and will be pushed in 1.0.15

**Comment by Rkroy** [comment]
If the code is ready to be pushed, then please inform the user.
https://secure.helpscout.net/conversation/1070083740/108854?folderId=673457

**Comment by MohammedKaludi** [comment]
not working with different type of scripts, check with this 

[redux_options_redux_builder_amp_backup_06-02-2020.json.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4164711/redux_options_redux_builder_amp_backup_06-02-2020.json.zip)

**Comment by Rkroy** [comment]
Please test this code using Ads for WP plugin, add auto-ads and normal AdSense ads and check if the auto-ad script is loading properly or not.

**Comment by MohammedKaludi** [comment]
alternative check required if the script is not found.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/507a7226c3dfbbdd2fc8c1e3d5bd46dfbed07c51#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7698

**Comment by MohammedKaludi** [comment]
Make sure `if($comp=='state'){`  is added above `if($is_script==false){` while merging.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1b014dfdcfbb2b34f8b134cf7450c7843a03205f#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7733-R7735

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.28
