### ISSUE TITLE
When AMP is disabled on pages,give an option of hide/unhide AMP on Blog page when in edit mode.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4066]
Ref:- https://secure.helpscout.net/conversation/1050841031/105798?folderId=3243584

https://monosnap.com/file/oMkFCpy2qP8n6R4VUPHFBvjhEw3K2C
https://monosnap.com/file/DIUIPwhD3heBdwNkqhaM1VpBZ5lgyz

**Comment by MohammedKaludi** [comment]
add escaping on both the places.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/72cb0cf70e009a22ade8e2b4659cff620142fb7f#diff-6aa5512f7dd8d5ce60fc97b0f340912cR706

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
