### ISSUE TITLE
Detect Component and add or remove script accordingly

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4067]
Detect AMP based Components and add or remove script accordingly

Continue of this ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4057

**Comment by MohammedKaludi** [comment]
Need to improve the regex so it can work with "<script async custom-element="amp-script" src="https://cdn.ampproject.org/v0/amp-script-0.1.js"></script>" this type of scripts.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4e020b333deaa3790f00186e62f60d6c17b3865b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7669

**Comment by MohammedKaludi** [comment]
One usecase is pending.

**Comment by sonaliramteke** [comment]
If the amp-pixel tag is added then it is automatically adding the script of amp-pixel and due to that validation error is coming.

**Comment by MohammedKaludi** [comment]
Need to re-review the whole process.

**Comment by MohammedKaludi** [comment]
@WasimM3  

script added in this format is not able to detect while sanitizing.

`<script async custom-element="amp-auto-ads"`
`src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js"`
`</script>`

**Comment by Zabi09** [comment]
Added the script in Enter HTML in Head but it's not working and showing a blank screen, Will you please check once

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.15
