### ISSUE TITLE
Need to remove the default AMP functionality from the User's theme as it is breaking the layout.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4068]
By default, the user is using the 'Diginex' theme and in this theme, there is a default AMP script and functions due to this it is conflicting with our script causing layout destruction.

Coming to the main issue, we need to remove the default AMP script from the user's theme. 

Note: The issue is created in the localhost.

Steps to recreate the issue: 

1) Download the theme from user and install it in our localhost.
2) In the localhost except 'design one' theme, you can fetch the issue in all other designs.

Screenshot of the issue:
https://monosnap.com/file/Z0cxmG9O1S2FTHmxHi8IvNA1Qox2GJ

Ref Ticket:
https://secure.helpscout.net/conversation/1045979330/104709/

**Comment by MohammedKaludi** [comment]
add function_exists to make sure this only runs when function is enabled.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ed70ffd27fc0868d5c74ed70b076b03e5c027426#diff-1301281de287d2aed98746fc9ba777b4R42

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
