### ISSUE TITLE
If treeshaking is enabled then " Content sneak to peek " button is showing below the content.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4069]
Case:I

https://secure.helpscout.net/conversation/1053876646/106288?folderId=2770543

Recreate in local:
See this video clip: https://monosnap.com/direct/SBUI1KbAm9vImhydILQ08iL672uL8o

Note:" Content sneak to peek button "showing when clicking on the Show Full Article button, actually, it hides dynamically. this behavior is happened due to when tree shaking is enabled.

**Comment by MohammedKaludi** [comment]
Hover effect on the button is required: https://take.ms/CYMMp

**Comment by MohammedKaludi** [comment]
just this code was required  ` .fd-b-c .fd-b:hover{cursor:pointer;}`

Not the whole option. 

Please remove the color option created.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.17
