### ISSUE TITLE
Social icons and Menu Icon not working on Google Cached Amp version in Amp layout

### ISSUE THREAD

**Issue by Omnitos** [ahmedkaludi/accelerated-mobile-pages#4071]
I am facing this issue since 2 weeks IN SWIFT ICONS amp layout, **earlier it was working fine**, I have not made any changes. Even after reading some threads of yours enabled CORS, still no effect.
**I DO NOT WANT TO USE FONT AWESOME** it reduces speed.
Please do look into the issue, only Google CDN URLs are facing this issue. Please help.
See ss below:
https://prnt.sc/qn0xnh
Site: [https://omnitos.com](url)

**Comment by MohammedKaludi** [comment]
this is strange, can  you please revert back to version 1.0.9 and test if the issue is persisting or not?

**Comment by Omnitos** [comment]
Still, the problem persists

**Comment by MohammedKaludi** [comment]
Use font awesome until AMP provides a solution to handle this.
