### ISSUE TITLE
Warring in console : [DOM] Found 2 elements with non-unique id #s / #amp-search-submit

### ISSUE THREAD

**Issue by samuelmarkno** [ahmedkaludi/accelerated-mobile-pages#4073]
Console elements elements with non-unique id not yet resolved.

Screenshot: https://prnt.sc/qnni05

**Comment by MohammedKaludi** [comment]
@samuelmarkno  Thank you for creating the ticket.

This will be fixed in this ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3946
