### ISSUE TITLE
Pages won't save apostophies in AMP page builder text module.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4074]
Reference :https://secure.helpscout.net/conversation/1055976272/106630?folderId=3514643

Issue was recreated on my localhost.
Steps to recreate:
1. Create a page using AMP page builder
2. Import the swift layout.
3. Modify text module with the keyword "can't", "don't" and "won't" .

**Comment by MohammedKaludi** [comment]
Why we were removing the apostrophes at the first place?
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/23e5609be22aea3c1014fcc23ecd3943b2edcf3d#diff-45752acf5e8ea05d2224fa9a73c54c7aL589

**Comment by MohammedKaludi** [comment]
Do let me know while merging.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.20
