### ISSUE TITLE
When categories that we exclude from AMP through the plugin configuration present redirection problem along with mobile redirection option

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4075]
When categories that we exclude from AMP through hiding AMP bulk tool option, and when mobile redirection option is enabled, those category posts are opened in mobile  then we will get an error as ERR_TOO_MANY_REDIRECTS, Ref: https://monosnap.com/file/3tMNEJCwl3CLTBcq8UcGY5zTqLojBQ

https://secure.helpscout.net/conversation/1056028624/106637?folderId=2632030

**Comment by ajeetku** [comment]
Add here is_object in $post to avoid notice on archive pages
 https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7a606dce60dc5f6370d17d085f6f18283e827218#diff-ab576767b896423d184ddafe2ede2310R16

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
