### ISSUE TITLE
WP Admin toolbar CSS is not loading when user is logged in

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4076]
Ref: https://secure.helpscout.net/conversation/947653087/80315?folderId=2770545

The issue is occurring in my local as well.

Screenshot: https://monosnap.com/file/1vszi7DQ2HfuV8ZFLHyG12NSdu80uu

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
