### ISSUE TITLE
Need to filter that user can edit breadcrumbs

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4077]
Need to filter that user can edit breadcrumbs URL or text.
Reference: https://wordpress.org/support/topic/edit-first-breadcrumb-url/

**Comment by MohammedKaludi** [comment]
What about changing the text?

**Comment by Zabi09** [comment]
To modify the first amp breadcrumb you can use this filter - "ampforwp_breadcrumbs_home_url" and if you want to change the text then you can do it from translation panel of AMP settings panel - https://prnt.sc/qyysvg

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.24
