### ISSUE TITLE
The tag 'template' requires including the 'amp-mustache' extension JavaScript.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4079]
Ref:- https://secure.helpscout.net/conversation/1057338960/106856?folderId=3243584
Only occurring on the category and archives.

https://monosnap.com/file/lHjTxAdiTXGHGswP92zKBhMonwcXE3

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.16 update.
