### ISSUE TITLE
Loop(redirection){Unable to comment}

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#408]
pages are getting redirected from normal to amp and amp to normal in loops which makes them unable to comment if the mobile redirection is ON.

https://wordpress.org/support/topic/several-issues-19/
https://wordpress.org/support/topic/bypass-automatic-redirection-on-mobile/

**Comment by MohammedKaludi** [comment]
Closing this ticket already added in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/415
