### ISSUE TITLE
Events Calendar Page(Months Page) is getting blank when when 'Minify' option is enable under performance tab

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#4080]
Below is the url where the issue was occurring when minify option is enabled which is fixed by modify the code from  
$process = preg_replace(array ('/\>[^\S ]+' . $mod, '/[^\S ]+\<' . $mod, '/\s+/' ), array('> ', ' <', ' '), $process);
to 
$process = preg_replace(array ('/\>[^\S ]+' . $mod, '/[^\S ]+\<' . $mod ), array('> ', ' <' ), $process);
https://setx.events/events/month/?amp

This issue is not getting recreated in localhost.

Reff: https://trello.com/c/3yc3gc0E/1370-event-month-calendar-page-is-blank-in-amp-version

**Comment by MohammedKaludi** [comment]
Are you sure this is the correct fix?

I think that there is some issues in the code.

**Comment by MohammedKaludi** [comment]
Add the filter instead of the code, as this can break alot of sites.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.24
