### ISSUE TITLE
AMP version of single page has timeout

### ISSUE THREAD

**Issue by eboye** [ahmedkaludi/accelerated-mobile-pages#4082]
I'm not sure what the issue is, I'm out of options to find out what is causing the slowdown (timeout) on singles.

Few updates back (I think a week back) it started this. Has anything changed in single templates or it's generation?

Here's the example link that is having timeout. But almost every single has timeout now.

https://srbodroid.com/recenzije/aplikacije/google-files-go-ukratko/amp/

**Comment by eboye** [comment]
I've found that it breaks at [this line](https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/components/components-core.php#L534).

Actually amp_content in single.php in swift theme call that and it can't get the post ID for some reason.

**Comment by MohammedKaludi** [comment]
This is strange, is it happening with all the pages/posts or few pages ?

**Comment by eboye** [comment]
@MohammedKaludi almost all posts ... pages, categories etc. are not affected

**Comment by MohammedKaludi** [comment]
the post says "Connection Timeout"? also how many number of posts you have in your blog?

**Comment by MohammedKaludi** [comment]
Hi @eboye 

Thank you very much for raising the ticket and I have checked call for `get_queried_object_id ()` function and improved the code.

I'm attaching the modified version of **components-core.php** file with this reply.

Can you please overwrite the attached file with the one you have in your system and test if we are able to resolve it or not?

File:  [components-core.php.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4080284/components-core.php.zip)

Please use FTP or Cpanel to overwrite the file and please have backup of your files so it can be reverted at any time. 

Please do let me know the results of it.

Thanks.

**Comment by eboye** [comment]
@MohammedKaludi I see what you did there. I've tried it myself and still no go. I've tried replacing your modification but it still gives timeout.

I've got more then 2500 posts.

**Comment by MohammedKaludi** [comment]
Then the issue might not be related to queried object function,  can you share more details which other plugins you use with AMPforWP? 

And could you please share the screenshot of the issue?

**Comment by eboye** [comment]
I've done some tweaking with the theme (not AMP related). Removed some slow queries etc. And it seems that some of the singles are loading as they should. But some are still painfully slow like this one:
https://youtu.be/9jVJskGD1WM

Few more seconds and CloudFlare would throw timeout error.

These plugins are installed, too many for my taste, but it's an old blog with lot's of old dependacies:

1. Accelerated Mobile Pages
2. Admin Commenters Comments Count
3. Ads.txt Manager
4. Akismet Anti-Spam
5. AMPforWP Plugin Manager
6. Autoptimize
7. Broken Link Checker
8. Cache Enabler
9. Classic Editor
10. Contact Form 7
11. Google XML Sitemaps
12. instant.page
13. Multipage
14. Preconnect
15. Query Monitor (for now, just for testing)
16. Simple Image Sizes
17. Thank You Counter Button
18. UpdraftPlus - Backup/Restore
19. Virtual Robots.txt
20. Wordfence Security
21. WP Featherlight
22. WP-Appbox
23. WP-Polls

Now that I have this new behavior. I'm thinking maybe it's the oembed (twitter, yt etc.) for the items that are deleted at the 3rd party end.

**Comment by MohammedKaludi** [comment]
As you are using AMPforWP plugin manager.

Can you please deactivate the following plugins in AMP mode (for testing purpose) so we can test if any of these plugins creating any issue in AMP.

Admin Commenters Comments Count
Ads.txt Manager
Broken Link Checker
instant.page
Multipage
Preconnect
Simple Image Sizes
Thank You Counter Button
UpdraftPlus - Backup/Restore
Virtual Robots.txt
WP Featherlight
WP-Appbox
WP-Polls

Meanwhile i'm looking deep into the code.

**Comment by eboye** [comment]
Hmm, tried to disable everything except:

Accelerated Mobile Pages
Akismet
AMP plugin manager
CF7
Wordfence

and I still have slow loading time on those posts.

I've also tried disabling every single action hook from the theme that alters content to be sure, but still the same.

The funny thing is that everything worked few updates back.

**Comment by MohammedKaludi** [comment]
As you mentioned that it was working before, 

Can you please rollback to old version and test in which version it was working?

You can follow this tutorial for quick way to rollback to older AMP versions. https://ampforwp.com/tutorials/article/how-to-rollback-the-amp-to-an-older-version/

**Comment by MohammedKaludi** [comment]
So I'll check the code difference from that version to current version and ill improve the code in next updates/

**Comment by MohammedKaludi** [comment]
Hey @eboye Any Update on thie?

**Comment by MohammedKaludi** [comment]
Hey @eboye Any Update on this?

**Comment by MohammedKaludi** [comment]
Hey @eboye Any Update on this?

**Comment by eboye** [comment]
@MohammedKaludi sorry for the late reply ... I haven't had time to response nor do anything about this.

But to update you on this. Last update I did today seems to fixed it. It's now loading as fast as before.

I'm not sure if it was WP-AMP or One Signal Update (which I don't use on AMP pages) but it seems it's stable now.

I'll try to downgrade the version to see if was the WP-AMP, but can't promise any ETA ...

**Comment by MohammedKaludi** [comment]
No Problem @eboye I'm glad that as issue has been fixed, I'm closing this ticket for now.

Please  do let us know if you need any other help, or create a new ticket if you find any other issue.

Thanks
