### ISSUE TITLE
Need to make compatibility with the Mediavine plugin

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4083]
https://secure.helpscout.net/conversation/1041900538/103985?folderId=1060556

We need to make compatibility with the Mediavine plugin due to this plugin validation errors are appearing.

Use case1: They have an option amp GDPR concent:

https://monosnap.com/file/zEnJ2NAbVX51iLcciPd6wkfQuT78Aj

When we disable this all validation error will get fixed

They have generated a script: https://monosnap.com/file/HAAEDMOE3PuOBjIq7jcwLXwXFNR8bT
And we also generated the script by finding the tag <amp-geo>: https://monosnap.com/file/DjWFE4Jw6hRp8PjWCxjjG9Qvj2mvRb

2.Second use case:

The tag 'amp-consent' appears more than once in the document.
The tag 'amp-consent extension .json script' appears more than once in the document.

https://monosnap.com/file/NHb5iYZ5AWMARIoltvN84MqUW9Vu5T

.json script' appears twice in the document: This is coming from there plugin itself

https://monosnap.com/file/EHvphSsTt4MhR7DSfDKV3dkw6QArXe

**Comment by Laxmikanth2502** [comment]
another issue with the error

Ref:https://secure.helpscout.net/conversation/1056358484/0/?folderId=3528427

**Comment by MohammedKaludi** [comment]
Breaking `<script src="https://cdn.ampproject.org/v0.js" async></script>` main script file.

**Comment by MohammedKaludi** [comment]
`<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>`

<script src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js" async custom-element="amp-carousel"></script>`

<script async src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js" custom-element="amp-carousel"></script>`

`<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>`


the code should work with all these formats.

Two instances are still loading. https://take.ms/7s0Cg

**Comment by WasimM3** [comment]
This issue is fixed in #4064
