### ISSUE TITLE
Playbuzz is not working 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4085]
Playbuzz is not working in AMP
Reference: https://wordpress.org/support/topic/class-amp-playbuzz-sanitizer-php-is-not-working/

**Comment by MohammedKaludi** [comment]
Why fix not done in PlayBuzz sanitizer file?

Why fixed globally, when we have a dedicated PlayBuzz sanitizer file?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8193790e8fbcc11687811c5159a3ca9f4a3ca395#diff-54dac7dab9dd460d137d86d279822cc5R17

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
