### ISSUE TITLE
video is not displaying in AMP when a video is inserted from gutenberg video module

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4086]
video is not displaying in AMP when a video is inserted from the Gutenberg video module.

Issue recreated in local.

https://secure.helpscout.net/conversation/1053461837/106223?folderId=1060554

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
