### ISSUE TITLE
Your setup is not completed. Please setup for better AMP Experience.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4088]
What am I supposed to do?
![image](https://user-images.githubusercontent.com/16532359/72684744-3b11fb00-3b09-11ea-942d-69865beb0997.png)

**Comment by MohammedKaludi** [comment]
Labeling improvement required.

**Comment by MohammedKaludi** [comment]
1. Checkbox view improvement.
2. Change "Easy Setup View" -> "Basic Setup"
3. Change "Full Options View" -> "Advance Setup"

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
