### ISSUE TITLE
make import/export easier

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4089]

**Comment by MohammedKaludi** [comment]
1. https://take.ms/OK8bn 

2. Styling improvement required.

**Comment by MohammedKaludi** [comment]
escaping missing.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1482c06920b109c6ecbfd40b4dbf3afbafd7eb96#diff-07d23db92e5da724e4e89325b1dec634R113

**Comment by MohammedKaludi** [comment]
escaping still missing `$content` 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/75857780e7c3f13a6f3b7898e9ac93f0a743e114#diff-07d23db92e5da724e4e89325b1dec634R112

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.26
