### ISSUE TITLE
"AMP on Pages = off" not working

### ISSUE THREAD

**Issue by loano** [ahmedkaludi/accelerated-mobile-pages#409]
General Setting -> Front Page -> **Enable or Disable AMP on all Pages = off** does not work. If disabled, still example.com/amp added to front page. Tested locally and online. E.g: http://lustaufeinbier.de/amp

**Comment by loano** [comment]
Temporary solution: Disable "AMP" from Automattic, then enable it again. Result: AMP on Homepage disappears. Only works until I update "Accelerated Mobile Pages", afterwards I have to do the same procedure again.

**Comment by ahmedkaludi** [comment]
@loano We have just pushed an update. Can youPlease check and confirm?

**Comment by loano** [comment]
@ahmedkaludi Just figured that out with the most recent version, 0.9.34

**Comment by loano** [comment]
@ahmedkaludi , unfortunately my trick works one for example.com/amp, it still adds example.com/?amp

**Comment by MohammedKaludi** [comment]
Proper Page On-Off support added

**Comment by loano** [comment]
Hey @MohammedKaludi, even with 0.9.35 it adds example.com/?amp
