### ISSUE TITLE
Code improvements 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4090]
Remove few unnecessary code from the plugin.

for example : https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/f2e8768e6e594d5ed4a214785f61418063f2f9b3/templates/design-manager.php#L238

**Comment by MohammedKaludi** [comment]
Code improvements in components-core.php 
example : `function amp_excerpt( $no_of_words=15 ) {`

**Comment by MohammedKaludi** [comment]
Few more improvements required
1. Files not removed.
2. Duplicate code: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/782d7175b975990cb1892a9976262f07a24c4d2d#diff-6aa5512f7dd8d5ce60fc97b0f340912cL6154

**Comment by Zabi09** [comment]
Need to add escaping in redux-code/framework.php file

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
