### ISSUE TITLE
Performance section all features not working when Ezoic integration plugin is active.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4092]
This creates a stylesheet validation error.
Ref:- https://secure.helpscout.net/conversation/1061154824/107495?folderId=3243584

https://wordpress.org/plugins/ezoic-integration/

When the plugin is deactivated Minify, Treeshaking works.

**Comment by MohammedKaludi** [comment]
add for removal only if class exists.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b846c9023ab9d4be0796d1b951851a7d55d85780

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
