### ISSUE TITLE
Auto Ads not working for the past 6 days

### ISSUE THREAD

**Issue by wedlockideas** [ahmedkaludi/accelerated-mobile-pages#4093]
I raised multiple tickets regarding this issue in your support forums but no proper response yet. Auto ads not working in my website for the past 6 days from Friday I am sending email and posted tickets no response. 

Suddenly auto ads not working on my website. I am already using ads above the header, before the post content & auto ads but now only auto ads not working remaining ads are fine.
Not using ads for wp plugin instead of that using advertisement feature in your plugin.  I tried using ads for wp plugin and disabled ads above the header, before the post content but still auto ads not working. I already shared a login credential to your email id.  Here is the link to my website https://www.wedlockindia.com/paithani-blouse-designs/

**Comment by ahmedkaludi** [comment]
Github is for tried and tested bugs.

Technical Support is provided on the website.
