### ISSUE TITLE
Referenced AMP Url in not an Amp

### ISSUE THREAD

**Issue by sarkariresult526** [ahmedkaludi/accelerated-mobile-pages#4094]
Kindly Resolve my Problem m getting this issue in my website sarkariresultonline.info
My Link-(https://sarkariresultonline.info/rpsc-agriculture-officer/)
Kindly Resolve my Issue

**Comment by ahmedkaludi** [comment]
The page is properly valid https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=uJUKhCfJ9FIQmBAWUilSdg

Also, Github is for tried and tested bugs, Technical support is provided on the website.

**Comment by Techbland** [comment]
I have the same issue, anyone can help me?

**Comment by MohammedKaludi** [comment]
@Techbland can you please share more information on this issue?

**Comment by ahmedkaludi** [comment]
I’m sorry to hear that. GitHub is for recreatable bugs, kindly create a technical team first: https://ampforwp.com/support/
