### ISSUE TITLE
data-block-on-consent is missing for Vuukle comments when gdpr is enabled

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4095]
https://secure.helpscout.net/conversation/1062408668/107732?folderId=2632030

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/782d7175b975990cb1892a9976262f07a24c4d2d#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6198 && https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/782d7175b975990cb1892a9976262f07a24c4d2d#diff-3358181277138e309fc94ee4e552f7feR232

Wrong escaping

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
