### ISSUE TITLE
Search result not looking good.

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4098]
https://take.ms/GVLFX

Why Search result is not looking good in new design.

**Comment by MohammedKaludi** [comment]
Use this options panel if you are not able to recreate the issue.
[redux_options_redux_builder_amp_backup_23-01-2020.json.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4104904/redux_options_redux_builder_amp_backup_23-01-2020.json.zip)

**Comment by Zabi09** [comment]
Unable to recreate the issue and the styling was not coming due to some cache and now it is coming fine so closing this one.

**Comment by MohammedKaludi** [comment]
Archive pages.

https://take.ms/8B2bJ
