### ISSUE TITLE
Remove Purge AMP CDN cache Settings buuton:

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4099]
Remove the Purge AMP CDN cache Settings button from the core. 
Shows error "Sorry, you are not allowed to access this page." when clicking on Settings

https://secure.helpscout.net/conversation/1057517486/106883?folderId=3514643

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
