### ISSUE TITLE
AMP-carousel Issue

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#410]
Steps to create : 
1. Install and Activate amp-woocommerce
2. dont use any features from woocommerce
3. simply view posts and you can see the warning

Solution : 
1. the addition of this amp-carousel-extension.js file should only be added when there is actually a carousel being added....changes to be made in Plugin : AMP WooCommerce

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/amp-woocommerce #7](https://github.com/ahmedkaludi/amp-woocommerce/issues/7) via [**ZenHub**](https://www.zenhub.com/)
