### ISSUE TITLE
Alignment issue in GDPR Privacy link.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4101]
Case:1 https://secure.helpscout.net/conversation/1058578585/107041?folderId=1060556

Note: Alignment issue in amp consent.css file need to change position: fixed to position: relative;
Actually, privacy link load below the footer section but its loading header section 

 See this video clip: https://monosnap.com/direct/pmpP4lKw7dZ7DseoKehJmXEz20bGWU

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.19
