### ISSUE TITLE
Allow users to change the name of the endpoint.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4104]
Users want to show the URL like this: "test.bondevalue.com/m" or "/mobile", instead of "/?amp"

Ref: https://secure.helpscout.net/conversation/1064322035/107980?folderId=3257665

**Comment by MohammedKaludi** [comment]
can be done via this extension: https://ampforwp.com/addons/subdomain-endpoints-for-amp/
