### ISSUE TITLE
Number of Days to be added while for prior renewals

### ISSUE THREAD

**Issue by ajeetku** [ahmedkaludi/accelerated-mobile-pages#4105]
Need to have a Refresh button next to the expiring days in the Plugin's extension section
https://trello.com/c/62kSBoh2/145-number-of-days-to-be-added-while-for-prior-renewals

**Comment by sonaliramteke** [comment]
These changes are required in this ticket
1. Remove this text - >https://prnt.sc/r0oonc
2.  Once we click on this refresh Icon it should be refresh like this ->https://media2.giphy.com/media/ywDxXjUlln3qM/source.gif
3. Space is required - https://prnt.sc/r0ovza

**Comment by ajeetku** [comment]
Need to add 2 things:
1) if license is expired, then refresh will always go to server and check the status{Make sure at one time only one call}
2) if license is not expired refresh will call once in 24 hr

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
