### ISSUE TITLE
When Insert post ads plugin is enable then AMP settings panel is not showing.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4107]
When Insert post ads (http://insertpostads.com/) plugin is enabled then the AMP setting panel is not working. it's showing blank only.

Ref: https://secure.helpscout.net/conversation/1066344650/108272?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.22
