### ISSUE TITLE
Analytics ID is not loading the source code for the GTM

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4108]
- [ ] If the user is adding the Analytics ID after enabling the GTM then also it's not loading in the source code.
Screenshot: https://monosnap.com/file/sWLBsV2gaFfRejwiCNdQoF1TBxUUd0

- [ ] If the user has set up the GTM then also it's showing the config. 
Screenshot: https://monosnap.com/file/4S5eB0U2zLxM5OedAnOFpFVGJ6u7Ce

Ref: https://secure.helpscout.net/conversation/1024067281/100973?folderId=3528427

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.22
