### ISSUE TITLE
What's function to deactivate lazy load images?

### ISSUE THREAD

**Issue by PedroFumero** [ahmedkaludi/accelerated-mobile-pages#4109]
I want to deactivate lazy load on home page, which is the function name of lazy load?

**Comment by MohammedKaludi** [comment]
Hi @PedroFumero,

You can check below link as we have added the compatibility with various lazy loading plugins and by following the same pattern you can disable Lazy Loading functionality.
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php#L1004

Also, you mentioned that it you only want to deactivate it on "home page" you can use `ampforwp_is_home()` condition.

Please do let me know if you need any thing else from us.

I'm closing this ticket as this is not related to any issue or feature for the plugin. 

But will continue to reply back in this ticket if you have any other question.
