### ISSUE TITLE
Shortcodes working with AMP but not with AMPforWP

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#411]
The gallery part that does not work is
[gallery special_type="1-2" link="file" size="main-content" ids="1106,1109,1108,1107"]

Also: the youtube embed with the shortcode [embedyt][/embedyt] is not working either.
Both things work with the original AMP plugin but not with this plugin activated.
ref: https://wordpress.org/support/topic/gallery-not-showing-14/

**Comment by khaledMohammed000** [comment]
https://wordpress.org/support/topic/wp-gallery-display-error/

**Comment by khaledMohammed000** [comment]
Gallery working: http://take.ms/yWUlG
WP Gallery working : http://take.ms/N3Srw

**Comment by ahmedkaludi** [comment]
We need to test this properly with default and our plugin.

**Comment by ahmedkaludi** [comment]
Its working.
