### ISSUE TITLE
Add the following  schema types : Last reviewed & Reviewed by.

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4110]
ref:https://secure.helpscout.net/conversation/1068220527/108566?folderId=3528427

Last reviewed https://schema.org/lastReviewed
Reviewed by https://schema.org/reviewedBy

**Comment by MohammedKaludi** [comment]
The ticket is related to schema plugin https://github.com/ahmedkaludi/schema-and-structured-data-for-wp
