### ISSUE TITLE
When the tree shaking is enabled then the CSS of the layouts break

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4113]
Ref: https://secure.helpscout.net/conversation/1065302588/108106/

If the user enables the tree shaking in the AMP then the CSS of the layouts breaks. The issue is a rare one and occurs only for the few users.

Screenshot: https://monosnap.com/file/OH0e47awvlYbURH1rj5PzRVnba5xAH

**Comment by ahmedkaludi** [comment]
Many people are facing but we were not able to pin point this, 

Let's use this as a use case.

**Comment by Arihantkankariya09** [comment]
Another user with this issue. Happening only on random posts and pages https://secure.helpscout.net/conversation/1068758860/108664?folderId=3448350

**Comment by MohammedKaludi** [comment]
Make sure `esc_url` is added while merging.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e79554b56792bf2a9a70c6610947d694f75d9a45#diff-54dac7dab9dd460d137d86d279822cc5R374

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
