### ISSUE TITLE
Need to make compatibility with the Better AMP plugin..

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4115]
We need to make compatibility with the "Better AMP" plugin. (https://wordpress.org/plugins/better-amp/)
Ref: https://secure.helpscout.net/conversation/1067400248/108459?folderId=3257665

**Comment by ahmedkaludi** [comment]
This is a wrong ticket, @wankhedekomal please move to the right place
