### ISSUE TITLE
The meta data is not working in Head section

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4116]
Reference: https://wordpress.org/support/topic/meta-data-29/
Screenshot: https://monosnap.com/file/6sxRSyqnOAIueFwfOISpZ6I4Bjc0c1

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.22
