### ISSUE TITLE
Upgrade to Pro option is removing in the setting panel when we activated PWA for WP plugin 

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#4117]
Upgrade to Pro option is removing in the setting panel when we activated PWA for WP plugin.

**Comment by ajeetku** [comment]
Unused code inside plugins list
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/2ed74f1f45772ae59a32c2255f4c3e3cfff40f89/includes/options/admin-config.php#L255

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.22
