### ISSUE TITLE
Option panel FAQ's similar response for different questions.

### ISSUE THREAD

**Issue by HANEEFRIYAZ** [ahmedkaludi/accelerated-mobile-pages#4119]
01. https://monosnap.com/file/FJB0n0zDzgPYr9rQIbc48ecIyjO4JP
02. https://monosnap.com/file/KHC4QSEx3bRYlcKdvxcT4RWltzrb4C

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.22
