### ISSUE TITLE
compatibility with the Smart slider 3 plugin

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4120]
Need to make compatibility with the Smart Slider 3 plugin. (https://wordpress.org/plugins/smart-slider-3/)

Ref: https://secure.helpscout.net/conversation/1065325410/108114?folderId=3257665

**Comment by MohammedKaludi** [comment]
Moved to https://ampforwp.com/compatibility/idea-board/
