### ISSUE TITLE
 change H2 tag to H1 tag

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4121]
Reference: https://wordpress.org/support/topic/how-to-change-h2-tag-to-h1-tag/

**Comment by MohammedKaludi** [comment]
Heading styling is messing up, for d1, d2 and d3

https://take.ms/q5cRm

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.24

**Comment by EugenioParnaso** [comment]
With the update has made any header disappear. It is no longer that the H1 does not appear, but now they lack it.

**Comment by EugenioParnaso** [comment]
We have already seen that you have updated the plugin. Now it works. Thank you.

**Comment by MohammedKaludi** [comment]
Fixed in #4138 and pushed in 1.0.25

**Comment by MohammedKaludi** [comment]
> We have already seen that you have updated the plugin. Now it works. Thank you.

Thank you very much for your feedback,
