### ISSUE TITLE
Need to show extension tab menu in Basic Setup view.

### ISSUE THREAD

**Issue by WasimM3** [ahmedkaludi/accelerated-mobile-pages#4122]
![basic_setup.png](https://images.zenhubusercontent.com/5d481440846989047d3c14a6/f148de5f-82d6-4224-af26-ff7e3108393f)![basic setup.png](https://images.zenhubusercontent.com/5d481440846989047d3c14a6/e7031113-15ae-484d-a34f-ab68d1c40c61)

**Comment by MohammedKaludi** [comment]
escaping required and code improvement required in `$style`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b79dd9e3a7ac9e89f659000183a5c361e23cd744#diff-1a0e52b2651cea85b13d1cbf4f2198b0R3247

**Comment by MohammedKaludi** [comment]
Code improvement required.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/77c8e4ac240c74190a6789c71ce4894a94cdbbfc#diff-1a0e52b2651cea85b13d1cbf4f2198b0R3243

**Comment by MohammedKaludi** [comment]
code improvements

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6e9dbdfc925b36095f5a2f2bb2dfe332089e8e55#diff-1a0e52b2651cea85b13d1cbf4f2198b0L3237

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.26

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.27 update.
