### ISSUE TITLE
'link rel=canonical' appears more than once when using Rank Math

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4124]
Reference: https://wordpress.org/support/topic/link-relcanonical-duplicated-when-using-rank-math/
https://monosnap.com/file/GUFJJRcJGLhN6iVEAHhrp4tmJQKt6j

**Comment by MohammedKaludi** [comment]
typo `dedected` it should be `detected`

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
