### ISSUE TITLE
Iframe error due to Jetpack needs to be fixed.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4125]
Case1) https://secure.helpscout.net/conversation/1056909059/106786?folderId=3514643
AMP users facing a validation issue due to iframe error while logged in on their dashboard. It is not

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
