### ISSUE TITLE
Related posts not working well

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4126]
3 Users have got the same error.
case1: https://wordpress.org/support/topic/related-posts-not-working-well/
cases: https://wordpress.org/support/topic/related-posts-not-display/
cases3: https://wordpress.org/support/topic/related-posts-pt2/

**Comment by Zabi09** [comment]
Unable to recreate the issue, So Closing this ticket
