### ISSUE TITLE
Error coming on AMP setting panel when "Leverage Browser Caching" option is enable.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4127]
- [ ] When the user activates "Leverage Browser Caching" option then the user is getting this errors message (https://monosnap.com/file/01xWJxlIn5HNA2Oi9dDiQZd6Vp3r1i)

- [ ] Need to change the error message. so it will be more understandable to user.

Ref: https://secure.helpscout.net/conversation/1066008977/0/?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.24
