### ISSUE TITLE
Getting fatal along with amp theme frame work with the latest version 1.0.20

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4128]
https://secure.helpscout.net/conversation/1070940476/108971?folderId=1060556

https://monosnap.com/file/8YBxtWEczVNo4WIhe1AbHPeavMlyt0

Warning: Use of undefined constant AMPFORWP_CUSTOM_THEME - assumed 'AMPFORWP_CUSTOM_THEME' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\lc\wp-content\plugins\accelerated-mobile-pages\components\theme-loader.php on line 18

Notice: Undefined variable: amp_main_dir in C:\xampp\htdocs\lc\wp-content\plugins\accelerated-mobile-pages\components\theme-loader.php on line 20

Warning: require_once(/functions.php): failed to open stream: No such file or directory in C:\xampp\htdocs\lc\wp-content\plugins\accelerated-mobile-pages\components\theme-loader.php on line 22

Fatal error: require_once(): Failed opening required '/functions.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\lc\wp-content\plugins\accelerated-mobile-pages\components\theme-loader.php on line 22

[redux_options_redux_builder_amp_backup_01-02-2020 (1).txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4142329/redux_options_redux_builder_amp_backup_01-02-2020.1.txt)

User is using First Pixel theme

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.21
