### ISSUE TITLE
AMP Menu option is not showing in WP settings.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4129]
When the user disabled the AMP menu option in swift theme at first and later user change his theme to Design1,2,3 even the menu option is enabled in those respected themes AMP menu option is not showing in Appearance settings.

Note: The issue is recreating in Localhost.

Please check with the below video to recreate the issue:
https://monosnap.com/file/8pUo9tK1YQmzZ0faHhn0U3sHIMGb8V

Ref Ticket: https://secure.helpscout.net/conversation/1068163690/108559/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.24
