### ISSUE TITLE
Admin bar css is not loaded on amp pages

### ISSUE THREAD

**Issue by jlariza** [ahmedkaludi/accelerated-mobile-pages#4130]
Good day, 

I was testing the plugin using a fresh wordpress installation. However, the admin bar looks badly in the amp version of the pages

![image](https://user-images.githubusercontent.com/16421045/73684719-c3a8a380-4692-11ea-932c-49105ac58689.png)

according to #4076 the issue was fixed in 1.0.19 version but I am using 1.0.20 version and it still looks bad. Am I missing something?

Thank you

**Comment by MohammedKaludi** [comment]
@jlariza This is strange, yes as you mentioned it has been fixed in the previous versions.

Can you please clear the AMP cache once and test it?

If issue still persists then let us know, we will look into it inside the code.

Thanks.

**Comment by jlariza** [comment]
@MohammedKaludi I tried clearing cache and and using `Optimize CSS (beta)` option. The admin bar still looks bad, with or without that option enabled. I checked the css that is being loaded and it seems that the admin bar css is not loaded. Maybe the plugin is removing it somewhere?

**Comment by jlariza** [comment]
@MohammedKaludi I checked the code and this seems to be the line with issues:
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/00b79a4b4f62019114b2bafaa161525fa4bf73f4/templates/features.php#L7309

it seems that `ampforwp_get_remote_content` is not returning the admin css code so it is not added. Checking that line, it seems that method makes an http request to get the css; and for some reason it is no having the expected response.

I replaced that line for `$css = file_get_contents(AMPFORWP_PLUGIN_DIR."/templates/template-mode/admin-bar.css");` and it is working. Reading the file directly instead of using http seems a better approach.

I hope that this would help you to find the source of the issue. Ty

**Comment by MohammedKaludi** [comment]
thanks @jlariza 

Thank you for the explanation and yes, we will look into it and improve the code.

**Comment by MohammedKaludi** [comment]
we cannot use `file_get_contents ()` according to wp.org guidelines.

need to check why `ampforwp_get_remote_content()` is not working.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by WasimM3** [comment]
Need to improve the code ampforwp_head_css->ampforwp_get_remote_content

**Comment by MohammedKaludi** [comment]
Esc_url while merging.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/eb0d99bbcf43637dbf330ca6669dd4a973f4ce44#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7345

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
