### ISSUE TITLE
Featured image is displayed when the AMP page builder is enabled.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4131]
Ref:- https://secure.helpscout.net/conversation/1070839129/108942?folderId=3243584

Screenshot https://monosnap.com/file/ez232130oQfy5OGolNIlNxcJeRyZJV

**Comment by MohammedKaludi** [comment]
Need to discuss this fix

**Comment by MohammedKaludi** [comment]
Ready to merge. 
Also need to notify the user in Helpscout.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.24

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.26
