### ISSUE TITLE
Compatibility with the Jetpack Contact form.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4132]
We need to make compatibility with the Jetpack contact form. 
https://jetpack.com/support/jetpack-blocks/form-block/

Ref: https://secure.helpscout.net/conversation/1054996444/106469?folderId=3257665

**Comment by MohammedKaludi** [comment]
moved to https://ampforwp.com/compatibility/idea-board/
