### ISSUE TITLE
"Twitter Handle" in social sharing field does not need to enter "@"

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4135]
Twitter Handle does not need to enter @, otherwise it turns out to double @@, although the filled field indicates that you need to enter @.
screenshot: https://monosnap.com/file/wah2EsfV0s14wpw0WOsR5HsArBvuHK

Ref: https://secure.helpscout.net/conversation/1073793397/109311/

**Comment by MohammedKaludi** [comment]
Check if `@` is already present or not and then add it if it is not added.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.24
