### ISSUE TITLE
Need to make subscript<sub> or superscript<sup> text support in AMP

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4137]
subscript<sub></sub> and superscript<sup></sup> support in AMP.
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_sup
Ref: https://secure.helpscout.net/conversation/1073749379/109299/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
