### ISSUE TITLE
option "Title on static page front page"  not working for desgin 1, 2 and 3

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4138]
case1) https://secure.helpscout.net/conversation/1066555977/108319?folderId=3514643

Screengrab:  https://monosnap.com/file/6aJI89aePK1zrnD2SNV3S7t8arCWHH

**Comment by sonaliramteke** [comment]
This option "Title on static page front page" is not working in Swift Theme

**Comment by MohammedKaludi** [comment]
Ready to push,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.24

**Comment by MohammedKaludi** [comment]
Fixed and Pushed in 1.0.25
