### ISSUE TITLE
The Save Changes button is not displayed in AMP >> Versión 5.3.2

### ISSUE THREAD

**Issue by jairo1212** [ahmedkaludi/accelerated-mobile-pages#4139]
The free version does not allow me to save the changes because the button disappears.

It appears briefly when I enter but when I add the changes it disappears.

**Comment by MohammedKaludi** [comment]
This is strange, can you please share a screenshot or a small video, so that we could understand the issue. 

Because we have not faced any issue like this.

**Comment by ahmedkaludi** [comment]
@jairo1212 
It's usually due to the browser cache, try to hard refresh and it should be solved.

If not then just write us on https://ampforwp.com/support/ and we will check it out.
