### ISSUE TITLE
When "Sub-Categories under Category" option is enable then links are going to Non-AMP

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4140]
Design —> Misc —> Sub-Categories under Category
If this option is enabled, then links to sub-categories will be Non-AMP.

Ref: https://secure.helpscout.net/conversation/1073791580/109310?folderId=3257665

**Comment by Zabi09** [comment]
We have connected that with Internal links to AMP option #3924
