### ISSUE TITLE
Need to update sabberworm folder.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4142]
desc: Need to update sabberworm folder and delete unnecessary files from "php-css-parser" folder.
also make sure to check function exist for iconv function

**Comment by MohammedKaludi** [comment]
also make sure to check function exist for `iconv` function

This is still pending.

**Comment by WasimM3** [comment]
function exist for `iconv` fucntion is already there

**Comment by WasimM3** [comment]
if(function_exists('iconv')){
        		return iconv('utf-32le', $this->sCharset, $sUtf32);
      		}else{
        		return $sUtf32;
     		}

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
