### ISSUE TITLE
Create a option for  sort home page by post order

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4144]
REF:https://secure.helpscout.net/conversation/1072749425/109169?folderId=3528427

Create an option to sort the home page by post order

Ref plugin Link:https://wordpress.org/plugins/simple-custom-post-order/

**Comment by MohammedKaludi** [comment]
Moved to https://ampforwp.com/compatibility/idea-board/
