### ISSUE TITLE
Getting fatal error form the latest version of AMPforWP plugin along with amp theme framework

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4145]
Getting fatal error form the latest version of AMPforWP plugin:

Scenario: The issue is occurring due to the user has altered the plugin directory path, no the WordPress's usual path.

General WordPress path REf: https://monosnap.com/file/SqUh47byFhlSWNrgMJcOJmdK40MfOj

User's path of the plugin directories:https://monosnap.com/file/kqrUrR7dIa20fMQSwwSNerZyJc8c8r

https://secure.helpscout.net/conversation/1076106003/109985?folderId=2632030

**Comment by Zabi09** [comment]
You can use our filter and change the path of that AMP theme framework plugin directory and it will be fixed

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.23
