### ISSUE TITLE
Compatibility with the "Easy social share buttons" plugin.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4146]
Need to make compatibility with the "Easy social share buttons" plugin.
https://socialsharingplugin.com/
Ref: https://secure.helpscout.net/conversation/1061598219/107570?folderId=3257665

**Comment by MohammedKaludi** [comment]
Reported in https://ampforwp.com/compatibility/idea-board/

**Comment by MohammedKaludi** [comment]
Reported on : https://ampforwp.com/compatibility/idea-board/
