### ISSUE TITLE
View non AMP version & Mobile redirection

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#415]
View non AMP version & Mobile redirection.... When we click on view-non amp, it is supposed to do it even in Mobile redirection

**Comment by ladislavsulc** [comment]
Thank you, will add later my other findings on Github if there are any.

**Comment by MohammedKaludi** [comment]
Updated some code https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ee02ddc35abaae2ddd753cc3a649aa91a2fc38b9

@khaledMohammed000 Session was not starting at the very beginning  https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ee02ddc35abaae2ddd753cc3a649aa91a2fc38b9#diff-ab576767b896423d184ddafe2ede2310R7

**Comment by MohammedKaludi** [comment]
Code refined : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bdfda6746ffabc39b5380d9713681e5d796233b3

**Comment by MohammedKaludi** [comment]
Redirection properly working.
