### ISSUE TITLE
Instant article started to show empty.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4150]
Instant article are not showing. and WordPress database error is generating:
Lost connection to MySQL server during query.
https://monosnap.com/file/hSl1Ol7MnxMEOMKfyJSeCrsephwtUr

This issue is occurring at the user's end only. and it's a potential issue that could happen to others as well

Ref: https://secure.helpscout.net/conversation/1069646937/108776?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
