### ISSUE TITLE
Issues related to category support on the AMP Pages

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4151]
Ref: https://secure.helpscout.net/conversation/1067414344/108460?folderId=2770545

- [x] If the category support is disabled on the AMP and it is selected in the category is selected in the hide AMP bulk tool then category pages are opening the AMP URL

- [x] Need to improve the "Select Categories to Hide AMP" label. Screenshot:
https://prnt.sc/qytr65

It is a little bit confusing. It is hiding the posts of these categories, not the categories.

- [x] Also, Amp is showing on the Categories pagination pages as well if it is hidden.

**Comment by Zabi09** [comment]
Escaping is missing

**Comment by sonaliramteke** [comment]
It is not working in this condition - https://prnt.sc/r3epbf

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
