### ISSUE TITLE
Debug warning when empty item added in Slider module in AMP pagebuilder

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4152]
Debug warning when empty item added in Slider module in AMP pagebuilder

Backend: https://take.ms/rlqi1

Warning: https://take.ms/F9FfW

**Comment by ajeetku** [comment]
put in the same condition, inside above if
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0bdea79bf9891e438348071128df9ee96992b103#diff-45752acf5e8ea05d2224fa9a73c54c7aR748

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.27 update.
