### ISSUE TITLE
Show/Hide Slider or Icon module  in Pagebuilder is not properly clickable

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4153]
Show/Hide Slider or Icon module  in Pagebuilder is not properly clickable

https://take.ms/RRDxH

**Comment by ajeetku** [comment]
Avoid here jquery if possible, Use javascript Vuejs.

can use here `this.repeaterAcoordian();` instead of `jQuery(event.target).parent(".amp-accordion-head").click();`

**Comment by WasimM3** [comment]
this.repeaterAcoordian(); will not work in this scenario.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.27 update.
