### ISSUE TITLE
Issue with GDPR popup not blocking the whole site.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4155]
Header and menu are working when GDPR popup is on screen, once GDPR notification pops up then the whole site needs to be blocked.

Note: make sure fix should be worked with sticky header(user is using sticky header)

Screenshot: 
https://monosnap.com/file/GtgIX1QWHayxa5hfbIVquvuc6XBCJa

Ref URL: https://heilpraktiker-arno-kreuer.de/?amp

Ref Ticket: https://secure.helpscout.net/conversation/1074739818/109768?folderId=1060556

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.27 update.
