### ISSUE TITLE
Need to add a field so that we can add preload key requests URLs.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4158]
Previously we have implemented preload key requests for font icons in AMP, please check with the ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3752

But we didn't add any option or a field related to the above ticket.

**Comment by WasimM3** [comment]
We are going to improve this in #3997 ticket for this option. So closing it.
