### ISSUE TITLE
Version: 0.9.33 had this error 

### ISSUE THREAD

**Issue by hieu-nguyen-duc** [ahmedkaludi/accelerated-mobile-pages#416]
Hi Please check this bug 

when i update lastest version 
![image](https://cloud.githubusercontent.com/assets/17900278/21973595/61f34d2c-dbf4-11e6-8038-42cc3aa88fd8.png)

So i Deactivate it's working

**Comment by ahmedkaludi** [comment]
@hieu-nguyen-duc We're working on this. We will push an update today for this fix

**Comment by loano** [comment]
Same here, using "Newspaper by Tagdiv". I get the following to see on http://lustaufeinbier.de/:

wp booster error:
td_api_base::mark_used_on_page : a component with the ID: td_mobile_theme is not set.
/homepages/12/d640651372/htdocs/clickandbuilds/LustaufeinBier/wp-content/themes/Newspaper/includes/wp_booster/td_api.php

wp booster error:
Missing parameter: 'file'
/homepages/12/d640651372/htdocs/clickandbuilds/LustaufeinBier/wp-content/themes/Newspaper/includes/wp_booster/td_autoload_classes.php

Hope that helps :)

**Comment by ahmedkaludi** [comment]
Hey @hieu-nguyen-duc @loano 

We have just fixed this issue. Can you please check and confirm?

**Comment by loano** [comment]
Hey @ahmedkaludi, for me it works, now. Thanks!

**Comment by hieu-nguyen-duc** [comment]
Yes. It's working
Thanks Ahmedkudi
