### ISSUE TITLE
Incorrect time showing on AMP if we select Timezone as UTC-3

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4160]
Incorrect time showing on AMP if we select Timezone as UTC-3
Steps to be followed:
1. Set Timezone as UTC-3 
https://monosnap.com/file/4sUefbG749YJTz0Gaspc2VUS3ExlTx
2. Create new posts and check article:published_time and amp-wp-meta amp-wp-posted-on, both showing different times.
https://monosnap.com/file/Q3IGoGdBrIk4tI8VQRdPAnEhldKVao
https://monosnap.com/file/nPVV3wgz2bmDhTkNdHeDo4fnGqcAQY
Ref: https://secure.helpscout.net/conversation/1074879187/109777?folderId=2322651

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
