### ISSUE TITLE
WPappbox images are not loading on the amp pages

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4161]
REF:https://secure.helpscout.net/conversation/1079041045/110435?folderId=3528427

1. User is not able to view the wpappbox images on the amp pages 
2. Having an issue in the design.
3.make compatible  with the wpappbox

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
