### ISSUE TITLE
In single option create tooltip for Author Name

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#4162]
This is the tutorial link - https://ampforwp.com/tutorials/article/how-to-show-author-name-in-single-page/
https://prnt.sc/r07gtu

Need to replace the tutorial link of Author Name in Author Bio Section
 https://ampforwp.com/tutorials/article/how-to-add-author-name-in-author-bio-section/
https://prnt.sc/r0jyei

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.27 update.
