### ISSUE TITLE
Display the Search button in AMP option panel.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4165]

**Comment by MohammedKaludi** [comment]
Few improvements required.
1. Hover pointer effect.
2. The field should be closed by default.

**Comment by MohammedKaludi** [comment]
event needs to be updated to `click` not `mouseover`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
