### ISSUE TITLE
There should be no notices or messages from other third party plugins on the AMP option panel.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4166]
AMP option panel should only have our plugin settings. No third party plugin warning or notices should be visible 
Screenshot:- https://monosnap.com/file/kpwmHyQLOVi2tbdK7ntGH6pNpx3dxU

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
