### ISSUE TITLE
Extra 301 redirect after enabling ?amp

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4167]
Extra 301 redirect after enabling  ?amp and removing  '/ ' from custom structure.
Reference: https://wordpress.org/support/topic/problens-2/

**Comment by MohammedKaludi** [comment]
use `add_query_args`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e4489f04cc212bba3e96b2c9b963ca9cef1fd730#diff-6aa5512f7dd8d5ce60fc97b0f340912cR357

**Comment by MohammedKaludi** [comment]
While merging Move `esc_url` from here 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f52f8fbeb0b812452a6609d7aa398d21d63eefac#diff-6aa5512f7dd8d5ce60fc97b0f340912cR362

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update

**Comment by HaripriyaHari** [comment]
But all links in amp version has url with slash “/?amp”, and then 301 redirect to non-slash “?amp”. You can see links on https://orho.ru/?amp

**Comment by MohammedKaludi** [comment]
this is not the correct fix.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0865cfd813d11ce4b190562970950823ca67e788#diff-04b38a94ddf918855eed7a68ecaa512dR797

**Comment by MohammedKaludi** [comment]
use `ampforwp_is_home()` and `ampforwp_is_frontpage()`

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
