### ISSUE TITLE
Need to make compatibility with Yoast SEO: Local plugin

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4170]
https://secure.helpscout.net/conversation/1073750505/109301?folderId=2632030

From this plugin, we get fields as mentioned in this screenshot where we generate a shortcode form this:https://monosnap.com/file/VGvQ4h0wQvUVopIVmquiCeAS76IMsz

https://monosnap.com/file/scitlw8BvWA1x6lP1HjSHhezjlAILz

https://monosnap.com/file/RTQKXwYrf9k8JeU4UfjMWlh5J7ADwU

**Comment by sonaliramteke** [comment]
Google map is not displaying in Design 1, 2, 3 - https://prnt.sc/r6u279

**Comment by MohammedKaludi** [comment]
function exists is required 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1e90f8496085e2fac89098d67dbb72fccf8fb930#diff-1301281de287d2aed98746fc9ba777b4R1058

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.62
