### ISSUE TITLE
Alignment issue when there is no caption in featured image 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#4171]
https://prnt.sc/r1lfas

**Comment by ajeetku** [comment]
need to put this closing figure tag inside if like opening
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8a8b7aebd5793cc6a50060b95a2874e370f9853b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7133

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.27 update.
