### ISSUE TITLE
Warning issue on AMP option panel.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4172]
/var/www/html/wp-content/plugins/accelerated-mobile-pages/includes/ampforwp-fields-array.php on line 122
ref) https://secure.helpscout.net/conversation/1059605973/107207?folderId=3514643

**Comment by MohammedKaludi** [comment]
why this was removed?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/942c1248f9a3e7fd2e20d2b1b5707f896e0d78ba#diff-b9f3d1733a48b4175877261d173b1028L121

**Comment by MohammedKaludi** [comment]
Still incorrect fix.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
