### ISSUE TITLE
CSS of CTA button is over-riding while user using more than one CTA button in AMP pagebuilder.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4173]
When user using more than one CTA module in AMP page builder, then CSS of the last CTA module is applying on all CTA modules.

Note: issue recreated in localhost, Please check with the below video to recreate the issue.

Video: https://monosnap.com/file/EptocEN7gGnxs3PWwExYOeYuJ8ozWm

AMP Version: 1.0.26

Ref Ticket: https://secure.helpscout.net/conversation/1074739818/109768?folderId=3126461
Issue URL: https://heilpraktiker-arno-kreuer.de/?amp
Screenshot: https://monosnap.com/file/EW5HBE1pFlbtA9vOAd7aPYkWapCzcs

**Comment by ajeetku** [comment]
Check properly the scenario we can do it via CSS block of CTA module.
Not need to change on `viewShowFrontData.php`. For reference, you can check the `content` or `counter` modules. The same situation tackle on there.

**Comment by ajeetku** [comment]
In CSS use {{module-class}} same as `content module` will resolve the issue.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
