### ISSUE TITLE
optimize the CSS

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4174]
Optimize CSS for Design3 and Swift
1. comment
2. Social
3. -moz-
4. Related posts
5. -Webkit-

Reference:  https://wordpress.org/support/topic/the-author-stylesheet-specified-in-tag-style-amp-custom-is-too-long-5/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
