### ISSUE TITLE
compatibility with the "Tawk.To Live Chat" plugin.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4175]
Need to make compatibility with the "Tawk.To Live Chat" plugin.
https://wordpress.org/plugins/tawkto-live-chat/

Ref: https://secure.helpscout.net/conversation/1082741467/111047?folderId=3257665

**Comment by Zabi09** [comment]
Wrong commit of #4171

**Comment by MohammedKaludi** [comment]
moved to https://ampforwp.com/compatibility/idea-board/
