### ISSUE TITLE
Content Sneak Peek issue with below the content ads in Mozilla browser.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4178]
Content Sneak Peek issue with below the content ads in the Mozilla browser.
https://secure.helpscout.net/conversation/1082933868/111110?folderId=2322651

**Comment by MohammedKaludi** [comment]
Need to make sure that this should only work with `swift design` it will break the advertisements of other designs.


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7bd3f9fe64479885dca8279c4bd936a20b604c40#diff-5a452fac5c17477612b7a28b265b48aeR264

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
