### ISSUE TITLE
Change "Just Launched: Ads for WP" to AMP Blocks with link

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4180]
![image](https://user-images.githubusercontent.com/16532359/74590743-2e64c200-5037-11ea-9812-30efac4cb81c.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
