### ISSUE TITLE
Fatal error: Undefined function ampforwp_css_sanitizer()

### ISSUE THREAD

**Issue by satriaenur** [ahmedkaludi/accelerated-mobile-pages#4181]
WP Version: 5.3.2
Plugin Version: 1.0.26

Getting error when opening plugin option page
`Fatal error: Uncaught Error: Call to undefined function ReduxCore\ReduxFramework\ampforwp_css_sanitizer() 
in wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php:3244`

I've activated AMP by Automattic compatibility

**Comment by ahmedkaludi** [comment]
That’s strange, let me check and get back to you immediately

**Comment by MohammedKaludi** [comment]
Hey @satriaenur, 

This has been fixed in the latest update which we have just pushed.

Please update to the latest version and do let us know.

**Comment by MohammedKaludi** [comment]
Fixed in this commit : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/e126e160b354eaefa08424791692923bd4da10cc#diff-1a0e52b2651cea85b13d1cbf4f2198b0R3244



Fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4122

and pushed in 1.0.27 update.

**Comment by satriaenur** [comment]
Nice thank you!
