### ISSUE TITLE
Jetpack lazy loading not working when AMPforWP is active

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4183]
when AMPforWP plugin is enabled then jetpack lazy loading is not working on AMP and Non-AMP also. 

https://wordpress.org/support/topic/bug-found-jetpack-lazy-loading-incompatibility/

Ref: https://secure.helpscout.net/conversation/1081725947/110856?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.30
