### ISSUE TITLE
Need to remove Table styles that are coming from the core when amp pagebuilder compatibility plugin is enabled

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/accelerated-mobile-pages#4185]
Refference : https://trello.com/c/hiX0rUbl/1493-compatibility-with-anywhere-elementor
Url: https://www.crossingbroad.com/sports-betting/pa

**Comment by MohammedKaludi** [comment]
Ready to merge. Need to discuss while merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.30

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
