### ISSUE TITLE
Reusable blocks contents should show in the visual mode in the Custom AMP Editor

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4187]
When the user copies the content of the reusable block then it's not showing in the visual mode in the  Custom AM{P Editor. Although the output is correct. So, It should show the content in the Custom AMP Editor in the visual mode.

Screenshot: https://monosnap.com/file/Epns4ljAtPzKXe6dyt7tBXdsIdD1yO

Ref: https://secure.helpscout.net/conversation/1085036326/111548?folderId=2770545

Steps to recreate the issue:

1. Create reusable content.
2. After creating it copy the content in the Custom AMP Editor using the Copy the content button.
3. You can see the reusable contents are not showing in the Custom AMP Editor.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
