### ISSUE TITLE
Compatibility with embed Getty Images.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4188]
We need to make compatibility with the embed Getty Images.

Ref: https://secure.helpscout.net/conversation/1086961035/111969?folderId=3257665

**Comment by MohammedKaludi** [comment]
not sure this is a good fix
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bbe14ca5cd45cc77357e22a64c3a6841d81aa745#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8050

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.14
