### ISSUE TITLE
short pixel is trying to insert the java  script in the amp

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4189]
REF:(https://prnt.sc/r42qzh)
REf:https://secure.helpscout.net/conversation/1085417322/111634?folderId=3528427

User has a different issue but we caught the error while logged in users dashboard

**Comment by ahmedkaludi** [comment]
There’s already a ticket where we remove notices of others. Maybe it’ll fix with that

**Comment by WasimM3** [comment]
This will fix in #4166
