### ISSUE TITLE
CleanTalk is adding extra js 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#419]
https://wordpress.org/plugins/cleantalk-spam-protect/

<script async type='text/javascript' src='http://www.femalevenue.com/wp-content/plugins/cleantalk-spam-protect/inc/cleantalk_nocache.js?random=5.55'></script>

https://validator.ampproject.org/#url=http%3A%2F%2Fwww.femalevenue.com%2Fwellness-for-women%2Fweight-loss-tips%2Ftop-weight-loss-success-stories%2Famp%2F

http://take.ms/OhIfn

**Comment by MohammedKaludi** [comment]
Tested.
