### ISSUE TITLE
AMP redirects to Non-AMP Pages

### ISSUE THREAD

**Issue by EugenioParnaso** [ahmedkaludi/accelerated-mobile-pages#4191]
Some of my AMP pages redirect to non-AMP pages. I tried it in 2 different browsers and on mobile, but always the same. Here an example:

https://cartujacenter.com/live-music/jose-luis-perales-baladas-para-una-despedida/amp/
https://cartujacenter.com/live-music/tributo-a-dire-straits-brothers-in-band/amp/
https://cartujacenter.com/live-music/vetusta-morla-gira-canciones-dentro-de-canciones-2020/amp/

**Comment by ahmedkaludi** [comment]
@EugenioParnaso  I’m sorry to hear that. GitHub is for recreatable bugs, kindly create a technical team first: https://ampforwp.com/support/
