### ISSUE TITLE
Compatibility with the primary feature of "superfly menu" pluign.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4192]
We need to make compatibility with the "superfly menu" plugin's primary feature(navigation responsive menu) only.
https://codecanyon.net/item/superfly-responsive-wordpress-menu-plugin/8012790

Ref: https://secure.helpscout.net/conversation/1084833333/111492?folderId=3257665

**Comment by MohammedKaludi** [comment]
Reported : https://ampforwp.com/compatibility/idea-board/
