### ISSUE TITLE
Add 'alt' attribute for image element in Slider module of AMP page builder.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4193]
There is no 'alt ' attribute for image in the Slider module of AMP page builder. 

reference: https://secure.helpscout.net/conversation/1062102432/107666/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
