### ISSUE TITLE
option  to hide vukkle comments emoji

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4194]
option to hide the vuukle comments  emoji 

Ref: https://secure.helpscout.net/conversation/1075020689/109824/
vuukle ref screenshot: https://prnt.sc/r41rvk

**Comment by sonaliramteke** [comment]
It's not hiding on Design 1, 2, 3 - https://prnt.sc/r6tgn5

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
