### ISSUE TITLE
Notice Errors in AMP FOR WP(Trying to get property 'title' )

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4196]
Notice: Trying to get property 'title' of non-object in E:\XAMPP\htdocs\WP53\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 7366

Notice: Trying to get property 'title' of non-object in E:\XAMPP\htdocs\WP53\wordpress\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 7372

Screenshot: https://monosnap.com/file/bEUoiRGCEVt5oCxkU0Pezc6M7wtRJz

Ref: https://secure.helpscout.net/conversation/1087924864/112169/

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
