### ISSUE TITLE
Need to make compatibility with Paid Memberships Pro plugin's feature content restriction feature

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4197]
Need to make compatibility with Paid Memberships Pro plugin's feature content restriction feature

In Non-AMP the content is getting restricted after 7 paragraphs but in AMP it is getting restricted for 1 paragraph.

1.In AMP version: https://monosnap.com/file/EHZ1j0tNc0qLY6GeSXc9UovlA17VKM

2.In NON-AMP version: https://monosnap.com/file/sa46WFUiYLKkHWi5hbk2yQu28BEPW4

https://jetsxfactor.wpengine.com/2020/01/26/new-york-jets-all-time-53-man-roster-joe-namath-jamal-adams-and-more/

**Comment by MohammedKaludi** [comment]
Issue moved in https://ampforwp.com/compatibility/idea-board/
