### ISSUE TITLE
Vido is not playing on mobile device if uploaded through the Video Press

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4198]
Ref: https://secure.helpscout.net/conversation/1086997997/111982?folderId=2770545

URL: https://yummybarcelona.com/el-celler-de-can-roca-menu-2020/amp/

Screenshot Android: https://monosnap.com/file/RqGxk2WmI4lg7zXTfovgs6g5NFoiKA

IOS: https://monosnap.com/file/BEwx5JRbyU4iOVxvDiIpPpL3ELxtaT

The issue is occurring on actual mobile devices. If we go through the mobile version on the desktop then it is working.

**Comment by Zabi09** [comment]
Going to fix in 26977 of ampproject/amphtml

**Comment by MohammedKaludi** [comment]
This issue is related with AMPHTML and they are going to fix is so closing this ticket as no further development is required.
