### ISSUE TITLE
script is not being appended via Enter HTML in Head

### ISSUE THREAD

**Issue by luan03** [ahmedkaludi/accelerated-mobile-pages#4199]
Hi guys,

I've noticed that some of my scripts appended via **Enter HTML in Head** at WordPress admin section are not being included on the page.

My test was include `<script async custom-element="amp-access" src="https://cdn.ampproject.org/v0/amp-access-0.1.js"></script>` in that section but I'm getting an error via amp validator. I also checked via HTML inspector.

I'm pretty sure that was working a few months ago.

Thanks

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update

**Comment by luan03** [comment]
Thank you guys.
