### ISSUE TITLE
Please bring back Mobile Detection & Auto Redirection as option

### ISSUE THREAD

**Issue by Asif2BD** [ahmedkaludi/accelerated-mobile-pages#42]
You had this feature before, codes are just commented out, I know its not for everyone, but could you please bring it back via option page? Or is there a way I could do it as an addon, any hooks I should use? Or do it completely externally?

**Comment by MohammedKaludi** [comment]
Thanks for your suggestion, as we have everything already built, we will create an option to turn on-off auto redirection for mobile devices.

**Comment by Asif2BD** [comment]
@MohammedKaludi Exactly! I was thinking the same, its very easy, you have everything there. if you do so, then I could turn it on my main site, I am using a forked version now.

**Comment by khaledMohammed000** [comment]
https://github.com/Asif2BD/Accelerated-Mobile-Pages

**Comment by MohammedKaludi** [comment]
Mobile redirection feature added
