### ISSUE TITLE
Warning Errors

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4200]
Reference:  https://wordpress.org/support/topic/warnings-on-amp-view/
https://monosnap.com/file/irg1lp2ZVGMyEzE7G5wcOZD7Vg3VnX

**Comment by MohammedKaludi** [comment]
incorrect escaping. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f8c43ba443907a34cbbba541ae65700f8b864f93#diff-3e982094fdfeced008470c3941cbb19cR84

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.29 update
