### ISSUE TITLE
Need to make deactivate button visible and expired in red color

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4202]
Need to make deactivate button visible when we install it and also expired should in red color

ref screenshot:https://monosnap.com/file/DIlThkY6UbOMZ6ORLaoUmbYThtZYLZ

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
