### ISSUE TITLE
Validation error due to Mediavine Plugin(URGENT)

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4206]
Ref: https://secure.helpscout.net/conversation/1085139986/111573
- [x] The tag 'amp-consent extension .json script' is missing or incorrect, but required by 'amp-consent'.

- [x] The mandatory attribute 'action' is missing in tag 'FORM [method=GET]'. error due to Create by Mediavine plugin.

- [ ] Also, we need to inform and discuss  Mediavine Plugin about the issue.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
