### ISSUE TITLE
Need to create option "preserve original permalinks" in Mobile redirection.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4207]
Need to create a child option "preserve original permalinks" in the mobile redirection option. where users can visit AMP sites with the URL that does not have "/amp" or "/?amp". so whenever the user visits the site using mobile then the URL structure is like Non-AMP URL. but it will load the AMP version.

Ref: https://secure.helpscout.net/conversation/1088106375/112231/

**Comment by ahmedkaludi** [comment]
another https://wordpress.org/support/topic/any-way-to-remove-url-amp/

**Comment by MohammedKaludi** [comment]
need to do a very deep testing to make sure it works with all scenarios

**Comment by Zabi09** [comment]
Pushed in 1.0.76.13
