### ISSUE TITLE
Amp comments Bug with update 1.0.28

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4209]
![CE9ECBB3-DBA9-46AA-B10F-EA0B1F408ED0](https://user-images.githubusercontent.com/16532359/75085674-888ee700-5551-11ea-81df-54e371b6203a.png)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.30
