### ISSUE TITLE
Problem with alignment buttons rel = "next" and rel = "prev" pagination on the mobile device screen.

### ISSUE THREAD

**Issue by duendecasino** [ahmedkaludi/accelerated-mobile-pages#4211]
Hi everyone!
In recent versions of this plugin I have found that the rel = "next" & rel = "prev" page buttons are not aligned when the screen resolution is changed. In other words, one of the buttons is lower than another.
I have solved this error by modifying some values in file /accelerated-mobile-pages/templates/design-manager/design-2/style.php:

/ * Pagination * /
.
.
`#pagination .next {float: right; max-width: 60%; text-align: right;}
#pagination .prev {float: left; max-width: 60%; }`
.
.
![Screenshot1](https://user-images.githubusercontent.com/13471801/75117829-655d5800-5675-11ea-8607-5d5946b44ba4.png)
![Screenshot2](https://user-images.githubusercontent.com/13471801/75117830-668e8500-5675-11ea-8fdb-739e6013b699.png)
![Screenshot3](https://user-images.githubusercontent.com/13471801/75117831-668e8500-5675-11ea-9cb0-d8d915ba452a.png)

Value "max" is added to "width". See screenshot "Screenshot3" that is correct.
You can see an example of my page: https://casinoduende.com/casinos-online/high-country-casino/?amp

**Comment by MohammedKaludi** [comment]
@Zabi09 Just confirm it once with @ahmedkaludi before working on it.

**Comment by MohammedKaludi** [comment]
Max width 50% is required.

**Comment by MohammedKaludi** [comment]
Ready for merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.35
