### ISSUE TITLE
Notice: Undefined index: display_webp in /home/crypgnil/cryptomoonpress.com/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 7982

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4212]
Ref: https://secure.helpscout.net/conversation/1087924864/112169/
Notice: Undefined index: display_webp in /home/crypgnil/cryptomoonpress.com/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 7982

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.30
