### ISSUE TITLE
I am Getting lots off css code on page , after removing this plugin page restored . 

### ISSUE THREAD

**Issue by hardikhari96** [ahmedkaludi/accelerated-mobile-pages#4213]
I am Getting lots off css code on page , after removing this plugin page restored

**Comment by MohammedKaludi** [comment]
Can you please share the url or the example of the page where is the issue happening.

**Comment by MohammedKaludi** [comment]
GitHub ticket section is for recreateble bugs, please provide the proper information on how can we recreate the issue. 

Ticket is closing, due to not proper information.

You can reopen the ticket with proper information.

**Comment by hardikhari96** [comment]
https://beta.skoopify.com/job-openings/amp/ 


This is my amp page
