### ISSUE TITLE
Need to remove search option when header type 2 is selected.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4214]
When the user selected header type 2 then we need to remove the search option.

Screenshots:
Selected menu: 
https://monosnap.com/file/QACbBlPqDP7ppjkxGNNVjGm50k2Ano
Need to remove option:
https://monosnap.com/file/pcGDu6WFMV2kQONuNd7Gp2jRKJmxFo

Ref Ticket:
https://secure.helpscout.net/conversation/1080760225/110714?folderId=1060556

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
