### ISSUE TITLE
CSS of the CTA button in AMP page builder is disturbed in the mobile view.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4215]
Please check with the below screenshots:
https://monosnap.com/file/l9ZunoCkyj9gsSrxHiZn23HpLG5q1M

Should be like this:
https://monosnap.com/file/07vGRRw7ygahMcEDlCBimKcLRMAe7e

Ref Ticket: https://secure.helpscout.net/conversation/1074739818/109768?folderId=1060556

Ref URL: https://heilpraktiker-arno-kreuer.de/?amp

Tested in local host.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
