### ISSUE TITLE
Need to add compatibility with the CIARO theme

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4220]
Ref: https://secure.helpscout.net/conversation/1087912126/112160?folderId=2770545

The menu is not showing properly with the Cairo theme. The Layout is breaking for the menu and the CSS is not loading properly. 

The theme file is available in the Magazine3 group. The issue also recreates local as well.
Screenshot: https://monosnap.com/file/q0B0iG4uTKloHqywqgGRSaUpinhzpQ

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
