### ISSUE TITLE
An issue with custom link add in AMP menu items.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4221]
User wants to navigate internally on home page, so created a custom link and added into menu items but the link is not working properly.

Please check with the below video for more details(created in localhost):
https://monosnap.com/file/lBlzgnPqw03fdtLYnUZAdN2rs7ZFqA

Issue URL: https://test.bondevalue.com/?amp
(Plan&price) is the Custom link in the menu items.

Ref Ticket: https://secure.helpscout.net/conversation/1080760225/110714?folderId=3126461

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/98ea1cd5f003977e03da976d9fe0c168e2a557a7#diff-6aa5512f7dd8d5ce60fc97b0f340912cR2996
put here `===` if `strpos` returns 0 than `if` will count it as false

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
