### ISSUE TITLE
light box appearing even when it disable for some particular size of images

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4222]
Use case:

When image height it above 400 and width above 600

Examples of the images:

img   src="https://casinoplusbonus.com/wp-content/uploads/2020/02/KW-8-2020-Grosse-Bandbreiten-bei-Echtgeld-Casino-Aktien-1-300x150.jpg" alt="KW 8-2020 Grosse Bandbreiten bei Echtgeld-Casino-Aktien" width="600" height="400" />

 img  src="https://casinoplusbonus.com/wp-content/uploads/2020/02/Serengeti-Kings-800x400-1.jpg" alt="Serengeti Kings Spielautomaten" width="800" height="400" />

https://secure.helpscout.net/conversation/1091796471/112968?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
