### ISSUE TITLE
Youtube video is not working in " The issue" Theme

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4223]
youtube video is not working in  " The issue"  when we are uploading it.

Ref: https://secure.helpscout.net/conversation/1079614668/110532/

**Comment by amer07** [comment]
Case:2 https://secure.helpscout.net/conversation/1098997787/114343?folderId=2770543

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
