### ISSUE TITLE
In mobile view "click here" link  in comment section is not genrating correct url.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4225]
Case 1:https://secure.helpscout.net/conversation/1092988824/113173?folderId=2770543

Note: In the comment section "click here" link generating by "Subscribe to Comments Reloaded plugin" which is pre-build feature working well, but in the mobile view it generates bad URL  like src..99999 like this. 

Here you see video clip: https://monosnap.com/direct/nE2rYf8Jq0XTewUfBaN08zZvjvLJrW

***Also, recreate in my end***

**Comment by Zabi09** [comment]
Not working will you please check once

**Comment by MohammedKaludi** [comment]
Ready for merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
