### ISSUE TITLE
Getting warnings in AMP FOR WP after installing the AMP

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4226]
Getting warnings in AMP FOR WP after installing the AMP

Ref screenshot:https://monosnap.com/file/MMmOIHWNmQrGUBVSBD5Wyuz7hC7Xjd
ref: https://secure.helpscout.net/conversation/1093945011/113342/

**Comment by MohammedKaludi** [comment]
pushed in 1.0.31
