### ISSUE TITLE
Template-mode search form not working 

### ISSUE THREAD

**Issue by jasthilokesh** [ahmedkaludi/accelerated-mobile-pages#4227]
Template-mode search form not working due to incorrect regular expression 

File path:
---------
\accelerated-mobile-pages\templates\template-mode\template-mode.php

Function:
----------
comment_form_conversion

form regular expression miss-match issue.

**Comment by ahmedkaludi** [comment]
Actually the search should use the default theme form and sanitise it

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Merge 1.0.33 into master.
