### ISSUE TITLE
Syntax is getting disturb of analytics code and creating syntactic errors in advance analytics section editor

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4228]
The syntax is getting disturbed of analytics code and creating syntactic errors in the advance analytics section editor.

https://secure.helpscout.net/conversation/1082087063/110966?folderId=2632030

**Comment by ajeetku** [comment]
At https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7a6119de49fc5caa83ac8f2bc21c2d44adfc52d3#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R1349 we already getting `WP_Screen`  object 

so we don't need to call this function again. we can use that object.
And put this condition on the top entry of the function.
For ref:  https://developer.wordpress.org/reference/hooks/current_screen/

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
