### ISSUE TITLE
Yoast Canonical

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4229]
Using static page as a homepage, The static page canonical already set at amp page.  But in homepage amp, it still point to non-amp. 

Reference:  https://wordpress.org/support/topic/yoast-canonical/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
