### ISSUE TITLE
Add Categories and Tags support

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#423]
Add the Categories and Tags support, with a switch which allows the users to enable and disable it.
By default, it should be OFF.

**Comment by MohammedKaludi** [comment]
Proposing to add this feature in 0.9.36  @ahmedkaludi need your feedback

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/340

**Comment by MohammedKaludi** [comment]
when AMP on archive is OFF, then it should be properly turned off

**Comment by MohammedKaludi** [comment]
Working Smoothly
