### ISSUE TITLE
I am Getting lots off css code on page , after removing this plugin page restored

### ISSUE THREAD

**Issue by hardikhari96** [ahmedkaludi/accelerated-mobile-pages#4230]
I am Getting lots off css code on page , after removing this plugin page restored

[url of site page](https://beta.skoopify.com/job-openings/amp/) 

or 

https://beta.skoopify.com/job-openings/amp/

This is my URL of site ,

**Comment by ahmedkaludi** [comment]
This is extremely strange and Unusual. GitHub is for tried and tested bugs, can you send this one to the technical team first so they can verify? https://ampforwp.com/support/
