### ISSUE TITLE
image is broken when  the image webp replacement is enabled in light speed cache plugin

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4231]
REF:https://secure.helpscout.net/conversation/1093241171/113252?folderId=3528427

User is facing the issue image broken in the lightspeed cache plugin when the image webp replacement option is enabled
(https://prnt.sc/r8vxtd)
(https://prnt.sc/r8vxau)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
