### ISSUE TITLE
Need to give option to show the "Addthis Floating Share" feature on the Pages.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4232]
We need to give an option to show the  "Addthis Floating Share" feature on the Pages. We are currently showing it on the posts. We have to add one option that will ask, Do you want to show it on the Pages? 

It should work with the AMP Page Builder Compatibility as well. We need to test it with the Elementor and DIVI properly.

Ref: https://secure.helpscout.net/conversation/1090646253/112698

**Comment by WasimM3** [comment]
We have this option for pages as well. This option is linked with the Design->page->social icon.

**Comment by WasimM3** [comment]
Enabled "Addthis Floating Share" from Design->Social Sharing->AddThis Share Buttons-> 
then
Enabled Design->page->social icon option it's working as expected.
So, closing the ticket
