### ISSUE TITLE
Custom JavaScript are not allowed issue

### ISSUE THREAD

**Issue by sonaliramteke** [ahmedkaludi/accelerated-mobile-pages#4233]
When we enable this two option "Convert AMP to WP theme (Beta)" and "Back to Top link" then validation error will appear - https://monosnap.com/direct/QOsbHmHguymp6w8UJCClcelLfsuXWZ

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
