### ISSUE TITLE
Tree shaking file is not deleted on post update

### ISSUE THREAD

**Issue by jasthilokesh** [ahmedkaludi/accelerated-mobile-pages#4234]
Tree shaking file is not deleted on post update

File Path
---------
C:\xampp\htdocs\mainsrc\wp-content\plugins\accelerated-mobile-pages\includes\features\performance\performance-options.php

Function:
----------

ampforwp_clear_tree_shaking_post

Root cause:
------------
is_singular,is_archive will not work in the admin , so tress shaking file was not deleted while post update.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
