### ISSUE TITLE
The pages which use the "?noamp=1" get a fatal error.  "Uncaught Error: Call to undefined function session_start() in /app/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php:67"

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4236]
reference: https://secure.helpscout.net/conversation/1095305645/113659?folderId=3514643
screnshot: https://monosnap.com/file/kbktvWyB6zH7ft1DG3eaTKB7V8bRl4

**Comment by MohammedKaludi** [comment]
Just make sure we are escaping the `$_GET` while merging. 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7d61a75bac7f1eb1dfa897195d44000a028127e5#diff-ab576767b896423d184ddafe2ede2310R61
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
