### ISSUE TITLE
Need to a feature that user can add utm_souce parameters in URLs to both related & incontent related posts.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4237]
Need to a feature so that users can add utm_souce parameters in URLs to both related & in-content related posts.

Ref Ticket: https://secure.helpscout.net/conversation/1096551007/113862?folderId=3126461

**Comment by MohammedKaludi** [comment]
some improvement in the code is required
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f7a04a628a258c5d1df508e453d796a06e0cae8d#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580R8113

**Comment by MohammedKaludi** [comment]
improvement required.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.13
