### ISSUE TITLE
The mandatory attribute 'target' is missing in tag 'FORM [method=GET]'.

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4239]
REF:https://secure.helpscout.net/conversation/1094256882/113427?folderId=3528427

 The mandatory attribute 'target' is missing in the tag 'FORM [method=GET]'. in the category section in 
which is added in the footer.

**Comment by Techbland** [comment]
Hello.

How can I fix the above errors on search console.

**Comment by Techbland** [comment]
Hello.

How can I fix the above errors on search console.

**Comment by MohammedKaludi** [comment]
@Techbland This ticket will be pushed in next update that we are planning to push on this Friday.

Please wait until friday, or if you want to fix it, you can copy and paste the code from the commits into the plugin files.

**Comment by Techbland** [comment]
I should paste the code into AMP plugin?

And in which area should I paste the code?

**Comment by ajeetku** [comment]
Current code can break refer https://regex101.com/r/XFpern/1

make sure we add the proper form method type as per defined in the ticket title

**Comment by Techbland** [comment]
So, i should add this code on my website?

**Comment by Zabi09** [comment]
@Techbland You no need to add or remove any code on your end as I have added the code on your end yesterday only and your target issue is fixed

**Comment by Techbland** [comment]
Ok thank you sir

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32

**Comment by Techbland** [comment]
Hello.

How to fix "referenced amp url is not an amp"?
