### ISSUE TITLE
Advanced AMP Ads - Incontent Ads: Missing spacing between ads and images

### ISSUE THREAD

**Issue by loano** [ahmedkaludi/accelerated-mobile-pages#424]
To reproduce the issue, add Adsense after 1. paragraph and 2. paragraph via "Custom Advertisement". Spacing to images within content = 0px, Screenshots (Iphone6s): 
https://www.dropbox.com/s/4b034k6nym2vf8m/2017-01-18%2016.00.13.png?dl=0
https://www.dropbox.com/s/f3nv5ja8zpztmu7/2017-01-18%2016.00.27.png?dl=0
Live URL: http://starzip.de/bibis-beauty-palace-familie/amp

**Comment by ahmedkaludi** [comment]
Continuing at https://github.com/ahmedkaludi/amp-ads-google-adsense/issues/19
