### ISSUE TITLE
How to fix "Referenced AMP URL is not an AMP" on search console

### ISSUE THREAD

**Issue by Techbland** [ahmedkaludi/accelerated-mobile-pages#4240]
I don't know why I have this issue. before changing my website theme there is not such a error but when I changed my website theme then I have multiple AMP issues.

What is the reason anyone can tell me?

**Comment by MohammedKaludi** [comment]
can you share the url

**Comment by Techbland** [comment]
Here are the error links

https://techbland.com/tag/tik-tok-app/ 
https://techbland.com/tag/install-andrid-10/
https://techbland.com/category/ios/
https://techbland.com/category/smartphones/
https://techbland.com/category/virtualbox/
https://techbland.com/tag/install-macos-catalina-on-vmware/
https://techbland.com/tag/vm/
https://techbland.com/tag/top-10-comedy-movies/
https://techbland.com/tag/download-macos-mojave-10-14-6-dmg-file/

**Comment by ahmedkaludi** [comment]
GitHub is for tried and tested bugs, kindly get the bugs confirmed at https://ampforwp.com/support/

**Comment by Techbland** [comment]
I just updated the footer.php and pasted the code you provided.

**Comment by ahmedkaludi** [comment]
I didn’t provided you any code?

**Comment by Techbland** [comment]
So how can I fix this issue? as I send you the article links those that
have an error.

But i didn't hear from you
