### ISSUE TITLE
Multiple debug warnings.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4242]
Undefined variable : amp_cur_url in wp-content\plugins\accelerated-mobile-pages\templates\features.php in line 5137 #4242

The warning is only visible on the Non-AMP for logged in users.

https://monosnap.com/file/z5I0slLjzWcAV755MnkBZBueAcTb4s

**Comment by HaripriyaHari** [comment]
Undefined variable:  transient_filename in /home/content/22/7568022/html/partisanissues/wp-content/plugins/accelerated-mobile-pages/includes/features/performance/performance-functions.php on line 373

Reference: https://wordpress.org/support/topic/amp-error-on-categories/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
