### ISSUE TITLE
Add "<ol> start attribute" to ordering items

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4243]
Takes the values in <ol> start Attribute.
Reference:  https://wordpress.org/support/topic/order-list-is-not-aligning-properly-in-post-detail-pages/

**Comment by MohammedKaludi** [comment]
Ready to mereg.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.33
