### ISSUE TITLE
Hide AMP Bulk Tools option isn't working with WPML

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#4249]
Use case:-
When user selects the Category in English (to hide) and then moves to Spanish Panel, adds Category in Spanish (to hide).
On first instance it works but when user moves from one language to the other the only One category is present(of current language) rather than two.

It resets the value in the Hide AMP Bulk Tools Option.
https://secure.helpscout.net/conversation/1099189908/114369?folderId=3575684

**Comment by MohammedKaludi** [comment]
Ready to go

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.37
