### ISSUE TITLE
Query Monitor queries should be visible in amp pages too when logged in.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4250]
Desc: Query Monitor queries should be visible in amp pages too when user is logged in.

Ref: https://secure.helpscout.net/conversation/1097120108/113970?folderId=2770545

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.32
