### ISSUE TITLE
Comments pagination is not working when amp takeover beta is enabled

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4251]
https://secure.helpscout.net/conversation/1098773669/114314?folderId=2632030

issue recreated in local

**Comment by sonaliramteke** [comment]
It is not working in Design 1,2 and 3

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
