### ISSUE TITLE
Elementor CSS not loading on custom front-page when ALL in One SEO plugin is active.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4253]
Elementor CSS not loading on custom front-page when ALL in One SEO plugin is active.
Ref: https://secure.helpscout.net/conversation/1098358078/114251?folderId=3257665
Solution: Need to remove $post from the below line in the features.php file
Line 1710 : $aiseop_title = $post = '';

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.33
