### ISSUE TITLE
"Select Categories to Hide in IA" option is not working.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4254]
when user select post categories to hide it from the instant article then also the articles are showing. 
Ref: https://secure.helpscout.net/conversation/1069646937/0/?folderId=3257665

**Comment by Zabi09** [comment]
Not working, Will you please check it once

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed. 1.0.33
