### ISSUE TITLE
Need to Implement pagination in custom AMP Editor

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4255]
Need to Implement pagination in custom AMP Editor. Pagination is not supported by that editor.
Reference:  https://wordpress.org/support/topic/need-help-in-implementing-pagination/#post-12506662

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
