### ISSUE TITLE
Treeshaking is not working with "Product Review Lite Plugin".

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4256]
At user's end, tree shaking is not working.
Ref: https://secure.helpscout.net/conversation/1092092231/113049?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Dont close the ticket after the update.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34

**Comment by MohammedKaludi** [comment]
need to add class exists
