### ISSUE TITLE
"srcset" is not getting implenented for the images which come from cdn url which is implemented by wp-rocket

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4257]
"srcset" is not getting implemented for the images which come from CDN URL which is implemented by wp-rocket.

Ref: https://secure.helpscout.net/conversation/1097000289/113934?folderId=2632030
https://www.siasat.com/picture-highlights-3rd-march-1846405/amp/

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/594f3c666f291def89c91777c301c9d21cf5efc5#diff-9b90095ac89c9920aff8f8f3bb89ffd3R56

`get_post_thumbnail_id ` can be a bit heavy when used inappropriately, this can be improved.

**Comment by MohammedKaludi** [comment]
Ready to go

**Comment by MohammedKaludi** [comment]
Multiple srcset in the image.

https://monosnap.com/file/jj97nkmAEc2RZzkGXbsnMHQgnBiZNl

https://monosnap.com/file/hdz7rxzBvnA7buBKuIA50Phi5LMk8H

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.36 update
