### ISSUE TITLE
Site is getting blank when activating imagify plugin

### ISSUE THREAD

**Issue by WasimM3** [ahmedkaludi/accelerated-mobile-pages#4260]
Found the issue in this line :
`$content_buffer = preg_replace('/<picture(.*?)<amp-img(.*?)><\/amp-img>(.*?)<\/picture>/s', '<noscript><picture$1</picture></noscript><amp-img$2></amp-img>$3', $content_buffer);`
of `ampforwp_minify_html_output` function

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.33
