### ISSUE TITLE
Images are not showing in AMP after embedding through the Gutenberg block due to Neva Child Theme.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4261]
URL: https://webmacter.ru/installing-filezilla/amp/

Ref: https://secure.helpscout.net/conversation/1095067068/113597?folderId=2770545

**Comment by MohammedKaludi** [comment]
do contact me or Akash when starting working on this ticket.

**Comment by goodwinpress** [comment]
Remove lazy load from the theme and amp will work fine.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.33
