### ISSUE TITLE
Have to make compatible with wordpress4.4.2 version

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4262]
REF:https://secure.helpscout.net/conversation/1094274887/113428?folderId=3528427
Have to make compatible with the Wordpress 4.4.2.
The amp pages are getting blank  on this version (https://prnt.sc/rcgffr)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
