### ISSUE TITLE
Create an option to allow users to upload and use local fonts on AMP.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4264]
REf:-https://secure.helpscout.net/conversation/1101960498/115245?folderId=3243584

**Comment by nakib4tech** [comment]
Hi @ahmedkaludi , we are still awaiting this feature.. when it will be merged, please?

**Comment by MohammedKaludi** [comment]
> Hey @ahmedkaludi , Also add some default fonts like Arial that do not create additional request to google api.

@jayendrasinhrajput You can follow this article and set default system fonts to achieve that, no need to upload additional fonts that are already available on the System. https://css-tricks.com/snippets/css/system-font-stack/#method-2-system-font-stacks

**Comment by MohammedKaludi** [comment]
Pushed in update 1.0.77.3
