### ISSUE TITLE
warning issue in the Notice: Undefined variable: 

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4265]
REF:https://secure.helpscout.net/conversation/1100347540/114954?folderId=3528427

warning issue in the Notice: Undefined variable: get_amp_custom_frontpage_id in /home/g2xba04xvkxa/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 105

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.33
