### ISSUE TITLE
Need to create option to remove "nofollow" attribute from the comment button.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4266]
Need to create option for removing "nofollow" attribute from the "leave a comment" button. because if user is checking in SEMRush its showing errors. so we have to create an option for it. if the user using SEMRush.
Ref: https://secure.helpscout.net/conversation/1100229253/114892?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
