### ISSUE TITLE
Need to make compatibility with the Imagify Webp images!

### ISSUE THREAD

**Issue by nakib4tech** [ahmedkaludi/accelerated-mobile-pages#4267]
Dear sirs,
I am using Imagify to optimize and convert images to webp type. 
All Images are conveted and showing as webp in non-amp pages. But in AMP pages images is not showing as wwbp.

**Comment by nakib4tech** [comment]
Here's a URL of the problem, check both amp and non-amp:
https://nakib4tech.com/ideal-wp-rocket-settings-with-cloudflare/amp/

**Comment by Zabi09** [comment]
@nakib4tech We are already compatible with the imagify plugin and I have checked your images in AMP and all your images are showing webp only in AMP also
See this screenshots - 
https://monosnap.com/file/mZOyMEhcQJpd9rvGgp7bq2YJbVCBTq
https://monosnap.com/file/NSyPX0SlgMipYvReDpHok1TyvHdAkM

Will you please check once and let us know

**Comment by Zabi09** [comment]
GitHub is for tried and tested bugs, can you send this one to the technical team first so they can verify? https://ampforwp.com/support/
