### ISSUE TITLE
Need an option to switch to CSS icons

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4268]
We need an option to switch to CSS icons
Ref:
https://secure.helpscout.net/conversation/1102749932/115402/

**Comment by ahmedkaludi** [comment]
- [ ] make sure we do in amp layouts as newspaper theme as well

**Comment by ansaritalha** [comment]
- [ ] Need to add some icons like menu icons, Breadcrumbs icon, check screenshots.
1- https://monosnap.com/file/HTp3lkCCI5ZlRv5DQm884AP2XMMfdL
2- https://monosnap.com/file/Z5vKo203rY6KUxU2mnN5McvNavUu4B

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
https://monosnap.com/file/BA632DRUvVBzd2MqkRZSxlHHR9UvLE

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.42
