### ISSUE TITLE
Remove imageanchor="1"

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#427]
imageanchor="1" has to be removed/strip/replaced which is causing validation errors.

Ref: https://search.google.com/search-console/amp?utm_source=wmx&utm_medium=link&utm_campaign=wmx-agg&id=vXV77W1qKSJZXfAnBY8LTA
http://foodnessgracious.com/sopapillas-the-homesick-texan-cook-off-2/amp/

**Comment by ahmedkaludi** [comment]
This was already fixed
