### ISSUE TITLE
 Need an Option to hide/show in sassy social share plugin in AMP

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4273]
Reference: https://wordpress.org/support/topic/compatibility-issues-help/

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7bb7fe1d3de880eb59fe7443745b5c2ba2cb7d6d#diff-1301281de287d2aed98746fc9ba777b4R60

this will disable the social share in non-amp as well.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.37
