### ISSUE TITLE
amp-fx-collection requires including the 'amp-fx-collection' 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4275]
The attribute 'amp-fx' requires including the 'amp-fx-collection' extension JavaScript.

Reference: https://wordpress.org/support/topic/contents-of-advanced-settinshead-not-loading/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.36 update
