### ISSUE TITLE
Individual AMP Post (Bulk Edit) "hide by default" option not working

### ISSUE THREAD

**Issue by AmiOta** [ahmedkaludi/accelerated-mobile-pages#4279]
Hi,

I reopen this, on version 1.0.32 is only working for pages, but no for posts, I followed the guide https://ampforwp.com/tutorials/article/allow-amp-only-on-few-posts-or-pages/ but the results are:

On Post (Not working):

![image](https://user-images.githubusercontent.com/46223934/76429219-b8752180-637c-11ea-8ac9-8c65ecd2487d.png)

On Page (Working):

![image](https://user-images.githubusercontent.com/46223934/76429256-c75bd400-637c-11ea-970f-515cd8159592.png)

_Originally posted by @AmiOta in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3610#issuecomment-597675650_

**Comment by Zabi09** [comment]
@AmiOta Currently, we only have the option of "Individual AMP Page (Bulk Edit)" - https://prnt.sc/rf4g7o and this will allow you to show/hide the AMP on individual pages and we don't have any feature like "Individual AMP Post (Bulk Edit)" in the current version 1.0.32, Will you please tell us where you have seen this option?

And also our team is already working on that feature and it will be released in the future update in this Github ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3571

**Comment by AmiOta** [comment]
Excellent!

In the guide (https://ampforwp.com/tutorials/article/allow-amp-only-on-few-posts-or-pages/), if you see, all reading seems that allow Post too
