### ISSUE TITLE
Test youtube embed shortcodes

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#428]
Youtube embed shortcodes need to be tested, user is reporting that it's not working for him.

ref: https://wordpress.org/support/topic/embed-iframes-and-shortcuts/

**Comment by retroriff** [comment]
Looking forward this update.

**Comment by MARQAS** [comment]
The progress of this ticket can be viewed in #557 as both issues are same.
So I am closing this ticket. @retroriff
