### ISSUE TITLE
AMP URL is displaying as "page URL undefined" in Matomo Analytics

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4280]
Ref: please see this screenshot: https://monosnap.com/file/gnBFYeVxXQpbZqdrNfrdjwBzNmw92v

https://secure.helpscout.net/conversation/1093900540/113335?folderId=2632030

AMP url is are displaying as page URL undefined in Matomo Analytics

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
