### ISSUE TITLE
Weekday should get not populated from the analytice code of  parameter published at

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4281]
weekday should get published from the analytics code of published id,

Ref: cd2":"{published_at}

https://prnt.sc/rf317m

https://monosnap.com/file/Cug7sG0Sw0LYrqdfqz8e6SmEdJFe6R

https://www.telugubulletin.com/exclusive-finally-b-town-actress-to-join-rrr-from-this-date-69974?amp

https://secure.helpscout.net/conversation/1102039293/115254?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.34
