### ISSUE TITLE
 related post images have no alt attribute

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4282]
REF:https://secure.helpscout.net/conversation/1105906493/116098/

**Comment by MohammedKaludi** [comment]
Create empty variable `$thumb_alt` otherwise it will give warnings.
 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2b422acd8abc9879da718a011caf20b84f833f92#diff-4df5c887c9bf062e619962dc7e2c804eR166

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.35
