### ISSUE TITLE
Getting validation error when "Optimize loading of Google font" option is enable of SG Optimizer pluign

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4287]
The user is getting validation error when the "Optimize loading of Google font" (https://monosnap.com/file/dkxY6QfaCBKSuMccrl0BYbkuu71Obq) option from the SG optimizer plugin.
URL: https://www.chelseaschimney.com/amp/
Ref: https://secure.helpscout.net/conversation/1106403269/116161?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.35
