### ISSUE TITLE
Performance improvements for large sites

### ISSUE THREAD

**Issue by calind** [ahmedkaludi/accelerated-mobile-pages#4288]
Currently, the related posts feature creates a `WP_Query` which uses `SQL_CALC_FOUND_ROWS`, although it doesn't need the post count. This results in MySQL scanning the entire `wp_posts` table, in turn, increasing the database load.

By setting `no_found_rows` to `true` (in `templates/design-manager/design-3/elements/related-posts.php` for example), I was able to reduce the related posts query time from 10s to under 1s. You should consider setting `no_found_rows` by default, and only enable it IF you need to count the posts.

Also please consider applying a filter to the query args (also giving some context - eg. `apply_filters('ampforwp_relads_posts_query_args', $args)`) so that people can integrate with other plugins - the one I have in mind is Elasticpress for related posts.

**Comment by ahmedkaludi** [comment]
@calind Thank you for the amazing find! We will act on this immediately

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
added in 1.0.35 in this commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/68960a10509e5d71ca5ca50189d50755d3fe0726

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
This fix breaks the Category module in AMP pagebuilder.

`no_found_rows' => true,` Disables the pagination automatically. 

So only add in the QUERY when pagination is disabled.

https://monosnap.com/file/9u9vPZiV5vcx5IlSNpnqLFb1c6xMQ1

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7113a76a1d3c03fb5fb8f26bd29e8aca7ad96ed7#diff-45752acf5e8ea05d2224fa9a73c54c7aR866

**Comment by MohammedKaludi** [comment]
Ready to go.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.37
