### ISSUE TITLE
Need to update AMP Allowed Tags (input ) in allowed tags sanitizer

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#4289]
We need to update the input tag array in class-amp-allowed-tags-generated.php.
currently, the input type file is missing from the array which causing the issue of input type 'file' tag missing in AMP form.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.35
