### ISSUE TITLE
Iframes are not working with WP optimize premium

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4290]
iframes are not working with WP optimize premium
Ref:
https://secure.helpscout.net/conversation/1095305645/113659?folderId=3611365

**Comment by MohammedKaludi** [comment]
wrap inside function_exists while mergeing.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0077ce7f8a7d100daa1b6ab2d1576c138acc51bd#diff-1301281de287d2aed98746fc9ba777b4R1113
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.35
