### ISSUE TITLE
Need to give feature for the changing the tags for the accordion module in AMP Page Builder

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4291]
Ref:https://secure.helpscout.net/conversation/1110549265/116951?folderId=2770545

We need to provide feature for the accordion module to change the tags. We show the title of the accordion by default in H3 tags but user wants to change it to H5 tags.

REF URL: https://pymesworld.com/diseno-paginas-web-wordpress/a-coruna/amp/

video link: https://www.loom.com/share/7dcc7b5aedd74109bfcee4def48afeb1

**Comment by Zabi09** [comment]
Added in #4208, So closing thie one
