### ISSUE TITLE
The attribute 'data-videoid' in tag 'amp-vimeo' is set to the invalid value 'ondemand'.( Validation error)

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4294]
Ref: https://secure.helpscout.net/conversation/1113261868/117421/

If the user is embedding the Vimeo videos through Gutenberg editor then he is getting the following error in AMP:
The attribute 'data-videoid' in tag 'amp-vimeo' is set to the invalid value 'ondemand'.( Validation error)

The issue is not occurring for every videos. It seems the issue is occurring for the paid videos.

The issue is also occurring on local.

Video URL for reference:  https://vimeo.com/ondemand/dceradaughter

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.35
