### ISSUE TITLE
 Need to make  compatibility  with the Read Meter – Reading Time & Progress Bar

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4295]
Need to make  compatibility  with the Read Meter – Reading Time & Progress Bar with AMP

Ref plugin:https://wordpress.org/plugins/read-meter/

ref:https://secure.helpscout.net/conversation/1113101944/117381?folderId=3575684

**Comment by fratposa** [comment]
Hi there, no news?

**Comment by MohammedKaludi** [comment]
Released an extension for this feature https://ampforwp.com/addons/reading-progress-bar-for-amp/
