### ISSUE TITLE
AMP Page Builder not working on the homepage

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4296]
Ref:https://secure.helpscout.net/conversation/1109517805/116710/

If the user is enabling the AMP Page Builder on the homepage and do the changes, It is not saving after refreshing the page.

The issue is occurring for only one page. It is not occurring for every page.

Steps to recreate the issue on local:
1. Import the XML file added in the Telegram group.
2. Set the Homepage as custom front page.
3. Enable the AMP Page Builder and then add any modules on the Homepage.
4. After doing all the changes save or update the page.
5. When we refresh it, All the AMP Page Builder modules get deleted.

**Comment by Zabi09** [comment]
The AMP pagebuilder was working as expected on all pages and even on homepage but it was not working on only one page maybe it was some issue only with that post ID but we have created a new page and added it as frontpage in AMP and now everything is working fine.
