### ISSUE TITLE
authour image is fixed in the static ratio 60x60 img 

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4297]
REF:https://secure.helpscout.net/conversation/1111279143/117075?folderId=3528427.
author image is fixed at the ratio on 60x60 in the amp version by using the wp-users avatars.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Image gone after inthe testing of the update.
https://monosnap.com/file/Y7AZhHklmeaJC7fgXoAnKetpZ0BMx5


this is the export: 
[redux_options_redux_builder_amp_backup_25-03-2020.json.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4383207/redux_options_redux_builder_amp_backup_25-03-2020.json.zip)

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.36 update
