### ISSUE TITLE
Related posts doesn't show more than 3-4 [Rare Issue]

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4300]
https://secure.helpscout.net/conversation/1106277168/116150/

If set to 1 - 3, it works, it doesn't show more than 4. Tested in Design 3 & Swift. 

It did not recreated on the localhost, however, this could potentially be an issue in core. 
https://secure.helpscout.net/conversation/1106277168/116150/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.36 update

**Comment by MohammedKaludi** [comment]
There is some performance improvements required

**Comment by MohammedKaludi** [comment]
FROM wp_posts
LEFT JOIN wp_term_relationships
ON (wp_posts.ID = wp_term_relationships.object_id)
INNER JOIN wp_postmeta
ON ( wp_posts.ID = wp_postmeta.post_id )
WHERE 1=1
AND wp_posts.ID NOT IN (1865145)
AND ( wp_term_relationships.term_taxonomy_id IN (13,21) )
AND ( ( wp_postmeta.meta_key = 'ampforwp-amp-on-off'
AND wp_postmeta.meta_value = 'default' ) )
AND wp_posts.post_password = ''
AND wp_posts.post_type = 'post'
AND ((wp_posts.post_status = 'publish'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.ID DESC
LIMIT 0, 5

**Comment by MohammedKaludi** [comment]
@ajeetku Need your review on this ticket in priority basis

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.37

**Comment by Zabi09** [comment]
Need to implement this in Facebook instance article also

**Comment by MohammedKaludi** [comment]
Use  `'fields' => 'ids',` 
in WP_Query args, it only fetches the post id of the posts in the query rather then the whole content. 

It will result in fast query as we  dont not need any other data.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2fdc4c40c4b7a6fb7b648c618f98839df0a5beee#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8464

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Code still needs improvement, call me when you start working on it.

**Comment by WasimM3** [comment]
Need to achieve the following
1. Move to tools section.
2. Automatic Trigger to update.
3. Use Option instead of Transient
4. On Uninstall remove clear option

**Comment by TMsravan** [comment]
Another user facing the same issue: https://secure.helpscout.net/conversation/1193178409/135663?folderId=2632030

Old related posts are not showing, only newly-created posts are getting displayed.

**Comment by amer07** [comment]
Another user:https://secure.helpscout.net/conversation/1250220682/147665/

Related posts not showing.

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://secure.helpscout.net/conversation/1336120468/164793

**Comment by MohammedKaludi** [comment]
Need to test the component thoroughly and make sure its working as expected and not having any adverse effect on the performance while rebuilding the meta information.

**Comment by MohammedKaludi** [comment]
https://monosnap.com/file/vbYBjMt01SXZEJKUCTzKJjbmgxZOOV


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/45d1c945eceb961332b607b871213402bb24f437#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580L8820

**Comment by Zabi09** [comment]
Pushed in 1.0.77
