### ISSUE TITLE
featured images are getting streched in the amp version

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4307]
Ref:https://secure.helpscout.net/conversation/1114486629/117653?folderId=3528427;

Featured images are getting stretched in the amp version as I have checked in the local to
the screenshots in the amp and non-amp(https://prnt.sc/rlnail )(https://prnt.sc/rlnbrd)
The dimension of the images should be flexible 

I am using the plugin called the featured image from URL
I have used this image
(https://user-images.githubusercontent.com/60213416/77423458-43323380-6df5-11ea-8291-2fe4e0f8f9bc.png)

**Comment by MohammedKaludi** [comment]
use `isset()` for the `$size[0]` and `$size[1]`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/938ca5ec1bbc324d0b369333c153d7667ea7ac10#diff-124aaba5bb04f0c209fee076b85b13b2R56

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
