### ISSUE TITLE
defer onload

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#431]
Remove defer onload 
And also check why http is getting stripped. Which 3rd party plugin is doing this.

Ref: http://take.ms/qvyAR
https://wordpress.org/support/topic/google-says-my-homepage-is-not-valid-amp/

**Comment by nicholasgriffintn** [comment]
I think my pull #440 should do the job to fix this.

**Comment by khaledMohammed000** [comment]
Waiting for mail from Pablo :)

**Comment by MohammedKaludi** [comment]
Looks ok.
