### ISSUE TITLE
amp child theme is not working from recent update.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4310]
https://secure.helpscout.net/conversation/1118507170/118510?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.36 update

**Comment by juniorbra** [comment]
I'm not able to update through the Wordpress panel. Where can I download version 1.0.36 to update via FTP

**Comment by MohammedKaludi** [comment]
You can download the zip from here: https://downloads.wordpress.org/plugin/accelerated-mobile-pages.1.0.36.zip
