### ISSUE TITLE
AMP setting panel is not showing when ""WPML for AMP" pluign is active.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4311]
The user is not able to see AMP Setting Panel(https://prnt.sc/rmbysh). getting blank page in amp settings. when we deactivate the "WPML for AMP" plugin then the AMP setting panel works properly.

Note: this issue is not occurring in the localhost.

Ref: https://secure.helpscout.net/conversation/1114266259/117604?folderId=3257665

**Comment by Zabi09** [comment]
Going to fix in WPML for AMP extension
