### ISSUE TITLE
Category module links in AMP pagebuilder are not changing into "/?amp" for related posts if "Change end point to?amp" is enabled.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4314]
Case 1:https://secure.helpscout.net/conversation/1117936088/118359?folderId=2770543

Category module links through adding AMP page builder, are not changing into "/?amp" for related posts if "Change endpoint to? amp"  is enabled it redirects to /amp.

Local recreate at my end.

**Comment by MohammedKaludi** [comment]
Ready to merfe

**Comment by MohammedKaludi** [comment]
pushed in 1.0.38
