### ISSUE TITLE
Issue while applying transparent header background-color.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4315]
When the user is applying a transparent header background-color from design > header > background-color. It is not applying in the front end.

Note: tested in localhost (latest version 1.0.35).
Video: https://monosnap.com/file/9UAlT6g4ZIOZYwGphuU7GQUKGu3rWq

Ref Ticket: https://secure.helpscout.net/conversation/1119082583/118625?folderId=3126461

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.37
