### ISSUE TITLE
Debug warnings in ampforwp_custom_og_image_homepage

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4321]
`ampforwp_custom_og_image_homepage()`

https://monosnap.com/file/xFBPgcbZ4hhk2DmZksjWLNNRmPZhU4

**Comment by MohammedKaludi** [comment]
Fixed here by wasim:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f5c5616b64b66fe2dc7c70bace71a51212943f2d

@ajeetku 
Need to make sure which is more stable that needs to be merged into the core.

**Comment by ajeetku** [comment]
In this f5c5616 
old code is more stable, because if we get image data from `wp_get_attachment_image_src` always gives us array either blank

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.38
