### ISSUE TITLE
Multiple Debug Warning

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4324]
[28-Mar-2020 15:41:58 UTC] PHP Notice: Undefined offset: 1 in /wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 7041
[28-Mar-2020 15:41:58 UTC] PHP Notice: Undefined offset: 1 in /wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 7038

Reference: https://wordpress.org/support/topic/error-php-notice-undefined-offset-4/

Notice: Undefined variable: izt_opt4 in \wp-content\plugins\accelerated-mobile-pages\includes\features\push-notification\push-notification-options.php on line 135

Notice: Undefined variable: izt_opt3 in \wp-content\plugins\accelerated-mobile-pages\includes\features\push-notification\push-notification-options.php on line 168

Notice: Undefined variable: izt_opt1 in \wp-content\plugins\accelerated-mobile-pages\includes\features\push-notification\push-notification-options.php on line 169

Notice: Undefined variable: izt_opt2 in \wp-content\plugins\accelerated-mobile-pages\includes\features\push-notification\push-notification-options.php on line 169

Reference : https://wordpress.org/support/topic/four-notices/

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.38
