### ISSUE TITLE
double quotes in the font-family breaks the default Typography

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4328]
- [ ] Disable Google fonts: https://take.ms/MbPPL

- [ ] double quotes should not be there, its breaking the default font-family: https://take.ms/RrNlI

https://secure.helpscout.net/conversation/1119296062/118706?folderId=3528427

**Comment by MohammedKaludi** [comment]
Ready  to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
