### ISSUE TITLE
Tablepress Tables don't Scroll Horizontally on AMP Pages

### ISSUE THREAD

**Issue by 7bhabesh** [ahmedkaludi/accelerated-mobile-pages#4329]
I am using the Tablepress plugin on my website. If I add more than 3 columns on Tables, the 4th/5th etc column don't show on AMP pages. Earlier it was working fine as the table scrolled horizontally. But after recent "AMP for WP" plugin updates, Tablepress Tables don't Scroll Horizontally on AMP Pages. Please fix the issue soon.

Example AMP Page with Tablepress (4 Column): https://www.dealntech.com/exynos-9611-vs-snapdragon-712-vs-helio-g90t/amp/

**Comment by Zabi09** [comment]
Going to fix in #4309

**Comment by MohammedKaludi** [comment]
@7bhabesh Thank you for raising the issue.

This issue will be fixed in #4309 and will be pushed in next 1.0.39 update, which is scheduled for next week.
