### ISSUE TITLE
AMP option panel is not working when Best brokers plugin is active.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4330]
Ref:- https://secure.helpscout.net/conversation/1120734131/118984?folderId=3243584

There are js errors in the console and the plugin is hiding the option panel tabs.
https://monosnap.com/direct/8bIbqRamBdazSVcJaikEUkMN0Y2aLy
https://monosnap.com/direct/Z5TDMhYuJhPwXdcYufJKLHZJW5VwZN

**Comment by MohammedKaludi** [comment]
add function exits

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
