### ISSUE TITLE
Need to integrate the "Call Rail" analytics integration

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4331]
Ref: https://secure.helpscout.net/conversation/1123823156/119727?folderId=2770545

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Missing from  **Basic Setup** section https://monosnap.com/file/ytUnL9YJ6IKwv4qMK8DQVLcBJFxzzC

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.42
