### ISSUE TITLE
Blank pages appear when we are using cloning posts 

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4332]
Blank pages appear when we are using cloning posts 

ref: https://secure.helpscout.net/conversation/1117539555/118304?folderId=3575684

**Comment by MohammedKaludi** [comment]
add check of `if exists ` to make sure it does not throw the validation error.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/58619481e155f99f5befdd1a76610a5a4d4cbdaf#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8374

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
