### ISSUE TITLE
Image is streching in the gallary

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4334]
Ref:https://secure.helpscout.net/conversation/1122092143/119280?folderId=3528427

Image is stretching in the gallery user is using the swift design

Ref URL link:https://strategycon.ru/grand-guilds/amp/

Ref screenshot:https://monosnap.com/file/SoBQAgZyoMm9EXmvx1XIoP3tI9plnQ

**Comment by Arskrigitsioniets** [comment]
A screenshot from my test page where you can see the problem with stretching more clearly: https://i.imgur.com/0PMXbOa.jpg

Also, there were large white areas before the update that stretched the images: https://i.imgur.com/BGJYPHk.png Then, when the plugin got the update, the white areas disappeared and were changed by stretched images.

By changing object-fit: property I get either a stretched image or white areas.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.39
