### ISSUE TITLE
Undefined variable error in query monitor. 

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4335]
User facing Undefined variable error in query monitor: 
Screenshot: https://monosnap.com/file/3TF34kxtVlWDQNOj9MO8NhiA5Qzt4v
Reference: https://secure.helpscout.net/conversation/1104726934/115896?folderId=673452

**Comment by MohammedKaludi** [comment]
Issue already reported and fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4324
