### ISSUE TITLE
Need to create a fliter to change post title tag.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4339]
Case 1:https://secure.helpscout.net/conversation/1124559724/119869?folderId=2770543

Example: The user can change post title as per this requirement it may be h1, h2, h3.... h6 tag.

**Comment by Zabi09** [comment]
add_filter('ampforwp_modify_title_tag','prefix_title');
function prefix_title($title){
$title = '<h5 class="amp-post-title">' . wp_kses_data( get_the_title(ampforwp_get_the_ID()) ) . '</h5>';
return $title;
}

**Comment by MohammedKaludi** [comment]
Ready for the merge.

**Comment by MohammedKaludi** [comment]
Pass one more parameter as `$ampforwp_title` in the filter.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6223f4cf500196f71bd0c8662bd98b390492d9ce#diff-b6438fc932bdcf0c8a01c3c146505c9eR126

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
