### ISSUE TITLE
The tag 'plusone' is disallowed

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#434]
The tag 'plusone' is disallowed

			<plusone href="https://www.droidextra.net/change-of-domain-name-from-android-tips-net-to-droidextra-org/"></plusone></div>&#13;

Here is the source: http://pastebin.com/wD56BSUx

**Comment by ahmedkaludi** [comment]
This was fixed in 0.9.40.

**Comment by heshamooo** [comment]
The tag 'plusone' is disallowed.

![image](https://user-images.githubusercontent.com/37954190/38162434-71959586-34e1-11e8-9953-47d39cb832e2.png)
