### ISSUE TITLE
If the "GDPR Compliancy" is enabled at users end then the menu link and the article links not working on the homepage

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4340]
Ref: https://secure.helpscout.net/conversation/1122805392/119522?folderId=2770545

If the GDPR compliance is enabled then user is not able to visit any link on the homepage like menubar links, articles link on the safari browser.

Steps to recreate the issue:

1. Change the VPN to European countries.
2. Use BrowserStack to check the issue.

The issue is occurring because GDPR is generating one layer which does not allow users to visit the links.

Screenshot: https://monosnap.com/file/xjfvsK8GeiQzU0Zpnl83BOmA7wSyTc

URL: https://www.meilleure-innovation.com/amp/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
