### ISSUE TITLE
When the user logged in as admin, strange error is showing

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4341]
PHP Notice at 
/var/www/vhosts/liesenfeld.de/httpdocs/WP/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 7487

$dom->loadHTML($title);

Reference: https://wordpress.org/support/topic/strange-error-31/

**Comment by ajeetku** [comment]
Do not use @ to remove notices of PHP dom extension. You can check in other dom used in the plugin.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
