### ISSUE TITLE
There is no save button in  AMP "Basic setup"

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4343]
In the AMP basic setup, user is using AMP-optin and not able to save changes. 
Note: the same issue is in localhost also.
Ref: https://secure.helpscout.net/conversation/1126177755/120214?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
