### ISSUE TITLE
Images are getting  streched in the newspaper theme of amp when it is rendering from CDN

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4344]
REF:https://secure.helpscout.net/conversation/1121158046/119073?folderId=3528427,

Des: Images are getting stretched in the newspaper theme of the amp when it is rendering 
through the CDN

REF:https://prnt.sc/rsb97v

**Comment by Zabi09** [comment]
Moved to trello
