### ISSUE TITLE
After activating AMP Extension manager "AMP Page Builder compatibility" is not updating

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4347]
If the user is using the AMP PRO Extension Manager and if he is going to update the "AMP Page Builder compatibility" plugin, it is redirecting it to the changelog. It is not updating the plugin.

The issue is occurring on my local as well.

**Comment by WasimM3** [comment]
It's fixed from server side so closing it
