### ISSUE TITLE
Auto Add AMP in Menu URL for product categories is not working

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4350]
https://secure.helpscout.net/conversation/1128222215/120641?folderId=2632030

I have tested in local and it is not working.

Use case at user end: In alternative it is working and in hamburger menu it is not working.

In my  local sytem in both cases it is not working./amp is not appending to the prodcut categories url in menu

https://www.hdcabling.co.za/amp/

https://secure.helpscout.net/conversation/1128222215/120641?folderId=2632030

Please see this video which I have tested in my local:

https://monosnap.com/file/DfQ4qtzep52buxm23ZhrjyzOSFF8AG

**Comment by Zabi09** [comment]
It will be fixed by clearing the transients please clear by just saving the menu again or by any third party plugin like transients manager.
