### ISSUE TITLE
Need to have an option for auto slide of images in AMP page builder - slider module. 

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4351]
The user is adding images in the slider module of AMP page builder which is working perfectly but the user don't want to use auto slide the images. so need to add an option such that 'images should be auto slide or not' (by default images are sliding automatically).

Exact Issue: https://monosnap.com/file/dYEqpyRFxK9N6azR7YGPnuvZrrh4hk

Ref URL:
https://secure.helpscout.net/conversation/1129255137/0/?folderId=3126461

**Comment by Zabi09** [comment]
Already added the autoplay option here - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3859 So closing this one
