### ISSUE TITLE
Video docking is not working in AMP.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4352]
User is trying to add below script:

<script async custom-element="amp-video-docking" src="https://cdn.ampproject.org/v0/amp-video-docking-0.1.js"></script>

But it is not rendering on the AMP version.

Ref Ticket:
https://secure.helpscout.net/conversation/1129265474/120992?folderId=3126461

Note: Tested in localhost.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update

**Comment by MohammedKaludi** [comment]
Incorrect fix so reverting the commit.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
1. Dock-on/off not working.

2.  should also work with `dock` attribute as well.  `<amp-video src="my-video.mp4" ... dock></amp-video>`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
code improvements done: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/985c9745e8e27f39a61da970f8c1129fb2382f83

**Comment by MohammedKaludi** [comment]
updated the code to work with amp-youtube but that needs imrpovement.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.43 update
