### ISSUE TITLE
due to the Post Grid by PickPlugins plugin the amp option panel is not working

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4353]
REF:https://secure.helpscout.net/conversation/1128866367/120869?folderId=3528427

Due to the post grid pick plugins, the amp option panel is not working

**Comment by Zabi09** [comment]
the amp option panel is not working because of his theme not by post grid plugin

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
