### ISSUE TITLE
Facebook instance article is not working when the permalink settings are in the plain

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4354]
Facebook instance article is not working when the permalink settings are in the plain.

ref:https://secure.helpscout.net/conversation/1126596869/120314?folderId=3575684

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.40 update
