### ISSUE TITLE
Compatibility with WebP Express plugin

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4357]
Reference:  https://wordpress.org/support/topic/amp-does-not-support-with-webp-express-plugin/

**Comment by hieptd** [comment]
I am applying for my plugin, but it is still not visible in Safari for iPhone even though Safari already supports Webp format.

**Comment by hieptd** [comment]
@Zabi09 - It seems that webp is not yet supported on iOS and older versions of macOS, I think developers should consider the option to display images in browsers that don't support webp.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by hieptd** [comment]
> ready to merge.

Hope it will be better

**Comment by hieptd** [comment]
> ready to merge.

How much longer will it be included in the update. I am too looking forward to it

**Comment by thegulshankumar** [comment]
If you're on Apache / LiteSpeed server, plugin can serve WebP automatically by rewriting via .htaccess. For NGINX you need to configure its rule. It's simple and elegant solution. Happy to help if you've any question.

**Comment by hieptd** [comment]
> If you're on Apache / LiteSpeed server, plugin can serve WebP automatically by rewriting via .htaccess. For NGINX you need to configure its rule. It's simple and elegant solution. Happy to help if you've any question.

It looks like it hasn't been included in the update yet

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.3 update

**Comment by Zabi09** [comment]
Images not appearing in related posts and recent posts

**Comment by eddie9999** [comment]
But this fix does not affect srcset. It's still the same .jpg

**Comment by Sasirekhamarella** [comment]
An issue with Featured Image preload and srcset.  
Reference ticket: https://wordpress.org/support/topic/featured-image-preload-and-srcset/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.8
