### ISSUE TITLE
when we click on the comment section the page is showing a 404 error  when "Site Kit by Google" plugin is activated

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4360]
when we click on the comment section the page is showing a 404 error when the "Site Kit by Google" plugin is activated.

 plugin Ref: https://wordpress.org/plugins/google-site-kit/

ref: https://secure.helpscout.net/conversation/1120675700/118978?folderId=3575684

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.42
