### ISSUE TITLE
 Embed pinterest images to the amp

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4361]
REF:https://secure.helpscout.net/conversation/1127905186/120564?folderId=3528427
Embed the Pinterest images on the amp.
REF Code:<a data-pin-do="embedPin" data-pin-lang="it" href="https://www.pinterest.com/pin/16958936079233089/"></a>
<script async defer src="//assets.pinterest.com/js/pinit.js"></script>

REF https://amp.dev/documentation/examples/components/amp-pinterest/

**Comment by MohammedKaludi** [comment]
Add ticket number while merging.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0f4c3b288a40c201bb166ddd10aff39d9190aa56#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4100

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.42
