### ISSUE TITLE
We need to enhance "Post type in loop" field to select multiples values.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4365]
Please check with the below screenshot:

https://prnt.sc/rz0y2t

In the above optional field we need to create an option to select multiple values like posts, videos etc..not only for a single value.

For example, in the exclude category field we will select multiple categories. similarly, we need to add multiple values in the "post type in loop" field.

Ref Ticket: https://secure.helpscout.net/conversation/1134915678/122550?folderId=3126461

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
