### ISSUE TITLE
In AMP page builder,  category module's pagination is not working when amp cache is enabled

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4367]
In AMP page builder,  category module's pagination is not working when amp cache is enabled

And also when we go the second page,  the page again starts from the top, so we we need to scroll it down where the category module is present.

https://secure.helpscout.net/conversation/1113329842/117432?folderId=2632030

Issue recreated in local.

Please see this video for referece:https://monosnap.com/file/OMMH5WzdzdSa1IfFfoCE6KLtinucpU

**Comment by Zabi09** [comment]
Will you please remove your contents-module.php file and replace it with this and let us know
[contents-module.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4481680/contents-module.zip)

**Comment by arundhati1213** [comment]
Hi Syed,
I have replaced the contents-module.php from this path - accelerated-mobile-pages/pagebuilder/modules
Still the same issues are appearing. 
1) When I click on pagination page no 2 it's active the 3 page.
2) Focus shift problem is there
Kindly check this url - https://test.bondevalue.com

Thanks

**Comment by arundhati1213** [comment]
https://monosnap.com/file/IHg7F9uLsjSeVk1DBrmVj3zV8KRnMD
please check the screen recorder - https://monosnap.com/file/IHg7F9uLsjSeVk1DBrmVj3zV8KRnMD

**Comment by Zabi09** [comment]
Fixed in AMP cache extension

**Comment by arundhati1213** [comment]
Do I update the cache ext. or what?

**Comment by merajali294** [comment]
@arundhati1213 ,Yeah you can update the AMP Cache Extension to 2.2.5 which will resolve the Pagination issue.

**Comment by arundhati1213** [comment]
First and last button on pagination does not scroll down to blog. Can you please fix this?

**Comment by arundhati1213** [comment]
@merajali294 First and last button on pagination does not scroll down to blog

**Comment by arundhati1213** [comment]
> @arundhati1213 ,Yeah you can update the AMP Cache Extension to 2.2.5 which will resolve the Pagination issue.

@merajali294 First and last button on pagination does not scroll down to blog, Can you please check it now?
Really it's been 2 months still we are facing the issues.
