### ISSUE TITLE
Sidebar showing on the front end on the "Hebrew" language bog post

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4371]
Ref: https://secure.helpscout.net/conversation/1127120892/120393?folderId=2770545

Steps to create:

1. Go to www.saveatrain.com/blog/
2. Pick an article you didn't read before
3. Click the Hebrew flag

On the first time you will see the menu all over the screen.
Screenshot: https://monosnap.com/file/IvSLIezZoAm9tN0hQTZdDEkput7gI3

**Comment by Zabi09** [comment]
Fixed the issue on the users end
