### ISSUE TITLE
Remove the Google index on AMP pages

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4372]
User doesn't want to google index his amp pages like this: 

http://www.sitename.com/amp/page2
http://www.sitename.com/amp/page3
http://www.sitename.com/amp/page3

He needs google index on the home page, category pages, and posts .

Reference: https://wordpress.org/support/topic/how-i-can-stop-index-pages/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.43 update
