### ISSUE TITLE
Need to add an option to choose how the pagination url should be,under the page break option

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4373]
Need to add an option to choose how the pagination URL should be, under the page break option:

Use case: At the user end the singal post page navigation URL are not validated by the google as showing error,  Referenced AMP URL is not an AMP

Pagination in the post is done by using the page break.

Example this URL: https://www.siasat.com/photos-lockdown-mumbai-1871291/2/?amp=1

The above URL is showing an amp version when it is logged in and in the incognito mode, the amp version is not showing.

https://search.google.com/search-console/amp/drilldown?resource_id=https%3A%2F%2Fwww.siasat.com%2F&item_key=GgQIGRAD

**Comment by sonaliramteke** [comment]
It is not working in 1.0+  - https://prnt.sc/t4v57u

**Comment by MohammedKaludi** [comment]
not working with Gutenburg next page block

**Comment by WasimM3** [comment]
Tested it by deploying on the siasat stating site and it's working as expected.

**Comment by ahmedkaludi** [comment]
- [ ] If the user is on Page 2 or beyond, it shouldn't show the featured image, see: https://take.ms/Uggyy

**Comment by MohammedKaludi** [comment]
Instead of calling `get_query_var` multiple times, why not call near `<?php amp_header(); ?>` at the very top and use it through out the page.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/53fb5cd63df0a6e57fab0ee3719bfeac8ad1dedd#diff-7d3a92ac5e6165548bf9bc556f4f887aR23

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Not working: 

- [ ]  in this permalink format https://monosnap.com/file/ict3363kBEYldbu5H55xLRRIzxOPYG

- [ ] Content is not sanitizing 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3a8d24c59eff63c44d1d5a101262dfa0c3e99e7b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3962
and 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3a8d24c59eff63c44d1d5a101262dfa0c3e99e7b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4122

Add an image, gallery and video on sub pages and test it.

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69 update
