### ISSUE TITLE
white spacing in the responsive mode on left side

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4375]
[redux_options_redux_builder_amp_backup_18-04-2020.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4496559/redux_options_redux_builder_amp_backup_18-04-2020.zip)

REF:https://secure.helpscout.net/conversation/1131116707/121712?folderId=3528427
User is using design3
REF screenshot:https://prnt.sc/s1qg7k

**Comment by MohammedKaludi** [comment]
READY to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.43 update
