### ISSUE TITLE
Need to add the pop-up option of the one signal which should display on the desktop 

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4377]
Need to add the pop-up option of the one signal which should display on the desktop.

ref:https://secure.helpscout.net/conversation/1132475241/121972?folderId=3575684

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.15
