### ISSUE TITLE
AMP Lightbox is not working on the Single images,it is working on the Gallery images only.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4378]
[redux_options_redux_builder_amp_backup_18-04-2020.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4496676/redux_options_redux_builder_amp_backup_18-04-2020.zip)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.43 update
