### ISSUE TITLE
Facebook comments for AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#438]
Facebook comments for AMP

**Comment by pram22** [comment]
I am waiting for this.
Hope this features release soon :D

**Comment by ahmedkaludi** [comment]
Ticket #289 closed and resuming here

**Comment by pegazee** [comment]
The progress of this ticket can be viewed in #825 as both are same.
So @MohammedKaludi close this ticket.

**Comment by MohammedKaludi** [comment]
@pegazee Done :)
