### ISSUE TITLE
Add support for Mautic

### ISSUE THREAD

**Issue by nisiwi** [ahmedkaludi/accelerated-mobile-pages#4381]
AMPforWP supports Matomo open-source analytics, however, no provision for open source marketing automation tools like Mautic (and their tracking scripts) has been included in the plugin config.

As a temp fix could we inject the tracking method through a hook of some kind ?

**Comment by MohammedKaludi** [comment]
Hey @nisiwi,

Can you please share the link where we can see the example of Mautic Tracking script and also do their tracking supports AMP?

**Comment by nisiwi** [comment]
Here's some info on their tracking script:

https://docs.mautic.org/en/contacts/manage-contacts/contact-monitoring

Don't believe they currently supports AMP, however given their recent acquisition by Acquia a lot of new development is planned and requests are starting to come in:

https://forum.mautic.org/t/support-for-amp-websites/13327

**Comment by ahmedkaludi** [comment]
Currently there isn't any support for Mautic Tracking, once it's there, we will re-open this integration request
