### ISSUE TITLE
Detect the Mobile redirection config to avoid manual tasks

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4382]
https://ampforwp.com/tutorials/article/how-to-redirect-all-mobile-visitors-to-amp/#6-how-to-enable-mobile-device-caching-in-sg-optimizer

**Comment by Zabi09** [comment]
Not added for W3 Total Cache as it showing "always enabled"

**Comment by sonaliramteke** [comment]
It is not working in Litespeed cache

**Comment by MohammedKaludi** [comment]
Ready to go

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update
