### ISSUE TITLE
Validation errors when adding 2 columns in AMP pagebuilder 

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#4383]
Import this file in AMP page builder to recreate it
[layout-21042020.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4510184/layout-21042020.zip)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58 update
