### ISSUE TITLE
AMP Not Working 

### ISSUE THREAD

**Issue by dewanrk** [ahmedkaludi/accelerated-mobile-pages#4384]
I got a message Malformed URL found for attribute 'href' in tag 'a'.

Website URL: https://reviewsgeek.com/get-a-2500-worth-amazon-gift-card/

**Comment by MohammedKaludi** [comment]
Can you please share more info where are you getting the error ?

Because on AMP validator it says page is valid. https://monosnap.com/file/gtB6aBjdSSu2vXy8KzmdC6oKmfOrn8

**Comment by dewanrk** [comment]
Problem solved thanks
