### ISSUE TITLE
Shortcodes should not show in meta descrption

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4385]
Ref: https://secure.helpscout.net/conversation/1144108022/124467?folderId=2770545
Screenshot: https://take.ms/mInoY
Screenshot: https://prnt.sc/s3xemb

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.43 update
