### ISSUE TITLE
Hello, again I have this problem with the latest AMPForWP updates.

### ISSUE THREAD

**Issue by antoniomanco** [ahmedkaludi/accelerated-mobile-pages#4386]
Hello, again I have this problem with the latest AMPForWP updates.

The AMPForWp plugin filter to not display articles in Instant Articles does not work. Even though I click on “No” for the posts that I don’t want to show in Instant Articles (For monetization policies), all of my site’s publications appear in my site’s feed https://antoniomanco.com/instant_articles

This has caused me to receive several AI alerts. I did tests by deactivating all the caches and the problem remains.

You guys solved this problem a few months ago, so I include the support link in wordpress and Github.

- https://wordpress.org/support/topic/problems-with-instant-articles-feed-filter/

- https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3891

Thanks for the support

_Originally posted by @antoniomanco in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3891#issuecomment-617895636_

**Comment by MohammedKaludi** [comment]
Get a review from before merging @WasimM3 

I think this is not required as this fix is done in #4300

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.43 update
