### ISSUE TITLE
Need to add an option to show post according to the" Updated date" in the instant article.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4389]
Need to add an option to show the post according to the" Updated date" in the instant article.

Ref:https://secure.helpscout.net/conversation/1140003386/123606?folderId=3575684

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
