### ISSUE TITLE
Blank class in archives loop and loop on homepage.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4390]
Archives:- https://monosnap.com/direct/gzMG7VKhVKvQVT4u8jMKWKjw7wFRsP

Homepage:- https://monosnap.com/direct/b5bT0hz8ruQM0meyNWAx3p55KADs1Y

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update
