### ISSUE TITLE
Fatal error in extension customizer:- Due to trucking theme

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4391]
https://secure.helpscout.net/conversation/1138250284/123249?folderId=3243584

https://monosnap.com/direct/ZXVp48jqlccBLBNP0nMcHwc5jzhkYG

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update
