### ISSUE TITLE
Content  links unclickable with Amp-consent

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4392]
The top:0 is adding and that could cause the problem

 https://prnt.sc/s44snx

https://www.google.com/amp/s/www.blogamico.it/spiare-whatsapp-conoscendo-numero-1335.html/amp

Reference: https://wordpress.org/support/topic/content-links-no-work/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.45
