### ISSUE TITLE
If the "?amp" is enabled and then "amphtml" is generating wrong URL for category pages

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4393]
Screenshot: https://prnt.sc/s4o8o8

The issue is creating on localhost. When we enable the "?amp" support then for the category pages it is generating link of a random post instead of category pages in AMP.

LINK: https://staging1.etramping.com/destinations/?amp

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update
