### ISSUE TITLE
Need to render shortcode placed through Yoast's visual editor in categories description.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4394]
Here we have two issues interconnected with extension & core.

- [ ] We Need to render Image gallery shortcode placed through Yoast's visual editor in categories description. (Core)
 Steps to recreate the issue:
1) Need to install Yoast plugin in the localhost.
2) Generate an image gallery shortcode.
3) Now place the shortcode in Category content (screenshot: https://prnt.sc/s4pujx )
4) Now check the category page.

- [ ] User is placing UX builder's gallery shortcode in product categories description, we need to fix this at user end. (Extension)

Screenshot:  https://prnt.sc/s4q06w
Issue URL: https://flowerportal.in/cakes/amp

Ref Ticket: https://secure.helpscout.net/conversation/1141898755/124045?folderId=3126461

**Comment by Zabi09** [comment]
Fixed on the user's end, So closing this one
