### ISSUE TITLE
Entities instead of UTF-8 in footer json

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4395]
Reference: https://wordpress.org/support/topic/entities-instead-of-utf-8-in-footer-json/

https://wordpress.org/support/topic/html-entities-creater-in-social-description-content/

**Comment by Zabi09** [comment]
For testing, you can add this - Κι ο θάνατος

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update

**Comment by chopinesque** [comment]
This appears fixed, apart from the ellipsis entity being used at the end:

`ξηλώνουν νήματα απόμερα τα πλένουν στη &hellip;`
