### ISSUE TITLE
The white space is adding in the srcset of the image

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4396]
The attribute 'srcset' in tag 'amp-img' is set to the invalid value 'https://syncopatedtimes.com/wp-content/uploads/2020/04/Lee- Konitz-young-300x225.jpeg 300w, https://syncopatedtimes.com/wp-content/uploads/2020/04/Lee-Konitz-young-1024x768.jpeg 1024w, https://syncopatedtimes.com/wp-content/uploads/2020/04/Lee-Konitz-young-200x150.jpeg 200w, https://syncopatedtimes.com/wp-content/uploads/2020/04/Lee-Konitz-young-768x576.jpeg 768w, https://syncopatedtimes.com/wp-content/uploads/2020/04/Lee-Konitz-young-24x18.jpeg 24w, https://syncopatedtimes.com/wp-content/uploads/2020/04/Lee-Konitz-young.jpeg 1200w'.

Ref: https://secure.helpscout.net/conversation/1144561823/124561?folderId=2770545

Screenshot: https://prnt.sc/s54vgq
Screenshot2: https://prnt.sc/s54ytq

**Comment by HaripriyaHari** [comment]
One user have the same issue.
The attribute 'srcset' in tag 'amp-img' is set to the invalid value https://www.aktuelbilgiler.com/sac-botoksu-nedir/amp/

Reference: https://wordpress.org/support/topic/disallowed-attribute-or-attribute-value-present-in-html-tag-10/

**Comment by WasimM3** [comment]
A card is created on trello. So closing this ticket
