### ISSUE TITLE
Page builde Modules are not displaying above the background video of the row.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4398]
https://secure.helpscout.net/conversation/1145560404/124736?folderId=2632030

Use case: when we add the youtube as the background video for the row,and then we add the page builder modules in that row.Those modules are not displaying in that row they are displaying below the video.

Ref: https://wordpress-123147-847862.cloudwaysapps.com/caldera-form-test-2/amp

https://secure.helpscout.net/conversation/1145560404/124736?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to go

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update

**Comment by MohammedKaludi** [comment]
Ready

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.49 update
