### ISSUE TITLE
Next Page is shitting to the top of the page when it clicked on the pagination of category module from amp page builder

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4401]
https://secure.helpscout.net/conversation/1113329842/117432?folderId=2632030

https://test.bondevalue.com/amp/

Next Page is shitting to the top of the page when it clicked on the pagination of category module from amp page builder.

when we click the next page 2 of the category block again the page starts from the top and we need to scroll down toward the category moudle.

**Comment by MohammedKaludi** [comment]
If we add multiple blocks it will show console warning as same Id is defined and used multiple times.

Add module id with the id, so it creates unique id for every block

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update

**Comment by TMsravan** [comment]
https://monosnap.com/file/BkaQCJJVF589MnMnSSdyY9aeDKezSS

First and the last button with the alphabetic letters on pagination does not scroll down to the blog

https://secure.helpscout.net/conversation/1113329842/117432?folderId=2632030

**Comment by arundhati1213** [comment]
@Zabi09 Last button is not working

**Comment by Zabi09** [comment]
@arundhati1213 I have checked your website and the last one is also working fine, Will you please check once now and let us know

**Comment by arundhati1213** [comment]
@Zabi09 it's working fine now. One things need to confirm that we have 4 websites where we used AMP.
Do you need to modify this code in all 4 websites or it will be fixed once I update the AMP cache ext.?

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
@arundhati1213 We are going to push the update today so make sure you update our plugin to the latest version and also make sure you are using AMP Cache 2.2.5 Version or above on all your websites and that will fix all your issue and you no need modify any code

**Comment by arundhati1213** [comment]
@Zabi09 Thanks for the update. please inform us once you are done 
Yes I updated the cache ext 2.2.5 version

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update
