### ISSUE TITLE
CSS syntax error in tag 'style amp-custom' - incomplete declaration.

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4402]
Screenshot: https://monosnap.com/file/G9dcLfruo6IH8SAb0CQ7LV1IWr83kh
Maybe this issue related to https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4396 

Reference: https://wordpress.org/support/topic/disallowed-attribute-or-attribute-value-present-in-html-tag-10/

**Comment by WasimM3** [comment]
This issue is connected to the ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4396, and for this card is created on trello. So closing this ticket
