### ISSUE TITLE
Need to add end point in lincence key  for agency users

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4404]
@amer07 commented on [Sat Apr 25 2020](https://github.com/ahmedkaludi/pwa-for-wp/issues/369)

Case 1: https://secure.helpscout.net/conversation/1142996369/124250?folderId=2770543

---

@ahmedkaludi commented on [Sun Apr 26 2020](https://github.com/ahmedkaludi/pwa-for-wp/issues/369#issuecomment-619452927)

This needs to be built into AMPforWP

**Comment by WasimM3** [comment]
Pushed code in ampforwp_custom_plugin. moving direct to approval @MohammedKaludi Sir review it and can close directly, if there is no issue.

**Comment by MohammedKaludi** [comment]
was built here: https://github.com/ahmedkaludi/ampforwp-custom-plugin

**Comment by MohammedKaludi** [comment]
Fixed and working.
