### ISSUE TITLE
rel="canonical" is missing on the AMP Homepage and "/amp" is getting indexing on Desktop Google Seach

### ISSUE THREAD

**Issue by epilateuravis** [ahmedkaludi/accelerated-mobile-pages#4405]
I'm using the Latest Version of AMPforWP plugin and I'm using a custom page as my Homepage and the same has been selected on the AMP Settings.

But today I observed that my /amp version of the homepage is getting listed on the Google Search when I checked my Index on Desktop.

Here's the AMP URL of the Homepage: [https://epilateur-avis.com/amp/](https://epilateur-avis.com/amp/)

I checked the source code and found there's no "rel=canonical" tag to the actual homepage URL. Can you please check and fix the issue?

**Comment by MohammedKaludi** [comment]
This is very strange. 

@Zabi09 do look into this first thing in the morning.

**Comment by Zabi09** [comment]
@epilateuravis I have checked your issue and found that everything is working as expected you have both canonical and amphtml in your normal page - https://monosnap.com/file/8IjN3oSGOYPrsHydBMjqNuAaic2yfW and you do have canonical in your AMP homepage - https://monosnap.com/file/mehLO0X0dxReftARRNZI76H7Mxgvy3

Will you please check once and let us know

**Comment by epilateuravis** [comment]
Thanks @MohammedKaludi for assigning the issue to your team.

@Zabi09 Thanks for the confirmation. That's strange, Even I see the canonical tag on the /amp page's source code now. When I opened the issue the code wasn't there on the /amp page.

So now it's there on the source code, my indexing issue will be solved right. BTW, Can you take a look at "site:epilateur-avis.com" on Google to see the /amp page being indexed?

Looking forward to your reply.

**Comment by Zabi09** [comment]
@epilateuravis Currently your AMP pages have not been indexed and it will be indexed by Google automatically which means you no need to do anything, So please wait for 3-4 days and I hope your AMP pages will get indexed in Google.

**Comment by Zabi09** [comment]
@epilateuravis So I am closing this ticket now as canonical is appearing fine

**Comment by epilateuravis** [comment]
![image](https://user-images.githubusercontent.com/64375320/80404980-d4724b00-8876-11ea-9adc-e6784e580cbf.png)

Actual there's a Indexed page which is why I opened this issue. No problem, I'll give it some more time to see if the amp is removed from the Index or not.
