### ISSUE TITLE
When the amp theme framework enables than no content will shown on theme section.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4408]
Case: 1https://secure.helpscout.net/conversation/1146554267/124932?folderId=2770543

When the amp theme framework enables than no content will load on the theme section, it should be plain.

See this screenshot: https://prnt.sc/s6jpba

**Comment by MohammedKaludi** [comment]
Why 123 added ?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3b487c5f594f87423c627bda8a52715da08e4078#diff-260eba6333c3222e59a6aed22ac5ab37R3641

**Comment by MohammedKaludi** [comment]
also need to make sure that it doesnot show with design 1,2 & 3

**Comment by MohammedKaludi** [comment]
https://monosnap.com/file/NSBMQqiC2n3oUNS9dWsATsm6eFsC3d

**Comment by Zabi09** [comment]
Yes bhai it will not show when ATF is selected

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update
