### ISSUE TITLE
Create an option to display the GDPR bar at top or bottom.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4409]
https://secure.helpscout.net/conversation/1147137765/125038?folderId=3243584
https://monosnap.com/direct/hXjDfORQK1YQEEZvPEVV26XUlgoOti

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
