### ISSUE TITLE
Fetal error with the yoast (14.0 ) latest update

### ISSUE THREAD

**Issue by WasimM3** [ahmedkaludi/accelerated-mobile-pages#4412]
Uncaught Error: Too few arguments to function ampforwp_custom_twitter_image_homepage(), 0 passed in C:\xampp\htdocs\wpsite\wp-includes\class-wp-hook.php on line 288 and exactly 1 expected in C:\xampp\htdocs\wpsite\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 1503

**Comment by HaripriyaHari** [comment]
Same issue for another user: https://wordpress.org/support/topic/fatal-error-in-homepage/

**Comment by MohammedKaludi** [comment]
The further compatibility will be added in this ticket. https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4415
