### ISSUE TITLE
Subscribe to notification text not displaying when One signal is turned on in AMP option panel. 

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4413]
https://secure.helpscout.net/conversation/1148670771/125475?folderId=3243584

The bell icon is displayed but not the text https://monosnap.com/direct/dNNbHwLxLY89I0yzz028qAmPoMyayG

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update
