### ISSUE TITLE
Scary banner in frontpage

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4414]
https://take.ms/wMTsA

**Comment by MohammedKaludi** [comment]
Need spacing in the banner.

https://monosnap.com/file/HaQD75bhxoIVtdcDRZXxmOtp5YxYD0

**Comment by MohammedKaludi** [comment]
Remove X mark from the https://monosnap.com/file/nS88KfC6OM3kuVKJfEd0iaoFzIBj5e

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
