### ISSUE TITLE
Need to update the code as per new update of Yoast 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4415]
These following code has to be updated to the latest version of Yoast (v14+) because these genius developers did not created a fallback for their old code.

Adding the screenshot just for the reference.
https://monosnap.com/file/JP4dVu3QSC7WX0JE8J6jWenkuzH4BQ

Need to make sure these things are working properly with latest AMPforWP and Yoast.

- All the title tags, meta descriptions and robots tags are working with old and new version
- All the opengraph tags are working properly with new and old version
- all the above tags are loading properly in Posts, Pages, custom frontpage, AMPforWP Pagebuilder page and archive/tags/search pages
- All the tags are loading properly with Design 1,2,3, swift, AMP theme framework, AMP Newspaper theme and AMP Layouts
- Schema Generated by Yoast should be same on the above mentioned pages
- Rel canonicals should be same on all the pages, including pagination pages in Home, archive and search pages

**Comment by MohammedKaludi** [comment]
Need to update this function also: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/769c38595c891bba83e11cfb747955df098ebf20

**Comment by MohammedKaludi** [comment]
@zabi09 

https://wordpress.org/support/topic/sc-pipe-in-the-title-of-page/

One user is facing the issue. Need to make sure this type of issues are fixed with AMPforWP and yoast.

**Comment by Zabi09** [comment]
Yes it will be fixed by the above commits

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.45
