### ISSUE TITLE
Need to create Hooks in Instant Article.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4417]
Need to create hooks in Instant Article so that users can add adding code to it according to their needs.

Ref: https://secure.helpscout.net/conversation/1147308767/125104?folderId=3257665

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9e8d62a4575d072e2cf5f66b86925e20962b846d#diff-6dbf3bfd469ab6187b7b08e4d2c61abeR13

Look placement seems incorrect.

**Comment by MohammedKaludi** [comment]
ready to merge,

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
