### ISSUE TITLE
Need to make compatibility for custom permalinks.

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4418]
REF :https://secure.helpscout.net/conversation/1136353435/122888?folderId=3611365
Video Ref  https://api.monosnap.com/file/download?id=7aJ6OlPpjREMBudNF8YqIRbHgshSkT

User is using LVSR Knowledge base Theme to add custom category.
https://themeforest.net/item/lore-elegant-knowledge-base-wordpress-theme/16965024
https://preview.lsvr.sk/lore/knowledge-base/theme-installation/

**Comment by Zabi09** [comment]
Going to add the fix in this ticket here - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4478

So closing this one
