### ISSUE TITLE
Exclude shortcodes from Excerpts

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#442]
Shortcodes need to be excluded from excerpts.

http://www.femalevenue.com/?amp

**Comment by nicholasgriffintn** [comment]
I believe that my pull #443 should work for fixing this.

**Comment by khaledMohammed000** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3c437a7dc8ce256b7a45f8cefa9635685f2249bf
