### ISSUE TITLE
Issues with photo gallery plugin.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4421]
Case 1: https://secure.helpscout.net/conversation/1145299286/124689?folderId=2770543

- [x] the issue will come when inserting two galleries

- [x] Need to collect correct images, it picks random from gallery

****Recreate in local****

**Comment by sonaliramteke** [comment]
Gallery next previous button is not visible

**Comment by WasimM3** [comment]
Tested it multiple times in different systems it's working as expected.

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58 update
