### ISSUE TITLE
GFYCAT sister site RedGIFs embeds break site

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#4422]
Hello, GFYCAT is moving to REDGIFS for adult content in few weeks and if I replace gfycat embed with gfycat, it breaks amp pages with error

CSS syntax error in tag 'style amp-custom' - invalid declaration.

this is because hundreds of lines of extra code appears on css custom, please make this priority

**Comment by djixas** [comment]
Can this get a priority? The redgifs will force users to switch from fycat on may 12 ar may 14 and that means if your plugin doesn't work by then, it will cause millions of posts to become invalid all over the web

**Comment by Zabi09** [comment]
I have added one Gfycat and it is working fine - https://amptest123.000webhostapp.com/hello-world/amp/

Will you please elaborate more about your issue so that we can recreate on our end and fix it

**Comment by djixas** [comment]
Yes, it says REDGIFS, not GFYCAT

**Comment by Zabi09** [comment]
Can you please give me the URL where you are having an error so that I will check and let you know

**Comment by djixas** [comment]
Embed any REDGIFS URL, https://www.redgifs.com/watch/negligibledeficientauklet-small-tits-blonde-asian-boobs for example, in your amp test site :)

**Comment by Zabi09** [comment]
GitHub is for technical precise issues please contact us on https://ampforwp.com/support/ and our team will help you to fix your issue

**Comment by ahmedkaludi** [comment]
@Zabi09 was this issue actually re-occurred on your end?

**Comment by amer07** [comment]
To recreate this issue, add this css code in global.

div. {
            position: relative;
            padding-bottom: 177.78%;
            )
        }

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
