### ISSUE TITLE
When using Subdomain and enabling Auto Add AMP in Menu option the url is not getting properly.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4423]
Desc: When using Subdomain and enabling Auto Add AMP in Menu option the url is not getting properly.

Desc:  https://secure.helpscout.net/conversation/1131908317/121883?folderId=3126461

**Comment by MohammedKaludi** [comment]
Ready to mege.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update
