### ISSUE TITLE
Need to make the table fromat look like same as amp by automatic's table output

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4424]
Need to make the table look like same amp by automatic such as responsiveness, images, and the colums need to fix with in the screens in mobile large screens at 425px like the same as amp by atuomatic

Amp by automatic ouput in mobile large screens at 425px:

https://monosnap.com/file/Sgw9GJfqmOwkTaB07NmdcFXgwo56B6

Amp by automatic ouput in mobile small screens at 320px:

https://monosnap.com/file/AP4M0dVugjZ55cpZmWs56hYhg30M5y

Amp by automatic ouput Desktop view:

https://monosnap.com/file/LJV9yCtkIMiu0eXZguNl7vLIIbvxPv

But when comes to ampforwp output:

There are some design issues,like mentioned below. as the output of the ampforwp should be the same amp by auotmaic

AMPfroWP ouput in mobile large screens at 425px:

In Desing 3: https://monosnap.com/file/9ZX8dVJ28PsLAKDYvBPfKxR6pGS7NG

Issue1#: image is getting displyed small.

AMPfroWP ouput in mobile large screens at 320px and 375px as well:

In Desing 3:https://monosnap.com/file/RM2OHs3xYlLd6cK8GhYzbzUbbfSPv9

Issue2#: Images are not getting displyed and the coulmn headings are misalligned

at 375px mobile medium screens: https://monosnap.com/file/VdQrLdQPHXeJfaEP11oGTiCI91mSNL

In swift design at 425px:

issue#3: https://monosnap.com/file/kTFFMExNOcMZ3X9P1iWiO0axhmDXeY

Image is looking small and image alignment is at the top and need to be in center.

https://monosnap.com/file/LqSSRy7qN23wO2PZilrAJ3wQriUsDL

https://secure.helpscout.net/conversation/1147125447/125033/

**Comment by sagar772** [comment]
Thank you @TMsravan for adding the issue after so much of discussion over the emails. 
I hope I'll get the tables just like the AMPbyAutomattic now. Hope it will be fixed soon.

**Comment by Zabi09** [comment]
If anyone wants to make the table to look similar to the AMP by Automattic then you can use copy the below CSS and add it in custom CSS option of our AMP panel

table {
    display: block;
}
table amp-img {
    width: 130px;
}
.single-post .amp-wp-article-content amp-img {
    max-width: 50%;
    margin-left: 35px;
}
.wp-block-table table th:first-child {
    text-align: center;
}
.wp-block-table table th {
    background: #fff;
    color: #000;
    border: none;
}
td strong {
    font-weight: 800;
    color: #000;
}
.wp-block-table table td {
    color: #000;
    padding: inherit;
}
a.maxbutton-1.maxbutton.maxbutton-view-on-amazon {
    color: #0a89c0;
    text-decoration: underline;
}
.wp-block-table.is-style-stripes tbody tr:nth-child(odd) {
    background-color: #f3f4f5;
}
table th {
    padding: 10px 0;
}

table tr {
    text-align: inherit;
    padding-left: inherit;
}

**Comment by sagar772** [comment]
Hi team,

The table is still not like the AMP by Automattic. It would be better to
have the same exact table just like the AMP by Automattic. (PFA)

Please check it.

Regards,
*Sagar Verma*

**Comment by Zabi09** [comment]
We have made our table to look similar to the amp by automattic plugin by giving you the above CSS but if you need exactly 100% same then you need to add your own custom CSS as it is open source project we cannot do exactly same to same like that but we have tried our best to make it similar.

**Comment by sagar772** [comment]
Hi, after using the code, some of the hyperlinks are black in color while others are blue. What is the issue?
Check the table here
https://urbanhomecart.com/best-dishwasher-india/amp/
![Issue](https://user-images.githubusercontent.com/64630272/99382333-6c5a8380-28f2-11eb-9d0d-6dfee1ef12e6.jpg)
