### ISSUE TITLE
Need to create option for showing only the primary category in category breadcrumb.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4427]
Nee to create an option for showing only the primary category in category breadcrumb.

URL: https://eleftherostypos.gr/ellada/567855-karamanlis-kanenas-den-tha-mpei-se-mmm-xoris-maska/amp/

screenshot: https://prnt.sc/s9ktbs

Ref: https://secure.helpscout.net/conversation/1147737569/125224/

**Comment by Zabi09** [comment]
This issue was not for breadcrumb but for category text which will be below the breadcrumb, So we can add the CSS to fix it, So closing this one
