### ISSUE TITLE
drawer css class From admin-style.css is geeting conflict with the Ninja Tables css and hiding their colums in option panel 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4428]
Please see this video it is clearly shown Ref: https://monosnap.com/file/spwMtq9hhsKCofyJRGpj6QpfE1opBb

https://secure.helpscout.net/conversation/1152881498/126508?folderId=2632030

Plugin:https://wordpress.org/plugins/ninja-tables/

This is the class:
.drawer {
max-width: 375px;
box-shadow: 0px 8px 10px -5px rgba(0, 0, 0, 0.2), 0px 16px 24px 2px rgba(0, 0, 0, 0.14), 0px 6px 30px 5px rgba(0, 0, 0, 0.12);
width: 75%;

http://localhost/wordpress/wp-content/plugins/accelerated-mobile-pages/includes/admin-style.css?ver=1.0.45

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 update
