### ISSUE TITLE
Menu links and internal links are not working if visiting the link through the Google CDN

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4429]
Ref: https://secure.helpscout.net/conversation/1153796021/126748?folderId=2770545

If the GDPR is enabled and the user is visiting the AMP links through Google CDN.

Ref Video: https://monosnap.com/file/oHewtlzvqyvaQyICT32QG0qtMe0tp9

**Comment by MohammedKaludi** [comment]
Ready to go

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update
