### ISSUE TITLE
Few issues with yoast plugin along with multilingual plugins wpml and polylang

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4430]
1. Getting validation error:The tag 'link rel=canonical' appears more than once in the document. with yoast plugin along with multilingual plugins wpml and polylang 

https://www.yourprivatedriver.be/sv/amp/

https://www.nexustraducciones.com/?lang=fr&amp=1

The tag 'link rel=canonical' appears more than once in the document.

When we deactivate the Yoast plugin, the validation error is not occurring.

https://secure.helpscout.net/conversation/1149540527/125640?folderId=2632030

https://secure.helpscout.net/conversation/1151909465/126312?folderId=2632030

2. Multiple titles in homepage and in single.

**Comment by djixas** [comment]
This issue needs URGENT care just like REDGIFS embeds not working

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.46 and 1.0.47 update

**Comment by djixas** [comment]
Not fixed

> Pushed in 1.0.46 and 1.0.47 update

Not fixed, home page of blog in amp still has same issue, very infuriating that this is still not properly fixed
