### ISSUE TITLE
Stop focusing on adding new features and stabilize the code base

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#4431]
I'm so tired of updating AMPFORWP on all my sites only to see something broken after useless new feature implementations. 

The next months should be spend fixing all known issues and improving the code and not adding new features

**Comment by ahmedkaludi** [comment]
@djixas i totally agree with you and we are actually doing the same! 

We haven’t pushed any features lately, what error or issue are you facing recently?

Are you also effected by the yoast update?

**Comment by djixas** [comment]
All AMP pages were invalid due to your plugin using old data from yoast as explained by yoast admins

All AMP pages will soon be invalid as it's not supporting redgifs embeds

WP review plugin is giving issues (ticket submitted)

AMP Plugin Manager plugin is showing different data and is incompatible with old licenses (ticket submitted today) where one page says expires in 7 days while other page says expires in 1 year and licenses don't sync

AMP Advanced Ads didn't work with iframe ads for more than a year before it was fixed, i've had tickets with no solution

GFYCAT embeds on amp pages have large half screen padding / space below after every GIF since 2018, the fix that I apply manually every time plugin is updated is by editing class-amp-style-sanitizer.php and removing "return 'acss'.substr(md5($string), 0, 5);" line so it does not generate a random string that cannot be stylized

Sometimes my all plugins would shut down and stop working asking me to re-enter license data (all data and settings were auto removed), did not happen since installing plugin manager pro yet but it was once in a 3 months issue that i can't reproduce

These are at the top of my head

**Comment by ahmedkaludi** [comment]
These are all been taken care of. I have noted them down. github is for technical precise issues, this broad feedback has been noted elsewhere, thus its closed
