### ISSUE TITLE
layouts is only part of swift, it should not show in others

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4432]
![image](https://user-images.githubusercontent.com/16532359/80934405-aac0a300-8de5-11ea-959b-a6e037903be2.png)
User did not report this but it was seen in this case; https://secure.helpscout.net/conversation/1151765057/126233/

**Comment by MohammedKaludi** [comment]
will be fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4408
