### ISSUE TITLE
Referenced AMP URL is not an AMP page when post name and category name are similar 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4437]
If the post name and category name is similar, then it is not generating the proper AMP page.

Reference: https://wordpress.org/support/topic/referenced-amp-url-is-not-an-amp-14/

**Comment by MohammedKaludi** [comment]
1. need to update the message

"We have detected that you removed Category Base from Yoast SEO plugin but not from AMPforWP settings. Please click here to set up to make sure AMP pages work properly on category pages or click here for the tutorial."

2. Notices are not visible in AMP options panel in master. 
https://monosnap.com/file/aggKLntF4aqilOYrjsSXSAXQjMLS7M

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update
