### ISSUE TITLE
Fatal error on one of the urls. 

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4438]
Fatal error appears for a user on one of the URLs. 
User: https://secure.helpscout.net/conversation/1155954688/127345?folderId=673452

Reference: Fatal error: Uncaught Requests_Exception: Only HTTP(S) requests are handled. in /home/duwitmu.com/public_html/wp-includes/class-requests.php:564 Stack trace: #0 /home/duwitmu.com/public_html/wp-includes/class-requests.php(458): Requests::set_defaults('chrome-extensio...', Array, Array, 'GET', Array) #1 /home/duwitmu.com/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/lib/fasterimage/FasterImage.php(88): Requests::request_multiple(Array, Array) #2 /home/duwitmu.com/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/utils/class-amp-image-dimension-extractor.php(216): FasterImage\FasterImage->batch(Array) #3 /home/duwitmu.com/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/utils/class-amp-image-dimension-extractor.php(172): AMPforWP\AMPVendor\AMP_Image_Dimension_Extractor::fetch_images_via_faster_image(Array, Array) #4 /home/duwitmu.com/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/include in /home/duwitmu.com/public_html/wp-includes/class-requests.php on line 564

**Comment by Zabi09** [comment]
The issue was coming due to featured image added the same image again and the issue is fixed

**Comment by WasimM3** [comment]
Temporary fixed the issue by commenting the line 
`$dimensions_by_url = AMP_Image_Dimension_Extractor::extract( array_keys( $need_dimensions ) );`
I think issue is occurring because of these type of url
`chrome-extension://gmpljdlgcdkljlppaekciacdmdlhfeon/images/beside-link-icon.svg`

**Comment by ahmedkaludi** [comment]
Another user at Priority: https://secure.helpscout.net/conversation/1201816159/137216

**Comment by HaripriyaHari** [comment]
Another user have the same issue: https://wordpress.org/support/topic/fatal-error-uncaught-requests_exception/

**Comment by DikshantJoshi** [comment]
> Another user at Priority: https://secure.helpscout.net/conversation/1201816159/137216

The user has sent a list of URLs that have issues with internal links. Unfortunately, I can't upload the original file here because the format is not supported. Although you can find them in the above-mentioned ticket.

File in PDF format.
[convertcsv (1).pdf](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4840003/convertcsv.1.pdf)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.55
