### ISSUE TITLE
Getting Notices on the AMP pages.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4440]
Getting Notices on the AMP pages.

Ref: https://prnt.sc/sb8s3i

Ref: https://secure.helpscout.net/conversation/1150486794/125892?folderId=3575684

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update
