### ISSUE TITLE
html entities created in social description content

### ISSUE THREAD

**Issue by chopinesque** [ahmedkaludi/accelerated-mobile-pages#4441]
Reference: https://wordpress.org/support/topic/html-entities-creater-in-social-description-content/

If you check out the source, you will see something like the code below. Checking the non-amp version, the same metas are displayed with normal text. I traced this to jetpack’s jetpack\class.jetpack-twitter-cards.php file. Somehow AMPforWP affects the way it is displayed.

`meta name="description" content="Κι ο θάνατος δεν θα 'χει πια εξουσία, Γυμνοί οι νεκροί θα γίνουν ένα, Με&hellip;"/> <meta name="amp-google-client-id-api" content="googleanalytics"> <meta name="twitter:card" content="summary_large_image" /> <meta name="twitter:description" content="&Kappa;&iota; &omicron; &theta;ά&nu;&alpha;&tau;&omicron;&sigmaf; &delta;&epsilon;&nu; &theta;&alpha; &lsquo;&chi;&epsilon;&iota; &pi;&iota;&alpha; &epsilon;&xi;&omicron;&upsilon;&sigma;ί&alpha;, &Gamma;&upsilon;&mu;&nu;&omicron;ί &omicron;&iota; &nu;&epsilon;&kappa;&rho;&omicron;ί &theta;&alpha; &gamma;ί&nu;&omicron;&upsilon;&nu; έ&nu;&alpha;,`

**Comment by Zabi09** [comment]
@chopinesque I have tried to add the `<meta name="twitter:description"` but I am unable to add it, Will you please tell us how to recreate the issue on our end so that we can fix it

**Comment by chopinesque** [comment]
Hi, as mentioned in the forum I traced this to jetpack’s jetpack\class.jetpack-twitter-cards.php file. Somehow AMPforWP affects the way it is displayed. You can check the non-amp site, this does not happen. So it is some sort of interaction between Jetpack and AMPforWP. Did you have installed Jetpack for your test?

**Comment by Zabi09** [comment]
Yes I have installed Jetpack but still, I am unable to recreate it and when I open this URL - https://poiimata.com/2020/04/13/ki-o-thanatos-den-tha-chei-pia-exoysia-ntilan-tomas/ I didn't find any meta tag with name="twitter:description" in non-amp and also in AMP. Have you removed it?

**Comment by chopinesque** [comment]
No, I have not done anything, maybe some automatic update changed something. I can see og:description now though on the amp page:

`<meta property="og:description" content="&Kappa;&iota; &omicron; &theta;&#940;&nu;&alpha;&tau;&omicron;&sigmaf; &delta;&epsilon;&nu; &theta;&alpha; &lsquo;&chi;&epsilon;&iota; &pi;&iota;&alpha; &epsilon;&xi;&omicron;&upsilon;&sigma;&#943;&alpha;, &Gamma;&upsilon;&mu;&nu;&omicron;&#943; &omicron;&iota; &nu;&epsilon;&kappa;&rho;&omicron;&#943; &theta;&alpha; &gamma;&#943;&nu;&omicron;&upsilon;&nu; &#941;&nu;&alpha;, &Mu;&epsilon; &tau;&omicron;&nu; &#940;&nu;&theta;&rho;&omega;&pi;&omicron; &tau;&omicron;&upsilon; &alpha;&nu;&#941;&mu;&omicron;&upsilon; &kappa;&alpha;&iota; &tau;&omicron;&upsilon; &delta;&upsilon;&tau;&iota;&kappa;&omicron;&#973; &phi;&epsilon;&gamma;&gamma;&alpha;&rho;&iota;&omicron;&#973; &#908;&tau;&alpha;&nu; &alpha;&sigma;&pi;&rho;&#943;&sigma;&omicron;&upsilon;&nu; &tau;&alpha; &kappa;&#972;&kappa;&alpha;&lambda;&#940; &tau;&omicron;&upsilon;&sigmaf; &kappa;&alpha;&iota; &tau;&rho;&iota;&phi;&tau;&omicron;&#973;&nu; &tau;&rsquo; &#940;&sigma;&pi;&rho;&alpha; &kappa;&#972;&kappa;&alpha;&lambda;&alpha; &theta;&alpha; &lsquo;&chi;&omicron;&upsilon;&nu; &alpha;&sigma;&tau;&#941;&rho;&iota;&alpha; &sigma;&tau;&omicron;&nu; &alpha;&gamma;&kappa;&#974;&nu;&alpha; &kappa;&alpha;&iota; &sigma;&tau;&omicron; &pi;&#972;&delta;&iota; &Alpha;&nu; &tau;&rho;&epsilon;&lambda;&#940;&theta;&eta;&kappa;&alpha;&nu;, &eta; &gamma;&nu;&#974;&sigma;&eta; &tau;&omicron;&upsilon;&sigmaf; &theta;&alpha; &xi;&alpha;&nu;&#940;&rho;&theta;&epsilon;&iota;, &Alpha;&nu; &beta;&omicron;&#973;&lambda;&iota;&alpha;&xi;&alpha;&nu; &sigma;&tau;&omicron; &pi;&#941;&lambda;&alpha;&gamma;&omicron;&sigmaf;, &theta;&rsquo; &alpha;&nu;&alpha;&delta;&upsilon;&theta;&omicron;&#973;&nu;, &Alpha;&nu; &hellip; Συνεχίστε την ανάγνωση Κι ο θάνατος δεν θα &#8216;χει πια εξουσία (Ντίλαν Τόμας)" /> <meta property="og:url" content="https://poiimata.com/2020/04/13/ki-o-thanatos-den-tha-chei-pia-exoysia-ntilan-tomas/" /> <meta property="og:site_name" content="Ποιήματα" /> <meta property="article:published_time" content="2020-04-13T10:11:10+00:00" /> `

**Comment by Zabi09** [comment]
I have added the jetpack og tags with your description and it is showing properly on my end - https://monosnap.com/file/E2FBIt7HaSfoTybEdzWEK2B5vSiA9u

Will you please help us to recreate the issue and that we can fix it

**Comment by chopinesque** [comment]
Right, I found it. It was through Yoast SEO not Jetpack that these were injected. When I deactivated Yoast SEO the issue on AMP disappeared. So it is a Yoast SEO Open Graph incompatibility.

**Comment by Zabi09** [comment]
Are you using the latest version of our AMPforWP and the Yoast plugin? because I have checked on my end and the Yoast description is working fine - https://monosnap.com/file/DGI7yXzcfq1K6HBnWuEGVmAQOjVdFI

**Comment by chopinesque** [comment]
AMPforWP 1.0.47
Yoast 14.0.4

**Comment by Zabi09** [comment]
Have you done any changes because I have checked your website and it seems your Open Graph description is appearing fine at the moment

**Comment by chopinesque** [comment]
As I said, the only change was to turn off Yoast Open Graph and use the Jetpack Open Graph.

**Comment by Zabi09** [comment]
Will you please create the new ticket on Yoast repo - https://github.com/Yoast/wordpress-seo and we hope there will check it

As it is working fine in AMP can I close this ticket?

**Comment by Zabi09** [comment]
As the error is not coming from our plugin I am closing this ticket
