### ISSUE TITLE
Even after disabling the lightbox images option  still it is working on the images

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4442]
Even after disabling the lightbox images option  still, it is working on the images

Ref:https://github.com/ampproject/amphtml/blob/master/spec/auto-lightbox.md

Ref:https://secure.helpscout.net/conversation/1149945786/125773?folderId=3575684

**Comment by MohammedKaludi** [comment]
@Zabi09  You know why the ticket failed:

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/73e06821f3c6ee2f4fd1b4021c77ddf9ac0d5753#diff-b6438fc932bdcf0c8a01c3c146505c9eR398

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
