### ISSUE TITLE
Lighthouse issues.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4443]
Case 1: https://secure.helpscout.net/conversation/1156744130/0/?folderId=2770543
Same URL 

- [ ] ID attributes on the page are not unique.
See this screenshot:https://prnt.sc/sbr8vw
- [x] Form elements do not have associated labels
See this screenshot:https://prnt.sc/sbr9jm
- [x] 'tap targets' is not sized properly.
See this screenshot:https://prnt.sc/sbrahu
- [x] Links do not have a discernible name
See this screenshot:https://prnt.sc/sbrc8t
- [ ] The warning shows as "<frame> or <iframe> elements do not have a title" - https://prnt.sc/schg4p

**Comment by MohammedKaludi** [comment]
Why two are still pending?

**Comment by MohammedKaludi** [comment]
`id=placement` might cause duplication if multiple search forms are added.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4d8ca047a21e4e686cb012dd3e77b18e10e05316#diff-50ca97af891aedfd1983582931b0cda8R29

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
