### ISSUE TITLE
Too many redirect with WPML plugin when mobile redirection enable

### ISSUE THREAD

**Issue by WasimM3** [ahmedkaludi/accelerated-mobile-pages#4444]

**Comment by MohammedKaludi** [comment]
Need to make sure that the escaping is done,  before we sent the URL 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/72f20f5671c6d5e9b8864773b71a560498d423e1#diff-6aa5512f7dd8d5ce60fc97b0f340912cR395

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in  1.0.48 update
