### ISSUE TITLE
Error 500 when activated

### ISSUE THREAD

**Issue by TimothyFran** [ahmedkaludi/accelerated-mobile-pages#4445]
Plugin version: 1.0.47
PHP Version: 7.4
Wordpress version: 5.4.1
Error: ERROR 500

The error comes in the admin panel, in the plugins page and in the updates page.

![SnapCrab_NoName_2020-5-6_13-16-15_No-00](https://user-images.githubusercontent.com/64901580/81170905-c66daa00-8f9b-11ea-8e4d-cb5f7a80f488.png)
The other active plugins are:

- a3 Lazy Load             2.3.2
- Akismet Anti-Spam    4.1.5
- All In One SEO Pack   3.4.3
- Async JavaScript         2.20.03.01

No log is writte in debug.log

**Comment by MohammedKaludi** [comment]
This is very strange, can you please let us know the list of all the pluigns and the active theme you are using?

**Comment by TimothyFran** [comment]
I also received a mail saying that:

> An error of E_COMPILE_ERROR was caused on line 616 of the file /homepages/37/d706472970/htdocs/clickandbuilds/Sos3DPrinting/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php. Error message: require_once(): Failed opening required '/homepages/37/d706472970/htdocs/clickandbuilds/Sos3DPrinting/wp-content/plugins/accelerated-mobile-pages/includes/features/structure-data/structured-data-functions.php' (include_path='.:/usr/lib/php7.4')

The theme I'm using is ColorMag 1.4.6.

**Comment by MohammedKaludi** [comment]
This is very strange, can you please reinstall the plugin.

The error shows as the plugin is missing `structured-data-functions.php` file from the folder.

But this is present as thousands of websites are using this, can you please reinstall the plugin and test it?

Please do let us know if the issue is not resolved we are here to help  you.

Thanks,

**Comment by TimothyFran** [comment]
Problem solved, thanks
