### ISSUE TITLE
One signal push notifications button is not visible.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4446]
https://secure.helpscout.net/conversation/1150853405/126045?folderId=3243584

https://www.mondocalcionews.it/football-story/dener_erede_pele_morto/vittorio-cornacchia-2/amp/

**Comment by MohammedKaludi** [comment]
Few improvements required : https://monosnap.com/file/mDgqGohKYppjRdcObrRqjhh9yN6g78
