### ISSUE TITLE
Please add support for Matomo Tag Manager & query parameter exclusion

### ISSUE THREAD

**Issue by nisiwi** [ahmedkaludi/accelerated-mobile-pages#4448]
AMPforWP already supports Google Tag Manager and Matomo Analytics and it would make a lot of sense to also include support for Matomo Tag Manager to deploy additional functionality in much the same way that Google Tag Manager allows.

Also, as I'm using a hosted instance of Matomo I don't need to worry about passing URL query parameters (GDPR) as I control the data.  However, from a GDPR perspective when using GTM/GA, I need a way to programmatically exclude these parameters from being sent as they may contain personal identifiers which would require a modification of the tracking code.  I can do this for Non-AMP via Tag Manager, however, for AMP pages I cannot (custom HTML Tag not available), so it needs a modification of the script directly through AMPforWP.

https://developers.google.com/analytics/devguides/collection/analyticsjs/pages#modifying_page_urls

**Comment by ahmedkaludi** [comment]
There's very little or no data about Matemo Tag manager integration for AMP. Matemo needs to include the support for this first, only then it can be added. Currently, it's a closed from our side until the support is built and docs are out.
