### ISSUE TITLE
Corrupted .htaccess after installation

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4449]
Ref : https://secure.helpscout.net/conversation/1157868431/128150?folderId=3611365

**Comment by Zabi09** [comment]
I am unable to recreate it and we don't modify anything in .htaccess file if you just install our plugin and we have one option of "Leverage Browser Caching" in performance section and if you enable this option then only we modify your .htaccess file and add the code which you have mentioned.

And you can add more the one <IfModule mod_expires.c> on the .htaccess file and it will not break anything
