### ISSUE TITLE
amp-carousel gallery with captions is not valid amp code

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4452]
<amp-carousel> with <figure> end <figcaption> causing page to turn BLANK

https://wordpress.org/support/topic/amp-carousel-gallery-with-captions-is-not-valid-amp-code/

REf: https://secure.helpscout.net/conversation/1157625419/128114?folderId=3257665

**Comment by DrLightman** [comment]
Hello,

amp-carousel was not related to the error.

Instead, the preg_replace() inside the shortpixel compatibiliy filter as I specified in the last replies of the topic you linked.

To try to replicate the issue you may want to try to:

- enable https://wordpress.org/plugins/shortpixel-adaptive-images/ . I have 1.8.0 right now, have to update

- attach and embed a lot of images in the body of the post, al least 5 or more, go with 10 if you can, all of them must be one after the other without normal text between them and the amp should minify this html into a long line. while uploading, fill in some alt text for each image too and description via the wp media manager

- theme in use I have AMP Layouts and both Magazine and News on different sites gave me the error so maybe it's not relevant

my php is 7.4

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
