### ISSUE TITLE
 Yoast’s FAQ Schema Block not working in sync with AMPforWP

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4453]
I am having the same issue with the pages where I have used Yoast’s FAQ Schema Block. The AMP Plugin isn’t picking FAQ Schema from the Yoast which results in the mismatched Structured data between AMP Version and the regular version.

https://wordpress.org/support/topic/error-in-required-structured-data-elements/
https://wordpress.org/support/topic/error-in-required-structured-data-element-26/

**Comment by Zabi09** [comment]
We have tested the Yoast’s FAQ Schema Block on our end and its working fine and also currently working on the user end as well, So closing this ticket
