### ISSUE TITLE
Update the amp-mustache script to 0.2 and remove the deprecated version 0.1

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4454]
https://secure.helpscout.net/conversation/1138250284/123249/

https://monosnap.com/direct/u42OHjOUBrRIzVDSw356UssFOXMhe8

**Comment by Zabi09** [comment]
The warning is coming due to AMP Contact FORM 7 by Arshid and not by our plugin
