### ISSUE TITLE
"Last Modified Date" showing "Thu, 1 Jan 1970" in header.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4456]
Ref: https://secure.helpscout.net/conversation/1153738349/126723?folderId=2770545

Screenshot: https://prnt.sc/sf6doi

The issue is very strange and occurs at a few user's end. It is not occurring on the local but it is occurring on the cloudways.

URL: https://wordpress-123147-847862.cloudwaysapps.com/amp-test-page/amp

in the header of non AMP it is not showing the modified date as 1 Jan 1970 but it is showing for the AMP.

User URL: https://www.rnbjunk.com/bad-bunny-lancia-il-secondo-album-a-sorpresa-in-3-mesi/amp/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
