### ISSUE TITLE
Incorrect hook used to add admin scripts

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4457]
The way of coded Redux is conflicting with others.

Please change this line of code:
add_action( 'admin_enqueue_scripts', 'ampforwp_add_admin_styling' );

to this:
add_action( 'redux/page/redux_builder_amp/enqueue', 'ampforwp_add_admin_styling' );

This can be found in on line 25 of your ~/includes/features/functions.php file

Reference: https://wordpress.org/support/topic/please-use-proper-hook/

**Comment by akshaywali** [comment]
Pushed in AMPforWP 1.0.84
