### ISSUE TITLE
The content gets hide in the Samsung chrome browser

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4458]
Screenshot: https://prnt.sc/sfxv29

Ref: https://secure.helpscout.net/conversation/1162960978/129429?folderId=2770545

The issue is a very rare one and occurring only on few devices. We tested it on almost 20 Android devices and it is occurring on only one.

**Comment by Zabi09** [comment]
Going to fix in - https://github.com/ahmedkaludi/ads-for-wp/issues/340
