### ISSUE TITLE
If the RTL option is enabled then the thumbnail images are not showing for the AMP Page Builder Category module

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4459]
Ref: https://secure.helpscout.net/conversation/1161204224/129031?folderId=2770545

Screenshot: https://prnt.sc/sg00en

URL:
 https://dev.moshaveranco.com/tax-services/amp/
 https://dev.moshaveranco.com/services-registration-enterprises/amp
 https://dev.moshaveranco.com/accounting-services-financial-audit/amp

If the user has enabled the RTL support then the thumbnail images of the posts for the Category module of the  "AMP Page Builder" are not showing

**Comment by akashagrjsr** [comment]
The issue is occurring due to "Call To Action" module of AMP Page Builder if RTL is enabled. The issue recreated on the local as well.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
