### ISSUE TITLE
Enable AMP on Homepage option with On/off option. By default, it should be on

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#446]
Enable AMP on Homepage option with On/off option. By default, it should be on

**Comment by khaledMohammed000** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1a0a9a45a9a21b2ede08daa1b2be7ac7da188c85

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1043d53ed5c94bff0e3cea6694f12a595007e6ca

**Comment by MohammedKaludi** [comment]
Working, Closing the ticket
