### ISSUE TITLE
Vertical scroll Issue in iOS devices when the 'menu overlay' is positioned in right.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4461]
How to check and recreate the issue (please refer to the below video).

Video: https://monosnap.com/file/ItslUOd5UixkA258SJXphuCKSvY6d0

Reference Ticket: https://secure.helpscout.net/conversation/1161291469/129044?folderId=3126461

Note: The issue is occurring only in iOS devices.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.53.2
