### ISSUE TITLE
Text links are not working in mobile.

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4462]
Ref : https://secure.helpscout.net/conversation/1146316523/124874?folderId=3611365
https://monosnap.com/file/vP7pmRdVXQUA7J1wxtFYDHfPcDeIJv

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.50
