### ISSUE TITLE
Facebook Instant Articles (FBIA) Crawler Ingestion (ia:markup_url) tag not working like it suppose to.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4463]
User ref: https://secure.helpscout.net/conversation/1156089505/127681?folderId=673452
refer to previous ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1474

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
