### ISSUE TITLE
Create an extra argument to pass for amp_author_box function so author links can be controlled.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4466]
For example, I am passing $author_box['author_link'] as Non-amp Url, but in the function amp_author_box, it is still converting that author link into AMP.
Note: My requirement is to redirect the author link to the Non-amp page.
Ref: https://secure.helpscout.net/conversation/1147793417/125255?folderId=2770543

**Comment by WasimM3** [comment]
We can disable author amp link by adding arguments `$args['is_author_link_amp']=false;`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.53.2
