### ISSUE TITLE
Controlling Analytics Deployment without Cookie Notice/GDPR Compliance Bar Displaying

### ISSUE THREAD

**Issue by nisiwi** [ahmedkaludi/accelerated-mobile-pages#4467]
AMPforWP allows various analytics platforms to be deployed which can be controlled for privacy (disabled on enabled) by setting a cookie.

If I disable the Notice Bar/GDPR control from within AMPforWP can I still set and remove the related cookies externally and therefore control the deployment of analytics?

i.e. if I set the cookie ampforwp_gdpr_action false 0 OR ampforwp_gdpr_action true 30 will it allow me to control when the tracking code is deployed without GDPR Compliance being switched on within AMPforWP?

If the AMPforWP switch needs to be on to enable detection of the cookie, how do I prevent the banner from being displayed to the user (so I can control it externally) ?

**Comment by MohammedKaludi** [comment]
No, it will not work, 
as the loading of the cookie, code is connected with the GDPR on/off control.

As it will not make sense to load all the code for whoever does not want it to be loaded on his site. So if the GDPR control off then it will not load the GDPR related markup, scripts, etc.

Can you please let me know your use case or what you are trying to achieve out of this so I can suggest you some alternative?

**Comment by nisiwi** [comment]
I'm trying to unify the control of tracking scripts across AMP and non-AMP and I don't want to use a notice bar.  Instead I'd like a button on the privacy policy page that lets users activate or deactivate tracking across AMP and non-AMP.

**Comment by MohammedKaludi** [comment]
What if I add a filter to modify the on/off switch, so it can be controlled from externally?

**Comment by nisiwi** [comment]
Great.  That would work.

**Comment by MohammedKaludi** [comment]
I have created a separate ticket for it and not added to this, to keep the conversation and development separate.

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4471

This filter will be added to the 1.0.51 update, that we are planning to push at around 25th May.

**Comment by MohammedKaludi** [comment]
Closing this ticket for now. 

Please do let me know if you need anything else from me and you can keep an eye on #4471 for the progress of development.
