### ISSUE TITLE
Disqus comments are not displaying when user visits through Google.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4468]
Console Error: https://prnt.sc/sgmzdr

Please check the above screenshot once(console error), if users visit the site through google then 'Disqus comments' are failed to display.

Note: The issue is occurring only with 'Disqus' other comments are displaying perfectly.

Ref Ticket: https://secure.helpscout.net/conversation/1163376474/129482?folderId=3126461

**Comment by Zabi09** [comment]
This error is not coming from our plugin - https://disqus.com/home/discussion/channel-discussdisqus/there_is_a_error_refused_to_display_httpsdisquscomembedcomments/
