### ISSUE TITLE
debug warning: Notice: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by saranshkataria** [ahmedkaludi/accelerated-mobile-pages#4469]
Staring with an error message: Notice: Trying to access array offset on value of type bool in /var/www/html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 6728
to
[Action] Unrecognized AMP element "amp-animation".​​​ <amp-animation id=​"hideAnim" layout=​"nodisplay" class=​"i-amphtml-error i-amphtml-element-error i-amphtml-element i-amphtml-layout-nodisplay" error-message=​"[Action]​ Unrecognized AMP element "amp-animation".&#8203;​&#8203;​&#8203;​" hidden i-amphtml-layout=​"nodisplay">​…​</amp-animation>​,

There are quite a few errors in my Webmaster console too.

![image](https://user-images.githubusercontent.com/1450819/81990372-e3395b80-95f3-11ea-94d2-1a45a9ebd402.png)

Sample URL for debugging: https://www.wisdomgeek.com/amp/#development=1

I also am getting a lot more errors with Yoast as well, I had to downgrade Yoast to 13.5.0 to resolve those

**Comment by MohammedKaludi** [comment]
Thank you very much for raising the ticket.

This is just a debug warning, but as amp markup is very strict, it does not allow anything unwanted in the markup and will invalidate the page.

Please turnoff the wp debug, by setting wp_debug to false in wp-config.php as it not advisable to enable debug in the production site.

We will fix the debug warning in Future updates.

**Comment by saranshkataria** [comment]
Thank you! Turning debug mode off fixed it. Let me know if you want me to close this issue or keep it open as a task for removing the debug warning in the future :)

**Comment by MohammedKaludi** [comment]
No, keep the tickets open we will fix the debug warning in future updates.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
