### ISSUE TITLE
design 2 error on php file

### ISSUE THREAD

**Issue by danielmrey** [ahmedkaludi/accelerated-mobile-pages#447]
When design 2 is selected (with no custom rules added):
ERROR in this file:
wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-2/style.php on line 3

Thanks

Daniel.

**Comment by khaledMohammed000** [comment]
Hey @danielmrey what do you mean by Custom Rules ? can you please elaborate

**Comment by danielmrey** [comment]
Wordpress > AMP > Getting Started > Design > Design Selector > Design 2 > Custom CSS: with no CSS rules (blank)

Then you get that error in the front end...

Thanks

Daniel.

**Comment by danielmrey** [comment]
But now it works!... 

?

Thanks

Daniel
