### ISSUE TITLE
DNS -prefetch value is disappearing even after saving in safari browser

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4470]
DNS -prefetch value is disappearing even after saving in safari browser

Ref:https://secure.helpscout.net/conversation/1149945786/125773?folderId=3575684

Ref:https://drive.google.com/file/d/1Xk44RsYoLgJ7PndzBtW1KNe3OOmApENM/view

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
