### ISSUE TITLE
Robots txt is not working when AMP takeover (Beta)is enabled.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4475]
Robots txt is not working when AMP takeover(Beta)  is enabled.

Ref:https://secure.helpscout.net/conversation/1159193231/128446?folderId=3575684

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
