### ISSUE TITLE
Need to add an option for the change the image size of the first image if user is using Swift theme

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4476]
Ref: https://secure.helpscout.net/conversation/1164869093/129784?folderId=2770545

Screenshot: https://prnt.sc/sixzq6

If the user is using the swift theme and changing the image size of the post loop images then the image size of the first image is not changing. So, we need to add an option for this.
https://prnt.sc/siy9rb

**Comment by sonaliramteke** [comment]
Image is not visible when screen is changing in the bigger screen

**Comment by MohammedKaludi** [comment]
escaping while merging 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a5da6a3559f8eb1454ed1377f07639a1c2c5236d#diff-2ae5550e31f40c1962ca69d373af6b93R428

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
