### ISSUE TITLE
Hundreds of gigabytes in error log with this message

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#4477]
[18-May-2020 14:19:23 UTC] PHP Warning:  readdir() expects parameter 1 to be resource, bool given in /home/xxx/public_html/wp-content/plugins/amp-cache/ampforwp-cache.php on line 118

This log is killing my server hardrives as it's writing hundreds of gigabytes of data per day, latest version everything

**Comment by ahmedkaludi** [comment]
We're sorry for this, it's happening because of the AMP-cache, I have created a bug request for this, This will be fixed immediately in the next amp-cache update which will be released this week.

**Comment by MohammedKaludi** [comment]
in the meantime you can add this in your wp-config.php file  `define( 'WP_DEBUG_LOG', false );` and it will not create the log of errors.
