### ISSUE TITLE
custom taxonomy archive is not working a rare scenario

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4478]
the custom taxonomy support is added, AMPhtml is generated but then it goes to 404 - https://beta.yargikararlari.net/ictihat/amp/

Most probably because of the theme but let's find the root cause and fix it 
https://secure.helpscout.net/conversation/1136353435/122888/

**Comment by MohammedKaludi** [comment]
usage of array_filter seems incorrect.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cbc2638920cd5c3d667c5f75edb26f68b8331cd7#diff-4c7e8aaf3d2ea6555ce6cdd4ecae8e69R252

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
