### ISSUE TITLE
AMP pages getting blank when <amp-pixel code is added in Advanced Enter html in body section.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4479]
https://secure.helpscout.net/conversation/1169511667/130692?folderId=3243584

Code tried:-https://help.narratiive.com/article/66-amp

**Comment by WasimM3** [comment]
Wrong amp pixel component was inserted in the header that is why post was getting blank, Not inserted as per the documentation (https://amp.dev/documentation/components/amp-pixel/). Fixed the issue after inserting as per the documentation. So, closing the ticket
