### ISSUE TITLE
Push through Gutenberg editor 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4483]
https://wordpress.org/plugins/amp-blocks/

**Comment by ahmedkaludi** [comment]
There should be a markup like the default gutenberg add module section, which will be named "Pre-built AMP Blocks Designs"  https://take.ms/tDPlY

and when you open, it will have some description says that there are some designs and requires a plugin and then an install button underneath it.

**Comment by MohammedKaludi** [comment]
not required anymore
