### ISSUE TITLE
FlexMLS® IDX has a conflict with AMP

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4484]
Whenever the plugin(FlexMLS® IDX) is activated "link rel=canonical' is missing or incorrect." error pops up on the AMP validator test. 
The issue has been tested on Local Host as well. 
Reference: https://secure.helpscout.net/conversation/1171607964/131108?folderId=673452

**Comment by Zabi09** [comment]
incorrect ticket - https://monosnap.com/file/bRRhVodiRUOqpgp4K3Anv15fXKos1m
