### ISSUE TITLE
Need to add moderation tool for the Facebook comments 

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4485]
Need to add moderation tool for the Facebook comments It should integrated via the Facebook application ID. Each Facebook comment you receive a notification to accept or not .

ref : https://secure.helpscout.net/conversation/1159131329/128436?folderId=3575684

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.13
