### ISSUE TITLE
Meta description is not working on homepage with yoast

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#4486]
The meta description is not working on the homepage with Yoast https://secure.helpscout.net/conversation/1166125991/130030/

**Comment by ajeetku** [comment]
Need to add class exists https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d360af4be3a3c6bff428a26bd6b1f57b6797de72#diff-6aa5512f7dd8d5ce60fc97b0f340912cR3212 
because if desc is empty and Class not `'Yoast\\WP\\SEO\\Integrations\\Front_End_Integration'` its will go in else part

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
