### ISSUE TITLE
Add able to custom amp keyword

### ISSUE THREAD

**Issue by vanduc1102** [ahmedkaludi/accelerated-mobile-pages#4487]
Due to some reasons, my site doesnt allow to use ```amp```,
Can we have an option to change the `/amp`  ?

I'm thinking of a solution to replace all https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/accelerated-moblie-pages.php#L36 with a CONST

**Comment by ahmedkaludi** [comment]
Its possible to change that endpoint, you can do it using: https://ampforwp.com/addons/subdomain-endpoints-for-amp/
