### ISSUE TITLE
Create a filter and hook from which user can control Mobile redirection

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4488]
User can be able to control the Mobile redirection via code regardless of what is set in the options panel

https://secure.helpscout.net/conversation/1168448486/130528?folderId=1060554

**Comment by ajeetku** [comment]
no need to define same apply_filter hook 2 times
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c58e08788f2ee86a300528768de1bc83d68033d9#diff-ab576767b896423d184ddafe2ede2310R265
we can call the previous function on second time also

**Comment by Zabi09** [comment]
`add_filter('ampforwp_modify_mobile_redirection_switch' ,'prefix_mobile_switch');
function prefix_mobile_switch($mobile){
  $mobile = 1;
  return $mobile;
}

add_filter('ampforwp_modify_mobile_redirection' ,'prefix_mobile_support');
function prefix_mobile_support($mobile){
  if(!is_category('sports')){ //Mobile Redirection will only work for sports category
    $mobile = true;
  }
  return $mobile;
}`

**Comment by MohammedKaludi** [comment]
Incorrect fix: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c58e08788f2ee86a300528768de1bc83d68033d9#diff-570ea02e01314bbe208d018b021ea5750aa69ef730daaba966c2a82f84f7a7bdR2806

**Comment by MohammedKaludi** [comment]
also few improvement required for this ticket.

1. Change the variable name `$default` to something self explanatory, like `$stop_mob_redirection` 
2. Improvement in condition saying `if($default === true){` if true sent from the filter then only it should stop the Mobile redirect, in the current case if we pass anything it will make the condition true.
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/549fe33128ad244b47ca95f1c3734ce36ad9609f#diff-57c5eea21595fc80cd4182b4b90474dc3f5c7733b773be5a63d809fbd520d4f3R178

**Comment by Zabi09** [comment]
Pushed in 1.0.77.1
