### ISSUE TITLE
Whats happen when front page is not home page nor archive page....

### ISSUE THREAD

**Issue by Lofesa** [ahmedkaludi/accelerated-mobile-pages#449]
If in customizer you designate a page (name it frontpage for example) as a front page, and other (say postpage) as posts page....
I had 2 pages with a listing of post. In home page (https://site and https://site/postspage) in home page the next button works as expected but in posts page don´t.

**Comment by ahmedkaludi** [comment]
Hey @Lofesa Can you attach a screenshot or link? It would really help me understand and fix this issue.

**Comment by Lofesa** [comment]
Step by step explanation:
I had a site https://spublicos.intersindicalrm.org/ , as you can view, the front page show only the lates 4 post, is a page customized by Visual Composer (the page is called **Sindicato**), if I configure your pluglin to have a custom front page, I get a page with these 4 post.... but link to these post are not "ampnized" (I think you need a function to convert all internal links in the $content to the amp version if  don´´t) thus I have chosen not to have a custom front page in the plugin and get an amp front page with a list of post (https://spublicos.intersindicalrm.org/amp/). In this front page, if you click on the next button, you go to the page 2, rel canonical is ok, but titles, well if you digg in the html code you can view that og:title, twitter:title title and the schema json+ld are diferent, some of they come from posts page (diferent to front page)
And I had a page for post (called **Publicaciones**), it show a list of post ,same as front page, but if you click on the next button don´t go to the page 2, rel canonical change, but not title and other stuff....
I can´t attach any screenshot as you can view it live

**Comment by Lofesa** [comment]
About "ampizing" internal url, perhaps you can do some like [this](https://github.com/better-studio/better-amp/blob/master/includes/classes/class-better-amp-content-sanitizer.php#L260-L312)

**Comment by Lofesa** [comment]
Hi @ahmedkaludi @MohammedKaludi 
Take a look on [this demo](http://demo.ampprojectwp.com/amp/) of a premium amp plugin. Can you see at what I still saying, the front page can´t be the page for post.

**Comment by MohammedKaludi** [comment]
Hey @Lofesa thank you for your feedback, I was  down with the fever for the last 12 days. Now back  on the work. 
It's a great idea to add amp in menu items.
Planning to fix this issue in next update. I'll keep you all updated.

Thanks

**Comment by ahmedkaludi** [comment]
Hey @Lofesa 
So, from what I understand, You are saying that:
1. AMP on all internal links.
2. AMP on menu automatically.

Did I get this right?

**Comment by Lofesa** [comment]
Yes, that is!
Internal links are those url´s that appear in the $content and go to another page/post in the same site, but exclude those that are images, css... I mean those that contain /wp-content/ in their path.
In menu, the same and only when is a custom url test is needed to check if is a link to the same site or not.
Basic infraestructure to do this is in the plugin because it convert post/pages links to amp version in titles of page for posts

**Comment by ahmedkaludi** [comment]
Sure, we already have it in menu and have a ticket for internal links, so I'm closing this one
