### ISSUE TITLE
Getting validation error as The mandatory tag 'link rel=canonical' is missing or incorrect when yoast is activated

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4490]
Getting validation error of The mandatory tag 'link rel=canonical' is missing or incorrect when yoast is activated.

Issue occurs with yoast free versions and also with the premium version.

Ref: https://www.viaggi-usa.it/pagina-per-prova/amp/

For the post as well: https://www.viaggi-usa.it/test-icons/amp/

The above url has yoast free version

https://staging.atelier-performance.fr/decalaminage-decarbonisation-nettoyage-moteur-hydrogene/amp/

Both pages are build using amp page builder.

If the page is built using by anormal editor also it is coming: https://staging.atelier-performance.fr/test/amp/

The above url has the yoast premium verison

https://secure.helpscout.net/conversation/1159149672/128439?folderId=2632030

**Comment by CharlyAes32** [comment]
Same error on another example page:
[https://staging.atelier-performance.fr/reparation-de-votre-auto/amp/](https://staging.atelier-performance.fr/reparation-de-votre-auto/amp/) .
Note is a "staging mode" on this site and the Yoast plugin does not accept another subdomain in this version of premium license which does not accept subdomains.

**Comment by TMsravan** [comment]
Anothere user: https://www.clickable.it/blog-rubriche/da-sapere/amp/

https://secure.helpscout.net/conversation/1171921573/131175?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
need to update class exists

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
