### ISSUE TITLE
Front / Home Page Meta Description Not Showing For Amp

### ISSUE THREAD

**Issue by nisiwi** [ahmedkaludi/accelerated-mobile-pages#4491]
I'm using Rank Math in combination with Elementor and AMPforWP.  All pages show their respective meta description tag apart from the front/home page AMP version.  The Home/Front page is a static page.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
