### ISSUE TITLE
Image are not getting displayed when CDN option in wp rocket is enabled.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4492]
Images are not getting displayed when CDN option in wp rocket is enabled.

https://secure.helpscout.net/conversation/1172421233/131290?folderId=1060556

https://celebshistory.com/amp/

https://celebshistory.com/catherine-bell-plastic-surgery-before-and-after/amp

Issue recreated in local: Please see this video it is clearly shown: 

https://monosnap.com/file/qVKfjJhOil20MbMuhqMqpcQ1P30hob

**Comment by alexisekrygin** [comment]
I am the owner of the site! https://celebshistory.com/amp/
I installed another caching plugin and the problem went away

**Comment by MohammedKaludi** [comment]
This was fixed in #4342
