### ISSUE TITLE
Need to implement YOAST breadcrumb for the category and the tags pages

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4493]
Ref: https://secure.helpscout.net/conversation/1172948904/131391?folderId=2770545

**Comment by akashagrjsr** [comment]
-  The Breadcrumb links are redirecting to the NON-AMP Pages. The issue is occurring only at users' end.

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.53.2
