### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method WPSEO_Options::get()

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4494]
Ref: https://secure.helpscout.net/conversation/1170911169/130964?folderId=2770545

Fatal error: Uncaught Error: Call to undefined method WPSEO_Options::get() in /var/www/vhosts/goticomania.it/httpdocs/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php:1372 Stack trace: #0 /var/www/vhosts/goticomania.it/httpdocs/wp-includes/class-wp-hook.php(287): ampforwp_category_base_remove_notice('') #1 /var/www/vhosts/goticomania.it/httpdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /var/www/vhosts/goticomania.it/httpdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /var/www/vhosts/goticomania.it/httpdocs/wp-admin/admin-header.php(281): do_action('admin_notices') #4 /var/www/vhosts/goticomania.it/httpdocs/wp-admin/admin.php(234): require_once('/var/www/vhosts...') #5 {main} thrown in /var/www/vhosts/goticomania.it/httpdocs/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 1372

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.51 update
