### ISSUE TITLE
Heading text alignment problem of accodion module in amp page builder

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4498]
Heading text alignment problem of the accordion module in amp page builder: IN MOBILE VIEW

As the heading text is of second-line heading needs to have the padding.

But it is starting under the toggle button(+).

Please see this video it is clearly shown: https://monosnap.com/file/yTiAuAEPaH8Udn2xplqs8EqL2oONrQ

https://secure.helpscout.net/conversation/1175421997/131976?folderId=2632030

**Comment by Zabi09** [comment]
We cannot override that CSS because it's coming from AMP Project and if we override also then we will have validation error so its better if you decrease the font size of the labels of accordion and that will fix your issue.
