### ISSUE TITLE
If(Show AMP for Current Page?” as “Hide”){“err_too_many_redirects”}

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#450]
In mobiles an error is occurring  When Show AMP for Current Page? is set  as “Hide” on posts.

ref: https://wordpress.org/support/topic/getting-err_too_many_redirects-in-my-amp-pages/

**Comment by ahmedkaludi** [comment]
I'm pretty sure that this was fixed in 0.9.40 Update
