### ISSUE TITLE
Rare issue: when rtl is option enable  hamburger menu menu is not displaying RIGHT in category pages.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4501]
Case 1:https://secure.helpscout.net/conversation/1171018441/131010?folderId=2770543
See this screenshot:https://monosnap.com/file/ETKqtgykcOSVcBAyACKdgOuIHLzCVI

**Comment by raju-jeelaga** [comment]
This issue is not recreating on our end, this is appearing only on the user end, this issue we see on the rare scenario, so after discussion with @ahmedkaludi I just fix the problem on user end and I am closing the ticket.
