### ISSUE TITLE
Gallery images(Gutenberg editor) are stretched when the Optimize CSS option is enabled.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4502]
https://secure.helpscout.net/conversation/1171138826/131055/
Temporarily switched off the option on users' end.
Here is an example link from user's website https://meus.reviews/motorola-one-hyper-chega-2499/

**Comment by MohammedKaludi** [comment]
Ready for merge.

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.53.2
