### ISSUE TITLE
Need support for TikTok embed video

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4504]
Ref : https://secure.helpscout.net/conversation/1175995017/132101/
https://github.com/ampproject/amp-wp/issues/4326
https://github.com/ampproject/amp-wp/issues/4633

**Comment by ahmedkaludi** [comment]
should work in two use-cases

- [ ] custom html module https://pastebin.com/zqNmB5we

- [ ] Tiktok videos gutenberg module of the Tagdiv Newspaper theme

**Comment by MohammedKaludi** [comment]
Need to fix this then: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c271adf032cfc6560343dbb7f9739bb987b31fed

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
