### ISSUE TITLE
Need to make comatibility with the wordpress embed block in guntenburg editor

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4506]
The problem here is the content of the embed url in rendering in amp but the content which is in amp iframe is not redirecting to that link.

Please add this url for the testing purpose to embed: https://armyupdate.com/index.php/2020/06/12/gen-milley-considered-resigning-after-trump-photo-op-during-protest/

We are unable to follow the link.

https://secure.helpscout.net/conversation/1176196536/132156?folderId=2632030

Issue recreated in local please see this link it is clearly shown:

Ref: https://monosnap.com/file/hsYWD8WYl36drN2BHKuu9UhaRjZeod

**Comment by MohammedKaludi** [comment]
Change to  90% for the smaller screens while merging

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f5bcd3a470c51cd4f27a3ce63d858aece72fe3a7#diff-2ae5550e31f40c1962ca69d373af6b93R758

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
