### ISSUE TITLE
Issue with Image block of Gutenberg .

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4507]
When GIF is added via Image block of Gutenberg on a post/page. Anchor tag does not work on the AMP version of post/page. while it does on the non-AMP version of the page.
ref: https://secure.helpscout.net/conversation/1181336131/133094?folderId=673452
Tested on localhost.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.53.2
