### ISSUE TITLE
Debug warning

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4508]
warnings are be occurring from the plugin.

ref screenshot: https://prnt.sc/srk2fn

ref:https://secure.helpscout.net/conversation/1180266772/132837?folderId=3575684

**Comment by Laxmikanth2502** [comment]
Notice: Undefined variable: inline_related_posts in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4945
 
REF:https://cbshop.in/amazon-prime-subscription-offer/amp/

REF:https://prnt.sc/t7dxv6

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.55
