### ISSUE TITLE
Need to add rel=”noreferrer noopener” attributes on social media links(Social sharing)

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4509]
Need to add rel=”noreferrer noopener” attributes on social media links(Social sharing options).

**Comment by MohammedKaludi** [comment]
Code improvement required.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2b8b2c4c7024478faa6f5ac0778ecb918e7b67d8#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7328

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.59 update
