### ISSUE TITLE
Getting warnings due to Yoast SEO plugin.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4510]
Deprecated: title is deprecated since version WPSEO 14.0 with no alternative available. in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 4723
Deprecated: WPSEO_Frontend::get_title is deprecated since version WPSEO 14.0 with no alternative available. in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 4723
Deprecated: title is deprecated since version WPSEO 14.0 with no alternative available. in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 4723
Deprecated: WPSEO_Frontend::get_title is deprecated since version WPSEO 14.0 with no alternative available. in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 4723

Recreated on local

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
incorrect fix is done.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2547b0c7a1e77fd49f018de4c863e84b00f6eed8#diff-6aa5512f7dd8d5ce60fc97b0f340912cR1425

1. make sure the filter removed is backward compatible 
2. The action was removed and filter was added in the same function? Without changing the logic.

**Comment by MohammedKaludi** [comment]
This needs to be fixed

**Comment by MohammedKaludi** [comment]
Ready to go.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.53.2
