### ISSUE TITLE
The tag 'link rel=canonical' appears more than once in the document. due to Yoast SEO premium plugin.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4511]
https://secure.helpscout.net/conversation/1179311162/132662?folderId=3243584

**Comment by TMsravan** [comment]
Another user is also facing the same issue, but he is using a free version.

https://secure.helpscout.net/conversation/1178543171/132534?folderId=2632030

**Comment by MohammedKaludi** [comment]
variable name improvement required 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9349b08031ce03b0cf8664e52e2bc6e1ea2bc85c#diff-1301281de287d2aed98746fc9ba777b4R70

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.53.2
