### ISSUE TITLE
Post title is not appearing when a post is shared through Whatsapp

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4513]
In amp page, when post is shared through Whats app, title is not getting displayed and only URL is getting shared.
Ref: 
https://secure.helpscout.net/conversation/1167143931/130226?folderId=3611365

Issue is recreated by importing RankMath and AMP settings of the user

**Comment by MohammedKaludi** [comment]
Why `\n` was used?
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cf463b7803240dfaa36c1b412abb13cf8336f0b7#diff-9cbf83e0d21caa7d8505ed4a8d03b158R87

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
