### ISSUE TITLE
Need to add Google theme color 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4514]
Reference: https://wordpress.org/support/topic/how-to-set-google-theme-color/

**Comment by WasimM3** [comment]
Please add escaping in the selected line

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b67dcb901a3eb0703f18276e817212de5a60183a#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8608

**Comment by netnaps** [comment]
could do this simply by adding the same to stye_cs line $swift_cs_color = '#HEX';
plugins/accelerated-mobile-pages/templates/design-manager/swift/stple.php

also to wp-content/plugins/accelerated-mobile-pages/includes/onesignal-integration/ some html file between heads without any code !

**Comment by MohammedKaludi** [comment]
@netnaps 
If you want to add it without the code then you can add this code in head section in advance settings in amp options panel 

`<meta name="theme-color" content="#HEX_CODE"/>`

**Comment by netnaps** [comment]
tried this was not working now disabled all the cache and checking again, 

i just saw the amp validator and found a default Hex Code, then went on to find that Hex code and replaced the same in style.php 

if its added to the default plugin i think would be great as its just a small thing but looks awesome to get on the mobile browser.

**Comment by MohammedKaludi** [comment]
Yes that's why we are adding it in the plugin.

**Comment by netnaps** [comment]
would await the update :) Thanks

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by netnaps** [comment]
hi thanks now is this in the options at the admin or manual to the <head> tag ?

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.55
