### ISSUE TITLE
The attribute 'src' in tag 'amp-form extension .js script' is set to the invalid value'.

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4515]
Ref : 
https://secure.helpscout.net/conversation/1175203874/131934?folderId=3611365

This error occurs when Newspaper theme is activated.
https://monosnap.com/file/DbXbaJlhZbVzBMhVxDHaySY7NS2PQq

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.53.2
