### ISSUE TITLE
Bug in CTA plugin

### ISSUE THREAD

**Issue by lorey80** [ahmedkaludi/accelerated-mobile-pages#4516]
Deactivating the option "Automatically show CTA box in content" does not deactivate the CTA, on the contrary, it shows a duplicate of the text of the article, thus generating a sort of double article, one after another. So I am forced to let appear the CTA to remove the problem. Thanks

**Comment by TMsravan** [comment]
I have checked this issue and created a ticket in Trello.

https://trello.com/c/ZtSfnabY/1791-automatically-show-cta-box-in-content-option-is-not-properly-linked-with-the-internal-option.

Please close this ticket.
