### ISSUE TITLE
Need to add compatibility of the "Brightcove Video Connect" plugin.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4517]
URL: https://staging.familyproof.com/brid-tv-shortcode-test/amp/?cachebust=12345

Ref: https://secure.helpscout.net/conversation/1182158811/133263?folderId=2770545

The user is adding the video using the "Brightcove Video Connect" plugin. The video docking feature is not working at the user's end.

**Comment by ahmedkaludi** [comment]
with amp-brid-player tag

**Comment by sonaliramteke** [comment]
Video docking feature is working only with amp-video and YouTube Video and also this error getting - The attribute 'dock' requires including the 'amp-video-docking' extension JavaScript.

**Comment by MohammedKaludi** [comment]
Update the variable names and merge the code in proper branch 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/74255c6a6fb0b61c10847e5fb03bc19b6b15f995#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8073

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
