### ISSUE TITLE
 Incorrect meta description in custom frontpage with Rank math SEO

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4519]
REF:https://secure.helpscout.net/conversation/1171209035/131066?folderId=3528427

REF: Non-AMP Description Tag: (https://take.ms/kWDKw)
       AMP page description tag: (https://take.ms/6CUS2)
      User is using the Rank Math Seo

**Comment by Zabi09** [comment]
The user was getting two meta descriptions one from Rankmath and another from our AMP plugin tried to recreate the issue on localhost but unable to recreate it and the user needs only the rank math meta description so told the user to disable the meta description from our AMP panel, So closing this ticket
