### ISSUE TITLE
Alignment problem in RTL

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#452]
There seems to be some problem in RTL,  meta info is showing incorrectly. See the screenshot for reference.

![screenshot_20170126-110122](https://cloud.githubusercontent.com/assets/15303814/22365678/e670c5f4-e49e-11e6-8c69-e360f809f43c.png)

**Comment by ahmedkaludi** [comment]
this was fixed.
