### ISSUE TITLE
 "No-index" tags are appearing on the AMP pages  while using rank math SEO .

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4520]
"No-index" tags are appearing on the AMP pages while using rank math SEO.

Ref:https://secure.helpscout.net/conversation/1182584850/133332?folderId=3575684

**Comment by Zabi09** [comment]
The user is only adding no index - https://prnt.sc/stp361 so closing this ticket
