### ISSUE TITLE
Meta description tag is missing in AMP, when custom home page is selected.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4521]
When the Custom home page is selected in AMP settings & the same page is selected as static homepage in Reading settings(https://prnt.sc/strz8q) then Meta description Tag is missing at the user end & in localhost too.

The meta description is adding through Yoast plugin & both AMP & non-AMP pages is having different meta descriptions due to the above issue.

Ref Ticket: https://secure.helpscout.net/conversation/1183510165/133497?folderId=3126461

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.53.2
