### ISSUE TITLE
Button is not working on AMP

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4523]
The user change his site to AMP, only the button text appears. He is using Gutenberg to add buttons.

Reference: https://wordpress.org/support/topic/button-issue-6/

**Comment by MohammedKaludi** [comment]
will be resolved in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4572

**Comment by jayendrasinhrajput** [comment]
@MohammedKaludi it's not fixed yet

**Comment by ahmedkaludi** [comment]
@jayendrasinhrajput the development on this ticket will be resumed on #4572

**Comment by MohammedKaludi** [comment]
> @MohammedKaludi it's not fixed yet

Yes, we know and we are working on it, as this ticket also reporting the same issue. So there is no point in creating multiple tickets for same issue, that's why we closed this one and the development will be done on another ticket.
