### ISSUE TITLE
Getting validation error as "The attribute '"_blank"' may not appear in tag 'a'."

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4527]
Getting validation error as "_blank" not appear in the tag "a". The user is using rank math and TranslatePress plugin. when we are changing the language and the option "Open link in new tab" (https://prnt.sc/svtr55) of rank math plugin is enabled then we are getting this validation error.

URL: https://currenttrends.fr/en/divers/serie-latine-el-vato-netflix/amp/

Ref: https://secure.helpscout.net/conversation/1182638367/133344?folderId=3257665

Issue recreated on the localhost.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.53.2
