### ISSUE TITLE
Even after activating amp page builder compatibility we are getting this message this feature requires Page Builder For AMP extension.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4530]
Desc: Even after activating amp page builder compatibility we are getting this message this feature requires Page Builder For AMP extension. 
sreenshot  : https://monosnap.com/direct/l3G9mVjhVgq3I4sAlmJK117A7OXXEY

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
