### ISSUE TITLE
We can Optimize Pagespeed score by implimenting AMP video lightbox

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4531]
If a youtube video is present

Score is: 65
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fprinceliestfrigatebird.htmlpasta.com%2F
https://pastebin.com/KWZ6DnMP

but with this new method, 

Score is: 89

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fhuntawaypuppy.htmlpasta.com%2F
https://pastebin.com/tTB5kSKY

**Comment by WasimM3** [comment]
Need to create tutorial for this

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.67
