### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4532]

**Comment by WasimM3** [comment]
I am moving this to failed for now, please confirm the "Install Plugin" link, for more info please check the following screenshot pointed area. If link is OK then please move it Testing.
https://monosnap.com/file/C5cJFsd0z3sYfOm21EexwPAfmjRTVG?idx=undefined&total=0&canMove=true

**Comment by ajeetku** [comment]
we can use function_exists instead of is_plugin_active

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
code improvements required:
1. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8c65e26dba73fbe852f9162baf5e86e3e831b9c2#diff-d794f55e3ee0aead59adf8c61f67f9edR16 dont use get_plugin  as this is very heavy function to call 
 
2. https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8c65e26dba73fbe852f9162baf5e86e3e831b9c2#diff-d794f55e3ee0aead59adf8c61f67f9edR18  Translation is required 

3. escpaing required for admin url

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
