### ISSUE TITLE
Featured images showing blur in the AMP version

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4533]
Ref: https://secure.helpscout.net/conversation/1164869093/129784?folderId=2770545

In the AMP version the URL of the featured image changing and adding the sizes of the featured image. The issue is occurring on the local.

Screenshots:
https://prnt.sc/swgpjj
https://prnt.sc/swgq7k

URL: https://tastesofhealth.eu/stay-at-home-my-life-and-food-under-quarantine/amp/

**Comment by syedimran22** [comment]
As the feature image size option was selected to medium due which the image was blurred once it is selected to full size it will get the original size of the image.
option screenshot: https://ibb.co/H4KfcBn
original image link: https://ibb.co/NxbqNGH
