### ISSUE TITLE
Show notice when user is enabling option "sort related item randomly".

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/accelerated-mobile-pages#4535]
When user has so many posts and if the user tries to enable the option "sort related item randomly" (https://monosnap.com/file/IkIvIrvBTEwHTUcR16PszAxX0rOtib) then we need to show a notice like "We recommend you not to do it. because it will affect the performance of the site".

Ref: https://secure.helpscout.net/conversation/1176098007/132131?folderId=3257665

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
