### ISSUE TITLE
AMP Takeover functionality is not working on the Homepage with WP Ultimate recipe plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4538]
Ref: https://secure.helpscout.net/conversation/1164869093/129784?folderId=2770545

The issue recreated on the local after just installing the WP Ultimate Recipe Plugin.

**Comment by MohammedKaludi** [comment]
Tested on multiple scenarios and its working as expected.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
we could have added it directly inside the function?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b16fb2dfabd143e6047fbe6fd4a2951d11a1c9f7#diff-6aa5512f7dd8d5ce60fc97b0f340912cR327

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.62
