### ISSUE TITLE
The below script is adding when the user using orbital theme and it is showing a validation error on the AMP Pages

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4539]
The below script is adding when the user using orbital theme and it showing a validation error on the AMP Pages

Script: <script>function orbital_expand_navbar() {var element = document.getElementById("search-navbar");if (element.classList.contains('expand-searchform')) {element.classList.remove("expand-searchform");return;}else {element.classList.add("expand-searchform");document.getElementById("search-input").focus();}}</script>

Ref:https://secure.helpscout.net/conversation/1172829716/131356?folderId=3575684

**Comment by MohammedKaludi** [comment]
add function exists for the theme 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/31e517612dd4eceec331d484cc94bc57e36801fb#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8054

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
