### ISSUE TITLE
Need to make compatibility with TravelTour Theme.

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4540]
Ref : 
https://secure.helpscout.net/conversation/1190735845/135189?folderId=3611365

If we are creating the content through the theme(TravelTour) then it's not getting displayed.

**Comment by LaxmiBhavani-98** [comment]
Ref video :
https://monosnap.com/file/q95q1vI3miCS3KIxiQf1x9KwDXVh8M

**Comment by MohammedKaludi** [comment]
Why using after content hook? instead of appending it to the content via the_content filter?

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ef28ed16646b14174309b8003ee1018e7f7dd52a#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6409

**Comment by MohammedKaludi** [comment]
still improvement required

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.55
