### ISSUE TITLE
robots.txt file is not generating when AMP takeover beta opotion is enabled.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4541]
https://wordpress-123147-847862.cloudwaysapps.com/robots.txt

https://secure.helpscout.net/conversation/1191220977/135300?folderId=2632030

https://www.bunadformenn.info/robots.txt

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
