### ISSUE TITLE
When gdpr option is enabled the site is becoming unclickable in browser Safari on IOS and MacOS 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4542]
When testing with Google Chrome and Microsoft Edge everything works fine with the GDPR popup

It´s only when using the browsers Safari on IOS and MacOS the problem exists.

https://secure.helpscout.net/conversation/1191220977/135300?folderId=2632030

The issue is occuirng in our staing as well. when gdpr is enabled the site is becoming unclikable 

https://monosnap.com/file/6vm5nUGhKdm4lZ3zq2zL2qafkE0rtl

https://wordpress-123147-847862.cloudwaysapps.com/amp/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.53.2

**Comment by Arihantkankariya09** [comment]
https://secure.helpscout.net/conversation/1202904212/137428?folderId=3243584

**Comment by TMsravan** [comment]
Another user facing the same when GDPR option is enabled, the site is becoming un interactive in the safari browser.

Ref: https://secure.helpscout.net/mailbox/cfb9786cbb6b9b7c/2632030/

https://monosnap.com/file/yxxngZOLPGastHnZhW9O0xWwKAKXni

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.56
