### ISSUE TITLE
Page is getting blank after redirecting from non-amp using Gusto theme

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4543]
Desc: Page is getting blank after redirecting from non-amp using Gusto theme and mobile redirection option enabled.

Ref: https://secure.helpscout.net/conversation/1185165931/134150?folderId=3611365

**Comment by MohammedKaludi** [comment]
Creating a custom plugin for it and will add the tutorial and will add the solution in the tutorial for it.

**Comment by syedimran22** [comment]
Here is the tutorial to troubleshoot issue https://ampforwp.com/tutorials/article/how-to-troubleshoot-page-getting-blank-redirecting-from-non-amp-using-gusto-theme/
