### ISSUE TITLE
Fixed TOC

### ISSUE THREAD

**Issue by mmprep** [ahmedkaludi/accelerated-mobile-pages#4545]
Dear developers,

there's a Fixed TOC plugin. And it's probably the best one for outputting a table of contents (TOC).

I've compared Fixed TOC with other popular plugins, including Easy Table of Contents and Table of Contents Plus, but they're all inferior in both functionality and visual presentation.
For example, only Fixed TOC offers an adequate floating TOC implementation.

Unfortunately, Fixed TOC works exclusively in desktop view.

I contacted the Fixed TOC developer about adding AMP support. He responded that hi is waiting for if WordPress Core provides the unified API.
Could you contact him to coordinate further steps to implement Fixed TOC support in AMP for WP?

Thank you in advance.

P.S. I started discussing possible support with the developer of Fixed TOC -- see here https://codecanyon.net/item/fixed-toc-wordpress-plugin/7264676/comments?page=14&filter=all#comment_24539952

**Comment by MohammedKaludi** [comment]
Hey @mmprep 

Thank you for creating the ticket, I will create the ticket in the extension department and they will look into it and we will surely make the compatibility for it if the plugin data is properly accessible via hooks and filters.

Also, I'm closing this ticket as this is not an active issue and if you have any questions regarding the update on this you can ask us from here: https://ampforwp.com/support/
