### ISSUE TITLE
E_PARSE error in  redux_api.php

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4546]
It follows with more details: An error of type E_PARSE was caused in line 195 of the file hd100_DOT_in/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/inc/class.redux_api.php. Error message: syntax error, unexpected end of file, expecting ‘]’

Reference: https://wordpress.org/support/topic/this-plugin-failed-to-load-properly-and-is-paused-during-recovery-mode-5/

**Comment by MohammedKaludi** [comment]
after trying multiple times and im not able to re-create the issue either on local server or on some other test sites.

Need to ask the user the exact environment of his site and then try to create a similar setup and hope to reproduce the error, but until then closing the ticket.
