### ISSUE TITLE
Need to add favicon support in AMP

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4548]
Ref : 
https://secure.helpscout.net/conversation/1190538212/135139?folderId=3611365

User facing issue even after adding the favicon.
https://monosnap.com/file/xbmzqr8SVa5UcmyBIO74Bc4FVYlfhC

**Comment by syedimran22** [comment]
If the favicon is set in site icon it will render in amp pages too.
Path to set site icon WordPress Dashboard -> Appearance -> Customize->Site Identify->Site Icon
for a complete tutorial to set favicon in amp follow this link https://ampforwp.com/tutorials/article/how-to-add-favicon-in-amp/
