### ISSUE TITLE
Create a notice on plugin installation, telling users to update their permalink settings

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#455]
Create a notice on plugin installation, telling users to update their permalink settings

Code started, complete it till next update.

**Comment by khaledMohammed000** [comment]
I think this was done yesterday in this commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4dee86c227c762f7b4e34f5a85d72ef5d55b0dba

**Comment by ahmedkaludi** [comment]
We flush now. We are closing this to stay focused
