### ISSUE TITLE
If Sitekit By Google plugin is active then anchor tag is stripping in AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4552]
Ref: https://secure.helpscout.net/conversation/1186609501/134381?folderId=2770545

If the user enabled the Sitekit by Google plugin then the "Anchor" tag is removing in the AMP. The issue is recreated on the local.

**Comment by ahmedkaludi** [comment]
Another issue, https://trello.com/c/TDXwtTp3/1830-table-of-content-plus-for-amp-functionality-is-getting-break-in-amp-when-site-kit-by-google-plugin-activated

**Comment by TMsravan** [comment]
As Ahmed sir commented: This is the user. also facing the same issue: 

https://secure.helpscout.net/conversation/1195892118/136164?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.53.2
