### ISSUE TITLE
Disqus Comments are not working in AMP(mobile view).

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4553]
User is adding Disqus comments in AMP and comments are submitting perfectly in Desktop view but failing to submit comments in Mobile view.

I have configured the user setup in our Cloudways site issue is occurring with CloudwaysID too.

Issue URL(disabled at user end): https://www.ringsidenews.com/2020/06/15/wwe-required-fans-to-sign-coronavirus-waivers-before-attending-raw-taping/amp/

Issue Video: please check in the User's ticket(Jun 16, 5:30 pm).

Ref Ticket: https://secure.helpscout.net/conversation/1194798332/136012/#thread-3414075552

**Comment by MohammedKaludi** [comment]
Issues seems to be in Disqus system, its working as expected now.
