### ISSUE TITLE
Need to create an option in the recent post and related post settings where when we enable it, the Utm parameters should get append to those links

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4554]
Need to create an option in the recent post and related post settings where when we enable it, the utm parameters should get append to those recent posts and related post links.

https://secure.helpscout.net/conversation/1190739299/135190?folderId=2632030

**Comment by Zabi09** [comment]
Added here - #4237 So closing this one
