### ISSUE TITLE
Need to create an option that allows users to put noindex on some pages(be able to select them) and not on all.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4559]
User needs to put noindex on some pages(individual pages) and not on all. more specifically on dynamically generated pages such as pagination or pages with variable "?amp".

Ref: https://secure.helpscout.net/conversation/1196523862/136286?folderId=3678830

**Comment by ahmedkaludi** [comment]
i'm closing this ticket until there is a valid use-case
