### ISSUE TITLE
When marfeelpress(if the amp is active ) and amp activate at a same time, we need to give very first priority to load amp markup.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4560]
Case 1:https://secure.helpscout.net/conversation/1182236098/133274/

**Comment by WasimM3** [comment]
Please wrap the filter with function exist check if possible `function_exists('mrfp_activate_marfeel_press')` to avoid unnecessary execution of the hook. 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/395e8c1769dbbce64d2bc5e77c00e0441fd45b65#diff-1301281de287d2aed98746fc9ba777b4R510

**Comment by syedimran22** [comment]
@WasimM3 as the function_exists condition is only working once it is inside the function under plugins_loaded hook.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.55
