### ISSUE TITLE
Need to add an option to display comments on Homepage.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4561]
One of our users is using Disqus comments on his homepage but on the AMP homepage, comments are not showing.

So we need to add an option in the comments area to Display comments on the homepage.
https://prnt.sc/t2ppvw

Ref Ticket: https://secure.helpscout.net/conversation/1199494890/136689?folderId=3126461

**Comment by ahmedkaludi** [comment]
i'm closing this ticket until there is a valid use-case
