### ISSUE TITLE
Yoast not working in rare scenario

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4562]
- [ ] Canonical is not working on frontpage

- [ ] robots is no-index on frontpage

https://secure.helpscout.net/conversation/1180453980/132897/

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c85119f881e455ca51724ad3626770d0bcf80a11#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4137
unused code why the global variable added outside of function

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
