### ISSUE TITLE
AMP homepage has a wrong canonical link.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4564]
AMP homepage has a wrong canonical link.
The issue gets resolved when rolling back Yoast plugin to version 13.5.

Could not recreate it on the localhost.
ref: https://secure.helpscout.net/conversation/1199430222/136682?folderId=3678830

**Comment by ahmedkaludi** [comment]
https://wordpress.org/support/topic/the-tag-link-relcanonical-appears-more-than-once-in-the-document-14/#post-13014454

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
