### ISSUE TITLE
yoast breadcrumb links not redirecting to amp pages.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4566]
Desc: yoast breadcrumb links not redirecting to amp pages.
Ref: https://secure.helpscout.net/conversation/1172948904/131391?folderId=2770545

**Comment by WasimM3** [comment]
Please use ampforwp_url_controller to create amp url and check with "Change internal link to AMP" option
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8a817590d5cc35d3e947e45c8a808332cea9c635#diff-6aa5512f7dd8d5ce60fc97b0f340912cR7289

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
