### ISSUE TITLE
AMP not valid due to [class] in amp-comments form

### ISSUE THREAD

**Issue by januzi** [ahmedkaludi/accelerated-mobile-pages#4567]
For some reason the main plugin leaves the [class] markings from the amp-comments untouched, which leads to:
`<p [class]="formData.submit.success" class="comment-form-comment"><label for="comment">Comment</label>` and `<p id="ampCommentsButton" [class]="formData.submit.success" class="form-submit">`. The validator that's under #development=1 says: 
`[object HTMLParagraphElement]: "" is not a valid result for [class]. amp-bind null`.

**Comment by ahmedkaludi** [comment]
Github is for tested and re-creatable bugs, for support please go to https://ampforwp.com/support - our technical team will help.
