### ISSUE TITLE
Debug Warning

### ISSUE THREAD

**Issue by raydvard** [ahmedkaludi/accelerated-mobile-pages#4568]
Notice: Undefined index: amp-on-off-for-all-pages in /var/www/html/stockmarketdaily.co/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 5923

I am having an unexpected issue after updating the Accelerated Mobile Pages plugin from version 1.0.51 to 1.0.52

Anyone having this issue?

please check : stockmarketdaily.co
How can I solve it?

**Comment by MohammedKaludi** [comment]
Thank you very much for raising the ticket.

This is just a debug warning, but as amp markup is very strict, it does not allow anything unwanted in the markup and will invalidate the page.

Please turn off the wp debug, by setting wp_debug to false in wp-config.php as it is not advisable to enable debug in the production site.

`define( 'WP_DEBUG_LOG', false );`

We will fix the debug warning in Future updates.

**Comment by raydvard** [comment]
Is this solved in the new update Version 1.0.53.2 ?

**Comment by MohammedKaludi** [comment]
It was reported at the very last minute, but we will fix it and push it in next update.

**Comment by raydvard** [comment]
Okay sure, Thanks

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
