### ISSUE TITLE
The mandatory tag 'link rel=canonical' is missing or incorrect.due to Yoast SEO premium plugin.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4569]
The mandatory tag 'link rel=canonical' is missing or incorrect.due to Yoast SEO premium plugin.
example URL:https://www.theholmgroupaz.com/desert-ridge-homes-for-sale-2/amp

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
