### ISSUE TITLE
Image popup feature( Lightbox for Images ) In specific scenario is not working for the images.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4570]
Image popup feature( Lightbox for Images ) In a specific scenario is not working.

Specific scenario of type :

1. When the images are inserted by using the shortcode of the Download Manager.

For this shortcode, we need to append the template id.  where in this template the HTML code of the view of the image is present. and css for this template code is applied in the custom css.

2. Also, the Herland theme has the functionality of it https://prnt.sc/t3d4g7 when we enable this option. then the image will get appear as a pop on the same window.

But in the amp, the images are opening in the new window. we need to get the image open in the same window.

Please see this video it is shown how the scenario created:

For the short code: [wpdm_tag id="media" template="download01" cols=2]

https://monosnap.com/file/hTpEo5SKtrFZj3jR6ClTVN7RuBWCdU

Template code and the CSS is in this file: https://pastebin.com/mnwvjfue

Please see this video issue is shown: https://monosnap.com/file/0jO1lRUD5hDSpXJPAp6BXwXIvlh02i

https://secure.helpscout.net/conversation/1193178409/135663?folderId=2632030

**Comment by techzotezo** [comment]
We are using your POUP plugins for AMP and it is working fine except these features-
1) Cannot be resized the Popup from Admin Panel, cannot able to resize from Admin settings-Mainly Various Size of Pop Up and Various Template required
2) No Analytics integration or GTM tracking features
3) one per sessions/page
4) After x Seconds show
5) Exit intent pop up
6) Able to see "Clicks" " Clicks on Which Pages" "Impressions" "CTR"
7)Flexibility to show pop up in specific pages
Can you please update the plugins with the following features?

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.55
