### ISSUE TITLE
Comments are not displaying on Homepage. (only in swift theme)

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4571]
The user is trying to add comments on the homepage but in AMP, comments are not displaying on the home page(only in swift theme).

The issue is occurring from AMP version: 0.9.98.12, before that it is perfectly displaying on all designs.

This may be due to the below reference ticket:
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3647

Ref Ticket(user): https://secure.helpscout.net/conversation/1199494890/136689?folderId=3126461

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
