### ISSUE TITLE
Bug: meta title not pulled from YOAST in version 1.0.53.2

### ISSUE THREAD

**Issue by seriou5** [ahmedkaludi/accelerated-mobile-pages#4574]
The meta title for posts is not pulled from YOAST SEO - instead it is generated from the title + the site name, which leads in most cases to too long titles for SERPS. 

This worked in version 1.0.52.

**Comment by syedimran22** [comment]
Hi @seriou5 could you send me the URL where you are getting the issue.

**Comment by seriou5** [comment]
Hi @syedimran22 sorry, i reverted the update on our most important websites. But you can test it here: https://www.skinfellaz.com/haare/frisuren/glatze-rasieren-so-machst-du-es-richtig/

Meta title normal page: "Glatze rasieren - So machst du es richtig"
Meta title AMP: "Glatze rasieren – So machst du es richtig | Skin Fellaz – Der Haare, Bart und Haut Blog für Männer"
(german)

We use: YOAST (latest version) + AMPforWP (latest version)

SEO Settings in AMPforWP:

- select seo plugin: yoast
- meta tags from yoast: true
- yoast description in ld+json: true
- canonical from yoast: true
- breadcrumbs from yoast: true

**Comment by MohammedKaludi** [comment]
@seriou5 thank you very much for the information, these type of detailed information really helps us in debugging the issue.

I wish more and more people send info like this.🙏

Will look into this issue and fix it in an immediate update.

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.54
