### ISSUE TITLE
Create compatibility for WP stateless Google cloud storage plugin to serve images from CDN.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4575]
https://secure.helpscout.net/conversation/1201172745/137063?folderId=3243584

Plugin link:- https://wordpress.org/plugins/wp-stateless/

Usecase:- User is serving the images from the CDN and on the AMP fallback images are shown on all posts except for the original ones.

**Comment by tripledm** [comment]
Images on AMP version of home page and categories not displaying so it reverts to fallback.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.6
