### ISSUE TITLE
Need to add support for the audio from the Pennews Theme

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4576]
Need to add support for the audio from the Pennews Theme.

Ref:https://secure.helpscout.net/conversation/1169139544/130631?folderId=3575684

**Comment by MohammedKaludi** [comment]
I realize it's the audio support it's doesn't work with any audio embed who uses percents instead pixels. Spotify, for example, use percents.

For example:

<iframe src="https://open.spotify.com/embed-podcast/episode/1IbjCbfEZmkpiPMWkVpsHs" width="100%" height="232" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

Plus, it's putting a weird and big vertical scrollbar to the embeds in amp version. You can check that in this URL: https://secure.helpscout.net/conversation/1169139544/130631?folderId=3575684

Greetings.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Some more improvements required

**Comment by Zabi09** [comment]
Pushed in 1.0.76.16
