### ISSUE TITLE
Category pages are is not working properly.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4579]
The issue is occurring when the user is enabled option Strip Category Base in the Rank math SEO /Yoast SEO plugin and the Category base remove in AMP is disabled. AMP HTML generating from the Non-amp.if we open the AMP version it is showing the 404 error or improper content.

Ref: https://secure.helpscout.net/conversation/1198428182/136527?folderId=3575684
Ref 2: https://secure.helpscout.net/conversation/1201259020/137100?folderId=3575684
Ref 3:  https://secure.helpscout.net/conversation/1204007204/137702?folderId=3575684(Yoast SEO)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58 update
