### ISSUE TITLE
amp-embed doesn't include the amp-ad script

### ISSUE THREAD

**Issue by astaoutbrain** [ahmedkaludi/accelerated-mobile-pages#4580]
Based on the AMP documentation [https://amp.dev/documentation/components/amp-ad/](https://amp.dev/documentation/components/amp-ad/) the tag **amp-embed** is an alias for the tag **amp-ad**, so the **amp-ad** script is required for both tags. The documentation says to use **amp-embed** when semantically more accurate. When I try to embed the tag **amp-embed** in a custom template the **amp-ad** scripts isn't added. When I try to change the tag name to amp-ad it includes the script. Not including the script wasn't require until now, but I recently got some warnings from google search console saying: _The tag 'amp-ad extension .js script' is missing or incorrect, but required by 'amp-embed'. This will soon be an error._ Please fix before it becomes an official error.

**Comment by MohammedKaludi** [comment]
Thank you very  much for creating the ticket and we will look into it and fix it in upcoming updates.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.55
