### ISSUE TITLE
Need to add option to disable/enable default "Site Navigation Element schema" generated by our AMP.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4583]
As per the user, using 3rd party schema plugin to generate schema markup on his website but the main issue is in AMP by default "Site Navigation Element schema" is added and user wants to disable it.

In order rectify this, we need to add an option to enable/disable "Site Navigation Element schema" on AMP in AMP > structured data settings.

Ref Ticket: https://secure.helpscout.net/conversation/1203920782/137674?folderId=3126461

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.14
