### ISSUE TITLE
The duplicate text showing after the anchor link

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4584]
Ref: https://secure.helpscout.net/conversation/1203284279/137542?folderId=2770545

Screenshot: https://prnt.sc/t6q86l

1. The duplicate text is showing after the anchor link due to the Rank Math SEO Plugin.

2. The anchor link text showing the " su primer millÃ³n de usuarios" instead of the "su primer millón de usuarios"

URL: https://www.eduardvelazquez.com/4-cosas-growth-hacking/amp/

[testcode.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/4835463/testcode.txt)

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.54.1

**Comment by MohammedKaludi** [comment]
Need to test this with, Arabic or Persian, Japanese or Chinese, Hindi and Turkish text to make sure the Text is properly converting and not breaking for non-english languages.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.55

**Comment by MohammedKaludi** [comment]
Issue fixed in 1.0.57 update.
