### ISSUE TITLE
type="googleanalytics" is not working, we need to change it to gtag

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4585]
if you enable "Advanced Google Analytics", it will take type="googleanalytics" by default, but that does not track the analytics views. It's tested with 100% surety. 
Helpscout ticket number 137166

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58 update
