### ISSUE TITLE
Autoptimize is causing validation for logged in users, confusing alot of people

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4586]
The attribute 'percentage' may not appear in tag 'div'. Debug.
1
71498
The attribute 'target' may not appear in tag 'div'. Debug.
1
74443
The attribute 'target' may not appear in tag 'div'. Debug.

**Comment by MohammedKaludi** [comment]
Commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/03a9771881a1316ee4fdb5ca19bbd03953484df7

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58 update

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.60
