### ISSUE TITLE
when user is not an ampforwp admin, then newely created posts are not getting added in the instantarticles feed

### ISSUE THREAD

**Issue by ghost** [ahmedkaludi/accelerated-mobile-pages#4588]
Please see this video the issue is shown: https://monosnap.com/file/qicvYG6QZVSSWScW7gw6ylKApzmFgN

I have checked it in internal system, the issue is recreated.

https://secure.helpscout.net/conversation/1207451275/138276?folderId=2632030

**Comment by Zabi09** [comment]
Working as expected so closing the ticket

**Comment by akshaywali** [comment]
![image](https://user-images.githubusercontent.com/36995680/233568553-3dc7b683-b660-4d28-8a93-b4ff9ebdb4da.png)

User just need to make sure that **Show Instant Article for Current Post ?** is enabled before published the post.

 Note :- the above option will be enabled by default for AMP admin roles and disabled for other roles
