### ISSUE TITLE
Rich snippets support

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#459]
Hi all,

Any idea about how to implement Rich snippets support in this plugin? Like a local bussiness type schema.

At this moment only see BlogPosting type.

I think with this SEO improves.

Thanks in advance

ref: https://wordpress.org/support/topic/rich-snippets-support-2/

**Comment by Lofesa** [comment]
HI @ahmedkaludi 
you can put an eye to [this](https://github.com/schemapress/Schema/tree/master/includes) plugin, they had integration with the amp plugin from Automattic, and suposed to work only in post and categorys but i think you can  manage to add apropiate schema data to pages, front page and so.
It is not necessary to invent the wheel twice

**Comment by Lofesa** [comment]
Well... as a resume on this:
#323  #288 #242 are issues related and with open status.
In #288 @amazingdropout recommend (as I) include the output of the [Schema](https://github.com/schemapress/Schema) plugin to your amp pages.
Is simple and feasible, only need a file and modifi other file in the Schema plugin to include it, take a look in the [integrations](https://github.com/schemapress/Schema/tree/master/includes/integrations) folder of the pluing

**Comment by ahmedkaludi** [comment]
Continuing this ticket in #323
