### ISSUE TITLE
Post Pagination not working for the long posts for Design 1

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4590]
Pagination is not working in my website . AMP page is https://sapbrainsonline.com/crm-tutorial?amp . You can refer the original url https://sapbrainsonline.com/crm-tutorial showing post pagination. How can I fix this?

**Comment by Zabi09** [comment]
Hi @syamsasi,

I have checked your website and found that you are not using our AMPforWP plugin and due to that pagination is not working on your website and will you please install our plugin and check once and we are sure that the pagination will work for sure.

**Comment by MohammedKaludi** [comment]
The issue not with our plugin will reopen the ticket if the issue is valid.
