### ISSUE TITLE
 customize font size of the h1 tag value is not applying in the post title.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4592]
Case 1:https://secure.helpscout.net/conversation/1209235324/138560?folderId=2770543

See these screenshots:

1.https://prnt.sc/ta9psb
2.https://monosnap.com/file/Tqek1VwchXQbuOqY916N0p6fz4BSvk

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58 update
