### ISSUE TITLE
Arrows not getting aligned properly in Breadcrumbs in Arabic Language with Swift theme

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4593]
The issue is occurring when the user is using Arabic to develop there website.
Arrows in the breadcrumbs section are not getting aligned properly.

 Screenshot : https://prnt.sc/tag0j8

Reference link to helpscout : https://secure.helpscout.net/conversation/1211897958/138784?folderId=3953286

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58 update
