### ISSUE TITLE
When yoast title is modified then the same modified title is not redering in amp

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4595]
when yost title is modified then the same modified title is not rendering in amp instead wp title is rendering

Ref: https://secure.helpscout.net/conversation/1212753135/138952?folderId=2632030

Ref URL: https://www.castlecrypto.gg/william-shatner-blockchain-trading-cards-wax/amp/

https://www.castlecrypto.gg/william-shatner-blockchain-trading-cards-wax

**Comment by MohammedKaludi** [comment]
Issue fixed in 1.0.57 update.
