### ISSUE TITLE
Need to add an attribute "Open By Default" inside the accordion module of the AMP Page Builder

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4597]
Ref: https://secure.helpscout.net/conversation/1110549265/116951?folderId=2770545

We need to add an attribute "Open By Default" inside the accordion module of the AMP Page Builder.  If the user sets this attribute then that accordion should show open by default on the load of the page.

Ref: https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fcomponents%2Famp-accordion.example.1.html%3Fformat%3Dwebsites&format=websites

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.61
