### ISSUE TITLE
Letter-spacing in Swift Theme if RTL is enabled 

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4598]
If the RTL is enabled in the  Swift theme there should not be any letter-spacing(CSS property) which is creating separated letters issues.

Video recording : https://take.ms/Z2s8S

Reference link to helpscout : https://secure.helpscout.net/conversation/1211897958/138784?folderId=3953286

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.59 update
