### ISSUE TITLE
Hunderts of PHP Warnings

### ISSUE THREAD

**Issue by onemillionplaces** [ahmedkaludi/accelerated-mobile-pages#4600]
Hi,

I bought your Plugin on Codecanyon already in 2016... so I´m one of the firt users :)

At the moment I got every 1-5 minutes new PHP Warnings from your plugin in my Error Logs:

[03-Jul-2020 15:21:05 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/travelth/public_html/wp-content/plugins/wp-amp/templates/single-content.php on line 19

This means I got hunderts of entries every day - so my Error Log is full with this :(

I know it´s just a PHP Warning - but what´s wrong with the "Invalid argument" on line 19? And how can I fix it?

Michael

**Comment by ahmedkaludi** [comment]
We’re not that plug-in. We are AMPforWP, opensource at Wordpress.org repo. We never sell on the codecanyon as well.

But I think you must try our plug-in, hopefully you won’t have that many debug warnings, and even if you did, our responsible team of developers will help you solve as fast as possible
