### ISSUE TITLE
Menu is hidden behind the content in iOS devices only when the sticky header option is enabled.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4601]
https://secure.helpscout.net/conversation/1212190941/138828?folderId=3243584
ramdistribution.co.uk/amp
*Currently the sticky header option is turned off.

Android devices:- https://prnt.sc/tbl0mg
iOS devices :- https://prnt.sc/tbl0vt

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://wordpress.org/support/topic/the-menu-in-ios-appears-cut-off/

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58.1

**Comment by Marcocastro2020** [comment]
I see that in Github it says that the issue has been fixed in the version that was updated today,  Version 1.0.58.1.

But I have tested it in various browsers on my Iphones and the menu is still behind the content.

I have cleared the cache on the website and phones but still, the issue remains the same.

:(   :(

**Comment by MohammedKaludi** [comment]
did you updated to the latest version of AMPforWP and if it still not working with 1.0.58.1 can you share your site's URL?

**Comment by Marcocastro2020** [comment]
Hi, Yes updated it a couple of hours ago.
https://www.ramdistribution.co.uk/
![amp1](https://user-images.githubusercontent.com/66689284/87037145-b2386a00-c1e3-11ea-93f2-5e3c3e6d0be5.PNG)

**Comment by Marcocastro2020** [comment]
Please see screen video I just made now, on my iPhone:

https://streamable.com/olj9fv

**Comment by MohammedKaludi** [comment]
Can you please update to 1.0.58.2 and test it please.

**Comment by Marcocastro2020** [comment]
Hi, Where can I download version 1.0.58.2 from?

**Comment by MohammedKaludi** [comment]
its already live in WordPress.org 

![image](https://user-images.githubusercontent.com/16618009/87050562-0c552180-c21c-11ea-892f-379a3679f924.png)

**Comment by Marcocastro2020** [comment]
Its, WORKING!!   :)  :) 👍 👍 🥇

**Comment by MohammedKaludi** [comment]
@Marcocastro2020 If you could rate us 5 ⭐️  review in WordPress.org  that would be very helpful for the plugin.

Thanks.

**Comment by Marcocastro2020** [comment]
Will do!

**Comment by Marcocastro2020** [comment]
![AMP BEST PLUGIN](https://user-images.githubusercontent.com/66689284/87055039-ba040880-c1fb-11ea-9b93-4bb0ae9f43a3.PNG)

**Comment by MohammedKaludi** [comment]
Thank you very much for the feedback.
We really appreciate it.
