### ISSUE TITLE
Need to load the "Webmaster Tools" details of rank math on the AMP Homepage

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4602]
Ref: https://secure.helpscout.net/conversation/1213887343/139143?folderId=2770545

We need to add the "Webmaster Tools" details of the rank math on the AMP homepage. The user is using the AMP Takeover option.

Screenshot: 
https://prnt.sc/tbl2f5
https://prnt.sc/tbl2lr

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.59 update
