### ISSUE TITLE
A paragraph with the entire post un-formatted content is published if we don't add anything in the "Excerpt"

### ISSUE THREAD

**Issue by netnaps** [ahmedkaludi/accelerated-mobile-pages#4603]
Maybe this is a small issue, but if we don't use the excerpt while making a post entire post content is displayed twice, that is an unformatted post as plain text and then the edited blocks, 

as soon as we submit some text in the **excerpt,** everything is normal,

So, in short, the post content is published twice one is unformatted at the top and then it's the formatted one,

Note: No plugins are on the posting page besides Free Yoast Seo.

**Comment by MohammedKaludi** [comment]
@netnaps 
This is very strange, can you send the URL of the site and can you please let me know what theme are you using?

Also,is. this first install of yours or you were using AMPforWP for some time and this happened after some recent update?

**Comment by netnaps** [comment]
Yes its the first time this happened, I have just started a blog I actually corrected this on my page as I have mentioned above by doing an excerpt for a text line. 

You can check this on any environment I am not using any theme its default 2020 and no extra plugins as well. 

it's an AMP take over.

the URL of my recent post is: https://netnaps.com/wordpress-premium-plugin-sold-cheap-as-a-gpl-not-the-right-choice/

Also in the sharing part, I can't see the **twitter icon** after the recent 2 updates, for caching i am using Autoptimize that I usually keep it deactivated and have some cache commands at the .htaccess

**Comment by MohammedKaludi** [comment]
Thank you for the info, we are testing it, give me some time I'll get back to you.

**Comment by netnaps** [comment]
Ok, Please check with the Twitter Icon as well, and hopefully, if you find it out, roll it out in the next update, please.
The plugin is excellent. I like this a lot. Thanks!!

One more thing if you don't mind as an improvement 

On the posting page, while posting a new post at last it says: " Show AMP for current Page " That Should be " Show AMP for Current Post"  as Posts & Pages are entirely different in WordPress. 

Small things, but improvement is an improvement.

**Comment by MohammedKaludi** [comment]
> On the posting page, while posting a new post at last it says: " Show AMP for current Page " That Should be " Show AMP for Current Post" as Posts & Pages are entirely different in WordPress.

Sure will keep it in mind.

**Comment by netnaps** [comment]
Thanks

**Comment by netnaps** [comment]
It was quick, Thanks by when does this rolls out?

**Comment by MohammedKaludi** [comment]
If it passes through the testing, it can be pushed either on Monday or
Tuesday.

**Comment by netnaps** [comment]
Ok thanks, Kindly check on the twitter icon missing as well.

Your support and plugin are both great! Best of Luck

**Comment by MohammedKaludi** [comment]
Increase the length to 25 while merging

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58 update

**Comment by netnaps** [comment]
Thanks, twitter icon not shown near author bio still if you can check sharing bar this is showing now.
