### ISSUE TITLE
Breadcrumb after the recent update is not inline 

### ISSUE THREAD

**Issue by netnaps** [ahmedkaludi/accelerated-mobile-pages#4604]
After the recent update, the breadcrumb at the mobile view is not showing inline and also is showing in ALL Caps this gives a look like 

HOME >
BLOG >
TECHNOLOGY > 
POST TITLE 

earlier it was simple Home > Blog > Technology > Title 

Please make the same as it was earlier this looks out of the design.

**Comment by netnaps** [comment]
Also, the Default Gutenberg List Block is not supporting the font size if you can check the same.

**Comment by ahmedkaludi** [comment]
@netnaps can you share the URL where you are facing this issue?

**Comment by netnaps** [comment]
https://netnaps.com/wordpress-premium-plugin-sold-cheap-as-a-gpl-not-the-right-choice/

it's on the mobile view, earlier it was capitalized now its all caps, 

also, see the list in the content has different font size as the AMP is not supporting default list type block.

**Comment by Zabi09** [comment]
Our breadcrumbs will appear in the caps only and if you want it to display capitalized  then add this CSS to make your breadcrumb capitalized 
`ul#breadcrumbs li a, ul#breadcrumbs li span { text-transform: capitalize; }`

And also we have tested the Default Gutenberg List Block and there is no option to change the font size in that - https://prnt.sc/tdy54a and if you want change it then you can also add font size CSS in our plugin.
