### ISSUE TITLE
" No index" tag is appearing on the AMP page while using rank math SEO.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4608]
" No index" tag is appearing on the AMP page while using rank math SEO.

Ref: https://secure.helpscout.net/conversation/1214367406/139218?folderId=3575684

**Comment by Zabi09** [comment]
User enabled tag base remove in AMP but he didn't remove in non-amp that's the reason the user was getting noindex as he also enabled the Noindex Empty Category and Tag Archives in rank math settings - https://prnt.sc/td62lq

So closing this ticket
