### ISSUE TITLE
noindex on homepage using Yoast

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4609]
it's coming on the Homepage, https://louisbouten.nl/amp/

https://secure.helpscout.net/conversation/1215146033/139403/

**Comment by MohammedKaludi** [comment]
Need to add method exists for `WPSEO_Meta::get_value`
 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5f47a26a0e40db2e1662146ca7ba8bdae245b55e#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8820

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.59 update
