### ISSUE TITLE
AMP is not serving in the home next page when we use "Magplus" theme

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4611]
AMP is not serving in the home next page when we use "Magplus" theme

Ref:https://secure.helpscout.net/conversation/1215347875/139501?folderId=3575684

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.59 update
