### ISSUE TITLE
View non amp version is not working in mobile due to conflict with Redis Cache and WP Rocket

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4614]
Ref : https://secure.helpscout.net/conversation/1168676747/130585?folderId=3611365

Video : https://monosnap.com/file/EbpCcmMqlrZOFfAuvxGRaxFLjvmsqL

User is using Cloudflare, WP rocket, Redis cache plugins.

**Comment by MohammedKaludi** [comment]
Closing the ticket due to lack of information, will reopen if we have any or if we are able to recreate the issue at the localhost.

**Comment by MohammedKaludi** [comment]
Now we have the required info, we can start the debugging

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
