### ISSUE TITLE
Infinite Scroll is not working due to conflict with Redis Cache and WP Rocket

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4615]
Ref : https://secure.helpscout.net/conversation/1168984716/130623?folderId=3611365

Video : https://monosnap.com/file/ie0ibwcxLEmQn0TTmzFtDNdJN9OpvK

User is using Cloudflare, WP rocket, Redis cache plugins.

**Comment by MohammedKaludi** [comment]
Closing the ticket due to lack of information, will reopen if we have any or if we are able to recreate the issue at the localhost.

**Comment by MohammedKaludi** [comment]
@Zabi09 do looking into this ticket

**Comment by Zabi09** [comment]
Infinite Scroll is working fine on this website, So closing this ticket
