### ISSUE TITLE
Quote Block Shows A different style not default one 

### ISSUE THREAD

**Issue by netnaps** [ahmedkaludi/accelerated-mobile-pages#4616]
**This is shown:** 

![Screenshot 2020-07-08 at 12 43 52 AM](https://user-images.githubusercontent.com/67054369/86831328-633fe700-c0b4-11ea-97e3-7aa82baf1a12.png)

**While the Default is this:**

![Screenshot 2020-07-08 at 12 43 31 AM](https://user-images.githubusercontent.com/67054369/86831424-81a5e280-c0b4-11ea-8848-e4f29be1f5af.png)

**Comment by ahmedkaludi** [comment]
The one you See in editor is coming from the theme. So it’s different, while amp has different design. For more answers, please contact us through website
