### ISSUE TITLE
Creating Database Deadlocks resulting in Wordpress unavailability

### ISSUE THREAD

**Issue by raydvard** [ahmedkaludi/accelerated-mobile-pages#4618]
**_WordPress Version: 5.4.2_**

**_AMP for WP – Accelerated Mobile Pages: 1.0.58_**

I am having so much issue with this plugin on the website, which creating deadlocks in my database constantly and making the WordPress site unavailable.

**_Basically, it is trying to insert and update an entry for amp transient and get stuck._**

**_Here is the deadlocks transaction history:_**

[https://pastebin.com/qjp0rxCz](https://pastebin.com/qjp0rxCz)

**Comment by MohammedKaludi** [comment]
This is very strange, Looking into the issue, and will be fixed in next update.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58.5
