### ISSUE TITLE
Featured Images  are Too Small using Envato Elements plugin

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4619]
When a user using the "Envato Elements" plugin on his AMP page the featured images are too small. 

Reference: https://wordpress.org/support/topic/featured-images-too-small-2/
Website: https://granite.ph/amp/

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/1146176081/124829/

**Comment by Zabi09** [comment]
It was due to AMP page builder compatibility so created the ticket in Trello board
