### ISSUE TITLE
Valdatioin error  The attribute 'target' may not appear in tag 'span'. is appearing when Rank Math plugin is activated

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4620]
Ref: https://secure.helpscout.net/conversation/1214345097/139211?folderId=2632030

https://www.feedough.com/brand-value/amp/

Validation error  The attribute 'target' may not appear in tag 'span'. is appearing when Rank Math plugin is activated.

The error is occurring after the update 1.0.57

The issue is occurring when the span element contains data-preserver-spaces="true" attribute after the link content then for this span target="_blank" attribute is getting added and creating a validation error.

Ex this line of HTML markup : <a href="https://www.google.com">fdfsdsf</a><span data-preserver-spaces="true">The rising competition</span>

Please see this video the issue is shown: https://monosnap.com/file/nK2lU34kFFbzCilHreyz9SkKmauSEf

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.58.1
