### ISSUE TITLE
Internal feedback Improvement for Longtime Users

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4622]
Internal feedback Improvement for Longtime Users

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Some code improvement is required 


https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6b9bd781d8f08bd04c63ed6f9e7768d705eca489#diff-04b38a94ddf918855eed7a68ecaa512dR1436

**Comment by MohammedKaludi** [comment]
Translation required 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d2871a47e85cfbc45e9cc6e7e51a50d9e1c2b927#diff-04b38a94ddf918855eed7a68ecaa512dR1444

**Comment by MohammedKaludi** [comment]
add this option in the uninstall file so that all the data is properly removed after uninstallation 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d2871a47e85cfbc45e9cc6e7e51a50d9e1c2b927#diff-04b38a94ddf918855eed7a68ecaa512dR1452

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
