### ISSUE TITLE
Fatal error due to social sharing option after the latest update of Jetpack 8.7

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4624]
JetPack’s 8.7 updates the have added new social icon code and that is breaking in AMP pages

If rolled back to 8.6 or Turning off Social Share its working fine.

https://wordpress.org/support/topic/plugin-causing-500-internal-server-error-3/

**Comment by MohammedKaludi** [comment]
pushed in 1.0.58.3 update.
