### ISSUE TITLE
The tag ‘link rel=canonical’ appears more than once in the document.

### ISSUE THREAD

**Issue by kuljeet07** [ahmedkaludi/accelerated-mobile-pages#4625]
The tag ‘link rel=canonical’ appears more than once in the document.” webmaster amp error I am using AMP for WP - Accelerated Mobile Pages and rank math plugin please help

**Comment by MohammedKaludi** [comment]
Have you set up SEO integration from the AMPforWP options panel? And chose RankMath in `Select SEO Plugin` field?

https://monosnap.com/file/RdF7NRmJD9WKJiN9E4MPiKqxFoudyU

**Comment by kuljeet07** [comment]
> Have you set up SEO integration from the AMPforWP options panel? And chose RankMath in `Select SEO Plugin` field?
> 
> https://monosnap.com/file/RdF7NRmJD9WKJiN9E4MPiKqxFoudyU

sir, i have seen this too but nothing has happened i have checked in the amp checker so it is showing this error again and again.
https://monosnap.com/file/mmONCeb8QRG9xMM9XBUeYgfnDhbqt6

**Comment by MohammedKaludi** [comment]
Just tested and seems there is no issue reported in AMP validator 

https://monosnap.com/file/0R8kZi8mbG7rovUjT8jPZXqcTHB6LW
https://search.google.com/test/amp?id=CLKieKzbMTH9TMnakkgi1Q

Closing the ticket, for now, please reopen the issue if the issue persists.

**Comment by kuljeet07** [comment]
> Just tested and seems there is no issue reported in AMP validator
> 
> https://monosnap.com/file/0R8kZi8mbG7rovUjT8jPZXqcTHB6LW
> https://search.google.com/test/amp?id=CLKieKzbMTH9TMnakkgi1Q
> 
> Closing the ticket, for now, please reopen the issue if the issue persists.

ok thanks sir,
