### ISSUE TITLE
Debug warnings  should be the title

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4626]
Notice: Undefined property: DOMElement::$tagName

Website: https://greentealobby.com/life-extension-mega-green-tea-extract-review/amp/
Reference: https://wordpress.org/support/topic/notice-undefined-property-domelementtagname/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.59 update
