### ISSUE TITLE
Table is are displaying blank in the AMP version when the table is created with a " Tiny MCE advanced " plugin.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4627]
The table is are displaying blank in the AMP version when the table is created with a " Tiny MCE advanced " plugin.

Ref:https://secure.helpscout.net/conversation/1207102411/138218?folderId=3575684

Ref:(https://wordpress.org/plugins/tinymce-advanced/)

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.61
