### ISSUE TITLE
Error : GET https://cdn.onesignal.com/sdks/amp/amp-helper-frame.js net::ERR_ABORTED 404 in console when onesignal option is chosen for push notification

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4629]
User has notified the error "GET https://cdn.onesignal.com/sdks/amp/amp-helper-frame.js net::ERR_ABORTED 404" in console when the onesignal option is chosen. 

ref: https://secure.helpscout.net/conversation/1221350330/141201?folderId=3678830
link reference: https://cdn.onesignal.com/sdks/amp/amp-helper-frame.js

**Comment by Zabi09** [comment]
Currently the user is not getting any error on his website and the user is saying "It seems the issue was solved on the last update."

So closing the ticket
