### ISSUE TITLE
Does homepage loop displays other posts than published posts?

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#463]
Such as..
Drafts, Private posts, and other types like these?

STATUS: VERY CRITICAL

**Comment by ahmedkaludi** [comment]
Exhibit A: https://wordpress.org/support/topic/which-one-feature-will-make-this-plugin-perfect-for-you/page/4/#post-8681287

**Comment by MohammedKaludi** [comment]
Fixed
