### ISSUE TITLE
Issue with menu background when user add internal page navigation menu-items.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4630]
As per the user, having a single page and internal navigation menu-items in the AMP menu.

When Users click on those menu Items the page is perfectly scrolling to the exact location but the menu is still active on the screen, It should be like when it navigates to the exact location menu needs to be closed automatically.

Ref Ticket: https://secure.helpscout.net/conversation/1217309329/139919?folderId=3126461
Ref Video: https://secure.helpscout.net/conversation/1217309329/139919/#thread-3492642262

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
