### ISSUE TITLE
duplicate <title> tag on non-amp [rare issue]

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4631]
duplicate <title> tag on non-amp

https://secure.helpscout.net/conversation/1222651103/141486/

**Comment by HaripriyaHari** [comment]
Same issue for another user: https://wordpress.org/support/topic/duplicate-title-tags-21/

**Comment by saranshkataria** [comment]
I don't think this is a rare issue. I am having it on all pages of my website

**Comment by MohammedKaludi** [comment]
@saranshkataria this issue has been fixed and we have just pushed it.

Pushed in 1.0.58.5
