### ISSUE TITLE
AMP shows blank page when using  classic wordpress editor

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4632]
When a user uses an old classic editor of WordPress, the AMP pages are showing a blank page.

Reference: https://wordpress.org/support/topic/amp-shows-blank-page-when-article-use-classic-wordpress-editor/
website: https://www.byothe.fr/2019/12/imprimer-une-page-web-entiere-en-pdf-avec-pdf-cyborg/amp/

**Comment by MohammedKaludi** [comment]
Fixed in 1.0.58.4

**Comment by MohammedKaludi** [comment]
was fixed in #4586 
this was happening due to this code which was removed
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a34f1222460abfa521bbe794c33e28b4eea9384a
