### ISSUE TITLE
URL with square brackets [ ] causing issue in AMP

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4635]
In non-AMP version URLs with square brackets[ ] are working but in AMP version it is causing error.

Example URL :- https://microcimento.pt/portfolio/interiores/casas-de-banho/#iLightbox[gallery_image_1]/1

sample code : `<a href="https://microcimento.pt/portfolio/interiores/casas-de-banho/#iLightbox[gallery_image_1]/1">test</a>`

Helpscout ticket:- https://secure.helpscout.net/conversation/1209240928/138561?folderId=3953286

Error Screenshot :- https://prnt.sc/ti97u2

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.59 update
