### ISSUE TITLE
Product review disappeared in AMP 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4636]
When a user using Product Review Lite plugin, the AMP page is not showing.
Reference: https://wordpress.org/support/topic/product-review-disappeared-in-amp/

**Comment by Zabi09** [comment]
Going to fix in - https://wordpress.org/support/topic/product-review-disappeared-in-amp-2/

**Comment by MohammedKaludi** [comment]
The issue is due to WP Product Review Lite  and  not with ampforwp

they are looking into the issue 
https://wordpress.org/support/topic/product-review-disappeared-in-amp-2/

Closing the issue.
