### ISSUE TITLE
AMP page is facing styling issues with Reactions plugin by Vicomi

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4637]
AMP page is facing styling issues while using this plugin "Vicomi feedback".

Ref:https://secure.helpscout.net/conversation/1225078907/141910?folderId=3575684

Note: This issue not unable to recreate local because when we install this plugin it showing an error as per the screenshot(https://prnt.sc/tiy10d).

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.60
