### ISSUE TITLE
Ability to change AMP ads class

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#4638]
Hello,

Now with some adblockers, all amp ads are blocked and it's causing revenue issues. I suspect it's due to obvious tags like "ad", etc. 

I'd like to suggest a change where these ad-wrappers are renamed to that of user selection or made into a random string.

> amp-ad-wrapper amp_ad_3 ampforwp-standard-custom-banner ampforwp-ad-above-post

**Comment by ahmedkaludi** [comment]
We will create the ad blocker feature in the future release, this issue will be moved to its respective repository
