### ISSUE TITLE
Create a filter when either user is using any external CDN or want to turn off the Aqua_resizer for some reason.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4641]
Example url:- https://seucreditodigital.com.br/amp/
Fix has been made on users' end.

` // Disable ampforwp_aq_resize and return images without compressing.
        // Usefull for some who wants to disable when using CDN images
        $disable_aq_resize = false;
        $disable_aq_resize = apply_filters('ampforwp_disable_aq_resize', $disable_aq_resize);
        if ( $disable_aq_resize ){
            return $image = array(
                0 => $url,
                1 => $width,
                2 => $height,
            );
        }`

1. https://prnt.sc/tjofb9
2. https://prnt.sc/tjog6t

**Comment by MohammedKaludi** [comment]
ready to go

**Comment by MohammedKaludi** [comment]
pushed in 1.0.59 update
