### ISSUE TITLE
Need to add a filter so we can overwrite the scripts.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4642]
Need to add a filter so we can overwrite the loaded scripts and add any new script by using that filter.

**Comment by MohammedKaludi** [comment]
this is incorrect fix done.

**Comment by MohammedKaludi** [comment]
this is how one can overwrite the script to different versions 

`add_filter('ampforwp_modify_scripts', 'test');`
`function test($s){`
             `return $s .= '<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>';`
`}`

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.67
