### ISSUE TITLE
Need to create an amp code - Add truepush as push notification in AMP for Wp plugin

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4644]
Need to create an amp code - Add true push like a push notification in AMP for Wp plugin

https://secure.helpscout.net/conversation/1225930426/142050?folderId=1060556

**Comment by ahmedkaludi** [comment]
Here is a link to the integration method for AMP in our push notifications tool.
https://www.truepush.com/blog/truepush-api-integration-for-amp/

**Comment by MohammedKaludi** [comment]
Making the same mistake again, use the `esc_raw_url` function whenever we have a query string in the URL, esc_url will convert the string into characters and that could lead to some issues. 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8ded27e4eb60e515bf83d73c36e9c2f380456621#diff-7d6877c810fb733c65e0e21cc6c96d61R238

The naming of the settings -> `ampforwp-truepush-public_key` it should be standard as `ampforwp-truepush-public-key`
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8ded27e4eb60e515bf83d73c36e9c2f380456621#diff-7d6877c810fb733c65e0e21cc6c96d61R229

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
