### ISSUE TITLE
Google Analytics trigger functionality not working.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4645]
Desc: Need to place GA trigger code parallel to vars as of now it is inside var code.
https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/includes/features/analytics/analytics-functions.php#L26

**Comment by MohammedKaludi** [comment]
ready yo merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.59 update
