### ISSUE TITLE
Need to add a new redux field type "multitext_repeater"

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4647]
Desc: Need to add a new redux field type "multitext_repeater".

**Comment by Zabi09** [comment]
Toggle not working in GTP - https://monosnap.com/file/gmor2xFbGARvzwOEpEjDIekBKD5BuI
Incorrect url - https://prnt.sc/tl7omq

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
escaping required on multiple places.
for `$div_cls= $form_class=$span = $hide = '';` and other vars
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9e158330257a99740120634261883d3b8e0c2a76#diff-67bc8d819b90ffe7515f486032e99692R215

**Comment by MohammedKaludi** [comment]
ready to go.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.60
