### ISSUE TITLE
The autoplay attribute is getting stripped in the amp-vimeo tag.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4648]
The autoplay attribute is getting stripped in the amp-vimeo tag.
Ref: https://secure.helpscout.net/conversation/1223232345/141560/

**Comment by Zabi09** [comment]
Commit - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/990073ef7d7865d9478a956c19ba6edc4c25654d

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.60
