### ISSUE TITLE
Need to add an option to accept individual cookies

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4649]
Case 1: https://secure.helpscout.net/conversation/1226466997/142174?folderId=2770543

We need an option, user can select individual cookies and also select all cookies.

**Comment by Zabi09** [comment]
we create only 3 cookies, and in that one will be just the value of whether you have accepted or rejected and the remaining 2 will be for analytics and all these 3 things are essential for us - https://monosnap.com/file/5kEE9XNZCHHxDXkQdEqzeTcFvMyen2.

So closing this ticket for now
