### ISSUE TITLE
Script not loading for Amp-iframe not working inside Custom AMP Editor

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#465]
I added Custom content with iframe inside Custom AMP Editor –

<amp-iframe src=”URL” width=”1000″ height=”320″ frameborder=”0″ sandbox=”allow-scripts allow-same-origin”></amp-iframe>

But it is not working as the script is not included in head –

#ref https://wordpress.org/support/topic/amp-iframe-not-working-inside-custom-amp-editor/

**Comment by tvarghesedt** [comment]
@khaledMohammed000 , I am facing a similar issue with amp-carousel. How can I add it inside Custom AMP Editor in the HTML form. Can you please help out.

**Comment by ahmedkaludi** [comment]
You can just add gallery in the Custom AMP editor and it will show up as carousel.

**Comment by tvarghesedt** [comment]
@ahmedkaludi  Thanks for the solution, it helped a lot. :)

I am wondering there are so many components in amp, so i think on pages we should allow amp-html. I am working on a site where i need to make amp alternate version of Pages, i may need so many components. How can i just add them simply, please suggest.

**Comment by MARQAS** [comment]
Hey @tvarghesedt , 
We closed this ticket long ago, that's why unable to see this comment of yours.
Have you got the solution for your problem?

**Comment by tvarghesedt** [comment]
Yes, Found the solution. Thanks!
