### ISSUE TITLE
While using infinity scroll user wants to show related posts after the last post.

### ISSUE THREAD

**Issue by wokstationKomal** [ahmedkaludi/accelerated-mobile-pages#4652]
When we use infinity scroll with the related post option then related posts show after every post. The user wants to show related posts after the last post.
Ref: https://secure.helpscout.net/conversation/1229920605/142982?folderId=3257665

**Comment by MohammedKaludi** [comment]
done

**Comment by Zabi09** [comment]
Pushed in 1.0.76.14
