### ISSUE TITLE
Lighthouse Audits

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4654]
- [x] Swift

- [x] D3

- [x] D2

- [x] D1

**Comment by DikshantJoshi** [comment]
lighthouse issue:
Links are not crawlable:

Uncrawlable Link
<a id="scrollToTopButton" title="back to top" on="tap:backtotop.scrollTo(duration=500)" class="btt">

Screengrab: https://monosnap.com/file/F5tQr2M7KyyRsxXdEHA0e9VEprnLVe

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by hieptd** [comment]
@Zabi09 At the "back to top link" section, I to fix it to the button and it worked fine.

**Comment by hieptd** [comment]
I look forward to improvements based on Lighthouse Audits. Especially the speed improvements @MohammedKaludi  @Zabi09

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
