### ISSUE TITLE
Optimize code to reduce the calls in database

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4657]
Optimize menu caching code to reduce the calls in database

**Comment by Arihantkankariya09** [comment]
A new user with the issue of slow queries and high load, https://secure.helpscout.net/conversation/1248662788/147271?folderId=2770543

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65.2 update
