### ISSUE TITLE
Remove Shorthand versions of PHP from the code base

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4659]
Reference: https://wordpress.org/support/topic/php-short-tag-deprecation/

-  accelerated-mobile-pages/classes/class-ampforwp-infinite-scroll.php lines 106 and 107

- accelerated-mobile-pages/includes/options/extensions/vendor_support/vendor_support/vendor/ace_editor/snippets/php.js

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.61
