### ISSUE TITLE
Issues on categories on mobile...redirecting to home page instead of categories

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#466]
https://wordpress.org/support/topic/category-redirects-to-homepage/

**Comment by khaledMohammed000** [comment]
This is slightly related to mobile redirection so this am posting here https://wordpress.org/support/topic/redirect-amp-dont-work-with-wpforo/#post-8718950

**Comment by khaledMohammed000** [comment]
This is also related https://wordpress.org/support/topic/menu-selections-not-working/

**Comment by ahmedkaludi** [comment]
This was fixed in 0.9.40.
