### ISSUE TITLE
Need to update the code for amp pagebuilder's category-module

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4660]
https://monosnap.com/file/Hs6JvYd8haiMhaMQb1mlbxu9LZEFwB

this code is calling even when not is used, which is impacting the performance of the site when logged in.
for non-logged in users it has no impact at all.

`$categories = get_categories( array(   
                   'orderby' => 'name',   
                   'order'   => 'ASC',
                   'number'  => 500   
               ) ); `

**Comment by ajeetku** [comment]
This will completely blank the page
https://prnt.sc/tnu75l result: https://prnt.sc/tnu7d8

For this we can add a solution with 2 conditions:
Frontend: when page builder enabled on the respective page
backend: only on page-new.php and page.php

**Comment by MohammedKaludi** [comment]
also the gallery is not working https://monosnap.com/file/ucCe33eHfq9FzD4hJ4jizOmHvQKxLJ

**Comment by MohammedKaludi** [comment]
@ajeetku is this the correct fix?
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cbb62a1516d98e085d293b980b3e8104ec713d06

**Comment by ajeetku** [comment]
Yes it's working now

**Comment by MohammedKaludi** [comment]
![image](https://user-images.githubusercontent.com/16618009/98213534-35d44e80-1f6b-11eb-9b97-e6a1baf87b76.png)

Instead of placing the `$checkpb`

on-line no:23  if the check is added on top it will save some PHP operations and checks at the very top and can improve some performance.

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5c9b79802dd83514d8ca1ff325614a071d127f0a#diff-929aa2a7d1e1f6a14b511b507217d02d0e6e3ad9cbffcd5a0cda0d6dcd915c52L23

**Comment by MohammedKaludi** [comment]
ask ajeet for the reason of failing.

**Comment by MohammedKaludi** [comment]
Ready to push.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.68
