### ISSUE TITLE
Homepage URL has /amp at the end even after enabling AMP Takeover (Beta)

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/accelerated-mobile-pages#4662]
Ref : 
https://secure.helpscout.net/conversation/1226891061/142260?folderId=3611365

Issue is recreated by importing user's AMP settings.
Ref : 
https://monosnap.com/file/0BWybGVu7lsfxIQvqTsy2Wdl9d80ss

**Comment by MohammedKaludi** [comment]
Previous ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1994

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.61
