### ISSUE TITLE
Add a hook filter. to be able to filter URLS before output to meta amphtml

### ISSUE THREAD

**Issue by kacevnik** [ahmedkaludi/accelerated-mobile-pages#4663]
Add a hook filter. to be able to filter URLS before output to meta amphtml. Since the problem occurs when the url parameter is present, it is also displayed in the amphtml tag. Example: https://test.com/article/?pag=9 -> https://test.com/article/amp/?page=9"

```php
function ampforwp_home_archive_rel_canonical() {

		$amp_url = "";

		$amp_url = apply_filters( 'ampforwp_filter_htmlapm_url', ampforwp_amphtml_generator() );

		if ( $amp_url ) {
			printf('&lt;link rel="amphtml" href="%s" /&gt;', esc_url($amp_url));
			if(false==ampforwp_get_setting('hide-amp-version-from-source')){
				printf('&lt;meta name="generator" content="%s %s"/&gt;', esc_html__('AMP for WP'), esc_attr(AMPFORWP_VERSION) );
			}
		}

	} //end of ampforwp_home_archive_rel_canonical()
```

**Comment by MohammedKaludi** [comment]
the filter is available inside he `ampforwp_amphtml_generator()` function which is generating the url.

you can access the filter from here https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/features.php#L379

and you can modify the url using this filter : `$amp_url = apply_filters('ampforwp_modify_rel_canonical',$amp_url);`

Closing the ticket for now, please do let me know if you have any other questions.
