### ISSUE TITLE
The wrong breadcrumb links are generating in the AMP 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4666]
Ref: 
1. https://secure.helpscout.net/conversation/1225406893/141959?folderId=2770545
2. https://secure.helpscout.net/conversation/1233676168/143741?folderId=1060554

In the AMP breadcrumbs URL are generating like href="http://https://www.meilleure-innovation.com/environnement/ecologie/amp/"> instead of href="https://www.meilleure-innovation.com/environnement/ecologie/amp/">

Screenshot: https://prnt.sc/tp3j01

Steps to recreate:

1. Enable option is the "Change Internal Links to AMP" option in the AMP Advance settings
2. Enable the  "Breadcrumbs From Yoast" option in the Seo settings after selecting YOAST.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.61
