### ISSUE TITLE
Need to make AMP compatible with Web stories by Google

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4667]
I have run a basic test on my localhost by installing the plugin and adding the stories to my posts.
While the stores did appear on the NON-AMP version of the post, but not on AMP version.
A few screen grabs for reference:
Non-AMP: https://monosnap.com/file/kyVUN6nrBpuLSR7uPUfpTVuWPJmIVA
AMP: https://monosnap.com/file/42vErOy6tJqA7ezoF0onVSGH4yCeIC

**Comment by sonaliramteke** [comment]
While testing this ticket validation error occurred  - https://prnt.sc/ufhjkh

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://wordpress.org/support/topic/will-the-web-stories-plugin-from-google-be-supported/

**Comment by akashagrjsr** [comment]
one more user requested it:
https://secure.helpscout.net/conversation/1307525488/159030?folderId=2770545

On local after adding the story in the AMP version only the title is showing, other contents are not showing.
Screenshot: https://prnt.sc/uycxdm

**Comment by MohammedKaludi** [comment]
this is not required 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ab5c942206652e538575d440f1366ed4153131df#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580R9186

**Comment by MohammedKaludi** [comment]
Make sure to test the fix and its working fine. after merging.
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update

**Comment by juniorbra** [comment]
Hi @MohammedKaludi to make your plugin compatible with the Google Web Stories plugin, do I have to install your AMP Stories extension?
