### ISSUE TITLE
The right and left arrows are converting into the special characters in AMP

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4668]
Screenshot: https://prnt.sc/tpqvg5
Website: https://www.hoelangmoethetkoken.nl/amp/
Reference: https://wordpress.org/support/topic/trailing-en-following-a-2/

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9e276c3cb21d51dca7dbecd64cd38bda541b3328

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.61

**Comment by MohammedKaludi** [comment]
pushed in 1.0.61.1
