### ISSUE TITLE
Wrong preview link is generating for the AMP pages and posts

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4670]
Ref: https://secure.helpscout.net/conversation/1235145439/144162/

When we are creating an AMP page using the AMP Page Builder and saving to draft and when seeing for the preview it is generating the wrong preview URL.

For Example: 
For this preview page: https://wordpress-123147-847862.cloudwaysapps.com/?page_id=2043/
In it is generating the URL like https://wordpress-123147-847862.cloudwaysapps.com/?p=2048/amp/

It should generate like this: https://wordpress-123147-847862.cloudwaysapps.com/?page_id=2043&amp=1&preview=true

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
generating incorrect url in AMP mode https://monosnap.com/file/K7n2RrxBJiUMAP9XdpaRzzY9kPETsr

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.61
