### ISSUE TITLE
Query Monitor gives PHP Errors when on AMP option panel.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4671]
https://secure.helpscout.net/conversation/1230224966/143047?folderId=3243584

Screenshot for the errors.
https://prnt.sc/tqyk7z

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.62
