### ISSUE TITLE
CSS overirding issue for the list and accourdion moudules 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4674]
CSS overriding issue for the list and accordion modules in the amp page builder

Issue recreated in the internal system.

First module css is getting override the last modules css. The last modules css is getting applied for all other modules of the same type above to it.

REf: https://secure.helpscout.net/conversation/1237662815/144694?folderId=2632030

https://monosnap.com/file/0uDuOtKNPH5LTqUYEX3sWCGwapw3FZ

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.62
