### ISSUE TITLE
Need to compatible with Image Photo Gallery Final Tiles Grid plugin

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4675]
The galleries are not showing when checked in the Mobile devices.

Screenshot: https://prnt.sc/tr66lg
Website: https://www.foodfest.sk/cokoladova-torta-bez-muky/amp/
Reference: https://wordpress.org/support/topic/gallery-not-showing-on-amp/

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
