### ISSUE TITLE
Bug? Analytics not loading on Google hosted AMP Pages if GDPR Popup is used

### ISSUE THREAD

**Issue by seriou5** [ahmedkaludi/accelerated-mobile-pages#4679]
Hi guys,

we maybe discovered a strange bug/behaviour:

- we use GTM to track AMP traffic (via Analytics Universal Tag)
- we activated the GDPR consent popup in AMPforWP a few days ago
- since we activated the GDPR consent popup we are not receiving correct traffic data (it is decreasing day by day - we have a huge website with over 1000 posts, so I guess this is just normal as the problem "spreads")

After noticing this problem we compared our local AMP pages with the ones stored on the Google Servers. 

Example for local AMP page: https://www.we-go-wild.com/gefuellte-champignons-mit-frischkaese-low-carb/amp/
Same AMP page on Google servers: https://www.google.com/amp/s/www.we-go-wild.com/gefuellte-champignons-mit-frischkaese-low-carb/amp/ (you have to open it with Chrome Dev Tools and **simulated mobile devices** to load properly from Google - otherwise it will redirect to our normal page)

We found out that after giving consent the Analytics Cookies etc. are loading normal on our local AMP pages BUT they are not loading on the AMP pages stored on the Google servers. Resulting in false (nearly zero) data. Resulting in a drop in tracked AMP traffic in Analytics. 

We tested this behavior with GTM and the built in GA settings. 

You should be able to check it on the example pages mentioned above. (Dev Tools --> Application --> Cookies)

Best regards

---

AMPforWP Version: 1.0.60
Newspaper AMP Template Version: 2.0.5 (I know it is a bit older, but should not be the problem right?)
WordPress Version: 5.4.2

**Comment by ahmedkaludi** [comment]
Github is for tested and re-creatable bugs, for support please reach out to us via website.

**Comment by Zabi09** [comment]
Going to fix in #4707
