### ISSUE TITLE
Need to Add a “current-menu-item” class for “Homepage” menu

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4680]
Need to add a class “current-menu-item” in the menu for li element of a “Homepage” menu link which will mark that this menu is currently active, and it works for the other menu item.

Here is an example – class for the menu of Homepage:
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home"><a href="/amp/" class="dropdown-toggle" data-toggle="dropdown"><span>Home</span></a></li>

And here is an example of an internal page: 
<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item current_page_item"><a href="/contacts/amp/" class="dropdown-toggle" data-toggle="dropdown"><span>Contacts</span></a></li>

Reference: https://wordpress.org/support/topic/add-a-current-menu-item-class-for-homepage/

**Comment by Zabi09** [comment]
We do add the current-menu-item in the menu for homepage and also for active pages and may be due to transients the user was not able to see, So closing the ticket
