### ISSUE TITLE
Create a help section for the users in Options panel

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#4683]
Create a help section for the users in Options panel

**Comment by ahmedkaludi** [comment]
- [ ]  https://take.ms/iNpTC Let's add a link here called Documentation which will take them to: https://ampforwp.com/tutorials/

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/98fc7d3639fdb109b3b3fffb1170ee9698ddb466#diff-260eba6333c3222e59a6aed22ac5ab37R8496
Add escaping for translation

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.67
