### ISSUE TITLE
Need to integrate iubenda Cookie Solution

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4687]
Ref: https://secure.helpscout.net/conversation/1246110282/146776/

Ref URL: https://www.iubenda.com/en/help/22135-cookie-solution-amp

**Comment by syedimran22** [comment]
iubenda – Cookie and Consent Solution for the GDPR & ePrivacy Plugins https://wordpress.org/plugins/iubenda-cookie-law-solution/ already added their cookie solution for ampforwp plugin too.
Settings screenshot: https://ibb.co/ccV17QG

And if you are getting any trouble while integrating it you can through this guide https://www.iubenda.com/en/help/3182-cookie-consent-amp-pages
