### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function fifu_amp_url()

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4688]
Ref: https://secure.helpscout.net/conversation/1247132873/146982/

Fatal error: Uncaught Error: Call to undefined function fifu_amp_url() in /home/u510011965/domains/allnews.co.in/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php:332 Stack trace: #0 /home/u510011965/domains/allnews.co.in/public_html/wp-content/plugins/accelerated-mobile-pages/components/loop/loop.php(497): ampforwp_aq_resize('https://allnews...', 723, 394, true, false, true) #1 /home/u510011965/domains/allnews.co.in/public_html/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/swift/index.php(29): amp_loop_image(Array) #2 /home/u510011965/domains/allnews.co.in/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(489): include('/home/u51001196...') #3 /home/u510011965/domains/allnews.co.in/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-post-template.php(164): AMPforWP\AMPVendor\AMP_Post_Template->verify_and_include('/home/u51001196...', 'single') #4 /home/u5100 in /home/u510011965/domains/allnews.co.in/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/aq_resizer.php on line 332

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.62.1 update
