### ISSUE TITLE
Detect and remove custom js from last content filter

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4689]
e.g. CW

**Comment by MohammedKaludi** [comment]
not working with different scenarios 
`		<script type="text/javascript">
					jQuery(document).ready(
					function($) {
					jQuery('form').submit(
					function() {
					var splitName = jQuery('#inf_field_FirstName').val();
					var names = splitName.split(' ');
					var firstName = names[0];
					names.splice(0,1); // removes the first name from the array
					var lastName = names.join(' '); // put any remaining values from array into lastName, separate with a space
					jQuery('#inf_field_FirstName').val(firstName);
					jQuery('#LastName').val(lastName);
					return true; }); });
				</script>`

and  `<script type="text/javascript" src="https://di209.infusionsoft.com/app/webTracking/getTrackingCode"></script>`

but this seeems to be working 

`<script(.*?)type="text\/javascript"(.*?)>[\s\S]*?<\/script>`

**Comment by MohammedKaludi** [comment]
Ready to go.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.62.1 update
