### ISSUE TITLE
Instant articles not working when Site directory / Installation directory is different

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4690]
- [x] the URL is wrong because of the installed directory: https://take.ms/SZlxG

- [x] but when manually going to the URL, it doesn't show the full feed: https://take.ms/zcUkK

https://secure.helpscout.net/conversation/1225328698/141954?folderId=3528427

**Comment by MohammedKaludi** [comment]
Use `esc_raw_url` while merging:

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/02cc076f257de8a1f78d36e2f2163aab1f563248#diff-260eba6333c3222e59a6aed22ac5ab37R2545
