### ISSUE TITLE
Scroll to top button not visible in Design 2

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4693]
When user  scrolls down to the bottom of the page scroll-to-top button is missing. Issue is also occurring in localhost.

Screen capture: https://monosnap.com/direct/DmZBYWkGsyMNhiuI5A3sswdAbxwBCn
Screen capture(localhost): https://monosnap.com/direct/cOTBihlBWlifvlfv7CVq5ubaCdP144

ref: https://secure.helpscout.net/conversation/1248224887/147215/

**Comment by MohammedKaludi** [comment]
need to make sure it works properly with AMP theme framework themes.

**Comment by Zabi09** [comment]
Working fine with AMP theme framework

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
