### ISSUE TITLE
Inccorect path passed to load_plugin_textdomain function

### ISSUE THREAD

**Issue by uNknownMark** [ahmedkaludi/accelerated-mobile-pages#4694]
Hey there. Right now load_plugin_textdomain call looks like
`load_plugin_textdomain( 'accelerated-mobile-pages', false, trailingslashit(AMPFORWP_PLUGIN_DIR) . 'languages' );`
but third arg for load_plugin_textdomain is $plugin_rel_path (not absolute as it is right now).
On some systems with open_basedir this can cause redundant warnings in error logs.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
