### ISSUE TITLE
Need to make "SEO" option disappear in wordpress tool bar when No SEO plugin is being used.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4698]
It should hide the SEO option if no SEO plugins installed.
Currently, the toolbar displays SEO regardless, and it could be confusing for users.
recreated in the localhost. 
https://secure.helpscout.net/conversation/1246170298/146788?folderId=3514643
Screengrab for reference: https://monosnap.com/file/rrsMzHmG1lwOSBWu6d2OxXcQaDxbnI

**Comment by MohammedKaludi** [comment]
ready ot merge,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
