### ISSUE TITLE
Anchor tag getting stripped when Site Kit by Google is active.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4699]
This issue said to be resolved in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4552, but the issue is not fixed on the below user's site.
https://secure.helpscout.net/conversation/1186609501/134381?folderId=2770545

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64 update
