### ISSUE TITLE
Navigation Menu doesn't appear

### ISSUE THREAD

**Issue by Taig7** [ahmedkaludi/Accelerated-Mobile-Pages#47]
Hi!
I followed yours instructions by assign AMP menu in the WordPress Menus but the menu doesn't appear on my amp version of my article.
Can you help me ?
Cordialy,
Vincent

**Comment by ahmedkaludi** [comment]
I believe you have already created a topic in the WordPress.org forum, right? I may be already answered that.

Regards,
Ahmed

**Comment by Taig7** [comment]
Yes. It is the reason for i send you 2 e-mails before with screenshots because i don't know how to do appear the navigation menu.

Did you see the problem with screenshots?

Cordialy,

Vincent

www.vincent-body-expert.com<http://www.vincent-body-expert.com>

________________________________
De : Ahmed Kaludi <notifications@github.com>
Envoyé : jeudi 18 août 2016 19:27
À : ahmedkaludi/Accelerated-Mobile-Pages
Cc : Taig7; Author
Objet : Re: [ahmedkaludi/Accelerated-Mobile-Pages] Navigation Menu doesn't appear (#47)


I believe you have already created a topic in the WordPress.org forum, right? I may be already answered that.

Regards,
Ahmed

-

**Comment by ahmedkaludi** [comment]
You seem to be having an AMP plugin by Automattic activated as well?

**Comment by Taig7** [comment]
Yes. It is activated.


________________________________
De : Ahmed Kaludi <notifications@github.com>
Envoyé : jeudi 18 août 2016 19:42
À : ahmedkaludi/Accelerated-Mobile-Pages
Cc : Taig7; Author
Objet : Re: [ahmedkaludi/Accelerated-Mobile-Pages] Navigation Menu doesn't appear (#47)


You seem to be having an AMP plugin by Automattic activated as well?

-

**Comment by ahmedkaludi** [comment]
I would recommend you to deactivate the plugin.

**Comment by Taig7** [comment]
Ok. I will do the test now.


________________________________
De : Ahmed Kaludi <notifications@github.com>
Envoyé : jeudi 18 août 2016 19:47
À : ahmedkaludi/Accelerated-Mobile-Pages
Cc : Taig7; Author
Objet : Re: [ahmedkaludi/Accelerated-Mobile-Pages] Navigation Menu doesn't appear (#47)


I would recommend you to deactivate the plugin.

-

**Comment by Taig7** [comment]
I had disactivated the AMP by Automattic but now i didn't have AMP format on my mobile phone.


________________________________
De : v.70 Pro <v.70@hotmail.fr>
Envoyé : jeudi 18 août 2016 19:48
À : ahmedkaludi/Accelerated-Mobile-Pages
Objet : RE: [ahmedkaludi/Accelerated-Mobile-Pages] Navigation Menu doesn't appear (#47)


Ok. I will do the test now.


________________________________
De : Ahmed Kaludi <notifications@github.com>
Envoyé : jeudi 18 août 2016 19:47
À : ahmedkaludi/Accelerated-Mobile-Pages
Cc : Taig7; Author
Objet : Re: [ahmedkaludi/Accelerated-Mobile-Pages] Navigation Menu doesn't appear (#47)


I would recommend you to deactivate the plugin.

-

**Comment by ahmedkaludi** [comment]
Hey,

Please use http://website.com/?amp to see the AMP version of your website.

**Comment by ahmedkaludi** [comment]
This was fixed after 0.8 update.

**Comment by Taig7** [comment]
Hi !


I have other questions.


1) Is it normal that amp pages from your plugin appear only if the AMP from automattic is installed?


2) Icon Menu appears but when i click on it, it disappears in 1 sec. Impossible to access to complete menu.


3) There are also all my links in the text of my page who disappeared. Is it normal for amp version?


Cordialy,


Vincent

www.vincent-body-expert.com<http://www.vincent-body-expert.com>

________________________________
De : Ahmed Kaludi <notifications@github.com>
Envoyé : jeudi 22 septembre 2016 01:19
À : ahmedkaludi/Accelerated-Mobile-Pages
Cc : Taig7; Author
Objet : Re: [ahmedkaludi/Accelerated-Mobile-Pages] Navigation Menu doesn't appear (#47)


This was fixed after 0.8 update.

-
