### ISSUE TITLE
Google tag manager

### ISSUE THREAD

**Issue by Lofesa** [ahmedkaludi/accelerated-mobile-pages#470]
Updated to 0.9.38 and I get 
```
Request URL:https://www.googletagmanager.com/amp.json?id=&gtm.url=https%3A%2F%2Fintersindical.intersindicalrm.org%2Famp%2F&__amp_source_origin=https%3A%2F%2Fintersindical.intersindicalrm.org
Request Method:GET
Status Code:400 
Remote Address:216.58.211.232:443
```

I leave blank the GTM config as don´t use GTM at all

Ok I see... GTM is enabled by default and I need to disable it. I think it must be disabled on default

**Comment by ahmedkaludi** [comment]
@MohammedKaludi  @khaledMohammed000 Please don't tell me that GTM is enabled by default?

**Comment by ahmedkaludi** [comment]
@Lofesa We have confirmed that GTM is disabled by default. Have you turned it on?

**Comment by khaledMohammed000** [comment]
any update on this @Lofesa  ?

**Comment by Lofesa** [comment]
Sorry for the delay
I don´t have toyrned it on, only updated. And yes, I heve tourned it off when I discover whats happend as I have reported in a P.S to the 1s post

**Comment by khaledMohammed000** [comment]
@Lofesa yes by default its turned off
