### ISSUE TITLE
In admin tool bar, (+) icon loading small and also author image invisible.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4700]
Case 1:https://secure.helpscout.net/conversation/1252530163/148166?folderId=2770543

See these screenshots:

Also, reoccur in local
https://monosnap.com/file/Z898on5RqtKQNWTOtKTOj02wvAnUQt

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64 update
