### ISSUE TITLE
AMPforWP Canonical BUG!!

### ISSUE THREAD

**Issue by adstikoz** [ahmedkaludi/accelerated-mobile-pages#4701]
**BUG: When using AMPforWP + Yoast SEO 14 the tag 'link rel=canonical' appears more than once in the document.**

**Comment by MohammedKaludi** [comment]
can you share the url of the site?

and can you also share the export of the options panel?

**Comment by adstikoz** [comment]
> can you share the url of the site?
> 
> and can you also share the export of the options panel?

https://instaconcours.com/
![Capture](https://user-images.githubusercontent.com/69708333/90317664-f0cbed80-df22-11ea-8b69-50e231987d78.PNG)
![Capture1](https://user-images.githubusercontent.com/69708333/90317675-f75a6500-df22-11ea-9dec-179950671222.PNG)

**Comment by ahmedkaludi** [comment]
Github is for tested and re-creatable bugs, for support please reach out via website.
