### ISSUE TITLE
AmpForWpError

### ISSUE THREAD

**Issue by jeelpatel567** [ahmedkaludi/accelerated-mobile-pages#4702]
Does not Open website On Amp Version.
How to fix this.
[Wordpress error on Amp](https://weetech.in/2020/08/13/what-is-supercomputer-and-how-does-it-work/amp/)

**Comment by MohammedKaludi** [comment]
@jeelpatel567 Can you please activate debug mode, by adding 

`define( 'WP_DEBUG', true );`
`define( 'WP_DEBUG_LOG', true );`
`define( 'WP_DEBUG_DISPLAY', true );`

in WP-config.php and then we will able to see what is the error and will be able to fix it.

Can you please add this and let me know what error do you see in debug log?

**Comment by jeelpatel567** [comment]
Not show debug file Sent from Mail for Windows 10 From: Mohammed KaludiSent: 15 August 2020 13:48To: ahmedkaludi/accelerated-mobile-pagesCc: jeelpatel567; MentionSubject: Re: [ahmedkaludi/accelerated-mobile-pages] AmpForWpError (#4702) @jeelpatel567 Can you please activate debug mode, by addingdefine( 'WP_DEBUG', true );define( 'WP_DEBUG_LOG', true );define( 'WP_DEBUG_DISPLAY', true );in WP-config.php and then we will able to see what is the error and will be able to fix it.Can you please add this and let me know what error do you see in debug log?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MohammedKaludi** [comment]
@jeelpatel567 this is just css. 

Can you provide more information on this. This is very insufficient information.

**Comment by jeelpatel567** [comment]
I could not open post in amp version on wordpress.Pages are open. Only error in post does not show. When I click any post and show the this screenshot.You understand ?  Sent from Mail for Windows 10 From: Mohammed KaludiSent: 15 August 2020 15:14To: ahmedkaludi/accelerated-mobile-pagesCc: jeelpatel567; MentionSubject: Re: [ahmedkaludi/accelerated-mobile-pages] AmpForWpError (#4702) @jeelpatel567 this is just css.Can you provide more information on this. This is very insufficient information.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MohammedKaludi** [comment]
can you share the debug log file?

**Comment by jeelpatel567** [comment]
I don’t show any debug_log file.  Sent from Mail for Windows 10 From: Mohammed KaludiSent: 15 August 2020 17:41To: ahmedkaludi/accelerated-mobile-pagesCc: jeelpatel567; MentionSubject: Re: [ahmedkaludi/accelerated-mobile-pages] AmpForWpError (#4702) can you share the debug log file?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ahmedkaludi** [comment]
Github is for tested and re-creatable bugs, for support please reach out via website

**Comment by jeelpatel567** [comment]
Thank you  Sent from Mail for Windows 10 From: Ahmed KaludiSent: 16 August 2020 23:06To: ahmedkaludi/accelerated-mobile-pagesCc: jeelpatel567; MentionSubject: Re: [ahmedkaludi/accelerated-mobile-pages] AmpForWpError (#4702) Closed #4702.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MohammedKaludi** [comment]
@jeelpatel567 

You are sending repeated information that is not helping us to debug the issue please send us the appropriate information regarding the issue so we can help you resolve it this information is insufficient
