### ISSUE TITLE
jQuery.fn.live() is deprecated .../accelerated-mobile-pages/includes/modules/js/amp.js

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#4706]
When we enable Enable jQuery Migrate Helper plugin then this warning is appearing

**Comment by WasimM3** [comment]
The live() method was deprecated in jQuery version 1.7, and removed in version 1.9. Use of on() method is correct fix. So moving forward.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.62.1 update
