### ISSUE TITLE
Breadcrumb links are not generating the "amp/"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4708]
Ref: https://secure.helpscout.net/conversation/1253294985/148307?folderId=2770545

Screenshot: https://prnt.sc/tzhsxk

When the user visiting the breadcrumb links then it is not ending with "amp/". It is ending with the "/amp".

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
