### ISSUE TITLE
Featured images are not showing when "Enable lazy load images" option is enabled in the "DEUS" Theme

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4710]
Ref: https://secure.helpscout.net/conversation/1257318570/149080?folderId=2770545

If the "Enable lazy load images" option is enabled in the "DEUS" Theme then the image URL is changing no image.jpg. 

Screenshot: 
1. https://prnt.sc/u1lwr9
2. https://prnt.sc/u1lwj3

Steps to recreate the issue: 
1. Install the DUES Theme.
2. Install the DUES Core plugin.
3. Goto Theme option > General > Enable lazy load images

The theme and plugin is available in the Magazine3 Telagram group.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.68 update
