### ISSUE TITLE
Featured Image doesn’t appear on single post

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4711]
The featured image doesn’t appear on a single post design even if the “Featured Image” option has been activated.
options panel export: https://gist.github.com/tdenea/4a3c34ad9df3ae9a02e61d817dee3dbb

Reference: https://wordpress.org/support/topic/featured-image-doesnt-appear-on-single-post-2/
Screenshots:  https://prnt.sc/u21qu2
https://prnt.sc/u21qb0

**Comment by syedimran22** [comment]
Commit of this ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/0291c98d7d1f7161612b04066de886eaa38196d9

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.63
