### ISSUE TITLE
Feature Request: Support Elementor Elements That Use JS

### ISSUE THREAD

**Issue by nisiwi** [ahmedkaludi/accelerated-mobile-pages#4712]
I have a number of Elementor Pro elements (e.g. Animated Headline) and some plugins (Essential Addons & Ultimate Addons) that use JS to create animated effects or delivery image comparisons with a sliding reveal.  Usually these end up rendering on the AMP pages with parts missing or in the case of image comparison the images are just dumped out with no explanations such as "Before" and "After".

Ideally AMPforWP should resolve this for us and/or we need a way of dynamically excluding or replacing these elements on AMP pages with an alternative element / design.

**Comment by ahmedkaludi** [comment]
@nisiwi  Sure, I request you to share your website and few of those elements to our support team via website, they will have a look and raise a request in the extension milestone board which is used internally to improve compatibilities.
