### ISSUE TITLE
Need to improve the mobile redirection feature code

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4713]
Ref: https://secure.helpscout.net/conversation/1258369054/149301?folderId=2770545

If the user is enabling the mobile redirection feature along with the SG optimizer plugin then in the response headers it is showing no-cache. 

Screenshot: https://prnt.sc/u269oa

**Comment by Zabi09** [comment]
Closing the ticket due to lack of information will reopen if we have any or if we are able to recreate the issue at the localhost.
