### ISSUE TITLE
Related posts are not showing below the posts. (Any number of posts.)

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4714]
https://secure.helpscout.net/conversation/1250220682/147665?folderId=3243584

[redux_options_redux_builder_amp_backup_19-08-2020.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/5095996/redux_options_redux_builder_amp_backup_19-08-2020.zip)
The above zip is the amp settings of my localhost where the related posts are not displayed.
Local screenshot https://prnt.sc/u268nl

**Comment by syedimran22** [comment]
This issue will be fixed in this ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4300
until then you can use this custom plugin 
[ampforwp-related-post-query.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/5103239/ampforwp-related-post-query.zip)
