### ISSUE TITLE
Need to add <meta name="referrer" content="no-referrer-when-downgrade"> or <meta name="referrer" content="always">

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4715]
User has noticed that on the Safari browser, one of thier ad partners script isn't loading creative. This apparently was because there is an AMP package bug. The proper referrer is not passed through Safari as it is for Chrome.

There is more information here -
https://github.com/ampproject/amphtml/issues/17842

Ticket for reference: https://secure.helpscout.net/conversation/1258139489/149264?folderId=3514643

**Comment by MohammedKaludi** [comment]
use default global variables
https://codex.wordpress.org/Global_Variables#Browser_Detection_Booleans

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64 update
