### ISSUE TITLE
Backend button translation

### ISSUE THREAD

**Issue by dmata47** [ahmedkaludi/accelerated-mobile-pages#4717]
My wordpress is fully translated into Spanish: es_ES.
Since I update to wordpress 5.5 the plugin affects the translation of some buttons in the backend: replying to comments, save draft, among others. It prevents its translation into Spanish.

Screenshot: 
https://i2.wp.com/imgfz.com/i/xtNkGIL.png
http://imgfz.com/i/CBUO1uF.png
Reference: https://wordpress.org/support/topic/untranslated-comment-buttons/

**Comment by Zabi09** [comment]
@dmata47 If you deactivate our AMPforWP plugin then the translation is working correctly? Please let me know

**Comment by dmata47** [comment]
> @dmata47 If you deactivate our AMPforWP plugin then the translation is working correctly? Please let me know

**Comment by dmata47** [comment]
> > @dmata47 If you deactivate our AMPforWP plugin then the translation is working correctly? Please let me know

Yes, if I deactivate it, the translation works.
In fact, disable all other plugins except AMP for WP and the bug was shown.

(Excuse me for closing the ticket, I'm a github newbie)

**Comment by Zabi09** [comment]
I have selected the language as Spanish and I am using the latest version of both WordPress 5.5 and our plugin but still, I am not able to recreate the issue of translation, below are the screenshots of what I have done so far will you please look into it and let me know if I am missing anything 
https://prnt.sc/u65qcy
https://prnt.sc/u65qs7
https://prnt.sc/u65q6w

Please check once and let me know

**Comment by dmata47** [comment]
> I have selected the language as Spanish and I am using the latest version of both WordPress 5.5 and our plugin but still, I am not able to recreate the issue of translation, below are the screenshots of what I have done so far will you please look into it and let me know if I am missing anything
> https://prnt.sc/u65qcy
> https://prnt.sc/u65qs7
> https://prnt.sc/u65q6w
> 
> Please check once and let me know

I can give you an administrator access to my test site where you can see the bug.

Tell me where I send it.

**Comment by Zabi09** [comment]
@dmata47 my email is team@magazine3.com please send here and I cannot share email here because this is a public thread.

**Comment by dmata47** [comment]
> I have selected the language as Spanish and I am using the latest version of both WordPress 5.5 and our plugin but still, I am not able to recreate the issue of translation, below are the screenshots of what I have done so far will you please look into it and let me know if I am missing anything
> https://prnt.sc/u65qcy
> https://prnt.sc/u65qs7
> https://prnt.sc/u65q6w
> 
> Please check once and let me know


I sent you the access information to the email you sent me

**Comment by MohammedKaludi** [comment]
@Zabi09 can you look into it once again.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.16
