### ISSUE TITLE
TCF integration in AMP.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4718]
One of our user requesting TCF integration in AMP.

They are two cases here to integrate:

Case 1 - Integration with GDPR consent.
Consent data of the site will store in the cookie, so we need to write the code to fetch the details of consent stored in the cookies according to the user and send that specific data to the specific advertisement company.

Case 2 - Integration with Google Tag Manager.
In this, we need to send data that weather TCF is enabled or not at the user end.

Documentation: https://support.google.com/admanager/answer/9805023?hl=en&ref_topic=9760861
Ref Ticket: https://secure.helpscout.net/conversation/1259413832/149496?folderId=3126461

**Comment by Zabi09** [comment]
AMP supports popular transparency consent frameworks including the IAB TCF v1, TCF v2, and the IAB US Privacy String. Please check with your consent management platform (CMP) and ad networks on their AMP support. AMP will read and pass the strings passed by the frameworks (IAB TCF v1, TCF v2, and the IAB US Privacy String) when received by CMPs/ad networks.

If you face any issue/problem in TCF integration with our AMPforWP plugin then please let us know and we are happy to help you.
