### ISSUE TITLE
In the design2 while clicking on the menu getting # at the end of the URL 

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4722]
REF:https://secure.helpscout.net/conversation/1256125255/148854?folderId=3528427

DES: Getting the # at the end of the URL link while clicking on the menu in the design2

Ref screenshots: https://prnt.sc/u6599m  https://prnt.sc/u659mk

**Comment by MohammedKaludi** [comment]
Was `#` added because of lighthouse test?

**Comment by Zabi09** [comment]
I have checked with and without # but the result was the same in the lighthouse and also I have searched for lighthouse tickets of the past but didn't found commit related to that so I removed it

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
