### ISSUE TITLE
AMP 404 template is applying on non amp page

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4723]
link: http://garfagnanadream.it/404test
Reference: https://wordpress.org/support/topic/disable-the-plugins-404-page/

**Comment by Leonardo-Fiori** [comment]
@HaripriyaHari This happens also for the default search page, it gets overridden by AMP for WP.

https://www.garfagnanadream.it/

Just use the magnifying glass and see. I would like to use my theme's search bar, not AMP for WP.

https://www.garfagnanadream.it/?s=asdads+adsasd

**Comment by MohammedKaludi** [comment]
ready to mereg.

**Comment by Zabi09** [comment]
@Leonardo-Fiori We have fixed the issue in our beta version and that will be pushed tomorrow and once you update the plugin just disable the option of "Search Result Page in AMP" - https://prnt.sc/upsb5p and the search results will appear from your theme -

**Comment by Leonardo-Fiori** [comment]
Perfect, thank you!

**Comment by Leonardo-Fiori** [comment]
@Zabi09 is the update ready? Can i update the plugin?

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64 update
