### ISSUE TITLE
GDPR banner is off-centered, the 'X 'is out of the screen

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4724]
GDPR banner is off-centered, the 'X 'is out of the screen. This issue is occurring but Andriod and IOS

Ref screenshot : andriod(https://prnt.sc/u6ozrj)
Ref screenshot: IOS(https://prnt.sc/u6pcp0)

Ref:https://secure.helpscout.net/conversation/1259361494/149481?folderId=3575684

**Comment by sonaliramteke** [comment]
I have tested this issue but it is not working

**Comment by Zabi09** [comment]
@sonaliramteke can you please tell me how are you testing it? as I have checked on my localhost as well as garage, it is working fine.
Master with a bug - https://monosnap.com/file/lmR768N6TgEJIr04EvvUojxWb7ilwl
Beta without bug - https://monosnap.com/file/gLNQIxOniGmVWpZUW2vd5dvACcQZvA

**Comment by ahmedkaludi** [comment]
We have to fix the AMP CDN scenario 
![image](https://user-images.githubusercontent.com/16532359/92123980-d5b21680-ee1a-11ea-80d5-c3528cf4861c.png)

Issue raised by Leonardo Fiori on Skype

**Comment by Leonardo-Fiori** [comment]
Happening also when not server through google's servers, just it's less noticeable. But the X is still off, and the text too. Using a Xiaomi Mi9 Lite

![image](https://user-images.githubusercontent.com/25549272/92124222-ca9cbd80-edfd-11ea-9a58-20c3cfd9a8e3.png)

**Comment by AnupriyaSurapaneni** [comment]
Same GDPR banner offset issue, 
Reference screenshot : https://prnt.sc/umxoxz
Reference helpscout ticket : https://secure.helpscout.net/conversation/1289317511/155646?folderId=4074390

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Leonardo-Fiori** [comment]
@MohammedKaludi is the update ready? Can i update the plugin?

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
