### ISSUE TITLE
Need to add the support for webp images on the homepage and Archives [Category & Tags] page as well

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4725]
Need to add the support for webp images on the homepage, Archives [Category & Tags] pages as well

Use case: user is adding the webp images by using the plugin imagify.

And on the home page, the posts featured images are not the webp. when the homepage is tested in the google page speed it recommends using the webp images.

Ref: https://sai.coach/blog/amp/

https://secure.helpscout.net/conversation/1264684056/150554?folderId=2632030

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.72 update
