### ISSUE TITLE
Merriweather font option in Design 1 does not work.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4726]
https://secure.helpscout.net/conversation/1250220682/147665?folderId=3243584

https://prnt.sc/u7i27s

[redux_options_redux_builder_amp_backup_28-08-2020.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/5142245/redux_options_redux_builder_amp_backup_28-08-2020.zip)

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
