### ISSUE TITLE
Notice: Undefined index: Cpage

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4728]
Notice: Undefined index: Cpage in /web/htdocs/www.garfagnanadream.it/home/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 299

and also when activating AMP some page has missed the content example URL(https://www.garfagnanadream.it/alloggi-hotels/rittenhouse-square/) this page is created with Geodirectory

Before activating AMP: https://prnt.sc/u9hmhr
After activating AMP: https://prnt.sc/u9ho0f

Ref:https://secure.helpscout.net/conversation/1259361494/149481?folderId=3575684

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
