### ISSUE TITLE
AMP html URL is not forming correct the URL when the AMP take over (beta) option and ?amp option is enabled.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4731]
AMP html URL is not forming correct the URL when the AMP take over (beta) option and ?amp option is enabled.

Ref:https://secure.helpscout.net/conversation/1249853194/147564?folderId=3575684

**Comment by hieptd** [comment]
It seems that when I checked, it still had some problems. When I check it out at: https://search.google.com/test/amp
Links of the format: /? Amp / will fail.
For example:
Error: https://www.ahisu.com/ca-otto/?amp/
No error: https://www.ahisu.com/ca-otto/

**Comment by hieptd** [comment]
After I fix it like you, the website has another error: https://drive.google.com/file/d/18H2KB9GmPxMsHwr-yg3s_wOdksSrdJAs/view?usp=sharing

**Comment by hieptd** [comment]
While editing the code according to your template, I discovered a new bug. The categories / tags received incorrectly rel="amphtml" tag. When viewsource we will see rel="amphtml" error received the wrong link. @Zabi09 @laharikakuna @khaledMohammed000

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
