### ISSUE TITLE
Compatiblity issue with the UberMenu 3 - The Ultimate WordPress Mega Menu Plugin

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4732]
Use case: when menu list items which are added by using this plugin and have an integration of amp menu with this plugin.

To integrate the amp menu we need to check this option in the ubermenu settings:

https://monosnap.com/file/56a9cVJ9yrum6ZyrDSrrVHyRo4IHs5

Then that menu has functionality issues in amp:

1. Submenu items display directly, without selecting its functionality. Some unwanted content such as the name of the menu is displayed in the top menu item.

Please see this video which is checked in the internal system:

https://monosnap.com/file/Abw82jwPTXnC6zW043SBwtvj9jauPg

Ref: Plugin UberMenu 3 - The Ultimate WordPress Mega Menu

User website: https://stage.trinitydentalcenters.com/amp/ 

Plugin link: https://codecanyon.net/item/ubermenu-wordpress-mega-menu-plugin/154703?irgwc=1&clickid=RNhyD0XYUxyORfPwUx0Mo3QWUkiVnz3-F2ZX0M0&iradid=275988&irpid=1230622&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius_1230622&utm_medium=affiliate&utm_source=impact_radius

https://secure.helpscout.net/conversation/1267198892/151107?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.67
