### ISSUE TITLE
GDPR Banner is not working on iOS ipad.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4733]
GDPR Banner pop is not displaying on the IOS iPad device and also youtube video and comment section is not loading until the GDPR banner is accepted.

Ref: https://secure.helpscout.net/conversation/1259361494/149481?folderId=1060556

For solution: Please do any desk with Ahmed sir.

**Comment by Zabi09** [comment]
Tested on ios and other devices and it is working fine on garage and cloudways so closing this ticket for now but if anyone has the issue then please let us know and we will reopen this ticket again
