### ISSUE TITLE
Auto add amp in menu url functionality is not working the tag added as menulist item.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4734]
In this link: https://www.pest-control-products.net/2689/reviews/top-3-rat-mouse-glue-traps/amp/

How to get rid of is the tag which is added as a list item in the menu.

checked in the local as well by adding the tag in the menu list item and for this Auto Add AMP in Menu URL is not working for it.

Ref: https://secure.helpscout.net/conversation/1263710719/150357?folderId=2632030

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
