### ISSUE TITLE
Error: An AMP component 'script' tag is present, but unused.

### ISSUE THREAD

**Issue by MarkSchusste** [ahmedkaludi/accelerated-mobile-pages#4735]
The following AMP errors have been detected:

- An AMP component 'script' tag is present, but unused.
- The tag 'style amp-custom' appears more than once in the document.

I did not change anything, these errors showed up all of a sudden.
I suspect they're caused by a glitch in the plugin.

Can you please dig a bit deeper into this?

Thank you.
Mark

**Comment by MohammedKaludi** [comment]
@MarkSchusste can you share the url of the site so we can check it?

**Comment by ahmedkaludi** [comment]
Github is for recreatable issues, for technical support, please contact on site
