### ISSUE TITLE
In Design three, when click on the menu, the  page gets pushed to the right side 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4736]
Screenshot: https://imgur.com/bRYa2Hx
Website: https://www.garfagnanadream.it/il-bosco-del-fatonero-lorigine-di-tutte-le-leggende-garfagnine/
Reference: https://wordpress.org/support/topic/disable-menu-push-page-to-the-right-animation/

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by Leonardo-Fiori** [comment]
@MohammedKaludi is the update ready? Can i update the plugin?

**Comment by MohammedKaludi** [comment]
@Leonardo-Fiori we are pushing the update as we speak, it should be live in sometime.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
