### ISSUE TITLE
Shortpixel is not generating WebP in AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4738]
- [ ] Siasat (Asghar)

- [ ] a user called Od  https://tudenuncia.mx/nina-queda-atrapada-en-un-papalote-y-vuela-por-los-aires/amp/ in Telegram community

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
