### ISSUE TITLE
AMP Takeover (Beta) causes the "Referenced AMP URL is self-canonical AMP" on Google Search Console.

### ISSUE THREAD

**Issue by ahisu** [ahmedkaludi/accelerated-mobile-pages#4739]
Hello,
Recently Search Console has reported errors so many times, I tried to find a fix but with no success.
Here is the video about the error: https://youtu.be/4pxcBXQiIDM
I am using AMP Takeover (Beta) mode, I think the interface of AMP for WP - Accelerated Mobile Pages is more than enough for me.
It's beautiful, minimal, and has all I need. However, some unexpected errors have occurred, please check on this issue.
Link my article: https://www.ahisu.com/tran-chau-ngoc-trai/

**Comment by Zabi09** [comment]
We have fixed the issue in this ticket - #4731 So closing this one
