### ISSUE TITLE
In addon mode we are forcefully redirecting to reader mode for other amp modes too.

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4742]
In addon mode we are forcefully redirecting to reader mode for other amp modes too.
The AMP pages redirect to standard pages with AMP (Official plugin).
Reference: https://wordpress.org/support/topic/issue-your-plugin-not-compatible-with-amp-official-plugin-2-0-0/

**Comment by devhelper** [comment]
yes, I have this issue on my site!

**Comment by devhelper** [comment]
Can you fix it with new update?

**Comment by Zabi09** [comment]
@devhelper I have fixed the issue and now our testing team will have a look at my fixed and once it is done we will push it in the next update for sure

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
