### ISSUE TITLE
In-Content Related Post appearing inside the blockquote when "After 50% of content" option is selected

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#4743]
https://monosnap.com/file/EcyBKExguzWgLnV0rXvu6WlIotIPHU
https://monosnap.com/file/i9dDrNFBpHGBjkUI3oR2ymuX0cjF7d

**Comment by MohammedKaludi** [comment]
is blockquote check is required in `strpos($value,`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/00bbae06b5395d59ca41114611fca7f6cb75dc9c#diff-6aa5512f7dd8d5ce60fc97b0f340912cR5082

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64 update
