### ISSUE TITLE
optimize queries loading in the Non-AMP 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4744]
SINGLE
1. Our Testing: https://take.ms/TNhNg
2. User Scenario: https://take.ms/ycQPN

HOME
1. Our Testing: https://take.ms/djzTf
2. User Scenario: https://take.ms/dvCUp

Reported by me with Ajay Arvind on Telegram

**Comment by ajaymaravind** [comment]
When could we see this fix be done in live?
We are eagerly waiting for a solution taking the toll of slow loading.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.66

**Comment by MohammedKaludi** [comment]
Pushed 1.0.66.3
