### ISSUE TITLE
Comments module from amp page builder is rendering only admin comments in amp,not the other user comments

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4745]
Ref: https://secure.helpscout.net/conversation/1274697863/152894?folderId=2632030

https://web-4u.cz/types-of-maintenance/amp/
Non-AMP
https://web-4u.cz/types-of-maintenance/

When comment module is added in the amp page builder it is rendering only the admin comment, not the other comments which are commented by users.

The issue checked in internal systems well.https://monosnap.com/file/OJP1QRQOOvaJMICmRisiTC56zWE6Om

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
