### ISSUE TITLE
The internal link for the the author page is generating in the AMP if the archive  page support is disable

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4746]
Ref: https://secure.helpscout.net/conversation/1277035769/153350?folderId=2770545

If the archive page support is disabled in the AMP even after this the author page is internal link is generating in the AMP.

Screenshot: https://prnt.sc/uetcz2

It should generate the non-AMP internal link.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
