### ISSUE TITLE
FAQ icon button is a too big in amp page.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4747]
If the FAQ schema block is added by the "Ultimate Addons for Gutenberg" plugin the FQA icon button is a too big AMP page

Ref screenshot: https://prnt.sc/ufdvxh 
Ref URL: https://goodmood.com.tw/cbd/?amp=1/

Ref screenshot of the local: https://prnt.sc/ufdwk2

Ref: https://secure.helpscout.net/conversation/1278165113/153525?folderId=3575684

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://wordpress.org/support/topic/gutenberg-faq-plugin-issue/

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
