### ISSUE TITLE
If the sticky ads is active then the sticky social share link tab is hiding behind the ads

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4749]
Ref: https://secure.helpscout.net/conversation/1278789412/153667?folderId=2770545

Screenshot: https://prnt.sc/ug36y7

After adding the below CSS code it got fixed: 
.s_stk {
    z-index: 99999999;
}

**Comment by MohammedKaludi** [comment]
`z-index: 99999999;` Itne 99999 is this the correct fix?

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
