### ISSUE TITLE
If adding the twitter embed through the Gutenberg editor then need to remove margin from top

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4750]
Ref: https://secure.helpscout.net/conversation/1168274274/130489?folderId=2770545

If the user is adding the twitter embed through the Gutenberg editor then the margin-top is adding causing unnecessary spacing. The margin-top of the 45px for desktop and 95px for mobile is adding.

Screenshot:
https://prnt.sc/uhh8di
https://prnt.sc/uhhfxi

We need to remove it.

**Comment by MohammedKaludi** [comment]
this will remove the margin for all the blocks, not only for twitter:

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a4b2032bf7dfdc438af53853379624bde470f03e#diff-2ae5550e31f40c1962ca69d373af6b93L777

**Comment by MohammedKaludi** [comment]
Need proper testing after the merge is done so that there are no issues with styling for other Embeds

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
