### ISSUE TITLE
Caching enables browser caching for non amp version as well

### ISSUE THREAD

**Issue by ajaymaravind** [ahmedkaludi/accelerated-mobile-pages#4751]
Caching enables browser caching for non amp version as well. This creates stale content for non-amp version and also messes with other caching plugins as they handle non-amp caching

**Comment by Zabi09** [comment]
Hi @ajaymaravind 

Can you please elaborate more on your issue by proving us with some screenshots and the exact way to recreate the issue on our end, So that we can fix it as soon as possible.
