### ISSUE TITLE
Need to make compatibility with the IO Technologies company's provider analytics tarcking code. 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4753]
Ref: https://secure.helpscout.net/conversation/1284672582/154905?folderId=2632030

https://docs.iotechnologies.com/?hash=uwwZYzHZUivNFS6w0xjOsNY5mMrUNarS#3-add-tracking-code

**Comment by tripledm** [comment]
hello do you have an ETA on this please

**Comment by MohammedKaludi** [comment]
Change `esc_html` to `esc_attr` on all places 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/ca3daa1af8416da9d328ffef05336e734c05184b#diff-20374415782ee754e97c2f1d6ac46764e76479a3600765cc369852843a95a662R357

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
