### ISSUE TITLE
If the user is adding the HTML code in the background video module then code is showing as output

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4755]
Ref: https://secure.helpscout.net/conversation/1290923001/155859?folderId=2770545

When the user is adding the HTML code in the text section of the background video module, then the HTML code is showing instead of the output of the HTML code.

URL: https://dentalworkmexico.com/demo/

Screenshot:
https://prnt.sc/umypoc

The issue is also recreated on the local:

Screenshot: https://prnt.sc/umykf8

Steps to recreate the issue:
1. Enable the AMP Page Builder.
2. Add the youtube background video
3. Goto Text section and add some HTML code (https://prnt.sc/umyrr4)

**Comment by MohammedKaludi** [comment]
Removing escaping is not a correct fix, need to replace it with proper escaping function
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c15dda93c97591cfcef0b16155bf62a19f3a5983#diff-45752acf5e8ea05d2224fa9a73c54c7aL614

**Comment by MohammedKaludi** [comment]
add div in the list

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/51e869aa5cc42cfbde664b3a3da9f14e844c7e7c#diff-45752acf5e8ea05d2224fa9a73c54c7aR614

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.64
