### ISSUE TITLE
Even after the subscribing still the Subscribe button is displaying the same in the one signal

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4756]
Even after the subscribing still, the Subscribe button is displaying the same in the one signal. This issue is occurring on both mobile and desktop and also if we subscribe from the AMP pages we are not getting any notification.

Ref video of the website: https://monosnap.com/direct/VKlLw5V40vY1QbwuJynXSNjYu6n6QY
Ref video of the local: https://monosnap.com/direct/oCVb2FFOE2kOvB3oUl3rc3rNfVSrXc

Ref:https://secure.helpscout.net/conversation/1284685740/154911?folderId=3575684

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/1294397905/156485/

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://wordpress.org/support/topic/onesignal-not-working-with-amp/

**Comment by Zabi09** [comment]
https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/255

**Comment by Zabi09** [comment]
Jon from 0nesignal says - Thanks for reaching out. We are aware of this and will be prioritizing it later next quarter. Sorry for the inconvenience

So it will be fixed in - https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/255
