### ISSUE TITLE
Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4757]
Reference:  https://wordpress.org/support/topic/image-elements-do-not-have-alt-attributes-2/
https://wordpress.org/support/topic/alt-attribute-of-images/

Website: https://www.noblehomeremedies.com/ear-piercing-for-weight-loss/amp/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
