### ISSUE TITLE
When genesis theme  is activated we are getting a Error notice in AMPforWP Dashboard from the updated verison 1.0.63

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4758]
Error notice showing as:

Incorrect SEO plugin has been selected in AMPforWP SEO Settings, Please select Genesis from SEO Settings.

https://secure.helpscout.net/conversation/1263710719/150357?folderId=2632030

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
