### ISSUE TITLE
In the Contact form module, wp form options are not getting selected.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4761]
* Need to change the path of the wp forms plugin, so the form details can be fetched in the Contact form module.
* In the Contact form module, wp form options are not getting selected, if we refresh, then the option shows as empty and shows no output in the frontend.
Ref: https://secure.helpscout.net/conversation/1292880367/156124/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
