### ISSUE TITLE
Deprecated tag_rewrite_rules 

### ISSUE THREAD

**Issue by augustocmarinho** [ahmedkaludi/accelerated-mobile-pages#4762]
The plugin give's me the following warning: 

Deprecated: tag_rewrite_rules está obsoleto desde a versão 3.1.0! Use post_tag_rewrite_rules em seu lugar. in [...]/wp-includes/functions.php on line 5148

After wordpress update

**Comment by Zabi09** [comment]
Fixed in #4664

**Comment by augustocmarinho** [comment]
I'm, on the last version of the plugin, and the error still showing

Deprecated: tag_rewrite_rules está obsoleto desde a versão 3.1.0! Use post_tag_rewrite_rules em seu lugar. in /var/www/html/wp-includes/functions.php on line 5148
