### ISSUE TITLE
Socil share Buttons do not have an accessible name using  Design One

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4764]
Screenshot: https://prnt.sc/ur8dse
Website: https://www.noblehomeremedies.com/ear-piercing-for-weight-loss/amp/
Reference: https://wordpress.org/support/topic/buttons-do-not-have-an-accessible-name-3/

**Comment by MohammedKaludi** [comment]
ready

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
