### ISSUE TITLE
Table on a website blog is created with 2 columns but displaying 1 extra column(2+1) on mobile view

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#4765]
Two columns are created in a table of blog post but three columns are shown for few tables on the Mobile view of AMP pages.

Ref Ticket : https://secure.helpscout.net/conversation/1299492610/157298/

User website : Screenshot on Mobile view - https://prnt.sc/usbywg
                       Screenshot on Desktop view - https://prnt.sc/usc0re

Local host : Screenshot on Mobile view - https://prnt.sc/usbw1o
                   Screenshot on Desktop view - https://prnt.sc/usbx4g

**Comment by sonaliramteke** [comment]
In design 1 2 3 extra column is displaying - https://prnt.sc/uv6xmw

**Comment by MohammedKaludi** [comment]
I dont think this is a correct fix..

**Comment by MohammedKaludi** [comment]
are you sure this is fixed?

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.68
