### ISSUE TITLE
Getting warnings on the AMP posts.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4767]
Getting warnings on the AMP posts.

Warning: preg_replace(): Compilation failed: missing closing parenthesis at offset 188 in /home/customer/www/missedvotes.com/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8620

Warning: preg_replace(): Compilation failed: missing closing parenthesis at offset 188 in /home/customer/www/missedvotes.com/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8649
 
Ref screenshot: https://prnt.sc/utdzn2

Ref:https://secure.helpscout.net/conversation/1300164154/157455?folderId=3575684.

**Comment by MohammedKaludi** [comment]
Warning: preg_replace(): Compilation failed: missing closing parenthesis at offset 188 in /home/customer/www/missedvotes.com/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8620

Screenshot: https://prnt.sc/utgb5y
Website: https://www.missedvotes.com/a/amp/
Reference: https://wordpress.org/support/topic/preg_replacecomputation-failed/

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/241fa8e309cf686d51f0e0b27ee11747f9aa1e8b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8782
`$cols` variable moved inside in the if condition, there is no fallback added here. so initialize it before if condition.

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/241fa8e309cf686d51f0e0b27ee11747f9aa1e8b#diff-6aa5512f7dd8d5ce60fc97b0f340912cR8948
regular expression is broke when https://regex101.com/r/n1rXDx/1

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3d8d2df7c3a59c958d789eceb14682df5ad88cd1#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580R8949

regular expression will be https://prnt.sc/uywv5q `<a(.*?)href=['|"](.*?)['|"]`

**Comment by Zabi09** [comment]
No, we dont need href content and we just need to check if href exists or not and if it exists then we are adding target="_blank" statically

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
