### ISSUE TITLE
Warning Error: preg_replace():computation failed

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4768]
Warning: preg_replace(): Compilation failed: missing closing parenthesis at offset 188 in /home/customer/www/missedvotes.com/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8620

Screenshot: https://prnt.sc/utgb5y
Website: https://www.missedvotes.com/a/amp/
Reference: https://wordpress.org/support/topic/preg_replacecomputation-failed/

**Comment by MohammedKaludi** [comment]
already reported in #4767
