### ISSUE TITLE
Need to make compatibiliyt with the Genesis theme functionality"Archive Intro Text" in category section

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4769]
Ref: https://secure.helpscout.net/conversation/1263710719/150357?folderId=2632030

Use case: the user is adding the text in the Archive Intro Text and the field comes from the genesis theme in the category section and this content is not coming in the amp version of the category page.

Ref:https://www.pest-control-products.net/category/questions-and-answers/

**Comment by ajeetku** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c2b4fd2f546ed837e95713afadff5afa67bd3998#diff-faeb19fc0c2a07ee1c906366dee6d247R104-R105
We can reduce the db unnecessary call if "genesis_term_meta_defaults" method not exists

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
