### ISSUE TITLE
amp-incontent-ads V1.5 field restrictions

### ISSUE THREAD

**Issue by loano** [ahmedkaludi/accelerated-mobile-pages#477]
amp-incontent-ads does not allow 2 custom ads in one field anymore. The versions before did, and I used it to have an Adsense ad above Plista recommendations. E.g. http://starzip.de/rainbow-underlights-jetzt-traegt-man-die-haare-als-regenbogen/amp

**Comment by ahmedkaludi** [comment]
@loano I will test this properly and get back to you soon as possible.

**Comment by loano** [comment]
@ahmedkaludi I just figured out, that with V1.5 "Below the Post Content (Single Post)" no custom ad code is working, not matter from which advertiser.
