### ISSUE TITLE
Need to make the compatibility with the Post Layout Template feature of the News beat theme

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4770]
Use case:  when the post layout template for the single post is selected as the gallery or video then for that single post the feature image should not get a display for that post. as the gallery or the video will be getting displayed in that feature image place.

Ref: Please see this URL of the non-amp version, as the feature image won't get a display.

https://www.corriereromagna.it/basket-a2-il-primo-allenamento-dell-unieuro-forli/

https://secure.helpscout.net/conversation/1294282938/156458?folderId=2632030

**Comment by Zabi09** [comment]
Going to get fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3668
