### ISSUE TITLE
latest update causes Error 5xx: internal server error in Wordpress site

### ISSUE THREAD

**Issue by Samorax** [ahmedkaludi/accelerated-mobile-pages#4771]
Wordpress  = version 5.5.1, PHP = 7.3.19

Latest version fails to update and disconnects site from database making website not to load with error message - 'internal server error'

**Comment by Zabi09** [comment]
@Samorax We are extremely for the inconvenience will you please provide us your website URL and also will you please turn on wp-debug to true in the wp-config. php file like define('WP_DEBUG', true), So that we can check the error and fix it immediately

**Comment by Samorax** [comment]
> @Samorax We are extremely for the inconvenience will you please provide us your website URL and also will you please turn on wp-debug to true in the wp-config. php file like define('WP_DEBUG', true), So that we can check the error and fix it immediately

I have solved the issue on my website by re-uploading core files (wp_admins) and deactivating all plugins temporarily until I was able login into the admin area. I discovered it was the plugin when I tried updating it again. However, this is the [website](http://www.flamingwords.org) and I have changed wp-debug to true.

**Comment by Zabi09** [comment]
I have visited the website which you have sent us but I am unable to see any AMP version on your website. Have you deactivated our AMPforWP plugin? If yes then will you please enable it so that we can check the error and fix it

**Comment by Samorax** [comment]
Hello, I have enabled it and now it has crashed my website. THis is the message I get: "Update failed: An attempt was made to access a socket in a way forbidden by its access permissions. Error reconnecting to the database This means that we lost contact with the database server at 127.0.0.1:51878. This could mean your host&#8217;s database server is down. Are you sure the database server is running? Are you sure the database server is not under particularly heavy load? If you&#8217;re unsure what these terms mean you should probably contact your host. If you still need help you can always visit the WordPress Support Forums. An attempt was made to access a socket in a way forbidden by its access permissions. Error reconnecting to the database This means that we lost contact with the database server at 127.0.0.1:51878. This could mean your host&#8217;s database server is down. Are you sure the database server is running? Are you sure the database server is not under particularly heavy load? If you&#8217;re unsure what these terms mean you should probably contact your host. If you still need help you can always visit the WordPress Support Forums."

**Comment by Zabi09** [comment]
This issue is not related to our plugin, So I am closing
