### ISSUE TITLE
If the Convert AMP to WP theme (Beta) theme option is enabled then one fallback image is adding

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4773]
Ref: https://secure.helpscout.net/conversation/1302871513/158241?folderId=2770545

If the "Convert AMP to WP theme (Beta) theme" option is enabled then one fallback image is adding after the image in the frontend. We need to remove it.

Screenshot:
User end: https://prnt.sc/uungbo
Local End: https://prnt.sc/uunf9i

The issue is recreated on the local.

Steps to recreate:
1. Add any page and set it as the homepage in the reding settings as well as in the AMP settings custom front page option.
2.  User AMP Page Builder prebuilt layout and import the swift Layout
  Screenshot: https://prnt.sc/uunmv0
3. Save the changes and see the non-AMP homepage.

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
