### ISSUE TITLE
If the user is activating the "OMGF | Host Google Fonts Locally" plugin the getting validation error

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4775]
Ref: https://secure.helpscout.net/conversation/1302035931/158108?folderId=2770545

Screenshot: https://prnt.sc/uv93jt

Plugin URL:  https://wordpress.org/plugins/host-webfonts-local/

URL : https://www.neler.com/sinameki-cayinin-faydalari/amp/

When the user is activating the  "OMGF | Host Google Fonts Locally" and its pro version then the user is getting the validation issue.  The issue is not occurring locally.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
