### ISSUE TITLE
'Missing the script tag of the AMP component' 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4776]
When the user activates the  Cache Enabler plugin, in AMP pages, it gives the following error:
 The amp-state tag requires the amp-bind JavaScript extension.
The script tag needs to add the JavaScript amp-bind extension.

Website:  https://hotskidki.by/deal/jap-stock/amp/
Reference: https://wordpress.org/support/topic/amp-pages-are-not-valid-after-recent-updates/

**Comment by Zabi09** [comment]
I have activated both Autoptimize and Cache Enabler on my end – https://prnt.sc/uwk1bh but still, I am not getting any error – https://wordpress-123147-847862.cloudwaysapps.com/amp/

Also, I noticed that if you activate both plugins Autoptimize and Cache Enabler then the admin notice is appearing in Autoptimize settings to disabled the cache enabler minification – https://prnt.sc/uwk10b

And also you can follow this tutorial if you want to use the Cache Enabler in your normal website and you remove it only in the AMP website – https://ampforwp.com/tutorials/article/what-is-ampforwp-plugin-manager-and-how-to-use-it/

Hope it helps

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.66
