### ISSUE TITLE
Site problems after installing the "AMP for WP" plugin

### ISSUE THREAD

**Issue by papyon2016** [ahmedkaludi/accelerated-mobile-pages#4777]
Hello.
My site is not English and uses Unicode.(Arabic and persian)
This is my site address:
https://www.iranntv.com/
I installed the "AMP for WP" plugin.
The problem I had with my mobile was that the menus sidebar does not work and it marked "xxxx".
Regarding the menu showing "xxx" I found the problem.
I needed to add the "mb-string" extension to my php setup in my linux server.
It would be nice to have this documented somewhere for other users.
I've run into a new issue now:
the mobile redirection is not working. I.e. 
when on a mobile device, it is not redirecting automatically to the AMP version despite the redirection setting being on.
I did some digging, and found that the Mobile_Detect system is not working correctly.
My website is behind Amazon Cloudfront and while this system has a method for such cases, it is not detecting the mobile device from the headers.
Any ideas? 
Thanks in advance.

**Comment by Zabi09** [comment]
@papyon2016 Its nice to hear that you have fixed the issue of the menu by enabling the mb-string but we do have the tutorial for that already and here is the URL for that - https://ampforwp.com/tutorials/article/troubleshooting-the-problems-with-the-menu-navigation/

And for the mobile redirection will you please follow this tutorial and let us know if it's helpful or not - https://ampforwp.com/tutorials/article/mobile-redirection-not-working-even-after-enabling-the-option-why/

**Comment by papyon2016** [comment]
Hi there:
My site  uses Unicode.(Arabic and persian)
This is my site URL:
https://www.iranntv.com/
I installed the "AMP for WP" plugin.
I've run into a  issue now:
the mobile redirection is not working. I.e.
when on a mobile device, it is not redirecting automatically to the AMP version despite the redirection setting being on.
I did some digging, and found that the Mobile_Detect system is not working correctly.
My website is behind Amazon Cloudfront and while this system has a method for such cases, it is not detecting the mobile device from the headers.
For more informations:
I am using the Wp Rocket plugin and I made the settings according to your instructions.
Which you can see below.
![My adjust in wp rocket](https://user-images.githubusercontent.com/28312311/95738651-d6479380-0c89-11eb-9393-5c27eca1afa8.PNG)
But it still does not work.
Please connect to my site and see the issue closely.
https://www.iranntv.com/
PLS guide me, what can i do now?
Best Regards

**Comment by Zabi09** [comment]
@papyon2016 I have checked your website now and the mobile redirection is working fine. Have you done any changes?

**Comment by Zabi09** [comment]
Github is for recreatable issues, for technical support, please contact on site
