### ISSUE TITLE
create a filter hook to modify GDPR popup output

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#4778]
User want to translate the GDPR popup content (including setting strings like "Reject", "accept" )etc, in different language using Polylang so need to add filter hook to modify it.

**Comment by Zabi09** [comment]
Need to add the key of the array and just change the value of it like the below example:
```
add_filter('ampforwp_modify_gdpr_output','prefix_test');
function prefix_test($gdpr){
	$gdpr['headline'] = 'Translated Headline';
	return $gdpr;
}
```

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
