### ISSUE TITLE
If the "Change End Point to ?amp" option is enabled then the correct amphtml is not generating for the homepage if homepage support is enabled.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4780]
Ref: https://secure.helpscout.net/conversation/1304903823/158539?folderId=2770545

If the "Change End Point to ?amp" option is enabled then the correct amphtml is not generating for the homepage if homepage support is enabled.

Screenshot:
https://prnt.sc/uy8c87

The issue is also occurring on the local.

URL: https://firstranker.com/

The issue only occurs for the homepage.

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://wordpress.org/support/topic/amp-page-is-invalid/#post-13527748
website:  https://rajksite.com

**Comment by sardarui** [comment]
Same issue with this user too: https://secure.helpscout.net/conversation/1303368635/0/?folderId=3126461

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65.2

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by pgdeep** [comment]
My homepage is down again with "Too many redirect error". Please refer screenshot/ screen recording from below drive link

https://drive.google.com/drive/folders/1JPKHn2acILa1j2cOfIryB6Y57Gi2jOwd?usp=sharing

![20201024_114326](https://user-images.githubusercontent.com/16613943/97091858-089fac00-160d-11eb-897c-1a001c72d273.jpg)

**Comment by Zabi09** [comment]
@pgdeep I have checked your website by opening it directly and also through google search and in both cases it's working fine.

See this video - http://magazine3.com/garage/wp-content/uploads/2020/10/Desktop-2020-10-26-12.01.45.mp4

Will you please elaborate more on it so that we can help you

**Comment by pgdeep** [comment]
Hi Syed,

Thanks for checking. I saw your video and you are opening the cached amp page from google, which will work as its coming from google servers as a cached copy.

you are not able to see the redirect error, because home redirection is not working. I deleted cached files/ cookies in the browser. Please check below video to better understand the issue.

https://drive.google.com/file/d/15V2j9Oiad3cj9ZQ5SI6D8qkapnyOdaOy/view?usp=sharing

**Comment by Zabi09** [comment]
I have checked your mobile redirection on the homepage and also on some posts and it is working fine now

See this video - http://magazine3.com/garage/wp-content/uploads/2020/10/Desktop-2020-10-28-14.38.32.mp4

Have you done any changes? and also Github is for recreatable issues, for technical support, please contact on site
