### ISSUE TITLE
<amp-youtube gets flagged as not being accessible by Lighthouse.

### ISSUE THREAD

**Issue by Frenchomatic** [ahmedkaludi/accelerated-mobile-pages#4781]
Adding title tags to amp-youtube such as <amp-youtube title="this is my description" gets flagged as not being accessible by lighthouse. They say this is an AMP issue. 

The accessibility error is given as <iframe> elements do not have a title. In other words, adding a title tag to <amp-youtube> is being ignored or removed when turned into an iframe.

**Comment by Zabi09** [comment]
This is a known issue that is being worked on in AMP. See https://github.com/ampproject/amphtml/issues/29874

So closing this ticket because it's not from our AMP plugin
