### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function ampforwp_is_home() in /home/tastesof/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php:1084 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4782]
Fatal error: Uncaught Error: Call to undefined function ampforwp_is_home() in /home/tastesof/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php:1084 Stack trace: #0 /home/tastesof/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php(240): ampforwp_get_all_post_types() #1 /home/tastesof/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php(394): ampforwp_add_custom_rewrite_rules() #2 /home/tastesof/public_html/wp-includes/class-wp-hook.php(287): ampforwp_rewrite_activation('') #3 /home/tastesof/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #4 /home/tastesof/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /home/tastesof/public_html/wp-admin/plugins.php(193): do_action('activate_accele...') #6 {main} thrown in /home/tastesof/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 1084

Ref: https://secure.helpscout.net/conversation/1164869093/129784/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.65 update
