### ISSUE TITLE
polylang string transaltion support

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#4784]
user want to translate the static words in different language using polylang the words are mentioned below.

 Next,
 Previous,
 Related Post, 
 Recent Post, 
 tags, 
 All Rights Reserved
 View Non-AMP Version,
 Type here (search place holder),
 Homepage (in breadcrumb)

we have added all these strings in Polylang string translation panel using amp polylang just need to wrap all these string in polylang function to translate it.

example:

if(function_exists('pll__')){
 echo pll__('View Non-AMP Version');
}else{
    echo 'View Non-AMP Version';
}
need to make sure we have added this in all designs.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
