### ISSUE TITLE
 validation error occurs with the src and alt The attribute 'alt','src' may not appear in tag 'input'

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4785]
This issue occurs when the below type of content is added in the content.

`<input title="PayPal - The safer, easier way to pay online!" alt="PayPal - The safer, easier way to pay online!" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" type="image" />
`

Need to strip the tags as the validation occurs with the src and alt,

 The attribute 'alt','src' may not appear in tag 'input'

Ref:https://djcarl.com/itunes-podcast-urban-music-2017/amp/

Ref:https://secure.helpscout.net/conversation/1298330501/157093?folderId=2632030

**Comment by Zabi09** [comment]
https://amp.dev/documentation/components/amp-form/#not-allowed

**Comment by MohammedKaludi** [comment]
Incorrect fix if the fix is done this way, the payment button will disappear: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3fc269e3ace153c2fc8997c691e8132a2d8b999d#diff-be686f3f8620ee9c483237ef6ca42b708d31b1f75dc1d24ad2dcdd000ae9691dR47

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.68 update
