### ISSUE TITLE
In AMP, two H1 tags appear in Design one

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4786]
Website: https://www.noblehomeremedies.com/heavy-mind-anxiety-stress/amp/
Reference: https://wordpress.org/support/topic/two-h1-tags-on-amp-pages/

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66
