### ISSUE TITLE
Undefined index: plugin_status in amp-pro-extension-manager

### ISSUE THREAD

**Issue by nisiwi** [ahmedkaludi/accelerated-mobile-pages#4788]
I'm running query monitor and seeing the following PHP error:

Undefined index: plugin_status

wp-content/plugins/amp-pro-extension-manager/amp-pro-extension-manager.php:793
AMPExtensionManager->amforwppro_plugin_extension_list()
wp-includes/class-wp-hook.php:287
apply_filters('all_plugins')
wp-admin/includes/class-wp-plugins-list-table.php:106
WP_Plugins_List_Table->prepare_items()
wp-admin/plugins.php:533

Plugin: amp-pro-extension-manager

**Comment by merajali294** [comment]
@nisiwi , We've noted down this issue and will be resolved in the very next update.
Reference:- https://prnt.sc/v0gob8
