### ISSUE TITLE
Trying to get property 'ID' of non-object in Plugin: amp-cta

### ISSUE THREAD

**Issue by nisiwi** [ahmedkaludi/accelerated-mobile-pages#4789]
Here’s another PHP error I’m seeing in Query monitor, this time from AMPforWP CTA extension.
This is occuring for me when I have no CTA's in the system, just the plugin enabled.

Trying to get property 'ID' of non-object

wp-content/plugins/amp-cta/output.php:200
amp_cta_bar_comparison_logic_checker()
wp-content/plugins/amp-cta/output.php:200
array_map()
wp-content/plugins/amp-cta/output.php:71
amp_cta_bar_generate_field_data()
wp-content/plugins/amp-cta/output.php:20
amp_cta_bar_get_all_schema_posts()
wp-content/plugins/amp-cta/amp-cta.php:712
ampforwp_cta_bar_css_condition()
wp-includes/class-wp-hook.php:287
do_action_ref_array('wp')
wp-includes/class-wp.php:758
WP->main()
wp-includes/functions.php:1285
wp()
wp-admin/includes/post.php:1203
wp_edit_posts_query()
wp-admin/includes/class-wp-posts-list-table.php:154
WP_Posts_List_Table->prepare_items()
wp-admin/edit.php:215

Plugin: amp-cta

**Comment by Zabi09** [comment]
Added in Trello board and it will be fixed ASAP - https://prnt.sc/v15fhu

**Comment by Arihantkankariya09** [comment]
@nisiwi I tried to recreate the warnings on my end following the same scenario that you mentioned, I do not see any of them. 
I have to fix this on your end only. Please create a ticket on our technical support, https://ampforwp.com/support/#contact
we will work on it.
