### ISSUE TITLE
More control over the logo size

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#479]
More control over the logo size 

As suggested on: https://wordpress.org/support/topic/logo-size-why-is-it-set-on-the-image/

**Comment by ahmedkaludi** [comment]
Logo size image feature added in the latest update.

**Comment by shswanson** [comment]
I don't see the option to change the size - can you point me in the right direction?

**Comment by shswanson** [comment]
(great work on this plugin, btw - it's outstanding)

**Comment by ahmedkaludi** [comment]
@shswanson Here you go: http://take.ms/nuaR8 < check this screenshot.

P.S. i'm working with one hand

**Comment by shswanson** [comment]
Omg how embarrassing. Sorry to waste your time.
