### ISSUE TITLE
Need to add the new Infinite scrolling experience for document-level page recommendations.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4791]
Currently, amp-next-page 0.1 is being used for the infinity scroll, but the better version is now available. 

For more information visit: https://amp.dev/documentation/components/amp-next-page/?format=websites

ref: https://secure.helpscout.net/conversation/1311012233/159565?folderId=3514643

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.37.1
