### ISSUE TITLE
Getting "CSS syntax error in tag 'style amp-custom' - unterminated comment " Error on AMP.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4792]
Getting "CSS syntax error in tag 'style amp-custom' - unterminated comment "Error on AMP pages and post. This error occurring if we use the below pattern for the Image:

For images if we use this pattern the issue is occring : <style="width: 229px;/* float: right; */">

Ref screenshot of local:https://prnt.sc/v29r88

Ref URL of the issue:https://www.resperate.com/blog/hypertension/treatments/alternative-treatments/reflexology-natural-approach-lowering-blood-pressure/amp

Ref:https://secure.helpscout.net/conversation/1312868437/160044?folderId=3575684.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.67
