### ISSUE TITLE
Feature request to add Google Analytics 4 support

### ISSUE THREAD

**Issue by AnkitaBeniwal** [ahmedkaludi/accelerated-mobile-pages#4793]
Google has recently released Google Analytics 4. AMP for WP already has support for Google Analytics and Google Tag Manager. Support for Google Analytics 4 will be great.

**Comment by Zabi09** [comment]
@AnkitaBeniwal I have searched and did not find any official tutorial on how to add Google Analytics 4 properties to the AMP pages. If you have any documentation on how to add it to AMP then please share with us so that we can check that and make feature in our plugin also

**Comment by Zabi09** [comment]
https://github.com/ampproject/amphtml/issues/24621

**Comment by TMsravan** [comment]
Another user:  https://secure.helpscout.net/conversation/1529041773/199595?folderId=2632030

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/analytics-4-support-in-amp/#post-14565318

**Comment by MohammedKaludi** [comment]
https://github.com/ampproject/amphtml/issues/24621#issuecomment-848715411

This feature is still under development as of today:
![image](https://user-images.githubusercontent.com/16618009/122339467-c261d900-cf5e-11eb-88b4-22d4874bba5b.png)

**Comment by 77naveenop** [comment]
There are two more user's request related to GA4, which is not working with AMP.
