### ISSUE TITLE
AMP validation error due to unnecessary amp component script

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#4794]
if parallax effect [amp-fx-flying-carpet component] is used in amp ads then amp-story-player script loading unnecessarily which causing an amp validation error.

need to improve this condition in feature.php line no:8338
if(preg_match('/(type|template|id)="('.$ocomp.')"/', $content) || preg_match("/<\/$key>/",  $content) || preg_match("/amp-fx/",  $content)){
}

 Ref: https://secure.helpscout.net/conversation/1313722776/160204?folderId=2770543

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66.1
