### ISSUE TITLE
Havent touched my AMP settings

### ISSUE THREAD

**Issue by JoeStambray** [ahmedkaludi/accelerated-mobile-pages#4795]
I haven't changed my AMP settings in months. Getting this now on search console. Tried everything to fix.
A tag on this page requires an AMP component 'script' tag, which is missing.

**Comment by bakhtorg** [comment]
I have same issue in [my site](https://bakht.link/tinybet/amp/)

Temporary you can add this lines to **functions.php**

```
add_action('init', function () {

    remove_action('ampforwp_after_post_content', 'ampforwp_truepush_markup');
    remove_action('ampforwp_before_post_content', 'ampforwp_truepush_markup');

}, 11);
```

**Comment by Zabi09** [comment]
@bakhtorg Sorry for the inconvenience, We have fixed the issue - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4796 and we are going to push it immediately, just update the plugin to 1.0.66.1 and it will be fixed

**Comment by MohammedKaludi** [comment]
1.0.66.1 update has been pushed
