### ISSUE TITLE
The tag 'amp-web-push-widget' requires including the 'amp-web-push' extension JavaScript.

### ISSUE THREAD

**Issue by bakhtorg** [ahmedkaludi/accelerated-mobile-pages#4796]
Today I got lots of validation error for all of my wordpress websites.

Google error: A tag on this page requires an AMP component 'script' tag, which is missing.
Validation error: The tag 'amp-web-push-widget' requires including the 'amp-web-push' extension JavaScript.

Version: 1.0.66

I have another site with amp plugin and one-signal together, but it has not error.

Site with error: [https://bakht.link/hazarat/amp/](https://bakht.link/hazarat/amp/)
Site without error: [https://bakht.org/gambling-website/hazarat-bet/amp/](https://bakht.org/gambling-website/hazarat-bet/amp/)

**Comment by MohammedKaludi** [comment]
Ready to merge,

**Comment by MohammedKaludi** [comment]
pushed in 1.0.66.1

**Comment by garimaajjain** [comment]
Hi MohammedKaludi,

I have updated the pligin, but in Google Search Console Showing an error The tag 'amp-web-push-widget' requires including the 'amp-web-push' extension JavaScript.

**Comment by MohammedKaludi** [comment]
@garimaajjain 
Just checked your site with AMP Validation tool and your site is fully validated with AMP standards.
Please check this screenshot-> https://monosnap.com/file/4qHqTvzUy4vklMQew1hv0j0KJ1PMcc

Search console's data will be updated in a day or two as the data are shown in the Search Console are not Live, you can do Validate Fix to make the process faster.

Hope this helps.

**Comment by garimaajjain** [comment]
Please check for internal webpages: https://monosnap.com/file/J6iDs0fQGzVySKD91q8BGoJxAr7fsR

**Comment by garimaajjain** [comment]
This is another issues in webmaster : The tag 'amp-web-push-widget' requires including the 'amp-web-push' extension JavaScript. Please check the screenshot : https://monosnap.com/file/PlCoPjOCz7GVxI6aEnYm7CPMiLSXQG

**Comment by MohammedKaludi** [comment]
> Please check for internal webpages: https://monosnap.com/file/J6iDs0fQGzVySKD91q8BGoJxAr7fsR

You have tested an incorrect page 
You have to test the amp pages and the one you are testing is non amp page as show me the screenshot

**Comment by garimaajjain** [comment]
Thanks for your valuable inputs.

It means you say everything is ok.

Please check the final screenshot and give me your inputs: https://monosnap.com/file/A7WsqQrV080X5ri5hTMjGNOzAw8Up7

**Comment by MohammedKaludi** [comment]
Yes, everything seems good. 
Checked the Kareena Kapoor URL and amp page looks fine.
Enjoy the rest of the day :)

**Comment by garimaajjain** [comment]
Thank you once again.

**Comment by devansh234** [comment]
Hi MohammedKaludi,

Hope you're doing great!

I have updated the plugin, but Google Search Console is showing the error "The tag 'amp-web-push-widget' requires including the 'amp-web-push' extension JavaScript.", for two of my web pages:

https://infinitians.com/the-real-meaning-of-meditation/amp/
https://infinitians.com/why-your-relationships-sucks-how-to-manage-it/amp/
