### ISSUE TITLE
Submenus are not showing properly in the AMP Footer menu

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4797]
Ref: https://secure.helpscout.net/conversation/1312042936/159794?folderId=2770545

Screeenshot: https://prnt.sc/v713xx

In the AMP footer menu, the submenus are not showing. If the custom link option in the menu settings contains the "#" symbol or the "URL", the submenus inside it are not showing in the footer.

The issue recreated on the local also. 

Screenshot:
1. https://prnt.sc/v716cf
2. https://prnt.sc/v716z1

Steps to create:
1. Create one menu and use the Custom Link feature while creating the menus.
a) https://prnt.sc/v717x9
2. Add the submenus below it.
3. Enable the AMP Footer Menu Checkbook(https://prnt.sc/v71a13)
4. In the footer it is only showing the main menus not the submenus.

**Comment by Zabi09** [comment]
If you want the same footer of non-amp in AMP also then all you need to do is to go to the widgets section and add text widgets in AMP footer like - https://prnt.sc/v8jamc and it will also appear in AMP just like in non-amp - https://prnt.sc/v8ephu

So closing this ticket
