### ISSUE TITLE
If the excerpt available in the excerpt box then it should show otherwise not

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4798]
Ref: https://secure.helpscout.net/conversation/1293700425/156325/

1. The user wants to show the excerpt in a single post only if the excerpt is available in the excerpt box otherwise it should not show the excerpt.

Currently, we have the option to show the excerpt on the post but if it does not find any content in the excerpt box then it is taking the excerpt of the the_content. Also, it should not show the excerpt of the YOAST also.

2. Currently, we are sowing the excerpt at some limited characters., like this (https://prnt.sc/v8hvzo). The user wants to show the full content that he added in the excerpt box like this: (https://prnt.sc/v8hxfn)

URL:
1. https://wordpress-433650-1545074.cloudwaysapps.com/central-bank-spain-priority-cbdc/
2.https://wordpress-433650-1545074.cloudwaysapps.com/central-bank-spain-priority-cbdc/?amp

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.68 update
