### ISSUE TITLE
Wp post ratings error

### ISSUE THREAD

**Issue by intelezsol** [ahmedkaludi/Accelerated-Mobile-Pages#48]
Hello sir, 
This plugin is awesome. It has a very beautiful looking design. But it leads to some errors. You can check out this errors on my site. Check this url= <a href="https://goo.gl/sWneqA">https://goo.gl/sWneqA</a> as you can see this page is non-amp and the ratings displayed are normal. No check its amp version <a href="https://goo.gl/q8SMp9">https://goo.gl/q8SMp9 </a>as you can see the ratings are not displayed and the loading sign is very large. Please fix this, but if you can't then you can bring a new feature where we can exclude some plugins in amp pages.

Some design suggestions
The white header above the navigation is not so attractive but the whole design is good. Is there anyway so that we can display our custom header in the place of that white header present above the navigation. Eg: - the blue header which you can check out on non-amp version of my site techwhack.com
Check out my site non-mobile version page . I want to display the same header. You can check this screen shot <a href="http://i.imgur.com/LxNzgJZ.gif">http://i.imgur.com/LxNzgJZ.gif</a> . Please bring your next update as soon as possible. 
With all schema updates and these custom designs, your plugin would get more active install then automattic amp
Thanks

**Comment by ahmedkaludi** [comment]
This was fixed after 0.8 update.
