### ISSUE TITLE
website post not showing

### ISSUE THREAD

**Issue by amitkum1984** [ahmedkaludi/accelerated-mobile-pages#4800]
On my website, posts are not showing. all posts disappeared when goes to their URL. my website is khbr.in
for example, go to this URL and you will find (https://khbr.in/netflix-streamfest-aane-wala-hai-milega-free-netflix-dekhne-ka-mauka/)
please use your mobile for this
search this URL on google then click the 1st link
after this issue I deactivate the plugin amp for wp. and uses its original website theme.
![ar](https://user-images.githubusercontent.com/73599339/97452364-a9b69b80-195a-11eb-8a61-08cd24b84a7c.jpg)

**Comment by Zabi09** [comment]
We are extremely sorry for the inconvenience, We have fixed that issue in our  #4744 GitHub ticket and we are going to push it as soon as possible

**Comment by MohammedKaludi** [comment]
Pushed 1.0.66.3
