### ISSUE TITLE
Get Error on Google Console HTML tags contain disallowed attribute or attribute values

### ISSUE THREAD

**Issue by nubitool** [ahmedkaludi/accelerated-mobile-pages#4801]
After updating to version 1.0.66.1 I got an error on the google console "HTML tags contain disallowed attribute or attribute values". Within 1 day 42 pages were affected. Please help.

NB: Sorry for my bad English

**Comment by Zabi09** [comment]
It's not a problem with the AMP Plugin but came with the latest version of YOAST SEO and it is going to be fixed in the next update of the Yoast.

Ref: https://github.com/Yoast/wordpress-seo/issues/16255

**Comment by Zabi09** [comment]
Temporarily fix is to disable the ‘Enhanced Slack sharing’ feature in SEO>General>Features.
