### ISSUE TITLE
HTML tag please help

### ISSUE THREAD

**Issue by JoeStambray** [ahmedkaludi/accelerated-mobile-pages#4802]
I have stripped my AMP down to nothing. No social sharing no widgets at all. Still getting this error on search console.
Disallowed attribute or attribute value present in HTML tag.
Then it says something about Twitter. I don't know why. Even disconnected Yoast.

**Comment by Zabi09** [comment]
@JoeStambray can you please give me the URL where you are having the error, So that I can check it and help you in fixing it

**Comment by MohammedKaludi** [comment]
Issue seems to be resolved with the last update of Yoast, so closing the ticket.

Please reopen if the issue persists.
