### ISSUE TITLE
has_related_thumbnail image title is getting break and leading to the validation error

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4804]
**The attribute 'التّونسي"' may not appear in tag 'a'**

Ref: https://secure.helpscout.net/conversation/1315045793/160375/

https://www.mabapost.tn/%D8%A8%D8%B1%D8%AC-%D8%A7%D9%84%D9%88%D8%B2%D9%8A%D8%B1-%D8%A5%D8%B4%D8%AA%D8%A8%D8%A7%D9%83%D8%A7%D8%AA-%D9%88%D8%AA%D8%A8%D8%A7%D8%AF%D9%84-%D8%B9%D9%86%D9%81/

Use Case:1. when the post contains the title of this type:

كريم الغربي يستعدّ لتقديم برنامج ''ملاّ توانسة" على قناة الحوار التّونسي

To recreate:

1. add a post with the above title.

2. Enable the: In-Content Related Post option

3.Enable the: Disable wptexturize option.

Currently, Disable wptexturize option is disabled at the user end.

Issue recreated in local:

Ref: https://monosnap.com/file/K5FAdDG9AsO32UTA0gNmksaC3dUJrt

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.67
