### ISSUE TITLE
Additional characters at the end of footer text - Design Two

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4805]
In Design Two there are additional characters at the end of the footer text, Issue is occurring in localhost too.

Reference: https://wordpress.org/support/topic/additional-characters-at-the-end-of-footer-text/
User end: https://prntscr.com/vaku3s
Localhost: https://prnt.sc/vakvif

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.67
