### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by kkbharankar** [ahmedkaludi/accelerated-mobile-pages#4808]
Hi team, 

Could you please check what is below issue I am facing on my website. All amp versions showing same issue. Please let me know how to resolve it.

https://sarvkahimarathi.in/apsara-aali-lyrics/amp/

**Error:**
Fatal error: Uncaught Error: Class 'DOMDocument' not found in /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/utils/class-amp-dom-utils.php:63 Stack trace: #0 /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/utils/class-amp-dom-utils.php(324): AMPforWP\AMPVendor\AMP_DOM_Utils::get_dom('<html><head><me...') #1 /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(114): AMPforWP\AMPVendor\AMP_DOM_Utils::get_dom_from_content('<h2>\xE0\xA4\x85\xE0\xA4\xAA\xE0\xA5\x8D\xE0\xA4...') #2 /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(44): AMPforWP\AMPVendor\AMP_Content_Sanitizer::sanitize('<h2>\xE0\xA4\x85\xE0\xA4\xAA\xE0\xA5\x8D\xE0\xA4...', Array) #3 /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(26): AMPforW in /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/utils/class-amp-dom-utils.php on line 63
There has been a critical error on your website.

Learn more about debugging in WordPress.

Fatal error: Uncaught Error: Class 'DOMDocument' not found in /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php:8285 Stack trace: #0 /home2/sarvkahi/public_html/wp-includes/class-wp-hook.php(287): ampforwp_include_required_scripts('<br /> <b>Fatal...') #1 /home2/sarvkahi/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters('<br /> <b>Fatal...', Array) #2 /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php(236): apply_filters('ampforwp_the_co...', '<br />\n<b>Fatal...') #3 [internal function]: ampforwp_the_content_filter_full('<br />\n<b>Fatal...', 9) #4 /home2/sarvkahi/public_html/wp-includes/functions.php(4673): ob_end_flush() #5 /home2/sarvkahi/public_html/wp-includes/class-wp-hook.php(287): wp_ob_end_flush_all('') #6 /home2/sarvkahi/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #7 /home2/sarvkahi/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #8 /home2/sarvk in /home2/sarvkahi/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8285

**Comment by Zabi09** [comment]
@kkbharankar Here is the fix - https://ampforwp.com/tutorials/article/how-to-fix-domdocument-not-found-fatal-error/
