### ISSUE TITLE
The amphtml is not generating for the product category pages

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4810]
Ref: https://secure.helpscout.net/conversation/1323187087/162022?folderId=2770545

The amp HTML is not generating for the product category pages. 
Screenshot: https://prnt.sc/vcdgju

The issue is occurring after the 1.0.63 version. The issue is also occurring on the local.

Steps to recreate:
1. Install the AMP Woocommerce Pro and Woocommerce plugin.
2. Select the Product in the custom Post Type
3. Create one product category page and check the issue.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by Zabi09** [comment]
Fixed in #4822
