### ISSUE TITLE
The canonical links are not generating for the coupon store when YOAST Plugin is active with AMPFORWP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4811]
Ref: https://secure.helpscout.net/conversation/1316260297/160604/

Ref URL: https://pegastaging.jelastic.saveincloud.net/desconto/10web/?amp

Screenshot: https://prnt.sc/vcghub

Steps to recreate it:
1. Install the WP Coupon theme and the CM2 plugin.
2. Create one store: https://prnt.sc/vcgl53
3. Activate the YOAST plugin and select the YOAST SEO in the AMP settings panel.
4. Add the Coupon store in the custom taxonomy section: https://prnt.sc/vcgo1e

Plugin and theme are available in the Magazine3 Telegram group.

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.68 update
