### ISSUE TITLE
AMP Push Notification - Dropdown issue

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4812]
We have an issue with the AMP Push notification drop-down wherein even though there is nothing in the selection we have position and translation options displayed down.
https://monosnap.com/file/afWjTOLgeHf1c6mxgkwwv8vO3cZVNT

Please, find a link to a short video created for your immediate reference.
https://monosnap.com/file/Og5F6L8yw41sjhUGrBwiUErWn5AeXe

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.68 update
