### ISSUE TITLE
Content not displayed in AMP post/pages - Design 2

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4814]
Content is not displayed in AMP pages/post if plain permalinks are used.

Ref: https://wordpress.org/support/topic/amp-content-not-displayed/
Localhost : https://prnt.sc/vdxp8w

**Comment by MohammedKaludi** [comment]
ready for merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.68 update
