### ISSUE TITLE
The images added with the WP Block Editor are not showing in the AMP due to SG Optimizer lazy load feature

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4815]
Ref: https://secure.helpscout.net/conversation/1321213101/161604?folderId=2770545

When the user is adding the images through the WP Block Editor, then the images are not showing in the AMP in the AMP Takeover mode. If the AMP Takeover option is disabled the images are showing properly.

The issue is happening due to the SG Optimizer Lazy load feature(https://prnt.sc/ve05ex).
Screenshot: https://prnt.sc/ve0jq2

It should show like this: https://prnt.sc/ve0l2p

URL: https://askambulance.com/how-to-call-an-ambulance/

**Comment by Zabi09** [comment]
https://wordpress.org/support/topic/image-not-showing-in-amp/

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69 update
