### ISSUE TITLE
AMP option panel page is blank when the  ECPay Payment for WooCommerce" plugin is activated.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4816]
AMP option panel page is blank when the " ECPay Payment for WooCommerce" plugin is activated.

Please follow steps to recreate this issue:

1. Please activate both the " Woo-commerce plugin" and  " ECPay Payment for WooCommerce"(https://wordpress.org/plugins/ecpay-payment-for-woocommerce/).

2. Then please go to settings of the  Woocommerce -> payment -> Please enabled this option ECPay and ECPay Paid Automatically(https://prnt.sc/vei39q) then please check the AMP option panel.

Ref screenshot: https://prnt.sc/vehx4b

Ref: https://secure.helpscout.net/conversation/1326332218/162750?folderId=3575684

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69 update
