### ISSUE TITLE
Any filter to remove amphtml globally?

### ISSUE THREAD

**Issue by thegulshankumar** [ahmedkaludi/accelerated-mobile-pages#4817]

**Comment by Zabi09** [comment]
@thegulshankumar Yes we do have filters to remove amphtml globally but will you please tell us why you want to remove it? Because if you remove it then Google doesn't index your AMP pages in the search console.

Please let us know

**Comment by Zabi09** [comment]
You can simply enable the option of "Dev Mode in AMP" in the AMP options panel to remove amphtml on AMP pages. Here is the link for more info - https://ampforwp.com/tutorials/article/what-is-dev-mode-in-amp-and-how-to-use-it/

OR you can use this filter "ampforwp_modify_rel_canonical" and return empty like below to remove the amphtml

`add_filter('ampforwp_modify_rel_canonical', 'prefix_remove_amphtml');
function prefix_remove_amphtml($amphtml){
	return;
}`

**Comment by thegulshankumar** [comment]
It was required for safely removing plugin. Glad to know, there is dev mode. Thanks

**Comment by MohammedKaludi** [comment]
Just curious to know why you want to remove the amp from the site?

Any specific reason so that we can improve the plugin?

**Comment by MohammedKaludi** [comment]
Closing the ticket
