### ISSUE TITLE
Blank lines between paragraphs are cutted out

### ISSUE THREAD

**Issue by mmprep** [ahmedkaludi/accelerated-mobile-pages#4818]
Hi!

Why in AMP versions of pages blank lines are cutted out, for example between paragraphs?

I need these blank lines, which are in the desktop versions of pages, to visually separate the logical blocks of text.

Besides, in this case it is wrong that AMP versions of pages change the design of text at their own will.

**Comment by MohammedKaludi** [comment]
double explode?
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/72854bfbe62e75e5aceca7d891cce5ee99c408b1#diff-be686f3f8620ee9c483237ef6ca42b708d31b1f75dc1d24ad2dcdd000ae9691dR69

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69 update
