### ISSUE TITLE
The related recipe content changing in the AMP Takeover mode

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4819]
Ref:https://secure.helpscout.net/conversation/1164869093/129784?folderId=2770545

When the user is adding the related recipe through the editor(https://prnt.sc/vfvq6e) then, the contents are changing in the AMP Takeover mode.  The iframe contents are changing:

AMP Takeover: https://prnt.sc/v98uet
Without AMP Takeover: https://prnt.sc/v98tco

The content in the AMP Takeover is wrong. It should show like this:https://prnt.sc/vfvls4

On local, not the same scenario but the content is different:
In AMP Takeover: https://prnt.sc/vfvtmi
Without AMP Takeover: https://prnt.sc/vfvv0s

URL: https://tastesofhealth.eu/devtest/recipe/pasta-with-chanterelles-prawns-and-saffron-sauce/amp/

The recipe is creating using the  WP Ultimate Recipe Premium plugin.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69 update
