### ISSUE TITLE
Rewrite updates?

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#482]
1. This is a tag page but the tag is 'sweepstakes' 
Example: http://www.contestbank.com/sweepstakes/aarp/?amp

2. This is a category page but /category/ is not available, instead, he has used no slug.
http://www.contestbank.com/home-garden/?amp

Regards,
Ahmed

**Comment by ahmedkaludi** [comment]
@MohammedKaludi Any update on this? Isn't this already fixed?

**Comment by MohammedKaludi** [comment]
This is fixed in V0.9.40
