### ISSUE TITLE
Need to compatibility with the Google web stories.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4820]
One of our users is using Google web stories on his site where it is not working in AMP, so we need to add compatibility with the Google web stories plugin.

Plugin URL: https://wordpress.org/plugins/web-stories/

Ref Ticket: https://secure.helpscout.net/conversation/1329393675/163625/#thread-3838068461

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69 update
