### ISSUE TITLE
The "amphtml" is not generating for the pages in the AMP if the Hide By Default option is enabled with AMP Takeover

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4824]
Ref: https://secure.helpscout.net/conversation/1332722277/164200/

The "amphtml" is not generating for the pages in the AMP if the Hide By Default option is enabled with AMP Takeover for the pages having the "Show AMP For the current page" option is enabled.

Steps to recreate:
1. Enable the AMP Takeover and enable the AMP on the pages(https://prnt.sc/vif84v)
2. In the Tools section enable the "Hide By default"(https://prnt.sc/vif1vj)
3. Create a new page and enable the  "Show AMP For the current page" option.(https://prnt.sc/vif48x)

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7df5a63df87bde34de8568a9c0e7d60986ece239#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580R7193


get singular meta vaule of `ampforwp-amp-on-off ` instead of getting all the meta and it will improve the performance

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
