### ISSUE TITLE
Infinite Scroll and wrong sharing link

### ISSUE THREAD

**Issue by mmprep** [ahmedkaludi/accelerated-mobile-pages#4825]
When Infinite Scroll is enabled and you scroll down to the next post the link for the sharing options are wrong.

Whether it's social networking, messenger, or email, the link you send is for the FIRST post itself, not the one you've scrolled to.

**Comment by Zabi09** [comment]
@mmprep I have checked your issue on my local server and the social sharing links are working in the infinite scroll as expected, Will you please share your website URL So that I can check once and let you know

**Comment by mmprep** [comment]
You can check any link on https://mosmedpreparaty.ru/amp

**Comment by Zabi09** [comment]
I have checked your concern and found that the normal social share icons are working fine but the sticky social share is not working and we have already fixed this issue - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4791
