### ISSUE TITLE
When amp take beta option is enabled home page url is not redirecting to non-amp url when ?amp is added to the URL

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4826]
Ref: https://secure.helpscout.net/conversation/1292179008/156014?folderId=1060556

Use case: Due to this we are facing an error in the google search console: Referenced AMP URL is self-canonical AMP

The homepage URL is not getting validated.https://androidhackers.io/?amp

But when we add /amp it is redirecting to the non-amp version URL.

Checked in the local as well it is happening the same.

Only on the homepage URL, the issue is occurring. 

Ref: https://www.awesomescreenshot.com/video/1721035?key=3abd115149638728889821d0cdfac3e8

**Comment by MohammedKaludi** [comment]
ready to merge ,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
