### ISSUE TITLE
 Breadcrumb bug in amp homepage

### ISSUE THREAD

**Issue by dailyjulai** [ahmedkaludi/accelerated-mobile-pages#4827]
We are getting error in amp homepage for breadcrumbs that saying 'Either "name" or "item.name" should be specified'. See the link- https://search.google.com/test/rich-results?id=ebpdFeyL-WXrYefjcZd5Eg . Though its not happening on others page or post, you can check - https://search.google.com/test/rich-results?id=c5bt_LjbqmWQWwVYN4jYMw . 

We replaced yoast seo by rankmath pro to check whether its coming from their schema or not . But same issue getting there also. Also when we are using Google amp, there is no error then.

**Comment by Zabi09** [comment]
I have checked your issue and found that the schema is generated from the Yoast plugin - https://monosnap.com/file/CV4no8TrILf63KfT3T52GYCx2FTXuL and the breadcrumbs error is coming from there schema only.

So I recommend you to disable this option from our AMP options panel - https://prnt.sc/vkjymv and use our default schema or else we have created a separate plugin for the schema in which you will have so many features and also it's free - https://wordpress.org/plugins/schema-and-structured-data-for-wp/

Please try this and let us know

**Comment by dailyjulai** [comment]
If this problem happening for yoast then why its working properly with google amp plugin? Not only that when we are using Rankmath Pro instead of yoast, we are facing same issue. 

Now about your default schema, it is not working properly . Because breadcrumbs not showing in the article . We also tried your schema and structure data for wp plugin, but it decreasing our site speed.

**Comment by ajeetku** [comment]
Need to verify this filter will work inside the AMP, Currently, it can work for both AMP & NON-AMP.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
