### ISSUE TITLE
Preload amp-story-player

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4828]
ref: https://wordpress.org/support/topic/remove-preload-amp-story-js/
localhost: https://prnt.sc/vjyv1h

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://secure.helpscout.net/conversation/1336062224/164779/
Website:  https://goodmood.com.tw/improve-sleeping-health-food/amp/
Screenshot: https://prnt.sc/vmlh96
https://prnt.sc/vmli44

**Comment by MohammedKaludi** [comment]
Ready to mereg.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69
