### ISSUE TITLE
Changes in All in one SEO plugins from the authors.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4829]
Connect with the authors on mail:- https://secure.helpscout.net/conversation/1339593082/165373?folderId=4074390
Discuss up with the authors to make changes in our core plugin too.

**Comment by MohammedKaludi** [comment]
Ready for merge,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update

**Comment by arnaudbroes** [comment]
Hey @MohammedKaludi, 

You're still doing an add_filter for aioseop_amp_description without a check to see if the old plugin is active. Also, I don't see any compatibility for the new version.
