### ISSUE TITLE
[priority: highest] redirection issues few recreated

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#483]
- [ ] when post excluded and then mobile redirection on, then this gets too many redirections

- [ ] when home page support is off and then do we switch on mobile redirection, so this gets redirected too many times
- [ ] archive page switched off and mobile redirection on, then this gets too many redirections

- [ ] when pages are off/on and mobile redirection is on, then the directory is getting outputted for that page ...weird

**Comment by ahmedkaludi** [comment]
@MohammedKaludi What's the status of this? Any progress on it?
