### ISSUE TITLE
Role Based Access not working 

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4830]
If we create a user with SEO manager(role from SEO plugin) role and login through that username and password, AMP option panel is not available.

Ref: https://wordpress.org/support/topic/role-based-access-not-working/

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
