### ISSUE TITLE
Need to create compatibility with the WP-PageNavi plugin.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4831]
Need to create compatibility with the page navigation functionality(https://prnt.sc/vlxyez) by the WP-PageNavi plugin.

Ref:https://wordpress.org/plugins/wp-pagenavi/

Ref:https://secure.helpscout.net/conversation/1339520197/165360?folderId=3575684.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.72 update
