### ISSUE TITLE
Mobile redirection is not working with sg optimizer (user end issue)

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4832]
https://secure.helpscout.net/conversation/1327756095/163031?folderId=2632030

https://toocooltrafficschool.com/

Conflict with the sg optimizer plugin.

**Comment by Zabi09** [comment]
The issue is fixed by excluding AMP URLs from being cached - https://prnt.sc/vmnjvo
