### ISSUE TITLE
Special banner for the Black Friday & Cyber Monday offer inside every plugin

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4833]
We will have a special banner about the offer inside every plugin and need to release it by 23rd November 2020.
Reach out to Ahmed sir as every plugin will have its own unique positioning in the plugin,

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69 update

**Comment by MohammedKaludi** [comment]
pushed in 1.0.69.1

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.69.2

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
