### ISSUE TITLE
The background color of feature module of layout2 is not getting applied

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#4835]
Desc: The background color is not showing for the feature module contents for design two layout of amp page builder.
Ref: https://secure.helpscout.net/conversation/1313027733/160071?folderId=2770545

**Comment by Arihantkankariya09** [comment]
Media query CSS is not working when different layouts are used in the AMP page builder.
Issue location:- https://prnt.sc/vtib9g'
Expected solution attempt:- https://prnt.sc/vr8e6d

The issue originated from here:- The pricing module layout was not proper in the mobile view.
https://trello.com/c/PUbphdmE/2093-the-background-color-is-not-showing-for-the-feature-module-contents-for-layouts-design-two
Point 2.

**Comment by MohammedKaludi** [comment]
Ready for merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
