### ISSUE TITLE
Avatar image doesn't have alt attribute 

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4836]
A user is using WP User Avatar plugin for image avatar, the non-AMP version of the post loads the alt attribute in the Img tag, but when in amp it doesn't get alt in img tag.

Screengrab(non-AMP): https://monosnap.com/file/353gTSfKQMa5T1gchWGoWlTd1J9trm
Screengrab(AMP): https://monosnap.com/file/oh0bwVEgbdwuunAGIw4YJF7AWCOqrJ

Ref: https://secure.helpscout.net/conversation/1327241214/162883?folderId=3514643

**Comment by MohammedKaludi** [comment]
Ready for merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
