### ISSUE TITLE
Need to create compatibility with" i2Pros &cons" plugin.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4837]
Need to create compatibility with " i2Pros &cons" plugin.

Ref:https://wordpress.org/plugins/i2-pro-cons/.

Ref:https://secure.helpscout.net/conversation/1329524624/163652?folderId=3575684

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2a76607f3ad144cc16b81040d6ea51da85a0db57#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580R9267

Missing escaping 

I dont understand at this stage why its getting failed for escaping?

**Comment by MohammedKaludi** [comment]
Wrap the Hook inside class exists so that it will prevent a all if the plugin is not active. 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/2a76607f3ad144cc16b81040d6ea51da85a0db57#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580R9206

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.72 update
