### ISSUE TITLE
Error :The extension 'amp-story-player' was found on this page, but is unused.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4839]
Error: The extension 'amp-story-player' was found on this page, but is unused.

Due to this issue, there is an error in the google console to "An AMP component 'script' tag is present but unused."

Ref:https://validator.amp.dev/#url=https%3A%2F%2Ftechnicaljayendra.com%2Fbrave-browser-vs-uc-browser%2Famp%2F

Ref;https://secure.helpscout.net/conversation/1344989562/166179?folderId=3575684.

**Comment by MohammedKaludi** [comment]
pushed in 1.0.69.1

**Comment by jayendrasinhrajput** [comment]
@ahmedkaludi  the issue is still there nothing was resolved.
