### ISSUE TITLE
[debug error] If(Wp_debug=true){its showing the attached error}

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#484]
<img width="910" alt="captura de tela 2017-02-03 s 08 58 59" src="https://cloud.githubusercontent.com/assets/15303814/22618464/e6e61c7c-eb02-11e6-8dd4-2accac2d2b35.png">

**Comment by khaledMohammed000** [comment]
![image](https://cloud.githubusercontent.com/assets/16471728/25002573/c2345664-2068-11e7-8b6f-5de44edc0ba5.png)
This is not getting recreated

**Comment by khaledMohammed000** [comment]
This code seems perfectly fine to me, I guess this issue was fixed long back
