### ISSUE TITLE
 AMP Sidebar Menu Remains Open After Browser Back in Firefox and Safari web browsers 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4840]
AMP Sidebar Menu Remains Open After Browser Back in Firefox and Safari web browsers (but not in Chrome)

Ref: https://secure.helpscout.net/conversation/1346420611/166523?folderId=2632030

Please see this video which is checked in local as well:

https://monosnap.com/file/LGVfd66z337jKrFu1R8OzXBC4xpfYQ

1. once we click on the menu  item and it will redirect to that clicked the link

2. After that again when we click on the back tab of the browser, then we redirect to the back page of it. 

3.So when we come back to the previous page of it, the menu remains open in firefox.

but it chrome the menu will be in the closed position.

whereas in the firefox the menu will be in the opened position.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.71
