### ISSUE TITLE
The "amphtml" is not generating on the custom taxonomy and the custom post types

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4841]
Ref: https://secure.helpscout.net/conversation/1331694976/164006?folderId=2770545

The amphtml is not generating for the custom taxonomy and the custom post types after the 1.0.63 version update.

Custom post type: https://demo6.petclassifieds.com/ad/1-year-old-basset-hound/

Custom taxonomy: https://demo6.petclassifieds.com/ad_category/dogs/

The user is creating the post types and the custom taxonomy using the Adforest theme.

**Comment by sardarui** [comment]
Another User facing the same issue - "amphtml" is not generating on his custom post type.

Ref Ticket: https://secure.helpscout.net/conversation/1319924373/161362/

**Comment by MohammedKaludi** [comment]
working when removed then why the code was added in the first place?
and why its not working anymore?

**Comment by Zabi09** [comment]
I have checked many commits but not unable to find when we have added this code and because of this code only the problem is appearing, So thought to remove it for now

**Comment by MohammedKaludi** [comment]
ok

**Comment by DikshantJoshi** [comment]
Similar issue, with another user as well. 
amphtml is not being generated for Category pages of custom post type:
Ref: https://secure.helpscout.net/conversation/1352925457/167754?folderId=3514643

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
