### ISSUE TITLE
The post pages are redirecting to the 404 page after the update.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4842]
Ref: https://secure.helpscout.net/conversation/1349104409/166918?folderId=2770545

The issue occurred when the user is switching from the 1.0.62.2 version to the 1.0.69.1 version.

URL: https://folhago.com.br/entretenimento/separacao-de-zeze-di-camargo-e-luciano-e-anunciada-por-fonte-proxima-e-surpreende-a-web/36573/amp/

The issue is very rare.

**Comment by Zabi09** [comment]
To recreate select this in permalink - /%category%/%postname%/%post_id%/

**Comment by MohammedKaludi** [comment]
is_singular can be added so that it only works on single pages
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/31af90b10cc8c9b114ff64563406380165731bcd#diff-da2fca09e20c67536731a4070a82eb498deef93bc36774fdcf9d98c372825c2dR304

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
