### ISSUE TITLE
Ads are displyaing even GDPR popup is rejected.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4843]
Ref: https://wordpress-123147-847862.cloudwaysapps.com/amp/

https://secure.helpscout.net/conversation/1347325764/166629/

Even though the GDPR popup is rejected, still the ads are loading on the site.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update

**Comment by JNAzeem** [comment]
Ads are still displayed even after declining GDPR popup 
Ref: https://monosnap.com/direct/3gkpGz02S1JvMcfaviV9vEARbTGX3T
