### ISSUE TITLE
Undefined variable: allscripts 

### ISSUE THREAD

**Issue by ahsanali71184** [ahmedkaludi/accelerated-mobile-pages#4846]
hi there!

In my error log Following error is appearing!

Undefined variable: allscripts in /home/pmlforum/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8525

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
