### ISSUE TITLE
AMP version of page/post throws a validation error when using web stories plugin.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4847]
Validation error: The tag 'amp-story-player' requires including the 'amp-story-player' extension JavaScript.

Occurs in the local environment as well. 
The issue was resolved in version 1.0.65 of the AMP. 
And as expected when rolled back to the 1.0.65  it did fix the issue.

Ticket ref: https://secure.helpscout.net/conversation/1351987920/167533?folderId=3514643
Github: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4667

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
