### ISSUE TITLE
When the minify option is disabled, the WhatsApp share link has a space issue.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4848]
When the minify option is disabled, the WhatsApp share link has a space issue as space is not getting between the title and the site link.
issue recreated in the local.

Ref: https://secure.helpscout.net/conversation/1348800371/166868?folderId=1060556

Please see the video the issue is shown: https://monosnap.com/file/jV5yKByBcyv6JjG1CIE1dmRQWbq7T3

**Comment by sonaliramteke** [comment]
While testing this ticket the same issue occurred in design 1 2 3 - https://prnt.sc/vtlzqi

**Comment by MohammedKaludi** [comment]
Ready

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
