### ISSUE TITLE
Next-Previous Links Not Showing in Single of DESIGN ONE

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#485]
SEE: https://wordpress.org/support/topic/next-previous-links-not-showing-in-content/#post-8737973
Hey Paul,

Thank you so much for using the plugin.

Actually, you are using Design One and it doesn't have the Next/Previous in Single. I will create a ticket for this and we will make sure that this is available in the upcoming updates.

I hope it helps,

Regards,
Ahmed

**Comment by MohammedKaludi** [comment]
Fixed
