### ISSUE TITLE
Special characters are showing for the the post titles after sharing tweets in the Twitter

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4850]
Ref: https://secure.helpscout.net/conversation/1352369267/167618/

When the user is sharing the post on Twitter the post titles having some characters like the "double quotes, single quotes are converting into special characters. 

Screenshot:
Non-AMP:https://prnt.sc/vtlzbg
AMP: https://prnt.sc/vtm0gt

The issue occurring at the user end when activating the "Schema And Structured Data For WP & AMP" plugin.

The issue is not recreating on the local.

**Comment by MohammedKaludi** [comment]
we have created a builtin function to sanitize/format for twitter.
Use that instead of `htmlspecialchars`

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.71
