### ISSUE TITLE
Error: The extension 'amp-auto-ads' was found on this page, but is unused.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4851]
Error: The extension 'amp-auto-ads' was found on this page, but is unused.

Due to this issue, there is an error in the google console to "An AMP component 'script' tag is present but unused." 

This issue is occurring by the site kit by google plugin.

Ref:https://validator.amp.dev/#url=https%3A%2F%2Febiz.tools%2Fconversion-rate-optimization-tools%2F%3Famp

Ref: https://secure.helpscout.net/conversation/1338988341/165271?folderId=3575684.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.71
