### ISSUE TITLE
We need to add the attribute inside the analytics section (id= 'analytics')

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4852]
Ref: https://secure.helpscout.net/conversation/1352787703/167726?folderId=2770545

We need to add the id attribute inside the analytics section. We need to add it inside this function:

function ampforwp_analytics_options($opt_name){
         'id'  => 'analytics',

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.71
