### ISSUE TITLE
Need to add the LGDP (Brazil's GDPR)

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4854]
Ref: https://secure.helpscout.net/conversation/1351002277/167315?folderId=2770545

Ref: https://github.com/ampproject/amphtml/issues/31382

We need to add the GDPR support for Brazil.  Currently, Brazil is not added to the country list (https://prnt.sc/vu54vi)

**Comment by MohammedKaludi** [comment]
Ready for merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.70 update
