### ISSUE TITLE
Indent property doesn't work within Shortcodes Ultimate Compatibility Addon

### ISSUE THREAD

**Issue by mmprep** [ahmedkaludi/accelerated-mobile-pages#4855]
Hi,

Indent property doesn't work within installed Shortcodes Ultimate Compatibility Addon.

If I setup List shortcode like this

`[su_list indent="25"]
`

the AMP output doesn't considerate the indention.

But in desktop mode everything is OK.

Compare https://mosmedpreparaty.ru/news/21859  vs https://mosmedpreparaty.ru/news/21859?amp

Screenshots: https://prnt.sc/vutjeu vs https://prnt.sc/vutjza

**Comment by Zabi09** [comment]
This Github repo is for our AMPforWP plugin and if you need help in our paid extension then please contact us on our website - https://ampforwp.com/support/ and one of our extension team members will help you to fix your issues
