### ISSUE TITLE
"Heading elements are not in a sequentially-descending order" issue was noticed when using blurb module of AMP page builder.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4856]
Heading elements are not in a sequentially-descending order issue was noticed when using blurb module of AMP page builder.
This was noticed when a lighthouse test was conducted.

Screengrab: https://monosnap.com/file/79SHyfWG4pVwvacaI9V1azFXeARRWu
Ref: https://secure.helpscout.net/conversation/1327241214/162883?folderId=3514643

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.71
