### ISSUE TITLE
Need to create option to show the author details after the feature image.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4858]
Need to create an option to show the author details after the feature image (or) after the title. 

Ref: https://secure.helpscout.net/conversation/1355996300/168242?folderId=3575684

**Comment by MohammedKaludi** [comment]
Need improvement in the fix.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.6
