### ISSUE TITLE
Need to update Facebook Messanger Icon to the latest Icon in our plugin.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4859]
The user is requesting to update the Facebook Messenger Icon to the latest one.

Ref Ticket: https://secure.helpscout.net/conversation/1359826933/168839/

**Comment by MohammedKaludi** [comment]
Remove the old icon from the plugin to make plugin size small.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.71
