### ISSUE TITLE
Sidebar not working properly in the AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4861]
Ref: https://secure.helpscout.net/conversation/1356864556/168378?folderId=2770545

- Not redirecting to the category pages after selecting the category name in the dropdown

- Comment box is showing above the content on the Homepage when enabling the sidebar

Steps to recreate the first issue:
1. Enable the Twenty Twenty Theme and enable the sidebar option in the AMP.
2. Add the category Module in the sidebar Widget(https://prnt.sc/vxc0et)
3. When selecting the categories name from the dropdown it should redirect to the categories page but it is not happening in the AMP.

Steps to recreate the second issue:
1.Enable the sidebar for the Homepage from the AMP option panel
2. Enable the Facebook comments option and the comments option from the AMP option panel.
You will see the output like this:
https://prnt.sc/vxbtku

User Screenshot: https://prnt.sc/vxc55a

URL: https://graciayvida.com/la-navidad-escuela-biblica-para-ninos/amp/

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.71
