### ISSUE TITLE
Validation error in author bio alt attribute

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4864]
Users are getting Validation error in author bio alt attribute after plugin update version 1.0.70 

WordPress ref: https://wordpress.org/support/topic/amp-error-24/

**Comment by HaripriyaHari** [comment]
Same issue on another user: https://secure.helpscout.net/conversation/1361761067/

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
pushed in 1.0.71.1
