### ISSUE TITLE
AMPhtml is generating improper format url on blog homepage when ?amp is enabled

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4865]
AMPhtml is generating an improper format URL on the blog homepage when ?amp is enabled

https://www.directoriocubano.info/?amp/&amp

http://localhost/key/?amp/&amp

https://secure.helpscout.net/conversation/1364187004/169994?folderId=2632030

it is recreated in the internal system as well.

Ref: https://monosnap.com/file/vo5dQd7nsJX3hvQSAKf2Sg0TVm2aMU

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.71.2
