### ISSUE TITLE
'-' symbol is appearing on title tag.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4866]
Ref:https://secure.helpscout.net/conversation/1349518039/166967?folderId=2770543
Screenshots:https://prnt.sc/w11287

https://monosnap.com/file/P1BQogjVanbr1wQubDkkg8roVSn29a

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.73
