### ISSUE TITLE
Update to AMP Version 1.0.71.2 failed and caused website outage

### ISSUE THREAD

**Issue by TheMout** [ahmedkaludi/accelerated-mobile-pages#4870]
Hello,

Updated AMP to Version 1.0.71.2 and the update failed which caused website to become unavailable. Had to log back into admin area using recovery mode and to deactivate AMP plugin. Error is:

Version 1.0.71.2 | By Ahmed Kaludi, Mohammed Kaludi | View details
 This plugin failed to load properly and is paused during recovery mode.

An error of type E_COMPILE_ERROR was caused in line 803 of the file /home2/themoutn/domains/energyselectcontractors.com/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php. Error message: require(): Failed opening required '/home2/themoutn/domains/energyselectcontractors.com/public_html/wp-content/plugins/accelerated-mobile-pages//install/index.php' (include_path='.:/opt/alt/php74/usr/share/pear')

Currently, all AMP pages are indexed and now unavailable. Will likely start seeing "mobility" errors in Google soon. Please help to resolve as soon as possible. Much appreciated.

**Comment by Zabi09** [comment]
@TheMout The error seems to be caused by a missing file in our plugin while updating on your website, Kindly delete our plugin folder through FTP or c-panel, and do a clean reinstall and I hope your issue will be fixed and if not do let us know and we are here to help.

**Comment by MohammedKaludi** [comment]
@TheMout Were you able to resolve the issue as Zabi suggested? or you are still facing the issue?

**Comment by TheMout** [comment]
Hello,

I deleted the plugin through the WP Admin panel and checked in CPanel file manager but did not find this pugin directory in wp-content/plugins folder. Next, I added the plugin back and all appears to be fine now. At current version and appears to be fully activated without any issues. Thanks.

**Comment by TheMout** [comment]
Issue resolved. Thanks.
