### ISSUE TITLE
Facebook page embed fails

### ISSUE THREAD

**Issue by illord** [ahmedkaludi/accelerated-mobile-pages#4871]
Embedding a Facebook page results in this error:
"This Facebook post is no longer available. It may have been removed, or the privacy settings of the post may have changed"

Digging in to it, I found this patch : https://github.com/ampproject/amp-wp/blob/024e450798c35a89c3390c410ab42522a924f712/includes/embeds/class-amp-facebook-embed.php#L97-L136

I was able to fix the issue by editing accelerated-mobile-pages/includes/vendor/amp/includes/embeds/class-amp-facebook-embed.php and changing all the amp-facebook to amp-facebook-page

Of course now all FB shares are handled as amp-facebook-page so this does not work for everyone.
I would still like to point out this bug and how it can be fixed.

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.72 update

**Comment by absentio** [comment]
**"Of course now all FB shares are handled as amp-facebook-page so this does not work for everyone."** @Zabi09 that's the problem behind this patch. Facebook shares(post,videos) are handled as Facebook page.
