### ISSUE TITLE
Referenced AMP URL is self-canonical AMP while using  All in One Seo 

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4873]
While using All in one seo, amp pages and post are being self-canonical.
WordPress ref: https://wordpress.org/support/topic/referenced-amp-url-is-self-canonical-amp-9/
Localhost screenshot: https://prnt.sc/w2c2fg

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.72 update
