### ISSUE TITLE
GDPR strings are not getting translated when WPML is used.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4874]
1) User adding GDPR cookies content on his AMP site but the user is unable to translate GDPR information in AMP.

Video: https://www.youtube.com/watch?v=ZE15IV0tAJ0&feature=youtu.be

Tested in Cloudways unable to fetch any GDPR related string translation fields.

Ref Ticket:
https://secure.helpscout.net/conversation/1324910223/162314?folderId=3126461#thread-3813476271

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.73
