### ISSUE TITLE
AMP Browser caching policy

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4876]
WordPress ref :  https://wordpress.org/support/topic/browser-caching-policy-2/

**Comment by MohammedKaludi** [comment]
Ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.73

**Comment by Zabi09** [comment]
The user is saying - 
1 - The caching policy for the static files only and never for text/html content
2 - Removing ExpiresDefault line ensure strictness in caching policy, prevents caching of unknown files

Both are valid points, So need to remove that from our plugin

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.3
