### ISSUE TITLE
Copy protection / disable right click for amp pages

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4877]
WordPress ref: https://wordpress.org/support/topic/copy-protection-disable-right-click-for-amp-pages-2/.

**Comment by MohammedKaludi** [comment]
escaping again?

**Comment by thegulshankumar** [comment]
This can help in disabling text-selection.

```
.*
{
-moz-user-select:none;
-webkit-user-select:none;
cursor: default;
}
html
{
-webkit-touch-callout: none;
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
-webkit-tap-highlight-color: rgba(0,0,0,0);
}
```
Inspired by WP Content Copy Protection & No Right Click plugin

**Comment by Zabi09** [comment]
@thegulshankumar No need to add all these CSS you can disable the right-click by just simply adding  - `<body oncontextmenu="return false">` which we have added and you just need to enable the option of "Disable Right Click" in advance settings to disable the right-click in AMP

Is this method not working on your end? Please let us know

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.3

**Comment by timothiex** [comment]
I'm not using AMP, so.. how do i disable right click on my HTML page?
