### ISSUE TITLE
Reader Mode/Reader View

### ISSUE THREAD

**Issue by mmprep** [ahmedkaludi/accelerated-mobile-pages#4880]
Just imagine this scenario. I have posts that, in one way or another, require registration for their viewing. But in Reader Mode/Reader View of Safari and Firefox browsers on mobile devices and on desktops, this restriction is removed. In addition, all advertising is cut out. Moreover, Reader View can be enabled by default for all opened posts. And there are Reader View extensions for the Chrome browser.

Question/Improvement: Can I completely disable Reader View/Reader Mode in AMP pages?

By the way, some sites do not allow you to view their content in Reader View mode.

**Comment by Zabi09** [comment]
@mmprep can you please send me your website URL where you have reader view/reader mode, so I will check and let you know the solution

**Comment by mmprep** [comment]
https://mosmedpreparaty.ru/

**Comment by mmprep** [comment]
@Zabi09 https://mosmedpreparaty.ru/

**Comment by Zabi09** [comment]
Can you please send me the URL where it requires registration for their viewing So that I can check it and let you know

**Comment by mmprep** [comment]
Thank you!

Hear you are:

https://mosmedpreparaty.ru/news/21952
https://mosmedpreparaty.ru/news/21949

**Comment by Zabi09** [comment]
Have you removed the AMP on the above posts - https://mosmedpreparaty.ru/articles/21992?amp as I am checking your other posts AMP is present - https://mosmedpreparaty.ru/articles/21992?amp but did not find any AMP on those posts,

Will you please enable it so that I can check it in some browsers and find a solution for you

**Comment by Zabi09** [comment]
@mmprep Will you please help us to recreate your issue on our end so that we can fix it as soon as possible

**Comment by Zabi09** [comment]
@mmprep Please help us to recreate the issue on our end So that we can fix it ASAP

**Comment by Zabi09** [comment]
Github is for recreatable issues, for technical support, please contact on site
