### ISSUE TITLE
I'm having problems with .WEBP images - When will you support webp images?

### ISSUE THREAD

**Issue by EltonDanielOliv** [ahmedkaludi/accelerated-mobile-pages#4881]
To make my site even faster and smaller, I am changing my images to images in webp format, however, the AMPForWP plugin does not display images in the correct size, and [PageSpeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fandroidfinal.com%2F&tab=mobile) is capturing images in inappropriate formats.

I need you to fix this, please!

I love your work, congratulations on everything! <3

**Comment by Zabi09** [comment]
We are currently having support for webp format in some of the plugins like imagify, Ewww, and webp express etc. May I know which webp plugin you are using for your normal website,

Please let us know So that we can build compatibility with that plugin too in AMP pages

**Comment by EltonDanielOliv** [comment]
I am not using any plugin, I am sending the images in webp format directly
to my wordpress, as if it were a png image.

I did this to avoid using too many plugins.

https://androidfinal.com/

Em sáb, 19 de dez de 2020 07:18, Syed Zabiuddin <notifications@github.com>
escreveu:

**Comment by Zabi09** [comment]
@EltonDanielOliv Thank you for sharing the URL and I have checked the images on your website and found that on your homepage you have 10 images and out of that 7 images are appearing in webp only and 3 are appearing in jpg format - https://prnt.sc/w6wdkb

Will you please check whether you have created the webp format for those images also because when I check it by replacing jpg with wepb then there are no images available.

**Comment by EltonDanielOliv** [comment]
Yes, indeed.  I am gradually replacing the jpg to webp images.  I am
replaced one by one.

Em seg, 21 de dez de 2020 02:13, Syed Zabiuddin <notifications@github.com>
escreveu:

**Comment by EltonDanielOliv** [comment]
I am converting the images from jpg to webp manually, one by one.  Then the
process takes a little time.  But I believe that next year I will have most
webp images.

Em seg, 21 de dez de 2020 13:41, Elton Dx <eltondaniel16@gmail.com>
escreveu:

**Comment by Zabi09** [comment]
Let's take an example of the first 2 images of your blog - https://prnt.sc/w7tfi5 - on the first image webp format is present in the image then it automatically adding a webp to it and for the 2nd image there is no webp format available and if I manually add the .webp also there is still no image available that's the reason its showing jpg

Once your process is completed and all your images have webp then it will show webp only.

and if you have any questions then let me know

**Comment by Zabi09** [comment]
@EltonDanielOliv is your issue fixed? Can I close this ticket?

**Comment by EltonDanielOliv** [comment]
Yes

Em sáb, 2 de jan de 2021 06:13, Syed Zabiuddin <notifications@github.com>
escreveu:
