### ISSUE TITLE
Validation error :The tag 'area' is disallowed.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#4882]
Ref: https://secure.helpscout.net/conversation/1374013261/171413?folderId=2770543

To recreate this issue, add below the code on your local.

map <area title="Anthem Homes for Sale" alt="Anthem Homes for Sale" coords="93,13,182,60" shape="rect" href="https://www.theholmgroupaz.com/anthem-homes-for-sale-2/" target="" /> <area title="Desert Hills Homes for Sale" alt="Desert Hills Homes for Sale" coords="109,69,159,89" shape="rect" href="https://www.theholmgroupaz.com/desert-hills-homes-for-sale-3/" target="" /></map>

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.73
