### ISSUE TITLE
"Custom JS is not allowed" validation error issue has been noticed when ALL in one SEO pro plugin is active.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4883]
"Custom JS is not allowed" validation error issue has been noticed when ALL in one SEO pro plugin is active.

I was able to recreate the same on the localhost. 

Ref: https://secure.helpscout.net/conversation/1359037460/168709?folderId=3514643

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.73 update
