### ISSUE TITLE
The yoast meta title is not reflecting in the title tag after modifications

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4885]
Ref: https://secure.helpscout.net/conversation/1312292479/159851?folderId=2770545

When the user is modifying the meta title from the Yoast editor (https://prnt.sc/w8fc3p), the changes are not reflecting in the title tag (https://prnt.sc/w8fdw3).

The title tag is taking the default title of the post with the site title of the Wordpress settings. The user does not want the site title settings because, in the search result, it is showing the site title of the Wordpress for every post.

Screenshot: https://prnt.sc/w7s41u

The issue is not occurring on the local. The issue is only the user end.

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.74
