### ISSUE TITLE
AMP pages returns 404 ever and again

### ISSUE THREAD

**Issue by mmazurekdev** [ahmedkaludi/accelerated-mobile-pages#4888]
Hi, 
ever and again my amp pages return 404 error. I must deactivate and activate this plugin. 

For cache I have Fast Velocity Minify and WP Super Cache. I have changed the ttl for cache in wp super cache to 72h but it doesn't change anything. 

AMP 1.0.73, Wordpress 5.6, PHP 7.2, nginx/1.16.1, 5.5.65-MariaDB + Cloudflare. I have noticed this for the first time at 23.12.2020.

I'm not sure is this a amp problem, but I will be very gratefull if someone could help me.

**Comment by Zabi09** [comment]
Hi @mmazurekdev,

I have checked your website homepage and also some posts and the AMP is working fine on https://mmazurek.dev/amp/ and https://mmazurek.dev/redis-i-python-dobrze-dobrana-para-10/amp/

Can you send me the exact URL where you have 404 for AMP pages so that I can check once and help you to fix it

**Comment by mmazurekdev** [comment]
@Zabi09 when you was checking my website it was working ok. Try again, now this two URLs result in 404. I will not repait it (deactivate and activate plugin)

**Comment by Zabi09** [comment]
@mmazurekdev We are extremely sorry for this and this is a very strange issue which is occurring on your website.

Will you please change the endpoint from '/amp' to '?amp' by following this - https://ampforwp.com/tutorials/article/how-to-change-end-point-to-amp-in-amp/ and check once it's working fine or not.

**Comment by mmazurekdev** [comment]
@Zabi09 I have noticed that saving changes under permalinks option cause the pages appear! Maybe it will be helpfull. Of course I will change to "?amp" style and I will give you a feedback.

**Comment by Zabi09** [comment]
@mmazurekdev I have checked your website now and it is working fine at the moment and will monitor it for 2-3 more days and if everything works as expected then will close this ticket.

**Comment by Zabi09** [comment]
Everything is working fine, So closing the ticket
