### ISSUE TITLE
The "Advertising" section is displaying blank in the AMP option panel when the " Ads for WP" plugin is activated.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4889]
The "Advertising" section is displaying blank in the AMP option panel. When the " Ads for WP" plugin is activated.

Ref screenshot: https://prnt.sc/wfrkjl
local screenshot: https://prnt.sc/wfrku5

Ref: https://secure.helpscout.net/conversation/1381234895/172674?folderId=3575684

**Comment by Zabi09** [comment]
Pushed in 1.0.75
