### ISSUE TITLE
Disqus constant is missing from accelerated-moblie-pages.php

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#489]
Disqus constant is missing from accelerated-moblie-pages.php

is missing 

AMPFORWP_DISQUS_URL

**Comment by nicholasgriffintn** [comment]
I'm pretty interested in this, commenting for updates.

**Comment by ahmedkaludi** [comment]
Disqus was added properly in the latest update.
