### ISSUE TITLE
AMP Page Builder not working on the pages and posts except the homepage

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4890]
Ref: https://secure.helpscout.net/conversation/1383293379/173037?folderId=2770545

When the user is creating any pages or posts using the AMP Page Builder, the contents showing on the AMP is not related to the AMP Page Builder. The contents are showing of the classic editor.

The issue is recreating on the local after importing the AMP setup of the user but after disabling each and every option, the issue was still there.

URL: https://30minutedpfclean.syncwin.dev/about/amp/

**Comment by Zabi09** [comment]
To recreate enable this option - Change Pagination Links to /amp

**Comment by Zabi09** [comment]
Pushed in 1.0.75
