### ISSUE TITLE
Why are my Website pages not indexed ofren with the AMP status?

### ISSUE THREAD

**Issue by Empathyfine** [ahmedkaludi/accelerated-mobile-pages#4891]
Please how can I get more of my website pages indexed more with the AMP status.

I noticed that a friend who uses another AMP plugin gets his pages easily indexed with the AMP status, but not so with me using AMP for WP.

Once he publishes a post, in a few days it's already showing AMP badge status in search result, but such does not happen with my own pages where I use the AMP for WP.

Please @Zabi09  and @MohammedKaludi  what do you have to say about this? I need my pages indexed more for AMP in search results.  What can I do about this? Is there any configuration I need to do in my AMP for WP plugin??

Please share your recommendations. Thanks!

**Comment by Zabi09** [comment]
@Empathyfine can you please send me the link of your website, So that I can check it once and let you know

**Comment by Empathyfine** [comment]
@Zabi09 here is the link to my website fanslite.com

**Comment by Zabi09** [comment]
I have checked your website homepage and also the latest post and both are indexed in Google.
Homepage - https://prnt.sc/whhf0j
Latest Post - https://prnt.sc/whhgts

Actually, the indexing is done by Google bots and as far as the website is concern everything is fine

**Comment by Empathyfine** [comment]
@Zabi09 thanks for your feedback. Now that you have said, it's okay. Glad to know there's no problem on my website and AMP for WP plugin end. Thanks once more!
