### ISSUE TITLE
p tags getting stripped when Change Pagination Links to /amp option is active.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#4892]
If we enable Change Pagination Links to /amp option then it is striping p tags from the content.
Ref: https://secure.helpscout.net/conversation/1376621091/171852?folderId=2770543

**Comment by MohammedKaludi** [comment]
This is not a correct fix.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.5
