### ISSUE TITLE
Swift Theme 2nd header menu aligned towards right: conflict with polylang plugin

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4893]
Menu in header 2 of swift theme is aligned to right while polylang plugin is activate.

WordPress Ref: https://wordpress.org/support/topic/header-menu-location-problem-swift-theme/
Localhost ref: https://prnt.sc/wi2mh7

**Comment by Zabi09** [comment]
Pushed in 1.0.75
