### ISSUE TITLE
Youtube videos aren't loading on the AMP when it is being added via the Thrive theme builder. 

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4895]
Youtube videos aren't loading on the AMP when it is being added via the Thrive theme builder. 
The iframe isn't being generated on the AMP pages/posts.

Ref: https://secure.helpscout.net/conversation/1365270592/170145?folderId=3514643

**Comment by Zabi09** [comment]
Working fine on our end so fixed by creating a custom plugin so closing the ticket
