### ISSUE TITLE
A number of unnecessary warnings and notices

### ISSUE THREAD

**Issue by papyon2016** [ahmedkaludi/accelerated-mobile-pages#4896]
Hi
We encountered a number of warnings and notices in the code and would like to have them solved. I have the code too, if you could just merge them for future updates:

/accelerated-mobile-pages/components/gdpr/gdpr.php
Line 33 should become:
`$more_info = isset($gdpr_text['more_info']) ? $gdpr_text['more_info'] : "";`

author-box.php:
in some scenarios, $post_author is not defined. I added the following code on line 12:
```
if(empty($post_author))
  return;
```

Thanks!

**Comment by Zabi09** [comment]
@papyon2016 Thank you for helping us to improve our plugin, I have added the code in our plugin and we will push it in our next update

**Comment by Zabi09** [comment]
Pushed in 1.0.75
