### ISSUE TITLE
Need help in getting AMP URL

### ISSUE THREAD

**Issue by thegulshankumar** [ahmedkaludi/accelerated-mobile-pages#4897]
Suppose a blog use AMP for WP plugin.

In PHP, How do I get AMP version permalink which generally appear with rel="amphtml" for WordPress its home, post, page, tag, cat, etc

Dont want to use arbitrary(?amp or /amp/) something without validating its existance 

Thanks in advanced

**Comment by thegulshankumar** [comment]
`amp_get_permalink( int $post_id )`

https://amp-wp.org/reference/function/amp_get_permalink/

Please confirm.

**Comment by Zabi09** [comment]
You can use this funtion - ampforwp_amphtml_generator() to get the AMP permalink,

**Comment by thegulshankumar** [comment]
Could you please link to some example or documentation for additional details? Thanks
