### ISSUE TITLE
The product and review schema markup added through the "Smart Mag Theme" is not showing in the AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4898]
Ref: https://secure.helpscout.net/conversation/1385729328/173450?folderId=2770545

The user is adding the Product and the review schema markup through the "Smart Mag Theme" editor (https://prnt.sc/wjplf2), is getting stripped in the AMP version.

NON AMP URL: https://www.meilleure-innovation.com/test-aspirateur-balai-hoover-free-500-hydro-plus/

AMP URL:  https://www.meilleure-innovation.com/test-aspirateur-balai-hoover-free-500-hydro-plus/amp/

These markups are not loading in the AMP:
https://prnt.sc/wkuvzr
https://prnt.sc/wkuwn2

**Comment by MohammedKaludi** [comment]
ready to merge

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.3
