### ISSUE TITLE
Imgur embed code is not working

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#4899]
Hello,

When using imgur embed, AMP plugin shows a black bar and not the video itself, try embeding anything moving in the post and you'll see on AMP

`<blockquote class="imgur-embed-pub" lang="en" data-id="a/AoMTUk5" data-context="false" ><a href="//imgur.com/a/AoMTUk5">We ride at dawn</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

**Comment by djixas** [comment]
Thanks. Is this coming to 1.0.75 this week??

**Comment by Zabi09** [comment]
@djixas Yes it will be coming in 1.0.75 next week

**Comment by Zabi09** [comment]
Pushed in 1.0.75
