### ISSUE TITLE
Divi Theme Compatibility (Shortcodes)

### ISSUE THREAD

**Issue by noinput** [ahmedkaludi/Accelerated-Mobile-Pages#49]
Thanks for this plugin, working great. We're using Divi by ElegantThemes.com and when viewing our pages via the Divi Builder, AMP pages are outputting shortcodes used at the top and bottom.

Live here: https://heelthatpain.com/heel-pain/heel-pain-exercises/?amp

and here's a screenshot: 
![screen shot 2016-08-17 at 9 59 17 pm](https://cloud.githubusercontent.com/assets/183243/17762484/e5ec124a-64c5-11e6-885c-458d44a20782.png)

Any ideas on how these can be filtered from the content output?

**Comment by ahmedkaludi** [comment]
Hey Jim @noinput 
I really love the idea of Divi support, and we want to do this, but honestly, this is not a simple task. It is complex and a big one. 

We're two developers, we dedicate 2 days out of our week to the AMP plugin development. I will try my best to look into adding Divi support next week and If it is easy, we will even start the implementation immediately.

If we cannot implement the Divi support right away then we will at least find an alternative solution to this problem. 

I hope it helps,

Regards,
Ahmed

**Comment by ahmedkaludi** [comment]
This was added after 0.8 update
