### ISSUE TITLE
'Srcset' attribute is not loading in amp-img from AMP page builder Category module.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4900]
Ref: https://secure.helpscout.net/conversation/1321213101/161604?folderId=2770543

Scenario:- in amp version srcset attribute not loading in amp-img,

Issue: https://askambulance.com/homepage/

Results in pagespeed insights giving opportunity for improving speed:-  https://prnt.sc/wkzxxu

**Comment by ajeetku** [comment]
Can use [`wp_get_attachment_image_srcset`](https://developer.wordpress.org/reference/functions/wp_get_attachment_image_srcset/) instead of adding just image, add propper srcset generated by WordPress

**Comment by Zabi09** [comment]
Pushed in 1.0.76
