### ISSUE TITLE
View Non-Amp Version link does not link to canonical page for /amp/x links

### ISSUE THREAD

**Issue by lucas-koehler** [ahmedkaludi/accelerated-mobile-pages#4901]
If a page xyz.com/mypage/amp/1 is opened and its canonical link correctly is xyz.com/mypage/, the "View Non-Amp Version" link points to xyz.com/mypage/1 instead of the canonical link xyz.com/mypage/. This leads to a 404 because xyz.com/mypage/1 does not exist.
Thereby, `1` can be replaced with any other number.

The page this occurs on also uses Yoast SEO.

**Comment by Zabi09** [comment]
I have tested your issue on my end - https://monosnap.com/file/I65OHjURNcSC0RG6SII0CyX13YO0nC but I am unable to understand your concern, Will you please help me with some URLs and screenshots so that I can understand and fix it

**Comment by lucas-koehler** [comment]
@Zabi09 Thanks for the fast reply :)

I'll gladly give you additional info.

In the image below you see web page `https://eclipsesource.com/products/amp/1` being opened. The canonical URL of this page is `https://eclipsesource.com/products/`. In the web page's source code this is specified via the `<link rel="canonical" href="https://eclipsesource.com/products/">` element (this is auto generated, not a custom solution).

Thus, my expectation would be that the `View Non-AMP Version` link points to `https://eclipsesource.com/products/`. However, currently the link points to `https://eclipsesource.com/products/1`, which is not defined.

![image](https://user-images.githubusercontent.com/6959840/104486028-7e436480-55cb-11eb-89dd-4327568f2add.png)


Is this description detailed enough or do you need more information?
Thanks for your help :)

**Comment by Zabi09** [comment]
@lucas-koehler thank you for explaining in details and I have fixed your issue now and it will be pushed in the next update

**Comment by lucas-koehler** [comment]
Great! Thanks for working on this so fast.

**Comment by Zabi09** [comment]
Pushed in 1.0.76
