### ISSUE TITLE
Facebook Video Embed not working

### ISSUE THREAD

**Issue by absentio** [ahmedkaludi/accelerated-mobile-pages#4903]
In AMP when a Facebook video is embedded inside a post it will not be processed as a Facebook post but as a Facebook Page. 
Test url: https://www.facebook.com/bbc/videos/751869069047498
AMPforWP Version 1.0.74

**Comment by Zabi09** [comment]
@absentio I have checked both the Facebook video and also the Facebook fan page on one of our testing server and both are working fine - https://magazine3.com/garage/dfsf/amp/

Will you please elaborate more about your issue so that we can understand it better and help you

**Comment by absentio** [comment]
Good morning. In my case, adding a video using the original plugin version available in Wordpress repository would result in this kind of representation:
![Schermata 2021-01-16 alle 12 44 28](https://user-images.githubusercontent.com/20925479/104810986-b24f9d00-57f8-11eb-928d-4e44a4f0d142.png)

Moreover If I modify the filed mentioned I can have the first representation on your link(the video player).

Sorry for my English but that's not my native language.

Thanks in advance.

**Comment by Zabi09** [comment]
Will you please tell me more about what you mean by "adding a video using the original plugin version"? Will you please help us o recreate the same issue on our end so that we can understand and help you

**Comment by Zabi09** [comment]
@absentio Please help us by which WordPress plugin you are adding the video? help us to recreate the same issue on our end so that we can help you.

**Comment by absentio** [comment]
> @absentio Please help us by which WordPress plugin you are adding the video? help us to recreate the same issue on our end so that we can help you.

I am adding the video by simply copying and paste the URL. I am also using the Custom Facebook Feed Pro plugin to improve embed because with latest update Wordpress and Facebook embedding aren't working that good anymore

**Comment by Zabi09** [comment]
@absentio I have checked the same by simply copying and paste the URL and it is working fine for us and previously Facebook page embed was not working and due to that, we have modified our code. you can check this GitHub ticket for more info - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4871

Can you send me the Custom Facebook Feed Pro plugin and will check it and let you know

**Comment by absentio** [comment]
> @absentio I have checked the same by simply copying and paste the URL and it is working fine for us and previously Facebook page embed was not working and due to that, we have modified our code. you can check this GitHub ticket for more info - #4871
> 
> Can you send me the Custom Facebook Feed Pro plugin and will check it and let you know

https://it.wordpress.org/plugins/custom-facebook-feed/

It's this one but the pro version. They do the same things, go into settings and then oEmbed

**Comment by Zabi09** [comment]
I have tested the same but I am unable to recreate your issue, Github is for recreatable issues, for technical support, please contact on site
