### ISSUE TITLE
BUG: <amp-brid-player> --> data-playlist gets removed automatically

### ISSUE THREAD

**Issue by seriou5** [ahmedkaludi/accelerated-mobile-pages#4906]
Hi, short issue + solution:

**Bug:** When using the <amp-brid-player> tag your plugin automatically removes the mandatory attribute "data-playlist" resulting in errors and not-working players.

**Solution:** in /accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-allowed-tags-generated.php on line 577 add 'mandatory' => true, 

**Version:** latest version 1.0.74

Maybe also other mandatory attributes are affected. Please see https://amp.dev/documentation/components/amp-brid-player/ for mandatory fields. ("Embed code must either have video, playlist or outstream attribute.")

Cheers

**Comment by Zabi09** [comment]
@seriou5 I have added the code which you have suggested and found that now it working properly and don't user data-video and data-playlist both at the same time and if you add then you will have a validation error saying - Mutually exclusive attributes encountered in tag 'amp-brid-player' - pick one of ['data-outstream', 'data-playlist', 'data-video'].

**Comment by Zabi09** [comment]
Pushed in 1.0.76
