### ISSUE TITLE
Tag base remove in AMP not working after 1.0.60

### ISSUE THREAD

**Issue by haynhat** [ahmedkaludi/accelerated-mobile-pages#4908]
Hi,

Tag base remove in AMP not working in the latest version 1.0.74 (category remove still working). I have tried to go back to the previous versions and see that 1.0.60 is working fine.

Can you please help to check it.

Thank you

**Comment by Zabi09** [comment]
@haynhat I have checked your issue and found that it was working perfectly till 1.0.66 on my end and the problem was from 1.0.67 Anyways I have fixed the issue Will you please add the commit and let us know if its been fixing on your end as well

**Comment by haynhat** [comment]
Hi @Zabi09 

Can you please guide me how to add the commit to this issue? I don't know

**Comment by Zabi09** [comment]
@haynhat we are going to push an update tomorrow just our plugin and it will be fixed

**Comment by Zabi09** [comment]
Pushed in 1.0.76

**Comment by haynhat** [comment]
Hi @Zabi09

I updated to 1.0.76 and the issue has been fixed

Thank you
