### ISSUE TITLE
Icons are not loading from the file.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4909]
https://trello.com/c/G2vUC3pG/2203-social-media-profile-telegram-is-not-appearing-even-it-is-selected
The icon Unicode starting from the letter "e" are not working with TreeShaking enabled.
https://prnt.sc/wtnsr9
https://prnt.sc/wtnw2o
Working:- https://prnt.sc/wtougx

**Comment by Zabi09** [comment]
That Unicode will work only for swift theme, not in design 1 2 3 or newspaper please add the icon in some another way or add the telegram icon by image check the method in  design 3 for more info and also it has nothing to do with tree shaking
