### ISSUE TITLE
Error : "Missing URL for attribute 'src' in tag 'amp-img'.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#4911]
Error : "Missing URL for attribute 'src' in tag 'amp-img'.

The above error is occurring when we use the ' src' image type in the post/page.

Ref of local:https://magazine3.com/garage/testttttt/amp/

Ref;https://secure.helpscout.net/conversation/1398555544/175974?folderId=3575684

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
READY TO MERGE

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.3
