### ISSUE TITLE
SEO Checklist banner integration

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#4912]
let's have a call for this integration

**Comment by romainbrabant** [comment]
Dear Ahmed,

We just created your Vanity URL: https://seobuddy.com/seo-checklist/magazine3 <- need to click twice to reset cookies
As well as you Discount Coupon: MAGAZINE3 (25% Off)

And this is the sticky bar your visitor will see:
![image](https://user-images.githubusercontent.com/49922765/105487873-1074f800-5cb1-11eb-958e-b266cf3fd963.png)

You can use the link above as "Affiliate Link" everything will be redirected and tracked properly.
I hope we'll both get great passive income from this.

For the record, this is what another WP Plugin Developer is doing on the account dashboard alert today:

![image](https://user-images.githubusercontent.com/49922765/105487888-18cd3300-5cb1-11eb-8fd8-d3eb9db2684b.png)

If you have any questions, just let me know I'm here to help.

**Comment by Zabi09** [comment]
@romainbrabant I have added it, Will you please check it once - https://prnt.sc/xhxaik and tell me how it is looking?

**Comment by romainbrabant** [comment]
It looks awesome, very well done.

**Comment by Zabi09** [comment]
Pushed in 1.0.76
