### ISSUE TITLE
Related posts are not showing correctly for the recipes

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4915]
Ref: https://secure.helpscout.net/conversation/1164869093/129784?folderId=2770545

When the user selects the categories in the single settings of the related post, the user is getting the same related posts for every posts.

URL: https://tastesofhealth.eu/recipe/double-chocolate-cake-chocolate-mousse-cake/

https://prnt.sc/xr1r49

The issue is not recreating on the local.

The user is using the WP Ultimate recipe plugin.

**Comment by Zabi09** [comment]
Going to get fixed in - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4300
