### ISSUE TITLE
Comment button has Wrong URL

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#492]
User says: 
https://www.statistikian.com/2017/02/metode-penelitian.html, Still not resolve... if the my visitors click the button "leave Comments", page reload, so my visitor cannot leave comments on my website. (I'll have been enabling this AMP redirection since a few minute ago until two hours from now. Please check again...

Check the issue and fix it ASAP.

**Comment by khaledMohammed000** [comment]
when clicked on leave a comment button it properly redirects to the users home page

**Comment by khaledMohammed000** [comment]
tested several times......working wonderfully
