### ISSUE TITLE
Fatal error on bbpress profile page.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4922]
Fatal error: Cannot redeclare ampforwp_sanitize_archive_desc() (previously declared in /home/fishingmag/public_html/wp-content/plugins/accelerated-mobile-pages/components/components-core.php:319) in /home/fishingmag/public_html/wp-content/plugins/accelerated-mobile-pages/components/components-core.php on line 318

I have made changes in the bbpress extension. This error needs to be fixed.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.1
