### ISSUE TITLE
The wrong breadcrumb links are generating for the posts having multiple categories and if YOAST plugin is active

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4923]
Ref: https://secure.helpscout.net/conversation/1401946860/176470?folderId=2770545

If a post contains multiple categories(https://prnt.sc/yxka7f) and if the Yoast plugin is active, then the incorrect breadcrumb links are generating for the post categories (https://prnt.sc/yxkn9k).

The user is not creating the breadcrumb from the YOAST plugin.

URL:https://s2.diyarbakirescort.com/damak-tadinizi-yenileten-eskort-hulya/

It is creating the malformed URL validation issue when the user is activating the "Subdomain Endpoints for AMP" plugin.
Screenshot: https://prnt.sc/yxjzig

If the post has only one category, it is generating correct URL (https://prnt.sc/yxl42o)

**Comment by Zabi09** [comment]
Pushed in 1.0.76.1
