### ISSUE TITLE
Debug warnings

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#4924]
Undefined variable: is_script in plugins\accelerated-mobile-pages\templates\features.php on line 8421

Notice: Undefined index: in plugins\accelerated-mobile-pages\templates\features.php on line 5421

Notice: Trying to get property of non-object in plugins\accelerated-mobile-pages\templates\features.php on line 5421

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.3
