### ISSUE TITLE
Fatal conflict with Yoast Premium

### ISSUE THREAD

**Issue by Djennez** [ahmedkaludi/accelerated-mobile-pages#4926]
Hi there!

We've released Yoast (premium 15.8) and noticed some fatal errors coming in through our support department. These fatals would only occur with Yoast Premium 15.8 and AMP for WP active, and Yoast free installed (but not active).

```
Fatal error: Cannot declare class WPSEO_Meta_Columns, because the name is already in use in /home/xxxx/public_html/test/wp-content/plugins/wordpress-seo/admin/class-meta-columns.php on line 15
```

This is likely due to your inclusion logic in https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/a316edb1a04ff6ed3994f7c57314ce7b18e32bdd/includes/thirdparty-compatibility.php#L1151-L1174

We are currently transitioning our Premium plugin to an addon, rather than a standalone plugin. Currently we still include free with Premium, but as a dependency, rather than part of the base code. Eventually that will be removed as well and it will be a complete addon to Yoast free.

Could you have a look at fixing this inclusion logic? Our [developer docs](https://developer.yoast.com/customization/apis/surfaces-api#for-other-pages) should provide some more efficient code to do what you want to do. If you need any assistance, please feel free to reach out.

**Comment by Zabi09** [comment]
@Djennez can you please send me the zip file of Yoast Premium 15.8 on team@ampforwp.com, So that I can check it out and fix it as soon as possible.

**Comment by Djennez** [comment]
@Zabi09 thanks for the followup! I have sent you an e-mail with the latest version attached.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.1
