### ISSUE TITLE
AMP for WP is getting slower and slower

### ISSUE THREAD

**Issue by djixas** [ahmedkaludi/accelerated-mobile-pages#4928]
Hello,

This was an issue for a while now as with every update new features / codes  are thrown into the mix but the latest upgrade that we did on multiple blogs was a rather meaningful one, I skip some versions to see a "more bug fix" focused release so the last one I did is 1.0.69.1 to > 1.0.76

Results after cache was warmed up, etc. This is on **multiple sites, multiple page speed test tools, identical issue, no exceptions, always slower**, only showing 3 just to prove my point, with and without clouidflare DNS (depended on site)

https://www.airytea.com/blog/how-to-brew-the-best-cup-of-tea/amp/

GTMETRIX / PAGESPEED / PINGDOM

1.0.69.1 vs 1.0.76
LCP: 474ms
**LCP: 0.6s**

Total Blocking Time 160ms
Total Blocking Time 180ms

Time to Interactive: 3.6s
Time to Interactive: 3.7s

AMP html code / start load time
280.7ms
**356.4ms**

**NEW GOOGLE PAGESPEED PERFORMANCE ERRORS ON ALL SITES**

> Minimize main-thread work 2.1 s
> Consider reducing the time spent parsing, compiling and executing JS. You may find delivering smaller JS payloads helps with this. Learn more
> Category
> Time Spent
> Script Evaluation
> 1,023 ms
> Style & Layout
> 464 ms
> Other
> 326 ms
> Rendering
> 156 ms
> Script Parsing & Compilation
> 83 ms
> Parse HTML & CSS
> 40 ms
> Garbage Collection
> 8 ms

Identical issues with

https://www.anglumokykla.lt/anglu-kalbos-mokytojos-patarimai/amp/

--

https://www.airyhair.com/blog/best-hair-extension-brands/amp/

https://gtmetrix.com/reports/www.airyhair.com/XEHJLNM3/
https://gtmetrix.com/reports/www.airyhair.com/HonVmnQ9/

GTMETRIX

LCP 0.9s
**LCP 1.1s**

AMP html code / start load time
347.1ms
**389.2ms**

PINGDOM
Load time 898 ms
https://tools.pingdom.com/#5de40f0538c00000

**Load time 1.61 ms** (due to WAIT time doubling after AMP update)
https://tools.pingdom.com/#5de40ffecd000000

**Comment by Zabi09** [comment]
@djixas I have checked your website - https://www.airytea.com/blog/how-to-brew-the-best-cup-of-tea/amp/ - in which you are using the latest version and in that, it's showing 90 but with different LCP, blocking time, etc.. - https://prnt.sc/zluzkv

Have you done any changes?

**Comment by MohammedKaludi** [comment]
@djixas any update?

**Comment by djixas** [comment]
Hi, I think it's getting closer to the previosu times, so maybe some extra cache was loaded after a week, but I'll keep on monitoring after the next buiild, thank you.
