### ISSUE TITLE
Need to an option in single page settings to hide the title.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4929]
As per the user scenario - on his single-page user is adding the title from the theme template.

Now Our plugin by default adding the title to a single page.

So they are two H1 tags generating on a single page - in order to overcome this, we need an option in single page settings to hide the title.
Screenshot: https://prnt.sc/z7np76

Ref Issue URL: https://pacificexpertsgaragedoor.com/services/24-hour-repair-service/amp/

Ref Ticket: https://secure.helpscout.net/conversation/1418070530/179507/

**Comment by MohammedKaludi** [comment]
Need to discuss.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.3
