### ISSUE TITLE
Screen size of module editing page in AMP page builder is getting narrowed when All in One SEO plugin is active

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#4930]
When the All in One SEO plugin is used with AMP, while editing a module in the AMP page builder, screen is narrowed.

Reference ticket: https://secure.helpscout.net/conversation/1427813046/181151?folderId=4074390
Local test snaps: without All in One SEO - https://prnt.sc/zyoqnj
with All in one SEO - https://prnt.sc/zyojy2

**Comment by Zabi09** [comment]
Pushed in 1.0.76.5
