### ISSUE TITLE
There is an issue with the Single post links in blog page which are generated without '/' at the end.

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#4932]
Here is the User scenario in detail:

The user is building a blog page by using AMP page builder categories blocks, now when we visit the page on all single post links generated without '/' at the end.

Ref Screenshot: https://prnt.sc/100ii8x

When we visit the single post '/' is added at the end of the URL.

Ref Screenshot: https://prnt.sc/100ikac

So we need to add '/' at the end of the single posts on the blog page.

Ref Ticket: https://secure.helpscout.net/conversation/1427749638/181150?folderId=4405906

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/878592ec2062d3469323cb9bc5019d5cbc060a88#diff-e05fa8765bb6894f7cebfdf82e79ba5dec4fd58cc02e82218f949b77f42456a8R403

remove from here and add a newline at the end like this:  ` $ampforwp_post_url = user_trailingslashit($ampforwp_post_url) ` to make sure that slash is removed after the whole url is build.

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.6
