### ISSUE TITLE
add options array for UX Builder compatibility

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#4933]

**Comment by MohammedKaludi** [comment]
variable name is incorrect:  `$AmpUxBuilderChecker`
check other names and add accordingly 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d44da7a6014ab25018174001f0969152764ca0cb#diff-fb0561b26123ffc0bf7f74172ae4a0e22fb2b3f8e879c874d011dfe48a1d45d8R7

**Comment by Zabi09** [comment]
Pushed in 1.0.76.5
