### ISSUE TITLE
Sticky social share bar icon colliding  Non-AMP version element : conflict with polylang plugin

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4935]
WordPress ref: https://wordpress.org/support/topic/sticky-social-share-bar-icon-not-aligned/
Localhost ref: https://prnt.sc/104idf8

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.6
