### ISSUE TITLE
Need to review the Truepush code and then implement it.

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4936]
Ref: https://secure.helpscout.net/conversation/1431404668/181721/

We need to review the Truepush code in and if everything is correct then we need to implement it in our AMP plugin.

The Truepush team did changes in two files for the AMp support. I have added the zip file of the two files in which they did the changes.
[code.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/6028872/code.zip)

**Comment by ahmedkaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.6
