### ISSUE TITLE
The JSON markup of the AMP Page Builder is breaking at user's end

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4937]
Ref: https://secure.helpscout.net/conversation/1426254542/180918?folderId=2770545

Screenshot: https://prnt.sc/105kbrm

The issue is occurring at the user's end only.

**Comment by ahmedkaludi** [comment]
Ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.6
