### ISSUE TITLE
Need to add connect the infinite scroll feature with tags

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4939]
Ref: https://secure.helpscout.net/conversation/1422902865/180293?folderId=2770545

The user wants to connect the infinite scroll feature for the single with tags. He also wants the option of "Set the no. post Limits" like mentioned in the screenshot:

https://prnt.sc/1068v6q

The user is adding this feature for the non-AMP by JNEWS Theme.

For example NON-AMP URL: https://www.rnbjunk.com/anne-marie-e-david-guetta-presentano-il-singolo-dont-leave-me-alone/

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.11
