### ISSUE TITLE
Youtube iframe not converting into tag, a 1000s of errors thrown in search console

### ISSUE THREAD

**Issue by amrushavishwanath** [ahmedkaludi/accelerated-mobile-pages#4941]
We use iframe code to embed youtube video and it does not convert to <amp-youtube> automatically on AMP page.

Is there any specific setting that is required to load AMP youtube JS and convert the iframe youtube embed to corresponding <amp-youtube> tage?

or we should code for it explicitly using a hook?

This is our current code for embedding youtube videos look like in page source: I just copy paste YouTube video links, video is showing but error comes in, iframe is same in amp

<div class=”embed-responsive embed-responsive-16by9″>
<iframe class=”embed-responsive-item” width=”560″ height=”315″ src=”VIDEO_CODE” frameborder=”0″ allowfullscreen></iframe>
</div>

**Comment by Zabi09** [comment]
@amrushavishwanath Will you please tell us exactly where you are adding this code?
if you adding in the WordPress editor or in the widgets section then it will work automatically.
Are you adding it through that or you are adding in any custom field?
Please let us know and also share your website URL so that we can check and let us know

**Comment by amrushavishwanath** [comment]
Hi.. I adding in a custom field and also checked by adding wordpress editor
also, both delivers same error..
https://wikinbio.com/tv-serial/paavam-ganesan/amp/ this is the error url
example...

**Comment by Zabi09** [comment]
@amrushavishwanath I have checked your website and found that the videos are appearing fine and also showing a valid AMP page

https://prnt.sc/10a1pdm
https://prnt.sc/10a1pow

Have you done any changes?

**Comment by amrushavishwanath** [comment]
Hi Sir,

The strange part is it works only fine in acf field, which I tested by
adding another field.. In wordpress editor and other fields it is not
working  . Still the errors building up in the search console, is there any
code to add to make it auto convert in all other fields, wordpress editor?

https://wikinbio.com/tv-serial/jijaji-chhat-par-koi-hai-tv-serial-cast-timings-story-episodes-videos-wiki/amp/
- here is the example

And one more issue which needs your help, how to adjust thumbnails of
recent post ?

https://imghostr.com/43424c_uf8 - you can see the difference of Recent
Posts and Related posts? and also all over my thumbnails has more height
than width. Can you please help me with his ?

Thanks In Advance.
Amrusha

**Comment by Zabi09** [comment]
@amrushavishwanath I have added the youtube video with both the methods on one of our testing server and it is working fine, See this - https://magazine3.com/garage/amrushavishwanath-video-test/amp/

And I have checked your website and found some classes like "flex-video flex-video-youtube"  and the iframe is being wrapped in this classes,

Are you using any plugin for adding the videos?

**Comment by amrushavishwanath** [comment]
No I'm not using any extra plugin, I use theme outspoken by mythemeshop.com.
and it doesn't makes issue in my other website.. Please give me a solution
or code to override this..

**Comment by Zabi09** [comment]
@amrushavishwanath Will you please create a video by showing us exactly how you are adding the video in WordPress so that we can also replicate the same on our end and once we find the exact issue/error then only we can give you a solution,

So please tell us the steps to recreate your issue and once we find the issue we will fix it ASAP

**Comment by Zabi09** [comment]
@amrushavishwanath will you please send us so that we can check and fix it

**Comment by amrushavishwanath** [comment]
Sure, will do that.

**Comment by Zabi09** [comment]
@amrushavishwanath We are still waiting on this issue

**Comment by amrushavishwanath** [comment]
Get Video Link Here,

https://drive.google.com/file/d/1GCn8NdZ83ab3_ZW67RWwAgiYRBn2YHM_/view?usp=sharing

**Comment by amrushavishwanath** [comment]
Hi Sorry for the delay, check attached video, hope you will understand
whats is happening...


https://drive.google.com/file/d/1GCn8NdZ83ab3_ZW67RWwAgiYRBn2YHM_/view?usp=sharing

**Comment by Zabi09** [comment]
@amrushavishwanath Thank you for sending the video and that's strange to see that and after seeing the video again I tried to recreate it but still, I am not able to do it.

Added - https://prnt.sc/10g0t6n
Output - https://prnt.sc/10g0tde
Sourcecode - https://monosnap.com/file/HCyYXsHbdTpMzZqVuRlqDzCUOCFBRi

Will you please deactivate all your plugins temporary and use any default theme (Twenty Twenty) etc and check once

**Comment by amrushavishwanath** [comment]
Actually, site is live now.. If I do this, not having confident to regain
as it now... No other way to do any overide code?

**Comment by Zabi09** [comment]
If we were able to recreate the issue then we could have fixed it by giving you the code. Can you please create a staging website same as the live website and on that staging website try to deactivate the plugins and check with the default WordPress theme and let us know

**Comment by Zabi09** [comment]
@amrushavishwanath any update?

**Comment by Zabi09** [comment]
@amrushavishwanath Will you please send me the outspoken by mythemeshop theme, So that I can check it on my end and fix it as soon as possible

**Comment by amrushavishwanath** [comment]
Sure, will do that.

**Comment by amrushavishwanath** [comment]
Hi, here with attached theme files ..
 mts_outspoken.zip
<https://drive.google.com/file/d/1ot2nxeawaNfHlY3pP8idU5Guy46IH__k/view?usp=drive_web>

**Comment by amrushavishwanath** [comment]
FYI - Drive Link -
https://drive.google.com/file/d/1ot2nxeawaNfHlY3pP8idU5Guy46IH__k/view?usp=sharing

**Comment by Zabi09** [comment]
@amrushavishwanath I have added the theme but I am not able to activate it, Please check the video - https://we.tl/t-gSRHlmCBab

**Comment by amrushavishwanath** [comment]
Just skp the plugin...

**Comment by Zabi09** [comment]
@amrushavishwanath I have added the theme on one of our live websites and here are the steps which I have followed 

1 - Activated theme - https://prnt.sc/10o4se7
2 - Added Video - https://prnt.sc/10o4ur9

Here is the non-amp URL - http://magazine3.com/garage/video-test-amp/
Here is the AMP URL - http://magazine3.com/garage/video-test-amp/amp/

The video is displaying in AMP also or do I need to do anything else?

**Comment by Zabi09** [comment]
@amrushavishwanath any update on this?

**Comment by amrushavishwanath** [comment]
Hi..Yes, video is displaying, that's not matter.. It's not a valid amp
page, that's the issue.. Have you checked running test? Check attached
street shot for reference please...

**Comment by Zabi09** [comment]
@amrushavishwanath The website which I have to send you is our testing website and yes currently it is having errors because of some http because its a testing website and there is no error of youtube video, please check once

**Comment by Zabi09** [comment]
@amrushavishwanath We have added the theme on one of our live website and everything is working fine and Github is for tested and re-creatable bugs, for the technical issues, we will help you via website
