### ISSUE TITLE
The date format is not correct in the French format

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4943]
Ref: https://secure.helpscout.net/conversation/1436471808/182496?folderId=2770545

The % days ago is not converting into the correct French format. In the French, it should be in the format  "Il y a % jours". When the user is adding it in the "Text Date Format" section (https://prnt.sc/1086nuu), he is getting the output like this:
https://prnt.sc/1086p4x

The issue is also recreated on the local.

Steps to recreate:
1. In the WordPress general settings, Choose the default language as French. 
Screenshot: https://prnt.sc/1086r5v

2. Then goto AMP > Design > Date > Text Date Format > Enter " "Il y a % jours" > Save Changes.
Screenshot: https://prnt.sc/1086u74

**Comment by Zabi09** [comment]
Add in this way and it will work for sure

1 - https://prnt.sc/10b10se
2 - https://prnt.sc/10b10y5
3 - https://prnt.sc/10b116n
4 - https://prnt.sc/10b11dl

So closing the ticket
