### ISSUE TITLE
AMP Version Not Loading

### ISSUE THREAD

**Issue by acincyguy** [ahmedkaludi/accelerated-mobile-pages#4944]
I'm using AMP for WP. The AMP version is not appearing in the mobile version. Google Search Console says AMP is valid. PageSpeed Insights, WebPageTest, and GTmetrix all load the desktop version when asked to test mobile pages. I downgraded WP to version 5.5.3 to see if WP was causing the problem, but that didn't fix it.

**Comment by acincyguy** [comment]
I had the cache disabled on my server, but they did an upgrade that enabled it again without my knowledge. As soon as I cleared the cache everything returned to normal.

**Comment by Zabi09** [comment]
Can you tell us which server cache you are using? 

Will you please follow this tutorial and let us know if your issue is fixed or not - https://ampforwp.com/tutorials/article/how-to-redirect-all-mobile-visitors-to-amp/#here-is-the-list-of-cache-plugin-which-supports-the-mobile-redirection

**Comment by Zabi09** [comment]
@acincyguy Have you tried the above tutorial?

**Comment by Zabi09** [comment]
@acincyguy any update on this?

**Comment by acincyguy** [comment]
Syed:

 

Please see my second entry.

 

 

Mark Fleming

President

 



academyofbusinesstraining.com

We provide exceptional training for exceptional companies.

888-632-2093, Extension 703

Follow us on LinkedIn <https://www.linkedin.com/company/academy-of-business-training?trk=company_name>

**Comment by Zabi09** [comment]
@acincyguy Can you tell us which server cache you are using? Have you followed this tutorial - https://ampforwp.com/tutorials/article/how-to-redirect-all-mobile-visitors-to-amp/#here-is-the-list-of-cache-plugin-which-supports-the-mobile-redirection

**Comment by Zabi09** [comment]
@acincyguy any update on this?

**Comment by Zabi09** [comment]
Github is for tested and re-creatable bugs, for the technical issues, we will help you via website
