### ISSUE TITLE
Deprecated and Warning issues with PHP 8.02 and WordPress 5.6.2

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#4946]
Deprecated: Required parameter $is_script follows optional parameter $list in D:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\inc\class.redux_cdn.php on line 21
Deprecated: Required parameter $handle follows optional parameter $register in D:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\inc\class.redux_cdn.php on line 45
Deprecated: Required parameter $handle follows optional parameter $register in D:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\inc\class.redux_cdn.php on line 100
Deprecated: Required parameter $path follows optional parameter $expire in D:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\inc\class.redux_functions.php on line 54
Deprecated: Required parameter $data follows optional parameter $force in D:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\updater\update.php on line 260
Deprecated: Required parameter $wp_customize follows optional parameter $args in D:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\inc\extensions\customizer\extension_customizer.php on line 585
Deprecated: Required parameter $wp_customize follows optional parameter $args in D:\xampp\htdocs\wordpress\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\inc\extensions\customizer\extension_customizer.php on line 608
Warning: Only the first byte will be assigned to the string offset in D:\xampp\htdocs\wordpress\wp-includes\class.wp-scripts.php on line 492

**Comment by Sanjeevsetu** [comment]
To re create the issue follow steps

1. Install xampp with PHP v8.0.2
2. Install fresh WordPress v5.6.2
3. Activate AMPforWP

**Comment by Zabi09** [comment]
Pushed in 1.0.76.8
