### ISSUE TITLE
Background Video(youtube) loop is not working

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#4948]
Reference Ticket: https://secure.helpscout.net/conversation/1441460387/183308?folderId=1060556
Background Video youtube had a loop option but it is not working
Reference video: https://monosnap.com/file/fiV88hZby616sX46KBIpJxW1GQI4qV
Need to add loop option for Background Video (MP4).
Reference Screenshot: https://prnt.sc/10dgl3a

**Comment by Zabi09** [comment]
Pushed in 1.0.76.8
