### ISSUE TITLE
Need Compatibility for Add Widget After Content(plugin)

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#4949]
Reference Ticket: https://secure.helpscout.net/conversation/1434717389/182209?folderId=4409869
The user places the Category Menu inside the Add Widget After Content(Plugin) but Category Menu(show in the drop-down list) is not working. 
Reference Screenshot: 
Non-AMP: https://prnt.sc/10co75n    
Amp: https://prnt.sc/10co6ld    
Widget: https://prnt.sc/10co526

Add Widget After Content(Plugin) URL: https://wordpress.org/plugins/add-widget-after-content/

**Comment by Zabi09** [comment]
Pushed in 1.0.76.10
