### ISSUE TITLE
Captions are not working on Slideshow Module by Jetpack Plugin

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#4950]
Reference Ticket: https://secure.helpscout.net/conversation/1443416551/183941?folderId=4409869
Captions are not working on Slideshow Module by Jetpack plugin.

How to Re-Create the issue.
1. We have to install and activate the Jetpack Plugin.  https://prnt.sc/10doz1g
2. Select any Post or Create any post.
3. Select the SlideShow option like given in the ScreenShot  https://prnt.sc/10dp1qg
4. Add the photos with Captions. https://prnt.sc/10dp2rq
Reference Screenshot:
Non-Amp: https://prnt.sc/10dl41z
Amp: https://prnt.sc/10dl3hl

**Comment by Zabi09** [comment]
Pushed in 1.0.76.8
