### ISSUE TITLE
Need to add the Quantcast CMP (consent management platform) support 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4951]
Ref: https://secure.helpscout.net/conversation/1443955669/184054?folderId=2770545

The user requested to add "Quantcast CMP (consent management platform) support " in our AMP plugin. We need to first check whether the Quantcast CMP is providing the AMP Support or not.

If Quantcast CMP providing proper support for the AMP, then we need to implement it.

One ref URL: https://help.quantcast.com/hc/en-us/articles/360057007654-Quantcast-Choice-AMP-Implementation-Guide

**Comment by Sasirekhamarella** [comment]
This user is also using Consent Manager / Quantcast on his pages. 

Ticket: https://wordpress.org/support/topic/consent-manager-quantcast/

**Comment by sardarui** [comment]
Another user requesting the Quantcast CMP feature in our plugin.

Ref Ticket: https://secure.helpscout.net/conversation/1463684259/187702?folderId=3126461

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.13
