### ISSUE TITLE
Need to add srcset attribute to images when they are being added via AMP page builder(edit page section)

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4954]
Need to add srcset attribute to images when they are being added via AMP page builder(edit page section)
The images that are being added via page builder aren't being displayed in the appropriate sizes.
Screengrab for reference: https://monosnap.com/file/mvseNMhoZFZjqjaImIh1juJyQWLVIQ
Ref: https://secure.helpscout.net/conversation/1422680881/180260?folderId=3514643

**Comment by Zabi09** [comment]
Pushed in 1.0.76.8
