### ISSUE TITLE
Three amp issue

### ISSUE THREAD

**Issue by editinghero** [ahmedkaludi/accelerated-mobile-pages#4955]
"The author stylesheet specified in tag 'style amp-custom' is too long - the limit is 75000 bytes."

"The tag 'link rel=canonical' appears more than once in the document"

"Disallowed attribute or attribute value present in HTML tag."

Website link
https://gfx-eh.tech/
https://gfx-eh.tech/amp

Active plugin
1.Accelerated Mobile Pages
2.Advanced Editor Tools (previously TinyMCE Advanced)
3.Akismet Anti-Spam
4.AMP Blocks
5.AMP Cache
6.AMP Comments
7.AMP Layouts
8.AMP Rating
9.AMP Shortcodes Ultimate
10.AMP StoriesA
11.stra Bulk Edit
12.Astra Customizer Reset
13.Astra Pro
14.Astra Widgets
15.Cloudflare
16.Contact Form 7
17.Contact Form 7 for AMP
18.Custom Fonts
19.Customizer Search
20.Easy Table of Contents
21.EDD for AMP
22.Health Check & Troubleshooting
23.Insert Headers and Footers
24.Jetpack by WordPress.com	
25.Liveblog For AMP
26.OneSignal Push Notifications
27.Polls for AMP
28.Rank Math SEO PRO
29.Really Simple SSL pro
30.Reading Progress Bar for AMP
31.Shortcodes Ultimate
32.Site Kit by Google
33.Smush Pro
34.Starter Templates
35.Web Stories
36.Wp Polls

Some Issues link:-

https://search.google.com/test/amp?id=jp2KftDKIUyBitekbOiPLg

Some Issues :-

![Screenshot_20210311-092245](https://user-images.githubusercontent.com/69391940/110735887-adcfbf80-8250-11eb-8a75-79c43629ba8a.jpg)
![Screenshot_20210311-092251](https://user-images.githubusercontent.com/69391940/110735890-b0321980-8250-11eb-86ad-ccfacc4a8c95.jpg)
![Screenshot_20210311-092254](https://user-images.githubusercontent.com/69391940/110735893-b1634680-8250-11eb-8001-5e3b1bddb357.jpg)
![Screenshot_20210311-092257](https://user-images.githubusercontent.com/69391940/110735897-b1fbdd00-8250-11eb-8985-98363907d3e7.jpg)

Help my Clients site !!!!!!
Plz

**Comment by Zabi09** [comment]
@editinghero I have tested your website and found that your AMP homepage is valid without any errors but all your posts are invalid and that is due to a lot of CSS, in AMP only 75k CSS is allowed and when I check your website then almost 83K CSS is being loaded and due to that you are facing this error - https://search.google.com/test/amp?id=kpYdGtfxwU1cWKHCerlwVQ

I have seen a lot of CSS with the name of dem-graph, dem-results, dem-percent, etc, Can you tell me which plugin is adding this dem CSS and also I have seen so much of CSS with the AMP blocks. Are you using it? 

Please let me know

**Comment by editinghero** [comment]
I have installed AMP Blocks in my website but never used

**Comment by editinghero** [comment]
![Screenshot_20210311-182305](https://user-images.githubusercontent.com/69391940/110790271-dda1b600-8296-11eb-9fb8-4725b4119046.jpg)
I uninstalled it but wating for some reason on my website

**Comment by editinghero** [comment]
https://search.google.com/test/amp?id=pMpSk3p0nVcTnKmFW0P_Yg

No change

**Comment by Zabi09** [comment]
@editinghero Will you please clear the cache of the AMP Cache as I can still see the AMP block code on your pages, Please clear the cache and check once

**Comment by editinghero** [comment]
I just delete some extension and plugin & dose many settings and passed all issue but my money wasted on the extension purchase 😓😓😓 but no problem

**Comment by Zabi09** [comment]
@editinghero You no need to delete any extension and you only need to deactivate AMP Blocks as you are not using it and you just need to enable this option and hit save - https://prnt.sc/10jklj1 and then it will fix the errors,

Do it once and let us know

**Comment by Zabi09** [comment]
@editinghero Now all your pages are showing valid - https://search.google.com/test/amp?id=xcPc_RZfkmYIarhyPhQHOw

Will you please click on validate fix in search console and check once and do let us know

**Comment by editinghero** [comment]
Thanks you It is fixed now
