### ISSUE TITLE
Need to add compatibility with the Schema Pro FAQ

### ISSUE THREAD

**Issue by nakib4tech** [ahmedkaludi/accelerated-mobile-pages#4956]
I am adding FAQ schema to my articles using the Schema Pro plugin. 

The problem that its not render on AMP pages and Google Rich Results test does not showing the FAQ schema on my amp page.

Page in question: http://bit.ly/3t6OSU0

**Comment by Zabi09** [comment]
@nakib4tech Are you using our free Schema & Structured Data for WP & AMP plugin - https://wordpress.org/plugins/schema-and-structured-data-for-wp/

**Comment by nakib4tech** [comment]
No.

**Comment by Zabi09** [comment]
@nakib4tech We have created Schema & Structured Data for WP & AMP plugin for adding all the schema compatibilities, Will you please use that and check once

**Comment by nakib4tech** [comment]
@Zabi09 I am sorry, I stopped using it for about 1 year and started using Schema Pro as its lightweight and has minimal affect on Speed.

Any chance for allowing Schema Pro FAQ to rendering on AMP please?

**Comment by Zabi09** [comment]
@nakib4tech We have improved our Schema plugin a lot and now our schema plugin is far better than what it was previously, will you please check it out once and tell us about your feedback and I am sure you will not be disappointed and also can you send us the Schema Pro plugin so that we can check it once and add the compatibility for you,

**Comment by nakib4tech** [comment]
@Zabi09 Thank you, I am always promoting your products on my channel & blog. I have sent you the Schema pro by the Email. please check:)

**Comment by Zabi09** [comment]
@nakib4tech I have checked the schema pro and the FAQ schema is working fine with our AMPforWP plugin and here are the steps I have followed:
1 - Added FAQ - https://prnt.sc/10mxuyw
2 - Updated FAQ - https://prnt.sc/10mxwi4
3 - Able to see the FAQ in AMP source code as well - https://monosnap.com/file/ybcKExVtsNRXeZABft4H049S26tL1P

Will you please tell us exactly how you are adding it so that we can add it in that way and check

**Comment by nakib4tech** [comment]
@Zabi09 Dear Sir, Thank you for your reply.
I am adding FAQ schema using a FAQ block in the Gutenberg editor and not adding sitewide like you do.

Please just replicate these steps:
1. Edit any post using Gutenberg.
2. Add a FAQ block anywere inside the post.
3. Then, check and you will not see the FAQ markup in the amp page. Also, the layout of the FAQ will showing broken on AMP.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.10

**Comment by MohammedKaludi** [comment]
@nakib4tech Did the issue resolved after updating to the latest version of AMPforWP?

Waiting for your feedback.

**Comment by nakib4tech** [comment]
@MohammedKaludi 
No sir, you can see that your compatibility code is only for hidding FAQ's Icons.

But, the Schema markup (FAQ), is still not rendering on my AMP pages. And so Google is not showing rich snippet (FAQ) on mobile results.

**Comment by MohammedKaludi** [comment]
@Zabi09 please look into this.

**Comment by MohammedKaludi** [comment]
> @MohammedKaludi
> No sir, you can see that your compatibility code is only for hidding FAQ's Icons.
> 
> But, the Schema markup (FAQ), is still not rendering on my AMP pages. And so Google is not showing rich snippet (FAQ) on mobile results.

@Zabi09 I thought so. Do look into this.

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/3022caf011ed8a702183ec086d58145015aeb4ab#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580R9406
empty return will make the content empty. just return $content variable with it.

**Comment by nakib4tech** [comment]
@Zabi09 
Dear Sir, Thanks a lot for your hard work on this. I just updated to 1.0.76.14 and the code is now rendering in AMP. But there is some missing data and so the markup becomes invalid!

- Please check [this link](https://search.google.com/test/rich-results?hl=en&id=gb21UnjsbHjonWEojGuY_w) for my post in Google Rich Results Testing Tool.
- Below is a screenshot for the error (**Missing field "mainEntity"**): 

![Capture](https://user-images.githubusercontent.com/40723843/115976114-59b83a80-a573-11eb-9e9f-4aa5da67dfba.PNG)

**Comment by MohammedKaludi** [comment]
Ready for merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.17 
@nakib4tech please update the plugin to the latest version and let us know if the issue is resolved.

**Comment by nakib4tech** [comment]
@MohammedKaludi 
Sorry for the delay. Its working fine now and the schema markup is valid. Thanks a lot for your help:)
