### ISSUE TITLE
'Upgrade for Free' button in structured data settings is not working

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#4960]
Upgrade for Free button in structured data of AMP plugin is not working. It keeps on loading for a long time with no result. 
Local site references, https://prnt.sc/10o56ip, https://prnt.sc/10o5bze
Reference ticket, https://secure.helpscout.net/conversation/1455166836/186339?folderId=4074390

**Comment by Zabi09** [comment]
Pushed in 1.0.76.9
