### ISSUE TITLE
Docking functionality is not working for the amp-video type in mobile view

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4961]
https://secure.helpscout.net/conversation/1441819187/183343?folderId=2632030

https://staging-rapup.kinsta.cloud/2021/03/17/test-post/amp/

Docking functionality is not working for the amp-video type in mobile view. and for the amp-youtube element type, it is working fine.

There is an error in the console:

![image](https://user-images.githubusercontent.com/46995400/111609851-b8fe8e80-8800-11eb-8a57-f96b4eede230.png)

**Comment by Zabi09** [comment]
Pushed in 1.0.76.9
