### ISSUE TITLE
AMP page builder's "copy", and "settings" icons overlap. 

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/accelerated-mobile-pages#4962]
AMP page builder's "copy", and "settings" icons overlap in the edit section of the page. 
CSS causing the problem: .dashicons, .validate_icon{margin-left: -24px;
Ref: https://secure.helpscout.net/conversation/1454062615/186120?folderId=3514643

**Comment by DikshantJoshi** [comment]
A fix was released today. The current can be closed.

**Comment by Zabi09** [comment]
Fixed in AMP Opt-in Forms 1.9.39 Version
