### ISSUE TITLE
The AMP For WP option panel not saving due to redux plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4963]
Ref: https://secure.helpscout.net/conversation/1455472874/186406/

At the user's end the AMP For WP option panel not saving. The issue is occurring due to conflict with the redux plugin (https://it.wordpress.org/plugins/redux-framework/) 

The issue is not occurring on the local.

Screenshot: https://prnt.sc/10oy2or

**Comment by Zabi09** [comment]
Pushed in 1.0.76.9
