### ISSUE TITLE
Warnings appearing 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4966]
The warnings are in the attached text file.

[New Text Document.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/6181616/New.Text.Document.txt)

https://secure.helpscout.net/conversation/1460029028/187214?folderId=2632030

![image](https://user-images.githubusercontent.com/46995400/111980677-a780f380-8b2c-11eb-985b-bb581eb1605b.png)

**Comment by Zabi09** [comment]
It was due to some conflict in AMP options panel so deleted the plugin and installed it again and now everything is working fine, So closing the ticket
