### ISSUE TITLE
AMP menu automatically scrolls down to bottom in Design three

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4967]
Localhost ref: https://monosnap.com/direct/6tI0Fx6UFVIOPMVFiAZkvLpkG5aHHu
Helpscout ref: https://secure.helpscout.net/conversation/1451554280/185590?folderId=4473027

**Comment by MohammedKaludi** [comment]
ready to merge.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.11

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.076.14
