### ISSUE TITLE
Close button not visible in the menu for the Google Cached AMP Pages.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#4969]
Close button not visible in the menu for the Google Cached AMP Pages. The issue is encountering only when we search the website from google chrome.

Ref screenshot: https://prnt.sc/10u2l1y

Ref https://secure.helpscout.net/conversation/1460777234/187354?folderId=3575684

**Comment by Zabi09** [comment]
Pushed in 1.0.76.9
