### ISSUE TITLE
When Yoast SEO Multilingual is activated canonical link has getting generated addition http:// in the link

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4970]
https://secure.helpscout.net/conversation/1451431212/185493?folderId=2632030

When Yoast SEO Multilingual is activated canonical link has getting generated addition http:// in the link

For post and pages.

https://www.packshot-creator.com/360-photos-marketplaces/amp/

issue recreated in local as well.

<link rel="canonical" href="http://http://localhost/wp7/2021/03/24/yoasttest/" /> 

![image](https://user-images.githubusercontent.com/46995400/112334881-c8d71080-8ce1-11eb-9aec-8120ce20a696.png)

**Comment by Zabi09** [comment]
Pushed in 1.0.76.9
