### ISSUE TITLE
The incorrect excerpt details are showing for the custom front page if user is using the DIVI

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4972]
Ref: 
1. https://secure.helpscout.net/conversation/1427265871/181077?folderId=2770545

2. https://secure.helpscout.net/conversation/1436334252/182478?folderId=2632030

Steps to recreate:

1. Install the DIVI theme.
2. Create a page using Divi.
3. Use the blog module of the DIVI.
4. Select 3 or more posts in the module: https://prnt.sc/10w6a8j
5. For the latest post that you have selected, edit the posts and enter some excerpts.
Screenshot: https://prnt.sc/10w6cwj
6. Now select the page as the custom front page.
7. add some details in the Yoast meta excerpt:
Screenshot: https://prnt.sc/10w6goe

Now after viewing the AMP page the meta details that we have added in the YOAST are taking as the excerpt.
Screenshot:
Localhost:
NON AMP : https://prnt.sc/10w6myb
AMP: https://prnt.sc/10w6lbe

User's end:
URL: https://www.paoson.com/blog/?amp

The second user is using the Astra theme and facing the same issue.

We need to fix this issue urgently and also need to deploy the fix at the first user end.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.9
