### ISSUE TITLE
Issue with the facebook videos embedding in AMP.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#4973]
One of our users is trying to embed a Facebook video on one of his post but the video is not showing in AMP(Working perfectly in non-AMP).

Steps to recreate the issue:
- Please copy the below video URL and paste it on any editor(Gutenberg/classic).
URL: https://www.facebook.com/GeekCulture/posts/3734789059943382 or else any Facebook video
Note: your testing environment should serve on "https:" 
- Hit save & check it in both AMP & non-AMP.

Ref Ticket: https://secure.helpscout.net/conversation/1451559727/185591?folderId=3126461
Ref post URL: https://geekculture.co/the-long-awaited-dynasty-warriors-movie-starring-louis-koo-finally-has-a-full-trailer/amp

**Comment by Zabi09** [comment]
Pushed in 1.0.76.9
