### ISSUE TITLE
Automatic redirect from the AMP version to non-amp version when access is from desktop.

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#4975]
User scenario: 

If someone shares the amp link and I try to access it from the desktop, I’ll find AMP version on the desktop. Is there a way to avoid the Amp version from the desktop, even if I received an amp link?

He is looking for is an automatic redirect from the AMP version to non-amp version when access is from desktop.

Ref ticket: https://wordpress.org/support/topic/non-amp-version-in-desktop/

**Comment by Zabi09** [comment]
Pushed in 1.0.76.10
