### ISSUE TITLE
“Search Bar” Close Button is hidden behind the Google AMP Bar/Header

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#4977]
The user website “Search Bar” Close Button is hidden behind the Google AMP Bar/Header.

Ref screenshot:  https://prnt.sc/114l25z
Ref ticket: https://wordpress.org/support/topic/search-close-button-not-visible-from-google-cached-amp-pages/

**Comment by Zabi09** [comment]
Pushed in 1.0.76.10
