### ISSUE TITLE
Google Fonts are not getting saved while using Safari

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#4978]
While it works with Chrome, Google Font settings are not getting saved when done using Safari.
Reference ticket - https://secure.helpscout.net/conversation/1470102991/188608?folderId=4074390
Screenshot - https://prnt.sc/115l2a4
A clear video of the user's observation is available in the helpscout ticket. 
Recurred in our localhost - https://take.ms/wv0o7

**Comment by MohammedKaludi** [comment]
Ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.4 update
