### ISSUE TITLE
Need an option to add Breadcrumbs through Blog

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#4979]
Need a setting to create breadcrumbs through the blog of a site like we currently have it through categories and tags. 
Example: Home > Blog > Current post
Reference ticket - https://secure.helpscout.net/conversation/1469674288/188548?folderId=4074390
Url - https://villaraffaelli.it/idee-vacanza/cosa-vedere-in-garfagnana/

**Comment by MohammedKaludi** [comment]
https://monosnap.com/file/LMZFAcyMje9hxFiS2ypZRBQXrzUudy

Escaping

**Comment by MohammedKaludi** [comment]
ready to push, just add escaping in the update branch.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.11
