### ISSUE TITLE
 Deprecated Filters Detected Warning: aioseop_amp_description

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4980]
https://secure.helpscout.net/conversation/1475337438/189792?folderId=2632030

![image](https://user-images.githubusercontent.com/46995400/114138418-3c585f00-992b-11eb-90b3-c4b3552ec0c5.png)

checked in local as well, it is appearing.

**Comment by arnaudbroes** [comment]
AIOSEO dev here. Feel free to ping me if you want me to verify any changes you make.

Basically, you need check whether the AIOSEOP_VERSION (old version) or AIOSEO_VERSION (new version) constant is defined and act accordingly. The new title and description filters are aioseo_title and aioseo_description.

**Comment by Zabi09** [comment]
@arnaudbroes can you tell me the exact version on which you people have depreciated the "aioseop_amp_description" and also in the latest updates you people have only created the AMP compatibility so thought to remove the old filters without the check.

let me know your thoughts on this

**Comment by arnaudbroes** [comment]
@Zabi09 version is 4.0.0. 

You can delete the old filters if you like, but that would break the functionality for any of our users that are still using the old version (3.7.1 or lower) of the plugin, which unfortunately is still the majority of our users.

**Comment by Zabi09** [comment]
@arnaudbroes okay as you say, I will add the check for the version and then delete it.

**Comment by MohammedKaludi** [comment]
ready to push.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.11
