### ISSUE TITLE
php 8 errors

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#4981]
The user has updated to WordPress 5.7 and PHP 8 and the plugin has PHP errors. The images from the amp article disappeared.  

notice : Undefined index: ampforwp-ia-on-off
notice: Trying to access array offset on the value of type null

wp-content/plugins/accelerated-mobile-pages/templates/features.php:6873

Ref ticket: https://wordpress.org/support/topic/php-8-13/

**Comment by MohammedKaludi** [comment]
ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.11
