### ISSUE TITLE
Need to compatible with muffin pagebuilder

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4983]
AMP has not compatible with the muffin page builder. The content is not showing on AMP pages. The content render for muffin builder is broken and nothing renders.
Website URL: https://asadorelescorial.es/carta-bebidas/
Reference: https://secure.helpscout.net/conversation/1476598637/189949/

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.11
