### ISSUE TITLE
Need Alt tag in social media icons 

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#4984]
Reference Ticket: https://secure.helpscout.net/conversation/1471067975/188742?folderId=4409869

Need alt tag in Social media icons because lighthouse showing warning
Reference Screenshot: https://monosnap.com/file/8bi5KLhSIuBPLrRcP97Xplh8jyv7gP

How to Recreate:
1. In the AMP setting-->Design-->Social Sharing-->Sticky Social Sharing bar(enable)
2. Do the lighthouse test 
3. now in SEO it's showing (Image elements do not have [alt] attributes)

**Comment by MohammedKaludi** [comment]
done.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.13
