### ISSUE TITLE
Fatal error occuring with the recent update Version 1.0.76.11 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4986]
Fatal error: Uncaught Error: Undefined constant "AIOSEO_VERSION" in C:\xampp\htdocs\sravan\wp-content\plugins\accelerated-mobile-pages\templates\features.php:3333

an error occurring when All in One SEO Pro is not activated.

Ref: https://secure.helpscout.net/conversation/1483458039/190934?folderId=2632030

issue occurring in local as well.

![image](https://user-images.githubusercontent.com/46995400/114669765-e1a27700-9d1f-11eb-88a7-46e5c21e19cd.png)

**Comment by TMsravan** [comment]
Another user Facing the same issue: https://secure.helpscout.net/conversation/1483501976/190945?folderId=2632030

**Comment by Sasirekhamarella** [comment]
Another user Facing the same issue: https://wordpress.org/support/topic/warning-use-of-undefined-constant-aioseo_version/#post-14315685

he is getting this as a warning.

**Comment by Sasirekhamarella** [comment]
Another user Facing the same issue: https://wordpress.org/support/topic/error-last-version/

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://secure.helpscout.net/conversation/1483561804/190968?folderId=4195936

**Comment by MohammedKaludi** [comment]
Fixed and pushed in 1.0.76.12
