### ISSUE TITLE
Menu item that have subMenu is showing an extra text as + - Open menu.

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#4988]
While Menu is set in the AMP site, the submenu item is showing a text as '+-Open menu' without any button action.
Reference - https://secure.helpscout.net/conversation/1480459232/190536/
Site URL - https://thebettervacation.com/
user's site snap - https://prnt.sc/11djgtb
Local test snap - https://prnt.sc/11djieb

**Comment by Zabi09** [comment]
I tried to recreate the issue locally but still not able to recreate it and also Anu Priya said, I'm also unable to recreate this now. I recreated on my local on that day, snap is in the ticket as well but now, even in local, I can see it perfectly.

So added the CSS on users end and that has fixed the issue
