### ISSUE TITLE
“Search Bar” Close Button is hidden behind the admin navigation bar

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4991]
If the user is logged into dashboard and visits AMP site and clicks on search button, Close button of search bar is hidden behind admins navigation bar.

Helpscout ref: https://secure.helpscout.net/conversation/1484234770/191092?folderId=4544752
localhost screenshot: https://prnt.sc/11fvhom

**Comment by MohammedKaludi** [comment]
Done and pushed in 1.0.76.14
