### ISSUE TITLE
Add option to set Target for CTA button in swift theme

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#4995]
User wants an option where he/she can set target attribute for CTA button in swift theme header.
  
Helpscout ref: https://secure.helpscout.net/conversation/1489217896/191861?folderId=4544752

**Comment by MohammedKaludi** [comment]
I think that the esc_html will break the quotes in the attribute: 

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bb08185c1e3d948dccf38ab5f66280c41869efcd#diff-3a712a835654d5095120baf05299111a266046574b64dd2a6dc88d456ab78dffR277

**Comment by Zabi09** [comment]
If we add like this - `$new_tab = 'target="_blank"'` then it was breaking so I updated the code I added like - `$new_tab = 'target=_blank'` and checked and it was working fine

**Comment by Zabi09** [comment]
Pushed in 1.0.76.15
