### ISSUE TITLE
single post content is not showing when using subdomain in design 1,2 3

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/accelerated-mobile-pages#4996]
single post content is not rendering while using subdomain due to ampforwp_is_amp_inURL function, which is coming false due missing amp in subdomain URL.

solution: add below condition in ampforwp_is_amp_inURL function before checking amp in array.

if (class_exists('AMPforWP_Subdomain_Endpoint') && ampforwp_get_setting('amp-subdomain-url-format')) {
   return true;
}

I have added this code at user end, so need to push it in next update.

**Comment by Zabi09** [comment]
Pushed in 1.0.76.14
