### ISSUE TITLE
Compatibility problem with Gutenberg block background color

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4997]
One user has an issue with the Compatibility problem Gutenberg block background color. When the user adds a background block, it shows a background black box with whits text inside in AMP page.
Non-amp page: https://prnt.sc/11x15k7
AMP page: https://prnt.sc/11yfrrf
Using this block: https://prnt.sc/11x1iar
Website:  www.agorafs./com/amp 
Reference: https://secure.helpscout.net/conversation/1489048409/191847

**Comment by MohammedKaludi** [comment]
Isset for `$matches[4][0]`

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cf8ab55bfc0991b3304dd1ba223a966feec53487#diff-391410f392e1a47efb0301aaa8ee0fb2f16a30a47c7fc47f87ed392bf400e580R9437


If the url is not there then it might show that not able to get 0 of 4

**Comment by Zabi09** [comment]
Pushed in 1.0.76.16
