### ISSUE TITLE
Slide content from Slide Anything - Responsive Content / HTML Slider and Carousel plugin is not rendering in amp

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#4999]
https://secure.helpscout.net/conversation/1480947125/190612?folderId=2632030

Please see this video the issue is shown.

https://monosnap.com/direct/3NsykCkFPrA8UDoGdlMNi9dfniDjMO

And we have done compatibility with it previously: https://ampforwp.com/compatibility/slide-anything/

Plugin link: https://wordpress.org/plugins/slide-anything/

**Comment by Zabi09** [comment]
Pushed in 1.0.76.16
