### ISSUE TITLE
1.0.76.13. Update Breaks WP Recipe Maker

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#5000]
https://wordpress.org/support/topic/update-breaks-wp-recipe-maker/

**Comment by Zabi09** [comment]
I have tried using WP Recipe Maker and also WP Recipe Maker Premium but I am not able to recreate it and I have also tested with previous versions and the latest version but still did not found any issue.

So closing this ticket but if anyone has this issue then please let us know the steps to recreate it and we will reopen this ticket and fix it
