### ISSUE TITLE
Undefined variable $q / Attempt to read property “max_num_pages” on null

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5004]
The user spotted these in error log with php 8:
`[28-Apr-2021 04:02:15 UTC] PHP Warning:  Undefined variable $q in plugins/accelerated-mobile-pages/templates/design-manager/design-2/archive.php on line 160
[28-Apr-2021 04:02:15 UTC] PHP Warning:  Attempt to read property "max_num_pages" on null in plugins/accelerated-mobile-pages/templates/design-manager/design-2/archive.php on line 160`

Ref ticket: https://wordpress.org/support/topic/undefined-variable-q-attempt-to-read-property-max_num_pages-on-null/

**Comment by mohammed-qutubuddin** [comment]
User getting this PHP error.

It says: PHP Deprecated: Function get_magic_quotes_gpc() is
deprecated in ../accelerated-mobile-pages/includes/options/redux-core/framework.php
on line 2849

Reference Ticket: https://secure.helpscout.net/conversation/1495213121/192909?folderId=4409869

**Comment by Zabi09** [comment]
Pushed in 1.0.76.16
