### ISSUE TITLE
Error : The attribute 'height' in tag 'amp-img' is set to the invalid value. 

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#5005]
Error: The attribute 'height' in tag 'amp-img' is set to the invalid value. 

The above issue is occurring when the height and width values are in the decimal.

Ref screenshot: https://prnt.sc/12crf02

Ref:https://secure.helpscout.net/conversation/1493696211/192551?folderId=3575684.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.17
