### ISSUE TITLE
?amp doesn’t removing from non-amp 

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5006]
User scenario:

He is using /?amp for amp post.  the problem he is facing is that when he opens the amp post and click on “View Non-AMP Version” then the /?amp isn’t removed from the URL.  The /?amp is appearing in the non-amp version too.

Ref ticket: https://wordpress.org/support/topic/amp-doesnt-remove-from-non-amp/

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.76.17
