### ISSUE TITLE
Issues with Megashop theme.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#5010]
Issues with Megashop theme.

When we are using the Mega shop theme "AMP option panel "and "sub-menus" are also not working.

Ref URL:https://audible-free-subscription.com/amp/

Ref: https://secure.helpscout.net/conversation/1492075039/192337?folderId=3575684.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.3
