### ISSUE TITLE
Favicon not working correctly

### ISSUE THREAD

**Issue by jlariza** [ahmedkaludi/accelerated-mobile-pages#5011]
Good day,

According to favicon instructions for amp

https://developers.google.com/search/docs/advanced/appearance/favicon-in-search

if the file is not svg, `Your favicon should be a multiple of 48px square` . However, following the tutorial set here using a 48px square image
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4548

The file is uploaded but wordpress renders the size attribute as `32x32`. This may lead to mistakes to google index and avoid showing the favicon even if the image is following the required dimensions.

Is it possible to handle this from the amp plugin and not from the wordpress theme? considering wordpress engine does not consider favicons multiple of 48px square

Thank you,

**Comment by Zabi09** [comment]
@jlariza Will you please follow this tutorial and add the favicon - https://ampforwp.com/tutorials/article/how-to-add-favicon-in-amp/ and the favicon image which you have added in non-amp will also appear in AMP automatically

**Comment by Zabi09** [comment]
@jlariza And also can you please share your website URL for us to check it once

**Comment by Zabi09** [comment]
@jlariza please share your website URL for us to check it once

**Comment by Zabi09** [comment]
@jlariza the Favicon in AMP totally depends on your non-amp theme and what sizes you have added in that will appear because I have added two different sizes in non-amp and the same applied for AMP too. So closing the ticket.
