### ISSUE TITLE
Bad GT metrix result after changing featured image 

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5016]
Bad GT metrix result after changing featured image. 
User have attached a video - https://www.youtube.com/watch?v=a5jsY1bZ5sU

helpscout link - https://secure.helpscout.net/conversation/1502051738/194165?folderId=4459751

**Comment by arenbatu** [comment]
Web site is halt, after changing featured ımage as old time png picture.

**Comment by Zabi09** [comment]
Fixed in - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5020

So closing the ticket
