### ISSUE TITLE
Hide featured images on a single post if this is older than certain date

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#5018]
https://secure.helpscout.net/conversation/1487889910/191685/

**Comment by Zabi09** [comment]
Here is the code and you just need to change the date of your choice.
`add_filter('ampforwp_modify_featured_image','ampforwp_featured_image_date');
function ampforwp_featured_image_date($image){
  $post_id = ampforwp_get_the_ID();
  if (strtotime(get_post( $post_id )->post_date) < strtotime("2021-02-10")){
   $image = '';
  }
return $image;
}`

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.3
