### ISSUE TITLE
Dynamic Copyright code so that year changes automatically 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#5019]
Dynamic Copyright code so that year changes automatically in the footer 

https://monosnap.com/file/5txkzIEb9UZkdcn1AkvklNCggwZEwK

**Comment by Zabi09** [comment]
With the help of this shortcode - [year] - you can add the dynamic copyright of year in the footer or anywhere else if you need

Add like this - https://www.awesomescreenshot.com/image/8571207?key=cf7f9c9503b59149c00637e32754e3a7
Output - https://www.awesomescreenshot.com/image/8571238?key=aeb5e17d8dc2c4df9e51c9846a2a6425

**Comment by MohammedKaludi** [comment]
this is not the correct fix, please use do_shortcode method to achieve this.

**Comment by MohammedKaludi** [comment]
1. Also add the shortcode and how to add it in the ToolTip 
2. Change the shortcode name to `ampforwp_current_year`

**Comment by MohammedKaludi** [comment]
Ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.4 update
