### ISSUE TITLE
Twitter Handle Not Showing On Twitter Shares

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#502]
REF: https://wordpress.org/support/topic/twitter-handle-not-showing-on-twitter-shares/#post-8742579

I’ve noticed that my twitter handle isn’t showing when people share an article from the site. e.g. 19 Tips For Beginners To Market A Small Business Online via @JacksAdvice_com

Is there a way to add this in, even within the editor. If so, it would be great if you could let us know, as we’ll lose some serious social awareness otherwise.

Paul.

**Comment by MohammedKaludi** [comment]
Working
