### ISSUE TITLE
Need to get featured image preloaded on AMP

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#5020]
Reference - https://secure.helpscout.net/conversation/1470715571/188705?folderId=4074390
Hero image of AMP posts is not getting preloaded. 
Need this facility in AMP to get featured image create a link rel="preload" as="image" href="xxxxx.xxx"... 
Ref Snap - https://prnt.sc/12y9qkg

**Comment by Zabi09** [comment]
Pushed in 1.0.77.1

**Comment by cookingwithdog** [comment]
@Zabi09 @MohammedKaludi

Hello, I think there is a bug in the preload featured image feature.

The full-size image is preloaded when you select the image size for the Swift theme. This downloads an unnecessary full-size image and it is bad for the page speed.

![preload-featured-image-issue](https://user-images.githubusercontent.com/84653339/119250321-4df37e80-bbda-11eb-895a-d110e85c9f9b.jpg)

Please check the attached screenshot. Thank you.
