### ISSUE TITLE
Need to add a  feature to set mobile redirection with some condition

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5022]
The user wanted to enable “Mobile Redirection” for all mobile users from all countries of the world except Egypt because AMP blocked in Egypt. Since this option is not available in the plugin,  he found a workable temporary solution.

He made a little bet modify in this file /wp-content/plugins/accelerated-mobile-pages/includes/redirect.php under the comment line “// Mobile redirection” on line “253”.

Now he wants a permanent solution to work on his scenario. We need to add a feature to set mobile redirection with conditions.

Reference ticket: https://wordpress.org/support/topic/could-i-enable-mobile-redirection-with-a-condition-%D8%9F/?loggedout=true

**Comment by Zabi09** [comment]
Mobile redirection filter added in this ticket -  #4488 with the help of this filter you can control the mobile redirection according to your needs.

Here is the example code on how to use these filters to control mobile redirection

`add_filter('ampforwp_modify_mobile_redirection' ,'prefix_mobile_support');
function prefix_mobile_support($mobile){
if(!is_category('sports')){ //Mobile Redirection will only work for sports category
$mobile = true;
}
return $mobile;
}`

**Comment by Zabi09** [comment]
So closing this ticket
