### ISSUE TITLE
CLS issue while using theme:  Design 1,2,3

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#5023]
User is encountering high CLS issue while user  is using  design 3  theme https://prnt.sc/131bn04.  while debugging the issue at our end I noticed that the issue also occurs in design 1 and design 2 as well. 

Helpscout ref: https://secure.helpscout.net/conversation/1514126788/196367/

cloudways screenshot Design 1: https://prnt.sc/131bty3
cloudways screenshot Design 2 : https://prnt.sc/131bwkf
cloudways screenshot Design 3: https://prnt.sc/131bzwn
cloudways screenshot swift theme(no issue): https://prnt.sc/131c45l

**Comment by Zabi09** [comment]
I have checked your website on GTmetrix and yes your CLS is one but when I check the same on PageSpeed Insights and also Lighthouse then it is showing zero please see the screenshot:

https://www.awesomescreenshot.com/image/8501300?key=162f4e422b72ecab18d08295cec68bb2

So I suggest you ignore this for now as its showing no issues in PageSpeed Insights and Lighthouse
