### ISSUE TITLE
Two amp version layout appearing on the custom front page ( compatibility issue with Betheme )

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5026]
Two amp version layout appearing on the custom front page ( compatibility issue with Betheme )

help scout link - https://secure.helpscout.net/conversation/1509918936/195763?folderId=4459751

**Comment by Zabi09** [comment]
Fixed in - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5013
