### ISSUE TITLE
Getting Console Error/AMP validation Error 

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5027]
Reference Ticket URL: https://secure.helpscout.net/conversation/1504166166/194814?folderId=4409869
Getting Console Error/AMP validation Error 
**The mandatory attribute 'target' is missing in tag 'form'.**

Recreate Steps: 
1. Install and activate the "Add Widget After Content" plugin(https://wordpress.org/plugins/add-widget-after-content/).
2. In After Content Widget add the category as shown in the below screenshot https://monosnap.com/file/gIh0E6zt4DSkyKWxNb5IRaoSNQtQBh

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.3
