### ISSUE TITLE
Links to social profiles

### ISSUE THREAD

**Issue by Lofesa** [ahmedkaludi/accelerated-mobile-pages#503]
As a enhancement you can add links to social profiles (well to the most relevant: facebook, twitter and G+) in the sidebar

**Comment by nicholasgriffintn** [comment]
I hard coded our social links straight into our footer with Font Awesome, which is probably the easiest way of getting that support right now.

I'm unsure about how easy that would be for the sidebar, I presume it to be similar.

Also, I'm unsure how useful social links would be in the sidebar, is that not something people look for in the header/ footer? That's my preference.  Anyway, it shouldn't be too hard to code it into the options tbh, just depends on where that placement would be.

**Comment by Lofesa** [comment]
Well, sidebar or whatever else, but links to social profiles.... FontAwesome, yes, but locally, if downloaded from maxcdn (the one white listed) can add  up to 200ms to render page

**Comment by nicholasgriffintn** [comment]
@Lofesa Sure it can, but that doesn't really matter if you are loading it from Google's cache, of course if you are using AMP for other means then that may be a problem.

**Comment by Lofesa** [comment]
@nicholasgriffintn ¿? Links to social profiles are added in desing 3

**Comment by nicholasgriffintn** [comment]
@Lofesa I believe so, I noticed that change so @ahmedkaludi and @MohammedKaludi must have thought the same thing as you :).
