### ISSUE TITLE
Debug Warnings

### ISSUE THREAD

**Issue by raza-web** [ahmedkaludi/accelerated-mobile-pages#5031]
https://secure.helpscout.net/conversation/1516836527/196767?folderId=4626537

![AMP errors](https://user-images.githubusercontent.com/67839276/119145998-d0a7fc80-ba67-11eb-9cae-f7093ee6e7c5.JPG)

**Comment by Zabi09** [comment]
The errors are coming due to some missing options on your end and to fix this error will you please reset the AMP options panel once and check again and I am sure it will be fixed
