### ISSUE TITLE
Fatal error:   Uncaught Error: Call to a member function get_contents() on null 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#5032]
PHP Fatal error:  Uncaught Error: Call to a member function get_contents() on null in /home/infantje/simplyraw.in/wp-content/plugins/accelerated-mobile-pages/components/components-core.php:398

**Conflict with the Sassy Social Share plugin.**

https://www.simplyraw.in/akira-kurosawa-a-great-storyteller-on-celluloid/amp/

issue recreated in the local.

PHP Fatal error:  Uncaught Error: Call to a member function get_contents() on null in C:\xampp\htdocs\sravan\wp-content\plugins\accelerated-mobile-pages\components\components-core.php:398
Stack

steps to recreate :

1. Activate: Sassy Social Share plugin

2. Enable Optimize CSS (beta) option in AMP >> settings >> performance

3. Then open the single post/single page 

4. error appears only we logged out the wp-admin.

5. when we logged in, an error won't appear.

Please see this video the issue is shown: https://monosnap.com/file/TMNM3IQWTjPJC53Lq6vghIDcEH33IL

https://secure.helpscout.net/conversation/1519195023/197168/

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.3
