### ISSUE TITLE
AMP optimizer implementation 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#5034]
Make sure the AMP optimizer is implemented properly in AMPforWP

https://github.com/ampproject/amp-toolbox-php

**Comment by Zabi09** [comment]
3 validations errors - 
1 - The mandatory attribute 'i-amphtml-version' is missing in tag 'style[amp-runtime]'.
2 - The attribute 'class' in tag 'i-amphtml-sizer' is set to the invalid value
3 - The attribute 'data-webvital-original-style' may not appear in tag 'i-amphtml-sizer'.

**Comment by MohammedKaludi** [comment]
Breaking due to treeshaking : https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5048

**Comment by TMsravan** [comment]
when updating plugin Version 1.0.77.5 

 along with option Optimize CSS (beta)  is enabled and  none of the styles are loading in the amp version
 
 and getting validation error: The text inside tag 'style amp-custom' contains 'CSS i-amphtml- name prefix', which is disallowed. 
 
 
![Uploading image.png…]()


https://monosnap.com/direct/CYyHZcavIMlSpam4IEvvPbcL7R2ONC

**Comment by amer07** [comment]
Noticed validation errors.

https://monosnap.com/file/Z32QpV8HhclyfMW5MKklwndsr7spFO

The parent tag of tag 'img' is 'a', but it can only be 'i-amphtml-sizer-intrinsic'.
Usage of the !important CSS qualifier is not allowed
Custom JavaScript is not allowed.
The author stylesheet specified in tag 'style amp-custom' is too long - document contains 190006 bytes whereas the limit is 75000 bytes.

**Comment by Zabi09** [comment]
@amer07 I have checked your issue and found that those errors are appearing in master too and that is due to "powered by 000webhost" image - https://www.awesomescreenshot.com/image/8973144?key=599b58322d408aaf577a6864fd36e560

**Comment by MohammedKaludi** [comment]
1. Excess styling coming and treeshking is not working properly 
2. UTF charset is getting added in the css

**Comment by merajali294** [comment]
When we use AMP Pagebuilder compatibility, with Elementor/Divi/Avada, it's completely breaking the Design and style tag becomes empty(might be a regex problem). 
Screenshots:-
Elementor before (https://www.awesomescreenshot.com/image/9427569?key=8c707e87fc164a11e112e502b2adea9d)
Elementor after (https://www.awesomescreenshot.com/image/9427631?key=7604025e49e319419c1234bbd52d1002) 
same goes for other builders.

**Comment by merajali294** [comment]
Have tested AMP Woocommerce pro, it has the design break issue as well.
Screenshot
https://www.awesomescreenshot.com/image/9427569?key=8c707e87fc164a11e112e502b2adea9d

**Comment by merajali294** [comment]
AMP Cache functionality works well, no issues

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.7 version
