### ISSUE TITLE
Error in debug.log

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5035]
Error message:  Function get_magic_quotes_gpc() is deprecated in ..../public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php on line 2849

Issue ticket : https://wordpress.org/support/topic/error-in-debug-log-20/

**Comment by MohammedKaludi** [comment]
Ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.4 update

**Comment by Zabi09** [comment]
The slashes (\) are no longer appear in the custom CSS - https://wordpress.org/support/topic/fontawesome-problem-in-amp-pages/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.8
