### ISSUE TITLE
Full-size image is always preloaded for the featured image in Swift theme

### ISSUE THREAD

**Issue by cookingwithdog** [ahmedkaludi/accelerated-mobile-pages#5038]
Hello, There is a bug in the new preload featured image #5020 .

For the Swift theme, a full-size image is always preloaded even if you select a smaller size for the featured image. This will significantly slow down the page speed. Please check the attached screenshots.

![preload-featured-image-issue1](https://user-images.githubusercontent.com/84653339/119430535-ee1ce500-bd4b-11eb-8cd1-0ae7bbba0fa4.jpg)
![preload-featured-image-issue2](https://user-images.githubusercontent.com/84653339/119430556-f83ee380-bd4b-11eb-81a5-a543573e7be9.jpg)

Thank you.

**Comment by AnupriyaSurapaneni** [comment]
Similar issue with a user, speed insights still sometimes showing the suggestion on preload of the image.
Original featured image is preloaded (.jpg) but not the optimized image (.jpg.webp - with Imagify)

Reference ticket - https://secure.helpscout.net/conversation/1470715571/188705?folderId=4074390
Snap - https://prnt.sc/13drfh9

**Comment by MohammedKaludi** [comment]
pushed in 1.0.77.3
