### ISSUE TITLE
'View Non-amp version'on footer redirecting to 404 using custom permalink structure

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#5039]
If we set this permalink like this: /%category%/%year%/%monthnum%/%day%/%postname%/ and the month & day are the same the 'View Non-amp version' on footer redirecting to 404. 
Recreating steps:
1. permalink getting like this: /%category%/%year%/%monthnum%/%day%/%postname%/ : https://prnt.sc/13fi977
2. Set the month $date are same using the quick edit option: https://prnt.sc/13fi7gs
 Screenshot: https://prnt.sc/13fdjks
Reference: https://secure.helpscout.net/conversation/1512328655/196136/

**Comment by MohammedKaludi** [comment]
Ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.4 update
