### ISSUE TITLE
Getting Aq_resize.process() error in error logs

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5041]
Getting Aq_resize.process() error in error logs. (Using string locator plugin to find the Aq_resize string)

helpscout link - https://secure.helpscout.net/conversation/1515583304/196611?folderId=4459751

**Comment by MohammedKaludi** [comment]
Ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.4 update
