### ISSUE TITLE
Facing amp validation error: The tag 'animatetransform' is disallowed.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#5043]
https://www.knowyourmobile.com/pt/not%C3%ADcia/sem-google-pixel-5-xl-somente-pixel-5/amp/

Ref: https://secure.helpscout.net/conversation/1523634979/198529?folderId=2632030

The issue occurs when we add this content in the attachment file.

<svg version="1.1" id="trspin" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 0 0" xml:space="preserve"><circle fill="#888" stroke="none" cx="6" cy="50" r="6"><animateTransform attributeName="transform" dur="1s" type="translate" values="0 15 ; 0 -15; 0 15" repeatCount="indefinite" begin="0.1"></animateTransform></circle><circle fill="#888" stroke="none" cx="30" cy="50" r="6"><animateTransform attributeName="transform" dur="1s" type="translate" values="0 10 ; 0 -10; 0 10" repeatCount="indefinite" begin="0.2"></animateTransform></circle><circle fill="#888" stroke="none" cx="54" cy="50" r="6"><animateTransform attributeName="transform" dur="1s" type="translate" values="0 5 ; 0 -5; 0 5" repeatCount="indefinite" begin="0.3"></animateTransform></circle></svg>

issue recreated in local.

![image](https://user-images.githubusercontent.com/46995400/119966547-0b121c00-bfc9-11eb-9e78-8608eee7e5ab.png)

**Comment by MohammedKaludi** [comment]
Ready to push

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.4 update
