### ISSUE TITLE
The Date/Time of publishing in the post & blog page is translating incorrect on a spanish user's AMP site.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/accelerated-mobile-pages#5045]
One of our users reporting that the Date/Time of publishing on the blog page is translating incorrectly on a Spanish user's site.

For example:  

The below article is published 2weeks ago,
URL: https://www.deagenciapanama.com/suv-con-el-peor-equipamiento-de-seguridad/amp/

Currently, it is showing in AMP "2 semanas hace" where it should be pronounced like this "hace 2 semanas"

Reference Screenshot of the issue: https://prnt.sc/13jnfun
The user requesting the correct translation in the screenshot: 
https://prnt.sc/13jni2e
https://prnt.sc/13jnl30

I have checked in my local host by changing site language to Spanish, the issue is occurring in the local host too.
Ref Screenshot: https://prnt.sc/13jnogx
The correct one is: https://prnt.sc/13jnqnx

Ref Ticket: https://secure.helpscout.net/conversation/1525131420/198814/

**Comment by Zabi09** [comment]
For changing the date format to spanish we already have the option - https://ampforwp.com/tutorials/wp-content/uploads/2020/07/16-1-1024x505.png

So closing the ticket
