### ISSUE TITLE
Primary category compatibility of all SEO plugins

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#5049]
Primary category compatibility of all SEO plugins because right now it shows all the categories and it's not looking good if we have many categories 

https://github.com/ahmedkaludi/accelerated-mobile-
pages/blob/b34e2ef245d585f640a487745dc72643fc2dcfce/components/categories-tags/categories-tags.php#L12

https://monosnap.com/file/DVGg9laqbIVqfenPzutuHPSFISQ44X

**Comment by Zabi09** [comment]
This will return only 1 category name

add_filter('ampforwp_modify_categories','prefix_function_name');
function prefix_function_name($count){
	return 1; //change the count here
}

**Comment by ajaymaravind** [comment]
@Zabi09 @MohammedKaludi we need an option to add a custom primary category field as well. To avoid dependence on SEO plugins, we handle primary categories on site-specific plugins. It will be great to add a hook where we can add our own output for the primary category.

if (function_exists( 'ampforwp_custom_primary_cat' )) {
              
		$cat_id =ampforwp_custom_primary_cat(ampforwp_get_the_ID());
	}
	
Something similar will work out.  We could use this function and outpt primary cat id

**Comment by Zabi09** [comment]
@ajaymaravind I have added the filter and below is the code which you need to use for adding the custom primary category

add_filter('ampforwp_custom_primary_cat','ampforwp_custom_primary_cat_fn');
function ampforwp_custom_primary_cat_fn($cat_id){
	if ( get_the_ID() === 5138) {  // Enter the post id here on which you need to add custom primary category
		$cat_id = 484; // Enter the category id here
	}
	return $cat_id;
}

**Comment by ajaymaravind** [comment]
@Zabi09 which line is the code implemented? I would like to see it I was unable to find it in the above commit

**Comment by Zabi09** [comment]
@ajaymaravind Here is the filter which I have added - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/4934bbfce771699cbe354695f45afcd1bc2e8ebf

Now you need to create a custom plugin like this - https://ampforwp.com/tutorials/article/extend-amp-plugin/ and add the below code

@ajaymaravind I have added the filter and below is the code which you need to use for adding the custom primary category

add_filter('ampforwp_custom_primary_cat','ampforwp_custom_primary_cat_fn');
function ampforwp_custom_primary_cat_fn($cat_id){
if ( get_the_ID() === 5138) { // Enter the post id here on which you need to add custom primary category
$cat_id = 484; // Enter the category id here
}
return $cat_id;
}

**Comment by ajaymaravind** [comment]
perfect! Thanks for this. @Zabi09

**Comment by Zabi09** [comment]
Pushed in 1.0.77.8
