### ISSUE TITLE
Referenced AMP URL is self-canonical AMP when AMP takeover is enabled

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#5053]
https://wordpress.org/support/topic/referenced-amp-url-is-self-canonical-amp-13/

**Comment by mohammed-qutubuddin** [comment]
Reference Ticket URL: https://secure.helpscout.net/conversation/1535610981/201048/
this user did not enable AMP takeover but he is reporting this issue.
**Referenced AMP URL is self-canonical AMP**

**Comment by Zabi09** [comment]
Pushed in 1.0.77.5
