### ISSUE TITLE
Disqus comments not showing on mobile

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#5055]
Disqus started showing ads above the comments. When I use the Responsive Disqus layout in AMP, ads appear but comments are not shown on the page in mobile view.
Like this: https://prnt.sc/14j2wkz
Website: https://www.oppohub.it/realme-7-e-7i-aggiornati-ad-android-11-in-italia-oppo-reno2-il-prossimo/?amp
Reference: https://secure.helpscout.net/conversation/1532388552/200205?folderId=4195936

**Comment by Zabi09** [comment]
Pushed in 1.0.77.8
