### ISSUE TITLE
Some issues found while refresh the individual extension from the Extension section

### ISSUE THREAD

**Issue by WasimM3** [ahmedkaludi/accelerated-mobile-pages#5056]
- [x] When sending refresh request `redux_builder_amp` is updating with the latest license data even though activation status is `invalid` this is causing lost of that particular extension data. **Better to move update condition after successful refresh**.
- [x] Need to improve the code to check whether item_name is passing to the server properly or not, because on my test case I found NULL value is passing to server, because of this refresh action is not working and loosing the existing data.
- [x]  If `plugin_refresh_check` Cookie is set refresh button should disable or can stop refresh and show some notification that `Can't refresh ` some thing like this.
- [x] Icons are not loading properly 
 https://monosnap.com/direct/4pXyNscjrKdVrbkMBZ7kwurrvYCL4o

**Comment by Zabi09** [comment]
Pushed in 1.0.77.5
