### ISSUE TITLE
Icons are not loading when visiting first time or visiting after clearing cache.

### ISSUE THREAD

**Issue by rsinghcodes** [ahmedkaludi/accelerated-mobile-pages#5060]

**Comment by nsgoyat** [comment]
I am feeling exactly the same issue. It has been almost two weeks since this critical issue was first reported yet it hasn't been fixed. 

https://wordpress.org/support/topic/icomoon-icons-missing-from-amp-pages/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.9
