### ISSUE TITLE
Images are not getting loaded on posts in the amp version after updating to version 1.0.77.3

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5061]
WebP Express plugin is getting conflict after updating to version 1.0.77.3. On version 1.0.77.2, images are getting loaded with WebP Express plugin.

Help scout link - https://secure.helpscout.net/conversation/1536343212/201143?folderId=4459751

**Comment by Zabi09** [comment]
Commit added in #4357
