### ISSUE TITLE
Custom JavaScript is not allowed.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#5062]
Error: Custom JavaScript is not allowed.

This error is occurring by the "All in one SEO" pro plugin and issue is occurring only on the user end.

Ref: https://secure.helpscout.net/conversation/1535770598/201093?folderId=3575684

**Comment by kupveja** [comment]
Same issue is occuring on the 2 user's end

Ref: https://secure.helpscout.net/conversation/1535878399/201107?folderId=4459751

       https://secure.helpscout.net/conversation/1530284408/199868?folderId=4459751

**Comment by Zabi09** [comment]
Pushed in 1.0.77.6
