### ISSUE TITLE
Some images are not getting displayed using normal gutenberg block on the amp version.

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5069]
Some images are not getting displayed using normal gutenberg block on the amp version.

On changing the user's current theme ( EAS child ), all images are loading on the amp version. Also, when we change the swift theme to any other theme, images are loading on the amp version.

ref: https://secure.helpscout.net/conversation/1543244270/202062?folderId=4459751

**Comment by Zabi09** [comment]
Github is for tested and re-creatable bugs, for the technical issues, we will help you via website
