### ISSUE TITLE
Warning: fopen error.

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#507]
Its showing in some pages, sometimes but after refresh it goes away.

ref: http://take.ms/4FLKz
http://snacksdeliverytw.com/%E6%AD%90%E6%B4%B2%E9%9B%B6%E9%A3%9F%E9%96%8B%E7%AE%B1-%E4%BE%86%E8%87%AA%E6%AF%94%E5%88%A9%E6%99%82%E5%B7%A7%E5%85%8B%E5%8A%9B%E4%B9%8B%E9%83%BD%E7%9A%84-duc-do-%E9%BB%9B%E6%9C%B5%EF%BC%81/amp/

**Comment by howthou** [comment]
I open the new post we posted, is also showed error message, as the link:https://megabackup.com/g/gc8a/K6JD4PSHNJ6E3RSK5EGLJZMOQDO7TJTX

and the post link is:http://snacksdeliverytw.com/零食開箱推薦-霸氣側漏的金條，你能猜到他是什/amp/

**Comment by khaledMohammed000** [comment]
Hey @howthou, I was able to see the issue http://take.ms/EnGmQ , can you please disable photon (flush cache too ) once and recheck

**Comment by ahmedkaludi** [comment]
This was fixed https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/eed4cb8795c663f04b0e79a0edb855657678f768

**Comment by howthou** [comment]
Hello @khaledMohammed000,

I dont know how to disable photon, please tell me how to do ,thanks!

**Comment by howthou** [comment]
The other page I opened:http://snacksdeliverytw.com/%E5%BF%AB%E9%81%9E%E5%85%88%E7%94%9F%E9%9B%B6%E9%A3%9F%E9%96%8B%E7%AE%B1%E6%97%A5%E6%9C%ACkabaya-%E4%B8%8D%E5%8F%AF%E6%80%9D%E8%AD%B0%E5%8F%AF%E6%A8%82%E8%98%87%E6%89%93%E7%B3%96/amp/

https://megabackup.com/g/y7lp/ME24B57Z3RBRWXBF3CKY6BH36G7JFYRU

**Comment by khaledMohammed000** [comment]
Hey @howthou Please have a look at the video http://take.ms/15h3l ,  I have shown where you need to click to disable jetpack photon and then Purge all cache

Let me know if you have anymore quireies

**Comment by khaledMohammed000** [comment]
@howthou please update the plugin to the latest version and do let us know, you still use the older version , get the latest version 0.9.43.6

**Comment by howthou** [comment]
@khaledMohammed000 Thank you very much! I will try later!

**Comment by howthou** [comment]
@khaledMohammed000 Could you please give me the plug in link about the widget called "Performance" , because I am not sure which one you used.
