### ISSUE TITLE
Meta description of Rank Math SEO plugin not showing on amp posts

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5071]
Meta description of Rank Math SEO plugin not showing on amp posts. User is using amp by automatic and as an add-on using our ampforwp plugin. When our ampforwp plugin is deactivated, meta description on amp posts are visible.

Recreated successfully on local too.

ref: https://secure.helpscout.net/conversation/1548180521/202731?folderId=4459751

**Comment by Zabi09** [comment]
Pushed in 1.0.77.9
