### ISSUE TITLE
Slide Anything -Plugin slider content is not showing

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#5073]
Plugin : Slide Anything - Responsive Content / HTML Slider and Carousel

https://wordpress.org/plugins/slide-anything/

Slide Anything -Plugin slider content is not showing when the content tag has spaces.

Please see this video the issue is shown in it Ref: https://monosnap.com/file/G0ZSFNOVux7HUlmG8WbLYLc7Vfitva

Issue recreated in local as well.

https://secure.helpscout.net/conversation/1541470439/201827?folderId=1060556

https://dev.hayhurst.me.uk/tanyagoodin.com/amp/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.9
