### ISSUE TITLE
Remove preload if Featured Image option is off in AMP options panel

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5077]
Even after disabling the Featured image, it is still showing the preload code when we inspect it.

Reference video: https://monosnap.com/file/MHP3ZVeHjtMgpkisArWd3tkWu0KukM

Ref ticket: https://wordpress.org/support/topic/remove-preload-featured-image/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.9
