### ISSUE TITLE
Search keyword with apostrophe returning not found result

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#5078]
In AMP if we search a keyword with apostrophe, its returning not found result.
 
Helpscout ref: https://secure.helpscout.net/conversation/1557166619/204641?folderId=4544752
Localhost screengrab: https://monosnap.com/file/U7FQLNhsq55yRrXnarCsOYU8tlFiIX

**Comment by Zabi09** [comment]
Working fine on our end so closing the ticket
