### ISSUE TITLE
Litespeed cache and Webp images

### ISSUE THREAD

**Issue by dmata47** [ahmedkaludi/accelerated-mobile-pages#5081]
Hi.

I have Litespeed cache and I am using webp images with this plugin.

When I activate the WebP image replacement option in Litespeed some images in the AMP pages are not displayed (almost all).

I see 404 errors in the Chrome dev console regarding this, of images that do not exist on the server, when in fact they are all on the server, both in their normal versions (png, jpg) and webp.

When I try to open the images with 404 errors (which are on the server since I checked them manually) in the chrome dev console, I see that it adds this: `%E2%80%8B%E2%80%8B%E2%80%8B` after the image file extension.

If I disable the substitution of webp images in litespeed they are displayed correctly.

On this page you can see the error: https://bit.ly/35XmA4M

I would appreciate the help.

**Comment by Zabi09** [comment]
@dmata47 Your issue was valid and we have fixed that issue and we are going to push it next week,

**Comment by MohammedKaludi** [comment]
pushed in 1.0.77.10
