### ISSUE TITLE
Post title is in the h2 tag, instead of h1.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#5086]
https://secure.helpscout.net/conversation/1557383879/204665?folderId=1060554

User screenshot:- https://prnt.sc/18q7yk9

Localhost:- https://prnt.sc/18q83xk

Checked by resetting the redux settings. Still, the issue is the same.

**Comment by Zabi09** [comment]
Working as expected so closing the ticket
