### ISSUE TITLE
Amp is not working when WPML Multilingual CMS is activated.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#5087]
Ref:https://secure.helpscout.net/conversation/1562406268/205210?folderId=2770543

Use case: when amp & WPML Multilingual CMS both are activated, pages/post not opening in amp version.

I have done all debugging processes, and recreate in local.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.12
