### ISSUE TITLE
Loop Display Controls, Exclude Categories is not working.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5088]
Reference ticket: https://secure.helpscout.net/conversation/1562948685/205270?folderId=4409869

Loop Display Controls, Exclude Categories is not working.
I write the first two alphabets of a category but nothing appears in the list to select.

Reference Video: https://monosnap.com/file/lPadSCY5uqe5UEgtgaiOygqhhg3xsJ

Recreate Steps: 
1. AMP-->Design
2. Homepage-->Loop Display Control
3. Exclude category (type alphabet of your category)

**Comment by TMsravan** [comment]
Another user facing the same issue: 

As categories are not showing/ getting selected in Select Categories to Hide AMP posts option:

AMP >> settings >>tool
