### ISSUE TITLE
Post title not breaking in mobile view.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#5092]
https://secure.helpscout.net/conversation/1571503545/206250?folderId=1060554

When the post title is continuous with no space, the title does not break into the next line and moves out of the pageview on mobile devices.
Screenshot:- 
Title:- https://prnt.sc/1bddjkf
AMP post:- https://prnt.sc/1bddqtk

User scenario screenshots in the ticket.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.13

**Comment by ankit644** [comment]
The issue is still there don't close the ticket It happening in my local as well.

Screenshot:-
Title:- https://prnt.sc/1izqvsy
AMP post:- https://prnt.sc/1izrc8d
