### ISSUE TITLE
Fatal error in AMP appearence section

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5093]
`Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($function) must be a valid callback, non-static method AMPforWP\AMPVendor\AMP_Customizer_Design_Settings::register_customizer_ui() cannot be called statically in /home/wayearni/public_html/wp-includes/class-wp-hook.php:292 Stack trace: #0 /home/wayearni/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters() #1 /home/wayearni/public_html/wp-includes/plugin.php(484): WP_Hook->do_action() #2 /home/wayearni/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/admin/class-amp-customizer.php(121): do_action() #3 /home/wayearni/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/admin/class-amp-customizer.php(58): AMPforWP\AMPVendor\AMP_Template_Customizer->register_ui() #4 /home/wayearni/public_html/wp-includes/class-wp-hook.php(292): AMPforWP\AMPVendor\AMP_Template_Customizer::init() #5 /home/wayearni/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters() #6 /home/wayearni/public_html/wp-includes/plugin.php(484): WP_Hook->do_action() #7 /home/wayearni/public_html/wp-includes/class-wp-customize-manager.php(933): do_action() #8 /home/wayearni/public_html/wp-includes/class-wp-hook.php(292): WP_Customize_Manager->wp_loaded() #9 /home/wayearni/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters() #10 /home/wayearni/public_html/wp-includes/plugin.php(484): WP_Hook->do_action() #11 /home/wayearni/public_html/wp-settings.php(582): do_action() #12 /home/wayearni/public_html/wp-config.php(80): require_once('/home/wayearni/...') #13 /home/wayearni/public_html/wp-load.php(37): require_once('/home/wayearni/...') #14 /home/wayearni/public_html/wp-admin/admin.php(34): require_once('/home/wayearni/...') #15 /home/wayearni/public_html/wp-admin/customize.php(13): require_once('/home/wayearni/...') #16 {main} thrown in /home/wayearni/public_html/wp-includes/class-wp-hook.php on line 292`

Issue ticket: https://wordpress.org/support/topic/unable-to-access-amp-under-appearance-section-from-dashboard/

**Comment by Zabi09** [comment]
Github is for tested and re-creatable bugs, for the technical issues, we will help you via website
