### ISSUE TITLE
Unable to fetch content of the page with query string in the AMP URL from 1.0.66 version

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#5096]
Reference - https://secure.helpscout.net/conversation/1570491597/206135?folderId=4074390
The user has set query string in the web URL and they are fetched perfectly on AMP as well until the 1.0.65.2 version of the plugin but stopped showing the content from the 1.0.66 version. Normal AMP URLs are working fine but the issue is only with URLs that have query strings added.
Example - https://new.centsai.com/life/cost-of-living/advanced-child-tax-credit-for-2021-what-you-need-to-know/?amp&co_id=123
Sample video - https://monosnap.com/direct/ahu7K4qQpTE3j2kZCGwRK2HqSeWRzu
Reference videos from the user end are in the helpscout ticket conversation.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.14
