### ISSUE TITLE
AMP Issue say => The parent tag of tag ‘picture’ must be ‘noscript’.

### ISSUE THREAD

**Issue by Empathyfine** [ahmedkaludi/accelerated-mobile-pages#5097]
Please how can I resolve this AMP issue;

**The parent tag of tag ‘picture’ must be ‘noscript’.**

I have been having this issue for the past few days, and I have not been able to resolve it. Please any assistance and support to help me fix this issue will be appreciated.

Thanks, and looking forward.

**Comment by Zabi09** [comment]
@Empathyfine Will you please give me the URL of your website for us to check that AMP issue?

**Comment by Empathyfine** [comment]
Hello @Zabi09 thank you for your response. Please [here is the link](https://www.fanslite.com/top-10-richest-musicians-in-nigeria-and-their-net-worth/) to the the post with the AMP issue.

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.15
