### ISSUE TITLE
Incompatibility with Video Yoast Plugin

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#5098]
The video does not appear on the AMP page when enabling "Youtube Embed Function" in the Video Yoast plugin.

Add a video on the post: https://prnt.sc/1e9dl3b
enable "Youtube Embed Function" in the YoastVideo plugin: https://prnt.sc/1e9e5at
Video on Non-amp: https://prnt.sc/1e9fua6
AMP: https://prnt.sc/1e9fx07

Reference: https://secure.helpscout.net/conversation/1572707489/206439?folderId=4195936

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.15
