### ISSUE TITLE
If "Front page displays" has Static Pages, AMP Index does not work

### ISSUE THREAD

**Issue by Asif2BD** [ahmedkaludi/Accelerated-Mobile-Pages#51]
If a site has Static Pages setup in "Front page displays", then the index page of amp shows black and the index loop does not work. Here is what I am talking about - [Example Setting](http://d.pr/i/1amXI). This is gotta be a big issue, as many advance themes and site use static front page, to customize look and feel, and go beyond the tradition latest 10 posts.

Regards

**Comment by ahmedkaludi** [comment]
Hey Asif,

Thank you so much for reporting the issue as it helps me serve the users better.

I will look into this and try my best to implement in the next week's update cycle.

Regards,
Ahmed

**Comment by nicholasgriffintn** [comment]
I haven't really tested this yet, but I am looking for a way to do it for my own site.

Currently I think the easiest way to fix this problem would be to use an expression like this:

`<?php if (is_page('Home')) { LOAD LATEST POSTS } ?>`

And just set up a custom latest posts section just for those who use static pages as their front page.

Aside from that, all I can think of doing is setting a redirect to the static posts page.

**Comment by nicholasgriffintn** [comment]
Here's an update to what I previously posted.

I have written up some code that uses the idea that I previously had, you can check it out here: #60.

I am currently using it on our live site and it works in showing the latest posts, however, I have yet to fix the pagination. Just wanted to provide you with some ideas on how this could be done, whilst fixing it for myself.

**Comment by ahmedkaludi** [comment]
This was an old issue but pretty similar to the current situation, this has a updated ticket at #92
