### ISSUE TITLE
'White screen of death' is occurred while using AMP

### ISSUE THREAD

**Issue by Suleman0498** [ahmedkaludi/accelerated-mobile-pages#510]
By using the  "WP-HTML-Compression" plugin the AMP is not working properly.
Reference: https://secure.helpscout.net/conversation/314768782/10817/?folderId=1060551

**Comment by ahmedkaludi** [comment]
We need to un register this one

**Comment by Suleman0498** [comment]
We have found the similar case with the "JCH Optimize Pro" plugin.
Reference: https://secure.helpscout.net/conversation/298816636/10230/?folderId=1060551

**Comment by khaledMohammed000** [comment]
With regards to "JCH Optimize Pro" , I have created a thread here on the support forum of their plugin
https://wordpress.org/support/topic/please-make-your-pro-version-amp-compatible/

**Comment by Suleman0498** [comment]
We got the "JCH Optimize Pro" plugin to test.
Reference: https://secure.helpscout.net/conversation/298816636/10230/?folderId=1060551

**Comment by khaledMohammed000** [comment]
unable to recreate the issue, needs extensive tests @MohammedKaludi  @ahmedkaludi

**Comment by ahmedkaludi** [comment]
we are closing this to stay focused
