### ISSUE TITLE
Need to add Yoast custom breadcrumbs title support in amp.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#5100]
Ref:https://secure.helpscout.net/conversation/1576761717/207067?folderId=2770543

Custom breadcrumbs title option is available Yoast Premium.

See this screenshot:https://monosnap.com/file/vNoLNdt2Svmkff8uAoizDx92ISNrWk

**Comment by Zabi09** [comment]
Pushed in 1.0.77.16
