### ISSUE TITLE
Need to remove last-modified header in amp.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#5101]
Ref:https://secure.helpscout.net/conversation/1570242230/206123?folderId=2770543

Need to remove last modified date, day on header response, in amp version.

See this screenshot:https://monosnap.com/file/mfLRzsPD8b1nsBx1oqK43BtvXP73kq

**Comment by Zabi09** [comment]
add_filter('ampforwp_update_last_modified_header','prefix_last_odified_header');
function prefix_last_odified_header($header){
	$header = false;
	return $header;
}

**Comment by MohammedKaludi** [comment]
pushed in 1.0.77.16
