### ISSUE TITLE
Getting validation error: The tag 'lite-youtube' is disallowed 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#5102]
Getting validation error: The tag 'lite-youtube' is disallowed,

 When Enable Video Facade option in Avada theme >> Maintenance >> performance >>  optimization>> Enable Video Facade
 is enabled

The youtube applied video is get converted into the tag lite-youtube and this is creating a validation error and the video is not displaying in the amp version.

https://casinoplusbonus.com/loewen-play-online-casino/amp/

Currently use has disabled that option

Please see this video the setup of it and the issue is shown: https://monosnap.com/direct/6tttpkKqostBMQb77MZM4NDuBSsfNV

https://secure.helpscout.net/conversation/1560195687/204946?folderId=2632030

**Comment by Zabi09** [comment]
Pushed in 1.0.77.16
