### ISSUE TITLE
Need to add support to preserve 'query string' with /?amp as endpoint

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/accelerated-mobile-pages#5103]
Users need an option to preserve /?amp URLs when used with a query string.
Reference, https://secure.helpscout.net/conversation/1570491597/206135?folderId=4074390
In reference with, https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5096

**Comment by Zabi09** [comment]
Pushed in 1.0.77.17
