### ISSUE TITLE
 (") Quotation marks are showing as (x) in the amp version

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/accelerated-mobile-pages#5104]
https://secure.helpscout.net/conversation/1577183308/207140?folderId=4874234

Quotation mark showing as an (x) instead of (")  and this is only occur in the amp version.. This issue is just coming on the user end.

(") Quotation marks are showing as (x) :- https://prnt.sc/1g42i5h

**Comment by Zabi09** [comment]
You are getting this issue because the multi-byte string function is not present on your server please enable it and it will be fixed
