### ISSUE TITLE
How can I add a missing script in desired AMP page

### ISSUE THREAD

**Issue by thezainulabideen** [ahmedkaludi/accelerated-mobile-pages#5105]
An error "Content mismatch: Missing embedded video" occur for the page https://ezmob.com/push-ad-network/amp/. I want to add script "<script async custom-element="amp-youtube" src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js"></script>" at this amp page. How should I add this script (From where I can find option to insert manual script within WP site) ? Please help!

**Comment by Zabi09** [comment]
@thezainulabideen I have checked your website and the video is appearing fine and also we will add the required scripts based on your content and you no need to add it manually for example - if you add the youtube video or gallery etc then we will add the amp-youtube or amp-carousel script automatically and you no need to worry about it.

I can see the video is showing correctly now on your website now. Have you done any changes?

**Comment by thezainulabideen** [comment]
> @thezainulabideen I have checked your website and the video is appearing fine and also we will add the required scripts based on your content and you no need to add it manually for example - if you add the youtube video or gallery etc then we will add the amp-youtube or amp-carousel script automatically and you no need to worry about it.
> 
> I can see the video is showing correctly now on your website now. Have you done any changes?

Actually, I had recently fix this problem. There was a problem with the WP Elementor (The video link did not detect by AMP), so I removed the Link and add it by **'href'** HTML code. Now it's working fine. Thanks for your consideration.

**Comment by MohammedKaludi** [comment]
Thank you very much for your reply
As the issue has been resolved closing the ticket.

**Comment by thezainulabideen** [comment]
Hi M.Kaludi,
The same issue "**Content mismatch: Missing embedded video**" for the same page "https://ezmob.com/push-ad-network/amp/" has been detected again by the crawler (As the last scan of the crawler was on the 8th of august, 2021). Please review the mentioned page and let me know about the actual issue and how to resolve it.
