### ISSUE TITLE
How to change related posts thumbnail size filter is not working.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5106]
Tutorial URL: https://ampforwp.com/tutorials/article/how-to-change-related-posts-thumbnail-size/
Ticket URL: https://secure.helpscout.net/conversation/1578917856/207264?folderId=1060556

change related posts thumbnail size filter is not working.

**Comment by Zabi09** [comment]
There is a space in front of filter name and due to that it was not working, please remove the space and I am sure it will work - https://prnt.sc/1hi01ms
