### ISSUE TITLE
Need to add dotmetrics analytics support  in amp.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/accelerated-mobile-pages#5107]
https://secure.helpscout.net/conversation/1554470807/204249?folderId=2770543

For ref pls check this url: https://github.com/guardian/dotcom-rendering/blob/main/src/amp/components/Analytics.tsx

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/737f314d4f6d4abe2288887a6fa633787f49b93e#r54177705

**Comment by Zabi09** [comment]
Pushed in 1.0.77.17
