### ISSUE TITLE
Webp Express plugin is not compatible with ampforwp.

### ISSUE THREAD

**Issue by rsinghcodes** [ahmedkaludi/accelerated-mobile-pages#5108]
Images are being optimized in webp format for non-amp urls but images are not being optimized in webp format for amp urls.

Optimized image at non-amp URL: https://monosnap.com/file/haUnLu7PmPZ9Wqlobvkml8RNtTaY3v
Image not optimized for amp URL: https://monosnap.com/file/BGZUdVUHBAND0z6CTikKqjudBKDqUw

**Comment by Zabi09** [comment]
Pushed in 1.0.77.16
