### ISSUE TITLE
Password protected post/page is not working.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5109]
Reference Ticket: https://secure.helpscout.net/conversation/1585671506/207984?folderId=4409869

In WordPress, we have an option to protect a page with a password.
Reference Screenshot: https://monosnap.com/file/vF4jlEDdUJhbFVCGwAHpZGLmkzcPfR

Re-create Steps: 
1. Create a page/post
2. Quick Edit it.
3. Protect it with a password.

Reference Video: https://monosnap.com/file/OaCNcBoW4ilZcAbQogYyifdaiwi8iN

**Comment by Zabi09** [comment]
incorrect ticket
