### ISSUE TITLE
Re-save permalinks issues. Enhancement

### ISSUE THREAD

**Issue by Lofesa** [ahmedkaludi/accelerated-mobile-pages#511]
Why don´t use flush_rewrite_rules() each time plugin options are saved?
Whit this you don´t care on tell all time to the users they had to re-save permalinks

**Comment by ahmedkaludi** [comment]
@MohammedKaludi What do you think about this feedback?

**Comment by nicholasgriffintn** [comment]
I'd agree with this. Just to add my own opinion. I don't know if you need to do this for all saved options, but definitely a good idea for the ones that require it.

**Comment by MohammedKaludi** [comment]
Fixed
