### ISSUE TITLE
How can I add a missing script in desired AMP page

### ISSUE THREAD

**Issue by thezainulabideen** [ahmedkaludi/accelerated-mobile-pages#5112]
Hi M.Kaludi,
The same issue "**Content mismatch: Missing embedded video**" for the same page "https://ezmob.com/push-ad-network/amp/" has been detected again by the crawler (As the last scan of the crawler was on the 8th of august, 2021). Please review the mentioned page and let me know about the actual issue and how to resolve it.

Please note: This problem was detected by the crawler one month before, and I fixed this problem at that time, and the Search Console mark this problem as solved but now (After a month), the same problem occurs again.

**Comment by Zabi09** [comment]
@thezainulabideen I have checked your AMP website and I am able to see the video on both AMP and non AMP page and also I have tested your website on https://search.google.com/test/amp and its showing valid - https://search.google.com/test/amp?id=aoe2TCcjUdpwsLqOtrGKPA

Everything is looking fine to me will you please click on validate fix button and I am sure it will be fixed
