### ISSUE TITLE
Even though "Disable AMP on desktop" option is enabled still the AMP is display on the desktop with "?amp".

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/accelerated-mobile-pages#5113]
Even though "Disable AMP on desktop" option is enabled still the AMP is display on the desktop with "?amp".

Ref video :https://www.awesomescreenshot.com/video/4776422?key=759138c8374cd992dee43bcb982bcc97

Ref : https://secure.helpscout.net/conversation/1585614872/207973?folderId=3575684

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.19
