### ISSUE TITLE
Twitter embeds not showing up on AMP pages

### ISSUE THREAD

**Issue by Marghoob123** [ahmedkaludi/accelerated-mobile-pages#5117]
The Customer been having issues with his twitter embeds not showing up on AMP pages. He had given a test article to fix the issue and the link of the test article is  https://staging.nextshark.com/good-samaritan-intervenes-during-armed-robbery-shooting-in-oakland-chinatown/ and we recreated the issue to our localhost ,the screenshot  of the localhost is
![Screenshot (1)](https://user-images.githubusercontent.com/86001197/129336078-0cfc0d1a-5c96-421c-93bd-7904a43ce446.png)
Helpscout refrence link https://secure.helpscout.net/conversation/1597603837/209450?folderId=5044124

**Comment by Zabi09** [comment]
Twitter embeds are working fine so closing the ticket
