### ISSUE TITLE
Incorrect canonical for Homepage if WordPress installation is in folder

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#5122]
User has reported that he is getting incorrect canonical link as he has WordPress installation in a folder, in the canonical link /foldername is been added. 

User has suggested to use get_home_url()  instead of  get_site_url() in accelerated-mobile-pages/templates/features.php file , lines 4410 and 4425.

Screenshot : https://prnt.sc/1qgy4q7
Helpscout ref: https://secure.helpscout.net/conversation/1594580848/209135/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.21
