### ISSUE TITLE
Debug log errors

### ISSUE THREAD

**Issue by rsinghcodes** [ahmedkaludi/accelerated-mobile-pages#5124]
*PHP Warning: Undefined array key 1 in ccelerated-mobile-pages/includes/vendor/amp/includes/utils/class-amp-image-dimension-extractor.php on line 244*

*PHP Warning: Undefined array key "ampforwp-gallery-design-type" in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 1192*

Only user-end issue.

Ref :- https://secure.helpscout.net/conversation/1501634003/194083?folderId=4672784

**Comment by Zabi09** [comment]
Pushed in 1.0.77.21
