### ISSUE TITLE
Missing rel tag "noopener" in link

### ISSUE THREAD

**Issue by Ysery** [ahmedkaludi/accelerated-mobile-pages#5125]
Hi

IF (Html page)
`<a rel="nofollow noopener" title="test" href="https://test" target="_blank">test</a>`

Resut (AMP page)
`<a rel="nofollow" title="test" href="https://test" target="_blank">test</a>`

Missing tag **noopener**

Example http://sitework.epizy.com/2021/06/08/hello-world/

Lighthouse dissatisfied

<img src="https://i1.wp.com/i115.fastpic.org/big/2021/0825/da/0e861e08e2a1ae708ca2fd20f0e5e4da.png?ssl=1" border="0" width="524" height="97">

Sorry for my English.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.21
