### ISSUE TITLE
Need Compatibility for Lazy loading function in Zeen theme

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/accelerated-mobile-pages#5126]
Reference Ticket: https://secure.helpscout.net/conversation/1617027437/211710/

The User placed the image using **Zeen theme** (https://themeforest.net/item/zeen-next-generation-magazine-wordpress-theme/22709856)  but the image is not appears on AMP and appear on non AMP.

Non-AMP: https://prnt.sc/1qxvm27
Amp: https://prnt.sc/1qxvqtu

**Comment by Zabi09** [comment]
Pushed in 1.0.77.21
