### ISSUE TITLE
Getting validation error when multiple words are used in the alt tag. 

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/accelerated-mobile-pages#5135]
Getting validation error when multiple words are used in the alt tag.

Ref screenshot: https://www.awesomescreenshot.com/image/13548346?key=96c52b8dcb63b681863cfb73151e62cd
Ref URL: https://www.saveatrain.com/blog/sd/best-cafes-europe/amp/

Ref: https://secure.helpscout.net/conversation/1617529849/211745?folderId=3575684

**Comment by Zabi09** [comment]
Pushed in 1.0.77.24 update
