### ISSUE TITLE
Issue Export Backup Redux AMP For Wp

### ISSUE THREAD

**Issue by yunvonks** [ahmedkaludi/accelerated-mobile-pages#5137]
Can you Please how to solve these Warning: Use of undefined constant AUTH_KEY - assumed 'AUTH_KEY' (this will throw an Error in a future version of PHP) in /home/fakhrurp/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/inc/extensions/import_export/import_export/field_import_export.php on line 79

Warning: Use of undefined constant SECURE_AUTH_KEY - assumed 'SECURE_AUTH_KEY' (this will throw an Error in a future version of PHP) in /home/fakhrurp/public_html/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/inc/extensions/import_export/import_export/field_import_export.php on line 79

**Comment by Zabi09** [comment]
Pushed in 1.0.77.24 update
