### ISSUE TITLE
Hide bulk tools improvement to hide and show.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/accelerated-mobile-pages#5139]
Use case:- All the categories are selected here to hide https://prnt.sc/1sod7ex and there is one category that needs to be shown on  AMP from here https://prnt.sc/1sodcf7, it should be considered as a priority and not the bulk tool condition.

Note:- When this is ready, make full step documentation on it.

Reference:- https://wordpress.org/support/topic/disable-amp-for-all-except-one-category/

**Comment by Zabi09** [comment]
We have created a filter for you and with the help of the below code you can remove the AMP on all the categories except one

```
add_filter(‘ampforwp_skip_category’ ,’prefix_skip_category’);
function prefix_skip_category($skip){
$cat_id = get_the_category();
//AMP will only work on sports category
if($cat_id[0]->name != ‘sports’){
$skip = true;
}
return $skip;
}
```

You just need to remove the sports from the code and replace it with the name of the category you want to show AMP.

Please do that and let us know

**Comment by Zabi09** [comment]
Pushed in 1.0.77.24 update
