### ISSUE TITLE
Wrong Non-Amp link in Archives

### ISSUE THREAD

**Issue by Lofesa** [ahmedkaludi/accelerated-mobile-pages#514]
Seems is here again.
In templates/design-manager/design-2/footer.php you get this code:
```
  if( is_archive() ) {
    global $wp;
    $ampforwp_backto_nonamp = esc_url( untrailingslashit(home_url( **$wp->request** )).'?nonamp=1' );
  }
```
whych get this on archive pages in the Non-Amp link

[https://spublicos.intersindicalrm.org/category/carm/educacion/amp/?nonamp=1](https://spublicos.intersindicalrm.org/category/carm/educacion/amp/?nonamp=1)

and don´t go to the non-amp version.

**Comment by khaledMohammed000** [comment]
@Lofesa This is a valid issue, thanx for pointing it out :)

**Comment by khaledMohammed000** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/9950804d318af95ef84d3a16b4f8a04d044df6ef

**Comment by ahmedkaludi** [comment]
I need @khaledMohammed000 YOur status on this

**Comment by Lofesa** [comment]
In version 0.9.42 Desing 3 categories don´t have non-AMP button

**Comment by khaledMohammed000** [comment]
@lofesa its fixed
