### ISSUE TITLE
Adding Plausible Analytics compatible for AMP

### ISSUE THREAD

**Issue by VHGoradiya** [ahmedkaludi/accelerated-mobile-pages#5142]
As Plausible Analytics is not present in the AMP vendors list, on doing research Ahmed sir came across a GitHub conversation where a GitHub user has mentioned about an unofficial code to add by which the Plausible Analytics can be added to AMP. We discussed this code with one of our client and it worked perfectly on the website.

As our client has implemented that code on the website and it is working perfectly, I request to add the code to our plugin so another Analytics option is also available for clients.

Venders List - https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/?format=websites#vendors

Code - https://github.com/plausible/analytics/discussions/220#discussioncomment-904022

Ticket - https://secure.helpscout.net/conversation/1633203638/213136?folderId=5170093

**Comment by Zabi09** [comment]
Pushed in 1.0.77.25

**Comment by Zabi09** [comment]
Pushed in 1.0.77.41
