### ISSUE TITLE
Vulnerability found by Virusdie

### ISSUE THREAD

**Issue by altf4444** [ahmedkaludi/accelerated-mobile-pages#5148]
**WP.Redux.3.CVE**

WordPress Redux Framework plugin vulnerabilities. 

Immediate update is highly recommended. Versions: < 4.2.13. **Affected file: redux-framework.php.** 

Type: Broken Access Control. More details: the vulnerability allows an attacker to perform unauthorized actions, such as Arbitrary Plugin Installation and Post Deletion. https://wordpress.org/plugins/redux-framework/#developers , https://wpscan.com/plugin/redux-framework . Update the plugin for the latest version: https://wordpress.org/plugins/redux-framework/

**Comment by MohammedKaludi** [comment]
Hi @altf4444 

Thank you very much for creating the ticket and notifying us about this vulnerability. 

The vulnerability that you are referring to is related  to the **Gutenberg Template Library & Redux Framework** not the core Redux Framework that we are using.

The vulnerability found are under the Gutenberg Blocks templates loading method that is `redux/v1/templates/ REST API namespace` as we are not using any code related to Gutenberg Blocks, we dont have this codebase and thus don't fall under this. 

The main issue is: Arbitrary Plugin Installation and Post Deletion via rest api as it does not have proper authorisation check
https://wpscan.com/vulnerability/e690b887-de5f-4950-bedf-4a9f5fe9b773

Vulnerability description from WPScan:
`The plugin did not correctly check the authorisation in the redux/v1/templates/ REST API namespace, allowing any users with the edit_posts capability (ie contributor and above) to call the endpoints define in it. By using the redux/v1/templates/plugin-install one, they could install plugins from the WordPres repository, or delete arbitrary posts/pages via redux/v1/templates/delete_saved_block`

As mentioned we are not using any redux code that contains Redux Framework's Gutenberg Blocks templates or template manager.

But still we will look into our codebase as we cannot take the vulnerability lightly and update it if required.

Appreciate you taking time and notifying about the issue.

**Comment by altf4444** [comment]
Thanks for the explanation!
