### ISSUE TITLE
plugin support “FV Gravatar Cache” for caching gravatars.

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5149]
Reference ticket: https://wordpress.org/support/topic/add-plugin-support-fv-gravatar-cache-2/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.28

**Comment by Ysery** [comment]
Excuse me for missing. I upgraded to version 1.0.77.30 and it still doesn't work http://sitework.epizy.com/2021/08/25/hello-world/
