### ISSUE TITLE
Non-AMP link in the header logo Homepage [testing]

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#515]
![unwanted amp link in logo](https://cloud.githubusercontent.com/assets/16532359/22722321/24161fd0-eddc-11e6-81b6-b6add5a7ba4f.JPG)
![unwanted amp link in logo 1](https://cloud.githubusercontent.com/assets/16532359/22722322/24c797f6-eddc-11e6-9ea2-7cae60896fd2.JPG)

**Comment by nicholasgriffintn** [comment]
I've been using this feature and it does add the "?noamp=1" tag to my header image.

**Comment by khaledMohammed000** [comment]
Hey guys this is properly tested with design 2 , Fix for the above issue http://take.ms/m8vSb

**Comment by ahmedkaludi** [comment]
I need your opinion on this @khaledMohammed000
