### ISSUE TITLE
AMP rendering default fall back image instead of Featured image if Offload Media Lite-Rewrite Media URLs enable

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5153]
Reference Ticket URL: https://secure.helpscout.net/conversation/1659887408/215242?folderId=4409869

AMP rendering default fallback image instead of Featured image if Offload Media Lite-Rewrite Media URLs enable.
if we remove the default fallback image then it is working perfectly.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.28

**Comment by mohammed-qutubuddin** [comment]
Category, tags feature image is not working on AMP site rendering default fall back image
Reference Screenshot: https://prnt.sc/1y2346j
Make sure that it'll work on the home page also.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.30
