### ISSUE TITLE
Images in posts are getting stretched. [Two Examples] 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#516]
Images in posts are getting stretched. 

1. Rahul Jain's website
2. Sally's website.

**Comment by khaledMohammed000** [comment]
Status : 

1. mailed sally https://secure.helpscout.net/conversation/306796602/10470/?folderId=1060556

**Comment by ahmedkaludi** [comment]
Also, https://wordpress.org/support/topic/custom-homepage-posts-images-get-stretched/

**Comment by ahmedkaludi** [comment]
we are closing this to stay focused
