### ISSUE TITLE
Preloaded image is maximum size and does not use Webp (webp express plugin)

### ISSUE THREAD

**Issue by dreamgeekcoder** [ahmedkaludi/accelerated-mobile-pages#5165]
On a single post, the feature image is always loaded as non .webp and the preloaded image is also always maximum size. The 1200w option
`<amp-img fallback="" data-hero="" src="https://www.test.com/apps/accelerated-mobile-pages/images/SD-default-image.png" srcset="https://www.test.com/apps/accelerated-mobile-pages/images/SD-default-image.png 600w, https://www.test.com/media/2021/10/test.jpg 1200w" width="600" height="338" layout="responsive" alt="test" class="i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built" i-amphtml-layout="responsive" i-amphtml-auto-lightbox-visited=""><i-amphtml-sizer style="display:block;padding-top:56.3333%" slot="i-amphtml-svc"></i-amphtml-sizer></amp-img>`

And

`<img class="i-amphtml-fill-content i-amphtml-replaced-content" decoding="async" alt="test" src="https://www.test.com/wp-content/webp-express/webp-images/uploads/2021/10/test.jpg.webp" srcset="https://www.test.com/wp-content/webp-express/webp-images/uploads/2021/10/test.jpg.webp 600w, https://www.test.com/media/2021/10/test.jpg 1200w" data-hero="" i-amphtml-auto-lightbox-visited="">`

This causes significant page load increase time.

I’ve also noticed an error in the console that is related –

The resource https://www.test.com/media/2021/10/test.jpg.webp was preloaded using link preload but not used within a few seconds from the window’s load event. Please make sure it has an appropriate as value and it is preloaded intentionally.

So it looks like the last image is not going through the function ampforwp_get_featured_image_from_content(); properly to have the Webp express renaming of the URL that happens there…

**Comment by Zabi09** [comment]
Pushed in 1.0.77.30
