### ISSUE TITLE
a feature to keep author name and published time in the above of the content

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5166]
Reference ticket: https://wordpress.org/support/topic/keep-author-name-and-published-time-in-same-line/

**Comment by Zabi09** [comment]
Add this CSS and to keep author name and published time in same line
`.post-date.mob-date {
border: none;
position: relative;
left: 20%;
top: -58px;
text-transform: lowercase;
}
.sp-cnt {
margin-top: -25px;
}
.r-pf h3 {
border: none;
}
.sp-rt .amp-author {
display: none;
}``
