### ISSUE TITLE
Pagination + infinite scroll creates 404 links

### ISSUE THREAD

**Issue by brenovieira** [ahmedkaludi/accelerated-mobile-pages#5167]
Hey guys, AMP for WP pagination is creating a next posts link / button even when there are no more posts to be shown, which leads to a 404 error page.

Example:
https://viajandocomamalarosa.com.br/categoria/gastronomia/amp/

Scroll down until the end of the page, it’ll show on the right the ‘next posts’ button (or ‘Veja mais posts’ in Portuguese) linking to the page https://viajandocomamalarosa.com.br/categoria/gastronomia/amp/page/4/ which doesn’t exist since I only have 26 posts in this category (and showing 10 posts per page, it should show up to the 3th page only).

The issue of pagination + infinite scroll happens on all category pages, see below other examples:
– https://viajandocomamalarosa.com.br/categoria/hoteis/amp/page/2/ (shows link to 5th page even with 37 posts only in this category)
– https://viajandocomamalarosa.com.br/categoria/canoa-quebrada/amp/ (shows link to 4th page with 12 posts only)
…

(I posted the same error on [wp support page](https://wordpress.org/support/topic/amp-pagination-creates-link-to-404-error-page/) a few days ago because I didn't find this github page - just to reference it)

**Comment by Zabi09** [comment]
Pushed in 1.0.77.30
