### ISSUE TITLE
Infinite scroll loading posts from different category when same category is enabled

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5168]
User has enabled same category in infinite scroll but posts from different categories are loading in infinite scroll.

helpscout ref : https://secure.helpscout.net/conversation/1652802564/214745?folderId=5658732

screen-recording ref : https://monosnap.com/file/CbmfHsM5yBiBOzBAP64wcOqoHE4TGh

**Comment by Zabi09** [comment]
Pushed in 1.0.77.30
