### ISSUE TITLE
Service schema tab missing to enter details

### ISSUE THREAD

**Issue by Shivam704** [ahmedkaludi/accelerated-mobile-pages#5169]
A user is facing issues related to option selection in Service Schema. According to the documentation he is not getting those options to select.

I have attached some screenshot for the reference.

Below Screenshot is what documentation shows
https://paste.pics/62409720495b3ffbe4be5aa65e69392a

For detailed information please visit the below link.
https://secure.helpscout.net/conversation/1680245673/216442?folderId=5458148

**Comment by Zabi09** [comment]
https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1568
