### ISSUE TITLE
Uploading Custom image stopped working after installing AMPforWP

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#517]
site: http://landt.co

this custom field stop working
<img width="1027" alt="data" src="https://cloud.githubusercontent.com/assets/15303814/22733376/7e1bc3aa-ee17-11e6-9180-43fbf79fd0c4.png">

got message from console
<img width="817" alt="data 1" src="https://cloud.githubusercontent.com/assets/15303814/22733391/92eb7046-ee17-11e6-86a5-5a9094becc3b.png">

**Comment by nicholasgriffintn** [comment]
That's most likely to be a problem with another plugin or theme to be honest with you, it would be hard to diagnose for the developers with just a screenshot as well.

**Comment by nicholasgriffintn** [comment]
Yeah, that file doesn't exist, no upload folder in the fields destination.

**Comment by khaledMohammed000** [comment]
@ahmedkaludi this folder even does not exist in the actual redux core let alone our plugin,

Fix to this would be to add that file from their Redux theme into out folder

**Comment by khaledMohammed000** [comment]
@MohammedKaludi @ahmedkaludi @MARQAS please confirm with the user once things are working correctly as expected

**Comment by ahmedkaludi** [comment]
@khaledMohammed000 Let's check this with Salient theme in metabox.
