### ISSUE TITLE
Filter to customize the tags 

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5171]
Reference ticket: https://wordpress.org/support/topic/filter-for-allowed_tags/

**Comment by MohammedAkramU7** [comment]
Helpscout reference URL link: https://secure.helpscout.net/conversation/1705151672/218219?folderId=1060556

**Comment by Zabi09** [comment]
Pushed in 1.0.77.30
