### ISSUE TITLE
Getting stylesheet errors while using Qoxag - WordPress News Magazine Theme.

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5177]
Reference screenshot of local: https://prnt.sc/22b7tjw
Users reference: https://prnt.sc/1zvew1f

Reference theme: https://themeforest.net/item/qoxag-wordpress-news-magazine-theme/31582011
Ref ticket: https://wordpress.org/support/topic/external-stylesheets-are-not-supported-except-for-allowed-font-providers-use-t/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.33
