### ISSUE TITLE
HTML <p> tag is shown in the title in category!

### ISSUE THREAD

**Issue by Suleman0498** [ahmedkaludi/accelerated-mobile-pages#518]
![ahmedsupport1](https://cloud.githubusercontent.com/assets/25592669/22772776/a316c76a-eec4-11e6-933b-e7831ad59caa.jpg)
The <p> tag should not be shown in the title as shown below.
Reference:     view-source:http://mentepost.com/entretenimiento/series/amp/

Screenshot:
http://monosnap.com/image/dm65joMtvYOhP5uERSyMnQkbG4N7LF/

Code:
<title>
Categoría: Series<p>Noticias y análisis de los lanzamientos más destacados de series de TV y en línea.</p>
</title>

**Comment by MohammedKaludi** [comment]
Fixed
