### ISSUE TITLE
AMP for WP incompatible or have issues with WP Rocket.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5185]
User ticket:-
Helpscout URL
https://secure.helpscout.net/conversation/1739891408/220914?folderId=5893563

Documentation URL https://docs.wp-rocket.me/article/1326-using-amp-plugins

The user sent the documentation URL where wp-rocket team mention our ampforwp plugin is incompatible.

Wp-rocket mention issues like
Why are WP Rocket’s advanced optimizations not applied on AMP pages?
How to exclude AMP pages from other plugins to prevent issues?

WP-Rocket team reply:-
Helpscout URL 
https://secure.helpscout.net/conversation/1740056173/220944?folderId=5893563

Issues GitHub link
https://github.com/wp-media/wp-rocket/issues/2498 

Issues:-
CDN rewriting
?amp URLs are not being cached by WP Rocket.

**Comment by Zabi09** [comment]
Natalia From Wp Rocket replied:

These compatibility fixes have to be done on our end.

I talked with our Product team and they are planning to add the
compatibility fix in one of our next 4 releases that would be released
within 2 months.

You can follow the updates in our GitHub issue:
https://github.com/wp-media/wp-rocket/issues/2498 [1]

For now, WP Rocket can work with AMP for WP plugin but with limited
compatibility. We recommend excluding /amp/ pages to eliminate the
issues as we share here:
https://docs.wp-rocket.me/article/1326-using-amp-plugins#how-to-exclude
