### ISSUE TITLE
AMP Takeover functionality is not working on the blog posts.

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/accelerated-mobile-pages#5188]
Ref: https://secure.helpscout.net/conversation/1720544803/219536?folderId=4874234

When we set pages off in the settings, show hide is not showing in the blog page, there is a use case where user wanted to show amp with takeover only on blog page but not on all pages.

**Comment by MohammedKaludi** [comment]
After fixing this, the Take Over not working with the Pages.

Need to test throughly.

**Comment by Zabi09** [comment]
Working fine so closing the ticket for now
