### ISSUE TITLE
Current year is not showing in design 1,2,3.

### ISSUE THREAD

**Issue by Shaik-Hafeez** [ahmedkaludi/accelerated-mobile-pages#5190]
Ref: https://secure.helpscout.net/conversation/1747936872/221692?folderId=5884441

I have checked the issue in my localhost in amp theme designs 1,2 and 3 the current year in the footer is not showing only in the swift theme design it shows.  The user is using amp theme design 2 and he wants to add the current year in the footer.

I have used this short-code [ampforwp_current_year] for showing the current year in the footer.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.35
