### ISSUE TITLE
While user using Google Fonts AMP page experience asking to use &display: optional

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5191]
Ticket URL: https://secure.helpscout.net/conversation/1658483792/215156?folderId=1060554

While users using Google Fonts AMP page experience asking to use **&display: optional** to improve FCP.
Reference Screenshot: https://prnt.sc/267ukd3

**Comment by Zabi09** [comment]
Pushed in 1.0.77.35
