### ISSUE TITLE
Embed URLs not working with Amp takeover active.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#5193]
Embed URLs not showing embed content when Amp takeover is active, /embed is getting removed from URL.
Eg: http://localhost/wp/senorita/embed/ is redirecting to http://localhost/wp/senorita/ which is incorrect.
Steps to recreate the issue.
1. Just add any post URL in the editor. eg: http://localhost/wp/senorita/
Also, after the embed content is created, the link is not clickable.
Ref: https://secure.helpscout.net/conversation/1658635264/215172?folderId=4874234

**Comment by Zabi09** [comment]
Pushed in 1.0.77.35

**Comment by Zabi09** [comment]
Pushed in 1.0.77.37.1
