### ISSUE TITLE
VKontakte social media not working in social media profile links under social sharing settings

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5196]
VKontakte social media not working in social media profile links under social sharing settings
video - https://monosnap.com/direct/EdDuN41lleoCLS7ZdcdrvsZCkiYRSf
ref - https://secure.helpscout.net/conversation/1751588068/221963?folderId=4459751

**Comment by Zabi09** [comment]
Pushed in 1.0.77.35
