### ISSUE TITLE
Fatal error with AMP optimizer(Particular User) and PHP Deprecated issue(Globally).

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5197]
Reference URL: https://secure.helpscout.net/conversation/1753497884/222111?folderId=1060556

1. Fatal Error on the log if the AMP optimizer is enabled. (Particular User's end)
#2 /home2/gaadiwa/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/Optimizer/Transformer/AmpRuntimeCss.php(139):
AmpProject\Optimizer\Transformer\AmpRuntimeCss->inlineCss(Object(AmpProject\Dom\Element), '') #3 /home2/gaadiwa/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/Optimizer/Transformer/AmpRuntimeCss.php(101):
AmpProject\Optimizer\Transformer\Am in /home2/gaadiwa/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/RemoteRequest/CurlRemoteGetRequest.php on line 142

2. PHP Deprecated issue if the category base removes and Tag base remove option is enabled. (This issue is occuring globally re-created on a local host).
12-Jan-2022 08:01:49 UTC] PHP Deprecated:  tag_rewrite_rules is <strong>deprecated</strong> since version 3.1.0! Use post_tag_rewrite_rules instead. in /home/customer/www/garage3.magazine3.com/public_html/wp-includes/functions.php on line 5586

**Comment by 77naveenop** [comment]
All we can provide you is the following error log recorded on the server-side:
[Mon Jan 17 12:14:12.078171 2022] [php7:error] [pid 20062] [client 172.70.174.159:62584] PHP Fatal error: Uncaught Error: Class 'AmpProject\\Exception\\FailedToGetFromRemoteUrl' not found in /var/www/html/retro/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/RemoteRequest/CurlRemoteGetRequest.php:142\nStack trace:\n#0 /var/www/html/retro/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/RuntimeVersion.php(78): AmpProject\\RemoteRequest\\CurlRemoteGetRequest->get('https://cdn.amp...')\n#1 /var/www/html/retro/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/Optimizer/Transformer/AmpRuntimeCss.php(163): AmpProject\\RuntimeVersion->currentVersion(Array)\n#2 /var/www/html/retro/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/Optimizer/Transformer/AmpRuntimeCss.php(139): AmpProject\\Optimizer\\Transformer\\AmpRuntimeCss->inlineCss(Object(AmpProject\\Dom\\Element), '')\n#3 /var/www/html/retro/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/Optimizer/Transformer/AmpRuntimeCss.php(101): AmpProject\\Optimizer\\Transformer\\AmpRuntimeCss->addStaticCss(Object(Am in /var/www/html/retro/wp-content/plugins/accelerated-mobile-pages/includes/vendor/tool/RemoteRequest/CurlRemoteGetRequest.php on line 142

Reference helpscout URL - https://secure.helpscout.net/conversation/1760127616/222660?folderId=5893230

**Comment by Zabi09** [comment]
https://wordpress.org/support/topic/uncaught-error-class-ampprojectexceptionfailedtogetfromremoteurl/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.35
