### ISSUE TITLE
Need to make compatibility with Cloudinary

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/accelerated-mobile-pages#5198]
User moving all the images to Cloudinary found that AMP pages doesn't display images. It does not use Cloudinary URL to display the images and it still uses WP location.

Ref: https://secure.helpscout.net/conversation/1729925190/220246?folderId=4874234

**Comment by Zabi09** [comment]
Github is for tested and re-creatable bugs, for the technical issues, we will help you via website
