### ISSUE TITLE
Issue is in Sitemap AMP page.

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/accelerated-mobile-pages#5200]
Description:- User facing the issue on the plugin when he activated this settings https://prnt.sc/26coctv on the advanced settings of the plugin then semrush detected 403 broken internal links and AMP page caused 403 internal broken links.
It adds amp in every link of sitemap.xml page here you can see in this screenshot https://prnt.sc/26coln2.
Issue is not recreate on our end and this issue is only at the user end.

Ref:- https://secure.helpscout.net/conversation/1713274809/218951?folderId=4874234

**Comment by Zabi09** [comment]
His pages were cached and due to that he was facing this issue not everything looks good on his website, So closing the ticket
