### ISSUE TITLE
Gdpr form submission issue

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5201]
Helpscout URL
https://secure.helpscout.net/conversation/1756069738/222304?folderId=5893563

Issue URL 
https://www.androidsis.com/tv-box-android-para-que-sirve/amp/

Description:- 
When the user clicks on GDPR form submission, a pop-up should appear. server is password-protected and asks for the password when the user tries to submit.

screenshot:-
https://prnt.sc/26f5x5h

**Comment by Zabi09** [comment]
incorrect ticket
