### ISSUE TITLE
Images not displaying when added through AMP page builder 

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#5204]
If we are using AMP pagebuilder and add Images, those image are not displaying in AMP.

Helpscout ref: https://secure.helpscout.net/conversation/1759901808/222647/
Localhost ref: https://monosnap.com/file/3mf7LYmIHoTlt4lQzVa46dSOr6w5UJ

**Comment by Zabi09** [comment]
The images were not appearing due to an improper SSL certificate
