### ISSUE TITLE
Errror getting in /plugins/accelerated-mobile-pages/components/featured-image/featured-image.php, on line 77

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5207]
The user telling that, in /plugins/accelerated-mobile-pages/components/featured-image/featured-image.php, on line 77. If he put “” in the attribute layout=responsive., it's working and If he doesn’t add those “"then it does not work.

Reference ticket: https://wordpress.org/support/topic/amp-img-alt-problems-with/page/2/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.36
