### ISSUE TITLE
If the server-side cache is aggressive, then the pagination URL ?amp=1 is redirecting to non-AMP

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5208]
Ticket URL: https://secure.helpscout.net/conversation/1759142952/222578?folderId=1060556

If the server-side cache is aggressive, then the pagination URL ?amp=1 is redirecting to non-AMP.
Due to this canonical issue occurring in Google Search Console

So need to change /?amp to /amp.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.36
