### ISSUE TITLE
JavaScript issue with nitro pack and web stories combination.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5209]
Helpscout URL:-
https://secure.helpscout.net/conversation/1769317619/223499?folderId=5893563

Issue URL:-
https://www.kotastonesupplier.com/amp/
https://www.kotastonesupplier.com/web-stories/kota-stone-flooring/ ( Find URL in Google search console)

Description:-
when a user uses nitro pack and web stories combination amp validator showing error "custom javascript not allowed". recreate on local also same error shows.

Issues screenshot:-
https://monosnap.com/direct/wRaMwuVeAmFH48ZJBSXqpq86Rmn0ZY (Amp Dev tool)
https://monosnap.com/file/Ad9Krob2h7Yv37StsDRVqw6qXAZakM ( with an amp in source code javascript add)
https://prnt.sc/26gy3eb ( without an amp )
https://monosnap.com/file/YKYfHXeHJtx2vPkn67GclUunUFO7PJ ( google search console)

**Comment by Zabi09** [comment]
incorrect ticket
