### ISSUE TITLE
Need to make compatibility of FireWork

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5210]
Reference Ticket: https://secure.helpscout.net/conversation/1759142952/222578?folderId=4409869

Need to make compatibility of FireWork
Use Case: https://dev-gulte.trypl.com/movienews/140101/rrr-trailer-rrr-memes-shake-the-internet/
Reference: https://docs.firework.tv/web/components/embed-firework-feed

**Comment by Zabi09** [comment]
Pushed in 1.0.77.37
