### ISSUE TITLE
AMP page is valid with warnings (Error in required structured data element)

### ISSUE THREAD

**Issue by Empathyfine** [ahmedkaludi/accelerated-mobile-pages#5214]
Hello @ahmedkaludi and @Zabi09 please I need your assistance of the following errors I see in my Google Search Console;

**1. AMP page is valid with warnings

2. Error in required structured data element**

Here is one of the affected pages => [Here](https://www.fanslite.com/waptrick-mp3-download-free-waptrick-music-waptrick-videos-waptrick-games-waptrick-mp3-music/)

Please help me as this has affected the page and other pages negatively in Google search result.
Thanks and looking forward to hearing from you!

**Comment by Zabi09** [comment]
@Empathyfine I have checked your issue and found that you are facing this issue due to schema plugin and not with AMPforWP so I have created the ticket on GitHub - https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1615 and its going to get fixed here
