### ISSUE TITLE
Unhandled preg_match fatal error in SiteHealth

### ISSUE THREAD

**Issue by Bielousov** [ahmedkaludi/accelerated-mobile-pages#5215]
AMP v2.2.1
WP v5.9
PHP v8.0-fpm
Nginx v1.14.0 (Ubuntu)

When AMP plugin is active, navigating to the WP Site Health page, or any AMP settings page in WP Admin throws an error:
![Screen Shot 2022-02-10 at 10 17 56 AM](https://user-images.githubusercontent.com/1741272/153473040-4c14792d-ee77-430f-8d28-dbccf2fe0ebb.png)

```
[error] 27680#27680: *1869 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /wp-content/plugins/amp/src/Admin/SiteHealth.php:548
Stack trace:
#0 /wp-content/plugins/amp/src/Admin/SiteHealth.php(548): preg_match()
#1 /wp-content/plugins/amp/src/Admin/SiteHealth.php(634): AmpProject\AmpWP\Admin\SiteHealth::AmpProject\AmpWP\Admin\{closure}()
#2 /wp-content/plugins/amp/src/Admin/SiteHealth.php(491): AmpProject\AmpWP\Admin\SiteHealth->check_for_page_caching()
#3 /wp-content/plugins/amp/src/Admin/OptionsMenu.php(230): AmpProject\AmpWP\Admin\SiteHealth->get_page_cache_detail()
#4 //wp-includes/class-wp-hook.php(307): AmpProject\AmpWP\Admin\OptionsMenu->enqueue_assets()
#5 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /wp-includes/plugin.php(474): WP_Hook->do_action()
#7 /wp-adm" while reading response header from upstream, client: *****, server: bielousov.com, request: "GET /wp-admin/admin.php?page=amp-options HTTP/1.1", ...
```

The actual AMP pages appear to be generated ok, with some features of the unsupported plugin not available, as expected (e.g. no player for the unsupported Embed Plus Plugin for YouTube plugin).

### This is a regression observed after:
- update to v5.9
- new plugin added ([Embed Plus Plugin for YouTube](https://wordpress.org/plugins/youtube-embed-plus/))
- some changes to the custom theme

Disabling the Embed Plus Plugin for YouTube plugin doesn't fix the issue, but disabling the AMP plugin does (for the Site Health page).

### Expected behaviour
The `preg_match` in the SiteHealth should have an appropriate type check and/or graceful error handling and should not crash the WP Admin interface. The encountered error could be added to the SiteHealth results though.

**Comment by Zabi09** [comment]
@Bielousov I have checked your concern and found that you are using this AMP plugin - https://wordpress.org/plugins/amp/ - 2.2.1 version and not our AMPforWP plugin.

Please create the ticket on their GitHub repo and why don't you try our AMPforWP plugin and if you face any issues then we are here to fix all your issues
