### ISSUE TITLE
AMP Setup Buttons are not clickable in the Microsoft Edge Browser.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#5218]
AMP Setup Buttons are not clickable in the Microsoft Edge Browser.
Ref: https://secure.helpscout.net/conversation/1779811703/226714?folderId=5893563

**Comment by Zabi09** [comment]
Working on my end - https://ibb.co/NY0gZ3m
Github is for tested and re-creatable bugs, for the technical issues, we will help you via website
