### ISSUE TITLE
Unable to connect to Matomo analytics

### ISSUE THREAD

**Issue by mohmmadasim** [ahmedkaludi/accelerated-mobile-pages#5221]
Ref: https://secure.helpscout.net/conversation/1788290145/227464?folderId=5633920

The problem is when the URL link of the Matomo analytics is been added in the **Enter Your Piwik Analytics URL** section  it is stripping away the "=" operator in the URL 

https://monosnap.com/file/mpVnzIKrFgbP50icd7PdOoWJD7CeKQ

**Comment by Zabi09** [comment]
Pushed in 1.0.77.37
