### ISSUE TITLE
Font style not loading correctly on first page load

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/accelerated-mobile-pages#5224]
Front style is not loading correctly on first page load, if we refresh the page, correct font style is been displayed. same issue is occurring while we try to access the site via Google search

helpscout ref: https://secure.helpscout.net/conversation/1789392946/227547?folderId=4544752
issue ref: https://monosnap.com/file/k8oZAQQsFjCtmgxC32aXFRLVP51Gx4
https://monosnap.com/file/8Ua3M7rx3WPYfTTBo8sX95WFyWv5RA

**Comment by Zabi09** [comment]
Pushed in 1.0.77.39
