### ISSUE TITLE
Need to make GDPR according to the new Guidelines

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/accelerated-mobile-pages#5225]
Ref:- https://secure.helpscout.net/conversation/1785012816/227169?folderId=4874234

Need to add new categories of the cookies according to the new European provisions of January 2022.

link:- https://amp.dev/documentation/examples/user-consent/granular_user_consent/?format=websites

**Comment by Zabi09** [comment]
Pushed in 1.0.77.39
