### ISSUE TITLE
Unable to modify the H1-H6 size for mobile devices

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5227]
User is unable to modify the size for h1-h6 for mobile phones while its working for desktop.

Help scout URL -: https://secure.helpscout.net/conversation/1803132558/228676?folderId=5893230

**Comment by Zabi09** [comment]
https://ampforwp.com/tutorials/article/how-to-modify-the-h1-h6-size-for-mobile-devices/
