### ISSUE TITLE
Custom Shortcodes Eliminated/Removed

### ISSUE THREAD

**Issue by jigar-burda** [ahmedkaludi/accelerated-mobile-pages#5229]
Hi,

I have created a plugin which allows editors to create form and paste the shortcode of the form in the post. The shortcode works fine for non-amp pages but the shortcode is getting eliminated/removed from the content for AMP pages. Could someone please help me on how to fix it?

**Comment by MohammedKaludi** [comment]
@jigar-burda Usually it should work, what type of content are you adding through shortcode?

Are you adding the Shortcode in the Custom AMP Editor or in regular editor?

**Comment by jigar-burda** [comment]
@MohammedKaludi as mentioned earlier I have created a shortcode which renders a form tag with inputs tags. I am adding shortcode in regular editor.

**Comment by Zabi09** [comment]
@jigar-burda if your shortcode consists of a form tag or other HTML tags which are not allowed as per AMP guidelines then our blacklist sanitizer will strip it and if you really need those tags then you need to override it by simply adding the class name 'ampforwp-form-allow' for sanitizing the form and once you add this class then it will not be removed in AMP.

You can manually add that class or you can also add the below code which will automatically add the class for you

`add_filter('the_content','new_form_content');
function new_form_content($content){
 if ( function_exists( 'ampforwp_is_amp_endpoint' ) && ampforwp_is_amp_endpoint() ) {
 $content = preg_replace('#<form action="(.*?)" (.*?)>#ius', '<form action-xhr="$1" class="ampforwp-form-allow" $2 target="_blank">', $content);
 
 }
return $content;
}`

Please add it and let us know
