### ISSUE TITLE
AT internet  does not support for our AMP .

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5233]
Hi 
The issue is CX  currently using AMP for WP on his blog. But since he is using AT internet as an analytics tool, he has no stats coming from amp content. 

 ref=https://secure.helpscout.net/conversation/1808013475/229545?folderId=6370795

Since AT  internet does not support our AMP plugin but it Support AMP.
 https://developers.atinternet-solutions.com/general-en/tagging-deletion/?kw=AMP%20INSA#amp-and-instant-article-tags_17

**Comment by Zabi09** [comment]
Pushed in 1.0.77.39
