### ISSUE TITLE
AMP option panel not working.

### ISSUE THREAD

**Issue by DeheemB** [ahmedkaludi/accelerated-mobile-pages#5236]
1. Using Bertha AI( https://wordpress.org/plugins/bertha-ai-free/ ) plugin  AMP setup not working.
2. Using Tour Booking Manager For Woocommerce( https://wordpress.org/plugins/tour-booking-manager/ ) plugin  AMP setup redirecting to 404 error.
 
Reference link  https://secure.helpscout.net/conversation/1803983162/228824?folderId=6406114

**Comment by Zabi09** [comment]
Pushed in 1.0.77.39
