### ISSUE TITLE
If the response is not available, then don't display the ads

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#5237]
1. Need to add the CDN URL instead of Heroku link. i.e, https://cdn.tpdads.com/json/amp-tags/337.json
2. Fall back

If a plugin user enters a publisher ID for which we have no match, the CDN returns a 404 response, e.g. 
https://cdn.tpdads.com/json/amp-tags/abcde.json
In such a case could the ad insertion be aborted? In the case of the herokuapp it returns empty arrays but it's difficult to achieve that with a CDN.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.40
