### ISSUE TITLE
Header and footer showing twice in new infine scroll

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/accelerated-mobile-pages#5238]
Ref:- https://secure.helpscout.net/conversation/1752450699/222045?folderId=4874234

By the help of this tutorial, we will fix the issue:- https://amp.dev/documentation/components/amp-next-page/#preventing-page-element-duplication

**Comment by Zabi09** [comment]
Pushed in 1.0.77.39

**Comment by Zabi09** [comment]
https://secure.helpscout.net/conversation/1752450699/222045?folderId=4874234

**Comment by Zabi09** [comment]
Pushed in 1.0.77.41
