### ISSUE TITLE
Remove the individual refresh checker button automatic to manual

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5240]
Helpscout:-
https://secure.helpscout.net/conversation/1817166921/231228?folderId=5893563

Description:-
Remove the individual refresh button automatically to manual. when the user clicks on the refresh button number of day to renew status are shown. but we only check once a day if we do twist popup are visible try to next day. 

Issue URL
https://www.loom.com/share/1ca0e15fd52a4649a49f138a63534af7

**Comment by Zabi09** [comment]
Pushed in 1.0.77.40
