### ISSUE TITLE
Duplicate tag that shouldn’t be

### ISSUE THREAD

**Issue by Ysery** [ahmedkaludi/accelerated-mobile-pages#5241]
<img src="https://i116.fastpic.org/big/2022/0321/8b/6faf41ffbf13d4c082e9f2383d376a8b.png">

I created a test site to demonstrate the problem. Everything is clearly visible there http://lefty.p-host.in/uncategorized/hello-world/amp/
I also recorded a video demonstrating the problem https://youtu.be/H0Ig7xtm9yw

**Comment by DanBusc** [comment]
The same on my site with noscript tags for weeks now. I did a zoom session with the developer, showed the problem, sent the plugin that supposedly causes it. No solution so far.
In the meantime, the plugin is so slow that I will deactivate it. The normal page loads in 1.5 seconds, AMP pages sometimes need 4 seconds. Something is wrong there.

**Comment by MohammedKaludi** [comment]
@Ysery the issue has been fixed in the latest update

**Comment by MohammedKaludi** [comment]
> The same on my site with noscript tags for weeks now. I did a zoom session with the developer, showed the problem, sent the plugin that supposedly causes it. No solution so far. In the meantime, the plugin is so slow that I will deactivate it. The normal page loads in 1.5 seconds, AMP pages sometimes need 4 seconds. Something is wrong there.

@DanBusc 
can you please tell with whom you did the zoom session so that I can talk with him and find out what exactly the issue is?

**Comment by DanBusc** [comment]
Hi Mohammed,

sure, with Kunal was the session.

**Comment by MohammedKaludi** [comment]
Kunal is on leave for last few days because of bad health.
I will get the update from him and get back to you.

Meanwhile I'm closing this ticket and and will continue the communication over the mail.
