### ISSUE TITLE
Need to make Compatibility with GenerateBlocks plugin

### ISSUE THREAD

**Issue by DeheemB** [ahmedkaludi/accelerated-mobile-pages#5248]
AMP for WP is not displaying the background image of the container block.
AMP  for WP screenshot: https://prnt.sc/k7uLmk5Icr8X
Non AMP screenshot: https://prnt.sc/AnSTMgSWGDSc

Ticket: https://secure.helpscout.net/conversation/1837110143/235433?folderId=6406114

**Comment by Zabi09** [comment]
Pushed in 1.0.77.41
