### ISSUE TITLE
Incompatible with bootstrap plugin

### ISSUE THREAD

**Issue by Suleman0498** [ahmedkaludi/accelerated-mobile-pages#525]
AMPforWP plugin is incompatible with bootstrap plugin

Reference: 
http://monosnap.com/image/LTAvib1i0BBvxyNxt6zu8fUPSsILxB/
https://2ix7v73eb2th1fhz401iceel-wpengine.netdna-ssl.com/wp-content/plugins/wordpress-bootstrap-css/resources/bootstrap-3.3.7/css/bootstrap.min.css

**Comment by MohammedKaludi** [comment]
Need to test with the PLUGIN: https://wordpress.org/plugins/wordpress-bootstrap-css/

**Comment by MohammedKaludi** [comment]
Tested with both minification options.
