### ISSUE TITLE
REHub/Content Egg causing a CSS break On AMP Version.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5250]
REHub Theme with Content Egg plugin is breaking the CSS of Comparision Table made using Content Egg plugin on the AMP version of the website.

Ref website URL: https://www.topmixergrinder.in/elgi-ultra-grind-plus-vs-butterfly-hippo-wet-grinder-comparison/?amp

Ref ticket: https://secure.helpscout.net/conversation/1842013027/236310?folderId=6406109

**Comment by Zabi09** [comment]
Pushed in 1.0.77.42
