### ISSUE TITLE
Undefined index error

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5251]
Error Notice: Undefined index: amp-license in /home/-II-/-II-/wp-content/plugins/accelerated-mobile-pages/includes/options/admin-config.php on line 8995

Reference ticket: https://wordpress.org/support/topic/problem-after-update-75/

**Comment by Zabi09** [comment]
Pushed in 1.0.77.42

**Comment by WesleyCarnicl** [comment]
I am getting this issue with the latest version of your plugin.
