### ISSUE TITLE
amp url needs to be redirected after the permalink is updated

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#5255]
when a post is updated with the permalink, the older url is not getting redirected to the new amp url

Ref: Telegram (asghar)

**Comment by pradipshende** [comment]
We have checked the post permalink query but we didn't find any issue regarding the post permalink in AMP please check the link https://monosnap.com/file/WXMKC9j9JQNSXvLBw7n8CnM9DZ25XC
