### ISSUE TITLE
AMP Validation issue with TOC+ latest version 2106

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5256]
AMP Validation issue with TOC+ latest version 2106
https://prnt.sc/MsOZhBB34pBU

Helpscout URL: https://secure.helpscout.net/conversation/1805739268/229117/

**Comment by Zabi09** [comment]
This AMP validation issue is due to TOC Plus for AMP and not related to the core AMP plugin so it's going to get fixed in our extension Trello board
