### ISSUE TITLE
Image Gallery Carousel in AMP does not change the gallery view in posts/pages.

### ISSUE THREAD

**Issue by DeheemB** [ahmedkaludi/accelerated-mobile-pages#5259]
Ticket: https://secure.helpscout.net/conversation/1858681338/239140?folderId=6406114

On selecting gallery design to any three settings
1. Carousel
2. Carousel with Thumbnail 
3. Grid With Lightbox
It is not changing the Gallery view in AMP.
https://prnt.sc/4uLRYFfU8RnG

**Comment by Zabi09** [comment]
- [ ] Gallery working on posts only but not on pages 

- [ ] Captions are not showing in AMP but showing in non amp - https://prnt.sc/6hM1yjnyGMnt

- [ ] Validation error after enabling Carousel with Thumbnail option - https://prnt.sc/q4uMsVL3wvi-

- [ ] Thumbnails are not properly aligned - https://prnt.sc/q4uMsVL3wvi-

- [ ] Backgroud color applying on images with Grid With Lightbox option -  https://prnt.sc/CqxH_6hRdgBD

**Comment by Zabi09** [comment]
- [ ]  Validation error after enabling Carousel with Thumbnail option - https://prnt.sc/q4uMsVL3wvi- ( Tested this issue and found that the validation error is coming only when we add an SVG image )
- [ ] Background color applying on images with Grid With Lightbox option - https://prnt.sc/CqxH_6hRdgBD (Still not fixed)

And why you have updated the changelog again with the same tickets and a new version number?
