### ISSUE TITLE
Preload Funtionality not working

### ISSUE THREAD

**Issue by Marghoob123** [ahmedkaludi/accelerated-mobile-pages#5260]
Was adding this link ( href="https://images.indiafantasy.com/wp-content/uploads/20220426170152/MyTeam11-M_optimized.webp ) ( https://prnt.sc/bDclfELE8-_q ) in preload and it was also showing in the source code ( https://prnt.sc/nHHoAPqSjN4u ) but the preload issue was occurring in the Page Speed Insight ( https://prnt.sc/FaOs97c7dkte )

then we added ( <link rel="preload"  as="image" href="https://images.indiafantasy.com/wp-content/uploads/20220426170152/MyTeam11-M_optimized.webp"crossorigin> ) in the Enter HTML in HEAD and got it fixed . ( https://prnt.sc/8BKCzceMO4BD )   

So the difference between both the preload link is that after adding the **as="image"** attribute manually, we got the fix.

**Comment by Zabi09** [comment]
Pushed in 1.0.77.44
