### ISSUE TITLE
compatibility issue with ubermenu3 plugin.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5264]
Helpscout URL:-https://secure.helpscout.net/conversation/1863435449/239773?folderId=5893563

Description:-
menu's subchild item does not expand.

Issue video & screenshot:-
https://share.tbsmo.com/QwuLpYKz
https://monosnap.com/direct/e1rrschP2NYyemCUYL3s9KEE3AmjyP

User website URL:-
https://dev.choosenj.com/blog/why-israeli-companies-are-choosing-new-jersey/?amp

**Comment by Zabi09** [comment]
Pushed in 1.0.77.46
