### ISSUE TITLE
Specific " HTML attributes " are not working in the AMP page builder modules

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5268]
For example, if we are adding this below code in " text " module of AMP page builder, so that if someone clicks the contact number, it can redirect to the dialer - 
 ref ode - https://monosnap.com/direct/hnDnyQcNuPN5Ce0ySduGgrHUe6cx7F

But, In the front end, we can't see any link generating for that particular text. In this case, if someone clicks the number "+47 333 78901", it should be clickable and redirects to the dialler but actually there is no link in it and hence, not clickable.

ref video - https://monosnap.com/direct/OJuNFDT20lI4IQ8tz7bttn7oztfELb

ref ticket - https://secure.helpscout.net/conversation/1864392867/239908?folderId=4459751

**Comment by Zabi09** [comment]
Pushed in 1.0.77.44
