### ISSUE TITLE
Instagram embed is not working

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5269]
When we try to embed any Instagram post, it is not loading. It just shows loader but doesn't load the post.

Reference URL -: https://secure.helpscout.net/conversation/1885965738/242877?folderId=5893230

Reference screenshot -: https://monosnap.com/direct/LIhQehlmuQu8L6zPzwFz13F2H6QHxq

**Comment by Zabi09** [comment]
Pushed in 1.0.77.44
