### ISSUE TITLE
Custom AMP editor for Custom post types

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#527]
We need Custom AMP editor for custom post types, many users are asking for it.

**Comment by khaledMohammed000** [comment]
Look here https://github.com/ahmedkaludi/amp-custom-post-type/commit/c7a78577990c64f717152201d93bf7c6bec100a4

**Comment by MohammedKaludi** [comment]
Fixed in : https://github.com/ahmedkaludi/amp-custom-post-type/commit/86b4c340bce26bfcd462f8133c88c182303ea0ed

**Comment by MohammedKaludi** [comment]
Needs testing

**Comment by cchase-spacesaver** [comment]
Could you add me to have access to the Repository for this case?
cchase@spacesaver.com

Thank you,

Carla Chase | Marketing Team Lead
Spacesaver Corporation
DIRECT:: 920.563.0764 |  TOLL:: 800.492.3434
FAX:: 920.563.2702 | WEB:: www.spacesaver.com<http://www.spacesaver.com/>
_____________________________________________
ONE TEAM ONE VISION

**Comment by ahmedkaludi** [comment]
@cchase-spacesaver 
Can you please let me know what's the purpose? Are you wanting to contribute to the code? But you can do that with pull requests.


Regards,
Ahmed
