### ISSUE TITLE
Need to add the compatibility of WP_table_builder 

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5270]
Tables are not working in the /amp version of the site, it is showing content as it is added.

Reference ticket -: https://secure.helpscout.net/conversation/1851188050/237962?folderId=5893230

Reference screenshot -: 
    /amp -: 
![Screenshot (200)](https://user-images.githubusercontent.com/78167698/170430706-53fdca45-bb55-4078-89c7-48ffe477f9dd.png)
![Screenshot (201)](https://user-images.githubusercontent.com/78167698/170430751-cdb42aec-1304-40eb-a9db-89503ec0a88a.png)

Non-amp -: 
![Screenshot (202)](https://user-images.githubusercontent.com/78167698/170430815-a77c923f-0f61-4781-8915-4fc9f36c5052.png)

**Comment by Zabi09** [comment]
Pushed in 1.0.77.44
