### ISSUE TITLE
 While using Divi theme Amp page is showing error (at user's end)

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5271]
While using the Divi theme classic builder embed URL Amp page shows an error.

Error ref:https://prnt.sc/giek591FMBS7
 
 ref:https://secure.helpscout.net/conversation/1893843739/243977?folderId=6370795

**Comment by ankit644** [comment]
I have tested it thoroughly and it is perfectly working so I am closing this ticket.

**Comment by ankit644** [comment]
I have tested it thoroughly and it is perfectly working at our end so I am closing this ticket.
