### ISSUE TITLE
Conflict issue with WPML

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5274]
Freescout:-
https://magazine3.in/conversation/5181?folder_id=21

Description:-
AMP takeover beta option blocks Automatic Translation in WPML

Issue Screenshot:-
https://prnt.sc/dfbVQZXlo8l7

WPML team send the code:-
add_filter('ampforwp_is_amp_endpoint_takeover', function ($return) {
if (is_user_logged_in() && !empty($_GET['wpml-app'])) {
return false;
}
return $return;
});

**Comment by pradipshende** [comment]
Pushed in 1.0.77.45
