### ISSUE TITLE
Debug Warnings - Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5277]
freecout URL:- https://magazine3.in/conversation/5744?folder_id=21

Description:-
PHP Warning:  Trying to access array offset on value of type null in /wp-content/plugins/accelerated-mobile-pages/includes/redirect.php] wp-content/plugins/accelerated-mobile-pages/includes/redirect.php) on line 227

**Comment by pradipshende** [comment]
Pushed in 1.0.77.45
