### ISSUE TITLE
Parse error while installing our plugin

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#528]
Parse error: syntax error, unexpected T_FUNCTION in /home/content/65/8239965/html/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-2/style.php on line 3

and this: Notice: Undefined index: ampforwp_amp_mode in /home/content/65/8239965/html/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php on line 26

Notice: Undefined index: ampforwp-custom-type in /home/content/65/8239965/html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 118

Notice: Undefined index: paged in /home/content/65/8239965/html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 127

**Comment by ahmedkaludi** [comment]
We are not facing this at the moment. so we'll close it for now.
