### ISSUE TITLE
Need to Make compatibility with conditional field pro plugin

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5282]
Freescout- https://magazine3.in/conversation/6254?folder_id=21

Description:-
Users use contact form 7 and add conditional fields with the help of a plugin. However, it only works in non-amp.

Issue video:-
https://monosnap.com/direct/jLI9cqX6Bdcp79xosYi8BTdMhrFKCv

Issue URL:-
https://silent-disco.it/xxxyyzz/amp/

**Comment by ahmedkaludi** [comment]
It's an extension issue, moved to Trello board: https://trello.com/c/JkaiMQJP/2681-contact-form-7-conflicts-with-add-conditional-fields-pro-plugin
