### ISSUE TITLE
"Read more" Text is not translatable via pot file

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5285]
Ref free scout: https://magazine3.in/conversation/8985?folder_id=29

Need to Add the option Read more in the ampforwp.pot file. 

Ref screenshot: https://prnt.sc/-wp8s2q5PHgj

Recreate step.
1) I have downloaded the software poedit.net
2) Then follow the steps from this video https://ampforwp.com/tutorials/article/how-to-use-pot-file-to-translate-amp-settings-panel/

**Comment by Zabi09** [comment]
Going to get fixed in this ticket - https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4362
