### ISSUE TITLE
Make it compatible with existing Embed Instagram code that user have in his website

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5289]
Ref:https://magazine3.in/conversation/10456?folder_id=29

User has around 19000 posts, so he doesn't want to edit each and every post, below shown code is added in the users website and it is working fine with AMP by Automattic plugin.

Need to make sure that our plugin is also compatible with below code.

"<blockquote class="instagram-media" data-instgrm-permalink="[http://instagram.com/p/CfKj60mjjsq"](http://instagram.com/p/CfKj60mjjsq) data-instgrm-version="8" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"></blockquote>"
<script async="" defer="" src="//[http://www.instagram.com/embed.js"></script>](http://www.instagram.com/embed.js)

Ref URL: https://cookinsta.com/%D8%A7%D8%AD%D8%A8-%D9%85%D9%8A%D9%84%D9%83-%D8%B4%D9%8A%D9%83-%D8%A7%D9%84%D8%A7%D9%88%D8%B1%D9%8A%D9%88-%D9%88%D8%A7%D9%86%D8%AA%D9%85-%D8%9F/?amp

**Comment by ramoooi** [comment]
hello just to let you know the issue is not yet fixed

**Comment by Zabi09** [comment]
Pushed in 1.0.77.47
