### ISSUE TITLE
There is an error with the HTML attribute 'data-video id's in the tag 'amp-youtube.'

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5292]
When a YouTube link is embedded in the classic editor, the error "Invalid value for HTML attribute 'data-videoid' in tag 'amp-youtube" appears. The problem is with the most recent version of AMP, 1.0.77.46. If we roll back the plugin to AMP Version 1.0.77.45, the issue is resolved. I have fixed the issue on the user end by doing a rollback of the plugin.

screenshot ref: https://prnt.sc/zBGZrD0DmdCi

Two users are facing the same issue. I have added the reference URL of the free scout.
1)https://magazine3.in/conversation/12649?folder_id=29
2)https://magazine3.in/conversation/9540?folder_id=29

**Comment by Zabi09** [comment]
Pushed in 1.0.77.47
