### ISSUE TITLE
Need to Add compatibility with Inline Related Post plugin by data443

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5296]
User adding button using Inline related post plugin but in the amp version of post it is not loading correctly ( CSS is not loading).

Reference Ticket -: https://magazine3.in/conversation/17010?folder_id=23

Reference Image -: 
![Desktop 2022-07-14 20-53-40](https://user-images.githubusercontent.com/78167698/179169702-decf1279-54a2-42ab-8910-7771a1b1596e.png)

**Comment by Zabi09** [comment]
Pushed in 1.0.77.48

**Comment by 77naveenop** [comment]
Issue still occurs.

Reference ticket -: https://magazine3.in/conversation/17010?folder_id=4
