### ISSUE TITLE
Conflict issue with All in One SEO latest update.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5299]
References ticket URL:- https://magazine3.in/conversation/21645?folder_id=21

Description:-
AMP page builder is no longer displayed/editable in the post section with All in One SEO v.4.2.3.1 version.

Issue screenshot:-
https://prnt.sc/9hdJb4yf7PPz

User sends CSS code AISEO modal CSS is overriding the AMP CSS.
.modal-mask .modal-wrapper .modal-container .modal-body {
overflow-y: auto;
overflow-x: hidden;
max-height:
80vh
;
position: relative;
}

this is now overrides admin-amp-page-builder.css?ver=1.0.77.47: position:absolute

.modal-mask .modal-body {
overflow-y: auto;
height: 92%;
​position: absolute;
left: 0;
top: 0;
left:
200px
;
right:
0px
;
}

**Comment by Zabi09** [comment]
Pushed in 1.0.77.48
