### ISSUE TITLE
If caching plugins like W3TC or WP Super Cache is Active AMP won't work

### ISSUE THREAD

**Issue by Asif2BD** [ahmedkaludi/Accelerated-Mobile-Pages#53]
If W3TC or other caching plugin is active, it cache the main site, and call does not even reach this plugin. 

Issue is even bigger when you do mobile redirection(which is not by default on, but coming in future update, and exist on commit before 0.6.0.

I am using [this guide](https://support.wptouch.com/support/solutions/articles/5000537668-configuring-cache-plugins-for-wptouch) to resolve from caching plugin end.

**Comment by nicholasgriffintn** [comment]
I don't use either of those plugins, but I might be right in thinking the following:

If you put something along the lines of " */?amp " in what might be named something like "never cache these pages", then it should stop the caching plugin from caching amp pages.

You should also disable cache on mobile, you should do that anyway as it never works well.

Personally, I use WP Rocket, which is a pretty awesome pro cache plugin that has its own mobile detection. You can find it here: https://wp-rocket.me/

**Comment by ahmedkaludi** [comment]
This issue was fixed after 0.8 update
