### ISSUE TITLE
Facebook embeds support

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#530]
Facebook embeds support should be added.

ref: http://www.bjpenn.com/mma-news/conor-mcgregor/photographer-details-opportunity-shoot-conor-mcgregor-gunnar-nelson-training-iceland/

http://www.bjpenn.com/mma-news/paul-daley/paul-daley-big-announcement-planned-next-fight/amp/

http://take.ms/LzACp

**Comment by ahmedkaludi** [comment]
It can be done like we do the instagram embed. https://ampforwp.com/tutorials/how-to-embed-instagram-images-videos/
