### ISSUE TITLE
While adding the multiple Webstories  on the website page, the image is not showing of the web stories  the AMP Pages.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5301]
While adding the multiple Web stories on the website page, the poster image is not showing of the web stories on the AMP Pages.

Ref screenshot NON AMP: https://prnt.sc/LJ5aiFWzqXfU 
Ref screenshot AMP: https://prnt.sc/nHe4Qn5FE8kb

Ref Freescout tickket ; https://magazine3.in/conversation/30593?folder_id=29

**Comment by akshaywali** [comment]
pushed in update 1.0.77.52
