### ISSUE TITLE
strange

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#5304]
- [x] https://take.ms/ApTmo
- [x] https://take.ms/jEHJ9

**Comment by akshaywali** [comment]
![Screenshot](https://user-images.githubusercontent.com/36995680/186134380-4adb170b-d8c8-427a-8a3e-edb3b15a7208.png)

Exclamation icon is due to fact the an extension is installed but not activated with license

**Comment by akshaywali** [comment]
Fixed in 1.0.77.50
