### ISSUE TITLE
"Back to Top link" option adds amp-animation & amp-position-observer script without its usage on page

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#5305]
Ref: Design -> Footer -> Back to Top link
Ref: https://prnt.sc/K_m8bgC6mkGo

**Comment by akshaywali** [comment]
![Screenshot](https://user-images.githubusercontent.com/36995680/186134380-4adb170b-d8c8-427a-8a3e-edb3b15a7208.png)

Exclamation icon is due to fact the an extension is installed but not activated with license
