### ISSUE TITLE
There is a compatibility issue with the latest version of the All in One SEO Plugin.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5306]
There is a compatibility issue with the latest version of the All in One SEO plugin (Version 4.2.4). When we roll back the All in One SEO plugin to Version 4.2.3.1 the issue is getting fixed.

Ref screenshot. https://prnt.sc/PBcftNGzhKVZ 
Free scout ref: https://magazine3.in/conversation/33010?folder_id=29

**Comment by MohammedKaludi** [comment]
Pushed in 1.0.77.49
