### ISSUE TITLE
auto-append /amp at the end of internal links in Menu

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#531]
SEE: https://wordpress.org/support/topic/amp-menu-doesnt-link-to-amp-pages/#topic-8478779-replies

BTW, if anyone else wants to do this, you can add the following code to “accelerated-mobile-pages/templates/header.php” via the plugin editor. It will append “/?amp” to the end of every menu link:

<div role=”button” tabindex=”0″ on=’tap:sidebar.close’ class=”close-nav”>X</div>

<?php /* INSERT NEW CODE STARTING HERE */ ?>
<?php function add_menu_atts( $atts, $item, $args ) {
$atts[‘href’] .= “/?amp”;
return $atts;
}
add_filter( ‘nav_menu_link_attributes’, ‘add_menu_atts’, 10, 3 );
?>
<?php /* END OF NEW CODE */ ?>

<?php wp_nav_menu( array( ‘theme_location’ => ‘amp-menu’ ) ); ?>

**Comment by Lofesa** [comment]
related to #509?

**Comment by MohammedKaludi** [comment]
Added with on-off option
