### ISSUE TITLE
 Need to make it compatible with the Co-Authors Plus plugin 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5313]
1) While using the Co-Authors Plus plugin for adding single and multiple authors, when we click on the author's name, it does not redirect to the author's page on the AMP pages.

Ref video.
https://monosnap.com/direct/CR8Dr1ivI8OdjVOKmX2z2GjExeJUHo 

Ref ticket. 
https://magazine3.in/conversation/36126?folder_id=29

RE-Creating steps.

1. Install the Co-Authors Plus plugin 
2. Enter the author's name and check the AMP pages. 
3. Refer to this screenshot to add multiple authors: https://prnt.sc/3-XExo6sVAsv 

2) While using the Fox theme if we hide the option to Show Thumbnail, the feature image is still showing on the AMP pages.

ref screenshot.
1 https://prnt.sc/GKcdeoYD3UYB
2. Non-AMP https://prnt.sc/Soaxznv46hjx
3. AMP post-https://prnt.sc/U7J3nXUwxW1A

RE-Creating steps.
1. Get and install the FOX theme.
2. Create a post and set a "Show Thumbnail" hide.
3. Locate the Amp post.

**Comment by akshaywali** [comment]
Pushed in 1.0.77.51
