### ISSUE TITLE
Shortcodes needs to work on all the ad settings

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#5314]
I use a plugin called 'Random Text' to rotate between different types of ads and see which one performs better, show random messages to visitors (e.g. bring attention to one of the 2-3 featured articles of the week), etc.

I can invoke one of those random blocks with a shortcode like [randomtext category="InArticle1AMP" random="1"]. That works fine in InContent Ads, but does not work in, for example, Above the Post Content (Single Post).

For example, right now, I am testing 2 providers of Ads, and I'd like to show ads from each provider randomly at each post, so I can compare which one performed better in terms of RPM (revenue per thousand impressions)

![image](https://user-images.githubusercontent.com/16532359/187460333-fab18bef-77cc-4a93-919f-4f056f18ed2d.png)

**Comment by akshaywali** [comment]
card  added in trello extension milestone
