### ISSUE TITLE
Author names are not shown in AMP when the Co-Authors Plus plugin is activated.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5319]
When we activated the Co-Authors Plus plugin, the author names were not showing on the AMP website. This issue is from the latest update of the AMP **Version 1.0.77.51** 

Ref ticket.https://magazine3.in/conversation/36126?folder_id=29

**Comment by akshaywali** [comment]
pushed in update 1.0.77.52
