### ISSUE TITLE
Duplicate canonical URL when AIOSEO is active

### ISSUE THREAD

**Issue by arnaudbroes** [ahmedkaludi/accelerated-mobile-pages#5320]
AIOSEO dev here. 

You are outputting a duplicate canonical URL for AMP pages regardless of whether this "Use canonical URL from AIOSEO" setting (SEO) is enabled or not when AIOSEO is active.

![image](https://user-images.githubusercontent.com/18156697/190700304-35261b21-2a89-4fae-93f0-57dc8ddf3057.png)

### Expected behaviour

When the setting is enabled, AIOSEO's canonical URL should be output.

When the setting is disabled, AIOSEO's canonical URL should not be output and instead AMP for WP should output it.

Regardless of the setting, there should never be a duplicate canonical URL.

### Possible solution

I've added a filter in our next upcoming version, 4.2.6, called `aioseo_canonical_url`. This release will be going out early October.

When the user does not want to use AIOSEO's canonical URL, you can use the filter to empty out the value, which will effectively prevent AIOSEO from outputting a canonical URL.

If the user does want to use AIOSEO's canonical URL, then you should simply prevent your own plugin from outputting one.

**Comment by arnaudbroes** [comment]
I've added a filter in our next upcoming version, 4.2.6, called `aioseo_canonical_url` so that you can filter ours if you like.

**Comment by arnaudbroes** [comment]
Hey @ravindra193, let me get that back to you on that. I'll see if I can figure out the steps to reproduce this.

**Comment by akshaywali** [comment]
Hello @arnaudbroes  
Thanks for pointing at the issue as well as for providing possible solution.
Basically we have already fixed the **Duplicate Canonical Issue** in AMP for WP 1.0.77.49 . If you are still having this issue with 1.0.77.49+ please let us know.
We will be implementing  `aioseo_canonical_url` filter in upcoming updates.

**Comment by arnaudbroes** [comment]
@akshaywali @ravindra193 thank you for your patience. It's been a bit busy but I just took a look and am still able to reproduce this issue. You can confirm this here - https://arnaudbroes.be/amp-for-wp-canonical-url-test/amp/.

You'll see two canonical URLs while the "Canonical from All in One SEO" setting in AMP for WP is enabled - 
![image](https://user-images.githubusercontent.com/18156697/194549568-b449ead4-5932-4276-9eba-8144f043f1f4.png)

I'm using AIOSEO Pro 4.2.6 and Accelerated Mobile Pages (AMP for WP) 1.0.77.51.
AIOSEO Lite 4.2.6 should be out next Tuesday along with the new filter hook that I added.

Let me know if you have any questions.

**Comment by akshaywali** [comment]
@arnaudbroes 
I see the issue is coming with AIOSEO Pro , thanks for pointing this out . We will fix this on priority.
