### ISSUE TITLE
Youtube embedded videos via elementor is not displaying in the AMP version.

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/accelerated-mobile-pages#5322]
Youtube embedded videos via elementor is not displaying in the AMP version.
ref video - https://monosnap.com/direct/Meq6TtZJIkzgO1ppoMNq4IVZ3LI9ci
ref ticket - https://magazine3.in/conversation/47572?folder_id=15

**Comment by ravindra193** [comment]
hi

I got video display solution. it is currently for single video display. I want to update change in client website so can you please share ftp so i can update there and check it.

**Comment by akshaywali** [comment]
pushed in update 1.0.77.52
