### ISSUE TITLE
PHP Warning:  Attempt to read property "post_type" on null

### ISSUE THREAD

**Issue by portalzine** [ahmedkaludi/accelerated-mobile-pages#5323]
`PHP Warning:  Attempt to read property "post_type" on null in ..accelerated-mobile-pages/includes/vendor/amp/includes/amp-helper-functions.php on line 29`
Getting the above warning on PHP 8.0+ and latest Wordpress

**Comment by portalzine** [comment]
Outdated vendor include of amp-wp, which has been fixed in current version

`/**
 * Determine whether a given post supports AMP.
 *
 * @since 2.0 Formerly known as post_supports_amp().
 * @see AMP_Post_Type_Support::get_support_errors()
 *
 * @param WP_Post|int $post Post.
 * @return bool Whether the post supports AMP.
 */
function amp_is_post_supported( $post ) {
	return 0 === count( AMP_Post_Type_Support::get_support_errors( $post ) );
}`

**Comment by akshaywali** [comment]
pushed in update 1.0.77.52
