### ISSUE TITLE
TikTok embed video is not working in AMP

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5325]
Ref ticket:- https://magazine3.in/conversation/52083?folder_id=21

Issue screenshot:-
https://prnt.sc/4itAnqBP9RgZ non-AMP
https://prnt.sc/Ep0dijTLEKSV

Issue URL:-
https://goodyfeed.com/mrt-station-free-masks/

**Comment by akshaywali** [comment]
pushed in 1.0.77.53
