### ISSUE TITLE
lightbox for Youtube feature is not working properly 

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5327]
Ref ticket:- https://magazine3.in/conversation/53513?folder_id=21

Description:-
User add the youtude video in elementor in two way. But lightbox feature is not working.
Option 1 - Then I go to Elementor, and then I add an HTML widget and there I paste the Embed code for the youtube video.
Option 2 - The second option is if I go to Elementor, and then I add a Video Widget - and then I paste the video URL.

Issue video URL:-
https://monosnap.com/file/lxyG354QrDBSYjgM5Io1FKMoQPgl9k

**Comment by akshaywali** [comment]
pushed in 1.0.77.53

**Comment by akshaywali** [comment]
![image](https://user-images.githubusercontent.com/36995680/197807803-58362464-fb24-485f-84c9-8a0bcdb719f7.png)

make sure that this setting is enabled in the Design > Single

**Comment by akshaywali** [comment]
it is working as expected  demo video below
https://www.awesomescreenshot.com/video/11971055?key=dc544c302c37bec69708adffe78a5c77

**Comment by nicolasfranz** [comment]
Thanks @akshaywali - confirmed, is active: Design >> Single >> General >> Check the Gif:

![campos](https://user-images.githubusercontent.com/4133280/197810798-2b0e3ef7-eb93-4ddd-a0e8-cbd8315fb0cc.gif)

**Comment by akshaywali** [comment]
Is lightbox working now ?

**Comment by nicolasfranz** [comment]
Thanks @akshaywali 
The error keeps happening unfortunately, check it out, like this video:  https://www.loom.com/share/94309e28b66a4aad86eaf0b99c62aff5

This is the link for you test: https://dev.whooonewstack.com/yapoli/elementor-1278/?amp

**Comment by akshaywali** [comment]
@nicolasfranz
What I can see from the html is that some other plugin is also adding its overlay code to the video and that is why it is not working . Make sure the overlay is added from only one plugin and then try

**Comment by nicolasfranz** [comment]
Thanks @akshaywali ! So well, I'm applying a debug basic method here, and see the results please:

- I have reduced the amount of plugins, as you'll see here: https://www.loom.com/share/786b03076bb94d48895f003a4d34c4a5 but it didn't workout.
- I have change the Theme.. still, it didn't work out at all: https://www.loom.com/share/24ebcfe6cdf64e23a707908bd038f1a2

What is your suggestion in this case?

**Comment by akshaywali** [comment]
I also used the same set of plugins and theme but I was unable to recreate the issue. 
Can you create a new test page , add Youtube video and then check

**Comment by akshaywali** [comment]
@nicolasfranz
https://dev.whooonewstack.com/yapoli/lightbox-test/?amp
Just added this CSS and its working
.ew-video .ect{
    transform: inherit !important;
}
amp-lightbox{
    z-index: 9999 !important;
}

This was just css issue :)

**Comment by nicolasfranz** [comment]
Absolutely amazing, seems to be working now, thanks a lot @akshaywali 
We should update the plugin? Where exactly you added this CSS for us to have this in our log.

Thanks for your amazing support!

**Comment by akshaywali** [comment]
@nicolasfranz 
Design > Global > Custom CSS
