### ISSUE TITLE
Deprecated warning in php 8.1.10

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#5333]
Deprecated: Automatic conversion of false to array is deprecated in D:\XAMPP\htdocs\magazine3\wp-content\plugins\accelerated-mobile-pages\includes\options\admin-config.php on line 5858

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in D:\XAMPP\htdocs\magazine3\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\inc\class.redux_helpers.php on line 685

**Comment by akshaywali** [comment]
pushed in 1.0.77.54
