### ISSUE TITLE
Error generated by amp purge cache

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5337]
PHP Warning:  in_array() expects parameter 2 to be array, int given in /public_html//wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8569

PHP Warning:  Cannot use a scalar value as an array in /public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8591

the plugin doesn't work well with php8, it doesn't redirect "/amp" to "?amp", generating an unreachable page.

**Comment by shridhamdeveloper** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
Still waiting for user reply. Issue does not seem to global. so we are closing this issue. once we get proper tested issue we will open it
