### ISSUE TITLE
When implementing callRail analytics, it throws error in console.

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5344]
When we implement CallRail analytics, it shows 500 error in the browser console.

Reference ticket -: https://magazine3.in/conversation/25889?folder_id=23

Reference screenshot -: 

![photo_2022-11-28_12-36-14](https://user-images.githubusercontent.com/78167698/204215415-fc823763-0215-43f8-a9aa-e90a48fd29e8.jpg)

**Comment by shridhamdeveloper** [comment]
Waiting for your reply
