### ISSUE TITLE
Image URL gets changed in the AMP version if it is optimized  by the plugin imagify.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5349]
Bug Name: Image URL gets changed in the AMP version if it is optimized by the plugin imagify.
Area: Network section
Version Number: 1.0.77.54.1
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/64408?folder_id=27

Description: If the image is optimized by the plugin imagify and converted to the .webp format then the URL of the image gets changed in the network section.
Reference screenshot: https://prnt.sc/64pivbTFRxWN

Steps to recreate the issue:
1. Download the plugin imagify
2. Optimize a URL that contains at least 1 image
3. Open the URL in the AMP version.
4. Open the network tab and here you will see the issue occurring.

**Comment by Sasirekhamarella** [comment]
same issue: https://wordpress.org/support/topic/imagify-plugin-problem/

**Comment by isrgrajan** [comment]
Try switching to Cloudflare and enable Real-AMP URL feature for free of cost while caching AMP based contents as it works by default.
