### ISSUE TITLE
Disqus comments are not showing on the AMP.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5353]
When we enable the option of a Disqus comment and add the Disqus name, the Disqus comment is not visible on the AMP page.

Ref screenshoot:https://prnt.sc/vq3ZZIBhR_db 

Ref ticket; https://magazine3.in/conversation/74131?folder_id=29

**Comment by shridhamdeveloper** [comment]
We checked this issue and there is a problem with Disqus Name entered by user. Please add correct Disqus name to display Disqus comments.
For Eg: https://[YOUR DISCUSS NAME].disqus.com
Here replace [YOUR DISCUSS NAME] with your disqus name

Please refer this below screenshot for your reference
Screenshot: https://prnt.sc/qXaMTRoUuJMg

**Comment by Sdaud1950** [comment]
Same issue :https://magazine3.in/conversation/277397?folder_id=29
