### ISSUE TITLE
Feature request for Google Analytics GA4

### ISSUE THREAD

**Issue by isrgrajan** [ahmedkaludi/accelerated-mobile-pages#5355]
Although GTag works well, but there is need to add option and configuration for **Google Analytics GA4** version since the older version of Google Analytics is going to retire.

**Comment by Sanjeevsetu** [comment]
It has been added in ticket Feature request to add Google Analytics 4 support #4793

**Comment by Sanjeevsetu** [comment]
Hi @isrgrajan 

You can try our new latest version v1.0.80. We have added GA4 there.

**Comment by isrgrajan** [comment]
Thanks a ton @Sanjeevsetu
