### ISSUE TITLE
Easy Table Of contents not appearing properly on AMP version.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5356]
Bug Name: Easy Table Of contents not appearing properly on the AMP version.
Area: AMP post/pages
Version Number: 1.0.77.54.1
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/81315?folder_id=27

Reference screenshot: https://prnt.sc/uWSSJjJUKbfd

Steps to Reproduce:

Login into your wp-admin dashboard
Activate the plugin AMPforWP and Easy Table Of Contents.
Visit a post that has TOC enabled on it in the AMP version.

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/amp-problem-11/#post-16301888

**Comment by sajandara** [comment]
Added a new ticket here  https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/373 so closing this one.
