### ISSUE TITLE
Videos are not playing after recent update i.e. 1.0.77.55.1

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5369]
After a recent update, MP4 videos stopped playing on the amp because the update has modified the code and added *no-controls=""*.

Reference ticket  -: https://magazine3.in/conversation/83541?folder_id=23

**Comment by Sanjeevsetu** [comment]
This is similar to After the update there is no control="" in video's code #5366 so closing it
