### ISSUE TITLE
Avada's element Table Of Contents links not working in the AMP version.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5378]
Bug: Avada's element Table Of Contents links not working in the AMP version and the design appears broken
Area: AMP version
Version Number: AMPforWP: 1.0.78 | Avada Theme: 7.9.1 | Avada builder: 3.9.1 | Avada Core: 5.9.1
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/84648?folder_id=27

Description: Avada's element Table Of Contents links are not working on the AMP version.
Reference video: https://monosnap.com/direct/Xnz1a7s3LD2mZcZo7eFoDc6pzqd3VM

**Comment by akshaywali** [comment]
For TOC on AMP we already have an addon . You can check it here https://ampforwp.com/addons/easy-table-of-contents-for-amp/
