### ISSUE TITLE
Image gallery is not working in AMP

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5385]
Ref ticket:-
https://magazine3.in/conversation/98395?folder_id=21

Description:-
"p" tags have been added before amp-carousel and create a issue when we remove those tag gallery appears.

Issue screenshot:-
https://prnt.sc/6zD55LwHB6wC

Issue video:-
https://monosnap.com/file/0OKrk7WBOtyiyXcFSH8LCghfZA8Dpz

**Comment by 77naveenop** [comment]
Working on user end.
