### ISSUE TITLE
The attribute 'area-label' may not appear in tag 'a'.

### ISSUE THREAD

**Issue by isrgrajan** [ahmedkaludi/accelerated-mobile-pages#5390]
Incompatible with Easy Table of Contents plugin and throwing `<a href=# class="ez-toc-pull-right ez-toc-btn ez-toc-btn-xs ez-toc-btn-default ez-toc-toggle" area-label=ez-toc-toggle-icon-1>` error in AMP version:

**The attribute 'area-label' may not appear in tag 'a'.**

**Comment by MohammedAkramU7** [comment]
Another user :- https://magazine3.in/conversation/104418?folder_id=21

**Comment by isrgrajan** [comment]
I've fixed the issue. There was issue in the Easy Table Contents Plugin
