### ISSUE TITLE
Call rail analytics generating warning in Google Search Console

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5400]
When implementing CallRail analytics, it generates a warning in Google Search Console "the script tag contains invalid json that cannot be parsed".

Reference ticket -: https://magazine3.in/conversation/25889?folder_id=23

**Comment by Sanjeevsetu** [comment]
This issue seems invalid. There was cache issue at user end. I am closing it
