### ISSUE TITLE
Need to create an option where user can add the custom code in the GA4

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5401]
Need to create an option where the user can add the custom code in the GA4

Ref ticket: https://magazine3.in/conversation/108571?folder_id=29

**Comment by akshaywali** [comment]
IN GA4 you just have to create an event on GA4 dashboard then it will automatically propagate to you website and will track events (given that you have connected GA4 to your website). So you dont have to copy paste any event tracking coding. Hope this helps

For more info you check out this link https://support.google.com/tagmanager/answer/13034206?hl=en
