### ISSUE TITLE
Conflict issue with Newspaper theme

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5414]
Ref ticket:- https://magazine3.in/conversation/116865?folder_id=21

Description:-
When we activate the Newspaper theme with tagDiv amp plugin "Addon Mode" automatically activated.

**Comment by Sanjeevsetu** [comment]
This is not a bug. This plugin works in add on mode when tagDiv amp ro AMP official is installed because if two or more AMP plugin is active at the same time, it will conflict each other
