### ISSUE TITLE
The Facebook like button is not showing up properly on the AMP version.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5416]
The Facebook-like button is not showing up properly on the AMP version.

Ref screenshot: https://prnt.sc/8r63jEtSQr97

Ref ticket : https://magazine3.in/conversation/106927?folder_id=29

**Comment by Sasirekhamarella** [comment]
Ref: https://wordpress.org/support/topic/bad-support-108/
