### ISSUE TITLE
Conflict WP-Bakery page builder with AMP

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5417]
When we use the WP-Bakery page builder with AMP, there is an error showing in the AMP Validator.
The attribute 'a' may not appear in tag 'a 

Ref screenshot:https://prnt.sc/0XNONXdHXlTp

Ref ticket: https://magazine3.in/conversation/112903?folder_id=29

**Comment by Sanjeevsetu** [comment]
The solution was not correct. We had to reverse the code and reopen the ticket

**Comment by akshaywali** [comment]
pushed in update 1.0.89
