### ISSUE TITLE
QUERY STRING in amphtml

### ISSUE THREAD

**Issue by Ysery** [ahmedkaludi/accelerated-mobile-pages#5419]
Hi

When visiting the site, [Yandex search](https://webmaster.yandex.ru/blog/novyy-parametr-dlya-bolee-tochnogo-raspoznavaniya-poiskovykh-fraz-v-metrike) engine adds …`?ysclid=xxxxx` And as a result, the page is cached and the url in the code looks like this.

`<link rel="amphtml" href="https://sample.com/testpage.html/amp?ysclid=12345678" />`

Video problem https://youtu.be/utIv6AcFUcA

Remove QUERY STRING from the link.

Sorry for my English.

**Comment by akshaywali** [comment]
**The issue you are  facing is due to lightspeed cache plugin not our plugin.**
**You just have to drop  query string  "ysclid" as shown below in the screenshot to fix this issue.**

![image](https://user-images.githubusercontent.com/36995680/234521548-5a734249-0dda-4cb3-8df7-a186f62a42d3.png)
