### ISSUE TITLE
Conflict issue with Jetpack plugin

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5424]
Ref ticket:- https://magazine3.in/conversation/125075?folder_id=21

Description:
User added the gallery with the help of the Jetpack plugin, but the carousel feature is not working in AMP. The user recently upgraded to the WordPress 6.2 version.

Issue screenshot:
https://prnt.sc/pCZHZNi8P1g9

**Comment by Sasirekhamarella** [comment]
Same issue: https://wordpress.org/support/topic/wp-6-2-galeries-are-broken-in-amp/

**Comment by akshaywali** [comment]
Issue with jetpack was  due to Change in css in Wordpress 6.2 that is fixed in this ticket 

For default WP gallery not working please  refer this ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5422

**Comment by akshaywali** [comment]
Pushed in AMPforWP 1.0.84
