### ISSUE TITLE
Need to make compatibility with the Google Reviews plugin

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5425]
When we add the Google review from the Google Reviews plugin, the review shows up on the non-Amp but not on the AMP.

Ref Ticket: https://magazine3.in/conversation/129502?folder_id=29

**Comment by akshaywali** [comment]
![image](https://user-images.githubusercontent.com/36995680/233936042-1ca0d6c7-5f18-45f8-8a34-7a0e20f3cad0.png)

The plugin which user is using (Widgets for Google Reviews) does not support AMP on free version . That is why it is not working on AMP and purposely disabling the Reviews on AMP.
