### ISSUE TITLE
The Analytic option Google Tag Manager is causing an error in the console while using with AMP Pop-up

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5429]
The Analytic option Google Tag Manager is causing an error in the console while using with AMP Pop-up

Ref ticket: https://magazine3.in/conversation/125689?folder_id=27

Ref screenshot: https://prnt.sc/25pl-jvm9mrr

**Comment by akshaywali** [comment]
Pushed in AMP POPUP 1.5.25
