### ISSUE TITLE
Conflict issue with Imagify and WP Offload Media Lite plugin

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5432]
Ref ticket:- https://magazine3.in/conversation/130732?folder_id=21

Description:-
When we activate the Imagify and WP Offload Media Lite plugins, an error appears in the AMP validator. "The attribute 'width' in tag 'amp-img' is set to the invalid value ''

Issue screenshot:-
https://prnt.sc/dgcemqho64ZY

**Comment by akshaywali** [comment]
There was settings issue on the user site .User enabled the change size option for related post images but didnt set any size. This is causing the issue.

![image](https://user-images.githubusercontent.com/36995680/233587452-2b4f641e-1965-4709-a4dd-f4e4e1382bb1.png)

We will also have to add condition to check whether user has set any data or not.

**Comment by akshaywali** [comment]
Pushed in AMPforWP 1.0.84
