### ISSUE TITLE
PHP error after the recent update 1.0.84

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5436]
**_Error notice_**
` PHP Notice:  Function WP_Scripts::localize was called <strong>incorrectly</strong>. The <code>$l10n</code> parameter must be an array. To pass arbitrary data to scripts, use the <code>wp_add_inline_script()</code> function instead. Please see <a href="https://wordpress.org/documentation/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.7.0.) in C:\xampp\htdocs\wordpress\wp-includes\functions.php on line 5865
`
Reference ticket: https://wordpress.org/support/topic/function-wp_scriptslocalize-was-called-incorrectly-the-l10n-parameter-must-b-2/

**Comment by akshaywali** [comment]
pushed in 1.0.85
