### ISSUE TITLE
Issue with Google Font and Global Font Weight Selector

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5440]
In the latest version 1.0.84 of the AMP, the Google fonts are showing only 8 to 9, but when we roll back the plugin, the Google fonts are showing correctly, and the Global Font Weight Selector is not working.

Ref video: https://monosnap.com/file/fq9pNa6IA1LuiulKbGwCyxIufsTl9X 

Ref Ticket: https://magazine3.in/conversation/137190?folder_id=29

**Comment by Sdaud1950** [comment]
same issue with this user: https://magazine3.in/conversation/137362?folder_id=29

**Comment by aamiralishah** [comment]
Any update on this issue

**Comment by akshaywali** [comment]
pushed in 1.0.85
