### ISSUE TITLE
An error is appearing in the console and the AMP setting panel is frizzed

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5442]
An error is appearing in the console and the AMP setting panel is frizzed

Ref ticket: https://magazine3.in/conversation/137698?folder_id=27

Ref Screenshot: https://monosnap.com/direct/cRFfJC6DutjuBkLKwNYieJ0szPmlVW

**Comment by akshaywali** [comment]
Pushed in update 1.0.87
