### ISSUE TITLE
A Notice is appearing in the wp-admin dashboard

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5443]
A Notice is appearing in the wp-admin dashboard

Notice: Function WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see Debugging in WordPress for more information. (This message was added in version 5.7.0.) in C:\xampp\htdocs\mag\wp-includes\functions.php on line 5857

Ref ticket: https://magazine3.in/conversation/136940?folder_id=27

**Comment by Sanjeevsetu** [comment]
It is similar to a ticket https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5435 and has been fixed there so closing it
