### ISSUE TITLE
If Yoast is not available and the options are ON then FATAL error

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#545]
If Yoast is not available and the options are ON then FATAL error

http://take.ms/fZOTl  & http://pastebin.com/hi5V6yL9

**Comment by khaledMohammed000** [comment]
Seriously unable to recreate this issue @MohammedKaludi if you could please help on this, would help alot :)

**Comment by Lofesa** [comment]
Hi @ahmedkaludi 
This [issue](https://wordpress.org/support/topic/getting-this-error-on-my-blog/) in wordpress.com forum seems to be related but user had disabled amp plugin and can´t view amp pages. Site is http://waowtech.com

**Comment by MohammedKaludi** [comment]
There was the issue, I can confirm that by digging into previous commits but has been resolved and fixed in commit : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/f5889e5c8093813be8f8f230f0396df128d80162

**Comment by MohammedKaludi** [comment]
Needs testing when yoast seo active and AMP seo settings are on in some cases.

**Comment by ahmedkaludi** [comment]
we are closing this to stay focused
