### ISSUE TITLE
WPCore Module of Search is throwing error in AMP validation

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5450]
Reference Screenshot: https://prnt.sc/exT4cVAarMY2
Validation Error: https://prnt.sc/H5ApmjZWn5wR
The mandatory attribute 'target' is missing in tag 'form'.

https://magazine3.in/conversation/140197?folder_id=19

**Comment by akshaywali** [comment]
update pushed in 1.0.86
