### ISSUE TITLE
Hestia Pro theme buttons are not appearing in the AMP version of the website.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5452]
Hestia Pro theme buttons are not appearing in the AMP version of the website.

Ref ticket: https://magazine3.in/conversation/142632?folder_id=27

Ref screenshot: 
NON_AMP: https://monosnap.com/direct/Z51GU6jLz3SuMn1POOzrs5ZJn9bNfX
AMP: https://monosnap.com/direct/dPnovdSCVC60bH7xNRHhRwj7n7QLby

**Comment by akshaywali** [comment]
Pushed in update 1.0.87
