### ISSUE TITLE
Truepush integration not working: missing file /accelerated-mobile-pages/includes/truepush-integration/sw.js

### ISSUE THREAD

**Issue by global-es** [ahmedkaludi/accelerated-mobile-pages#5455]
Hi!
We are triying to use Truepush in AMP, and the required file:
/accelerated-mobile-pages/includes/truepush-integration/sw.js
Is missing in your repository:
[ahmedkaludi/accelerated-mobile-pages/tree/master/includes/truepush-integration](https://github.com/ahmedkaludi/accelerated-mobile-pages/tree/master/includes/truepush-integration)
This file loads the remote SDK library:
https://sdki.truepush.com/sdk/v2.0.4/sw.js
This must be their content:
```
var version = "v2.0.4";
var swPath;
var urlObject = new URL(location);
var host;
if (urlObject.searchParams.get("swPath")) {
    swPath = urlObject.searchParams.get("swPath");
}
else {
    if (urlObject.searchParams.get("version")) {
        version = urlObject.searchParams.get("version");
    }
    if (urlObject.searchParams.get("swJSHost")) {
        host = "https://" + urlObject.searchParams.get("swJSHost");
    }




    else {
        host = "https://sdki.truepush.com/sdk/";
    }
    swPath = host + version + "/sw.js";
}
importScripts(swPath);
```

Also, when you open the page to subscribe it tries to load it from the root directory of the site, so we had to add this rewrite rule to make it work:

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^sw.js$ /wp-content/plugins/accelerated-mobile-pages/includes/truepush-integration/sw.js [L]
</IfModule>
```

We hope that these problems can be solved in future versions of your add-on.
Best regards.

**Comment by Sanjeevsetu** [comment]
Hi @global-es 

Thank you for the bug report. Yea we will test and fix it in coming updates. I have added priority high on it.

**Comment by akshaywali** [comment]
Hi @global-es ,
Actually you have to add sw.js file at the root of the website. This is required for **Truepush Push Notifications** plugin to work both  in amp as well as on non-amp.
You can see these instruction on Truepush dashboard. Once you have added the file you  don't have to modify any file or add redirect

![image](https://github.com/ahmedkaludi/accelerated-mobile-pages/assets/36995680/5a19f758-4ef6-4929-b942-124213a93917)

**Comment by global-es** [comment]
> Hi @global-es , Actually you have to add sw.js file at the root of the website. This is required for **Truepush Push Notifications** plugin to work both in amp as well as on non-amp. You can see these instruction on Truepush dashboard. Once you have added the file you don't have to modify any file or add redirect
> 
> ![image](https://user-images.githubusercontent.com/36995680/249037605-5a19f758-4ef6-4929-b942-124213a93917.png)

Hi, @akshaywali.

In non-amp version works fine WITHOUT this file on root directory. You don't need to make the code integration, they have their own WordPress plugin:

[Truepush – Most Affordable Web Push Notifications](https://wordpress.org/plugins/truepush-free-web-push-notifications/)

And it loads another verison ot their SDK:

[sdki.truepush.com/sdk/v2.0.4/main.js](https://sdki.truepush.com/sdk/v2.0.4/main.js)

So, the problem is only in AMP version created with your plugin.

**Comment by akshaywali** [comment]
@global-es  
Thanks for sharing the  information.  
Looking more into the issue we came to know that issue is caused by https://sdki.truepush.com/sdk/v2.0.3/amp-permission-dialog.js
This is used in amp version only to display  permission dialog. Issue is caused by UrlExists() function which check whether  url exits or not . and strangely is returning  200 for sw.js when no such file exists.
We are  working on it and will push it in upcoming update. 
Thanks for your patience and understanding.

**Comment by global-es** [comment]
> @global-es Thanks for sharing the information. Looking more into the issue we came to know that issue is caused by https://sdki.truepush.com/sdk/v2.0.3/amp-permission-dialog.js This is used in amp version only to display permission dialog. Issue is caused by UrlExists() function which check whether url exits or not . and strangely is returning 200 for sw.js when no such file exists. We are working on it and will push it in upcoming update. Thanks for your patience and understanding.

@akshaywali , We are waiting with great hope for your update, do you have any forecast of when it will be available?

Thanks!

**Comment by akshaywali** [comment]
@global-es Fix will be release in the very next update.

**Comment by akshaywali** [comment]
Pushed in update 1.0.87
