### ISSUE TITLE
AMP not working with categories.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5456]
Ref ticket:-https://magazine3.in/conversation/137802?folder_id=21

Description:-
The user added the categories post with the help of the product post, and the user added the dual categories.

Example: 
www.Test/product-category/Test1categories/test2categories/amp

Issue screenshot:-
https://prnt.sc/Pd7kA5gWqwlk

**Comment by Idelfonsorobertosantos** [comment]
hi
My name is Idelfonso
I'm a contributor to the domain https://www.2e4rodas.com.br/
this is the domain where the problem happens.

Our URL has wordpress and Woocomerce with DOKAN
we have more than 800 posts and more than 200 products, about 3000 images, and the URL is about 10 years old.

The structure is relatively large with categories and subcategories, both for Posts and Products.

We use DIVI THEME only for header and footer, we edit all POSTs, using GUTEMBERG, to improve performance on MOBILE. inside the posts, we use only one column. decreasing the processing to assemble the page on the cell phone.

https://www.2e4rodas.com.br/site/autocenter/duplicador-de-garagem-hidraulico/amp/

let me know if you need anything.

thanks

**Comment by akshaywali** [comment]
Pushed in update 1.0.87
