### ISSUE TITLE
Page for post and front page related issues

### ISSUE THREAD

**Issue by Lofesa** [ahmedkaludi/accelerated-mobile-pages#546]
Hi @MohammedKaludi  @khaledMohammed000  @ahmedkaludi 
Well I have done a search to solve the issue that front page is "confused" with page for post when you make it separate items.
I have searched your code for new instances of WP_query and only found that you instantiate one in index.php or for related post and so.... All the rest stuff is dealing with the default instance of WP_query initiated by Wordpress itself.
I found that these default instance has a value for post_type of post, so you never got info from the WP_query related to pages, for that you need to instantiate WP_Query with post_type='page' in the parameters when you deal with pages not with post.
This makes the only thing that is true is is_home() and is_front_page maybe not, and that produces rare things. For example:
If I don´t select a custom front page in the plugin option, I get 2 pages for post, 1 in https://site  and 1 in https://site/blog (for use the same structure you have in your own site), bot have posts listing  but in htttp://site pagination works but in htttps://site/blog don´t (I think because rewrite rules)
If I select a custom front page in the plugin options.....  you may hope to get http://site with the custom content of the front page and http://site/blog with the list of post but you have, again, 2 pages with the same identical content (the content from the custom front page) in bot pages, "/" and "/blog".

Make this sense for some one? 

related issues #388  and #449

**Comment by Lofesa** [comment]
This wordpress.com issue seems to be related
https://wordpress.org/support/topic/amp-iframe-2/#post-8804557

**Comment by ahmedkaludi** [comment]
Hey @MohammedKaludi Can you have a look at this ticket? I'd like to have your opinion on it.

**Comment by ahmedkaludi** [comment]
This was fixed. Please confirm @Lofesa
