### ISSUE TITLE
PHP Error is showing in the AMP

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5464]
PHP Error is showing in the AMP  "Attempt to read property 'term_id' on null in /www/energynowusa_173/public/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 220."
 
Ref screenshot: https://magazine3.in//storage/attachment/8/8/1/Sin-ti%C3%ACtulo-1.jpg?id=29388&token=b091feb7dd7bf4e3fafb3123fd4fcc78 

Ref Ticket:https://magazine3.in/conversation/147346?folder_id=29

**Comment by akshaywali** [comment]
Pushed in update 1.0.87
