### ISSUE TITLE
Undefined array key “amp” in wp-content/plugins/core-web-vitals-pagespeed-booster/includes/functions.php on line 380

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5465]
Error log:  Warning: Undefined array key "amp" in /home/clients/426cfb65c92a452feb9beff7261a9a2e/sites/site-exemple.com/wp-content/plugins/core-web-vitals-page speed-booster/includes/functions.php on line 380

Reference ticket:https://wordpress.org/support/topic/error-warning-undefined-array-key-amp-in-home-clients/

**Comment by Rkroy** [comment]
Ticket related to Core Web vital Plugin, so closing the ticket.
