### ISSUE TITLE
Playfair Display font is not showing in the heading font family.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5469]
When we add the Google Font API key, all fonts show up on the global font family, but on the heading font family, only a few fonts show, and Playfair Display is not showing on the heading font family.

Ref screenshot: https://prnt.sc/SG_4SuBwc0o3 

Ref Ticket : https://magazine3.in/conversation/152696?folder_id=29

**Comment by akshaywali** [comment]
Pushed in update 1.0.87
