### ISSUE TITLE
Title H1 tags is automatically converted to H2 tags in AMP

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5470]
Ref ticket:-https://magazine3.in/conversation/152188?folder_id=21

Description:-
H1 tags is automatically converted to H2 tags in AMP

Issue screenshot:-
https://prnt.sc/SMZUN7Z6OFqT non-AMP
https://prnt.sc/egLhJMNDgWgV AMP.

**Comment by Rakeshrai14** [comment]
Hi @MohammedAkramU7 ,
Did you made any changes in AMP plugin?

**Comment by akshaywali** [comment]
Pushed in update 1.0.87
