### ISSUE TITLE
GA4 activity fails when the AMP page is hosted on Google

### ISSUE THREAD

**Issue by rodriamaya** [ahmedkaludi/accelerated-mobile-pages#5471]
Hi

To reproduce this, several conditions must be met:

- The amp page must be hosted by google
- You have to obtain the google hosted page url
- You have to open the developer console on the mobile responsive view on Chrome

Here a screenshot:
![Screen Shot 2023-06-21 at 12 12 51](https://github.com/ahmedkaludi/accelerated-mobile-pages/assets/52326467/0b440d0b-c349-47f6-bba8-634d1a606b21)

The file ga4.json is hosted on a different server, where we can avoid a CORS error. We had to modify this on the plugin.

Otherwise, when the google hosted amp page is seen, the file cannot be retrieved due to that CORS error (since google.com is a different domain than the site).

We changed the line 25 of accelerated-mobile-pages.php:
`define('AMPFORWP_ANALYTICS_URL',plugin_dir_url(__FILE__).'includes/features/analytics');`

For our hosted file.

This is used on includes/features/analytics/analytics-functions.php
` 		<amp-analytics type="googleanalytics" <?php if(ampforwp_get_data_consent()){?>data-block-on-consent <?php } ?>config="<?php echo AMPFORWP_ANALYTICS_URL?>/ga4.json" data-credentials="include">
`

I don't know a proper fix. 
May be something related to embedding the ga4.json content on analytics-functions.php?

**Comment by akshaywali** [comment]
Pushed in update 1.0.87
