### ISSUE TITLE
We need to create a Short code so that user can show or hide some content in AMP.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5474]
We need to create a Short code so that user can show or hide some content in AMP.
example: the user just wants 1 or 2 components (video and gravity form) to appear or hide depending on whether the page is AMP or Regular.

Ref ticket:https://magazine3.in/conversation/154347?folder_id=29

**Comment by akshaywali** [comment]
### Shortcode Usage 

[ampforwp_visibility visibility="show"]
**This content will only be shown in AMP mode.**
[/ampforwp_visibility]

[ampforwp_visibility visibility="hide"]
**This content will only be hidden in AMP mode.**
[/ampforwp_visibility]

[ampforwp_visibility mode="non-amp" visibility="show"]
**This content will only be shown in non-AMP mode.**
[/ampforwp_visibility]

[ampforwp_visibility mode="non-amp" visibility="hide"]
**This content will only be hidden in non-AMP mode.**
[/ampforwp_visibility]

**Comment by akshaywali** [comment]
pushed in 1.0.94
