### ISSUE TITLE
Need to make Publytics.net compatibility in AMPforWP

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5477]
Ref ticket:-https://magazine3.in/conversation/156101?folder_id=21

Description:-
Publytics is a analytics platform which we need to make compatibility in AMPforWP.

**Comment by Rkroy** [comment]
@enzorevo We've Made the changes, please check.

**Comment by enzorevo** [comment]
> @enzorevo We've Made the changes, please check.

I confirm it's ok! Thanks.
