### ISSUE TITLE
Some alphabetic letters are missing in the category, but the same letter shows on the post.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5484]
An "a" alphabetic letter is missing in the category, but the same letter shows in the post.

Ref screenshoot Post :https://prnt.sc/Qf7RbqO2z2-g 

Ref screenshoot of Catergry: https://prnt.sc/uZxU_uA0keqC  'a" alphabetic letter missing in the tittle.

Ref screenshoot: https://magazine3.in/conversation/132082?folder_id=29

**Comment by Sanjeevsetu** [comment]
This issue arose due fix in the ticket number #5417 . I have reopened that ticket.
