### ISSUE TITLE
Embeds are not working on the AMP version

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5486]
Embeds are not working/appearing on the AMP version if the plugin Embedpress is activated

Ref video: https://monosnap.com/direct/Ls6E043JSk1jGZQGOc5hWu7mCrRp2f

Ref ticket: https://magazine3.in/conversation/162356?folder_id=27

**Comment by akshaywali** [comment]
pushed in update 1.0.89
