### ISSUE TITLE
The excerpt is not showing inside the em tag in AMP, and the font is not working.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5487]
The excerpt is not showing inside the em tag in AMP, and the font is not working.

Ref screenshoot of Non-amp: https://prnt.sc/NS3yD3QWjcdk 

Ref screenshoot of AMP: https://prnt.sc/9zRaJAM-uYsV 

Ref Ticket: https://magazine3.in/conversation/36126?folder_id=29

**Comment by akshaywali** [comment]
pushed in 1.0.94
