### ISSUE TITLE
 Uses deprecated APIs warning 

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5490]
Ref ticket:-https://magazine3.in/conversation/165911?folder_id=21

Description:-
Truepush notification and embed.dugout application create a warning in Pagespeed Insights.

Issue screenshot:-
https://monosnap.com/direct/4Ezfi4Yuc0U4PqtOSogvA2WUzmQpLf

**Comment by Rkroy** [comment]
The warning coming from video Ad and not from our plugin, so please reach out to the Ad provider to fix the api warning.
