### ISSUE TITLE
Jetpack Stats are not showing in the AMP.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5495]
Jetpack Stats are not showing in the AMP.

Ref Ticket: https://magazine3.in/conversation/168586?folder_id=29

**Comment by Sanjeevsetu** [comment]
Hi @jeherve 

Thank you so much for the help. Sure we will change it.

**Comment by jpettibone13** [comment]
Hi,

I'm from WordPress VIP, and we have a customer whose stat tracking has been rendered invalid by the lack of AMP tracking. I just wanted to check in on their behalf and see if this issue is scheduled to be addressed soon, or if there's any ETA.
