### ISSUE TITLE
GA4 analytic throwing warning in Chrome Console.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5501]
log.js:232 [AmpAnalytics <unknown id>] Warning from analytics vendor googleanalytics: [object Object]
log.js:232 [AmpAnalytics <unknown id>] Warning from analytics vendor googleanalytics with remote config url https://website/wp-content/plugins/accelerated-mobile-pages/includes/features/analytics/ga4.json: [object Object]

**Comment by akshaywali** [comment]
Issue already fixed in previous versions so closing the ticket
