### ISSUE TITLE
Add an option to configure the number of posts appearing on the category pages

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5503]
Add an option to configure the number of posts appearing on the category pages

Ref ticket: https://magazine3.in/conversation/137698?folder_id=27

**Comment by 77naveenop** [comment]
Same feature is needed for the homepage and post pagination for both the homepage and category page.

Reference user -: https://magazine3.in/conversation/187386?folder_id=23
