### ISSUE TITLE
Warning in error log

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5504]
PHP Warning: Attempt to read property “title” on bool in /home2/piedras1/public_html/cita-sepe.es/wp-content/plugins/accelerated-mobile-pages /templates/features.php on line 1796

Reference User -: https://wordpress.org/support/topic/warnings-after-upgrading-to-php-8-0-from-yoast-title/

**Comment by akshaywali** [comment]
pushed in update 1.0.89
