### ISSUE TITLE
AMP for WP Update Causes Dashboard Notices and Warnings

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/accelerated-mobile-pages#5508]
User reported the below errors:
Notice: Accessing static property ReduxCore\ReduxFramework\ReduxFramework::$old_opt_name as non static in C:\WWW\OCP\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\framework.php on line 237

Notice: Accessing static property ReduxCore\ReduxFramework\ReduxFramework::$old_opt_name as non static in C:\WWW\OCP\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\framework.php on line 253

Notice: Accessing static property ReduxCore\ReduxFramework\ReduxFramework::$old_opt_name as non static in C:\WWW\OCP\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\framework.php on line 254

Notice: Accessing static property ReduxCore\ReduxFramework\ReduxFramework::$transients as non static in C:\WWW\OCP\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\framework.php on line 2526

Notice: Accessing static property ReduxCore\ReduxFramework\ReduxFramework::$transients as non static in C:\WWW\OCP\wp-content\plugins\accelerated-mobile-pages\includes\options\redux-core\framework.php on line 2527

Notice: Accessing static property ReduxCore\ReduxFramework\ReduxFramework::$wp_data as non static in /var/www/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-core/framework.php on line 888

Here reference ticket: https://wordpress.org/support/topic/accessing-static-property-reduxcore/

**Comment by akshaywali** [comment]
update pushed in 1.0.88.1
