### ISSUE TITLE
Need to add Analytics of piwik .pro

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/accelerated-mobile-pages#5510]
user requires the implementation of Piwik.pro within the AMP Plugin. These are two distinct websites: 'https://piwik.com/' and 'https://piwik.pro/web-analytics/'.

Reference ticket: https://wordpress.org/support/topic/amp-analytics-with-piwik-pro/

**Comment by akshaywali** [comment]
Need to add tutorial for the feature
Ref : https://developers.piwik.pro/en/latest/data_collection/other_integrations/AMP_integration.html

**Comment by akshaywali** [comment]
pushed in update 1.0.89
