### ISSUE TITLE
Amp Validation Error in New update.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/accelerated-mobile-pages#5528]
User reported that AMP Validation issue they are facing with the new update (Version 1.0.90)

Reference Ticket: https://wordpress.org/support/topic/amp-validation-error-tag-foritem-is-not-allowed/

**Comment by pasgeeken** [comment]
I also have this issue.

**Comment by pasgeeken** [comment]
I have manually added this code change to my live site and tested a few pages and they are now ok, no AMP validation errors. :-)

**Comment by sajandara** [comment]
Another user is facing the same issue: 
https://magazine3.in/conversation/196262?folder_id=27

**Comment by sajandara** [comment]
Navin also has a user who is facing the same issue:
https://magazine3.in/conversation/198086?folder_id=23
