### ISSUE TITLE
Disable AMP on desktop option is not working

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/accelerated-mobile-pages#5543]
When using any cache plugin, Disable AMP of desktop option is not working.

Reference user -: https://magazine3.in/conversation/197134?folder_id=23

**Comment by isrgrajan** [comment]
> When using any cache plugin, Disable AMP of desktop option is not working.
> 
> Reference user -: https://magazine3.in/conversation/197134?folder_id=23

**Make sure to enable AMP extension or in the cache plugin.**
Here's is how you can disable it with [W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/)

- **Step 1**
![image](https://github.com/ahmedkaludi/accelerated-mobile-pages/assets/17787860/71c588b9-a3a1-45b2-b8e8-0d785278735e)

- **Step 2**
![image](https://github.com/ahmedkaludi/accelerated-mobile-pages/assets/17787860/4e32e56b-29d5-475d-bf75-abc27cd15759)

- **Step 3**
![image](https://github.com/ahmedkaludi/accelerated-mobile-pages/assets/17787860/85c29a70-bd26-4c2c-9851-4f6f5707d7f8)

- **Step 4**
![image](https://github.com/ahmedkaludi/accelerated-mobile-pages/assets/17787860/1e82a7ae-5fc3-4405-b985-e866a7008c23)

- **Step 5**
![image](https://github.com/ahmedkaludi/accelerated-mobile-pages/assets/17787860/0972d149-0517-4beb-93ec-3dfbce2e2979)

**Comment by akshaywali** [comment]
Disable AMP on desktop option is working fine as of version 1.0.93
Issue might  have been fixed in pervious updates.

**Comment by akshaywali** [comment]
pushed in 1.0.93
