### ISSUE TITLE
A PHP error is appearing WP VIP Error log

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5547]
A PHP error is appearing WP VIP Error log

Error: Undefined array key "enable-single-gplus-share" in .../wp-content/plugins/amp-layouts/extended/swift-css-extended.php on line 1076

Ref ticket: https://magazine3.in/conversation/211034?folder_id=27

**Comment by Rkroy** [comment]
Fix done in AMP layouts extension.
