### ISSUE TITLE
Issue with a cookie banner (GDPR)

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5561]
1. We need to create an option. We can change the text according to our needs and Translet in our needed language, and we need to create an option where we can change the cookies and add the cookies dynamically.
Ref screenshoot: https://prnt.sc/isjmGqhWfwfK  

2. We need to compatiblity with advance ads, as when we reject the cookies, ads should not show.

4. We need to create an option where we can show or hide the “See preferences” option.

Ref ticket:https://magazine3.in/conversation/231844?folder_id=29

**Comment by akshaywali** [comment]
pushed in 1.0.94
