### ISSUE TITLE
ERROR: CSS syntax error in the “style amp-custom” tag

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/accelerated-mobile-pages#5564]
Multiple users reached out for this issue **CSS syntax error in the “style amp-custom”** tag when use with the Swift theme. 

Reference tickets: https://wordpress.org/support/topic/css-syntax-error-in-tag-style-amp-custom-27/ 

https://wordpress.org/support/topic/there-is-a-css-syntax-error-in-the-style-amp-custom-tag/

https://wordpress.org/support/topic/css-syntax-error-in-tag-style-amp-custom-bad-url-3/

https://wordpress.org/support/topic/css-syntax-error-in-style-amp-custom-tag/

**Comment by akshaywali** [comment]
pushed in 1.0.93.1
