### ISSUE TITLE
Code improvement part 2

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#5567]
- [ ] function prefix should be ampforwp check func "amp_flush_rewrite_rules", "amp_breadcrumb_output", "amp_consent_submission", "amp_archive_title", "call_loops_standard", check whole /components/loop.php
- [x] loop validation classes\class-ampforwp-photo-gallery-embed.php Line : 50
- [x] loop validation \components\breadcrumb\breadcrumb.php Line : 139
- [x] wrong escaping and few are missing finf func 'ampforwp_framework_get_facebook_comments'
- [x] every message should be escaped and pass to translation string. Check this kind of statement in whole plugin. eg echo json_encode(array("status"=>300,"message"=>'Request not valid'));
- [x] use wp_json_encode instead of json_encode everywhere
- [x] undefined variable $thumb_url_array_2. components\related-posts\related-posts.php Line: 144, 148
- [x] every placeholder text should be escaped and pass to translation. check whole plugin and use esc_attr__(

**Comment by akshaywali** [comment]
pushed in 1.0.94
