### ISSUE TITLE
Youtube Shortcode Compatibility of Shortcode Ultimate Plugin

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#557]
ref:
http://www.camerpost.com/cameroun-nino-njopkou-jeune-entrepreneur-numerique/amp/
 [youtube url="https://youtu.be/JKHtRItE7KM" width="1000" height="600"]

**Comment by khaledMohammed000** [comment]
https://wordpress.org/plugins/shortcodes-ultimate/

The above issue is caused by this plugin and it does not seem to work with AMP well

**Comment by khaledMohammed000** [comment]
The plugin works Excellently with AMP
Editor:
http://take.ms/G6P8p
Output:
http://take.ms/KlHf3

**Comment by khaledMohammed000** [comment]
#428 has same issue since standard AMP plugin de hooks the youtube shortcode

**Comment by MARQAS** [comment]
#428 and this ticket are same

**Comment by retroriff** [comment]
It works, but when pages that doesn't have a Youtube embed code return this error message:

> The extension 'amp-youtube extension .js script' was found on this page, but is unused (no 'amp-youtube' tag seen). This may become an error in the future.

**Comment by ahmedkaludi** [comment]
@retroriff That's strange, it should be working perfectly. Can you share the URL?

**Comment by retroriff** [comment]
Yes, I will send it by email.

**Comment by ahmedkaludi** [comment]
Please send it to team@magazine3.com
