### ISSUE TITLE
noindex seo tags in page/2/ and stuff

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#558]
noindex seo tags in page/2/ and stuff

**Comment by Lofesa** [comment]
Same issue #469

**Comment by ahmedkaludi** [comment]
REVIEW:

1. Not all of them should be on by default: http://take.ms/qTt8o

2. When you say "On" what do you exactly mean? because On & Off does not make sense for the users in this case.

3. Don't add index/noindex in the option labels itself. The Labels should have the name and the it should be index/noindex instead of on/off.

4. All 4 options should have a section title called "Advanced Index & No Index Options"

**Comment by khaledMohammed000** [comment]
redone here : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a16d5e69347f1f33d5f3dc9c760a4e0a8b984867
