### ISSUE TITLE
Issue persist due to recent update with poll maker plugin

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5585]
Ref ticket: https://magazine3.in/conversation/232318?folder_id=21

Description:-
After recent update, globally disable poll shortcodes. It works, but removes that shortcode both in AMP and no AMP pages, so all polls have disappeared from user websites.

User provide the solution: commenting line:1891 in file includes/thirdparty-compatibility.php:

add_action('wp','ampforwp_poll_maker_remove_html');

**Comment by akshaywali** [comment]
pushed in update 1.0.95
