### ISSUE TITLE
Fatal error: Uncaught Error: rtrim(): Argument #1 ($string) must be of type string, WP_Error given

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5588]
Fatal error: Uncaught Error: rtrim(): Argument #1 ($string) must be of type string, WP_Error given in /var/www/wptbox/wp-content/plugins/accelerated-mobile-pages/components/breadcrumb/breadcrumb.php on line 131

**Comment by akshaywali** [comment]
pushed in update 1.0.95
