### ISSUE TITLE
Can we use Responsive AMP Ad units

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#559]
http://stackoverflow.com/questions/36774571/responsive-ads-for-amp-sites-width-only

**Comment by pegazee** [comment]
The functionality of Responsive AMP Ad units is not supported in AMP because it uses the javascript to get the responsive ads. @MohammedKaludi  please close the ticket.

**Comment by ahmedkaludi** [comment]
We
