### ISSUE TITLE
Trying to Reach out to o6asan (NOT STALKING, their website is down)

### ISSUE THREAD

**Issue by angelatwin333** [ahmedkaludi/accelerated-mobile-pages#5590]
Does anyone know how to reach o6asan?

I'm trying out to reach out, because their website for Hyohaku and any domain with the name o6asan is down.
Here's the link: https://o6asan.com/hyohaku/hyohaku-1/

I couldn't find any other way to reach out, not even through BBS contact (NetOwl security blocked me from commenting there). I can't access their translation for Hyohaku anymore.  It says ERR_ADDRESS_UNREACHABLE. I didn't save their email address either, and since it was on said website, I couldn't email either, hence I am trying to contact them here.

At first I thought the issue was with my server, but I realized it would happen regardless of device, browser of computers. I had a bunch of classmates try it with their respective servers, internet, and devices too-issue's with this website. I tried commenting on past forums/ issues o6asan commented on in github, but those issues were closed. Not sure is o6asan will receive notifications that a new comment has been posted.. I'm not sure how github works, so I think I ended up commenting on all o6asan's forums (created an account just to try to reach out). I know, seems like stalker ish behavior. I'm so sorry! Not trying to stalk at all, just desperate because Hyohaku is down, plus Hyohaku is a personal favorite of mine to read. I can't find any other translations for Hyohaku either.

**Comment by 77naveenop** [comment]
Please generate a ticket via https://ampforwp.com/support/ and we will address your issues.
