### ISSUE TITLE
PHP warning message displayed on the user's end.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5594]
Warning: Attempt to read property "post_date" on null in /home/www//wp-content/plugins/accelerated-mobile-pages/includes/features/structure-data/structured-data-functions.php on line 184

Warning: Attempt to read property "post_modified" on null in /home/www/wp-content/plugins/accelerated-mobile-pages/includes/features/structure-data/structured-data-functions.php on line 185

Warning: Attempt to read property "post_author" on null in /home/www/wp-content/plugins/accelerated-mobile-pages/includes/features/structure-data/structured-data-functions.php on line 195

Warning: Attempt to read property "post_content" on null in /home/www/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 352

Warning: Attempt to read property "post_content" on null in /home/www/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php on line 352

Warning: Attempt to read property "post_content" on null in /home/www/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4093

Ref Ticket : https://magazine3.in/conversation/271686?folder_id=29

**Comment by akshaywali** [comment]
pushed in 1.0.96
