### ISSUE TITLE
Warning: Undefined property: stdClass::$response in

### ISSUE THREAD

**Issue by pasgeeken** [ahmedkaludi/accelerated-mobile-pages#5598]
In the admin panel / Plugins it now shows these errors. I recently updated to PHP 8.2, perhaps this is related?

```
Warning: Undefined property: stdClass::$response in /home/REDACTED/public_html/wp-content/themes/Extra/core/components/Updates.php on line 782

Warning: foreach() argument must be of type array|object, null given in /home/REDACTED/public_html/wp-content/themes/Extra/core/components/Updates.php on line 782
```
![Screenshot 2024-05-17 094955](https://github.com/ahmedkaludi/accelerated-mobile-pages/assets/44490072/e4897054-4c8c-406b-813f-82d5230fa667)

**Comment by Sanjeevsetu** [comment]
hi @pasgeeken 

This warning does not seem related to AMPforWP. You are still facing the issue just contact us through https://ampforwp.com/support/
