### ISSUE TITLE
Alternate Mobile Tag for AMP Pages

### ISSUE THREAD

**Issue by Asif2BD** [ahmedkaludi/Accelerated-Mobile-Pages#56]
If you push the AMP version as the default one for mobile, you need alternate tag to keep Google Mobile Friendliness.

Here is a small approach - [link](https://github.com/Asif2BD/Alternate-Mobile-Tag-For-AMP)

When you bring that feature to select if anybody want to deploy amp in all their mobile visitor, then add this one in your code.

**Comment by nicholasgriffintn** [comment]
+1.

This is a great pointer, glad that someone has thought of this. I was thinking that it would awesome to redirect to AMP on mobile, but didn't think of this, it should be pretty simple to integrate too, and you could probably even put some options in the AMP plugin for your mobile domain, IE: if you have a mobile domain set to "m.example.com".

**Comment by MohammedKaludi** [comment]
Thank you @Asif2BD for pointing this out. 

I will get back to this ticket and the caching one, once I start working on the mobile redirection feature.

Thank you @Asif2BD and @nicholasgriffintn for your valuable feedback.

**Comment by MohammedKaludi** [comment]
Caching issue ticket reference: https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/issues/53
