### ISSUE TITLE
Add an option so that related posts can be opened in the NON-AMP version

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5600]
Add an option so that related posts can be opened in the NON-AMP version

Ref ticket: https://magazine3.in/conversation/267476?folder_id=27

**Comment by WasimM3** [comment]
Feature is already there
![image](https://github.com/user-attachments/assets/b8cbadbb-83e3-4fbe-846f-716e6499e7be)
