### ISSUE TITLE
When the AMPforWP plugin is enabled with the webstories plugin, then it shows an error in the AMP validator.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5601]
When we enable monetization, https://prnt.sc/LK1vcNeIs47C option in the Webstories plugin with the AMPforWP plugin, it shows an issue in the AMP validator: https://prnt.sc/nqI1hhrOyZC0. (User-end issue)

Ref ticket:https://magazine3.in/conversation/274254?folder_id=29

**Comment by WasimM3** [comment]
Not Recreating

**Comment by Sanjeevsetu** [comment]
It was user specific issue and no more exists. I am closing the ticket
