### ISSUE TITLE
While using the News12Paper theme and tagDiv Composer plugin, there is an issue with the AMP menu (user-end issue).

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5608]
While using the News12Paper theme and tagDiv Composer plugin, there is an issue with the AMP menu (user-end issue).

Ref screenshot:https://prnt.sc/a42nkOFR5QVh

Ref ticket:https://magazine3.in/conversation/280758?folder_id=29

**Comment by akshaywali** [comment]
pushed in 1.0.96
