### ISSUE TITLE
FV Gravatar Cache plugin conflicts with AMP.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/accelerated-mobile-pages#5611]
One user reported this issue that ,"The code in the plugin does not work – for those users who have avatars, the default one is still shown. " 

Reference ticket: https://wordpress.org/support/topic/correct-code-local-cash-gravatars-with-plugin-fv-gravatar-cache/

**Comment by akshaywali** [comment]
pushed in AMP for WP 1.1.1
