### ISSUE TITLE
NEW ERRORS IN MENU AND FOOTER

### ISSUE THREAD

**Issue by MIEZUCO1973** [ahmedkaludi/accelerated-mobile-pages#5620]
Errors in last version (1.0.96.1) with MENU HEADER and FOOTER. Words that have any written accent, ñ and special characters like emoticons are not seen correctly, signs appear instead.

**Comment by Sanjeevsetu** [comment]
Hi @MIEZUCO1973 

Have you checked with earlier version rollbacked. Please check once and confirm the same?

**Comment by MIEZUCO1973** [comment]
Hi!With version 1.0.95 all is fine. However, with higher versions there are errors with Ñ, spelling accents (tilde) and emoticons.






Jose MontesEl 1 ago 2024, a las 8:51, Sanjeev Kumar ***@***.***> escribió:﻿
Hi @MIEZUCO1973
Have you checked with earlier version rollbacked. Please check once and confirm the same?

**Comment by akshaywali** [comment]
pushed in 1.0.99
