### ISSUE TITLE
PHP warnings are appearing on user end

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5624]
Uncaught Error: Call to undefined function is_amp_endpoint() in /home/aris75/adiam.net/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php:1918 Stack trace: #0 /home/aris75/adiam.net/wp-includes/class-wp-hook.php(308): ampforwp_aal_content_fix('[et_pb_section ...') #1 /home/aris75/adiam.net/wp-includes/plugin.php(205): WP_Hook->apply_filters('[et_pb_section ...', Array) #2 /home/aris75/adiam.net/wp-content/themes/Divi/includes/builder/plugin-compat/wordpress-seo.php(92): apply_filters('the_content', '[et_pb_section ...') #3 /home/aris75/adiam.net/wp-includes/class-wp-hook.php(308): ET_Builder_Plugin_Compat_WordPress_SEO->do_shortcode('[et_pb_section ...') #4 /home/aris75/adiam.net/wp-includes/plugin.php(205): WP_Hook->apply_filters('[et_pb_section ...', Array) #5 /home/aris75/adiam.net/wp-content/plugins/wordpress-seo/inc/sitemaps/class-sitemap-image-parser.php(96): apply_filters('wpseo_sitemap_c...', '[et_pb_section ...') #6 /home/aris75/adiam.net/wp-content/plugins/wordpress-se in /home/aris75/adiam.net/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php on line 1918

Ref ticket https://magazine3.in/conversation/296992?folder_id=29

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5617
