### ISSUE TITLE
PHP Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/accelerated-mobile-pages#5626]
user reported this issue,"PHP Fatal error: Uncaught Error: Call to undefined function is_amp_endpoint() in /wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php" Also said, "the plugin is causing “There has been a critical error on this website” when I attempt to look at a sitemap from Yoast. When I disable the AMP plugin, I’m able to see the Yoast sitemap."

Reference ticket: https://wordpress.org/support/topic/php-fatal-error-442/

**Comment by mohammed-qutubuddin** [comment]
One more user faced the similar issue, below is the path.

/wp-content/plugins/accelerated-mobile-pages/includes/thirdparty-compatibility.php and line number 1918

Reference Screenshot: https://prnt.sc/BwAJVUm-Cs9A

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5617
