### ISSUE TITLE
Finnish characters was changes in 1.0.96 version.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5627]
Ref ticket:  https://magazine3.in/conversation/300284?folder_id=21

Description:
Characters was changed in AMP 1.0.96 version in menu.

Here is issue screenshot
https://prnt.sc/NMjrsoDR1nSY non-AMP
https://prnt.sc/9L2OyScw8YZr AMP

**Comment by MohammedAkramU7** [comment]
Another user turkey character changes in 1.0.96 version. Ref ticket: https://magazine3.in/conversation/305793?folder_id=21

**Comment by chopinesque** [comment]
See also https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5639

**Comment by akshaywali** [comment]
pushed in 1.0.99
