### ISSUE TITLE
Warning appears due to AMP pagebuilder extension.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5628]
Ref ticket: https://magazine3.in/conversation/103736?folder_id=21

Warnings:
 [STDERR] PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input in /home/ausffcom/public_html/wp-content/plugins/amp-pagebuilder-compatibility/amp-pagebuilder-compatibility.php on line 298\n
[STDERR] PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input in /home/ausffcom/public_html/wp-content/plugins/amp-pagebuilder-compatibility/amp-pagebuilder-compatibility.php on line 298\n
[STDERR] PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input in /home/ausffcom/public_html/wp-content/plugins/amp-pagebuilder-compatibility/amp-pagebuilder-compatibility.php on line 298\n

**Comment by Sanjeevsetu** [comment]
Ref commit https://github.com/ahmedkaludi/amp-pagebuilder-compatibility/commit/f38cbb38a420810050f8e8a061337e4ff7ecbe3c
