### ISSUE TITLE
Call Now Button 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#563]
Call Now Button

**Comment by MohammedKaludi** [comment]
@MARQAS Proper color for design #1 http://take.ms/vndvm

and I'm not able to find call now button in design 3 where is it?

**Comment by MARQAS** [comment]
@MohammedKaludi 
Color is same for all designs, which one should I give?
And sorry design 3 ka code sync nai hua tha sahi se

**Comment by ahmedkaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/54777b6ac07f358d4a4cfcac517fe127e19e247e
