### ISSUE TITLE
Conflict issue with Infinite Scroll option.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/accelerated-mobile-pages#5638]
Ref ticket: https://magazine3.in/conversation/306718?folder_id=21

Description:
H1 tag missing or empty message shows in href dashboard.

Here is the screenshot
https://monosnap.com/direct/nUn7YRuxiNjaKRBgEpi3KBncnivPau

**Comment by akshaywali** [comment]
pushed in 1.0.99
