### ISSUE TITLE
AMP menu not Unicode safe

### ISSUE THREAD

**Issue by chopinesque** [ahmedkaludi/accelerated-mobile-pages#5639]
If you click on the menu, you will not get proper Unicode characters:
https://ibb.co/ZWYtzgX
https://wordpress.org/support/topic/amp-menu-not-unicode-safe/

https://poiimata.com/

https://youtu.be/xG6HLrcB_CY

**Comment by Sanjeevsetu** [comment]
Hi @chopinesque 

We have released a new version 1.0.99.1 with this fix. Please update to it and know us.
