### ISSUE TITLE
Afterpay Gateway for WooCommerce plugin is causing issue in Amp Validator

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5643]
Afterpay Gateway for WooCommerce plugin is causing issue in Amp Validator

Ref screenshoot: https://prnt.sc/7oMo6wJsQV3m

Ref Ticket: https://magazine3.in/conversation/310277?folder_id=29

**Comment by akshaywali** [comment]
pushed in AMP for WP 1.1.1
