### ISSUE TITLE
ERROR LAST VERSION 1.0.99 WITH TAGS IN MENU

### ISSUE THREAD

**Issue by MIEZUCO1973** [ahmedkaludi/accelerated-mobile-pages#5646]
I updated to Version 1.0.99 and see several errors in MENU with this warning:
The tag ´<?´ is disallowed.

I have also received notification in Google Console

**Comment by Sanjeevsetu** [comment]
Hi @MIEZUCO1973 

We have just release an update v1.0.99.1. Could you please try with that and know us.
