### ISSUE TITLE
 The attribute 'data-videoid' in tag 'amp-youtube' is set to the invalid value

### ISSUE THREAD

**Issue by sinxwal** [ahmedkaludi/accelerated-mobile-pages#5648]
AMPforWP - 1.0.98.

I`m getting the error #5292 again.
Error message: The attribute 'data-videoid' in tag 'amp-youtube' is set to the invalid value ''

Can we locally disable amp_youtube_the_content hook somehow without editing templates/features.php file?

**Comment by Sanjeevsetu** [comment]
Hi @sinxwal

We are unable to re create the issue. We are closing the ticket. If you still have issue, Kindly create new ticket with more details or contact our support ( https://ampforwp.com/support/ )
