### ISSUE TITLE
Add a new feature to add Whatsapp Group links to Floating Buttons for AMP

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5649]
Add a new feature to add Whatsapp Group links to Floating Buttons for AMP

Ref ticket: https://magazine3.in/conversation/315458?folder_id=27

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
