### ISSUE TITLE
Latest version 1.0.99.1 causing Tag issue.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/accelerated-mobile-pages#5650]
One user reported this issue. Kindly refer the below ticket for better explanation.

Reference ticket: https://wordpress.org/support/topic/not-show-tags/

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by akshaywali** [comment]
pushed in AMP for WP 1.1.1
