### ISSUE TITLE
Add manual post selection in infinite scroll

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5651]
Need an option where user can control the infinite scroll post.

User want to set his own post on infinite scroll, he want to set by each individual post.

https://magazine3.in/conversation/316015?folder_id=19

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by akshaywali** [comment]
pushed in AMP for WP 1.1.1
