### ISSUE TITLE
Errors in debug.log, PHP Deprecated:  trim(): Passing null to parameter 

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/accelerated-mobile-pages#5652]
Reference ticket: https://wordpress.org/support/topic/errors-in-debug-log-13/

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by akshaywali** [comment]
pushed in AMP for WP 1.1.1
