### ISSUE TITLE
GA-4 Analytic not working on infinite scroll post

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/accelerated-mobile-pages#5656]
1. GA-4 is not counting the view for the second page.
2. Analytic count increasing 3 count on a single visit for a single post

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by akshaywali** [comment]
pushed in AMP for WP 1.1.1
