### ISSUE TITLE
The Last Modified date appears broken in the AMP version

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5659]
The Last Modified date appears broken in the AMP version

The bug occurred in version: 1.0.99.1

Ref screenshot: https://monosnap.com/direct/bF5CwCiMM5mCs2kDyo1XLVElf6eRIQ

Ref ticket: https://magazine3.in/conversation/322121?folder_id=27

**Comment by akshaywali** [comment]
pushed in AMP for WP 1.1.1
