### ISSUE TITLE
Few improvements part 2

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/accelerated-mobile-pages#5662]

**Comment by djixas** [comment]
Any more info on this? What's 112 release ETA?

**Comment by Sanjeevsetu** [comment]
https://magazine3.in/conversation/325344?folder_id=3

**Comment by MIEZUCO1973** [comment]
Any problem with version 1.1.1.? Works it fine?

**Comment by Sanjeevsetu** [comment]
Hi @djixas & @MIEZUCO1973 

There is no problem with version 1.1.1. Its very much fine. Its just normal coding improvement which is optional.

**Comment by MIEZUCO1973** [comment]
Great! Thank you so much 😊 I will update next week 

El 16 nov 2024, a las 13:31, Sanjeev Kumar ***@***.***> escribió:﻿
Hi @djixas & @MIEZUCO1973
There is no problem with version 1.1.1. Its very much fine. Its just normal coding improvement which is optional.
