### ISSUE TITLE
Logo custom sizes

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#568]
Logo custom sizes

**Comment by ahmedkaludi** [comment]
also see https://wordpress.org/support/topic/design-3-do-not-show-authors-description/

**Comment by khaledMohammed000** [comment]
Done here https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8ff5260a93a34a1735fd83304f25b32329a34cf5

**Comment by ahmedkaludi** [comment]
There should be a switch button with the text "Custom Logo Size" it should be turned off by default, when they on it, then it will display the fields with the default values. 

See: http://take.ms/fSuBG
