### ISSUE TITLE
YouTube videos are not working

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/Accelerated-Mobile-Pages#57]
YouTube videos are not working, video is not playing. 

amp-youtube-js is also not added.

**Comment by nicholasgriffintn** [comment]
I wrote #54, which seems to fix this. amp-youtube might provide better results than amp-iframe does, however, my pull fix does seem to be a fix for the amp-iframe problem.

**Comment by ahmedkaludi** [comment]
This was fixed in 0.8
