### ISSUE TITLE
Homepage Image size option in Loop

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#576]
Homepage Image size option in Loop

**Comment by ahmedkaludi** [comment]
Problem: Users want to change the image dimension of the Homepage posts loop.

Solution: There should be an option called "Custom Thumbnail Size" in the homepage section, which should be turned off by default. When we enable it, people can set the height and width of the thumbnail size of the homepage image. That way, they have more control over it. The default sizes should be the the ones, but I guess they are different in design 1, 2 and 3? 

Well, we can just make an option which is off by default, so that we use the current default values according to the design and then people can overwrite it if they want by enabling it.

Hope it helps,

**Comment by khaledMohammed000** [comment]
did a proper discussion with @ahmedkaludi and issue is taken care of

**Comment by MohammedKaludi** [comment]
Remove Overwrite image option in design 3

**Comment by MohammedKaludi** [comment]
Working.
