### ISSUE TITLE
Date in Design-3 is missing

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#583]
ref:  https://wordpress.org/support/topic/post-date-in-design-3/

**Comment by ahmedkaludi** [comment]
Code is not ready for production. Here are the changes:

The span should have a unique class to it. Preferably 'ampforwp-design3-single-date'
It should display after the category part.
It should be connected with an option. That option will allow users to show / hide date in the Single of Design 3. By default, it should be hidden or off.
