### ISSUE TITLE
Yandex Metrika support in AMP

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#585]
ref: https://wordpress.org/support/topic/yandex-metrika-liveinternet-counters/

**Comment by nicholasgriffintn** [comment]
I think it might be an idea to add a custom section in the analytics section for these kinds of things, so many analytics services, you can't support all of them.

**Comment by MohammedKaludi** [comment]
@nicholasgriffintn Yes, will add some basic tracking support and then for others, we will provide a text area, so users can add more analytics companies according to their requirement.

Thank you for your feedback, I'm glad to see your comment and it was helpful as always.
Take care,
Mohammed Kaludi
