### ISSUE TITLE
Option to hide/show AMP on all custom post types

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#587]
Users want to  show or hide AMP on custom post types.

For ex: They want the option of Show/Hide AMP on product pages just like on normal posts and pages

**Comment by ahmedkaludi** [comment]
The on/off AMP on the post only displays on the posts, we need to make it that it displays on all custom post types's page editor. Let me know if you have any questions @khaledMohammed000
