### ISSUE TITLE
Homepage is taking OG tags from the first post,

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#588]
The Homepage's OG (yoast) meta tags are from the Yoast, but in homepage, it is taking the data from the first post, instead it should have the homepage data or this data should only be displayed on the single posts.

See: view-source:https://www.maidcleaningnashville.com/amp/

IMAGE: http://take.ms/rnOJ9

**Comment by Lofesa** [comment]
Perhaps related to #546

**Comment by Lofesa** [comment]
perhaps [related](https://wordpress.org/support/topic/front-page-errors-2/)
