### ISSUE TITLE
Remove defer

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#589]
It is causing validation issues

ref: http://take.ms/ffBEZ

**Comment by khaledMohammed000** [comment]
https://www.druglawsuitsource.com/new-york-woman-files-ivc-filter-lawsuit/amp/
https://www.druglawsuitsource.com/amp/

both of the above links seem absolutely fine no occurrences of defer, can we close this issue once this gets recreated we can act immediately @ahmedkaludi  ?

**Comment by MohammedKaludi** [comment]
Working
