### ISSUE TITLE
Incompatibility with Custom Sidebar by WPMU DEV

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#590]
AMP options panel is not working when this plugin is activated

**Comment by Sejiro-Hiko** [comment]
I'm not seeing any compatibility issues with our plugin.

**Comment by pegazee** [comment]
I also checked,  And it seems that there are no issues in our plugin when we activate the Custom Sidebar by WPMU DEV plugin.

**Comment by MohammedKaludi** [comment]
Tested on multiple installations and seems working.
