### ISSUE TITLE
disable amp for forum plugin

### ISSUE THREAD

**Issue by fikryans** [ahmedkaludi/accelerated-mobile-pages#592]
hello i need some help, i've blog and using plugin wp-foro for making forum, how i disabled amp for forum slugs?
because i've got this error.
![screenshot_3](https://cloud.githubusercontent.com/assets/8897997/23090934/89d95c30-f5dc-11e6-9c67-37e51f9aa571.png)

**Comment by nicholasgriffintn** [comment]
You will probably be interested in #587 if I am right in thinking that the forum is using custom post types, some do some don't if it doesn't then it would be a case of implementing something different.

There's not much that you can do aside from wait for an option to turn it off it in the plugin (currently the plugin does allow you to turn it off for pages if they are pages, however, you can't do custom post types yet.), so you'll have to put up with the errors, they won't do no harm aside from being annoying.
