### ISSUE TITLE
Use of undefined constant AMP_QUERY_VAR

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#596]
Today I installed this plugin along with AMP.

The Plugin is great with all the required options. Thanks for the free version.

But I see two issues here.
1. two notices appear on the home page and admin page

Notice: Use of undefined constant AMP_QUERY_VAR – assumed ‘AMP_QUERY_VAR’ in /home/krazyu2i/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 25
Notice: Use of undefined constant AMP_QUERY_VAR – assumed ‘AMP_QUERY_VAR’ in /home/krazyu2i/public_html/wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 26

REF: https://wordpress.org/support/topic/use-of-undefined-constant-amp_query_var/

**Comment by khaledMohammed000** [comment]
done here https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5811ba884f1d97d07c40d05de9df7fc48f4781f4

**Comment by MohammedKaludi** [comment]
Closing it now.
