### ISSUE TITLE
Same wrong rel="amphtml" issue on my site

### ISSUE THREAD

**Issue by hayksaakian** [ahmedkaludi/accelerated-mobile-pages#597]
See: http://i.imgur.com/YHjGBVV.png

home page points to /amp/ instead of /?amp and so it shows the wrong content.
I have home page html defined with the amp editor, I don't want to show a blog roll, I want to show a page of written content.

I've resaved permalinks and flushed cache multiple times, this still hasn't updated

Here are the plugins i'm using:

http://i.imgur.com/Zu8XVbY.png

Same issue as these two:

https://wordpress.org/support/topic/wrong-homepage-rel-amphtml/
https://wordpress.org/support/topic/amphtml-url-incorrect/

**Comment by ahmedkaludi** [comment]
Hey @hayksaakian I just checked your URL with /amp and it's working http://www.iphonescreenrepairnear.me/amp

So, why do you think it's showing wrong URL if it's not /?amp ?

**Comment by hayksaakian** [comment]
Seems like it was some sort of cache causing it to show me the old one.

Please close this issue.

**Comment by ahmedkaludi** [comment]
@hayksaakian Sure. Thanks :)
