### ISSUE TITLE
Bugs noticed on Design 3

### ISSUE THREAD

**Issue by anirudhpulikonda** [ahmedkaludi/accelerated-mobile-pages#600]
1. Posts Slider is not working properly -
issue: Slider is displaying but the posts are movie Pretty Fast ( fast with a capital " F " ). In a span of 1 sec almost 10 posts are appearing ing the post slider

2. Including Search is an Awesome thing. Loving it. But...

Issue: Search is working on Amp site when browsed from Desktop browser. But it's now working on Mobiel Devices. Also tried several browsers like safari and chrome etc.,

When I hit Go nothing is happening. Please fix the issue.

**Comment by ahmedkaludi** [comment]
Hey @anirudhpulikonda 

Can you share the URL of the site? I'd like to see the reason of moving the slider too fast.

Also, regarding the search, We have fixed the issue in the latest update.

**Comment by anirudhpulikonda** [comment]
Thanks @ahmedkaludi 

All the bugs are fixed now, Thank you!. I haven't checked with the Search feature yet. I'll check and will let you know if the bug still exists or not? 
Anyway thanks, guys, You people are really awesome. AMP for WP is a revolutionary plugin in entire AMP plugins section. Looking forward to meeting you guys in Hyderabad in any meetup or event.

**Comment by ahmedkaludi** [comment]
Thanks @anirudhpulikonda
