### ISSUE TITLE
Google search results shows “Your page has AMP implementation errors"

### ISSUE THREAD

**Issue by ravibandakkanavar** [ahmedkaludi/accelerated-mobile-pages#602]
Hi,

My website pages contain Java programs. For these pages, google shows an error message in the search results saying “Your page has AMP implementation errors.” I do not see such error on other posts.

Following is the link:

http://krazytech.com/programs/a-login-application-in-java-using-model-view-controllermvc-design-pattern/amp

Also, the coding part is completely broken and looks like the post is truncated. I see only one part of the coding. (If you compare AMP and nonAMP page you will understand it)

&lt;table align=&quot;center&quot;&gt;
&lt;tr&gt;
&lt;td&gt;Username&lt;/td&gt;
&lt;td&gt;&lt;input type=&quot;text&quot; name=&quot;username&quot; /&gt;&lt;/td&gt;
&lt;/tr&gt;

I do not see the broken/truncated code for another post
http://krazytech.com/programs/java-programs/java-registration-page-using-servlet-mysql-mvc/amp

Is there any way that I skip AMP for selected pages/posts?

Your help would be appreciated.

**Comment by nicholasgriffintn** [comment]
It seems to be the following code:

```
<servlet -class>. 
</servlet><servlet -class>com.mvc.controller.LoginServlet</servlet>
```

That code would either have to be removed for the AMP version of the page or the plugin would have to have some new code to filter out the tag, depending on what the plugin author wants to do.

**Comment by MohammedKaludi** [comment]
Hey @ravibandakkanavar,
You can turn off AMP for specific pages and we have the option built in post page check out this screenshot http://take.ms/kzFvc

and as @nicholasgriffintn mentioned, there is some code that is breaking blockquote and that is messing up the output.

**Comment by ahmedkaludi** [comment]
@ravibandakkanavar 

You should embed code with Gist. I am sure it's possible to embed gist with AMP.

**Comment by ahmedkaludi** [comment]
we are closing this to stay focused
