### ISSUE TITLE
Design 3 Optimization

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#603]
Design 3 drops Google Page Speed score (from 86 “Green” to 62 “Red”) and the first cause is from Render Blocking CSS https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|PT+Serif:400,700

Design 2 not have this problem, but 3 rocks!

Ref:  https://wordpress.org/support/topic/design-3-drops-google-page-speed-score/

**Comment by Dibbyo456** [comment]
Wo... That is horrible. But any thought of ways to fix?

**Comment by Sure-no** [comment]
I'm not technical but I think you try this

<script type="text/javascript">
WebFontConfig = {
	google: { families: [ 'Open+Sans+Condensed:300'] } };
	(function() {
		var wf = document.createElement('script');
		wf.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
		wf.type = 'text/javascript';
		wf.async = 'true';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(wf, s);
	})();
</script>

**Comment by ahmedkaludi** [comment]
@Sure-no But the custom Javascript is not allowed on the AMP.

**Comment by Sure-no** [comment]
It's only an idea. I'm not programmer

**Comment by ahmedkaludi** [comment]
@Sure-no Yes, We really appreciate that! and we are working on solving this with some creative solution.

**Comment by ahmedkaludi** [comment]
There are pro's and cons for everything. 

I'm closing this for now.
