### ISSUE TITLE
AMP Frontpage + Override AMP Content = Blank page

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#604]
Try to setup a frontpage for the AMP section and then use the option "Use AMP content" from the post editor and then see the homepage, You will find that it is blank

**Comment by MohammedKaludi** [comment]
Fixed.

**Comment by clicknathan** [comment]
When I updated to the most recent version, neither my home nor blog page would show any content? I tried with custom content and the checkbox under the AMP settings (in the post / page editor) as well as without that.

**Comment by ahmedkaludi** [comment]
Hey Nathan @clicknathan 

This fix has not been released yet. it will be released in the next update on Saturday. 

The latest version does not has this code yet.

**Comment by michieldewit** [comment]
Seems like a pretty serious problem. Sure there is no way to fix this earlier?

**Comment by ahmedkaludi** [comment]
Hey @michieldewit 
It is possible if you try this commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/adf7dd6d82369659ae3ef6c2a2ae8e063dae5e15

or directly try the beta version, but this is a beta version: https://github.com/ahmedkaludi/accelerated-mobile-pages/tree/0.9.44

But please use it with care.

Regards,
Ahmed

**Comment by michieldewit** [comment]
My blog is still not showing any content: http://www.michieldewit.nl/2014/04/29/ochtendmist/amp/. Updated to 0.9.44

**Comment by jaspersorrio** [comment]
Is this fixed?

**Comment by khaledMohammed000** [comment]
Yes Jasper it was fixed 2-3 versions before 🎉

**Comment by jaspersorrio** [comment]
I can't seem to get my front page working.
http://racking.com.sg/amp/

**Comment by clicknathan** [comment]
Hi Khaled & team - this doesn't appear to be fixed at all. :(

Even if you turn on Pages in General Settings, then choose "Homepage Support" and/or try and set a custom Page as Front Page, once you do this there is no longer a page to show all of your posts.

That is, custom front page and the page you set to show your posts will both show the same content, always, no matter what settings you use.

**Comment by khaledMohammed000** [comment]
Hey @clicknathan @jaspersorrio @michieldewit we will recheck everything related to this issue, really sorry for the inconvenience @MohammedKaludi we nee to make this work once and for all 👍

**Comment by sandeep24041995** [comment]
neither my home nor blog page would show any content?

**Comment by sandeep24041995** [comment]
it doesn't show my custom blog or pages anyone can help me
