### ISSUE TITLE
Gist Support 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#608]
https://github.com/ampproject/amphtml/issues/829
https://github.com/ampproject/amp-by-example/issues/90

**Comment by MARQAS** [comment]
https://ampbyexample.com/components/amp-gist/

**Comment by ahmedkaludi** [comment]
Wow @MARQAS Good Job on this finding! We must have this!

**Comment by MARQAS** [comment]
Just add a shortcode and enjoy Devs (Ex: [amp-gist id="b9bb35bc68df68259af94430f012425f"] )

**Comment by MohammedKaludi** [comment]
Tested and code is working nicely, but need to convert it as Gist Sanitizer in future.
