### ISSUE TITLE
The Tag Font is disallowed

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#616]
The Tag Font is disallowed in AMP.
Many users are getting this error, we need to fix this.

ref: http://take.ms/8CBwA
https://sps-priority.co.il/%D7%90%D7%A8%D7%9B%D7%99%D7%95%D7%9F-%D7%93%D7%99%D7%92%D7%99%D7%98%D7%9C%D7%99-%D7%91%D7%A4%D7%A8%D7%99%D7%95%D7%A8%D7%99%D7%98%D7%99/amp/

**Comment by MohammedKaludi** [comment]
Checked and it is working.
