### ISSUE TITLE
Forty

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#617]
Forty

**Comment by khaledMohammed000** [comment]
@ahmedkaludi you need to collaborate with Raju on this from where i have left :)

**Comment by ahmedkaludi** [comment]
@MohammedKaludi  Please check your telegram

**Comment by MohammedKaludi** [comment]
1. test it with some default widgets and
2. Default value of AMP Category post numbers are not working.

**Comment by khaledMohammed000** [comment]
works perfectly fine, just made a small change in the default value
