### ISSUE TITLE
Validation Error: "The attribute 'type' may not appear in tag 'amp-iframe'."

### ISSUE THREAD

**Issue by dayhawkkim** [ahmedkaludi/Accelerated-Mobile-Pages#62]
This results in 'Validation Status: Fail'. Thanks!

**Non-AMP Code:**

`<iframe class='youtube-player' type='text/html' width='1020' height='604' src='https://www.youtube.com/embed/BXmIpbBOSvI?version=3&#038;rel=1&#038;fs=1&#038;autohide=2&#038;showsearch=0&#038;showinfo=1&#038;iv_load_policy=1&#038;wmode=transparent' allowfullscreen='true' style='border:0;'></iframe>`

**AMP Code**

`<amp-iframe class='youtube-player' **type='text/html'** width='640' height='390' src='https://www.youtube.com/embed/BXmIpbBOSvI?version=3&#038;rel=1&#038;fs=1&#038;autohide=2&#038;showsearch=0&#038;showinfo=1&#038;iv_load_policy=1&#038;wmode=transparent' allowfullscreen='true' ></amp-iframe>`

**Comment by MohammedKaludi** [comment]
@dayhawkkim Thanks for reporting, we are going to release a major update in few day and these issues will be fixed in that release.

Thank you once again for reporting the bug.
Mohammed Kaludi

**Comment by dayhawkkim** [comment]
@MohammedKaludi Thanks! Look forward to it.

**Comment by ahmedkaludi** [comment]
This was fixed in the 0.8 release
