### ISSUE TITLE
Homepage and Blog page always show the same content

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#620]
Perhaps I posted about this before, but if your WP setup is to show a static page on the homepage and choose another page for your latest blog posts (in Settings > Reading), and then you set this plugin to show Page content vs. latest blog posts on the homepage (in Amp > General Settings > ), then this Page content shows up on both the homepage and the page for latest blog posts.

This also happens if you try and customize the content via the custom field in the Page editor for the homepage or blog post pageholder.

REFERENCE: https://wordpress.org/support/topic/homepage-and-blog-page-always-show-the-same-content/#post-8843565

**Comment by MohammedKaludi** [comment]
Fixed in #775
