### ISSUE TITLE
Posibility to rewrite links in posts and menu to AMP version

### ISSUE THREAD

**Issue by woutheijnen** [ahmedkaludi/accelerated-mobile-pages#627]
Hi,

Would it be possible to automatically rewrite link urls in AMP enabled posts and pages?
For example if mysite.com/post1/amp has a link in the text going to mysite.com/post2/ and the post is AMP enabled, could it be possible to automatically rewrite it to mysite.com/post2/amp ?

Other cases would be if post2 is not AMP enabled, it should not rewrite the link to /amp and keep it how it is. Or if the link goes to another site, then also it should not rewrite the link.

Similarly, I would like to request this for the menu so we can use 1 menu for both the main website and the AMP enabled website :).

Hope on the best for this amazing plugin.
Cheers!

**Comment by ahmedkaludi** [comment]
we will resume it in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1156
