### ISSUE TITLE
Featured Image Excluded From AMPforWP

### ISSUE THREAD

**Issue by dayhawkkim** [ahmedkaludi/Accelerated-Mobile-Pages#63]
Images inserted into blog posts as the Featured Image are excluded from AMP.

Was this by design? Other images that inserted as media into the post appear just fine.

Thanks.

**Comment by MohammedKaludi** [comment]
Yes, this was intentional. But we will create an option in future to Show/Hide featured image in single post.

So users will have more control.

**Comment by ahmedkaludi** [comment]
This was fixed in d1be130cec3de0122dc13a59ff89660c62045b0c
