### ISSUE TITLE
In Search AMP rel canonical is different

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#631]
When opening a  page from Search AMP rel canonical is different.

ref: http://take.ms/h0ye5

**Comment by khaledMohammed000** [comment]
done in https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/bbe4ba12981e8e5c12acaafa8795b069bda55c3a and https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/6bdefa50be3c5808b1d2744f9e04aaa01b436c68

**Comment by MohammedKaludi** [comment]
Fixed as add the search support for design one and two, and it will not give the broken page
