### ISSUE TITLE
Accordian script loads if the dropdown menu is not setup in design 3

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#634]
Accordian script loads if the dropdown menu is not setup in design 3

REF: https://wordpress.org/support/topic/few-issues-with-my-amp-version-website/

**Comment by MohammedKaludi** [comment]
Seems working.

**Comment by IvanPr** [comment]
I still get this issue with the Custom Theme.
Perhaps you should wrap the menu into the <amp-accordion>?

Warning quote:
The extension 'amp-accordion extension .js script' was found on this page, but is unused (no 'amp-accordion' tag seen). This may become an error in the future.

**Comment by IvanPr** [comment]
p.s. Tag 'amp-accordion > section' must have 2 child tags with first child tag being one of ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'header']

The usage of the accordion for the menu is improper therefore...

**Comment by IvanPr** [comment]
If the drop-down menu does not have child elements, the amp-accordion library can be removed using the following code in the child-theme:

// Remove AMP-accordion Library
add_filter( 'amp_post_template_data', 'gp_ampforwp_add_design3_required_scripts', 101 );

function gp_ampforwp_add_design3_required_scripts( $data ) {
	unset($data['amp_component_scripts']['amp-accordion']);
	return $data;
}

**Comment by MARQAS** [comment]
The issue still remains, re-opening this ticket.
@MohammedKaludi we have to find a better solution for this
