### ISSUE TITLE
should there be JSON-Ld even for search pages ?

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#636]
because there isn't any

**Comment by nicholasgriffintn** [comment]
You shouldn't really allow Google to index your search pages, that's pretty bad SEO, so no not really.

**Comment by khaledMohammed000** [comment]
@nicholasgriffintn thanx for the reply :)

**Comment by khaledMohammed000** [comment]
check commit : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c3f59a49de27e9de332018f58f73291877fb14e8

**Comment by MohammedKaludi** [comment]
All the search pages are noindex and nofollow so search engines are notified not to crawl the search pages of the site. but for the validation satisfaction of the users, we are adding the SD in search pages.
