### ISSUE TITLE
All in one SEO Support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#646]
All in one SEO Support

**Comment by khaledMohammed000** [comment]
They are adding it, let's follow the Progress:
 https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/733

Also there are many other tickets open here related to AMP
https://github.com/semperfiwebdesign/all-in-one-seo-pack/search?q=amp&type=Issues&utf8=%E2%9C%93

**Comment by MohammedKaludi** [comment]
All in one seo guys are going to add this code in their next update.
commit ref : https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/02c81349b677f05f9ab9eb9f90e2fb305c741e07
