### ISSUE TITLE
Correctly displays only the main page. The second level shows the error:

### ISSUE THREAD

**Issue by Michaelyurov** [ahmedkaludi/Accelerated-Mobile-Pages#66]
Correctly displays only the main page. The second level shows the error:
Warning: include(/home/mystart/oftalmika.com/www/wp-content/plugins/accelerated-mobile-pages/themes//oftalmika/template-single-service.php): failed to open stream: No such file or directory in /home/mystart/oftalmika.com/www/wp-includes/template-loader.php on line 89

Warning: include(): Failed opening '/home/mystart/oftalmika.com/www/wp-content/plugins/accelerated-mobile-pages/themes//oftalmika/template-single-service.php' for inclusion (include_path='.:/usr/local/pear/php54') in /home/mystart/oftalmika.com/www/wp-includes/template-loader.php on line 89

**Comment by MohammedKaludi** [comment]
Have you deactivated the plugin? As I cannot see the amp on oftalmika.com

Also, if you are trying to add AMP on custom post types, it is not supported yet, but it will be supported very soon, as we are working on the update which will release on few days.

Thanks.

**Comment by Michaelyurov** [comment]
I deactivated the plugin due to incorrect display, so as not to lose traffic.

01.09.2016 16:25, Mohammed Kaludi &lt;notifications@github.com&gt;
 
Have you deactivated the plugin? As I cannot see the amp on oftalmika.com
Also, if you are trying to add AMP on custom post types, it is not supported yet, but it will be supported very soon, as we are working on the update which will release on few days.
Thanks.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
 
     


-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by ahmedkaludi** [comment]
This issue was after the 0.8 release.
