### ISSUE TITLE
Undefined Index causing UX problems

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#661]
See: http://take.ms/uikV3

**Comment by khaledMohammed000** [comment]
there are still issues on search.php and this occurs when there is nothing found, to fix this we need to solve it the empty-filter.php way .... apart from this search.php has no errors

**Comment by khaledMohammed000** [comment]
i think the issue with archive.php on all designs is there is no custom query for loop....instead we have a standard line from wordpress...thats the issue i guess
