### ISSUE TITLE
Website's social media links in the footer not working in Social Media Profiles (Design #3)

### ISSUE THREAD

**Issue by vartiksethi** [ahmedkaludi/accelerated-mobile-pages#662]
In the Social Media Profiles (Design #3), the website links that are available in the footer are not working. Like, there is this Facebook URL section. When I enter my URL there. Example: www.facebook,com/nutkhatt.
It redirects to www.nutkhatt.com/facebook.com/nutkhatt instead of just facebook.com/nutkhatt.

Kudos to your great work, please fix this small error:) 

Thanks.

**Comment by ahmedkaludi** [comment]
Hey, Are you sure you are adding the link with http? like http://facebook.com/nutkhatt  ? because that's required for the link, just www doesn't work.

I hope that helps.

**Comment by vartiksethi** [comment]
Thanks bro, it works now
  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=vartik.sethi97@gmail.com&idSignature=22>
