### ISSUE TITLE
Incompatibility twitter and Instagram embed

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#664]
Twitter, Instagram Embed support in AMP 

Ref: http://rd1.com.br/hugh-jackman-encontra-dublador-brasileiro-de-wolverine-e-emocao-rola-solta/amp/

**Comment by nicholasgriffintn** [comment]
Was it added as an iframe code to the site or did you copy the link in? If you just copy the link of an Instagram or Twitter post into the post of an article then the embed will work as Wordpress will automatically format that into AMP compatible code for you, if you paste an embed code in it doesn't.

**Comment by ahmedkaludi** [comment]
We need to test the both embeds properly.

**Comment by khaledMohammed000** [comment]
Just as @nicholasgriffintn pointed out simply paste your Instagram or twitter post URL in the editor and AMP sanitizer will do their magic

ref http://take.ms/VPq54

Works perfectly 👍

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn  I have seen many people adding using blockquote to embed instagram video. I wonder where they are they getting that code from.

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi I believe it is the default embed code from Instagram, I think it's just that a lot of people don't know that you don't have to go through that trouble, just paste in the URL of the item that you want to embed.
