### ISSUE TITLE
Excerpt on top of the content in Single

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#665]
Add Excerpt on top of the content in Single AMP page

Ref: http://take.ms/mHejy

**Comment by nicholasgriffintn** [comment]
A bit of php code added to the single.php file for the design that you have chosen (templates/design-manager/YOURDESIGN) should do that for you.

Something like this (change the number at the top for length):

`<?php
the_excerpt_max_charlength(140);

function the_excerpt_max_charlength($charlength) {
	$excerpt = get_the_excerpt();
	$charlength++;

	if ( mb_strlen( $excerpt ) > $charlength ) {
		$subex = mb_substr( $excerpt, 0, $charlength - 5 );
		$exwords = explode( ' ', $subex );
		$excut = - ( mb_strlen( $exwords[ count( $exwords ) - 1 ] ) );
		if ( $excut < 0 ) {
			echo mb_substr( $subex, 0, $excut );
		} else {
			echo $subex;
		}
		echo '[...]';
	} else {
		echo $excerpt;
	}
}
?>`

Or as simple as this:

`<?php $excerpt = get_the_excerpt( $post ) ?> `

Source: https://codex.wordpress.org/Function_Reference/get_the_excerpt

**Comment by MohammedKaludi** [comment]
Tested.
