### ISSUE TITLE
Add / at the end of AMP links with in the AMP pages (Internal links) 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#668]
Add / at the end of AMP links with in the AMP pages (Internal links) 

Ref: https://secure.helpscout.net/conversation/327491766/11292/?folderId=1060551

**Comment by khaledMohammed000** [comment]
Please ignore https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1dacdffa2e57ceaefb3d54c18e363d85f767453a created into wrong branch

**Comment by ahmedkaludi** [comment]
fixed recently https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/b7e71f605f16bff2fb2242dff434412231a84963
