### ISSUE TITLE
No fixed size for images in amp and validation errors due to a plugin

### ISSUE THREAD

**Issue by intelezsol** [ahmedkaludi/Accelerated-Mobile-Pages#67]
I want to report 2 issue
**1)** 
My site is techwhack.com. Check out my site page's non-amp version first http://goo.gl/MtK3k9 Here you can see the size of images are proportionate. Moreover, you can see the stars marked in the picture are small sized and properly aligned.
![screen shot 2016-09-06 at 4 24 20 pm](https://cloud.githubusercontent.com/assets/20015363/18271246/c4cd67b0-744e-11e6-9b78-9651c4c48401.png)
But in amp version. Check here http://goo.gl/RARD2e. These stars are large sized and are not aligned.
**2)**
Moreover, I am using a ratings plugin called kk star ratings plugin. This plugin is creating 5 validation errors. Check out its validation below
http://goo.gl/Eomfg3
![screencapture-validator-ampproject-org-1473159774936](https://cloud.githubusercontent.com/assets/20015363/18271429/9e70e514-744f-11e6-8558-75a490a37b7c.png)
Please fix these issues as soon as possible.

**Comment by ahmedkaludi** [comment]
This was fixed in the recent update.
