### ISSUE TITLE
Featured Image not displaying on Design two 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#670]
Some people are reporting this bug after the recent 0.9.44
- https://wordpress.org/support/topic/feature-image-no-longer-showing/#post-8877004

We still don't have the proof but let's keep an eye on this.

**Comment by ahmedkaludi** [comment]
Similar issue was once re-created into the @riyaz95 's localhost. Let me check it with him first before we close this ticket.

**Comment by riyaz95** [comment]
#707 is the same issue so we will be continuing this

**Comment by MohammedKaludi** [comment]
Issue is exactly as mentioned in #707 
If the same image in Featured-image and the_content then no Featured image is showing.

I went deep to find the issue and it was coming from default AMP plugin.
Check out:
amp/includes/class-amp-post-template.php in line no 262

// If an image with the same ID as the featured image exists in the content, skip the featured image markup.
// Prevents duplicate images, which is especially problematic for photo blogs.
// A bit crude but it's fast and should cover most cases.

Now the solution, I'm going to propose a filter (amp_allow_featured_image) to AMP team with a pull request. From which code anyone can change the value.

Code: 
$post_content = $this->post->post_content;
if ( true !== apply_filters('amp_allow_featured_image', false) && ( false !== strpos( $post_content, 'wp-image-' . $featured_id )  || false !== strpos( $post_content, 'attachment_' . $featured_id ) ) ) {
	return;
}

I hope after this pull request, we will be able to allow the users either show or hide featured image.

Mohammed Kaludi

**Comment by ahmedkaludi** [comment]
haven't faced of this issue since long time. Safe to close.
