### ISSUE TITLE
Align left and align right of design 2 doesn't look right in the mobile

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#671]
Align left and align right of design 2 doesn't look right in the mobile

REF: https://wordpress.org/support/topic/responsive-images-in-amp/#post-8876103
Example: http://guidetodetailing.com/amp/

**Comment by MohammedKaludi** [comment]
@ahmedkaludi need to discuss with you on this ticket.

**Comment by MohammedKaludi** [comment]
Have tested on posts as well pages, with and without caption and it is working correctly. Added the screenshot as well.

![image alignment test](https://cloud.githubusercontent.com/assets/16618009/24826889/f47e0b38-1c5d-11e7-9c36-321190762759.png)
