### ISSUE TITLE
 Global button for Social Share 

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#673]
One Single button to turn off all Social Sharing Buttons. In case if I don't want social buttons to appear I should turn off every social sharing button manually. Instead of it, a Global button to Turn Off Social Share buttons.

**Comment by pegazee** [comment]
This issue is already resolved. the option is in Appeareance>AMP>design> just untick the Social Icon.
ScreenShot> http://take.ms/JyMe3
So, I'm Closing this issue
