### ISSUE TITLE
Woopra support

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#676]
Woopra Analytics Support

Reference: https://secure.helpscout.net/conversation/328866292/11325/?folderId=1060551

**Comment by khaledMohammed000** [comment]
There does not seem to be any support for Woopra from AMP team and also they have closed this issue for now
ref links:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md
https://github.com/ampproject/amphtml/issues/2475
