### ISSUE TITLE
SEO by SQUIRRLY is adding analytics twice

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#678]
SEO by SQUIRRLY is adding analytics twice

**Comment by MARQAS** [comment]
@ahmedkaludi can you tell me what settings in SEO Squirly is adding the analytics.?
I tried to recreate this issue, but I am not getting the error.

**Comment by ahmedkaludi** [comment]
@MARQAS Sure, I'll give it to you in a second.

**Comment by ahmedkaludi** [comment]
@MARQAS Their UI is very confusing... Here is the screenshot: http://take.ms/Gz9RF - scroll down to the bottom of the screen.
