### ISSUE TITLE
WP-rocket incompatibility with rel=”amphtml” tag 

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#689]
WP-rocket plugin with CSS minification is incompatable with rel=''amphtml'' tag.
 https://secure.helpscout.net/conversation/327996425/11302/?folderId=1060556

**Comment by nicholasgriffintn** [comment]
That sounds like an issue for WP-Rocket TBH, you should bring it up with them considering that will be an issue for them with all AMP plugins, not just this one.

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn Yes, but it's our users who are facing the problems. We have tried to take some steps to solve this.

Hopefully the code we applied in 0.9.45 should fix this issue.
