### ISSUE TITLE
AMP Page without /?amp or /amp at the end

### ISSUE THREAD

**Issue by shubam12342344** [ahmedkaludi/accelerated-mobile-pages#69]
How can i view my amp version without adding /?amp at the last in the url i just want when the users visted my blog posts amp version should be automatically display .

**Comment by ahmedkaludi** [comment]
Hey @shubam12342344 

We are working on a redirect feature, which will allow you do to so.

I am sure this can be done.

**Comment by MohammedKaludi** [comment]
Mobile redirection feature added in 0.9.2 announcement link https://ampforwp.com/mobile-redirection/
