### ISSUE TITLE
JW player compatibility  needs to be added.

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#691]

**Comment by nicholasgriffintn** [comment]
Hey, I just created a pull request for this #693, I reckon that should do the job.

**Comment by khaledMohammed000** [comment]
Thanx alot for the commit, we would like to know how have you tested this ?

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn have you tested this?

**Comment by nicholasgriffintn** [comment]
@khaledMohammed000 and @ahmedkaludi, I use this code myself to load up a script for JW Player, the only issue is that you have to enter the JW Player tag code yourself, IE: 

```
<amp-jwplayer
    data-player-id="aBcD1234"
    data-media-id="5678WxYz"
    layout="responsive"
    width="16" height="9">
</amp-jwplayer>
```

I've not yet figured out how to change the code from JW Player to the AMP code as that differs depending on how you are embedding it, are you using the plugin? Or just adding in the code manually? That's a bit more coding than I have time for, however, this does work if you are okay with adding the AMP code manually, which is better than nothing.

**Comment by ahmedkaludi** [comment]
Another Ticket, https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/362 

Closing this for now
