### ISSUE TITLE
Post images are not centered in Design 3

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#695]
Post images are not centered in design 3, it is looking like it is right aligned.
Not featured, just post images.

Ref: http://www.motorverso.com/living-massive-isuzu-d-max-arctic-trucks-at35/amp/

**Comment by MohammedKaludi** [comment]
i think its amp-anim?

**Comment by MohammedKaludi** [comment]
Alignment still not working in design 3 with caption check out image http://take.ms/sdEEh

working in design 2 checkout this https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/671#issuecomment-292701927

**Comment by MohammedKaludi** [comment]
@riyaz95 check and fix the ticket please

**Comment by MohammedKaludi** [comment]
Fixed and tested with and without a caption, image float left, right and center.
