### ISSUE TITLE
Parent Page Re-direction after Plugin Deactivation. 

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#698]
When both the AMP plugins are deactivated, /amp page must return to parent page instead of 404 

Ref > http://take.ms/PXfG7

**Comment by khaledMohammed000** [comment]
In plugin deactivation hook add new rewrite rules, I could not recreate everywhere but yes at few pleaces it got recreated and it gave 404

**Comment by ahmedkaludi** [comment]
Can be achieved by following this tutorial https://ampforwp.com/tutorials/fix-404-on-amp/
