### ISSUE TITLE
Issue while activation

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#70]
REPORTED: https://wordpress.org/support/topic/plugin-could-not-be-activated-because-it-triggered-a-fatal-error-133/

I think your plugin might be clashing with this one that we have enabled:

Social Structured Data

as that one seems to be using some sort of a ReduxFramework as well.

Can you add a check for that somehow, so that if Redux is loaded by another plugin yours doesn’t end up looking for it or something? I dunno how that works…

**Comment by khaledMohammed000** [comment]
#35
