### ISSUE TITLE
GTM Tests as per the mrzimmy on WP.org forums

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#700]
Needs testing as per: https://wordpress.org/support/topic/google-analytics-163/

**Comment by Verticalmag** [comment]
@ahmedkaludi all pages on verticalmag.com and skiesmag.com (except home pages) are running the AMP plugin and have GTM ID attached.  I see the GTM ID inserted in the footer on amp pages by the plugin but it fails to trigger properly.  I'm getting HTTP response code indicates tag failed to fire: Status 403 when using Googles Tag Assistant extension in chrome.

**Comment by Verticalmag** [comment]
Hi @ahmedkaludi  Have you been able to review / confirm my observations about AMP content not being recorded with GTM?

**Comment by Verticalmag** [comment]
Hi @ahmedkaludi,
I can even see it breaking when I do a webpagetest.org

[](http://www.webpagetest.org/result/170322_7B_YVJ/1/details/#waterfall_view_step1)
  

URL: https://www.googletagmanager.com/amp.json?id=GTM-PSNT2C&gtm.url=https%3A%2F%2Fwww.verticalmag.com%2Ffeatures%2Frecording-issues-industry-slow-embrace-fdm%2Famp%2F&__amp_source_origin=https%3A%2F%2Fwww.verticalmag.com
Loaded By: https://cdn.ampproject.org/v0.js:345
Host: www.googletagmanager.com
IP: 216.58.217.72
**Error/Status Code: 403**

**Comment by Verticalmag** [comment]
I'm still not able to track analytics with google or with google GTM.


www.skiesmag.com/:1 Fetch API cannot load https://www.googletagmanager.com/amp.json?id=GTM-XXXXXXXX&gtm.url=https%3A%2F…lands-montreal%2Famp%2F&__amp_source_origin=https%3A%2F%2Fwww.skiesmag.com. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.skiesmag.com' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
error.js:128 Fetch failed  https://www.googletagmanager.com/amp.json?id=GTM-XXXXXXX&gtm.url=https%3A%2F…lands-montreal%2Famp%2F&__amp_source_origin=https%3A%2F%2Fwww.skiesmag.com : Failed to fetch
Hd @ error.js:128
f.assert @ log.js:301
(anonymous) @ xhr-impl.js:164
error.js:135 No request strings defined. Analytics data will not be sent from this page.​​​
Hd @ error.js:135
f.error @ log.js:214
Bc @ amp-analytics.js:445
push.f.h.$a @ amp-analytics.js:187
error.js:135 Ignoring event. Request string not found:  pageview​​​


Any updates?  I have been looking at others that user your plugin and they too are not tracking,  I'm not sure if anyone else is aware how big of an issue this really is for your clients.

**Comment by khaledMohammed000** [comment]
@Verticalmag this  will be fixed in tomorrow's update , please don't worry 👍

**Comment by khaledMohammed000** [comment]
Hello @Verticalmag I have seen the above URL's you have provided and have seen the issue that you have, I have made changes tot the UI of GTM section https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/da689f989f27a3ba545aca9519c7c65fff1d69c4 

It is observed from your URL that you have not given **type=**  value  on your GTM code that is on those URLS

I have now made all fields compulsory like so in the image, so you won't be able to save unless you enter all the required fields
![image](https://cloud.githubusercontent.com/assets/16471728/24829612/d3cdb55c-1c92-11e7-9332-d1c0d8b010c0.png)

**Comment by khaledMohammed000** [comment]
@Verticalmag you can immediately fix your issue by entering **Analytics Type value** since that is actually missing on those URL's that you have provided

**Comment by MohammedKaludi** [comment]
Tested and seems working.
