### ISSUE TITLE
Sub Categories not properly getting redirected to AMP When Category Base is removed 

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#705]
When Category base is removed, Sub Categories not properly getting redirected to AMP. 

Ref: https://wordpress.org/support/topic/bad-redirections/

**Comment by MohammedKaludi** [comment]
Check the Issue with new version of category base remover and test if issue persists.

**Comment by MohammedKaludi** [comment]
tested on multiple systems and it is working as expected
