### ISSUE TITLE
Undefined index : Paged Issue in PHP 7 

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#710]
Undefined index : Paged Issue in PHP 7  

Ref: https://wordpress.org/support/topic/undefined-index-paged/

**Comment by sybrew** [comment]
The fix would be this.

From:
```
if ( is_home() && $wp->query_vars['paged'] >= '2' ) {
```

To:
```
if ( is_home() && isset( $wp->query_vars['paged'] ) && $wp->query_vars['paged'] >= '2' ) {
```

This also accounts for the upcoming check for archives.

**Comment by khaledMohammed000** [comment]
Already done in the previous update 0.9.48

**Comment by MohammedKaludi** [comment]
Needs Testing.
