### ISSUE TITLE
W3 Total cache proper implimentation

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#713]
http://hookr.io/plugins/w3-total-cache/0.9.5.1/filters/w3tc_minify_js_enable/

http://hookr.io/plugins/w3-total-cache/0.9.5.1/filters/w3tc_minify_css_enable/

Due to the wrong code at https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5c776ffbfcd45a7c40a675c4d5ed07ac95b62578  - We faced alot of fatal error issues in php 7.1

So, we need to properly test and do it.

Check: Error log attached
[error_log.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/857662/error_log.txt)

SEE the line number: http://take.ms/tOkmp

**Comment by MohammedKaludi** [comment]
Closing the ticket. More at #936
