### ISSUE TITLE
Images in Comment must become AMP Compatible

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#714]
Images in Comment must become AMP Compatible

Ref: https://wordpress.org/support/topic/can-you-fix-my-bugs-in-search-console/#post-8934515

**Comment by osseonews** [comment]
I second this request. Google throws errors whenever there are images in comments. The reason is because the images in comments are not converted to the proper AMP format.

**Comment by khaledMohammed000** [comment]
Hey @osseonews I have also created a generalized function for sanitization of html to amphtml, you can use it everywhere you want to sanitize the content

Its called **ampforwp_sanitize_html_to_amphtml** it takes one parameter that is String of html to be sanizied and returns the string of AMPHTML code, you dont have to worry about scripts the function takes care of that too automatically 👍

**Comment by khaledMohammed000** [comment]
AN Example usage of this usage of this Helper Function can be seen here in this commit : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/c3200b66d6a9734ea6e0e72ff837e18d3dd06758

**Comment by osseonews** [comment]
Thanks. I will test this on comments with images.

**Comment by osseonews** [comment]
Hi there,
We tried to use the function but got an error: "Call to undefined function ampforwp_sanitize_html_to_amphtml()" Where is this function defined? It is not the latest release on wordpress yet? Can you please let us know so we can copy the function to our dev server. thanks.

**Comment by osseonews** [comment]
Has this ever been fixed? Plan to open up another ticket about this. This is an essential fix, as any images in comments are not AMP compatible.

**Comment by khaledMohammed000** [comment]
@osseonews rest assured this Saturday you will receive 0.9.47 update which will have this fix also look at the 0.9.47 branch issues that will get fixed by this weekend, since past two weeks we were working on absolutely complete code base revamp , you can see its around 200+ commits ahead of master, we will merge part by part of that branch into master over few weeks, we are really sorry fr the Delay 👍

**Comment by MohammedKaludi** [comment]
Working smoothly.

**Comment by MohammedKaludi** [comment]
@khaledMohammed000 
Reverted the ampforwp_content_sanitizer() and need to create a new sanitizer for this.
As ampforwp_content_sanitizer is not working adding the content elements in the comments / descriptions added by the third part plugins.

**Comment by osseonews** [comment]
This is a bit confusing here. Does the 0.9.4.7 version fix this bug? Or does the fix simply introduce new errors, so it is best to not install 0.9.4.7 until the errors are fixed?

**Comment by MohammedKaludi** [comment]
@osseonews  There was some issue with the sanitizer in 0.947 but soon it was reverted in next minor version. And this has been fixed now.
