### ISSUE TITLE
Ad#2 not working on design-3 frontpage.php

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#719]
# Dont Close this Until everyone has tested this and have Given Green Signal 👍 
## Steps Todo for Entire Team : 

Check all Ads first from normal plugin on All designs

- [x] index.php
- [x] frontpage.php
- [x] single.php
- [x] archive.php
- [x] search.php

Check all Ads first from Our Ads Extension plugin on All designs

- [x] index.php
- [x] frontpage.php
- [x] single.php
- [x] archive.php
- [x] search.php

**Comment by khaledMohammed000** [comment]
This may be working but is being outputted in wrong place ? 🤔🤔🤔🤔🤔

**Comment by riyaz95** [comment]
Everything seems to be working fine. All Ads are getting displayed properly....!!!!

**Comment by riyaz95** [comment]
In design 3, 

In advertisements, Ad#2 output is above footer

In Paid Ads, Ad Output is below Footer
