### ISSUE TITLE
New update breaks doesn't include anything

### ISSUE THREAD

**Issue by aashishpahwa** [ahmedkaludi/Accelerated-Mobile-Pages#72]
The new update doesn't include anything
I can't see my images, ads, videos. All i can see is text. Not even the logo of my website (navigation is written on the top instead of logo).
IDK if it's because of my caching plugins as it wasn't an issue before
Please see to it
Website www.feedough.com
caching plugins used autoptimise, wp supercache, speed booster pack

**Comment by ahmedkaludi** [comment]
Can you please send your WP-admin info to my email? ahmed [at] magazine3.com ?

**Comment by ahmedkaludi** [comment]
@aashishpahwa Can you please post an update on this ticket?

**Comment by aashishpahwa** [comment]
Hi, my defer settings of speed booster pack were not compatible with the
plugin. The plugin works fine now.
