### ISSUE TITLE
WP-Rocket is not working after activating Plugin 0.9.45.3

### ISSUE THREAD

**Issue by IRM89** [ahmedkaludi/accelerated-mobile-pages#720]
The Feature "Lazy Load" from Images is not working when your AMP plugin is activated.

**Comment by ahmedkaludi** [comment]
Hey @IRM89 

I have personally checked and it seems to be working fine.

1. Could you share the URL? 
2. Was it working with previous version, meaning before updating to this version?


Thank you for using the plugin and also helping us improve it.

**Comment by ahmedkaludi** [comment]
3 more users reported the issue, so we need to look into this.

**Comment by IRM89** [comment]
Hi @ahmedkaludi .
0.9.45.5 has also this issue.

Featured Images has no lazy-src attribute after activating the amp plugin. See the both pictures.

![bildschirmfoto 2017-03-26 um 10 57 46](https://cloud.githubusercontent.com/assets/24268250/24329908/984c4554-1213-11e7-9095-6506ef82ca15.png)
![bildschirmfoto 2017-03-26 um 10 57 14](https://cloud.githubusercontent.com/assets/24268250/24329909/9a2460fa-1213-11e7-88d0-ea6ff4f9da19.png)

**Comment by ahmedkaludi** [comment]
@IRM89 Are you still having this issue?

**Comment by IRM89** [comment]
WP-Rocket is now working fine with the new AMP Plugin Update. No issues here.

**Comment by MohammedKaludi** [comment]
@ahmedkaludi need to test this before closing the ticket, I need your help in testing out this ticket.

**Comment by MohammedKaludi** [comment]
We don't have enough data to make sure if this issue is fixed or not. So, closing the ticket after discussing with Ahmed.
