### ISSUE TITLE
Add More Hooks

### ISSUE THREAD

**Issue by osseonews** [ahmedkaludi/accelerated-mobile-pages#721]
I suggest adding more Hooks to the theme. Specifically, hooks should be added to the "content/elements" files, which show elements in the actual post. These elements are controlled by just one filter: ampforwp_design_elements, which makes it very difficult to customize. I suggest adding more action hooks to each of the elements/*.php files. This will make it easier to add stuff via via the functions.php file, instead of modifying the plugin files. 

As an example, we added our own action to the elements/related-posts.php file. We added: do_action(‘ampforwp_post_before_related_posts’) - which now allows us to add custom content for the Related Posts element which shows up on every post.

**Comment by ahmedkaludi** [comment]
@osseonews Thank you so much for using the plugin and helping us improve the plugin.

I have added this in the my priority list. We will start working on this and release it in the next update for sure.

We would appreciate any pull requests you could send. 

Regards,
Ahmed

**Comment by MohammedKaludi** [comment]
We have more hooks now yay!!! 
Before and after every design elements and more hooks added, hope it will help devs.

Mohammed Kaludi
