### ISSUE TITLE
UI menu admin bar is broken 

### ISSUE THREAD

**Issue by tutv95** [ahmedkaludi/accelerated-mobile-pages#722]
Screenshot:

![5b56f40955574d1fb5b71d3ee6d3896a](https://cloud.githubusercontent.com/assets/7255177/24184970/3b3be2e2-0f03-11e7-87d5-8db3e6ec894f.png)

**Comment by ahmedkaludi** [comment]
Thank you so much for using the plugin and helping us improve it.

May I know which version of the plugin are you using?

Because, we decided to remove that Menu from the wp-admin bar in 0.9.45. But are you still seeing that menu item?

Regards,
Ahmed

**Comment by nicholasgriffintn** [comment]
Report and Issue and Request a feature are supposed to be the same menu item under my understanding, so I would say his pull is correct, there shouldn't be a <br> tag there, and the code is there in the most recent version.

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn Exactly. The code @tutv95 sent is for the options panel and not the wp-admin bar.

We have already removed the options link from the wp-admin bar.

So I am closing the ticket. Thank you so much for helping us improve the product.
