### ISSUE TITLE
Custom AMP Editor is not functioning proproerly on frontpage

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#724]
When using Custom AMP Editor on posts, it is working perfectly fine and taking the size of post images automatically, but when using Custom AMP Editor on the frontpage, it is not taking the size of post images automatically. showing this error.  http://take.ms/dQlet

**Comment by khaledMohammed000** [comment]
Tested and its working absolutely fine, But still need your opinion on this @ahmedkaludi
