### ISSUE TITLE
Tables responsiveness in ALL Designs 

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#726]
Tables are not responsible in ALL Designs. Tables must be made Responsive / Scrollable in all designs. 

Ref: https://secure.helpscout.net/conversation/331506616/11380/?folderId=1060551

**Comment by nicholasgriffintn** [comment]
This is correct.

Thanks for pointing this out because that's a problem I just noticed I had myself.

**Comment by nicholasgriffintn** [comment]
I've just had a mess around and got my own tables responsive with the following css:

```
table {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    overflow-x: auto;
}
```
