### ISSUE TITLE
ON/OFF button for Navigation Menu [PS]

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#735]
A ON/OFF button to be created for Navigation Menu. 

Ref: https://secure.helpscout.net/conversation/336921419/11575/?folderId=1060551

**Comment by nicholasgriffintn** [comment]
This is something I have had in my own code for some time now as I didn't want the menu to show up either.

I have cleaned up the code and submitted a pull request for it, I have been using this code since I first used the plugin, so I know it works.
