### ISSUE TITLE
Homepage Support must be Off, when we turn Off Homepage Support.

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#738]
Homepage Support must be Off, when we turn Off Homepage Support.

Ref: https://secure.helpscout.net/conversation/338254797/11626/?folderId=1060551

**Comment by ahmedkaludi** [comment]
When it's turned off, the amphtml tag gets removed from the homepage, so technically no AMP page is asscociated with that page. therefore, it's safe to assume that homepage support has been turned off. 

The most ideal scenario would be that we redirect it to homepage but that again will cause validation issues.

So, the current option seems like a safe setting.

Therefore, I am closing this ticket.

**Comment by khaledMohammed000** [comment]
This is not solved yet, Example URL : https://goo.gl/k6rt4m
