### ISSUE TITLE
Notice warnings since 0.4.2 update

### ISSUE THREAD

**Issue by LiamMcArthur** [ahmedkaludi/accelerated-mobile-pages#740]
Since upgrading to version 0.4.2, two PHP notices have appeared when viewing an AMP page:

`Notice: Undefined variable: structured_data_logo in C:\xampp\htdocs\example\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 725`

`Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\example\wp-content\plugins\wordpress-seo\frontend\class-twitter.php on line 476`

**Comment by khaledMohammed000** [comment]
this ticket was done this way because the i=cause couldn't be understood be me
