### ISSUE TITLE
Issue with titles after 0.9.45.5 update

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#744]
Ref: https://fototrekking.com/amp/  shows a wrong title "temas y consejos…" (title for a category), not the correct one "Calendario…" for this page.

Ref: https://secure.helpscout.net/conversation/340521189/11748/?folderId=1060551

**Comment by MohammedKaludi** [comment]
Fixed in commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/647d25803b22ba2034e50085ed17d2553460dffd

and will be pushing out this in next update. Which is due on Saturday 8th April.

**Comment by MohammedKaludi** [comment]
Tested with and without yoastseo and its working,
