### ISSUE TITLE
Option to turn off AMP on all pages, so people can turn on only for specific pages

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#746]
Option to turn off AMP on all pages, so people can turn on on specific pages

**Comment by MARQAS** [comment]
Option to turn off pages is already there, we have to add an option which allows us to keep AMP on specific pages if AMP on pages option is set to disable

**Comment by MohammedKaludi** [comment]
Working, tested on multiple environments.
