### ISSUE TITLE
Fatal error: require_once report-bugs.php

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#747]
( ! ) Warning: require_once(/wp-content/plugins/accelerated-mobile-pages/templates/report-bugs.php): failed to open stream: No such file or directory in /wp-content/plugins/accelerated-mobile-pages/accelerated-moblie-pages.php on line 132

Ref: https://wordpress.org/support/topic/fatal-error-require_once-report-bugs-php/

**Comment by khaledMohammed000** [comment]
@MohammedKaludi this I could not recreate but I could see that it's done a different way , so redid this again

**Comment by ahmedkaludi** [comment]
0.9.47.1 release fixed
