### ISSUE TITLE
Ads issue with RTL Support

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#749]
Ads are showing cut in the half and also ads go to the left in mobile mode.

Ref: https://secure.helpscout.net/conversation/343316912/11854/?folderId=1060551
       https://secure.helpscout.net/conversation/343303744/11853/?folderId=1060551
       https://secure.helpscout.net/conversation/336353102/11539/?folderId=1060551
       https://secure.helpscout.net/conversation/342962515/11840/?folderId=1060551

**Comment by MohammedKaludi** [comment]
Working.
