### ISSUE TITLE
ACF Support Advanced custom fields

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#75]
ACF Support Advanced custom fields

**Comment by ahmedkaludi** [comment]
we will release this as an extension

**Comment by nfsarmento** [comment]
Hi, do you have release time for this extension ? Thank you.

**Comment by khaledMohammed000** [comment]
@nfsarmento very soon this will be out , will get back to you once we have tested it fully 👍

**Comment by ahmedkaludi** [comment]
This was released https://ampforwp.com/acf-amp/
