### ISSUE TITLE
Add Compatibility with  Lazy load plugin

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#751]
Add Compatibility with  Lazy load plugin

Ref: https://wordpress.org/support/topic/lazy-load-images-4/

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/15224ad100133d27eaf7c388adc42e246dd55a91

**Comment by MohammedKaludi** [comment]
Tested and its working.
