### ISSUE TITLE
Thrive content needs to go through amp sanitizer

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#754]
Thrive content needs to go through amp sanitizer

this is where they add the content: http://take.ms/9LeIv

**Comment by MohammedKaludi** [comment]
Tested with Thrive Content Builder with multiple elements and its working correctly. All the builder content is sanitizing and images and youtube videos are properly converting to amp-img and amp-iframe.

Closing the ticket.
