### ISSUE TITLE
Design-3 Slider URL redirecting to non-AMP page 

### ISSUE THREAD

**Issue by koffisani** [ahmedkaludi/accelerated-mobile-pages#758]
I remarked that the slider's URL ends up with `//amp`. So it's redirecting to non-AMP page.
I think this is due to the fact that `the_permalink()` function return a URL ending up with `/`. On line [82](https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/design-3/index.php#L82) of this [file](https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/templates/design-manager/design-3/index.php), you should remove the `/` before `amp`.
```
<a href="<?php the_permalink(); ?>/amp">
```
Into : 
```
<a href="<?php the_permalink(); ?>amp">
```
Cc @khaledMohammed000 @ahmedkaludi @MohammedKaludi

**Comment by khaledMohammed000** [comment]
This has been done in the previous update itself 👍 @koffisani  please lemme know if it got fixed

![image](https://cloud.githubusercontent.com/assets/16471728/24853130/b1388844-1df7-11e7-876c-e5cfa20438f9.png)

**Comment by koffisani** [comment]
I've updated my plugin, but remaked that the slider url doesn't end with `amp` nor `amp/`.

**Comment by MohammedKaludi** [comment]
@koffisani Fixed this issue. I'm sure this will now work flawlessly.

Thank you for reporting.

**Comment by koffisani** [comment]
Right. Thanks. @MohammedKaludi @khaledMohammed000
