### ISSUE TITLE
AMP woocommerce widget

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#763]
AMP woocommerce widget

**Comment by khaledMohammed000** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5d0dc17c4c0f42accf02bc586dea27f82e333c76

https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/8871f8bc612592d63a039aa4085663509473e44b

**Comment by MohammedKaludi** [comment]
1. Labels are missing. http://take.ms/7Ed6X
2. Titles are missing in the post http://take.ms/u9NpA
3. Widget title is left aligned.

**Comment by khaledMohammed000** [comment]
lables : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/586a68479ac947b16a1fcd88e0beaef2f522754d

**Comment by MohammedKaludi** [comment]
@ahmedkaludi need to discuss with you on this.
