### ISSUE TITLE
Latest post shows in the title

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#769]
1. activate yoast seo
2. set a custom frontpage from reading settings.
3. and then check the homepage:

video: https://monosnap.com/file/osXpnmeBS8XrcLczLSctQlMJwJ8POH

REF: https://wordpress.org/support/topic/roundup-of-all-the-issues-i-have/

**Comment by MohammedKaludi** [comment]
Working Tested with Yoast SEO as well.
