### ISSUE TITLE
Test SHOW MORE POSTS button in mobile using Design 3

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#771]
“Show more posts” redirects to the wrong page. So We have to Test SHOW MORE POSTS button in mobile using Design 3

**Comment by khaledMohammed000** [comment]
Testing works perfectly

**Comment by MohammedKaludi** [comment]
Working Tested on the mobile phone with and without mobile redirection turned ON.

**Comment by MARQAS** [comment]
This issue still persists 
example URL: https://www.meilleursgadgetsdunet.com/maison/toilettes/amp/

**Comment by MohammedKaludi** [comment]
Dug deep and found out that it was only happening to TagDiv's newspaper theme. And working with all the default themes and with some other themes as well.

Checking now what exactly is the issue with the Newspaper theme.

Closing this ticket as there is no issue as it is reported and continuing this ticket on  https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/842 and https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/796
