### ISSUE TITLE
Issues with Featured image in Design 3 in 0.9.47

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/accelerated-mobile-pages#773]
When I updated the plugin from 0.9.43.1 to 0.9.43.5 or later, the featured images on my site will not be shown.
I just downgrade the plugin to 0.9.43.1, the featured image is back.
Kindly check it, the file accelerated-mobile-pages.0.9.43.5\accelerated-mobile-pages\templates\design-manager\design-3\elements\featured-image.php is different from the previous versions.
Please check the link of my site.

Ref: https://secure.helpscout.net/conversation/347268842/0/

**Comment by riyaz95** [comment]
Ref: https://secure.helpscout.net/conversation/347018622/0/?folderId=1060551

**Comment by MohammedKaludi** [comment]
this is related to #670 and mentioned in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/670#issuecomment-292542432

**Comment by MohammedKaludi** [comment]
Closing for more details please refer  #670
