### ISSUE TITLE
add amp_post_template_above_footer hook global in all the designs

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#779]
make amp_post_template_above_footer hook global in all the designs

**Comment by khaledMohammed000** [comment]
replace with ampforwp_home_below_loop

**Comment by khaledMohammed000** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/1450ea4af7277624083cb9060b983dedc2b5319a

**Comment by MohammedKaludi** [comment]
Working and tested by adding ads.
