### ISSUE TITLE
404 on paged home page

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#781]
Steps to recreate
http://take.ms/067P3

**Comment by khaledMohammed000** [comment]
the same url works with ?amp http://localhost/wordpress/page/2/?amp

**Comment by khaledMohammed000** [comment]
in case of front page it does not work well even with the ?amp

**Comment by riyaz95** [comment]
What about On Page 1/ Page 2 / Page 3? 

Its working there too?
