### ISSUE TITLE
0.9.48 Pre-release issue: 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#782]
- [x] Comment button is blank ( https://monosnap.com/file/WnqBRcZPvSFnuwYEbQxfmJUNlw8Vsz )

- [x] Tags CSS was compromised ( https://monosnap.com/file/WnqBRcZPvSFnuwYEbQxfmJUNlw8Vsz )

- [x] Custom CSS Box default text

**Comment by MohammedKaludi** [comment]
Working,
