### ISSUE TITLE
Twitter handle should be at the end of the tweet not in the beginning

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#787]
the twitter share button doesn't work if you put your twitter handle in, when it tweets it puts @marqas36 at the start of the tweet so the tweet is sent to me and not shared with the followers, the twitter handle should be at the end of the tweet not the start and would usually say via @yourname
http://take.ms/XYznM

**Comment by ahmedkaludi** [comment]
@MARQAS It was party fixed but not from all the places, so I did it in this commit: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/df796ce7efe9d3a1aa8893713c60d3eccf8e7888

Fixed and closed.
