### ISSUE TITLE
How to disable amp on this page/url

### ISSUE THREAD

**Issue by fikryans** [ahmedkaludi/accelerated-mobile-pages#789]
i've plugin forum called wp-foro.
thats plugin make a new page called /forum.
when i see log error on google webmaster.
i see too many error on this url.
how to disable amp for indexing for this url?
can i use robots.txt to disallow this url /forum/amp ?
thx
![screenshot_124](https://cloud.githubusercontent.com/assets/8897997/25209140/3ab639b0-25a3-11e7-9a75-1d341a481a29.png)

**Comment by ahmedkaludi** [comment]
@fikryans Can you please give me an update on this? Does this still happen?
