### ISSUE TITLE
Needs testing with Titles 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#800]
https://wordpress.org/support/topic/meta-info-on-amp-post-is-wrong-if-a-static-home-page-is-set/

**Comment by khaledMohammed000** [comment]
replied to the reporter of this issue, since that particular point he made could not be created in both master and also int the development branch @MohammedKaludi

**Comment by ahmedkaludi** [comment]
Let's discuss this and finalize.
