### ISSUE TITLE
Optimising the rows that you add to Wordpress

### ISSUE THREAD

**Issue by nicholasgriffintn** [ahmedkaludi/accelerated-mobile-pages#801]
Hey,

I've just been doing some maintenance if my database to get rid of some old rows within the postmeta table and I noticed what you guys have added and was wondering if there were ways to optimize this.

In particular, I noticed 'ampforwp-amp-on-off' which is set to 'default' the whole way through, would it not be better to set this to default without using the database and only use the database if the user selects something else?

On top of this, 'ampforwp_custom_content_editor' is being added even when there's no custom content, this should not be the case, same for 'ampforwp_custom_content_editor_checkbox'.

When you have a lot of posts like I do, this is a lot of data for no real reason.

**Comment by ahmedkaludi** [comment]
If you could give me some more details?

**Comment by nicholasgriffintn** [comment]
Well, I don't know how much more I can add really lol.

Basically, the plugin adds a value for every post for the 'ampforwp-amp-on-off' tag, this fills up the postmeta table quite quick and I was thinking that it might be better to simply set this tag to default without the need for the database, I'm sure you could set this to off without the need for a database.

The second part was simply that values are being added to the database when you're not using them.

**Comment by ahmedkaludi** [comment]
Sure, @nicholasgriffintn 

Let me get some info on this from @ajeetku

**Comment by nicholasgriffintn** [comment]
That sounds great, I would love to see this plugin a little more optimised.

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
This will be taken care in the Performance ticket #3732
