### ISSUE TITLE
OneSignal integration on AMP pages

### ISSUE THREAD

**Issue by partnershipweb** [ahmedkaludi/accelerated-mobile-pages#807]
I am not a technical user, but I am trying to add Onesignal web push notification to my AMP pages. As I understand it, this can only be done with the non-amp pages right now. I have found that the Onesignal repo links to a recently created AMP extension which specifically allows web push notifications with native AMP pages. I am hoping this javascript code can be used to enable Onesignal to work with the AMP pages on my website. It is available here - https://github.com/OneSignal/amp-push-notifications
If this extension does not solve the problem or cannot be easily integrated, is there another solution?
Thank you

**Comment by ahmedkaludi** [comment]
@partnershipweb Thank you so much for showing me this! We have started working on this one.

**Comment by pegazee** [comment]
One more request from user,

Ref: https://secure.helpscout.net/conversation/427779994/16022/?folderId=1060551
https://documentation.onesignal.com/docs/amp-web-push-setup

**Comment by ahmedkaludi** [comment]
We are already working on this as an extension. It will be released soon. Closing this ticket.

**Comment by MohammedKaludi** [comment]
Merging the integration in the core, @MARQAS will do the integration.

**Comment by ahmedkaludi** [comment]
https://www.instagram.com/p/BayYBU9nMC9/?igref=ogexp
