### ISSUE TITLE
PHP warnings in debug mode

### ISSUE THREAD

**Issue by NilsHoyer** [ahmedkaludi/accelerated-mobile-pages#808]
I enabled the debug mode of WordPress inside the `wp-config.php` with this:
```PHP
define('WP_DEBUG', true);
```

After this, I see on all my pages this waring:
```
Notice: A session had already been started - ignoring session_start() in /var/www/clients/client4/web22/web/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php on line 25

Notice: Undefined index: ampforwp_amp_mode in /var/www/clients/client4/web22/web/wp-content/plugins/accelerated-mobile-pages/includes/redirect.php on line 26
```

Should I try to find a solution and offering it as a Pull Request?

**Comment by MohammedKaludi** [comment]
Hey @NilsHoyer,

Thank you for reporting the issue. 

That would be great if you could send us the Pull Request. Your help in improving this plugin will be highly appreciated.

Thank you,
Mohammed Kaludi
