### ISSUE TITLE
Meta Titles and Description on Home page

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#813]
Custom frontpage shows the title from the blog post.

Ref: https://wordpress.org/support/topic/meta-titles-and-description-home-page/#topic-9080526-replies
Screenshot: http://take.ms/7kZad

**Comment by ahmedkaludi** [comment]
and also http://take.ms/CLaEb

**Comment by pegazee** [comment]
Not only in custom frontpage, This issue also in default HomePage.

Ref:  https://secure.helpscout.net/conversation/356634029/0/?folderId=1060551

ScreenShots: 
In AMP> http://take.ms/yGD9y
In Non-AMP> http://take.ms/L1sGy

**Comment by infokurs** [comment]
Sorry, but not fixed. Look test page http://homely-salmon.w4.poopy.life/amp/
current title: "Home | Sandbox"
correct title: "My Home Title"
Look to weird meta name and meta property tags.

Tested and working fix: https://wordpress.org/support/topic/meta-titles-and-description-home-page/#post-9097273

**Comment by infokurs** [comment]
still doesn't work >> http://homely-salmon.w4.poopy.life/amp/

**Comment by infokurs** [comment]
>> https://wordpress.org/support/topic/meta-titles-and-description-home-page/page/2/#post-9125829
