### ISSUE TITLE
"Show More Posts" tab should be hidden when there are no Posts on second page

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#816]
"Show More Posts" tab should be hidden when there are no posts on the second page. 

Ref: https://secure.helpscout.net/conversation/357756360/12555/?folderId=1060551

**Comment by ahmedkaludi** [comment]
If there is no Next Page available, it should not show the next page.

**Comment by Sejiro-Hiko** [comment]
The issue has been already fixed.

Tested On Index, Archive pages, and everything working as expected.

**Comment by MohammedKaludi** [comment]
Yes, tested and its working.
