### ISSUE TITLE
BUG: Logo size is do not applying

### ISSUE THREAD

**Issue by LeoKesler** [ahmedkaludi/accelerated-mobile-pages#817]
Hello,
In **AMP->Structured Data->Default Structured Data Logo**, any image inserted is always ignored and the default value of 190x36 is used.

Using AMP Bench Validator, it show a FAIL about the logo do not being at correct size:
https://ampbench.appspot.com/

Publisher Logo
(Top Stories with AMP) 
**FAIL**
Schema.org Type [ImageObject] Image Height [36] Width [190]
[invalid: should be either 60px high (preferred) or 600px wide]
Image URL [PASS: Publisher logo image URL appears to be valid]
[PASS] [HTTP: 200] URL is reachable using agent: [Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)]

**Comment by MohammedKaludi** [comment]
Hey @LeoKesler Can you please give me the URL of the post so that i can check and help you

Thank you so much for using the plugin

Regards,.

**Comment by MohammedKaludi** [comment]
Might be related to issue https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/162 But will check the issue in detail while fixing the ticket.
