### ISSUE TITLE
Safari Browser, Website Scroll instead of Menu items 

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#823]
Ref: https://secure.helpscout.net/conversation/357056794/12515/?folderId=1060551

In Safari browser, WebSite Scroll instead of menu items.

**Comment by MohammedKaludi** [comment]
I think this is working, but just need to test before closing the ticket,

**Comment by MohammedKaludi** [comment]
Tested on Safari 10.3 ios and tested page :https://ampforwp.com/demo/two/amp/
