### ISSUE TITLE
Fatal error while activation: see the video 0.9.49 Beta

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#827]
http://take.ms/IUwQO

**Comment by MohammedKaludi** [comment]
Fixed.

**Comment by infokurs** [comment]
Notice:  Trying to get property of non-object in /var/www/public/homely-salmon/wp-content/plugins/accelerated-mobile-pages-0.9.49/accelerated-moblie-pages.php on line 39

**Comment by MohammedKaludi** [comment]
@infokurs are you sure you downloaded the latest copy coz i just fixed it and tested it in commit https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/080daef63bea0b72b7b267126f627650ad5d70d9 

Can you please check it once and do let me know.

**Comment by infokurs** [comment]
@MohammedKaludi, yes. Latest version from git, after #827, #813 and #826 commits.

btw, #813 - still doesn't work
Look: http://homely-salmon.w4.poopy.life/amp/

**Comment by infokurs** [comment]
and:

Notice:  AMP_Post_Template::verify_and_include was called incorrectly. Path validation for template () failed. Path cannot traverse and must be located in `WP_CONTENT_DIR`. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 0.1.) in /var/www/public/homely-salmon/wp-includes/functions.php on line 4138
Notice:  Undefined variable: post_id in /var/www/public/homely-salmon/wp-content/plugins/accelerated-mobile-pages-0.9.49/templates/design-manager/design-3/style.php on line 5
