### ISSUE TITLE
The tag 'amp-sidebar extension .js script' appears more than once in the document

### ISSUE THREAD

**Issue by danielmrey** [ahmedkaludi/accelerated-mobile-pages#828]
The Chrome extension "AMP Validator" says: The tag 'amp-sidebar extension .js script' appears more than once in the document. This will soon be an error. Debug. Learn more.

Looked in the code and this appears twice:
<script custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js" async></script>

Thank you!

Daniel

**Comment by MohammedKaludi** [comment]
@danielmrey thank you for reporting, we will look into the this and will get back to you.

Can you please tell me which design you are using,

Thank you.

**Comment by danielmrey** [comment]
http://www.medlar.in/amp/

Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by MohammedKaludi** [comment]
@MARQAS

**Comment by Sejiro-Hiko** [comment]
Hey @danielmrey,

Thank you for making us notice this issue which is quite strange. 

Could you please give me the login info, so that I can look into it further to resolve the issue.
you can send us the info at team@magazine3.com, please notify me here also.

Regards,
Mohammed Asif.

**Comment by danielmrey** [comment]
Sorry, is a client website and I cannot give the login.

But I can do any test that you want me to do...

Thank you!


Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by danielmrey** [comment]
-- Please reply above this line --


Hey,

Even you understand without troubleshooting, we can't do anything.
Could you please make the staging site for us? and share the info. So,
that we can troubleshoot and resolve that issue.

Hope you understand, Let me know.

Regards,
Abdul Azeem
Team AMPforWP 
 (About Our Team [1])

Links:
------
[1] https://goo.gl/1LGjzO

**Comment by Sejiro-Hiko** [comment]
Hey @danielmrey,

Are you using any other AMP plug-in or made any changes to it.
And are you giving us the staging site login info?

Regards,
Mohammed Asif.

**Comment by danielmrey** [comment]
I only have "*Accelerated Mobile Pages: AMP for WP - Accelerated Mobile
Pages for WordPress Version 0.9.49 | By Ahmed Kaludi, Mohammed Kaludi*"
 And the other one needed "*AMP: Add AMP support to your WordPress site.
Version 0.4.2 | By Automattic*"

Yes I made changes to "Accelerated Mobile Pages" but only in settings never
in the code

I do not understand what you mean by "giving us the staging site login info"

Thank you!


Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by Sejiro-Hiko** [comment]
Hey @danielmrey,

I meant that if you have a staging or development site of your customer for testing out things before making changes to the original site.
so we can test or troubleshoot there as you can't share the login info, right!

Regards,
Mohammed Asif.

**Comment by danielmrey** [comment]
I do not have staging or development site, just the Admin area login and
the front end: http://www.medlar.in

And the Amp: http://www.medlar.in/amp/

Sorry about that

But I can test or try anything you tell me

Thanks again!


Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by MARQAS** [comment]
Hey @danielmrey,
Thank you for showing this to us.
I was able to trace this issue and resolved it as well. 
It will be added in our next update.

**Comment by danielmrey** [comment]
which was the problem?

Can I update my site with the solved issue?

Thanks!


Thank you.

Best Regards.


*Daniel Muñoz Rey*
Freelance Web designer and developer
www.danielmrey.com
info@danielmrey.com
linkedin.com/in/danielmrey <https://www.linkedin.com/in/danielmrey>
+44 (0)776 517 0430
Free estimate <http://www.danielmrey.com/create-website.php> for *new
websites*
Free consultation <http://www.danielmrey.com/check-website.php> for
*existing websites*

**Comment by MARQAS** [comment]
Hey @danielmrey , yes you can make changes like this: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/142366bc3d2454bfc2738121554e8b42ac4e5031

**Comment by MohammedKaludi** [comment]
Hey @danielmrey,

Did the above solution solve your issue?
