### ISSUE TITLE
Remove the scripts which are added by Siteapps

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#829]
Siteapps are trying to add some scripts in AMP pages/posts.

Ref: https://secure.helpscout.net/conversation/361940569/12693/?folderId=1060556 
       https://secure.helpscout.net/conversation/354135491/12356/?folderId=1060556

For Code: https://pastebin.com/18J4SYVu

**Comment by MohammedKaludi** [comment]
code is working, but it is not able to remove the js added by siteapps, as it is adding it a bit later or adding it in some other fashion. Have contacted siteapps, waiting for their reply.

**Comment by ahmedkaludi** [comment]
SiteApps are not getting back. We cannot have this ticket opened.

**Comment by maustyle** [comment]
going to SiteApps and turn the option off is not possible as the website has been down for a while. any other suggestion is appreciated.
