### ISSUE TITLE
Pagination inside a long posts

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#834]
A user wants to divide their posts into different pages.

Ref: https://secure.helpscout.net/conversation/363114035/12738/?folderId=1060551
> https://secure.helpscout.net/conversation/399150010/14299/?folderId=1060551

**Comment by MohammedKaludi** [comment]
Working nicely great work.

**Comment by syamsasi** [comment]
Pagination is not working in my website .  AMP page is [https://sapbrainsonline.com/crm-tutorial?amp](https://sapbrainsonline.com/crm-tutorial?amp) . You can refer the original url [https://sapbrainsonline.com/crm-tutorial](https://sapbrainsonline.com/crm-tutorial) showing post pagination. How can I fix this?

**Comment by MohammedKaludi** [comment]
> Pagination is not working in my website . AMP page is https://sapbrainsonline.com/crm-tutorial?amp . You can refer the original url https://sapbrainsonline.com/crm-tutorial showing post pagination. How can I fix this?

I have created a ticket for this https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4590

please do follow that ticket for the further development.

Thanks

**Comment by Zabi09** [comment]
Hi @syamsasi,

I have checked your website and found that you are not using our AMPforWP plugin and due to that pagination is not working on your website and will you please install our plugin and check once and we are sure that the pagination will work for sure.
