### ISSUE TITLE
Front page - static or not static, mixed problems

### ISSUE THREAD

**Issue by infokurs** [ahmedkaludi/accelerated-mobile-pages#836]
Since a long time still not resolved ( https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/813 is closed, bad still not fixed )

It seems that there is a problem understanding the rules https://developer.wordpress.org/reference/functions/is_home/#usage

Wen i set static front page, i demand static page, not blog (post list).
Well, check it. Page ID=5 (named homepage) set as static FP.

http://defiant-bat.w3.poopy.life/
**title**: Correct Homepage Title
**description**: Correct Homepage Description
...all meta tags ok.

And AMP? http://defiant-bat.w3.poopy.life/amp/
**title**: Sandbox | Just another WordPress site
**description**: Test Post Description (is from latest post http://defiant-bat.w3.poopy.life/test-post/ )
also others data (comment status*, mata tags via SEO, WordPress conditionals function return bad values etc.) is loaded from post, not from selected page.

Fault is defective WP_Query, described https://wordpress.org/support/topic/meta-titles-and-description-home-page/#post-9089953

For correct WP_Query all works as it should. Onlt this fix work https://wordpress.org/support/topic/meta-titles-and-description-home-page/#post-9097273 . And works with all SEO plugins.

**Comment by MohammedKaludi** [comment]
Hey @infokurs,

First of all, thank you for your feedback and I really appreciate your help and contributions in improving the plugin.

I have gone through the above ticket description and the forum and tested the code you provided here at https://github.com/infokurs/accelerated-mobile-pages/commit/16bb64e5a774b758fc5972fc35e60899aca36e43

There are few issues with the code, you are redirecting if the front page is set from the settings page not updating the meta info. It is causing a number of issues, first, it will have the incorrect rel-canonical url on the amp page, second blog pages will break after the updated permalink and will make things worse. 

So what would be the soultion then? If you set custom front page, from WordPress Settings you also have to set custom front page from the AMP panel http://take.ms/FMVAw this would solve all the above-mentioned issues and all the things will work smoothly.

Please do check once and let us know if any issue persists.
Thank you once again for your contribution and we all at AMPforWP team appreciate your valuable 

Mohammed Kaludi

**Comment by infokurs** [comment]
Hi @MohammedKaludi,
Ummm, yes, is not perfect.
You're right, canonical tag missing on homepage.
About blog page - maybe is something wrong, i don't use blog page, so i did not notice.
But normal, additional blog page also not work correctly (vide meta tags).
(mentioned settings in AMP panel not solve problem)

Well, any other solution for proper static homepage? Any method to get valid wp_query on AMP homepahe?

**Comment by MohammedKaludi** [comment]
You can set custom front page from the AMP panel http://take.ms/FMVAw and it should fix the problem.

**Comment by infokurs** [comment]
@MohammedKaludi, i know. It should fix, but don't fix anything.
Please read this topics once again: https://wordpress.org/support/topic/strange-seo-yoast-or-die/ and https://wordpress.org/support/topic/meta-titles-and-description-home-page/

Look once again to demo (pure wp, all in one seo and not modified amp) and compare meta from normal homepage and amp version.

Problem is here >> https://wordpress.org/support/topic/meta-titles-and-description-home-page/#post-9097273
The question, how to make an amp version has a complete $wp_query.

**Comment by infokurs** [comment]
demo: http://defiant-bat.w3.poopy.life/ vs http://defiant-bat.w3.poopy.life/amp
