### ISSUE TITLE
Front page - comments not found as expected

### ISSUE THREAD

**Issue by infokurs** [ahmedkaludi/accelerated-mobile-pages#837]
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/717 still not resolved.
In all designs frontpage.php files contains:
```
if ( !comments_open() ) {
 return;
}
```
This **return** stopped executing rest code (if comments closed, socials, footer etc. disappear) ...and he's still there.

This problem corresponds also to https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/836
If static page is set as front page, front page don't load comment status from selected page, but from latest post.

**Comment by MohammedKaludi** [comment]
Fixed.
