### ISSUE TITLE
Error: customizer.php on line 221

### ISSUE THREAD

**Issue by danielmrey** [ahmedkaludi/accelerated-mobile-pages#844]
Just updated the plugin in a client website and I got this error live! in the Admin area and in the Front end:

Parse error: syntax error, unexpected T_FUNCTION in /home/content/01/5282701/html/wp-content/plugins/accelerated-mobile-pages/templates/customizer/customizer.php on line 221

So I had to delete both plugins folders using FTP:
- accelerated-mobile-pages
- amp

Thank you.

**Comment by MARQAS** [comment]
Hey @danielmrey,

I am unable to recreate the issue,  it's working fine on my end. 
Can you tell me which version of the plugin you are using? If you can give us the Test area with the same issue, it would really help us to resolve this issue.

**Comment by danielmrey** [comment]
it resolved it by itself... ?

Thank you!
