### ISSUE TITLE
 Ability to switch off Google analytics completely 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#846]
Ability to switch off Google analytics completely 

https://wordpress.org/support/topic/cant-remove-google-analytics-2/

**Comment by pegazee** [comment]
My suggestion is when we click the 'x' button which will be seen in Google Analytics option( http://take.ms/NySoF ), It will show 'Select an item'. So, that Analytic code will be automatically removed from the page. 
ScreenShot> http://take.ms/G6UZ3

**Comment by MohammedKaludi** [comment]
Its working as expected after making the field empty.
