### ISSUE TITLE
Title and meta issues still persists 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#850]
Hey Mohammed,

Yeah, this issue has been going on for some time now.

Basically, if I set my site to use a ‘static home page’ then the meta info displayed is totally wrong on every blog post. Rather than display the actual meta info as normal on each post, the post uses the homepage meta title and description instead, on every single blog post.

It might be Genesis specific but it's not a plugin conflict because it happens on a new site.

I went over this issue for hours trying to figure it out, but somehow I stumbled onto working out that if I set a static home page, the issues begin. But if the homepage is set to ‘latest blog posts’ then all is well. I'm not an expert with this stuff by any stretch, this was just my observation.

I've setup a test site: http://atmospherepro.siterubix.com/example-post-title/amp

You can see that when you view the page source for the AMP version, the meta info is wrong. When you view it for the standard version, it's perfect.

You will also see that when you change the homepage to 'latest blog posts' the issue goes away. At least, this was the case when I tested it a while ago.

Username: admin
Password: c1Gnts1M

I know this is a public forum but this is just a test site so I figured I'd post the login info here. It's running Genesis, Atmosphere Pro theme.

Thanks for your time on this! Cheers

**Comment by MARQAS** [comment]
Hey @timmson87, 
I have applied the changes to the test site which you have provided, please do check once and let us know if that solves the issue or not

**Comment by timmson87** [comment]
Hey @MARQAS, I checked the test site and it's working perfectly. I also checked my main site and it's the same old issue for some weird reason. Could it just be a plugin conflict? I checked a few different settings and nothing seemed to help. Same theme. Same settings.

**Comment by MohammedKaludi** [comment]
@timmson87 yes, the fix is not available for the public until it is checked, so as the fix is now working we will be adding it to the main plugin and release it with next update, which we are planning to push in few days.

Thank you once again for your feedback and providing us the test area and explained the issue in detail.

Mohammed Kaludi

**Comment by timmson87** [comment]
@MohammedKaludi I thought so, kind of realised that was a noob question after I asked it lol. Thanks for getting this issue straightened out so quickly, much appreciated :)

**Comment by MohammedKaludi** [comment]
@timmson87 no problem, I'm glad that issue has been resolved, planning to push the code within 24 hours.

Cheers,
Mohammed Kaludi
