### ISSUE TITLE
If all ads are off then there is amp-ad .js missing error

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#855]
See: http://take.ms/tlIum

The tag 'amp-ad extension .js script' is missing or incorrect, but required by 'amp-ad'. This will soon be an error. Debug. Learn more.

Ad is added by Advanced AMP ads

**Comment by MARQAS** [comment]
This issue is due to Advanced AMP Ads plugin but not due to this plugin. 
Closing this issue and created a ticket about it in Advanced AMP Ads and resolved it as well
