### ISSUE TITLE
Debug errors follow up thread

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#859]
https://wordpress.org/support/topic/debug-0-9-49/

and 
https://secure.helpscout.net/conversation/367510543/12916/?folderId=1060551

**Comment by MohammedKaludi** [comment]
Will look into the PRs when will look into the ticket.
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/810 
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/811

**Comment by MARQAS** [comment]
Archive and Customizer warnings are left

**Comment by MARQAS** [comment]
Closing this ticket. 
Same as #966
