### ISSUE TITLE
Add support for Facebook's new AMP to Instant Articles conversions

### ISSUE THREAD

**Issue by nicholasgriffintn** [ahmedkaludi/accelerated-mobile-pages#862]
Hey,

I just seen that Facebook has finally given up and decided to support AMP instead of forced their own way of doing it, which is awesome because open is always better.

[https://media.fb.com/2017/05/25/instant-articles-sdk-extension-will-support-amp-soon-apple-news/](https://media.fb.com/2017/05/25/instant-articles-sdk-extension-will-support-amp-soon-apple-news/)

So I was thinking that it would be awesome if this plugin could add support for that, maybe through the plugin or via an extension.

Let me know what you think.

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn That's great news!  Wasn't expecting this but it's actually really good for the community!

I'll read the blog post and get back to you with my thoughts on what we can do!

**Comment by MohammedKaludi** [comment]
All the aspects seems working fine and closing this ticket.

**Comment by nicholasgriffintn** [comment]
Awesome! I'll check it out, thanks for doing that.
