### ISSUE TITLE
Autoptimize plugin adding script in AMP

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#864]
We need to modify the code so that Autoptimize plugin will compatible with our plugin.

Code: <script async type="text/javascript" src="http://www.brameshtechanalysis.com/wp-content/cache/minify/55d70.default.include.2d82bb.js"></script>

Ref: https://secure.helpscout.net/conversation/369840081/13030/?folderId=1060551

**Comment by MohammedKaludi** [comment]
@pegazee whats the status of this ticket?

**Comment by ahmedkaludi** [comment]
We haven't heard of this for a while now. Let's keep an eye on next milestone.
