### ISSUE TITLE
Page 2 goes to the wrong URL

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#865]
Two users are reported.

Ref: view-source:https://www.tech.com.pk/page/2
ScreenShot> http://take.ms/Pjr50

Ref: https://secure.helpscout.net/conversation/364434472/12795/?folderId=1060551
ScreenShot> http://take.ms/4Mzxd

**Comment by MohammedKaludi** [comment]
Tested and its working as expected
