### ISSUE TITLE
make sure scripts and styling is properly adding when sanitizing the sidebar 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#868]
Make sure scripts and styling is properly adding when sanitizing the sidebar or any other custom content.

Right now, the data is being cleaned but scripts and styling is not added in custom elements.
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/849

**Comment by ahmedkaludi** [comment]
@MohammedKaludi Can you give me more details on it?

**Comment by ahmedkaludi** [comment]
👍

**Comment by ahmedkaludi** [comment]
Failed in another review. Need to recheck the code.

**Comment by MohammedKaludi** [comment]
:+1:
