### ISSUE TITLE
Feature request from user from WP.org

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/Accelerated-Mobile-Pages#87]
Hello guys, you are awesome. I love this plugin. I have some new suggestions for your next big update.
Can you please enable comments section in the amp page.
Please try to enhance the beauty of the pages like this site has goo.gl/xA51R1

https://wordpress.org/support/topic/suggestions-for-bigger-one/

**Comment by ahmedkaludi** [comment]
Comment section was added
