### ISSUE TITLE
Show/Hide AMP for  Categories of Posts or All posts

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#872]
A user wants to make it either certain categories of posts do not have AMP or that they have a no index meta tag. 

Ref: https://secure.helpscout.net/conversation/371049723/13089/?folderId=1060551

Ref: https://secure.helpscout.net/conversation/369602229/13020/?folderId=1060551

**Comment by MARQAS** [comment]
Users want to hide AMP for all posts as well so that they can show AMP on only few pages.

**Comment by MohammedKaludi** [comment]
This code can be used, adding here as a referance 
`function ampforwp_posts_to_remove () {

    $args           = array();
    $cat            = '';
    $posts          = array();
    $post_id_array  = array();

    $args = array(
      'post_type' => 'post',
    );
    $cat =  1;   
    
    $posts = get_posts( array(
        'category'          => $cat,
        'numberposts'       => '-1',
        'post_type'         => $args,
        'post_status'       => 'publish',
        'suppress_filters'  => false
    ) );

    foreach ($posts as $post) {
        $post_id_array[] =  $post->ID;
    }

    return $post_id_array;
}

add_filter( 'amp_skip_post', 'ampforwp_cat_specific_skip_amp_post', 10, 3 );
function ampforwp_cat_specific_skip_amp_post( $skip, $post_id, $post ) {
    $list_of_posts  = '';
    $skip_this_post = '';

    $list_of_posts = ampforwp_posts_to_remove();

    $skip_this_post = in_array($post_id, $list_of_posts);

    if( $skip_this_post ) {
      $skip = true;
    }
    return $skip;
}`

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/497bee94920182e0d58dac509291f709cb6f7d49

**Comment by MohammedKaludi** [comment]
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/497bee94920182e0d58dac509291f709cb6f7d49

**Comment by MohammedKaludi** [comment]
This feature is working. 
One thing that I see is, non-amp category pages should redirect to non-amp pages.

**Comment by MohammedKaludi** [comment]
Working.
