### ISSUE TITLE
Change meta name ="Viewport" and its value

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#878]
ningnoom (@ ningnoom)

<meta name=”viewport” content=”width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no”>

I need “user-scalable=yes” but i don’t know to edit file location.

please tell me.

Ref link: https://wordpress.org/support/topic/how-to-chang-meta-nameviewport/

**Comment by MohammedKaludi** [comment]
Use this  code to modify the Viewport meta 

add_filter('ampforwp_modify_meta_viewport_filter', 'custom_prefix_modify_view_port_value');
function  custom_prefix_modify_view_port_value() {
	return '<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=2,user-scalable=yes">';
};

Thank you,
Mohammed Kaludi

**Comment by MohammedKaludi** [comment]
Tested and its Working.

**Comment by ElQadi** [comment]
we modified viewport using your code
add_filter('ampforwp_modify_meta_viewport_filter', 'custom_prefix_modify_view_port_value');
function custom_prefix_modify_view_port_value() {
return '<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=2,user-scalable=yes">';
};

but still not scalable

[https://el3rod.com/amp](https://el3rod.com/amp)

**Comment by MohammedKaludi** [comment]
Hey @ElQadi 
I the code is working on your site, the viewport value has been updated and I also see the reflection of that code in the mobile view, here is the screenshot http://take.ms/IGpN2

TIP: Please set initial-scale and minimum-scale to 1 your set to 2, it will make the screen size 200% on the load.

**Comment by ElQadi** [comment]
Thanks Mohammed for your time, but we have been trying to "zoom in" with many mobile devices but can't.

**Comment by MohammedKaludi** [comment]
Hey @ElQadi,

Can you please tell me on which phone you tested? Because I'm able to Zoom in on my iPhone 5s with Safari.

Mohammed Kaludi

**Comment by ElQadi** [comment]
Hi Mohammed,
We use android mobiles like SAMSUNG Note3 using firefox and chrome

**Comment by ElQadi** [comment]
Hi Mohammed,
Do you support Android devices zoom?
