### ISSUE TITLE
Histats analytics Support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#880]
This is no Java script code:

<! - START Histats.com (hidden counter) -> 
<a  href="/" alt="free hit counter" a target="_ blank" > 
<img src = "//sstatic1.histats.com/0.Gif?2260369&101 "alt="free hit counter" border="0">
<! - Histats.com END ->

In order for the histats code to work, last line should be

<Amp-pixel src="//sstatic1.histats.com/0.gif?2260369&101"></amp-pixel>    

And ID 2260369 should be customized. 

That's all.

**Comment by MohammedKaludi** [comment]
Tested.
