### ISSUE TITLE
The tag 'if' is disallowed

### ISSUE THREAD

**Issue by luizalmeida2015** [ahmedkaludi/accelerated-mobile-pages#886]
1 Error  The tag 'if' is disallowed

<if cond="data:blog.pageType == &quot;item&quot;"><p class="amp-wp-inline-9b385107b1989eed397061d8ada44812">&#13;

https://validator.ampproject.org/#url=http%3A%2F%2Fwww.arquivoti.net%2Fcomo-conversar-com-alguem-no-whatsapp-mesmo-bloqueado%2Famp%2F

**Comment by MohammedKaludi** [comment]
@luizalmeida2015 I have just checked the above link and it is said AMP page is validated. Can you please check it once again and confirm?

**Comment by luizalmeida2015** [comment]
I already solved the problem. I was using a script to align the ads on my theme and this was causing the problem.

**Comment by luizalmeida2015** [comment]
Thanks

**Comment by MohammedKaludi** [comment]
I'm glad that the issue has been resolved.
