### ISSUE TITLE
Adobe Analytics Support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#887]
https://marketing.adobe.com/resources/help/en_US/sc/implement/accelerated-mobile-pages.html

**Comment by pegazee** [comment]
Adobe Analytics required the host to maintain the analytics. And for reference do not have any documentation for the host.

**Comment by ahmedkaludi** [comment]
I'm closing this ticket because of the poor implementation method with poor documentation from Adobe analytics's side.

**Comment by githubjabbar** [comment]
Addon the Adobe Analytics to AMP.

Reference: https://marketing.adobe.com/resources/help/en_US/sc/implement/accelerated-mobile-pages.html

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by Zabi09** [comment]
looking forward to it

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.14
