### ISSUE TITLE
Latest Posts (Content Builder) Module

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#888]
Latest Posts (Content Builder) Module

- [x]  Create a feild type called Category Select Option with default value as recent posts (Ajeet)
- [x]  Make the Category Block Module (Azeem)

- [x] Css loading section (Ajeet)

- [x]  Front End of it. (Ahmed)

**Comment by ajeetku** [comment]
Created new module Category Content f74ff75
Recent posts or Selected category post will show 
according to selection of,  no of posts to show

**Comment by ahmedkaludi** [comment]
The Category Selection is not saving..
