### ISSUE TITLE
Favicon only on the homepage

### ISSUE THREAD

**Issue by aashishpahwa** [ahmedkaludi/Accelerated-Mobile-Pages#89]
Favicon doesn't appear on any page other than the home page

**Comment by ahmedkaludi** [comment]
We will be working and fixing this in the next update.

**Comment by MohammedKaludi** [comment]
Reported on : https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/issues/43 

will be fixed in V0.8.6
