### ISSUE TITLE
Refine frontpage-elements.php 

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#890]
Refine frontpage-elements.php and make sure sticky social icons are added properly and no spacing is shown when builder is in user.

**Comment by ahmedkaludi** [comment]
@MohammedKaludi What exactly do we need to refine?

**Comment by Sejiro-Hiko** [comment]
discussed along with @ahmedkaludi, after looking into this ticket and the referred commit to It the changes were made a day before opening this issue...

Now comes a question does a Frontpage requires sticky social? think not! so we'll leave the way as it is.
