### ISSUE TITLE
View nonamp in header

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#892]
Users are asking for view nonamp in header as well like footer

ref: https://wordpress.org/support/topic/making-header-code-does-in-the-footer-non-amp-version-link/

**Comment by MohammedKaludi** [comment]
Made the appropriate changes and also made a tutorial on how to add View non AMP link in header 
https://ampforwp.com/tutorials/add-view-non-amp-things-header/
