### ISSUE TITLE
Errors notified by Google

### ISSUE THREAD

**Issue by sharonknowles** [ahmedkaludi/Accelerated-Mobile-Pages#90]
- Prohibited or invalid use of HTML Tag

- Syntax  error

- Invalid usage of AMP tags

These errors are being picked up only on the AMP pages, plugin is updated.

Version 0.8.1 (Wordpress Site)

**Comment by ahmedkaludi** [comment]
They @sharonknowles 
Can you click on them and post the exact errors ?

Or if you could share the website url, then that would help us too.

**Comment by sharonknowles** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  The website URL is Home | Da Vinci Forensics
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Home | Da Vinci Forensics
 
Da Vinci Forensics is a Cyber Security Organisation that offers solutions to ensure rapid detection and response. Monitor and assist with IT Risk Strategy
  |   |

  |

  |

 




Sent from Yahoo Mail for iPhone


On Wednesday, September 21, 2016, 21:56, Ahmed Kaludi <notifications@github.com> wrote:


They @sharonknowles 
Can you click on them and post the exact errors ?

Or if you could share the website url, then that would help us too.

**Comment by ahmedkaludi** [comment]
Hey @sharonknowles 
I have just checked your site: https://davinciforensics.co.za/ 

There is a problem with autoptimize plugin. It defer's it incorrectly which messes up the scripts. Please disable the defer and that should solve this issue.

**Comment by ahmedkaludi** [comment]
Just a Note to self: 

See if we can solve this by adding a defer by default and check it with Autoptimize plugin. If yes, then fix this 0.8.2

**Comment by sharonknowles** [comment]
Done
These are the errors i get after running the google AMP validator and after disabling Autoptimize:
  The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.MANDATORY_AMP_TAG_MISSING_OR_INCORRECTline 493, column 7

The tag 'script' is disallowed except in specific forms.CUSTOM_JAVASCRIPT_DISALLOWEDline 15, column 2
  The attribute 'prefix' may not appear in tag 'html ⚡ for top-level html'.DISALLOWED_HTMLline 2, column 0
The attribute 'charset' may not appear in tag 'meta name= and content='.DISALLOWED_HTMLline 4, column 0  The property 'minimum-scale' is missing from attribute 'content' in tag 'meta name=viewport'.MANDATORY_AMP_TAG_MISSING_OR_INCORRECTline 5, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 38, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 39, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 40, column 0  The tag 'script' is disallowed except in specific forms.CUSTOM_JAVASCRIPT_DISALLOWEDline 42, column 2  The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.DISALLOWED_HTMLline 46, column 2  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 60, column 0  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 416, column 9  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 416, column 52  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 416, column 127  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 614, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 663, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 670, column 16279  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 670, column 18624  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 5102, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 5195, column 9  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 5388, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 5388, column 51  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 5388, column 94  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 8597, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 8601, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 8606, column 9  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 8609, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 8895, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 8895, column 51  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 9642, column 8  The attribute 'media' may not appear in tag 'style amp-custom'.DISALLOWED_HTMLline 9642, column 27226  The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value '/cybersecurity/?mcsf_action=main_css&ver=1.5.2'.AUTHOR_STYLESHEET_PROBLEMline 9662, column 138  The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value '//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,600'.AUTHOR_STYLESHEET_PROBLEMline 9662, column 245  The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value '//fonts.googleapis.com/css?family=Raleway:400,500,600'.AUTHOR_STYLESHEET_PROBLEMline 9662, column 373  The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value 'https://davinciforensics.co.za/cybersecurity/?sccss=1'.AUTHOR_STYLESHEET_PROBLEMline 9662, column 487  The tag 'script' is disallowed except in specific forms.CUSTOM_JAVASCRIPT_DISALLOWEDline 9663, column 0  The tag 'script' is disallowed except in specific forms.CUSTOM_JAVASCRIPT_DISALLOWEDline 9681, column 0  The tag 'head > style[amp-boilerplate] - old variant' is deprecated - use 'head > style[amp-boilerplate]' instead.DEPRECATIONline 9714, column 0  The mandatory text (CDATA) inside tag 'head > style[amp-boilerplate] - old variant' is missing or incorrect.MANDATORY_AMP_TAG_MISSING_OR_INCORRECTline 9714, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9723, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9724, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9725, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9726, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9727, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9728, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9729, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9730, column 0  The attribute 'rel' in tag 'link rel=' is set to the invalid value 'dns-prefetch'.DISALLOWED_HTMLline 9731, column 0  The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.DISALLOWED_HTMLline 9732, column 0  The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.DISALLOWED_HTMLline 9732, column 57  The parent tag of tag 'noscript > style[amp-boilerplate] - old variant' is 'head', but it can only be 'noscript'.DISALLOWED_HTMLline 9752, column 0  The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?DISALLOWED_HTML_WITH_AMP_EQUIVALENTline 9770, column 98  The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?DISALLOWED_HTML_WITH_AMP_EQUIVALENTline 9800, column 4  Invalid URL protocol 'http:' for attribute 'action' in tag 'form'.DISALLOWED_HTMLline 9846, column 74  The tag 'script' is disallowed except in specific forms.CUSTOM_JAVASCRIPT_DISALLOWEDline 9855, column 0  The attribute 'onclick' may not appear in tag 'a'.DISALLOWED_HTMLline 9875, column 3  The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?DISALLOWED_HTML_WITH_AMP_EQUIVALENTline 9875, column 161  The attribute 'onclick' may not appear in tag 'a'.DISALLOWED_HTMLline 9875, column 352  The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?DISALLOWED_HTML_WITH_AMP_EQUIVALENTline 9875, column 480  The attribute 'onclick' may not appear in tag 'a'.DISALLOWED_HTMLline 9877, column 3  The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?DISALLOWED_HTML_WITH_AMP_EQUIVALENTline 9877, column 129  The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?DISALLOWED_HTML_WITH_AMP_EQUIVALENTline 9877, column 363  Invalid URL protocol 'http:' for attribute 'action' in tag 'form'.DISALLOWED_HTMLline 9882, column 78  The tag 'script' is disallowed except in specific forms.CUSTOM_JAVASCRIPT_DISALLOWEDline 9891, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9901, column 126  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9902, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9903, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9904, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9905, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9906, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9907, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9908, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9909, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9910, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9911, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9912, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9913, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9914, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9915, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9916, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9917, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9918, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9919, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9920, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9921, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9922, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9923, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9924, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9925, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9926, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9927, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9928, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9929, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9930, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9931, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9932, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9933, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9934, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 9935, column 0  The attribute 'style' may not appear in tag 'a'.DISALLOWED_HTMLline 993 

    On Thursday, September 22, 2016 12:46 AM, Ahmed Kaludi <notifications@github.com> wrote:
 

 Just a Note to self: See if we can solve this by adding a defer by default and check it with Autoptimize plugin. If yes, then fix this 0.8.2—

**Comment by ahmedkaludi** [comment]
@sharonknowles I would appreciate if you could share your URL, it would help me troubleshoot.

**Comment by sharonknowles** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } https://davinciforensics.co.za/cybersecurity


Sent from Yahoo Mail for iPhone


On Tuesday, September 27, 2016, 09:39, Ahmed Kaludi <notifications@github.com> wrote:


@sharonknowles I would appreciate if you could share your URL, it would help me troubleshoot.

**Comment by ahmedkaludi** [comment]
It seems like you are using Speed Booster plugin. There is a compatibility issue with Speed Booster since it tries to make changes in the AMP which it shouldn't. 

The solution for this is to disable the defer from the options. Here is the screenshot of it:
![speed-booster-options](https://cloud.githubusercontent.com/assets/16532359/18917097/51289ce0-85b4-11e6-945b-58ad47a52f1f.jpg)
