### ISSUE TITLE
Fatal error when WPSEO is activated

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#900]
Q: Plugin does not work with WPseo Plugin:
https://wpseo.de
getting a 500 Error and all pages are blank, once the WPseo Plugin is active.
any idea?

ref: https://wordpress.org/support/topic/500-error-with-wpseo-plugin/
NOTE: This is not YoastSEO aka WPSEO, this is some other WPSEO plugin (https://wpseo.de).

**Comment by MohammedKaludi** [comment]
Fixed.
