### ISSUE TITLE
Space Above Featured Image

### ISSUE THREAD

**Issue by saumyabratadutt** [ahmedkaludi/accelerated-mobile-pages#901]
Website link - worldnews.gq
Hello,
I've installed the AMP plugin. It's working fine. But, I don't understand why it is adding extra space above my featured image. Else everything is working fine. I've checked all the designs but the problem persists. 
![screenshot_2017-06-10-20-56-50](https://user-images.githubusercontent.com/24366687/27004065-88ae80f0-4e20-11e7-8b98-2d825ccc7a3f.png)

![screenshot_2017-06-10-20-56-56](https://user-images.githubusercontent.com/24366687/27004042-fa5e931c-4e1f-11e7-86a6-2c8b401e9374.png)
Also, here's the ads I added.
![fireshot capture 41 - accelerated mobile pages options _ - https___worldnews gq_wp-admin_admin php](https://user-images.githubusercontent.com/24366687/27004048-25e2696e-4e20-11e7-832c-6501e67a2527.png)
I'll appreciate a solution for this.
Thanks!

**Comment by Sejiro-Hiko** [comment]
@saumyabratadutt I was trying to resolve this issue but I'm unable to recreate the issue on my end, and your site doesn't seem to have the AMP can you please enable the AMP so that i can resolve the issue or can you provide us the staging site to us.

**Comment by MohammedKaludi** [comment]
This was the one off issue and we are unable to re-create the issue, so closing the ticket due to lack of proof about the issue.
