### ISSUE TITLE
Remove 'Welcome to AMP' from Dashboard sub-menu

### ISSUE THREAD

**Issue by HammyHavoc** [ahmedkaludi/accelerated-mobile-pages#902]
This doesn't need to be there permanently and is just more needless clutter in the WordPress menu system.

**Comment by ahmedkaludi** [comment]
I agree @HammyHavoc 

What do you think @MohammedKaludi ?

**Comment by Sejiro-Hiko** [comment]
@ajeetku user should visit the welcome page only once when installation is done and after that, the clicking of AMP logo should lead to options panel instead of a welcome page.
