### ISSUE TITLE
Pages not supporting /amp

### ISSUE THREAD

**Issue by koffisani** [ahmedkaludi/accelerated-mobile-pages#903]
It seems like wp pages are not supporting /amp. I'm running into 404 error page. I'm using version 0.9.51
Thanks.

**Comment by ahmedkaludi** [comment]
Can you post the website URL please?

**Comment by koffisani** [comment]
https://www.koffisani.ga. 
Can it also be possible to redirect all pages request to amp version ?

**Comment by MohammedKaludi** [comment]
@koffisani I can see the amp on pages like this one https://www.koffisani.ga/about/amp/

**Comment by koffisani** [comment]
Oh, right. I was confused when accessing via the menu link. It seems that the amp menu doesn't prioritize amp version of entries.
