### ISSUE TITLE
Navigating to other AMP Pages not working unless double clicking

### ISSUE THREAD

**Issue by tanujdamani** [ahmedkaludi/accelerated-mobile-pages#906]
When testing if the AMP pages work, each individual page loads fine, however when clicking on a link to another AMP page the pages will not load unless you double-click a link.
If a link is clicked once, the page will just remain in a state of "waiting".

Furthermore, if I do this a few times, eventually the my server gets overloaded and the Apache server stops responding. I then have to go and manually end all processes.

More details can be provided.

Website Specs:
- Wordpress: 4.8
- AMP by Automattic: 0.4.2
- AMP for WP: 0.9.51.1

Server Specs:
- Apache Version: 2.2.31
- PHP Version: 5.4.45
- MySQL Version: 5.5.51-38.2

**Comment by MohammedKaludi** [comment]
@tanujdamani This is a very strange issue, can you share the url of the site where you are facing the issue?
This will help understand and debug the issue.

Thanks,
MK

**Comment by tanujdamani** [comment]
@MohammedKaludi I had this issue when I first tested the website with the AMP plug-ins.
Recently I re-activated the plug-in and the issue persisted for a couple of days.

However the problem is no longer there. If however This issue re-surfaces I will be sure to let you know.

Thanks
