### ISSUE TITLE
MashShare compatiblity in Category section

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#908]
MshShare buttons on Category section, causing a validation error. But in posts, it is validated.

Ref for Category: http://www.afterschoolafrica.com/article/amp/
Ref for post: http://www.afterschoolafrica.com/21851/follow-8-time-management-tips-study-smarter/amp/

Ref: https://secure.helpscout.net/conversation/377695935/13354/?folderId=1060551

**Comment by MohammedKaludi** [comment]
The issue coming due to user is adding sharing button manually and in the single, it's working correctly. Waiting for the user's reply on this ticket.

**Comment by Iykepress** [comment]
Thanks Mohammed for fixing the redirection error on afterschoolafrica.com and for taking this further. You have been very helpful. I hope this is taken care of.

**Comment by MohammedKaludi** [comment]
Thank you very much, I'm glad that plugin is working out well for you.
