### ISSUE TITLE
Exclude Some Pages from Mobile Redirection

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#914]
A user should be able to remove/exclude some pages from mobile redirection.

Feedback Ref: https://secure.helpscout.net/conversation/382049263/13520/?folderId=1060551

**Comment by WebSwiftSEO** [comment]
Nice, will make a good addition ;-)

**Comment by NilsHoyer** [comment]
I have a problem with a JetPack contact formula inside a amp page. So it would be nice for me, if the user would see the normal page instead of the AMP page.

... but I don't have an idea, how you could realize this...

**Comment by MohammedKaludi** [comment]
Tested on native post types and custom post types and its working.
