### ISSUE TITLE
Problem with a category overview

### ISSUE THREAD

**Issue by NilsHoyer** [ahmedkaludi/accelerated-mobile-pages#918]
I have (normal view) category:
http://nils-weg.de/aus-meinem-leben/

... but there is no handling as a AMP category overview:
http://nils-weg.de/aus-meinem-leben/amp/

**Comment by ahmedkaludi** [comment]
To @NilsHoyer  Undefined index issues in my opinion. Did I get this right?

TO THE AMP TEAM: some of them are coming from extensions so make respective tickets for it.

See the screenshot:
![aus meinem leben archive nils weg](https://user-images.githubusercontent.com/16532359/29740194-a18080ee-8a6e-11e7-9a1f-29a2e4847d26.png)

**Comment by NilsHoyer** [comment]
If I disable the debug mode of wordpress, everything is well. So I believe, you could solve this problem, if you try.
