### ISSUE TITLE
Problem with Auto Add AMP in Menu URL

### ISSUE THREAD

**Issue by NilsHoyer** [ahmedkaludi/accelerated-mobile-pages#919]
I have a menu with a individual link for the feed. If I enable "Auto Add AMP in Menu URL", the link to the feed get's an "amp/" too. But there is no amp feed.

My amp homepage with that menu: http://nils-weg.de/amp/

I'm sorry, but I don't have a suggestion, how you could handle this issue.

**Comment by ahmedkaludi** [comment]
@NilsHoyer In this case, you should not enable 'Auto Append AMP' at the end of the menu and just setup the menu manually. You can choose to add /amp and non-amp links in that.
