### ISSUE TITLE
Amp brings up blog post page instead of main home page

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#92]
The AMP has been installed, however when I check the amp pages by going: https://mydomain.com.au and add /?amp onto the end, instead of my home page amp brings up the blog post page (there are only a few blog posts) not my home page. This will affect my google indexing.

How can I set the amp home url or home page as my main home page?

------
Happening to me too. http://wwwFrench-Chiropractic.com/?amp

**REPORTED ON: https://wordpress.org/support/topic/amp-brings-up-blog-post-page-instead-of-main-home-page/**

**Comment by ahmedkaludi** [comment]
Everything is done, just need to connect pages select option from the options 
at "<?php $the_query = new WP_Query( 'page_id=120' ); ?>" in frontpage.php

**Comment by CryssDOTnet** [comment]
Which frontpage.php?

**Comment by ahmedkaludi** [comment]
This was fixed in 41f70836c70f3ddb68c7a6693b0992ad8cb3e80d
