### ISSUE TITLE
Variable index after update

### ISSUE THREAD

**Issue by mobilapk** [ahmedkaludi/accelerated-mobile-pages#921]
Hello there
First of all, I would like to say that I love the extension very much. Thank you so much for making such a nice addition :). But I have a problem. I made a small change in index.php. This change is constantly disappearing when you update. How can I solve this. I made a mistake when installing

My website: https://mobilapk.com/

**Comment by ahmedkaludi** [comment]
You should use this to modify the plugin: https://ampforwp.com/tutorials/article/create-a-custom-amp-theme-for-wordpress/
