### ISSUE TITLE
Website is down :/

### ISSUE THREAD

**Issue by thetwosents** [ahmedkaludi/accelerated-mobile-pages#926]
Was excited to check out the product but can't get to the marketing website :(

**Comment by ahmedkaludi** [comment]
Hey! What are you facing the issue. Are you seeing any specific issue? Can
you send a screenshot? I would really appreciate the help.

**Comment by ahmedkaludi** [comment]
@

**Comment by ahmedkaludi** [comment]
@thetwosents I would appreciate your help In this. 

We take user experience seriously and I cant wait to get to the root cause of this and solve it for you.

**Comment by thetwosents** [comment]
It redirected me and now it works. Takes around 4-6 seconds total to view the site though. Yesterday it did not work, gave 404

**Comment by ahmedkaludi** [comment]
@thetwosents How about now, is it opening fine?

**Comment by ahmedkaludi** [comment]
@thetwosents We have controlled everything so it should be fine now.
