### ISSUE TITLE
Unnecessary: Adding the Markup for AMP Woocommerce latest Products

### ISSUE THREAD

**Issue by IvanPr** [ahmedkaludi/accelerated-mobile-pages#929]
The …/templates/features.php has the following excessive add_action for the websites without the WooCommerce at:

53. Adding the Markup for AMP Woocommerce latest Products

   // Adding the styling for AMP Woocommerce latest Products
   add_action('amp_post_template_css','amp_latest_products_styling',PHP_INT_MAX);
   function amp_latest_products_styling() { ?>
.ampforwp_wc_shortcode{margin-top: 0;padding:0;display:inline-block;width: 100%;}
.ampforwp_wc_shortcode li{position: relative;width:29%; font-size:12px; line-height: 1; float: left;list-style-type: none;margin:2%;}
.ampforwp_wc_shortcode .onsale{position: absolute;top: 0;right: 0;background: #ddd;padding: 7px;font-size: 12px;}
.single-post .ampforwp_wc_shortcode li amp-img{margin:0}
.ampforwp-wc-title{margin: 8px 0px 10px 0px;font-size: 13px;}
.ampforwp-wc-price{color:#444}
.wc_widgettitle{text-align:center;margin-bottom: 0px;}
.ampforwp-wc-price, .ampforwp_wc_star_rating{float:left;margin-right: 10px;}
<?php }
Can those type of things be conditionally disabled?

And why setting this add_action with the PHP_INT_MAX?

**Comment by MohammedKaludi** [comment]
Above code is added on AMP-WooCommerce Plugin https://github.com/ahmedkaludi/amp-woocommerce/commit/d910e0182ecfe7660d9dfd026722219d8dfb7b1d and https://github.com/ahmedkaludi/amp-woocommerce/commit/ca8110ac6346ea0005fa4ae04ba4249a867b160f

Styling is kept here because some of the users use WC Widget to add in the normal site as well. So, need the styling on the main plugin.

Mohammed Kaludi

**Comment by IvanPr** [comment]
Why would the other million of users need this code when they do not use WC Widgets?
Please consider making this output conditional...

**Comment by MohammedKaludi** [comment]
@IvanPr Yes, agreed with your suggestion. Added the condition, will only load if WC is activated.
