### ISSUE TITLE
AMP Plugin "AMPhtml" link conflict possibly leading to Google discovery issue.

### ISSUE THREAD

**Issue by kIwOk168** [ahmedkaludi/Accelerated-Mobile-Pages#93]
Greetings Ahmed and Mohammed,

Please bear with me as I'll try to be as specific as possible with the issue I encountered.

I've decided to install your Accelerated-Mobile-Pages Wordpress plugin to amp-enable my site.  I chose your plugin because it supports "pages" and my website is created mostly on pages, not posts.

When I activated the plugin, I got a "This theme requires the following plugin: AMP. Begin installing plugin" notification.  You can see it from the image below:
![issue01](https://cloud.githubusercontent.com/assets/22364679/18740081/59612d16-80da-11e6-8e95-d8d909e86174.jpg)

I've tried and your plugin really doesn't work in my setup if the AMP plugin (by Automattic) isn't installed.  Once installed, my pages do work by appending /?amp in the url.  You can see an example below:
![issue02](https://cloud.githubusercontent.com/assets/22364679/18740334/cf7abe8a-80db-11e6-914b-e70a29e9aa23.jpg)

However, I looked at the <link rel="amphtml"> value on the non-amp page and it's pointing to the /amp/ URL append (probably because this is the URL append of the AMP plugin) instead of your plugin's /?amp URL append.  You can see this highlighted in the image below:
![issue03](https://cloud.githubusercontent.com/assets/22364679/18740590/10c4c7f4-80dd-11e6-86d3-60c030de71e3.jpg)

I've tested and the /amp/ versions don't exist (because the AMP plugin doesn't support pages yet), only the /?amp versions do.

Now I'm foreseeing a problem that Google will have an issue with discovery since the <link rel="amphtml"> value is pointing to non-existent pages (/amp/ versions).

I would love to hear your thoughts.

In any case, maybe a quick solution would be to allow customization of the amp append.  Like add a setting wherein we can change the amp append from the default /?amp into something else.

Thank you very much.

**Comment by nicholasgriffintn** [comment]
Yeah the plugin requires AMP, it was part of a new release because the AMP plugin has already solved many of the validation issues to do with AMP, and fixed a lot of hard to fix problems to do with iframes, galleries, etc, so it made sense for the developer to switch to that.

As for the page AMPhtml links, that's a good shout. It does seem to be the case that pages have the "/amp/" tag for AMPhtml, although they only work with the "/?amp" URL.

@ahmedkaludi

**Comment by nicholasgriffintn** [comment]
I think that my latest pull request might fix this issue, you can find it here: #94

**Comment by kIwOk168** [comment]
Oh, so that AMP+Accelerated Mobile Pages combo was intentional, I thought it was just a theme issue.  Thanks for clarifying this, Nicholas.

I do hope that @ahmedkaludi and @MohammedKaludi can resolve this AMPhtml conflict in the next release.  It seems like Google is not detecting the amp-enabled pages generated by the Accelerated Mobile Pages plugin.  It's only been a day so I'll wait a few more days to see if Google discovered the amp-enabled pages.

**Comment by nicholasgriffintn** [comment]
@kIwOk168 It does take a while for Google to notice your AMP pages, personally it took them about a week to detect all of ours.

**Comment by kIwOk168** [comment]
So just to update, Google was able to discover the AMP pages but has a lot of errors, probably because it's reading the /amp/ pages and not the /?amp versions.

These are all the errors being shown:
![issues01](https://cloud.githubusercontent.com/assets/22364679/18834577/4e738794-8429-11e6-9eaf-c59f7dc6980b.jpg)

While these are the "pages" that Google is detecting, notice that they all have the /amp/ extension instead of the /?amp extensions:
![issues02](https://cloud.githubusercontent.com/assets/22364679/18834616/7d04a926-8429-11e6-9680-afaade0cd8bc.jpg)

**Comment by nicholasgriffintn** [comment]
Hey,

What your issue seems to be is that "/amp/" is redirecting to the base URL, instead of loading the amp page. The link should load with "/amp/", however, your site is redirecting that for some reason.

**Comment by ahmedkaludi** [comment]
Yes @nicholasgriffintn  Nicholas is right!  @kIwOk168 Can flush the rewrite rules?

**Comment by kIwOk168** [comment]
Hmmm... I don't really know what's doing the redirect.  The AMP versions work with /?amp though like https://www.relationshipspotlight.com/unlock-her-legs-review/?amp

I really feel that it's because "AMPhtml" is pointing at "https://www.relationshipspotlight.com/unlock-her-legs-review/amp/" which is non-existent; only the /?amp version is existent.

Sorry @ahmedkaludi , I don't know how to flush rewrite rules... I'm not a programmer, I'm just a guy who loves and wants to make your plugin work.  How do I exactly do that?  Thanks.

**Comment by nicholasgriffintn** [comment]
@kIwOk168 Just go to your WP-admin page, hover over settings, click "Permalinks" and hit the save button, then go into the AMP settings and hit the save button, that should do it.

**Comment by nicholasgriffintn** [comment]
It's real simple @kIwOk168, just follow the instructions here:

https://typerocket.com/flushing-permalinks-in-wordpress/

No programming needed :).

**Comment by kIwOk168** [comment]
ooohh, so that's what it's called.

And wow, it worked :)  /amp/ versions are working now... I hope Google now gets to see these pages correctly... Thanks @nicholasgriffintn and @ahmedkaludi ... great plugin!

**Comment by ahmedkaludi** [comment]
Thanks @kIwOk168 Please share your review on the plugin page, https://wordpress.org/support/plugin/accelerated-mobile-pages/reviews/

We will appreciate it.
