### ISSUE TITLE
Disqus Comments show up even when disabled per post

### ISSUE THREAD

**Issue by IvanPr** [ahmedkaludi/accelerated-mobile-pages#931]
The Disqus comments show on the page even when disabled - http://i.imgur.com/gWUAozO.png

The non-AMP pages of the Theme display comments conditionally...

**Comment by MohammedKaludi** [comment]
amp-iframe scripts is loading, even if the comments are off. @MARQAS Need to fix

**Comment by MARQAS** [comment]
Done
