### ISSUE TITLE
amp-user-notification is already registered. The script tag for amp-user-notification is likely included twice in the page.

### ISSUE THREAD

**Issue by Meh0** [ahmedkaludi/accelerated-mobile-pages#932]
Had a similar problem to this one : #828 

Solved it the same way.
In \wp-content\plugins\accelerated-mobile-pages\templates\design-manager\design-2\frontpage.php:27
```php
foreach ($amp_component_scripts as $ampforwp_service => $ampforwp_js_file) {
    if ( 'amp-user-notification' == $ampforwp_service || 'amp-sidebar' == $ampforwp_service || 'amp-analytics' == $ampforwp_service ) {
		continue;
	} ?>
	<script custom-element="<?php echo $ampforwp_service; ?>"  src="<?php echo $ampforwp_js_file; ?>" async></script> <?php
}
```

**Comment by MARQAS** [comment]
Hey @Meh0, can you give us the URL where you are having this issue?

**Comment by MARQAS** [comment]
There are no issues at my end.

**Comment by Meh0** [comment]
Ok, might be specific to my setup then. Don't have time to investigate further for the moment.

**Comment by MARQAS** [comment]
@Meh0 Sure, Let us know if you found any issues, we will resolve them.
