### ISSUE TITLE
How to disable for AMP by default for post ?

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#935]
A user wants to disable AMP on the posts. He wants to enable it only on pages. 

https://wordpress.org/support/topic/how-to-disable-for-amp-by-default-for-post-and-custom-post-type/

**Comment by MohammedKaludi** [comment]
I think this is one off request and that can be done by custom coding, but I don't think this feature is useful.
If we make this then users will tell that it's getting very annoying, need to AMP support for every post.
@ahmedkaludi, @nicholasgriffintn  and @MARQAS Need your opinion.

**Comment by nicholasgriffintn** [comment]
I just wonder why you would want an AMP plugin if not for the posts? That's the point of AMP, to provide a faster article reading experience and for Google to recognise that faster experience.

I don't see many users using this and I also don't think that should be encouraged to do so either as their might be some SEO implications on doing that. I think having the option to disable on a post-by-post basis is good, however, in my opinion, you shouldn't be disabling it for all posts as that's where AMP's strength lies.

My advice for this person would be to simply not use AMP if he doesn't want AMP posts and instead make his website faster in general, it would result in a much better experience for his users.

**Comment by MohammedKaludi** [comment]
When Post support is turned off  then Meta box should also be removed 
![image](https://user-images.githubusercontent.com/16618009/31309423-81b27640-aba3-11e7-8d20-db8c7a93c3b8.png)

**Comment by ahmedkaludi** [comment]
The original thing was done, the @MohammedKaludi saying is valid but let's continue it on #1253
