### ISSUE TITLE
W3 total cache plugin inserting Script in AMP pages.

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#936]
W3 total cache plugin is trying to insert the minify Script in AMP pages/posts.

Ref: https://secure.helpscout.net/conversation/385373455/13671/?folderId=1060551

ScreenShot> https://monosnap.com/file/oUULevxi90zQ20G0NDPO2M0z9IcF20 , If we untick this option the problem will resolve but the users want to keep that option enabled.

**Comment by MohammedKaludi** [comment]
There was an option inside W3Cache panel called extension->AMP extension, http://take.ms/UfgAb

Just activated and done. Everything is working fine. Even tested on a client's site.

Regards,
MK

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko and @pegazee  https://secure.helpscout.net/conversation/385373455/13671/?folderId=1060551
