### ISSUE TITLE
Error on google structure data (The attribute image.width has an invalid value)

### ISSUE THREAD

**Issue by atifnoor1122** [ahmedkaludi/accelerated-mobile-pages#937]
Sir, How to solved this error in AMPtoWP "**The attribute image.width has an invalid value**"? (but valid AMP page on AMP test). This error check on google structure data test tool and its show on google web-master AMP error in 102 post. My website [PricePakistan.ml](https://www.PricePakistan.ml) most of images width 160px and hight 200px and i don't want to use high resolution images and also don't want to stretch images. As Google documentation says "**Images should be at least 696 pixels wide**". 

Screen-shoot : [https://ibb.co/kmtv9a](https://ibb.co/kmtv9a)

any way to change minimum value of images width and get valid amp structure data??? 

Please Help Me..... Thanks in Advance

**Comment by ahmedkaludi** [comment]
Yes, it automatically takes the featured image sizes. It's not an error but warning, and so you should upload larger featured images and it will automatically get the values for you.
