### ISSUE TITLE
Embed PowerPress podcasts into AMP

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#938]
Podcasts added through PowerPress is not showing with our plugin.

We have to test it properly and make sure that it gets fixed as soon as possible.

ref: https://wordpress.org/support/topic/how-to-embed-powerpress-podcasts-into-amp-site/
https://wordpress.org/support/topic/embedding-powerpress-into-amp/#post-9221844

**Comment by MohammedKaludi** [comment]
Podcasts are working on my localhost properly. Both audio players are working as expected http://take.ms/ARehA

**Comment by MohammedKaludi** [comment]
Podcasts Added through Shortcode in the content are working as expected.
