### ISSUE TITLE
Home page amp version doesn't work and comes blank

### ISSUE THREAD

**Issue by shivgre** [ahmedkaludi/accelerated-mobile-pages#939]
Hi, I have a homepage and I added amp version html in wp-editor of the page but google reports major content mismatch on /amp/ page i.e. homepage of my website due to /amp/ version being empty.

https://homepocket.com/amp/ is the page in question. Also I did notice the menu navs are non amp urls in amp versions and I am not sure if that is intended or a bug.

**Comment by ahmedkaludi** [comment]
so, is the content same then?

Is there a mismatch between the amp and non-amp?

**Comment by shivgre** [comment]
Our homepage is a separate page(set a wordpress page as homepage by settings->reading->home->pageName) which works fine in amp version but only homepage is not having any content displayed in AMP version.

So yes there is mismatch between amp and non-amp versions of same page(amp version is blank). This same page if accessed via page slug works fine in amp version. 

I am not sure if this issue has been fixed in updated version of the plugin.

**Comment by ahmedkaludi** [comment]
@shivgre I understand that this is an issue in the webmaster tools for you but there is nothing we can do in the plugin's code side. This ticket will be closed.
