### ISSUE TITLE
Limit number of posts has a problem.

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#940]
elements/related-posts.php

OLD:
$int_number_of_related_posts = round(abs(floatval($string_number_of_related_posts)));

NEW:
$int_number_of_related_posts = (int) $string_number_of_related_posts;

We need a confirmation  before we proceed.

https://wordpress.org/support/topic/cant-limit-of-related-posts/#post-9286585

**Comment by MohammedKaludi** [comment]
@Sejiro-Hiko need to do this all the designs

**Comment by MohammedKaludi** [comment]
Waiting for the user status reply

**Comment by ahmedkaludi** [comment]
Just message him again, Let's see what Brian has to say on this.

**Comment by ahmedkaludi** [comment]
Closed this ticket on the request of the reporter.
