### ISSUE TITLE
Instant Articles Error: "The HTML element does not contain any text"

### ISSUE THREAD

**Issue by nicholasgriffintn** [ahmedkaludi/accelerated-mobile-pages#949]
I'm getting the following error from Facebook about Instant Articles:

> The HTML element does not contain any text: Avoid including empty HTML elements

For code like this:

`<figure><img src="IMAGE-URL"><figcaption></figcaption></figure></header><!-- body --><p>BODY TEXT</p>`

I presume it's for the `<figcaption></figcaption>` which doesn't contain anything because there's no caption, probably shouldn't go in if that's the case.

**Comment by MARQAS** [comment]
Hi @nicholasgriffintn , I have tested the code and it's coming for me. 

Can you check again? and check it by giving the caption for featured image

**Comment by nicholasgriffintn** [comment]
I am still getting this error, it doesn't show when a caption is on the image, so i presume it's because of the caption code still coming up.

Here's a screen:

![image](https://user-images.githubusercontent.com/12116098/28042387-e6eefec2-65c4-11e7-8100-1d644e49b028.png)

**Comment by MohammedKaludi** [comment]
Hi @nicholasgriffintn , 

Is above check is working and is the issue fixed?

MK

**Comment by nicholasgriffintn** [comment]
@MohammedKaludi I will update my fork and let you know, sorry haven't been keeping up with the commits or notifications.
