### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#950]
Notice: Undefined index: ampforwp-custom-type in /var/www/web/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1053

ref: https://wordpress.org/support/topic/undefined-indexes-9/

**Comment by MARQAS** [comment]
Notice: Undefined index: ampforwp-amp-on-off in /home/xxx/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1097

Notice: Undefined index: ampforwp-redirection-on-off in /home/xxx/public_html/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 1182

ref: https://wordpress.org/support/topic/debug-0-9-49/

**Comment by MARQAS** [comment]
AMPFORWP_DM_SOCIAL_CHECK’ in C:\xampp\htdocs\my-site\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 356
https://wordpress.org/support/topic/php-error-warning-on-features-php/

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/too-many-errors-on-archive-and-post/

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/undefined-index-ampforwp-seo-custom-additional-meta/

**Comment by MARQAS** [comment]
#859

**Comment by MARQAS** [comment]
Resolved in #859

**Comment by ahmedkaludi** [comment]
fixed
