### ISSUE TITLE
Compatibility With Relevanssi plugin(Search Plugin)

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#953]
1. https://secure.helpscout.net/conversation/390617519/13902/?folderId=1060551
2. https://wordpress.org/support/topic/amp-search-support-for-site-using-relevanssi/

Plugin Ref: https://wordpress.org/plugins/relevanssi/

**Comment by ahmedkaludi** [comment]
It's not that easy to do. But since users are requesting it, we will keep this here and keep an eye on it.

**Comment by ahmedkaludi** [comment]
There is another problem which is related to that: https://wordpress.org/support/topic/search-is-noat-working/#post-9581885

We will have to implement this for sure.

**Comment by ahmedkaludi** [comment]
The bug with this plugin has been fixed #1503

**Comment by MohammedKaludi** [comment]
Proper integration of Relevanssi done in  #2307
