### ISSUE TITLE
Featured Slider "Tag" support

### ISSUE THREAD

**Issue by techmagus** [ahmedkaludi/accelerated-mobile-pages#954]
Hi, can support for Tags be added in "Featured Slider"? 5 themes I'm using (in 5 sites), are using Tags as basis for their built-in Featured Slider (non-amp) so I switched the relevant "name" from Category to Tag taxonomy. It would be redundant to have the same "name" for both taxonomies for the same purpose. "Featured" for Category (AMP) and "Featured" for tags (theme/non-amp).

Thank you!

**Comment by ahmedkaludi** [comment]
Hmm.... I am not sure if this is really necessary, is it? @techmagus

**Comment by ahmedkaludi** [comment]
There should be an option called "Recent Posts" which will be a default. 

See: http://take.ms/2gH6i

**Comment by ahmedkaludi** [comment]
**REVIEW:**

- [ ] Create a limit in the dropdown, what if a website have 1000 Categories and 10,000 tags? Won't that exhaust the memory and crash the options panel?

**Comment by ahmedkaludi** [comment]
Reviewed.

**Comment by Omair52** [comment]
pushed in 0.9.97.17
