### ISSUE TITLE
Featured Slider Category, not detecting categories

### ISSUE THREAD

**Issue by techmagus** [ahmedkaludi/accelerated-mobile-pages#955]
Hi, for some reason, the Featured Slider Category field is not displaying a selection of categories to choose from even though there are categories and posts associated with those categories.

This is affecting 5 sites, all of which are under a Multisite setup. Here are the details:
* AMP -- network activated
* AMPforWP -- network activated
* Both plugins, freshly installed direct from the Plugins area of WP.

Error message: No items of this type were found.

In a non-Multisite website, the categories are showing fine.

Thank you for the assistance!

PS
I haven't tried doing a "per site" activation and not "network", as I'm not sure if all the settings will be retained in all 5 sites, since I've finished that part except for the Featured Slider option.

![image](https://user-images.githubusercontent.com/1079205/27990959-ffa89c38-6499-11e7-8e21-4862c8ffecd3.png)

**Comment by ahmedkaludi** [comment]
@techmagus Do you have any categories in your site at all? If so then it should be working.

Can you give me more insight on this?

**Comment by ahmedkaludi** [comment]
@techmagus Please let us know more or we have no option but to close the ticket.

**Comment by techmagus** [comment]
@ahmedkaludi 

> Do you have any categories in your site at all? If so then it should be working.
Yes, of course :) I actually prefer "Tags" instead of "Categories" for Featured Sliders but regardless, it isn't detecting any categories (there are many).

> Can you give me more insight on this?
I actually have no idea what else to provide other than what I've already included in the original report.

It's only affecting sites part of a WP-multisite setup. In a single-site WP setup, it works fine.

Anything that you need specifically?

Here's the latest screenshot based on the current version: 0.9.65.2

![image](https://user-images.githubusercontent.com/1079205/32034433-20c28cde-ba45-11e7-91d0-380da49d8810.png)

PS
It does take time for me to reply/get back.

**Comment by mayanksharma9033** [comment]
Hi @techmagus,

Could you please contact on the team@magazine3.com, we will look into this and will get back to you.

**Comment by ahmedkaludi** [comment]
When we have the login info, we will check and understand the issue. 
If we find a bug, then we will make a ticket about it and work on it. Until then, this shall be closed.
