### ISSUE TITLE
FB Instant Article Feature Requests

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#956]
Hi, I am using ‘allfacebook.de Instant Articles’ plugin for FB instant articles currently. But, it would be awesome to remove this plugin and then enable Facebook Instant Articles option in your awesome plugin.

But currently, I don’t see any option to use ‘Ad placement’ from ‘Facebook Audience Network’ under these articles and also no option to track these using Google Analytics. Here is a snapshot of the options we have available with my current FB instant articles: https://s23.postimg.org/qjyxbc7gr/2017-07-09_23-14-33.jpg

When can we expect at least a few of these options under your plugin to remove my current plugin completely. Also, please keep it free. 🙂

REF: https://ampforwp.com/facebook-instant-articles-support-60th-update/#comment-14691

**Comment by niteshmanav** [comment]
Thank you for adding the request here. Looking forward to it.

Regards,

**Comment by nicholasgriffintn** [comment]
Advertising in Instant Articles is a huge feature, but the guys are working to add it now, here's that issue: #943.

As for integration with Google Analytics, that would be awesome, I'd have to agree with that.

**Comment by pegazee** [comment]
from user:-

Few basic things you must include in the next update to make it in direct competition with any standalone instant article plugins:

1. Option to choose the style. Currently, you plugin automatically chooses the default style template.
2. Option to add 'Analytics' especially Google analytics.
3. Native ad support if possible.

**Comment by nicholasgriffintn** [comment]
So I have created a pull request for analytics in Instant Articles pages.

You can find it here: #977

It works by adding a text box for the user to enter their analytics code into the admin page, including the script tag from Google Analytics and then framing that in the instant articles pages, which is what Facebook suggest you do.

**Comment by dan-eth** [comment]
Thanks for including my request @Pegazee
But I came up with a simpler request:

You already provided the option: Show Ad after 50% of the content. 
Why not add more options like it?
20%, 40, 33%, etc.

This should be easier.

And why limit inside post Ads placements to 3?
5 Ad slots sounds like a more reasonable number.

Keep up the good work.

**Comment by MARQAS** [comment]
@dan-eth Are you talking about the Advanced AMP Ads or instant articles ads?

**Comment by nicholasgriffintn** [comment]
@dan-eth If you are talking about instant articles, they are mostly automatic. You can configure them by a number of words, the default is a 250-word gap, which is currently the setting but you can change it to 350 or 500 words. We would just need to add a setting to change the ad density section of the meta tag with default, medium or low.

**Comment by nicholasgriffintn** [comment]
I just created a pull that would allow you to do what I was just talking about, check it out here: #1287

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn Thanks for PR, we will focus it on that ticket then.
