### ISSUE TITLE
AMP Optin issue

### ISSUE THREAD

**Issue by IvanPr** [ahmedkaludi/accelerated-mobile-pages#957]
AMP Optin has following issues:
The Title and Description can not be left empty and absent - if those are left empty and submitted, all the fields get re-populated again with default value and the following Notice is output:
Notice: Undefined offset: 0 in \wp-content\plugins\amp-optin\amp-optin.php on line 209

**Comment by IvanPr** [comment]
The .amp-optin-form-wrapper background can not be set transparent.
If I remove the color selection from .amp-optin-form-wrapper the CSS outputs empty background-color ;

**Comment by ahmedkaludi** [comment]
This is valid, But It needs to be moved to it's own private repo. I have moved. It will be solved in the next update of Opt-in.

I will close this now.
