### ISSUE TITLE
GTM Code Review by Francesco Tinti

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#958]
Francesco Tinti on Telegram group has sent us this code. We need to review him. I tested it in my personal blog, with design 2 and it works. 

I downloaded and installed the plugin from the website.
I configured via admin panel GTM.
I see traffic drop via Google Analytics, so I started investigating and realized that the code output was in the footer, not as GTM require part in <header> and part after <body> tag

[amp-gtm-plugin (1).php.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/1135662/amp-gtm-plugin.1.php.zip)

**Comment by oG14108149527Exl0Ftr7sY** [comment]
I am using this on a site, but still getting 403 error with GTM

**Comment by MARQAS** [comment]
Hi @oG14108149527Exl0Ftr7sY ,

Can you check now? I have made some changes in the code as per GTM guidelines.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
GTM - Google Tag Manager - with CloudFlare.com is still not working.

A.
Error message=
HTTP response code indicates tag failed to fire: Status 403

Please see:

https://www.gourmethjort.no/amp/

https://www.bjornespray.no/amp/



B.
GTM works correctly when using:
https://www.gourmethjort.no
https://www.bjornespray.no
with the "DuracellTomi's Google Tag Manager for WordPress" plugin



C.
I have contacted Thomas Geiger to get help with this issue.
Thomas is the developer of "DuracellTomi's Google Tag Manager for WordPress"
"DuracellTomi's Google Tag Manager for WordPress" plugin at:
https://wordpress.org/plugins/duracelltomi-google-tag-manager/

WordPress support ticket:
https://github.com/duracelltomi/gtm4wp/issues/38

GIThub.com issue:
https://wordpress.org/support/topic/setting-gtm-for-amp-pages/

Homepage:
https://duracelltomi.com

Contact form:
https://duracelltomi.com/contact








D.
The attached WordPress plugin could be modified to place the "DuracellTomi's Google Tag Manager for WordPress" plugin tag in the correct place in AMPforWP.com

To open the attached "amp-gtm-plugin-zip.txt" please change the filename to: "amp-gtm-plugin.zip"

[amp-gtm-plugin-zip.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/1244192/amp-gtm-plugin-zip.txt)

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Hello

Thank you very much for your help.

The issue is now solved.

Created a separate AMP container and tag.

Now using “AMP” as the container type instead of “Web”.

Everything works correctly.

Thanks

TBT

**Comment by ahmedkaludi** [comment]
@oG14108149527Exl0Ftr7sY Can you explain me what worked?

Please help me so that I can understand and improve the code in the AMP for WP plugin.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
When creating the Google Tag Manager container at:
https://tagmanager.google.com

Then you should create separate containers for the standard WordPress site and the the AMPforWP.com site.

When creating the AMPforWP.com container then you must choose container type= "AMP"
When creating the container for use with the PC version and standard WordPress theme then you should create a container type= "Web"

This means there will be different "container" / "container type" and different tags for the AMP and the non-AMP version of the site.

Mentioning this in the help section on the "Analytics" tab on /wp-admin/admin.php?page=amp_options&tab=2 might avoid frustration among future users.

**Comment by ahmedkaludi** [comment]
@oG14108149527Exl0Ftr7sY Thanks! We have made changes and also created a tutorial along with a link to with in the GTM section for people who can get the help easily.

Thanks for helping us out with one.

Regards,
Ahmed

**Comment by oG14108149527Exl0Ftr7sY** [comment]
It would be very nice if it was possible to use
"DuracellTomi's Google Tag Manager for WordPress" plugin at:
https://wordpress.org/plugins/duracelltomi-google-tag-manager/

toghether with AMPforWP.com

because this enables access to a wealth of information and statistics.

This information would be not accessible when using the native AMPforWP.com GTM integration.

**Comment by ahmedkaludi** [comment]
@oG14108149527Exl0Ftr7sY We are planning to allow users to get all those data in the AMP and an Advanced GTM integration in the AMP which is planned for the near future.

Regards,
Ahmed

**Comment by westville** [comment]
Hi there, 

New here in terms of posting, but a regular reader! 

I run a WordPress blog and I've used AMP right from the beginning. In fact, 50% of my traffic is on my AMP pages. Check the blog [here](https://bikebrewers.com/).

I've had the same issue with the misfire of the code (403) and creating a separate container did the trick. BUT; when using the Tag Assistant in Chrome (deleted cookies and cleared browser cache + Cloudflare & WordPress cache) I get 2 tags in the recording. 

For the normal page:

1. The Universal Analytics code (blue smiley)
2. The Tag Manager code (green smiley)

Which is OK I guess?

Form the AMP page:
1. The Universal Analytics code (yellow smiley)
2. The Tag Manager code (blue smiley)

With the error code:
Same web property ID is tracked twice.  

What seems to go wrong?

Thanks!

Westville
