### ISSUE TITLE
Few bugs (featured image not showing) and an error found at the attribute 'clear' for my posts

### ISSUE THREAD

**Issue by jboesh** [ahmedkaludi/Accelerated-Mobile-Pages#96]
Hi,

Thanks for creating this great plugin. Very easy to customise the AMP layout.
I have some bugs found:

– I have set a featured image for all my posts, but they are not appearing in the AMP page.
- Google Search console shows me this error ' The attribute 'clear' may not appear in tag 'br'.' on all my posts (I am using KK-rating plugin) -> See the full code below but it gives an error for this line: 

`<br clear="both">.`

Not important, but useful to know:
- Can you also tell me how to change the language? (like this text: View Non-AMP Version). Which php-file, or it is possible to add a option to change the language on the frontend? a request for the future.

Thanks in advance! Keep up the good work. This is only plugin at the moment, with active support.
Kind regards,
John.
## 

`<div class="kksr-stars kksr-star gray">&#13;<div class="kksr-fuel kksr-star yellow"></div>&#13; <a href="#1" data-wpel-link="internal"></a><a href="#2" data-wpel-link="internal"></a><a href="#3" data-wpel-link="internal"></a><a href="#4" data-wpel-link="internal"></a><a href="#5" data-wpel-link="internal"></a>&#13;</div>&#13; &#13;<div class="kksr-legend"><div><div>MY SUBJECT OF THE POST COMES HERE EXAMPLE FOR THE ERROR</div><div><span>5</span> (100%) <span>2</span> vote(s)<meta></meta><meta></meta></div></div></div>&#13; &#13;</div>&#13; &#13; <br clear="both"></br></div><div class="amp-wp-content post-pagination-meta"><li class="amp-wp-tax-category"> <span class="screen-reader-text">Categories:</span>`

**Comment by nicholasgriffintn** [comment]
Hey,

I'm not the author, but here are a few quick answers.

The plugin doesn't show featured images atm, this is something I also want to be implemented. If you are interested in adding it on your own site, you could copy the code from one of my recent pull requests: #82 .

As for the issue with the clear tag, AMP only allows certain tags and content to be loaded in AMP pages, so certain code will invalidate pages, it would need a similar fix to #77.
