### ISSUE TITLE
W3 Total Cache~ Include AMP Extension Option in our Plugin

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#965]
![extensions - w3 total cache fantastico theme wordpress 2017-07-13 00-35-03](https://user-images.githubusercontent.com/28556545/28159430-86c187dc-67da-11e7-83a3-b15edcb86350.jpg)

**Comment by MARQAS** [comment]
Tutorial would be better for this
