### ISSUE TITLE
Check and fix all errors in E_ALL errors mode

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#966]
Check and fix all errors in E_ALL errors mode

by the way: you should develop main plugin in E_ALL errors mode, you have many notices like:

Notice: Trying to get property of non-object in wp-content\plugins\amp\includes\class-amp-post-template.php on line 222
Notice: Trying to get property of non-object in wp-content\plugins\amp\includes\class-amp-post-template.php on line 148
Notice: Trying to get property of non-object in wp-content\plugins\amp\includes\class-amp-post-template.php on line 172
etc...

Notices may couse wrong behaviour of plugin in future or in specified conditions. Also it make harder to develop websites for develpers becouse they have to hide them.

REF: https://secure.helpscout.net/conversation/394784124/14098/?folderId=1060551

**Comment by MARQAS** [comment]
@ahmedkaludi reference?

**Comment by MARQAS** [comment]
It is same as #859 
 The remaining are archives and customizer warnings.

**Comment by MohammedKaludi** [comment]
:+1:
