### ISSUE TITLE
Images aligntment with caption

### ISSUE THREAD

**Issue by realraghavgupta** [ahmedkaludi/accelerated-mobile-pages#968]
The images are not properly aligned. All images get left aligned, and the caption is not picked up correctly.
For the feauted posts, the caption is not working. For the images inside the post, it is working, but alignment is not correct.
Example: https://eurasiantimes.com/review-nmp-mdi-gurgaon/amp {featured post, caption not correct}
https://eurasiantimes.com/movie-review-tubelight/amp/ {photo and caption coming correct, but alignment problems

**Comment by ahmedkaludi** [comment]
It was fixed in 0.9.59
