### ISSUE TITLE
Disable AMP linking at Wordpress Search Page 

### ISSUE THREAD

**Issue by IvanPr** [ahmedkaludi/accelerated-mobile-pages#969]
Is there a way to disable <link rel="amphtml" href="https://ampforwp.com/demo/three/?amp=1&#038;s=result"/>

On pages like:
https://ampforwp.com/demo/three?s=result

Thank you.

**Comment by MARQAS** [comment]
@IvanPr Thanks for your suggestion.
Right now, it is not available, but we will add it in our next updates.

**Comment by ahmedkaludi** [comment]
@IvanPr So you want to disable the AMP on the search results?

**Comment by IvanPr** [comment]
Well, why making the search page AMPabple, if the AMPed version does not work?
Try https://ampforwp.com/demo/three?s=result
amd see the AMP link to https://ampforwp.com/demo/three/?amp=1&s=result/

**Comment by MohammedKaludi** [comment]
@IvanPr Thank you for reporting it, we have fixed it and after this update, search pages will work properly on pages.

Thank you once again.
Mohammed Kaludi

**Comment by MohammedKaludi** [comment]
Working on both sides as expected.
