### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by aashishpahwa** [ahmedkaludi/accelerated-mobile-pages#97]
Images used to show when the plugin was updated
But the don't show anymore.
I haven't made any change in the plugins. Please Help

**Comment by ahmedkaludi** [comment]
@aashishpahwa Are you still having this issue?

**Comment by cachipech** [comment]
I have the same problem. In mydomain.com/amp see all the options (social networks, comments, main image of the post) but cannot see the internal images of the post. What can I do? I have assets of the two plugins (AMP and AMP beta). Thank you.

**Comment by cachipech** [comment]
Is there any css code to be able to see the images in the posts? I have configured the plugin so that the images have a size of 804x350, but the images do not appear, and the space comes out blank. I am using Best theme of MyThemeShop.

**Comment by khaledMohammed000** [comment]
@aashishpahwa @cachipech Guys can you please update on this ?

**Comment by cachipech** [comment]
Hi!

On my site, I can see at the end of the post the featured image, but not display the internal images of the article. How can I send you the url of my site? What can be inserted using the css attribute amp-img?

Thanks!

**Comment by aashishpahwa** [comment]
Hi,
The issue is solved for me.
Thanks.

**Comment by cachipech** [comment]
I am still having the same problem. How do I fix?

**Comment by MohammedKaludi** [comment]
@cachipech can you please explain a bit more about your issue and also the url of the site will also be very helpful.

**Comment by ahmedkaludi** [comment]
The plugin is much more stable now. This should not be able a problem.
