### ISSUE TITLE
Undefined index: ampforwp-custom-type

### ISSUE THREAD

**Issue by IvanPr** [ahmedkaludi/accelerated-mobile-pages#970]
I still get the following error with the latest v. 0.9.55 update:

> Notice: Undefined index: ampforwp-custom-type in ...\wp-content\plugins\accelerated-mobile-pages\templates\features.php on line 1050

You should have the following code instead at line ~1050:
```
    if ( array_key_exists('ampforwp-custom-type', $redux_builder_amp) && $redux_builder_amp['ampforwp-custom-type'] ) {
      $post_types = array_merge($post_types, $redux_builder_amp['ampforwp-custom-type']);
    }
```

**Comment by ahmedkaludi** [comment]
We will resolve this in https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1219
