### ISSUE TITLE
Page builder text and button module issues

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#972]
text in text module is not center aligned.

Button: There is no button after the update, just plain text.

ref: https://wordpress.org/support/topic/button-link-not-working-2/
https://thidiweb.com/amp/

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/amp-button-module/

**Comment by MohammedKaludi** [comment]
Sanitization ticket #868 
But still, not 100%, need to create a universal function that can accept any data and sanitize it
