### ISSUE TITLE
Author image and Compatibility with WP User Avatar

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#975]
Make the author image conditional, if gravatar is present then only show the image.

ref: https://wordpress.org/support/topic/mixed-content-15/

**Comment by MARQAS** [comment]
We can change it from Settings->Discussion.

**Comment by MARQAS** [comment]
I guess he is using some plugin to add the custom avatars

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/missing-url-for-attribute-src-in-tag-amp-img-4/

**Comment by ahmedkaludi** [comment]
Reviewed
