### ISSUE TITLE
Adding analytics to Instant Articles #977

### ISSUE THREAD

**Issue by nicholasgriffintn** [ahmedkaludi/accelerated-mobile-pages#978]
So I created a pull for adding analytics code to Instant Articles pages.

You can find it here: #977

I've tested it on my own site and it seems to work great so far.

**Comment by MohammedKaludi** [comment]
@nicholasgriffintn Thank you very much for the pull request. Will merge it when 0.9.56 is merged with master.

One request is, please when you send your future Pull requests, please send it to the most recent branch, not to master. So I can review it and merge in the appropriate version and then merge that version to master.

Thank you very much for your contributions.
Mohammed kaludi
