### ISSUE TITLE
$authordata global variable not set for amp posts

### ISSUE THREAD

**Issue by jeiseman** [ahmedkaludi/accelerated-mobile-pages#979]
I have a shortcode in my post and the shortcode calls the function get_the_author_meta but this function fails on the amp page for the post because the global variable $authordata is not set (and the function depends on this global  variable). To workaround the problem I added the following to my functions.php:

```
function musical_preamp( $post_id )
{
    global $authordata;
    if (!isset($authordata)) {
        $post = get_post($post_id);
        $authordata = get_userdata( $post->post_author );
    }
}
add_action('pre_amp_render_post', 'musical_preamp');
```

**Comment by ahmedkaludi** [comment]
@jeiseman Can you tell me why is this?

**Comment by MohammedKaludi** [comment]
@jeiseman I have tested and I can access the global $authordata;
Here you can see in the screenshot http://take.ms/TwJBS 

`
add_action('pre_amp_render_post','authordata_dump');
function authordata_dump() {
	global $authordata;
	var_dump( $authordata );
}`

Closing the ticket, for now, feel free to reopen if you have any questions.
