### ISSUE TITLE
Perfect SEO url + Yoast SEO Compatibility

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#982]
![perfect seo url](https://user-images.githubusercontent.com/28556545/28518715-817839ce-7086-11e7-8eb6-34b0c0ff7b77.png)

This option is generating/adding one more rel canonical link in the AMP and creating validation errors.

filter which is adding the link:
add_filter( 'wpseo_canonical', array( $this, 'canonical' ), 10, 1 );

Solution code to be added in features.php : 
ampforwp_remove_filters_for_class( 'wpseo_canonical', 'PSU', 'canonical', 10 );

**Comment by ahmedkaludi** [comment]
@Sejiro-Hiko 

If this was fixed then why do we have this without milestone.

**Comment by MARQAS** [comment]
It's already there in our code. 
Moving this to the Review board
