### ISSUE TITLE
Genesis Compatibility 

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#984]
ref: https://wordpress.org/support/topic/meta-data-defined-in-genesis-framework/

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/comments-link-homeapge/

**Comment by MARQAS** [comment]
https://wordpress.org/support/topic/blog-template-for-archives-doesnt-show-posts-in-amp/

**Comment by ahmedkaludi** [comment]
@MARQAS what's the status of this one?

**Comment by Frenchomatic** [comment]
I don't see any specific genesis issues anymore.

**Comment by mayanksharma9033** [comment]
We don't have any specific feature right now soi am moving this ticket to review and Q/A, if we will have to need this feature in future then we will add this.

**Comment by MohammedKaludi** [comment]
@Frenchomatic thank you for letting us know. 
Thank you for all your feedback and contribution in improving this plugin.

Closing the ticket.
Mohammed Kaludi
