### ISSUE TITLE
The tag 'amp-video extension .js script' is missing or incorrect, but required by 'amp-video'. This will soon be an error.

### ISSUE THREAD

**Issue by riyaz-ahmed** [ahmedkaludi/accelerated-mobile-pages#985]
I get below error while I submit my post  in google webmaster which has video

"The tag 'amp-video extension .js script' is missing or incorrect, but required by 'amp-video'. This will soon be an error."

**Comment by ahmedkaludi** [comment]
@riyaz-prosper Could you please share the website URL? So we can understand better?

**Comment by ahmedkaludi** [comment]
no data at the moment. Long time. Closing the ticket.
