### ISSUE TITLE
Help! What is this ->"The implied layout 'CONTAINER' is not supported by tag 'amp-img'."

### ISSUE THREAD

**Issue by Ireviewuread** [ahmedkaludi/accelerated-mobile-pages#987]
So over 40 of my posts have this problems. I'm not good at coding and now I don't know what to do! Can you please help me step by step if possible. I just want to solve this! BTW my site is hosted on tumblr. 
Oh and the top problem it said " Invalid layout property found in AMP tag (Critical)" then the bottom problem it said "The implied layout 'CONTAINER' is not supported by tag 'amp-img'." I think the images are missing on the amp side but it's ok on desktop. How do I make them appear again? What code do I need to put in? Here are some URLs which are affected: 

AMP - http://ireviewuread.com/post/61001383322/the-face-shop-flebote-white-crystal-effect/amp
Desktop - http://ireviewuread.com/post/61001383322/the-face-shop-flebote-white-crystal-effect

AMP - http://ireviewuread.com/post/54692459989/listerine-green-tea-sample-and-review/amp
Desktop - http://ireviewuread.com/post/54692459989/listerine-green-tea-sample-and-review

AMP - http://ireviewuread.com/post/62950306718/daiso-charcoal-mask-natural-pack-review/amp
Desektop - http://ireviewuread.com/post/62950306718/daiso-charcoal-mask-natural-pack-review

**Comment by MARQAS** [comment]
Hi @Ireviewuread ,

I am sorry to say that you have created the ticket at a different place. This is a WordPress plugin.

But the reason why you are getting that error is Images, Images in AMP don't have width and height. Try adding width and height.

I checked other posts of yours but there are no issues on them, so there are 2 concerns.
1: Some images are directly getting converted into AMP and some are not (In that case contact Tumblr and ask them about it).
2: Some images don't have width and height attributes which are mandatory for AMP validation. Try adding them, it will resolve the issue.

**Comment by MARQAS** [comment]
Closing this ticket as it is not related to our plugin
