### ISSUE TITLE
amp-video is missing

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#991]
pages with video get this error:

The tag ‘amp-video extension .js script’ is missing or incorrect, but required by ‘amp-video’.

ref: https://wordpress.org/support/topic/missing-amp-video-extension/

**Comment by ahmedkaludi** [comment]
How can we re-create this issue?

My suggestion, let's try to add a video mp4 (by uploading) and then check.

**Comment by ahmedkaludi** [comment]
tested and working.
