### ISSUE TITLE
ACF Extension doesn't sanitize WYSIWYG Fields

### ISSUE THREAD

**Issue by daxhansen** [ahmedkaludi/accelerated-mobile-pages#993]
ACF Extension doesn't seem to be sanitizing flexible content WYSIWYG field types. Is this going to be supported?

**Comment by MARQAS** [comment]
Hi @daxhansen 
We are working on major update of ACF which is going to resolve all these problems

**Comment by daxhansen** [comment]
Any updates on this issue?

**Comment by ahmedkaludi** [comment]
With this, it will work fine: https://ampforwp.com/introducing-acf-amp-2-0-built-scratch-ready-future/
