### ISSUE TITLE
Published Date for posts is "48 years ago" in design 3 

### ISSUE THREAD

**Issue by Sejiro-Hiko** [ahmedkaludi/accelerated-mobile-pages#996]
The publish date is showing "48 years ago" in design 3.

The code is correct and working perfectly fine for almost everyone but those who faced the issue have one thing in common that the site is multi lingual. and in the structured data for the published date is showing 1970/01/01 (48 years ago) irrespective of design.

Ref: bartabangla.com/amp 
       and
       famososnaweb.com/

**Comment by ahmedkaludi** [comment]
@Sejiro-Hiko we still don't know what's causing it and we see it very rarely. How are we suppose to fix it? I think we should be on a lookout to find more details on it.
