### ISSUE TITLE
Custom Frontpage: the implied layout ‘container’ is not supported by tag ‘amp-img’

### ISSUE THREAD

**Issue by MARQAS** [ahmedkaludi/accelerated-mobile-pages#998]
Custom frontpage images are not getting sanitized I guess. It is happening when images don't have height and width on custom frontpage.

ref: https://wordpress.org/support/topic/the-implied-layout-container-is-not-supported-by-tag-amp-img/

**Comment by ahmedkaludi** [comment]
This ticket is pointless.  The original issue that user is facing is because Divi is not adding the images properly, these issues with page builders are quite common, but that's just for another day. For now, this ticket is not actionable.
