### ISSUE TITLE
non-amp category pages should redirect to non-amp pages if turned off from HIde AMP

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/accelerated-mobile-pages#999]
non-amp category pages should redirect to non-amp pages if turned off from HIde AMP.

Currently redirecting to amp pages and we are only removing the amphtml so google will not be able to detect the amp page on it.

#872

**Comment by ahmedkaludi** [comment]
So, we have a ticket with commit but not added to a milestone, but perhaps it was not reviewed either? Let's find out.

**Comment by MARQAS** [comment]
It has been resolved, but I guess it is not tested properly or may forget to close this ticket, adding it in review boards

**Comment by MARQAS** [comment]
rels have been removed but redirection has to be done. 

If AMP is disabled /amp will redirect to non-AMP.

**Comment by ahmedkaludi** [comment]
The commit attached to this ticket was for "If the mobile redirection is ON and the category is excluded to display the AMP then it should redirect properly", not for the redirection which was mentioned in the ticket. But it has been referenced into #1052  and we will be working on fixing it.

So, we will be closing it for now. More development regarding this ticket at #1052
